import { I, gap, mc, sb } from '../shared.mjs'

const AUX = 'haben / sein'
const DILARA = 'Dilara schreibt: „Gestern habe ich meine Cousine in Bremen besucht. Leider habe ich den Zug verpasst, weil die Straßenbahn Verspätung hatte. Ich bin eine Stunde später angekommen.“'
const OLGA = 'Olga schreibt: „Am Samstag habe ich die Familie von meinem Mann kennengelernt. Zuerst war ich sehr nervös. Aber seine Eltern waren sehr nett und sein Bruder hat mir viel von der Familie erzählt. Schließlich haben wir alle zusammen gegessen.“'

/** A2.1 · Pfad 1 · Ankommen – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Neffe', I.choose, 'Der Sohn von meiner Schwester ist mein …', ['Neffe', 'Cousin', 'Enkel'],
      ['My sister’s son is my …', 'Сын моей сестры – это мой …', 'Син моєї сестри – це мій …', 'Kız kardeşimin oğlu benim …']),
    mc('K2', 'arbeitslos', I.choose, 'Herr Petrov sucht seit drei Monaten eine Stelle. Er hat im Moment keine Arbeit. Er ist …', ['arbeitslos', 'berufstätig', 'in Rente'],
      ['Mr Petrov has been looking for a job for three months. He has no work at the moment. He is …', 'Господин Petrov уже три месяца ищет работу. Сейчас у него нет работы. Он …', 'Пан Petrov уже три місяці шукає роботу. Зараз у нього немає роботи. Він …', 'Petrov Bey üç aydır iş arıyor. Şu anda işi yok. O …']),
    mc('K1', 'reagieren', I.react, '„Stell dir vor, mein Handy ist ins Wasser gefallen!“', ['So ein Mist! Funktioniert es noch?', 'Das gefällt mir.', 'Zum Glück! Herzlichen Glückwunsch!'],
      ['“Just imagine, my mobile fell into the water!”', '«Представь себе, мой телефон упал в воду!»', '«Уяви собі, мій телефон упав у воду!»', '“Düşünsene, telefonum suya düştü!”']),
    mc('K3', 'ihm', I.choose, 'Jonas muss jeden Samstag arbeiten. Wie findet er das?', ['Das gefällt ihm nicht.', 'Das gefällt ihr nicht.', 'Das gefällt ihnen nicht.'],
      ['Jonas has to work every Saturday. What does he think of that?', 'Jonas должен работать каждую субботу. Как он к этому относится?', 'Jonas мусить працювати щосуботи. Як він до цього ставиться?', 'Jonas her cumartesi çalışmak zorunda. Bunu nasıl buluyor?']),
    mc('K4', 'dann', I.choose, 'Zuerst habe ich gefrühstückt. … bin ich zur Arbeit gefahren.', ['Dann', 'Zuerst', 'Weil'],
      ['First I had breakfast. Then I went to work.', 'Сначала я позавтракал. Потом поехал на работу.', 'Спочатку я поснідав. Потім поїхав на роботу.', 'Önce kahvaltı yaptım. Sonra işe gittim.']),
    mc('Z1', 'Grund', I.read, `${DILARA} Warum hat Dilara den Zug verpasst?`, ['Die Straßenbahn war nicht pünktlich.', 'Sie hat verschlafen.', 'Ihre Cousine hat sie nicht abgeholt.'],
      ['Why did Dilara miss the train?', 'Почему Dilara опоздала на поезд?', 'Чому Dilara запізнилася на потяг?', 'Dilara treni neden kaçırdı?']),
    mc('G1', 'Verb am Ende', I.sentence, 'Tim kommt heute nicht zum Fußball.', ['Er kommt nicht, weil er Fieber hat.', 'Er kommt nicht, weil er hat Fieber.', 'Er kommt nicht, weil hat er Fieber.'],
      ['Tim is not coming to football today.', 'Tim сегодня не придёт на футбол.', 'Tim сьогодні не прийде на футбол.', 'Tim bugün futbola gelmiyor.']),
    gap('G1', 'mit Modalverb', I.modal, 'Ich kann nicht kommen, weil ich meine Tante vom Bahnhof abholen ', '.', 'muss', ['müssen', 'musst'],
      ['I cannot come because I have to pick up my aunt from the station.', 'Я не могу прийти, потому что мне нужно встретить тётю на вокзале.', 'Я не можу прийти, тому що мені треба зустріти тітку на вокзалі.', 'Gelemiyorum, çünkü teyzemi istasyondan almam gerekiyor.'], 'müssen'),
    gap('G2', 'aufstehen', I.participle, 'Wann bist du heute ', '? – Um halb sieben.', 'aufgestanden', ['aufgesteht', 'geaufstanden'],
      ['When did you get up today? – At half past six.', 'Когда ты сегодня встал? – В половине седьмого.', 'Коли ти сьогодні встав? – О пів на сьому.', 'Bugün ne zaman kalktın? – Altı buçukta.'], 'aufstehen'),
    gap('G3', 'telefonieren', I.participle, 'Wir haben eine Stunde ', '. Jetzt ist mein Akku leer.', 'telefoniert', ['getelefoniert', 'telefonieren'],
      ['We talked on the phone for an hour. Now my battery is empty.', 'Мы час говорили по телефону. Теперь у меня разряжен аккумулятор.', 'Ми годину говорили телефоном. Тепер у мене розряджений акумулятор.', 'Bir saat telefonda konuştuk. Şimdi şarjım bitti.'], 'telefonieren'),
    gap('G4', 'verstehen', I.participle, 'Hast du die Hausaufgabe ', '? – Nein, sie ist zu schwer.', 'verstanden', ['geverstanden', 'verstehen'],
      ['Did you understand the homework? – No, it is too difficult.', 'Ты понял домашнее задание? – Нет, оно слишком трудное.', 'Ти зрозумів домашнє завдання? – Ні, воно надто складне.', 'Ödevi anladın mı? – Hayır, çok zor.'], 'verstehen'),
    gap('G5', 'von + Dativ', I.possessive, 'Das ist die Katze von ', ' Nachbarin.', 'meiner', ['meine', 'meinem'],
      ['This is my neighbour’s cat.', 'Это кошка моей соседки.', 'Це кішка моєї сусідки.', 'Bu komşumun kedisi.'], 'mein', { h: 'dative' }),
    sb('G2', 'anrufen', I.order, 'Ich / habe / dich / gestern / angerufen.',
      ['I called you yesterday.', 'Я звонил тебе вчера.', 'Я телефонував тобі вчора.', 'Seni dün aradım.'],
      { alt: ['Gestern habe ich dich angerufen.'] }),
  ],
  size: 13,
  test: [
    mc('W1', 'Schwägerin', I.choose, 'Die Frau von meinem Bruder ist meine …', ['Schwägerin', 'Nichte', 'Tante'],
      ['My brother’s wife is my …', 'Жена моего брата – это моя …', 'Дружина мого брата – це моя …', 'Erkek kardeşimin karısı benim …']),
    mc('W1', 'Enkel', I.choose, 'Meine Eltern haben einen Enkel. Wer ist das?', ['Mein Sohn.', 'Mein Onkel.', 'Mein Schwager.'],
      ['My parents have a grandson. Who is that?', 'У моих родителей есть внук. Кто это?', 'У моїх батьків є онук. Хто це?', 'Annemle babamın bir erkek torunu var. O kim?']),
    mc('G1', 'Verb am Ende', I.sentence, 'Frau Nowak fährt heute mit dem Bus.', ['Sie fährt mit dem Bus, weil ihr Auto in der Werkstatt ist.', 'Sie fährt mit dem Bus, weil ihr Auto ist in der Werkstatt.', 'Sie fährt mit dem Bus, weil ist ihr Auto in der Werkstatt.'],
      ['Ms Nowak is going by bus today.', 'Госпожа Nowak сегодня едет на автобусе.', 'Пані Nowak сьогодні їде автобусом.', 'Nowak Hanım bugün otobüsle gidiyor.']),
    mc('G1', 'im Perfekt', I.choose, 'Warum hast du Hunger? – Weil ich heute noch nichts …', ['gegessen habe.', 'habe gegessen.', 'essen habe.'],
      ['Why are you hungry? – Because I have not eaten anything yet today.', 'Почему ты голоден? – Потому что я сегодня ещё ничего не ел.', 'Чому ти голодний? – Тому що я сьогодні ще нічого не їв.', 'Neden açsın? – Çünkü bugün daha hiçbir şey yemedim.'], { c: 'p1_weil2' }),
    mc('G2', 'anfangen', I.choose, 'Der Kurs hat um neun Uhr …', ['angefangen.', 'geanfangen.', 'anfangt.'],
      ['The course started at nine o’clock.', 'Курс начался в девять часов.', 'Курс почався о дев’ятій годині.', 'Kurs saat dokuzda başladı.']),
    mc('G3', 'reparieren', I.choose, 'Mein Bruder hat sein Fahrrad selbst …', ['repariert.', 'gerepariert.', 'reparieren.'],
      ['My brother repaired his bike himself.', 'Мой брат сам починил свой велосипед.', 'Мій брат сам полагодив свій велосипед.', 'Erkek kardeşim bisikletini kendisi tamir etti.']),
    mc('G4', 'bezahlen', I.choose, 'Ich habe für das Ticket 20 Euro …', ['bezahlt.', 'gebezahlt.', 'bezahlen.'],
      ['I paid 20 euros for the ticket.', 'Я заплатил за билет 20 евро.', 'Я заплатив за квиток 20 євро.', 'Bilet için 20 avro ödedim.']),
    mc('G5', 'Name + s', I.choose, 'Das ist der Hund von Frau Kaya. = Das ist …', ['Frau Kayas Hund', 'Frau Kaya Hund', 'Hunds Frau Kaya'],
      ['This is the dog of Ms Kaya. = This is …', 'Это собака госпожи Kaya. = Это …', 'Це собака пані Kaya. = Це …', 'Bu Kaya Hanım’ın köpeği. = Bu …']),
    mc('K1', 'reagieren', I.react, '„Ich habe meinen Zug verpasst und bin zwei Stunden am Bahnhof geblieben.“', ['Oje, so ein Pech!', 'Wie schön für dich!', 'Guten Appetit!'],
      ['“I missed my train and stayed at the station for two hours.”', '«Я опоздал на поезд и два часа просидел на вокзале».', '«Я запізнився на потяг і дві години просидів на вокзалі».', '“Trenimi kaçırdım ve iki saat istasyonda kaldım.”']),
    mc('K1', 'Zum Glück', I.choose, 'Ich habe mein Handy im Café vergessen. … hat die Kellnerin es gefunden.', ['Zum Glück', 'So ein Pech', 'Wie peinlich'],
      ['I left my mobile in the café. Luckily the waitress found it.', 'Я забыл телефон в кафе. К счастью, официантка его нашла.', 'Я забув телефон у кафе. На щастя, офіціантка його знайшла.', 'Telefonumu kafede unuttum. Neyse ki garson onu buldu.']),
    mc('K2', 'getrennt', I.choose, 'Lena und Tom sind kein Paar mehr, aber sie sind noch nicht geschieden. Sie leben …', ['getrennt', 'zusammen', 'in einer Großfamilie'],
      ['Lena and Tom are no longer a couple, but they are not divorced yet. They live …', 'Lena и Tom больше не пара, но ещё не развелись. Они живут …', 'Lena і Tom більше не пара, але ще не розлучилися. Вони живуть …', 'Lena ile Tom artık çift değil, ama henüz boşanmadılar. Onlar … yaşıyor.']),
    mc('K3', 'ihr', I.choose, 'Meine Schwester hat eine neue Stelle. Die Arbeit macht ihr Spaß. Wie findet sie die Stelle?', ['Die Stelle gefällt ihr.', 'Die Stelle gefällt ihm.', 'Die Stelle findet sie nicht so toll.'],
      ['My sister has a new job. She enjoys the work. What does she think of the job?', 'У моей сестры новая работа. Работа ей в радость. Как ей эта работа?', 'У моєї сестри нова робота. Робота їй до душі. Як їй ця робота?', 'Kız kardeşimin yeni bir işi var. İşini severek yapıyor. İşi nasıl buluyor?']),
    mc('K4', 'zuerst', I.choose, '… habe ich lange gewartet. Dann ist der Bus endlich gekommen.', ['Zuerst', 'Schließlich', 'Danach'],
      ['First I waited for a long time. Then the bus finally came.', 'Сначала я долго ждал. Потом автобус наконец пришёл.', 'Спочатку я довго чекав. Потім автобус нарешті приїхав.', 'Önce uzun süre bekledim. Sonra otobüs nihayet geldi.']),
    mc('Z1', 'Gefühl', I.read, `${OLGA} Wie war Olga am Anfang?`, ['Nervös.', 'Müde.', 'Sehr glücklich.'],
      ['How did Olga feel at the beginning?', 'Как Olga чувствовала себя вначале?', 'Як Olga почувалася спочатку?', 'Olga başta nasıldı?']),
    mc('Z1', 'Ende', I.read, `${OLGA} Was haben alle am Ende gemacht?`, ['Sie haben zusammen gegessen.', 'Sie haben ferngesehen.', 'Sie sind nach Hause gefahren.'],
      ['What did they all do at the end?', 'Что все сделали в конце?', 'Що всі зробили в кінці?', 'Sonunda hepsi ne yaptı?']),
    gap('G1', 'weil', I.conjunction, 'Ich lerne jeden Tag, ', ' ich die Prüfung bestehen möchte.', 'weil', ['aber', 'dann'],
      ['I study every day because I want to pass the exam.', 'Я занимаюсь каждый день, потому что хочу сдать экзамен.', 'Я вчуся щодня, тому що хочу скласти іспит.', 'Her gün çalışıyorum, çünkü sınavı geçmek istiyorum.'], 'weil / aber / dann'),
    gap('G1', 'Verb am Ende', I.verb, 'Emre geht zum Arzt, weil er Kopfschmerzen ', '.', 'hat', ['haben', 'ist'],
      ['Emre is going to the doctor because he has a headache.', 'Emre идёт к врачу, потому что у него болит голова.', 'Emre йде до лікаря, тому що в нього болить голова.', 'Emre doktora gidiyor, çünkü başı ağrıyor.'], 'haben'),
    gap('G1', 'im Perfekt', I.auxiliary, 'Mia ist glücklich, weil sie eine Wohnung gefunden ', '.', 'hat', ['ist', 'haben'],
      ['Mia is happy because she has found a flat.', 'Mia счастлива, потому что нашла квартиру.', 'Mia щаслива, тому що знайшла квартиру.', 'Mia mutlu, çünkü bir daire buldu.'], AUX, { c: 'p1_weil2', h: 'aux' }),
    gap('G2', 'abholen', I.participle, 'Ich habe meine Freundin vom Flughafen ', '.', 'abgeholt', ['geabholt', 'abholt'],
      ['I picked my friend up from the airport.', 'Я встретил подругу в аэропорту.', 'Я зустрів подругу в аеропорту.', 'Arkadaşımı havalimanından aldım.'], 'abholen'),
    gap('G2', 'einschlafen', I.participle, 'Gestern Abend bin ich auf dem Sofa ', '.', 'eingeschlafen', ['eingeschlaft', 'geeinschlafen'],
      ['Last night I fell asleep on the sofa.', 'Вчера вечером я заснул на диване.', 'Учора ввечері я заснув на дивані.', 'Dün akşam kanepede uyuyakaldım.'], 'einschlafen'),
    gap('G3', 'passieren', I.participle, 'Was ist ', '? Warum weinst du?', 'passiert', ['gepassiert', 'passieren'],
      ['What happened? Why are you crying?', 'Что случилось? Почему ты плачешь?', 'Що сталося? Чому ти плачеш?', 'Ne oldu? Neden ağlıyorsun?'], 'passieren'),
    gap('G4', 'vergessen', I.participle, 'Ich habe meine Jacke im Bus ', '. Jetzt ist mir kalt.', 'vergessen', ['gevergessen', 'vergisst'],
      ['I left my jacket on the bus. Now I am cold.', 'Я забыл куртку в автобусе. Теперь мне холодно.', 'Я забув куртку в автобусі. Тепер мені холодно.', 'Ceketimi otobüste unuttum. Şimdi üşüyorum.'],
      ['forget', 'забывать', 'забувати', 'unutmak']),
    gap('G4', 'erleben', I.participle, 'So etwas habe ich noch nie ', '!', 'erlebt', ['geerlebt', 'erleben'],
      ['I have never experienced anything like it!', 'Такого со мной ещё никогда не было!', 'Такого зі мною ще ніколи не було!', 'Böyle bir şeyi daha önce hiç yaşamadım!'], 'erleben'),
    gap('G5', 'von + Dativ', I.possessive, 'Das ist das Auto von ', ' Eltern.', 'meinen', ['meine', 'meiner'],
      ['This is my parents’ car.', 'Это машина моих родителей.', 'Це машина моїх батьків.', 'Bu annemle babamın arabası.'], 'mein', { h: 'dative' }),
    gap('G5', 'Name + s', I.form, 'Der Mann von Marta heißt Jan. ', ' Mann heißt Jan.', 'Martas', ['Marta', 'Martan'],
      ['Marta’s husband is called Jan.', 'Мужа Marta зовут Jan.', 'Чоловіка Marta звати Jan.', 'Marta’nın kocasının adı Jan.'], 'Marta'),
    gap('K2', 'allein', I.word, 'Mein Bruder hat keine Partnerin und keine Kinder. Er lebt ', '.', 'allein', ['zusammen', 'verheiratet'],
      ['My brother has no partner and no children. He lives alone.', 'У моего брата нет ни партнёрши, ни детей. Он живёт один.', 'У мого брата немає ні партнерки, ні дітей. Він живе сам.', 'Erkek kardeşimin ne partneri ne de çocuğu var. Yalnız yaşıyor.'],
      ['alone', 'один', 'сам', 'yalnız']),
    gap('K3', 'ihnen', I.pronoun, 'Meine Eltern haben einen Garten. Der Garten gefällt ', ' sehr.', 'ihnen', ['ihm', 'sie'],
      ['My parents have a garden. They like the garden very much.', 'У моих родителей есть сад. Сад им очень нравится.', 'У моїх батьків є сад. Сад їм дуже подобається.', 'Annemle babamın bir bahçesi var. Bahçe çok hoşlarına gidiyor.'], 'sie (Plural)'),
    gap('K4', 'schließlich', I.word, 'Zuerst haben wir eingekauft, dann gekocht und ', ' haben wir gegessen.', 'schließlich', ['zuerst', 'weil'],
      ['First we did the shopping, then we cooked, and finally we ate.', 'Сначала мы сходили за покупками, потом готовили и наконец поели.', 'Спочатку ми сходили по покупки, потім готували й нарешті поїли.', 'Önce alışveriş yaptık, sonra yemek pişirdik ve sonunda yedik.'],
      ['finally', 'наконец', 'нарешті', 'sonunda']),
    sb('G1', 'weil-Satz', I.order, 'Er / bleibt / zu Hause, / weil / er / Fieber / hat.',
      ['He is staying at home because he has a fever.', 'Он остаётся дома, потому что у него температура.', 'Він залишається вдома, тому що в нього температура.', 'Evde kalıyor, çünkü ateşi var.'],
      { alt: ['Weil er Fieber hat, bleibt er zu Hause.'] }),
    sb('G2', 'aufräumen', I.order, 'Wir / haben / am Samstag / die Wohnung / aufgeräumt.',
      ['We tidied up the flat on Saturday.', 'В субботу мы убрали квартиру.', 'У суботу ми прибрали квартиру.', 'Cumartesi günü evi topladık.'],
      { alt: ['Am Samstag haben wir die Wohnung aufgeräumt.', 'Die Wohnung haben wir am Samstag aufgeräumt.'] }),
    sb('K1', 'nachfragen', I.question, 'Und / was / hast / du / dann / gemacht?',
      ['And what did you do then?', 'И что ты сделал потом?', 'І що ти зробив потім?', 'Peki sonra ne yaptın?']),
  ],
}

export default check
