import { I, gap, mc, sb } from '../shared.mjs'

const REINIGUNG = 'Aushang: „Am Freitag reinigt eine Firma das Treppenhaus. Bitte stellen Sie keine Schuhe und keine Kinderwagen vor die Wohnungstür.“'
const RAUCHMELDER = 'Aushang: „Liebe Mieterinnen und Mieter, am Dienstag, 4. Mai, kontrolliert ein Techniker die Rauchmelder in allen Wohnungen. Bitte seien Sie zwischen 9 und 12 Uhr zu Hause oder geben Sie einem Nachbarn Ihren Schlüssel.“'

/** A2.1 · Pfad 2 · Zu Hause – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Glühbirne', I.choose, 'Du hast kein Licht in der Küche. Was ist kaputt?', ['die Glühbirne', 'der Briefkasten', 'die Mülltonne'],
      ['You have no light in the kitchen. What is broken?', 'У вас на кухне нет света. Что сломалось?', 'У вас на кухні немає світла. Що зламалося?', 'Mutfakta ışık yok. Ne bozuk?']),
    mc('K1', 'ansprechen', I.situation, 'Du brauchst eine Information vom Hausmeister. Wie sprichst du ihn höflich an?', ['Entschuldigung, darf ich Sie etwas fragen?', 'He, Sie da!', 'Was ist denn los?'],
      ['You need some information from the caretaker. How do you address him politely?', 'Вам нужна информация от завхоза. Как вежливо к нему обратиться?', 'Вам потрібна інформація від завгоспа. Як ввічливо до нього звернутися?', 'Bina görevlisinden bir bilgi almanız gerekiyor. Ona kibarca nasıl seslenirsiniz?']),
    mc('K2', 'Briefkasten leeren', I.situation, 'Du bist drei Tage nicht zu Hause und möchtest keine Post im Briefkasten lassen. Was fragst du deinen Nachbarn Tim?', ['Kannst du bitte meinen Briefkasten leeren?', 'Kannst du bitte meinen Briefkasten kaufen?', 'Leerst du gern Briefkästen?'],
      ['You are away for three days and do not want to leave any post in the letterbox. What do you ask your neighbour Tim?', 'Вас три дня не будет дома, и вы не хотите оставлять почту в ящике. О чём вы попросите соседа Tim?', 'Вас три дні не буде вдома, і ви не хочете залишати пошту в скриньці. Про що ви попросите сусіда Tim?', 'Üç gün evde olmayacaksınız ve posta kutusunda posta kalmasını istemiyorsunuz. Komşunuz Tim’e ne sorarsınız?']),
    mc('K3', 'zusagen', I.react, '„Würden Sie bitte kurz auf meine Tasche aufpassen?“', ['Natürlich, kein Problem.', 'Das war keine Absicht.', 'Mit freundlichen Grüßen.'],
      ['“Would you mind keeping an eye on my bag for a moment?”', '«Не могли бы вы минутку присмотреть за моей сумкой?»', '«Чи не могли б ви хвилинку наглянути за моєю сумкою?»', '“Çantama kısa bir süre göz kulak olur musunuz?”']),
    mc("K4", "danken", I.situation, "Herr Kaya hat dein Paket angenommen. Was sagst du?", ["Vielen Dank, das ist wirklich nett von Ihnen.","Tut mir leid, das habe ich nicht gewusst.","Nein, gar nicht."], ["Mr Kaya accepted your parcel. What do you say?","Господин Kaya принял вашу посылку. Что вы скажете?","Пан Kaya прийняв вашу посилку. Що ви скажете?","Kaya Bey paketinizi teslim aldı. Ne dersiniz?"], {"c":"p2_dank"}),
    mc('K5', 'sich entschuldigen', I.situation, 'Du hast nachts laut Musik gehört. Dein Nachbar ist sauer. Was sagst du?', ['Entschuldigung, das war keine Absicht.', 'Das mache ich gern.', 'Vielen Dank für Ihre Hilfe.'],
      ['You played loud music at night. Your neighbour is annoyed. What do you say?', 'Ночью вы громко слушали музыку. Сосед недоволен. Что вы скажете?', 'Уночі ви голосно слухали музику. Сусід невдоволений. Що ви скажете?', 'Gece yüksek sesle müzik dinlediniz. Komşunuz kızgın. Ne dersiniz?']),
    mc("K6", "Frau", I.situation, "Welche formelle Anrede für eine Frau mit dem Nachnamen Weber ist korrekt?", ["Sehr geehrte Frau Weber,","Sehr geehrter Frau Weber,","Liebe Weber,"], ["Which formal salutation for a woman with the surname Weber is correct?","Какое официальное обращение к женщине с фамилией Weber правильное?","Яке офіційне звертання до жінки з прізвищем Weber правильне?","Soyadı Weber olan bir kadına hangi resmî hitap doğrudur?"], {"c":"p2_brief"}),
    mc('Z1', 'Was tun?', I.read, `${REINIGUNG} Was sollen die Hausbewohner machen?`, ['Den Platz vor der Wohnungstür frei machen.', 'Das Treppenhaus selbst putzen.', 'Am Freitag zu Hause bleiben.'],
      ['What should the residents do?', 'Что должны сделать жильцы?', 'Що мають зробити мешканці?', 'Bina sakinleri ne yapmalı?']),
    gap('G1', 'unter + Dativ', I.article, 'Der Kinderwagen steht unter ', ' Treppe.', 'der', ['die', 'dem'],
      ['The pram is under the stairs.', 'Детская коляска стоит под лестницей.', 'Дитячий візок стоїть під сходами.', 'Bebek arabası merdivenin altında duruyor.'], 'die Treppe'),
    gap('G1', 'vor + Akkusativ', I.article, 'Stell die Schuhe bitte vor ', ' Tür.', 'die', ['der', 'dem'],
      ['Please put the shoes in front of the door.', 'Поставь, пожалуйста, обувь перед дверью.', 'Постав, будь ласка, взуття перед дверима.', 'Ayakkabıları lütfen kapının önüne koy.'], 'die Tür', { c: 'p2_wohin' }),
    gap('G2', 'legen', I.verb, 'Ich ', ' die Post auf den Küchentisch.', 'lege', ['liege', 'stehe'],
      ['I am putting the post on the kitchen table.', 'Я кладу почту на кухонный стол.', 'Я кладу пошту на кухонний стіл.', 'Postayı mutfak masasının üstüne koyuyorum.'], 'legen / liegen / stehen'),
    gap('G3', 'runter', I.adverb, 'Wir wohnen im dritten Stock. Der Ball liegt unten im Hof. Ich gehe schnell ', ' und hole ihn.', 'runter', ['rauf', 'rein'],
      ['We live on the third floor. The ball is down in the courtyard. I will quickly go down and get it.', 'Мы живём на четвёртом этаже. Мяч лежит внизу во дворе. Я быстро спущусь и принесу его.', 'Ми живемо на четвертому поверсі. М’яч лежить унизу у дворі. Я швидко спущуся й принесу його.', 'Üçüncü katta oturuyoruz. Top aşağıda, avluda duruyor. Hemen aşağı inip onu alıyorum.'], 'runter / rauf / rein', { h: 'short' }),
    sb('G1', 'hinter + Dativ', I.order, 'Das Fahrrad / steht / hinter / dem Haus.',
      ['The bike is behind the house.', 'Велосипед стоит за домом.', 'Велосипед стоїть за будинком.', 'Bisiklet evin arkasında duruyor.'],
      { alt: ['Hinter dem Haus steht das Fahrrad.'] }),
  ],
  size: 13,
  test: [
    mc('W1', 'Mieter', I.choose, 'Wer wohnt in einer Wohnung und zahlt jeden Monat Miete?', ['der Mieter', 'der Vermieter', 'der Hausmeister'],
      ['Who lives in a flat and pays rent every month?', 'Кто живёт в квартире и каждый месяц платит за аренду?', 'Хто живе у квартирі та щомісяця платить за оренду?', 'Kim bir dairede oturur ve her ay kira öder?']),
    mc('W1', 'Steckdose', I.choose, 'Der Akku von deinem Handy ist leer. Wohin steckst du das Ladekabel?', ['In die Steckdose.', 'In die Glühbirne.', 'In den Briefkasten.'],
      ['Your mobile battery is empty. Where do you plug in the charger?', 'Телефон разрядился. Куда вы вставите зарядку?', 'Телефон розрядився. Куди ви вставите зарядку?', 'Telefonunuzun şarjı bitti. Şarj kablosunu nereye takarsınız?']),
    mc('G1', 'im', I.choose, 'Wo ist der Hausmeister? – Er arbeitet gerade … Keller.', ['im', 'in den', 'ins'],
      ['Where is the caretaker? – He is working in the cellar right now.', 'Где завхоз? – Он сейчас работает в подвале.', 'Де завгосп? – Він зараз працює в підвалі.', 'Bina görevlisi nerede? – Şu anda bodrumda çalışıyor.']),
    mc('G1', 'in + Akkusativ', I.choose, 'Wohin stellst du das Fahrrad? – … Hof.', ['In den', 'Im', 'In dem'],
      ['Where are you putting the bike? – In the courtyard.', 'Куда ты ставишь велосипед? – Во двор.', 'Куди ти ставиш велосипед? – У двір.', 'Bisikleti nereye koyuyorsun? – Avluya.'], { c: 'p2_wohin' }),
    mc('G1', 'unter', I.choose, 'Der Tisch steht auf dem Teppich. Also liegt der Teppich … dem Tisch.', ['unter', 'über', 'neben'],
      ['The table is standing on the carpet. So the carpet is under the table.', 'Стол стоит на ковре. Значит, ковёр лежит под столом.', 'Стіл стоїть на килимі. Отже, килим лежить під столом.', 'Masa halının üstünde duruyor. Yani halı masanın altında.'], { h: 'prep' }),
    mc('G2', 'hängen', I.choose, 'Die Jacke … an der Garderobe.', ['hängt', 'legt', 'stellt'],
      ['The jacket is hanging on the coat rack.', 'Куртка висит на вешалке.', 'Куртка висить на вішалці.', 'Ceket askıda asılı.']),
    mc('G2', 'stellen', I.choose, 'Bitte … Sie die Leiter an die Wand.', ['stellen', 'stehen', 'liegen'],
      ['Please stand the ladder against the wall.', 'Пожалуйста, поставьте лестницу к стене.', 'Будь ласка, поставте драбину до стіни.', 'Lütfen merdiveni duvara dayayın.']),
    mc('G3', 'raus', I.situation, 'Die Kinder sitzen seit Stunden im Zimmer. Draußen scheint die Sonne. Was sagst du?', ['Geht doch raus in den Garten!', 'Kommt doch rein in den Garten!', 'Fallt nicht runter!'],
      ['The children have been sitting in their room for hours. Outside the sun is shining. What do you say?', 'Дети уже несколько часов сидят в комнате. На улице светит солнце. Что вы скажете?', 'Діти вже кілька годин сидять у кімнаті. Надворі світить сонце. Що ви скажете?', 'Çocuklar saatlerdir odada oturuyor. Dışarıda güneş var. Ne dersiniz?'], { h: 'short' }),
    mc('K1', 'ein Anliegen nennen', I.situation, 'Du gehst ins Büro von der Hausverwaltung. Wie beginnst du?', ['Guten Tag, ich habe eine Frage.', 'Guten Tag, kein Problem.', 'Guten Tag, das mache ich sofort.'],
      ['You go to the property management office. How do you begin?', 'Вы приходите в офис управляющей компании. Как вы начнёте?', 'Ви приходите в офіс керуючої компанії. Як ви почнете?', 'Bina yönetiminin ofisine gidiyorsunuz. Nasıl başlarsınız?']),
    mc("K2", "höflich bitten", I.situation, "Du brauchst eine Leiter. Dein Nachbar, Herr Haddad, hat eine. Was fragst du höflich?", ["Könnten Sie mir bitte Ihre Leiter leihen?","Geben Sie mir Ihre Leiter!","Ich will Ihre Leiter."], ["You need a ladder. Your neighbour, Mr Haddad, has one. What do you ask politely?","Вам нужна лестница. У вашего соседа, господина Haddad, она есть. Как вежливо попросить?","Вам потрібна драбина. У вашого сусіда, пана Haddad, вона є. Як ввічливо попросити?","Bir merdivene ihtiyacınız var. Komşunuz Haddad Bey’de var. Kibarca ne sorarsınız?"], {"c":"p2_bitten"}),
    mc('K3', 'absagen', I.react, '„Könntest du mir am Samstag beim Umzug helfen?“ – Du musst am Samstag arbeiten.', ['Leider kann ich nicht, weil ich arbeiten muss.', 'Natürlich, das mache ich gern.', 'Nein, gar nicht. Komm doch rein.'],
      ['“Could you help me move house on Saturday?” – You have to work on Saturday.', '«Не мог бы ты в субботу помочь мне с переездом?» – В субботу вам нужно работать.', '«Чи не міг би ти в суботу допомогти мені з переїздом?» – У суботу вам треба працювати.', '“Cumartesi günü taşınmama yardım edebilir misin?” – Cumartesi çalışmanız gerekiyor.']),
    mc('K4', 'Verständnis', I.choose, 'Ein Zettel von der Hausverwaltung endet so: „Wir hoffen auf Ihr …“', ['Verständnis.', 'Problem.', 'Wasser.'],
      ['A note from the property management ends like this: “We hope for your …”', 'Записка от управляющей компании заканчивается так: «Надеемся на ваше …»', 'Записка від керуючої компанії закінчується так: «Сподіваємося на ваше …»', 'Bina yönetiminden gelen bir not şöyle bitiyor: “… rica ederiz.”']),
    mc('K5', 'sich entschuldigen', I.react, '„Au! Sie stehen auf meinem Fuß!“', ['Oh, Entschuldigung! Das war keine Absicht.', 'Vielen Dank für den Tipp.', 'Das wäre wirklich nett.'],
      ['“Ouch! You are standing on my foot!”', '«Ой! Вы стоите на моей ноге!»', '«Ой! Ви стоїте на моїй нозі!»', '“Ay! Ayağıma basıyorsunuz!”']),
    mc('K6', 'an Freunde', I.situation, 'Du schreibst einem guten Freund. Wie beginnst du?', ['Lieber Jonas,', 'Sehr geehrter Herr Jonas,', 'Sehr geehrte Damen und Herren,'],
      ['You are writing to a good friend. How do you begin?', 'Вы пишете хорошему другу. Как вы начнёте?', 'Ви пишете доброму другові. Як ви почнете?', 'İyi bir arkadaşınıza yazıyorsunuz. Nasıl başlarsınız?']),
    mc('Z1', 'Was?', I.read, `${RAUCHMELDER} Was macht der Techniker?`, ['Er kontrolliert die Rauchmelder.', 'Er repariert die Heizung.', 'Er bringt neue Schlüssel.'],
      ['What does the technician do?', 'Что делает техник?', 'Що робить технік?', 'Teknisyen ne yapıyor?']),
    mc('Z1', 'Was tun?', I.read, `${RAUCHMELDER} Du arbeitest am Dienstagvormittag. Was machst du?`, ['Ich gebe einem Nachbarn meinen Schlüssel.', 'Ich rufe den Techniker am Abend an.', 'Ich muss nichts machen.'],
      ['You are working on Tuesday morning. What do you do?', 'Во вторник утром вы работаете. Что вы сделаете?', 'У вівторок уранці ви працюєте. Що ви зробите?', 'Salı sabahı çalışıyorsunuz. Ne yaparsınız?']),
    gap('W1', 'Briefkasten', I.word, 'Der Brief vom Amt ist da. Er liegt im ', '.', 'Briefkasten', ['Treppenhaus', 'Hausmeister'],
      ['The letter from the office has arrived. It is in the letterbox.', 'Письмо из ведомства пришло. Оно лежит в почтовом ящике.', 'Лист з установи прийшов. Він лежить у поштовій скриньці.', 'Resmî daireden mektup gelmiş. Posta kutusunda duruyor.'],
      ['letterbox', 'почтовый ящик', 'поштова скринька', 'posta kutusu']),
    gap('G1', 'über + Dativ', I.article, 'Das Bild hängt über ', ' Bett.', 'dem', ['das', 'den'],
      ['The picture is hanging above the bed.', 'Картина висит над кроватью.', 'Картина висить над ліжком.', 'Resim yatağın yukarısında asılı.'], 'das Bett'),
    gap('G1', 'neben + Akkusativ', I.article, 'Ich hänge den Spiegel neben ', ' Garderobe.', 'die', ['der', 'den'],
      ['I am hanging the mirror next to the coat rack.', 'Я вешаю зеркало рядом с вешалкой.', 'Я вішаю дзеркало поруч із вішалкою.', 'Aynayı askının yanına asıyorum.'], 'die Garderobe', { c: 'p2_wohin' }),
    gap('G1', 'zwischen + Dativ Plural', I.article, 'Die Kinder spielen zwischen ', ' Bäumen.', 'den', ['die', 'dem'],
      ['The children are playing between the trees.', 'Дети играют между деревьями.', 'Діти граються між деревами.', 'Çocuklar ağaçların arasında oynuyor.'], 'die Bäume (Plural)'),
    gap('G2', 'liegen', I.verb, 'Der Brief ', ' auf dem Schreibtisch.', 'liegt', ['legt', 'stellt'],
      ['The letter is lying on the desk.', 'Письмо лежит на письменном столе.', 'Лист лежить на письмовому столі.', 'Mektup masanın üstünde duruyor.'], 'liegen / legen / stellen'),
    gap('G2', 'stecken', I.verb, 'Ich ', ' den Schlüssel ins Schloss.', 'stecke', ['steckt', 'stelle'],
      ['I am putting the key into the lock.', 'Я вставляю ключ в замок.', 'Я вставляю ключ у замок.', 'Anahtarı kilide takıyorum.'], 'stecken'),
    gap('G3', 'dorthin', I.adverb, 'Stell den Karton bitte ', ', neben den Schrank.', 'dorthin', ['dort', 'hier'],
      ['Please put the box over there, next to the wardrobe.', 'Поставь, пожалуйста, коробку вон туда, рядом со шкафом.', 'Постав, будь ласка, коробку он туди, поруч із шафою.', 'Koliyi lütfen oraya, dolabın yanına koy.'], 'dort / dorthin / hier'),
    gap('G3', 'rein', I.adverb, 'Die Tür ist offen. Kommen Sie doch ', '!', 'rein', ['raus', 'runter'],
      ['The door is open. Do come in!', 'Дверь открыта. Заходите же!', 'Двері відчинені. Заходьте ж!', 'Kapı açık. Buyurun, içeri gelin!'], 'rein / raus / runter', { h: 'short' }),
    gap('K2', 'Könnten Sie …?', I.polite, '', ' Sie bitte meine Pflanzen gießen? Ich bin im Urlaub.', ['Könnten', 'Können'], ['Könntest', 'Kannst'],
      ['Could you water my plants, please? I am on holiday.', 'Не могли бы вы полить мои растения? Я в отпуске.', 'Чи не могли б ви полити мої рослини? Я у відпустці.', 'Lütfen çiçeklerimi sulayabilir misiniz? Tatildeyim.'], 'können'),
    gap('K4', 'danke für', I.prep, 'Danke ', ' Ihr Verständnis!', 'für', ['auf', 'mit'],
      ['Thank you for your understanding!', 'Спасибо за понимание!', 'Дякую за розуміння!', 'Anlayışınız için teşekkürler!'], 'für / auf / mit'),
    gap('K5', 'nicht gewusst', I.participle, 'Tut mir leid, das habe ich nicht ', '.', 'gewusst', ['gewisst', 'wissen'],
      ['I am sorry, I did not know that.', 'Простите, я этого не знал.', 'Перепрошую, я цього не знав.', 'Özür dilerim, bunu bilmiyordum.'], 'wissen'),
    gap('K6', 'Herr', I.ending, 'Sehr ', ' Herr Albers, ich habe eine Frage zur Miete.', 'geehrter', ['geehrte', 'geehrten'],
      ['Dear Mr Albers, I have a question about the rent.', 'Уважаемый господин Albers, у меня вопрос по поводу арендной платы.', 'Шановний пане Albers, у мене запитання щодо орендної плати.', 'Sayın Albers, kirayla ilgili bir sorum var.'], 'geehrt-'),
    gap('K1', 'ein Problem', I.word, 'Ich habe ein ', ': Meine Heizung funktioniert nicht.', 'Problem', ['Paket', 'Glück'],
      ['I have a problem: my heating is not working.', 'У меня проблема: не работает отопление.', 'У мене проблема: не працює опалення.', 'Bir sorunum var: Kaloriferim çalışmıyor.'],
      ['problem, trouble', 'проблема', 'проблема', 'sorun']),
    gap('K3', 'gar nicht', I.word, 'Störe ich? – Nein, ', ' nicht.', 'gar', ['sehr', 'viel'],
      ['Am I disturbing you? – No, not at all.', 'Я не помешаю? – Нет, совсем нет.', 'Я не заважаю? – Ні, зовсім ні.', 'Rahatsız ediyor muyum? – Hayır, hiç.'], 'gar / sehr / viel'),
    sb('G1', 'neben + Akkusativ', I.order, 'Ich / stelle / die Lampe / neben / das Sofa.',
      ['I am putting the lamp next to the sofa.', 'Я ставлю лампу рядом с диваном.', 'Я ставлю лампу поруч із диваном.', 'Lambayı kanepenin yanına koyuyorum.'], { alt: ['Die Lampe stelle ich neben das Sofa.', 'Neben das Sofa stelle ich die Lampe.'], c: 'p2_wohin' }),
    sb('K2', 'Kannst du …?', I.question, 'Kannst / du / bitte / meine Blumen / gießen?',
      ['Can you water my flowers, please?', 'Можешь, пожалуйста, полить мои цветы?', 'Можеш, будь ласка, полити мої квіти?', 'Lütfen çiçeklerimi sulayabilir misin?'],
      { alt: ['Kannst du meine Blumen bitte gießen?'] }),
  ],
}

export default check
