import { I, gap, mc, sb } from '../shared.mjs'

const HEIZUNG = 'Aushang: „Liebe Hausbewohner, am Donnerstag kommt die Firma Rohrfix und repariert die Heizung. Von 8 bis 14 Uhr gibt es kein warmes Wasser. Wir hoffen auf Ihr Verständnis. Ihre Hausverwaltung“'
const PARTY = 'Zettel im Treppenhaus: „Liebe Nachbarn, am Samstag feiere ich meinen 30. Geburtstag. Es kann ein bisschen laut sein. Ab 23 Uhr machen wir die Musik leise. Kommen Sie doch auch auf ein Glas vorbei! Viele Grüße, Dilara Aksoy, 3. Stock“'
const ORDNUNG = 'Hausordnung: „Bitte trennen Sie den Müll: Papier kommt in die blaue Tonne, Glas in den Container an der Ecke. Stellen Sie keine Fahrräder ins Treppenhaus. Der Fahrradkeller ist immer offen.“'

/** A2.1 · Pfad 2 · Zu Hause – Lektionen. Wiederholung und Test: p2-check.mjs */
const path = {
  n: 2,
  slug: 'zu-hause',
  title: 'Zu Hause',
  t: ['At home', 'Дома', 'Удома', 'Evde'],
  objectives: {
    G1: 'Wechselpräpositionen an, auf, hinter, in, neben, über, unter, vor, zwischen: Wo? mit Dativ – Wohin? mit Akkusativ.',
    G2: 'Verben für Ort und Richtung: liegen, stehen, hängen, stecken (Wo?) – legen, stellen, hängen, stecken (Wohin?).',
    G3: 'Richtungen nennen: hier, da, dort – hierhin, dahin, dorthin; rein, raus, rauf, runter, rüber.',
    K1: 'Jemanden höflich ansprechen und um Hilfe bitten: Störe ich? Darf ich Sie etwas fragen? Ich habe ein Problem.',
    K2: 'Nachbarn um einen Gefallen bitten: Könnten Sie bitte …? Kannst du bitte …? Würden Sie …?',
    K3: 'Auf eine Bitte reagieren: Natürlich. Kein Problem. Leider kann ich nicht, weil …',
    K4: 'Sich bedanken: Vielen Dank für Ihre Hilfe. Das ist wirklich nett. Wir hoffen auf Ihr Verständnis.',
    K5: 'Sich entschuldigen: Tut mir leid. Das war keine Absicht. Das habe ich nicht gewusst.',
    K6: 'Anrede und Gruß in Briefen und Mitteilungen: Sehr geehrte …, Liebe …, Mit freundlichen Grüßen.',
    Z1: 'Kann-Ziele: Aushänge und Mitteilungen im Mietshaus verstehen.',
    W1: 'Wortschatz: Wohnung und Mietshaus.',
  },
  nodes: [
    {
      title: 'Im Mietshaus',
      t: ['In the block of flats', 'В многоквартирном доме', 'У багатоквартирному будинку', 'Apartmanda'],
      card: {
        id: 'p2_haus',
        rule: 'Im Mietshaus: Der Mieter oder die Mieterin wohnt in der Wohnung und zahlt Miete. Der Vermieter oder die Vermieterin bekommt die Miete. Der Hausmeister repariert Sachen im Haus. Alle Hausbewohner benutzen das Treppenhaus, den Hof, den Keller und den Aufzug. Die Post kommt in den Briefkasten, der Müll in die Mülltonne. In der Wohnung: die Wand, die Decke, der Boden, das Fenster, die Heizung, die Steckdose, die Glühbirne.',
        examples: ['Der Hausmeister repariert das Licht im Treppenhaus.', 'Der Müll kommt in die Mülltonne im Hof.', 'Das Bild hängt an der Wand.'],
        highlight: 'article',
        t: [
          'In a block of flats: der Mieter / die Mieterin (tenant) lives in the flat and pays die Miete (rent). Der Vermieter / die Vermieterin (landlord, landlady) gets the rent. Der Hausmeister (caretaker) repairs things in the building. All Hausbewohner (residents) use das Treppenhaus (stairwell), den Hof (courtyard), den Keller (cellar) and den Aufzug (lift). The post goes into den Briefkasten (letterbox), the rubbish (der Müll) into die Mülltonne (bin). In the flat: die Wand (wall), die Decke (ceiling), der Boden (floor), das Fenster (window), die Heizung (heating), die Steckdose (socket), die Glühbirne (light bulb).',
          'В многоквартирном доме: der Mieter / die Mieterin (квартиросъёмщик) живёт в квартире и платит die Miete (арендную плату). Der Vermieter / die Vermieterin (арендодатель) получает плату. Der Hausmeister (управдом, завхоз) чинит всё в доме. Все Hausbewohner (жильцы) пользуются das Treppenhaus (лестничной клеткой), den Hof (двором), den Keller (подвалом) и den Aufzug (лифтом). Почта попадает в den Briefkasten (почтовый ящик), мусор (der Müll) – в die Mülltonne (мусорный бак). В квартире: die Wand (стена), die Decke (потолок), der Boden (пол), das Fenster (окно), die Heizung (отопление), die Steckdose (розетка), die Glühbirne (лампочка).',
          'У багатоквартирному будинку: der Mieter / die Mieterin (орендар) живе у квартирі та платить die Miete (орендну плату). Der Vermieter / die Vermieterin (орендодавець) отримує плату. Der Hausmeister (завгосп будинку) лагодить усе в будинку. Усі Hausbewohner (мешканці) користуються das Treppenhaus (сходовою кліткою), den Hof (двором), den Keller (підвалом) і den Aufzug (ліфтом). Пошта потрапляє в den Briefkasten (поштову скриньку), сміття (der Müll) – у die Mülltonne (сміттєвий бак). У квартирі: die Wand (стіна), die Decke (стеля), der Boden (підлога), das Fenster (вікно), die Heizung (опалення), die Steckdose (розетка), die Glühbirne (лампочка).',
          'Apartmanda: der Mieter / die Mieterin (kiracı) dairede oturur ve die Miete (kira) öder. Der Vermieter / die Vermieterin (ev sahibi) kirayı alır. Der Hausmeister (kapıcı, bina görevlisi) binadaki şeyleri tamir eder. Bütün Hausbewohner (bina sakinleri) das Treppenhaus (merdiven boşluğu), den Hof (avlu), den Keller (bodrum) ve den Aufzug’u (asansör) kullanır. Posta den Briefkasten’a (posta kutusu), çöp (der Müll) die Mülltonne’ye (çöp bidonu) gider. Dairede: die Wand (duvar), die Decke (tavan), der Boden (zemin), das Fenster (pencere), die Heizung (kalorifer), die Steckdose (priz), die Glühbirne (ampul).',
        ],
        hint: ['Überleg: Ist es eine Person im Haus, ein Ort im Haus oder ein Teil von der Wohnung?', 'Think: is it a person in the building, a place in the building or a part of the flat?', 'Подумайте: это человек в доме, место в доме или часть квартиры?', 'Подумайте: це людина в будинку, місце в будинку чи частина квартири?', 'Düşünün: Bu binadaki bir kişi mi, binadaki bir yer mi, yoksa dairenin bir parçası mı?'],
      },
      ex: [
        mc('W1', 'Hausmeister', I.choose, 'Das Licht im Treppenhaus ist kaputt. Wer repariert es?', ['der Hausmeister', 'der Briefkasten', 'der Mieter'],
          ['The light in the stairwell is broken. Who repairs it?', 'На лестнице не горит свет. Кто его починит?', 'На сходах не горить світло. Хто його полагодить?', 'Merdivendeki ışık bozuk. Onu kim tamir eder?']),
        mc('W1', 'Briefkasten', I.choose, 'Wo findest du deine Post?', ['Im Briefkasten.', 'In der Mülltonne.', 'An der Decke.'],
          ['Where do you find your post?', 'Где вы найдёте свою почту?', 'Де ви знайдете свою пошту?', 'Postanızı nerede bulursunuz?']),
        mc('W1', 'Vermieterin', I.choose, 'Frau Lindner gehört das Haus. Sie bekommt jeden Monat die Miete. Sie ist die …', ['Vermieterin', 'Mieterin', 'Hausmeisterin'],
          ['The house belongs to Ms Lindner. She gets the rent every month. She is the …', 'Дом принадлежит госпоже Lindner. Каждый месяц она получает арендную плату. Она …', 'Будинок належить пані Lindner. Щомісяця вона отримує орендну плату. Вона …', 'Ev Lindner Hanım’a ait. Her ay kirayı o alıyor. O …']),
        mc('W1', 'Mietshaus', I.odd, 'Drei Wörter gehören zum Mietshaus, ein Wort nicht.', ['Bahnhof', 'Treppenhaus', 'Hof', 'Keller'], null),
        gap('W1', 'Müll', I.word, 'Die Dose ist leer. Sie kommt in den ', '.', 'Müll', ['Brief', 'Hof'],
          ['The tin is empty. It goes into the rubbish.', 'Банка пустая. Её нужно выбросить в мусор.', 'Банка порожня. Її треба викинути у сміття.', 'Kutu boş. Çöpe atılacak.'],
          ['rubbish', 'мусор', 'сміття', 'çöp']),
        gap('W1', 'Wand', I.word, 'Das Foto von meiner Familie hängt an der ', '.', 'Wand', ['Miete', 'Steckdose'],
          ['The photo of my family is hanging on the wall.', 'Фото моей семьи висит на стене.', 'Фото моєї родини висить на стіні.', 'Ailemin fotoğrafı duvarda asılı.'],
          ['wall', 'стена', 'стіна', 'duvar']),
        gap('W1', 'Treppenhaus', I.word, 'Der Aufzug ist kaputt. Wir müssen durch das ', ' gehen.', 'Treppenhaus', ['Fenster', 'Dach'],
          ['The lift is broken. We have to go through the stairwell.', 'Лифт сломан. Нам придётся идти по лестнице.', 'Ліфт зламаний. Нам доведеться йти сходами.', 'Asansör bozuk. Merdivenden çıkmamız gerekiyor.'],
          ['stairwell', 'лестничная клетка', 'сходова клітка', 'merdiven boşluğu']),
        gap('W1', 'Mieter', I.word, 'Ich wohne hier und zahle jeden Monat 600 Euro. Ich bin der ', '.', 'Mieter', ['Vermieter', 'Hausmeister'],
          ['I live here and pay 600 euros every month. I am the tenant.', 'Я живу здесь и каждый месяц плачу 600 евро. Я квартиросъёмщик.', 'Я живу тут і щомісяця плачу 600 євро. Я орендар.', 'Burada oturuyorum ve her ay 600 avro ödüyorum. Ben kiracıyım.'],
          ['tenant', 'квартиросъёмщик', 'орендар', 'kiracı']),
        sb('W1', 'Hausmeister', I.order, 'Der Hausmeister / repariert / heute / die Heizung.',
          ['The caretaker is repairing the heating today.', 'Сегодня завхоз чинит отопление.', 'Сьогодні завгосп лагодить опалення.', 'Bina görevlisi bugün kaloriferi tamir ediyor.'],
          { alt: ['Heute repariert der Hausmeister die Heizung.', 'Die Heizung repariert der Hausmeister heute.'] }),
      ],
    },
    {
      title: 'Wo? – Auf dem Tisch.',
      t: ['Where? – On the table.', 'Где? – На столе.', 'Де? – На столі.', 'Nerede? – Masanın üstünde.'],
      card: {
        id: 'p2_wo',
        rule: 'Wo ist etwas? Die Präpositionen an, auf, hinter, in, neben, über, unter, vor und zwischen brauchen bei der Frage Wo? den Dativ: der → dem, das → dem, die → der, Plural: die → den (Nomen + n). Das Buch liegt auf dem Tisch. Die Katze sitzt unter dem Sofa. Das Bild hängt an der Wand. Die Schuhe stehen vor den Türen. Kurzformen: in dem = im, an dem = am.',
        examples: ['Der Schlüssel liegt auf dem Tisch.', 'Die Lampe hängt über dem Sofa.', 'Das Fahrrad steht im Keller.'],
        highlight: 'article',
        t: [
          'Where is something? With the question Wo? the prepositions an (at, on a vertical surface), auf (on), hinter (behind), in (in), neben (next to), über (above), unter (under), vor (in front of) and zwischen (between) take the dative: der → dem, das → dem, die → der, plural: die → den (noun + n). Das Buch liegt auf dem Tisch. Die Katze sitzt unter dem Sofa. Das Bild hängt an der Wand. Die Schuhe stehen vor den Türen. Short forms: in dem = im, an dem = am.',
          'Где что-то находится? При вопросе Wo? предлоги an (у, на вертикальной поверхности), auf (на), hinter (за), in (в), neben (рядом), über (над), unter (под), vor (перед) и zwischen (между) требуют Dativ: der → dem, das → dem, die → der, множественное число: die → den (существительное + n). Das Buch liegt auf dem Tisch. Die Katze sitzt unter dem Sofa. Das Bild hängt an der Wand. Die Schuhe stehen vor den Türen. Краткие формы: in dem = im, an dem = am.',
          'Де щось розташоване? При запитанні Wo? прийменники an (біля, на вертикальній поверхні), auf (на), hinter (за), in (в), neben (поруч), über (над), unter (під), vor (перед) і zwischen (між) вимагають Dativ: der → dem, das → dem, die → der, множина: die → den (іменник + n). Das Buch liegt auf dem Tisch. Die Katze sitzt unter dem Sofa. Das Bild hängt an der Wand. Die Schuhe stehen vor den Türen. Короткі форми: in dem = im, an dem = am.',
          'Bir şey nerede? Wo? sorusunda an (yanında, dik yüzeyde), auf (üstünde), hinter (arkasında), in (içinde), neben (yanında), über (yukarısında), unter (altında), vor (önünde) ve zwischen (arasında) edatları Dativ ister: der → dem, das → dem, die → der, çoğul: die → den (isim + n). Das Buch liegt auf dem Tisch. Die Katze sitzt unter dem Sofa. Das Bild hängt an der Wand. Die Schuhe stehen vor den Türen. Kısa biçimler: in dem = im, an dem = am.',
        ],
        hint: ['Wo? → Dativ: dem (der, das), der (die), den (Plural).', 'Wo? → dative: dem (der, das), der (die), den (plural).', 'Wo? → Dativ: dem (der, das), der (die), den (множественное число).', 'Wo? → Dativ: dem (der, das), der (die), den (множина).', 'Wo? → Dativ: dem (der, das), der (die), den (çoğul).'],
        hints: {
          prep: ['auf = oben mit Kontakt, über = oben ohne Kontakt, an = an der Seite, neben = links oder rechts, zwischen = in der Mitte von zwei Sachen.', 'auf = on top, touching; über = above, not touching; an = at the side; neben = to the left or right; zwischen = in the middle of two things.', 'auf = сверху, касаясь; über = сверху, не касаясь; an = сбоку, вплотную; neben = слева или справа; zwischen = посередине между двумя предметами.', 'auf = зверху, торкаючись; über = зверху, не торкаючись; an = збоку, впритул; neben = ліворуч або праворуч; zwischen = посередині між двома предметами.', 'auf = üstünde, değerek; über = yukarısında, değmeden; an = yanında, bitişik; neben = solunda ya da sağında; zwischen = iki şeyin ortasında.'],
        },
      },
      ex: [
        mc('G1', 'auf + Dativ', I.choose, 'Wo ist die Zeitung? – Sie liegt auf … Tisch.', ['dem', 'den', 'der'],
          ['Where is the newspaper? – It is on the table.', 'Где газета? – Она лежит на столе.', 'Де газета? – Вона лежить на столі.', 'Gazete nerede? – Masanın üstünde.']),
        mc('G1', 'an + Dativ', I.choose, 'Wo hängt das Bild? – An … Wand.', ['der', 'die', 'dem'],
          ['Where is the picture hanging? – On the wall.', 'Где висит картина? – На стене.', 'Де висить картина? – На стіні.', 'Resim nerede asılı? – Duvarda.']),
        mc('G1', 'über', I.choose, 'Die Lampe hängt … dem Tisch. Sie berührt den Tisch nicht.', ['über', 'auf', 'unter'],
          ['The lamp hangs above the table. It does not touch the table.', 'Лампа висит над столом. Она не касается стола.', 'Лампа висить над столом. Вона не торкається стола.', 'Lamba masanın yukarısında asılı. Masaya değmiyor.'], { h: 'prep' }),
        mc('G1', 'im', I.choose, 'Wo sind die Kinder? – Sie spielen … Hof.', ['im', 'in den', 'ins'],
          ['Where are the children? – They are playing in the courtyard.', 'Где дети? – Они играют во дворе.', 'Де діти? – Вони граються у дворі.', 'Çocuklar nerede? – Avluda oynuyorlar.']),
        gap('G1', 'unter + Dativ', I.article, 'Die Katze schläft unter ', ' Sofa.', 'dem', ['das', 'der'],
          ['The cat is sleeping under the sofa.', 'Кошка спит под диваном.', 'Кішка спить під диваном.', 'Kedi kanepenin altında uyuyor.'], 'das Sofa'),
        gap('G1', 'vor + Dativ', I.article, 'Das Auto steht vor ', ' Garage.', 'der', ['die', 'dem'],
          ['The car is in front of the garage.', 'Машина стоит перед гаражом.', 'Машина стоїть перед гаражем.', 'Araba garajın önünde duruyor.'], 'die Garage'),
        gap('G1', 'hinter + Dativ', I.article, 'Die Mülltonnen stehen hinter ', ' Haus.', 'dem', ['das', 'den'],
          ['The bins are behind the house.', 'Мусорные баки стоят за домом.', 'Сміттєві баки стоять за будинком.', 'Çöp bidonları evin arkasında duruyor.'], 'das Haus'),
        gap('G1', 'zwischen', I.prep, 'Der Stuhl steht ', ' dem Schrank und dem Fenster.', 'zwischen', ['über', 'in'],
          ['The chair is between the wardrobe and the window.', 'Стул стоит между шкафом и окном.', 'Стілець стоїть між шафою та вікном.', 'Sandalye dolap ile pencerenin arasında duruyor.'],
          ['between', 'между', 'між', 'arasında'], { h: 'prep' }),
        gap('G1', 'neben + Dativ Plural', I.article, 'Die Briefe liegen neben ', ' Büchern.', 'den', ['die', 'dem'],
          ['The letters are next to the books.', 'Письма лежат рядом с книгами.', 'Листи лежать поруч із книжками.', 'Mektuplar kitapların yanında duruyor.'], 'die Bücher (Plural)'),
        sb('G1', 'auf + Dativ', I.order, 'Die Schlüssel / liegen / auf / dem Tisch.',
          ['The keys are on the table.', 'Ключи лежат на столе.', 'Ключі лежать на столі.', 'Anahtarlar masanın üstünde.'],
          { alt: ['Auf dem Tisch liegen die Schlüssel.'] }),
      ],
    },
    {
      title: 'Wohin? – Auf den Tisch.',
      t: ['Where to? – Onto the table.', 'Куда? – На стол.', 'Куди? – На стіл.', 'Nereye? – Masanın üstüne.'],
      card: {
        id: 'p2_wohin',
        rule: 'Wohin kommt etwas? Bei der Frage Wohin? brauchen an, auf, hinter, in, neben, über, unter, vor und zwischen den Akkusativ: der → den, das → das, die → die, Plural: die → die. Ich lege das Buch auf den Tisch. Die Katze läuft unter das Sofa. Ich hänge das Bild an die Wand. Kurzformen: in das = ins, an das = ans. Vergleich: Wo? Das Buch liegt auf dem Tisch. (Dativ) Wohin? Ich lege das Buch auf den Tisch. (Akkusativ)',
        examples: ['Ich stelle die Flaschen in den Keller.', 'Häng die Jacke bitte an die Garderobe.', 'Wir gehen ins Treppenhaus.'],
        highlight: 'article',
        t: [
          'Where does something go? With the question Wohin? (where to?) an, auf, hinter, in, neben, über, unter, vor and zwischen take the accusative: der → den, das → das, die → die, plural: die → die. Ich lege das Buch auf den Tisch. Die Katze läuft unter das Sofa. Ich hänge das Bild an die Wand. Short forms: in das = ins, an das = ans. Compare: Wo? Das Buch liegt auf dem Tisch. (dative) Wohin? Ich lege das Buch auf den Tisch. (accusative)',
          'Куда что-то помещают? При вопросе Wohin? (куда?) предлоги an, auf, hinter, in, neben, über, unter, vor и zwischen требуют Akkusativ: der → den, das → das, die → die, множественное число: die → die. Ich lege das Buch auf den Tisch. Die Katze läuft unter das Sofa. Ich hänge das Bild an die Wand. Краткие формы: in das = ins, an das = ans. Сравните: Wo? Das Buch liegt auf dem Tisch. (Dativ) Wohin? Ich lege das Buch auf den Tisch. (Akkusativ)',
          'Куди щось кладуть? При запитанні Wohin? (куди?) прийменники an, auf, hinter, in, neben, über, unter, vor і zwischen вимагають Akkusativ: der → den, das → das, die → die, множина: die → die. Ich lege das Buch auf den Tisch. Die Katze läuft unter das Sofa. Ich hänge das Bild an die Wand. Короткі форми: in das = ins, an das = ans. Порівняйте: Wo? Das Buch liegt auf dem Tisch. (Dativ) Wohin? Ich lege das Buch auf den Tisch. (Akkusativ)',
          'Bir şey nereye konur? Wohin? (nereye?) sorusunda an, auf, hinter, in, neben, über, unter, vor ve zwischen Akkusativ ister: der → den, das → das, die → die, çoğul: die → die. Ich lege das Buch auf den Tisch. Die Katze läuft unter das Sofa. Ich hänge das Bild an die Wand. Kısa biçimler: in das = ins, an das = ans. Karşılaştırın: Wo? Das Buch liegt auf dem Tisch. (Dativ) Wohin? Ich lege das Buch auf den Tisch. (Akkusativ)',
        ],
        hint: ['Wohin? → Akkusativ: den (der), das, die. Nur maskulin ändert sich: der → den.', 'Wohin? → accusative: den (der), das, die. Only the masculine changes: der → den.', 'Wohin? → Akkusativ: den (der), das, die. Меняется только мужской род: der → den.', 'Wohin? → Akkusativ: den (der), das, die. Змінюється лише чоловічий рід: der → den.', 'Wohin? → Akkusativ: den (der), das, die. Yalnızca eril değişir: der → den.'],
        hints: {
          both: ['Bewegung zu einem Ort: Wohin? + Akkusativ. Kein Ortswechsel: Wo? + Dativ.', 'Movement to a place: Wohin? + accusative. No change of place: Wo? + dative.', 'Движение к месту: Wohin? + Akkusativ. Без перемещения: Wo? + Dativ.', 'Рух до місця: Wohin? + Akkusativ. Без переміщення: Wo? + Dativ.', 'Bir yere doğru hareket: Wohin? + Akkusativ. Yer değişmiyorsa: Wo? + Dativ.'],
        },
      },
      ex: [
        mc('G1', 'auf + Akkusativ', I.choose, 'Wohin legst du die Zeitung? – Auf … Tisch.', ['den', 'dem', 'der'],
          ['Where are you putting the newspaper? – On the table.', 'Куда ты кладёшь газету? – На стол.', 'Куди ти кладеш газету? – На стіл.', 'Gazeteyi nereye koyuyorsun? – Masanın üstüne.']),
        mc('G1', 'über + Akkusativ', I.choose, 'Wohin hängen wir die Lampe? – Über … Sofa.', ['das', 'dem', 'den'],
          ['Where shall we hang the lamp? – Above the sofa.', 'Куда повесим лампу? – Над диваном.', 'Куди повісимо лампу? – Над диваном.', 'Lambayı nereye asalım? – Kanepenin yukarısına.']),
        mc('G1', 'in + Akkusativ', I.choose, 'Wohin bringst du die Kartons? – … Keller.', ['In den', 'Im', 'In dem'],
          ['Where are you taking the boxes? – To the cellar.', 'Куда ты несёшь коробки? – В подвал.', 'Куди ти несеш коробки? – У підвал.', 'Kolileri nereye götürüyorsun? – Bodruma.']),
        mc('G1', 'Wo oder Wohin?', I.choose, 'Welcher Satz antwortet auf die Frage „Wo?“', ['Die Tasche steht neben der Tür.', 'Ich stelle die Tasche neben die Tür.', 'Stell die Tasche bitte neben die Tür.'],
          ['Which sentence answers the question “Wo?” (where?)', 'Какое предложение отвечает на вопрос «Wo?» (где?)', 'Яке речення відповідає на запитання «Wo?» (де?)', 'Hangi cümle “Wo?” (nerede?) sorusuna cevap veriyor?'], { h: 'both' }),
        mc('G1', 'Wo oder Wohin?', I.choose, 'Die Kinder laufen aus dem Haus in … Hof.', ['den', 'dem', 'der'],
          ['The children run out of the house into the courtyard.', 'Дети выбегают из дома во двор.', 'Діти вибігають із будинку у двір.', 'Çocuklar evden avluya koşuyor.'], { h: 'both' }),
        gap('G1', 'auf + Akkusativ', I.article, 'Ich stelle die Blumen auf ', ' Balkon.', 'den', ['dem', 'der'],
          ['I am putting the flowers on the balcony.', 'Я ставлю цветы на балкон.', 'Я ставлю квіти на балкон.', 'Çiçekleri balkona koyuyorum.'], 'der Balkon'),
        gap('G1', 'neben + Akkusativ', I.article, 'Leg das Handy bitte neben ', ' Lampe.', 'die', ['der', 'den'],
          ['Please put the mobile next to the lamp.', 'Положи, пожалуйста, телефон рядом с лампой.', 'Поклади, будь ласка, телефон поруч із лампою.', 'Telefonu lütfen lambanın yanına koy.'], 'die Lampe'),
        gap('G1', 'auf + Akkusativ', I.article, 'Die Katze springt auf ', ' Bett.', 'das', ['dem', 'den'],
          ['The cat jumps onto the bed.', 'Кошка прыгает на кровать.', 'Кішка стрибає на ліжко.', 'Kedi yatağın üstüne atlıyor.'], 'das Bett'),
        gap('G1', 'hinter + Akkusativ', I.article, 'Häng den Mantel bitte hinter ', ' Tür.', 'die', ['der', 'dem'],
          ['Please hang the coat behind the door.', 'Повесь, пожалуйста, пальто за дверь.', 'Повісь, будь ласка, пальто за двері.', 'Paltoyu lütfen kapının arkasına as.'], 'die Tür'),
        sb('G1', 'an + Akkusativ', I.order, 'Ich / hänge / das Bild / an / die Wand.',
          ['I am hanging the picture on the wall.', 'Я вешаю картину на стену.', 'Я вішаю картину на стіну.', 'Resmi duvara asıyorum.'],
          { alt: ['Das Bild hänge ich an die Wand.', 'An die Wand hänge ich das Bild.'] }),
      ],
    },
    {
      title: 'liegen oder legen?',
      t: ['liegen or legen?', 'liegen или legen?', 'liegen чи legen?', 'liegen mi, legen mi?'],
      card: {
        id: 'p2_verben',
        rule: 'Zwei Gruppen von Verben. Wo? + Dativ: liegen, stehen, hängen, stecken. Das Buch liegt auf dem Tisch. Die Flasche steht im Schrank. Das Bild hängt an der Wand. Der Schlüssel steckt im Schloss. Wohin? + Akkusativ: legen, stellen, hängen, stecken. Ich lege das Buch auf den Tisch. Ich stelle die Flasche in den Schrank. Ich hänge das Bild an die Wand. Ich stecke den Schlüssel ins Schloss. Liegen und legen: flach. Stehen und stellen: aufrecht.',
        examples: ['Die Zeitung liegt auf dem Sofa.', 'Stell die Flasche bitte in den Kühlschrank.', 'Der Schlüssel steckt in der Tür.'],
        highlight: 'verb',
        t: [
          'Two groups of verbs. Wo? + dative: liegen (to lie), stehen (to stand), hängen (to hang), stecken (to be stuck in). Das Buch liegt auf dem Tisch. Die Flasche steht im Schrank. Das Bild hängt an der Wand. Der Schlüssel steckt im Schloss. Wohin? + accusative: legen (to lay), stellen (to stand something somewhere), hängen (to hang something), stecken (to put into). Ich lege das Buch auf den Tisch. Ich stelle die Flasche in den Schrank. Ich hänge das Bild an die Wand. Ich stecke den Schlüssel ins Schloss. Liegen and legen: flat. Stehen and stellen: upright.',
          'Две группы глаголов. Wo? + Dativ: liegen (лежать), stehen (стоять), hängen (висеть), stecken (торчать, быть вставленным). Das Buch liegt auf dem Tisch. Die Flasche steht im Schrank. Das Bild hängt an der Wand. Der Schlüssel steckt im Schloss. Wohin? + Akkusativ: legen (класть), stellen (ставить), hängen (вешать), stecken (вставлять). Ich lege das Buch auf den Tisch. Ich stelle die Flasche in den Schrank. Ich hänge das Bild an die Wand. Ich stecke den Schlüssel ins Schloss. Liegen и legen: предмет лежит плашмя. Stehen и stellen: предмет стоит вертикально.',
          'Дві групи дієслів. Wo? + Dativ: liegen (лежати), stehen (стояти), hängen (висіти), stecken (стирчати, бути вставленим). Das Buch liegt auf dem Tisch. Die Flasche steht im Schrank. Das Bild hängt an der Wand. Der Schlüssel steckt im Schloss. Wohin? + Akkusativ: legen (класти), stellen (ставити), hängen (вішати), stecken (вставляти). Ich lege das Buch auf den Tisch. Ich stelle die Flasche in den Schrank. Ich hänge das Bild an die Wand. Ich stecke den Schlüssel ins Schloss. Liegen і legen: предмет лежить пласко. Stehen і stellen: предмет стоїть вертикально.',
          'İki fiil grubu. Wo? + Dativ: liegen (yatmak, durmak), stehen (dik durmak), hängen (asılı olmak), stecken (takılı olmak). Das Buch liegt auf dem Tisch. Die Flasche steht im Schrank. Das Bild hängt an der Wand. Der Schlüssel steckt im Schloss. Wohin? + Akkusativ: legen (yatırarak koymak), stellen (dik koymak), hängen (asmak), stecken (takmak, sokmak). Ich lege das Buch auf den Tisch. Ich stelle die Flasche in den Schrank. Ich hänge das Bild an die Wand. Ich stecke den Schlüssel ins Schloss. Liegen ve legen: yatay. Stehen ve stellen: dik.',
        ],
        hint: ['Wo? → liegen, stehen, hängen, stecken. Wohin? → legen, stellen, hängen, stecken.', 'Where? → liegen, stehen, hängen, stecken. Where to? → legen, stellen, hängen, stecken.', 'Wo? (где?) → liegen, stehen, hängen, stecken. Wohin? (куда?) → legen, stellen, hängen, stecken.', 'Wo? (де?) → liegen, stehen, hängen, stecken. Wohin? (куди?) → legen, stellen, hängen, stecken.', 'Wo? (nerede?) → liegen, stehen, hängen, stecken. Wohin? (nereye?) → legen, stellen, hängen, stecken.'],
      },
      ex: [
        mc('G2', 'liegen', I.choose, 'Wo ist das Handy? – Es … auf dem Bett.', ['liegt', 'legt', 'stellt'],
          ['Where is the mobile? – It is lying on the bed.', 'Где телефон? – Он лежит на кровати.', 'Де телефон? – Він лежить на ліжку.', 'Telefon nerede? – Yatağın üstünde duruyor.']),
        mc('G2', 'stellen', I.choose, 'Ich … die Vase auf den Tisch.', ['stelle', 'stehe', 'liege'],
          ['I am putting the vase on the table.', 'Я ставлю вазу на стол.', 'Я ставлю вазу на стіл.', 'Vazoyu masanın üstüne koyuyorum.']),
        mc('G2', 'stecken', I.choose, 'Ich kann die Tür nicht schließen. Der Schlüssel … innen im Schloss.', ['steckt', 'stellt', 'legt'],
          ['I cannot lock the door. The key is in the lock on the inside.', 'Я не могу закрыть дверь. Ключ вставлен в замок изнутри.', 'Я не можу зачинити двері. Ключ вставлений у замок ізсередини.', 'Kapıyı kilitleyemiyorum. Anahtar içeriden kilide takılı.']),
        mc('G2', 'hängen', I.choose, 'Wir … die neue Lampe über den Tisch.', ['hängen', 'liegen', 'stehen'],
          ['We are hanging the new lamp above the table.', 'Мы вешаем новую лампу над столом.', 'Ми вішаємо нову лампу над столом.', 'Yeni lambayı masanın yukarısına asıyoruz.']),
        gap('G2', 'stehen', I.verb, 'Die Flaschen ', ' im Keller.', 'stehen', ['stellen', 'legen'],
          ['The bottles are in the cellar.', 'Бутылки стоят в подвале.', 'Пляшки стоять у підвалі.', 'Şişeler bodrumda duruyor.'], 'stehen / stellen / legen'),
        gap('G2', 'legen', I.verb, 'Bitte ', ' Sie den Brief auf meinen Schreibtisch.', 'legen', ['liegen', 'stehen'],
          ['Please put the letter on my desk.', 'Пожалуйста, положите письмо на мой письменный стол.', 'Будь ласка, покладіть лист на мій письмовий стіл.', 'Lütfen mektubu masamın üstüne koyun.'], 'legen / liegen / stehen'),
        gap('G2', 'hängen', I.verb, 'Das Foto ', ' an der Wand über dem Sofa.', 'hängt', ['legt', 'stellt'],
          ['The photo is hanging on the wall above the sofa.', 'Фотография висит на стене над диваном.', 'Фотографія висить на стіні над диваном.', 'Fotoğraf kanepenin üstündeki duvarda asılı.'], 'hängen / legen / stellen'),
        gap('G2', 'stellen', I.verb, 'Er ', ' den Stuhl neben das Fenster.', 'stellt', ['steht', 'liegt'],
          ['He is putting the chair next to the window.', 'Он ставит стул рядом с окном.', 'Він ставить стілець поруч із вікном.', 'Sandalyeyi pencerenin yanına koyuyor.'], 'stellen / stehen / liegen'),
        gap('G2', 'liegen', I.verb, 'Die Zeitung ', ' auf dem Boden.', 'liegt', ['legt', 'stellt'],
          ['The newspaper is lying on the floor.', 'Газета лежит на полу.', 'Газета лежить на підлозі.', 'Gazete yerde duruyor.'], 'liegen / legen / stellen'),
        sb('G2', 'stecken', I.order, 'Der Schlüssel / steckt / in / der Tür.',
          ['The key is in the door.', 'Ключ торчит в двери.', 'Ключ стирчить у дверях.', 'Anahtar kapıda takılı.'],
          { alt: ['In der Tür steckt der Schlüssel.'] }),
      ],
    },
    {
      title: 'dorthin, rein, runter',
      t: ['dorthin, rein, runter (directions)', 'dorthin, rein, runter (направления)', 'dorthin, rein, runter (напрямки)', 'dorthin, rein, runter (yönler)'],
      card: {
        id: 'p2_richtung',
        rule: 'Richtungen nennen: Wo? hier, da, dort. Wohin? hierhin, dahin, dorthin. Stellen Sie die Leiter bitte dahin. In der gesprochenen Sprache: rein (in einen Raum), raus (aus einem Raum), rauf (nach oben), runter (nach unten), rüber (auf die andere Seite). Diese Wörter stehen oft mit einem Verb zusammen: reinkommen, rausgehen, raufgehen, runterfallen, rübergehen. Kommen Sie doch rein! Fallen Sie nicht runter!',
        examples: ['Stell die Kiste bitte dorthin.', 'Komm doch rein!', 'Vorsicht, die Vase fällt runter!'],
        highlight: null,
        t: [
          'Giving directions: Wo? hier (here), da, dort (there). Wohin? hierhin (to here), dahin, dorthin (to there). Stellen Sie die Leiter bitte dahin. In spoken German: rein (into a room), raus (out of a room), rauf (up), runter (down), rüber (over to the other side). These words often go together with a verb: reinkommen (come in), rausgehen (go out), raufgehen (go up), runterfallen (fall down), rübergehen (go over). Kommen Sie doch rein! Fallen Sie nicht runter!',
          'Как назвать направление: Wo? hier (здесь), da, dort (там). Wohin? hierhin (сюда), dahin, dorthin (туда). Stellen Sie die Leiter bitte dahin. В разговорной речи: rein (внутрь), raus (наружу), rauf (наверх), runter (вниз), rüber (на другую сторону). Эти слова часто стоят вместе с глаголом: reinkommen (войти), rausgehen (выйти), raufgehen (подняться), runterfallen (упасть вниз), rübergehen (перейти на другую сторону). Kommen Sie doch rein! Fallen Sie nicht runter!',
          'Як назвати напрямок: Wo? hier (тут), da, dort (там). Wohin? hierhin (сюди), dahin, dorthin (туди). Stellen Sie die Leiter bitte dahin. У розмовній мові: rein (усередину), raus (назовні), rauf (нагору), runter (униз), rüber (на інший бік). Ці слова часто стоять разом із дієсловом: reinkommen (увійти), rausgehen (вийти), raufgehen (піднятися), runterfallen (упасти вниз), rübergehen (перейти на інший бік). Kommen Sie doch rein! Fallen Sie nicht runter!',
          'Yön bildirmek: Wo? hier (burada), da, dort (orada). Wohin? hierhin (buraya), dahin, dorthin (oraya). Stellen Sie die Leiter bitte dahin. Konuşma dilinde: rein (içeri), raus (dışarı), rauf (yukarı), runter (aşağı), rüber (karşı tarafa). Bu kelimeler çoğu zaman bir fiille birlikte kullanılır: reinkommen (içeri gelmek), rausgehen (dışarı çıkmak), raufgehen (yukarı çıkmak), runterfallen (aşağı düşmek), rübergehen (karşıya geçmek). Kommen Sie doch rein! Fallen Sie nicht runter!',
        ],
        hint: ['Wo? → hier, da, dort. Wohin? → hierhin, dahin, dorthin.', 'Where? → hier, da, dort. Where to? → hierhin, dahin, dorthin.', 'Wo? (где?) → hier, da, dort. Wohin? (куда?) → hierhin, dahin, dorthin.', 'Wo? (де?) → hier, da, dort. Wohin? (куди?) → hierhin, dahin, dorthin.', 'Wo? (nerede?) → hier, da, dort. Wohin? (nereye?) → hierhin, dahin, dorthin.'],
        hints: {
          short: ['rein = nach innen, raus = nach draußen, rauf = nach oben, runter = nach unten, rüber = auf die andere Seite.', 'rein = inside, raus = outside, rauf = up, runter = down, rüber = to the other side.', 'rein = внутрь, raus = наружу, rauf = наверх, runter = вниз, rüber = на другую сторону.', 'rein = усередину, raus = назовні, rauf = нагору, runter = униз, rüber = на інший бік.', 'rein = içeri, raus = dışarı, rauf = yukarı, runter = aşağı, rüber = karşı tarafa.'],
        },
      },
      ex: [
        mc('G3', 'dorthin', I.choose, 'Wohin kommt die Leiter? – Stellen Sie sie bitte …', ['dorthin.', 'dort.', 'hier.'],
          ['Where does the ladder go? – Please put it over there.', 'Куда поставить лестницу? – Поставьте её, пожалуйста, вон туда.', 'Куди поставити драбину? – Поставте її, будь ласка, он туди.', 'Merdiven nereye konacak? – Lütfen onu oraya koyun.']),
        mc('G3', 'rein', I.situation, 'Es klingelt. Du öffnest die Tür und sagst zu deiner Nachbarin:', ['Kommen Sie doch rein!', 'Kommen Sie doch raus!', 'Fallen Sie doch runter!'],
          ['The doorbell rings. You open the door and say to your neighbour:', 'Звонок в дверь. Вы открываете и говорите соседке:', 'Дзвінок у двері. Ви відчиняєте й кажете сусідці:', 'Kapı çalıyor. Kapıyı açıp komşunuza diyorsunuz ki:'], { h: 'short' }),
        mc('G3', 'raus', I.choose, 'Der Hund ist im Haus und möchte in den Garten. Er will …', ['raus', 'rein', 'rauf'],
          ['The dog is in the house and wants to go into the garden. It wants to go …', 'Собака в доме и хочет в сад. Она хочет …', 'Собака в будинку й хоче в сад. Вона хоче …', 'Köpek evde ve bahçeye çıkmak istiyor. O … istiyor.'], { h: 'short' }),
        mc('G3', 'runter', I.situation, 'Dein Freund steht auf der Leiter. Du hast Angst und rufst:', ['Fall nicht runter!', 'Fall nicht rauf!', 'Komm nicht rein!'],
          ['Your friend is standing on the ladder. You are afraid and shout:', 'Ваш друг стоит на лестнице. Вам страшно, и вы кричите:', 'Ваш друг стоїть на драбині. Вам страшно, і ви кричите:', 'Arkadaşınız merdivenin üstünde duruyor. Korkuyorsunuz ve bağırıyorsunuz:'], { h: 'short' }),
        mc('G3', 'dort', I.choose, 'Wo ist dein Fahrrad? – Es steht …', ['dort.', 'dorthin.', 'dahin.'],
          ['Where is your bike? – It is over there.', 'Где твой велосипед? – Он стоит вон там.', 'Де твій велосипед? – Він стоїть он там.', 'Bisikletin nerede? – Orada duruyor.']),
        gap('G3', 'hierhin', I.adverb, 'Leg die Zeitung bitte ', ', auf den Tisch.', 'hierhin', ['hier', 'dort'],
          ['Please put the newspaper here, on the table.', 'Положи газету, пожалуйста, сюда, на стол.', 'Поклади газету, будь ласка, сюди, на стіл.', 'Gazeteyi lütfen buraya, masanın üstüne koy.'], 'hier / hierhin / dort'),
        gap('G3', 'rauf', I.adverb, 'Die Nachbarn wohnen im vierten Stock. Der Aufzug ist kaputt, wir müssen zu Fuß ', '.', 'rauf', ['runter', 'rein'],
          ['The neighbours live on the fourth floor. The lift is broken, we have to walk up.', 'Соседи живут на пятом этаже. Лифт сломан, нам придётся подниматься пешком.', 'Сусіди живуть на п’ятому поверсі. Ліфт зламаний, нам доведеться підійматися пішки.', 'Komşular dördüncü katta oturuyor. Asansör bozuk, yürüyerek yukarı çıkmamız gerekiyor.'], 'rauf / runter / rein', { h: 'short' }),
        gap('G3', 'rüber', I.adverb, 'Meine Freundin wohnt auf der anderen Straßenseite. Ich gehe schnell zu ihr ', '.', 'rüber', ['rauf', 'rein'],
          ['My friend lives on the other side of the street. I am quickly going over to her.', 'Моя подруга живёт на другой стороне улицы. Я быстро сбегаю к ней.', 'Моя подруга живе на іншому боці вулиці. Я швидко збігаю до неї.', 'Arkadaşım caddenin karşı tarafında oturuyor. Hemen ona geçiyorum.'], 'rüber / rauf / rein', { h: 'short' }),
        gap('G3', 'rein', I.adverb, 'Es regnet. Die Kinder kommen schnell aus dem Garten ', ' ins Haus.', 'rein', ['raus', 'runter'],
          ['It is raining. The children quickly come in from the garden.', 'Идёт дождь. Дети быстро заходят из сада в дом.', 'Іде дощ. Діти швидко заходять із саду в будинок.', 'Yağmur yağıyor. Çocuklar bahçeden hemen içeri, eve giriyor.'], 'rein / raus / runter', { h: 'short' }),
        sb('G3', 'dahin', I.request, 'Stellen / Sie / die Leiter / bitte / dahin.',
          ['Please put the ladder over there.', 'Поставьте, пожалуйста, лестницу туда.', 'Поставте, будь ласка, драбину туди.', 'Lütfen merdiveni oraya koyun.'],
          { alt: ['Stellen Sie bitte die Leiter dahin.'] }),
      ],
    },
    {
      title: 'Darf ich Sie etwas fragen?',
      t: ['May I ask you something?', 'Можно вас спросить?', 'Можна вас запитати?', 'Size bir şey sorabilir miyim?'],
      card: {
        id: 'p2_fragen',
        rule: 'Jemanden höflich ansprechen und um Hilfe bitten: Entschuldigung, störe ich? Darf ich Sie etwas fragen? Ich habe ein Problem. Ich habe eine Frage. Ich habe eine Bitte. Sagen Sie mal, … Mit wem kann ich denn da sprechen? Seien Sie bitte so nett und helfen Sie mir.',
        examples: ['Entschuldigung, störe ich?', 'Darf ich Sie etwas fragen?', 'Mit wem kann ich da sprechen?'],
        highlight: null,
        t: [
          'Addressing someone politely and asking for help: Entschuldigung, störe ich? (Excuse me, am I disturbing you?) Darf ich Sie etwas fragen? (May I ask you something?) Ich habe ein Problem. Ich habe eine Frage. Ich habe eine Bitte (a request). Sagen Sie mal, … (Tell me, …) Mit wem kann ich denn da sprechen? (Who can I talk to about that?) Seien Sie bitte so nett und helfen Sie mir. (Would you be so kind as to help me.)',
          'Как вежливо обратиться и попросить о помощи: Entschuldigung, störe ich? (Извините, я не помешаю?) Darf ich Sie etwas fragen? (Можно вас спросить?) Ich habe ein Problem. Ich habe eine Frage. Ich habe eine Bitte (просьба). Sagen Sie mal, … (Скажите, …) Mit wem kann ich denn da sprechen? (С кем я могу об этом поговорить?) Seien Sie bitte so nett und helfen Sie mir. (Будьте так добры, помогите мне.)',
          'Як ввічливо звернутися й попросити про допомогу: Entschuldigung, störe ich? (Вибачте, я не заважаю?) Darf ich Sie etwas fragen? (Можна вас запитати?) Ich habe ein Problem. Ich habe eine Frage. Ich habe eine Bitte (прохання). Sagen Sie mal, … (Скажіть, …) Mit wem kann ich denn da sprechen? (З ким я можу про це поговорити?) Seien Sie bitte so nett und helfen Sie mir. (Будьте такі ласкаві, допоможіть мені.)',
          'Birine kibarca seslenmek ve yardım istemek: Entschuldigung, störe ich? (Affedersiniz, rahatsız ediyor muyum?) Darf ich Sie etwas fragen? (Size bir şey sorabilir miyim?) Ich habe ein Problem. Ich habe eine Frage. Ich habe eine Bitte (bir ricam var). Sagen Sie mal, … (Söyler misiniz, …) Mit wem kann ich denn da sprechen? (Bu konuda kiminle konuşabilirim?) Seien Sie bitte so nett und helfen Sie mir. (Lütfen bana yardım eder misiniz.)',
        ],
        hint: ['Zuerst höflich ansprechen (Entschuldigung, störe ich?), dann das Problem nennen.', 'First address the person politely (Entschuldigung, störe ich?), then say what the problem is.', 'Сначала вежливо обратитесь (Entschuldigung, störe ich?), затем назовите проблему.', 'Спочатку ввічливо зверніться (Entschuldigung, störe ich?), потім назвіть проблему.', 'Önce kibarca seslenin (Entschuldigung, störe ich?), sonra sorunu söyleyin.'],
      },
      ex: [
        mc('K1', 'ansprechen', I.situation, 'Du klopfst an die Tür vom Hausmeister. Er telefoniert gerade. Was sagst du zuerst?', ['Entschuldigung, störe ich?', 'Kein Problem.', 'Das mache ich gern.'],
          ['You knock on the caretaker’s door. He is on the phone. What do you say first?', 'Вы стучите в дверь к завхозу. Он как раз говорит по телефону. Что вы скажете сначала?', 'Ви стукаєте у двері до завгоспа. Він саме говорить телефоном. Що ви скажете спочатку?', 'Bina görevlisinin kapısını çalıyorsunuz. O sırada telefonda konuşuyor. Önce ne dersiniz?']),
        mc('K1', 'ansprechen', I.situation, 'Du brauchst Hilfe und sprichst eine Nachbarin an:', ['Darf ich Sie etwas fragen?', 'Da haben Sie recht.', 'Das war keine Absicht.'],
          ['You need help and speak to a neighbour:', 'Вам нужна помощь, и вы обращаетесь к соседке:', 'Вам потрібна допомога, і ви звертаєтеся до сусідки:', 'Yardıma ihtiyacınız var ve bir komşunuza sesleniyorsunuz:']),
        mc('K1', 'Mit wem …?', I.situation, 'Deine Heizung ist kaputt. Im Büro von der Hausverwaltung weißt du nicht, wer helfen kann. Was fragst du?', ['Mit wem kann ich denn da sprechen?', 'Wie spät ist es denn?', 'Darf ich hier parken?'],
          ['Your heating is broken. At the property management office you do not know who can help. What do you ask?', 'У вас сломалось отопление. В офисе управляющей компании вы не знаете, кто может помочь. Что вы спросите?', 'У вас зламалося опалення. В офісі керуючої компанії ви не знаєте, хто може допомогти. Що ви запитаєте?', 'Kaloriferiniz bozuk. Bina yönetiminin ofisinde kimin yardım edebileceğini bilmiyorsunuz. Ne sorarsınız?']),
        mc('K1', 'höflich bitten', I.choose, 'Was ist höflich?', ['Seien Sie bitte so nett und halten Sie die Tür auf.', 'Tür auf!', 'Sie müssen die Tür aufhalten.'],
          ['What is polite?', 'Что звучит вежливо?', 'Що звучить ввічливо?', 'Hangisi kibar?']),
        gap('K1', 'Darf ich …?', I.modal, 'Entschuldigung, ', ' ich Sie etwas fragen?', 'darf', ['dürfen', 'darfst'],
          ['Excuse me, may I ask you something?', 'Извините, можно вас спросить?', 'Вибачте, можна вас запитати?', 'Affedersiniz, size bir şey sorabilir miyim?'], 'dürfen'),
        gap('K1', 'eine Bitte', I.word, 'Ich habe eine ', ': Können Sie mir bitte helfen?', ['Bitte', 'Frage'], ['Antwort', 'Miete'],
          ['I have a request: could you help me, please?', 'У меня просьба: не могли бы вы мне помочь?', 'У мене прохання: чи не могли б ви мені допомогти?', 'Bir ricam var: Bana yardım edebilir misiniz lütfen?'],
          ['request', 'просьба', 'прохання', 'rica']),
        gap('K1', 'stören', I.verb, 'Guten Tag, ', ' ich? Ich habe nur eine kurze Frage.', 'störe', ['stört', 'stören'],
          ['Hello, am I disturbing you? I just have a quick question.', 'Здравствуйте, я не помешаю? У меня только один короткий вопрос.', 'Добрий день, я не заважаю? У мене лише одне коротке запитання.', 'İyi günler, rahatsız ediyor muyum? Sadece kısa bir sorum var.'], 'stören'),
        gap('K1', 'so nett', I.word, 'Seien Sie bitte so ', ' und öffnen Sie mir die Tür.', 'nett', ['gern', 'leider'],
          ['Would you be so kind as to open the door for me.', 'Будьте так добры, откройте мне дверь.', 'Будьте такі ласкаві, відчиніть мені двері.', 'Lütfen bana kapıyı açar mısınız, çok naziksiniz.'],
          ['kind', 'любезный', 'люб’язний', 'nazik']),
        sb('K1', 'Darf ich …?', I.question, 'Darf / ich / Sie / etwas / fragen?',
          ['May I ask you something?', 'Можно вас спросить?', 'Можна вас запитати?', 'Size bir şey sorabilir miyim?']),
      ],
    },
    {
      title: 'Könnten Sie bitte …?',
      t: ['Could you please …?', 'Не могли бы вы …?', 'Чи не могли б ви …?', 'Lütfen … yapabilir misiniz?'],
      card: {
        id: 'p2_bitten',
        rule: 'Nachbarn um einen Gefallen bitten: Zuerst nennst du den Grund: Ich bin nächste Woche im Urlaub. Ich habe morgen Frühschicht. Dann kommt die Bitte. Mit du: Kannst du bitte meinen Briefkasten leeren? Könntest du die Pflanzen gießen? Mit Sie: Könnten Sie bitte ein Paket für mich annehmen? Würden Sie den Techniker in meine Wohnung lassen? Könnten und würden sind besonders höflich. Der Infinitiv steht am Ende.',
        examples: ['Könnten Sie bitte meine Blumen gießen?', 'Kannst du morgen meinen Briefkasten leeren?', 'Würden Sie mit meinem Hund spazieren gehen?'],
        highlight: 'verb',
        t: [
          'Asking neighbours for a favour: first you give the reason: Ich bin nächste Woche im Urlaub. Ich habe morgen Frühschicht (early shift). Then comes the request. With du: Kannst du bitte meinen Briefkasten leeren? (empty my letterbox) Könntest du die Pflanzen gießen? (water the plants) With Sie: Könnten Sie bitte ein Paket für mich annehmen? (accept a parcel) Würden Sie den Techniker in meine Wohnung lassen? (let the technician in) Könnten and würden are especially polite. The infinitive goes to the end.',
          'Как попросить соседей об одолжении: сначала назовите причину: Ich bin nächste Woche im Urlaub. Ich habe morgen Frühschicht (утренняя смена). Затем идёт просьба. На «ты»: Kannst du bitte meinen Briefkasten leeren? (вынуть почту) Könntest du die Pflanzen gießen? (полить растения) На «вы»: Könnten Sie bitte ein Paket für mich annehmen? (принять посылку) Würden Sie den Techniker in meine Wohnung lassen? (впустить мастера) Könnten и würden звучат особенно вежливо. Инфинитив стоит в конце.',
          'Як попросити сусідів про послугу: спочатку назвіть причину: Ich bin nächste Woche im Urlaub. Ich habe morgen Frühschicht (ранкова зміна). Потім іде прохання. На «ти»: Kannst du bitte meinen Briefkasten leeren? (вийняти пошту) Könntest du die Pflanzen gießen? (полити рослини) На «ви»: Könnten Sie bitte ein Paket für mich annehmen? (прийняти посилку) Würden Sie den Techniker in meine Wohnung lassen? (впустити майстра) Könnten і würden звучать особливо ввічливо. Інфінітив стоїть у кінці.',
          'Komşulardan bir iyilik istemek: Önce nedeni söylersiniz: Ich bin nächste Woche im Urlaub. Ich habe morgen Frühschicht (sabah vardiyası). Sonra rica gelir. du ile: Kannst du bitte meinen Briefkasten leeren? (posta kutumu boşaltmak) Könntest du die Pflanzen gießen? (çiçekleri sulamak) Sie ile: Könnten Sie bitte ein Paket für mich annehmen? (paketi teslim almak) Würden Sie den Techniker in meine Wohnung lassen? (teknisyeni içeri almak) Könnten ve würden özellikle kibardır. Mastar sonda durur.',
        ],
        hint: ['Höflich bitten: Könnten Sie …? Würden Sie …? Könntest du …? Der Infinitiv steht am Ende.', 'Asking politely: Könnten Sie …? Würden Sie …? Könntest du …? The infinitive goes to the end.', 'Вежливая просьба: Könnten Sie …? Würden Sie …? Könntest du …? Инфинитив стоит в конце.', 'Ввічливе прохання: Könnten Sie …? Würden Sie …? Könntest du …? Інфінітив стоїть у кінці.', 'Kibarca rica: Könnten Sie …? Würden Sie …? Könntest du …? Mastar sonda durur.'],
      },
      ex: [
        mc('K2', 'Pflanzen gießen', I.situation, 'Du fährst in den Urlaub. Deine Pflanzen brauchen Wasser. Was fragst du deine Nachbarin, Frau Bondar?', ['Könnten Sie bitte meine Pflanzen gießen?', 'Könnten Sie bitte meine Pflanzen kaufen?', 'Gießen Sie Ihre Pflanzen!'],
          ['You are going on holiday. Your plants need water. What do you ask your neighbour, Ms Bondar?', 'Вы уезжаете в отпуск. Вашим растениям нужна вода. О чём вы попросите соседку, госпожу Bondar?', 'Ви їдете у відпустку. Вашим рослинам потрібна вода. Про що ви попросите сусідку, пані Bondar?', 'Tatile gidiyorsunuz. Çiçeklerinizin suya ihtiyacı var. Komşunuz Bondar Hanım’a ne sorarsınız?']),
        mc('K2', 'Paket annehmen', I.situation, 'Morgen kommt ein Paket für dich, aber du bist am Vormittag nicht zu Hause. Was fragst du deinen Nachbarn?', ['Würden Sie bitte ein Paket für mich annehmen?', 'Würden Sie bitte ein Paket für mich packen?', 'Haben Sie mein Paket geöffnet?'],
          ['A parcel is coming for you tomorrow, but you are not at home in the morning. What do you ask your neighbour?', 'Завтра вам привезут посылку, но утром вас не будет дома. О чём вы попросите соседа?', 'Завтра вам привезуть посилку, але вранці вас не буде вдома. Про що ви попросите сусіда?', 'Yarın size bir paket gelecek, ama öğleden önce evde değilsiniz. Komşunuza ne sorarsınız?']),
        mc('K2', 'du oder Sie', I.choose, 'Welche Bitte passt zu „du“?', ['Kannst du bitte meinen Briefkasten leeren?', 'Könnten Sie bitte meinen Briefkasten leeren?', 'Würden Sie bitte meinen Briefkasten leeren?'],
          ['Which request goes with “du”?', 'Какая просьба подходит для обращения на «ты»?', 'Яке прохання підходить для звертання на «ти»?', 'Hangi rica “du” hitabına uyuyor?']),
        mc('K2', 'Könnten Sie …?', I.choose, 'Ich habe morgen Frühschicht. … Sie die Handwerker um acht Uhr in meine Wohnung lassen?', ['Könnten', 'Könntest', 'Kannst'],
          ['I have the early shift tomorrow. Could you let the workmen into my flat at eight o’clock?', 'Завтра у меня утренняя смена. Не могли бы вы в восемь часов впустить мастеров в мою квартиру?', 'Завтра в мене ранкова зміна. Чи не могли б ви о восьмій впустити майстрів у мою квартиру?', 'Yarın sabah vardiyasındayım. Ustaları saat sekizde daireme alabilir misiniz?']),
        gap('K2', 'Würden Sie …?', I.polite, '', ' Sie bitte mit meinem Hund spazieren gehen? Ich bin krank.', 'Würden', ['Würdest', 'Werden'],
          ['Would you please take my dog for a walk? I am ill.', 'Не могли бы вы погулять с моей собакой? Я болею.', 'Чи не могли б ви погуляти з моїм собакою? Я хворію.', 'Lütfen köpeğimi gezdirir misiniz? Hastayım.'], 'werden'),
        gap('K2', 'Briefkasten leeren', I.verb, 'Kannst du bitte meinen Briefkasten ', '? Ich bin zwei Wochen weg.', 'leeren', ['lernen', 'gießen'],
          ['Could you empty my letterbox, please? I am away for two weeks.', 'Можешь, пожалуйста, вынимать мою почту? Меня не будет две недели.', 'Можеш, будь ласка, виймати мою пошту? Мене не буде два тижні.', 'Lütfen posta kutumu boşaltır mısın? İki hafta yokum.'],
          ['empty', 'опустошать', 'спорожняти', 'boşaltmak']),
        gap('K2', 'Blumen gießen', I.verb, 'Könntest du am Wochenende meine Blumen ', '?', 'gießen', ['leeren', 'essen'],
          ['Could you water my flowers at the weekend?', 'Не мог бы ты в выходные полить мои цветы?', 'Чи не міг би ти на вихідних полити мої квіти?', 'Hafta sonu çiçeklerimi sular mısın?'],
          ['water', 'поливать', 'поливати', 'sulamak']),
        gap('K2', 'Könntest du …?', I.polite, '', ' du mir bitte deine Leiter leihen?', ['Könntest', 'Kannst'], ['Könnten', 'Könnt'],
          ['Could you lend me your ladder, please?', 'Не мог бы ты одолжить мне свою лестницу?', 'Чи не міг би ти позичити мені свою драбину?', 'Bana merdivenini ödünç verebilir misin lütfen?'], 'können'),
        sb('K2', 'Könnten Sie …?', I.question, 'Könnten / Sie / bitte / meine Pflanzen / gießen?',
          ['Could you water my plants, please?', 'Не могли бы вы полить мои растения?', 'Чи не могли б ви полити мої рослини?', 'Lütfen çiçeklerimi sulayabilir misiniz?'],
          { alt: ['Könnten Sie meine Pflanzen bitte gießen?'] }),
      ],
    },
    {
      title: 'Kein Problem!',
      t: ['No problem!', 'Без проблем!', 'Без проблем!', 'Sorun değil!'],
      card: {
        id: 'p2_reagieren',
        rule: 'Auf eine Bitte reagieren. Ja: Natürlich. Gern. Kein Problem. Das mache ich gern. Das mache ich sofort. Störe ich? – Nein, gar nicht. Kommen Sie doch rein. Was ist denn los? Nein, höflich mit Grund: Leider kann ich nicht, weil ich arbeiten muss. Tut mir leid, das geht leider nicht. Weiterhelfen: Da sprechen Sie am besten mit dem Hausmeister. Zustimmen: Da haben Sie recht.',
        examples: ['Störe ich? – Nein, gar nicht. Kommen Sie doch rein.', 'Kein Problem, das mache ich gern.', 'Leider kann ich nicht, weil ich am Samstag arbeite.'],
        highlight: null,
        t: [
          'Reacting to a request. Yes: Natürlich (of course). Gern (gladly). Kein Problem. Das mache ich gern. Das mache ich sofort (right away). Störe ich? – Nein, gar nicht (not at all). Kommen Sie doch rein. Was ist denn los? (What is the matter?) No, politely with a reason: Leider kann ich nicht, weil ich arbeiten muss. Tut mir leid, das geht leider nicht. Passing someone on: Da sprechen Sie am besten mit dem Hausmeister. (You had best talk to the caretaker.) Agreeing: Da haben Sie recht. (You are right there.)',
          'Как ответить на просьбу. Да: Natürlich (конечно). Gern (с удовольствием). Kein Problem. Das mache ich gern. Das mache ich sofort (сейчас же). Störe ich? – Nein, gar nicht (совсем нет). Kommen Sie doch rein. Was ist denn los? (Что случилось?) Нет, вежливо и с причиной: Leider kann ich nicht, weil ich arbeiten muss. Tut mir leid, das geht leider nicht. Направить к другому: Da sprechen Sie am besten mit dem Hausmeister. (Об этом лучше поговорить с завхозом.) Согласиться: Da haben Sie recht. (Тут вы правы.)',
          'Як відповісти на прохання. Так: Natürlich (звичайно). Gern (охоче). Kein Problem. Das mache ich gern. Das mache ich sofort (зараз же). Störe ich? – Nein, gar nicht (зовсім ні). Kommen Sie doch rein. Was ist denn los? (Що сталося?) Ні, ввічливо й з причиною: Leider kann ich nicht, weil ich arbeiten muss. Tut mir leid, das geht leider nicht. Скерувати до іншого: Da sprechen Sie am besten mit dem Hausmeister. (Про це краще поговорити із завгоспом.) Погодитися: Da haben Sie recht. (Тут ви маєте рацію.)',
          'Bir ricaya karşılık vermek. Evet: Natürlich (tabii ki). Gern (memnuniyetle). Kein Problem. Das mache ich gern. Das mache ich sofort (hemen). Störe ich? – Nein, gar nicht (hayır, hiç). Kommen Sie doch rein. Was ist denn los? (Ne oldu?) Hayır, kibarca ve nedeniyle: Leider kann ich nicht, weil ich arbeiten muss. Tut mir leid, das geht leider nicht. Yönlendirmek: Da sprechen Sie am besten mit dem Hausmeister. (Bunu en iyisi bina görevlisiyle konuşun.) Katılmak: Da haben Sie recht. (Bu konuda haklısınız.)',
        ],
        hint: ['Ja → Natürlich. Gern. Kein Problem. Nein → Leider …, weil … (höflich mit Grund).', 'Yes → Natürlich. Gern. Kein Problem. No → Leider …, weil … (polite, with a reason).', 'Да → Natürlich. Gern. Kein Problem. Нет → Leider …, weil … (вежливо, с причиной).', 'Так → Natürlich. Gern. Kein Problem. Ні → Leider …, weil … (ввічливо, з причиною).', 'Evet → Natürlich. Gern. Kein Problem. Hayır → Leider …, weil … (kibarca, nedeniyle).'],
      },
      ex: [
        mc('K3', 'Störe ich?', I.react, '„Entschuldigung, störe ich?“', ['Nein, gar nicht. Kommen Sie doch rein.', 'Ja, gern. Auf Wiedersehen.', 'Das mache ich sofort.'],
          ['“Excuse me, am I disturbing you?”', '«Извините, я не помешаю?»', '«Вибачте, я не заважаю?»', '“Affedersiniz, rahatsız ediyor muyum?”']),
        mc('K3', 'zusagen', I.react, '„Könnten Sie bitte meine Blumen gießen?“ – Du hilfst gern.', ['Natürlich, das mache ich gern.', 'Leider kann ich nicht.', 'Was ist denn los?'],
          ['“Could you water my flowers, please?” – You are happy to help.', '«Не могли бы вы полить мои цветы?» – Вы охотно поможете.', '«Чи не могли б ви полити мої квіти?» – Ви охоче допоможете.', '“Lütfen çiçeklerimi sulayabilir misiniz?” – Seve seve yardım edersiniz.']),
        mc('K3', 'absagen', I.react, '„Kannst du morgen meinen Briefkasten leeren?“ – Du bist morgen nicht da.', ['Leider kann ich nicht, weil ich morgen wegfahre.', 'Kein Problem, das mache ich sofort.', 'Nein, gar nicht.'],
          ['“Can you empty my letterbox tomorrow?” – You are away tomorrow.', '«Можешь завтра вынуть мою почту?» – Завтра вас не будет.', '«Можеш завтра вийняти мою пошту?» – Завтра вас не буде.', '“Yarın posta kutumu boşaltabilir misin?” – Yarın orada değilsiniz.']),
        mc('K3', 'zustimmen', I.react, '„Die Musik im dritten Stock ist immer so laut!“ – Du findest das auch.', ['Da haben Sie recht.', 'Das mache ich gern.', 'Kommen Sie doch rein.'],
          ['“The music on the third floor is always so loud!” – You think so too.', '«Музыка на четвёртом этаже всегда такая громкая!» – Вы тоже так считаете.', '«Музика на четвертому поверсі завжди така гучна!» – Ви теж так вважаєте.', '“Üçüncü kattaki müzik hep çok yüksek!” – Siz de öyle düşünüyorsunuz.']),
        mc('K3', 'weiterhelfen', I.react, '„Mein Fenster schließt nicht richtig. Können Sie das reparieren?“ – Du bist ein Nachbar und kannst das nicht.', ['Da sprechen Sie am besten mit dem Hausmeister.', 'Das mache ich sofort.', 'Nein, gar nicht.'],
          ['“My window does not close properly. Can you repair it?” – You are a neighbour and cannot do that.', '«Моё окно плохо закрывается. Вы можете его починить?» – Вы сосед и не умеете этого.', '«Моє вікно погано зачиняється. Ви можете його полагодити?» – Ви сусід і не вмієте цього.', '“Pencerem düzgün kapanmıyor. Tamir edebilir misiniz?” – Siz bir komşusunuz ve bunu yapamazsınız.']),
        gap('K3', 'Kein Problem', I.word, 'Kein ', '! Ich helfe Ihnen gern.', 'Problem', ['Glück', 'Dank'],
          ['No problem! I am happy to help you.', 'Без проблем! Я с удовольствием вам помогу.', 'Без проблем! Я охоче вам допоможу.', 'Sorun değil! Size seve seve yardım ederim.'],
          ['problem, trouble', 'проблема', 'проблема', 'sorun']),
        gap('K3', 'Was ist los?', I.word, 'Du siehst traurig aus. Was ist denn ', '?', 'los', ['weg', 'da'],
          ['You look sad. What is the matter?', 'Ты выглядишь грустным. Что случилось?', 'Ти виглядаєш сумним. Що сталося?', 'Üzgün görünüyorsun. Ne oldu?'], 'los / weg / da'),
        gap('K3', 'absagen mit Grund', I.conjunction, 'Leider kann ich Ihnen nicht helfen, ', ' ich gleich zur Arbeit muss.', 'weil', ['aber', 'und'],
          ['Unfortunately I cannot help you because I have to go to work in a moment.', 'К сожалению, я не могу вам помочь, потому что мне сейчас нужно на работу.', 'На жаль, я не можу вам допомогти, тому що мені зараз треба на роботу.', 'Maalesef size yardım edemiyorum, çünkü birazdan işe gitmem gerekiyor.'], 'weil / aber / und'),
        gap('K3', 'zusagen', I.verb, 'Das ', ' ich gern. Wann fahren Sie in den Urlaub?', 'mache', ['macht', 'machen'],
          ['I am happy to do that. When are you going on holiday?', 'Я с удовольствием это сделаю. Когда вы уезжаете в отпуск?', 'Я охоче це зроблю. Коли ви їдете у відпустку?', 'Bunu seve seve yaparım. Ne zaman tatile gidiyorsunuz?'], 'machen'),
        sb('K3', 'zusagen', I.order, 'Das / mache / ich / sofort.',
          ['I will do that right away.', 'Я сейчас же это сделаю.', 'Я зараз же це зроблю.', 'Bunu hemen yapıyorum.'],
          { alt: ['Ich mache das sofort.'] }),
      ],
    },
    {
      title: 'Danke! – Entschuldigung!',
      t: ['Thank you! – Sorry!', 'Спасибо! – Извините!', 'Дякую! – Вибачте!', 'Teşekkürler! – Özür dilerim!'],
      card: {
        id: 'p2_dank',
        rule: 'Danken: Vielen Dank für Ihre Hilfe. Danke für Ihr Verständnis. Das ist wirklich nett von Ihnen. Das wäre wirklich nett. Nach danke für steht der Akkusativ: für die Hilfe, für den Tipp, für das Paket. In Mitteilungen: Wir hoffen auf Ihr Verständnis. Ich hoffe, das ist in Ordnung für Sie. Sich entschuldigen: Oh, Entschuldigung! Tut mir leid. Das war keine Absicht. Das habe ich nicht gewusst. Antwort: Kein Problem. Das macht nichts. Schon gut.',
        examples: ['Vielen Dank für Ihre Hilfe!', 'Tut mir leid, das war keine Absicht.', 'Das habe ich nicht gewusst. – Das macht nichts.'],
        highlight: null,
        t: [
          'Saying thank you: Vielen Dank für Ihre Hilfe. Danke für Ihr Verständnis (understanding). Das ist wirklich nett von Ihnen. Das wäre wirklich nett. (That would be really kind.) After danke für comes the accusative: für die Hilfe, für den Tipp, für das Paket. In notices: Wir hoffen auf Ihr Verständnis. Ich hoffe, das ist in Ordnung für Sie. Apologising: Oh, Entschuldigung! Tut mir leid. Das war keine Absicht. (I did not mean to.) Das habe ich nicht gewusst. (I did not know that.) Answer: Kein Problem. Das macht nichts. (It does not matter.) Schon gut.',
          'Как поблагодарить: Vielen Dank für Ihre Hilfe. Danke für Ihr Verständnis (понимание). Das ist wirklich nett von Ihnen. Das wäre wirklich nett. (Это было бы очень мило.) После danke für стоит Akkusativ: für die Hilfe, für den Tipp, für das Paket. В объявлениях: Wir hoffen auf Ihr Verständnis. Ich hoffe, das ist in Ordnung für Sie. Как извиниться: Oh, Entschuldigung! Tut mir leid. Das war keine Absicht. (Я не нарочно.) Das habe ich nicht gewusst. (Я этого не знал.) Ответ: Kein Problem. Das macht nichts. (Ничего страшного.) Schon gut.',
          'Як подякувати: Vielen Dank für Ihre Hilfe. Danke für Ihr Verständnis (розуміння). Das ist wirklich nett von Ihnen. Das wäre wirklich nett. (Це було б дуже мило.) Після danke für стоїть Akkusativ: für die Hilfe, für den Tipp, für das Paket. В оголошеннях: Wir hoffen auf Ihr Verständnis. Ich hoffe, das ist in Ordnung für Sie. Як вибачитися: Oh, Entschuldigung! Tut mir leid. Das war keine Absicht. (Я не навмисно.) Das habe ich nicht gewusst. (Я цього не знав.) Відповідь: Kein Problem. Das macht nichts. (Нічого страшного.) Schon gut.',
          'Teşekkür etmek: Vielen Dank für Ihre Hilfe. Danke für Ihr Verständnis (anlayış). Das ist wirklich nett von Ihnen. Das wäre wirklich nett. (Bu gerçekten çok iyi olurdu.) danke für’den sonra Akkusativ gelir: für die Hilfe, für den Tipp, für das Paket. Duyurularda: Wir hoffen auf Ihr Verständnis. Ich hoffe, das ist in Ordnung für Sie. Özür dilemek: Oh, Entschuldigung! Tut mir leid. Das war keine Absicht. (İsteyerek olmadı.) Das habe ich nicht gewusst. (Bunu bilmiyordum.) Cevap: Kein Problem. Das macht nichts. (Önemli değil.) Schon gut.',
        ],
        hint: ['Danken: Vielen Dank für … Sich entschuldigen: Tut mir leid. Das war keine Absicht.', 'Thanking: Vielen Dank für … Apologising: Tut mir leid. Das war keine Absicht.', 'Благодарность: Vielen Dank für … Извинение: Tut mir leid. Das war keine Absicht.', 'Подяка: Vielen Dank für … Вибачення: Tut mir leid. Das war keine Absicht.', 'Teşekkür: Vielen Dank für … Özür: Tut mir leid. Das war keine Absicht.'],
      },
      ex: [
        mc('K4', 'danken', I.situation, 'Deine Nachbarin hat zwei Wochen deine Blumen gegossen. Was sagst du?', ['Vielen Dank für Ihre Hilfe!', 'Das war keine Absicht.', 'Das habe ich nicht gewusst.'],
          ['Your neighbour watered your flowers for two weeks. What do you say?', 'Соседка две недели поливала ваши цветы. Что вы скажете?', 'Сусідка два тижні поливала ваші квіти. Що ви скажете?', 'Komşunuz iki hafta boyunca çiçeklerinizi suladı. Ne dersiniz?']),
        mc('K5', 'keine Absicht', I.situation, 'Du hast im Treppenhaus das Fahrrad von Herrn Weber umgeworfen. Was sagst du?', ['Oh, Entschuldigung! Das war keine Absicht.', 'Vielen Dank für Ihr Verständnis.', 'Das mache ich gern.'],
          ['You knocked over Mr Weber’s bike in the stairwell. What do you say?', 'Вы уронили на лестнице велосипед господина Weber. Что вы скажете?', 'Ви впустили на сходах велосипед пана Weber. Що ви скажете?', 'Merdivende Weber Bey’in bisikletini devirdiniz. Ne dersiniz?']),
        mc('K5', 'nicht gewusst', I.situation, 'Der Hausmeister sagt: „Hier dürfen Sie nicht parken.“ Du hast das Schild nicht gesehen.', ['Tut mir leid, das habe ich nicht gewusst.', 'Das ist wirklich nett von Ihnen.', 'Natürlich, gern.'],
          ['The caretaker says: “You are not allowed to park here.” You did not see the sign.', 'Завхоз говорит: «Здесь нельзя парковаться». Вы не видели знак.', 'Завгосп каже: «Тут не можна паркуватися». Ви не бачили знак.', 'Bina görevlisi diyor ki: “Buraya park edemezsiniz.” Tabelayı görmediniz.']),
        mc('K4', 'Das wäre nett', I.react, '„Ich kann Ihr Paket morgen annehmen.“', ['Das wäre wirklich nett.', 'Das war keine Absicht.', 'Tut mir leid.'],
          ['“I can accept your parcel tomorrow.”', '«Я могу завтра принять вашу посылку».', '«Я можу завтра прийняти вашу посилку».', '“Yarın paketinizi teslim alabilirim.”']),
        mc('K5', 'auf eine Entschuldigung antworten', I.react, '„Entschuldigung, ich habe Ihre Zeitung genommen. Das war keine Absicht.“', ['Kein Problem, das macht nichts.', 'Vielen Dank für die Hilfe.', 'Das wäre nett.'],
          ['“Sorry, I took your newspaper. I did not mean to.”', '«Извините, я взял вашу газету. Я не нарочно».', '«Вибачте, я взяв вашу газету. Я не навмисно».', '“Özür dilerim, gazetenizi almışım. İsteyerek olmadı.”']),
        gap('K4', 'danke für', I.prep, 'Vielen Dank ', ' Ihre Hilfe!', 'für', ['auf', 'mit'],
          ['Thank you very much for your help!', 'Большое спасибо за вашу помощь!', 'Щиро дякую за вашу допомогу!', 'Yardımınız için çok teşekkürler!'], 'für / auf / mit'),
        gap('K4', 'hoffen auf', I.prep, 'Am Samstag feiern wir im Hof. Wir hoffen ', ' Ihr Verständnis.', 'auf', ['für', 'mit'],
          ['On Saturday we are having a party in the courtyard. We hope for your understanding.', 'В субботу мы празднуем во дворе. Надеемся на ваше понимание.', 'У суботу ми святкуємо у дворі. Сподіваємося на ваше розуміння.', 'Cumartesi günü avluda kutlama yapıyoruz. Anlayışınızı rica ederiz.'], 'auf / für / mit'),
        gap('K5', 'Tut mir leid', I.word, 'Tut mir ', '! Ich habe Ihren Brief geöffnet.', 'leid', ['gern', 'weh'],
          ['I am sorry! I opened your letter.', 'Мне очень жаль! Я открыл ваше письмо.', 'Мені дуже шкода! Я відкрив ваш лист.', 'Özür dilerim! Mektubunuzu açmışım.'], 'leid / gern / weh'),
        gap('K5', 'keine Absicht', I.word, 'Entschuldigung, das war keine ', '.', 'Absicht', ['Ahnung', 'Hilfe'],
          ['Sorry, I did not mean to.', 'Извините, я не нарочно.', 'Вибачте, я не навмисно.', 'Özür dilerim, isteyerek olmadı.'],
          ['intention', 'умысел, намерение', 'намір', 'kasıt']),
        sb('K4', 'danken', I.order, 'Vielen Dank / für / Ihr / Verständnis.',
          ['Thank you very much for your understanding.', 'Большое спасибо за ваше понимание.', 'Щиро дякую за ваше розуміння.', 'Anlayışınız için çok teşekkürler.']),
      ],
    },
    {
      title: 'Sehr geehrte Frau …',
      t: ['Dear Ms …', 'Уважаемая госпожа …', 'Шановна пані …', 'Sayın …'],
      card: {
        id: 'p2_brief',
        rule: 'Anrede und Gruß im Brief. Formell, kein Name bekannt: Sehr geehrte Damen und Herren, … Formell mit Namen: Sehr geehrte Frau Kaya, … Sehr geehrter Herr Weber, … Gruß: Mit freundlichen Grüßen. An Nachbarn oder Kollegen: Hallo Frau Kaya, … Liebe Nachbarn, … Gruß: Viele Grüße. Herzliche Grüße. An Freunde: Liebe Lena, … Lieber Paul, … Nach der Anrede steht ein Komma, danach schreibt man klein weiter.',
        examples: ['Sehr geehrter Herr Weber, …', 'Liebe Nachbarn, am Samstag feiere ich Geburtstag.', 'Mit freundlichen Grüßen'],
        highlight: null,
        t: [
          'Greeting and closing in a letter. Formal, no name known: Sehr geehrte Damen und Herren, … (Dear Sir or Madam) Formal with a name: Sehr geehrte Frau Kaya, … Sehr geehrter Herr Weber, … Closing: Mit freundlichen Grüßen (Yours sincerely). To neighbours or colleagues: Hallo Frau Kaya, … Liebe Nachbarn, … Closing: Viele Grüße. Herzliche Grüße. To friends: Liebe Lena, … Lieber Paul, … After the greeting there is a comma, and the text continues with a small letter.',
          'Обращение и прощание в письме. Официально, имя неизвестно: Sehr geehrte Damen und Herren, … (Уважаемые дамы и господа) Официально с именем: Sehr geehrte Frau Kaya, … Sehr geehrter Herr Weber, … Прощание: Mit freundlichen Grüßen (С уважением). Соседям или коллегам: Hallo Frau Kaya, … Liebe Nachbarn, … Прощание: Viele Grüße. Herzliche Grüße. Друзьям: Liebe Lena, … Lieber Paul, … После обращения ставится запятая, дальше пишут с маленькой буквы.',
          'Звертання і прощання в листі. Офіційно, ім’я невідоме: Sehr geehrte Damen und Herren, … (Шановні пані та панове) Офіційно з іменем: Sehr geehrte Frau Kaya, … Sehr geehrter Herr Weber, … Прощання: Mit freundlichen Grüßen (З повагою). Сусідам або колегам: Hallo Frau Kaya, … Liebe Nachbarn, … Прощання: Viele Grüße. Herzliche Grüße. Друзям: Liebe Lena, … Lieber Paul, … Після звертання ставиться кома, далі пишуть із малої літери.',
          'Mektupta hitap ve kapanış. Resmî, isim bilinmiyor: Sehr geehrte Damen und Herren, … (Sayın Bayanlar ve Baylar) Resmî ve isimle: Sehr geehrte Frau Kaya, … Sehr geehrter Herr Weber, … Kapanış: Mit freundlichen Grüßen (Saygılarımla). Komşulara ya da iş arkadaşlarına: Hallo Frau Kaya, … Liebe Nachbarn, … Kapanış: Viele Grüße. Herzliche Grüße. Arkadaşlara: Liebe Lena, … Lieber Paul, … Hitaptan sonra virgül konur, ardından küçük harfle devam edilir.',
        ],
        hint: ['Frau → Sehr geehrte / Liebe. Herr → Sehr geehrter / Lieber. Formeller Gruß: Mit freundlichen Grüßen.', 'Frau → Sehr geehrte / Liebe. Herr → Sehr geehrter / Lieber. Formal closing: Mit freundlichen Grüßen.', 'Frau → Sehr geehrte / Liebe. Herr → Sehr geehrter / Lieber. Официальное прощание: Mit freundlichen Grüßen.', 'Frau → Sehr geehrte / Liebe. Herr → Sehr geehrter / Lieber. Офіційне прощання: Mit freundlichen Grüßen.', 'Frau → Sehr geehrte / Liebe. Herr → Sehr geehrter / Lieber. Resmî kapanış: Mit freundlichen Grüßen.'],
      },
      ex: [
        mc('K6', 'formelle Anrede', I.situation, 'Du schreibst an die Hausverwaltung. Du kennst keinen Namen. Wie beginnst du?', ['Sehr geehrte Damen und Herren,', 'Liebe Hausverwaltung, hallo!', 'Hallo Leute,'],
          ['You are writing to the property management. You do not know a name. How do you begin?', 'Вы пишете в управляющую компанию. Имени вы не знаете. Как вы начнёте?', 'Ви пишете до керуючої компанії. Імені ви не знаєте. Як ви почнете?', 'Bina yönetimine yazıyorsunuz. Bir isim bilmiyorsunuz. Nasıl başlarsınız?']),
        mc('K6', 'Herr', I.situation, 'Du schreibst einen Brief an deinen Vermieter, Herrn Lindner. Wie beginnst du?', ['Sehr geehrter Herr Lindner,', 'Sehr geehrte Herr Lindner,', 'Lieber Lindner,'],
          ['You are writing a letter to your landlord, Mr Lindner. How do you begin?', 'Вы пишете письмо своему арендодателю, господину Lindner. Как вы начнёте?', 'Ви пишете листа своєму орендодавцю, пану Lindner. Як ви почнете?', 'Ev sahibiniz Lindner Bey’e bir mektup yazıyorsunuz. Nasıl başlarsınız?']),
        mc('K6', 'formeller Gruß', I.choose, 'Wie endet ein formeller Brief?', ['Mit freundlichen Grüßen', 'Tschüss und bis bald', 'Viele Küsse'],
          ['How does a formal letter end?', 'Как заканчивается официальное письмо?', 'Як закінчується офіційний лист?', 'Resmî bir mektup nasıl biter?']),
        mc('K6', 'Nachbarn', I.situation, 'Du schreibst einen Zettel für alle Nachbarn im Haus. Was passt?', ['Liebe Nachbarn,', 'Sehr geehrter Herr,', 'Lieber Paul,'],
          ['You are writing a note for all the neighbours in the building. What fits?', 'Вы пишете записку для всех соседей в доме. Что подходит?', 'Ви пишете записку для всіх сусідів у будинку. Що підходить?', 'Binadaki bütün komşulara bir not yazıyorsunuz. Hangisi uygun?']),
        mc('K6', 'Anrede und Gruß', I.choose, 'Welche Anrede passt zum Gruß „Mit freundlichen Grüßen“?', ['Sehr geehrte Frau Weber,', 'Hallo Tom,', 'Liebe Oma,'],
          ['Which greeting goes with the closing “Mit freundlichen Grüßen”?', 'Какое обращение подходит к прощанию «Mit freundlichen Grüßen»?', 'Яке звертання підходить до прощання «Mit freundlichen Grüßen»?', '“Mit freundlichen Grüßen” kapanışına hangi hitap uyar?']),
        gap('K6', 'Frau', I.ending, 'Sehr ', ' Frau Rojas, vielen Dank für Ihren Brief.', 'geehrte', ['geehrter', 'geehrten'],
          ['Dear Ms Rojas, thank you very much for your letter.', 'Уважаемая госпожа Rojas, большое спасибо за ваше письмо.', 'Шановна пані Rojas, щиро дякую за вашого листа.', 'Sayın Rojas, mektubunuz için çok teşekkür ederim.'], 'geehrt-'),
        gap('K6', 'Lieber', I.ending, '', ' Paul, wie geht es dir?', 'Lieber', ['Liebe', 'Liebes'],
          ['Dear Paul, how are you?', 'Дорогой Paul, как у тебя дела?', 'Дорогий Paul, як у тебе справи?', 'Sevgili Paul, nasılsın?'], 'lieb-'),
        gap('K6', 'formeller Gruß', I.form, 'Mit freundlichen ', ' Emre Demir', 'Grüßen', ['Grüße', 'Gruß'],
          ['Yours sincerely, Emre Demir', 'С уважением, Emre Demir', 'З повагою, Emre Demir', 'Saygılarımla, Emre Demir'], 'der Gruß'),
        gap('K6', 'Viele Grüße', I.form, 'Bis bald und viele ', ' von deiner Nachbarin Mia', 'Grüße', ['Grüßen', 'Gruß'],
          ['See you soon and best wishes from your neighbour Mia', 'До скорого и большой привет от твоей соседки Mia', 'До зустрічі й щирі вітання від твоєї сусідки Mia', 'Yakında görüşmek üzere, komşun Mia’dan selamlar'], 'der Gruß'),
      ],
    },
    {
      title: 'Aushänge lesen',
      t: ['Reading notices', 'Читаем объявления', 'Читаємо оголошення', 'Duyuruları okumak'],
      card: {
        id: 'p2_aushang',
        rule: 'Mitteilungen im Mietshaus verstehen: Ein Aushang hängt im Treppenhaus und informiert alle Hausbewohner. Wichtige Wörter: die Hausordnung (Regeln im Haus), die Ruhezeit (keine laute Musik, zum Beispiel von 22 bis 6 Uhr), den Müll trennen (Papier, Glas und Restmüll kommen in verschiedene Tonnen), das Treppenhaus reinigen (sauber machen), die Hausverwaltung (das Büro für das Haus), der Handwerker. Achte auf: Wer schreibt? Was passiert? Wann? Wo?',
        examples: ['Am Montag gibt es von 8 bis 12 Uhr kein Wasser.', 'Bitte trennen Sie den Müll!', 'Ruhezeit: 22 bis 6 Uhr.'],
        highlight: null,
        t: [
          'Understanding notices in a block of flats: der Aushang (notice) hangs in the stairwell and informs all residents. Important words: die Hausordnung (house rules), die Ruhezeit (quiet hours: no loud music, for example from 10 pm to 6 am), den Müll trennen (sort the rubbish: paper, glass and other waste go into different bins), das Treppenhaus reinigen (clean the stairwell), die Hausverwaltung (property management), der Handwerker (workman). Look for: who is writing? What is happening? When? Where?',
          'Как понимать объявления в доме: der Aushang (объявление) висит на лестнице и информирует всех жильцов. Важные слова: die Hausordnung (правила дома), die Ruhezeit (время тишины: никакой громкой музыки, например с 22 до 6 часов), den Müll trennen (сортировать мусор: бумага, стекло и остальной мусор – в разные баки), das Treppenhaus reinigen (убирать лестницу), die Hausverwaltung (управляющая компания), der Handwerker (мастер). Обратите внимание: кто пишет? Что происходит? Когда? Где?',
          'Як розуміти оголошення в будинку: der Aushang (оголошення) висить на сходах та інформує всіх мешканців. Важливі слова: die Hausordnung (правила будинку), die Ruhezeit (час тиші: жодної гучної музики, наприклад із 22 до 6 години), den Müll trennen (сортувати сміття: папір, скло й решта сміття – у різні баки), das Treppenhaus reinigen (прибирати сходи), die Hausverwaltung (керуюча компанія), der Handwerker (майстер). Зверніть увагу: хто пише? Що відбувається? Коли? Де?',
          'Apartmandaki duyuruları anlamak: der Aushang (duyuru) merdiven boşluğunda asılıdır ve bütün bina sakinlerini bilgilendirir. Önemli kelimeler: die Hausordnung (bina kuralları), die Ruhezeit (sessizlik saatleri: örneğin 22 ile 6 arası yüksek sesle müzik yok), den Müll trennen (çöpü ayırmak: kâğıt, cam ve diğer çöpler ayrı bidonlara), das Treppenhaus reinigen (merdivenleri temizlemek), die Hausverwaltung (bina yönetimi), der Handwerker (usta). Şunlara dikkat edin: Kim yazıyor? Ne oluyor? Ne zaman? Nerede?',
        ],
        hint: ['Such im Aushang: Wer schreibt? Was passiert? Wann und wo?', 'Look in the notice: who is writing? What is happening? When and where?', 'Найдите в объявлении: кто пишет? Что происходит? Когда и где?', 'Знайдіть в оголошенні: хто пише? Що відбувається? Коли й де?', 'Duyuruda arayın: Kim yazıyor? Ne oluyor? Ne zaman ve nerede?'],
      },
      ex: [
        mc('Z1', 'Was?', I.read, `${HEIZUNG} Was ist am Donnerstag?`, ['Es gibt sechs Stunden kein warmes Wasser.', 'Die Firma bringt neue Möbel.', 'Alle Hausbewohner müssen zu Hause bleiben.'],
          ['What happens on Thursday?', 'Что будет в четверг?', 'Що буде в четвер?', 'Perşembe günü ne oluyor?']),
        mc('Z1', 'Wer?', I.read, `${HEIZUNG} Wer hat den Aushang geschrieben?`, ['Die Hausverwaltung.', 'Die Firma Rohrfix.', 'Ein Nachbar.'],
          ['Who wrote the notice?', 'Кто написал объявление?', 'Хто написав оголошення?', 'Duyuruyu kim yazdı?']),
        mc('Z1', 'Warum?', I.read, `${PARTY} Warum schreibt Dilara den Zettel?`, ['Sie feiert und es ist vielleicht laut.', 'Sie sucht eine neue Wohnung.', 'Sie braucht Hilfe mit dem Müll.'],
          ['Why is Dilara writing the note?', 'Зачем Dilara пишет записку?', 'Навіщо Dilara пише записку?', 'Dilara notu neden yazıyor?']),
        mc('Z1', 'Wann?', I.read, `${PARTY} Was passiert ab 23 Uhr?`, ['Die Musik ist nicht mehr laut.', 'Die Party beginnt.', 'Alle Nachbarn müssen gehen.'],
          ['What happens from 11 pm?', 'Что происходит с 23 часов?', 'Що відбувається з 23 години?', 'Saat 23’ten itibaren ne oluyor?']),
        mc('Z1', 'Wohin?', I.read, `${ORDNUNG} Wohin kommt Papier?`, ['In die blaue Tonne.', 'In den Container an der Ecke.', 'Ins Treppenhaus.'],
          ['Where does paper go?', 'Куда выбрасывать бумагу?', 'Куди викидати папір?', 'Kâğıt nereye atılır?']),
        mc('Z1', 'Wo?', I.read, `${ORDNUNG} Wo dürfen Fahrräder stehen?`, ['Im Fahrradkeller.', 'Im Treppenhaus.', 'Neben der blauen Tonne.'],
          ['Where may bikes be kept?', 'Где можно оставлять велосипеды?', 'Де можна залишати велосипеди?', 'Bisikletler nerede durabilir?']),
        gap('Z1', 'Müll trennen', I.verb, 'Papier, Glas und Restmüll kommen nicht zusammen in eine Tonne. Man muss den Müll ', '.', 'trennen', ['gießen', 'leeren'],
          ['Paper, glass and other waste do not go into one bin together. You have to sort the rubbish.', 'Бумагу, стекло и остальной мусор нельзя бросать в один бак. Мусор нужно сортировать.', 'Папір, скло й решту сміття не можна кидати в один бак. Сміття треба сортувати.', 'Kâğıt, cam ve diğer çöpler aynı bidona atılmaz. Çöpü ayırmak gerekir.'],
          ['separate, sort', 'сортировать, разделять', 'сортувати, розділяти', 'ayırmak']),
      ],
    },
  ],
}

export default path
