import { I, gap, mc, sb } from '../shared.mjs'

const MIA = 'Mia schreibt: „Bei uns zu Hause gibt es zweimal pro Woche Fisch, immer dienstags und freitags. Fleisch essen wir selten, weil mein Mann Vegetarier ist.“'
const DILARA = 'Dilara erzählt: „In meiner Familie kocht meistens mein Vater. Unter der Woche gibt es einfache Gerichte, zum Beispiel Nudeln oder Suppe. Am Sonntag kocht er zwei Stunden und die Großeltern kommen zum Essen.“'

/** A2.1 · Pfad 3 · Essen und Trinken – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Kanne', I.choose, 'Der Tee ist fertig. Er ist in der …', ['Kanne', 'Gabel', 'Pfanne'],
      ['The tea is ready. It is in the …', 'Чай готов. Он в …', 'Чай готовий. Він у …', 'Çay hazır. Çay … içinde.']),
    mc('K1', 'selten', I.choose, 'Ich esse nur an Weihnachten Gans. Ich esse … Gans.', ['selten', 'oft', 'immer'],
      ['I only eat goose at Christmas. I … eat goose.', 'Я ем гуся только на Рождество. Я … ем гуся.', 'Я їм гуску лише на Різдво. Я … їм гуску.', 'Sadece Noel’de kaz yerim. Ben … kaz yerim.']),
    mc('K2', 'annehmen', I.react, '„Darf ich dir noch etwas Suppe geben?“', ['Ja, gern. Sie schmeckt sehr gut.', 'Nein, lass sie ruhig an.', 'Kommt gut nach Hause!'],
      ['“May I give you some more soup?”', '«Положить тебе ещё супа?»', '«Покласти тобі ще супу?»', '“Sana biraz daha çorba vereyim mi?”']),
    mc('K3', 'Platz anbieten', I.react, '„Entschuldigung, ist hier noch frei?“', ['Ja, sicher. Setzen Sie sich doch.', 'Ich nehme den Fisch.', 'Zusammen, bitte.'],
      ['“Excuse me, is this seat free?”', '«Извините, здесь свободно?»', '«Вибачте, тут вільно?»', '“Affedersiniz, burası boş mu?”']),
    mc('K4', 'höflich reklamieren', I.situation, 'Dein Kaffee ist kalt. Was sagst du zur Kellnerin?', ['Entschuldigung, aber der Kaffee ist leider kalt.', 'Vielen Dank, der Kaffee ist sehr gut.', 'Ich möchte einen Kaffee.'],
      ['Your coffee is cold. What do you say to the waitress?', 'Ваш кофе холодный. Что вы скажете официантке?', 'Ваша кава холодна. Що ви скажете офіціантці?', 'Kahveniz soğuk. Garsona ne dersiniz?']),
    mc('K5', 'getrennt', I.situation, 'Ihr seid drei Freunde. Jeder bezahlt sein Essen selbst. Was sagt ihr zum Kellner?', ['Getrennt, bitte.', 'Zusammen, bitte.', 'Stimmt so.'],
      ['You are three friends. Everyone pays for their own meal. What do you say to the waiter?', 'Вас трое друзей. Каждый платит за себя. Что вы скажете официанту?', 'Вас троє друзів. Кожен платить за себе. Що ви скажете офіціантові?', 'Üç arkadaşsınız. Herkes kendi yemeğini ödüyor. Garsona ne dersiniz?']),
    mc('K6', 'genauso', I.situation, 'In Deutschland gibt man im Restaurant Trinkgeld. In deinem Land macht man das auch. Was sagst du?', ['Bei uns ist das genauso.', 'Bei uns ist das anders.', 'Das überrascht mich.'],
      ['In Germany people tip in restaurants. In your country people do that too. What do you say?', 'В Германии в ресторане оставляют чаевые. В вашей стране тоже так делают. Что вы скажете?', 'У Німеччині в ресторані залишають чайові. У вашій країні теж так роблять. Що ви скажете?', 'Almanya’da restoranda bahşiş verilir. Sizin ülkenizde de böyle yapılır. Ne dersiniz?']),
    mc('K7', 'süß', I.choose, 'In diesem Tee ist sehr viel Zucker. Er ist sehr …', ['süß', 'scharf', 'salzig'],
      ['There is a great deal of sugar in this tea. It is very …', 'В этом чае очень много сахара. Он очень …', 'У цьому чаї дуже багато цукру. Він дуже …', 'Bu çayda çok fazla şeker var. Çay çok …']),
    mc('Z1', 'Wie oft?', I.read, `${MIA} Wie oft isst die Familie Fisch?`, ['Zweimal pro Woche.', 'Jeden Tag.', 'Selten.'],
      ['How often does the family eat fish?', 'Как часто семья ест рыбу?', 'Як часто родина їсть рибу?', 'Aile ne sıklıkta balık yiyor?']),
    gap('G1', 'eins', I.pronoun, 'Ich brauche ein Messer. – Schau mal, neben dem Teller liegt ', '.', 'eins', ['einer', 'eine'],
      ['I need a knife. – Look, there is one next to the plate.', 'Мне нужен нож. – Смотри, рядом с тарелкой лежит один.', 'Мені потрібен ніж. – Дивись, поруч із тарілкою лежить один.', 'Bir bıçağa ihtiyacım var. – Bak, tabağın yanında bir tane duruyor.'], 'das Messer'),
    gap('G1', 'keiner', I.pronoun, 'Ist noch ein Stuhl frei? – Nein, leider ist ', ' mehr frei.', 'keiner', ['keins', 'keine'],
      ['Is there a chair free? – No, unfortunately there is none left.', 'Есть ещё свободный стул? – Нет, к сожалению, свободных больше нет.', 'Є ще вільний стілець? – Ні, на жаль, вільних більше немає.', 'Boş bir sandalye daha var mı? – Hayır, maalesef hiç kalmadı.'], 'der Stuhl'),
    gap('G2', 'keinen', I.pronoun, 'Hast du einen Stift? – Nein, ich habe leider ', '.', 'keinen', ['keiner', 'keins'],
      ['Do you have a pen? – No, unfortunately I do not have one.', 'У тебя есть ручка? – Нет, к сожалению, нет.', 'У тебе є ручка? – Ні, на жаль, немає.', 'Kalemin var mı? – Hayır, maalesef yok.'], 'der Stift'),
    sb('G2', 'eins', I.order, 'Ich / nehme / auch / eins.',
      ['I will have one too.', 'Я тоже возьму одно.', 'Я теж візьму одне.', 'Ben de bir tane alıyorum.'],
      { alt: ['Auch ich nehme eins.'] }),
  ],
  size: 13,
  test: [
    mc('W1', 'Gabel', I.choose, 'Du isst einen Salat. Was brauchst du?', ['eine Gabel', 'eine Kanne', 'einen Topf'],
      ['You are eating a salad. What do you need?', 'Вы едите салат. Что вам нужно?', 'Ви їсте салат. Що вам потрібно?', 'Salata yiyorsunuz. Neye ihtiyacınız var?']),
    mc('W1', 'Abendessen', I.choose, 'Das Abendessen isst man …', ['am Abend.', 'am Morgen.', 'am Mittag.'],
      ['You eat dinner …', 'Ужинают …', 'Вечеряють …', 'Akşam yemeği … yenir.']),
    mc('G1', 'einer', I.choose, 'Ich brauche einen Stift. – Auf dem Tisch liegt …', ['einer.', 'eins.', 'eine.'],
      ['I need a pen. – There is one on the table.', 'Мне нужна ручка. – На столе лежит одна.', 'Мені потрібна ручка. – На столі лежить одна.', 'Bir kaleme ihtiyacım var. – Masanın üstünde bir tane duruyor.']),
    mc('G1', 'keine (Plural)', I.choose, 'Sind noch Kartoffeln da? – Nein, es sind … mehr da.', ['keine', 'keiner', 'keins'],
      ['Are there any potatoes left? – No, there are none left.', 'Картошка ещё осталась? – Нет, больше не осталось.', 'Картопля ще залишилася? – Ні, більше не залишилося.', 'Patates kaldı mı? – Hayır, hiç kalmadı.']),
    mc('G2', 'einen', I.choose, 'Möchtest du einen Tee? – Ja, gern, ich nehme …', ['einen.', 'einer.', 'eins.'],
      ['Would you like a tea? – Yes, please, I will have one.', 'Хочешь чаю? – Да, с удовольствием.', 'Хочеш чаю? – Так, охоче.', 'Çay ister misin? – Evet, lütfen, bir tane alayım.']),
    mc('G2', 'keins', I.choose, 'Hast du ein Handy? – Nein, ich habe …', ['keins.', 'keinen.', 'keiner.'],
      ['Do you have a mobile? – No, I do not have one.', 'У тебя есть мобильный телефон? – Нет, у меня нет.', 'У тебе є мобільний телефон? – Ні, у мене немає.', 'Cep telefonun var mı? – Hayır, yok.']),
    mc('K1', 'dreimal', I.choose, 'Olga isst montags, mittwochs und freitags in der Kantine. Sie isst … pro Woche dort.', ['dreimal', 'einmal', 'zweimal'],
      ['Olga eats in the canteen on Mondays, Wednesdays and Fridays. She eats there … a week.', 'Olga ест в столовой по понедельникам, средам и пятницам. Она ест там … в неделю.', 'Olga їсть у їдальні в понеділок, середу та п’ятницю. Вона їсть там … на тиждень.', 'Olga pazartesi, çarşamba ve cuma günleri kantinde yiyor. Orada haftada … yiyor.']),
    mc('K1', 'meistens', I.choose, 'Welches Wort bedeutet „fast immer“?', ['meistens', 'selten', 'nie'],
      ['Which word means “almost always”?', 'Какое слово означает «почти всегда»?', 'Яке слово означає «майже завжди»?', 'Hangi kelime “neredeyse her zaman” anlamına gelir?']),
    mc('K2', 'loben', I.situation, 'Du bist zu Gast. Das Essen steht auf dem Tisch und riecht sehr gut. Was sagst du?', ['Das riecht aber lecker!', 'Zahlen, bitte!', 'Ist hier noch frei?'],
      ['You are a guest. The food is on the table and smells very good. What do you say?', 'Вы в гостях. Еда на столе и очень вкусно пахнет. Что вы скажете?', 'Ви в гостях. Їжа на столі й дуже смачно пахне. Що ви скажете?', 'Misafirliktesiniz. Yemek masada ve çok güzel kokuyor. Ne dersiniz?']),
    mc('K2', 'Abschied', I.react, '„Vielen Dank für den schönen Abend!“', ['Gern! Kommt bald mal wieder!', 'Guten Appetit!', 'Nein danke, ich kann nicht mehr.'],
      ['“Thank you very much for the lovely evening!”', '«Большое спасибо за чудесный вечер!»', '«Щиро дякую за чудовий вечір!»', '“Bu güzel akşam için çok teşekkürler!”']),
    mc('K3', 'Gast', I.choose, 'Was sagt der Gast im Restaurant?', ['Ich nehme die Tomatensuppe.', 'Was darf ich Ihnen bringen?', 'Zusammen oder getrennt?'],
      ['What does the guest in a restaurant say?', 'Что говорит гость в ресторане?', 'Що каже гість у ресторані?', 'Restoranda müşteri ne der?']),
    mc('K4', 'höflich reklamieren', I.situation, 'Du hast ein Schnitzel bestellt. Es ist kalt. Was sagst du?', ['Entschuldigung, aber das Schnitzel ist leider kalt.', 'Das Schnitzel ist sehr lecker.', 'Ich nehme das Schnitzel.'],
      ['You ordered a schnitzel. It is cold. What do you say?', 'Вы заказали шницель. Он холодный. Что вы скажете?', 'Ви замовили шніцель. Він холодний. Що ви скажете?', 'Şnitzel sipariş ettiniz. Soğuk. Ne dersiniz?']),
    mc('K5', 'Stimmt so', I.choose, 'Die Rechnung ist 46 Euro. Du gibst 50 Euro und sagst: „Stimmt so.“ Wie viel Geld bekommst du zurück?', ['Nichts.', '4 Euro.', '46 Euro.'],
      ['The bill is 46 euros. You give 50 euros and say: “Stimmt so.” How much money do you get back?', 'Счёт – 46 евро. Вы даёте 50 евро и говорите: «Stimmt so». Сколько денег вам вернут?', 'Рахунок – 46 євро. Ви даєте 50 євро й кажете: «Stimmt so». Скільки грошей вам повернуть?', 'Hesap 46 avro. 50 avro verip “Stimmt so.” diyorsunuz. Ne kadar para üstü alırsınız?']),
    mc('K6', 'anders', I.situation, 'In Deutschland essen viele Menschen schon um 18 Uhr zu Abend. Bei dir zu Hause isst man erst um 21 Uhr. Was sagst du?', ['Bei uns ist das anders.', 'Bei uns ist das genauso.', 'Das ist bei uns auch so.'],
      ['In Germany many people have dinner as early as 6 pm. At home in your country people eat at 9 pm. What do you say?', 'В Германии многие ужинают уже в 18 часов. У вас дома ужинают только в 21 час. Что вы скажете?', 'У Німеччині багато хто вечеряє вже о 18 годині. У вас удома вечеряють аж о 21 годині. Що ви скажете?', 'Almanya’da birçok kişi akşam yemeğini daha saat 18’de yiyor. Sizin ülkenizde ancak 21’de yeniyor. Ne dersiniz?']),
    mc('K7', 'Vegetarier', I.choose, 'Herr Petrov sagt: „Ich bin Vegetarier.“ Was isst er nicht?', ['Fleisch', 'Gemüse', 'Brot'],
      ['Mr Petrov says: “I am a vegetarian.” What does he not eat?', 'Господин Petrov говорит: «Я вегетарианец». Чего он не ест?', 'Пан Petrov каже: «Я вегетаріанець». Чого він не їсть?', 'Petrov Bey “Ben vejetaryenim.” diyor. Ne yemez?']),
    mc('Z1', 'Wer?', I.read, `${DILARA} Wer kocht in Dilaras Familie fast immer?`, ['Der Vater.', 'Die Großeltern.', 'Dilara.'],
      ['Who almost always cooks in Dilara’s family?', 'Кто в семье Dilara готовит почти всегда?', 'Хто в родині Dilara готує майже завжди?', 'Dilara’nın ailesinde neredeyse her zaman kim yemek yapıyor?']),
    mc('Z1', 'Sonntag', I.read, `${DILARA} Was ist am Sonntag anders?`, ['Der Vater kocht lange und die Großeltern kommen.', 'Es gibt nur Nudeln.', 'Die Familie isst im Restaurant.'],
      ['What is different on Sunday?', 'Что иначе в воскресенье?', 'Що інакше в неділю?', 'Pazar günü farklı olan ne?']),
    gap('W1', 'Pfanne', I.word, 'Eier und Fleisch macht man in der ', '.', 'Pfanne', ['Kanne', 'Tasse'],
      ['You cook eggs and meat in the frying pan.', 'Яйца и мясо готовят на сковороде.', 'Яйця та м’ясо готують на сковороді.', 'Yumurta ve et tavada yapılır.'],
      ['frying pan', 'сковорода', 'сковорода', 'tava']),
    gap('G1', 'eine', I.pronoun, 'Wo ist eine Serviette? – Hier liegt ', '.', 'eine', ['einer', 'eins'],
      ['Where is a napkin? – Here is one.', 'Где салфетка? – Вот лежит одна.', 'Де серветка? – Ось лежить одна.', 'Peçete nerede? – Burada bir tane var.'], 'die Serviette'),
    gap('G1', 'welche', I.pronoun, 'Haben wir noch Zwiebeln? – Ja, in der Küche liegen ', '.', 'welche', ['eine', 'eins'],
      ['Do we still have onions? – Yes, there are some in the kitchen.', 'У нас ещё есть лук? – Да, на кухне лежит.', 'У нас іще є цибуля? – Так, на кухні лежить.', 'Soğanımız kaldı mı? – Evet, mutfakta birkaç tane var.'], 'die Zwiebeln (Plural)'),
    gap('G1', 'meiner', I.pronoun, 'Ist das dein Teller? – Ja, das ist ', '.', 'meiner', ['meins', 'meine'],
      ['Is that your plate? – Yes, that is mine.', 'Это твоя тарелка? – Да, моя.', 'Це твоя тарілка? – Так, моя.', 'Bu senin tabağın mı? – Evet, benimki.'], 'der Teller, mein-'),
    gap('G2', 'eine', I.pronoun, 'Ich habe keine Gabel. – Moment, ich gebe dir ', '.', 'eine', ['einen', 'eins'],
      ['I have no fork. – Just a moment, I will give you one.', 'У меня нет вилки. – Минутку, я дам тебе.', 'У мене немає виделки. – Хвилинку, я дам тобі.', 'Çatalım yok. – Bir dakika, sana bir tane vereyim.'], 'die Gabel'),
    gap('G2', 'einen', I.pronoun, 'Brauchst du einen Teller? – Nein danke, ich habe schon ', '.', 'einen', ['einer', 'eins'],
      ['Do you need a plate? – No thanks, I already have one.', 'Тебе нужна тарелка? – Нет, спасибо, у меня уже есть.', 'Тобі потрібна тарілка? – Ні, дякую, у мене вже є.', 'Tabağa ihtiyacın var mı? – Hayır, teşekkürler, bende var.'], 'der Teller'),
    gap('K1', 'nie', I.word, 'Ich trinke keinen Alkohol, wirklich ', '.', 'nie', ['oft', 'immer'],
      ['I do not drink alcohol, really never.', 'Я не пью алкоголь, действительно никогда.', 'Я не п’ю алкоголь, справді ніколи.', 'Alkol içmem, gerçekten hiç.'],
      ['never', 'никогда', 'ніколи', 'hiç, asla']),
    gap('K3', 'Platz', I.word, 'Entschuldigung, ist der ', ' neben Ihnen noch frei? – Ja, bitte.', ['Platz', 'Stuhl', 'Sitzplatz'], ['Kellner', 'Appetit'],
      ['Excuse me, is the seat next to you free? – Yes, please.', 'Извините, место рядом с вами свободно? – Да, пожалуйста.', 'Вибачте, місце поруч із вами вільне? – Так, будь ласка.', 'Affedersiniz, yanınızdaki yer boş mu? – Evet, buyurun.'],
      ['seat', 'место', 'місце', 'yer']),
    gap('K4', 'salzig', I.word, 'Entschuldigung, im Essen ist zu viel Salz. Es ist viel zu ', '.', 'salzig', ['süß', 'sauber'],
      ['Excuse me, there is too much salt in the food. It is far too salty.', 'Извините, в еде слишком много соли. Она слишком солёная.', 'Вибачте, у їжі забагато солі. Вона занадто солона.', 'Affedersiniz, yemekte çok fazla tuz var. Çok fazla tuzlu.'],
      ['salty', 'солёный', 'солоний', 'tuzlu']),
    gap('K5', 'zusammen oder getrennt', I.conjunction, 'Zahlen Sie zusammen ', ' getrennt?', 'oder', ['und', 'aber'],
      ['Are you paying together or separately?', 'Вы платите вместе или раздельно?', 'Ви платите разом чи окремо?', 'Birlikte mi ödüyorsunuz, yoksa ayrı ayrı mı?'], 'oder / und / aber'),
    gap('K6', 'man', I.verb, 'In Deutschland ', ' man viel Brot.', 'isst', ['essen', 'esst'],
      ['In Germany people eat a lot of bread.', 'В Германии едят много хлеба.', 'У Німеччині їдять багато хліба.', 'Almanya’da çok ekmek yenir.'], 'essen'),
    gap('K7', 'Vegetarier', I.word, 'Ich esse kein Fleisch und keinen Fisch. Ich bin ', '.', ['Vegetarier', 'Vegetarierin'], ['Kellner', 'Gast'],
      ['I do not eat meat or fish. I am a vegetarian.', 'Я не ем ни мяса, ни рыбы. Я вегетарианец.', 'Я не їм ні м’яса, ні риби. Я вегетаріанець.', 'Ne et ne balık yerim. Ben vejetaryenim.'],
      ['vegetarian', 'вегетарианец', 'вегетаріанець', 'vejetaryen']),
    sb('K3', 'Kellner', I.question, 'Was / darf / ich / Ihnen / bringen?',
      ['What can I get you?', 'Что вам принести?', 'Що вам принести?', 'Size ne getireyim?']),
    sb('K5', 'getrennt zahlen', I.order, 'Wir / möchten / bitte / getrennt / zahlen.',
      ['We would like to pay separately, please.', 'Мы хотели бы заплатить раздельно.', 'Ми хотіли б заплатити окремо.', 'Ayrı ayrı ödemek istiyoruz lütfen.'],
      { alt: ['Wir möchten getrennt zahlen, bitte.'] }),
  ],
}

export default check
