import { I, gap, mc, sb } from '../shared.mjs'

const PAUL = 'Paul schreibt im Forum: „Ich koche fast nie. Dreimal pro Woche hole ich mir eine Pizza oder einen Döner. Am Wochenende esse ich bei meinen Eltern. Meine Mutter kocht sehr gut, am liebsten mag ich ihre Kartoffelsuppe.“'
const KRITIK = 'Restaurantkritik: „Im ‚Lindenhof‘ ist das Essen frisch und lecker, besonders der Fisch. Leider muss man lange warten: Wir haben 50 Minuten auf das Hauptgericht gewartet. Die Kellner sind aber sehr freundlich.“'

/** A2.1 · Pfad 3 · Essen und Trinken – Lektionen. Wiederholung und Test: p3-check.mjs */
const path = {
  n: 3,
  slug: 'essen-und-trinken',
  title: 'Essen und Trinken',
  t: ['Food and drink', 'Еда и напитки', 'Їжа та напої', 'Yeme içme'],
  objectives: {
    G1: 'Indefinitpronomen im Nominativ: einer, eins, eine, welche – keiner, keins, keine; auch meiner, meins, meine.',
    G2: 'Indefinitpronomen im Akkusativ: einen, eins, eine, welche – keinen, keins, keine.',
    K1: 'Sagen, wie oft man etwas macht: immer, meistens, oft, manchmal, selten, nie; einmal pro Woche.',
    K2: 'Gespräche bei einer privaten Einladung zum Essen führen: bei der Ankunft, beim Essen und beim Abschied.',
    K3: 'Im Restaurant einen Platz suchen und bestellen: Ist hier noch frei? Ich nehme …',
    K4: 'Im Restaurant höflich reklamieren: Entschuldigung, aber die Suppe ist leider kalt.',
    K5: 'Im Restaurant bezahlen: Zahlen, bitte! Zusammen oder getrennt? Stimmt so.',
    K6: 'Essgewohnheiten mit dem eigenen Land vergleichen: Bei uns ist das anders. Das überrascht mich.',
    K7: 'Über Kochgewohnheiten und Vorlieben sprechen: Ich koche gern scharf. Mein Lieblingsrezept ist …',
    Z1: 'Kann-Ziele: kurze Interviews und Texte über Essgewohnheiten verstehen.',
    W1: 'Wortschatz: Geschirr, Besteck und Mahlzeiten.',
  },
  nodes: [
    {
      title: 'Geschirr und Besteck',
      t: ['Crockery and cutlery', 'Посуда и столовые приборы', 'Посуд і столові прибори', 'Tabak çanak ve çatal bıçak'],
      card: {
        id: 'p3_geschirr',
        rule: 'Auf dem Tisch: der Teller, der Löffel, der Topf, die Tasse, die Gabel, die Schüssel, die Kanne, die Pfanne, das Glas, das Messer. Messer, Gabel und Löffel sind das Besteck. Teller, Tassen und Schüsseln sind das Geschirr. Mahlzeiten: das Frühstück (morgens), das Mittagessen (mittags), das Abendessen (abends). Ein Gericht ist ein fertiges Essen, zum Beispiel Suppe oder Nudeln mit Soße. Im Restaurant: die Vorspeise, das Hauptgericht, die Nachspeise.',
        examples: ['Die Suppe isst man mit dem Löffel.', 'Der Tee ist in der Kanne.', 'Zum Frühstück gibt es Brot und Käse.'],
        highlight: 'article',
        t: [
          'On the table: der Teller (plate), der Löffel (spoon), der Topf (pot), die Tasse (cup), die Gabel (fork), die Schüssel (bowl), die Kanne (pot for tea or coffee), die Pfanne (frying pan), das Glas (glass), das Messer (knife). Knife, fork and spoon are das Besteck (cutlery). Plates, cups and bowls are das Geschirr (crockery). Meals: das Frühstück (breakfast), das Mittagessen (lunch), das Abendessen (dinner). Ein Gericht is a finished dish, for example soup or pasta with sauce. In a restaurant: die Vorspeise (starter), das Hauptgericht (main course), die Nachspeise (dessert).',
          'На столе: der Teller (тарелка), der Löffel (ложка), der Topf (кастрюля), die Tasse (чашка), die Gabel (вилка), die Schüssel (миска), die Kanne (чайник, кофейник), die Pfanne (сковорода), das Glas (стакан), das Messer (нож). Нож, вилка и ложка – это das Besteck (столовые приборы). Тарелки, чашки и миски – это das Geschirr (посуда). Приёмы пищи: das Frühstück (завтрак), das Mittagessen (обед), das Abendessen (ужин). Ein Gericht – готовое блюдо, например суп или макароны с соусом. В ресторане: die Vorspeise (закуска), das Hauptgericht (основное блюдо), die Nachspeise (десерт).',
          'На столі: der Teller (тарілка), der Löffel (ложка), der Topf (каструля), die Tasse (чашка), die Gabel (виделка), die Schüssel (миска), die Kanne (чайник, кавник), die Pfanne (сковорода), das Glas (склянка), das Messer (ніж). Ніж, виделка й ложка – це das Besteck (столові прибори). Тарілки, чашки й миски – це das Geschirr (посуд). Прийоми їжі: das Frühstück (сніданок), das Mittagessen (обід), das Abendessen (вечеря). Ein Gericht – готова страва, наприклад суп або макарони із соусом. У ресторані: die Vorspeise (закуска), das Hauptgericht (основна страва), die Nachspeise (десерт).',
          'Masada: der Teller (tabak), der Löffel (kaşık), der Topf (tencere), die Tasse (fincan), die Gabel (çatal), die Schüssel (kâse), die Kanne (demlik, sürahi), die Pfanne (tava), das Glas (bardak), das Messer (bıçak). Bıçak, çatal ve kaşık das Besteck’tir (çatal bıçak takımı). Tabaklar, fincanlar ve kâseler das Geschirr’dir (tabak çanak). Öğünler: das Frühstück (kahvaltı), das Mittagessen (öğle yemeği), das Abendessen (akşam yemeği). Ein Gericht hazır bir yemektir, örneğin çorba ya da soslu makarna. Restoranda: die Vorspeise (başlangıç), das Hauptgericht (ana yemek), die Nachspeise (tatlı).',
        ],
        hint: ['Essen: Messer, Gabel, Löffel, Teller, Schüssel. Trinken: Tasse, Glas, Kanne. Kochen: Topf, Pfanne.', 'Eating: Messer, Gabel, Löffel, Teller, Schüssel. Drinking: Tasse, Glas, Kanne. Cooking: Topf, Pfanne.', 'Для еды: Messer, Gabel, Löffel, Teller, Schüssel. Для напитков: Tasse, Glas, Kanne. Для готовки: Topf, Pfanne.', 'Для їжі: Messer, Gabel, Löffel, Teller, Schüssel. Для напоїв: Tasse, Glas, Kanne. Для готування: Topf, Pfanne.', 'Yemek için: Messer, Gabel, Löffel, Teller, Schüssel. İçmek için: Tasse, Glas, Kanne. Pişirmek için: Topf, Pfanne.'],
        hints: {
          article: ['Lern jedes Wort mit Artikel: der Löffel, die Gabel, das Messer.', 'Learn every word with its article: der Löffel, die Gabel, das Messer.', 'Учите каждое слово с артиклем: der Löffel, die Gabel, das Messer.', 'Вчіть кожне слово з артиклем: der Löffel, die Gabel, das Messer.', 'Her kelimeyi artikeliyle öğrenin: der Löffel, die Gabel, das Messer.'],
        },
      },
      ex: [
        mc('W1', 'Löffel', I.choose, 'Die Suppe isst man mit dem …', ['Löffel', 'Messer', 'Glas'],
          ['You eat soup with a …', 'Суп едят …', 'Суп їдять …', 'Çorba … ile içilir.']),
        mc('W1', 'Messer', I.choose, 'Du möchtest Fleisch schneiden. Was brauchst du?', ['ein Messer', 'eine Tasse', 'eine Kanne'],
          ['You want to cut meat. What do you need?', 'Вы хотите порезать мясо. Что вам нужно?', 'Ви хочете порізати м’ясо. Що вам потрібно?', 'Et kesmek istiyorsunuz. Neye ihtiyacınız var?']),
        mc('W1', 'Frühstück', I.choose, 'Wann isst man das Frühstück?', ['Am Morgen.', 'Am Mittag.', 'Am Abend.'],
          ['When do you eat breakfast?', 'Когда завтракают?', 'Коли снідають?', 'Kahvaltı ne zaman yapılır?']),
        mc('W1', 'Besteck', I.odd, 'Drei Wörter sind Besteck, ein Wort nicht.', ['Teller', 'Gabel', 'Messer', 'Löffel'], null),
        gap('W1', 'Tasse', I.word, 'Kaffee trinkt man aus einer ', '.', 'Tasse', ['Gabel', 'Pfanne'],
          ['You drink coffee from a cup.', 'Кофе пьют из чашки.', 'Каву п’ють із чашки.', 'Kahve fincandan içilir.'],
          ['cup', 'чашка', 'чашка', 'fincan']),
        gap('W1', 'Schüssel', I.word, 'Der Salat für alle ist in der großen ', '.', 'Schüssel', ['Gabel', 'Kanne'],
          ['The salad for everyone is in the big bowl.', 'Салат для всех лежит в большой миске.', 'Салат для всіх лежить у великій мисці.', 'Herkes için yapılan salata büyük kâsede.'],
          ['bowl', 'миска', 'миска', 'kâse']),
        gap('W1', 'Hauptgericht', I.word, 'Zuerst gibt es eine Suppe als Vorspeise, dann kommt das ', ' und am Ende die Nachspeise.', 'Hauptgericht', ['Frühstück', 'Besteck'],
          ['First there is soup as a starter, then comes the main course and at the end the dessert.', 'Сначала подают суп как закуску, затем основное блюдо, а в конце десерт.', 'Спочатку подають суп як закуску, потім основну страву, а в кінці десерт.', 'Önce başlangıç olarak çorba var, sonra ana yemek ve en sonunda tatlı geliyor.'],
          ['main course', 'основное блюдо', 'основна страва', 'ana yemek']),
        gap('W1', 'Artikel', I.article, '', ' Gabel liegt links neben dem Teller.', 'Die', ['Der', 'Das'],
          ['The fork is on the left next to the plate.', 'Вилка лежит слева от тарелки.', 'Виделка лежить ліворуч від тарілки.', 'Çatal tabağın solunda duruyor.'], 'der / die / das', { h: 'article' }),
        gap('W1', 'Artikel', I.article, '', ' Messer ist nicht scharf.', 'Das', ['Der', 'Die'],
          ['The knife is not sharp.', 'Нож не острый.', 'Ніж не гострий.', 'Bıçak keskin değil.'], 'der / die / das', { h: 'article' }),
        sb('W1', 'Abendessen', I.order, 'Zum Abendessen / gibt / es / heute / Suppe.',
          ['There is soup for dinner today.', 'Сегодня на ужин суп.', 'Сьогодні на вечерю суп.', 'Bugün akşam yemeğinde çorba var.'],
          { alt: ['Heute gibt es zum Abendessen Suppe.', 'Heute gibt es Suppe zum Abendessen.', 'Es gibt heute zum Abendessen Suppe.', 'Es gibt heute Suppe zum Abendessen.'] }),
      ],
    },
    {
      title: 'Wie oft?',
      t: ['How often?', 'Как часто?', 'Як часто?', 'Ne sıklıkta?'],
      card: {
        id: 'p3_oft',
        rule: 'Wie oft machst du etwas? immer – fast immer – meistens – oft – manchmal – selten – fast nie – nie. Mit Zahlen: einmal, zweimal, dreimal pro Tag, pro Woche, im Monat, im Jahr. Mahlzeiten: Zum Frühstück gibt es meistens Müsli. Zum Abendessen esse ich oft Brot. Das Wort für die Häufigkeit steht meistens nach dem Verb: Ich koche selten. Ich gehe einmal pro Woche ins Restaurant.',
        examples: ['Ich frühstücke immer zu Hause.', 'Wir essen zweimal pro Woche Fisch.', 'Mittags esse ich fast nie warm.'],
        highlight: null,
        t: [
          'How often do you do something? immer (always) – fast immer (almost always) – meistens (mostly) – oft (often) – manchmal (sometimes) – selten (rarely) – fast nie (hardly ever) – nie (never). With numbers: einmal, zweimal, dreimal (once, twice, three times) pro Tag, pro Woche, im Monat, im Jahr. Meals: Zum Frühstück gibt es meistens Müsli. Zum Abendessen esse ich oft Brot. The frequency word usually comes after the verb: Ich koche selten. Ich gehe einmal pro Woche ins Restaurant.',
          'Как часто вы что-то делаете? immer (всегда) – fast immer (почти всегда) – meistens (чаще всего) – oft (часто) – manchmal (иногда) – selten (редко) – fast nie (почти никогда) – nie (никогда). С числами: einmal, zweimal, dreimal (один, два, три раза) pro Tag, pro Woche, im Monat, im Jahr. Приёмы пищи: Zum Frühstück gibt es meistens Müsli. Zum Abendessen esse ich oft Brot. Слово, обозначающее частоту, обычно стоит после глагола: Ich koche selten. Ich gehe einmal pro Woche ins Restaurant.',
          'Як часто ви щось робите? immer (завжди) – fast immer (майже завжди) – meistens (здебільшого) – oft (часто) – manchmal (іноді) – selten (рідко) – fast nie (майже ніколи) – nie (ніколи). З числами: einmal, zweimal, dreimal (один, два, три рази) pro Tag, pro Woche, im Monat, im Jahr. Прийоми їжі: Zum Frühstück gibt es meistens Müsli. Zum Abendessen esse ich oft Brot. Слово, що означає частоту, зазвичай стоїть після дієслова: Ich koche selten. Ich gehe einmal pro Woche ins Restaurant.',
          'Bir şeyi ne sıklıkta yaparsınız? immer (her zaman) – fast immer (neredeyse her zaman) – meistens (çoğunlukla) – oft (sık sık) – manchmal (bazen) – selten (nadiren) – fast nie (neredeyse hiç) – nie (hiç, asla). Sayılarla: einmal, zweimal, dreimal (bir, iki, üç kez) pro Tag, pro Woche, im Monat, im Jahr. Öğünler: Zum Frühstück gibt es meistens Müsli. Zum Abendessen esse ich oft Brot. Sıklık bildiren kelime çoğunlukla fiilden sonra gelir: Ich koche selten. Ich gehe einmal pro Woche ins Restaurant.',
        ],
        hint: ['Von viel zu wenig: immer – meistens – oft – manchmal – selten – nie.', 'From a lot to a little: immer – meistens – oft – manchmal – selten – nie.', 'От частого к редкому: immer – meistens – oft – manchmal – selten – nie.', 'Від частого до рідкого: immer – meistens – oft – manchmal – selten – nie.', 'Çoktan aza: immer – meistens – oft – manchmal – selten – nie.'],
      },
      ex: [
        mc("K1", "immer", I.choose, "Leon isst jeden Tag Obst. Er isst ___ Obst.", ["immer","selten","nie"], ["Leon eats fruit every day. He … eats fruit.","Leon ест фрукты каждый день. Он … ест фрукты.","Leon їсть фрукти щодня. Він … їсть фрукти.","Leon her gün meyve yiyor. O … meyve yer."], {"c":"p3_oft"}),
        mc('K1', 'nie', I.choose, 'Tom trinkt keinen Kaffee, wirklich keinen. Er trinkt … Kaffee.', ['nie', 'oft', 'meistens'],
          ['Tom does not drink coffee, really none at all. He … drinks coffee.', 'Tom не пьёт кофе, совсем. Он … пьёт кофе.', 'Tom не п’є каву, зовсім. Він … п’є каву.', 'Tom kahve içmiyor, gerçekten hiç. O … kahve içmez.']),
        mc('K1', 'zweimal', I.choose, 'Ich gehe am Montag und am Donnerstag schwimmen. Ich gehe … pro Woche schwimmen.', ['zweimal', 'einmal', 'dreimal'],
          ['I go swimming on Monday and on Thursday. I go swimming … a week.', 'Я хожу плавать в понедельник и в четверг. Я хожу плавать … в неделю.', 'Я ходжу плавати в понеділок і в четвер. Я ходжу плавати … на тиждень.', 'Pazartesi ve perşembe günleri yüzmeye gidiyorum. Haftada … yüzmeye gidiyorum.']),
        mc('K1', 'Wie oft?', I.react, '„Wie oft kochst du?“', ['Fast jeden Tag.', 'Seit zwei Jahren.', 'Um 18 Uhr.'],
          ['“How often do you cook?”', '«Как часто ты готовишь?»', '«Як часто ти готуєш?»', '“Ne sıklıkta yemek yaparsın?”']),
        mc('K1', 'selten', I.choose, 'Welches Wort bedeutet „nicht oft“?', ['selten', 'meistens', 'immer'],
          ['Which word means “not often”?', 'Какое слово означает «не часто»?', 'Яке слово означає «не часто»?', 'Hangi kelime “sık değil” anlamına gelir?']),
        gap('K1', 'meistens', I.word, 'Ich esse fast jeden Morgen Müsli. Ich esse ', ' Müsli zum Frühstück.', 'meistens', ['selten', 'nie'],
          ['I eat muesli almost every morning. I mostly have muesli for breakfast.', 'Почти каждое утро я ем мюсли. На завтрак я чаще всего ем мюсли.', 'Майже щоранку я їм мюслі. На сніданок я здебільшого їм мюслі.', 'Neredeyse her sabah müsli yiyorum. Kahvaltıda çoğunlukla müsli yerim.'],
          ['mostly, usually', 'чаще всего', 'здебільшого', 'çoğunlukla']),
        gap('K1', 'einmal', I.word, 'Wir gehen nur an meinem Geburtstag ins Restaurant: ', ' im Jahr.', 'einmal', ['zweimal', 'immer'],
          ['We only go to a restaurant on my birthday: once a year.', 'Мы ходим в ресторан только в мой день рождения: один раз в год.', 'Ми ходимо в ресторан лише на мій день народження: один раз на рік.', 'Sadece doğum günümde restorana gidiyoruz: yılda bir kez.'],
          ['once', 'один раз', 'один раз', 'bir kez']),
        gap('K1', 'Wie oft?', I.qword, 'Wie ', ' isst du Fleisch? – Dreimal pro Woche.', 'oft', ['viel', 'lange'],
          ['How often do you eat meat? – Three times a week.', 'Как часто ты ешь мясо? – Три раза в неделю.', 'Як часто ти їси м’ясо? – Тричі на тиждень.', 'Ne sıklıkta et yersin? – Haftada üç kez.'], 'oft / viel / lange'),
        gap('K1', 'pro Woche', I.word, 'Ich koche zweimal ', ' Woche: am Samstag und am Sonntag.', 'pro', ['für', 'am'],
          ['I cook twice a week: on Saturday and on Sunday.', 'Я готовлю два раза в неделю: в субботу и в воскресенье.', 'Я готую двічі на тиждень: у суботу й у неділю.', 'Haftada iki kez yemek yapıyorum: cumartesi ve pazar.'], 'pro / für / am'),
        sb('K1', 'meistens', I.order, 'Ich / esse / mittags / meistens / in der Kantine.',
          ['I mostly have lunch in the canteen.', 'В обед я чаще всего ем в столовой.', 'В обід я здебільшого їм у їдальні.', 'Öğlenleri çoğunlukla kantinde yerim.'],
          { alt: ['Mittags esse ich meistens in der Kantine.', 'Meistens esse ich mittags in der Kantine.'] }),
      ],
    },
    {
      title: 'Da ist einer.',
      t: ['There is one.', 'Вот один.', 'Ось один.', 'İşte bir tane.'],
      card: {
        id: 'p3_indef_nom',
        rule: 'Indefinitpronomen ersetzen ein Nomen: Ist hier ein Löffel? – Ja, hier ist einer. Nein, hier ist keiner. Nominativ: der Löffel → einer, keiner. Das Messer → eins, keins. Die Gabel → eine, keine. Plural: die Teller → welche, keine. Genauso mit mein: Der Löffel? Das ist meiner. Das Glas? Das ist meins. Die Tasse? Das ist meine.',
        examples: ['Wo ist ein Teller? – Dort steht einer.', 'Ich brauche ein Glas. – Hier ist eins.', 'Sind noch Brötchen da? – Ja, hier sind welche.'],
        highlight: null,
        t: [
          'Indefinite pronouns replace a noun: Ist hier ein Löffel? – Ja, hier ist einer. (Yes, here is one.) Nein, hier ist keiner. (No, there is none.) Nominative: der Löffel → einer, keiner. Das Messer → eins, keins. Die Gabel → eine, keine. Plural: die Teller → welche (some), keine. The same with mein: Der Löffel? Das ist meiner. (That is mine.) Das Glas? Das ist meins. Die Tasse? Das ist meine.',
          'Неопределённые местоимения заменяют существительное: Ist hier ein Löffel? – Ja, hier ist einer. (Да, вот одна.) Nein, hier ist keiner. (Нет, здесь ни одной.) Nominativ: der Löffel → einer, keiner. Das Messer → eins, keins. Die Gabel → eine, keine. Множественное число: die Teller → welche (несколько), keine. Так же с mein: Der Löffel? Das ist meiner. (Это моя.) Das Glas? Das ist meins. Die Tasse? Das ist meine.',
          'Неозначені займенники замінюють іменник: Ist hier ein Löffel? – Ja, hier ist einer. (Так, ось одна.) Nein, hier ist keiner. (Ні, тут жодної.) Nominativ: der Löffel → einer, keiner. Das Messer → eins, keins. Die Gabel → eine, keine. Множина: die Teller → welche (кілька), keine. Так само з mein: Der Löffel? Das ist meiner. (Це моя.) Das Glas? Das ist meins. Die Tasse? Das ist meine.',
          'Belgisiz zamirler bir ismin yerini tutar: Ist hier ein Löffel? – Ja, hier ist einer. (Evet, burada bir tane var.) Nein, hier ist keiner. (Hayır, burada hiç yok.) Nominativ: der Löffel → einer, keiner. Das Messer → eins, keins. Die Gabel → eine, keine. Çoğul: die Teller → welche (birkaç tane), keine. mein ile de aynı: Der Löffel? Das ist meiner. (O benimki.) Das Glas? Das ist meins. Die Tasse? Das ist meine.',
        ],
        hint: ['der → einer, keiner. das → eins, keins. die → eine, keine. Plural → welche, keine.', 'der → einer, keiner. das → eins, keins. die → eine, keine. Plural → welche, keine. (Look at the article of the noun.)', 'der → einer, keiner. das → eins, keins. die → eine, keine. Множественное число → welche, keine.', 'der → einer, keiner. das → eins, keins. die → eine, keine. Множина → welche, keine.', 'der → einer, keiner. das → eins, keins. die → eine, keine. Çoğul → welche, keine.'],
      },
      ex: [
        mc('G1', 'einer', I.choose, 'Ist hier ein Löffel? – Ja, da liegt …', ['einer.', 'eins.', 'eine.'],
          ['Is there a spoon here? – Yes, there is one.', 'Здесь есть ложка? – Да, вот лежит одна.', 'Тут є ложка? – Так, ось лежить одна.', 'Burada kaşık var mı? – Evet, şurada bir tane duruyor.']),
        mc('G1', 'eins', I.choose, 'Wo ist ein Messer? – Hier ist …', ['eins.', 'einer.', 'eine.'],
          ['Where is a knife? – Here is one.', 'Где нож? – Вот один.', 'Де ніж? – Ось один.', 'Bıçak nerede? – İşte bir tane.']),
        mc('G1', 'welche', I.choose, 'Haben wir noch Gläser? – Ja, im Schrank stehen …', ['welche.', 'eine.', 'eins.'],
          ['Do we still have glasses? – Yes, there are some in the cupboard.', 'У нас ещё есть стаканы? – Да, в шкафу стоят.', 'У нас іще є склянки? – Так, у шафі стоять.', 'Daha bardağımız var mı? – Evet, dolapta birkaç tane var.']),
        mc('G1', 'keine', I.choose, 'Gibt es noch eine Tasse? – Nein, hier ist … mehr.', ['keine', 'keiner', 'keins'],
          ['Is there another cup? – No, there is none left here.', 'Есть ещё чашка? – Нет, здесь больше ни одной.', 'Є ще чашка? – Ні, тут більше жодної.', 'Bir fincan daha var mı? – Hayır, burada hiç kalmadı.']),
        mc('G1', 'meins', I.choose, 'Ist das dein Glas? – Ja, das ist …', ['meins.', 'meiner.', 'mein.'],
          ['Is that your glass? – Yes, that is mine.', 'Это твой стакан? – Да, мой.', 'Це твоя склянка? – Так, моя.', 'Bu senin bardağın mı? – Evet, benimki.']),
        gap('G1', 'einer', I.pronoun, 'Ich suche einen Teller. – Auf dem Tisch steht ', '.', 'einer', ['eins', 'eine'],
          ['I am looking for a plate. – There is one on the table.', 'Я ищу тарелку. – На столе стоит одна.', 'Я шукаю тарілку. – На столі стоїть одна.', 'Bir tabak arıyorum. – Masanın üstünde bir tane var.'], 'der Teller'),
        gap('G1', 'keins', I.pronoun, 'Ist noch ein Brötchen da? – Nein, leider ist ', ' mehr da.', 'keins', ['keiner', 'keine'],
          ['Is there a roll left? – No, unfortunately there is none left.', 'Осталась ещё булочка? – Нет, к сожалению, ни одной не осталось.', 'Залишилася ще булочка? – Ні, на жаль, жодної не залишилося.', 'Bir küçük ekmek daha var mı? – Hayır, maalesef hiç kalmadı.'], 'das Brötchen'),
        gap('G1', 'eine', I.pronoun, 'Wo ist eine Gabel? – Dort liegt ', '.', 'eine', ['einer', 'eins'],
          ['Where is a fork? – There is one over there.', 'Где вилка? – Вон там лежит одна.', 'Де виделка? – Он там лежить одна.', 'Çatal nerede? – Orada bir tane duruyor.'], 'die Gabel'),
        gap('G1', 'welche', I.pronoun, 'Sind noch Eier im Kühlschrank? – Ja, da sind noch ', '.', 'welche', ['eine', 'eins'],
          ['Are there any eggs left in the fridge? – Yes, there are still some.', 'В холодильнике ещё есть яйца? – Да, ещё есть.', 'У холодильнику ще є яйця? – Так, іще є.', 'Buzdolabında yumurta kaldı mı? – Evet, hâlâ birkaç tane var.'], 'die Eier (Plural)'),
        gap('G1', 'meiner', I.pronoun, 'Wem gehört der Löffel? – Das ist ', '.', 'meiner', ['meins', 'meine'],
          ['Whose spoon is this? – It is mine.', 'Чья это ложка? – Моя.', 'Чия це ложка? – Моя.', 'Bu kaşık kimin? – Benimki.'], 'der Löffel, mein-'),
      ],
    },
    {
      title: 'Ich brauche einen.',
      t: ['I need one.', 'Мне нужен один.', 'Мені потрібен один.', 'Bir taneye ihtiyacım var.'],
      card: {
        id: 'p3_indef_akk',
        rule: 'Indefinitpronomen im Akkusativ: Nur maskulin ändert sich. Der Löffel → einen, keinen. Das Messer → eins, keins. Die Gabel → eine, keine. Plural → welche, keine. Brauchst du einen Löffel? – Ja, ich brauche einen. Nein, ich brauche keinen. Hast du ein Messer? – Ja, ich habe eins. Möchtest du Nudeln? – Ja, ich nehme welche. Auch mit mein: Nimm meinen! Nimm meins! Nimm meine!',
        examples: ['Möchtest du einen Kaffee? – Ja, ich nehme einen.', 'Hast du ein Glas? – Nein, ich habe keins.', 'Wir brauchen Servietten. – Ich hole welche.'],
        highlight: null,
        t: [
          'Indefinite pronouns in the accusative: only the masculine changes. Der Löffel → einen, keinen. Das Messer → eins, keins. Die Gabel → eine, keine. Plural → welche, keine. Brauchst du einen Löffel? – Ja, ich brauche einen. (Yes, I need one.) Nein, ich brauche keinen. Hast du ein Messer? – Ja, ich habe eins. Möchtest du Nudeln? – Ja, ich nehme welche. (I will take some.) Also with mein: Nimm meinen! Nimm meins! Nimm meine! (Take mine!)',
          'Неопределённые местоимения в Akkusativ: меняется только мужской род. Der Löffel → einen, keinen. Das Messer → eins, keins. Die Gabel → eine, keine. Множественное число → welche, keine. Brauchst du einen Löffel? – Ja, ich brauche einen. (Да, нужна.) Nein, ich brauche keinen. Hast du ein Messer? – Ja, ich habe eins. Möchtest du Nudeln? – Ja, ich nehme welche. (Да, возьму немного.) Так же с mein: Nimm meinen! Nimm meins! Nimm meine! (Возьми мой!)',
          'Неозначені займенники в Akkusativ: змінюється лише чоловічий рід. Der Löffel → einen, keinen. Das Messer → eins, keins. Die Gabel → eine, keine. Множина → welche, keine. Brauchst du einen Löffel? – Ja, ich brauche einen. (Так, потрібна.) Nein, ich brauche keinen. Hast du ein Messer? – Ja, ich habe eins. Möchtest du Nudeln? – Ja, ich nehme welche. (Так, візьму трохи.) Так само з mein: Nimm meinen! Nimm meins! Nimm meine! (Візьми мій!)',
          'Akkusativ’te belgisiz zamirler: Yalnızca eril değişir. Der Löffel → einen, keinen. Das Messer → eins, keins. Die Gabel → eine, keine. Çoğul → welche, keine. Brauchst du einen Löffel? – Ja, ich brauche einen. (Evet, bir taneye ihtiyacım var.) Nein, ich brauche keinen. Hast du ein Messer? – Ja, ich habe eins. Möchtest du Nudeln? – Ja, ich nehme welche. (Evet, biraz alayım.) mein ile de: Nimm meinen! Nimm meins! Nimm meine! (Benimkini al!)',
        ],
        hint: ['Akkusativ: der → einen, keinen. das → eins, keins. die → eine, keine. Plural → welche, keine.', 'Accusative: der → einen, keinen. das → eins, keins. die → eine, keine. Plural → welche, keine. (Only der changes.)', 'Akkusativ: der → einen, keinen. das → eins, keins. die → eine, keine. Множественное число → welche, keine.', 'Akkusativ: der → einen, keinen. das → eins, keins. die → eine, keine. Множина → welche, keine.', 'Akkusativ: der → einen, keinen. das → eins, keins. die → eine, keine. Çoğul → welche, keine.'],
      },
      ex: [
        mc('G2', 'einen', I.choose, 'Brauchst du einen Löffel? – Ja, ich brauche …', ['einen.', 'einer.', 'eins.'],
          ['Do you need a spoon? – Yes, I need one.', 'Тебе нужна ложка? – Да, нужна.', 'Тобі потрібна ложка? – Так, потрібна.', 'Kaşığa ihtiyacın var mı? – Evet, bir taneye ihtiyacım var.']),
        mc('G2', 'keins', I.choose, 'Möchtest du ein Ei? – Nein danke, ich möchte …', ['keins.', 'keinen.', 'keiner.'],
          ['Would you like an egg? – No thanks, I do not want one.', 'Хочешь яйцо? – Нет, спасибо, не хочу.', 'Хочеш яйце? – Ні, дякую, не хочу.', 'Yumurta ister misin? – Hayır, teşekkürler, istemiyorum.']),
        mc('G2', 'welche', I.choose, 'Wir haben keine Tomaten mehr. – Ich gehe einkaufen und hole …', ['welche.', 'welcher.', 'einer.'],
          ['We have no tomatoes left. – I will go shopping and get some.', 'У нас больше нет помидоров. – Я схожу в магазин и куплю.', 'У нас більше немає помідорів. – Я сходжу в магазин і куплю.', 'Domatesimiz kalmadı. – Alışverişe gidip biraz alırım.']),
        mc('G2', 'eine', I.choose, 'Hast du eine Kanne für den Tee? – Ja, ich habe …', ['eine.', 'einen.', 'eins.'],
          ['Do you have a pot for the tea? – Yes, I have one.', 'У тебя есть чайник для чая? – Да, есть.', 'У тебе є чайник для чаю? – Так, є.', 'Çay için demliğin var mı? – Evet, bir tane var.']),
        mc('G2', 'einen', I.choose, 'Die Äpfel sehen lecker aus. Ich nehme …', ['einen.', 'einer.', 'eins.'],
          ['The apples look delicious. I will take one.', 'Яблоки выглядят аппетитно. Я возьму одно.', 'Яблука виглядають апетитно. Я візьму одне.', 'Elmalar lezzetli görünüyor. Bir tane alıyorum.']),
        gap('G2', 'einen', I.pronoun, 'Ich habe keinen Teller. – Warte, ich hole dir ', '.', 'einen', ['einer', 'eins'],
          ['I have no plate. – Wait, I will get you one.', 'У меня нет тарелки. – Подожди, я принесу тебе.', 'У мене немає тарілки. – Зачекай, я принесу тобі.', 'Tabağım yok. – Bekle, sana bir tane getireyim.'], 'der Teller'),
        gap('G2', 'eins', I.pronoun, 'Möchtest du ein Glas Wasser? – Ja, ich nehme gern ', '.', 'eins', ['einen', 'eine'],
          ['Would you like a glass of water? – Yes, I would like one.', 'Хочешь стакан воды? – Да, с удовольствием.', 'Хочеш склянку води? – Так, охоче.', 'Bir bardak su ister misin? – Evet, bir tane alayım.'], 'das Glas'),
        gap('G2', 'keine', I.pronoun, 'Brauchst du eine Gabel? – Nein danke, ich brauche ', '.', 'keine', ['keinen', 'keins'],
          ['Do you need a fork? – No thanks, I do not need one.', 'Тебе нужна вилка? – Нет, спасибо, не нужна.', 'Тобі потрібна виделка? – Ні, дякую, не потрібна.', 'Çatala ihtiyacın var mı? – Hayır, teşekkürler, ihtiyacım yok.'], 'die Gabel'),
        gap('G2', 'keinen', I.pronoun, 'Hast du einen Topf für die Suppe? – Nein, ich habe ', '.', 'keinen', ['keiner', 'keins'],
          ['Do you have a pot for the soup? – No, I do not have one.', 'У тебя есть кастрюля для супа? – Нет, у меня нет.', 'У тебе є каструля для супу? – Ні, у мене немає.', 'Çorba için tenceren var mı? – Hayır, yok.'], 'der Topf'),
        gap('G2', 'meins', I.pronoun, 'Mein Messer ist weg. – Nimm ', '! Ich brauche es nicht.', 'meins', ['meinen', 'meiner'],
          ['My knife is gone. – Take mine! I do not need it.', 'Мой нож пропал. – Возьми мой! Он мне не нужен.', 'Мій ніж зник. – Візьми мій! Він мені не потрібен.', 'Bıçağım kayboldu. – Benimkini al! Ona ihtiyacım yok.'], 'das Messer, mein-'),
      ],
    },
    {
      title: 'Zu Gast bei Freunden',
      t: ['A meal at friends’', 'В гостях у друзей', 'У гостях у друзів', 'Arkadaşlarda misafirlik'],
      card: {
        id: 'p3_gast',
        rule: 'Eine private Einladung zum Essen. Ankunft: Die Blumen sind für dich. – Oh, danke, das ist aber nett! Soll ich die Schuhe ausziehen? – Ja, bitte. / Nein, lass sie ruhig an. Beim Essen: Das riecht so lecker! Guten Appetit! Möchtest du noch etwas? Darf ich dir noch etwas geben? – Ja, gern. / Nein danke, ich kann nicht mehr. Danke fürs Kochen! Abschied: Vielen Dank für den schönen Abend. – Komm bald mal wieder! Kommt gut nach Hause! Das nächste Mal kommt ihr zu mir.',
        examples: ['Die Blumen sind für Sie. – Das ist aber nett!', 'Möchtest du noch Suppe? – Nein danke, ich kann nicht mehr.', 'Vielen Dank für den schönen Abend!'],
        highlight: null,
        t: [
          'A private invitation to a meal. Arriving: Die Blumen sind für dich. (The flowers are for you.) – Oh, danke, das ist aber nett! (How kind!) Soll ich die Schuhe ausziehen? (Shall I take my shoes off?) – Ja, bitte. / Nein, lass sie ruhig an. (No, just keep them on.) During the meal: Das riecht so lecker! (That smells so good!) Guten Appetit! Möchtest du noch etwas? Darf ich dir noch etwas geben? (May I give you some more?) – Ja, gern. / Nein danke, ich kann nicht mehr. (I am full.) Danke fürs Kochen! Leaving: Vielen Dank für den schönen Abend. – Komm bald mal wieder! (Come again soon!) Kommt gut nach Hause! (Get home safely!) Das nächste Mal kommt ihr zu mir.',
          'Приглашение на обед или ужин домой. Приход: Die Blumen sind für dich. (Цветы для тебя.) – Oh, danke, das ist aber nett! (Как мило!) Soll ich die Schuhe ausziehen? (Мне разуться?) – Ja, bitte. / Nein, lass sie ruhig an. (Нет, можешь не разуваться.) За столом: Das riecht so lecker! (Как вкусно пахнет!) Guten Appetit! Möchtest du noch etwas? Darf ich dir noch etwas geben? (Положить тебе ещё?) – Ja, gern. / Nein danke, ich kann nicht mehr. (Я больше не могу.) Danke fürs Kochen! Прощание: Vielen Dank für den schönen Abend. – Komm bald mal wieder! (Приходи ещё!) Kommt gut nach Hause! (Счастливо добраться!) Das nächste Mal kommt ihr zu mir.',
          'Запрошення на обід чи вечерю додому. Прихід: Die Blumen sind für dich. (Квіти для тебе.) – Oh, danke, das ist aber nett! (Як мило!) Soll ich die Schuhe ausziehen? (Мені роззутися?) – Ja, bitte. / Nein, lass sie ruhig an. (Ні, можеш не роззуватися.) За столом: Das riecht so lecker! (Як смачно пахне!) Guten Appetit! Möchtest du noch etwas? Darf ich dir noch etwas geben? (Покласти тобі ще?) – Ja, gern. / Nein danke, ich kann nicht mehr. (Я більше не можу.) Danke fürs Kochen! Прощання: Vielen Dank für den schönen Abend. – Komm bald mal wieder! (Приходь іще!) Kommt gut nach Hause! (Щасливо дістатися додому!) Das nächste Mal kommt ihr zu mir.',
          'Eve yemeğe davet. Varış: Die Blumen sind für dich. (Çiçekler senin için.) – Oh, danke, das ist aber nett! (Ne kadar naziksin!) Soll ich die Schuhe ausziehen? (Ayakkabılarımı çıkarayım mı?) – Ja, bitte. / Nein, lass sie ruhig an. (Hayır, kalsın.) Yemekte: Das riecht so lecker! (Ne güzel kokuyor!) Guten Appetit! Möchtest du noch etwas? Darf ich dir noch etwas geben? (Sana biraz daha vereyim mi?) – Ja, gern. / Nein danke, ich kann nicht mehr. (Doydum.) Danke fürs Kochen! Vedalaşma: Vielen Dank für den schönen Abend. – Komm bald mal wieder! (Yine gel!) Kommt gut nach Hause! (Evinize iyi gidin!) Das nächste Mal kommt ihr zu mir.',
        ],
        hint: ['Ankunft: schenken und danken. Beim Essen: loben, anbieten, annehmen oder ablehnen. Abschied: danken und wieder einladen.', 'Arriving: giving and thanking. During the meal: praising, offering, accepting or declining. Leaving: thanking and inviting again.', 'Приход: подарить и поблагодарить. За столом: похвалить, предложить, согласиться или отказаться. Прощание: поблагодарить и пригласить снова.', 'Прихід: подарувати й подякувати. За столом: похвалити, запропонувати, погодитися або відмовитися. Прощання: подякувати й запросити знову.', 'Varış: hediye vermek ve teşekkür etmek. Yemekte: övmek, ikram etmek, kabul etmek ya da reddetmek. Vedalaşma: teşekkür etmek ve yeniden davet etmek.'],
      },
      ex: [
        mc('K2', 'Ankunft', I.situation, 'Du kommst zu Freunden zum Essen und gibst ihnen Blumen. Was sagst du?', ['Die Blumen sind für euch.', 'Die Blumen sind lecker.', 'Die Blumen kosten zehn Euro.'],
          ['You arrive at your friends’ for a meal and give them flowers. What do you say?', 'Вы пришли к друзьям на ужин и дарите им цветы. Что вы скажете?', 'Ви прийшли до друзів на вечерю й даруєте їм квіти. Що ви скажете?', 'Arkadaşlarınıza yemeğe geliyorsunuz ve onlara çiçek veriyorsunuz. Ne dersiniz?']),
        mc('K2', 'sich bedanken', I.react, '„Die Pralinen sind für dich.“', ['Oh, danke! Das ist aber nett.', 'Nein danke, ich kann nicht mehr.', 'Kommt gut nach Hause!'],
          ['“The chocolates are for you.”', '«Конфеты для тебя».', '«Цукерки для тебе».', '“Çikolatalar senin için.”']),
        mc('K2', 'Schuhe', I.react, '„Soll ich die Schuhe ausziehen?“', ['Nein, lass sie ruhig an.', 'Ja, gern, guten Appetit!', 'Danke fürs Kochen.'],
          ['“Shall I take my shoes off?”', '«Мне разуться?»', '«Мені роззутися?»', '“Ayakkabılarımı çıkarayım mı?”']),
        mc('K2', 'ablehnen', I.react, 'Du bist satt. Die Gastgeberin fragt: „Möchtest du noch Reis?“', ['Nein danke, ich kann nicht mehr.', 'Ja, bitte, ich habe großen Hunger.', 'Kein Problem.'],
          ['You are full. The hostess asks: “Would you like some more rice?”', 'Вы сыты. Хозяйка спрашивает: «Хочешь ещё риса?»', 'Ви ситі. Господиня питає: «Хочеш іще рису?»', 'Doydunuz. Ev sahibi soruyor: “Biraz daha pilav ister misin?”']),
        mc('K2', 'Abschied', I.situation, 'Der Abend ist zu Ende. Du gehst nach Hause. Was sagst du?', ['Vielen Dank für den schönen Abend!', 'Guten Appetit!', 'Soll ich die Schuhe ausziehen?'],
          ['The evening is over. You are going home. What do you say?', 'Вечер закончился. Вы уходите домой. Что вы скажете?', 'Вечір закінчився. Ви йдете додому. Що ви скажете?', 'Akşam sona erdi. Eve gidiyorsunuz. Ne dersiniz?']),
        mc('K2', 'Abschied', I.situation, 'Deine Gäste gehen. Was sagst du?', ['Kommt gut nach Hause!', 'Kommt doch rein!', 'Nehmt doch Platz!'],
          ['Your guests are leaving. What do you say?', 'Ваши гости уходят. Что вы скажете?', 'Ваші гості йдуть. Що ви скажете?', 'Misafirleriniz gidiyor. Ne dersiniz?']),
        gap('K2', 'Das riecht lecker', I.verb, 'Du kochst gerade? Mmh, das ', ' aber lecker!', 'riecht', ['hört', 'sieht'],
          ['Are you cooking right now? Mmm, that smells delicious!', 'Ты сейчас готовишь? М-м, как вкусно пахнет!', 'Ти зараз готуєш? М-м, як смачно пахне!', 'Şu anda yemek mi yapıyorsun? Mmm, ne güzel kokuyor!'],
          ['smells', 'пахнет', 'пахне', 'kokuyor']),
        gap('K2', 'Guten Appetit', I.word, 'Das Essen steht auf dem Tisch. Guten ', '!', 'Appetit', ['Durst', 'Teller'],
          ['The food is on the table. Enjoy your meal!', 'Еда на столе. Приятного аппетита!', 'Їжа на столі. Смачного!', 'Yemek masada. Afiyet olsun!'],
          ['enjoy your meal', 'приятного аппетита', 'смачного', 'afiyet olsun']),
        gap('K2', 'Danke fürs Kochen', I.word, 'Danke ', ' Kochen! Es war sehr lecker.', 'fürs', ['für', 'vom'],
          ['Thank you for cooking! It was delicious.', 'Спасибо за ужин! Было очень вкусно.', 'Дякую за вечерю! Було дуже смачно.', 'Yemek için teşekkürler! Çok lezzetliydi.'], 'für + das'),
        sb('K2', 'anbieten', I.question, 'Darf / ich / dir / noch etwas / geben?',
          ['May I give you some more?', 'Положить тебе ещё?', 'Покласти тобі ще?', 'Sana biraz daha vereyim mi?']),
      ],
    },
    {
      title: 'Ist hier noch frei?',
      t: ['Is this seat free?', 'Здесь свободно?', 'Тут вільно?', 'Burası boş mu?'],
      card: {
        id: 'p3_restaurant',
        rule: 'Im Restaurant. Einen Platz suchen: Ist hier noch frei? Ist der Platz noch frei? – Ja, sicher. Nehmen Sie doch Platz. Setzen Sie sich doch. / Nein, tut mir leid, der Platz ist besetzt. Bestellen: Kann ich bitte die Karte haben? Wir möchten bitte bestellen. – Was darf ich Ihnen bringen? – Ich nehme die Suppe. Ich möchte ein Wasser. Für mich bitte den Salat. Nach ich nehme und ich möchte steht der Akkusativ: den Salat, einen Tee.',
        examples: ['Entschuldigung, ist hier noch frei? – Ja, bitte.', 'Was darf ich Ihnen bringen?', 'Ich nehme den Fisch und ein Wasser.'],
        highlight: null,
        t: [
          'In a restaurant. Looking for a seat: Ist hier noch frei? Ist der Platz noch frei? (Is this seat free?) – Ja, sicher. Nehmen Sie doch Platz. Setzen Sie sich doch. (Do sit down.) / Nein, tut mir leid, der Platz ist besetzt. (taken) Ordering: Kann ich bitte die Karte haben? (the menu) Wir möchten bitte bestellen. (order) – Was darf ich Ihnen bringen? (What can I get you?) – Ich nehme die Suppe. Ich möchte ein Wasser. Für mich bitte den Salat. After ich nehme and ich möchte comes the accusative: den Salat, einen Tee.',
          'В ресторане. Как найти место: Ist hier noch frei? Ist der Platz noch frei? (Здесь свободно?) – Ja, sicher. Nehmen Sie doch Platz. Setzen Sie sich doch. (Садитесь, пожалуйста.) / Nein, tut mir leid, der Platz ist besetzt. (занято) Как заказать: Kann ich bitte die Karte haben? (меню) Wir möchten bitte bestellen. (сделать заказ) – Was darf ich Ihnen bringen? (Что вам принести?) – Ich nehme die Suppe. Ich möchte ein Wasser. Für mich bitte den Salat. После ich nehme и ich möchte стоит Akkusativ: den Salat, einen Tee.',
          'У ресторані. Як знайти місце: Ist hier noch frei? Ist der Platz noch frei? (Тут вільно?) – Ja, sicher. Nehmen Sie doch Platz. Setzen Sie sich doch. (Сідайте, будь ласка.) / Nein, tut mir leid, der Platz ist besetzt. (зайнято) Як замовити: Kann ich bitte die Karte haben? (меню) Wir möchten bitte bestellen. (зробити замовлення) – Was darf ich Ihnen bringen? (Що вам принести?) – Ich nehme die Suppe. Ich möchte ein Wasser. Für mich bitte den Salat. Після ich nehme та ich möchte стоїть Akkusativ: den Salat, einen Tee.',
          'Restoranda. Yer aramak: Ist hier noch frei? Ist der Platz noch frei? (Burası boş mu?) – Ja, sicher. Nehmen Sie doch Platz. Setzen Sie sich doch. (Buyurun, oturun.) / Nein, tut mir leid, der Platz ist besetzt. (dolu) Sipariş vermek: Kann ich bitte die Karte haben? (menü) Wir möchten bitte bestellen. (sipariş vermek) – Was darf ich Ihnen bringen? (Size ne getireyim?) – Ich nehme die Suppe. Ich möchte ein Wasser. Für mich bitte den Salat. ich nehme ve ich möchte’den sonra Akkusativ gelir: den Salat, einen Tee.',
        ],
        hint: ['frei ↔ besetzt. Bestellen: Ich nehme … / Ich möchte … + Akkusativ.', 'frei (free) ↔ besetzt (taken). Ordering: Ich nehme … / Ich möchte … + accusative.', 'frei (свободно) ↔ besetzt (занято). Заказ: Ich nehme … / Ich möchte … + Akkusativ.', 'frei (вільно) ↔ besetzt (зайнято). Замовлення: Ich nehme … / Ich möchte … + Akkusativ.', 'frei (boş) ↔ besetzt (dolu). Sipariş: Ich nehme … / Ich möchte … + Akkusativ.'],
      },
      ex: [
        mc('K3', 'Platz suchen', I.situation, 'Du suchst im Restaurant einen Platz. An einem Tisch sitzt schon ein Mann. Was fragst du?', ['Entschuldigung, ist hier noch frei?', 'Was darf ich Ihnen bringen?', 'Zahlen, bitte!'],
          ['You are looking for a seat in a restaurant. A man is already sitting at one table. What do you ask?', 'Вы ищете место в ресторане. За одним столом уже сидит мужчина. Что вы спросите?', 'Ви шукаєте місце в ресторані. За одним столом уже сидить чоловік. Що ви запитаєте?', 'Restoranda yer arıyorsunuz. Bir masada bir adam oturuyor. Ne sorarsınız?']),
        mc('K3', 'besetzt', I.react, '„Ist der Platz noch frei?“ – Deine Freundin kommt gleich und sitzt dort.', ['Nein, tut mir leid, der ist besetzt.', 'Ja, sicher, nehmen Sie doch Platz.', 'Ich nehme die Suppe.'],
          ['“Is this seat free?” – Your friend is coming in a moment and sits there.', '«Это место свободно?» – Ваша подруга сейчас придёт, она сидит там.', '«Це місце вільне?» – Ваша подруга зараз прийде, вона сидить там.', '“Bu yer boş mu?” – Arkadaşınız birazdan gelecek ve orada oturuyor.']),
        mc('K3', 'Kellner', I.choose, 'Wer sagt das? „Was darf ich Ihnen bringen?“', ['Der Kellner.', 'Der Gast.', 'Der Koch.'],
          ['Who says this? “What can I get you?”', 'Кто это говорит? «Что вам принести?»', 'Хто це каже? «Що вам принести?»', 'Bunu kim söyler? “Size ne getireyim?”']),
        mc('K3', 'die Karte', I.situation, 'Du möchtest wissen, was es zu essen gibt. Was sagst du zum Kellner?', ['Kann ich bitte die Karte haben?', 'Kann ich bitte die Rechnung haben?', 'Ist hier noch frei?'],
          ['You want to know what there is to eat. What do you say to the waiter?', 'Вы хотите узнать, что есть в меню. Что вы скажете официанту?', 'Ви хочете дізнатися, що є в меню. Що ви скажете офіціантові?', 'Yiyecek ne olduğunu öğrenmek istiyorsunuz. Garsona ne dersiniz?']),
        mc('K3', 'bestellen', I.react, '„Was möchten Sie trinken?“', ['Ich nehme einen Apfelsaft.', 'Ich nehme Platz.', 'Ja, hier ist frei.'],
          ['“What would you like to drink?”', '«Что вы будете пить?»', '«Що ви будете пити?»', '“Ne içmek istersiniz?”']),
        gap('K3', 'besetzt', I.word, 'Der Tisch ist nicht frei. Er ist ', '.', 'besetzt', ['bestellt', 'geschlossen'],
          ['The table is not free. It is taken.', 'Стол не свободен. Он занят.', 'Стіл не вільний. Він зайнятий.', 'Masa boş değil. Dolu.'],
          ['taken, occupied', 'занят', 'зайнятий', 'dolu']),
        gap('K3', 'Platz nehmen', I.word, 'Guten Abend! Nehmen Sie doch ', '.', 'Platz', ['Tisch', 'Karte'],
          ['Good evening! Do take a seat.', 'Добрый вечер! Садитесь, пожалуйста.', 'Добрий вечір! Сідайте, будь ласка.', 'İyi akşamlar! Buyurun, oturun.'],
          ['a seat', 'место', 'місце', 'yer']),
        gap('K3', 'Akkusativ', I.article, 'Ich nehme ', ' Salat mit Käse, bitte.', 'den', ['der', 'dem'],
          ['I will have the salad with cheese, please.', 'Мне, пожалуйста, салат с сыром.', 'Мені, будь ласка, салат із сиром.', 'Peynirli salata alayım lütfen.'], 'der Salat'),
        gap('K3', 'bestellen', I.verb, 'Wir möchten bitte ', '. – Gern. Was bekommen Sie?', 'bestellen', ['bezahlen', 'besuchen'],
          ['We would like to order, please. – Certainly. What will you have?', 'Мы хотели бы сделать заказ. – Пожалуйста. Что вы будете?', 'Ми хотіли б зробити замовлення. – Будь ласка. Що ви будете?', 'Sipariş vermek istiyoruz lütfen. – Tabii. Ne alırsınız?'],
          ['order', 'заказывать', 'замовляти', 'sipariş vermek']),
        sb('K3', 'die Karte', I.question, 'Kann / ich / bitte / die Karte / haben?',
          ['May I have the menu, please?', 'Можно мне меню, пожалуйста?', 'Можна мені меню, будь ласка?', 'Menüyü alabilir miyim lütfen?'],
          { alt: ['Kann ich die Karte bitte haben?'] }),
      ],
    },
    {
      title: 'Die Suppe ist kalt!',
      t: ['The soup is cold!', 'Суп холодный!', 'Суп холодний!', 'Çorba soğuk!'],
      card: {
        id: 'p3_reklamieren',
        rule: 'Im Restaurant reklamieren: höflich beginnen, dann das Problem nennen. Entschuldigung, aber die Suppe ist leider kalt. Verzeihung, das Fleisch ist viel zu salzig. Das Messer ist nicht sauber. Ich habe keinen Löffel. Ich warte schon 40 Minuten auf das Essen. Ich habe einen Salat bestellt, keinen Fisch. Die Antwort: Oh, das tut mir leid. Ich bringe Ihnen sofort eine neue Suppe. Ich bringe Ihnen ein anderes Messer.',
        examples: ['Entschuldigung, aber der Kaffee ist kalt.', 'Die Gabel ist nicht sauber. – Oh, ich bringe sofort eine andere.', 'Wir warten schon eine halbe Stunde.'],
        highlight: null,
        t: [
          'Complaining in a restaurant: begin politely, then name the problem. Entschuldigung, aber die Suppe ist leider kalt. Verzeihung, das Fleisch ist viel zu salzig. (far too salty) Das Messer ist nicht sauber. (not clean) Ich habe keinen Löffel. Ich warte schon 40 Minuten auf das Essen. (I have been waiting for the food for 40 minutes.) Ich habe einen Salat bestellt, keinen Fisch. The answer: Oh, das tut mir leid. Ich bringe Ihnen sofort eine neue Suppe. Ich bringe Ihnen ein anderes Messer.',
          'Как пожаловаться в ресторане: начните вежливо, затем назовите проблему. Entschuldigung, aber die Suppe ist leider kalt. Verzeihung, das Fleisch ist viel zu salzig. (слишком солёное) Das Messer ist nicht sauber. (нечистый) Ich habe keinen Löffel. Ich warte schon 40 Minuten auf das Essen. (Я уже 40 минут жду еду.) Ich habe einen Salat bestellt, keinen Fisch. Ответ: Oh, das tut mir leid. Ich bringe Ihnen sofort eine neue Suppe. Ich bringe Ihnen ein anderes Messer.',
          'Як поскаржитися в ресторані: почніть ввічливо, потім назвіть проблему. Entschuldigung, aber die Suppe ist leider kalt. Verzeihung, das Fleisch ist viel zu salzig. (занадто солоне) Das Messer ist nicht sauber. (нечистий) Ich habe keinen Löffel. Ich warte schon 40 Minuten auf das Essen. (Я вже 40 хвилин чекаю на їжу.) Ich habe einen Salat bestellt, keinen Fisch. Відповідь: Oh, das tut mir leid. Ich bringe Ihnen sofort eine neue Suppe. Ich bringe Ihnen ein anderes Messer.',
          'Restoranda şikâyet etmek: Kibarca başlayın, sonra sorunu söyleyin. Entschuldigung, aber die Suppe ist leider kalt. Verzeihung, das Fleisch ist viel zu salzig. (fazla tuzlu) Das Messer ist nicht sauber. (temiz değil) Ich habe keinen Löffel. Ich warte schon 40 Minuten auf das Essen. (40 dakikadır yemeği bekliyorum.) Ich habe einen Salat bestellt, keinen Fisch. Cevap: Oh, das tut mir leid. Ich bringe Ihnen sofort eine neue Suppe. Ich bringe Ihnen ein anderes Messer.',
        ],
        hint: ['zu salzig, zu kalt, zu scharf = mehr als gut. nicht sauber = schmutzig.', 'zu salzig, zu kalt, zu scharf = more than is good. nicht sauber = dirty.', 'zu salzig, zu kalt, zu scharf = слишком. nicht sauber = грязный.', 'zu salzig, zu kalt, zu scharf = занадто. nicht sauber = брудний.', 'zu salzig, zu kalt, zu scharf = gereğinden fazla. nicht sauber = kirli.'],
      },
      ex: [
        mc('K4', 'höflich reklamieren', I.situation, 'Deine Suppe ist kalt. Was sagst du zum Kellner?', ['Entschuldigung, aber die Suppe ist leider kalt.', 'Vielen Dank, die Suppe ist sehr lecker.', 'Ich nehme die Suppe.'],
          ['Your soup is cold. What do you say to the waiter?', 'Ваш суп холодный. Что вы скажете официанту?', 'Ваш суп холодний. Що ви скажете офіціантові?', 'Çorbanız soğuk. Garsona ne dersiniz?']),
        mc('K4', 'zu salzig', I.choose, 'Im Essen ist sehr viel Salz. Das Essen ist …', ['zu salzig', 'zu süß', 'zu kalt'],
          ['There is a great deal of salt in the food. The food is …', 'В еде очень много соли. Еда …', 'У їжі дуже багато солі. Їжа …', 'Yemekte çok fazla tuz var. Yemek …']),
        mc('K4', 'auf eine Reklamation antworten', I.react, '„Entschuldigung, mein Glas ist nicht sauber.“', ['Oh, das tut mir leid. Ich bringe Ihnen sofort ein anderes.', 'Guten Appetit!', 'Das macht 12 Euro.'],
          ['“Excuse me, my glass is not clean.”', '«Извините, мой стакан грязный».', '«Вибачте, моя склянка брудна».', '“Affedersiniz, bardağım temiz değil.”']),
        mc('K4', 'lange warten', I.situation, 'Du hast vor 45 Minuten bestellt. Das Essen ist noch nicht da. Was sagst du?', ['Entschuldigung, wir warten schon sehr lange auf das Essen.', 'Entschuldigung, wir möchten bitte bestellen.', 'Das Essen schmeckt sehr gut.'],
          ['You ordered 45 minutes ago. The food has not come yet. What do you say?', 'Вы сделали заказ 45 минут назад. Еду ещё не принесли. Что вы скажете?', 'Ви зробили замовлення 45 хвилин тому. Їжу ще не принесли. Що ви скажете?', '45 dakika önce sipariş verdiniz. Yemek hâlâ gelmedi. Ne dersiniz?']),
        mc('K4', 'falsche Bestellung', I.situation, 'Du hast Nudeln bestellt. Der Kellner bringt Reis. Was sagst du?', ['Entschuldigung, ich habe Nudeln bestellt, keinen Reis.', 'Vielen Dank, der Reis ist für mich.', 'Der Reis ist zu salzig.'],
          ['You ordered pasta. The waiter brings rice. What do you say?', 'Вы заказали макароны. Официант приносит рис. Что вы скажете?', 'Ви замовили макарони. Офіціант приносить рис. Що ви скажете?', 'Makarna sipariş ettiniz. Garson pilav getiriyor. Ne dersiniz?']),
        gap('K4', 'sauber', I.word, 'Die Gabel ist schmutzig. Sie ist nicht ', '.', 'sauber', ['salzig', 'scharf'],
          ['The fork is dirty. It is not clean.', 'Вилка грязная. Она нечистая.', 'Виделка брудна. Вона нечиста.', 'Çatal kirli. Temiz değil.'],
          ['clean', 'чистый', 'чистий', 'temiz']),
        gap('K4', 'viel zu', I.word, 'Entschuldigung, die Soße ist viel ', ' scharf. Ich kann sie nicht essen.', 'zu', ['sehr', 'so'],
          ['Excuse me, the sauce is far too hot. I cannot eat it.', 'Извините, соус слишком острый. Я не могу его есть.', 'Вибачте, соус занадто гострий. Я не можу його їсти.', 'Affedersiniz, sos çok fazla acı. Yiyemiyorum.'], 'zu / sehr / so'),
        gap('K4', 'warten auf', I.prep, 'Wir warten schon 30 Minuten ', ' die Getränke.', 'auf', ['für', 'an'],
          ['We have been waiting for the drinks for 30 minutes.', 'Мы уже 30 минут ждём напитки.', 'Ми вже 30 хвилин чекаємо на напої.', '30 dakikadır içecekleri bekliyoruz.'], 'auf / für / an'),
        gap('K4', 'antworten', I.verb, 'Oh, das tut mir leid. Ich ', ' Ihnen sofort eine neue Suppe.', 'bringe', ['bringt', 'bringen'],
          ['Oh, I am sorry. I will bring you a new soup right away.', 'Ой, простите. Я сейчас же принесу вам другой суп.', 'Ой, перепрошую. Я зараз же принесу вам інший суп.', 'Ah, özür dilerim. Size hemen yeni bir çorba getiriyorum.'], 'bringen'),
        sb('K4', 'nicht sauber', I.order, 'Das Messer / ist / leider / nicht / sauber.',
          ['Unfortunately the knife is not clean.', 'К сожалению, нож грязный.', 'На жаль, ніж брудний.', 'Maalesef bıçak temiz değil.'],
          { alt: ['Leider ist das Messer nicht sauber.'] }),
      ],
    },
    {
      title: 'Zahlen, bitte!',
      t: ['The bill, please!', 'Счёт, пожалуйста!', 'Рахунок, будь ласка!', 'Hesap lütfen!'],
      card: {
        id: 'p3_zahlen',
        rule: 'Im Restaurant bezahlen: Zahlen, bitte! Die Rechnung, bitte! Ich möchte bitte bezahlen. Der Kellner fragt: Zusammen oder getrennt? Zusammen: Eine Person bezahlt alles. Getrennt: Jeder bezahlt sein Essen. Das macht 18,40 Euro. Trinkgeld geben: Stimmt so. (Der Rest ist für Sie.) Machen Sie 20, bitte. (Ich bezahle 20 Euro.)',
        examples: ['Zahlen, bitte! – Zusammen oder getrennt?', 'Das macht 27,50 Euro. – Machen Sie 30, bitte.', 'Hier sind 20 Euro. Stimmt so.'],
        highlight: null,
        t: [
          'Paying in a restaurant: Zahlen, bitte! Die Rechnung, bitte! (The bill, please!) Ich möchte bitte bezahlen. The waiter asks: Zusammen oder getrennt? Zusammen (together): one person pays for everything. Getrennt (separately): everyone pays for their own meal. Das macht 18,40 Euro. (That comes to …) Giving a tip (das Trinkgeld): Stimmt so. (Keep the change.) Machen Sie 20, bitte. (Make it 20, please: I pay 20 euros.)',
          'Как расплатиться в ресторане: Zahlen, bitte! Die Rechnung, bitte! (Счёт, пожалуйста!) Ich möchte bitte bezahlen. Официант спрашивает: Zusammen oder getrennt? Zusammen (вместе): один человек платит за всё. Getrennt (раздельно): каждый платит за себя. Das macht 18,40 Euro. (С вас …) Чаевые (das Trinkgeld): Stimmt so. (Сдачи не надо.) Machen Sie 20, bitte. (Пусть будет 20: я плачу 20 евро.)',
          'Як розрахуватися в ресторані: Zahlen, bitte! Die Rechnung, bitte! (Рахунок, будь ласка!) Ich möchte bitte bezahlen. Офіціант питає: Zusammen oder getrennt? Zusammen (разом): одна людина платить за все. Getrennt (окремо): кожен платить за себе. Das macht 18,40 Euro. (З вас …) Чайові (das Trinkgeld): Stimmt so. (Решти не треба.) Machen Sie 20, bitte. (Нехай буде 20: я плачу 20 євро.)',
          'Restoranda ödemek: Zahlen, bitte! Die Rechnung, bitte! (Hesap lütfen!) Ich möchte bitte bezahlen. Garson sorar: Zusammen oder getrennt? Zusammen (birlikte): Bir kişi her şeyi öder. Getrennt (ayrı ayrı): Herkes kendi yemeğini öder. Das macht 18,40 Euro. (… tutuyor.) Bahşiş (das Trinkgeld) vermek: Stimmt so. (Üstü kalsın.) Machen Sie 20, bitte. (20 olsun lütfen: 20 avro ödüyorum.)',
        ],
        hint: ['Stimmt so. = Der Rest ist Trinkgeld. Machen Sie 20. = Ich zahle 20 Euro mit Trinkgeld.', 'Stimmt so. = the rest is a tip. Machen Sie 20. = I pay 20 euros including the tip.', 'Stimmt so. = сдача остаётся как чаевые. Machen Sie 20. = я плачу 20 евро вместе с чаевыми.', 'Stimmt so. = решта залишається як чайові. Machen Sie 20. = я плачу 20 євро разом із чайовими.', 'Stimmt so. = para üstü bahşiş olarak kalır. Machen Sie 20. = bahşişle birlikte 20 avro ödüyorum.'],
      },
      ex: [
        mc('K5', 'zahlen', I.situation, 'Du bist fertig mit dem Essen und möchtest gehen. Was sagst du zum Kellner?', ['Zahlen, bitte!', 'Guten Appetit!', 'Ist hier noch frei?'],
          ['You have finished your meal and want to leave. What do you say to the waiter?', 'Вы поели и хотите уйти. Что вы скажете официанту?', 'Ви поїли й хочете піти. Що ви скажете офіціантові?', 'Yemeğinizi bitirdiniz ve gitmek istiyorsunuz. Garsona ne dersiniz?']),
        mc('K5', 'zusammen', I.react, '„Zusammen oder getrennt?“ – Du bezahlst für alle.', ['Zusammen, bitte.', 'Getrennt, bitte.', 'Stimmt so.'],
          ['“Together or separately?” – You are paying for everyone.', '«Вместе или раздельно?» – Вы платите за всех.', '«Разом чи окремо?» – Ви платите за всіх.', '“Birlikte mi, ayrı ayrı mı?” – Herkesin hesabını siz ödüyorsunuz.']),
        mc('K5', 'Stimmt so', I.situation, 'Die Rechnung ist 18,40 Euro. Du gibst 20 Euro und möchtest kein Geld zurück. Was sagst du?', ['Stimmt so.', 'Zahlen, bitte.', 'Getrennt, bitte.'],
          ['The bill is 18.40 euros. You give 20 euros and do not want any change. What do you say?', 'Счёт – 18,40 евро. Вы даёте 20 евро и не хотите сдачи. Что вы скажете?', 'Рахунок – 18,40 євро. Ви даєте 20 євро й не хочете решти. Що ви скажете?', 'Hesap 18,40 avro. 20 avro veriyorsunuz ve para üstü istemiyorsunuz. Ne dersiniz?']),
        mc('K5', 'Trinkgeld', I.choose, 'Die Rechnung ist 27,50 Euro. Du sagst: „Machen Sie 30, bitte.“ Wie viel Trinkgeld gibst du?', ['2,50 Euro', '30 Euro', '27,50 Euro'],
          ['The bill is 27.50 euros. You say: “Make it 30, please.” How much is your tip?', 'Счёт – 27,50 евро. Вы говорите: «Пусть будет 30». Сколько чаевых вы оставляете?', 'Рахунок – 27,50 євро. Ви кажете: «Нехай буде 30». Скільки чайових ви залишаєте?', 'Hesap 27,50 avro. “30 olsun lütfen.” diyorsunuz. Ne kadar bahşiş veriyorsunuz?']),
        mc('K5', 'getrennt', I.choose, 'Jeder bezahlt nur sein Essen. Wir zahlen …', ['getrennt', 'zusammen', 'sofort'],
          ['Everyone pays only for their own meal. We are paying …', 'Каждый платит только за свою еду. Мы платим …', 'Кожен платить лише за свою їжу. Ми платимо …', 'Herkes sadece kendi yemeğini ödüyor. Biz … ödüyoruz.']),
        gap('K5', 'Rechnung', I.word, 'Die ', ', bitte! Wir möchten bezahlen.', 'Rechnung', ['Vorspeise', 'Bestellung'],
          ['The bill, please! We would like to pay.', 'Счёт, пожалуйста! Мы хотели бы расплатиться.', 'Рахунок, будь ласка! Ми хотіли б розрахуватися.', 'Hesap lütfen! Ödemek istiyoruz.'],
          ['bill', 'счёт', 'рахунок', 'hesap']),
        gap('K5', 'Das macht …', I.verb, 'Zwei Suppen und zwei Wasser. Das ', ' zusammen 19 Euro.', ['macht', 'kostet'], ['zahlt', 'gibt'],
          ['Two soups and two waters. That comes to 19 euros altogether.', 'Два супа и две воды. Всего с вас 19 евро.', 'Два супи й дві води. Разом із вас 19 євро.', 'İki çorba ve iki su. Toplam 19 avro tutuyor.'], 'machen'),
        gap('K5', 'Stimmt so', I.word, 'Hier sind 50 Euro. ', ' so.', 'Stimmt', ['Macht', 'Zahlt'],
          ['Here are 50 euros. Keep the change.', 'Вот 50 евро. Сдачи не надо.', 'Ось 50 євро. Решти не треба.', 'Buyurun 50 avro. Üstü kalsın.'],
          ['keep the change', 'сдачи не надо', 'решти не треба', 'üstü kalsın']),
        gap('K5', 'getrennt', I.word, 'Zahlen Sie zusammen? – Nein, ', ', bitte. Jeder zahlt für sich.', 'getrennt', ['allein', 'geteilt'],
          ['Are you paying together? – No, separately, please. Everyone pays for themselves.', 'Вы платите вместе? – Нет, раздельно, пожалуйста. Каждый платит за себя.', 'Ви платите разом? – Ні, окремо, будь ласка. Кожен платить за себе.', 'Birlikte mi ödüyorsunuz? – Hayır, ayrı ayrı lütfen. Herkes kendi hesabını ödüyor.'],
          ['separately', 'раздельно', 'окремо', 'ayrı ayrı']),
        sb('K5', 'bezahlen', I.order, 'Ich / möchte / bitte / bezahlen.',
          ['I would like to pay, please.', 'Я хотел бы расплатиться.', 'Я хотів би розрахуватися.', 'Ödemek istiyorum lütfen.']),
      ],
    },
    {
      title: 'Bei uns ist das anders.',
      t: ['It is different where I come from.', 'У нас это по-другому.', 'У нас це інакше.', 'Bizde bu farklı.'],
      card: {
        id: 'p3_vergleich',
        rule: 'Mit dem eigenen Land vergleichen: Bei uns ist das genauso. Bei uns ist das anders. Bei uns ist das nicht so wichtig. Bei uns ist das nicht so schlimm. Reagieren: Das überrascht mich. Das finde ich interessant. Das finde ich seltsam. In Deutschland isst man abends oft kalt. Bei uns in der Türkei isst man abends warm. Nach man steht das Verb wie bei er: man isst, man trinkt, man kommt.',
        examples: ['In Deutschland kommt man pünktlich. Bei uns ist das nicht so wichtig.', 'Das überrascht mich!', 'Bei uns isst man auch viel Brot. Das ist genauso.'],
        highlight: null,
        t: [
          'Comparing with your own country: Bei uns ist das genauso. (It is just the same where I come from.) Bei uns ist das anders. (It is different.) Bei uns ist das nicht so wichtig. (not so important) Bei uns ist das nicht so schlimm. (not so bad) Reacting: Das überrascht mich. (That surprises me.) Das finde ich interessant. Das finde ich seltsam. (strange) In Deutschland isst man abends oft kalt. Bei uns in der Türkei isst man abends warm. After man (one, people) the verb is like with er: man isst, man trinkt, man kommt.',
          'Сравнение со своей страной: Bei uns ist das genauso. (У нас точно так же.) Bei uns ist das anders. (У нас по-другому.) Bei uns ist das nicht so wichtig. (не так важно) Bei uns ist das nicht so schlimm. (не так страшно) Реакция: Das überrascht mich. (Это меня удивляет.) Das finde ich interessant. Das finde ich seltsam. (странно) In Deutschland isst man abends oft kalt. Bei uns in der Türkei isst man abends warm. После man глагол стоит как при er: man isst, man trinkt, man kommt.',
          'Порівняння зі своєю країною: Bei uns ist das genauso. (У нас так само.) Bei uns ist das anders. (У нас інакше.) Bei uns ist das nicht so wichtig. (не так важливо) Bei uns ist das nicht so schlimm. (не так страшно) Реакція: Das überrascht mich. (Це мене дивує.) Das finde ich interessant. Das finde ich seltsam. (дивно) In Deutschland isst man abends oft kalt. Bei uns in der Türkei isst man abends warm. Після man дієслово стоїть як при er: man isst, man trinkt, man kommt.',
          'Kendi ülkenizle karşılaştırmak: Bei uns ist das genauso. (Bizde de aynı.) Bei uns ist das anders. (Bizde farklı.) Bei uns ist das nicht so wichtig. (o kadar önemli değil) Bei uns ist das nicht so schlimm. (o kadar kötü değil) Tepki vermek: Das überrascht mich. (Bu beni şaşırtıyor.) Das finde ich interessant. Das finde ich seltsam. (tuhaf) In Deutschland isst man abends oft kalt. Bei uns in der Türkei isst man abends warm. man’dan sonra fiil er’deki gibi çekilir: man isst, man trinkt, man kommt.',
        ],
        hint: ['gleich → genauso. nicht gleich → anders. neu für mich → Das überrascht mich.', 'the same → genauso. not the same → anders. new to me → Das überrascht mich.', 'одинаково → genauso. не одинаково → anders. новое для меня → Das überrascht mich.', 'однаково → genauso. не однаково → anders. нове для мене → Das überrascht mich.', 'aynı → genauso. aynı değil → anders. benim için yeni → Das überrascht mich.'],
      },
      ex: [
        mc('K6', 'genauso', I.situation, 'In Deutschland isst man abends oft Brot. In deinem Land isst man abends auch Brot. Was sagst du?', ['Bei uns ist das genauso.', 'Bei uns ist das anders.', 'Das finde ich seltsam.'],
          ['In Germany people often eat bread in the evening. In your country people also eat bread in the evening. What do you say?', 'В Германии вечером часто едят хлеб. В вашей стране вечером тоже едят хлеб. Что вы скажете?', 'У Німеччині ввечері часто їдять хліб. У вашій країні ввечері теж їдять хліб. Що ви скажете?', 'Almanya’da akşamları sık sık ekmek yenir. Sizin ülkenizde de akşamları ekmek yenir. Ne dersiniz?']),
        mc('K6', 'anders', I.situation, 'In Deutschland bringt man Gastgebern oft Blumen mit. In deinem Land bringt man nie Blumen mit. Was sagst du?', ['Bei uns ist das anders.', 'Bei uns ist das genauso.', 'Stimmt so.'],
          ['In Germany people often bring flowers for their hosts. In your country people never bring flowers. What do you say?', 'В Германии хозяевам часто приносят цветы. В вашей стране цветы никогда не приносят. Что вы скажете?', 'У Німеччині господарям часто приносять квіти. У вашій країні квіти ніколи не приносять. Що ви скажете?', 'Almanya’da ev sahiplerine sık sık çiçek götürülür. Sizin ülkenizde hiç çiçek götürülmez. Ne dersiniz?']),
        mc('K6', 'überrascht sein', I.situation, 'Du hörst etwas ganz Neues und bist erstaunt. Was sagst du?', ['Das überrascht mich.', 'Das ist genauso.', 'Guten Appetit.'],
          ['You hear something completely new and are astonished. What do you say?', 'Вы слышите что-то совсем новое и удивлены. Что вы скажете?', 'Ви чуєте щось зовсім нове й здивовані. Що ви скажете?', 'Tamamen yeni bir şey duyuyorsunuz ve şaşırıyorsunuz. Ne dersiniz?']),
        mc('K6', 'man', I.choose, 'In Deutschland … man zum Frühstück oft Brötchen.', ['isst', 'essen', 'esst'],
          ['In Germany people often eat rolls for breakfast.', 'В Германии на завтрак часто едят булочки.', 'У Німеччині на сніданок часто їдять булочки.', 'Almanya’da kahvaltıda sık sık küçük ekmek yenir.']),
        mc('K6', 'seltsam', I.situation, 'Viele Deutsche essen schon um 12 Uhr zu Mittag. Du findest das komisch. Was sagst du?', ['Das finde ich seltsam.', 'Das ist bei uns genauso.', 'Das schmeckt mir.'],
          ['Many Germans have lunch as early as 12 o’clock. You find that odd. What do you say?', 'Многие немцы обедают уже в 12 часов. Вам это кажется странным. Что вы скажете?', 'Багато німців обідають уже о 12 годині. Вам це здається дивним. Що ви скажете?', 'Birçok Alman öğle yemeğini daha saat 12’de yiyor. Bunu tuhaf buluyorsunuz. Ne dersiniz?']),
        gap('K6', 'anders', I.word, 'Bei uns isst man kein Brot zum Abendessen. Bei uns ist das ', '.', 'anders', ['genauso', 'gleich'],
          ['Where I come from people do not eat bread for dinner. It is different there.', 'У нас на ужин не едят хлеб. У нас это по-другому.', 'У нас на вечерю не їдять хліб. У нас це інакше.', 'Bizde akşam yemeğinde ekmek yenmez. Bizde bu farklı.'],
          ['different', 'по-другому', 'інакше', 'farklı']),
        gap('K6', 'genauso', I.word, 'Auch bei uns trinkt man viel Tee. Das ist bei uns ', '.', 'genauso', ['anders', 'seltsam'],
          ['Where I come from people drink a lot of tea too. It is just the same there.', 'У нас тоже пьют много чая. У нас это точно так же.', 'У нас теж п’ють багато чаю. У нас це так само.', 'Bizde de çok çay içilir. Bizde de aynı.'],
          ['just the same', 'точно так же', 'так само', 'aynı şekilde']),
        gap('K6', 'überraschen', I.verb, 'In Deutschland zieht man in der Wohnung oft die Schuhe aus. Das ', ' mich, das ist neu für mich.', 'überrascht', ['überraschen', 'überrasche'],
          ['In Germany people often take their shoes off in the flat. That surprises me, it is new to me.', 'В Германии в квартире часто разуваются. Меня это удивляет, для меня это ново.', 'У Німеччині у квартирі часто роззуваються. Мене це дивує, для мене це нове.', 'Almanya’da evde çoğu zaman ayakkabılar çıkarılır. Bu beni şaşırtıyor, benim için yeni.'], 'überraschen'),
        gap('K6', 'bei uns', I.pronoun, 'Bei ', ' in Spanien isst man sehr spät zu Abend.', 'uns', ['wir', 'unser'],
          ['Where I come from, in Spain, people have dinner very late.', 'У нас в Испании ужинают очень поздно.', 'У нас в Іспанії вечеряють дуже пізно.', 'Bizde, İspanya’da akşam yemeği çok geç yenir.'], 'wir'),
        sb('K6', 'interessant finden', I.order, 'Das / finde / ich / sehr interessant.',
          ['I find that very interesting.', 'По-моему, это очень интересно.', 'На мою думку, це дуже цікаво.', 'Bunu çok ilginç buluyorum.'],
          { alt: ['Ich finde das sehr interessant.'] }),
      ],
    },
    {
      title: 'Ich koche gern scharf.',
      t: ['I like cooking spicy food.', 'Я люблю готовить острое.', 'Я люблю готувати гостре.', 'Acılı yemek yapmayı severim.'],
      card: {
        id: 'p3_kochen',
        rule: 'Über Kochgewohnheiten sprechen: Ich koche gern scharf, süß oder vegetarisch. Ich koche oft Fleisch mit Gemüse. Mein Lieblingsrezept ist Kartoffelsuppe. Besonders gern biete ich meinen Gästen Fisch an. Das schmeckt allen Gästen. Schweinefleisch koche ich nicht. Viele Leute mögen keinen Fisch. Manche Gäste dürfen kein Fleisch essen. Ich esse kein Fleisch, ich bin Vegetarier oder Vegetarierin. Geschmack: scharf, süß, salzig, sauer.',
        examples: ['Mein Lieblingsrezept ist Gemüsesuppe.', 'Ich koche gern scharf.', 'Viele Kinder mögen keinen Spinat.'],
        highlight: null,
        t: [
          'Talking about cooking habits: Ich koche gern scharf (spicy), süß (sweet) oder vegetarisch. Ich koche oft Fleisch mit Gemüse. Mein Lieblingsrezept (favourite recipe) ist Kartoffelsuppe. Besonders gern biete ich meinen Gästen Fisch an. (I especially like to offer my guests fish.) Das schmeckt allen Gästen. (All guests like it.) Schweinefleisch (pork) koche ich nicht. Viele Leute mögen keinen Fisch. Manche Gäste dürfen kein Fleisch essen. Ich esse kein Fleisch, ich bin Vegetarier / Vegetarierin. Taste: scharf (hot, spicy), süß (sweet), salzig (salty), sauer (sour).',
          'Как говорить о том, что вы готовите: Ich koche gern scharf (остро), süß (сладко) oder vegetarisch. Ich koche oft Fleisch mit Gemüse. Mein Lieblingsrezept (любимый рецепт) ist Kartoffelsuppe. Besonders gern biete ich meinen Gästen Fisch an. (Особенно охотно я предлагаю гостям рыбу.) Das schmeckt allen Gästen. (Это нравится всем гостям.) Schweinefleisch (свинину) koche ich nicht. Viele Leute mögen keinen Fisch. Manche Gäste dürfen kein Fleisch essen. Ich esse kein Fleisch, ich bin Vegetarier / Vegetarierin. Вкус: scharf (острый), süß (сладкий), salzig (солёный), sauer (кислый).',
          'Як говорити про те, що ви готуєте: Ich koche gern scharf (гостро), süß (солодко) oder vegetarisch. Ich koche oft Fleisch mit Gemüse. Mein Lieblingsrezept (улюблений рецепт) ist Kartoffelsuppe. Besonders gern biete ich meinen Gästen Fisch an. (Особливо охоче я пропоную гостям рибу.) Das schmeckt allen Gästen. (Це смакує всім гостям.) Schweinefleisch (свинину) koche ich nicht. Viele Leute mögen keinen Fisch. Manche Gäste dürfen kein Fleisch essen. Ich esse kein Fleisch, ich bin Vegetarier / Vegetarierin. Смак: scharf (гострий), süß (солодкий), salzig (солоний), sauer (кислий).',
          'Yemek yapma alışkanlıklarından söz etmek: Ich koche gern scharf (acılı), süß (tatlı) oder vegetarisch. Ich koche oft Fleisch mit Gemüse. Mein Lieblingsrezept (en sevdiğim tarif) ist Kartoffelsuppe. Besonders gern biete ich meinen Gästen Fisch an. (Misafirlerime özellikle balık ikram etmeyi severim.) Das schmeckt allen Gästen. (Bütün misafirler bunu beğenir.) Schweinefleisch (domuz eti) koche ich nicht. Viele Leute mögen keinen Fisch. Manche Gäste dürfen kein Fleisch essen. Ich esse kein Fleisch, ich bin Vegetarier / Vegetarierin. Tat: scharf (acı), süß (tatlı), salzig (tuzlu), sauer (ekşi).',
        ],
        hint: ['Geschmack: scharf (Chili), süß (Zucker), salzig (Salz), sauer (Zitrone).', 'Taste: scharf (chilli), süß (sugar), salzig (salt), sauer (lemon).', 'Вкус: scharf (перец чили), süß (сахар), salzig (соль), sauer (лимон).', 'Смак: scharf (перець чилі), süß (цукор), salzig (сіль), sauer (лимон).', 'Tat: scharf (acı biber), süß (şeker), salzig (tuz), sauer (limon).'],
      },
      ex: [
        mc('K7', 'scharf', I.choose, 'In dieser Suppe ist viel Chili. Sie ist sehr …', ['scharf', 'süß', 'sauer'],
          ['There is a lot of chilli in this soup. It is very …', 'В этом супе много перца чили. Он очень …', 'У цьому супі багато перцю чилі. Він дуже …', 'Bu çorbada çok acı biber var. Çorba çok …']),
        mc('K7', 'Vegetarier', I.choose, 'Emre isst kein Fleisch und keinen Fisch. Er ist …', ['Vegetarier', 'Kellner', 'Gast'],
          ['Emre does not eat meat or fish. He is a …', 'Emre не ест ни мяса, ни рыбы. Он …', 'Emre не їсть ні м’яса, ні риби. Він …', 'Emre ne et ne balık yiyor. O bir …']),
        mc('K7', 'Lieblingsrezept', I.react, '„Was kochst du am liebsten?“', ['Mein Lieblingsrezept ist Gemüsesuppe.', 'Ich koche zweimal pro Woche.', 'Die Küche ist dort.'],
          ['“What do you like cooking best?”', '«Что ты больше всего любишь готовить?»', '«Що ти найбільше любиш готувати?»', '“En çok ne pişirmeyi seversin?”']),
        mc('K7', 'süß', I.choose, 'Kuchen und Schokolade sind …', ['süß', 'salzig', 'scharf'],
          ['Cake and chocolate are …', 'Пирог и шоколад …', 'Пиріг і шоколад …', 'Kek ve çikolata …']),
        mc('K7', 'Gäste', I.situation, 'Deine Gäste sind Vegetarier. Was bietest du an?', ['Nudeln mit Gemüse', 'Hähnchen mit Reis', 'Fisch mit Kartoffeln'],
          ['Your guests are vegetarians. What do you offer them?', 'Ваши гости – вегетарианцы. Что вы им предложите?', 'Ваші гості – вегетаріанці. Що ви їм запропонуєте?', 'Misafirleriniz vejetaryen. Onlara ne ikram edersiniz?']),
        gap('K7', 'Lieblingsrezept', I.word, 'Ich koche diese Suppe sehr oft und sehr gern. Sie ist mein ', '.', 'Lieblingsrezept', ['Lieblingsfach', 'Lieblingsbuch'],
          ['I cook this soup very often and with great pleasure. It is my favourite recipe.', 'Я готовлю этот суп очень часто и с удовольствием. Это мой любимый рецепт.', 'Я готую цей суп дуже часто й залюбки. Це мій улюблений рецепт.', 'Bu çorbayı çok sık ve severek yaparım. Bu benim en sevdiğim tarif.'],
          ['favourite recipe', 'любимый рецепт', 'улюблений рецепт', 'en sevdiğim tarif']),
        gap('K7', 'mögen', I.verb, 'Viele Kinder ', ' keinen Spinat.', 'mögen', ['mag', 'mögt'],
          ['Many children do not like spinach.', 'Многие дети не любят шпинат.', 'Багато дітей не люблять шпинат.', 'Birçok çocuk ıspanak sevmez.'],
          ['like', 'любить', 'любити', 'sevmek']),
        gap('K7', 'sauer', I.word, 'Zitronen sind nicht süß. Sie sind ', '.', 'sauer', ['scharf', 'salzig'],
          ['Lemons are not sweet. They are sour.', 'Лимоны не сладкие. Они кислые.', 'Лимони не солодкі. Вони кислі.', 'Limonlar tatlı değildir. Ekşidir.'],
          ['sour', 'кислый', 'кислий', 'ekşi']),
        gap('K7', 'allen Gästen', I.form, 'Dieses Gericht schmeckt allen ', '. Alle möchten noch mehr.', 'Gästen', ['Gäste', 'Gast'],
          ['All the guests like this dish. Everyone wants more.', 'Это блюдо нравится всем гостям. Все хотят добавки.', 'Ця страва смакує всім гостям. Усі хочуть добавки.', 'Bu yemeği bütün misafirler beğeniyor. Herkes biraz daha istiyor.'], 'der Gast (Plural)'),
        sb('K7', 'gern kochen', I.order, 'Ich / koche / gern / mit viel Gemüse.',
          ['I like cooking with lots of vegetables.', 'Я люблю готовить с большим количеством овощей.', 'Я люблю готувати з великою кількістю овочів.', 'Bol sebzeyle yemek yapmayı severim.'],
          { alt: ['Gern koche ich mit viel Gemüse.', 'Mit viel Gemüse koche ich gern.'] }),
      ],
    },
    {
      title: 'Wer isst was?',
      t: ['Who eats what?', 'Кто что ест?', 'Хто що їсть?', 'Kim ne yiyor?'],
      card: {
        id: 'p3_lesen',
        rule: 'Texte über Essgewohnheiten verstehen: Achte auf Wörter für die Häufigkeit (immer, oft, selten, nie), auf Zeitangaben (morgens, mittags, abends, am Wochenende, unter der Woche) und auf Vorlieben (gern, lieber, am liebsten, mag kein …). Auch Zahlen sind wichtig: zweimal pro Woche, um 12 Uhr, 40 Minuten.',
        examples: ['Morgens trinke ich nur Kaffee.', 'Am Wochenende kochen wir zusammen.'],
        highlight: null,
        t: [
          'Understanding texts about eating habits: look for frequency words (immer, oft, selten, nie), time expressions (morgens – in the morning, mittags – at midday, abends – in the evening, am Wochenende, unter der Woche – on weekdays) and likes (gern, lieber, am liebsten, mag kein …). Numbers matter too: zweimal pro Woche, um 12 Uhr, 40 Minuten.',
          'Как понимать тексты о привычках в еде: обращайте внимание на слова, обозначающие частоту (immer, oft, selten, nie), на указания времени (morgens – утром, mittags – днём, abends – вечером, am Wochenende, unter der Woche – в будни) и на предпочтения (gern, lieber, am liebsten, mag kein …). Важны и числа: zweimal pro Woche, um 12 Uhr, 40 Minuten.',
          'Як розуміти тексти про звички в їжі: звертайте увагу на слова, що означають частоту (immer, oft, selten, nie), на вказівки часу (morgens – уранці, mittags – удень, abends – увечері, am Wochenende, unter der Woche – у будні) та на вподобання (gern, lieber, am liebsten, mag kein …). Важливі й числа: zweimal pro Woche, um 12 Uhr, 40 Minuten.',
          'Yeme alışkanlıklarıyla ilgili metinleri anlamak: Sıklık bildiren kelimelere (immer, oft, selten, nie), zaman ifadelerine (morgens – sabahları, mittags – öğlenleri, abends – akşamları, am Wochenende, unter der Woche – hafta içi) ve tercihlere (gern, lieber, am liebsten, mag kein …) dikkat edin. Sayılar da önemlidir: zweimal pro Woche, um 12 Uhr, 40 Minuten.',
        ],
        hint: ['Wann? Wie oft? Was mag die Person, was nicht? Such diese Informationen im Text.', 'When? How often? What does the person like, what not? Look for this information in the text.', 'Когда? Как часто? Что человек любит, а что нет? Найдите эти сведения в тексте.', 'Коли? Як часто? Що людина любить, а що ні? Знайдіть ці відомості в тексті.', 'Ne zaman? Ne sıklıkta? Kişi neyi seviyor, neyi sevmiyor? Bu bilgileri metinde arayın.'],
      },
      ex: [
        mc("Z1", "Wie oft?", I.read, "Interview mit Herrn Haddad: „Unter der Woche frühstücke ich nie, ich trinke nur einen Kaffee. Mittags esse ich in der Kantine, meistens Salat. Abends koche ich für die Familie. Am Sonntag frühstücken wir alle zusammen, zwei Stunden lang!“ Was macht Herr Haddad morgens von Montag bis Freitag?", ["Er trinkt nur einen Kaffee.","Er isst Salat.","Er frühstückt zwei Stunden."], ["What does Mr Haddad do in the morning from Monday to Friday?","Что господин Haddad делает по утрам с понедельника по пятницу?","Що пан Haddad робить уранці з понеділка до п’ятниці?","Haddad Bey pazartesiden cumaya sabahları ne yapıyor?"], {"c":"p3_lesen"}),
        mc("Z1", "Wann?", I.read, "Interview mit Herrn Haddad: „Unter der Woche frühstücke ich nie, ich trinke nur einen Kaffee. Mittags esse ich in der Kantine, meistens Salat. Abends koche ich für die Familie. Am Sonntag frühstücken wir alle zusammen, zwei Stunden lang!“ Wann frühstückt die Familie zusammen?", ["Am Sonntag.","Nie.","Jeden Tag."], ["When does the family have breakfast together?","Когда семья завтракает вместе?","Коли родина снідає разом?","Aile ne zaman birlikte kahvaltı yapıyor?"], {"c":"p3_lesen","sitovOptionOrder":["Nie.","Am Sonntag.","Jeden Tag."]}),
        mc("Z1", "Wo?", I.read, "Interview mit Herrn Haddad: „Unter der Woche frühstücke ich nie, ich trinke nur einen Kaffee. Mittags esse ich in der Kantine, meistens Salat. Abends koche ich für die Familie. Am Sonntag frühstücken wir alle zusammen, zwei Stunden lang!“ Wo isst Herr Haddad mittags?", ["In der Kantine.","Im Restaurant.","Zu Hause."], ["Where does Mr Haddad have lunch?","Где господин Haddad обедает?","Де пан Haddad обідає?","Haddad Bey öğle yemeğini nerede yiyor?"], {"c":"p3_lesen","sitovOptionOrder":["Im Restaurant.","In der Kantine.","Zu Hause."]}),
        mc('Z1', 'Wie oft?', I.read, `${PAUL} Wie oft holt Paul Pizza oder Döner?`, ['Dreimal pro Woche.', 'Jeden Tag.', 'Nur am Wochenende.'],
          ['How often does Paul get a pizza or a doner kebab?', 'Как часто Paul берёт пиццу или дёнер?', 'Як часто Paul бере піцу або денер?', 'Paul ne sıklıkta pizza ya da döner alıyor?']),
        mc('Z1', 'Vorliebe', I.read, `${PAUL} Was isst Paul am liebsten?`, ['Die Kartoffelsuppe von seiner Mutter.', 'Pizza.', 'Döner.'],
          ['What does Paul like eating best?', 'Что Paul любит есть больше всего?', 'Що Paul любить їсти найбільше?', 'Paul en çok neyi yemeyi seviyor?']),
        mc('Z1', 'Problem', I.read, `${KRITIK} Was ist im „Lindenhof“ nicht gut?`, ['Man wartet lange auf das Essen.', 'Das Essen ist nicht frisch.', 'Die Kellner sind unfreundlich.'],
          ['What is not good at the “Lindenhof”?', 'Что в «Lindenhof» плохо?', 'Що в «Lindenhof» погано?', '“Lindenhof”ta iyi olmayan ne?']),
        mc('Z1', 'Lob', I.read, `${KRITIK} Was ist dort besonders gut?`, ['Der Fisch.', 'Die Suppe.', 'Der Preis.'],
          ['What is especially good there?', 'Что там особенно хорошо?', 'Що там особливо добре?', 'Orada özellikle iyi olan ne?']),
      ],
    },
  ],
}

export default path
