import { I, gap, mc, sb } from '../shared.mjs'


/** A2.1 · Pfad 7 · Feste und Geschenke – Lektionen. Wiederholung und Test: p7-check.mjs */
const path = {
  n: 7,
  slug: 'feste-und-geschenke',
  title: 'Feste und Geschenke',
  t: ['Celebrations and presents', 'Праздники и подарки', 'Свята й подарунки', 'Kutlamalar ve hediyeler'],
  objectives: {
    G1: 'Der Dativ als Objekt mit Possessivartikel und unbestimmtem Artikel: meinem Mann, meiner Nachbarin, meinen Freunden – Wem?',
    G2: 'Stellung der Objekte: Dativ vor Akkusativ – Ich schenke ihr ein Buch. Akkusativpronomen vor Dativ – Ich gebe es ihm.',
    G3: 'Sagen, von wem etwas ist: von + Dativ – von meinem Kollegen, von meiner Schwester, von mir.',
    K1: 'Etwas empfehlen: Probieren Sie doch mal … Ich kann es Ihnen nur empfehlen.',
    K2: 'Über Geschenke und Vorlieben sprechen: Ich schenke gern … In meinem Land … Das ist tabu.',
    K3: 'Sagen, was wichtig ist: Mir ist wichtig, dass … Die Hauptsache ist, … Muss das sein?',
    K4: 'Ein Fest planen und von einem Fest berichten: Unser Fest findet am … statt. Zu essen gibt es …',
    Z1: 'Kann-Ziele: Kurznachrichten über eine Hochzeit verstehen.',
    W1: 'Wortschatz: Geschenke.',
    W2: 'Wortschatz: Hochzeit.',
  },
  nodes: [
    {
      title: 'Geschenke',
      t: ['Presents', 'Подарки', 'Подарунки', 'Hediyeler'],
      card: {
        id: 'p7_geschenke',
        rule: 'Rund ums Schenken: das Geschenk, der Gutschein (damit kauft man später selbst etwas), das Parfüm, die Kette, der Ring, der Blumenstrauß, die Pralinen (Plural), das Spielzeug, das Buch, die Handcreme, die Konzertkarte. Verben: schenken, einpacken (in Papier), auspacken (aus dem Papier), sich etwas wünschen, sich freuen über. Man schenkt etwas zum Geburtstag, zur Hochzeit, zu Weihnachten.',
        examples: ['Ich schenke meiner Oma einen Blumenstrauß.', 'Zum Geburtstag wünsche ich mir einen Gutschein.', 'Das Kind packt das Geschenk aus.'],
        highlight: 'article',
        t: [
          'All about giving presents: das Geschenk (present), der Gutschein (voucher: you buy something yourself later), das Parfüm (perfume), die Kette (necklace), der Ring, der Blumenstrauß (bunch of flowers), die Pralinen (chocolates, plural), das Spielzeug (toy), das Buch, die Handcreme (hand cream), die Konzertkarte (concert ticket). Verbs: schenken (to give as a present), einpacken (to wrap), auspacken (to unwrap), sich etwas wünschen (to wish for something), sich freuen über (to be pleased with). You give presents zum Geburtstag (for a birthday), zur Hochzeit (for a wedding), zu Weihnachten (for Christmas).',
          'Всё о подарках: das Geschenk (подарок), der Gutschein (подарочный сертификат: по нему потом покупают что-то сами), das Parfüm (духи), die Kette (цепочка), der Ring (кольцо), der Blumenstrauß (букет цветов), die Pralinen (шоколадные конфеты, множественное число), das Spielzeug (игрушка), das Buch, die Handcreme (крем для рук), die Konzertkarte (билет на концерт). Глаголы: schenken (дарить), einpacken (упаковывать), auspacken (распаковывать), sich etwas wünschen (хотеть что-то в подарок), sich freuen über (радоваться чему-то). Дарят zum Geburtstag (на день рождения), zur Hochzeit (на свадьбу), zu Weihnachten (на Рождество).',
          'Усе про подарунки: das Geschenk (подарунок), der Gutschein (подарунковий сертифікат: за ним потім купують щось самі), das Parfüm (парфуми), die Kette (ланцюжок), der Ring (перстень), der Blumenstrauß (букет квітів), die Pralinen (шоколадні цукерки, множина), das Spielzeug (іграшка), das Buch, die Handcreme (крем для рук), die Konzertkarte (квиток на концерт). Дієслова: schenken (дарувати), einpacken (пакувати), auspacken (розпаковувати), sich etwas wünschen (хотіти щось у подарунок), sich freuen über (радіти чомусь). Дарують zum Geburtstag (на день народження), zur Hochzeit (на весілля), zu Weihnachten (на Різдво).',
          'Hediye vermekle ilgili her şey: das Geschenk (hediye), der Gutschein (hediye çeki: kişi daha sonra kendisi bir şey alır), das Parfüm (parfüm), die Kette (kolye), der Ring (yüzük), der Blumenstrauß (çiçek buketi), die Pralinen (çikolatalar, çoğul), das Spielzeug (oyuncak), das Buch, die Handcreme (el kremi), die Konzertkarte (konser bileti). Fiiller: schenken (hediye etmek), einpacken (paketlemek), auspacken (paketi açmak), sich etwas wünschen (bir şey dilemek), sich freuen über (sevinmek). Hediye zum Geburtstag (doğum gününde), zur Hochzeit (düğünde), zu Weihnachten (Noel’de) verilir.',
        ],
        hint: ['Mit einem Gutschein kauft man später selbst etwas. Pralinen isst man. Parfüm riecht gut. Eine Kette trägt man.', 'With a Gutschein you buy something yourself later. You eat Pralinen. Parfüm smells good. You wear a Kette.', 'По Gutschein потом покупают что-то сами. Pralinen едят. Parfüm хорошо пахнет. Kette носят.', 'За Gutschein потім купують щось самі. Pralinen їдять. Parfüm гарно пахне. Kette носять.', 'Gutschein ile kişi daha sonra kendisi bir şey alır. Pralinen yenir. Parfüm güzel kokar. Kette takılır.'],
      },
      ex: [
        mc('W1', 'Gutschein', I.situation, 'Du weißt nicht, was deine Freundin braucht. Sie soll selbst etwas kaufen. Was schenkst du?', ['einen Gutschein', 'eine Kette', 'ein Parfüm'],
          ['You do not know what your friend needs. She should buy something herself. What do you give her?', 'Вы не знаете, что нужно вашей подруге. Пусть она сама что-нибудь купит. Что вы подарите?', 'Ви не знаєте, що потрібно вашій подрузі. Нехай вона сама щось купить. Що ви подаруєте?', 'Arkadaşınızın neye ihtiyacı olduğunu bilmiyorsunuz. Kendisi bir şey alsın. Ne hediye edersiniz?']),
        mc('W1', 'Pralinen', I.choose, 'Welches Geschenk kann man essen?', ['Pralinen', 'Parfüm', 'Spielzeug'],
          ['Which present can you eat?', 'Какой подарок можно съесть?', 'Який подарунок можна з’їсти?', 'Hangi hediye yenebilir?']),
        mc('W1', 'Spielzeug', I.choose, 'Was schenkt man einem kleinen Kind?', ['ein Spielzeug', 'ein Parfüm', 'eine Handcreme'],
          ['What do you give a small child?', 'Что дарят маленькому ребёнку?', 'Що дарують маленькій дитині?', 'Küçük bir çocuğa ne hediye edilir?']),
        mc('W1', 'Geschenke', I.odd, 'Drei Wörter sind Geschenke, ein Wort nicht.', ['Rechnung', 'Kette', 'Gutschein', 'Blumenstrauß'], null),
        mc('W1', 'auspacken', I.situation, 'Du bekommst ein Geschenk in buntem Papier. Was machst du?', ['Ich packe es aus.', 'Ich packe es ein.', 'Ich verkaufe es.'],
          ['You get a present in colourful paper. What do you do?', 'Вы получаете подарок в яркой бумаге. Что вы сделаете?', 'Ви отримуєте подарунок у яскравому папері. Що ви зробите?', 'Renkli kâğıda sarılı bir hediye alıyorsunuz. Ne yaparsınız?']),
        gap('W1', 'Kette', I.word, 'Sie trägt eine schöne ', ' aus Gold um den Hals.', 'Kette', ['Karte', 'Creme'],
          ['She is wearing a beautiful gold necklace round her neck.', 'Она носит на шее красивую золотую цепочку.', 'Вона носить на шиї гарний золотий ланцюжок.', 'Boynunda güzel bir altın kolye var.'],
          ['necklace', 'цепочка', 'ланцюжок', 'kolye']),
        gap('W1', 'Blumenstrauß', I.word, 'Rosen, Tulpen und Lilien zusammen: Das ist ein ', '.', 'Blumenstrauß', ['Gutschein', 'Spielzeug'],
          ['Roses, tulips and lilies together: that is a bunch of flowers.', 'Розы, тюльпаны и лилии вместе – это букет цветов.', 'Троянди, тюльпани й лілії разом – це букет квітів.', 'Güller, laleler ve zambaklar bir arada: Bu bir çiçek buketi.'],
          ['bunch of flowers', 'букет цветов', 'букет квітів', 'çiçek buketi']),
        gap('W1', 'einpacken', I.verb, 'Das Geschenk ist für Mama. Ich muss es noch in Papier ', '.', 'einpacken', ['auspacken', 'einkaufen'],
          ['The present is for Mum. I still have to wrap it in paper.', 'Подарок для мамы. Мне ещё нужно завернуть его в бумагу.', 'Подарунок для мами. Мені ще треба загорнути його в папір.', 'Hediye annem için. Onu daha kâğıda sarmam gerekiyor.'],
          ['wrap', 'упаковать', 'запакувати', 'paketlemek']),
        gap('W1', 'Parfüm', I.word, 'Es riecht sehr gut und ist in einer kleinen Flasche: das ', '.', 'Parfüm', ['Papier', 'Spielzeug'],
          ['It smells very good and comes in a small bottle: perfume.', 'Они очень хорошо пахнут и находятся в маленьком флаконе: духи.', 'Вони дуже гарно пахнуть і містяться в маленькому флаконі: парфуми.', 'Çok güzel kokar ve küçük bir şişededir: parfüm.'],
          ['perfume', 'духи', 'парфуми', 'parfüm']),
        sb('W1', 'sich etwas wünschen', I.order, 'Zum Geburtstag / wünsche / ich / mir / einen Gutschein.',
          ['For my birthday I would like a voucher.', 'На день рождения я хочу подарочный сертификат.', 'На день народження я хочу подарунковий сертифікат.', 'Doğum günümde bir hediye çeki istiyorum.'],
          { alt: ['Ich wünsche mir zum Geburtstag einen Gutschein.'] }),
      ],
    },
    {
      title: 'Wem? – Meinem Bruder.',
      t: ['To whom? – To my brother.', 'Кому? – Моему брату.', 'Кому? – Моєму братові.', 'Kime? – Erkek kardeşime.'],
      card: {
        id: 'p7_dativ',
        rule: 'Der Dativ als Objekt: Wer schenkt wem was? Ich (Wer?) schenke meinem Bruder (Wem?) ein Buch (Was?). Dativ maskulin und neutral: dem, einem, meinem, deinem, seinem, ihrem, unserem. Ich schenke meinem Vater eine Uhr. Sie gibt dem Kind ein Spielzeug. Er zeigt seinem Freund das Foto. Verben mit Dativ und Akkusativ: schenken, geben, bringen, kaufen, zeigen, schicken, schreiben, empfehlen, leihen, erklären, wünschen.',
        examples: ['Ich schenke meinem Mann eine Uhr.', 'Wir kaufen unserem Kind ein Fahrrad.', 'Sie gibt einem Kollegen den Schlüssel.'],
        highlight: 'article',
        t: [
          'The dative as an object: who gives what to whom? Ich (who?) schenke meinem Bruder (to whom?) ein Buch (what?). Dative masculine and neuter: dem, einem, meinem, deinem, seinem, ihrem, unserem. Ich schenke meinem Vater eine Uhr. Sie gibt dem Kind ein Spielzeug. Er zeigt seinem Freund das Foto. Verbs with a dative and an accusative: schenken (give as a present), geben (give), bringen (bring), kaufen (buy), zeigen (show), schicken (send), schreiben (write), empfehlen (recommend), leihen (lend), erklären (explain), wünschen (wish).',
          'Dativ как дополнение: кто кому что дарит? Ich (кто?) schenke meinem Bruder (кому?) ein Buch (что?). Dativ мужского и среднего рода: dem, einem, meinem, deinem, seinem, ihrem, unserem. Ich schenke meinem Vater eine Uhr. Sie gibt dem Kind ein Spielzeug. Er zeigt seinem Freund das Foto. Глаголы с Dativ и Akkusativ: schenken (дарить), geben (давать), bringen (приносить), kaufen (покупать), zeigen (показывать), schicken (отправлять), schreiben (писать), empfehlen (рекомендовать), leihen (одалживать), erklären (объяснять), wünschen (желать).',
          'Dativ як додаток: хто кому що дарує? Ich (хто?) schenke meinem Bruder (кому?) ein Buch (що?). Dativ чоловічого й середнього роду: dem, einem, meinem, deinem, seinem, ihrem, unserem. Ich schenke meinem Vater eine Uhr. Sie gibt dem Kind ein Spielzeug. Er zeigt seinem Freund das Foto. Дієслова з Dativ і Akkusativ: schenken (дарувати), geben (давати), bringen (приносити), kaufen (купувати), zeigen (показувати), schicken (надсилати), schreiben (писати), empfehlen (рекомендувати), leihen (позичати), erklären (пояснювати), wünschen (бажати).',
          'Nesne olarak Dativ: Kim kime ne hediye ediyor? Ich (kim?) schenke meinem Bruder (kime?) ein Buch (ne?). Eril ve nötr Dativ: dem, einem, meinem, deinem, seinem, ihrem, unserem. Ich schenke meinem Vater eine Uhr. Sie gibt dem Kind ein Spielzeug. Er zeigt seinem Freund das Foto. Dativ ve Akkusativ alan fiiller: schenken (hediye etmek), geben (vermek), bringen (getirmek), kaufen (satın almak), zeigen (göstermek), schicken (göndermek), schreiben (yazmak), empfehlen (tavsiye etmek), leihen (ödünç vermek), erklären (açıklamak), wünschen (dilemek).',
        ],
        hint: ['Wem? → Dativ. der und das → -em: meinem Bruder, einem Kind.', 'Wem? (to whom?) → dative. der and das → -em: meinem Bruder, einem Kind.', 'Wem? (кому?) → Dativ. der и das → -em: meinem Bruder, einem Kind.', 'Wem? (кому?) → Dativ. der і das → -em: meinem Bruder, einem Kind.', 'Wem? (kime?) → Dativ. der ve das → -em: meinem Bruder, einem Kind.'],
      },
      ex: [
        mc('G1', 'meinem', I.choose, 'Ich schenke … Vater ein Buch.', ['meinem', 'meinen', 'mein'],
          ['I am giving my father a book.', 'Я дарю отцу книгу.', 'Я дарую батькові книжку.', 'Babama bir kitap hediye ediyorum.']),
        mc('G1', 'unserem', I.choose, 'Wir kaufen … Kind ein Spielzeug.', ['unserem', 'unser', 'unseren'],
          ['We are buying our child a toy.', 'Мы покупаем нашему ребёнку игрушку.', 'Ми купуємо нашій дитині іграшку.', 'Çocuğumuza bir oyuncak alıyoruz.']),
        mc('G1', 'Wem?', I.choose, '… schenkst du die Blumen? – Meiner Mutter.', ['Wem', 'Wen', 'Wer'],
          ['Who are you giving the flowers to? – To my mother.', 'Кому ты даришь цветы? – Моей маме.', 'Кому ти даруєш квіти? – Моїй мамі.', 'Çiçekleri kime hediye ediyorsun? – Anneme.']),
        mc("G1", "ihrem", I.choose, "Ergänze den Possessivartikel zu „sie (Singular)“ im Dativ: „Sie zeigt … Freund die Fotos.“", ["ihrem","ihren","ihr"], ["Complete the possessive article for sie (singular) in the dative: „Sie zeigt … Freund die Fotos.“","Дополните притяжательный артикль для sie (ед. число) в дательном падеже: „Sie zeigt … Freund die Fotos.“","Доповніть присвійний артикль для sie (однина) в давальному відмінку: „Sie zeigt … Freund die Fotos.“","sie (tekil) için Dativ iyelik artikelini tamamlayın: „Sie zeigt … Freund die Fotos.“"], {"c":"p7_dativ"}),
        mc('G1', 'dem', I.choose, 'Der Kellner bringt … Gast die Rechnung.', ['dem', 'den', 'der'],
          ['The waiter brings the guest the bill.', 'Официант приносит гостю счёт.', 'Офіціант приносить гостеві рахунок.', 'Garson misafire hesabı getiriyor.']),
        gap('G1', 'meinem', I.possessive, 'Ich gebe ', ' Bruder zehn Euro.', 'meinem', ['meinen', 'meiner'],
          ['I am giving my brother ten euros.', 'Я даю брату десять евро.', 'Я даю братові десять євро.', 'Erkek kardeşime on avro veriyorum.'], 'mein'),
        gap('G1', 'seinem', I.possessive, 'Paul schreibt ', ' Onkel eine Karte.', 'seinem', ['seinen', 'seiner'],
          ['Paul is writing his uncle a card.', 'Paul пишет своему дяде открытку.', 'Paul пише своєму дядькові листівку.', 'Paul amcasına bir kart yazıyor.'], 'sein'),
        gap('G1', 'dem', I.article, 'Die Oma erzählt ', ' Kind eine Geschichte.', 'dem', ['das', 'den'],
          ['Grandma is telling the child a story.', 'Бабушка рассказывает ребёнку историю.', 'Бабуся розповідає дитині історію.', 'Büyükanne çocuğa bir hikâye anlatıyor.'], 'das Kind'),
        gap('G1', 'deinem', I.possessive, 'Hast du ', ' Chef schon zum Geburtstag gratuliert?', 'deinem', ['deinen', 'dein'],
          ['Have you wished your boss a happy birthday yet?', 'Ты уже поздравил начальника с днём рождения?', 'Ти вже привітав начальника з днем народження?', 'Patronunun doğum gününü kutladın mı?'], 'dein'),
        sb('G1', 'Dativ + Akkusativ', I.order, 'Ich / schenke / meinem Vater / eine Uhr.',
          ['I am giving my father a watch.', 'Я дарю отцу часы.', 'Я дарую батькові годинник.', 'Babama bir saat hediye ediyorum.'],
          { alt: ['Meinem Vater schenke ich eine Uhr.', 'Eine Uhr schenke ich meinem Vater.'] }),
      ],
    },
    {
      title: 'meiner Mutter, meinen Eltern',
      t: ['meiner Mutter, meinen Eltern (dative: feminine and plural)', 'meiner Mutter, meinen Eltern (Dativ: женский род и множественное число)', 'meiner Mutter, meinen Eltern (Dativ: жіночий рід і множина)', 'meiner Mutter, meinen Eltern (Dativ: dişil ve çoğul)'],
      card: {
        id: 'p7_dativ2',
        rule: 'Dativ feminin: der, einer, meiner, deiner, seiner, ihrer, unserer. Ich schenke meiner Mutter Blumen. Er gibt seiner Nachbarin den Schlüssel. Dativ Plural: den, meinen, deinen, seinen, ihren, unseren. Das Nomen bekommt im Plural ein -n: Ich schenke meinen Eltern einen Gutschein. Wir schreiben unseren Freunden eine Karte. Sie gibt den Kindern Schokolade.',
        examples: ['Ich schenke meiner Schwester ein Parfüm.', 'Wir schicken unseren Freunden ein Paket.', 'Er kauft den Kindern ein Eis.'],
        highlight: 'article',
        t: [
          'Dative feminine: der, einer, meiner, deiner, seiner, ihrer, unserer. Ich schenke meiner Mutter Blumen. Er gibt seiner Nachbarin den Schlüssel. Dative plural: den, meinen, deinen, seinen, ihren, unseren. In the plural the noun gets an -n: Ich schenke meinen Eltern einen Gutschein. Wir schreiben unseren Freunden eine Karte. Sie gibt den Kindern Schokolade.',
          'Dativ женского рода: der, einer, meiner, deiner, seiner, ihrer, unserer. Ich schenke meiner Mutter Blumen. Er gibt seiner Nachbarin den Schlüssel. Dativ множественного числа: den, meinen, deinen, seinen, ihren, unseren. Существительное во множественном числе получает -n: Ich schenke meinen Eltern einen Gutschein. Wir schreiben unseren Freunden eine Karte. Sie gibt den Kindern Schokolade.',
          'Dativ жіночого роду: der, einer, meiner, deiner, seiner, ihrer, unserer. Ich schenke meiner Mutter Blumen. Er gibt seiner Nachbarin den Schlüssel. Dativ множини: den, meinen, deinen, seinen, ihren, unseren. Іменник у множині отримує -n: Ich schenke meinen Eltern einen Gutschein. Wir schreiben unseren Freunden eine Karte. Sie gibt den Kindern Schokolade.',
          'Dişil Dativ: der, einer, meiner, deiner, seiner, ihrer, unserer. Ich schenke meiner Mutter Blumen. Er gibt seiner Nachbarin den Schlüssel. Çoğul Dativ: den, meinen, deinen, seinen, ihren, unseren. Çoğulda isim -n alır: Ich schenke meinen Eltern einen Gutschein. Wir schreiben unseren Freunden eine Karte. Sie gibt den Kindern Schokolade.',
        ],
        hint: ['die → -er: meiner Mutter. Plural → -en und Nomen + n: meinen Eltern, den Kindern.', 'die → -er: meiner Mutter. Plural → -en and noun + n: meinen Eltern, den Kindern.', 'die → -er: meiner Mutter. Множественное число → -en и существительное + n: meinen Eltern, den Kindern.', 'die → -er: meiner Mutter. Множина → -en та іменник + n: meinen Eltern, den Kindern.', 'die → -er: meiner Mutter. Çoğul → -en ve isim + n: meinen Eltern, den Kindern.'],
      },
      ex: [
        mc('G1', 'meiner', I.choose, 'Ich schenke … Mutter eine Handcreme.', ['meiner', 'meine', 'meinem'],
          ['I am giving my mother a hand cream.', 'Я дарю маме крем для рук.', 'Я дарую мамі крем для рук.', 'Anneme bir el kremi hediye ediyorum.']),
        mc('G1', 'unseren', I.choose, 'Wir schicken … Großeltern eine Karte.', ['unseren', 'unsere', 'unserem'],
          ['We are sending our grandparents a card.', 'Мы отправляем бабушке и дедушке открытку.', 'Ми надсилаємо бабусі й дідусеві листівку.', 'Büyükannemizle büyükbabamıza bir kart gönderiyoruz.']),
        mc('G1', 'den (Plural)', I.choose, 'Der Lehrer erklärt … Kindern die Aufgabe.', ['den', 'die', 'dem'],
          ['The teacher explains the task to the children.', 'Учитель объясняет детям задание.', 'Учитель пояснює дітям завдання.', 'Öğretmen çocuklara görevi açıklıyor.']),
        mc('G1', 'seiner', I.choose, 'Emre kauft … Freundin einen Ring.', ['seiner', 'seine', 'seinem'],
          ['Emre is buying his girlfriend a ring.', 'Emre покупает своей девушке кольцо.', 'Emre купує своїй дівчині перстень.', 'Emre kız arkadaşına bir yüzük alıyor.']),
        mc('G1', 'Plural + n', I.choose, 'Sie schenkt ihren … Konzertkarten.', ['Freunden', 'Freunde', 'Freund'],
          ['She is giving her friends concert tickets.', 'Она дарит друзьям билеты на концерт.', 'Вона дарує друзям квитки на концерт.', 'Arkadaşlarına konser bileti hediye ediyor.']),
        gap('G1', 'meiner', I.possessive, 'Ich bringe ', ' Nachbarin ein Stück Kuchen.', 'meiner', ['meine', 'meinem'],
          ['I am taking my neighbour a piece of cake.', 'Я несу соседке кусочек пирога.', 'Я несу сусідці шматочок пирога.', 'Komşuma bir dilim kek götürüyorum.'], 'mein'),
        gap('G1', 'deinen', I.possessive, 'Was schenkst du ', ' Eltern zu Weihnachten?', 'deinen', ['deine', 'deiner'],
          ['What are you giving your parents for Christmas?', 'Что ты подаришь родителям на Рождество?', 'Що ти подаруєш батькам на Різдво?', 'Noel’de annenle babana ne hediye edeceksin?'], 'dein'),
        gap("G1", "ihrer", I.possessive, "Ergänze den Possessivartikel zu „sie (Singular)“: Sie zeigt ", " Tante das neue Kleid.", "ihrer", ["ihre","ihrem"], ["Complete the possessive for sie (singular): Sie zeigt … Tante das neue Kleid.","Дополните притяжательный артикль для sie (ед. число): Sie zeigt … Tante das neue Kleid.","Доповніть присвійний артикль для sie (однина): Sie zeigt … Tante das neue Kleid.","sie (tekil) için iyelik artikelini tamamlayın: Sie zeigt … Tante das neue Kleid."], "ihr", {"c":"p7_dativ2"}),
        gap('G1', 'Plural + n', I.form, 'Wir wünschen den ', ' viel Glück in der Schule.', 'Kindern', ['Kinder', 'Kind'],
          ['We wish the children lots of luck at school.', 'Мы желаем детям удачи в школе.', 'Ми бажаємо дітям успіхів у школі.', 'Çocuklara okulda bol şans diliyoruz.'], 'das Kind (Plural)'),
        sb('G1', 'Dativ Plural', I.order, 'Wir / schenken / unseren Eltern / eine Reise.',
          ['We are giving our parents a trip.', 'Мы дарим родителям путешествие.', 'Ми даруємо батькам подорож.', 'Annemizle babamıza bir gezi hediye ediyoruz.'],
          { alt: ['Unseren Eltern schenken wir eine Reise.', 'Eine Reise schenken wir unseren Eltern.'] }),
      ],
    },
    {
      title: 'Ich schenke ihr ein Buch.',
      t: ['I am giving her a book.', 'Я дарю ей книгу.', 'Я дарую їй книжку.', 'Ona bir kitap hediye ediyorum.'],
      card: {
        id: 'p7_objekte',
        rule: 'Stellung der Objekte. Zwei Nomen: zuerst der Dativ (die Person), dann der Akkusativ (die Sache). Jan schenkt seinen Eltern Konzertkarten. Ist der Dativ ein Pronomen, steht es direkt nach dem Verb: Jan schenkt ihnen Konzertkarten. Ich gebe ihm das Buch. Sie zeigt mir die Fotos. Dativpronomen: mir, dir, ihm, ihr, uns, euch, ihnen, Ihnen.',
        examples: ['Ich schenke meiner Freundin einen Ring.', 'Ich schenke ihr einen Ring.', 'Kannst du mir den Stift geben?'],
        highlight: null,
        t: [
          'The order of objects. Two nouns: first the dative (the person), then the accusative (the thing). Jan schenkt seinen Eltern Konzertkarten. If the dative is a pronoun, it comes straight after the verb: Jan schenkt ihnen Konzertkarten. Ich gebe ihm das Buch. Sie zeigt mir die Fotos. Dative pronouns: mir, dir, ihm, ihr, uns, euch, ihnen, Ihnen.',
          'Порядок дополнений. Два существительных: сначала Dativ (человек), затем Akkusativ (предмет). Jan schenkt seinen Eltern Konzertkarten. Если Dativ – местоимение, оно стоит сразу после глагола: Jan schenkt ihnen Konzertkarten. Ich gebe ihm das Buch. Sie zeigt mir die Fotos. Местоимения в Dativ: mir, dir, ihm, ihr, uns, euch, ihnen, Ihnen.',
          'Порядок додатків. Два іменники: спочатку Dativ (людина), потім Akkusativ (річ). Jan schenkt seinen Eltern Konzertkarten. Якщо Dativ – займенник, він стоїть одразу після дієслова: Jan schenkt ihnen Konzertkarten. Ich gebe ihm das Buch. Sie zeigt mir die Fotos. Займенники в Dativ: mir, dir, ihm, ihr, uns, euch, ihnen, Ihnen.',
          'Nesnelerin sırası. İki isim: önce Dativ (kişi), sonra Akkusativ (nesne). Jan schenkt seinen Eltern Konzertkarten. Dativ bir zamirse fiilin hemen arkasında durur: Jan schenkt ihnen Konzertkarten. Ich gebe ihm das Buch. Sie zeigt mir die Fotos. Dativ zamirleri: mir, dir, ihm, ihr, uns, euch, ihnen, Ihnen.',
        ],
        hint: ['Erst die Person (Dativ), dann die Sache (Akkusativ): Ich gebe ihm das Buch.', 'First the person (dative), then the thing (accusative): Ich gebe ihm das Buch.', 'Сначала человек (Dativ), затем предмет (Akkusativ): Ich gebe ihm das Buch.', 'Спочатку людина (Dativ), потім річ (Akkusativ): Ich gebe ihm das Buch.', 'Önce kişi (Dativ), sonra nesne (Akkusativ): Ich gebe ihm das Buch.'],
      },
      ex: [
        mc('G2', 'Dativ vor Akkusativ', I.sentence, 'Dilara hat ein Geschenk für ihren Bruder.', ['Sie schenkt ihm eine Uhr.', 'Sie schenkt eine Uhr ihm.', 'Sie ihm schenkt eine Uhr.'],
          ['Dilara has a present for her brother.', 'У Dilara есть подарок для брата.', 'У Dilara є подарунок для брата.', 'Dilara’nın erkek kardeşi için bir hediyesi var.']),
        mc('G2', 'ihr', I.choose, 'Ich schenke meiner Mutter Blumen. = Ich schenke … Blumen.', ['ihr', 'ihm', 'sie'],
          ['I am giving my mother flowers. = I am giving her flowers.', 'Я дарю маме цветы. = Я дарю ей цветы.', 'Я дарую мамі квіти. = Я дарую їй квіти.', 'Anneme çiçek hediye ediyorum. = Ona çiçek hediye ediyorum.']),
        mc('G2', 'ihnen', I.choose, 'Wir kaufen den Kindern ein Eis. = Wir kaufen … ein Eis.', ['ihnen', 'ihr', 'sie'],
          ['We are buying the children an ice cream. = We are buying them an ice cream.', 'Мы покупаем детям мороженое. = Мы покупаем им мороженое.', 'Ми купуємо дітям морозиво. = Ми купуємо їм морозиво.', 'Çocuklara dondurma alıyoruz. = Onlara dondurma alıyoruz.']),
        mc('G2', 'Dativ vor Akkusativ', I.sentence, 'Paul hat die Zeitung geholt.', ['Er bringt seinem Opa die Zeitung.', 'Er seinem Opa bringt die Zeitung.', 'Er bringt seinem Opa der Zeitung.'],
          ['Paul has fetched the newspaper.', 'Paul принёс газету.', 'Paul приніс газету.', 'Paul gazeteyi aldı.']),
        mc('G2', 'mir', I.choose, 'Kannst du … bitte das Salz geben?', ['mir', 'mich', 'ich'],
          ['Can you pass me the salt, please?', 'Можешь передать мне соль, пожалуйста?', 'Можеш передати мені сіль, будь ласка?', 'Bana tuzu verir misin lütfen?']),
        gap('G2', 'ihm', I.pronoun, 'Mein Bruder hat Geburtstag. Ich kaufe ', ' ein Buch.', 'ihm', ['ihn', 'ihr'],
          ['It is my brother’s birthday. I am buying him a book.', 'У моего брата день рождения. Я покупаю ему книгу.', 'У мого брата день народження. Я купую йому книжку.', 'Erkek kardeşimin doğum günü. Ona bir kitap alıyorum.'], 'er'),
        gap('G2', 'ihnen', I.pronoun, 'Meine Eltern feiern Hochzeitstag. Wir schenken ', ' eine Reise.', 'ihnen', ['sie', 'ihr'],
          ['My parents are celebrating their wedding anniversary. We are giving them a trip.', 'Мои родители отмечают годовщину свадьбы. Мы дарим им путешествие.', 'Мої батьки святкують річницю весілля. Ми даруємо їм подорож.', 'Annemle babam evlilik yıl dönümünü kutluyor. Onlara bir gezi hediye ediyoruz.'], 'sie (Plural)'),
        gap('G2', 'Ihnen', I.pronoun, 'Frau Kaya, ich zeige ', ' gern die Wohnung.', 'Ihnen', ['Sie', 'ihr'],
          ['Ms Kaya, I will gladly show you the flat.', 'Госпожа Kaya, я с удовольствием покажу вам квартиру.', 'Пані Kaya, я охоче покажу вам квартиру.', 'Kaya Hanım, size daireyi seve seve gösteririm.'], 'Sie'),
        gap('G2', 'dir', I.pronoun, 'Du hast Hunger? Ich mache ', ' ein Brot.', 'dir', ['dich', 'du'],
          ['Are you hungry? I will make you a sandwich.', 'Ты голоден? Я сделаю тебе бутерброд.', 'Ти голодний? Я зроблю тобі бутерброд.', 'Aç mısın? Sana bir ekmek hazırlayayım.'], 'du'),
        sb('G2', 'Dativpronomen', I.order, 'Ich / schenke / ihr / einen Blumenstrauß.',
          ['I am giving her a bunch of flowers.', 'Я дарю ей букет цветов.', 'Я дарую їй букет квітів.', 'Ona bir çiçek buketi hediye ediyorum.'],
          { alt: ['Ihr schenke ich einen Blumenstrauß.'] }),
      ],
    },
    {
      title: 'Ich gebe es ihm.',
      t: ['I am giving it to him.', 'Я даю это ему.', 'Я даю це йому.', 'Onu ona veriyorum.'],
      card: {
        id: 'p7_objekte2',
        rule: 'Ist der Akkusativ ein Pronomen, steht er vor dem Dativ: Ich gebe meinem Bruder das Buch. → Ich gebe es meinem Bruder. → Ich gebe es ihm. Dimi empfiehlt seinem Freund den Film. → Dimi empfiehlt ihn ihm. Akkusativpronomen: ihn (der), es (das), sie (die und Plural). Merke: Pronomen stehen vor Nomen. Bei zwei Pronomen steht der Akkusativ zuerst.',
        examples: ['Ich schenke dir die Kette. – Ich schenke sie dir.', 'Gibst du mir den Schlüssel? – Ja, ich gebe ihn dir.', 'Er empfiehlt es ihr.'],
        highlight: null,
        t: [
          'If the accusative is a pronoun, it comes before the dative: Ich gebe meinem Bruder das Buch. → Ich gebe es meinem Bruder. → Ich gebe es ihm. Dimi empfiehlt seinem Freund den Film. → Dimi empfiehlt ihn ihm. Accusative pronouns: ihn (der), es (das), sie (die and plural). Remember: pronouns come before nouns. With two pronouns the accusative comes first.',
          'Если Akkusativ – местоимение, оно стоит перед Dativ: Ich gebe meinem Bruder das Buch. → Ich gebe es meinem Bruder. → Ich gebe es ihm. Dimi empfiehlt seinem Freund den Film. → Dimi empfiehlt ihn ihm. Местоимения в Akkusativ: ihn (der), es (das), sie (die и множественное число). Запомните: местоимения стоят перед существительными. Из двух местоимений первым идёт Akkusativ.',
          'Якщо Akkusativ – займенник, він стоїть перед Dativ: Ich gebe meinem Bruder das Buch. → Ich gebe es meinem Bruder. → Ich gebe es ihm. Dimi empfiehlt seinem Freund den Film. → Dimi empfiehlt ihn ihm. Займенники в Akkusativ: ihn (der), es (das), sie (die та множина). Запам’ятайте: займенники стоять перед іменниками. Із двох займенників першим іде Akkusativ.',
          'Akkusativ bir zamirse Dativ’ten önce gelir: Ich gebe meinem Bruder das Buch. → Ich gebe es meinem Bruder. → Ich gebe es ihm. Dimi empfiehlt seinem Freund den Film. → Dimi empfiehlt ihn ihm. Akkusativ zamirleri: ihn (der), es (das), sie (die ve çoğul). Unutmayın: Zamirler isimlerden önce gelir. İki zamir varsa önce Akkusativ gelir.',
        ],
        hint: ['Zwei Pronomen: zuerst Akkusativ (ihn, es, sie), dann Dativ (mir, dir, ihm, ihr).', 'Two pronouns: first the accusative (ihn, es, sie), then the dative (mir, dir, ihm, ihr).', 'Два местоимения: сначала Akkusativ (ihn, es, sie), затем Dativ (mir, dir, ihm, ihr).', 'Два займенники: спочатку Akkusativ (ihn, es, sie), потім Dativ (mir, dir, ihm, ihr).', 'İki zamir: önce Akkusativ (ihn, es, sie), sonra Dativ (mir, dir, ihm, ihr).'],
      },
      ex: [
        mc('G2', 'ihn dir', I.choose, 'Gibst du mir den Stift? – Ja, ich gebe …', ['ihn dir.', 'dir ihn.', 'ihm dich.'],
          ['Will you give me the pen? – Yes, I will give it to you.', 'Ты дашь мне ручку? – Да, я дам её тебе.', 'Ти даси мені ручку? – Так, я дам її тобі.', 'Bana kalemi verir misin? – Evet, onu sana veriyorum.']),
        mc('G2', 'sie ihr', I.choose, 'Schenkst du deiner Mutter die Kette? – Ja, ich schenke …', ['sie ihr.', 'ihr sie.', 'es ihr.'],
          ['Are you giving your mother the necklace? – Yes, I am giving it to her.', 'Ты подаришь маме цепочку? – Да, я подарю её ей.', 'Ти подаруєш мамі ланцюжок? – Так, я подарую його їй.', 'Annene kolyeyi hediye edecek misin? – Evet, onu ona hediye edeceğim.']),
        mc('G2', 'es euch', I.choose, 'Zeigst du uns das Foto? – Ja, ich zeige …', ['es euch.', 'euch es.', 'ihn euch.'],
          ['Will you show us the photo? – Yes, I will show it to you.', 'Ты покажешь нам фото? – Да, я покажу его вам.', 'Ти покажеш нам фото? – Так, я покажу його вам.', 'Bize fotoğrafı gösterir misin? – Evet, onu size gösteriyorum.']),
        mc('G2', 'Pronomen vor Nomen', I.sentence, 'Der Verkäufer hat ein gutes Buch.', ['Er empfiehlt es dem Kunden.', 'Er empfiehlt dem Kunden es.', 'Er es empfiehlt dem Kunden.'],
          ['The shop assistant has a good book.', 'У продавца есть хорошая книга.', 'У продавця є добра книжка.', 'Satıcının iyi bir kitabı var.']),
        mc('G2', 'ihn', I.choose, 'Welches Pronomen steht für „den Ring“?', ['ihn', 'es', 'ihm'],
          ['Which pronoun stands for “den Ring”?', 'Какое местоимение заменяет «den Ring»?', 'Який займенник замінює «den Ring»?', '“den Ring” yerine hangi zamir kullanılır?']),
        gap('G2', 'es', I.pronoun, 'Wo ist das Geschenk für Opa? – Ich habe ', ' ihm schon gegeben.', 'es', ['ihn', 'sie'],
          ['Where is the present for Grandad? – I have already given it to him.', 'Где подарок для дедушки? – Я уже отдал его ему.', 'Де подарунок для дідуся? – Я вже віддав його йому.', 'Dedemin hediyesi nerede? – Onu ona verdim bile.'], 'das Geschenk'),
        gap('G2', 'sie (Plural)', I.pronoun, 'Die Blumen sind schön! – Ja, ich schenke ', ' meiner Lehrerin.', 'sie', ['ihn', 'es'],
          ['The flowers are lovely! – Yes, I am giving them to my teacher.', 'Цветы красивые! – Да, я дарю их своей учительнице.', 'Квіти гарні! – Так, я дарую їх своїй учительці.', 'Çiçekler çok güzel! – Evet, onları öğretmenime hediye ediyorum.'], 'die Blumen'),
        gap('G2', 'ihn', I.pronoun, 'Kannst du mir den Film empfehlen? – Ja, ich empfehle ', ' dir.', 'ihn', ['ihm', 'es'],
          ['Can you recommend the film to me? – Yes, I recommend it to you.', 'Ты можешь порекомендовать мне этот фильм? – Да, я рекомендую его тебе.', 'Ти можеш порекомендувати мені цей фільм? – Так, я рекомендую його тобі.', 'Bana bu filmi tavsiye eder misin? – Evet, onu sana tavsiye ederim.'], 'der Film'),
        gap('G2', 'mir', I.pronoun, 'Ich brauche den Schlüssel. Gib ihn ', ' bitte!', 'mir', ['mich', 'ich'],
          ['I need the key. Give it to me, please!', 'Мне нужен ключ. Дай его мне, пожалуйста!', 'Мені потрібен ключ. Дай його мені, будь ласка!', 'Anahtara ihtiyacım var. Onu bana ver lütfen!'], 'ich'),
        sb('G2', 'Akkusativ vor Dativ', I.order, 'Ich / gebe / es / dir / morgen.',
          ['I will give it to you tomorrow.', 'Я дам это тебе завтра.', 'Я дам це тобі завтра.', 'Onu sana yarın veririm.'],
          { alt: ['Morgen gebe ich es dir.'] }),
      ],
    },
    {
      title: 'von meinem Kollegen',
      t: ['from my colleague', 'от моего коллеги', 'від мого колеги', 'iş arkadaşımdan'],
      card: {
        id: 'p7_von',
        rule: 'Von wem ist das Geschenk? von + Dativ: Die Blumen sind von meinem Mann. Das Buch habe ich von meiner Schwester bekommen. Die Karte ist von meinen Kollegen. Mit Pronomen: von mir, von dir, von ihm, von ihr, von uns, von euch, von ihnen. Einige maskuline Nomen bekommen im Dativ ein -n: der Kollege → von meinem Kollegen, der Nachbar → von meinem Nachbarn, der Herr → von Herrn Weber.',
        examples: ['Die Kette ist von meinem Mann.', 'Den Gutschein habe ich von meinen Kollegen bekommen.', 'Das Geschenk ist von uns allen.'],
        highlight: null,
        t: [
          'Who is the present from? von + dative: Die Blumen sind von meinem Mann. Das Buch habe ich von meiner Schwester bekommen. Die Karte ist von meinen Kollegen. With pronouns: von mir, von dir, von ihm, von ihr, von uns, von euch, von ihnen. Some masculine nouns get an -n in the dative: der Kollege → von meinem Kollegen, der Nachbar → von meinem Nachbarn, der Herr → von Herrn Weber.',
          'От кого подарок? von + Dativ: Die Blumen sind von meinem Mann. Das Buch habe ich von meiner Schwester bekommen. Die Karte ist von meinen Kollegen. С местоимениями: von mir, von dir, von ihm, von ihr, von uns, von euch, von ihnen. Некоторые существительные мужского рода получают в Dativ -n: der Kollege → von meinem Kollegen, der Nachbar → von meinem Nachbarn, der Herr → von Herrn Weber.',
          'Від кого подарунок? von + Dativ: Die Blumen sind von meinem Mann. Das Buch habe ich von meiner Schwester bekommen. Die Karte ist von meinen Kollegen. Із займенниками: von mir, von dir, von ihm, von ihr, von uns, von euch, von ihnen. Деякі іменники чоловічого роду отримують у Dativ -n: der Kollege → von meinem Kollegen, der Nachbar → von meinem Nachbarn, der Herr → von Herrn Weber.',
          'Hediye kimden? von + Dativ: Die Blumen sind von meinem Mann. Das Buch habe ich von meiner Schwester bekommen. Die Karte ist von meinen Kollegen. Zamirlerle: von mir, von dir, von ihm, von ihr, von uns, von euch, von ihnen. Bazı eril isimler Dativ’te -n alır: der Kollege → von meinem Kollegen, der Nachbar → von meinem Nachbarn, der Herr → von Herrn Weber.',
        ],
        hint: ['von + Dativ: von meinem (der, das), von meiner (die), von meinen (Plural). Pronomen: von mir, von ihm, von ihr.', 'von + dative: von meinem (der, das), von meiner (die), von meinen (plural). Pronouns: von mir, von ihm, von ihr.', 'von + Dativ: von meinem (der, das), von meiner (die), von meinen (множественное число). Местоимения: von mir, von ihm, von ihr.', 'von + Dativ: von meinem (der, das), von meiner (die), von meinen (множина). Займенники: von mir, von ihm, von ihr.', 'von + Dativ: von meinem (der, das), von meiner (die), von meinen (çoğul). Zamirler: von mir, von ihm, von ihr.'],
      },
      ex: [
        mc('G3', 'von meiner', I.choose, 'Von wem ist die Karte? – Von … Kollegin.', ['meiner', 'meine', 'meinem'],
          ['Who is the card from? – From my colleague.', 'От кого открытка? – От моей коллеги.', 'Від кого листівка? – Від моєї колеги.', 'Kart kimden? – İş arkadaşımdan.']),
        mc('G3', 'von meinem', I.choose, 'Die Pralinen sind von … Chef.', ['meinem', 'mein', 'meine'],
          ['The chocolates are from my boss.', 'Конфеты от моего начальника.', 'Цукерки від мого начальника.', 'Çikolatalar patronumdan.']),
        mc('G3', 'von uns', I.choose, 'Wir haben das Geschenk zusammen gekauft. Es ist von …', ['uns', 'wir', 'unser'],
          ['We bought the present together. It is from us.', 'Мы купили подарок вместе. Он от нас.', 'Ми купили подарунок разом. Він від нас.', 'Hediyeyi birlikte aldık. O bizden.']),
        mc('G3', 'Von wem?', I.choose, '… hast du die Uhr bekommen? – Von meinem Opa.', ['Von wem', 'Wem', 'Wer'],
          ['Who did you get the watch from? – From my grandad.', 'От кого ты получил часы? – От дедушки.', 'Від кого ти отримав годинник? – Від дідуся.', 'Saati kimden aldın? – Dedemden.']),
        mc('G3', 'von ihm', I.choose, 'Die Blumen sind von Tim. Sie sind von …', ['ihm', 'ihn', 'er'],
          ['The flowers are from Tim. They are from him.', 'Цветы от Tim. Они от него.', 'Квіти від Tim. Вони від нього.', 'Çiçekler Tim’den. Onlar ondan.']),
        gap('G3', 'von meinem', I.possessive, 'Den Ring habe ich von ', ' Mann bekommen.', 'meinem', ['meinen', 'meiner'],
          ['I got the ring from my husband.', 'Кольцо я получила от мужа.', 'Перстень я отримала від чоловіка.', 'Yüzüğü kocamdan aldım.'], 'mein'),
        gap('G3', 'von meinen', I.possessive, 'Das Paket ist von ', ' Großeltern.', 'meinen', ['meine', 'meiner'],
          ['The parcel is from my grandparents.', 'Посылка от моих бабушки и дедушки.', 'Посилка від моїх бабусі й дідуся.', 'Paket büyükannemle büyükbabamdan.'], 'mein'),
        gap("G3", "von ihr", I.pronoun, "Ergänze das Pronomen zu „sie (Singular)“ nach „von“: Das Geschenk ist von ", ".", "ihr", ["ihm","sie"], ["Complete the pronoun for sie (singular) after von: Das Geschenk ist von …","Дополните местоимение для sie (ед. число) после von: Das Geschenk ist von …","Доповніть займенник для sie (однина) після von: Das Geschenk ist von …","von sonrasında sie (tekil) zamirini tamamlayın: Das Geschenk ist von …"], "sie", {"c":"p7_von"}),
        gap('G3', 'Kollegen', I.form, 'Die Karte ist von meinem ', ' aus der Firma.', 'Kollegen', ['Kollege', 'Kollegin'],
          ['The card is from my colleague at work.', 'Открытка от моего коллеги по работе.', 'Листівка від мого колеги з роботи.', 'Kart şirketteki iş arkadaşımdan.'], 'der Kollege'),
        gap('G3', 'Von wem?', I.qword, 'Von ', ' ist dieser Gutschein? – Von der ganzen Familie.', 'wem', ['wen', 'wer'],
          ['Who is this voucher from? – From the whole family.', 'От кого этот сертификат? – От всей семьи.', 'Від кого цей сертифікат? – Від усієї родини.', 'Bu hediye çeki kimden? – Bütün aileden.'], 'wer'),
      ],
    },
    {
      title: 'Probier doch mal …!',
      t: ['Why don’t you try …!', 'Попробуй-ка …!', 'Спробуй-но …!', 'Bir denesene …!'],
      card: {
        id: 'p7_empfehlen',
        rule: 'Etwas empfehlen: Probieren Sie doch mal den Kuchen! Probier doch die Suppe! Ich kann ihn Ihnen nur empfehlen. Ich kann sie dir nur empfehlen. Den Film musst du sehen! empfehlen: ich empfehle, du empfiehlst, er empfiehlt, wir empfehlen. Mit doch und mal klingt eine Aufforderung freundlich. Antworten: Danke für den Tipp! Das probiere ich gern.',
        examples: ['Probieren Sie doch mal den Fisch. Ich kann ihn Ihnen nur empfehlen.', 'Was empfiehlst du mir?', 'Danke für den Tipp!'],
        highlight: null,
        t: [
          'Recommending something: Probieren Sie doch mal den Kuchen! (Do try the cake!) Probier doch die Suppe! Ich kann ihn Ihnen nur empfehlen. (I can only recommend it to you.) Ich kann sie dir nur empfehlen. Den Film musst du sehen! empfehlen: ich empfehle, du empfiehlst, er empfiehlt, wir empfehlen. With doch and mal a request sounds friendly. Answers: Danke für den Tipp! (Thanks for the tip!) Das probiere ich gern.',
          'Как что-то порекомендовать: Probieren Sie doch mal den Kuchen! (Попробуйте-ка пирог!) Probier doch die Suppe! Ich kann ihn Ihnen nur empfehlen. (Очень вам его рекомендую.) Ich kann sie dir nur empfehlen. Den Film musst du sehen! empfehlen: ich empfehle, du empfiehlst, er empfiehlt, wir empfehlen. С doch и mal просьба звучит дружелюбно. Ответы: Danke für den Tipp! (Спасибо за совет!) Das probiere ich gern.',
          'Як щось порекомендувати: Probieren Sie doch mal den Kuchen! (Спробуйте-но пиріг!) Probier doch die Suppe! Ich kann ihn Ihnen nur empfehlen. (Дуже вам його рекомендую.) Ich kann sie dir nur empfehlen. Den Film musst du sehen! empfehlen: ich empfehle, du empfiehlst, er empfiehlt, wir empfehlen. Із doch і mal прохання звучить приязно. Відповіді: Danke für den Tipp! (Дякую за пораду!) Das probiere ich gern.',
          'Bir şeyi tavsiye etmek: Probieren Sie doch mal den Kuchen! (Keki bir deneyin!) Probier doch die Suppe! Ich kann ihn Ihnen nur empfehlen. (Onu size kesinlikle tavsiye ederim.) Ich kann sie dir nur empfehlen. Den Film musst du sehen! empfehlen: ich empfehle, du empfiehlst, er empfiehlt, wir empfehlen. doch ve mal ile istek daha samimi olur. Cevaplar: Danke für den Tipp! (Tavsiye için teşekkürler!) Das probiere ich gern.',
        ],
        hint: ['Probier doch mal …! Ich kann ihn (der), es (das), sie (die) dir nur empfehlen.', 'Probier doch mal …! Ich kann ihn (der), es (das), sie (die) dir nur empfehlen. (The pronoun matches the article.)', 'Probier doch mal …! Ich kann ihn (der), es (das), sie (die) dir nur empfehlen. (Местоимение зависит от артикля.)', 'Probier doch mal …! Ich kann ihn (der), es (das), sie (die) dir nur empfehlen. (Займенник залежить від артикля.)', 'Probier doch mal …! Ich kann ihn (der), es (das), sie (die) dir nur empfehlen. (Zamir artikele göre değişir.)'],
      },
      ex: [
        mc('K1', 'empfehlen', I.situation, 'Dein Kollege sucht ein gutes Restaurant. Du kennst das Restaurant „Lindenhof“. Was sagst du?', ['Probier doch mal den „Lindenhof“. Ich kann ihn dir nur empfehlen.', 'Der „Lindenhof“ ist leider geschlossen.', 'Ich esse nie im Restaurant.'],
          ['Your colleague is looking for a good restaurant. You know the “Lindenhof”. What do you say?', 'Ваш коллега ищет хороший ресторан. Вы знаете ресторан «Lindenhof». Что вы скажете?', 'Ваш колега шукає добрий ресторан. Ви знаєте ресторан «Lindenhof». Що ви скажете?', 'İş arkadaşınız iyi bir restoran arıyor. “Lindenhof” restoranını biliyorsunuz. Ne dersiniz?']),
        mc('K1', 'auf eine Empfehlung antworten', I.react, '„Probieren Sie doch mal unseren Apfelkuchen!“', ['Gern, danke für den Tipp!', 'Ich empfehle ihn Ihnen.', 'Das ist tabu.'],
          ['“Do try our apple cake!”', '«Попробуйте-ка наш яблочный пирог!»', '«Спробуйте-но наш яблучний пиріг!»', '“Elmalı kekimizi bir deneyin!”']),
        mc('K1', 'ihn', I.situation, 'Du empfiehlst einer Freundin einen Film. Was sagst du?', ['Ich kann ihn dir nur empfehlen.', 'Ich kann es dir nur empfehlen.', 'Ich kann sie dir nur empfehlen.'],
          ['You are recommending a film to a friend. What do you say?', 'Вы рекомендуете подруге фильм. Что вы скажете?', 'Ви рекомендуєте подрузі фільм. Що ви скажете?', 'Bir arkadaşınıza bir film tavsiye ediyorsunuz. Ne dersiniz?']),
        mc('K1', 'sie Ihnen', I.situation, 'Du empfiehlst Frau Weber eine Suppe. Was sagst du?', ['Ich kann sie Ihnen nur empfehlen.', 'Ich kann sie dir nur empfehlen.', 'Ich kann ihn Ihnen nur empfehlen.'],
          ['You are recommending a soup to Ms Weber. What do you say?', 'Вы рекомендуете госпоже Weber суп. Что вы скажете?', 'Ви рекомендуєте пані Weber суп. Що ви скажете?', 'Weber Hanım’a bir çorba tavsiye ediyorsunuz. Ne dersiniz?']),
        mc('K1', 'du empfiehlst', I.choose, 'Was … du mir? – Den Fisch.', ['empfiehlst', 'empfehlst', 'empfiehlt'],
          ['What do you recommend? – The fish.', 'Что ты мне порекомендуешь? – Рыбу.', 'Що ти мені порекомендуєш? – Рибу.', 'Bana ne tavsiye edersin? – Balığı.']),
        gap('K1', 'er empfiehlt', I.verb, 'Der Kellner ', ' uns den Salat mit Käse.', 'empfiehlt', ['empfehlt', 'empfehlen'],
          ['The waiter recommends the salad with cheese to us.', 'Официант рекомендует нам салат с сыром.', 'Офіціант рекомендує нам салат із сиром.', 'Garson bize peynirli salatayı tavsiye ediyor.'], 'empfehlen'),
        gap('K1', 'Probier doch mal', I.imperative, '', ' doch mal den Tee mit Zitrone! Er ist sehr lecker.', ['Probier', 'Probiere'], ['Probierst', 'Probieren'],
          ['Do try the tea with lemon! It is delicious.', 'Попробуй-ка чай с лимоном! Он очень вкусный.', 'Спробуй-но чай із лимоном! Він дуже смачний.', 'Limonlu çayı bir denesene! Çok lezzetli.'], 'probieren (du)'),
        gap('K1', 'nur empfehlen', I.word, 'Das Buch ist toll. Ich kann es dir ', ' empfehlen.', 'nur', ['nie', 'nicht'],
          ['The book is great. I can only recommend it to you.', 'Книга отличная. Очень тебе её рекомендую.', 'Книжка чудова. Дуже тобі її рекомендую.', 'Kitap harika. Onu sana kesinlikle tavsiye ederim.'], 'nur / nie / nicht'),
        gap('K1', 'Tipp', I.word, 'Danke für den ', '! Das Restaurant probiere ich aus.', 'Tipp', ['Tisch', 'Preis'],
          ['Thanks for the tip! I will try the restaurant.', 'Спасибо за совет! Я схожу в этот ресторан.', 'Дякую за пораду! Я сходжу до цього ресторану.', 'Tavsiye için teşekkürler! Restoranı deneyeceğim.'],
          ['tip, piece of advice', 'совет', 'порада', 'tavsiye']),
        sb('K1', 'nur empfehlen', I.order, 'Ich / kann / ihn / dir / nur / empfehlen.',
          ['I can only recommend it to you.', 'Очень тебе его рекомендую.', 'Дуже тобі його рекомендую.', 'Onu sana kesinlikle tavsiye ederim.']),
      ],
    },
    {
      title: 'Ich schenke gern …',
      t: ['I like giving …', 'Я люблю дарить …', 'Я люблю дарувати …', '… hediye etmeyi severim'],
      card: {
        id: 'p7_vorlieben',
        rule: 'Über Geschenke sprechen: Ich schenke gern Bücher, weil ich selbst gern lese. Ich schenke nicht gern Geld. Ich finde, ein Geschenk sollte persönlich sein. Am liebsten bekomme ich Blumen. In meinem Land schenkt man zur Hochzeit oft Geld. In meiner Heimat bringt man Gästen immer etwas mit. Tabus: Messer darf man auf keinen Fall schenken. Eine Uhr ist bei uns tabu.',
        examples: ['Ich schenke gern etwas Selbstgemachtes.', 'In meinem Land schenkt man keine gelben Blumen.', 'Geld ist bei uns kein Tabu.'],
        highlight: null,
        t: [
          'Talking about presents: Ich schenke gern Bücher, weil ich selbst gern lese. (I like giving books because I like reading myself.) Ich schenke nicht gern Geld. Ich finde, ein Geschenk sollte persönlich sein. (A present should be personal.) Am liebsten bekomme ich Blumen. (I like getting flowers best.) In meinem Land schenkt man zur Hochzeit oft Geld. In meiner Heimat bringt man Gästen immer etwas mit. Taboos: Messer darf man auf keinen Fall schenken. (You must never give knives.) Eine Uhr ist bei uns tabu. (A watch is taboo where I come from.)',
          'Как говорить о подарках: Ich schenke gern Bücher, weil ich selbst gern lese. (Я люблю дарить книги, потому что сам люблю читать.) Ich schenke nicht gern Geld. Ich finde, ein Geschenk sollte persönlich sein. (Подарок должен быть личным.) Am liebsten bekomme ich Blumen. (Больше всего я люблю получать цветы.) In meinem Land schenkt man zur Hochzeit oft Geld. In meiner Heimat bringt man Gästen immer etwas mit. Табу: Messer darf man auf keinen Fall schenken. (Ножи дарить ни в коем случае нельзя.) Eine Uhr ist bei uns tabu. (Часы у нас дарить не принято.)',
          'Як говорити про подарунки: Ich schenke gern Bücher, weil ich selbst gern lese. (Я люблю дарувати книжки, бо сам люблю читати.) Ich schenke nicht gern Geld. Ich finde, ein Geschenk sollte persönlich sein. (Подарунок має бути особистим.) Am liebsten bekomme ich Blumen. (Найбільше я люблю отримувати квіти.) In meinem Land schenkt man zur Hochzeit oft Geld. In meiner Heimat bringt man Gästen immer etwas mit. Табу: Messer darf man auf keinen Fall schenken. (Ножі дарувати в жодному разі не можна.) Eine Uhr ist bei uns tabu. (Годинник у нас дарувати не заведено.)',
          'Hediyelerden söz etmek: Ich schenke gern Bücher, weil ich selbst gern lese. (Kitap hediye etmeyi severim, çünkü kendim de okumayı severim.) Ich schenke nicht gern Geld. Ich finde, ein Geschenk sollte persönlich sein. (Hediye kişiye özel olmalı.) Am liebsten bekomme ich Blumen. (En çok çiçek almayı severim.) In meinem Land schenkt man zur Hochzeit oft Geld. In meiner Heimat bringt man Gästen immer etwas mit. Tabular: Messer darf man auf keinen Fall schenken. (Bıçak kesinlikle hediye edilmez.) Eine Uhr ist bei uns tabu. (Bizde saat hediye etmek tabudur.)',
        ],
        hint: ['auf keinen Fall = niemals. tabu = das macht man nicht. persönlich = extra für diese Person.', 'auf keinen Fall = never, under no circumstances. tabu = you do not do that. persönlich = specially for this person.', 'auf keinen Fall = ни в коем случае. tabu = так не делают. persönlich = специально для этого человека.', 'auf keinen Fall = у жодному разі. tabu = так не роблять. persönlich = спеціально для цієї людини.', 'auf keinen Fall = asla, hiçbir şekilde. tabu = bu yapılmaz. persönlich = özellikle o kişi için.'],
      },
      ex: [
        mc('K2', 'Tabu', I.situation, 'In deiner Heimat schenkt man niemals Messer. Was sagst du?', ['Messer darf man auf keinen Fall schenken.', 'Messer schenke ich am liebsten.', 'Messer sind ein gutes Geschenk.'],
          ['In your home country people never give knives as presents. What do you say?', 'На вашей родине ножи никогда не дарят. Что вы скажете?', 'На вашій батьківщині ножі ніколи не дарують. Що ви скажете?', 'Sizin memleketinizde asla bıçak hediye edilmez. Ne dersiniz?']),
        mc('K2', 'tabu', I.choose, 'Was bedeutet „Das ist tabu“?', ['Das macht man nicht.', 'Das macht man gern.', 'Das ist sehr teuer.'],
          ['What does “Das ist tabu” mean?', 'Что значит «Das ist tabu»?', 'Що означає «Das ist tabu»?', '“Das ist tabu” ne demek?']),
        mc('K2', 'Vorliebe', I.react, '„Was schenkst du gern?“', ['Ich schenke gern Bücher, weil ich selbst gern lese.', 'Ich bekomme gern Bücher.', 'Ich habe morgen Geburtstag.'],
          ['“What do you like giving as a present?”', '«Что ты любишь дарить?»', '«Що ти любиш дарувати?»', '“Ne hediye etmeyi seversin?”']),
        mc('K2', 'persönlich', I.choose, 'Ein Geschenk extra für eine Person, mit viel Liebe gemacht, ist …', ['persönlich', 'tabu', 'teuer'],
          ['A present made specially for one person, with lots of love, is …', 'Подарок, сделанный специально для одного человека и с большой любовью, – …', 'Подарунок, зроблений спеціально для однієї людини і з великою любов’ю, – …', 'Özellikle bir kişi için sevgiyle hazırlanan hediye …']),
        mc('K2', 'man', I.sentence, 'Olga erzählt von ihrem Land.', ['In meiner Heimat schenkt man zur Hochzeit Geld.', 'In meiner Heimat man schenkt zur Hochzeit Geld.', 'In meiner Heimat schenken man zur Hochzeit Geld.'],
          ['Olga is talking about her country.', 'Olga рассказывает о своей стране.', 'Olga розповідає про свою країну.', 'Olga ülkesini anlatıyor.']),
        gap('K2', 'auf keinen Fall', I.word, 'Eine Uhr darf man bei uns auf ', ' Fall schenken. Das bringt Unglück.', 'keinen', ['keine', 'jeden'],
          ['Where I come from you must never give a watch as a present. It brings bad luck.', 'У нас ни в коем случае нельзя дарить часы. Это приносит несчастье.', 'У нас у жодному разі не можна дарувати годинник. Це приносить нещастя.', 'Bizde saat kesinlikle hediye edilmez. Uğursuzluk getirir.'],
          ['no (under no circumstances)', 'ни в коем (случае)', 'у жодному (разі)', 'hiçbir (şekilde)']),
        gap('K2', 'Grund nennen', I.conjunction, 'Ich schenke nicht gern Geld, ', ' das nicht persönlich ist.', 'weil', ['dass', 'wenn'],
          ['I do not like giving money because it is not personal.', 'Я не люблю дарить деньги, потому что это не личный подарок.', 'Я не люблю дарувати гроші, бо це не особистий подарунок.', 'Para hediye etmeyi sevmem, çünkü bu kişisel değil.'], 'weil / dass / wenn'),
        gap('K2', 'in meinem Land', I.word, 'In meinem ', ' schenkt man Kindern zum Geburtstag Süßigkeiten.', ['Land', 'Heimatland'], ['Geschenk', 'Fest'],
          ['In my country people give children sweets for their birthday.', 'В моей стране детям на день рождения дарят сладости.', 'У моїй країні дітям на день народження дарують солодощі.', 'Benim ülkemde çocuklara doğum günlerinde şekerleme hediye edilir.'],
          ['country', 'страна', 'країна', 'ülke']),
        gap('K2', 'am liebsten', I.comparison, 'Am ', ' bekomme ich Blumen. Die mag ich mehr als alles andere.', 'liebsten', ['lieber', 'besten'],
          ['I like getting flowers best. I like them more than anything else.', 'Больше всего я люблю получать цветы. Они нравятся мне больше всего остального.', 'Найбільше я люблю отримувати квіти. Вони подобаються мені більше за все інше.', 'En çok çiçek almayı severim. Onları her şeyden çok severim.'], 'gern'),
        sb('K2', 'gern schenken', I.order, 'Ich / schenke / gern / Bücher.',
          ['I like giving books.', 'Я люблю дарить книги.', 'Я люблю дарувати книжки.', 'Kitap hediye etmeyi severim.'],
          { alt: ['Bücher schenke ich gern.', 'Gern schenke ich Bücher.'] }),
      ],
    },
    {
      title: 'Mir ist wichtig, dass …',
      t: ['It is important to me that …', 'Мне важно, чтобы …', 'Мені важливо, щоб …', 'Benim için … önemli'],
      card: {
        id: 'p7_wichtig',
        rule: 'Sagen, was wichtig ist: Mir ist die Familie wichtig. Mir ist wichtig, dass alle zusammen feiern. Ich finde es toll, wenn viele Gäste kommen. Die Hauptsache ist, dass alle Spaß haben. Hauptsache, das Essen schmeckt. Am wichtigsten ist, dass das Brautpaar glücklich ist. Nicht wichtig: Muss das sein? Ich finde das nicht so toll. Ist das wirklich so wichtig? Das ist mir egal.',
        examples: ['Mir ist wichtig, dass meine Freunde kommen.', 'Ich finde es toll, wenn alle tanzen.', 'Die Hauptsache ist, dass wir zusammen sind.'],
        highlight: null,
        t: [
          'Saying what is important: Mir ist die Familie wichtig. (My family is important to me.) Mir ist wichtig, dass alle zusammen feiern. Ich finde es toll, wenn viele Gäste kommen. (I think it is great when lots of guests come.) Die Hauptsache ist, dass alle Spaß haben. (The main thing is that everyone has fun.) Hauptsache, das Essen schmeckt. Am wichtigsten ist, dass das Brautpaar glücklich ist. (The most important thing is …) Not important: Muss das sein? (Is that really necessary?) Ich finde das nicht so toll. Ist das wirklich so wichtig? Das ist mir egal. (I do not mind.)',
          'Как сказать, что важно: Mir ist die Familie wichtig. (Для меня важна семья.) Mir ist wichtig, dass alle zusammen feiern. Ich finde es toll, wenn viele Gäste kommen. (По-моему, здорово, когда приходит много гостей.) Die Hauptsache ist, dass alle Spaß haben. (Главное, чтобы всем было весело.) Hauptsache, das Essen schmeckt. Am wichtigsten ist, dass das Brautpaar glücklich ist. (Важнее всего, чтобы …) Неважно: Muss das sein? (Это обязательно?) Ich finde das nicht so toll. Ist das wirklich so wichtig? Das ist mir egal. (Мне всё равно.)',
          'Як сказати, що важливо: Mir ist die Familie wichtig. (Для мене важлива родина.) Mir ist wichtig, dass alle zusammen feiern. Ich finde es toll, wenn viele Gäste kommen. (На мою думку, чудово, коли приходить багато гостей.) Die Hauptsache ist, dass alle Spaß haben. (Головне, щоб усім було весело.) Hauptsache, das Essen schmeckt. Am wichtigsten ist, dass das Brautpaar glücklich ist. (Найважливіше, щоб …) Неважливо: Muss das sein? (Це обов’язково?) Ich finde das nicht so toll. Ist das wirklich so wichtig? Das ist mir egal. (Мені байдуже.)',
          'Neyin önemli olduğunu söylemek: Mir ist die Familie wichtig. (Benim için aile önemli.) Mir ist wichtig, dass alle zusammen feiern. Ich finde es toll, wenn viele Gäste kommen. (Çok misafir gelmesini harika buluyorum.) Die Hauptsache ist, dass alle Spaß haben. (Önemli olan herkesin eğlenmesi.) Hauptsache, das Essen schmeckt. Am wichtigsten ist, dass das Brautpaar glücklich ist. (En önemlisi …) Önemli değil: Muss das sein? (Bu şart mı?) Ich finde das nicht so toll. Ist das wirklich so wichtig? Das ist mir egal. (Benim için fark etmez.)',
        ],
        hint: ['Mir ist … wichtig. Mir ist wichtig, dass … (Verb am Ende). Hauptsache = das Wichtigste.', 'Mir ist … wichtig. Mir ist wichtig, dass … (verb at the end). Hauptsache = the most important thing.', 'Mir ist … wichtig. Mir ist wichtig, dass … (глагол в конце). Hauptsache = самое главное.', 'Mir ist … wichtig. Mir ist wichtig, dass … (дієслово в кінці). Hauptsache = найголовніше.', 'Mir ist … wichtig. Mir ist wichtig, dass … (fiil sonda). Hauptsache = en önemli şey.'],
      },
      ex: [
        mc('K3', 'wichtig', I.situation, 'Für dich ist gutes Essen bei einem Fest sehr wichtig. Was sagst du?', ['Mir ist wichtig, dass das Essen gut ist.', 'Mir ist egal, wie das Essen ist.', 'Muss das Essen sein?'],
          ['Good food at a party is very important to you. What do you say?', 'Для вас на празднике очень важна хорошая еда. Что вы скажете?', 'Для вас на святі дуже важлива добра їжа. Що ви скажете?', 'Sizin için bir kutlamada iyi yemek çok önemli. Ne dersiniz?']),
        mc('K3', 'Muss das sein?', I.situation, 'Deine Freundin möchte 200 Gäste einladen. Du findest das zu viel. Was sagst du?', ['Muss das sein?', 'Das ist die Hauptsache.', 'Das finde ich toll.'],
          ['Your friend wants to invite 200 guests. You think that is too many. What do you say?', 'Ваша подруга хочет пригласить 200 гостей. Вы считаете, что это слишком много. Что вы скажете?', 'Ваша подруга хоче запросити 200 гостей. Ви вважаєте, що це забагато. Що ви скажете?', 'Arkadaşınız 200 misafir davet etmek istiyor. Bunu fazla buluyorsunuz. Ne dersiniz?']),
        mc('K3', 'Hauptsache', I.choose, 'Was bedeutet „Hauptsache, wir haben Spaß“?', ['Spaß ist das Wichtigste.', 'Spaß ist nicht wichtig.', 'Wir haben keinen Spaß.'],
          ['What does “Hauptsache, wir haben Spaß” mean?', 'Что значит «Hauptsache, wir haben Spaß»?', 'Що означає «Hauptsache, wir haben Spaß»?', '“Hauptsache, wir haben Spaß” ne demek?']),
        mc('K3', 'am wichtigsten', I.sentence, 'Tom spricht über seine Hochzeit.', ['Am wichtigsten ist, dass meine Familie da ist.', 'Am wichtigsten ist, dass meine Familie ist da.', 'Am wichtigsten ist, dass ist meine Familie da.'],
          ['Tom is talking about his wedding.', 'Tom говорит о своей свадьбе.', 'Tom говорить про своє весілля.', 'Tom düğününden söz ediyor.']),
        mc('K3', 'Ich finde es toll, wenn …', I.choose, 'Ich finde es toll, … alle zusammen singen.', ['wenn', 'aber', 'oder'],
          ['I think it is great when everyone sings together.', 'По-моему, здорово, когда все поют вместе.', 'На мою думку, чудово, коли всі співають разом.', 'Herkesin birlikte şarkı söylemesini harika buluyorum.']),
        gap('K3', 'Mir ist wichtig', I.pronoun, '', ' ist wichtig, dass meine Eltern bei dem Fest dabei sind.', 'Mir', ['Mich', 'Ich'],
          ['It is important to me that my parents are at the party.', 'Мне важно, чтобы мои родители были на празднике.', 'Мені важливо, щоб мої батьки були на святі.', 'Annemle babamın kutlamada olması benim için önemli.'], 'ich'),
        gap('K3', 'Hauptsache', I.word, 'Das Wetter ist egal. Die ', ' ist, dass alle Freunde kommen.', 'Hauptsache', ['Hochzeit', 'Hausaufgabe'],
          ['The weather does not matter. The main thing is that all our friends come.', 'Погода не имеет значения. Главное, чтобы пришли все друзья.', 'Погода не має значення. Головне, щоб прийшли всі друзі.', 'Hava fark etmez. Önemli olan bütün arkadaşların gelmesi.'],
          ['main thing', 'главное', 'головне', 'en önemli şey']),
        gap('K3', 'am wichtigsten', I.comparison, 'Am ', ' ist, dass das Brautpaar glücklich ist.', 'wichtigsten', ['wichtiger', 'wichtig'],
          ['The most important thing is that the bride and groom are happy.', 'Важнее всего, чтобы жених и невеста были счастливы.', 'Найважливіше, щоб наречені були щасливі.', 'En önemlisi gelin ve damadın mutlu olması.'], 'wichtig'),
        gap('K3', 'Verb am Ende', I.verb, 'Mir ist wichtig, dass das Fest nicht zu teuer ', '.', 'ist', ['sind', 'sein'],
          ['It is important to me that the party is not too expensive.', 'Мне важно, чтобы праздник не был слишком дорогим.', 'Мені важливо, щоб свято не було надто дорогим.', 'Kutlamanın çok pahalı olmaması benim için önemli.'], 'sein'),
        sb('K3', 'wichtig', I.order, 'Mir / ist / die Musik / sehr wichtig.',
          ['The music is very important to me.', 'Для меня очень важна музыка.', 'Для мене дуже важлива музика.', 'Benim için müzik çok önemli.'],
          { alt: ['Die Musik ist mir sehr wichtig.'] }),
      ],
    },
    {
      title: 'Die Hochzeit',
      t: ['The wedding', 'Свадьба', 'Весілля', 'Düğün'],
      card: {
        id: 'p7_hochzeit',
        rule: 'Die Hochzeit: Die Braut und der Bräutigam sind das Brautpaar. Bei der Trauung im Standesamt oder in der Kirche sagen beide Ja. Danach tragen sie Ringe. Die Braut trägt oft ein weißes Brautkleid. Nach der Trauung gibt es die Hochzeitsfeier mit den Gästen: Man isst die Hochzeitstorte, tanzt und feiert. Man gratuliert dem Brautpaar: Herzlichen Glückwunsch zur Hochzeit! Alles Gute für euch!',
        examples: ['Die Trauung beginnt um elf Uhr im Standesamt.', 'Das Brautpaar tanzt den ersten Tanz.', 'Herzlichen Glückwunsch zur Hochzeit!'],
        highlight: 'article',
        t: [
          'The wedding: die Braut (bride) and der Bräutigam (bridegroom) are das Brautpaar (the bridal couple). At die Trauung (the wedding ceremony) im Standesamt (at the registry office) or in church both say yes. After that they wear Ringe (rings). The bride often wears a white Brautkleid (wedding dress). After the ceremony there is die Hochzeitsfeier (the wedding reception) with the guests: people eat die Hochzeitstorte (the wedding cake), dance and celebrate. You congratulate the couple: Herzlichen Glückwunsch zur Hochzeit! Alles Gute für euch!',
          'Свадьба: die Braut (невеста) и der Bräutigam (жених) – это das Brautpaar (жених и невеста). На die Trauung (церемонии бракосочетания) im Standesamt (в загсе) или в церкви оба говорят «да». После этого они носят Ringe (кольца). Невеста часто надевает белое Brautkleid (свадебное платье). После церемонии проходит die Hochzeitsfeier (свадебный праздник) с гостями: едят die Hochzeitstorte (свадебный торт), танцуют и празднуют. Жениха и невесту поздравляют: Herzlichen Glückwunsch zur Hochzeit! Alles Gute für euch!',
          'Весілля: die Braut (наречена) і der Bräutigam (наречений) – це das Brautpaar (наречені). На die Trauung (церемонії шлюбу) im Standesamt (у РАЦСі) або в церкві обоє кажуть «так». Після цього вони носять Ringe (обручки). Наречена часто вдягає білу Brautkleid (весільну сукню). Після церемонії відбувається die Hochzeitsfeier (весільне свято) з гостями: їдять die Hochzeitstorte (весільний торт), танцюють і святкують. Наречених вітають: Herzlichen Glückwunsch zur Hochzeit! Alles Gute für euch!',
          'Düğün: die Braut (gelin) ve der Bräutigam (damat) birlikte das Brautpaar’dır (gelin ve damat). Die Trauung’da (nikâh töreni) im Standesamt (evlendirme dairesinde) ya da kilisede ikisi de “evet” der. Ondan sonra Ringe (yüzük) takarlar. Gelin çoğu zaman beyaz bir Brautkleid (gelinlik) giyer. Nikâhtan sonra misafirlerle die Hochzeitsfeier (düğün kutlaması) yapılır: die Hochzeitstorte (düğün pastası) yenir, dans edilir ve kutlanır. Gelin ve damat şöyle kutlanır: Herzlichen Glückwunsch zur Hochzeit! Alles Gute für euch!',
        ],
        hint: ['Braut + Bräutigam = Brautpaar. Trauung = der Moment mit dem Ja. Hochzeitsfeier = das Fest danach.', 'Braut + Bräutigam = Brautpaar. Trauung = the moment when they say yes. Hochzeitsfeier = the party afterwards.', 'Braut + Bräutigam = Brautpaar. Trauung = момент, когда говорят «да». Hochzeitsfeier = праздник после этого.', 'Braut + Bräutigam = Brautpaar. Trauung = момент, коли кажуть «так». Hochzeitsfeier = свято після цього.', 'Braut + Bräutigam = Brautpaar. Trauung = “evet” denilen an. Hochzeitsfeier = ondan sonraki kutlama.'],
      },
      ex: [
        mc('W2', 'Braut', I.choose, 'Eine Frau heiratet heute. Sie ist …', ['die Braut', 'die Trauung', 'der Bräutigam'],
          ['A woman is getting married today. She is …', 'Женщина сегодня выходит замуж. Она …', 'Жінка сьогодні виходить заміж. Вона …', 'Bir kadın bugün evleniyor. O …']),
        mc('W2', 'Bräutigam', I.choose, 'Ein Mann heiratet heute. Er ist …', ['der Bräutigam', 'das Brautpaar', 'der Gast'],
          ['A man is getting married today. He is …', 'Мужчина сегодня женится. Он …', 'Чоловік сьогодні одружується. Він …', 'Bir erkek bugün evleniyor. O …']),
        mc('W2', 'Trauung', I.choose, 'Das Paar sagt im Standesamt „Ja“. Wie heißt dieser Moment?', ['die Trauung', 'die Hochzeitstorte', 'der Ring'],
          ['The couple say “yes” at the registry office. What is this moment called?', 'Пара говорит «да» в загсе. Как называется этот момент?', 'Пара каже «так» у РАЦСі. Як називається цей момент?', 'Çift evlendirme dairesinde “evet” diyor. Bu ana ne denir?']),
        mc('W2', 'gratulieren', I.situation, 'Was sagst du zum Brautpaar?', ['Herzlichen Glückwunsch zur Hochzeit!', 'Gute Besserung!', 'Guten Appetit!'],
          ['What do you say to the bride and groom?', 'Что вы скажете жениху и невесте?', 'Що ви скажете нареченим?', 'Gelin ve damada ne dersiniz?']),
        mc('W2', 'Hochzeit', I.odd, 'Drei Wörter passen zur Hochzeit, ein Wort nicht.', ['Zeugnis', 'Braut', 'Trauung', 'Ring'], null),
        gap('W2', 'Brautpaar', I.word, 'Die Braut und der Bräutigam sind zusammen das ', '.', 'Brautpaar', ['Brautkleid', 'Standesamt'],
          ['The bride and the bridegroom together are the bridal couple.', 'Невеста и жених вместе – это молодожёны.', 'Наречена й наречений разом – це молодята.', 'Gelin ve damat birlikte gelin-damat çiftidir.'],
          ['bridal couple', 'молодожёны', 'молодята', 'gelin ve damat']),
        gap('W2', 'Ringe', I.form, 'Bei der Trauung geben sich Braut und Bräutigam die ', '.', 'Ringe', ['Ring', 'Ringen'],
          ['At the wedding ceremony the bride and groom exchange rings.', 'Во время церемонии жених и невеста обмениваются кольцами.', 'Під час церемонії наречені обмінюються обручками.', 'Nikâh töreninde gelin ve damat birbirine yüzük takar.'], 'der Ring (Plural)'),
        gap('W2', 'Hochzeitsfeier', I.word, 'Nach der Trauung gehen alle zur ', ' ins Restaurant. Dort essen und tanzen die Gäste.', 'Hochzeitsfeier', ['Hochzeitstorte', 'Trauung'],
          ['After the ceremony everyone goes to the wedding reception at the restaurant. The guests eat and dance there.', 'После церемонии все идут на свадебный праздник в ресторан. Там гости едят и танцуют.', 'Після церемонії всі йдуть на весільне свято до ресторану. Там гості їдять і танцюють.', 'Nikâhtan sonra herkes düğün kutlaması için restorana gidiyor. Misafirler orada yemek yiyip dans ediyor.'],
          ['wedding reception', 'свадебный праздник', 'весільне свято', 'düğün kutlaması']),
        gap('W2', 'Brautkleid', I.word, 'Die Braut trägt ein langes weißes ', '.', 'Brautkleid', ['Brautpaar', 'Standesamt'],
          ['The bride is wearing a long white wedding dress.', 'На невесте длинное белое свадебное платье.', 'На нареченій довга біла весільна сукня.', 'Gelin uzun beyaz bir gelinlik giyiyor.'],
          ['wedding dress', 'свадебное платье', 'весільна сукня', 'gelinlik']),
        sb('W2', 'gratulieren', I.order, 'Wir / gratulieren / dem Brautpaar / zur Hochzeit.',
          ['We congratulate the bride and groom on their wedding.', 'Мы поздравляем жениха и невесту со свадьбой.', 'Ми вітаємо наречених із весіллям.', 'Gelin ve damadın düğününü kutluyoruz.'],
          { alt: ['Zur Hochzeit gratulieren wir dem Brautpaar.', 'Dem Brautpaar gratulieren wir zur Hochzeit.'] }),
      ],
    },
    {
      title: 'Ein Fest planen',
      t: ['Planning a party', 'Планируем праздник', 'Плануємо свято', 'Bir kutlama planlamak'],
      card: {
        id: 'p7_fest',
        rule: 'Ein Fest planen und einladen: Unser Fest findet am 12. Juli um 18 Uhr statt. Wir feiern im Garten, im Restaurant oder zu Hause bei Lena. Unser Motto ist „Sommer“. Der Raum ist mit Blumen und Lichtern dekoriert. Zu essen gibt es Salate und Kuchen. Zu trinken gibt es Saft und Wasser. Natürlich haben wir auch Musik. Ihr müsst nichts mitbringen. Bitte sagt bis Freitag Bescheid. Von einem Fest berichten: Die Feier war toll. Wir haben bis Mitternacht getanzt.',
        examples: ['Unser Fest findet am Samstag ab 19 Uhr statt.', 'Zu essen gibt es Pizza und Salat.', 'Wir feiern bei mir zu Hause.'],
        highlight: null,
        t: [
          'Planning a party and inviting people: Unser Fest findet am 12. Juli um 18 Uhr statt. (Our party takes place on …) Wir feiern im Garten, im Restaurant oder zu Hause bei Lena. (at Lena’s place) Unser Motto ist „Sommer“. (Our theme is …) Der Raum ist mit Blumen und Lichtern dekoriert. (decorated) Zu essen gibt es Salate und Kuchen. Zu trinken gibt es Saft und Wasser. Natürlich haben wir auch Musik. Ihr müsst nichts mitbringen. (You do not have to bring anything.) Bitte sagt bis Freitag Bescheid. (Please let us know by Friday.) Reporting on a party: Die Feier war toll. Wir haben bis Mitternacht getanzt.',
          'Как спланировать праздник и пригласить гостей: Unser Fest findet am 12. Juli um 18 Uhr statt. (Наш праздник состоится …) Wir feiern im Garten, im Restaurant oder zu Hause bei Lena. (дома у Lena) Unser Motto ist „Sommer“. (Наша тема – …) Der Raum ist mit Blumen und Lichtern dekoriert. (украшен) Zu essen gibt es Salate und Kuchen. Zu trinken gibt es Saft und Wasser. Natürlich haben wir auch Musik. Ihr müsst nichts mitbringen. (Вам ничего не нужно приносить.) Bitte sagt bis Freitag Bescheid. (Пожалуйста, дайте знать до пятницы.) Как рассказать о празднике: Die Feier war toll. Wir haben bis Mitternacht getanzt.',
          'Як спланувати свято і запросити гостей: Unser Fest findet am 12. Juli um 18 Uhr statt. (Наше свято відбудеться …) Wir feiern im Garten, im Restaurant oder zu Hause bei Lena. (удома в Lena) Unser Motto ist „Sommer“. (Наша тема – …) Der Raum ist mit Blumen und Lichtern dekoriert. (прикрашений) Zu essen gibt es Salate und Kuchen. Zu trinken gibt es Saft und Wasser. Natürlich haben wir auch Musik. Ihr müsst nichts mitbringen. (Вам нічого не треба приносити.) Bitte sagt bis Freitag Bescheid. (Будь ласка, дайте знати до п’ятниці.) Як розповісти про свято: Die Feier war toll. Wir haben bis Mitternacht getanzt.',
          'Bir kutlama planlamak ve davet etmek: Unser Fest findet am 12. Juli um 18 Uhr statt. (Kutlamamız … yapılacak.) Wir feiern im Garten, im Restaurant oder zu Hause bei Lena. (Lena’nın evinde) Unser Motto ist „Sommer“. (Temamız …) Der Raum ist mit Blumen und Lichtern dekoriert. (süslenmiş) Zu essen gibt es Salate und Kuchen. Zu trinken gibt es Saft und Wasser. Natürlich haben wir auch Musik. Ihr müsst nichts mitbringen. (Bir şey getirmenize gerek yok.) Bitte sagt bis Freitag Bescheid. (Lütfen cumaya kadar haber verin.) Bir kutlamayı anlatmak: Die Feier war toll. Wir haben bis Mitternacht getanzt.',
        ],
        hint: ['Wann? am … um … Uhr. Wo? im Garten, bei Lena. Was gibt es? Zu essen gibt es … Zu trinken gibt es …', 'When? am … um … Uhr. Where? im Garten, bei Lena. What is there? Zu essen gibt es … Zu trinken gibt es …', 'Когда? am … um … Uhr. Где? im Garten, bei Lena. Что будет? Zu essen gibt es … Zu trinken gibt es …', 'Коли? am … um … Uhr. Де? im Garten, bei Lena. Що буде? Zu essen gibt es … Zu trinken gibt es …', 'Ne zaman? am … um … Uhr. Nerede? im Garten, bei Lena. Ne var? Zu essen gibt es … Zu trinken gibt es …'],
      },
      ex: [
        mc('K4', 'einladen', I.choose, 'Du schreibst eine Einladung. Welcher Satz passt?', ['Unser Fest findet am 3. Mai um 19 Uhr statt.', 'Unser Fest war sehr schön.', 'Wir haben bis Mitternacht getanzt.'],
          ['You are writing an invitation. Which sentence fits?', 'Вы пишете приглашение. Какое предложение подходит?', 'Ви пишете запрошення. Яке речення підходить?', 'Bir davetiye yazıyorsunuz. Hangi cümle uygun?']),
        mc('K4', 'Wo?', I.react, '„Wo feiert ihr?“', ['Wir feiern bei Jonas im Garten.', 'Wir feiern am Samstag.', 'Wir feiern mit Musik.'],
          ['“Where are you having the party?”', '«Где вы празднуете?»', '«Де ви святкуєте?»', '“Nerede kutluyorsunuz?”']),
        mc('K4', 'Zu essen gibt es …', I.choose, 'Was passt zum Essen auf dem Fest?', ['Zu essen gibt es Suppe und Salat.', 'Zu trinken gibt es Suppe und Salat.', 'Zu essen gibt es Musik.'],
          ['Which sentence is about the food at the party?', 'Какое предложение – о еде на празднике?', 'Яке речення – про їжу на святі?', 'Hangi cümle kutlamadaki yemekle ilgili?']),
        mc('K4', 'berichten', I.choose, 'Das Fest ist vorbei. Du erzählst einem Freund. Was passt?', ['Die Feier war toll. Wir haben viel getanzt.', 'Die Feier findet am Samstag statt.', 'Bitte sagt bis Freitag Bescheid.'],
          ['The party is over. You are telling a friend about it. What fits?', 'Праздник закончился. Вы рассказываете другу. Что подходит?', 'Свято закінчилося. Ви розповідаєте другові. Що підходить?', 'Kutlama bitti. Bir arkadaşınıza anlatıyorsunuz. Hangisi uygun?']),
        mc('K4', 'Bescheid sagen', I.choose, 'Die Gäste sollen antworten, ob sie kommen. Was schreibst du?', ['Bitte sagt bis Freitag Bescheid.', 'Bitte bringt bis Freitag Musik.', 'Bitte feiert bis Freitag.'],
          ['The guests should reply and say whether they are coming. What do you write?', 'Гости должны ответить, придут ли они. Что вы напишете?', 'Гості мають відповісти, чи прийдуть вони. Що ви напишете?', 'Misafirler gelip gelmeyeceklerini bildirsin. Ne yazarsınız?']),
        gap('K4', 'stattfinden', I.verb, 'Unser Fest ', ' am 20. Juni ab 17 Uhr statt.', 'findet', ['finden', 'feiert'],
          ['Our party takes place on 20 June from 5 pm.', 'Наш праздник состоится 20 июня с 17 часов.', 'Наше свято відбудеться 20 червня з 17 години.', 'Kutlamamız 20 Haziran’da saat 17’den itibaren yapılacak.'], 'stattfinden'),
        gap('K4', 'bei', I.prep, 'Wir feiern zu Hause ', ' Dilara. Sie hat einen großen Garten.', 'bei', ['von', 'nach'],
          ['We are having the party at Dilara’s place. She has a big garden.', 'Мы празднуем дома у Dilara. У неё большой сад.', 'Ми святкуємо вдома в Dilara. У неї великий сад.', 'Dilara’nın evinde kutluyoruz. Onun büyük bir bahçesi var.'], 'bei / von / nach'),
        gap('K4', 'Zu trinken gibt es …', I.verb, 'Zu ', ' gibt es Limonade, Saft und Kaffee.', 'trinken', ['essen', 'feiern'],
          ['To drink there is lemonade, juice and coffee.', 'Из напитков будут лимонад, сок и кофе.', 'Із напоїв будуть лимонад, сік і кава.', 'İçecek olarak limonata, meyve suyu ve kahve var.'],
          ['drink', 'пить', 'пити', 'içmek']),
        gap('K4', 'dekoriert', I.participle, 'Der Raum ist mit Blumen und Luftballons ', '.', 'dekoriert', ['gedekoriert', 'dekorieren'],
          ['The room is decorated with flowers and balloons.', 'Зал украшен цветами и воздушными шарами.', 'Зала прикрашена квітами й повітряними кульками.', 'Salon çiçekler ve balonlarla süslenmiş.'], 'dekorieren'),
        sb('K4', 'Zu essen gibt es …', I.order, 'Zu essen / gibt / es / Kuchen und Salat.',
          ['To eat there is cake and salad.', 'Из еды будут пирог и салат.', 'З їжі будуть пиріг і салат.', 'Yiyecek olarak kek ve salata var.'],
          { alt: ['Es gibt Kuchen und Salat zu essen.'] }),
      ],
    },
    {
      title: 'Nachrichten von der Hochzeit',
      t: ['Messages from the wedding', 'Сообщения со свадьбы', 'Повідомлення з весілля', 'Düğünden mesajlar'],
      card: {
        id: 'p7_nachrichten',
        rule: 'Kurznachrichten verstehen: Nachrichten auf dem Handy sind kurz. Oft fehlen Wörter: Bin gleich da! (Ich bin gleich da.) Achte auf Zeitangaben: gerade (jetzt, in diesem Moment), gleich (in wenigen Minuten), schon (es ist passiert), noch nicht (bis jetzt ist es nicht passiert), in zehn Minuten, vor einer Stunde, später.',
        examples: ['In zehn Minuten beginnt die Trauung.', 'Das Brautpaar ist gerade angekommen.', 'Die Torte ist noch nicht da.'],
        highlight: null,
        t: [
          'Understanding short messages: messages on a mobile are short. Words are often left out: Bin gleich da! (Ich bin gleich da. – I will be there in a moment.) Look for time expressions: gerade (right now, at this moment), gleich (in a few minutes), schon (already: it has happened), noch nicht (not yet: it has not happened so far), in zehn Minuten, vor einer Stunde (an hour ago), später (later).',
          'Как понимать короткие сообщения: сообщения в телефоне короткие. Часто слова пропускают: Bin gleich da! (Ich bin gleich da. – Сейчас буду.) Обращайте внимание на указания времени: gerade (сейчас, в этот момент), gleich (через несколько минут), schon (уже: это случилось), noch nicht (ещё не: пока этого не произошло), in zehn Minuten, vor einer Stunde (час назад), später (позже).',
          'Як розуміти короткі повідомлення: повідомлення в телефоні короткі. Часто слова пропускають: Bin gleich da! (Ich bin gleich da. – Зараз буду.) Звертайте увагу на вказівки часу: gerade (зараз, у цю мить), gleich (за кілька хвилин), schon (уже: це сталося), noch nicht (ще не: поки цього не сталося), in zehn Minuten, vor einer Stunde (годину тому), später (пізніше).',
          'Kısa mesajları anlamak: Telefondaki mesajlar kısadır. Çoğu zaman kelimeler atlanır: Bin gleich da! (Ich bin gleich da. – Hemen geliyorum.) Zaman ifadelerine dikkat edin: gerade (şu anda), gleich (birkaç dakika içinde), schon (çoktan: oldu), noch nicht (henüz değil: şimdiye kadar olmadı), in zehn Minuten, vor einer Stunde (bir saat önce), später (daha sonra).',
        ],
        hint: ['gerade = jetzt. gleich = in wenigen Minuten. schon = es ist passiert. noch nicht = bis jetzt nicht.', 'gerade = now. gleich = in a few minutes. schon = it has happened. noch nicht = not so far.', 'gerade = сейчас. gleich = через несколько минут. schon = это случилось. noch nicht = пока нет.', 'gerade = зараз. gleich = за кілька хвилин. schon = це сталося. noch nicht = поки ні.', 'gerade = şimdi. gleich = birkaç dakika içinde. schon = oldu. noch nicht = şimdiye kadar olmadı.'],
      },
      ex: [
        mc("Z1", "Wann?", I.read, "Nachrichten von Milan: „10.50 Uhr: In zehn Minuten beginnt die Trauung. Der Bräutigam ist noch nicht da! – 11.05 Uhr: Er ist da. Das Kleid ist wunderschön. – 11.40 Uhr: Sie haben Ja gesagt! Alle weinen. – 13.00 Uhr: Jetzt gibt es Essen. Die Torte kommt später.“ Wann beginnt die Trauung?", ["Um 11 Uhr.","Um 10.50 Uhr.","Um 13 Uhr."], ["When does the wedding ceremony begin?","Когда начинается церемония?","Коли починається церемонія?","Nikâh töreni ne zaman başlıyor?"], {"c":"p7_nachrichten"}),
        mc("Z1", "Problem", I.read, "Nachrichten von Milan: „10.50 Uhr: In zehn Minuten beginnt die Trauung. Der Bräutigam ist noch nicht da! – 11.05 Uhr: Er ist da. Das Kleid ist wunderschön. – 11.40 Uhr: Sie haben Ja gesagt! Alle weinen. – 13.00 Uhr: Jetzt gibt es Essen. Die Torte kommt später.“ Was ist um 10.50 Uhr das Problem?", ["Der Bräutigam ist noch nicht gekommen.","Es gibt kein Essen.","Die Torte ist nicht fertig."], ["What is the problem at 10.50?","В чём проблема в 10.50?","У чому проблема о 10.50?","Saat 10.50’de sorun ne?"], {"c":"p7_nachrichten","sitovOptionOrder":["Es gibt kein Essen.","Die Torte ist nicht fertig.","Der Bräutigam ist noch nicht gekommen."]}),
        mc("Z1", "Was?", I.read, "Nachrichten von Milan: „10.50 Uhr: In zehn Minuten beginnt die Trauung. Der Bräutigam ist noch nicht da! – 11.05 Uhr: Er ist da. Das Kleid ist wunderschön. – 11.40 Uhr: Sie haben Ja gesagt! Alle weinen. – 13.00 Uhr: Jetzt gibt es Essen. Die Torte kommt später.“ Was passiert um 13 Uhr?", ["Die Gäste essen.","Die Trauung beginnt.","Alle essen die Torte."], ["What happens at 1 pm?","Что происходит в 13 часов?","Що відбувається о 13 годині?","Saat 13’te ne oluyor?"], {"c":"p7_nachrichten"}),
        mc("Z1", "Wo?", I.read, "Nachricht von Samir an Leon: „Die Feier ist super! Wir sind im Restaurant ‚Seeblick‘. Das Brautpaar hat gerade getanzt, jetzt tanzen alle. Onkel Paul hat eine lustige Rede gehalten. Schade, dass du krank bist. Ich schicke dir gleich Fotos!“ Wo ist die Feier?", ["In einem Restaurant.","Im Standesamt.","Bei Samir zu Hause."], ["Where is the party?","Где проходит праздник?","Де відбувається свято?","Kutlama nerede?"], {"c":"p7_nachrichten"}),
        mc("Z1", "Warum?", I.read, "Nachricht von Samir an Leon: „Die Feier ist super! Wir sind im Restaurant ‚Seeblick‘. Das Brautpaar hat gerade getanzt, jetzt tanzen alle. Onkel Paul hat eine lustige Rede gehalten. Schade, dass du krank bist. Ich schicke dir gleich Fotos!“ Warum ist Leon nicht bei der Feier?", ["Er ist krank.","Er mag keine Hochzeiten.","Er muss arbeiten."], ["Why is Leon not at the party?","Почему Leon нет на празднике?","Чому Leon немає на святі?","Leon neden kutlamada değil?"], {"c":"p7_nachrichten","sitovOptionOrder":["Er mag keine Hochzeiten.","Er muss arbeiten.","Er ist krank."]}),
        mc("Z1", "Was?", I.read, "Nachricht von Samir an Leon: „Die Feier ist super! Wir sind im Restaurant ‚Seeblick‘. Das Brautpaar hat gerade getanzt, jetzt tanzen alle. Onkel Paul hat eine lustige Rede gehalten. Schade, dass du krank bist. Ich schicke dir gleich Fotos!“ Was schickt Samir gleich?", ["Fotos.","Die Torte.","Eine Einladung."], ["What is Samir going to send in a moment?","Что Samir сейчас отправит?","Що Samir зараз надішле?","Samir birazdan ne gönderecek?"], {"c":"p7_nachrichten"}),
        gap('Z1', 'gerade', I.adverb, 'Das Brautpaar ist ', ' angekommen. Jetzt, in diesem Moment, steigen sie aus dem Auto.', ['gerade', 'eben', 'soeben'], ['gleich', 'gestern'],
          ['The bride and groom have just arrived. Right now, at this moment, they are getting out of the car.', 'Жених и невеста только что приехали. Прямо сейчас они выходят из машины.', 'Наречені щойно приїхали. Саме зараз вони виходять із машини.', 'Gelin ve damat az önce geldi. Şu anda arabadan iniyorlar.'],
          ['just now', 'только что', 'щойно', 'az önce']),
      ],
    },
  ],
}

export default path
