import pathlib,json,hashlib,subprocess,collections
R=pathlib.Path('/Users/denniskostjuk/.codex/worktrees/sitov-night-s1/SmartGerman');C=pathlib.Path('/Users/denniskostjuk/Documents/SitovAcademy/SmartGerman/.git/sitov-orchestration/SITOV-NIGHT-2026-10-08');O=C/'S1';d=json.loads((O/'epoch47-coverage-private.json').read_text());inv=json.loads((O/'epoch47-inventory-snapshot-private.json').read_text());sha=lambda b:hashlib.sha256(b).hexdigest();canon=lambda x:json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode();source=d['sourceCommit'];paths={};snap={'sourceCommit':source,'inventorySHA256':d['inventorySHA256'],'files':[]}
for name,h in d['seedFileByteSHA256'].items():
 b=subprocess.check_output(['git','show',source+':supabase/seeds/'+name],cwd=R);assert sha(b)==h and b==(R/'supabase/seeds'/name).read_bytes();ps=json.loads(b);snap['files'].append({'file':'supabase/seeds/'+name,'bytes':len(b),'sha256':h,'utf8':b.decode()})
 for p in ps:
  for n in p.get('nodes',[]):paths[(p['level'].lower(),n['id'])]=(p,n)
p=O/'epoch47-source-snapshot-private.json';p.write_text(json.dumps(snap,ensure_ascii=False)+'\n');p.chmod(0o600)
s4= json.loads((C/'master/M-S4-epoch48-final-editorial-context-review-input-private.json').read_text());excluded={x['id']for x in s4['tasks']};assert len(excluded)==18;missing=[x for x in d['rows']if not x['explicitAcceptCandidate'] and x['id']not in excluded]
def priority(x):
 taskhit=any(x['hashDiscovery']['task'][k]for k in x['hashDiscovery']['task'])
 return (0 if not x['documentedSemanticRead'] and not taskhit else 1 if not x['documentedSemanticRead'] else 2 if not x['exactCurrentTaskAndParentRead'] else 3,x['level'],x['nodeSourceId'],x['ref'])
missing.sort(key=priority);blocks=[];allids=[]
for offset in range(0,len(missing),30):
 selected=missing[offset:offset+30];rows=[]
 for x in selected:
  p,n=paths[(x['level'].lower(),x['nodeSourceId'])];t=next(t for t in n['exercises']if t['id']==x['id']);parent={k:v for k,v in n.items()if k!='exercises'};goals=p.get('objectives',[]);assert t['id']not in allids and t['id']not in excluded;allids.append(t['id']);assert set(t.get('translations',{}))=={'en','ru','uk','tr'}
  rows.append({'id':x['id'],'ref':x['ref'],'level':x['level'],'contextKey':x['level']+'/'+p['id']+'/'+n['id'],'wholeTask':t,'wholeParentMinusChildren':parent,'allPathObjectives':goals,'wholeTaskSHA256':sha(canon(t)),'wholeParentMinusChildrenSHA256':sha(canon(parent)),'allPathObjectivesSHA256':sha(canon(goals)),'fiveLocaleScope':'Entire native German task fields plus all four complete stored translation records, unchanged and untruncated','priorCoverageCategory':x['coverageCategory'],'missingReasons':x['missingReasons'],'priorityBucket':priority(x)[0],'priorReviewEvidence':x['reviewRecords']})
 val={'group':'SITOV-NIGHT-2026-10-08','epoch':47,'sourceCommit':source,'inventorySHA256':d['inventorySHA256'],'taskCount':len(rows),'block':len(blocks)+1,'readScopeRequired':['actualWholeFinalTaskAllFiveLocalesIncludingOptionsPartsKeysHintsExplanations','completeActualParentMinusChildrenAllLocalesCardsRulesExamples','allActualPathObjectives'],'approvalFromPriorEvidence':False,'publicationApproved':False,'rows':rows};fp=O/f'epoch47-review-block-{len(blocks)+1:02d}-private.json';fp.write_text(json.dumps(val,ensure_ascii=False,indent=2)+'\n');fp.chmod(0o600);blocks.append({'block':len(blocks)+1,'path':str(fp),'sha256':sha(fp.read_bytes()),'bytes':fp.stat().st_size,'taskCount':len(rows),'ids':[x['id']for x in rows],'priorityBuckets':dict(collections.Counter(x['priorityBucket']for x in rows))})
assert set(allids)=={x['id']for x in missing};manifest={'epoch':47,'sourceCommit':source,'inventorySHA256':d['inventorySHA256'],'fullCandidatesExcluded':sum(x['explicitAcceptCandidate']for x in d['rows']),'S4e48Final18Excluded':sorted(excluded),'missingTaskCount':len(missing),'genuinelyUnreadNotAssumed':True,'priorityMeaning':{'0':'No supported reading scope and no exact whole-task-hash evidence in indexed original docs','1':'No adapted reading scope, but existing exact task-hash discovery; not semantic unread','2':'Source reading documented, current task+parent joint binding missing','3':'Exact current task+parent read exists; complete approval/context missing'},'blocks':blocks,'publicationApproved':False};fp=O/'epoch47-review-blocks-manifest-private.json';fp.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');fp.chmod(0o600);print(json.dumps({'blocks':len(blocks),'tasks':len(missing),'bucketCounts':dict(collections.Counter(priority(x)[0]for x in missing)),'S4e48Excluded':18}))
