import { I, gap, mc, sb } from '../shared.mjs'

const LESERBRIEF = 'Leserbrief von Herrn Aksoy: „In Ihrem Artikel heißt es, junge Leute hätten kein Interesse mehr an festen Beziehungen. Das sehe ich anders. Mein Sohn und seine Freunde sagen, ihnen sei Verlässlichkeit sehr wichtig. Sie wollten nur nicht so früh heiraten wie wir damals. Wer daraus schließt, die Jugend könne nicht lieben, der macht es sich zu einfach.“'
const WER = 'Wer / Wen / Wem'
const DER = 'der / den / dem'

/** B2.2 · Pfad 1 · Beziehungen – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Kompromiss', I.choose, 'Die beiden Brüder haben lange gestritten, aber am Ende einen … gefunden, mit dem beide leben können.', ['Kompromiss', 'Kommentar', 'Komfort'],
      ['The two brothers argued for a long time, but in the end they found a … that both can live with.', 'Два брата долго спорили, но в конце концов нашли …, с которым могут жить оба.', 'Два брати довго сперечалися, але зрештою знайшли …, з яким можуть жити обидва.', 'İki kardeş uzun süre tartıştı ama sonunda ikisinin de kabul edebileceği bir … buldu.']),
    mc('G1', 'die Sehnsucht nach', I.choose, 'Nach drei Monaten im Ausland wurde seine Sehnsucht … der Familie immer größer.', ['nach', 'zu', 'an'],
      ['After three months abroad his longing for his family grew stronger and stronger.', 'После трёх месяцев за границей его тоска по семье становилась всё сильнее.', 'Після трьох місяців за кордоном його туга за сім’єю ставала дедалі сильнішою.', 'Yurt dışında geçen üç aydan sonra ailesine duyduğu özlem giderek büyüdü.'], { h: 'muttersprache' }),
    mc('G2', 'Angst vor + Dativ', I.choose, 'Die Angst vor … hindert viele Menschen daran, offen zu sprechen.', ['einem Streit', 'einen Streit', 'eines Streits'],
      ['The fear of an argument prevents many people from speaking openly.', 'Страх перед ссорой мешает многим людям говорить откровенно.', 'Страх перед сваркою заважає багатьом людям говорити відверто.', 'Kavga korkusu birçok insanın açık konuşmasını engeller.'], { h: 'kasus' }),
    mc('G3', 'er brauche', I.choose, 'Der Autor schreibt, eine Freundschaft … vor allem Zeit und Geduld.', ['brauche', 'brauchte', 'brauchen'],
      ['The author writes that a friendship needs above all time and patience.', 'Автор пишет, что дружбе нужны прежде всего время и терпение.', 'Автор пише, що дружбі потрібні передусім час і терпіння.', 'Yazar, bir arkadaşlığın her şeyden önce zaman ve sabır istediğini yazıyor.'], { h: 'indikativ' }),
    mc('G4', 'sie müssten', I.choose, 'Indirekte Rede: Die Kollegen sagen, sie … heute leider länger im Büro bleiben.', ['müssten', 'müssen', 'müsse'],
      ['Indirect speech: The colleagues say that unfortunately they have to stay longer at the office today.', 'Косвенная речь: коллеги говорят, что сегодня им, к сожалению, придётся задержаться в офисе.', 'Непряма мова: колеги кажуть, що сьогодні їм, на жаль, доведеться затриматися в офісі.', 'Dolaylı anlatım: İş arkadaşları bugün ne yazık ki ofiste daha uzun kalmaları gerektiğini söylüyor.'], { h: 'ersatz' }),
    mc('G5', 'W-Frage in der Vergangenheit', I.sentence, 'Der Trainer fragt den Spieler: „Warum bist du nicht zum Training gekommen?“ → Der Trainer fragt den Spieler, …', ['warum er nicht zum Training gekommen sei.', 'ob er nicht zum Training gekommen sei.', 'warum sei er nicht zum Training gekommen.'],
      ['The coach asks the player: “Why did you not come to training?”', 'Тренер спрашивает игрока: «Почему ты не пришёл на тренировку?»', 'Тренер запитує гравця: «Чому ти не прийшов на тренування?»', 'Antrenör oyuncuya soruyor: “Antrenmana neden gelmedin?”'], { h: 'frage' }),
    mc('G6', 'Komparativ nach je', I.choose, 'Je … man einander zuhört, desto seltener kommt es zu Streit.', ['aufmerksamer', 'aufmerksam', 'am aufmerksamsten'],
      ['The more attentively people listen to each other, the less often arguments arise.', 'Чем внимательнее люди слушают друг друга, тем реже возникают ссоры.', 'Що уважніше люди слухають одне одного, то рідше виникають сварки.', 'İnsanlar birbirini ne kadar dikkatli dinlerse o kadar seyrek kavga çıkar.'], { h: 'komparativ' }),
    mc('G7', 'desto ruhiger bleiben …', I.choose, 'Je mehr Geduld ein Vater hat, …', ['desto ruhiger bleiben die Kinder.', 'desto die Kinder bleiben ruhiger.', 'desto ruhiger die Kinder bleiben.'],
      ['The more patience a father has, the calmer the children stay.', 'Чем больше у отца терпения, тем спокойнее остаются дети.', 'Що більше в батька терпіння, то спокійнішими залишаються діти.', 'Bir babanın sabrı ne kadar çoksa çocuklar o kadar sakin kalır.'], { h: 'desto' }),
    mc('G8', 'wem: einen Gefallen tun', I.choose, '… man einen Gefallen tut, der vergisst das meistens nicht.', ['Wem', 'Wer', 'Wen'],
      ['Anyone you do a favour for usually does not forget it.', 'Кому оказываешь услугу, тот обычно этого не забывает.', 'Кому робиш послугу, той зазвичай цього не забуває.', 'İyilik yaptığınız kişi bunu çoğu zaman unutmaz.'], { h: 'kasus' }),
    mc('G9', 'dem (fehlen)', I.choose, 'Wer neu in der Stadt ist, … fehlen am Anfang oft Freunde.', ['dem', 'der', 'den'],
      ['Anyone who is new in town often lacks friends at first.', 'Кто недавно в городе, тому поначалу часто не хватает друзей.', 'Хто нещодавно в місті, тому спочатку часто бракує друзів.', 'Şehre yeni gelenin başlangıçta çoğu zaman arkadaşı olmaz.'], { h: 'hauptsatz' }),
    mc('Z1', 'Leserbrief: Behauptung', I.read, `${LESERBRIEF} Was behauptet der Artikel laut Herrn Aksoy?`, ['Junge Leute hätten kein Interesse mehr an festen Beziehungen.', 'Junge Leute würden zu früh heiraten.', 'Junge Leute seien besonders verlässlich.'],
      ['According to Mr Aksoy, what does the article claim?', 'Что, по словам господина Aksoy, утверждается в статье?', 'Що, за словами пана Aksoy, стверджується у статті?', 'Bay Aksoy’a göre makale ne öne sürüyor?']),
    gap('G2', 'Interesse an + Dativ', I.article, 'Sein Interesse an ', ' Geschichte seiner Familie ist erst spät erwacht.', 'der', ['die', 'den'],
      ['His interest in the history of his family awoke only late.', 'Его интерес к истории своей семьи проснулся лишь поздно.', 'Його інтерес до історії своєї сім’ї прокинувся лише пізно.', 'Ailesinin geçmişine ilgisi ancak geç uyandı.'], 'die Geschichte', { h: 'kasus' }),
    sb('G5', 'Er sagt, … solle …', I.order, 'Er sagt, / sein Bruder / solle / ihn / morgen / anrufen.',
      ['He says his brother should call him tomorrow.', 'Он говорит, чтобы брат позвонил ему завтра.', 'Він каже, щоб брат зателефонував йому завтра.', 'Kardeşinin onu yarın aramasını söylüyor.'],
      { alt: ['Er sagt, morgen solle sein Bruder ihn anrufen.', 'Er sagt, morgen solle ihn sein Bruder anrufen.'] }),
  ],
  size: 13,
  test: [
    mc('W1', 'Zuneigung', I.choose, 'Was ist „Zuneigung“?', ['ein warmes Gefühl für einen Menschen', 'eine Meinung über einen Menschen', 'ein Streit zwischen zwei Menschen'],
      ['What is “Zuneigung”?', 'Что такое «Zuneigung»?', 'Що таке «Zuneigung»?', '“Zuneigung” nedir?']),
    mc('W1', 'aufeinander angewiesen', I.choose, 'Die beiden Freunde führen gemeinsam eine kleine Firma und sind …: Keiner schafft die Arbeit ohne den anderen.', ['aufeinander angewiesen', 'voneinander getrennt', 'miteinander zerstritten'],
      ['The two friends run a small company together and are …: neither can manage the work without the other.', 'Два друга вместе руководят небольшой фирмой и …: ни один не справится с работой без другого.', 'Два друзі разом керують невеликою фірмою і …: жоден не впорається з роботою без іншого.', 'İki arkadaş birlikte küçük bir şirket yönetiyor ve …: Hiçbiri işi ötekisi olmadan başaramaz.']),
    gap('W1', 'Missverständnis', I.word, 'Das war keine böse Absicht, sondern nur ein ', ': Er hatte meine Nachricht falsch verstanden.', 'Missverständnis', ['Misstrauen', 'Missgeschick'],
      ['It was not ill will, just a misunderstanding: he had understood my message wrongly.', 'Это был не злой умысел, а всего лишь недоразумение: он неправильно понял моё сообщение.', 'Це був не злий намір, а лише непорозуміння: він неправильно зрозумів моє повідомлення.', 'Kötü niyet yoktu, yalnızca bir yanlış anlama oldu: Mesajımı yanlış anlamıştı.'],
      ['misunderstanding', 'недоразумение', 'непорозуміння', 'yanlış anlama']),
    mc('G1', 'die Verantwortung für', I.choose, 'Welche Präposition gehört zu „die Verantwortung“?', ['für', 'an', 'vor'],
      ['Which preposition belongs to “die Verantwortung”?', 'Какой предлог употребляется с «die Verantwortung»?', 'Який прийменник уживається з «die Verantwortung»?', '“die Verantwortung” ile hangi edat kullanılır?']),
    mc('G1', 'die Abhängigkeit von', I.choose, 'Die Abhängigkeit … den Eltern endet für viele erst mit dem ersten eigenen Gehalt.', ['von', 'an', 'auf'],
      ['For many people dependence on their parents only ends with their first salary of their own.', 'Зависимость от родителей у многих заканчивается только с первой собственной зарплатой.', 'Залежність від батьків у багатьох закінчується лише з першою власною зарплатою.', 'Birçok kişi için anne babaya bağımlılık ancak ilk kendi maaşıyla sona erer.'], { h: 'muttersprache' }),
    gap('G1', 'der Zweifel an', I.prep, 'Nach dem Gespräch hatte er keinen Zweifel mehr ', ' der Ehrlichkeit seines Freundes.', 'an', ['über', 'vor'],
      ['After the conversation he no longer had any doubt about his friend’s honesty.', 'После разговора у него больше не было сомнений в честности друга.', 'Після розмови в нього більше не було сумнівів у чесності друга.', 'Konuşmadan sonra arkadaşının dürüstlüğünden artık hiç şüphesi kalmadı.'], 'an / über / vor', { h: 'muttersprache' }),
    mc('G2', 'Rücksicht auf + Akkusativ', I.choose, 'Die Rücksicht auf … ist in einer Wohngemeinschaft selbstverständlich.', ['die anderen Bewohner', 'den anderen Bewohnern', 'der anderen Bewohner'],
      ['Consideration for the other residents is a matter of course in a shared flat.', 'Внимание к остальным жильцам в общей квартире – само собой разумеющееся.', 'Увага до інших мешканців у спільній квартирі – річ самозрозуміла.', 'Paylaşımlı bir evde diğer sakinleri gözetmek doğal bir şeydir.'], { h: 'kasus' }),
    mc('G2', 'Lust auf + Akkusativ', I.choose, 'Er hat wirklich keine Lust auf … mit seinem Bruder.', ['einen Streit', 'einem Streit', 'eines Streits'],
      ['He really does not feel like an argument with his brother.', 'Ему совсем не хочется ссориться с братом.', 'Йому зовсім не хочеться сваритися з братом.', 'Kardeşiyle kavga etmeye gerçekten hiç niyeti yok.'], { h: 'kasus' }),
    gap('G2', 'Abhängigkeit von + Dativ', I.article, 'Die Abhängigkeit von ', ' Meinung anderer macht einen Menschen unfrei.', 'der', ['die', 'den'],
      ['Dependence on the opinion of others makes a person unfree.', 'Зависимость от мнения других делает человека несвободным.', 'Залежність від думки інших робить людину невільною.', 'Başkalarının görüşüne bağımlı olmak insanı özgürlükten yoksun bırakır.'], 'die Meinung', { h: 'kasus' }),
    mc('G3', 'er müsse', I.choose, 'Wie heißt der Konjunktiv I von „er muss“?', ['er müsse', 'er müsste', 'er musste'],
      ['What is the subjunctive I of “er muss”?', 'Как образуется Konjunktiv I от «er muss»?', 'Як утворюється Konjunktiv I від «er muss»?', '“er muss” biçiminin Konjunktiv I’i nedir?']),
    mc('G3', 'er sei', I.choose, 'Der Sprecher der Polizei teilte mit, der Fahrer … unverletzt.', ['sei', 'seien', 'seid'],
      ['The police spokesman announced that the driver was unhurt.', 'Представитель полиции сообщил, что водитель не пострадал.', 'Речник поліції повідомив, що водій не постраждав.', 'Polis sözcüsü sürücünün yaralanmadığını bildirdi.']),
    gap('G3', 'er fühle', I.verb, 'In dem Artikel steht, jeder dritte Erwachsene ', ' sich manchmal einsam.', 'fühle', ['fühlte', 'fühlen'],
      ['The article says that one adult in three sometimes feels lonely.', 'В статье говорится, что каждый третий взрослый иногда чувствует себя одиноким.', 'У статті сказано, що кожен третій дорослий іноді почувається самотнім.', 'Makalede her üç yetişkinden birinin kendini zaman zaman yalnız hissettiği yazıyor.'], 'fühlen (Konjunktiv I)', { h: 'indikativ' }),
    mc('G4', 'sie hätten', I.choose, 'Indirekte Rede: Die Forscher erklären, viele Menschen … heute weniger enge Freunde als früher.', ['hätten', 'haben', 'habe'],
      ['Indirect speech: The researchers explain that many people today have fewer close friends than in the past.', 'Косвенная речь: исследователи объясняют, что у многих людей сегодня меньше близких друзей, чем раньше.', 'Непряма мова: дослідники пояснюють, що в багатьох людей сьогодні менше близьких друзів, ніж раніше.', 'Dolaylı anlatım: Araştırmacılar, birçok insanın bugün eskisinden daha az yakın arkadaşı olduğunu açıklıyor.'], { h: 'ersatz' }),
    gap('G4', 'sie könnten', I.verb, 'Die Gäste sagten, sie ', ' leider nicht länger bleiben.', 'könnten', ['können', 'könne'],
      ['The guests said that unfortunately they could not stay any longer.', 'Гости сказали, что, к сожалению, не могут остаться дольше.', 'Гості сказали, що, на жаль, не можуть залишитися довше.', 'Konuklar ne yazık ki daha fazla kalamayacaklarını söylediler.'], 'können (Ersatzform)', { h: 'ersatz' }),
    mc('G5', 'Reflexivpronomen anpassen', I.sentence, 'Felix: „Ich habe mich über das Geschenk gefreut.“ → Felix sagt, …', ['er habe sich über das Geschenk gefreut.', 'er habe mich über das Geschenk gefreut.', 'ich habe sich über das Geschenk gefreut.'],
      ['Felix: “I was pleased with the present.”', 'Felix: «Я обрадовался подарку».', 'Felix: «Я зрадів подарунку».', 'Felix: “Hediyeye sevindim.”'], { h: 'pronomen' }),
    mc('G5', 'Aufforderung: solle', I.choose, 'Der Lehrer sagt zu dem Schüler: „Lies den Text noch einmal!“ → Der Lehrer sagt, der Schüler … den Text noch einmal lesen.', ['solle', 'wolle', 'habe'],
      ['The teacher says to the pupil: “Read the text again!”', 'Учитель говорит ученику: «Прочитай текст ещё раз!»', 'Учитель каже учневі: «Прочитай текст іще раз!»', 'Öğretmen öğrenciye diyor ki: “Metni bir kez daha oku!”']),
    gap('G5', 'W-Frage: wo', I.qword, 'Der Enkel fragt den Großvater: „Wo hast du früher gewohnt?“ → Der Enkel fragt den Großvater, ', ' er früher gewohnt habe.', 'wo', ['ob', 'dass'],
      ['The grandson asks his grandfather: “Where did you live in the past?” → The grandson asks his grandfather where he lived in the past.', 'Внук спрашивает дедушку: «Где ты жил раньше?» → Внук спрашивает дедушку, где он жил раньше.', 'Онук запитує дідуся: «Де ти жив раніше?» → Онук запитує дідуся, де він жив раніше.', 'Torun dedesine soruyor: “Eskiden nerede oturuyordun?” → Torun dedesine eskiden nerede oturduğunu soruyor.'], 'wo / ob / dass', { h: 'frage' }),
    mc('G6', 'Bedeutung', I.choose, 'Was bedeutet: „Je weniger man erwartet, desto zufriedener ist man.“?', ['Wer wenig erwartet, ist zufriedener.', 'Wer viel erwartet, ist zufriedener.', 'Zufriedene Menschen erwarten immer mehr.'],
      ['What does this mean: “Je weniger man erwartet, desto zufriedener ist man.”?', 'Что означает: «Je weniger man erwartet, desto zufriedener ist man.»?', 'Що означає: «Je weniger man erwartet, desto zufriedener ist man.»?', 'Şu ne demek: “Je weniger man erwartet, desto zufriedener ist man.”?']),
    mc('G6', 'je … umso', I.choose, 'Je mehr Zeit die Geschwister miteinander verbringen, … enger wird ihre Beziehung.', ['umso', 'als', 'wie'],
      ['The more time the brothers and sisters spend together, the closer their relationship becomes.', 'Чем больше времени братья и сёстры проводят вместе, тем ближе становятся их отношения.', 'Що більше часу брати й сестри проводять разом, то ближчими стають їхні стосунки.', 'Kardeşler birlikte ne kadar çok zaman geçirirse ilişkileri o kadar yakınlaşır.']),
    gap('G6', 'wichtiger', I.comparison, 'Je älter man wird, desto ', ' werden einem alte Freundschaften.', 'wichtiger', ['wichtig', 'am wichtigsten'],
      ['The older you get, the more important old friendships become to you.', 'Чем старше становишься, тем важнее для тебя старая дружба.', 'Що старшим стаєш, то важливішою для тебе стає давня дружба.', 'İnsan yaşlandıkça eski arkadaşlıklar onun için daha önemli hâle gelir.'], 'wichtig', { h: 'komparativ' }),
    mc('G7', 'desto genauer müssen wir …', I.choose, 'Je weniger Zeit wir haben, …', ['desto genauer müssen wir planen.', 'desto wir müssen genauer planen.', 'desto genauer wir planen müssen.'],
      ['The less time we have, the more precisely we have to plan.', 'Чем меньше у нас времени, тем точнее нам нужно планировать.', 'Що менше в нас часу, то точніше нам треба планувати.', 'Vaktimiz ne kadar azsa o kadar ayrıntılı plan yapmamız gerekir.'], { h: 'desto' }),
    sb('G7', 'Je älter …, desto seltener …', I.order, 'Je älter / mein Sohn / wird, / desto seltener / ruft / er / an.',
      ['The older my son gets, the less often he calls.', 'Чем старше становится мой сын, тем реже он звонит.', 'Що старшим стає мій син, то рідше він телефонує.', 'Oğlum büyüdükçe daha seyrek arıyor.'],
      { alt: ['Je älter er wird, desto seltener ruft mein Sohn an.'] }),
    mc('G8', 'wem: es fehlt an', I.choose, '… es an Geduld fehlt, der sollte nicht Lehrer werden.', ['Wem', 'Wer', 'Wen'],
      ['Anyone who lacks patience should not become a teacher.', 'Кому не хватает терпения, тому не стоит становиться учителем.', 'Кому бракує терпіння, тому не варто ставати вчителем.', 'Sabrı olmayan öğretmen olmamalıdır.'], { h: 'kasus' }),
    mc('G8', 'wer: sich entschuldigen', I.choose, '… sich nie entschuldigt, macht es den anderen schwer.', ['Wer', 'Wen', 'Wem'],
      ['Anyone who never apologises makes things difficult for the others.', 'Кто никогда не извиняется, тот усложняет жизнь другим.', 'Хто ніколи не перепрошує, той ускладнює життя іншим.', 'Hiç özür dilemeyen başkalarının işini zorlaştırır.']),
    gap('G8', 'Wen', I.pronoun, '', ' das Schicksal hart trifft, der braucht gute Freunde.', 'Wen', ['Wer', 'Wem'],
      ['Anyone who is hit hard by fate needs good friends.', 'Кого судьба бьёт тяжело, тому нужны хорошие друзья.', 'Кого доля б’є тяжко, тому потрібні добрі друзі.', 'Kaderin sert vurduğu kişinin iyi arkadaşlara ihtiyacı vardır.'], WER, { h: 'kasus' }),
    mc('G9', 'dem (danken)', I.choose, 'Wer sich für andere einsetzt, … dankt man oft erst später.', ['dem', 'der', 'den'],
      ['Anyone who stands up for others is often thanked only later.', 'Кто заступается за других, того часто благодарят лишь позже.', 'Хто заступається за інших, тому часто дякують лише згодом.', 'Başkaları için çaba gösterene çoğu zaman ancak sonradan teşekkür edilir.'], { h: 'hauptsatz' }),
    mc('G9', 'Sätze verbinden: den', I.sentence, 'Jemand kommt neu in die Gruppe. Wir heißen ihn herzlich willkommen.', ['Wer neu in die Gruppe kommt, den heißen wir herzlich willkommen.', 'Wen neu in die Gruppe kommt, der heißen wir herzlich willkommen.', 'Wer neu in die Gruppe kommt, dem heißen wir herzlich willkommen.'],
      ['Someone joins the group as a newcomer. We give him a warm welcome.', 'Кто-то приходит в группу новичком. Мы сердечно его приветствуем.', 'Хтось приходить до групи новачком. Ми щиро його вітаємо.', 'Biri gruba yeni katılıyor. Onu içtenlikle karşılıyoruz.'], { h: 'hauptsatz' }),
    gap('G9', 'der (bereuen)', I.pronoun, 'Wem der Beruf wichtiger ist als die Familie, ', ' bereut das vielleicht später.', 'der', ['den', 'dem'],
      ['Anyone to whom his job is more important than his family may regret it later.', 'Кому работа важнее семьи, тот, возможно, позже об этом пожалеет.', 'Кому робота важливіша за сім’ю, той, можливо, згодом про це пошкодує.', 'İşi ailesinden önemli olan kişi belki sonradan buna pişman olur.'], DER, { h: 'hauptsatz' }),
    mc('Z1', 'Leserbrief: Wichtiges', I.read, `${LESERBRIEF} Was ist dem Sohn und seinen Freunden nach eigener Aussage wichtig?`, ['Verlässlichkeit', 'eine frühe Hochzeit', 'viele kurze Beziehungen'],
      ['What do the son and his friends say is important to them?', 'Что, по их собственным словам, важно сыну и его друзьям?', 'Що, за їхніми власними словами, важливо синові та його друзям?', 'Oğul ve arkadaşları kendileri için neyin önemli olduğunu söylüyor?']),
    mc('Z1', 'Leserbrief: Haltung', I.read, `${LESERBRIEF} Wie steht Herr Aksoy zu der Aussage des Artikels?`, ['Er widerspricht ihr.', 'Er stimmt ihr völlig zu.', 'Er hat keine Meinung dazu.'],
      ['What is Mr Aksoy’s attitude to the article’s statement?', 'Как господин Aksoy относится к утверждению статьи?', 'Як пан Aksoy ставиться до твердження статті?', 'Bay Aksoy makaledeki görüşe nasıl yaklaşıyor?']),
  ],
}

export default check
