import { I, gap, mc, sb } from '../shared.mjs'

const BLOG = 'Blogbeitrag von Emil: „Seit einem Monat verzichte ich auf Zucker. Mein Kollege hatte mir erzählt, das wirke Wunder: Man soll besser schlafen und sich wacher fühlen. Ehrlich gesagt merke ich davon wenig. Trotz des Verzichts bin ich nachmittags müde wie immer. Abgenommen habe ich allerdings zwei Kilo. Falls ich bis zum Sommer durchhalte, schreibe ich hier einen zweiten Bericht.“'

/** B2.2 · Pfad 2 · Ernährung – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'ausgewogen', I.choose, 'Wer sich … ernährt, isst von allem etwas: Gemüse, Getreide, Eiweiß und ein wenig Fett.', ['ausgewogen', 'einseitig', 'eilig'],
      ['Anyone who eats a … diet has a bit of everything: vegetables, cereals, protein and a little fat.', 'Кто питается …, ест всего понемногу: овощи, злаки, белок и немного жира.', 'Хто харчується …, їсть усього потроху: овочі, злаки, білок і трохи жиру.', '… beslenen kişi her şeyden biraz yer: sebze, tahıl, protein ve biraz yağ.']),
    mc('G1', 'Bedeutung: Hörensagen', I.choose, 'Was bedeutet: „Der neue Supermarkt soll sehr günstig sein.“?', ['Ich habe gehört, dass er sehr günstig ist.', 'Er muss sehr günstig werden.', 'Ich weiß, dass er sehr günstig ist.'],
      ['What does this mean: “Der neue Supermarkt soll sehr günstig sein.”?', 'Что означает: «Der neue Supermarkt soll sehr günstig sein.»?', 'Що означає: «Der neue Supermarkt soll sehr günstig sein.»?', 'Şu ne demek: “Der neue Supermarkt soll sehr günstig sein.”?']),
    mc('G2', 'soll … behandelt haben', I.choose, 'Es heißt, dass der Bauer seine Tiere schlecht behandelt hat. → Der Bauer soll seine Tiere schlecht …', ['behandelt haben', 'behandeln', 'behandelt sein'],
      ['It is said that the farmer treated his animals badly.', 'Говорят, что фермер плохо обращался со своими животными.', 'Кажуть, що фермер погано поводився зі своїми тваринами.', 'Çiftçinin hayvanlarına kötü davrandığı söyleniyor.'], { h: 'zeit' }),
    mc('G3', 'der Anstieg', I.choose, 'Welches Nomen gehört zu „ansteigen“?', ['der Anstieg', 'die Ansteigung', 'der Ansteig'],
      ['Which noun belongs to “ansteigen”?', 'Какое существительное образовано от «ansteigen»?', 'Який іменник утворено від «ansteigen»?', '“ansteigen” fiilinden hangi isim türetilir?'], { h: 'stamm' }),
    mc('G4', 'Adverb → Adjektiv', I.choose, 'Man lagert die Lebensmittel kühl. → …', ['die kühle Lagerung der Lebensmittel', 'die kühl Lagerung der Lebensmittel', 'die kühle Lagerung die Lebensmittel'],
      ['The food is stored in a cool place.', 'Продукты хранят в прохладном месте.', 'Продукти зберігають у прохолодному місці.', 'Gıdalar serin yerde saklanır.'], { h: 'adjektiv' }),
    mc('G5', 'wegen → weil', I.sentence, 'Wegen der Schließung der Kantine essen die Mitarbeiter im Café.', ['Weil die Kantine geschlossen wurde, essen die Mitarbeiter im Café.', 'Obwohl die Kantine geschlossen wurde, essen die Mitarbeiter im Café.', 'Bevor die Kantine geschlossen wurde, essen die Mitarbeiter im Café.'],
      ['Because of the closure of the canteen the staff eat in the café.', 'Из-за закрытия столовой сотрудники едят в кафе.', 'Через закриття їдальні працівники їдять у кафе.', 'Yemekhane kapandığı için çalışanlar kafede yemek yiyor.'], { h: 'konjunktion' }),
    mc('G6', 'Sollte …', I.choose, '… das Produkt beschädigt sein, erhalten Sie Ihr Geld zurück.', ['Sollte', 'Falls', 'Sofern'],
      ['Should the product be damaged, you will get your money back.', 'Если товар окажется повреждённым, вам вернут деньги.', 'Якщо товар виявиться пошкодженим, вам повернуть гроші.', 'Ürün hasarlı çıkarsa paranızı geri alırsınız.'], { h: 'verb1' }),
    mc('G7', 'trotzdem', I.choose, 'Die Portion war riesig. … hat er alles aufgegessen.', ['Trotzdem', 'Obwohl', 'Trotz'],
      ['The portion was huge. Nevertheless he ate it all up.', 'Порция была огромной. Тем не менее он всё съел.', 'Порція була величезна. Проте він усе з’їв.', 'Porsiyon kocamandı. Yine de hepsini bitirdi.'], { h: 'verwechslung' }),
    mc('G8', 'konzessiv erkennen', I.choose, 'Welche Beziehung besteht? „Auch wenn es schnell gehen muss, koche ich lieber selbst.“', ['Gegengrund ohne Wirkung (konzessiv)', 'Bedingung (konditional)', 'Grund (kausal)'],
      ['What is the relationship? “Auch wenn es schnell gehen muss, koche ich lieber selbst.”', 'Какое здесь отношение? «Auch wenn es schnell gehen muss, koche ich lieber selbst.»', 'Яке тут відношення? «Auch wenn es schnell gehen muss, koche ich lieber selbst.»', 'Buradaki ilişki nedir? “Auch wenn es schnell gehen muss, koche ich lieber selbst.”'], { h: 'logik' }),
    mc('G9', 'obwohl → trotz', I.choose, 'Obwohl er wenig Erfahrung hat, kocht der Lehrling sehr gut. → … kocht der Lehrling sehr gut.', ['Trotz seiner geringen Erfahrung', 'Bei seiner geringen Erfahrung', 'Wegen seiner geringen Erfahrung'],
      ['Although he has little experience, the apprentice cooks very well.', 'Хотя у него мало опыта, ученик готовит очень хорошо.', 'Хоча в нього мало досвіду, учень готує дуже добре.', 'Az deneyimi olduğu hâlde çırak çok iyi yemek yapıyor.'], { h: 'relation' }),
    mc('Z1', 'Blog: Behauptung', I.read, `${BLOG} Was hatte der Kollege über den Verzicht auf Zucker erzählt?`, ['Man soll besser schlafen und sich wacher fühlen.', 'Man soll schnell zwei Kilo abnehmen.', 'Man soll nachmittags müde werden.'],
      ['What had the colleague said about giving up sugar?', 'Что коллега рассказывал об отказе от сахара?', 'Що колега розповідав про відмову від цукру?', 'İş arkadaşı şekerden vazgeçmek hakkında ne anlatmıştı?']),
    gap('G7', 'trotz der …', I.article, 'Trotz ', ' Warnung des Arztes isst er weiterhin jeden Tag Wurst.', 'der', ['die', 'den'],
      ['In spite of the doctor’s warning he still eats sausage every day.', 'Несмотря на предупреждение врача, он по-прежнему каждый день ест колбасу.', 'Попри попередження лікаря, він і далі щодня їсть ковбасу.', 'Doktorun uyarısına rağmen hâlâ her gün sucuk yiyor.'], 'die Warnung'),
    sb('G6', 'Falls …, …', I.order, 'Falls / Sie / Vegetarier / sind, / empfehlen / wir / die Gemüsepfanne.',
      ['If you are a vegetarian, we recommend the vegetable stir-fry.', 'Если вы вегетарианец, мы рекомендуем овощное блюдо на сковороде.', 'Якщо ви вегетаріанець, ми радимо овочеву страву на пательні.', 'Vejetaryenseniz sebze tavasını öneririz.']),
  ],
  size: 13,
  test: [
    mc('W1', 'Verbraucher', I.choose, 'Was ist ein „Verbraucher“?', ['jemand, der Waren kauft und nutzt', 'jemand, der Waren herstellt', 'jemand, der Waren transportiert'],
      ['What is a “Verbraucher”?', 'Кто такой «Verbraucher»?', 'Хто такий «Verbraucher»?', '“Verbraucher” kimdir?']),
    mc('W1', 'haltbar', I.choose, 'Konserven sind lange …: Man kann sie monatelang im Schrank aufbewahren.', ['haltbar', 'dankbar', 'sichtbar'],
      ['Tinned food is … for a long time: you can keep it in the cupboard for months.', 'Консервы долго …: их можно месяцами держать в шкафу.', 'Консерви довго …: їх можна місяцями тримати в шафі.', 'Konserveler uzun süre …: Aylarca dolapta saklanabilir.']),
    gap('W1', 'Fertiggericht', I.word, 'Er hatte keine Zeit zum Kochen und schob einfach ein ', ' in die Mikrowelle.', 'Fertiggericht', ['Fertighaus', 'Fertigkeit'],
      ['He had no time to cook and simply put a ready meal in the microwave.', 'У него не было времени готовить, и он просто поставил в микроволновку готовое блюдо.', 'Він не мав часу готувати і просто поставив у мікрохвильовку готову страву.', 'Yemek yapmaya vakti yoktu, mikrodalgaya bir hazır yemek koyuverdi.'],
      ['ready meal', 'готовое блюдо', 'готова страва', 'hazır yemek']),
    mc('G1', 'Gerücht erkennen', I.choose, 'In welchem Satz gibt „sollen“ ein Gerücht wieder?', ['Der Wirt soll im Lotto gewonnen haben.', 'Der Wirt soll die Rechnung bringen.', 'Was soll ich heute kochen?'],
      ['In which sentence does “sollen” pass on a rumour?', 'В каком предложении «sollen» передаёт слух?', 'У якому реченні «sollen» передає чутку?', 'Hangi cümlede “sollen” bir söylentiyi aktarıyor?'], { h: 'auftrag' }),
    mc('G1', 'Ich habe gehört → soll', I.choose, 'Ich habe gehört, dass diese Bäckerei das beste Brot der Stadt backt. → Diese Bäckerei … das beste Brot der Stadt backen.', ['soll', 'möchte', 'darf'],
      ['I have heard that this bakery bakes the best bread in town.', 'Я слышал, что эта пекарня печёт лучший хлеб в городе.', 'Я чув, що ця пекарня пече найкращий хліб у місті.', 'Bu fırının şehrin en iyi ekmeğini yaptığını duydum.']),
    gap('G1', 'soll', I.modal, 'Viele behaupten es: Kaffee ', ' gar nicht so ungesund sein, wie man früher dachte.', 'soll', ['will', 'darf'],
      ['Many people claim it: coffee is said not to be nearly as unhealthy as people used to think.', 'Многие это утверждают: кофе якобы вовсе не так вреден, как думали раньше.', 'Багато хто це стверджує: кава нібито зовсім не така шкідлива, як думали раніше.', 'Birçok kişi öne sürüyor: Kahve eskiden sanıldığı kadar sağlıksız değilmiş.'], 'sollen'),
    mc('G2', 'Gegenwart erkennen', I.choose, 'Welcher Satz spricht über die Gegenwart?', ['Der Wein soll hervorragend sein.', 'Der Wein soll hervorragend gewesen sein.', 'Der Winzer soll viele Preise gewonnen haben.'],
      ['Which sentence is about the present?', 'В каком предложении говорится о настоящем?', 'У якому реченні йдеться про теперішнє?', 'Hangi cümle şimdiki zamandan söz ediyor?'], { h: 'zeit' }),
    mc('G2', 'soll … gefahren sein', I.choose, 'Laut Zeugen ist der Lieferwagen zu schnell gefahren. → Der Lieferwagen soll zu schnell …', ['gefahren sein', 'gefahren haben', 'fahren'],
      ['According to witnesses the delivery van was going too fast.', 'По словам свидетелей, фургон ехал слишком быстро.', 'За словами свідків, фургон їхав надто швидко.', 'Tanıklara göre teslimat aracı çok hızlı gidiyordu.'], { h: 'zeit' }),
    gap('G2', 'gewesen sein', I.form, 'Der Koch soll in seiner Jugend sehr arm gewesen ', '.', 'sein', ['haben', 'ist'],
      ['The chef is said to have been very poor in his youth.', 'Говорят, в юности повар был очень беден.', 'Кажуть, у юності кухар був дуже бідний.', 'Aşçının gençliğinde çok yoksul olduğu söyleniyor.'], 'sein / haben / ist', { h: 'zeit' }),
    mc('G3', 'die Abnahme', I.choose, 'Welches Nomen gehört zu „abnehmen“?', ['die Abnahme', 'die Abnehmung', 'der Abnahm'],
      ['Which noun belongs to “abnehmen”?', 'Какое существительное образовано от «abnehmen»?', 'Який іменник утворено від «abnehmen»?', '“abnehmen” fiilinden hangi isim türetilir?'], { h: 'stamm' }),
    mc('G3', 'die Süße', I.choose, 'Welches Nomen gehört zu „süß“?', ['die Süße', 'die Süßheit', 'die Süßung'],
      ['Which noun belongs to “süß”?', 'Какое существительное образовано от «süß»?', 'Який іменник утворено від «süß»?', '“süß” sıfatından hangi isim türetilir?']),
    gap('G3', 'der Verzicht', I.word, 'Der völlige ', ' auf Fleisch fällt vielen Menschen schwer.', 'Verzicht', ['Verzehr', 'Verlust'],
      ['Giving up meat completely is hard for many people.', 'Полный отказ от мяса многим людям даётся тяжело.', 'Повна відмова від м’яса багатьом людям дається важко.', 'Etten tümüyle vazgeçmek birçok insana zor gelir.'], 'verzichten', { h: 'stamm' }),
    mc('G4', 'Adverb → Adjektiv', I.choose, 'Man verpackt die Ware sorgfältig. → …', ['die sorgfältige Verpackung der Ware', 'die sorgfältig Verpackung der Ware', 'die sorgfältige Verpackung die Ware'],
      ['The goods are packed carefully.', 'Товар тщательно упаковывают.', 'Товар ретельно пакують.', 'Mal özenle paketlenir.'], { h: 'adjektiv' }),
    mc('G4', 'Subjekt → Genitiv', I.choose, 'Der Fleischkonsum geht zurück. → …', ['der Rückgang des Fleischkonsums', 'der Rückgang den Fleischkonsum', 'der Rückgang dem Fleischkonsum'],
      ['Meat consumption is declining.', 'Потребление мяса снижается.', 'Споживання м’яса знижується.', 'Et tüketimi azalıyor.'], { h: 'genitiv' }),
    gap('G4', 'von + Dativ', I.prep, 'Man liefert Getränke. → die Lieferung ', ' Getränken', 'von', ['der', 'mit'],
      ['Drinks are delivered. → the delivery of drinks', 'Доставляют напитки. → доставка напитков', 'Доставляють напої. → доставка напоїв', 'İçecekler teslim ediliyor. → içecek teslimatı'], 'von / der / mit'),
    mc('G5', 'nach → nachdem', I.sentence, 'Nach dem Ende der Mittagspause räumte der Kellner die Tische ab.', ['Nachdem die Mittagspause zu Ende war, räumte der Kellner die Tische ab.', 'Bevor die Mittagspause zu Ende war, räumte der Kellner die Tische ab.', 'Obwohl die Mittagspause zu Ende war, räumte der Kellner die Tische ab.'],
      ['After the end of the lunch break the waiter cleared the tables.', 'После окончания обеденного перерыва официант убрал со столов.', 'Після закінчення обідньої перерви офіціант прибрав зі столів.', 'Öğle arasının bitiminden sonra garson masaları topladı.'], { h: 'konjunktion' }),
    mc('G5', 'vor = bevor', I.choose, 'Welche Konjunktion entspricht der zeitlichen Präposition „vor“?', ['bevor', 'nachdem', 'seitdem'],
      ['Which conjunction corresponds to the temporal preposition “vor”?', 'Какой союз соответствует временному предлогу «vor»?', 'Який сполучник відповідає часовому прийменникові «vor»?', 'Zaman bildiren “vor” edatına hangi bağlaç karşılık gelir?'], { h: 'konjunktion' }),
    mc('G6', 'wenn = sollte', I.choose, 'Welcher Satz hat dieselbe Bedeutung? „Wenn Sie Hilfe brauchen, drücken Sie die Taste.“', ['Sollten Sie Hilfe brauchen, drücken Sie die Taste.', 'Obwohl Sie Hilfe brauchen, drücken Sie die Taste.', 'Sie brauchen Hilfe, dennoch drücken Sie die Taste.'],
      ['Which sentence has the same meaning? “Wenn Sie Hilfe brauchen, drücken Sie die Taste.”', 'Какое предложение имеет то же значение? «Wenn Sie Hilfe brauchen, drücken Sie die Taste.»', 'Яке речення має те саме значення? «Wenn Sie Hilfe brauchen, drücken Sie die Taste.»', 'Hangi cümle aynı anlamı taşır? “Wenn Sie Hilfe brauchen, drücken Sie die Taste.”'], { h: 'verb1' }),
    mc('G6', 'bei + Dativ', I.choose, 'Bei … wenden Sie sich bitte an unseren Kundendienst.', ['einer Reklamation', 'eine Reklamation', 'eines Reklamation'],
      ['In the event of a complaint please contact our customer service.', 'В случае рекламации обратитесь, пожалуйста, в нашу службу поддержки.', 'У разі рекламації зверніться, будь ласка, до нашої служби підтримки.', 'Şikâyet durumunda lütfen müşteri hizmetlerimize başvurun.'], { h: 'bei' }),
    gap('G6', 'sofern', I.conjunction, 'Die Reservierung bleibt gültig, ', ' Sie bis 19 Uhr erscheinen.', ['sofern', 'wenn', 'falls'], ['obwohl', 'dennoch'],
      ['The reservation remains valid provided you arrive by 7 p.m.', 'Бронь остаётся в силе, если вы придёте до 19 часов.', 'Бронювання залишається чинним, якщо ви прийдете до 19-ї години.', 'Saat 19’a kadar gelirseniz rezervasyon geçerli kalır.'], 'sofern / obwohl / dennoch'),
    mc('G7', 'obwohl', I.choose, '… die Küche winzig ist, arbeiten dort fünf Köche.', ['Obwohl', 'Sofern', 'Trotz'],
      ['Although the kitchen is tiny, five chefs work there.', 'Хотя кухня крошечная, там работают пять поваров.', 'Хоча кухня крихітна, там працюють п’ять кухарів.', 'Mutfak minicik olduğu hâlde orada beş aşçı çalışıyor.'], { h: 'verwechslung' }),
    mc('G7', 'trotz + Genitiv', I.choose, 'Trotz … schmeckt der Kuchen sehr süß.', ['des wenigen Zuckers', 'der wenige Zucker', 'den wenigen Zucker'],
      ['In spite of the small amount of sugar the cake tastes very sweet.', 'Несмотря на малое количество сахара, пирог очень сладкий.', 'Попри малу кількість цукру, пиріг дуже солодкий.', 'Az şekere rağmen kek çok tatlı.']),
    gap('G7', 'Trotzdem / Dennoch', I.adverb, 'Er hatte keinen Hunger. ', ' setzte er sich zu den anderen an den Tisch.', ['Trotzdem', 'Dennoch'], ['Obwohl', 'Falls'],
      ['He was not hungry. Nevertheless he sat down at the table with the others.', 'Он не был голоден. Тем не менее он сел за стол к остальным.', 'Він не був голодний. Проте він сів за стіл до інших.', 'Aç değildi. Yine de ötekilerin yanına, masaya oturdu.'], 'Trotzdem / Obwohl / Falls', { h: 'verwechslung' }),
    mc('G8', 'konditional erkennen', I.choose, 'Welche Beziehung besteht? „Sofern die Ware gekühlt wird, ist sie eine Woche haltbar.“', ['Bedingung (konditional)', 'Gegengrund ohne Wirkung (konzessiv)', 'Grund (kausal)'],
      ['What is the relationship? “Sofern die Ware gekühlt wird, ist sie eine Woche haltbar.”', 'Какое здесь отношение? «Sofern die Ware gekühlt wird, ist sie eine Woche haltbar.»', 'Яке тут відношення? «Sofern die Ware gekühlt wird, ist sie eine Woche haltbar.»', 'Buradaki ilişki nedir? “Sofern die Ware gekühlt wird, ist sie eine Woche haltbar.”'], { h: 'logik' }),
    mc('G8', 'bei (Bedingung)', I.choose, '… großer Hitze verdirbt Fisch besonders schnell.', ['Bei', 'Trotz', 'Obwohl'],
      ['In great heat fish goes off particularly quickly.', 'В сильную жару рыба портится особенно быстро.', 'У сильну спеку риба псується особливо швидко.', 'Aşırı sıcakta balık özellikle çabuk bozulur.'], { h: 'logik' }),
    mc('G9', 'trotz → obwohl', I.choose, 'Trotz des schlechten Wetters grillten wir im Garten. → …, grillten wir im Garten.', ['Obwohl das Wetter schlecht war', 'Falls das Wetter schlecht war', 'Weil das Wetter schlecht war'],
      ['In spite of the bad weather we had a barbecue in the garden.', 'Несмотря на плохую погоду, мы жарили на гриле в саду.', 'Попри погану погоду, ми смажили на грилі в саду.', 'Kötü havaya rağmen bahçede mangal yaptık.'], { h: 'relation' }),
    mc('G9', 'bei richtiger Lagerung', I.choose, 'Wenn die Lagerung richtig ist, bleibt Honig jahrelang gut. → Bei … bleibt Honig jahrelang gut.', ['richtiger Lagerung', 'richtige Lagerung', 'richtigen Lagerung'],
      ['If it is stored correctly, honey stays good for years.', 'При правильном хранении мёд годами остаётся хорошим.', 'За правильного зберігання мед роками залишається добрим.', 'Doğru saklanırsa bal yıllarca bozulmaz.'], { h: 'kasus' }),
    gap('G9', 'trotz der großen Kritik', I.article, 'Obwohl die Kritik groß war, änderte der Hersteller das Rezept nicht. → Trotz ', ' großen Kritik änderte der Hersteller das Rezept nicht.', 'der', ['die', 'des'],
      ['Although there was a lot of criticism, the manufacturer did not change the recipe.', 'Хотя критика была сильной, производитель не изменил рецепт.', 'Хоча критика була сильною, виробник не змінив рецепт.', 'Eleştiri büyük olduğu hâlde üretici tarifi değiştirmedi.'], 'die Kritik', { h: 'kasus' }),
    mc('Z1', 'Blog: tatsächliche Wirkung', I.read, `${BLOG} Welche Wirkung des Verzichts hat Emil tatsächlich bemerkt?`, ['Er hat zwei Kilo abgenommen.', 'Er schläft viel besser.', 'Er ist nachmittags wacher.'],
      ['Which effect of giving up sugar has Emil actually noticed?', 'Какой результат отказа от сахара Emil действительно заметил?', 'Який результат відмови від цукру Emil справді помітив?', 'Emil şekeri bırakmanın hangi etkisini gerçekten fark etti?']),
    mc('Z1', 'Blog: Bedingung', I.read, `${BLOG} Unter welcher Bedingung schreibt Emil einen zweiten Bericht?`, ['falls er bis zum Sommer durchhält', 'falls er wieder Zucker isst', 'falls sein Kollege es verlangt'],
      ['On what condition will Emil write a second report?', 'При каком условии Emil напишет второй отчёт?', 'За якої умови Emil напише другий звіт?', 'Emil hangi koşulla ikinci bir yazı yazacak?']),
  ],
}

export default check
