import { I, gap, mc, sb } from '../shared.mjs'

const FORUM = 'Forumsbeitrag von Daniel: „Ich habe mich zu spät für das Seminar eingeschrieben, sodass ich nur noch einen Platz auf der Warteliste bekam. Der Dozent war so freundlich, dass er mich trotzdem zur ersten Sitzung einlud. Zwei Kommilitonen sind inzwischen abgesprungen; folglich bin ich jetzt regulär dabei. Mein Rat: Stellt eure Fragen früh in der Sprechstunde – das spielt eine größere Rolle, als man denkt.“'
const FOLGE = ['folglich', 'also', 'deshalb', 'daher', 'deswegen', 'infolgedessen', 'somit', 'darum']

/** B2.2 · Pfad 3 · An der Uni – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'sich einschreiben', I.choose, 'Er hat sich für das Wintersemester an der Universität Leipzig …', ['eingeschrieben', 'eingeschlafen', 'eingekauft'],
      ['He has … at the University of Leipzig for the winter semester.', 'Он … в Лейпцигский университет на зимний семестр.', 'Він … до Лейпцизького університету на зимовий семестр.', 'Kış dönemi için Leipzig Üniversitesi’ne …']),
    mc('G1', 'sodass', I.choose, 'Der Beamer funktionierte nicht, … der Student seinen Vortrag ohne Bilder halten musste.', ['sodass', 'weil', 'damit'],
      ['The projector was not working, so the student had to give his talk without pictures.', 'Проектор не работал, так что студенту пришлось делать доклад без изображений.', 'Проєктор не працював, тож студентові довелося робити доповідь без зображень.', 'Projeksiyon cihazı çalışmıyordu, bu yüzden öğrenci sunumunu görselsiz yapmak zorunda kaldı.'], { h: 'folge' }),
    mc('G2', 'dass nach so', I.choose, 'Das Seminar war so beliebt, … die Plätze nach zehn Minuten vergeben waren.', ['dass', 'sodass', 'weil'],
      ['The seminar was so popular that the places were gone after ten minutes.', 'Семинар был настолько популярен, что места разобрали за десять минут.', 'Семінар був настільки популярний, що місця розібрали за десять хвилин.', 'Seminer o kadar rağbet gördü ki yerler on dakikada doldu.'], { h: 'doppelt' }),
    mc('G3', 'folglich', I.choose, 'Er hat die Klausur nicht bestanden. … muss er sie im Herbst wiederholen.', ['Folglich', 'Sodass', 'Weil'],
      ['He did not pass the exam. Consequently he has to resit it in the autumn.', 'Он не сдал экзамен. Следовательно, осенью ему придётся его пересдавать.', 'Він не склав іспит. Отже, восени йому доведеться його перескладати.', 'Sınavı geçemedi. Dolayısıyla sonbaharda tekrar girmek zorunda.'], { h: 'hauptsatz' }),
    mc('G4', 'Ursache erkennen', I.choose, 'Was ist die Ursache? „Da er krank war, konnte er die Hausarbeit nicht rechtzeitig abgeben.“', ['Er war krank.', 'Er konnte die Hausarbeit nicht rechtzeitig abgeben.', 'Er hatte die Frist vergessen.'],
      ['What is the cause? “Da er krank war, konnte er die Hausarbeit nicht rechtzeitig abgeben.”', 'Какова причина? «Da er krank war, konnte er die Hausarbeit nicht rechtzeitig abgeben.»', 'Яка причина? «Da er krank war, konnte er die Hausarbeit nicht rechtzeitig abgeben.»', 'Neden nedir? “Da er krank war, konnte er die Hausarbeit nicht rechtzeitig abgeben.”']),
    mc('G5', 'infolge + Genitiv', I.choose, 'Infolge … wurde die Sprechstunde abgesagt.', ['einer Erkrankung des Dozenten', 'eine Erkrankung des Dozenten', 'einer Erkrankung dem Dozenten'],
      ['As a result of the lecturer’s illness the office hours were cancelled.', 'Вследствие болезни преподавателя приёмные часы отменили.', 'Унаслідок хвороби викладача години прийому скасували.', 'Öğretim görevlisinin hastalığı sonucunda görüşme saati iptal edildi.'], { h: 'genitiv' }),
    mc('G6', 'Fragen stellen', I.choose, 'Im Seminar darf jeder Teilnehmer jederzeit Fragen …', ['stellen', 'setzen', 'legen'],
      ['In the seminar every participant may ask questions at any time.', 'На семинаре каждый участник может в любое время задавать вопросы.', 'На семінарі кожен учасник може будь-коли ставити запитання.', 'Seminerde her katılımcı istediği zaman soru sorabilir.'], { h: 'fest' }),
    mc('G7', 'in Frage kommen', I.choose, 'Ein Wechsel des Studienfachs kommt für ihn nicht in …', ['Frage', 'Antwort', 'Zweifel'],
      ['Changing his subject is out of the question for him.', 'Смена специальности для него исключена.', 'Зміна спеціальності для нього виключена.', 'Bölüm değiştirmek onun için söz konusu değil.']),
    mc('G8', 'beantragen → einen Antrag stellen', I.sentence, 'Er beantragte ein Urlaubssemester.', ['Er stellte einen Antrag auf ein Urlaubssemester.', 'Er machte einen Antrag für ein Urlaubssemester.', 'Er stellte einen Antrag über ein Urlaubssemester.'],
      ['He applied for a semester’s leave of absence.', 'Он подал заявление на академический отпуск на семестр.', 'Він подав заяву на академічну відпустку на семестр.', 'Bir dönemlik izin için başvurdu.'], { h: 'ergaenzung' }),
    mc('G9', 'zur Verfügung stellen → stehen', I.choose, 'Die Stadt stellt den Studenten günstige Wohnungen zur Verfügung. → Den Studenten … günstige Wohnungen zur Verfügung.', ['stehen', 'stellen', 'setzen'],
      ['The city makes low-cost flats available to the students.', 'Город предоставляет студентам недорогие квартиры.', 'Місто надає студентам недорогі квартири.', 'Şehir öğrencilerin kullanımına uygun fiyatlı daireler sunuyor.'], { h: 'wer' }),
    mc('Z1', 'Forum: Warteliste', I.read, `${FORUM} Warum bekam Daniel zuerst nur einen Platz auf der Warteliste?`, ['Er hatte sich zu spät eingeschrieben.', 'Der Dozent wollte ihn nicht im Seminar haben.', 'Zwei Kommilitonen hatten sich beschwert.'],
      ['Why did Daniel at first only get a place on the waiting list?', 'Почему Daniel сначала получил только место в списке ожидания?', 'Чому Daniel спочатку отримав лише місце у списку очікування?', 'Daniel neden önce yalnızca bekleme listesinde yer bulabildi?']),
    gap('G5', 'führte dazu', I.verb, 'Der Ausfall der Heizung ', ' dazu, dass die Klausur in einem anderen Gebäude stattfand.', 'führte', ['folgte', 'fuhr'],
      ['The heating breakdown led to the exam being held in another building.', 'Поломка отопления привела к тому, что экзамен прошёл в другом здании.', 'Поломка опалення призвела до того, що іспит відбувся в іншій будівлі.', 'Isıtmanın arızalanması sınavın başka bir binada yapılmasına yol açtı.'], 'führen (Präteritum)', { h: 'richtung' }),
    sb('G3', '…, also …', I.order, 'Die Mensa / war geschlossen, / also / aßen / wir / in der Stadt.',
      ['The canteen was closed, so we ate in town.', 'Столовая была закрыта, поэтому мы поели в городе.', 'Їдальня була зачинена, тому ми поїли в місті.', 'Yemekhane kapalıydı, bu yüzden şehirde yedik.']),
  ],
  size: 13,
  test: [
    mc('W1', 'Sprechstunde', I.choose, 'Was ist eine „Sprechstunde“ an der Universität?', ['eine feste Zeit, in der der Dozent Fragen beantwortet', 'eine Stunde, in der die Studenten Vorträge halten', 'eine mündliche Prüfung am Semesterende'],
      ['What is a “Sprechstunde” at university?', 'Что такое «Sprechstunde» в университете?', 'Що таке «Sprechstunde» в університеті?', 'Üniversitede “Sprechstunde” nedir?']),
    mc('W1', 'Stipendium', I.choose, 'Er kann sich das Studium nur leisten, weil er ein … bekommt.', ['Stipendium', 'Studium', 'Stadium'],
      ['He can only afford to study because he receives a …', 'Он может позволить себе учёбу только потому, что получает …', 'Він може дозволити собі навчання лише тому, що отримує …', 'Öğrenimini ancak … aldığı için karşılayabiliyor.']),
    gap('W1', 'Klausur', I.word, 'In der ', ' am Ende des Semesters haben die Studenten neunzig Minuten Zeit für alle Aufgaben.', 'Klausur', ['Klasse', 'Klausel'],
      ['In the written exam at the end of the semester the students have ninety minutes for all the tasks.', 'На письменном экзамене в конце семестра у студентов есть девяносто минут на все задания.', 'На письмовому іспиті наприкінці семестру студенти мають дев’яносто хвилин на всі завдання.', 'Dönem sonundaki yazılı sınavda öğrencilerin bütün sorular için doksan dakikası vardır.'],
      ['written exam', 'письменный экзамен', 'письмовий іспит', 'yazılı sınav']),
    mc('G1', 'sodass', I.choose, 'Der Professor verlängerte die Frist, … alle ihre Arbeit in Ruhe beenden konnten.', ['sodass', 'weil', 'obwohl'],
      ['The professor extended the deadline, so everyone was able to finish their work in peace.', 'Профессор продлил срок, так что все смогли спокойно закончить работу.', 'Професор продовжив термін, тож усі змогли спокійно закінчити роботу.', 'Profesör süreyi uzattı, böylece herkes çalışmasını rahatça bitirebildi.'], { h: 'folge' }),
    mc('G1', 'Wortstellung', I.sentence, 'Welcher Satz ist richtig?', ['Es gab zu wenige Bücher, sodass wir uns eines teilen mussten.', 'Es gab zu wenige Bücher, sodass mussten wir uns eines teilen.', 'Sodass wir uns eines teilen mussten, gab es zu wenige Bücher.'],
      ['Which sentence is correct?', 'Какое предложение правильное?', 'Яке речення правильне?', 'Hangi cümle doğru?'], { h: 'nebensatz' }),
    gap('G1', 'Verb am Ende', I.modal, 'Der Aufzug war defekt, sodass wir die Bücher in den vierten Stock tragen ', '.', 'mussten', ['müssen', 'gemusst'],
      ['The lift was out of order, so we had to carry the books up to the fourth floor.', 'Лифт был сломан, так что нам пришлось нести книги на пятый этаж.', 'Ліфт був зламаний, тож нам довелося нести книжки на п’ятий поверх.', 'Asansör bozuktu, bu yüzden kitapları dördüncü kata taşımak zorunda kaldık.'], 'müssen (Präteritum)', { h: 'nebensatz' }),
    mc('G2', 'so + Adjektiv', I.choose, 'Die Aufgabe war … kompliziert, dass selbst der Tutor lange überlegen musste.', ['so', 'sehr', 'zu'],
      ['The task was so complicated that even the tutor had to think for a long time.', 'Задание было настолько сложным, что даже тьютору пришлось долго думать.', 'Завдання було настільки складним, що навіть тьюторові довелося довго думати.', 'Görev o kadar karmaşıktı ki eğitmen bile uzun süre düşünmek zorunda kaldı.']),
    gap('G2', 'so große Angst', I.ending, 'Er hatte so ', ' Angst vor der mündlichen Prüfung, dass er die ganze Nacht nicht schlafen konnte.', ['große', 'viel'], ['groß', 'sehr'],
      ['He was so afraid of the oral exam that he could not sleep all night.', 'Он так боялся устного экзамена, что не мог уснуть всю ночь.', 'Він так боявся усного іспиту, що не міг заснути всю ніч.', 'Sözlü sınavdan o kadar korkuyordu ki bütün gece uyuyamadı.'], 'groß', { h: 'menge' }),
    mc('G3', 'infolgedessen', I.choose, 'Die Universität hat weniger Geld bekommen. … wurden mehrere Stellen gestrichen.', ['Infolgedessen', 'Sodass', 'Weil'],
      ['The university received less money. As a result several posts were cut.', 'Университет получил меньше денег. Вследствие этого несколько ставок сократили.', 'Університет отримав менше грошей. Унаслідок цього кілька ставок скоротили.', 'Üniversite daha az para aldı. Bunun sonucunda birkaç kadro kaldırıldı.'], { h: 'hauptsatz' }),
    mc('G3', 'Wortstellung nach folglich', I.sentence, 'Welcher Satz ist richtig?', ['Der Raum ist belegt, folglich müssen wir ausweichen.', 'Der Raum ist belegt, folglich wir ausweichen müssen.', 'Der Raum ist belegt, folglich wir müssen ausweichen.'],
      ['Which sentence is correct?', 'Какое предложение правильное?', 'Яке речення правильне?', 'Hangi cümle doğru?'], { h: 'hauptsatz' }),
    gap('G3', 'folglich', I.adverb, 'Sein Antrag kam einen Tag zu spät an. Er bekam ', ' kein Stipendium.', FOLGE, ['sodass', 'weil'],
      ['His application arrived a day too late. He consequently did not get a scholarship.', 'Его заявление пришло на день позже. Следовательно, стипендию он не получил.', 'Його заява надійшла на день пізніше. Отже, стипендії він не отримав.', 'Başvurusu bir gün geç ulaştı. Dolayısıyla burs alamadı.'], 'folglich / sodass / weil', { h: 'hauptsatz' }),
    mc('G4', 'weil + Ursache', I.choose, 'Er lernt seit Wochen jeden Abend, … er die Prüfung unbedingt bestehen will.', ['weil', 'sodass', 'folglich'],
      ['He has been studying every evening for weeks because he is determined to pass the exam.', 'Он уже несколько недель занимается каждый вечер, потому что непременно хочет сдать экзамен.', 'Він уже кілька тижнів займається щовечора, бо неодмінно хоче скласти іспит.', 'Sınavı mutlaka geçmek istediği için haftalardır her akşam çalışıyor.'], { h: 'vertauscht' }),
    mc('G4', 'Richtung prüfen', I.sentence, 'Ursache: Das Internet fiel aus. Folge: Die Online-Vorlesung wurde abgebrochen.', ['Das Internet fiel aus, sodass die Online-Vorlesung abgebrochen wurde.', 'Die Online-Vorlesung wurde abgebrochen, sodass das Internet ausfiel.', 'Das Internet fiel aus, weil die Online-Vorlesung abgebrochen wurde.'],
      ['Cause: the internet went down. Result: the online lecture was broken off.', 'Причина: пропал интернет. Следствие: онлайн-лекцию прервали.', 'Причина: зник інтернет. Наслідок: онлайн-лекцію перервали.', 'Neden: İnternet kesildi. Sonuç: Çevrim içi ders yarıda kesildi.'], { h: 'vertauscht' }),
    gap('G4', 'sodass', I.conjunction, 'Er hatte den falschen Raum notiert, ', ' er eine halbe Stunde zu spät zur Prüfung kam.', ['sodass', 'so dass'], ['weil', 'da'],
      ['He had noted down the wrong room, so he arrived half an hour late for the exam.', 'Он записал не ту аудиторию, так что опоздал на экзамен на полчаса.', 'Він записав не ту аудиторію, тож запізнився на іспит на пів години.', 'Yanlış odayı not etmişti, bu yüzden sınava yarım saat geç geldi.'], 'sodass / weil / da', { h: 'vertauscht' }),
    mc('G5', 'führen zu', I.choose, 'Die Einführung von Studiengebühren führte … einem Rückgang der Bewerbungen.', ['zu', 'auf', 'in'],
      ['The introduction of tuition fees led to a fall in applications.', 'Введение платы за обучение привело к сокращению числа заявлений.', 'Запровадження плати за навчання призвело до зменшення кількості заяв.', 'Öğrenim harcının getirilmesi başvuruların azalmasına yol açtı.']),
    mc('G5', 'weil → infolge', I.sentence, 'Weil das Dach beschädigt war, wurde die Sporthalle geschlossen.', ['Infolge der Beschädigung des Daches wurde die Sporthalle geschlossen.', 'Trotz der Beschädigung des Daches wurde die Sporthalle geschlossen.', 'Infolge die Beschädigung des Daches wurde die Sporthalle geschlossen.'],
      ['Because the roof was damaged, the sports hall was closed.', 'Поскольку крыша была повреждена, спортзал закрыли.', 'Оскільки дах був пошкоджений, спортзал зачинили.', 'Çatı hasar gördüğü için spor salonu kapatıldı.'], { h: 'genitiv' }),
    gap('G5', 'infolge von', I.word, 'Infolge ', ' Bauarbeiten ist der Haupteingang der Universität geschlossen.', ['von', 'der'], ['zu', 'den'],
      ['As a result of building work the main entrance of the university is closed.', 'Вследствие строительных работ главный вход университета закрыт.', 'Унаслідок будівельних робіт головний вхід університету зачинений.', 'İnşaat çalışmaları nedeniyle üniversitenin ana girişi kapalı.'], 'von / zu / den', { h: 'genitiv' }),
    mc('G6', 'einen Fehler machen', I.choose, 'Im letzten Semester hat er einen großen Fehler …: Er hat sich für zu viele Kurse angemeldet.', ['gemacht', 'getroffen', 'gestellt'],
      ['Last semester he made a big mistake: he signed up for too many courses.', 'В прошлом семестре он сделал большую ошибку: записался на слишком много курсов.', 'Минулого семестру він зробив велику помилку: записався на надто багато курсів.', 'Geçen dönem büyük bir hata yaptı: Çok fazla derse kaydoldu.']),
    mc('G6', 'Rücksicht nehmen', I.choose, 'Welches Verb gehört zu „Rücksicht“?', ['nehmen', 'machen', 'stellen'],
      ['Which verb belongs to “Rücksicht”?', 'Какой глагол сочетается с «Rücksicht»?', 'Яке дієслово сполучається з «Rücksicht»?', '“Rücksicht” ile hangi fiil kullanılır?']),
    gap('G6', 'einen Vortrag halten', I.verb, 'Der Gastprofessor ', ' gestern einen Vortrag über künstliche Intelligenz.', 'hielt', ['stellte', 'traf'],
      ['The visiting professor gave a talk on artificial intelligence yesterday.', 'Приглашённый профессор вчера сделал доклад об искусственном интеллекте.', 'Запрошений професор учора зробив доповідь про штучний інтелект.', 'Konuk profesör dün yapay zekâ üzerine bir sunum yaptı.'], 'halten (Präteritum)', { h: 'fest' }),
    mc('G7', 'in Kraft treten', I.choose, 'Die neue Regelung tritt im Januar in …', ['Kraft', 'Macht', 'Stärke'],
      ['The new rule comes into force in January.', 'Новое правило вступает в силу в январе.', 'Нове правило набирає чинності в січні.', 'Yeni düzenleme ocakta yürürlüğe giriyor.']),
    mc('G7', 'Bedeutung: nicht in Frage kommen', I.choose, 'Was bedeutet „Das kommt nicht in Frage.“?', ['Das ist ausgeschlossen.', 'Das ist eine gute Frage.', 'Das wird bald beantwortet.'],
      ['What does “Das kommt nicht in Frage.” mean?', 'Что означает «Das kommt nicht in Frage.»?', 'Що означає «Das kommt nicht in Frage.»?', '“Das kommt nicht in Frage.” ne demek?']),
    gap('G7', 'unter Druck stehen', I.prep, 'Kurz vor der Abgabe stand er so ', ' Druck, dass er kaum noch schlief.', 'unter', ['im', 'über'],
      ['Shortly before the deadline he was under so much pressure that he hardly slept.', 'Незадолго до сдачи он был под таким давлением, что почти не спал.', 'Незадовго до здачі він був під таким тиском, що майже не спав.', 'Teslimden hemen önce o kadar baskı altındaydı ki neredeyse hiç uyumadı.'], 'unter / im / über', { h: 'praeposition' }),
    mc('G8', 'nutzen → in Anspruch nehmen', I.sentence, 'Die Studenten nutzen das Angebot der Bibliothek.', ['Die Studenten nehmen das Angebot der Bibliothek in Anspruch.', 'Die Studenten nehmen das Angebot der Bibliothek zum Anspruch.', 'Die Studenten bringen das Angebot der Bibliothek in Anspruch.'],
      ['The students use what the library offers.', 'Студенты пользуются услугами библиотеки.', 'Студенти користуються послугами бібліотеки.', 'Öğrenciler kütüphanenin sunduğu olanakları kullanıyor.']),
    gap('G8', 'entscheiden → eine Entscheidung treffen', I.verb, 'Der Ausschuss entscheidet morgen. → Der Ausschuss ', ' morgen eine Entscheidung.', 'trifft', ['macht', 'nimmt'],
      ['The committee decides tomorrow.', 'Комиссия принимает решение завтра.', 'Комісія ухвалює рішення завтра.', 'Kurul yarın karar veriyor.'], 'treffen'),
    mc('G9', 'zur Verfügung stellen', I.choose, 'Die Hochschule … jedem Erstsemester einen Mentor zur Verfügung.', ['stellt', 'steht', 'kommt'],
      ['The university provides every first-semester student with a mentor.', 'Вуз предоставляет каждому первокурснику наставника.', 'Виш надає кожному першокурсникові наставника.', 'Yüksekokul her birinci sınıf öğrencisine bir danışman sağlıyor.'], { h: 'wer' }),
    mc('G9', 'zur Diskussion stehen', I.choose, 'Was bedeutet „Der Vorschlag steht zur Diskussion.“?', ['Über den Vorschlag wird diskutiert.', 'Der Vorschlag diskutiert etwas.', 'Der Vorschlag wurde abgelehnt.'],
      ['What does “Der Vorschlag steht zur Diskussion.” mean?', 'Что означает «Der Vorschlag steht zur Diskussion.»?', 'Що означає «Der Vorschlag steht zur Diskussion.»?', '“Der Vorschlag steht zur Diskussion.” ne demek?']),
    gap('G9', 'in Gang kommen', I.verb, 'Die Verhandlungen ', ' nach langem Stillstand endlich wieder in Gang.', 'kamen', ['setzten', 'brachten'],
      ['After a long standstill the negotiations finally got going again.', 'После долгого застоя переговоры наконец снова сдвинулись с места.', 'Після довгого застою переговори нарешті знову зрушили з місця.', 'Uzun bir duraklamadan sonra görüşmeler nihayet yeniden başladı.'], 'kommen (Präteritum)', { h: 'wer' }),
    mc('Z1', 'Forum: Folge', I.read, `${FORUM} Warum ist Daniel jetzt regulär im Seminar?`, ['Zwei Kommilitonen sind abgesprungen.', 'Er hat sich beim Dozenten beschwert.', 'Das Seminar wurde vergrößert.'],
      ['Why is Daniel now a regular member of the seminar?', 'Почему Daniel теперь полноправный участник семинара?', 'Чому Daniel тепер повноправний учасник семінару?', 'Daniel neden artık seminerin asıl katılımcısı?']),
    mc('Z1', 'Forum: Rat', I.read, `${FORUM} Was rät Daniel den anderen Studenten?`, ['früh Fragen in der Sprechstunde zu stellen', 'sich möglichst spät einzuschreiben', 'auf die Warteliste zu verzichten'],
      ['What does Daniel advise the other students to do?', 'Что Daniel советует другим студентам?', 'Що Daniel радить іншим студентам?', 'Daniel diğer öğrencilere ne öneriyor?']),
  ],
}

export default check
