import { I, gap, mc, sb } from '../shared.mjs'

const AUSHANG = 'Aushang im Waschsalon: „Die Maschinen sind nur mit Münzen zu bedienen. Geld lässt sich am Automaten neben der Tür wechseln. Nach 22 Uhr wird nicht mehr gewaschen. Die Wäsche ist sofort nach Programmende aus der Maschine zu nehmen. Bei Störungen wird Ihnen unter der Nummer auf dem Schild geholfen. Für vergessene Kleidung wird nicht gehaftet.“'

/** B2.2 · Pfad 4 · Service – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'umtauschen', I.choose, 'Der Kunde möchte den defekten Toaster nicht reparieren lassen, sondern gegen ein neues Gerät …', ['umtauschen', 'umbauen', 'umdrehen'],
      ['The customer does not want to have the faulty toaster repaired but to … it for a new one.', 'Покупатель не хочет чинить неисправный тостер, а хочет … его на новый.', 'Покупець не хоче лагодити несправний тостер, а хоче … його на новий.', 'Müşteri arızalı tost makinesini onartmak değil, yenisiyle … istiyor.']),
    mc('G1', 'lässt sich', I.choose, 'Der Vertrag … sich jederzeit kündigen.', ['lässt', 'lasst', 'lassen'],
      ['The contract can be terminated at any time.', 'Договор можно расторгнуть в любое время.', 'Договір можна розірвати будь-коли.', 'Sözleşme istenildiği zaman feshedilebilir.'], { h: 'kongruenz' }),
    mc('G2', 'Bedeutung: muss', I.choose, 'Was bedeutet: „Die Gebrauchsanweisung ist genau zu lesen.“?', ['Die Gebrauchsanweisung muss genau gelesen werden.', 'Die Gebrauchsanweisung wurde genau gelesen.', 'Die Gebrauchsanweisung darf gelesen werden.'],
      ['What does this mean: “Die Gebrauchsanweisung ist genau zu lesen.”?', 'Что означает: «Die Gebrauchsanweisung ist genau zu lesen.»?', 'Що означає: «Die Gebrauchsanweisung ist genau zu lesen.»?', 'Şu ne demek: “Die Gebrauchsanweisung ist genau zu lesen.”?']),
    mc('G3', 'trinkbar', I.choose, 'Das Wasser aus diesem Brunnen ist nicht …', ['trinkbar', 'trinkend', 'getrunken'],
      ['The water from this well is not drinkable.', 'Вода из этого колодца непригодна для питья.', 'Вода з цієї криниці непридатна для пиття.', 'Bu çeşmenin suyu içilmez.'], { h: 'bildung' }),
    mc('G4', 'Möglichkeit erkennen', I.choose, 'Welche Bedeutung hat der Satz? „Der Fehler war nicht zu übersehen.“', ['Möglichkeit: Er konnte nicht übersehen werden.', 'Notwendigkeit: Er musste übersehen werden.', 'Erlaubnis: Er durfte übersehen werden.'],
      ['What does the sentence mean? “Der Fehler war nicht zu übersehen.”', 'Какое значение имеет предложение? «Der Fehler war nicht zu übersehen.»', 'Яке значення має речення? «Der Fehler war nicht zu übersehen.»', 'Cümlenin anlamı nedir? “Der Fehler war nicht zu übersehen.”'], { h: 'kontext' }),
    mc('G5', 'Passiv → sich lassen', I.sentence, 'Die Daten können nicht wiederhergestellt werden.', ['Die Daten lassen sich nicht wiederherstellen.', 'Die Daten lässt sich nicht wiederherstellen.', 'Die Daten sind nicht wiederherstellen.'],
      ['The data cannot be restored.', 'Данные невозможно восстановить.', 'Дані неможливо відновити.', 'Veriler geri yüklenemiyor.'], { h: 'form' }),
    mc('G6', 'wird gearbeitet', I.choose, 'In der Fabrik … in drei Schichten gearbeitet.', ['wird', 'werden', 'sind'],
      ['In the factory work is done in three shifts.', 'На фабрике работают в три смены.', 'На фабриці працюють у три зміни.', 'Fabrikada üç vardiya hâlinde çalışılıyor.'], { h: 'singular' }),
    mc('G7', 'kein es nach Position 1', I.sentence, 'Welcher Satz ist richtig?', ['Im Wartezimmer wird leise gesprochen.', 'Im Wartezimmer wird es leise gesprochen.', 'Im Wartezimmer es wird leise gesprochen.'],
      ['Which sentence is correct?', 'Какое предложение правильное?', 'Яке речення правильне?', 'Hangi cümle doğru?'], { h: 'platzhalter' }),
    mc('G8', 'Uns wurde versprochen', I.choose, '… wurde am Telefon versprochen, dass der Monteur morgen kommt.', ['Uns', 'Wir', 'Unser'],
      ['We were promised on the phone that the fitter would come tomorrow.', 'Нам пообещали по телефону, что монтёр придёт завтра.', 'Нам пообіцяли телефоном, що монтер прийде завтра.', 'Bize telefonda montajcının yarın geleceği söz verildi.'], { h: 'dativ' }),
    mc('G9', 'Perfekt: worden', I.sentence, 'Man hat die Rechnung zweimal geschickt.', ['Die Rechnung ist zweimal geschickt worden.', 'Die Rechnung ist zweimal geschickt geworden.', 'Die Rechnung hat zweimal geschickt worden.'],
      ['The bill was sent twice.', 'Счёт отправили дважды.', 'Рахунок надіслали двічі.', 'Fatura iki kez gönderildi.'], { h: 'zeit' }),
    mc('Z1', 'Aushang: Bezahlung', I.read, `${AUSHANG} Womit müssen die Maschinen bedient werden?`, ['mit Münzen', 'mit Geldscheinen', 'mit einer Karte'],
      ['What do the machines have to be operated with?', 'Чем нужно оплачивать работу машин?', 'Чим треба оплачувати роботу машин?', 'Makineler neyle çalıştırılmak zorunda?']),
    gap('G2', 'zurückzugeben', I.form, 'Der Mietwagen ist mit vollem Tank ', '.', 'zurückzugeben', ['zu zurückgeben', 'zurückgegeben'],
      ['The hire car must be returned with a full tank.', 'Арендованный автомобиль нужно вернуть с полным баком.', 'Орендований автомобіль треба повернути з повним баком.', 'Kiralık araba deposu dolu olarak geri verilmelidir.'], 'zurückgeben', { h: 'trennbar' }),
    sb('G8', 'Dem Kunden wurde geholfen', I.order, 'Dem Kunden / wurde / am Telefon / schnell / geholfen.',
      ['The customer was helped quickly on the phone.', 'Клиенту быстро помогли по телефону.', 'Клієнтові швидко допомогли телефоном.', 'Müşteriye telefonda hızlıca yardım edildi.'],
      { alt: ['Dem Kunden wurde schnell am Telefon geholfen.'] }),
  ],
  size: 13,
  test: [
    mc('W1', 'Reklamation', I.choose, 'Was ist eine „Reklamation“?', ['eine Beschwerde über eine fehlerhafte Ware oder Leistung', 'eine Werbung für ein neues Produkt', 'eine Bestellung im Internet'],
      ['What is a “Reklamation”?', 'Что такое «Reklamation»?', 'Що таке «Reklamation»?', '“Reklamation” nedir?']),
    mc('W1', 'Rückerstattung', I.choose, 'Der Kunde hat zu viel bezahlt und bekommt nun eine … von 30 Euro.', ['Rückerstattung', 'Rückmeldung', 'Rückkehr'],
      ['The customer paid too much and is now getting a … of 30 euros.', 'Клиент заплатил слишком много и теперь получает … в размере 30 евро.', 'Клієнт заплатив забагато і тепер отримує … у розмірі 30 євро.', 'Müşteri fazla ödeme yaptı ve şimdi 30 avroluk bir … alıyor.']),
    gap('W1', 'Wartung', I.word, 'Die Heizung funktioniert seit Jahren ohne Probleme, weil die jährliche ', ' nie ausfällt.', 'Wartung', ['Warnung', 'Wanderung'],
      ['The heating has worked without problems for years because the annual maintenance is never skipped.', 'Отопление годами работает без проблем, потому что ежегодное техническое обслуживание никогда не пропускают.', 'Опалення роками працює без проблем, бо щорічне технічне обслуговування ніколи не пропускають.', 'Yıllık bakım hiç aksatılmadığı için kalorifer yıllardır sorunsuz çalışıyor.'],
      ['maintenance', 'техническое обслуживание', 'технічне обслуговування', 'bakım']),
    mc('G1', 'Bedeutung', I.choose, 'Was bedeutet: „Die Lieferung lässt sich online verfolgen.“?', ['Die Lieferung kann online verfolgt werden.', 'Die Lieferung muss online verfolgt werden.', 'Die Lieferung wird nicht verfolgt.'],
      ['What does this mean: “Die Lieferung lässt sich online verfolgen.”?', 'Что означает: «Die Lieferung lässt sich online verfolgen.»?', 'Що означає: «Die Lieferung lässt sich online verfolgen.»?', 'Şu ne demek: “Die Lieferung lässt sich online verfolgen.”?']),
    mc('G1', 'lassen sich', I.choose, 'Manche Probleme … sich am Telefon nicht klären.', ['lassen', 'lässt', 'lasst'],
      ['Some problems cannot be sorted out on the phone.', 'Некоторые проблемы невозможно решить по телефону.', 'Деякі проблеми неможливо розв’язати телефоном.', 'Bazı sorunlar telefonda çözülemez.'], { h: 'kongruenz' }),
    gap('G1', 'lässt', I.verb, 'Der Fleck auf dem Teppich ', ' sich mit etwas Seife leicht entfernen.', 'lässt', ['lasst', 'lassen'],
      ['The stain on the carpet can easily be removed with a little soap.', 'Пятно на ковре легко удалить небольшим количеством мыла.', 'Пляму на килимі легко прибрати невеликою кількістю мила.', 'Halıdaki leke biraz sabunla kolayca çıkarılabilir.'], 'lassen', { h: 'kongruenz' }),
    mc('G2', 'zu + Infinitiv', I.choose, 'Die Miete ist bis zum dritten Werktag des Monats zu …', ['überweisen', 'überwiesen', 'überweist'],
      ['The rent must be transferred by the third working day of the month.', 'Арендную плату нужно перевести до третьего рабочего дня месяца.', 'Орендну плату треба переказати до третього робочого дня місяця.', 'Kira, ayın üçüncü iş gününe kadar havale edilmelidir.']),
    mc('G2', 'Passiv → sein + zu', I.sentence, 'Der Antrag muss persönlich abgegeben werden.', ['Der Antrag ist persönlich abzugeben.', 'Der Antrag ist persönlich zu abgeben.', 'Der Antrag hat persönlich abzugeben.'],
      ['The application must be handed in in person.', 'Заявление нужно подать лично.', 'Заяву треба подати особисто.', 'Başvuru şahsen teslim edilmelidir.'], { h: 'trennbar' }),
    gap('G2', 'sind zu beachten', I.verb, 'Die Hinweise des Herstellers ', ' genau zu beachten.', 'sind', ['ist', 'haben'],
      ['The manufacturer’s instructions must be followed exactly.', 'Указания производителя нужно точно соблюдать.', 'Вказівки виробника треба точно дотримувати.', 'Üreticinin uyarılarına tam olarak uyulmalıdır.'], 'sein', { h: 'sein' }),
    mc('G3', 'absehbar', I.choose, 'Was bedeutet „Die Kosten sind absehbar.“?', ['Die Kosten können abgeschätzt werden.', 'Die Kosten müssen bezahlt werden.', 'Die Kosten wurden übersehen.'],
      ['What does “Die Kosten sind absehbar.” mean?', 'Что означает «Die Kosten sind absehbar.»?', 'Що означає «Die Kosten sind absehbar.»?', '“Die Kosten sind absehbar.” ne demek?']),
    mc('G3', 'unvermeidlich', I.choose, 'Welches Adjektiv bedeutet „kann nicht vermieden werden“?', ['unvermeidlich', 'vermeidend', 'unvermieden'],
      ['Which adjective means “kann nicht vermieden werden”?', 'Какое прилагательное означает «kann nicht vermieden werden»?', 'Який прикметник означає «kann nicht vermieden werden»?', 'Hangi sıfat “kann nicht vermieden werden” anlamına gelir?']),
    gap('G3', 'lesbar', I.word, 'Ohne Brille ist die kleine Schrift auf der Verpackung für ihn nicht ', '.', 'lesbar', ['gelesen', 'lesend'],
      ['Without glasses the small print on the packaging is not legible for him.', 'Без очков он не может разобрать мелкий шрифт на упаковке.', 'Без окулярів він не може розібрати дрібний шрифт на упаковці.', 'Gözlüksüz ambalajdaki küçük yazıyı okuyamıyor.'], 'lesen', { h: 'bildung' }),
    mc('G4', 'nur: kann', I.choose, '„Die Tür ist nur mit einem Schlüssel zu öffnen.“ bedeutet: Die Tür … nur mit einem Schlüssel geöffnet werden.', ['kann', 'soll', 'darf nicht'],
      ['“Die Tür ist nur mit einem Schlüssel zu öffnen.” means: the door … only be opened with a key.', '«Die Tür ist nur mit einem Schlüssel zu öffnen.» означает: дверь … открыть только ключом.', '«Die Tür ist nur mit einem Schlüssel zu öffnen.» означає: двері … відчинити лише ключем.', '“Die Tür ist nur mit einem Schlüssel zu öffnen.” şu demektir: Kapı yalnızca anahtarla açıl…'], { h: 'kontext' }),
    mc('G4', 'Pflicht erkennen', I.choose, 'Welcher Satz drückt eine Pflicht aus?', ['Die Sicherheitsschuhe sind in der Halle zu tragen.', 'Die Sicherheitsschuhe lassen sich bequem tragen.', 'Die Sicherheitsschuhe sind gut tragbar.'],
      ['Which sentence expresses an obligation?', 'Какое предложение выражает обязанность?', 'Яке речення виражає обов’язок?', 'Hangi cümle bir zorunluluk bildiriyor?'], { h: 'kontext' }),
    mc('G5', 'sich lassen → Passiv', I.sentence, 'Die Rechnung lässt sich auch per Überweisung bezahlen.', ['Die Rechnung kann auch per Überweisung bezahlt werden.', 'Die Rechnung muss auch per Überweisung bezahlt werden.', 'Die Rechnung kann auch per Überweisung bezahlen werden.'],
      ['The bill can also be paid by bank transfer.', 'Счёт можно оплатить и банковским переводом.', 'Рахунок можна оплатити й банківським переказом.', 'Fatura havaleyle de ödenebilir.'], { h: 'bedeutung' }),
    mc('G5', 'Passiv → -bar', I.sentence, 'Das Wasser kann getrunken werden.', ['Das Wasser ist trinkbar.', 'Das Wasser ist zu trinkbar.', 'Das Wasser lässt trinken.'],
      ['The water can be drunk.', 'Эту воду можно пить.', 'Цю воду можна пити.', 'Su içilebilir.']),
    gap('G5', 'ist zu bestellen', I.form, 'Das Ersatzteil muss bestellt werden. → Das Ersatzteil ist zu ', '.', 'bestellen', ['bestellt', 'bestelle'],
      ['The spare part has to be ordered.', 'Запчасть нужно заказать.', 'Запчастину треба замовити.', 'Yedek parça sipariş edilmelidir.'], 'bestellen / bestellt / bestelle', { h: 'form' }),
    mc('G6', 'wurde gelacht', I.choose, 'Bei dem Betriebsfest wurde viel …', ['gelacht', 'lachen', 'lachte'],
      ['There was a lot of laughter at the company party.', 'На корпоративном празднике много смеялись.', 'На корпоративному святі багато сміялися.', 'Şirket şenliğinde çok gülündü.']),
    mc('G6', 'Passiv ohne Subjekt erkennen', I.choose, 'Welcher Satz ist ein Passiv ohne Subjekt?', ['Im Lager wird rund um die Uhr gearbeitet.', 'Das Lager wird rund um die Uhr bewacht.', 'Die Arbeiter werden gut bezahlt.'],
      ['Which sentence is a passive without a subject?', 'Какое предложение – пассив без подлежащего?', 'Яке речення – пасив без підмета?', 'Hangi cümle öznesiz edilgen yapıdır?']),
    gap('G6', 'wird', I.verb, 'In den Ferien ', ' in der Werkstatt nur vormittags gearbeitet.', 'wird', ['werden', 'ist'],
      ['During the holidays work is only done in the workshop in the mornings.', 'В каникулы в мастерской работают только до обеда.', 'Під час канікул у майстерні працюють лише до обіду.', 'Tatilde atölyede yalnızca öğleden önce çalışılır.'], 'wird / werden / ist', { h: 'singular' }),
    mc('G7', 'Satzglied nach vorn', I.sentence, 'Es wurde lange auf den Techniker gewartet. → Stelle „lange“ an den Anfang.', ['Lange wurde auf den Techniker gewartet.', 'Lange wurde es auf den Techniker gewartet.', 'Lange es wurde auf den Techniker gewartet.'],
      ['Es wurde lange auf den Techniker gewartet. → Put “lange” at the beginning.', 'Es wurde lange auf den Techniker gewartet. → Поставьте «lange» в начало.', 'Es wurde lange auf den Techniker gewartet. → Поставте «lange» на початок.', 'Es wurde lange auf den Techniker gewartet. → “lange” sözcüğünü başa alın.'], { h: 'platzhalter' }),
    gap('G7', 'Es', I.word, '', ' wird darum gebeten, die Handys auszuschalten.', 'Es', ['Man', 'Das'],
      ['You are requested to switch off your mobile phones.', 'Просьба выключить мобильные телефоны.', 'Прохання вимкнути мобільні телефони.', 'Cep telefonlarının kapatılması rica olunur.'], 'Es / Man / Das'),
    mc('G8', 'Dem Gast wurde … angeboten', I.sentence, 'Welcher Satz ist richtig?', ['Dem Gast wurde ein anderer Tisch angeboten.', 'Der Gast wurde ein anderer Tisch angeboten.', 'Den Gast wurde ein anderer Tisch angeboten.'],
      ['Which sentence is correct?', 'Какое предложение правильное?', 'Яке речення правильне?', 'Hangi cümle doğru?'], { h: 'dativ' }),
    mc('G8', 'kein Passiv: besitzen', I.choose, 'Welches Verb kann kein Passiv bilden?', ['besitzen', 'bezahlen', 'bestellen'],
      ['Which verb cannot form a passive?', 'Какой глагол не может образовать пассив?', 'Яке дієслово не може утворити пасив?', 'Hangi fiil edilgen yapı kuramaz?']),
    gap('G8', 'Dem Verkäufer', I.article, 'Man widersprach dem Verkäufer nicht. → ', ' Verkäufer wurde nicht widersprochen.', 'Dem', ['Der', 'Den'],
      ['Nobody contradicted the salesman.', 'Продавцу не возразили.', 'Продавцеві не заперечили.', 'Satıcıya itiraz edilmedi.'], 'Dem / Der / Den', { h: 'dativ' }),
    mc('G9', 'Akkusativ → Subjekt', I.sentence, 'Man informiert die Kunden per E-Mail.', ['Die Kunden werden per E-Mail informiert.', 'Die Kunden wird per E-Mail informiert.', 'Die Kunden werden per E-Mail informieren.'],
      ['The customers are informed by email.', 'Клиентов информируют по электронной почте.', 'Клієнтів інформують електронною поштою.', 'Müşteriler e-postayla bilgilendirilir.'], { h: 'man' }),
    mc('G9', 'ohne Akkusativ', I.sentence, 'Man tanzte bis Mitternacht.', ['Bis Mitternacht wurde getanzt.', 'Bis Mitternacht wurden getanzt.', 'Bis Mitternacht wurde man getanzt.'],
      ['People danced until midnight.', 'Танцевали до полуночи.', 'Танцювали до півночі.', 'Gece yarısına kadar dans edildi.'], { h: 'man' }),
    gap('G9', 'ist geholfen worden', I.form, 'Man hat uns nicht geholfen. → Uns ist nicht geholfen ', '.', 'worden', ['geworden', 'werden'],
      ['Nobody helped us.', 'Нам не помогли.', 'Нам не допомогли.', 'Bize yardım edilmedi.'], 'worden / geworden / werden', { h: 'zeit' }),
    mc('Z1', 'Aushang: nach 22 Uhr', I.read, `${AUSHANG} Was gilt nach 22 Uhr?`, ['Es darf nicht mehr gewaschen werden.', 'Die Maschinen kosten weniger.', 'Der Automat wechselt kein Geld mehr.'],
      ['What applies after 10 p.m.?', 'Что действует после 22 часов?', 'Що діє після 22-ї години?', 'Saat 22’den sonra ne geçerli?']),
    mc('Z1', 'Aushang: Haftung', I.read, `${AUSHANG} Wofür übernimmt der Waschsalon keine Verantwortung?`, ['für vergessene Kleidung', 'für defekte Maschinen', 'für falsches Wechselgeld'],
      ['What does the launderette take no responsibility for?', 'За что прачечная не несёт ответственности?', 'За що пральня не несе відповідальності?', 'Çamaşırhane neyin sorumluluğunu üstlenmiyor?']),
  ],
}

export default check
