import { I, gap, mc, sb } from '../shared.mjs'

const MERKBLATT = 'Merkblatt einer Praxis: „Bitte kommen Sie nicht in die Sprechstunde, ohne vorher einen Termin zu vereinbaren. Wenn man Fieber hat, sollte man die Praxis anrufen, anstatt im Wartezimmer zu sitzen. Rezepte kann jemand aus der Familie für Sie abholen. Durch die Anmeldung per Telefon vermeiden Sie lange Wartezeiten. Niemand muss sich für eine Frage schämen: Fragen Sie nach, wenn Ihnen etwas unklar ist.“'
const MAN = 'man / einen / einem'

/** B2.2 · Pfad 5 · Gesundheit – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Krankschreibung', I.choose, 'Der Arzt hat ihm für zwei Wochen eine … gegeben, damit er sich zu Hause erholen kann.', ['Krankschreibung', 'Krankenkasse', 'Krankenpflege'],
      ['The doctor has given him a … for two weeks so that he can recover at home.', 'Врач выдал ему … на две недели, чтобы он мог восстановиться дома.', 'Лікар видав йому … на два тижні, щоб він міг відновитися вдома.', 'Doktor evde dinlenebilsin diye ona iki haftalık bir … verdi.']),
    mc('G1', 'einen (Akkusativ)', I.choose, 'Zu viel Lärm kann … richtig krank machen.', ['einen', 'einem', 'man'],
      ['Too much noise can really make you ill.', 'Слишком сильный шум может по-настоящему довести до болезни.', 'Надто сильний шум може по-справжньому довести до хвороби.', 'Aşırı gürültü insanı gerçekten hasta edebilir.'], { h: 'kasus' }),
    mc('G2', 'jemandem (Dativ)', I.choose, 'Er wollte mit … über die Diagnose sprechen und rief seinen Bruder an.', ['jemandem', 'jemanden', 'jemandes'],
      ['He wanted to talk to someone about the diagnosis and phoned his brother.', 'Он хотел с кем-нибудь поговорить о диагнозе и позвонил брату.', 'Він хотів із кимось поговорити про діагноз і зателефонував братові.', 'Tanı hakkında biriyle konuşmak istedi ve kardeşini aradı.'], { h: 'endung' }),
    mc('G3', 'nichts Schlimmes', I.choose, 'Der Test hat nichts … ergeben – Sie sind gesund.', ['Schlimmes', 'schlimm', 'Schlimme'],
      ['The test showed nothing serious – you are healthy.', 'Анализ не показал ничего серьёзного – вы здоровы.', 'Аналіз не показав нічого серйозного – ви здорові.', 'Test kötü bir şey göstermedi – sağlıklısınız.'], { h: 'adjektiv' }),
    mc('G4', 'konsequent bleiben', I.choose, 'Welcher Satz ist konsequent unpersönlich formuliert?', ['Wenn man sich schwach fühlt, sollte man seinen Arzt anrufen.', 'Wenn man sich schwach fühlt, sollte man deinen Arzt anrufen.', 'Wenn man sich schwach fühlt, sollte er seinen Arzt anrufen.'],
      ['Which sentence is worded consistently impersonally?', 'Какое предложение последовательно сформулировано безлично?', 'Яке речення послідовно сформульоване безособово?', 'Hangi cümle tutarlı biçimde kişisiz kurulmuştur?'], { h: 'konsequent' }),
    mc('G5', 'indem', I.choose, 'Er hat seine Fitness verbessert, … er dreimal pro Woche schwimmen ging.', ['indem', 'obwohl', 'damit'],
      ['He improved his fitness by going swimming three times a week.', 'Он улучшил свою физическую форму, три раза в неделю занимаясь плаванием.', 'Він покращив свою фізичну форму, тричі на тиждень займаючись плаванням.', 'Haftada üç kez yüzmeye giderek formunu düzeltti.'], { h: 'mittel' }),
    mc('G6', 'Dadurch, dass', I.choose, 'Dadurch, … er mit dem Rauchen aufgehört hat, hustet er kaum noch.', ['dass', 'weil', 'ob'],
      ['Because he has stopped smoking, he hardly coughs any more.', 'Благодаря тому, что он бросил курить, он почти не кашляет.', 'Завдяки тому, що він кинув курити, він майже не кашляє.', 'Sigarayı bıraktığı için artık neredeyse hiç öksürmüyor.']),
    mc('G7', 'durch + Akkusativ', I.choose, 'Durch … konnte die Krankheit rechtzeitig erkannt werden.', ['die regelmäßige Vorsorge', 'der regelmäßigen Vorsorge', 'regelmäßig vorsorgen'],
      ['Thanks to regular check-ups the illness was detected in time.', 'Благодаря регулярным профилактическим обследованиям болезнь удалось вовремя распознать.', 'Завдяки регулярним профілактичним обстеженням хворобу вдалося вчасно розпізнати.', 'Düzenli koruyucu muayeneler sayesinde hastalık zamanında fark edilebildi.'], { h: 'akkusativ' }),
    mc('G8', 'trennbares Verb', I.choose, 'Er fuhr in den Urlaub, ohne seine Medikamente …', ['mitzunehmen', 'zu mitnehmen', 'mitnehmen'],
      ['He went on holiday without taking his medicines with him.', 'Он уехал в отпуск, не взяв с собой лекарства.', 'Він поїхав у відпустку, не взявши із собою ліки.', 'İlaçlarını yanına almadan tatile çıktı.'], { h: 'zu' }),
    mc('G9', 'Sätze verbinden', I.sentence, 'Er geht nicht zum Arzt. Er sucht im Internet nach einer Diagnose.', ['Statt zum Arzt zu gehen, sucht er im Internet nach einer Diagnose.', 'Statt zum Arzt gehen, sucht er im Internet nach einer Diagnose.', 'Statt dass zum Arzt zu gehen, sucht er im Internet nach einer Diagnose.'],
      ['He does not go to the doctor. He looks for a diagnosis on the internet.', 'Он не идёт к врачу. Он ищет диагноз в интернете.', 'Він не йде до лікаря. Він шукає діагноз в інтернеті.', 'Doktora gitmiyor. İnternette tanı arıyor.'], { h: 'form' }),
    mc('Z1', 'Merkblatt: Fieber', I.read, `${MERKBLATT} Was soll man tun, wenn man Fieber hat?`, ['die Praxis anrufen', 'sich ins Wartezimmer setzen', 'ein Rezept abholen'],
      ['What should you do if you have a temperature?', 'Что нужно сделать, если у вас температура?', 'Що треба зробити, якщо у вас температура?', 'İnsanın ateşi varsa ne yapmalıdır?']),
    gap('G5', 'indem', I.conjunction, 'Man kann Stress abbauen, ', ' man regelmäßig Pausen macht.', 'indem', ['damit', 'obwohl'],
      ['You can reduce stress by taking regular breaks.', 'Стресс можно снять, регулярно делая перерывы.', 'Стрес можна зняти, регулярно роблячи перерви.', 'Düzenli molalar vererek stres azaltılabilir.'], 'indem / damit / obwohl', { h: 'mittel' }),
    sb('G9', 'Statt …, ging er …', I.order, 'Statt / sich auszuruhen, / ging / er / krank / ins Büro.',
      ['Instead of resting, he went to the office ill.', 'Вместо того чтобы отдохнуть, он больным пошёл в офис.', 'Замість того щоб відпочити, він хворим пішов до офісу.', 'Dinlenmek yerine hasta hasta ofise gitti.']),
  ],
  size: 13,
  test: [
    mc('W1', 'Überweisung', I.choose, 'Was ist eine „Überweisung“ beim Arzt?', ['ein Schein, mit dem man zu einem Facharzt geht', 'ein Zettel mit dem Namen eines Medikaments', 'eine Rechnung für die Behandlung'],
      ['What is an “Überweisung” at the doctor’s?', 'Что такое «Überweisung» у врача?', 'Що таке «Überweisung» у лікаря?', 'Doktorda “Überweisung” nedir?']),
    mc('W1', 'sich erholen', I.choose, 'Nach der Grippe hat er sich an der Ostsee zwei Wochen lang …', ['erholt', 'erkältet', 'erinnert'],
      ['After the flu he spent two weeks … by the Baltic Sea.', 'После гриппа он две недели … на Балтийском море.', 'Після грипу він два тижні … на Балтійському морі.', 'Gripten sonra Baltık Denizi kıyısında iki hafta boyunca …']),
    gap('W1', 'Nebenwirkung', I.word, 'Müdigkeit ist eine häufige ', ' dieses Medikaments, deshalb sollte man danach nicht Auto fahren.', 'Nebenwirkung', ['Nebenstraße', 'Nebensache'],
      ['Tiredness is a common side effect of this medicine, so you should not drive after taking it.', 'Сонливость – частое побочное действие этого лекарства, поэтому после него не стоит садиться за руль.', 'Сонливість – часта побічна дія цих ліків, тому після них не варто сідати за кермо.', 'Yorgunluk bu ilacın sık görülen bir yan etkisidir, bu yüzden aldıktan sonra araba kullanılmamalıdır.'],
      ['side effect', 'побочное действие', 'побічна дія', 'yan etki']),
    mc('G1', 'man (Nominativ)', I.choose, 'Wenn … krank ist, merkt man erst, wie wichtig Gesundheit ist.', ['man', 'einen', 'einem'],
      ['Only when you are ill do you realise how important health is.', 'Только когда болеешь, понимаешь, как важно здоровье.', 'Лише коли хворієш, розумієш, яке важливе здоров’я.', 'İnsan ancak hasta olunca sağlığın ne kadar önemli olduğunu anlar.'], { h: 'kasus' }),
    mc('G1', 'einem (Dativ)', I.choose, 'Der Arzt hat … genau erklärt, was man tun soll.', ['einem', 'einen', 'man'],
      ['The doctor explained to you exactly what you should do.', 'Врач подробно объяснил, что нужно делать.', 'Лікар докладно пояснив, що треба робити.', 'Doktor insana ne yapması gerektiğini ayrıntılı biçimde açıkladı.'], { h: 'kasus' }),
    gap('G1', 'einem (die Angst nehmen)', I.pronoun, 'Ein guter Arzt nimmt ', ' die Angst vor der Behandlung.', 'einem', ['einen', 'man'],
      ['A good doctor takes away your fear of the treatment.', 'Хороший врач избавляет человека от страха перед лечением.', 'Добрий лікар позбавляє людину страху перед лікуванням.', 'İyi bir doktor insanın tedavi korkusunu giderir.'], MAN, { h: 'kasus' }),
    mc('G2', 'niemand (Nominativ)', I.choose, 'Heute Morgen war … in der Praxis, das Wartezimmer war leer.', ['niemand', 'jemand', 'niemanden'],
      ['This morning there was nobody at the practice; the waiting room was empty.', 'Сегодня утром в кабинете врача никого не было, приёмная была пуста.', 'Сьогодні вранці в кабінеті лікаря нікого не було, приймальня була порожня.', 'Bu sabah muayenehanede kimse yoktu, bekleme odası boştu.']),
    mc('G2', 'jemandem (Dativ)', I.choose, 'Ich möchte bitte mit … sprechen, der sich mit Allergien auskennt.', ['jemandem', 'jemanden', 'jemandes'],
      ['I would like to speak to someone who knows about allergies, please.', 'Я хотел бы поговорить с кем-нибудь, кто разбирается в аллергиях.', 'Я хотів би поговорити з кимось, хто знається на алергіях.', 'Alerjilerden anlayan biriyle konuşmak istiyorum lütfen.'], { h: 'endung' }),
    gap('G2', 'niemanden', I.pronoun, 'Er lag drei Tage allein zu Hause und hat ', ' gesehen.', 'niemanden', ['niemandem', 'niemandes'],
      ['He lay at home alone for three days and saw no one.', 'Он три дня пролежал дома один и никого не видел.', 'Він три дні пролежав удома сам і нікого не бачив.', 'Üç gün evde yalnız yattı ve kimseyi görmedi.'], 'niemand (Akkusativ)', { h: 'endung' }),
    mc('G3', 'irgendwie', I.choose, 'Was bedeutet „irgendwie“?', ['auf unbestimmte Weise', 'an einem unbestimmten Ort', 'zu einem unbestimmten Zeitpunkt'],
      ['What does “irgendwie” mean?', 'Что означает «irgendwie»?', 'Що означає «irgendwie»?', '“irgendwie” ne demek?']),
    mc('G3', 'alles Liebe', I.choose, 'Zum Geburtstag wünsche ich dir alles … und vor allem Gesundheit!', ['Liebe', 'Liebes', 'lieb'],
      ['For your birthday I wish you all the best and above all good health!', 'В день рождения желаю тебе всего самого доброго и прежде всего здоровья!', 'У день народження бажаю тобі всього найкращого і передусім здоров’я!', 'Doğum gününde sana her şeyin en güzelini ve en başta sağlık diliyorum!'], { h: 'adjektiv' }),
    gap('G3', 'etwas Leichtes', I.ending, 'Bei Fieber sollte man etwas ', ' essen, zum Beispiel eine Suppe.', 'Leichtes', ['Leichte', 'leicht'],
      ['If you have a temperature you should eat something light, for example a soup.', 'При температуре следует есть что-нибудь лёгкое, например суп.', 'За температури слід їсти щось легке, наприклад суп.', 'Ateş varken hafif bir şey yenmelidir, örneğin çorba.'], 'leicht', { h: 'adjektiv' }),
    mc('G4', 'ihr → man', I.sentence, 'Als allgemeiner Rat: Ihr solltet mehr Obst essen.', ['Man sollte mehr Obst essen.', 'Man solltet mehr Obst essen.', 'Einen sollte mehr Obst essen.'],
      ['As general advice: you should eat more fruit.', 'Как общий совет: вам следует есть больше фруктов.', 'Як загальна порада: вам слід їсти більше фруктів.', 'Genel bir öğüt olarak: Daha çok meyve yemelisiniz.']),
    gap('G4', 'sich', I.reflexive, 'Wenn man Kopfschmerzen hat, sollte man zuerst ein Glas Wasser trinken und ', ' ausruhen.', 'sich', ['dich', 'ihn'],
      ['If you have a headache, you should first drink a glass of water and rest.', 'Если болит голова, сначала нужно выпить стакан воды и отдохнуть.', 'Якщо болить голова, спершу треба випити склянку води й відпочити.', 'İnsanın başı ağrıyorsa önce bir bardak su içmeli ve dinlenmelidir.'], 'sich / dich / ihn', { h: 'konsequent' }),
    mc('G5', 'Antwort mit indem', I.choose, 'Wie hat er seine Angst vor Spritzen überwunden? – …', ['Indem er mit seinem Arzt darüber gesprochen hat.', 'Damit er mit seinem Arzt darüber gesprochen hat.', 'Obwohl er mit seinem Arzt darüber gesprochen hat.'],
      ['How did he overcome his fear of injections? – …', 'Как он преодолел страх перед уколами? – …', 'Як він подолав страх перед уколами? – …', 'İğne korkusunu nasıl yendi? – …'], { h: 'mittel' }),
    mc('G5', 'Sätze verbinden', I.sentence, 'Er geht jeden Abend früh ins Bett. So erholt er sich schneller.', ['Er erholt sich schneller, indem er jeden Abend früh ins Bett geht.', 'Er geht jeden Abend früh ins Bett, indem er sich schneller erholt.', 'Er erholt sich schneller, indem er geht jeden Abend früh ins Bett.'],
      ['He goes to bed early every evening. That way he recovers more quickly.', 'Он каждый вечер рано ложится спать. Так он быстрее восстанавливается.', 'Він щовечора рано лягає спати. Так він швидше відновлюється.', 'Her akşam erken yatıyor. Böylece daha çabuk toparlanıyor.'], { h: 'mittel' }),
    gap('G5', 'Verb am Ende', I.verb, 'Man beugt Zahnproblemen vor, indem man sich zweimal täglich die Zähne ', '.', 'putzt', ['putzen', 'geputzt'],
      ['You prevent dental problems by brushing your teeth twice a day.', 'Проблемы с зубами предотвращают, дважды в день чистя зубы.', 'Проблемам із зубами запобігають, двічі на день чистячи зуби.', 'Dişler günde iki kez fırçalanarak diş sorunları önlenir.'], 'putzen', { h: 'verb' }),
    mc('G6', 'Wortstellung', I.sentence, 'Welcher Satz ist richtig?', ['Dadurch, dass er weniger arbeitet, hat er mehr Zeit für Sport.', 'Dadurch, dass er arbeitet weniger, hat er mehr Zeit für Sport.', 'Dadurch, dass er weniger arbeitet, er hat mehr Zeit für Sport.'],
      ['Which sentence is correct?', 'Какое предложение правильное?', 'Яке речення правильне?', 'Hangi cümle doğru?'], { h: 'wortstellung' }),
    gap('G6', 'Dadurch als Adverb', I.adverb, 'Er hat seine Ernährung umgestellt. ', ' sind seine Blutwerte viel besser geworden.', 'Dadurch', ['Indem', 'Dass'],
      ['He has changed his diet. As a result his blood values have improved a great deal.', 'Он изменил питание. Благодаря этому его показатели крови стали намного лучше.', 'Він змінив харчування. Завдяки цьому його показники крові стали набагато кращими.', 'Beslenmesini değiştirdi. Bu sayede kan değerleri çok düzeldi.'], 'Dadurch / Indem / Dass', { h: 'adverb' }),
    mc('G7', 'durch + Nomen', I.choose, '… eine frühe Behandlung lassen sich viele Krankheiten heilen.', ['Durch', 'Indem', 'Dadurch'],
      ['Through early treatment many illnesses can be cured.', 'Благодаря раннему лечению многие болезни можно вылечить.', 'Завдяки ранньому лікуванню багато хвороб можна вилікувати.', 'Erken tedaviyle birçok hastalık iyileştirilebilir.'], { h: 'nomen' }),
    mc('G7', 'indem → durch', I.sentence, 'Indem man regelmäßig schwimmt, stärkt man den Rücken.', ['Durch regelmäßiges Schwimmen stärkt man den Rücken.', 'Durch regelmäßigem Schwimmen stärkt man den Rücken.', 'Durch regelmäßig schwimmen stärkt man den Rücken.'],
      ['By swimming regularly you strengthen your back.', 'Регулярно плавая, укрепляешь спину.', 'Регулярно плаваючи, зміцнюєш спину.', 'İnsan düzenli yüzerek sırtını güçlendirir.'], { h: 'akkusativ' }),
    gap('G7', 'durch eine Erkältung', I.article, 'Durch ', ' Erkältung hat er die Prüfung verpasst.', ['eine', 'die', 'seine'], ['einer', 'der'],
      ['Because of a cold he missed the exam.', 'Из-за простуды он пропустил экзамен.', 'Через застуду він пропустив іспит.', 'Soğuk algınlığı yüzünden sınavı kaçırdı.'], 'die Erkältung', { h: 'akkusativ' }),
    mc('G8', 'ohne dass', I.choose, 'Er hat das Krankenhaus verlassen, ohne … die Ärzte einverstanden waren.', ['dass', 'zu', 'ob'],
      ['He left the hospital without the doctors agreeing to it.', 'Он покинул больницу без согласия врачей.', 'Він залишив лікарню без згоди лікарів.', 'Doktorların onayı olmadan hastaneden ayrıldı.'], { h: 'subjekt' }),
    mc('G8', 'Sätze verbinden', I.sentence, 'Er nahm das Medikament. Er las die Hinweise nicht.', ['Er nahm das Medikament, ohne die Hinweise zu lesen.', 'Er nahm das Medikament, ohne die Hinweise nicht zu lesen.', 'Er nahm das Medikament, ohne dass die Hinweise zu lesen.'],
      ['He took the medicine. He did not read the instructions.', 'Он принял лекарство. Он не прочитал указания.', 'Він прийняв ліки. Він не прочитав указівок.', 'İlacı aldı. Uyarıları okumadı.'], { h: 'negativ' }),
    gap('G8', 'ohne … zu essen', I.form, 'Er arbeitete zehn Stunden am Stück, ohne etwas zu ', '.', ['essen', 'trinken'], ['gegessen', 'isst'],
      ['He worked for ten hours at a stretch without eating anything.', 'Он проработал десять часов подряд, ничего не съев.', 'Він працював десять годин поспіль, нічого не з’ївши.', 'Hiçbir şey yemeden on saat aralıksız çalıştı.'], 'essen / gegessen / isst', { h: 'zu' }),
    mc('G9', 'Bedeutung', I.choose, 'Was bedeutet: „Anstatt zu jammern, suchte er sich Hilfe.“?', ['Er jammerte nicht, sondern suchte sich Hilfe.', 'Er jammerte und suchte sich Hilfe.', 'Er suchte keine Hilfe, sondern jammerte.'],
      ['What does this mean: “Anstatt zu jammern, suchte er sich Hilfe.”?', 'Что означает: «Anstatt zu jammern, suchte er sich Hilfe.»?', 'Що означає: «Anstatt zu jammern, suchte er sich Hilfe.»?', 'Şu ne demek: “Anstatt zu jammern, suchte er sich Hilfe.”?'], { h: 'bedeutung' }),
    mc('G9', 'trennbares Verb', I.sentence, 'Welcher Satz ist richtig gebildet?', ['Anstatt früh aufzustehen, blieb er bis mittags im Bett.', 'Anstatt früh zu aufstehen, blieb er bis mittags im Bett.', 'Anstatt früh aufzustehen, er blieb bis mittags im Bett.'],
      ['Which sentence is formed correctly?', 'Какое предложение построено правильно?', 'Яке речення побудовано правильно?', 'Hangi cümle doğru kurulmuştur?'], { h: 'form' }),
    gap('G9', 'statt … zu essen', I.form, 'Statt jeden Tag Fleisch zu ', ', kocht er jetzt öfter Gemüse.', 'essen', ['isst', 'gegessen'],
      ['Instead of eating meat every day, he now cooks vegetables more often.', 'Вместо того чтобы каждый день есть мясо, он теперь чаще готовит овощи.', 'Замість того щоб щодня їсти м’ясо, він тепер частіше готує овочі.', 'Her gün et yemek yerine artık daha sık sebze pişiriyor.'], 'essen / isst / gegessen', { h: 'form' }),
    mc('Z1', 'Merkblatt: Termin', I.read, `${MERKBLATT} Was sollen Patienten vor dem Besuch der Sprechstunde tun?`, ['einen Termin vereinbaren', 'ein Rezept abholen', 'ihre Familie mitbringen'],
      ['What should patients do before coming to the surgery hours?', 'Что пациенты должны сделать перед посещением приёма?', 'Що пацієнти мають зробити перед відвідуванням прийому?', 'Hastalar muayene saatine gelmeden önce ne yapmalıdır?']),
    mc('Z1', 'Merkblatt: Rezept', I.read, `${MERKBLATT} Wer darf laut Merkblatt ein Rezept abholen?`, ['jemand aus der Familie', 'nur der Patient selbst', 'niemand'],
      ['According to the leaflet, who may collect a prescription?', 'Кто, согласно памятке, может забрать рецепт?', 'Хто, згідно з пам’яткою, може забрати рецепт?', 'Bilgi notuna göre reçeteyi kim alabilir?']),
  ],
}

export default check
