import { I, gap, mc } from '../shared.mjs'

const AKKUSCHRAUBER = 'Werbeanzeige: „Der Akkuschrauber für Profis und Heimwerker! Er ist sowohl kraftvoll als auch erstaunlich leise. Mit einer Akkuladung arbeiten Sie bis zu sechs Stunden. Im Koffer finden Sie alles, was Sie brauchen: zwei Akkus, ein Ladegerät und 30 Aufsätze. Drei Jahre Garantie – aber nur, wenn Sie das Gerät innerhalb von vier Wochen online registrieren.“'
const LEIHLADEN = 'Reportage: „In einer kleinen Stadt in Hessen teilen sich 400 Haushalte Bohrmaschinen, Leitern und Nähmaschinen. Im Leihladen, wo früher eine Bäckerei war, kann man Geräte für wenig Geld ausleihen. Die Idee hatte ein Rentner, der sich über seinen vollen Keller ärgerte. Geöffnet ist an drei Nachmittagen pro Woche. Die Mitarbeiter arbeiten ohne Bezahlung, was das Angebot so günstig macht.“'

/** B1.2 · Pfad 3 · Werbung und Konsum – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Reklamation', I.choose, 'Der Mixer war schon beim Auspacken defekt. Ich habe sofort eine … geschrieben und um Ersatz gebeten.', ['Reklamation', 'Reservierung', 'Einladung'],
      ['The blender was already faulty when I unpacked it. I immediately wrote a … and asked for a replacement.', 'Блендер оказался неисправным уже при распаковке. Я сразу написал … и попросил замену.', 'Блендер виявився несправним уже під час розпакування. Я одразу написав … і попросив заміну.', 'Blender daha kutudan çıkarken arızalıydı. Hemen bir … yazdım ve yenisini istedim.']),
    mc('G1', 'als auch', I.choose, 'Unsere Monteure arbeiten sowohl werktags … am Samstag.', ['als auch', 'noch', 'sondern'],
      ['Our fitters work both on weekdays and on Saturdays.', 'Наши монтёры работают как в будни, так и в субботу.', 'Наші монтери працюють як у будні, так і в суботу.', 'Tesisatçılarımız hem hafta içi hem de cumartesi çalışıyor.']),
    mc('G2', 'weder', I.choose, 'Ich habe … den Kassenbon noch die Verpackung aufgehoben. Kann ich das Gerät trotzdem umtauschen?', ['weder', 'sowohl', 'nicht nur'],
      ['I have kept neither the receipt nor the packaging. Can I exchange the appliance all the same?', 'Я не сохранил ни чек, ни упаковку. Могу ли я всё-таки обменять прибор?', 'Я не зберіг ні чека, ні упаковки. Чи можу я все-таки обміняти прилад?', 'Ne fişi ne de ambalajı sakladım. Cihazı yine de değiştirebilir miyim?']),
    mc('G3', 'dort, wo', I.choose, 'Wir essen heute dort, … wir unseren ersten Firmenausflug gefeiert haben.', ['wo', 'was', 'wie'],
      ['Today we are eating where we celebrated our first company outing.', 'Сегодня мы обедаем там, где отмечали нашу первую корпоративную поездку.', 'Сьогодні ми обідаємо там, де святкували нашу першу корпоративну поїздку.', 'Bugün ilk şirket gezimizi kutladığımız yerde yemek yiyoruz.']),
    mc('G4', 'nichts, was', I.choose, 'Es gibt nichts, … mich mehr ärgert als unfreundliche Verkäufer.', ['was', 'wo', 'wer'],
      ['There is nothing that annoys me more than unfriendly shop assistants.', 'Нет ничего, что раздражало бы меня больше, чем неприветливые продавцы.', 'Немає нічого, що дратувало б мене більше, ніж непривітні продавці.', 'Beni güler yüzsüz satıcılardan daha çok kızdıran hiçbir şey yok.']),
    mc('G5', 'die steigenden Kosten', I.choose, 'Die … Kosten für Strom und Gas machen vielen Familien Sorgen.', ['steigenden', 'steigende', 'steigend'],
      ['The rising costs of electricity and gas worry many families.', 'Растущие расходы на электричество и газ беспокоят многие семьи.', 'Витрати на електрику й газ, що зростають, непокоять багато родин.', 'Artan elektrik ve gaz giderleri birçok aileyi kaygılandırıyor.']),
    mc('K1', 'Also, ich muss sagen, …', I.choose, 'Also, ich muss …, das hat mich schon etwas enttäuscht: Niemand hat mich über die Verspätung informiert.', ['sagen', 'fragen', 'tragen'],
      ['Well, I must say that did disappoint me somewhat: nobody informed me about the delay.', 'Должен сказать, это меня несколько разочаровало: никто не сообщил мне о задержке.', 'Мушу сказати, це мене дещо розчарувало: ніхто не повідомив мені про затримку.', 'Doğrusu şunu söylemeliyim: Bu beni biraz hayal kırıklığına uğrattı; kimse bana gecikmeyi bildirmedi.']),
    mc('K2', 'Das tut mir leid. Selbstverständlich …', I.react, '„Die Rechnung ist falsch: Sie haben mir zwei Geräte berechnet, ich habe aber nur eins gekauft.“', ['Oh, das tut mir leid. Selbstverständlich korrigieren wir das sofort.', 'Wahnsinn! Unglaublich!', 'Das ist mir auch schon passiert, wie peinlich.'],
      ['“The invoice is wrong: you have charged me for two appliances, but I only bought one.”', '«Счёт неверный: вы посчитали мне два прибора, а я купил только один.»', '«Рахунок неправильний: ви порахували мені два прилади, а я купив лише один.»', '“Fatura yanlış: Bana iki cihaz yazmışsınız ama ben yalnızca bir tane aldım.”']),
    mc('K3', 'peinlich', I.choose, 'Ich habe den Kunden zwei Stunden warten lassen, weil ich den Termin falsch notiert hatte. Das war mir sehr …', ['peinlich', 'preiswert', 'praktisch'],
      ['I kept the customer waiting for two hours because I had noted down the appointment wrongly. That was very … for me.', 'Я заставил клиента ждать два часа, потому что неправильно записал время встречи. Мне было очень …', 'Я змусив клієнта чекати дві години, бо неправильно записав час зустрічі. Мені було дуже …', 'Randevuyu yanlış not ettiğim için müşteriyi iki saat beklettim. Bu benim için çok … oldu.']),
    mc('K4', 'Erstaunen ausdrücken', I.react, '„Dieser Koffer wiegt nur ein Kilo und trägt trotzdem vierzig!“', ['Ach, wirklich? Das ist ja nicht zu glauben.', 'Ich kann verstehen, dass Sie enttäuscht sind.', 'Es war abgemacht, dass er leichter ist.'],
      ['“This suitcase weighs only one kilo and still carries forty!”', '«Этот чемодан весит всего килограмм и при этом выдерживает сорок!»', '«Ця валіза важить лише кілограм і при цьому витримує сорок!»', '“Bu bavul yalnızca bir kilo ama yine de kırk kilo taşıyor!”']),
    mc('Z1', 'Garantie', I.read, `${AKKUSCHRAUBER} Unter welcher Bedingung bekommt man drei Jahre Garantie?`, ['Wenn man das Gerät innerhalb von vier Wochen online registriert.', 'Wenn man zwei Geräte kauft.', 'Wenn man den Koffer zurückschickt.'],
      ['On what condition do you get a three-year guarantee?', 'При каком условии даётся трёхлетняя гарантия?', 'За якої умови надається трирічна гарантія?', 'Üç yıllık garanti hangi koşulla veriliyor?']),
    gap('G1', 'als auch', I.conjunction, 'Sowohl der Preis als ', ' die Lieferzeit haben uns überzeugt.', 'auch', ['noch', 'ob'],
      ['Both the price and the delivery time convinced us.', 'Нас убедили и цена, и срок доставки.', 'Нас переконали і ціна, і термін доставки.', 'Hem fiyat hem de teslim süresi bizi ikna etti.'], 'auch / noch / ob'),
    gap('G4', 'alles, was', I.pronoun, 'Das ist alles, ', ' ich über dieses Produkt weiß.', 'was', ['wo', 'wie'],
      ['That is all I know about this product.', 'Это всё, что я знаю об этом товаре.', 'Це все, що я знаю про цей товар.', 'Bu ürün hakkında bildiğim her şey bu.'], 'was / wo / wie'),
  ],
  size: 13,
  test: [
    mc('W1', 'Umtausch', I.choose, 'Die Schuhe sind mir zu klein. Ist ein … gegen eine größere Größe möglich?', ['Umtausch', 'Umzug', 'Umweg'],
      ['The shoes are too small for me. Is an … for a larger size possible?', 'Туфли мне малы. Возможен ли … на больший размер?', 'Туфлі мені малі. Чи можливий … на більший розмір?', 'Ayakkabılar bana küçük geldi. Daha büyük bir numarayla … mümkün mü?']),
    mc('W1', 'Hersteller', I.choose, 'Auf der Verpackung steht, in welchem Land der … das Produkt produziert hat.', ['Hersteller', 'Zuschauer', 'Besitzer'],
      ['The packaging says in which country the … produced the product.', 'На упаковке указано, в какой стране … изготовил товар.', 'На упаковці зазначено, у якій країні … виготовив товар.', 'Ambalajın üzerinde … ürünü hangi ülkede ürettiği yazıyor.']),
    mc('G1', 'sowohl', I.choose, 'Das Auto verbraucht wenig und ist trotzdem schnell: Es ist … sparsam als auch sportlich.', ['sowohl', 'weder', 'entweder'],
      ['The car uses little fuel and is fast all the same: it is both economical and sporty.', 'Машина расходует мало топлива и при этом быстрая: она и экономичная, и спортивная.', 'Машина витрачає мало пального і водночас швидка: вона і економна, і спортивна.', 'Araba az yakıyor ve yine de hızlı: Hem tasarruflu hem de sportif.']),
    mc('G1', 'Verb im Plural', I.choose, 'Sowohl die Farbe als auch die Größe … genau zu meiner Küche.', ['passen', 'passt', 'passe'],
      ['Both the colour and the size suit my kitchen exactly.', 'И цвет, и размер точно подходят к моей кухне.', 'І колір, і розмір точно пасують до моєї кухні.', 'Hem renk hem de boyut mutfağıma tam uyuyor.']),
    mc('G2', 'noch', I.choose, 'Das Hotel war eine Enttäuschung: Es war weder sauber … ruhig.', ['noch', 'als auch', 'aber'],
      ['The hotel was a disappointment: it was neither clean nor quiet.', 'Отель разочаровал: он не был ни чистым, ни тихим.', 'Готель розчарував: він не був ні чистим, ні тихим.', 'Otel bir hayal kırıklığıydı: Ne temizdi ne de sessiz.']),
    mc('G2', 'weder … noch', I.sentence, 'Daniel beschwert sich über eine Lieferung.', ['Ich habe weder eine Rechnung noch einen Lieferschein bekommen.', 'Ich habe weder keine Rechnung noch einen Lieferschein bekommen.', 'Ich habe weder eine Rechnung als auch einen Lieferschein bekommen.'],
      ['Daniel is complaining about a delivery.', 'Daniel жалуется на доставку.', 'Daniel скаржиться на доставку.', 'Daniel bir teslimattan şikâyet ediyor.']),
    mc('G3', 'die Straße, wo', I.choose, 'Das ist die Straße, … früher die alte Fabrik stand.', ['wo', 'was', 'wer'],
      ['That is the street where the old factory used to stand.', 'Это улица, где раньше стояла старая фабрика.', 'Це вулиця, де раніше стояла стара фабрика.', 'Bu, eskiden eski fabrikanın bulunduğu sokak.']),
    mc('G3', 'in Wien, wo', I.choose, 'In Wien, … meine Firma eine Filiale hat, bin ich mindestens einmal im Monat.', ['wo', 'was', 'wohin'],
      ['I am in Vienna, where my company has a branch, at least once a month.', 'В Вене, где у моей фирмы есть филиал, я бываю как минимум раз в месяц.', 'У Відні, де моя фірма має філію, я буваю щонайменше раз на місяць.', 'Şirketimin bir şubesinin bulunduğu Viyana’ya ayda en az bir kez gidiyorum.']),
    mc('G4', 'alles, was', I.choose, 'Zeig mir bitte alles, … du für die Messe vorbereitet hast.', ['was', 'wo', 'wen'],
      ['Please show me everything you have prepared for the trade fair.', 'Покажи мне, пожалуйста, всё, что ты подготовил к выставке.', 'Покажи мені, будь ласка, усе, що ти підготував до виставки.', 'Fuar için hazırladığın her şeyi bana göster lütfen.']),
    mc('G4', 'was nach einem ganzen Satz', I.choose, 'Der Monteur kam zwei Stunden zu spät, … mich wirklich geärgert hat.', ['was', 'wo', 'wem'],
      ['The fitter arrived two hours late, which really annoyed me.', 'Монтёр опоздал на два часа, что меня действительно рассердило.', 'Монтер запізнився на дві години, що мене справді розсердило.', 'Tesisatçı iki saat geç geldi; bu beni gerçekten kızdırdı.']),
    mc('G5', 'den laufenden Motor', I.choose, 'Bitte stellen Sie den … Motor ab, wenn Sie länger warten.', ['laufenden', 'laufende', 'laufender'],
      ['Please switch off the running engine if you have to wait longer.', 'Пожалуйста, выключайте работающий двигатель, если ждёте долго.', 'Будь ласка, вимикайте двигун, що працює, якщо чекаєте довго.', 'Uzun süre bekleyecekseniz lütfen çalışan motoru kapatın.']),
    mc('G5', 'Bedeutung: ein bellender Hund', I.choose, 'Was ist ein „bellender Hund“?', ['Ein Hund, der gerade bellt.', 'Ein Hund, der gebellt hat.', 'Ein Hund, der nie bellt.'],
      ['What is a “bellender Hund” (barking dog)?', 'Что такое «bellender Hund» (лающая собака)?', 'Що таке «bellender Hund» (собака, що гавкає)?', '“Bellender Hund” (havlayan köpek) ne demektir?']),
    mc('K1', 'sachliche Beschwerde', I.situation, 'Dein neuer Kühlschrank macht laute Geräusche. Was schreibst du dem Händler?', ['Ich musste leider feststellen, dass der Kühlschrank sehr laut ist. Ich bitte um Reparatur oder Umtausch.', 'Ihr Kühlschrank ist Müll, und Sie sind Betrüger!', 'Ich möchte Ihnen zu Ihrem Kühlschrank gratulieren.'],
      ['Your new fridge is making loud noises. What do you write to the retailer?', 'Ваш новый холодильник сильно шумит. Что вы напишете продавцу?', 'Ваш новий холодильник сильно шумить. Що ви напишете продавцеві?', 'Yeni buzdolabınız çok ses çıkarıyor. Satıcıya ne yazarsınız?']),
    mc('K1', 'vereinbart', I.choose, 'Es war …, dass Sie die Küche bis Freitag einbauen. Heute ist Montag, und es fehlt immer noch die Hälfte.', ['vereinbart', 'verboten', 'verschwunden'],
      ['It was … that you would fit the kitchen by Friday. Today is Monday, and half of it is still missing.', 'Было …, что вы установите кухню до пятницы. Сегодня понедельник, а половины всё ещё нет.', 'Було …, що ви встановите кухню до п’ятниці. Сьогодні понеділок, а половини все ще немає.', 'Mutfağı cumaya kadar monte edeceğiniz … . Bugün pazartesi ve hâlâ yarısı eksik.']),
    mc('K2', 'mit Verständnis reagieren', I.react, '„Das bestellte Regal hat die falsche Farbe.“', ['Ich kann verstehen, dass Sie verärgert sind. Wir holen es ab und liefern das richtige.', 'Stell dir vor, was mir passiert ist!', 'Das Beste kommt noch!'],
      ['“The shelf unit I ordered is the wrong colour.”', '«У заказанного стеллажа не тот цвет.»', '«У замовленого стелажа не той колір.»', '“Sipariş ettiğim rafın rengi yanlış.”']),
    mc('K3', 'Oje, wie peinlich!', I.react, '„Ich habe beim Vorstellungsgespräch zwei verschiedene Schuhe getragen und es erst zu Hause gemerkt.“', ['Oje, wie peinlich! Hat es jemand gesehen?', 'Dazu möchte ich noch anmerken, dass die Schuhe teuer waren.', 'Selbstverständlich, kein Problem.'],
      ['“At the job interview I wore two different shoes and only noticed it at home.”', '«На собеседовании на мне были два разных ботинка, и я заметил это только дома.»', '«На співбесіді на мені були два різні черевики, і я помітив це лише вдома.»', '“İş görüşmesinde ayağımda iki farklı ayakkabı vardı ve bunu ancak evde fark ettim.”']),
    mc('K4', 'nicht nur …, sondern auch', I.choose, 'Der neue Staubsauger kann nicht … saugen, sondern auch die Luft reinigen.', ['nur', 'kein', 'noch'],
      ['The new vacuum cleaner can not only vacuum but also clean the air.', 'Новый пылесос умеет не только пылесосить, но и очищать воздух.', 'Новий пилосос уміє не лише пилососити, а й очищати повітря.', 'Yeni elektrikli süpürge yalnızca süpürmekle kalmıyor, havayı da temizliyor.']),
    mc('Z1', 'Inhalt des Koffers', I.read, `${AKKUSCHRAUBER} Was ist im Koffer?`, ['Zwei Akkus, ein Ladegerät und 30 Aufsätze.', 'Nur der Akkuschrauber.', 'Ein zweiter Akkuschrauber.'],
      ['What is in the case?', 'Что находится в чемоданчике?', 'Що лежить у валізці?', 'Çantanın içinde ne var?']),
    mc('Z1', 'Leihladen', I.read, `${LEIHLADEN} Was kann man im Leihladen machen?`, ['Geräte für wenig Geld ausleihen.', 'Brot und Kuchen kaufen.', 'Alte Geräte reparieren lassen.'],
      ['What can you do in the lending shop?', 'Что можно делать в пункте проката?', 'Що можна робити в пункті прокату?', 'Ödünç verme dükkânında ne yapılabilir?']),
    mc('Z1', 'Warum so günstig?', I.read, `${LEIHLADEN} Warum ist das Angebot so günstig?`, ['Weil die Mitarbeiter ohne Bezahlung arbeiten.', 'Weil die Stadt alles bezahlt.', 'Weil die Geräte alt und kaputt sind.'],
      ['Why is the service so cheap?', 'Почему услуга такая недорогая?', 'Чому послуга така недорога?', 'Hizmet neden bu kadar ucuz?']),
    gap('W1', 'Lieferung', I.word, 'Wir haben die Ware am Montag bestellt, aber die ', ' ist immer noch nicht angekommen.', 'Lieferung', ['Leistung', 'Lösung'],
      ['We ordered the goods on Monday, but the delivery has still not arrived.', 'Мы заказали товар в понедельник, но доставка до сих пор не пришла.', 'Ми замовили товар у понеділок, але доставка досі не прийшла.', 'Malı pazartesi sipariş ettik ama teslimat hâlâ gelmedi.'],
      ['delivery', 'доставка', 'доставка', 'teslimat']),
    gap('G1', 'sowohl … als auch', I.conjunction, 'Die Schuhe gibt es sowohl in Schwarz ', ' auch in Braun.', 'als', ['oder', 'noch'],
      ['The shoes are available both in black and in brown.', 'Эти туфли есть как в чёрном, так и в коричневом цвете.', 'Ці туфлі є як у чорному, так і в коричневому кольорі.', 'Ayakkabıların hem siyahı hem de kahverengisi var.'], 'als / oder / noch'),
    gap('G2', 'weder', I.conjunction, 'Der Händler hat sich ', ' entschuldigt noch eine Lösung angeboten.', 'weder', ['sowohl', 'entweder'],
      ['The retailer neither apologised nor offered a solution.', 'Продавец ни извинился, ни предложил решение.', 'Продавець ні вибачився, ні запропонував рішення.', 'Satıcı ne özür diledi ne de bir çözüm önerdi.'], 'weder / sowohl / entweder'),
    gap('G3', 'überall, wo', I.pronoun, 'Überall, ', ' wir unsere Produkte vorstellen, bekommen wir viele Fragen.', 'wo', ['was', 'wer'],
      ['Wherever we present our products, we get a lot of questions.', 'Везде, где мы представляем наши товары, нам задают много вопросов.', 'Усюди, де ми представляємо наші товари, нам ставлять багато запитань.', 'Ürünlerimizi tanıttığımız her yerde çok soru alıyoruz.'], 'wo / was / wer'),
    gap('G4', 'das Einzige, was', I.pronoun, 'Das Einzige, ', ' mir an dem Gerät nicht gefällt, ist die Farbe.', 'was', ['wo', 'wie'],
      ['The only thing I do not like about the appliance is the colour.', 'Единственное, что мне не нравится в приборе, – это цвет.', 'Єдине, що мені не подобається в приладі, – це колір.', 'Cihazda hoşuma gitmeyen tek şey rengi.'], 'was / wo / wie'),
    gap('G5', 'ein schlafendes Baby', I.ending, 'Auf dem Plakat sieht man ein ', ' Baby in einem weißen Bett.', 'schlafendes', ['schlafende', 'schlafender'],
      ['On the poster you can see a sleeping baby in a white bed.', 'На плакате изображён спящий младенец в белой кроватке.', 'На плакаті зображено немовля, що спить у білому ліжечку.', 'Afişte beyaz bir yatakta uyuyan bir bebek görülüyor.'], 'schlafen'),
    gap('K1', 'verärgert', I.word, 'Ich bin wirklich sehr ', ': Seit zwei Wochen verspricht man mir einen Rückruf.', 'verärgert', ['verliebt', 'verletzt'],
      ['I am really very annoyed: for two weeks I have been promised a call back.', 'Я действительно очень рассержен: мне уже две недели обещают перезвонить.', 'Я справді дуже розсерджений: мені вже два тижні обіцяють передзвонити.', 'Gerçekten çok kızgınım: İki haftadır beni geri arayacaklarını söylüyorlar.'],
      ['annoyed, angry', 'рассержен', 'розсерджений', 'kızgın']),
    gap('K2', 'kein Problem', I.word, 'Selbstverständlich, das ist überhaupt kein ', '. Wir tauschen das Gerät sofort um.', 'Problem', ['Programm', 'Projekt'],
      ['Of course, that is no problem at all. We will exchange the appliance at once.', 'Разумеется, это вообще не проблема. Мы сразу обменяем прибор.', 'Звісно, це взагалі не проблема. Ми одразу обміняємо прилад.', 'Elbette, bu hiç sorun değil. Cihazı hemen değiştiriyoruz.'],
      ['problem', 'проблема', 'проблема', 'sorun']),
    gap('K3', 'aus Versehen', I.word, 'Entschuldigung, ich habe aus ', ' Ihre Tasche genommen. Sie sieht genauso aus wie meine.', 'Versehen', ['Verstehen', 'Versprechen'],
      ['Sorry, I took your bag by mistake. It looks exactly like mine.', 'Извините, я по ошибке взял вашу сумку. Она выглядит точно так же, как моя.', 'Вибачте, я помилково взяв вашу сумку. Вона виглядає так само, як моя.', 'Affedersiniz, yanlışlıkla sizin çantanızı almışım. Tıpkı benimkine benziyor.'],
      ['mistake (by mistake)', 'ошибка (по ошибке)', 'помилка (помилково)', 'yanlışlık (yanlışlıkla)']),
    gap('K4', 'Unglaublich!', I.word, '', '! Ein Fahrrad, das man in zehn Sekunden zusammenfalten kann – das habe ich noch nie gesehen.', 'Unglaublich', ['Ungern', 'Ungefähr'],
      ['Unbelievable! A bicycle that you can fold up in ten seconds – I have never seen that before.', 'Невероятно! Велосипед, который складывается за десять секунд, – такого я ещё не видел.', 'Неймовірно! Велосипед, який складається за десять секунд, – такого я ще не бачив.', 'İnanılmaz! On saniyede katlanabilen bir bisiklet – bunu daha önce hiç görmemiştim.'],
      ['unbelievable', 'невероятно', 'неймовірно', 'inanılmaz']),
  ],
}

export default check
