import { I, gap, mc, sb } from '../shared.mjs'

const THERMOFLASCHE = 'Werbeanzeige: „Neu: unsere Thermoflasche für jeden Tag! Sie hält Getränke sowohl zwölf Stunden kalt als auch acht Stunden heiß. Die Flasche ist weder schwer noch empfindlich: Sie wiegt nur 250 Gramm und übersteht jeden Sturz. Alles, was Sie zum Reinigen brauchen, ist warmes Wasser. Nur diese Woche: 20 Prozent Rabatt auf alle Farben. Bestellen Sie dort, wo Sie am liebsten einkaufen – im Geschäft oder online.“'
const FALTHELM = 'Reportage: „Ein junges Team aus Dresden wollte einen Fahrradhelm entwickeln, der sich zusammenfalten lässt. Die Bank gab keinen Kredit. Also stellten die Gründer ihre Idee im Internet vor und baten um Unterstützung. Mehr als 2000 Menschen gaben kleine Beträge, zusammen fast 90 000 Euro. Wer mitmachte, bekam später einen der ersten Helme. Heute verkauft die Firma ihre Helme in zwölf Ländern.“'
const ZAHNBUERSTE = 'Kolumne: „Neulich stand ich im Elektromarkt vor einer sprechenden Zahnbürste. Sie lobt mich, wenn ich lange genug putze, und schickt die Ergebnisse an mein Handy. Brauche ich das? Früher war eine Zahnbürste etwas, was einfach nur putzt. Heute muss jedes Gerät ‚smart‘ sein. Ich habe die alte Bürste behalten. Sie redet nicht, sie braucht kein Update – und meine Zähne sind trotzdem sauber.“'
const ZWEITEILIG = 'sowohl / weder / entweder'

/** B1.2 · Pfad 3 · Werbung und Konsum – Lektionen. Wiederholung und Test: p3-check.mjs */
const path = {
  n: 3,
  slug: 'werbung-und-konsum',
  title: 'Werbung und Konsum',
  t: ['Advertising and consumption', 'Реклама и потребление', 'Реклама і споживання', 'Reklam ve tüketim'],
  objectives: {
    G1: 'Zweiteilige Konjunktion sowohl … als auch: das eine und auch das andere (Der Tee ist sowohl lecker als auch gesund).',
    G2: 'Zweiteilige Konjunktion weder … noch: das eine nicht und das andere auch nicht (Das Gerät ist weder billig noch praktisch).',
    G3: 'Relativsatz mit wo nach Ortsangaben: dort, wo …; in Köln, wo …; der Laden, wo …',
    G4: 'Relativsatz mit was nach das, alles, etwas, nichts und nach einem ganzen Satz: Das, was du suchst, …',
    G5: 'Partizip Präsens als Adjektiv: duften → duftend → der duftende Kaffee, ein hupendes Auto, lachende Kinder.',
    K1: 'Enttäuschung äußern, sich beschweren und ein Problem genauer beschreiben: Ich musste leider feststellen, dass … Es war vereinbart, dass …',
    K2: 'Mit Verständnis auf Kunden reagieren: Ich kann verstehen, dass Sie verärgert sind. Ich werde mich sofort persönlich darum kümmern.',
    K3: 'Von Pannen und Missgeschicken erzählen und darauf reagieren: Aus Versehen habe ich … Oje, wie peinlich! Das kenne ich.',
    K4: 'Ein Produkt präsentieren und Erstaunen ausdrücken: Stellen Sie sich nur vor, … Das Beste kommt noch! Wahnsinn!',
    Z1: 'Kann-Ziele: Produktwerbung, eine Reportage und eine Kolumne verstehen.',
    W1: 'Wortschatz: rund ums Produkt (Lieferung, Garantie, Reklamation, Umtausch, Kassenbon, Mangel, Rabatt, Hersteller).',
  },
  nodes: [
    {
      title: 'Rund ums Produkt',
      t: ['All about the product', 'Всё о товаре', 'Усе про товар', 'Ürünle ilgili her şey'],
      card: {
        id: 'p3_produkt',
        rule: 'Rund ums Produkt: Der Hersteller produziert die Ware, der Händler verkauft sie. Die Lieferung = die Ware wird gebracht (liefern, die Lieferzeit). Der Kassenbon oder die Quittung = der Beleg für den Kauf. Die Garantie = der Hersteller repariert oder ersetzt ein defektes Produkt kostenlos. Der Mangel = ein Fehler am Produkt. Die Reklamation = die Beschwerde über einen Mangel. Der Umtausch = Ware gegen andere Ware; das Geld erstatten = das Geld zurückgeben. Der Rabatt = der Preis wird reduziert. Der Gutschein = ein Papier oder Code mit einem Geldwert.',
        examples: ['Die Lieferung dauert drei bis fünf Werktage.', 'Auf dieses Gerät haben Sie zwei Jahre Garantie.', 'Ohne Kassenbon ist ein Umtausch leider nicht möglich.'],
        highlight: 'article',
        t: [
          'All about the product: der Hersteller (manufacturer) produces the goods, der Händler (retailer) sells them. Die Lieferung (delivery) = the goods are brought to you (liefern = to deliver, die Lieferzeit = delivery time). Der Kassenbon or die Quittung (receipt) = the proof of purchase. Die Garantie (guarantee) = the manufacturer repairs or replaces a faulty product free of charge. Der Mangel (defect) = a fault in the product. Die Reklamation = the complaint about a defect. Der Umtausch (exchange) = goods for other goods; das Geld erstatten = to refund the money. Der Rabatt (discount) = the price is reduced. Der Gutschein (voucher) = a slip of paper or a code with a cash value.',
          'Всё о товаре: der Hersteller (производитель) выпускает товар, der Händler (продавец, торговая фирма) его продаёт. Die Lieferung (доставка) = товар привозят (liefern = доставлять, die Lieferzeit = срок доставки). Der Kassenbon или die Quittung (чек, квитанция) = подтверждение покупки. Die Garantie (гарантия) = производитель бесплатно чинит или заменяет неисправный товар. Der Mangel (дефект) = недостаток товара. Die Reklamation (рекламация) = жалоба на дефект. Der Umtausch (обмен) = товар меняют на другой; das Geld erstatten = вернуть деньги. Der Rabatt (скидка) = цену снижают. Der Gutschein (подарочный сертификат) = бумага или код с денежной стоимостью.',
          'Усе про товар: der Hersteller (виробник) випускає товар, der Händler (продавець, торгова фірма) його продає. Die Lieferung (доставка) = товар привозять (liefern = доставляти, die Lieferzeit = термін доставки). Der Kassenbon або die Quittung (чек, квитанція) = підтвердження покупки. Die Garantie (гарантія) = виробник безкоштовно лагодить або замінює несправний товар. Der Mangel (дефект) = недолік товару. Die Reklamation (рекламація) = скарга на дефект. Der Umtausch (обмін) = товар міняють на інший; das Geld erstatten = повернути гроші. Der Rabatt (знижка) = ціну знижують. Der Gutschein (подарунковий сертифікат) = папір або код із грошовою вартістю.',
          'Ürünle ilgili her şey: der Hersteller (üretici) malı üretir, der Händler (satıcı) onu satar. Die Lieferung (teslimat) = malın getirilmesi (liefern = teslim etmek, die Lieferzeit = teslim süresi). Der Kassenbon ya da die Quittung (fiş, makbuz) = satın alma belgesi. Die Garantie (garanti) = üretici arızalı ürünü ücretsiz onarır ya da değiştirir. Der Mangel (kusur) = üründeki hata. Die Reklamation = bir kusurla ilgili şikâyet. Der Umtausch (değişim) = malın başka malla değiştirilmesi; das Geld erstatten = parayı iade etmek. Der Rabatt (indirim) = fiyatın düşürülmesi. Der Gutschein (hediye çeki) = para değeri olan kâğıt ya da kod.',
        ],
        hint: ['Hersteller produziert, Händler verkauft. Mangel = Fehler am Produkt. Reklamation = Beschwerde. Umtausch = andere Ware, erstatten = Geld zurück.', 'Hersteller produces, Händler sells. Mangel = fault in the product. Reklamation = complaint. Umtausch = other goods, erstatten = money back.', 'Hersteller производит, Händler продаёт. Mangel = дефект товара. Reklamation = жалоба. Umtausch = другой товар, erstatten = вернуть деньги.', 'Hersteller виробляє, Händler продає. Mangel = дефект товару. Reklamation = скарга. Umtausch = інший товар, erstatten = повернути гроші.', 'Hersteller üretir, Händler satar. Mangel = üründeki kusur. Reklamation = şikâyet. Umtausch = başka mal, erstatten = para iadesi.'],
      },
      ex: [
        mc('W1', 'Garantie', I.choose, 'Der Staubsauger ist nach acht Monaten kaputtgegangen. Zum Glück habe ich noch …', ['Garantie', 'Rabatt', 'Werbung'],
          ['The vacuum cleaner broke down after eight months. Luckily I still have a …', 'Пылесос сломался через восемь месяцев. К счастью, у меня ещё есть …', 'Пилосос зламався через вісім місяців. На щастя, у мене ще є …', 'Elektrikli süpürge sekiz ay sonra bozuldu. Neyse ki hâlâ … var.']),
        mc('W1', 'Kassenbon', I.choose, 'Wenn Sie die Ware umtauschen möchten, brauchen wir unbedingt den …', ['Kassenbon', 'Katalog', 'Hersteller'],
          ['If you would like to exchange the goods, we absolutely need the …', 'Если вы хотите обменять товар, нам обязательно нужен …', 'Якщо ви хочете обміняти товар, нам обов’язково потрібен …', 'Malı değiştirmek istiyorsanız mutlaka … gerekiyor.']),
        mc('W1', 'Reklamation', I.odd, 'Drei Wörter haben mit einer Reklamation zu tun, ein Wort nicht.', ['der Werbespot', 'der Mangel', 'der Umtausch', 'die Garantie'], null),
        mc('W1', 'Lieferzeit', I.choose, 'Das Sofa ist nicht auf Lager. Die … beträgt etwa sechs Wochen.', ['Lieferzeit', 'Öffnungszeit', 'Freizeit'],
          ['The sofa is not in stock. The … is about six weeks.', 'Дивана нет на складе. … составляет около шести недель.', 'Дивана немає на складі. … становить близько шести тижнів.', 'Koltuk stokta yok. … yaklaşık altı hafta.']),
        mc('W1', 'erstattet', I.choose, 'Die Jacke war beschädigt, deshalb hat mir das Geschäft den vollen Kaufpreis …', ['erstattet', 'erlaubt', 'erzählt'],
          ['The jacket was damaged, so the shop … the full purchase price to me.', 'Куртка была повреждена, поэтому магазин … мне полную стоимость покупки.', 'Куртка була пошкоджена, тому магазин … мені повну вартість покупки.', 'Ceket hasarlıydı, bu yüzden mağaza bana satış bedelinin tamamını … .']),
        mc('W1', 'Rabatt', I.choose, 'Weil die Waschmaschine einen kleinen Kratzer hat, bekommen Sie zehn Prozent …', ['Rabatt', 'Gehalt', 'Trinkgeld'],
          ['Because the washing machine has a small scratch, you get a ten per cent …', 'Поскольку на стиральной машине есть небольшая царапина, вы получаете десять процентов …', 'Оскільки на пральній машині є невелика подряпина, ви отримуєте десять відсотків …', 'Çamaşır makinesinde küçük bir çizik olduğu için yüzde on … alıyorsunuz.']),
        gap('W1', 'Hersteller', I.word, 'Für Ersatzteile wenden Sie sich bitte direkt an den ', ' des Geräts.', 'Hersteller', ['Vermieter', 'Besucher'],
          ['For spare parts please contact the manufacturer of the appliance directly.', 'За запасными частями обращайтесь, пожалуйста, напрямую к производителю прибора.', 'По запасні частини звертайтеся, будь ласка, безпосередньо до виробника приладу.', 'Yedek parçalar için lütfen doğrudan cihazın üreticisine başvurun.'],
          ['manufacturer', 'производитель', 'виробник', 'üretici']),
        gap('W1', 'Mangel', I.word, 'Bitte beschreiben Sie den ', ' genau: Was funktioniert an dem Gerät nicht?', 'Mangel', ['Mantel', 'Markt'],
          ['Please describe the defect precisely: what does not work on the appliance?', 'Пожалуйста, точно опишите дефект: что именно в приборе не работает?', 'Будь ласка, точно опишіть дефект: що саме в приладі не працює?', 'Lütfen kusuru tam olarak anlatın: Cihazda ne çalışmıyor?'],
          ['defect, fault', 'дефект, недостаток', 'дефект, недолік', 'kusur, arıza']),
        gap('W1', 'Gutschein', I.word, 'Zum Geburtstag habe ich einen ', ' über 50 Euro für das Sportgeschäft bekommen.', 'Gutschein', ['Geldschein', 'Führerschein'],
          ['For my birthday I got a 50-euro voucher for the sports shop.', 'На день рождения я получил подарочный сертификат на 50 евро в спортивный магазин.', 'На день народження я отримав подарунковий сертифікат на 50 євро до спортивного магазину.', 'Doğum günümde spor mağazası için 50 avroluk bir hediye çeki aldım.'],
          ['voucher', 'подарочный сертификат', 'подарунковий сертифікат', 'hediye çeki']),
        sb('W1', 'die Lieferung', I.order, 'Die Lieferung / kommt / leider / erst / nächste Woche.',
          ['Unfortunately the delivery will not come until next week.', 'К сожалению, доставка будет только на следующей неделе.', 'На жаль, доставка буде лише наступного тижня.', 'Ne yazık ki teslimat ancak gelecek hafta gelecek.'],
          { alt: ['Leider kommt die Lieferung erst nächste Woche.'] }),
      ],
    },
    {
      title: 'sowohl … als auch',
      t: ['sowohl … als auch (both … and)', 'sowohl … als auch (как …, так и …)', 'sowohl … als auch (як …, так і …)', 'sowohl … als auch (hem … hem de …)'],
      card: {
        id: 'p3_sowohl',
        rule: 'sowohl … als auch = das eine und auch das andere. Die zweiteilige Konjunktion verbindet zwei gleiche Satzteile: zwei Nomen, zwei Adjektive, zwei Verben oder zwei Angaben mit Präposition. Der Tee soll sowohl lecker schmecken als auch gute Laune machen. Wir liefern sowohl an Firmen als auch an Privatkunden. sowohl lecker als auch gesund = lecker und gesund. Ist das Subjekt zweiteilig, steht das Verb im Plural: Sowohl der Preis als auch die Qualität stimmen.',
        examples: ['Das Gerät ist sowohl leise als auch sparsam.', 'Wir beraten Sie sowohl im Geschäft als auch am Telefon.', 'Sowohl der Chef als auch die Kunden waren zufrieden.'],
        highlight: null,
        t: [
          'sowohl … als auch = both the one and the other (both … and, as well as). The two-part conjunction links two equal parts of a sentence: two nouns, two adjectives, two verbs or two phrases with a preposition. Der Tee soll sowohl lecker schmecken als auch gute Laune machen. Wir liefern sowohl an Firmen als auch an Privatkunden. sowohl lecker als auch gesund = lecker und gesund (tasty and healthy). If the subject has two parts, the verb is in the plural: Sowohl der Preis als auch die Qualität stimmen.',
          'sowohl … als auch = и то, и другое (как …, так и …). Двойной союз соединяет два одинаковых члена предложения: два существительных, два прилагательных, два глагола или два оборота с предлогом. Der Tee soll sowohl lecker schmecken als auch gute Laune machen. Wir liefern sowohl an Firmen als auch an Privatkunden. sowohl lecker als auch gesund = lecker und gesund (вкусный и полезный). Если подлежащее состоит из двух частей, глагол стоит во множественном числе: Sowohl der Preis als auch die Qualität stimmen.',
          'sowohl … als auch = і те, і інше (як …, так і …). Подвійний сполучник поєднує два однакові члени речення: два іменники, два прикметники, два дієслова або два звороти з прийменником. Der Tee soll sowohl lecker schmecken als auch gute Laune machen. Wir liefern sowohl an Firmen als auch an Privatkunden. sowohl lecker als auch gesund = lecker und gesund (смачний і корисний). Якщо підмет складається з двох частин, дієслово стоїть у множині: Sowohl der Preis als auch die Qualität stimmen.',
          'sowohl … als auch = hem biri hem öteki (hem … hem de …). Bu iki parçalı bağlaç cümlenin iki eşit ögesini bağlar: iki isim, iki sıfat, iki fiil ya da iki edatlı ifade. Der Tee soll sowohl lecker schmecken als auch gute Laune machen. Wir liefern sowohl an Firmen als auch an Privatkunden. sowohl lecker als auch gesund = lecker und gesund (lezzetli ve sağlıklı). Özne iki parçalıysa fiil çoğul olur: Sowohl der Preis als auch die Qualität stimmen.',
        ],
        hint: ['sowohl A als auch B = A und B. Zwei gleiche Satzteile. Zwei Subjekte → Verb im Plural.', 'sowohl A als auch B = A and B. Two equal parts of the sentence. Two subjects → plural verb.', 'sowohl A als auch B = A и B. Два одинаковых члена предложения. Два подлежащих → глагол во множественном числе.', 'sowohl A als auch B = A і B. Два однакові члени речення. Два підмети → дієслово в множині.', 'sowohl A als auch B = A ve B. İki eşit cümle ögesi. İki özne → fiil çoğul.'],
      },
      ex: [
        mc('G1', 'als auch', I.choose, 'Die neue Kaffeemaschine ist sowohl günstig … leicht zu bedienen.', ['als auch', 'noch', 'sondern'],
          ['The new coffee machine is both inexpensive and easy to use.', 'Новая кофемашина и недорогая, и простая в использовании.', 'Нова кавомашина і недорога, і проста у використанні.', 'Yeni kahve makinesi hem uygun fiyatlı hem de kullanımı kolay.']),
        mc('G1', 'sowohl', I.choose, 'Wir bieten … Reparaturen als auch eine kostenlose Beratung an.', ['sowohl', 'weder', 'entweder'],
          ['We offer both repairs and free advice.', 'Мы предлагаем как ремонт, так и бесплатную консультацию.', 'Ми пропонуємо як ремонт, так і безкоштовну консультацію.', 'Hem onarım hem de ücretsiz danışmanlık sunuyoruz.']),
        mc('G1', 'sowohl … als auch', I.sentence, 'Ein Satz aus einem Werbeprospekt.', ['Die Creme schützt sowohl im Sommer als auch im Winter.', 'Die Creme schützt sowohl im Sommer noch im Winter.', 'Die Creme schützt sowohl im Sommer als im Winter auch.'],
          ['A sentence from an advertising leaflet.', 'Предложение из рекламного проспекта.', 'Речення з рекламного проспекту.', 'Bir reklam broşüründen bir cümle.']),
        mc('G1', 'Bedeutung von sowohl … als auch', I.choose, 'Was bedeutet der Satz? „Der Laden verkauft sowohl neue als auch gebrauchte Fahrräder.“', ['Es gibt dort neue und gebrauchte Fahrräder.', 'Es gibt dort nur gebrauchte Fahrräder.', 'Es gibt dort keine Fahrräder mehr.'],
          ['What does this sentence mean? “The shop sells both new and second-hand bicycles.”', 'Что означает это предложение? «Магазин продаёт как новые, так и подержанные велосипеды.»', 'Що означає це речення? «Магазин продає як нові, так і вживані велосипеди.»', 'Bu cümle ne anlama geliyor? “Dükkân hem yeni hem de ikinci el bisiklet satıyor.”']),
        mc('G1', 'Verb im Plural', I.choose, 'Sowohl der Verkäufer als auch der Techniker … mir sehr freundlich geholfen.', ['haben', 'hat', 'habt'],
          ['Both the shop assistant and the technician helped me in a very friendly way.', 'И продавец, и техник очень любезно мне помогли.', 'І продавець, і технік дуже люб’язно мені допомогли.', 'Hem satıcı hem de teknisyen bana çok güler yüzlü şekilde yardım etti.']),
        mc('G1', 'als auch', I.choose, 'Sie können sowohl bar … mit Karte bezahlen.', ['als auch', 'als ob', 'aber auch'],
          ['You can pay both in cash and by card.', 'Вы можете заплатить как наличными, так и картой.', 'Ви можете заплатити як готівкою, так і карткою.', 'Hem nakit hem de kartla ödeyebilirsiniz.']),
        gap('G1', 'sowohl', I.conjunction, 'Unser Service ist ', ' schnell als auch zuverlässig.', 'sowohl', ['weder', 'entweder'],
          ['Our service is both fast and reliable.', 'Наш сервис и быстрый, и надёжный.', 'Наш сервіс і швидкий, і надійний.', 'Hizmetimiz hem hızlı hem de güvenilir.'], ZWEITEILIG),
        gap('G1', 'als auch', I.conjunction, 'Den Gutschein können Sie sowohl im Geschäft als ', ' im Onlineshop einlösen.', 'auch', ['noch', 'oder'],
          ['You can redeem the voucher both in the shop and in the online shop.', 'Сертификат можно использовать как в магазине, так и в интернет-магазине.', 'Сертифікат можна використати як у магазині, так і в інтернет-магазині.', 'Hediye çekini hem mağazada hem de internet mağazasında kullanabilirsiniz.'], 'auch / noch / oder'),
        gap('G1', 'waren', I.verb, 'Sowohl die Verpackung als auch die Anleitung ', ' leider beschädigt.', 'waren', ['war', 'wart'],
          ['Unfortunately both the packaging and the instructions were damaged.', 'К сожалению, и упаковка, и инструкция были повреждены.', 'На жаль, і упаковка, і інструкція були пошкоджені.', 'Ne yazık ki hem ambalaj hem de kullanım kılavuzu hasarlıydı.'], 'sein (Präteritum)'),
        sb('G1', 'sowohl leicht als auch robust', I.order, 'Das Handy / ist / sowohl / leicht / als auch / robust.',
          ['The phone is both light and robust.', 'Телефон и лёгкий, и прочный.', 'Телефон і легкий, і міцний.', 'Telefon hem hafif hem de sağlam.'],
          { alt: ['Das Handy ist sowohl robust als auch leicht.'] }),
      ],
    },
    {
      title: 'weder … noch',
      t: ['weder … noch (neither … nor)', 'weder … noch (ни … ни …)', 'weder … noch (ні … ні …)', 'weder … noch (ne … ne de …)'],
      card: {
        id: 'p3_weder',
        rule: 'weder … noch = das eine nicht und das andere auch nicht. Der Satz ist schon negativ – man braucht kein „nicht“ und kein „kein“: Das Gerät ist weder billig noch praktisch. Ich habe weder eine Rechnung noch eine Antwort bekommen. Der Tee ist weder lecker, noch macht er gute Laune. weder lecker noch gesund = nicht lecker und nicht gesund. Vergleiche: sowohl … als auch = beides, weder … noch = keins von beiden.',
        examples: ['Der Verkäufer war weder freundlich noch kompetent.', 'Ich habe weder Zeit noch Lust, mich zu ärgern.', 'Das Paket kam weder am Montag noch am Dienstag.'],
        highlight: null,
        t: [
          'weder … noch = not the one and not the other either (neither … nor). The sentence is already negative – you need neither “nicht” nor “kein”: Das Gerät ist weder billig noch praktisch. Ich habe weder eine Rechnung noch eine Antwort bekommen. Der Tee ist weder lecker, noch macht er gute Laune. weder lecker noch gesund = nicht lecker und nicht gesund (not tasty and not healthy). Compare: sowohl … als auch = both, weder … noch = neither of the two.',
          'weder … noch = ни то, ни другое (ни … ни …). Предложение уже отрицательное – не нужны ни «nicht», ни «kein»: Das Gerät ist weder billig noch praktisch. Ich habe weder eine Rechnung noch eine Antwort bekommen. Der Tee ist weder lecker, noch macht er gute Laune. weder lecker noch gesund = nicht lecker und nicht gesund (невкусный и неполезный). Сравните: sowohl … als auch = и то, и другое, weder … noch = ни одно из двух.',
          'weder … noch = ні те, ні інше (ні … ні …). Речення вже заперечне – не потрібні ні «nicht», ні «kein»: Das Gerät ist weder billig noch praktisch. Ich habe weder eine Rechnung noch eine Antwort bekommen. Der Tee ist weder lecker, noch macht er gute Laune. weder lecker noch gesund = nicht lecker und nicht gesund (несмачний і некорисний). Порівняйте: sowohl … als auch = і те, і інше, weder … noch = жодне з двох.',
          'weder … noch = ne biri ne de öteki (ne … ne de …). Cümle zaten olumsuzdur – “nicht” ya da “kein” gerekmez: Das Gerät ist weder billig noch praktisch. Ich habe weder eine Rechnung noch eine Antwort bekommen. Der Tee ist weder lecker, noch macht er gute Laune. weder lecker noch gesund = nicht lecker und nicht gesund (lezzetli değil ve sağlıklı değil). Karşılaştırın: sowohl … als auch = ikisi de, weder … noch = ikisinden hiçbiri.',
        ],
        hint: ['weder A noch B = nicht A und nicht B. Kein zusätzliches „nicht“ oder „kein“. Gegenteil: sowohl … als auch.', 'weder A noch B = not A and not B. No additional “nicht” or “kein”. Opposite: sowohl … als auch.', 'weder A noch B = не A и не B. Без дополнительного «nicht» или «kein». Противоположность: sowohl … als auch.', 'weder A noch B = не A і не B. Без додаткового «nicht» або «kein». Протилежність: sowohl … als auch.', 'weder A noch B = A değil, B de değil. Ayrıca “nicht” ya da “kein” kullanılmaz. Zıttı: sowohl … als auch.'],
      },
      ex: [
        mc('G2', 'noch', I.choose, 'Die Hotline ist weder am Wochenende … nach 18 Uhr erreichbar.', ['noch', 'als auch', 'oder'],
          ['The hotline can be reached neither at the weekend nor after 6 p.m.', 'На горячую линию нельзя дозвониться ни в выходные, ни после 18 часов.', 'На гарячу лінію не можна додзвонитися ні у вихідні, ні після 18-ї години.', 'Danışma hattına ne hafta sonu ne de saat 18’den sonra ulaşılabiliyor.']),
        mc('G2', 'weder', I.choose, 'Der Mixer ist … leise noch leicht zu reinigen. Ich bin wirklich enttäuscht.', ['weder', 'sowohl', 'entweder'],
          ['The blender is neither quiet nor easy to clean. I am really disappointed.', 'Блендер ни тихий, ни удобный в чистке. Я действительно разочарован.', 'Блендер ні тихий, ні зручний у чищенні. Я справді розчарований.', 'Blender ne sessiz ne de temizlemesi kolay. Gerçekten hayal kırıklığına uğradım.']),
        mc('G2', 'Bedeutung von weder … noch', I.choose, 'Was bedeutet der Satz? „Ich habe weder eine Bestätigung noch die Ware erhalten.“', ['Ich habe keine Bestätigung und keine Ware bekommen.', 'Ich habe eine Bestätigung, aber keine Ware bekommen.', 'Ich habe beides bekommen.'],
          ['What does this sentence mean? “I have received neither a confirmation nor the goods.”', 'Что означает это предложение? «Я не получил ни подтверждения, ни товара.»', 'Що означає це речення? «Я не отримав ні підтвердження, ні товару.»', 'Bu cümle ne anlama geliyor? “Ne bir onay ne de malı aldım.”']),
        mc('G2', 'ohne zweite Verneinung', I.sentence, 'Ein Kunde schreibt eine Bewertung.', ['Das Produkt ist weder haltbar noch preiswert.', 'Das Produkt ist weder nicht haltbar noch preiswert.', 'Das Produkt ist weder haltbar noch nicht preiswert.'],
          ['A customer is writing a review.', 'Клиент пишет отзыв.', 'Клієнт пише відгук.', 'Bir müşteri değerlendirme yazıyor.']),
        mc('G2', 'sowohl oder weder', I.choose, 'Der Fernseher ist ein Traum: Er hat … ein tolles Bild als auch einen guten Ton.', ['sowohl', 'weder', 'kein'],
          ['The television is a dream: it has both a great picture and good sound.', 'Телевизор – просто мечта: у него и отличная картинка, и хороший звук.', 'Телевізор – просто мрія: у нього і чудова картинка, і хороший звук.', 'Televizyon bir harika: Hem görüntüsü muhteşem hem de sesi iyi.']),
        mc('G2', 'noch', I.choose, 'Leider können wir Ihnen weder das Geld erstatten … das Gerät umtauschen, weil die Garantie abgelaufen ist.', ['noch', 'und', 'als auch'],
          ['Unfortunately we can neither refund your money nor exchange the appliance because the guarantee has expired.', 'К сожалению, мы не можем ни вернуть вам деньги, ни обменять прибор, потому что гарантия истекла.', 'На жаль, ми не можемо ні повернути вам гроші, ні обміняти прилад, бо гарантія закінчилася.', 'Garanti süresi dolduğu için ne yazık ki ne paranızı iade edebiliyoruz ne de cihazı değiştirebiliyoruz.']),
        gap('G2', 'weder', I.conjunction, 'In der Packung war ', ' eine Anleitung noch ein Ladekabel.', 'weder', ['sowohl', 'entweder'],
          ['There was neither a set of instructions nor a charging cable in the pack.', 'В упаковке не было ни инструкции, ни зарядного кабеля.', 'В упаковці не було ні інструкції, ні зарядного кабелю.', 'Paketin içinde ne kullanım kılavuzu ne de şarj kablosu vardı.'], 'weder / sowohl / entweder'),
        gap('G2', 'noch', I.conjunction, 'Der Kundendienst hat weder zurückgerufen ', ' auf meine E-Mail geantwortet.', 'noch', ['auch', 'oder'],
          ['Customer service neither called back nor replied to my e-mail.', 'Служба поддержки ни перезвонила, ни ответила на моё письмо.', 'Служба підтримки ні передзвонила, ні відповіла на мого листа.', 'Müşteri hizmetleri ne geri aradı ne de e-postama cevap verdi.'], 'noch / auch / oder'),
        gap('G2', 'weder günstig noch gut', I.conjunction, 'Das Angebot ist leider nichts für uns: Es ist ', ' günstig noch besonders gut.', 'weder', ['sowohl', 'zwar'],
          ['Unfortunately the offer is not for us: it is neither cheap nor particularly good.', 'К сожалению, это предложение нам не подходит: оно ни выгодное, ни особенно хорошее.', 'На жаль, ця пропозиція нам не підходить: вона ні вигідна, ні особливо добра.', 'Ne yazık ki bu teklif bize göre değil: Ne uygun fiyatlı ne de özellikle iyi.'], 'weder / sowohl / zwar'),
        sb('G2', 'weder Zeit noch Geld', I.order, 'Ich / habe / im Moment / weder / Zeit / noch / Geld.',
          ['At the moment I have neither time nor money.', 'Сейчас у меня нет ни времени, ни денег.', 'Зараз у мене немає ні часу, ні грошей.', 'Şu anda ne vaktim ne de param var.'],
          { alt: ['Im Moment habe ich weder Zeit noch Geld.', 'Ich habe im Moment weder Geld noch Zeit.', 'Im Moment habe ich weder Geld noch Zeit.'] }),
      ],
    },
    {
      title: 'dort, wo …',
      t: ['dort, wo … (relative clauses with wo)', 'dort, wo … (придаточные с wo)', 'dort, wo … (підрядні з wo)', 'dort, wo … (wo ile ilgi cümleleri)'],
      card: {
        id: 'p3_wo',
        rule: 'Relativsatz mit wo: Nach Ortsangaben kann man statt „in dem / in der / an dem“ einfach wo benutzen: Das ist der Laden, wo ich meine Schuhe kaufe (= in dem ich meine Schuhe kaufe). Nach Städte- und Ländernamen und nach da, dort, überall, hier steht immer wo: Ich fahre immer genau dort, wo der Stau am schlimmsten ist. In Leipzig, wo ich studiert habe, … Überall, wo man hinschaut, hängt Werbung. Das Verb steht am Ende.',
        examples: ['Das ist das Geschäft, wo es die besten Angebote gibt.', 'Wir treffen uns dort, wo wir uns immer treffen.', 'In Hamburg, wo die Firma ihren Sitz hat, arbeiten 300 Leute.'],
        highlight: 'verb',
        t: [
          'Relative clause with wo (where): after expressions of place you can simply use wo instead of “in dem / in der / an dem”: Das ist der Laden, wo ich meine Schuhe kaufe (= in dem ich meine Schuhe kaufe). After names of towns and countries and after da, dort, überall, hier you always use wo: Ich fahre immer genau dort, wo der Stau am schlimmsten ist. In Leipzig, wo ich studiert habe, … Überall, wo man hinschaut, hängt Werbung. The verb goes to the end.',
          'Придаточное определительное с wo (где): после обозначений места вместо «in dem / in der / an dem» можно просто использовать wo: Das ist der Laden, wo ich meine Schuhe kaufe (= in dem ich meine Schuhe kaufe). После названий городов и стран и после da, dort, überall, hier всегда стоит wo: Ich fahre immer genau dort, wo der Stau am schlimmsten ist. In Leipzig, wo ich studiert habe, … Überall, wo man hinschaut, hängt Werbung. Глагол стоит в конце.',
          'Підрядне означальне речення з wo (де): після позначень місця замість «in dem / in der / an dem» можна просто вжити wo: Das ist der Laden, wo ich meine Schuhe kaufe (= in dem ich meine Schuhe kaufe). Після назв міст і країн та після da, dort, überall, hier завжди стоїть wo: Ich fahre immer genau dort, wo der Stau am schlimmsten ist. In Leipzig, wo ich studiert habe, … Überall, wo man hinschaut, hängt Werbung. Дієслово стоїть у кінці.',
          'wo ile ilgi cümlesi (-diği yer): Yer bildiren ifadelerden sonra “in dem / in der / an dem” yerine yalnızca wo kullanılabilir: Das ist der Laden, wo ich meine Schuhe kaufe (= in dem ich meine Schuhe kaufe). Şehir ve ülke adlarından ve da, dort, überall, hier sözcüklerinden sonra her zaman wo gelir: Ich fahre immer genau dort, wo der Stau am schlimmsten ist. In Leipzig, wo ich studiert habe, … Überall, wo man hinschaut, hängt Werbung. Fiil sonda durur.',
        ],
        hint: ['Ort + wo: der Laden, wo …; dort, wo …; überall, wo …; in Köln, wo … Verb am Ende.', 'Place + wo: der Laden, wo …; dort, wo …; überall, wo …; in Köln, wo … Verb at the end.', 'Место + wo: der Laden, wo …; dort, wo …; überall, wo …; in Köln, wo … Глагол в конце.', 'Місце + wo: der Laden, wo …; dort, wo …; überall, wo …; in Köln, wo … Дієслово в кінці.', 'Yer + wo: der Laden, wo …; dort, wo …; überall, wo …; in Köln, wo … Fiil sonda.'],
      },
      ex: [
        mc('G3', 'dort, wo', I.choose, 'Ich kaufe mein Gemüse am liebsten dort, … es direkt vom Bauern kommt.', ['wo', 'was', 'das'],
          ['I prefer to buy my vegetables where they come straight from the farmer.', 'Овощи я охотнее всего покупаю там, где они поступают прямо от фермера.', 'Овочі я найохочіше купую там, де вони надходять просто від фермера.', 'Sebzemi en çok, doğrudan çiftçiden geldiği yerden almayı severim.']),
        mc('G3', 'in Köln, wo', I.choose, 'In Köln, … ich zehn Jahre gelebt habe, kenne ich jeden Laden.', ['wo', 'was', 'wer'],
          ['In Cologne, where I lived for ten years, I know every shop.', 'В Кёльне, где я прожил десять лет, я знаю каждый магазин.', 'У Кельні, де я прожив десять років, я знаю кожен магазин.', 'On yıl yaşadığım Köln’de her dükkânı tanırım.']),
        mc('G3', 'überall, wo', I.choose, 'Überall, … man hinschaut, hängen Plakate mit Sonderangeboten.', ['wo', 'das', 'wenn'],
          ['Wherever you look, there are posters with special offers.', 'Везде, куда ни посмотришь, висят плакаты со специальными предложениями.', 'Усюди, куди не глянеш, висять плакати зі спеціальними пропозиціями.', 'Nereye bakılsa özel indirim afişleri asılı.']),
        mc('G3', 'wo + Verb am Ende', I.sentence, 'Timur zeigt einem Freund die Stadt.', ['Das ist der Markt, wo ich jeden Samstag einkaufe.', 'Das ist der Markt, wo ich kaufe jeden Samstag ein.', 'Das ist der Markt, wo kaufe ich jeden Samstag ein.'],
          ['Timur is showing a friend round the town.', 'Timur показывает другу город.', 'Timur показує другові місто.', 'Timur bir arkadaşına şehri gezdiriyor.']),
        mc('G3', 'in der = wo', I.choose, 'Welcher Satz bedeutet dasselbe? „Das ist die Firma, in der mein Vater arbeitet.“', ['Das ist die Firma, wo mein Vater arbeitet.', 'Das ist die Firma, was mein Vater arbeitet.', 'Das ist die Firma, wer mein Vater arbeitet.'],
          ['Which sentence means the same? “That is the company in which my father works.”', 'Какое предложение означает то же самое? «Это фирма, в которой работает мой отец.»', 'Яке речення означає те саме? «Це фірма, в якій працює мій батько.»', 'Hangi cümle aynı anlama gelir? “Bu, babamın çalıştığı şirket.”']),
        mc('G3', 'da, wo', I.choose, 'Stell das Paket bitte da hin, … es niemanden stört.', ['wo', 'was', 'wie'],
          ['Please put the parcel down where it does not disturb anyone.', 'Поставь, пожалуйста, посылку туда, где она никому не мешает.', 'Постав, будь ласка, посилку туди, де вона нікому не заважає.', 'Paketi lütfen kimseyi rahatsız etmeyeceği bir yere koy.']),
        gap('G3', 'ein Dorf, wo', I.pronoun, 'Wir machen Urlaub in einem kleinen Dorf, ', ' es weder Supermärkte noch Werbung gibt.', 'wo', ['was', 'wer'],
          ['We are going on holiday to a small village where there are neither supermarkets nor advertising.', 'Мы проводим отпуск в маленькой деревне, где нет ни супермаркетов, ни рекламы.', 'Ми проводимо відпустку в маленькому селі, де немає ні супермаркетів, ні реклами.', 'Tatilimizi ne süpermarketin ne de reklamın olduğu küçük bir köyde geçiriyoruz.'], 'wo / was / wer'),
        gap('G3', 'wo … macht', I.verb, 'Das ist die Werkstatt, wo mein Bruder seine Ausbildung ', '.', 'macht', ['machen', 'gemacht'],
          ['That is the workshop where my brother is doing his training.', 'Это мастерская, где мой брат проходит обучение.', 'Це майстерня, де мій брат проходить навчання.', 'Bu, erkek kardeşimin meslek eğitimi yaptığı atölye.'], 'machen'),
        gap('G3', 'hier, wo', I.pronoun, 'Hier, ', ' früher ein kleines Kino war, steht heute ein Einkaufszentrum.', 'wo', ['was', 'wie'],
          ['Here, where there used to be a small cinema, there is a shopping centre today.', 'Здесь, где раньше был маленький кинотеатр, сегодня стоит торговый центр.', 'Тут, де раніше був маленький кінотеатр, сьогодні стоїть торговий центр.', 'Eskiden küçük bir sinemanın olduğu bu yerde bugün bir alışveriş merkezi var.'], 'wo / was / wie'),
        sb('G3', 'der Laden, wo …', I.order, 'Das ist / der Laden, / wo / ich / mein Fahrrad / gekauft habe.',
          ['That is the shop where I bought my bicycle.', 'Это магазин, где я купил свой велосипед.', 'Це магазин, де я купив свій велосипед.', 'Bu, bisikletimi aldığım dükkân.']),
      ],
    },
    {
      title: 'alles, was …',
      t: ['alles, was … (relative clauses with was)', 'alles, was … (придаточные с was)', 'alles, was … (підрядні з was)', 'alles, was … (was ile ilgi cümleleri)'],
      card: {
        id: 'p3_was',
        rule: 'Relativsatz mit was: Nach das, alles, etwas, nichts, vieles, einiges und nach einem Superlativ als Nomen (das Beste, das Einzige) steht was: Das, was du suchst, findest du im ersten Stock. Alles, was im Prospekt steht, ist reduziert. Es gibt nichts, was mich überrascht. Das ist das Beste, was mir passieren konnte. was kann sich auch auf den ganzen Satz beziehen: Die Lieferung kam pünktlich, was mich sehr gefreut hat.',
        examples: ['Das ist genau das, was ich brauche.', 'Hier gibt es nichts, was mir gefällt.', 'Er hat sich sofort entschuldigt, was ich sehr nett fand.'],
        highlight: 'verb',
        t: [
          'Relative clause with was: after das, alles (everything), etwas (something), nichts (nothing), vieles (a lot), einiges (some things) and after a superlative used as a noun (das Beste, das Einzige) you use was: Das, was du suchst, findest du im ersten Stock. Alles, was im Prospekt steht, ist reduziert. Es gibt nichts, was mich überrascht. Das ist das Beste, was mir passieren konnte. was can also refer to the whole sentence: Die Lieferung kam pünktlich, was mich sehr gefreut hat (… which pleased me very much).',
          'Придаточное определительное с was: после das, alles (всё), etwas (что-то), nichts (ничего), vieles (многое), einiges (кое-что) и после превосходной степени в роли существительного (das Beste, das Einzige) стоит was: Das, was du suchst, findest du im ersten Stock. Alles, was im Prospekt steht, ist reduziert. Es gibt nichts, was mich überrascht. Das ist das Beste, was mir passieren konnte. was может относиться и ко всему предложению: Die Lieferung kam pünktlich, was mich sehr gefreut hat (… что меня очень обрадовало).',
          'Підрядне означальне речення з was: після das, alles (усе), etwas (щось), nichts (нічого), vieles (багато чого), einiges (дещо) і після найвищого ступеня в ролі іменника (das Beste, das Einzige) стоїть was: Das, was du suchst, findest du im ersten Stock. Alles, was im Prospekt steht, ist reduziert. Es gibt nichts, was mich überrascht. Das ist das Beste, was mir passieren konnte. was може стосуватися й усього речення: Die Lieferung kam pünktlich, was mich sehr gefreut hat (… що мене дуже потішило).',
          'was ile ilgi cümlesi: das, alles (her şey), etwas (bir şey), nichts (hiçbir şey), vieles (birçok şey), einiges (bazı şeyler) sözcüklerinden ve isim olarak kullanılan üstünlük biçiminden (das Beste, das Einzige) sonra was gelir: Das, was du suchst, findest du im ersten Stock. Alles, was im Prospekt steht, ist reduziert. Es gibt nichts, was mich überrascht. Das ist das Beste, was mir passieren konnte. was bütün cümleye de gönderme yapabilir: Die Lieferung kam pünktlich, was mich sehr gefreut hat (… ki bu beni çok sevindirdi).',
        ],
        hint: ['das / alles / etwas / nichts / das Beste + was. Auch nach einem ganzen Satz: …, was mich gefreut hat. Verb am Ende.', 'das / alles / etwas / nichts / das Beste + was. Also after a whole sentence: …, was mich gefreut hat. Verb at the end.', 'das / alles / etwas / nichts / das Beste + was. Также после целого предложения: …, was mich gefreut hat. Глагол в конце.', 'das / alles / etwas / nichts / das Beste + was. Також після цілого речення: …, was mich gefreut hat. Дієслово в кінці.', 'das / alles / etwas / nichts / das Beste + was. Bütün bir cümleden sonra da: …, was mich gefreut hat. Fiil sonda.'],
      },
      ex: [
        mc('G4', 'das, was', I.choose, 'Das ist genau das, … ich schon lange gesucht habe!', ['was', 'wo', 'wer'],
          ['That is exactly what I have been looking for for a long time!', 'Это именно то, что я уже давно искал!', 'Це саме те, що я вже давно шукав!', 'Bu tam da uzun zamandır aradığım şey!']),
        mc('G4', 'alles, was', I.choose, 'Alles, … Sie in unserem Katalog sehen, können Sie auch online bestellen.', ['was', 'das', 'wo'],
          ['Everything you see in our catalogue can also be ordered online.', 'Всё, что вы видите в нашем каталоге, можно заказать и онлайн.', 'Усе, що ви бачите в нашому каталозі, можна замовити й онлайн.', 'Kataloğumuzda gördüğünüz her şeyi internetten de sipariş edebilirsiniz.']),
        mc('G4', 'nichts, was', I.choose, 'In diesem Geschäft gibt es nichts, … unter hundert Euro kostet.', ['was', 'wo', 'wie'],
          ['In this shop there is nothing that costs less than a hundred euros.', 'В этом магазине нет ничего, что стоило бы меньше ста евро.', 'У цьому магазині немає нічого, що коштувало б менше ста євро.', 'Bu mağazada yüz avrodan ucuz hiçbir şey yok.']),
        mc('G4', 'was nach einem ganzen Satz', I.choose, 'Der Verkäufer hat mir das Gerät in Ruhe erklärt, … ich sehr angenehm fand.', ['was', 'wo', 'wen'],
          ['The shop assistant explained the appliance to me calmly, which I found very pleasant.', 'Продавец спокойно объяснил мне, как работает прибор, что мне было очень приятно.', 'Продавець спокійно пояснив мені, як працює прилад, що мені було дуже приємно.', 'Satıcı cihazı bana sakin sakin anlattı; bunu çok hoş buldum.']),
        mc('G4', 'das Schönste, was', I.choose, 'Das ist das Schönste, … ich je geschenkt bekommen habe.', ['was', 'wo', 'wer'],
          ['That is the most beautiful thing I have ever been given.', 'Это самое прекрасное, что мне когда-либо дарили.', 'Це найпрекрасніше, що мені будь-коли дарували.', 'Bu, bugüne kadar bana hediye edilen en güzel şey.']),
        mc('G4', 'was + Verb am Ende', I.sentence, 'Luka ist mit seinem Kauf zufrieden.', ['Das ist das Beste, was ich je gekauft habe.', 'Das ist das Beste, was ich habe je gekauft.', 'Das ist das Beste, wo ich je gekauft habe.'],
          ['Luka is happy with his purchase.', 'Luka доволен своей покупкой.', 'Luka задоволений своєю покупкою.', 'Luka aldığı şeyden memnun.']),
        gap('G4', 'etwas, was', I.pronoun, 'Es gibt etwas, ', ' ich an dieser Werbung überhaupt nicht verstehe.', 'was', ['wo', 'wer'],
          ['There is something that I do not understand at all about this advertisement.', 'В этой рекламе есть кое-что, чего я совершенно не понимаю.', 'У цій рекламі є дещо, чого я зовсім не розумію.', 'Bu reklamda hiç anlamadığım bir şey var.'], 'was / wo / wer'),
        gap('G4', 'vieles, was', I.pronoun, 'Vieles, ', ' in der Werbung versprochen wird, stimmt in Wirklichkeit nicht.', 'was', ['wo', 'wie'],
          ['Much of what is promised in advertising is not true in reality.', 'Многое из того, что обещают в рекламе, на самом деле не соответствует действительности.', 'Багато з того, що обіцяють у рекламі, насправді не відповідає дійсності.', 'Reklamlarda vaat edilen birçok şey gerçekte doğru değil.'], 'was / wo / wie'),
        gap('G4', 'alles, was ich tun kann', I.modal, 'Das ist alles, was ich im Moment für Sie tun ', '.', 'kann', ['können', 'gekonnt'],
          ['That is all I can do for you at the moment.', 'Это всё, что я сейчас могу для вас сделать.', 'Це все, що я зараз можу для вас зробити.', 'Şu anda sizin için yapabileceğim her şey bu.'], 'können'),
        sb('G4', 'alles, was …', I.order, 'Das ist / alles, / was / ich / dazu / sagen kann.',
          ['That is all I can say about it.', 'Это всё, что я могу об этом сказать.', 'Це все, що я можу про це сказати.', 'Bu konuda söyleyebileceğim her şey bu.']),
      ],
    },
    {
      title: 'der duftende Kaffee',
      t: ['der duftende Kaffee (present participle as adjective)', 'der duftende Kaffee (Partizip Präsens как прилагательное)', 'der duftende Kaffee (Partizip Präsens як прикметник)', 'der duftende Kaffee (sıfat olarak Partizip Präsens)'],
      card: {
        id: 'p3_partizip_praesens',
        rule: 'Partizip Präsens als Adjektiv: Infinitiv + d = Partizip Präsens: duften → duftend, lachen → lachend, klingeln → klingelnd, wohltun → wohltuend. Es beschreibt, was gerade passiert. Vor einem Nomen bekommt es die normale Adjektivendung: der duftende Kaffee, ein duftender Kaffee, das hupende Auto, ein hupendes Auto, die sprechende Puppe, eine sprechende Puppe, die leuchtenden Schuhe, leuchtende Schuhe. Die lachenden Kinder = die Kinder, die lachen.',
        examples: ['Der duftende Kaffee weckt mich jeden Morgen.', 'Ein klingelndes Handy stört in jeder Besprechung.', 'In der Werbung sieht man immer lachende Familien.'],
        highlight: null,
        t: [
          'Present participle as an adjective: infinitive + d = Partizip Präsens: duften → duftend (fragrant, smelling good), lachen → lachend (laughing), klingeln → klingelnd (ringing), wohltun → wohltuend (soothing). It describes what is happening right now. Before a noun it takes the normal adjective ending: der duftende Kaffee, ein duftender Kaffee, das hupende Auto, ein hupendes Auto, die sprechende Puppe, eine sprechende Puppe, die leuchtenden Schuhe, leuchtende Schuhe. Die lachenden Kinder = die Kinder, die lachen (the children who are laughing).',
          'Partizip Präsens как прилагательное: инфинитив + d = Partizip Präsens: duften → duftend (ароматный, пахнущий), lachen → lachend (смеющийся), klingeln → klingelnd (звонящий), wohltun → wohltuend (благотворный, приятный). Оно описывает то, что происходит прямо сейчас. Перед существительным оно получает обычное окончание прилагательного: der duftende Kaffee, ein duftender Kaffee, das hupende Auto, ein hupendes Auto, die sprechende Puppe, eine sprechende Puppe, die leuchtenden Schuhe, leuchtende Schuhe. Die lachenden Kinder = die Kinder, die lachen (дети, которые смеются).',
          'Partizip Präsens як прикметник: інфінітив + d = Partizip Präsens: duften → duftend (запашний), lachen → lachend (той, що сміється), klingeln → klingelnd (той, що дзвонить), wohltun → wohltuend (благотворний, приємний). Воно описує те, що відбувається саме зараз. Перед іменником воно отримує звичайне закінчення прикметника: der duftende Kaffee, ein duftender Kaffee, das hupende Auto, ein hupendes Auto, die sprechende Puppe, eine sprechende Puppe, die leuchtenden Schuhe, leuchtende Schuhe. Die lachenden Kinder = die Kinder, die lachen (діти, які сміються).',
          'Sıfat olarak Partizip Präsens: mastar + d = Partizip Präsens: duften → duftend (mis kokan), lachen → lachend (gülen), klingeln → klingelnd (çalan), wohltun → wohltuend (iyi gelen, rahatlatan). O anda olan şeyi anlatır. İsimden önce normal sıfat ekini alır: der duftende Kaffee, ein duftender Kaffee, das hupende Auto, ein hupendes Auto, die sprechende Puppe, eine sprechende Puppe, die leuchtenden Schuhe, leuchtende Schuhe. Die lachenden Kinder = die Kinder, die lachen (gülen çocuklar).',
        ],
        hint: ['Infinitiv + d: lachend, duftend, hupend. Vor dem Nomen mit Adjektivendung: der duftende Kaffee, ein hupendes Auto, lachende Kinder.', 'Infinitive + d: lachend, duftend, hupend. Before the noun with an adjective ending: der duftende Kaffee, ein hupendes Auto, lachende Kinder.', 'Инфинитив + d: lachend, duftend, hupend. Перед существительным с окончанием прилагательного: der duftende Kaffee, ein hupendes Auto, lachende Kinder.', 'Інфінітив + d: lachend, duftend, hupend. Перед іменником із закінченням прикметника: der duftende Kaffee, ein hupendes Auto, lachende Kinder.', 'Mastar + d: lachend, duftend, hupend. İsimden önce sıfat ekiyle: der duftende Kaffee, ein hupendes Auto, lachende Kinder.'],
      },
      ex: [
        mc('G5', 'lachende Menschen', I.choose, 'In der Werbung sieht man fast immer … Menschen.', ['lachende', 'lachend', 'gelachte'],
          ['In advertising you almost always see laughing people.', 'В рекламе почти всегда видишь смеющихся людей.', 'У рекламі майже завжди бачиш людей, які сміються.', 'Reklamlarda neredeyse her zaman gülen insanlar görülür.']),
        mc('G5', 'Bildung: leuchtend', I.choose, 'Wie heißt das Partizip Präsens von „leuchten“?', ['leuchtend', 'geleuchtet', 'leuchtet'],
          ['What is the present participle of “leuchten” (to shine, to glow)?', 'Как образуется Partizip Präsens от «leuchten» (светиться)?', 'Як утворюється Partizip Präsens від «leuchten» (світитися)?', '“Leuchten” (parlamak, ışık vermek) fiilinin Partizip Präsens biçimi nedir?']),
        mc('G5', 'ein wohltuender Tee', I.choose, 'Ein … Tee am Abend hilft mir, mich zu entspannen.', ['wohltuender', 'wohltuende', 'wohltuend'],
          ['A soothing tea in the evening helps me to relax.', 'Приятный успокаивающий чай вечером помогает мне расслабиться.', 'Приємний заспокійливий чай увечері допомагає мені розслабитися.', 'Akşamları içimi rahatlatan bir çay gevşememe yardımcı oluyor.']),
        mc('G5', 'das hupende Auto', I.choose, 'Das … Auto hinter uns macht mich ganz nervös.', ['hupende', 'hupender', 'hupenden'],
          ['The car hooting behind us is making me really nervous.', 'Сигналящая машина позади нас очень меня нервирует.', 'Машина, що сигналить позаду нас, дуже мене нервує.', 'Arkamızda korna çalan araba beni çok geriyor.']),
        mc('G5', 'Bedeutung: die steigenden Preise', I.choose, 'Was bedeutet „die steigenden Preise“?', ['Die Preise, die steigen.', 'Die Preise, die gestiegen sind.', 'Die Preise, die sinken.'],
          ['What does “die steigenden Preise” (the rising prices) mean?', 'Что означает «die steigenden Preise» (растущие цены)?', 'Що означає «die steigenden Preise» (ціни, що зростають)?', '“Die steigenden Preise” (yükselen fiyatlar) ne anlama geliyor?']),
        mc('G5', 'mit einem schreienden Kind', I.choose, 'Mit einem … Kind auf dem Arm kann man schlecht einkaufen.', ['schreienden', 'schreiende', 'schreiender'],
          ['It is hard to go shopping with a screaming child in your arms.', 'С кричащим ребёнком на руках трудно делать покупки.', 'З дитиною, що кричить, на руках важко робити покупки.', 'Kucağınızda bağıran bir çocukla alışveriş yapmak zordur.']),
        gap('G5', 'mit dem leuchtenden Display', I.ending, 'Der Wecker mit dem ', ' Display kostet nur 15 Euro.', 'leuchtenden', ['leuchtende', 'leuchtender'],
          ['The alarm clock with the illuminated display costs only 15 euros.', 'Будильник со светящимся дисплеем стоит всего 15 евро.', 'Будильник із дисплеєм, що світиться, коштує лише 15 євро.', 'Işıklı ekranı olan çalar saat yalnızca 15 avro.'], 'leuchten'),
        gap('G5', 'einen Deutsch sprechenden Verkäufer', I.ending, 'Für unsere Filiale suchen wir einen gut Deutsch ', ' Verkäufer.', 'sprechenden', ['sprechende', 'sprechender'],
          ['For our branch we are looking for a salesman who speaks German well.', 'Для нашего филиала мы ищем продавца, хорошо говорящего по-немецки.', 'Для нашої філії ми шукаємо продавця, який добре розмовляє німецькою.', 'Şubemiz için iyi Almanca konuşan bir satış elemanı arıyoruz.'], 'sprechen'),
        gap('G5', 'eine singende Kartoffel', I.ending, 'Im Werbespot tanzt eine ', ' Kartoffel durch die Küche.', 'singende', ['singenden', 'singender'],
          ['In the commercial a singing potato dances through the kitchen.', 'В рекламном ролике поющая картофелина танцует по кухне.', 'У рекламному ролику картоплина, що співає, танцює кухнею.', 'Reklam filminde şarkı söyleyen bir patates mutfakta dans ediyor.'], 'singen'),
        sb('G5', 'der duftende Kaffee', I.order, 'Der duftende Kaffee / weckt / mich / jeden Morgen.',
          ['The fragrant coffee wakes me up every morning.', 'Ароматный кофе будит меня каждое утро.', 'Запашна кава будить мене щоранку.', 'Mis kokulu kahve beni her sabah uyandırıyor.'],
          { alt: ['Jeden Morgen weckt mich der duftende Kaffee.', 'Mich weckt jeden Morgen der duftende Kaffee.'] }),
      ],
    },
    {
      title: 'Sich beschweren',
      t: ['Making a complaint', 'Как пожаловаться', 'Як поскаржитися', 'Şikâyet etmek'],
      card: {
        id: 'p3_beschwerde',
        rule: 'Sich beschweren. Enttäuschung zeigen: Ich bin wirklich sehr verärgert / enttäuscht. Also, ich muss sagen, das hat mich schon etwas enttäuscht. Sich beschweren: Das geht doch nicht. Das kann man doch nicht machen. Das Problem genauer beschreiben: Dazu möchte ich noch anmerken, dass … Ich musste leider feststellen, dass … Es war abgemacht / vereinbart, dass … Das Hauptproblem war, … Bleib sachlich: Sag, was passiert ist und was du jetzt erwartest.',
        examples: ['Ich musste leider feststellen, dass das Gerät nicht funktioniert.', 'Es war vereinbart, dass die Lieferung am Montag kommt.', 'Also, ich muss sagen, das hat mich schon sehr enttäuscht.'],
        highlight: null,
        t: [
          'Making a complaint. Showing disappointment: Ich bin wirklich sehr verärgert / enttäuscht (I am really very annoyed / disappointed). Also, ich muss sagen, das hat mich schon etwas enttäuscht (Well, I must say that did disappoint me somewhat). Complaining: Das geht doch nicht (That really will not do). Das kann man doch nicht machen (You cannot do that). Describing the problem more precisely: Dazu möchte ich noch anmerken, dass … (I would like to add that …). Ich musste leider feststellen, dass … (Unfortunately I found that …). Es war abgemacht / vereinbart, dass … (It was agreed that …). Das Hauptproblem war, … (The main problem was …). Stay factual: say what happened and what you expect now.',
          'Как пожаловаться. Выразить разочарование: Ich bin wirklich sehr verärgert / enttäuscht (я действительно очень рассержен / разочарован). Also, ich muss sagen, das hat mich schon etwas enttäuscht (должен сказать, это меня несколько разочаровало). Пожаловаться: Das geht doch nicht (так нельзя). Das kann man doch nicht machen (так поступать нельзя). Точнее описать проблему: Dazu möchte ich noch anmerken, dass … (к этому хочу добавить, что …). Ich musste leider feststellen, dass … (к сожалению, я обнаружил, что …). Es war abgemacht / vereinbart, dass … (было договорено, что …). Das Hauptproblem war, … (главная проблема была в том, что …). Оставайтесь корректным: скажите, что произошло и чего вы теперь ожидаете.',
          'Як поскаржитися. Висловити розчарування: Ich bin wirklich sehr verärgert / enttäuscht (я справді дуже розсерджений / розчарований). Also, ich muss sagen, das hat mich schon etwas enttäuscht (мушу сказати, це мене дещо розчарувало). Поскаржитися: Das geht doch nicht (так не можна). Das kann man doch nicht machen (так чинити не можна). Точніше описати проблему: Dazu möchte ich noch anmerken, dass … (до цього хочу додати, що …). Ich musste leider feststellen, dass … (на жаль, я виявив, що …). Es war abgemacht / vereinbart, dass … (було домовлено, що …). Das Hauptproblem war, … (головна проблема була в тому, що …). Залишайтеся коректним: скажіть, що сталося і чого ви тепер очікуєте.',
          'Şikâyet etmek. Hayal kırıklığını göstermek: Ich bin wirklich sehr verärgert / enttäuscht (gerçekten çok kızgınım / hayal kırıklığına uğradım). Also, ich muss sagen, das hat mich schon etwas enttäuscht (doğrusu bu beni biraz hayal kırıklığına uğrattı). Şikâyet etmek: Das geht doch nicht (bu böyle olmaz). Das kann man doch nicht machen (böyle bir şey yapılmaz). Sorunu daha ayrıntılı anlatmak: Dazu möchte ich noch anmerken, dass … (buna şunu da eklemek isterim: …). Ich musste leider feststellen, dass … (ne yazık ki şunu fark ettim: …). Es war abgemacht / vereinbart, dass … (… diye anlaşmıştık). Das Hauptproblem war, … (asıl sorun şuydu: …). Nesnel kalın: Ne olduğunu ve şimdi ne beklediğinizi söyleyin.',
        ],
        hint: ['Beschwerde: Ich musste leider feststellen, dass … / Es war vereinbart, dass … / Das geht doch nicht. Sachlich bleiben.', 'Complaint: Ich musste leider feststellen, dass … / Es war vereinbart, dass … / Das geht doch nicht. Stay factual.', 'Жалоба: Ich musste leider feststellen, dass … / Es war vereinbart, dass … / Das geht doch nicht. Оставаться корректным.', 'Скарга: Ich musste leider feststellen, dass … / Es war vereinbart, dass … / Das geht doch nicht. Залишатися коректним.', 'Şikâyet: Ich musste leider feststellen, dass … / Es war vereinbart, dass … / Das geht doch nicht. Nesnel kalın.'],
      },
      ex: [
        mc('K1', 'Beschwerde beginnen', I.situation, 'Du hast einen Laptop bestellt. Geliefert wurde ein anderes Modell. Wie beginnst du deine Beschwerde am Telefon?', ['Guten Tag, ich musste leider feststellen, dass Sie mir das falsche Modell geschickt haben.', 'Sie haben ja wohl keine Ahnung von Ihrer Arbeit!', 'Hallo, ich möchte einen Laptop bestellen.'],
          ['You ordered a laptop. A different model was delivered. How do you begin your complaint on the phone?', 'Вы заказали ноутбук. Доставили другую модель. Как вы начнёте жалобу по телефону?', 'Ви замовили ноутбук. Доставили іншу модель. Як ви почнете скаргу телефоном?', 'Bir dizüstü bilgisayar sipariş ettiniz. Başka bir model teslim edildi. Telefonda şikâyetinize nasıl başlarsınız?']),
        mc('K1', 'abgemacht', I.choose, 'Es war …, dass der Monteur am Dienstag kommt. Aber niemand ist erschienen.', ['abgemacht', 'abgeholt', 'abgelaufen'],
          ['It was … that the fitter would come on Tuesday. But nobody turned up.', 'Было …, что монтёр придёт во вторник. Но никто не появился.', 'Було …, що монтер прийде у вівторок. Але ніхто не з’явився.', 'Tesisatçının salı günü geleceği … . Ama kimse gelmedi.']),
        mc('K1', 'anmerken', I.choose, 'Dazu möchte ich noch …, dass ich schon dreimal bei Ihrer Hotline angerufen habe.', ['anmerken', 'anmelden', 'anziehen'],
          ['I would also like to … that I have already called your hotline three times.', 'К этому я хотел бы ещё …, что уже трижды звонил на вашу горячую линию.', 'До цього я хотів би ще …, що вже тричі телефонував на вашу гарячу лінію.', 'Buna şunu da … isterim: Danışma hattınızı üç kez aradım.']),
        mc('K1', 'Ich möchte mich beschweren.', I.react, '„Guten Tag, was kann ich für Sie tun?“', ['Ich möchte mich beschweren: Die Waschmaschine, die Sie letzte Woche geliefert haben, ist schon kaputt.', 'Unglaublich! Das ist ja nicht zu glauben.', 'Oje, wie peinlich!'],
          ['“Good afternoon, what can I do for you?”', '«Добрый день, чем я могу вам помочь?»', '«Добрий день, чим я можу вам допомогти?»', '“İyi günler, sizin için ne yapabilirim?”']),
        mc('K1', 'Das geht doch nicht!', I.choose, 'Drei Wochen Wartezeit für eine einfache Reparatur? Das … doch nicht!', ['geht', 'kommt', 'läuft'],
          ['A three-week wait for a simple repair? That really will not do!', 'Три недели ожидания ради простого ремонта? Так же нельзя!', 'Три тижні очікування заради простого ремонту? Так же не можна!', 'Basit bir onarım için üç hafta beklemek mi? Bu böyle olmaz!']),
        mc('K1', 'sachlich bleiben', I.choose, 'Welcher Satz ist eine sachliche Beschwerde?', ['Das Hauptproblem war, dass niemand für meine Frage zuständig war.', 'Bei Ihnen arbeiten nur unfähige Leute!', 'Ihre Firma ist die schlechteste der Welt!'],
          ['Which sentence is a factual complaint?', 'Какое предложение – корректная жалоба по существу?', 'Яке речення – коректна скарга по суті?', 'Hangi cümle nesnel bir şikâyettir?']),
        gap('K1', 'enttäuscht', I.word, 'Ich bin wirklich sehr ', ': Der Tisch hat einen Kratzer, und ein Stuhl fehlt ganz.', 'enttäuscht', ['entspannt', 'entschuldigt'],
          ['I am really very disappointed: the table has a scratch and one chair is missing altogether.', 'Я действительно очень разочарован: на столе царапина, а одного стула вообще нет.', 'Я справді дуже розчарований: на столі подряпина, а одного стільця взагалі немає.', 'Gerçekten çok hayal kırıklığına uğradım: Masada bir çizik var, bir sandalye ise hiç yok.'],
          ['disappointed', 'разочарован', 'розчарований', 'hayal kırıklığına uğramış']),
        gap('K1', 'feststellen', I.word, 'Ich musste leider ', ', dass in dem Paket nur die Hälfte der bestellten Ware war.', 'feststellen', ['festhalten', 'bestellen'],
          ['Unfortunately I found that the parcel contained only half of the goods I ordered.', 'К сожалению, я обнаружил, что в посылке была только половина заказанного товара.', 'На жаль, я виявив, що в посилці була лише половина замовленого товару.', 'Ne yazık ki pakette sipariş edilen malın yalnızca yarısı olduğunu fark ettim.'],
          ['to find, to notice', 'обнаружить, установить', 'виявити, з’ясувати', 'fark etmek, tespit etmek']),
        gap('K1', 'vereinbart', I.word, 'Es war ', ', dass Sie mich zurückrufen. Ich warte jetzt seit einer Woche.', 'vereinbart', ['verboten', 'verkauft'],
          ['It was agreed that you would call me back. I have now been waiting for a week.', 'Было договорено, что вы мне перезвоните. Я жду уже неделю.', 'Було домовлено, що ви мені передзвоните. Я чекаю вже тиждень.', 'Beni geri arayacağınız kararlaştırılmıştı. Bir haftadır bekliyorum.'],
          ['agreed', 'договорено', 'домовлено', 'kararlaştırılmış']),
        sb('K1', 'Das kann man doch nicht machen!', I.order, 'Das / kann / man / doch / nicht / machen!',
          ['You really cannot do that!', 'Так ведь нельзя поступать!', 'Так же не можна чинити!', 'Böyle bir şey yapılmaz ki!']),
      ],
    },
    {
      title: 'Auf Beschwerden reagieren',
      t: ['Responding to complaints', 'Как реагировать на жалобы', 'Як реагувати на скарги', 'Şikâyetlere yanıt vermek'],
      card: {
        id: 'p3_kundenservice',
        rule: 'Mit Verständnis auf Kunden reagieren: Ich kann verstehen, dass Sie enttäuscht / verärgert sind. Selbstverständlich, das ist überhaupt kein Problem. Ach wirklich? Das ist wirklich sehr ärgerlich. Oh, das tut mir leid. Da sehe ich leider nur eine Möglichkeit: … Ich werde mich sofort persönlich darum kümmern. Gute Kundenberater hören zu, entschuldigen sich und bieten eine Lösung an: reparieren, umtauschen oder das Geld erstatten.',
        examples: ['Ich kann verstehen, dass Sie verärgert sind.', 'Oh, das tut mir leid. Wir tauschen das Gerät selbstverständlich um.', 'Ich werde mich sofort persönlich darum kümmern.'],
        highlight: null,
        t: [
          'Responding to customers with understanding: Ich kann verstehen, dass Sie enttäuscht / verärgert sind (I can understand that you are disappointed / annoyed). Selbstverständlich, das ist überhaupt kein Problem (Of course, that is no problem at all). Ach wirklich? Das ist wirklich sehr ärgerlich (Oh really? That is very annoying indeed). Oh, das tut mir leid (Oh, I am sorry). Da sehe ich leider nur eine Möglichkeit: … (I am afraid I see only one option: …). Ich werde mich sofort persönlich darum kümmern (I will see to it personally at once). Good customer advisers listen, apologise and offer a solution: repair, exchange or refund.',
          'Как с пониманием реагировать на клиентов: Ich kann verstehen, dass Sie enttäuscht / verärgert sind (я понимаю, что вы разочарованы / рассержены). Selbstverständlich, das ist überhaupt kein Problem (разумеется, это вообще не проблема). Ach wirklich? Das ist wirklich sehr ärgerlich (правда? Это действительно очень досадно). Oh, das tut mir leid (о, мне жаль). Da sehe ich leider nur eine Möglichkeit: … (к сожалению, я вижу только одну возможность: …). Ich werde mich sofort persönlich darum kümmern (я сейчас же лично этим займусь). Хорошие консультанты слушают, извиняются и предлагают решение: починить, обменять или вернуть деньги.',
          'Як із розумінням реагувати на клієнтів: Ich kann verstehen, dass Sie enttäuscht / verärgert sind (я розумію, що ви розчаровані / розсерджені). Selbstverständlich, das ist überhaupt kein Problem (звісно, це взагалі не проблема). Ach wirklich? Das ist wirklich sehr ärgerlich (справді? Це дійсно дуже прикро). Oh, das tut mir leid (о, мені шкода). Da sehe ich leider nur eine Möglichkeit: … (на жаль, я бачу лише одну можливість: …). Ich werde mich sofort persönlich darum kümmern (я зараз же особисто цим займуся). Добрі консультанти слухають, вибачаються і пропонують рішення: полагодити, обміняти або повернути гроші.',
          'Müşterilere anlayışla karşılık vermek: Ich kann verstehen, dass Sie enttäuscht / verärgert sind (hayal kırıklığına uğramanızı / kızmanızı anlıyorum). Selbstverständlich, das ist überhaupt kein Problem (elbette, bu hiç sorun değil). Ach wirklich? Das ist wirklich sehr ärgerlich (öyle mi? Bu gerçekten çok can sıkıcı). Oh, das tut mir leid (ah, üzgünüm). Da sehe ich leider nur eine Möglichkeit: … (maalesef yalnızca bir seçenek görüyorum: …). Ich werde mich sofort persönlich darum kümmern (bununla hemen bizzat ilgileneceğim). İyi müşteri temsilcileri dinler, özür diler ve bir çözüm sunar: onarmak, değiştirmek ya da parayı iade etmek.',
        ],
        hint: ['Kundenservice: Ich kann verstehen, dass … / Das tut mir leid. / Selbstverständlich. / Ich kümmere mich sofort darum. Dann eine Lösung anbieten.', 'Customer service: Ich kann verstehen, dass … / Das tut mir leid. / Selbstverständlich. / Ich kümmere mich sofort darum. Then offer a solution.', 'Служба поддержки: Ich kann verstehen, dass … / Das tut mir leid. / Selbstverständlich. / Ich kümmere mich sofort darum. Затем предложить решение.', 'Служба підтримки: Ich kann verstehen, dass … / Das tut mir leid. / Selbstverständlich. / Ich kümmere mich sofort darum. Потім запропонувати рішення.', 'Müşteri hizmetleri: Ich kann verstehen, dass … / Das tut mir leid. / Selbstverständlich. / Ich kümmere mich sofort darum. Ardından bir çözüm sunun.'],
      },
      ex: [
        mc('K2', 'sich darum kümmern', I.react, '„Ich warte seit drei Wochen auf mein Paket!“', ['Das tut mir sehr leid. Ich werde mich sofort persönlich darum kümmern.', 'Da haben Sie wohl Pech gehabt.', 'Wahnsinn! Unser Produkt ist einfach super!'],
          ['“I have been waiting for my parcel for three weeks!”', '«Я уже три недели жду свою посылку!»', '«Я вже три тижні чекаю на свою посилку!»', '“Üç haftadır paketimi bekliyorum!”']),
        mc('K2', 'Selbstverständlich', I.situation, 'Du arbeitest im Kundenservice. Ein Kunde möchte einen defekten Toaster umtauschen und hat den Kassenbon dabei. Was sagst du?', ['Selbstverständlich, das ist überhaupt kein Problem.', 'Das geht doch nicht!', 'Ich bin wirklich sehr enttäuscht.'],
          ['You work in customer service. A customer wants to exchange a faulty toaster and has the receipt with him. What do you say?', 'Вы работаете в службе поддержки. Клиент хочет обменять неисправный тостер, и у него с собой чек. Что вы скажете?', 'Ви працюєте у службі підтримки. Клієнт хоче обміняти несправний тостер і має із собою чек. Що ви скажете?', 'Müşteri hizmetlerinde çalışıyorsunuz. Bir müşteri arızalı bir ekmek kızartma makinesini değiştirmek istiyor ve fişi yanında. Ne dersiniz?']),
        mc('K2', 'verstehen', I.choose, 'Ich kann …, dass Sie verärgert sind. So etwas darf natürlich nicht passieren.', ['verstehen', 'versprechen', 'verkaufen'],
          ['I can … that you are annoyed. Of course something like this must not happen.', 'Я могу …, что вы рассержены. Такого, конечно, не должно происходить.', 'Я можу …, що ви розсерджені. Такого, звісно, не повинно траплятися.', 'Kızgın olmanızı … . Elbette böyle bir şey olmamalı.']),
        mc('K2', 'eine Möglichkeit', I.choose, 'Die Garantie ist leider abgelaufen. Da sehe ich nur eine …: Wir können das Gerät gegen Bezahlung reparieren.', ['Möglichkeit', 'Müdigkeit', 'Mehrheit'],
          ['Unfortunately the guarantee has expired. I see only one …: we can repair the appliance for a fee.', 'К сожалению, гарантия истекла. Я вижу только одну …: мы можем починить прибор за плату.', 'На жаль, гарантія закінчилася. Я бачу лише одну …: ми можемо полагодити прилад за плату.', 'Ne yazık ki garanti süresi dolmuş. Yalnızca bir … görüyorum: Cihazı ücret karşılığında onarabiliriz.']),
        mc('K2', 'Das ist sehr ärgerlich.', I.react, '„Der Pullover ist nach dem ersten Waschen eingelaufen.“', ['Ach wirklich? Das ist wirklich sehr ärgerlich. Haben Sie den Kassenbon noch?', 'Das habe ich mir fest vorgenommen.', 'Das Beste kommt noch!'],
          ['“The jumper shrank after the first wash.”', '«Свитер сел после первой же стирки.»', '«Светр збігся після першого ж прання.»', '“Kazak ilk yıkamada çekti.”']),
        mc('K2', 'darum', I.choose, 'Ich werde mich sofort persönlich … kümmern und Sie noch heute zurückrufen.', ['darum', 'daran', 'darauf'],
          ['I will see to it personally at once and call you back today.', 'Я сейчас же лично этим займусь и перезвоню вам ещё сегодня.', 'Я зараз же особисто цим займуся і передзвоню вам ще сьогодні.', 'Bununla hemen bizzat ilgileneceğim ve sizi bugün içinde geri arayacağım.']),
        gap('K2', 'ärgerlich', I.word, 'Das ist wirklich sehr ', '. Ich verstehe gut, dass Sie sich beschweren.', 'ärgerlich', ['ängstlich', 'ähnlich'],
          ['That is very annoying indeed. I quite understand that you are complaining.', 'Это действительно очень досадно. Я хорошо понимаю, почему вы жалуетесь.', 'Це справді дуже прикро. Я добре розумію, чому ви скаржитеся.', 'Bu gerçekten çok can sıkıcı. Şikâyet etmenizi çok iyi anlıyorum.'],
          ['annoying', 'досадный, неприятный', 'прикрий, неприємний', 'can sıkıcı']),
        gap('K2', 'erstatten', I.word, 'Selbstverständlich ', ' wir Ihnen den Kaufpreis, wenn Sie das Gerät zurückschicken.', 'erstatten', ['erwarten', 'erkälten'],
          ['Of course we will refund the purchase price if you send the appliance back.', 'Разумеется, мы вернём вам стоимость покупки, если вы отправите прибор обратно.', 'Звісно, ми повернемо вам вартість покупки, якщо ви надішлете прилад назад.', 'Cihazı geri gönderirseniz satış bedelini elbette size iade ederiz.'],
          ['to refund', 'возместить, вернуть (деньги)', 'відшкодувати, повернути (гроші)', 'iade etmek']),
        gap('K2', 'persönlich', I.word, 'Ich werde mich sofort ', ' darum kümmern. Sie müssen nichts weiter tun.', 'persönlich', ['pünktlich', 'peinlich'],
          ['I will see to it personally at once. You do not need to do anything else.', 'Я сейчас же лично этим займусь. Вам больше ничего не нужно делать.', 'Я зараз же особисто цим займуся. Вам більше нічого не треба робити.', 'Bununla hemen bizzat ilgileneceğim. Sizin başka bir şey yapmanıza gerek yok.'],
          ['personally', 'лично', 'особисто', 'şahsen, bizzat']),
        sb('K2', 'Ich kann verstehen, dass …', I.order, 'Ich / kann / verstehen, / dass / Sie / enttäuscht / sind.',
          ['I can understand that you are disappointed.', 'Я понимаю, что вы разочарованы.', 'Я розумію, що ви розчаровані.', 'Hayal kırıklığına uğramanızı anlayabiliyorum.']),
      ],
    },
    {
      title: 'Pannen und Missgeschicke',
      t: ['Mishaps and blunders', 'Накладки и оплошности', 'Накладки і прикрі випадки', 'Aksilikler ve talihsizlikler'],
      card: {
        id: 'p3_pannen',
        rule: 'Von Pannen und Missgeschicken erzählen: Stell dir vor, was mir passiert ist! Ich habe mal eine Nachricht abgeschickt, die für jemand anderen war. Aus Versehen = ohne Absicht. Das Missgeschick = ein kleines Unglück. Die Panne = etwas geht schief. peinlich = man schämt sich. Darauf reagieren: Oje, wie peinlich! Das kenne ich. Das ist mir auch schon passiert. Da hast du später bestimmt noch oft darüber gelacht, oder?',
        examples: ['Ich habe aus Versehen die falsche Datei verschickt.', 'Oje, wie peinlich! Und was hat dein Chef gesagt?', 'Das kenne ich. Das ist mir auch schon passiert.'],
        highlight: null,
        t: [
          'Talking about mishaps and blunders: Stell dir vor, was mir passiert ist! (Just imagine what happened to me!) Ich habe mal eine Nachricht abgeschickt, die für jemand anderen war (I once sent a message that was meant for someone else). Aus Versehen = by mistake, unintentionally. Das Missgeschick = a small mishap. Die Panne = something goes wrong. peinlich = embarrassing. Reacting: Oje, wie peinlich! (Oh dear, how embarrassing!) Das kenne ich (I know that). Das ist mir auch schon passiert (That has happened to me too). Da hast du später bestimmt noch oft darüber gelacht, oder? (You must have laughed about it many times afterwards, right?)',
          'Как рассказать о накладках и оплошностях: Stell dir vor, was mir passiert ist! (Представь, что со мной случилось!) Ich habe mal eine Nachricht abgeschickt, die für jemand anderen war (однажды я отправил сообщение, которое предназначалось другому человеку). Aus Versehen = по ошибке, нечаянно. Das Missgeschick = небольшая неприятность. Die Panne = что-то идёт не так. peinlich = неловко, стыдно. Как реагировать: Oje, wie peinlich! (Ой, как неловко!) Das kenne ich (мне это знакомо). Das ist mir auch schon passiert (со мной такое тоже случалось). Da hast du später bestimmt noch oft darüber gelacht, oder? (Потом ты наверняка ещё не раз над этим смеялся, да?)',
          'Як розповісти про накладки і прикрі випадки: Stell dir vor, was mir passiert ist! (Уяви, що зі мною сталося!) Ich habe mal eine Nachricht abgeschickt, die für jemand anderen war (якось я надіслав повідомлення, яке було призначене іншій людині). Aus Versehen = помилково, ненавмисно. Das Missgeschick = невелика прикрість. Die Panne = щось іде не так. peinlich = ніяково, соромно. Як реагувати: Oje, wie peinlich! (Ой, як ніяково!) Das kenne ich (мені це знайоме). Das ist mir auch schon passiert (зі мною таке теж траплялося). Da hast du später bestimmt noch oft darüber gelacht, oder? (Потім ти напевно ще не раз із цього сміявся, так?)',
          'Aksilikleri ve talihsizlikleri anlatmak: Stell dir vor, was mir passiert ist! (Başıma ne geldi, bir düşün!) Ich habe mal eine Nachricht abgeschickt, die für jemand anderen war (bir keresinde başkasına yazdığım bir mesajı yanlış kişiye gönderdim). Aus Versehen = yanlışlıkla, istemeden. Das Missgeschick = küçük bir talihsizlik. Die Panne = bir şeyin ters gitmesi. peinlich = utanç verici, mahcup edici. Tepki vermek: Oje, wie peinlich! (Eyvah, ne utanç verici!) Das kenne ich (bunu bilirim). Das ist mir auch schon passiert (bu benim de başıma geldi). Da hast du später bestimmt noch oft darüber gelacht, oder? (Sonradan buna kesin çok güldün, değil mi?)',
        ],
        hint: ['Panne: Stell dir vor, was mir passiert ist! aus Versehen = ohne Absicht. Reaktion: Oje, wie peinlich! Das ist mir auch schon passiert.', 'Mishap: Stell dir vor, was mir passiert ist! aus Versehen = by mistake. Reaction: Oje, wie peinlich! Das ist mir auch schon passiert.', 'Накладка: Stell dir vor, was mir passiert ist! aus Versehen = нечаянно. Реакция: Oje, wie peinlich! Das ist mir auch schon passiert.', 'Накладка: Stell dir vor, was mir passiert ist! aus Versehen = ненавмисно. Реакція: Oje, wie peinlich! Das ist mir auch schon passiert.', 'Aksilik: Stell dir vor, was mir passiert ist! aus Versehen = yanlışlıkla. Tepki: Oje, wie peinlich! Das ist mir auch schon passiert.'],
      },
      ex: [
        mc('K3', 'Oje, wie peinlich!', I.react, '„Ich habe die E-Mail über den Chef aus Versehen an den Chef selbst geschickt!“', ['Oje, wie peinlich! Und wie hat er reagiert?', 'Selbstverständlich, das ist kein Problem.', 'Dazu möchte ich noch etwas anmerken.'],
          ['“By mistake I sent the e-mail about the boss to the boss himself!”', '«Я по ошибке отправил письмо о начальнике самому начальнику!»', '«Я помилково надіслав листа про керівника самому керівникові!»', '“Patron hakkındaki e-postayı yanlışlıkla patronun kendisine gönderdim!”']),
        mc('K3', 'aus Versehen', I.choose, 'Ich wollte nur meinem Bruder schreiben, aber ich habe die Nachricht aus … an die ganze Abteilung geschickt.', ['Versehen', 'Verstehen', 'Vergnügen'],
          ['I only wanted to write to my brother, but by … I sent the message to the whole department.', 'Я хотел написать только брату, но по … отправил сообщение всему отделу.', 'Я хотів написати лише братові, але … надіслав повідомлення всьому відділу.', 'Yalnızca erkek kardeşime yazmak istemiştim ama mesajı … bütün bölüme gönderdim.']),
        mc('K3', 'peinlich', I.choose, 'Vor allen Gästen ist mir die Torte auf den Boden gefallen. Das war mir furchtbar …', ['peinlich', 'pünktlich', 'persönlich'],
          ['In front of all the guests I dropped the cake on the floor. That was terribly … for me.', 'На глазах у всех гостей я уронил торт на пол. Мне было ужасно …', 'На очах у всіх гостей я впустив торт на підлогу. Мені було страшенно …', 'Bütün misafirlerin önünde pastayı yere düşürdüm. Bu benim için çok … oldu.']),
        mc('K3', 'Das ist mir auch schon passiert.', I.react, '„Bei meinem ersten Kundentermin habe ich den Kunden mit dem falschen Namen angesprochen.“', ['Das kenne ich. Das ist mir auch schon passiert.', 'Das geht doch nicht! Ich will mein Geld zurück.', 'Wir liefern sowohl montags als auch dienstags.'],
          ['“At my first customer appointment I addressed the customer by the wrong name.”', '«На первой встрече с клиентом я назвал его чужим именем.»', '«На першій зустрічі з клієнтом я назвав його чужим ім’ям.»', '“İlk müşteri görüşmemde müşteriye yanlış adla hitap ettim.”']),
        mc('K3', 'auf eine lustige Panne reagieren', I.situation, 'Ein Freund erzählt dir eine lustige Panne von früher. Wie reagierst du?', ['Da hast du später bestimmt noch oft darüber gelacht, oder?', 'Ich bin wirklich sehr verärgert.', 'Es war vereinbart, dass du pünktlich bist.'],
          ['A friend tells you about a funny mishap from the past. How do you react?', 'Друг рассказывает вам о забавной накладке из прошлого. Как вы отреагируете?', 'Друг розповідає вам про кумедну накладку з минулого. Як ви відреагуєте?', 'Bir arkadaşınız size eskiden yaşadığı komik bir aksiliği anlatıyor. Nasıl tepki verirsiniz?']),
        mc('K3', 'Panne', I.choose, 'Der Beamer ging mitten in der Präsentation aus – so eine … kann jedem passieren.', ['Panne', 'Pause', 'Pfanne'],
          ['The projector went off in the middle of the presentation – a … like that can happen to anyone.', 'Проектор выключился посреди презентации – такая … может случиться с каждым.', 'Проєктор вимкнувся посеред презентації – така … може трапитися з кожним.', 'Projektör sunumun tam ortasında kapandı – böyle bir … herkesin başına gelebilir.']),
        gap('K3', 'passiert', I.participle, 'Stell dir vor, was mir gestern ', ' ist: Ich bin im falschen Zug eingeschlafen!', 'passiert', ['gepasst', 'probiert'],
          ['Just imagine what happened to me yesterday: I fell asleep on the wrong train!', 'Представь, что со мной вчера случилось: я заснул не в том поезде!', 'Уяви, що зі мною вчора сталося: я заснув не в тому поїзді!', 'Dün başıma ne geldi, bir düşün: Yanlış trende uyuyakaldım!'], 'passieren'),
        gap('K3', 'Missgeschick', I.word, 'Mir ist ein kleines ', ' passiert: Ich habe Kaffee über die Tastatur geschüttet.', 'Missgeschick', ['Missverständnis', 'Geschenk'],
          ['I had a little mishap: I spilt coffee over the keyboard.', 'Со мной случилась небольшая неприятность: я пролил кофе на клавиатуру.', 'Зі мною сталася невелика прикрість: я розлив каву на клавіатуру.', 'Başıma küçük bir aksilik geldi: Klavyenin üstüne kahve döktüm.'],
          ['mishap', 'оплошность, неприятность', 'прикрість, халепа', 'aksilik, talihsizlik']),
        gap('K3', 'für jemand anderen', I.word, 'Ich habe mal eine Nachricht abgeschickt, die für jemand ', ' war.', 'anderen', ['andere', 'anderes'],
          ['I once sent a message that was meant for someone else.', 'Однажды я отправил сообщение, которое предназначалось другому человеку.', 'Якось я надіслав повідомлення, яке було призначене іншій людині.', 'Bir keresinde başka birine yazılmış bir mesaj gönderdim.'],
          ['(someone) else', 'другой (кто-то другой)', 'інший (хтось інший)', 'başka (biri)']),
        sb('K3', 'Das ist mir auch schon passiert.', I.order, 'Das / ist / mir / auch / schon / passiert.',
          ['That has happened to me too.', 'Со мной такое тоже уже случалось.', 'Зі мною таке теж уже траплялося.', 'Bu benim de başıma geldi.'],
          { alt: ['Mir ist das auch schon passiert.'] }),
      ],
    },
    {
      title: 'Ein Produkt präsentieren',
      t: ['Presenting a product', 'Презентовать товар', 'Презентувати товар', 'Bir ürünü tanıtmak'],
      card: {
        id: 'p3_praesentieren',
        rule: 'Ein Produkt präsentieren: Unser neues Modell ist einfach super! Stellen Sie sich nur vor, er kann nicht nur …, sondern auch … Damit können Sie sowohl … als auch … Das Beste kommt noch! Erstaunen ausdrücken: Unglaublich! Wahnsinn! Ach, wirklich? Das ist ja nicht zu glauben. Werbesprache benutzt viele positive Wörter: praktisch, einzigartig, preiswert, hochwertig, umweltfreundlich, leistungsstark.',
        examples: ['Stellen Sie sich nur vor, er kann nicht nur saugen, sondern auch wischen.', 'Damit können Sie sowohl kochen als auch backen.', 'Wahnsinn! Das ist ja nicht zu glauben.'],
        highlight: null,
        t: [
          'Presenting a product: Unser neues Modell ist einfach super! (Our new model is simply great!) Stellen Sie sich nur vor, er kann nicht nur …, sondern auch … (Just imagine, it can not only …, but also …). Damit können Sie sowohl … als auch … (With it you can both … and …). Das Beste kommt noch! (The best is yet to come!) Expressing amazement: Unglaublich! (Unbelievable!) Wahnsinn! (Amazing!) Ach, wirklich? (Oh, really?) Das ist ja nicht zu glauben (That is hard to believe). Advertising language uses many positive words: praktisch (practical), einzigartig (unique), preiswert (good value), hochwertig (high-quality), umweltfreundlich (environmentally friendly), leistungsstark (powerful).',
          'Как презентовать товар: Unser neues Modell ist einfach super! (Наша новая модель просто великолепна!) Stellen Sie sich nur vor, er kann nicht nur …, sondern auch … (Только представьте: он умеет не только …, но и …). Damit können Sie sowohl … als auch … (С ним вы можете как …, так и …). Das Beste kommt noch! (Самое лучшее ещё впереди!) Как выразить удивление: Unglaublich! (Невероятно!) Wahnsinn! (С ума сойти!) Ach, wirklich? (Да что вы, правда?) Das ist ja nicht zu glauben (в это трудно поверить). В языке рекламы много положительных слов: praktisch (практичный), einzigartig (уникальный), preiswert (недорогой), hochwertig (высококачественный), umweltfreundlich (экологичный), leistungsstark (мощный).',
          'Як презентувати товар: Unser neues Modell ist einfach super! (Наша нова модель просто чудова!) Stellen Sie sich nur vor, er kann nicht nur …, sondern auch … (Тільки уявіть: він уміє не лише …, а й …). Damit können Sie sowohl … als auch … (З ним ви можете як …, так і …). Das Beste kommt noch! (Найкраще ще попереду!) Як висловити подив: Unglaublich! (Неймовірно!) Wahnsinn! (З глузду з’їхати!) Ach, wirklich? (Та невже, справді?) Das ist ja nicht zu glauben (у це важко повірити). У мові реклами багато позитивних слів: praktisch (практичний), einzigartig (унікальний), preiswert (недорогий), hochwertig (високоякісний), umweltfreundlich (екологічний), leistungsstark (потужний).',
          'Bir ürünü tanıtmak: Unser neues Modell ist einfach super! (Yeni modelimiz tek kelimeyle harika!) Stellen Sie sich nur vor, er kann nicht nur …, sondern auch … (Bir düşünün: yalnızca … değil, … de yapabiliyor). Damit können Sie sowohl … als auch … (Bununla hem … hem de … yapabilirsiniz). Das Beste kommt noch! (En güzeli daha gelmedi!) Şaşkınlık ifade etmek: Unglaublich! (İnanılmaz!) Wahnsinn! (Müthiş!) Ach, wirklich? (Sahi mi?) Das ist ja nicht zu glauben (buna inanmak zor). Reklam dili birçok olumlu sözcük kullanır: praktisch (pratik), einzigartig (eşsiz), preiswert (uygun fiyatlı), hochwertig (kaliteli), umweltfreundlich (çevre dostu), leistungsstark (güçlü).',
        ],
        hint: ['Präsentieren: Stellen Sie sich nur vor, … / nicht nur …, sondern auch … / Das Beste kommt noch! Erstaunen: Wahnsinn! Unglaublich!', 'Presenting: Stellen Sie sich nur vor, … / nicht nur …, sondern auch … / Das Beste kommt noch! Amazement: Wahnsinn! Unglaublich!', 'Презентация: Stellen Sie sich nur vor, … / nicht nur …, sondern auch … / Das Beste kommt noch! Удивление: Wahnsinn! Unglaublich!', 'Презентація: Stellen Sie sich nur vor, … / nicht nur …, sondern auch … / Das Beste kommt noch! Подив: Wahnsinn! Unglaublich!', 'Tanıtım: Stellen Sie sich nur vor, … / nicht nur …, sondern auch … / Das Beste kommt noch! Şaşkınlık: Wahnsinn! Unglaublich!'],
      },
      ex: [
        mc('K4', 'Wahnsinn!', I.react, '„Und das Beste kommt noch: Der Akku hält zwei Wochen!“', ['Wahnsinn! Das ist ja nicht zu glauben.', 'Oje, wie peinlich!', 'Das tut mir sehr leid.'],
          ['“And the best is yet to come: the battery lasts two weeks!”', '«И самое лучшее ещё впереди: аккумулятор держит заряд две недели!»', '«І найкраще ще попереду: акумулятор тримає заряд два тижні!»', '“En güzeli daha gelmedi: Batarya iki hafta dayanıyor!”']),
        mc('K4', 'sich vorstellen', I.choose, 'Stellen Sie sich nur …: Dieser Rucksack lädt unterwegs Ihr Handy auf!', ['vor', 'an', 'aus'],
          ['Just imagine: this rucksack charges your phone on the go!', 'Только представьте: этот рюкзак в дороге заряжает ваш телефон!', 'Тільки уявіть: цей рюкзак у дорозі заряджає ваш телефон!', 'Bir düşünün: Bu sırt çantası yoldayken telefonunuzu şarj ediyor!']),
        mc('K4', 'nicht nur …, sondern auch', I.choose, 'Er kann nicht nur Kaffee kochen, … auch Milch aufschäumen.', ['sondern', 'aber', 'oder'],
          ['It can not only make coffee but also froth milk.', 'Он умеет не только варить кофе, но и взбивать молоко.', 'Він уміє не лише варити каву, а й збивати молоко.', 'Yalnızca kahve yapmakla kalmıyor, süt de köpürtebiliyor.']),
        mc('K4', 'Interesse wecken', I.situation, 'Du präsentierst auf einer Messe einen neuen Staubsauger. Womit weckst du das Interesse der Besucher?', ['Unser neues Modell ist einfach super! Stellen Sie sich nur vor, es arbeitet fast lautlos.', 'Ich musste leider feststellen, dass das Gerät defekt ist.', 'Da sehe ich leider nur eine Möglichkeit.'],
          ['You are presenting a new vacuum cleaner at a trade fair. How do you arouse the visitors’ interest?', 'Вы представляете на выставке новый пылесос. Чем вы привлечёте внимание посетителей?', 'Ви представляєте на виставці новий пилосос. Чим ви привернете увагу відвідувачів?', 'Bir fuarda yeni bir elektrikli süpürge tanıtıyorsunuz. Ziyaretçilerin ilgisini nasıl çekersiniz?']),
        mc('K4', 'einzigartig', I.choose, 'Ein Produkt, das es nur ein einziges Mal auf der Welt gibt, ist …', ['einzigartig', 'eigenartig', 'einseitig'],
          ['A product that exists only once in the world is …', 'Товар, который существует в мире только в одном экземпляре, – …', 'Товар, який існує у світі лише в одному примірнику, – …', 'Dünyada yalnızca bir tane bulunan ürün …']),
        mc('K4', 'sowohl … als auch', I.choose, 'Mit dieser App können Sie … Rechnungen schreiben als auch Termine planen.', ['sowohl', 'weder', 'nicht nur'],
          ['With this app you can both write invoices and plan appointments.', 'С этим приложением вы можете как выписывать счета, так и планировать встречи.', 'З цим застосунком ви можете як виписувати рахунки, так і планувати зустрічі.', 'Bu uygulamayla hem fatura yazabilir hem de randevu planlayabilirsiniz.']),
        gap('K4', 'Das Beste kommt noch!', I.form, 'Das ', ' kommt noch: Zu jedem Gerät bekommen Sie eine zweite Batterie gratis dazu!', 'Beste', ['Bessere', 'Gute'],
          ['The best is yet to come: with every appliance you get a second battery free!', 'Самое лучшее ещё впереди: к каждому прибору вы получаете вторую батарею бесплатно!', 'Найкраще ще попереду: до кожного приладу ви отримуєте другу батарею безкоштовно!', 'En güzeli daha gelmedi: Her cihazın yanında ikinci bir pil bedava!'], 'gut (Superlativ)'),
        gap('K4', 'umweltfreundlich', I.word, 'Die Lampe verbraucht sehr wenig Strom und ist deshalb besonders ', '.', 'umweltfreundlich', ['unfreundlich', 'umständlich'],
          ['The lamp uses very little electricity and is therefore particularly environmentally friendly.', 'Лампа потребляет очень мало электроэнергии и поэтому особенно экологична.', 'Лампа споживає дуже мало електроенергії і тому особливо екологічна.', 'Lamba çok az elektrik harcıyor ve bu yüzden özellikle çevre dostu.'],
          ['environmentally friendly', 'экологичный', 'екологічний', 'çevre dostu']),
        gap('K4', 'preiswert', I.word, 'Das Gerät kostet nur 49 Euro – es ist also wirklich ', '.', 'preiswert', ['preislos', 'wertlos'],
          ['The appliance costs only 49 euros – so it really is good value.', 'Прибор стоит всего 49 евро – значит, он действительно недорогой.', 'Прилад коштує лише 49 євро – отже, він справді недорогий.', 'Cihaz yalnızca 49 avro – yani gerçekten uygun fiyatlı.'],
          ['good value, inexpensive', 'недорогой, выгодный', 'недорогий, вигідний', 'uygun fiyatlı']),
        sb('K4', 'Das ist ja nicht zu glauben!', I.order, 'Das / ist / ja / nicht / zu / glauben!',
          ['That is hard to believe!', 'В это просто невозможно поверить!', 'У це просто неможливо повірити!', 'Buna inanmak mümkün değil!']),
      ],
    },
    {
      title: 'Werbung, Reportage, Kolumne',
      t: ['Advertisement, report, column', 'Реклама, репортаж, колонка', 'Реклама, репортаж, колонка', 'Reklam, röportaj, köşe yazısı'],
      card: {
        id: 'p3_werbung',
        rule: 'Werbung, Reportage und Kolumne unterscheiden: Werbung will, dass man etwas kauft – sie nennt nur Vorteile, benutzt starke Wörter (neu, einzigartig, nur diese Woche) und fordert auf: Bestellen Sie jetzt! Eine Reportage berichtet über wirkliche Personen und Ereignisse: Wer? Was? Wo? Warum? Eine Kolumne zeigt die persönliche Meinung des Autors, oft mit Humor: Brauche ich das? Achte auf Zahlen, Gründe (weil, also, deshalb) und Meinungen.',
        examples: ['Nur diese Woche: 20 Prozent Rabatt auf alle Farben!', 'Mehr als 2000 Menschen unterstützten die Idee.', 'Brauche ich das wirklich?'],
        highlight: null,
        t: [
          'Telling apart an advertisement, a report and a column: advertising wants you to buy something – it mentions only advantages, uses strong words (neu, einzigartig, nur diese Woche) and urges you: Bestellen Sie jetzt! (Order now!) A Reportage (report) tells you about real people and events: who? what? where? why? A Kolumne (column) shows the author’s personal opinion, often with humour: Brauche ich das? (Do I need that?) Look out for figures, reasons (weil, also, deshalb) and opinions.',
          'Как различать рекламу, репортаж и колонку: реклама хочет, чтобы вы что-то купили, – она называет только преимущества, использует сильные слова (neu, einzigartig, nur diese Woche) и призывает: Bestellen Sie jetzt! (Закажите сейчас!) Репортаж (Reportage) рассказывает о реальных людях и событиях: кто? что? где? почему? Колонка (Kolumne) показывает личное мнение автора, часто с юмором: Brauche ich das? (Нужно ли мне это?) Обращайте внимание на цифры, причины (weil, also, deshalb) и мнения.',
          'Як розрізняти рекламу, репортаж і колонку: реклама хоче, щоб ви щось купили, – вона називає лише переваги, вживає сильні слова (neu, einzigartig, nur diese Woche) і закликає: Bestellen Sie jetzt! (Замовте зараз!) Репортаж (Reportage) розповідає про реальних людей і події: хто? що? де? чому? Колонка (Kolumne) показує особисту думку автора, часто з гумором: Brauche ich das? (Чи потрібно мені це?) Звертайте увагу на цифри, причини (weil, also, deshalb) і думки.',
          'Reklamı, röportajı ve köşe yazısını ayırt etmek: Reklam bir şey satın almanızı ister – yalnızca üstünlükleri sayar, güçlü sözcükler kullanır (neu, einzigartig, nur diese Woche) ve çağrı yapar: Bestellen Sie jetzt! (Şimdi sipariş verin!) Röportaj (Reportage) gerçek kişileri ve olayları anlatır: Kim? Ne? Nerede? Neden? Köşe yazısı (Kolumne) yazarın kişisel görüşünü, çoğu zaman mizahla gösterir: Brauche ich das? (Buna ihtiyacım var mı?) Rakamlara, nedenlere (weil, also, deshalb) ve görüşlere dikkat edin.',
        ],
        hint: ['Werbung = nur Vorteile, will verkaufen. Reportage = wirkliche Personen und Fakten. Kolumne = persönliche Meinung des Autors.', 'Advertisement = only advantages, wants to sell. Reportage = real people and facts. Kolumne = the author’s personal opinion.', 'Реклама = только преимущества, цель – продать. Reportage = реальные люди и факты. Kolumne = личное мнение автора.', 'Реклама = лише переваги, мета – продати. Reportage = реальні люди і факти. Kolumne = особиста думка автора.', 'Reklam = yalnızca üstünlükler, amaç satmak. Reportage = gerçek kişiler ve olgular. Kolumne = yazarın kişisel görüşü.'],
      },
      ex: [
        mc('Z1', 'Wie lange heiß?', I.read, `${THERMOFLASCHE} Wie lange bleiben Getränke in der Flasche heiß?`, ['Acht Stunden.', 'Zwölf Stunden.', 'Zwanzig Stunden.'],
          ['How long do drinks stay hot in the flask?', 'Как долго напитки остаются в термосе горячими?', 'Як довго напої залишаються в термосі гарячими?', 'İçecekler termosta ne kadar süre sıcak kalıyor?']),
        mc('Z1', 'weder schwer noch empfindlich', I.read, `${THERMOFLASCHE} Was erfährt man über die Flasche?`, ['Sie ist leicht und robust.', 'Sie ist schwer, aber stabil.', 'Sie geht leicht kaputt.'],
          ['What do you learn about the flask?', 'Что можно узнать о термосе?', 'Що можна дізнатися про термос?', 'Termos hakkında ne öğreniyoruz?']),
        mc('Z1', 'nur diese Woche', I.read, `${THERMOFLASCHE} Was gilt nur in dieser Woche?`, ['Es gibt 20 Prozent Rabatt.', 'Die Lieferung ist kostenlos.', 'Es gibt nur eine Farbe.'],
          ['What applies only this week?', 'Что действует только на этой неделе?', 'Що діє лише цього тижня?', 'Yalnızca bu hafta ne geçerli?']),
        mc('Z1', 'Warum im Internet?', I.read, `${FALTHELM} Warum stellten die Gründer ihre Idee im Internet vor?`, ['Weil die Bank ihnen kein Geld leihen wollte.', 'Weil sie berühmt werden wollten.', 'Weil sie keine Kunden im Ausland hatten.'],
          ['Why did the founders present their idea on the internet?', 'Почему основатели представили свою идею в интернете?', 'Чому засновники представили свою ідею в інтернеті?', 'Kurucular fikirlerini neden internette tanıttı?']),
        mc('Z1', 'Unterstützer', I.read, `${FALTHELM} Was bekamen die Unterstützer?`, ['Einen der ersten Helme.', 'Ihr Geld mit Zinsen zurück.', 'Einen Arbeitsplatz in der Firma.'],
          ['What did the supporters receive?', 'Что получили те, кто поддержал проект?', 'Що отримали ті, хто підтримав проєкт?', 'Destek verenler ne aldı?']),
        mc('Z1', 'Erfolg', I.read, `${FALTHELM} Wie erfolgreich ist die Firma heute?`, ['Sie verkauft ihre Helme in zwölf Ländern.', 'Sie musste schließen.', 'Sie verkauft nur in Dresden.'],
          ['How successful is the company today?', 'Насколько успешна фирма сегодня?', 'Наскільки успішна фірма сьогодні?', 'Şirket bugün ne kadar başarılı?']),
        mc('Z1', 'Was kann die Zahnbürste?', I.read, `${ZAHNBUERSTE} Was kann die neue Zahnbürste?`, ['Sie spricht und sendet Daten an das Handy.', 'Sie putzt ganz allein.', 'Sie braucht keinen Strom.'],
          ['What can the new toothbrush do?', 'Что умеет новая зубная щётка?', 'Що вміє нова зубна щітка?', 'Yeni diş fırçası ne yapabiliyor?']),
        mc('Z1', 'Meinung des Autors', I.read, `${ZAHNBUERSTE} Wie denkt der Autor über „smarte“ Geräte?`, ['Er findet, dass man nicht jedes braucht.', 'Er möchte möglichst viele davon kaufen.', 'Er findet sie zu billig.'],
          ['What does the author think about “smart” devices?', 'Что автор думает об «умных» устройствах?', 'Що автор думає про «розумні» пристрої?', 'Yazar “akıllı” cihazlar hakkında ne düşünüyor?']),
      ],
    },
  ],
}

export default path
