import { I, gap, mc } from '../shared.mjs'

const OKAFOR = 'Interview: „Herr Okafor, Sie kamen vor zwölf Jahren als Student nach Leipzig. Was hat Sie überrascht? – Dass man hier seine Meinung so direkt sagt. Am Anfang fand ich das unhöflich. Heute finde ich es praktisch, da man immer weiß, woran man ist. – Was vermissen Sie? – Die langen Abende mit der ganzen Familie. Hier plant man Besuche oft Wochen vorher. – Werden Sie bleiben? – Ja. Ich werde nächstes Jahr die deutsche Staatsangehörigkeit beantragen.“'
const RADFAHRER = 'Erfahrungsbericht: „Als ich aus Italien nach Münster kam, kaufte ich mir sofort ein Fahrrad. Schon am zweiten Tag hielt mich die Polizei an: Ich war ohne Licht gefahren. Ich entschuldigte mich und versprach, dass es nie wieder vorkommen wird. Der Polizist drückte ein Auge zu, da ich neu in der Stadt war. Inzwischen kenne ich die Regeln – und ärgere mich selbst über Radfahrer, die bei Rot fahren.“'

/** B1.2 · Pfad 4 · Miteinander – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Rücksicht nehmen', I.choose, 'Bitte seien Sie leise, wenn Sie spät nach Hause kommen. Wir bitten alle Mieter, … auf die Nachbarn zu nehmen.', ['Rücksicht', 'Vorfahrt', 'Abschied'],
      ['Please be quiet when you come home late. We ask all tenants to show … for their neighbours.', 'Пожалуйста, не шумите, когда поздно возвращаетесь домой. Мы просим всех жильцов … с соседями.', 'Будь ласка, не шуміть, коли пізно повертаєтеся додому. Ми просимо всіх мешканців … на сусідів.', 'Eve geç geldiğinizde lütfen sessiz olun. Bütün kiracılardan komşuları … rica ediyoruz.']),
    mc('W2', 'Tempolimit', I.choose, 'Vor der Schule gilt ein strenges …: Hier darf man höchstens 30 fahren.', ['Tempolimit', 'Trinkgeld', 'Vorurteil'],
      ['There is a strict … in front of the school: you may drive at 30 at most here.', 'Перед школой действует строгое …: здесь можно ехать не быстрее 30.', 'Перед школою діє суворе …: тут можна їхати не швидше 30.', 'Okulun önünde sıkı bir … var: Burada en fazla 30 ile gidilebilir.']),
    mc('W3', 'Heimat', I.choose, 'Viele Menschen, die ihr Land verlassen mussten, träumen davon, eines Tages in ihre … zurückzukehren.', ['Heimat', 'Heizung', 'Hälfte'],
      ['Many people who had to leave their country dream of returning to their … one day.', 'Многие люди, которым пришлось покинуть свою страну, мечтают однажды вернуться на …', 'Багато людей, яким довелося покинути свою країну, мріють одного дня повернутися на …', 'Ülkesini terk etmek zorunda kalan birçok insan bir gün … dönmeyi hayal ediyor.']),
    mc('G1', 'wir werden', I.choose, 'Nächstes Jahr … wir unser Büro in einen anderen Stadtteil verlegen.', ['werden', 'wird', 'werdet'],
      ['Next year we will move our office to another part of town.', 'В следующем году мы перенесём наш офис в другой район города.', 'Наступного року ми перенесемо наш офіс до іншого району міста.', 'Gelecek yıl ofisimizi şehrin başka bir semtine taşıyacağız.']),
    mc('G2', 'Vermutung', I.choose, 'Was drückt der Satz aus? „Die Züge werden morgen wegen des Streiks wahrscheinlich ausfallen.“', ['Eine Vermutung.', 'Ein Versprechen.', 'Eine Aufforderung.'],
      ['What does the sentence express? “The trains will probably be cancelled tomorrow because of the strike.”', 'Что выражает это предложение? «Завтра поезда из-за забастовки, вероятно, отменят.»', 'Що виражає це речення? «Завтра поїзди через страйк, імовірно, скасують.»', 'Bu cümle neyi ifade ediyor? “Trenler yarın grev yüzünden muhtemelen iptal olacak.”']),
    mc('G3', 'Da', I.choose, '… der Chef heute nicht im Haus ist, müssen wir die Entscheidung verschieben.', ['Da', 'Deshalb', 'Dann'],
      ['As the boss is not in today, we have to postpone the decision.', 'Так как начальника сегодня нет на месте, нам придётся отложить решение.', 'Оскільки керівника сьогодні немає на місці, нам доведеться відкласти рішення.', 'Patron bugün burada olmadığı için kararı ertelemek zorundayız.']),
    mc('K1', 'fest vorgenommen', I.choose, 'Ab morgen fahre ich nur noch mit dem Rad zur Arbeit. Das habe ich mir fest …', ['vorgenommen', 'vorgekommen', 'vorgeschlagen'],
      ['From tomorrow I will only cycle to work. I have firmly resolved to do that.', 'С завтрашнего дня я буду ездить на работу только на велосипеде. Я это твёрдо решил.', 'Від завтра я їздитиму на роботу лише велосипедом. Я це твердо вирішив.', 'Yarından itibaren işe yalnızca bisikletle gideceğim. Buna kesin karar verdim.']),
    mc('K2', 'Zweifel ausdrücken', I.react, '„Ich werde meinen Job kündigen und ein Café eröffnen.“', ['Ach, ist das nicht zu riskant? Bist du sicher?', 'Tut mir leid, es war keine Absicht.', 'Bei uns ist es üblich, die Schuhe auszuziehen.'],
      ['“I am going to quit my job and open a café.”', '«Я уволюсь с работы и открою кафе.»', '«Я звільнюся з роботи й відкрию кафе.»', '“İşimden ayrılıp bir kafe açacağım.”']),
    mc('K3', 'Ich wollte nur schnell …', I.choose, 'Entschuldigung, ich wollte nur … etwas ausladen. In zwei Minuten bin ich weg.', ['schnell', 'schlimm', 'schwer'],
      ['Sorry, I only wanted to unload something quickly. I will be gone in two minutes.', 'Извините, я только хотел быстро кое-что выгрузить. Через две минуты меня здесь не будет.', 'Вибачте, я лише хотів швидко дещо вивантажити. За дві хвилини мене тут не буде.', 'Affedersiniz, yalnızca çabucak bir şey indirmek istemiştim. İki dakikaya gidiyorum.']),
    mc('K4', 'Ich würde ihm erklären, dass …', I.choose, 'Ich würde ihm …, dass man in Deutschland bei Einladungen pünktlich sein sollte.', ['erklären', 'erlauben', 'erleben'],
      ['I would … to him that in Germany you should be on time when you are invited.', 'Я бы … ему, что в Германии в гости следует приходить вовремя.', 'Я б … йому, що в Німеччині в гості слід приходити вчасно.', 'Ona Almanya’da davetlere zamanında gitmek gerektiğini … .']),
    mc('Z1', 'am Anfang unhöflich', I.read, `${OKAFOR} Was fand Herr Okafor am Anfang unhöflich?`, ['Dass man seine Meinung so direkt sagt.', 'Dass man Besuche vorher plant.', 'Dass die Abende so lang sind.'],
      ['What did Mr Okafor find rude at first?', 'Что господин Okafor поначалу считал невежливым?', 'Що пан Okafor спочатку вважав неввічливим?', 'Bay Okafor başlangıçta neyi kaba buluyordu?']),
    gap('G1', 'dass du … wirst', I.verb, 'Ich hoffe, dass du dich in der neuen Stadt schnell einleben ', '.', 'wirst', ['wird', 'werdet'],
      ['I hope that you will settle in quickly in the new town.', 'Надеюсь, что ты быстро освоишься в новом городе.', 'Сподіваюся, що ти швидко освоїшся в новому місті.', 'Umarım yeni şehre çabuk alışırsın.'], 'werden'),
    gap('G3', 'da', I.conjunction, 'Wir nehmen besser die Bahn, ', ' es in der Innenstadt kaum Parkplätze gibt.', 'da', ['dann', 'dass'],
      ['We had better take the train, as there are hardly any parking spaces in the city centre.', 'Нам лучше поехать на поезде, так как в центре города почти нет парковочных мест.', 'Нам краще поїхати поїздом, оскільки в центрі міста майже немає місць для паркування.', 'Şehir merkezinde neredeyse hiç park yeri olmadığı için trenle gitsek daha iyi olur.'], 'da / dann / dass'),
  ],
  size: 13,
  test: [
    mc('W1', 'gutes Benehmen', I.choose, 'Es gehört zum guten …, sich für ein Geschenk zu bedanken.', ['Benehmen', 'Bekommen', 'Bezahlen'],
      ['It is part of good … to say thank you for a present.', 'Поблагодарить за подарок – это признак хорошего …', 'Подякувати за подарунок – це ознака доброї …', 'Bir hediye için teşekkür etmek iyi … gereğidir.']),
    mc('W1', 'rücksichtsvoll', I.choose, 'Jemand, der anderen die Tür aufhält und im Bus aufsteht, wenn ältere Leute einsteigen, ist …', ['rücksichtsvoll', 'rücksichtslos', 'ratlos'],
      ['Someone who holds the door open for others and stands up on the bus when older people get on is …', 'Тот, кто придерживает другим дверь и встаёт в автобусе, когда входят пожилые люди, – …', 'Той, хто притримує іншим двері і встає в автобусі, коли заходять літні люди, – …', 'Başkalarına kapıyı tutan ve otobüse yaşlılar bindiğinde ayağa kalkan kişi …']),
    mc('W2', 'Bußgeld', I.choose, 'Er ist in der Stadt 80 statt 50 gefahren. Jetzt muss er 200 Euro … zahlen.', ['Bußgeld', 'Kleingeld', 'Wechselgeld'],
      ['He drove at 80 instead of 50 in town. Now he has to pay a 200-euro …', 'Он ехал по городу 80 вместо 50. Теперь ему придётся заплатить 200 евро …', 'Він їхав містом 80 замість 50. Тепер йому доведеться заплатити 200 євро …', 'Şehir içinde 50 yerine 80 ile gitti. Şimdi 200 avro … ödemek zorunda.']),
    mc('W3', 'Flucht', I.choose, 'Die Familie musste über Nacht ihr Haus verlassen. Ihre … dauerte drei Wochen.', ['Flucht', 'Frucht', 'Frist'],
      ['The family had to leave their house overnight. Their … lasted three weeks.', 'Семье пришлось за одну ночь покинуть свой дом. Их … длилось три недели.', 'Родині довелося за одну ніч покинути свій дім. Їхня … тривала три тижні.', 'Aile bir gecede evini terk etmek zorunda kaldı. … üç hafta sürdü.']),
    mc('W3', 'Vorurteile', I.choose, 'Viele Menschen haben …: Sie urteilen über andere, obwohl sie sie gar nicht kennen.', ['Vorurteile', 'Vorteile', 'Vorräte'],
      ['Many people have …: they judge others although they do not know them at all.', 'У многих людей есть …: они судят о других, хотя совсем их не знают.', 'Багато людей мають …: вони судять про інших, хоча зовсім їх не знають.', 'Birçok insanın … var: Başkalarını hiç tanımadıkları hâlde yargılıyorlar.']),
    mc('G1', 'du wirst', I.choose, 'Wann … du endlich mit dem Chef über dein Gehalt sprechen?', ['wirst', 'wird', 'werdet'],
      ['When will you finally talk to the boss about your salary?', 'Когда ты наконец поговоришь с начальником о своей зарплате?', 'Коли ти нарешті поговориш із керівником про свою зарплату?', 'Patronla maaşın hakkında nihayet ne zaman konuşacaksın?']),
    mc('G1', 'werden + Infinitiv am Ende', I.sentence, 'Der Bürgermeister kündigt etwas an.', ['Die Stadt wird im nächsten Jahr zwanzig neue Radwege bauen.', 'Die Stadt wird im nächsten Jahr zwanzig neue Radwege gebaut.', 'Die Stadt wird bauen im nächsten Jahr zwanzig neue Radwege.'],
      ['The mayor is announcing something.', 'Мэр что-то объявляет.', 'Мер щось оголошує.', 'Belediye başkanı bir şey duyuruyor.']),
    mc('G2', 'Vorsatz', I.choose, 'Was drückt der Satz aus? „Ich werde ab sofort jeden Tag zehn neue Wörter lernen.“', ['Einen Vorsatz.', 'Eine Vermutung.', 'Eine Aufforderung an andere.'],
      ['What does the sentence express? “From now on I will learn ten new words every day.”', 'Что выражает это предложение? «С этого момента я буду каждый день учить десять новых слов.»', 'Що виражає це речення? «Відтепер я щодня вчитиму десять нових слів.»', 'Bu cümle neyi ifade ediyor? “Bundan sonra her gün on yeni kelime öğreneceğim.”']),
    mc('G2', 'Aufforderung', I.choose, 'Du … jetzt sofort das Handy weglegen und mir zuhören!', ['wirst', 'wird', 'bist'],
      ['You will put the phone away right now and listen to me!', 'Ты сейчас же отложишь телефон и выслушаешь меня!', 'Ти зараз же відкладеш телефон і вислухаєш мене!', 'Hemen şimdi telefonu bırakıp beni dinleyeceksin!']),
    mc('G3', 'da', I.choose, 'Ich liebe meinen Stadtteil, … hier Menschen aus der ganzen Welt zusammenleben.', ['da', 'dann', 'deshalb'],
      ['I love my part of town, as people from all over the world live together here.', 'Я люблю свой район, так как здесь вместе живут люди со всего мира.', 'Я люблю свій район, оскільки тут разом живуть люди з усього світу.', 'Semtimi seviyorum, çünkü burada dünyanın her yerinden insanlar bir arada yaşıyor.']),
    mc('G3', 'da + Verb am Ende', I.sentence, 'Ein Satz aus einer E-Mail an einen Kunden.', ['Da wir am Freitag geschlossen haben, liefern wir erst am Montag.', 'Da wir haben am Freitag geschlossen, liefern wir erst am Montag.', 'Da wir am Freitag geschlossen haben, wir liefern erst am Montag.'],
      ['A sentence from an e-mail to a customer.', 'Предложение из письма клиенту.', 'Речення з листа клієнтові.', 'Bir müşteriye yazılmış e-postadan bir cümle.']),
    mc('K1', 'In Zukunft', I.choose, 'Nächsten Montag fange ich an: In … werde ich jeden Morgen eine halbe Stunde früher aufstehen.', ['Zukunft', 'Zufall', 'Zweifel'],
      ['I will start next Monday: in … I will get up half an hour earlier every morning.', 'Начинаю со следующего понедельника: в … я буду каждое утро вставать на полчаса раньше.', 'Починаю з наступного понеділка: у … я щоранку вставатиму на пів години раніше.', 'Gelecek pazartesi başlıyorum: … her sabah yarım saat erken kalkacağım.']),
    mc('K1', 'einen Vorsatz bekräftigen', I.situation, 'Du hast deinem Freund versprochen, pünktlicher zu sein. Wie bekräftigst du das?', ['Das habe ich mir fest vorgenommen. Das verspreche ich dir.', 'Das ist doch nicht realistisch!', 'Können Sie nicht ein Auge zudrücken?'],
      ['You have promised your friend to be more punctual. How do you confirm that?', 'Вы пообещали другу быть пунктуальнее. Как вы это подтвердите?', 'Ви пообіцяли другові бути пунктуальнішим. Як ви це підтвердите?', 'Arkadaşınıza daha dakik olacağınıza söz verdiniz. Bunu nasıl pekiştirirsiniz?']),
    mc('K2', 'Zustimmung ausdrücken', I.react, '„Unsere Firma will allen Mitarbeitern ein Fahrrad schenken.“', ['Wirklich? Das ist ja super!', 'Das ist mir wirklich unangenehm.', 'Es wird nie wieder vorkommen.'],
      ['“Our company wants to give every employee a bicycle.”', '«Наша фирма хочет подарить всем сотрудникам по велосипеду.»', '«Наша фірма хоче подарувати всім працівникам по велосипеду.»', '“Şirketimiz bütün çalışanlara birer bisiklet hediye etmek istiyor.”']),
    mc('K2', 'nicht schlimm', I.choose, 'Ich finde es nicht …, wenn jemand fünf Minuten zu spät kommt. Das kann jedem passieren.', ['schlimm', 'schnell', 'schmal'],
      ['I do not think it is … if someone is five minutes late. That can happen to anyone.', 'Я не вижу ничего …, если кто-то опаздывает на пять минут. Это может случиться с каждым.', 'Я не бачу нічого …, якщо хтось запізнюється на п’ять хвилин. Це може трапитися з кожним.', 'Birinin beş dakika geç kalmasını … bulmuyorum. Bu herkesin başına gelebilir.']),
    mc('K3', 'Sie haben recht.', I.react, '„Sie stehen mit Ihrem Wagen mitten auf dem Gehweg!“', ['Sie haben ja vollkommen recht. Ich fahre sofort weg.', 'Eine tolle Idee. Nicht schlecht.', 'Das habe ich mir fest vorgenommen.'],
      ['“Your car is standing right in the middle of the pavement!”', '«Ваша машина стоит прямо посреди тротуара!»', '«Ваша машина стоїть просто посеред тротуару!»', '“Arabanız kaldırımın tam ortasında duruyor!”']),
    mc('K4', 'üblich', I.choose, 'Bei uns ist es …, den Gästen zuerst Tee anzubieten und erst danach über das Geschäft zu sprechen.', ['üblich', 'ungern', 'unterwegs'],
      ['In my country it is … to offer the guests tea first and only then to talk about business.', 'У нас … сначала предложить гостям чай и только потом говорить о делах.', 'У нас … спочатку запропонувати гостям чай і лише потім говорити про справи.', 'Bizde misafirlere önce çay ikram etmek ve ancak ondan sonra iş konuşmak … .']),
    mc('Z1', 'Was vermisst er?', I.read, `${OKAFOR} Was vermisst Herr Okafor?`, ['Die langen Abende mit der ganzen Familie.', 'Die direkte Art der Deutschen.', 'Sein Studium in Leipzig.'],
      ['What does Mr Okafor miss?', 'По чему скучает господин Okafor?', 'За чим сумує пан Okafor?', 'Bay Okafor neyi özlüyor?']),
    mc('Z1', 'Plan für das nächste Jahr', I.read, `${OKAFOR} Was plant er für das nächste Jahr?`, ['Er möchte die deutsche Staatsangehörigkeit beantragen.', 'Er möchte in seine Heimat zurückkehren.', 'Er möchte ein Studium beginnen.'],
      ['What is he planning for next year?', 'Что он планирует на следующий год?', 'Що він планує на наступний рік?', 'Gelecek yıl için ne planlıyor?']),
    mc('Z1', 'ein Auge zugedrückt', I.read, `${RADFAHRER} Warum drückte der Polizist ein Auge zu?`, ['Weil der Mann neu in der Stadt war.', 'Weil das Fahrrad neu war.', 'Weil es noch hell war.'],
      ['Why did the police officer turn a blind eye?', 'Почему полицейский закрыл на это глаза?', 'Чому поліцейський заплющив на це очі?', 'Polis neden görmezden geldi?']),
    gap('W1', 'unterbreche', I.verb, 'Entschuldigung, dass ich Sie ', ', aber Ihr Taxi ist da.', 'unterbreche', ['unterbricht', 'unterbrochen'],
      ['Sorry to interrupt you, but your taxi is here.', 'Извините, что перебиваю вас, но ваше такси приехало.', 'Вибачте, що перебиваю вас, але ваше таксі приїхало.', 'Sözünüzü kestiğim için özür dilerim ama taksiniz geldi.'], 'unterbrechen'),
    gap('W2', 'Vorfahrt', I.word, 'An der Kreuzung musst du warten: Der Bus von rechts hat ', '.', 'Vorfahrt', ['Vorsicht', 'Vorteil'],
      ['You have to wait at the junction: the bus from the right has right of way.', 'На перекрёстке тебе нужно подождать: у автобуса справа преимущество.', 'На перехресті тобі треба зачекати: автобус праворуч має перевагу.', 'Kavşakta beklemen gerek: Sağdan gelen otobüsün geçiş hakkı var.'],
      ['right of way', 'преимущество в движении', 'перевага в русі', 'geçiş hakkı']),
    gap('W3', 'sich eingelebt', I.participle, 'Nach zwei Jahren hatte er Freunde gefunden und sich in der neuen Stadt gut ', '.', 'eingelebt', ['eingeladen', 'eingestellt'],
      ['After two years he had found friends and settled in well in the new town.', 'Через два года он нашёл друзей и хорошо освоился в новом городе.', 'За два роки він знайшов друзів і добре освоївся в новому місті.', 'İki yıl sonra arkadaşlar edinmiş ve yeni şehre iyice alışmıştı.'], 'sich einleben'),
    gap('G1', 'dass ihr … werdet', I.verb, 'Ich glaube nicht, dass ihr den Zug noch erreichen ', '.', 'werdet', ['werden', 'wirst'],
      ['I do not think that you will still catch the train.', 'Не думаю, что вы ещё успеете на поезд.', 'Не думаю, що ви ще встигнете на поїзд.', 'Trene yetişeceğinizi sanmıyorum.'], 'werden'),
    gap('G2', 'wird wohl … sein', I.verb, 'Der Chef ist nicht da. Er ', ' wohl noch in der Besprechung sein.', 'wird', ['wirst', 'werdet'],
      ['The boss is not here. He is probably still in the meeting.', 'Начальника нет. Он, наверное, ещё на совещании.', 'Керівника немає. Він, мабуть, ще на нараді.', 'Patron burada değil. Herhâlde hâlâ toplantıdadır.'], 'werden'),
    gap('G3', 'da … fuhr', I.verb, 'Da der Fahrer zu schnell ', ', konnte er nicht mehr rechtzeitig bremsen.', 'fuhr', ['fährt', 'gefahren'],
      ['As the driver was going too fast, he could no longer brake in time.', 'Так как водитель ехал слишком быстро, он уже не смог вовремя затормозить.', 'Оскільки водій їхав надто швидко, він уже не зміг вчасно загальмувати.', 'Sürücü çok hızlı gittiği için zamanında fren yapamadı.'], 'fahren (Präteritum)'),
    gap('K1', 'Ab morgen', I.prep, 'So geht das nicht mehr weiter. ', ' morgen mache ich jeden Tag eine Stunde Sport.', 'Ab', ['Seit', 'Vor'],
      ['It cannot go on like this. From tomorrow I will do an hour of sport every day.', 'Так больше продолжаться не может. С завтрашнего дня я буду каждый день заниматься спортом по часу.', 'Так більше тривати не може. Від завтра я щодня займатимуся спортом по годині.', 'Bu böyle devam edemez. Yarından itibaren her gün bir saat spor yapacağım.'], 'ab / seit / vor'),
    gap('K2', 'nicht realistisch', I.word, 'In einer Woche zehn Kilo abnehmen? Das ist doch nicht ', '!', 'realistisch', ['regelmäßig', 'rücksichtsvoll'],
      ['Lose ten kilos in a week? That is not realistic!', 'Похудеть на десять килограммов за неделю? Это же нереально!', 'Схуднути на десять кілограмів за тиждень? Це ж нереально!', 'Bir haftada on kilo vermek mi? Bu hiç gerçekçi değil!'],
      ['realistic', 'реалистично', 'реалістично', 'gerçekçi']),
    gap('K3', 'keine Absicht', I.word, 'Bitte glauben Sie mir, es war wirklich keine ', '. Ich habe das Schild übersehen.', 'Absicht', ['Ansicht', 'Aufsicht'],
      ['Please believe me, it really was not on purpose. I overlooked the sign.', 'Пожалуйста, поверьте, я действительно сделал это не нарочно. Я не заметил знак.', 'Будь ласка, повірте, я справді зробив це не навмисно. Я не помітив знака.', 'Lütfen bana inanın, gerçekten kasıtlı değildi. Tabelayı gözden kaçırdım.'],
      ['intention, purpose', 'умысел, намерение', 'намір, умисел', 'kasıt, niyet']),
    gap('K4', 'Er muss wissen, dass …', I.word, 'Er muss ', ', dass man hier mit dem Essen wartet, bis alle am Tisch sitzen.', 'wissen', ['wischen', 'wechseln'],
      ['He has to know that people here wait with the meal until everyone is sitting at the table.', 'Он должен знать, что здесь не начинают есть, пока все не сядут за стол.', 'Він має знати, що тут не починають їсти, доки всі не сядуть за стіл.', 'Burada herkes sofraya oturana kadar yemeğe başlanmadığını bilmeli.'],
      ['to know', 'знать', 'знати', 'bilmek']),
  ],
}

export default check
