import { I, gap, mc } from '../shared.mjs'

const BUERGERMEISTERWAHL = 'Zeitungsmeldung: „Bei der Bürgermeisterwahl in Altdorf ist am Sonntag überraschend der parteilose Kandidat Martin Seidel gewählt worden. Er erhielt 54 Prozent der Stimmen. Die Wahlbeteiligung war mit 71 Prozent die höchste seit zwanzig Jahren. Seidel hatte im Wahlkampf versprochen, das Schwimmbad zu erhalten und mehr Wohnungen zu bauen. Er wird sein Amt am 1. Mai antreten.“'
const KAYA = 'Reportage: „Aydin Kaya kam 1972 als Kind mit seinen Eltern aus der Türkei nach Köln. Sein Vater war als Arbeiter für eine Autofabrik angeworben worden. Kaya machte eine Ausbildung zum Elektriker und gründete 1995 eine eigene Firma. Seit 2010 engagiert er sich im Integrationsrat der Stadt. Für seine Arbeit ist er im letzten Jahr mit einem Preis ausgezeichnet worden.“'
const WERDEN_PAST = 'werden (Präteritum)'

/** B1.2 · Pfad 6 · Politik und Geschichte – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Teilung', I.choose, 'Nach dem Krieg wurde Deutschland in zwei Staaten geteilt. Diese … endete erst 1990.', ['Teilung', 'Leitung', 'Heizung'],
      ['After the war Germany was divided into two states. This … did not end until 1990.', 'После войны Германия была разделена на два государства. Это … закончилось только в 1990 году.', 'Після війни Німеччину було поділено на дві держави. Цей … закінчився лише 1990 року.', 'Savaştan sonra Almanya iki devlete bölündü. Bu … ancak 1990’da sona erdi.']),
    mc('W2', 'streiken', I.choose, 'Morgen fährt keine Bahn: Die Lokführer … für bessere Arbeitszeiten.', ['streiken', 'stricken', 'streichen'],
      ['No trains will run tomorrow: the train drivers are going to … for better working hours.', 'Завтра поезда не ходят: машинисты … за лучший график работы.', 'Завтра поїзди не ходять: машиністи … за кращий графік роботи.', 'Yarın tren yok: Makinistler daha iyi çalışma saatleri için … .']),
    mc('G1', 'wurde organisiert', I.choose, 'Die erste Demonstration … von Studenten organisiert.', ['wurde', 'wurden', 'hat'],
      ['The first demonstration was organised by students.', 'Первая демонстрация была организована студентами.', 'Першу демонстрацію було організовано студентами.', 'İlk gösteri öğrenciler tarafından düzenlendi.']),
    mc('G2', 'genehmigt worden', I.choose, 'Unser Antrag ist endlich genehmigt …', ['worden', 'geworden', 'werden'],
      ['Our application has finally been approved.', 'Наше заявление наконец одобрили.', 'Нашу заяву нарешті схвалили.', 'Başvurumuz nihayet onaylandı.']),
    mc('G3', 'einen größeren Raum', I.choose, 'Für die Veranstaltung brauchen wir einen … Raum – hier passen nur dreißig Leute hinein.', ['größeren', 'größere', 'größer'],
      ['For the event we need a bigger room – only thirty people fit in here.', 'Для мероприятия нам нужно помещение побольше – сюда помещается только тридцать человек.', 'Для заходу нам потрібне більше приміщення – сюди вміщується лише тридцять людей.', 'Etkinlik için daha büyük bir salona ihtiyacımız var – buraya yalnızca otuz kişi sığıyor.']),
    mc('G4', 'die größte Demonstration', I.choose, 'Das war die … Demonstration, die es in unserer Stadt je gegeben hat.', ['größte', 'größten', 'größere'],
      ['That was the biggest demonstration there has ever been in our town.', 'Это была самая большая демонстрация за всю историю нашего города.', 'Це була найбільша демонстрація за всю історію нашого міста.', 'Bu, şehrimizde bugüne kadar yapılmış en büyük gösteriydi.']),
    mc('K1', 'Überleitung: Danach', I.choose, 'Zuerst möchten wir über die Kindheit sprechen. … kommen wir zu den Jahren in Berlin.', ['Danach', 'Davor', 'Dagegen'],
      ['First we would like to talk about his childhood. After that we will come to the years in Berlin.', 'Сначала мы хотели бы поговорить о детстве. После этого перейдём к годам в Берлине.', 'Спочатку ми хотіли б поговорити про дитинство. Після цього перейдемо до років у Берліні.', 'Önce çocukluğu hakkında konuşmak istiyoruz. Ondan sonra Berlin yıllarına geçeceğiz.']),
    mc('K2', 'befürworten', I.react, '„Sollen Kinder in der Schule mehr über Politik lernen?“', ['Das kann ich nur befürworten. Demokratie muss man lernen.', 'Der nächste Punkt ist seine Jugend.', 'Verglichen mit Hamburg ist es ruhig.'],
      ['“Should children learn more about politics at school?”', '«Должны ли дети больше узнавать о политике в школе?»', '«Чи мають діти більше дізнаватися про політику в школі?»', '“Çocuklar okulda siyaset hakkında daha çok şey öğrenmeli mi?”']),
    mc('K3', 'strengere Gesetze als', I.choose, 'Bei uns gibt es … Gesetze gegen das Rauchen als in Deutschland: Man darf nicht einmal im Park rauchen.', ['strengere', 'strenger', 'am strengsten'],
      ['In my country there are stricter laws against smoking than in Germany: you may not even smoke in the park.', 'У нас более строгие законы против курения, чем в Германии: курить нельзя даже в парке.', 'У нас суворіші закони проти куріння, ніж у Німеччині: курити не можна навіть у парку.', 'Bizde sigaraya karşı Almanya’dakinden daha katı yasalar var: Parkta bile içilemiyor.']),
    mc('Z1', 'Wer hat gewonnen?', I.read, `${BUERGERMEISTERWAHL} Wer hat die Wahl gewonnen?`, ['Ein Kandidat, der zu keiner Partei gehört.', 'Der bisherige Bürgermeister.', 'Niemand, es gibt eine zweite Wahl.'],
      ['Who won the election?', 'Кто победил на выборах?', 'Хто переміг на виборах?', 'Seçimi kim kazandı?']),
    mc('Z2', 'Warum nach Köln?', I.read, `${KAYA} Warum kam die Familie Kaya nach Köln?`, ['Der Vater hatte Arbeit in einer Autofabrik bekommen.', 'Aydin wollte in Köln studieren.', 'Die Familie hatte dort Verwandte.'],
      ['Why did the Kaya family come to Cologne?', 'Почему семья Kaya приехала в Кёльн?', 'Чому родина Kaya приїхала до Кельна?', 'Kaya ailesi neden Köln’e geldi?']),
    gap('G1', 'wurde eröffnet', I.verb, 'Die neue Schule ', ' letzten Sommer von 200 Gästen feierlich eröffnet.', 'wurde', ['wurden', 'würde'],
      ['The new school was ceremonially opened by 200 guests last summer.', 'Новую школу прошлым летом торжественно открыли в присутствии 200 гостей.', 'Нову школу минулого літа урочисто відкрили в присутності 200 гостей.', 'Yeni okul geçen yaz 200 konuğun katılımıyla törenle açıldı.'], WERDEN_PAST),
    gap('G2', 'sind übergeben worden', I.auxiliary, 'Die Unterschriften ', ' dem Bürgermeister schon übergeben worden.', 'sind', ['ist', 'haben'],
      ['The signatures have already been handed over to the mayor.', 'Подписи уже были переданы мэру.', 'Підписи вже було передано мерові.', 'İmzalar belediye başkanına teslim edildi bile.'], 'sein'),
  ],
  size: 13,
  test: [
    mc('W1', 'Diktatur', I.choose, 'In einer … bestimmt eine einzige Person oder Partei alles, und es gibt keine freien Wahlen.', ['Diktatur', 'Demokratie', 'Diskussion'],
      ['In a … one single person or party decides everything, and there are no free elections.', 'При … всё решает один человек или одна партия, и свободных выборов нет.', 'За … усе вирішує одна людина або одна партія, і вільних виборів немає.', 'Bir … her şeye tek bir kişi ya da parti karar verir ve özgür seçimler yoktur.']),
    mc('W1', 'Grenze', I.choose, 'Am 9. November 1989 feierten die Menschen in Berlin die Öffnung der …', ['Grenze', 'Größe', 'Gruppe'],
      ['On 9 November 1989 people in Berlin celebrated the opening of the …', '9 ноября 1989 года люди в Берлине праздновали открытие …', '9 листопада 1989 року люди в Берліні святкували відкриття …', '9 Kasım 1989’da Berlin’de insanlar … açılmasını kutladı.']),
    mc('W2', 'abgestimmt', I.choose, 'Über den Vorschlag wird morgen im Stadtrat … – dann wissen wir, ob die Mehrheit dafür ist.', ['abgestimmt', 'abgeholt', 'abgebogen'],
      ['The proposal will be … on in the town council tomorrow – then we will know whether the majority is in favour.', 'По этому предложению завтра в городском совете будут … – тогда мы узнаем, поддерживает ли его большинство.', 'Щодо цієї пропозиції завтра в міській раді будуть … – тоді ми дізнаємося, чи підтримує її більшість.', 'Öneri yarın belediye meclisinde … – o zaman çoğunluğun lehte olup olmadığını öğreneceğiz.']),
    mc('W2', 'Streik', I.choose, 'Die Arbeiter legen die Arbeit nieder. Der … soll drei Tage dauern.', ['Streik', 'Streit', 'Strich'],
      ['The workers are downing tools. The … is supposed to last three days.', 'Рабочие прекращают работу. … должна продлиться три дня.', 'Робітники припиняють роботу. … має тривати три дні.', 'İşçiler işi bırakıyor. … üç gün sürecek.']),
    mc('G1', 'wurden aufgebaut', I.choose, 'Nach dem Krieg … viele Städte wieder aufgebaut.', ['wurden', 'wurde', 'hatten'],
      ['After the war many towns were rebuilt.', 'После войны многие города были восстановлены.', 'Після війни багато міст було відбудовано.', 'Savaştan sonra birçok şehir yeniden inşa edildi.']),
    mc('G1', 'Aktiv → Passiv', I.choose, 'Wie heißt der Satz im Passiv? „Man eröffnete das Museum 2010.“', ['Das Museum wurde 2010 eröffnet.', 'Das Museum hat 2010 eröffnet.', 'Das Museum wurde 2010 eröffnen.'],
      ['What is the sentence in the passive? “They opened the museum in 2010.”', 'Как будет это предложение в пассиве? «Музей открыли в 2010 году.»', 'Як буде це речення в пасиві? «Музей відкрили 2010 року.»', 'Bu cümlenin edilgen biçimi nedir? “Müzeyi 2010’da açtılar.”']),
    mc('G2', 'ist gesperrt worden', I.choose, 'Die Straße … wegen der Demonstration für zwei Stunden gesperrt worden.', ['ist', 'hat', 'wird'],
      ['The road was closed for two hours because of the demonstration.', 'Из-за демонстрации улицу перекрыли на два часа.', 'Через демонстрацію вулицю перекрили на дві години.', 'Yol gösteri nedeniyle iki saatliğine kapatıldı.']),
    mc('G2', 'bin informiert worden', I.sentence, 'Daniel beschwert sich im Rathaus.', ['Ich bin über die Bauarbeiten nicht informiert worden.', 'Ich habe über die Bauarbeiten nicht informiert worden.', 'Ich bin über die Bauarbeiten nicht informiert geworden.'],
      ['Daniel is complaining at the town hall.', 'Daniel жалуется в ратуше.', 'Daniel скаржиться в ратуші.', 'Daniel belediyede şikâyette bulunuyor.']),
    mc('G3', 'bessere Arbeitsplätze', I.choose, 'Die Partei verspricht … Arbeitsplätze und niedrigere Mieten.', ['bessere', 'besser', 'besseren'],
      ['The party is promising better jobs and lower rents.', 'Партия обещает лучшие рабочие места и более низкую арендную плату.', 'Партія обіцяє кращі робочі місця і нижчу орендну плату.', 'Parti daha iyi iş yerleri ve daha düşük kiralar vaat ediyor.']),
    mc('G3', 'mit einem früheren Bus', I.choose, 'Wir sollten mit einem … Bus fahren, sonst kommen wir zu spät zur Wahlveranstaltung.', ['früheren', 'frühere', 'früher'],
      ['We should take an earlier bus, otherwise we will be late for the election meeting.', 'Нам стоит поехать на более раннем автобусе, иначе мы опоздаем на предвыборное собрание.', 'Нам варто поїхати ранішим автобусом, інакше ми запізнимося на передвиборчі збори.', 'Daha erken bir otobüse binmeliyiz, yoksa seçim toplantısına geç kalırız.']),
    mc('G4', 'das größte Problem', I.choose, 'Das ist das … Problem unserer Stadt: Es gibt zu wenige bezahlbare Wohnungen.', ['größte', 'größten', 'größere'],
      ['That is the biggest problem of our town: there are too few affordable flats.', 'Это самая большая проблема нашего города: слишком мало доступного жилья.', 'Це найбільша проблема нашого міста: надто мало доступного житла.', 'Şehrimizin en büyük sorunu bu: Uygun fiyatlı daire çok az.']),
    mc('G4', 'die meisten Stimmen', I.choose, 'Bei der Wahl bekam die Partei die … Stimmen und stellt jetzt den Bürgermeister.', ['meisten', 'meiste', 'mehr'],
      ['In the election the party received the most votes and now provides the mayor.', 'На выборах партия получила больше всего голосов, и теперь её представитель стал мэром.', 'На виборах партія отримала найбільше голосів, і тепер її представник став мером.', 'Seçimde en çok oyu bu parti aldı ve artık belediye başkanı onlardan.']),
    mc('K1', 'Habt ihr noch Fragen?', I.choose, 'Habt ihr zu diesem Punkt noch …? Wenn nicht, dann machen wir weiter.', ['Fragen', 'Antworten', 'Themen'],
      ['Do you have any more … on this point? If not, we will carry on.', 'У вас есть ещё … по этому пункту? Если нет, мы продолжим.', 'У вас є ще … щодо цього пункту? Якщо ні, ми продовжимо.', 'Bu maddeyle ilgili başka … var mı? Yoksa devam edelim.']),
    mc('K2', 'Davon halte ich nicht viel.', I.choose, 'Davon … ich nicht viel: Verbote allein lösen das Problem nicht.', ['halte', 'hole', 'höre'],
      ['I do not think much of that: bans alone will not solve the problem.', 'Я невысокого мнения об этом: одни запреты проблему не решат.', 'Я невисокої думки про це: самі заборони проблему не розв’яжуть.', 'Bunu pek doğru bulmuyorum: Yasaklar tek başına sorunu çözmez.']),
    mc('K2', 'Ich bin dafür, weil …', I.react, '„Die Innenstadt sollte am Wochenende für Autos gesperrt werden.“', ['Ich bin dafür, weil die Luft dann besser wird.', 'Nun zu seiner Kindheit.', 'Vielen Dank für eure Aufmerksamkeit.'],
      ['“The city centre should be closed to cars at the weekend.”', '«Центр города по выходным следует закрывать для автомобилей.»', '«Центр міста у вихідні слід закривати для автомобілів.»', '“Şehir merkezi hafta sonları arabalara kapatılmalı.”']),
    mc('K3', 'Im Gegensatz zu', I.choose, 'Im Gegensatz … früher können die Menschen heute frei durch ganz Europa reisen.', ['zu', 'von', 'mit'],
      ['In contrast to the past, people today can travel freely all over Europe.', 'В отличие от прошлого, сегодня люди могут свободно путешествовать по всей Европе.', 'На відміну від минулого, сьогодні люди можуть вільно подорожувати всією Європою.', 'Eskisinin aksine insanlar bugün bütün Avrupa’da özgürce seyahat edebiliyor.']),
    mc('Z1', 'Wahlbeteiligung', I.read, `${BUERGERMEISTERWAHL} Wie hoch war die Wahlbeteiligung?`, ['71 Prozent.', '54 Prozent.', '20 Prozent.'],
      ['How high was the turnout?', 'Какой была явка на выборах?', 'Якою була явка на виборах?', 'Seçime katılım oranı ne kadardı?']),
    mc('Z1', 'Versprechen im Wahlkampf', I.read, `${BUERGERMEISTERWAHL} Was hatte Herr Seidel im Wahlkampf versprochen?`, ['Das Schwimmbad zu erhalten und Wohnungen zu bauen.', 'Die Steuern zu senken.', 'Ein neues Rathaus zu bauen.'],
      ['What had Mr Seidel promised during the election campaign?', 'Что господин Seidel обещал во время предвыборной кампании?', 'Що пан Seidel обіцяв під час передвиборчої кампанії?', 'Bay Seidel seçim kampanyasında ne vaat etmişti?']),
    mc('Z1', 'Amtsantritt', I.read, `${BUERGERMEISTERWAHL} Wann beginnt er mit seiner Arbeit als Bürgermeister?`, ['Am 1. Mai.', 'Am Sonntag.', 'In zwanzig Jahren.'],
      ['When does he start his work as mayor?', 'Когда он приступит к работе в должности мэра?', 'Коли він почне працювати на посаді мера?', 'Belediye başkanı olarak görevine ne zaman başlıyor?']),
    mc('Z2', '1995', I.read, `${KAYA} Was machte Herr Kaya 1995?`, ['Er gründete eine eigene Firma.', 'Er kam nach Deutschland.', 'Er bekam einen Preis.'],
      ['What did Mr Kaya do in 1995?', 'Что сделал господин Kaya в 1995 году?', 'Що зробив пан Kaya 1995 року?', 'Bay Kaya 1995’te ne yaptı?']),
    mc('Z2', 'Auszeichnung', I.read, `${KAYA} Wofür ist er ausgezeichnet worden?`, ['Für seine Arbeit im Integrationsrat.', 'Für seine Arbeit in der Autofabrik.', 'Für seine Ausbildung zum Elektriker.'],
      ['What was he honoured for?', 'За что он был награждён?', 'За що його було нагороджено?', 'Hangi çalışması için ödüllendirildi?']),
    gap('W1', 'Wiedervereinigung', I.word, 'Seit der ', ' im Jahr 1990 ist Berlin wieder die Hauptstadt von ganz Deutschland.', 'Wiedervereinigung', ['Wiederholung', 'Wiedergabe'],
      ['Since reunification in 1990 Berlin has again been the capital of the whole of Germany.', 'После воссоединения в 1990 году Берлин снова стал столицей всей Германии.', 'Після возз’єднання 1990 року Берлін знову став столицею всієї Німеччини.', '1990’daki yeniden birleşmeden beri Berlin yine bütün Almanya’nın başkenti.'],
      ['reunification', 'воссоединение', 'возз’єднання', 'yeniden birleşme']),
    gap('W2', 'fordert', I.verb, 'Die Bürgerinitiative ', ', dass vor der Schule eine Ampel gebaut wird.', 'fordert', ['fördert', 'fährt'],
      ['The citizens’ action group is demanding that a set of traffic lights be installed in front of the school.', 'Гражданская инициатива требует, чтобы перед школой установили светофор.', 'Громадянська ініціатива вимагає, щоб перед школою встановили світлофор.', 'Yurttaş girişimi okulun önüne trafik ışığı konulmasını talep ediyor.'], 'fordern'),
    gap('G1', 'wurde gefragt', I.participle, 'Der Minister wurde von Journalisten nach seiner Meinung ', '.', 'gefragt', ['fragen', 'fragte'],
      ['The minister was asked for his opinion by journalists.', 'Журналисты спросили министра о его мнении.', 'Журналісти запитали міністра про його думку.', 'Bakana gazeteciler tarafından görüşü soruldu.'], 'fragen'),
    gap('G2', 'eröffnet worden', I.form, 'Der neue Spielplatz ist am Samstag vom Bürgermeister eröffnet ', '.', 'worden', ['geworden', 'wurden'],
      ['The new playground was opened by the mayor on Saturday.', 'Новую детскую площадку в субботу открыл мэр.', 'Новий дитячий майданчик у суботу відкрив мер.', 'Yeni oyun alanı cumartesi günü belediye başkanı tarafından açıldı.'], 'worden / geworden / wurden'),
    gap('G3', 'eine bessere Zukunft', I.ending, 'Die jungen Leute wünschen sich eine ', ' Zukunft und gehen deshalb auf die Straße.', 'bessere', ['besser', 'besseren'],
      ['The young people wish for a better future and are therefore taking to the streets.', 'Молодые люди хотят лучшего будущего и поэтому выходят на улицы.', 'Молоді люди хочуть кращого майбутнього і тому виходять на вулиці.', 'Gençler daha iyi bir gelecek istiyor ve bu yüzden sokağa çıkıyor.'], 'gut (Komparativ)'),
    gap('G4', 'der jüngste Feiertag', I.ending, 'Der Tag der Deutschen Einheit ist der ', ' Feiertag, der in ganz Deutschland gilt: Es gibt ihn erst seit 1990.', 'jüngste', ['jüngsten', 'jünger'],
      ['The Day of German Unity is the youngest public holiday that applies throughout Germany: it has only existed since 1990.', 'День германского единства – самый молодой праздник, который отмечается по всей Германии: он существует только с 1990 года.', 'День німецької єдності – наймолодше свято, яке відзначають по всій Німеччині: воно існує лише з 1990 року.', 'Alman Birliği Günü bütün Almanya’da geçerli olan en yeni resmî tatildir: Ancak 1990’dan beri var.'], 'jung (Superlativ)'),
    gap('K1', 'Thema', I.word, 'Unser heutiges ', ' ist die Geschichte der Gastarbeiter in Deutschland.', 'Thema', ['Theater', 'Tempo'],
      ['Our topic today is the history of the guest workers in Germany.', 'Наша сегодняшняя тема – история гастарбайтеров в Германии.', 'Наша сьогоднішня тема – історія гастарбайтерів у Німеччині.', 'Bugünkü konumuz Almanya’daki misafir işçilerin tarihi.'],
      ['topic', 'тема', 'тема', 'konu']),
    gap('K2', 'gegen', I.prep, 'Ich bin ', ' ein Handyverbot an Schulen, weil die Schüler dann nur heimlich telefonieren.', 'gegen', ['für', 'mit'],
      ['I am against a ban on mobile phones at schools because then the pupils will just use them in secret.', 'Я против запрета мобильных телефонов в школах, потому что тогда ученики будут просто пользоваться ими тайком.', 'Я проти заборони мобільних телефонів у школах, бо тоді учні просто користуватимуться ними потай.', 'Okullarda cep telefonu yasağına karşıyım, çünkü o zaman öğrenciler telefonlarını gizlice kullanır.'], 'gegen / für / mit'),
    gap('K3', 'anders als', I.word, 'Das Wahlrecht ist bei uns anders ', ' in Deutschland: Man muss wählen gehen.', 'als', ['wie', 'so'],
      ['Electoral law in my country is different from Germany: you have to go and vote.', 'Избирательное право у нас иное, чем в Германии: голосовать обязательно.', 'Виборче право в нас інше, ніж у Німеччині: голосувати обов’язково.', 'Bizde seçim hukuku Almanya’dakinden farklı: Oy kullanmak zorunlu.'], 'als / wie / so'),
  ],
}

export default check
