import { I, gap, mc, sb } from '../shared.mjs'

const SKATEPARK = 'Zeitungsmeldung: „Rund 50 Kinder und Jugendliche demonstrierten am Freitag vor dem Rathaus von Neustadt. Sie fordern, dass der Skatepark nicht geschlossen wird. Die Anlage war im Frühjahr wegen Lärmbeschwerden gesperrt worden. Der Bürgermeister nahm 800 Unterschriften entgegen und versprach eine Lösung. Im September soll im Stadtrat abgestimmt werden.“'
const RHEINBRUECKE = 'Zeitungsmeldung: „Nach zwei Jahren Bauzeit ist die neue Rheinbrücke am Montag eröffnet worden. Sie ist 400 Meter lang und damit die längste Brücke der Region. Gebaut wurde sie für Fußgänger und Radfahrer; Autos dürfen sie nicht benutzen. Die Kosten waren höher als geplant: Statt 12 Millionen Euro wurden 15 Millionen ausgegeben. Trotzdem ist die Mehrheit der Bürger laut einer Umfrage zufrieden.“'
const ARCHIVAR = 'Reportage: „Mit seinen 81 Jahren steht Walter Krause jeden Dienstag im Stadtarchiv. Geboren wurde er 1944 in Dresden. Nach dem Krieg wuchs er in der DDR auf und wurde Lehrer für Geschichte. 1989 demonstrierte er mit Tausenden für freie Wahlen. Nach der Wiedervereinigung wurde er in den Stadtrat gewählt, wo er sich vor allem für Schulen einsetzte. Heute führt er Schulklassen durch das Archiv. ‚Wer die Geschichte kennt, versteht die Gegenwart besser‘, sagt er.“'
const NACHKRIEGSZEIT = 'Vortrag: „Nach dem Zweiten Weltkrieg wurde Deutschland in vier Zonen geteilt. Aus den drei Westzonen wurde 1949 die Bundesrepublik, aus der Ostzone die DDR. Im Westen begann bald das sogenannte Wirtschaftswunder: Es wurden viele Arbeitskräfte gebraucht, deshalb kamen ab 1955 Menschen aus Italien, der Türkei und anderen Ländern. 1961 wurde in Berlin die Mauer gebaut. Erst 28 Jahre später, im November 1989, wurde die Grenze wieder geöffnet.“'
const WERDEN_PAST = 'werden (Präteritum)'

/** B1.2 · Pfad 6 · Politik und Geschichte – Lektionen. Wiederholung und Test: p6-check.mjs */
const path = {
  n: 6,
  slug: 'politik-und-geschichte',
  title: 'Politik und Geschichte',
  t: ['Politics and history', 'Политика и история', 'Політика та історія', 'Siyaset ve tarih'],
  objectives: {
    G1: 'Passiv Präteritum: wurde + Partizip II (Die Mauer wurde 1961 gebaut. Er wurde zum Bürgermeister gewählt).',
    G2: 'Passiv Perfekt: sein + Partizip II + worden (1975 ist ein Lernhilfeverein gegründet worden).',
    G3: 'Adjektivdeklination mit Komparativ: der größere Teil, ein größeres Problem, höhere Löhne, mit einem besseren Angebot.',
    G4: 'Adjektivdeklination mit Superlativ: der größte Teil, das größte Problem, die meisten Bürger, in der größten Stadt.',
    K1: 'Etwas präsentieren – Einleitung, Überleitung, Schluss: Unser heutiges Thema ist … Der nächste Punkt ist … Vielen Dank für eure Aufmerksamkeit.',
    K2: 'Etwas bewerten: Ich bin für / gegen …, weil … Davon halte ich (nicht) viel. Das kann ich nur befürworten / ablehnen.',
    K3: 'Etwas vergleichen: Das ist bei uns nicht so streng wie … / strenger als … Im Gegensatz zu … Verglichen mit …',
    Z1: 'Kann-Ziele: Zeitungsmeldungen über Politik und Stadtleben verstehen.',
    Z2: 'Kann-Ziele: eine Reportage über eine Person und einen Vortrag zur deutschen Nachkriegsgeschichte verstehen.',
    W1: 'Wortschatz: deutsche Geschichte (Teilung, Berliner Mauer, Grenze, Wiedervereinigung, Grundgesetz, Demokratie, Frieden).',
    W2: 'Wortschatz: politisches Engagement (wählen, abstimmen, Mehrheit, demonstrieren, protestieren, fordern, streiken, Bürgerinitiative).',
  },
  nodes: [
    {
      title: 'Deutsche Geschichte',
      t: ['German history', 'История Германии', 'Історія Німеччини', 'Alman tarihi'],
      card: {
        id: 'p6_geschichte',
        rule: 'Deutsche Geschichte nach 1945: Nach dem Zweiten Weltkrieg wurde Deutschland geteilt (die Teilung). 1949 wurden zwei Staaten gegründet: die Bundesrepublik Deutschland (BRD) im Westen und die Deutsche Demokratische Republik (DDR) im Osten. Das Grundgesetz ist die Verfassung der Bundesrepublik. 1961 baute die DDR die Berliner Mauer; die Grenze war geschlossen. 1989 fiel die Mauer (der Mauerfall). Am 3. Oktober 1990 kam die Wiedervereinigung. Die Demokratie ↔ die Diktatur; der Krieg ↔ der Frieden.',
        examples: ['Die Berliner Mauer fiel am 9. November 1989.', 'Seit der Wiedervereinigung ist der 3. Oktober ein Feiertag.', 'Das Grundgesetz gilt seit 1949.'],
        highlight: 'article',
        t: [
          'German history after 1945: after the Second World War Germany was divided (die Teilung = division). In 1949 two states were founded: the Federal Republic of Germany (die Bundesrepublik Deutschland, BRD) in the west and the German Democratic Republic (DDR) in the east. Das Grundgesetz (Basic Law) is the constitution of the Federal Republic. In 1961 the DDR built the Berlin Wall (die Berliner Mauer); die Grenze (border) was closed. In 1989 the Wall fell (der Mauerfall). On 3 October 1990 came die Wiedervereinigung (reunification). Die Demokratie (democracy) ↔ die Diktatur (dictatorship); der Krieg (war) ↔ der Frieden (peace).',
          'История Германии после 1945 года: после Второй мировой войны Германия была разделена (die Teilung = разделение). В 1949 году были основаны два государства: Федеративная Республика Германия (die Bundesrepublik Deutschland, BRD) на западе и Германская Демократическая Республика (DDR) на востоке. Das Grundgesetz (Основной закон) – это конституция ФРГ. В 1961 году ГДР построила Берлинскую стену (die Berliner Mauer); die Grenze (граница) была закрыта. В 1989 году стена пала (der Mauerfall). 3 октября 1990 года произошло die Wiedervereinigung (воссоединение). Die Demokratie (демократия) ↔ die Diktatur (диктатура); der Krieg (война) ↔ der Frieden (мир).',
          'Історія Німеччини після 1945 року: після Другої світової війни Німеччину було поділено (die Teilung = поділ). 1949 року було засновано дві держави: Федеративну Республіку Німеччина (die Bundesrepublik Deutschland, BRD) на заході та Німецьку Демократичну Республіку (DDR) на сході. Das Grundgesetz (Основний закон) – це конституція ФРН. 1961 року НДР збудувала Берлінський мур (die Berliner Mauer); die Grenze (кордон) було закрито. 1989 року мур упав (der Mauerfall). 3 жовтня 1990 року відбулося die Wiedervereinigung (возз’єднання). Die Demokratie (демократія) ↔ die Diktatur (диктатура); der Krieg (війна) ↔ der Frieden (мир).',
          '1945’ten sonra Alman tarihi: İkinci Dünya Savaşı’ndan sonra Almanya bölündü (die Teilung = bölünme). 1949’da iki devlet kuruldu: batıda Almanya Federal Cumhuriyeti (die Bundesrepublik Deutschland, BRD), doğuda Alman Demokratik Cumhuriyeti (DDR). Das Grundgesetz (Temel Yasa) Federal Cumhuriyet’in anayasasıdır. 1961’de DDR Berlin Duvarı’nı (die Berliner Mauer) inşa etti; die Grenze (sınır) kapalıydı. 1989’da Duvar yıkıldı (der Mauerfall). 3 Ekim 1990’da die Wiedervereinigung (yeniden birleşme) gerçekleşti. Die Demokratie (demokrasi) ↔ die Diktatur (diktatörlük); der Krieg (savaş) ↔ der Frieden (barış).',
        ],
        hint: ['1949: BRD und DDR. 1961: Mauer. 1989: Mauerfall. 1990: Wiedervereinigung. Teilung ↔ Wiedervereinigung, Krieg ↔ Frieden.', '1949: BRD and DDR. 1961: the Wall. 1989: fall of the Wall. 1990: reunification. Teilung ↔ Wiedervereinigung, Krieg ↔ Frieden.', '1949: ФРГ и ГДР. 1961: стена. 1989: падение стены. 1990: воссоединение. Teilung ↔ Wiedervereinigung, Krieg ↔ Frieden.', '1949: ФРН і НДР. 1961: мур. 1989: падіння муру. 1990: возз’єднання. Teilung ↔ Wiedervereinigung, Krieg ↔ Frieden.', '1949: BRD ve DDR. 1961: Duvar. 1989: Duvar’ın yıkılışı. 1990: yeniden birleşme. Teilung ↔ Wiedervereinigung, Krieg ↔ Frieden.'],
      },
      ex: [
        mc('W1', 'Wiedervereinigung', I.choose, 'Seit dem 3. Oktober 1990 sind Ost- und Westdeutschland wieder ein Staat. Dieses Ereignis nennt man die …', ['Wiedervereinigung', 'Wiederholung', 'Wiedergabe'],
          ['Since 3 October 1990 East and West Germany have been one state again. This event is called …', 'С 3 октября 1990 года Восточная и Западная Германия снова одно государство. Это событие называют …', 'Від 3 жовтня 1990 року Східна і Західна Німеччина знову одна держава. Цю подію називають …', '3 Ekim 1990’dan beri Doğu ve Batı Almanya yeniden tek bir devlet. Bu olaya … denir.']),
        mc('W1', 'Berliner Mauer', I.choose, 'Von 1961 bis 1989 trennte die Berliner … den Ost- und den Westteil der Stadt.', ['Mauer', 'Messe', 'Miete'],
          ['From 1961 to 1989 the Berlin … separated the eastern and western parts of the city.', 'С 1961 по 1989 год Берлинская … разделяла восточную и западную части города.', 'З 1961 до 1989 року Берлінський … розділяв східну й західну частини міста.', '1961’den 1989’a kadar Berlin … şehrin doğu ve batı kesimlerini ayırıyordu.']),
        mc('W1', 'deutsche Teilung', I.odd, 'Drei Wörter passen zum Thema deutsche Teilung, ein Wort nicht.', ['die Lieferung', 'die Grenze', 'die Mauer', 'die Wiedervereinigung'], null),
        mc('W1', 'Demokratie', I.choose, 'In einer … wählen die Bürger ihre Regierung frei und dürfen ihre Meinung offen sagen.', ['Demokratie', 'Diktatur', 'Demonstration'],
          ['In a … the citizens elect their government freely and may say what they think openly.', 'При … граждане свободно выбирают правительство и могут открыто высказывать своё мнение.', 'За … громадяни вільно обирають уряд і можуть відкрито висловлювати свою думку.', 'Bir … yurttaşlar hükümetlerini özgürce seçer ve düşüncelerini açıkça söyleyebilir.']),
        mc('W1', 'Grundgesetz', I.choose, 'Die Verfassung der Bundesrepublik Deutschland heißt …', ['Grundgesetz', 'Grundstück', 'Grundschule'],
          ['The constitution of the Federal Republic of Germany is called …', 'Конституция Федеративной Республики Германия называется …', 'Конституція Федеративної Республіки Німеччина називається …', 'Almanya Federal Cumhuriyeti’nin anayasasının adı …']),
        mc('W1', 'Frieden', I.choose, 'Nach vielen Jahren Krieg wünschten sich die Menschen nur noch eines: endlich …', ['Frieden', 'Freizeit', 'Frühling'],
          ['After many years of war people wished for only one thing: … at last.', 'После многих лет войны люди хотели только одного: наконец …', 'Після багатьох років війни люди хотіли тільки одного: нарешті …', 'Yıllarca süren savaştan sonra insanlar yalnızca bir şey istiyordu: nihayet …']),
        gap('W1', 'Grenze', I.word, 'Bis 1989 war die ', ' zwischen den beiden deutschen Staaten streng bewacht.', 'Grenze', ['Größe', 'Gruppe'],
          ['Until 1989 the border between the two German states was strictly guarded.', 'До 1989 года граница между двумя немецкими государствами строго охранялась.', 'До 1989 року кордон між двома німецькими державами суворо охоронявся.', '1989’a kadar iki Alman devleti arasındaki sınır sıkı biçimde korunuyordu.'],
          ['border', 'граница', 'кордон', 'sınır']),
        gap('W1', 'gegründet', I.participle, 'Die Bundesrepublik Deutschland wurde im Jahr 1949 ', '.', 'gegründet', ['gegrüßt', 'gegraben'],
          ['The Federal Republic of Germany was founded in 1949.', 'Федеративная Республика Германия была основана в 1949 году.', 'Федеративну Республіку Німеччина було засновано 1949 року.', 'Almanya Federal Cumhuriyeti 1949 yılında kuruldu.'], 'gründen'),
        gap('W1', 'Teilung', I.word, 'Die ', ' Deutschlands dauerte mehr als vierzig Jahre.', 'Teilung', ['Teilnahme', 'Zeitung'],
          ['The division of Germany lasted more than forty years.', 'Разделение Германии длилось более сорока лет.', 'Поділ Німеччини тривав понад сорок років.', 'Almanya’nın bölünmüşlüğü kırk yıldan fazla sürdü.'],
          ['division', 'разделение', 'поділ', 'bölünme']),
        sb('W1', 'Die Mauer fiel 1989.', I.order, 'Die Berliner Mauer / fiel / im November / 1989.',
          ['The Berlin Wall fell in November 1989.', 'Берлинская стена пала в ноябре 1989 года.', 'Берлінський мур упав у листопаді 1989 року.', 'Berlin Duvarı Kasım 1989’da yıkıldı.'],
          { alt: ['Im November 1989 fiel die Berliner Mauer.'] }),
      ],
    },
    {
      title: 'Wählen, fordern, protestieren',
      t: ['Voting, demanding, protesting', 'Голосовать, требовать, протестовать', 'Голосувати, вимагати, протестувати', 'Oy vermek, talep etmek, protesto etmek'],
      card: {
        id: 'p6_politik',
        rule: 'Politisches Engagement: wählen = bei einer Wahl seine Stimme abgeben. Die Partei = eine politische Gruppe. Die Mehrheit = mehr als die Hälfte. abstimmen = gemeinsam entscheiden: dafür ↔ dagegen stimmen. demonstrieren oder protestieren gegen + Akkusativ = öffentlich zeigen, dass man nicht einverstanden ist (die Demonstration, der Protest). fordern = etwas verlangen (die Forderung). streiken = aus Protest nicht arbeiten (der Streik). Die Bürgerinitiative = Bürger setzen sich gemeinsam für ein Ziel ein und sammeln zum Beispiel Unterschriften.',
        examples: ['Tausende demonstrierten gegen die Schließung des Schwimmbads.', 'Die Mehrheit stimmte für den neuen Spielplatz.', 'Die Bürgerinitiative sammelte 5000 Unterschriften.'],
        highlight: null,
        t: [
          'Political involvement: wählen = to vote, to cast your vote in an election (die Wahl). Die Partei = a political party. Die Mehrheit (majority) = more than half. abstimmen = to vote on something, to decide together: dafür ↔ dagegen stimmen (to vote for ↔ against). demonstrieren or protestieren gegen + accusative = to show publicly that you do not agree (die Demonstration, der Protest). fordern = to demand (die Forderung = demand). streiken = to go on strike, not to work as a protest (der Streik). Die Bürgerinitiative = citizens’ action group: citizens work together for a goal and collect signatures (Unterschriften), for example.',
          'Политическая активность: wählen = голосовать, отдавать свой голос на выборах (die Wahl). Die Partei = политическая партия. Die Mehrheit (большинство) = больше половины. abstimmen = голосовать по вопросу, решать вместе: dafür ↔ dagegen stimmen (голосовать за ↔ против). demonstrieren или protestieren gegen + аккузатив = публично показывать несогласие (die Demonstration, der Protest). fordern = требовать (die Forderung = требование). streiken = бастовать, не работать в знак протеста (der Streik). Die Bürgerinitiative = гражданская инициатива: граждане вместе добиваются цели и, например, собирают подписи (Unterschriften).',
          'Політична активність: wählen = голосувати, віддавати свій голос на виборах (die Wahl). Die Partei = політична партія. Die Mehrheit (більшість) = більше половини. abstimmen = голосувати з певного питання, вирішувати разом: dafür ↔ dagegen stimmen (голосувати за ↔ проти). demonstrieren або protestieren gegen + акузатив = публічно показувати незгоду (die Demonstration, der Protest). fordern = вимагати (die Forderung = вимога). streiken = страйкувати, не працювати на знак протесту (der Streik). Die Bürgerinitiative = громадянська ініціатива: громадяни разом домагаються мети і, наприклад, збирають підписи (Unterschriften).',
          'Siyasi katılım: wählen = oy vermek, bir seçimde (die Wahl) oyunu kullanmak. Die Partei = siyasi parti. Die Mehrheit (çoğunluk) = yarıdan fazlası. abstimmen = oylamak, birlikte karar vermek: dafür ↔ dagegen stimmen (lehte ↔ aleyhte oy vermek). demonstrieren ya da protestieren gegen + Akkusativ = aynı fikirde olmadığını açıkça göstermek (die Demonstration, der Protest). fordern = talep etmek (die Forderung = talep). streiken = grev yapmak, protesto için çalışmamak (der Streik). Die Bürgerinitiative = yurttaş girişimi: Yurttaşlar bir amaç için birlikte çalışır ve örneğin imza (Unterschriften) toplar.',
        ],
        hint: ['wählen → die Wahl. abstimmen: dafür ↔ dagegen. Mehrheit = mehr als die Hälfte. fordern = verlangen. streiken = aus Protest nicht arbeiten.', 'wählen → die Wahl. abstimmen: for ↔ against. Mehrheit = more than half. fordern = to demand. streiken = not to work as a protest.', 'wählen → die Wahl. abstimmen: за ↔ против. Mehrheit = больше половины. fordern = требовать. streiken = не работать в знак протеста.', 'wählen → die Wahl. abstimmen: за ↔ проти. Mehrheit = більше половини. fordern = вимагати. streiken = не працювати на знак протесту.', 'wählen → die Wahl. abstimmen: lehte ↔ aleyhte. Mehrheit = yarıdan fazlası. fordern = talep etmek. streiken = protesto için çalışmamak.'],
      },
      ex: [
        mc('W2', 'demonstrieren', I.choose, 'Rund 500 Schüler … gestern vor dem Rathaus für mehr Klimaschutz.', ['demonstrierten', 'dekorierten', 'diktierten'],
          ['Around 500 pupils … in front of the town hall yesterday for more climate protection.', 'Около 500 школьников вчера … перед ратушей, требуя лучше защищать климат.', 'Близько 500 школярів учора … перед ратушею, вимагаючи краще захищати клімат.', 'Yaklaşık 500 öğrenci dün belediye binasının önünde iklimin daha iyi korunması için … .']),
        mc('W2', 'Mehrheit', I.choose, 'Bei der Abstimmung waren 70 Prozent dafür. Die … war also für den Vorschlag.', ['Mehrheit', 'Minderheit', 'Meinung'],
          ['In the vote 70 per cent were in favour. So the … was for the proposal.', 'При голосовании 70 процентов были за. Значит, … поддержало предложение.', 'Під час голосування 70 відсотків були за. Отже, … підтримала пропозицію.', 'Oylamada yüzde 70 lehteydi. Demek ki … öneriden yanaydı.']),
        mc('W2', 'streiken', I.choose, 'Die Busfahrer verlangen höhere Löhne. Deshalb … sie morgen, und kein Bus fährt.', ['streiken', 'streiten', 'streichen'],
          ['The bus drivers are demanding higher wages. That is why they are going to … tomorrow, and no bus will run.', 'Водители автобусов требуют повышения зарплаты. Поэтому завтра они …, и ни один автобус не выйдет на линию.', 'Водії автобусів вимагають підвищення зарплати. Тому завтра вони …, і жоден автобус не вийде на лінію.', 'Otobüs şoförleri daha yüksek ücret istiyor. Bu yüzden yarın … ve hiçbir otobüs çalışmayacak.']),
        mc('W2', 'Bürgerinitiative', I.choose, 'Die Anwohner wollen keine neue Schnellstraße. Sie haben eine … gegründet und sammeln Unterschriften.', ['Bürgerinitiative', 'Bürgersteig', 'Bürgerbüro'],
          ['The residents do not want a new expressway. They have founded a … and are collecting signatures.', 'Местные жители не хотят новой скоростной дороги. Они создали … и собирают подписи.', 'Місцеві мешканці не хочуть нової швидкісної дороги. Вони створили … і збирають підписи.', 'Bölge sakinleri yeni bir ekspres yol istemiyor. Bir … kurdular ve imza topluyorlar.']),
        mc('W2', 'fordern', I.choose, 'Die Gewerkschaft … fünf Prozent mehr Lohn für alle Beschäftigten.', ['fordert', 'fördert', 'folgt'],
          ['The trade union is … five per cent more pay for all employees.', 'Профсоюз … повышения зарплаты на пять процентов для всех работников.', 'Профспілка … підвищення зарплати на п’ять відсотків для всіх працівників.', 'Sendika bütün çalışanlar için yüzde beş zam … .']),
        mc('W2', 'Partei', I.choose, 'Bei der Bundestagswahl kann man einen Kandidaten und eine … wählen.', ['Partei', 'Party', 'Partie'],
          ['In the Bundestag election you can vote for a candidate and a …', 'На выборах в бундестаг можно проголосовать за кандидата и за …', 'На виборах до бундестагу можна проголосувати за кандидата і за …', 'Federal Meclis seçiminde bir adaya ve bir … oy verilebilir.']),
        gap('W2', 'Wahl', I.word, 'Bei der letzten ', ' zum Stadtrat gingen nur 48 Prozent der Bürger wählen.', 'Wahl', ['Wahrheit', 'Ware'],
          ['In the last election to the town council only 48 per cent of citizens went to vote.', 'На последних выборах в городской совет проголосовали только 48 процентов граждан.', 'На останніх виборах до міської ради проголосували лише 48 відсотків громадян.', 'Son belediye meclisi seçiminde yurttaşların yalnızca yüzde 48’i oy kullandı.'],
          ['election', 'выборы', 'вибори', 'seçim']),
        gap('W2', 'Unterschriften', I.word, 'Für den Erhalt der Bibliothek hat die Initiative über 3000 ', ' gesammelt.', 'Unterschriften', ['Unterkünfte', 'Unterlagen'],
          ['The action group has collected over 3,000 signatures to save the library.', 'За сохранение библиотеки инициативная группа собрала более 3000 подписей.', 'За збереження бібліотеки ініціативна група зібрала понад 3000 підписів.', 'Girişim, kütüphanenin korunması için 3000’den fazla imza topladı.'],
          ['signatures', 'подписи', 'підписи', 'imzalar']),
        gap('W2', 'protestieren', I.word, 'Die Studenten ', ' gegen die höheren Gebühren und fordern ein Gespräch mit dem Minister.', 'protestieren', ['probieren', 'produzieren'],
          ['The students are protesting against the higher fees and demanding a meeting with the minister.', 'Студенты протестуют против повышения платы и требуют встречи с министром.', 'Студенти протестують проти підвищення плати і вимагають зустрічі з міністром.', 'Öğrenciler harçların artmasını protesto ediyor ve bakanla görüşme talep ediyor.'],
          ['to protest', 'протестовать', 'протестувати', 'protesto etmek']),
        sb('W2', 'für etwas stimmen', I.order, 'Die Mehrheit / stimmte / für / den neuen Spielplatz.',
          ['The majority voted for the new playground.', 'Большинство проголосовало за новую детскую площадку.', 'Більшість проголосувала за новий дитячий майданчик.', 'Çoğunluk yeni oyun alanı için oy kullandı.'],
          { alt: ['Für den neuen Spielplatz stimmte die Mehrheit.'] }),
      ],
    },
    {
      title: 'wurde gewählt',
      t: ['wurde gewählt (passive in the Präteritum)', 'wurde gewählt (пассив в Präteritum)', 'wurde gewählt (пасив у Präteritum)', 'wurde gewählt (Präteritum’da edilgen çatı)'],
      card: {
        id: 'p6_passiv_praeteritum',
        rule: 'Passiv Präteritum: wurde + Partizip II. Wichtig ist, was passiert ist – nicht, wer es getan hat. ich wurde, du wurdest, er/es/sie wurde, wir wurden, ihr wurdet, sie/Sie wurden + Partizip am Satzende: Er wurde zum Bürgermeister gewählt. Die Mauer wurde 1961 gebaut. Die Demonstranten wurden von der Polizei begleitet. Die handelnde Person nennt man mit von + Dativ. In Berichten und Zeitungsmeldungen steht meistens das Passiv Präteritum.',
        examples: ['Der Verein wurde 1975 gegründet.', 'Die Schule wurde im letzten Jahr renoviert.', 'Die Gäste wurden vom Bürgermeister begrüßt.'],
        highlight: 'verb',
        t: [
          'Passive in the Präteritum: wurde + past participle. What matters is what happened – not who did it. ich wurde, du wurdest, er/es/sie wurde, wir wurden, ihr wurdet, sie/Sie wurden + participle at the end of the sentence: Er wurde zum Bürgermeister gewählt (he was elected mayor). Die Mauer wurde 1961 gebaut. Die Demonstranten wurden von der Polizei begleitet. The person who acts is named with von + dative. Reports and newspaper items mostly use the passive in the Präteritum.',
          'Пассив в Präteritum: wurde + Partizip II. Важно то, что произошло, а не кто это сделал. ich wurde, du wurdest, er/es/sie wurde, wir wurden, ihr wurdet, sie/Sie wurden + причастие в конце предложения: Er wurde zum Bürgermeister gewählt (его избрали мэром). Die Mauer wurde 1961 gebaut. Die Demonstranten wurden von der Polizei begleitet. Действующее лицо называют с помощью von + датив. В отчётах и газетных заметках чаще всего используется пассив в Präteritum.',
          'Пасив у Präteritum: wurde + Partizip II. Важливо те, що сталося, а не хто це зробив. ich wurde, du wurdest, er/es/sie wurde, wir wurden, ihr wurdet, sie/Sie wurden + дієприкметник у кінці речення: Er wurde zum Bürgermeister gewählt (його обрали мером). Die Mauer wurde 1961 gebaut. Die Demonstranten wurden von der Polizei begleitet. Діючу особу називають за допомогою von + датів. У звітах і газетних замітках найчастіше вживають пасив у Präteritum.',
          'Präteritum’da edilgen çatı: wurde + Partizip II. Önemli olan ne olduğudur – kimin yaptığı değil. ich wurde, du wurdest, er/es/sie wurde, wir wurden, ihr wurdet, sie/Sie wurden + cümle sonunda Partizip: Er wurde zum Bürgermeister gewählt (belediye başkanı seçildi). Die Mauer wurde 1961 gebaut. Die Demonstranten wurden von der Polizei begleitet. Eylemi yapan kişi von + Dativ ile belirtilir. Raporlarda ve gazete haberlerinde çoğunlukla Präteritum’daki edilgen çatı kullanılır.',
        ],
        hint: ['Passiv Präteritum = wurde / wurden + Partizip II am Ende: wurde gebaut, wurden gewählt. Wer? → von + Dativ.', 'Passive in the Präteritum = wurde / wurden + past participle at the end: wurde gebaut, wurden gewählt. By whom? → von + dative.', 'Пассив в Präteritum = wurde / wurden + Partizip II в конце: wurde gebaut, wurden gewählt. Кем? → von + датив.', 'Пасив у Präteritum = wurde / wurden + Partizip II у кінці: wurde gebaut, wurden gewählt. Ким? → von + датів.', 'Präteritum’da edilgen = wurde / wurden + sonda Partizip II: wurde gebaut, wurden gewählt. Kim tarafından? → von + Dativ.'],
      },
      ex: [
        mc('G1', 'wurde gegründet', I.choose, 'Die Bundesrepublik Deutschland … 1949 gegründet.', ['wurde', 'wurden', 'wird'],
          ['The Federal Republic of Germany was founded in 1949.', 'Федеративная Республика Германия была основана в 1949 году.', 'Федеративну Республіку Німеччина було засновано 1949 року.', 'Almanya Federal Cumhuriyeti 1949’da kuruldu.']),
        mc('G1', 'wurden verletzt', I.choose, 'Bei dem Unfall auf der Demonstration … zwei Personen leicht verletzt.', ['wurden', 'wurde', 'werden'],
          ['Two people were slightly injured in the accident at the demonstration.', 'При происшествии на демонстрации два человека получили лёгкие травмы.', 'Під час пригоди на демонстрації двоє людей дістали легкі травми.', 'Gösterideki kazada iki kişi hafif yaralandı.']),
        mc('G1', 'wurde gewählt', I.choose, 'Der neue Bürgermeister wurde mit großer Mehrheit …', ['gewählt', 'wählen', 'wählte'],
          ['The new mayor was elected by a large majority.', 'Новый мэр был избран подавляющим большинством голосов.', 'Нового мера було обрано переважною більшістю голосів.', 'Yeni belediye başkanı büyük bir çoğunlukla seçildi.']),
        mc('G1', 'wurde + Partizip am Ende', I.sentence, 'Ein Satz aus einer Zeitungsmeldung.', ['Die Brücke wurde gestern wieder geöffnet.', 'Die Brücke wurde gestern wieder öffnen.', 'Die Brücke gestern wurde wieder geöffnet.'],
          ['A sentence from a newspaper report.', 'Предложение из газетной заметки.', 'Речення з газетної замітки.', 'Bir gazete haberinden bir cümle.']),
        mc('G1', 'Aktiv → Passiv', I.choose, 'Wie heißt der Satz im Passiv? „Man baute die Mauer 1961.“', ['Die Mauer wurde 1961 gebaut.', 'Die Mauer hat 1961 gebaut.', 'Die Mauer baute 1961.'],
          ['What is the sentence in the passive? “They built the Wall in 1961.”', 'Как будет это предложение в пассиве? «Стену построили в 1961 году.»', 'Як буде це речення в пасиві? «Мур збудували 1961 року.»', 'Bu cümlenin edilgen biçimi nedir? “Duvar’ı 1961’de inşa ettiler.”']),
        mc('G1', 'vom Bürgermeister', I.choose, 'Die Ausstellung wurde … Bürgermeister eröffnet.', ['vom', 'mit dem', 'für den'],
          ['The exhibition was opened by the mayor.', 'Выставку открыл мэр.', 'Виставку відкрив мер.', 'Sergi belediye başkanı tarafından açıldı.']),
        gap('G1', 'wurden gestohlen', I.verb, 'In der Nacht ', ' drei Fahrräder aus dem Keller gestohlen.', 'wurden', ['wurde', 'wurdet'],
          ['During the night three bicycles were stolen from the cellar.', 'Ночью из подвала были украдены три велосипеда.', 'Уночі з підвалу було вкрадено три велосипеди.', 'Gece bodrumdan üç bisiklet çalındı.'], WERDEN_PAST),
        gap('G1', 'wurde unterschrieben', I.verb, 'Der Vertrag ', ' gestern von beiden Firmen unterschrieben.', 'wurde', ['wurden', 'würde'],
          ['The contract was signed by both companies yesterday.', 'Договор был вчера подписан обеими фирмами.', 'Договір було вчора підписано обома фірмами.', 'Sözleşme dün iki şirket tarafından imzalandı.'], WERDEN_PAST),
        gap('G1', 'wurde zerstört', I.participle, 'Das Rathaus wurde im Krieg ', ' und später neu aufgebaut.', 'zerstört', ['zerstören', 'zerstörte'],
          ['The town hall was destroyed in the war and later rebuilt.', 'Ратуша была разрушена во время войны, а позже отстроена заново.', 'Ратушу було зруйновано під час війни, а пізніше відбудовано заново.', 'Belediye binası savaşta yıkıldı ve sonradan yeniden inşa edildi.'], 'zerstören'),
        sb('G1', 'wurde renoviert', I.order, 'Die Schule / wurde / im letzten Jahr / renoviert.',
          ['The school was renovated last year.', 'Школу отремонтировали в прошлом году.', 'Школу відремонтували торік.', 'Okul geçen yıl yenilendi.'],
          { alt: ['Im letzten Jahr wurde die Schule renoviert.'] }),
      ],
    },
    {
      title: 'ist gegründet worden',
      t: ['ist gegründet worden (passive in the Perfekt)', 'ist gegründet worden (пассив в Perfekt)', 'ist gegründet worden (пасив у Perfekt)', 'ist gegründet worden (Perfekt’te edilgen çatı)'],
      card: {
        id: 'p6_passiv_perfekt',
        rule: 'Passiv Perfekt: sein + Partizip II + worden. Ich bin gefragt worden, du bist gefragt worden, er/es/sie ist gefragt worden, wir sind gefragt worden, ihr seid gefragt worden, sie/Sie sind gefragt worden. 1975 ist ein Lernhilfeverein gegründet worden. Die Rechnung ist schon bezahlt worden. Achtung: Im Passiv heißt es worden – ohne ge-. geworden ist das Partizip von werden als Vollverb: Er ist Lehrer geworden. Im Gespräch benutzt man oft das Passiv Perfekt, in Texten das Passiv Präteritum.',
        examples: ['Das Paket ist gestern geliefert worden.', 'Wir sind nicht informiert worden.', 'Die Straße ist letzte Woche gesperrt worden.'],
        highlight: 'verb',
        t: [
          'Passive in the Perfekt: sein + past participle + worden. Ich bin gefragt worden, du bist gefragt worden, er/es/sie ist gefragt worden, wir sind gefragt worden, ihr seid gefragt worden, sie/Sie sind gefragt worden. 1975 ist ein Lernhilfeverein gegründet worden. Die Rechnung ist schon bezahlt worden. Careful: in the passive the form is worden – without ge-. geworden is the participle of werden as a full verb: Er ist Lehrer geworden (he has become a teacher). In conversation people often use the passive in the Perfekt, in texts the passive in the Präteritum.',
          'Пассив в Perfekt: sein + Partizip II + worden. Ich bin gefragt worden, du bist gefragt worden, er/es/sie ist gefragt worden, wir sind gefragt worden, ihr seid gefragt worden, sie/Sie sind gefragt worden. 1975 ist ein Lernhilfeverein gegründet worden. Die Rechnung ist schon bezahlt worden. Внимание: в пассиве используется worden – без ge-. geworden – это причастие от werden как самостоятельного глагола: Er ist Lehrer geworden (он стал учителем). В разговоре часто употребляют пассив в Perfekt, в текстах – пассив в Präteritum.',
          'Пасив у Perfekt: sein + Partizip II + worden. Ich bin gefragt worden, du bist gefragt worden, er/es/sie ist gefragt worden, wir sind gefragt worden, ihr seid gefragt worden, sie/Sie sind gefragt worden. 1975 ist ein Lernhilfeverein gegründet worden. Die Rechnung ist schon bezahlt worden. Увага: у пасиві вживають worden – без ge-. geworden – це дієприкметник від werden як самостійного дієслова: Er ist Lehrer geworden (він став учителем). У розмові часто вживають пасив у Perfekt, у текстах – пасив у Präteritum.',
          'Perfekt’te edilgen çatı: sein + Partizip II + worden. Ich bin gefragt worden, du bist gefragt worden, er/es/sie ist gefragt worden, wir sind gefragt worden, ihr seid gefragt worden, sie/Sie sind gefragt worden. 1975 ist ein Lernhilfeverein gegründet worden. Die Rechnung ist schon bezahlt worden. Dikkat: Edilgen çatıda worden kullanılır – ge- olmadan. geworden ise asıl fiil olan werden’in Partizip’idir: Er ist Lehrer geworden (öğretmen oldu). Konuşmada çoğunlukla Perfekt’teki, metinlerde ise Präteritum’daki edilgen çatı kullanılır.',
        ],
        hint: ['Passiv Perfekt = ist / sind + Partizip II + worden: ist gebaut worden. Nicht: geworden (Er ist Arzt geworden).', 'Passive in the Perfekt = ist / sind + past participle + worden: ist gebaut worden. Not: geworden (Er ist Arzt geworden).', 'Пассив в Perfekt = ist / sind + Partizip II + worden: ist gebaut worden. Не geworden (Er ist Arzt geworden).', 'Пасив у Perfekt = ist / sind + Partizip II + worden: ist gebaut worden. Не geworden (Er ist Arzt geworden).', 'Perfekt’te edilgen = ist / sind + Partizip II + worden: ist gebaut worden. geworden değil (Er ist Arzt geworden).'],
      },
      ex: [
        mc('G2', 'bezahlt worden', I.choose, 'Die Rechnung ist schon letzte Woche bezahlt …', ['worden', 'geworden', 'wurde'],
          ['The invoice was already paid last week.', 'Счёт был оплачен ещё на прошлой неделе.', 'Рахунок було оплачено ще минулого тижня.', 'Fatura daha geçen hafta ödendi.']),
        mc('G2', 'sind informiert worden', I.choose, 'Wir … leider nicht rechtzeitig informiert worden.', ['sind', 'haben', 'werden'],
          ['Unfortunately we were not informed in time.', 'К сожалению, нас не проинформировали вовремя.', 'На жаль, нас не поінформували вчасно.', 'Ne yazık ki zamanında bilgilendirilmedik.']),
        mc('G2', 'ist gegründet worden', I.choose, 'Der Verein … 1998 von fünf Nachbarn gegründet worden.', ['ist', 'hat', 'wird'],
          ['The association was founded by five neighbours in 1998.', 'Объединение было основано в 1998 году пятью соседями.', 'Об’єднання було засновано 1998 року п’ятьма сусідами.', 'Dernek 1998’de beş komşu tarafından kuruldu.']),
        mc('G2', 'worden oder geworden', I.choose, 'In welchem Satz ist „geworden“ richtig?', ['Mein Bruder ist Lehrer geworden.', 'Das Haus ist 1950 gebaut geworden.', 'Ich bin nicht gefragt geworden.'],
          ['In which sentence is “geworden” correct?', 'В каком предложении «geworden» употреблено правильно?', 'У якому реченні «geworden» вжито правильно?', 'Hangi cümlede “geworden” doğru kullanılmış?']),
        mc('G2', 'sein + Partizip + worden', I.sentence, 'Herr Demir erzählt von der Arbeit.', ['Die neue Maschine ist gestern geliefert worden.', 'Die neue Maschine hat gestern geliefert worden.', 'Die neue Maschine ist gestern worden geliefert.'],
          ['Mr Demir is talking about work.', 'Господин Demir рассказывает о работе.', 'Пан Demir розповідає про роботу.', 'Bay Demir işten söz ediyor.']),
        mc('G2', 'Präteritum = Perfekt', I.choose, 'Welcher Satz bedeutet dasselbe? „Der Präsident wurde 2022 gewählt.“', ['Der Präsident ist 2022 gewählt worden.', 'Der Präsident hat 2022 gewählt.', 'Der Präsident wird 2022 wählen.'],
          ['Which sentence means the same? “The president was elected in 2022.”', 'Какое предложение означает то же самое? «Президент был избран в 2022 году.»', 'Яке речення означає те саме? «Президента було обрано 2022 року.»', 'Hangi cümle aynı anlama gelir? “Cumhurbaşkanı 2022’de seçildi.”']),
        gap('G2', 'gestohlen worden', I.form, 'Mein Fahrrad ist gestern vor dem Bahnhof gestohlen ', '.', 'worden', ['geworden', 'werden'],
          ['My bicycle was stolen in front of the station yesterday.', 'Мой велосипед вчера украли у вокзала.', 'Мій велосипед учора вкрали біля вокзалу.', 'Bisikletim dün garın önünde çalındı.'], 'worden / geworden / werden'),
        gap('G2', 'sind aufgehängt worden', I.auxiliary, 'Die Wahlplakate ', ' schon am Montag aufgehängt worden.', 'sind', ['ist', 'haben'],
          ['The election posters were already put up on Monday.', 'Предвыборные плакаты развесили ещё в понедельник.', 'Передвиборчі плакати розвісили ще в понеділок.', 'Seçim afişleri daha pazartesi günü asıldı.'], 'sein'),
        gap('G2', 'bist eingeladen worden', I.auxiliary, 'Du ', ' doch auch eingeladen worden, oder? Warum kommst du nicht?', 'bist', ['hast', 'wirst'],
          ['You were invited too, were you not? Why are you not coming?', 'Тебя ведь тоже пригласили, да? Почему ты не идёшь?', 'Тебе ж теж запросили, так? Чому ти не йдеш?', 'Sen de davet edildin, değil mi? Neden gelmiyorsun?'], 'sein'),
        sb('G2', 'ist geliefert worden', I.order, 'Das Paket / ist / gestern / geliefert / worden.',
          ['The parcel was delivered yesterday.', 'Посылку доставили вчера.', 'Посилку доставили вчора.', 'Paket dün teslim edildi.'],
          { alt: ['Gestern ist das Paket geliefert worden.'] }),
      ],
    },
    {
      title: 'der größere Teil',
      t: ['der größere Teil (comparative before a noun)', 'der größere Teil (сравнительная степень перед существительным)', 'der größere Teil (вищий ступінь перед іменником)', 'der größere Teil (isimden önce Komparativ)'],
      card: {
        id: 'p6_komparativ',
        rule: 'Komparativ vor dem Nomen: Der Komparativ (größer, kleiner, besser, älter, höher) bekommt vor einem Nomen die normale Adjektivendung: der größere Teil, ein größerer Teil, das größere Problem, ein größeres Problem, die größere Frage, eine größere Frage, die größeren Fragen. Akkusativ maskulin und Dativ: den größeren Teil, dem größeren Teil, mit einer größeren Gruppe. Achtung: hoch → höher → ein höherer Lohn; teuer → teurer → eine teurere Wohnung; gut → besser → ein besseres Angebot.',
        examples: ['Wir brauchen eine größere Wohnung.', 'Die Arbeiter fordern höhere Löhne.', 'Das ist ein besserer Vorschlag.'],
        highlight: 'article',
        t: [
          'Comparative before a noun: the comparative (größer, kleiner, besser, älter, höher) takes the normal adjective ending before a noun: der größere Teil, ein größerer Teil, das größere Problem, ein größeres Problem, die größere Frage, eine größere Frage, die größeren Fragen. Masculine accusative and dative: den größeren Teil, dem größeren Teil, mit einer größeren Gruppe. Careful: hoch → höher → ein höherer Lohn (a higher wage); teuer → teurer → eine teurere Wohnung (a more expensive flat); gut → besser → ein besseres Angebot (a better offer).',
          'Сравнительная степень перед существительным: сравнительная степень (größer, kleiner, besser, älter, höher) перед существительным получает обычное окончание прилагательного: der größere Teil, ein größerer Teil, das größere Problem, ein größeres Problem, die größere Frage, eine größere Frage, die größeren Fragen. Аккузатив мужского рода и датив: den größeren Teil, dem größeren Teil, mit einer größeren Gruppe. Внимание: hoch → höher → ein höherer Lohn (более высокая зарплата); teuer → teurer → eine teurere Wohnung (более дорогая квартира); gut → besser → ein besseres Angebot (лучшее предложение).',
          'Вищий ступінь перед іменником: вищий ступінь (größer, kleiner, besser, älter, höher) перед іменником отримує звичайне закінчення прикметника: der größere Teil, ein größerer Teil, das größere Problem, ein größeres Problem, die größere Frage, eine größere Frage, die größeren Fragen. Акузатив чоловічого роду і датів: den größeren Teil, dem größeren Teil, mit einer größeren Gruppe. Увага: hoch → höher → ein höherer Lohn (вища зарплата); teuer → teurer → eine teurere Wohnung (дорожча квартира); gut → besser → ein besseres Angebot (краща пропозиція).',
          'İsimden önce Komparativ: Karşılaştırma biçimi (größer, kleiner, besser, älter, höher) isimden önce normal sıfat ekini alır: der größere Teil, ein größerer Teil, das größere Problem, ein größeres Problem, die größere Frage, eine größere Frage, die größeren Fragen. Eril Akkusativ ve Dativ: den größeren Teil, dem größeren Teil, mit einer größeren Gruppe. Dikkat: hoch → höher → ein höherer Lohn (daha yüksek bir ücret); teuer → teurer → eine teurere Wohnung (daha pahalı bir daire); gut → besser → ein besseres Angebot (daha iyi bir teklif).',
        ],
        hint: ['Komparativ + Adjektivendung: der größere Teil, ein größeres Problem, eine größere Frage, höhere Löhne, mit einem besseren Angebot.', 'Comparative + adjective ending: der größere Teil, ein größeres Problem, eine größere Frage, höhere Löhne, mit einem besseren Angebot.', 'Сравнительная степень + окончание прилагательного: der größere Teil, ein größeres Problem, eine größere Frage, höhere Löhne, mit einem besseren Angebot.', 'Вищий ступінь + закінчення прикметника: der größere Teil, ein größeres Problem, eine größere Frage, höhere Löhne, mit einem besseren Angebot.', 'Komparativ + sıfat eki: der größere Teil, ein größeres Problem, eine größere Frage, höhere Löhne, mit einem besseren Angebot.'],
      },
      ex: [
        mc('G3', 'eine größere Wohnung', I.choose, 'Die Familie wächst. Deshalb suchen wir eine … Wohnung.', ['größere', 'größer', 'größeren'],
          ['The family is growing. That is why we are looking for a bigger flat.', 'Семья растёт. Поэтому мы ищем квартиру побольше.', 'Родина зростає. Тому ми шукаємо більшу квартиру.', 'Aile büyüyor. Bu yüzden daha büyük bir daire arıyoruz.']),
        mc('G3', 'höhere Löhne', I.choose, 'Die Gewerkschaft fordert … Löhne für alle Beschäftigten.', ['höhere', 'höher', 'höheren'],
          ['The trade union is demanding higher wages for all employees.', 'Профсоюз требует более высокой зарплаты для всех работников.', 'Профспілка вимагає вищої зарплати для всіх працівників.', 'Sendika bütün çalışanlar için daha yüksek ücret talep ediyor.']),
        mc('G3', 'mit einem besseren Fahrrad', I.choose, 'Mit einem … Fahrrad wärst du viel schneller bei der Arbeit.', ['besseren', 'bessere', 'besser'],
          ['With a better bicycle you would get to work much faster.', 'На велосипеде получше ты бы добирался до работы гораздо быстрее.', 'На кращому велосипеді ти б діставався до роботи набагато швидше.', 'Daha iyi bir bisikletle işe çok daha çabuk varırdın.']),
        mc('G3', 'der ältere Bruder', I.choose, 'Der … Bruder heißt Jonas, der jüngere heißt Paul.', ['ältere', 'älterer', 'älteren'],
          ['The elder brother is called Jonas, the younger one is called Paul.', 'Старшего брата зовут Jonas, младшего – Paul.', 'Старшого брата звати Jonas, молодшого – Paul.', 'Büyük kardeşin adı Jonas, küçüğünün adı Paul.']),
        mc('G3', 'kein billigeres Zimmer', I.choose, 'Gibt es kein … Zimmer? Dieses hier kostet 120 Euro pro Nacht.', ['billigeres', 'billiger', 'billigere'],
          ['Is there no cheaper room? This one costs 120 euros a night.', 'Нет ли номера подешевле? Этот стоит 120 евро за ночь.', 'Чи немає дешевшого номера? Цей коштує 120 євро за ніч.', 'Daha ucuz bir oda yok mu? Bu oda gecesi 120 avro.']),
        mc('G3', 'einen größeren Parkplatz', I.sentence, 'Der Stadtrat diskutiert über den Bahnhof.', ['Wir brauchen einen größeren Parkplatz vor dem Bahnhof.', 'Wir brauchen einen größer Parkplatz vor dem Bahnhof.', 'Wir brauchen einen größere Parkplatz vor dem Bahnhof.'],
          ['The town council is discussing the station.', 'Городской совет обсуждает вокзал.', 'Міська рада обговорює вокзал.', 'Belediye meclisi garı tartışıyor.']),
        gap('G3', 'niedrigere Steuern', I.ending, 'Die Partei verspricht ', ' Steuern und mehr Geld für Schulen.', 'niedrigere', ['niedriger', 'niedrigeren'],
          ['The party is promising lower taxes and more money for schools.', 'Партия обещает более низкие налоги и больше денег для школ.', 'Партія обіцяє нижчі податки і більше грошей для шкіл.', 'Parti daha düşük vergiler ve okullar için daha fazla para vaat ediyor.'], 'niedrig (Komparativ)'),
        gap('G3', 'mit einem früheren Zug', I.ending, 'Mit einem ', ' Zug kommen wir pünktlich zur Demonstration.', 'früheren', ['frühere', 'früher'],
          ['With an earlier train we will get to the demonstration on time.', 'На более раннем поезде мы приедем на демонстрацию вовремя.', 'Ранішим поїздом ми приїдемо на демонстрацію вчасно.', 'Daha erken bir trenle gösteriye zamanında varırız.'], 'früh (Komparativ)'),
        gap('G3', 'ein größeres Problem', I.ending, 'Das ist ein ', ' Problem, als wir zuerst gedacht haben.', 'größeres', ['größere', 'größer'],
          ['That is a bigger problem than we first thought.', 'Это более серьёзная проблема, чем мы думали сначала.', 'Це більша проблема, ніж ми думали спочатку.', 'Bu, ilk başta düşündüğümüzden daha büyük bir sorun.'], 'groß (Komparativ)'),
        sb('G3', 'bessere Radwege', I.order, 'Die Stadt / braucht / dringend / mehr / und / bessere / Radwege.',
          ['The city urgently needs more and better cycle paths.', 'Городу срочно нужно больше хороших велодорожек.', 'Місту терміново потрібно більше добрих велодоріжок.', 'Şehrin acilen daha çok ve daha iyi bisiklet yollarına ihtiyacı var.'],
          { alt: ['Dringend braucht die Stadt mehr und bessere Radwege.'] }),
      ],
    },
    {
      title: 'das größte Problem',
      t: ['das größte Problem (superlative before a noun)', 'das größte Problem (превосходная степень перед существительным)', 'das größte Problem (найвищий ступінь перед іменником)', 'das größte Problem (isimden önce Superlativ)'],
      card: {
        id: 'p6_superlativ',
        rule: 'Superlativ vor dem Nomen: Stamm + -st- (oder -est-) + Adjektivendung, fast immer mit bestimmtem Artikel: der größte Teil, das größte Problem, die größte Frage, die größten Fragen. Akkusativ maskulin und Dativ: den größten Teil, dem größten Teil, in der größten Stadt. Unregelmäßig: gut → der beste, viel → die meisten, hoch → der höchste, nah → der nächste. Oft mit Relativsatz: Das ist das größte Stadion, das ich je gesehen habe.',
        examples: ['Berlin ist die größte Stadt Deutschlands.', 'Das war der schönste Tag meines Lebens.', 'Die meisten Bürger sind für den neuen Park.'],
        highlight: 'article',
        t: [
          'Superlative before a noun: stem + -st- (or -est-) + adjective ending, almost always with the definite article: der größte Teil, das größte Problem, die größte Frage, die größten Fragen. Masculine accusative and dative: den größten Teil, dem größten Teil, in der größten Stadt. Irregular: gut → der beste, viel → die meisten, hoch → der höchste, nah → der nächste. Often with a relative clause: Das ist das größte Stadion, das ich je gesehen habe (the biggest stadium I have ever seen).',
          'Превосходная степень перед существительным: основа + -st- (или -est-) + окончание прилагательного, почти всегда с определённым артиклем: der größte Teil, das größte Problem, die größte Frage, die größten Fragen. Аккузатив мужского рода и датив: den größten Teil, dem größten Teil, in der größten Stadt. Неправильные формы: gut → der beste, viel → die meisten, hoch → der höchste, nah → der nächste. Часто с придаточным определительным: Das ist das größte Stadion, das ich je gesehen habe (самый большой стадион, который я когда-либо видел).',
          'Найвищий ступінь перед іменником: основа + -st- (або -est-) + закінчення прикметника, майже завжди з означеним артиклем: der größte Teil, das größte Problem, die größte Frage, die größten Fragen. Акузатив чоловічого роду і датів: den größten Teil, dem größten Teil, in der größten Stadt. Неправильні форми: gut → der beste, viel → die meisten, hoch → der höchste, nah → der nächste. Часто з підрядним означальним: Das ist das größte Stadion, das ich je gesehen habe (найбільший стадіон, який я будь-коли бачив).',
          'İsimden önce Superlativ: kök + -st- (ya da -est-) + sıfat eki, neredeyse her zaman belirli artikelle: der größte Teil, das größte Problem, die größte Frage, die größten Fragen. Eril Akkusativ ve Dativ: den größten Teil, dem größten Teil, in der größten Stadt. Düzensiz biçimler: gut → der beste, viel → die meisten, hoch → der höchste, nah → der nächste. Çoğu zaman bir ilgi cümlesiyle: Das ist das größte Stadion, das ich je gesehen habe (bugüne kadar gördüğüm en büyük stadyum).',
        ],
        hint: ['Superlativ + Adjektivendung: der größte Teil, das größte Problem, die meisten Bürger, in der größten Stadt. gut → beste, hoch → höchste.', 'Superlative + adjective ending: der größte Teil, das größte Problem, die meisten Bürger, in der größten Stadt. gut → beste, hoch → höchste.', 'Превосходная степень + окончание прилагательного: der größte Teil, das größte Problem, die meisten Bürger, in der größten Stadt. gut → beste, hoch → höchste.', 'Найвищий ступінь + закінчення прикметника: der größte Teil, das größte Problem, die meisten Bürger, in der größten Stadt. gut → beste, hoch → höchste.', 'Superlativ + sıfat eki: der größte Teil, das größte Problem, die meisten Bürger, in der größten Stadt. gut → beste, hoch → höchste.'],
      },
      ex: [
        mc('G4', 'die größte Stadt', I.choose, 'Berlin ist die … Stadt Deutschlands.', ['größte', 'größere', 'am größten'],
          ['Berlin is the biggest city in Germany.', 'Берлин – самый большой город Германии.', 'Берлін – найбільше місто Німеччини.', 'Berlin Almanya’nın en büyük şehridir.']),
        mc('G4', 'der beste Kaffee', I.choose, 'Das ist der … Kaffee, den ich je getrunken habe.', ['beste', 'besten', 'am besten'],
          ['That is the best coffee I have ever drunk.', 'Это лучший кофе, который я когда-либо пил.', 'Це найкраща кава, яку я будь-коли пив.', 'Bu, bugüne kadar içtiğim en iyi kahve.']),
        mc('G4', 'die meisten Bürger', I.choose, 'Die … Bürger waren mit der Entscheidung des Stadtrats zufrieden.', ['meisten', 'meiste', 'mehr'],
          ['Most citizens were happy with the town council’s decision.', 'Большинство граждан были довольны решением городского совета.', 'Більшість громадян були задоволені рішенням міської ради.', 'Yurttaşların çoğu belediye meclisinin kararından memnundu.']),
        mc('G4', 'im ältesten Haus', I.choose, 'Wir wohnen im … Haus der ganzen Straße – es wurde 1750 gebaut.', ['ältesten', 'älteste', 'ältester'],
          ['We live in the oldest house in the whole street – it was built in 1750.', 'Мы живём в самом старом доме на всей улице – его построили в 1750 году.', 'Ми живемо в найстарішому будинку на всій вулиці – його збудували 1750 року.', 'Bütün sokağın en eski evinde oturuyoruz – 1750’de yapılmış.']),
        mc('G4', 'der höchste Berg', I.choose, 'Die Zugspitze ist der … Berg Deutschlands.', ['höchste', 'höchsten', 'höhere'],
          ['The Zugspitze is the highest mountain in Germany.', 'Цугшпитце – самая высокая гора Германии.', 'Цугшпітце – найвища гора Німеччини.', 'Zugspitze Almanya’nın en yüksek dağıdır.']),
        mc('G4', 'das interessanteste Museum', I.sentence, 'Timur erzählt von seinem Urlaub.', ['Das war das interessanteste Museum, das ich je besucht habe.', 'Das war das interessantere Museum, das ich je besucht habe.', 'Das war das am interessantesten Museum, das ich je besucht habe.'],
          ['Timur is talking about his holiday.', 'Timur рассказывает о своём отпуске.', 'Timur розповідає про свою відпустку.', 'Timur tatilini anlatıyor.']),
        gap('G4', 'eines der wichtigsten Ereignisse', I.ending, 'Der Mauerfall war eines der ', ' Ereignisse der deutschen Geschichte.', 'wichtigsten', ['wichtigste', 'wichtiger'],
          ['The fall of the Wall was one of the most important events in German history.', 'Падение стены было одним из важнейших событий немецкой истории.', 'Падіння муру було однією з найважливіших подій німецької історії.', 'Duvar’ın yıkılışı Alman tarihinin en önemli olaylarından biriydi.'], 'wichtig (Superlativ)'),
        gap('G4', 'mit dem nächsten Zug', I.ending, 'Mit dem ', ' Zug kommst du noch pünktlich: Er fährt in zehn Minuten.', 'nächsten', ['nächste', 'näher'],
          ['With the next train you will still be on time: it leaves in ten minutes.', 'На следующем поезде ты ещё успеешь вовремя: он отправляется через десять минут.', 'Наступним поїздом ти ще встигнеш вчасно: він вирушає за десять хвилин.', 'Bir sonraki trenle hâlâ zamanında varırsın: On dakika sonra kalkıyor.'], 'nah (Superlativ)'),
        gap('G4', 'das langweiligste Buch', I.ending, 'Das ist das ', ' Buch, das ich je gelesen habe. Ich bin nach zehn Seiten eingeschlafen.', 'langweiligste', ['langweiligsten', 'langweiliger'],
          ['That is the most boring book I have ever read. I fell asleep after ten pages.', 'Это самая скучная книга, которую я когда-либо читал. Я заснул через десять страниц.', 'Це найнудніша книжка, яку я будь-коли читав. Я заснув через десять сторінок.', 'Bu, bugüne kadar okuduğum en sıkıcı kitap. On sayfa sonra uyuyakaldım.'], 'langweilig (Superlativ)'),
        sb('G4', 'der schönste Tag', I.order, 'Das / war / der schönste Tag / meines Lebens.',
          ['That was the most beautiful day of my life.', 'Это был самый прекрасный день в моей жизни.', 'Це був найпрекрасніший день у моєму житті.', 'Bu, hayatımın en güzel günüydü.']),
      ],
    },
    {
      title: 'Eine Präsentation halten',
      t: ['Giving a presentation', 'Выступить с презентацией', 'Виступити з презентацією', 'Sunum yapmak'],
      card: {
        id: 'p6_praesentation',
        rule: 'Eine Präsentation halten. Einleitung: Unser heutiges Thema ist … Wir erzählen euch etwas über … Zuerst möchten wir über … sprechen. Überleitung: Nun zu seiner Kindheit / Jugend / Familie. Der nächste Punkt unserer Präsentation ist … Habt ihr zu diesem Punkt noch Fragen? Wenn nicht, dann kommen wir zum nächsten Punkt. Schluss: Zum Abschluss beschäftigen wir uns mit … Nun habt ihr einen Einblick in … erhalten. Habt ihr noch Fragen? Vielen Dank für eure Aufmerksamkeit.',
        examples: ['Unser heutiges Thema ist die Geschichte unserer Stadt.', 'Wenn es keine Fragen gibt, kommen wir zum nächsten Punkt.', 'Vielen Dank für eure Aufmerksamkeit.'],
        highlight: null,
        t: [
          'Giving a presentation. Introduction: Unser heutiges Thema ist … (our topic today is …). Wir erzählen euch etwas über … (we are going to tell you something about …). Zuerst möchten wir über … sprechen (first we would like to talk about …). Transition: Nun zu seiner Kindheit / Jugend / Familie (now to his childhood / youth / family). Der nächste Punkt unserer Präsentation ist … (the next point of our presentation is …). Habt ihr zu diesem Punkt noch Fragen? Wenn nicht, dann kommen wir zum nächsten Punkt (if not, let us move on to the next point). Conclusion: Zum Abschluss beschäftigen wir uns mit … (finally we will look at …). Nun habt ihr einen Einblick in … erhalten (now you have gained an insight into …). Habt ihr noch Fragen? Vielen Dank für eure Aufmerksamkeit (thank you for your attention).',
          'Как выступить с презентацией. Вступление: Unser heutiges Thema ist … (наша сегодняшняя тема – …). Wir erzählen euch etwas über … (мы расскажем вам о …). Zuerst möchten wir über … sprechen (сначала мы хотели бы поговорить о …). Переход: Nun zu seiner Kindheit / Jugend / Familie (теперь о его детстве / юности / семье). Der nächste Punkt unserer Präsentation ist … (следующий пункт нашей презентации – …). Habt ihr zu diesem Punkt noch Fragen? Wenn nicht, dann kommen wir zum nächsten Punkt (если нет, перейдём к следующему пункту). Заключение: Zum Abschluss beschäftigen wir uns mit … (в заключение мы рассмотрим …). Nun habt ihr einen Einblick in … erhalten (теперь вы получили представление о …). Habt ihr noch Fragen? Vielen Dank für eure Aufmerksamkeit (спасибо за внимание).',
          'Як виступити з презентацією. Вступ: Unser heutiges Thema ist … (наша сьогоднішня тема – …). Wir erzählen euch etwas über … (ми розповімо вам про …). Zuerst möchten wir über … sprechen (спочатку ми хотіли б поговорити про …). Перехід: Nun zu seiner Kindheit / Jugend / Familie (тепер про його дитинство / юність / родину). Der nächste Punkt unserer Präsentation ist … (наступний пункт нашої презентації – …). Habt ihr zu diesem Punkt noch Fragen? Wenn nicht, dann kommen wir zum nächsten Punkt (якщо ні, перейдемо до наступного пункту). Завершення: Zum Abschluss beschäftigen wir uns mit … (на завершення ми розглянемо …). Nun habt ihr einen Einblick in … erhalten (тепер ви отримали уявлення про …). Habt ihr noch Fragen? Vielen Dank für eure Aufmerksamkeit (дякуємо за увагу).',
          'Sunum yapmak. Giriş: Unser heutiges Thema ist … (bugünkü konumuz …). Wir erzählen euch etwas über … (size … hakkında bir şeyler anlatacağız). Zuerst möchten wir über … sprechen (önce … hakkında konuşmak istiyoruz). Geçiş: Nun zu seiner Kindheit / Jugend / Familie (şimdi çocukluğuna / gençliğine / ailesine gelelim). Der nächste Punkt unserer Präsentation ist … (sunumumuzun bir sonraki maddesi …). Habt ihr zu diesem Punkt noch Fragen? Wenn nicht, dann kommen wir zum nächsten Punkt (yoksa bir sonraki maddeye geçelim). Kapanış: Zum Abschluss beschäftigen wir uns mit … (son olarak … konusunu ele alacağız). Nun habt ihr einen Einblick in … erhalten (artık … hakkında fikir edindiniz). Habt ihr noch Fragen? Vielen Dank für eure Aufmerksamkeit (dikkatiniz için teşekkür ederiz).',
        ],
        hint: ['Einleitung: Unser heutiges Thema ist … Überleitung: Der nächste Punkt ist … Schluss: Vielen Dank für eure Aufmerksamkeit.', 'Introduction: Unser heutiges Thema ist … Transition: Der nächste Punkt ist … Conclusion: Vielen Dank für eure Aufmerksamkeit.', 'Вступление: Unser heutiges Thema ist … Переход: Der nächste Punkt ist … Заключение: Vielen Dank für eure Aufmerksamkeit.', 'Вступ: Unser heutiges Thema ist … Перехід: Der nächste Punkt ist … Завершення: Vielen Dank für eure Aufmerksamkeit.', 'Giriş: Unser heutiges Thema ist … Geçiş: Der nächste Punkt ist … Kapanış: Vielen Dank für eure Aufmerksamkeit.'],
      },
      ex: [
        mc('K1', 'Einleitung', I.choose, 'Womit beginnt man eine Präsentation?', ['Unser heutiges Thema ist die Geschichte der Berliner Mauer.', 'Vielen Dank für eure Aufmerksamkeit.', 'Habt ihr noch Fragen?'],
          ['How do you begin a presentation?', 'С чего начинают презентацию?', 'З чого починають презентацію?', 'Bir sunuma nasıl başlanır?']),
        mc('K1', 'Schluss', I.choose, 'Womit beendet man eine Präsentation?', ['Vielen Dank für eure Aufmerksamkeit.', 'Zuerst möchten wir über seine Kindheit sprechen.', 'Der nächste Punkt ist seine Ausbildung.'],
          ['How do you end a presentation?', 'Чем заканчивают презентацию?', 'Чим закінчують презентацію?', 'Bir sunum nasıl bitirilir?']),
        mc('K1', 'zum nächsten Punkt kommen', I.choose, 'Wenn es keine Fragen mehr gibt, dann … wir zum nächsten Punkt.', ['kommen', 'bringen', 'nehmen'],
          ['If there are no more questions, let us move on to the next point.', 'Если вопросов больше нет, перейдём к следующему пункту.', 'Якщо запитань більше немає, перейдемо до наступного пункту.', 'Başka soru yoksa bir sonraki maddeye geçelim.']),
        mc('K1', 'erzählen über', I.choose, 'Wir … euch heute etwas über die ersten Jahre nach dem Krieg.', ['erzählen', 'erziehen', 'erholen'],
          ['Today we are going to … you something about the first years after the war.', 'Сегодня мы … вам о первых годах после войны.', 'Сьогодні ми … вам про перші роки після війни.', 'Bugün size savaştan sonraki ilk yıllar hakkında bir şeyler … .']),
        mc('K1', 'Überleitung', I.situation, 'Du hast den ersten Teil deiner Präsentation beendet und möchtest zum zweiten Teil wechseln. Was sagst du?', ['Der nächste Punkt unserer Präsentation ist seine Zeit als Bürgermeister.', 'Vielen Dank fürs Zuhören und auf Wiedersehen.', 'Unser heutiges Thema ist beendet.'],
          ['You have finished the first part of your presentation and want to move on to the second part. What do you say?', 'Вы закончили первую часть презентации и хотите перейти ко второй. Что вы скажете?', 'Ви закінчили першу частину презентації і хочете перейти до другої. Що ви скажете?', 'Sunumunuzun ilk bölümünü bitirdiniz ve ikinci bölüme geçmek istiyorsunuz. Ne dersiniz?']),
        mc('K1', 'Zum Abschluss', I.choose, 'Zum … beschäftigen wir uns mit der Frage, was wir heute aus der Geschichte lernen können.', ['Abschluss', 'Anschluss', 'Ausschluss'],
          ['To conclude, we will look at the question of what we can learn from history today.', 'В заключение мы рассмотрим вопрос о том, чему нас сегодня может научить история.', 'На завершення ми розглянемо питання про те, чого нас сьогодні може навчити історія.', 'Son olarak bugün tarihten ne öğrenebileceğimiz sorusunu ele alacağız.']),
        gap('K1', 'Aufmerksamkeit', I.word, 'Vielen Dank für eure ', '. Wir hoffen, unsere Präsentation hat euch gefallen.', 'Aufmerksamkeit', ['Aufregung', 'Aufnahme'],
          ['Thank you very much for your attention. We hope you enjoyed our presentation.', 'Большое спасибо за внимание. Надеемся, наша презентация вам понравилась.', 'Щиро дякуємо за увагу. Сподіваємося, наша презентація вам сподобалася.', 'Dikkatiniz için çok teşekkür ederiz. Umarız sunumumuzu beğendiniz.'],
          ['attention', 'внимание', 'увага', 'dikkat']),
        gap('K1', 'Einblick', I.word, 'Nun habt ihr einen ', ' in die Geschichte unserer Stadt bekommen.', 'Einblick', ['Einkauf', 'Eingang'],
          ['Now you have gained an insight into the history of our town.', 'Теперь вы получили представление об истории нашего города.', 'Тепер ви отримали уявлення про історію нашого міста.', 'Artık şehrimizin tarihi hakkında bir fikir edindiniz.'],
          ['insight', 'представление', 'уявлення', 'fikir, genel bakış']),
        gap('K1', 'Zuerst möchten wir …', I.word, 'Zuerst ', ' wir über seine Kindheit in Lübeck sprechen.', 'möchten', ['möchtet', 'möchte'],
          ['First we would like to talk about his childhood in Lübeck.', 'Сначала мы хотели бы поговорить о его детстве в Любеке.', 'Спочатку ми хотіли б поговорити про його дитинство в Любеку.', 'Önce onun Lübeck’teki çocukluğu hakkında konuşmak istiyoruz.'],
          ['would like to', 'хотели бы', 'хотіли б', 'istiyoruz']),
        sb('K1', 'Der nächste Punkt ist …', I.order, 'Der nächste Punkt / unserer Präsentation / ist / seine Jugend.',
          ['The next point of our presentation is his youth.', 'Следующий пункт нашей презентации – его юность.', 'Наступний пункт нашої презентації – його юність.', 'Sunumumuzun bir sonraki maddesi onun gençliği.']),
      ],
    },
    {
      title: 'Etwas bewerten',
      t: ['Giving a judgement', 'Дать оценку', 'Дати оцінку', 'Bir şeyi değerlendirmek'],
      card: {
        id: 'p6_bewerten',
        rule: 'Etwas bewerten: Ich bin für / gegen …, weil … Davon halte ich viel / nicht viel, denn … Das kann ich nur befürworten. Das kann ich nur ablehnen. Ganz meine Meinung. Meiner Meinung / Ansicht nach … In diesem Zusammenhang finde ich auch wichtig, dass … befürworten = dafür sein; ablehnen = dagegen sein. für + Akkusativ, gegen + Akkusativ: Ich bin für den Vorschlag. Ich bin gegen das Verbot.',
        examples: ['Ich bin für ein Tempolimit, weil es weniger Unfälle gibt.', 'Davon halte ich nicht viel.', 'Ein Rauchverbot kann ich nur befürworten.'],
        highlight: null,
        t: [
          'Giving a judgement: Ich bin für / gegen …, weil … (I am for / against … because …). Davon halte ich viel / nicht viel, denn … (I think highly / little of that, because …). Das kann ich nur befürworten (I can only support that). Das kann ich nur ablehnen (I can only reject that). Ganz meine Meinung (I quite agree). Meiner Meinung / Ansicht nach … (in my opinion / view). In diesem Zusammenhang finde ich auch wichtig, dass … (in this context I also think it is important that …). befürworten = to be in favour; ablehnen = to be against. für + accusative, gegen + accusative: Ich bin für den Vorschlag. Ich bin gegen das Verbot.',
          'Как дать оценку: Ich bin für / gegen …, weil … (я за / против …, потому что …). Davon halte ich viel / nicht viel, denn … (я высокого / невысокого мнения об этом, так как …). Das kann ich nur befürworten (я могу это только поддержать). Das kann ich nur ablehnen (я могу это только отвергнуть). Ganz meine Meinung (полностью согласен). Meiner Meinung / Ansicht nach … (по моему мнению / на мой взгляд). In diesem Zusammenhang finde ich auch wichtig, dass … (в этой связи я считаю важным и то, что …). befürworten = быть за; ablehnen = быть против. für + аккузатив, gegen + аккузатив: Ich bin für den Vorschlag. Ich bin gegen das Verbot.',
          'Як дати оцінку: Ich bin für / gegen …, weil … (я за / проти …, бо …). Davon halte ich viel / nicht viel, denn … (я високої / невисокої думки про це, оскільки …). Das kann ich nur befürworten (я можу це лише підтримати). Das kann ich nur ablehnen (я можу це лише відхилити). Ganz meine Meinung (цілком згоден). Meiner Meinung / Ansicht nach … (на мою думку / на мій погляд). In diesem Zusammenhang finde ich auch wichtig, dass … (у цьому зв’язку я вважаю важливим і те, що …). befürworten = бути за; ablehnen = бути проти. für + акузатив, gegen + акузатив: Ich bin für den Vorschlag. Ich bin gegen das Verbot.',
          'Bir şeyi değerlendirmek: Ich bin für / gegen …, weil … (… taraftarıyım / karşıyım, çünkü …). Davon halte ich viel / nicht viel, denn … (bunu çok / pek doğru bulmuyorum, çünkü …). Das kann ich nur befürworten (bunu ancak desteklerim). Das kann ich nur ablehnen (bunu ancak reddederim). Ganz meine Meinung (tamamen aynı fikirdeyim). Meiner Meinung / Ansicht nach … (bana göre / benim görüşüme göre). In diesem Zusammenhang finde ich auch wichtig, dass … (bu bağlamda … olmasını da önemli buluyorum). befürworten = taraftar olmak; ablehnen = karşı olmak. für + Akkusativ, gegen + Akkusativ: Ich bin für den Vorschlag. Ich bin gegen das Verbot.',
        ],
        hint: ['Bewerten: Ich bin für / gegen … Davon halte ich (nicht) viel. Das kann ich nur befürworten / ablehnen. Ganz meine Meinung.', 'Judging: Ich bin für / gegen … Davon halte ich (nicht) viel. Das kann ich nur befürworten / ablehnen (support / reject). Ganz meine Meinung.', 'Оценка: Ich bin für / gegen … Davon halte ich (nicht) viel. Das kann ich nur befürworten / ablehnen (поддержать / отвергнуть). Ganz meine Meinung.', 'Оцінка: Ich bin für / gegen … Davon halte ich (nicht) viel. Das kann ich nur befürworten / ablehnen (підтримати / відхилити). Ganz meine Meinung.', 'Değerlendirme: Ich bin für / gegen … Davon halte ich (nicht) viel. Das kann ich nur befürworten / ablehnen (desteklemek / reddetmek). Ganz meine Meinung.'],
      },
      ex: [
        mc('K2', 'befürworten', I.choose, 'Ein Tempolimit auf Autobahnen? Das kann ich nur … – dann gibt es weniger schwere Unfälle.', ['befürworten', 'befragen', 'befestigen'],
          ['A speed limit on motorways? I can only … that – then there will be fewer serious accidents.', 'Ограничение скорости на автобанах? Я могу это только … – тогда будет меньше тяжёлых аварий.', 'Обмеження швидкості на автобанах? Я можу це лише … – тоді буде менше тяжких аварій.', 'Otobanlarda hız sınırı mı? Bunu ancak … – o zaman ağır kazalar azalır.']),
        mc('K2', 'gegen', I.choose, 'Ich bin … den Plan, die Bibliothek zu schließen. Viele Kinder lernen dort.', ['gegen', 'für', 'mit'],
          ['I am against the plan to close the library. Many children study there.', 'Я против плана закрыть библиотеку. Там занимаются многие дети.', 'Я проти плану закрити бібліотеку. Там навчається багато дітей.', 'Kütüphaneyi kapatma planına karşıyım. Orada birçok çocuk ders çalışıyor.']),
        mc('K2', 'Ganz meine Meinung.', I.react, '„Die Stadt sollte mehr Geld für Radwege ausgeben.“', ['Ganz meine Meinung. Das Radfahren muss sicherer werden.', 'Unser heutiges Thema ist beendet.', 'Vielen Dank für eure Aufmerksamkeit.'],
          ['“The city should spend more money on cycle paths.”', '«Город должен тратить больше денег на велодорожки.»', '«Місто має витрачати більше грошей на велодоріжки.»', '“Belediye bisiklet yollarına daha çok para harcamalı.”']),
        mc('K2', 'halten von', I.choose, 'Von höheren Parkgebühren … ich nicht viel, denn viele Menschen brauchen ihr Auto für die Arbeit.', ['halte', 'hebe', 'helfe'],
          ['I do not think much of higher parking charges, because many people need their car for work.', 'Я невысокого мнения о повышении платы за парковку, ведь многим людям машина нужна для работы.', 'Я невисокої думки про підвищення плати за паркування, адже багатьом людям машина потрібна для роботи.', 'Park ücretlerinin artmasını pek doğru bulmuyorum, çünkü birçok insanın işi için arabaya ihtiyacı var.']),
        mc('K2', 'Meiner Ansicht nach', I.choose, 'Meiner … nach sollten alle Bürger ab 16 wählen dürfen.', ['Ansicht', 'Aussicht', 'Absicht'],
          ['In my view all citizens aged 16 and over should be allowed to vote.', 'На мой взгляд, все граждане с 16 лет должны иметь право голосовать.', 'На мій погляд, усі громадяни від 16 років повинні мати право голосувати.', 'Benim görüşüme göre 16 yaşından itibaren bütün yurttaşlar oy kullanabilmeli.']),
        mc('K2', 'ablehnen', I.situation, 'In einer Diskussion schlägt jemand vor, das Stadtfest abzuschaffen. Du bist dagegen. Was sagst du?', ['Das kann ich nur ablehnen. Das Fest ist wichtig für die Stadt.', 'Das kann ich nur befürworten.', 'Ganz meine Meinung.'],
          ['In a discussion someone suggests abolishing the town festival. You are against it. What do you say?', 'В дискуссии кто-то предлагает отменить городской праздник. Вы против. Что вы скажете?', 'У дискусії хтось пропонує скасувати міське свято. Ви проти. Що ви скажете?', 'Bir tartışmada biri şehir şenliğinin kaldırılmasını öneriyor. Siz karşısınız. Ne dersiniz?']),
        gap('K2', 'für', I.prep, 'Ich bin ', ' längere Öffnungszeiten, weil viele Leute erst abends einkaufen können.', 'für', ['gegen', 'ohne'],
          ['I am in favour of longer opening hours because many people can only go shopping in the evening.', 'Я за более долгие часы работы, потому что многие люди могут ходить за покупками только вечером.', 'Я за довші години роботи, бо багато людей можуть ходити по покупки лише ввечері.', 'Daha uzun açılış saatlerinden yanayım, çünkü birçok insan ancak akşam alışveriş yapabiliyor.'], 'für / gegen / ohne'),
        gap('K2', 'In diesem Zusammenhang', I.word, 'In diesem ', ' finde ich auch wichtig, dass die Busse häufiger fahren.', 'Zusammenhang', ['Zusammenbruch', 'Zusammenstoß'],
          ['In this context I also think it is important that the buses run more frequently.', 'В этой связи я считаю важным и то, чтобы автобусы ходили чаще.', 'У цьому зв’язку я вважаю важливим і те, щоб автобуси ходили частіше.', 'Bu bağlamda otobüslerin daha sık çalışmasını da önemli buluyorum.'],
          ['context, connection', 'связь, контекст', 'зв’язок, контекст', 'bağlam']),
        gap('K2', 'Davon halte ich viel.', I.word, 'Davon halte ich ', ', denn so sparen wir Zeit und Geld.', 'viel', ['voll', 'vier'],
          ['I think highly of that, because that way we save time and money.', 'Я высокого мнения об этом, ведь так мы экономим время и деньги.', 'Я високої думки про це, адже так ми заощаджуємо час і гроші.', 'Bunu çok doğru buluyorum, çünkü böylece zamandan ve paradan tasarruf ediyoruz.'],
          ['a lot, much', 'много', 'багато', 'çok']),
        sb('K2', 'Ich bin gegen …, weil …', I.order, 'Ich / bin / gegen / ein Verbot, / weil / es / nichts / ändert.',
          ['I am against a ban because it changes nothing.', 'Я против запрета, потому что он ничего не меняет.', 'Я проти заборони, бо вона нічого не змінює.', 'Bir yasağa karşıyım, çünkü hiçbir şeyi değiştirmez.']),
      ],
    },
    {
      title: 'Etwas vergleichen',
      t: ['Making comparisons', 'Сравнивать', 'Порівнювати', 'Karşılaştırma yapmak'],
      card: {
        id: 'p6_vergleichen',
        rule: 'Etwas vergleichen: Bei uns / In … ist das genau(so) wie / anders als in … Das ist bei uns nicht so streng wie in … / strenger als in … Auch bei uns gibt es strengere Gesetze. Das ist hier ganz anders. Der Unterschied ist, dass … Verglichen mit … Im Gegensatz zu + Dativ … Ich finde es besser so, wie es in … ist. Nach so / genauso steht wie, nach dem Komparativ und nach anders steht als.',
        examples: ['Das ist bei uns nicht so streng wie in Deutschland.', 'Im Gegensatz zu früher gibt es heute keine Grenze mehr.', 'Verglichen mit Berlin ist unsere Stadt sehr ruhig.'],
        highlight: null,
        t: [
          'Making comparisons: Bei uns / In … ist das genau(so) wie / anders als in … (in my country that is just like / different from …). Das ist bei uns nicht so streng wie in … / strenger als in … (not as strict as / stricter than). Auch bei uns gibt es strengere Gesetze (we have stricter laws too). Das ist hier ganz anders (that is quite different here). Der Unterschied ist, dass … (the difference is that …). Verglichen mit … (compared with …). Im Gegensatz zu + dative … (in contrast to …). Ich finde es besser so, wie es in … ist (I prefer the way it is in …). After so / genauso you use wie, after the comparative and after anders you use als.',
          'Как сравнивать: Bei uns / In … ist das genau(so) wie / anders als in … (у нас это точно так же, как / иначе, чем в …). Das ist bei uns nicht so streng wie in … / strenger als in … (не так строго, как / строже, чем). Auch bei uns gibt es strengere Gesetze (у нас тоже есть более строгие законы). Das ist hier ganz anders (здесь это совсем иначе). Der Unterschied ist, dass … (разница в том, что …). Verglichen mit … (по сравнению с …). Im Gegensatz zu + датив … (в отличие от …). Ich finde es besser so, wie es in … ist (мне больше нравится так, как это в …). После so / genauso стоит wie, после сравнительной степени и после anders – als.',
          'Як порівнювати: Bei uns / In … ist das genau(so) wie / anders als in … (у нас це так само, як / інакше, ніж у …). Das ist bei uns nicht so streng wie in … / strenger als in … (не так суворо, як / суворіше, ніж). Auch bei uns gibt es strengere Gesetze (у нас теж є суворіші закони). Das ist hier ganz anders (тут це зовсім інакше). Der Unterschied ist, dass … (різниця в тому, що …). Verglichen mit … (порівняно з …). Im Gegensatz zu + датів … (на відміну від …). Ich finde es besser so, wie es in … ist (мені більше подобається так, як це в …). Після so / genauso стоїть wie, після вищого ступеня і після anders – als.',
          'Karşılaştırma yapmak: Bei uns / In … ist das genau(so) wie / anders als in … (bizde bu tıpkı …’deki gibi / …’dekinden farklı). Das ist bei uns nicht so streng wie in … / strenger als in … (… kadar katı değil / …’den daha katı). Auch bei uns gibt es strengere Gesetze (bizde de daha katı yasalar var). Das ist hier ganz anders (burada durum bambaşka). Der Unterschied ist, dass … (fark şu ki …). Verglichen mit … (… ile karşılaştırıldığında). Im Gegensatz zu + Dativ … (…’in aksine). Ich finde es besser so, wie es in … ist (…’deki gibi olmasını daha iyi buluyorum). so / genauso sözcüklerinden sonra wie, Komparativ’den ve anders sözcüğünden sonra als gelir.',
        ],
        hint: ['so / genauso … wie, Komparativ / anders … als. Im Gegensatz zu + Dativ. Verglichen mit + Dativ. Der Unterschied ist, dass …', 'so / genauso … wie, comparative / anders … als. Im Gegensatz zu + dative (in contrast to). Verglichen mit + dative (compared with). Der Unterschied ist, dass …', 'so / genauso … wie, сравнительная степень / anders … als. Im Gegensatz zu + датив (в отличие от). Verglichen mit + датив (по сравнению с). Der Unterschied ist, dass …', 'so / genauso … wie, вищий ступінь / anders … als. Im Gegensatz zu + датів (на відміну від). Verglichen mit + датів (порівняно з). Der Unterschied ist, dass …', 'so / genauso … wie, Komparativ / anders … als. Im Gegensatz zu + Dativ (…’in aksine). Verglichen mit + Dativ (… ile karşılaştırıldığında). Der Unterschied ist, dass …'],
      },
      ex: [
        mc('K3', 'nicht so streng wie', I.choose, 'Bei uns sind die Verkehrsregeln nicht so streng … in Deutschland.', ['wie', 'als', 'dass'],
          ['In my country the traffic rules are not as strict as in Germany.', 'У нас правила дорожного движения не такие строгие, как в Германии.', 'У нас правила дорожнього руху не такі суворі, як у Німеччині.', 'Bizde trafik kuralları Almanya’daki kadar katı değil.']),
        mc('K3', 'höher als', I.choose, 'In meiner Heimat sind die Strafen für Falschparker viel höher … hier.', ['als', 'wie', 'so'],
          ['In my home country the fines for illegal parking are much higher than here.', 'На моей родине штрафы за неправильную парковку гораздо выше, чем здесь.', 'На моїй батьківщині штрафи за неправильне паркування набагато вищі, ніж тут.', 'Benim memleketimde yanlış park cezaları buradakinden çok daha yüksek.']),
        mc('K3', 'Im Gegensatz zu', I.choose, 'Im … zu meinem Heimatland wird in Deutschland sehr viel Müll getrennt.', ['Gegensatz', 'Gegenstand', 'Gegenwart'],
          ['In contrast to my home country, a great deal of rubbish is separated in Germany.', 'В отличие от моей родины, в Германии очень тщательно сортируют мусор.', 'На відміну від моєї батьківщини, у Німеччині дуже ретельно сортують сміття.', 'Benim memleketimin aksine Almanya’da çöpler büyük ölçüde ayrıştırılıyor.']),
        mc('K3', 'Verglichen mit', I.choose, '… mit einer Großstadt wie Hamburg ist das Leben in unserem Dorf sehr ruhig.', ['Verglichen', 'Vergessen', 'Verboten'],
          ['Compared with a big city like Hamburg, life in our village is very quiet.', 'По сравнению с таким большим городом, как Гамбург, жизнь в нашей деревне очень спокойная.', 'Порівняно з таким великим містом, як Гамбург, життя в нашому селі дуже спокійне.', 'Hamburg gibi büyük bir şehirle karşılaştırıldığında köyümüzde hayat çok sakin.']),
        mc('K3', 'Das ist bei uns ganz anders.', I.react, '„Bei uns in Deutschland muss man für fast alles einen Termin machen.“', ['Das ist bei uns ganz anders: Man geht einfach hin und wartet.', 'Vielen Dank für eure Aufmerksamkeit.', 'Zum Abschluss kommen wir zum ersten Punkt.'],
          ['“Here in Germany you have to make an appointment for almost everything.”', '«У нас в Германии почти на всё нужно записываться заранее.»', '«У нас у Німеччині майже на все треба записуватися заздалегідь.»', '“Bizde, Almanya’da neredeyse her şey için randevu almak gerekiyor.”']),
        mc('K3', 'Der Unterschied ist, dass …', I.choose, 'Der … ist, dass man bei uns erst mit 18 wählen darf, in Österreich aber schon mit 16.', ['Unterschied', 'Unterricht', 'Untergang'],
          ['The … is that in my country you are only allowed to vote at 18, but in Austria at 16.', '… в том, что у нас голосовать можно только с 18 лет, а в Австрии – уже с 16.', '… в тому, що в нас голосувати можна лише з 18 років, а в Австрії – уже з 16.', '… şu: Bizde ancak 18 yaşında oy kullanılabiliyor, Avusturya’da ise 16 yaşında.']),
        gap('K3', 'genauso wie', I.word, 'Die Schulen sind bei uns genauso ', ' in Deutschland: Der Unterricht beginnt um acht.', 'wie', ['als', 'wenn'],
          ['Schools in my country are just the same as in Germany: lessons start at eight.', 'Школы у нас такие же, как в Германии: занятия начинаются в восемь.', 'Школи в нас такі самі, як у Німеччині: заняття починаються о восьмій.', 'Bizde okullar tıpkı Almanya’daki gibi: Dersler saat sekizde başlıyor.'], 'wie / als / wenn'),
        gap('K3', 'Im Gegensatz zu den Nachbarländern', I.article, 'Im Gegensatz zu ', ' Nachbarländern hat Deutschland kein allgemeines Tempolimit auf Autobahnen.', 'den', ['die', 'der'],
          ['In contrast to the neighbouring countries, Germany has no general speed limit on motorways.', 'В отличие от соседних стран, в Германии нет общего ограничения скорости на автобанах.', 'На відміну від сусідніх країн, у Німеччині немає загального обмеження швидкості на автобанах.', 'Komşu ülkelerin aksine Almanya’da otobanlarda genel bir hız sınırı yok.'], 'die (Plural, Dativ)'),
        gap('K3', 'besser so, wie …', I.comparison, 'Ich finde es ', ' so, wie es in Dänemark ist: Dort fahren fast alle mit dem Rad.', 'besser', ['gut', 'beste'],
          ['I prefer the way it is in Denmark: almost everyone cycles there.', 'Мне больше нравится так, как это устроено в Дании: там почти все ездят на велосипеде.', 'Мені більше подобається так, як це влаштовано в Данії: там майже всі їздять велосипедом.', 'Danimarka’daki gibi olmasını daha iyi buluyorum: Orada neredeyse herkes bisiklete biniyor.'], 'gut (Komparativ)'),
        sb('K3', 'ganz anders als', I.order, 'Das / ist / bei uns / ganz anders / als / in Deutschland.',
          ['In my country that is quite different from Germany.', 'У нас это совсем иначе, чем в Германии.', 'У нас це зовсім інакше, ніж у Німеччині.', 'Bizde bu, Almanya’dakinden bambaşka.'],
          { alt: ['Bei uns ist das ganz anders als in Deutschland.'] }),
      ],
    },
    {
      title: 'Zeitungsmeldungen',
      t: ['Newspaper reports', 'Газетные заметки', 'Газетні замітки', 'Gazete haberleri'],
      card: {
        id: 'p6_meldungen',
        rule: 'Zeitungsmeldungen verstehen: Eine Meldung ist kurz und sachlich. Das Wichtigste steht am Anfang: Wer? Was? Wann? Wo? Danach folgen Gründe und Folgen. Typisch sind Zahlen (rund 50, mehr als, statt 12 Millionen), das Passiv (wurde eröffnet, ist gesperrt worden, soll abgestimmt werden) und Quellen (laut einer Umfrage, nach Angaben der Polizei). rund = ungefähr. fordern = verlangen. laut + Dativ = wie … sagt.',
        examples: ['Rund 50 Jugendliche demonstrierten vor dem Rathaus.', 'Die Brücke ist am Montag eröffnet worden.', 'Laut einer Umfrage ist die Mehrheit zufrieden.'],
        highlight: null,
        t: [
          'Understanding newspaper reports: a report is short and factual. The most important information comes first: who? what? when? where? After that come reasons and consequences. Typical features are figures (rund 50 = around 50, mehr als = more than, statt 12 Millionen = instead of 12 million), the passive (wurde eröffnet, ist gesperrt worden, soll abgestimmt werden) and sources (laut einer Umfrage = according to a survey, nach Angaben der Polizei = according to the police). rund = approximately. fordern = to demand. laut + dative = according to.',
          'Как понимать газетные заметки: заметка короткая и деловая. Самое важное стоит в начале: кто? что? когда? где? Затем следуют причины и последствия. Типичны цифры (rund 50 = около 50, mehr als = более, statt 12 Millionen = вместо 12 миллионов), пассив (wurde eröffnet, ist gesperrt worden, soll abgestimmt werden) и источники (laut einer Umfrage = согласно опросу, nach Angaben der Polizei = по данным полиции). rund = примерно. fordern = требовать. laut + датив = согласно, по словам.',
          'Як розуміти газетні замітки: замітка коротка і ділова. Найважливіше стоїть на початку: хто? що? коли? де? Далі йдуть причини й наслідки. Типові цифри (rund 50 = близько 50, mehr als = понад, statt 12 Millionen = замість 12 мільйонів), пасив (wurde eröffnet, ist gesperrt worden, soll abgestimmt werden) і джерела (laut einer Umfrage = згідно з опитуванням, nach Angaben der Polizei = за даними поліції). rund = приблизно. fordern = вимагати. laut + датів = згідно з, за словами.',
          'Gazete haberlerini anlamak: Bir haber kısa ve nesneldir. En önemli bilgi başta yer alır: Kim? Ne? Ne zaman? Nerede? Ardından nedenler ve sonuçlar gelir. Rakamlar (rund 50 = yaklaşık 50, mehr als = -den fazla, statt 12 Millionen = 12 milyon yerine), edilgen çatı (wurde eröffnet, ist gesperrt worden, soll abgestimmt werden) ve kaynaklar (laut einer Umfrage = bir ankete göre, nach Angaben der Polizei = polisin verdiği bilgiye göre) tipiktir. rund = yaklaşık. fordern = talep etmek. laut + Dativ = …’e göre.',
        ],
        hint: ['Meldung: Wer? Was? Wann? Wo? – dann Gründe und Folgen. Achte auf Zahlen, Passiv und Quellen (laut …). rund = ungefähr.', 'News item: who? what? when? where? – then reasons and consequences. Look for figures, the passive and sources (laut …). rund = approximately.', 'Заметка: кто? что? когда? где? – затем причины и последствия. Обращайте внимание на цифры, пассив и источники (laut …). rund = примерно.', 'Замітка: хто? що? коли? де? – потім причини й наслідки. Звертайте увагу на цифри, пасив і джерела (laut …). rund = приблизно.', 'Haber: Kim? Ne? Ne zaman? Nerede? – sonra nedenler ve sonuçlar. Rakamlara, edilgen çatıya ve kaynaklara (laut …) dikkat edin. rund = yaklaşık.'],
      },
      ex: [
        mc('Z1', 'Wer demonstrierte?', I.read, `${SKATEPARK} Wer demonstrierte vor dem Rathaus?`, ['Rund 50 Kinder und Jugendliche.', 'Rund 800 Anwohner.', 'Der Stadtrat.'],
          ['Who demonstrated in front of the town hall?', 'Кто вышел на демонстрацию перед ратушей?', 'Хто вийшов на демонстрацію перед ратушею?', 'Belediye binasının önünde kimler gösteri yaptı?']),
        mc('Z1', 'Forderung', I.read, `${SKATEPARK} Was fordern die Demonstranten?`, ['Dass der Skatepark offen bleibt.', 'Dass ein neues Rathaus gebaut wird.', 'Dass der Bürgermeister zurücktritt.'],
          ['What are the demonstrators demanding?', 'Чего требуют демонстранты?', 'Чого вимагають демонстранти?', 'Göstericiler ne talep ediyor?']),
        mc('Z1', 'Grund der Sperrung', I.read, `${SKATEPARK} Warum war die Anlage gesperrt worden?`, ['Weil sich Leute über den Lärm beschwert hatten.', 'Weil sie zu alt war.', 'Weil ein Unfall passiert war.'],
          ['Why had the facility been closed?', 'Почему площадку закрыли?', 'Чому майданчик закрили?', 'Tesis neden kapatılmıştı?']),
        mc('Z1', 'Abstimmung', I.read, `${SKATEPARK} Was passiert im September?`, ['Der Stadtrat stimmt ab.', 'Der Park wird abgerissen.', 'Es gibt eine neue Demonstration.'],
          ['What will happen in September?', 'Что произойдёт в сентябре?', 'Що відбудеться у вересні?', 'Eylülde ne olacak?']),
        mc('Z1', 'Eröffnung', I.read, `${RHEINBRUECKE} Wann ist die Brücke eröffnet worden?`, ['Am Montag.', 'Vor zwei Jahren.', 'Im September.'],
          ['When was the bridge opened?', 'Когда открыли мост?', 'Коли відкрили міст?', 'Köprü ne zaman açıldı?']),
        mc('Z1', 'Für wen?', I.read, `${RHEINBRUECKE} Für wen wurde die Brücke gebaut?`, ['Für Fußgänger und Radfahrer.', 'Für Autos und Busse.', 'Für Züge.'],
          ['Who was the bridge built for?', 'Для кого построили мост?', 'Для кого збудували міст?', 'Köprü kimler için yapıldı?']),
        mc('Z1', 'Kosten', I.read, `${RHEINBRUECKE} Was erfährt man über die Kosten?`, ['Die Brücke war teurer als geplant.', 'Die Brücke war billiger als geplant.', 'Die Kosten sind nicht bekannt.'],
          ['What do you learn about the costs?', 'Что можно узнать о расходах?', 'Що можна дізнатися про витрати?', 'Maliyetler hakkında ne öğreniyoruz?']),
        mc('Z1', 'Meinung der Bürger', I.read, `${RHEINBRUECKE} Wie denken die meisten Bürger über die Brücke?`, ['Sie sind zufrieden.', 'Sie sind dagegen.', 'Sie haben keine Meinung.'],
          ['What do most citizens think about the bridge?', 'Что большинство граждан думает о мосте?', 'Що більшість громадян думає про міст?', 'Yurttaşların çoğu köprü hakkında ne düşünüyor?']),
      ],
    },
    {
      title: 'Biografie und Vortrag',
      t: ['Biography and talk', 'Биография и доклад', 'Біографія і доповідь', 'Biyografi ve konuşma'],
      card: {
        id: 'p6_biografie',
        rule: 'Eine Biografie und einen Vortrag verstehen: Eine Biografie erzählt ein Leben in zeitlicher Reihenfolge: geboren, aufgewachsen, Ausbildung, Beruf, wichtige Ereignisse, heute. Achte auf Jahreszahlen und Zeitangaben: 1944, nach dem Krieg, 1989, nach der Wiedervereinigung, heute. Ein Vortrag ordnet Informationen nach Themen und Daten. Typisch ist das Passiv: wurde geboren, wurde gewählt, wurde geteilt, wurde gebaut. Mit seinen 81 Jahren = obwohl er schon 81 ist.',
        examples: ['Geboren wurde er 1944 in Dresden.', 'Nach der Wiedervereinigung wurde er in den Stadtrat gewählt.', 'Deutschland wurde in vier Zonen geteilt.'],
        highlight: 'verb',
        t: [
          'Understanding a biography and a talk: a biography tells a life in chronological order: born, grew up, training, job, important events, today. Pay attention to dates and time expressions: 1944, nach dem Krieg (after the war), 1989, nach der Wiedervereinigung (after reunification), heute (today). A talk arranges information by topics and dates. The passive is typical: wurde geboren (was born), wurde gewählt (was elected), wurde geteilt (was divided), wurde gebaut (was built). Mit seinen 81 Jahren = although he is already 81.',
          'Как понимать биографию и доклад: биография рассказывает о жизни в хронологическом порядке: родился, вырос, образование, профессия, важные события, сегодня. Обращайте внимание на годы и указания времени: 1944, nach dem Krieg (после войны), 1989, nach der Wiedervereinigung (после воссоединения), heute (сегодня). Доклад упорядочивает информацию по темам и датам. Типичен пассив: wurde geboren (родился), wurde gewählt (был избран), wurde geteilt (была разделена), wurde gebaut (была построена). Mit seinen 81 Jahren = несмотря на свои 81 год.',
          'Як розуміти біографію і доповідь: біографія розповідає про життя в хронологічному порядку: народився, виріс, освіта, професія, важливі події, сьогодні. Звертайте увагу на роки і вказівки часу: 1944, nach dem Krieg (після війни), 1989, nach der Wiedervereinigung (після возз’єднання), heute (сьогодні). Доповідь упорядковує інформацію за темами і датами. Типовий пасив: wurde geboren (народився), wurde gewählt (був обраний), wurde geteilt (була поділена), wurde gebaut (була збудована). Mit seinen 81 Jahren = попри свій 81 рік.',
          'Bir biyografiyi ve bir konuşmayı anlamak: Biyografi bir yaşamı zaman sırasıyla anlatır: doğum, büyüme, eğitim, meslek, önemli olaylar, bugün. Yıllara ve zaman ifadelerine dikkat edin: 1944, nach dem Krieg (savaştan sonra), 1989, nach der Wiedervereinigung (yeniden birleşmeden sonra), heute (bugün). Bir konuşma bilgileri konulara ve tarihlere göre düzenler. Edilgen çatı tipiktir: wurde geboren (doğdu), wurde gewählt (seçildi), wurde geteilt (bölündü), wurde gebaut (inşa edildi). Mit seinen 81 Jahren = 81 yaşında olmasına rağmen.',
        ],
        hint: ['Biografie: geboren – aufgewachsen – Beruf – wichtige Ereignisse – heute. Achte auf Jahreszahlen und auf das Passiv (wurde gewählt).', 'Biography: born – grew up – job – important events – today. Look for dates and the passive (wurde gewählt).', 'Биография: родился – вырос – профессия – важные события – сегодня. Следите за годами и пассивом (wurde gewählt).', 'Біографія: народився – виріс – професія – важливі події – сьогодні. Стежте за роками і пасивом (wurde gewählt).', 'Biyografi: doğum – büyüme – meslek – önemli olaylar – bugün. Yıllara ve edilgen çatıya (wurde gewählt) dikkat edin.'],
      },
      ex: [
        mc('Z2', 'Beruf', I.read, `${ARCHIVAR} Welchen Beruf hatte Walter Krause?`, ['Er war Lehrer für Geschichte.', 'Er war Bürgermeister.', 'Er war Polizist.'],
          ['What was Walter Krause’s profession?', 'Кем работал Walter Krause?', 'Ким працював Walter Krause?', 'Walter Krause’nin mesleği neydi?']),
        mc('Z2', '1989', I.read, `${ARCHIVAR} Wofür demonstrierte er 1989?`, ['Für freie Wahlen.', 'Für höhere Löhne.', 'Für neue Schulen.'],
          ['What did he demonstrate for in 1989?', 'За что он выходил на демонстрации в 1989 году?', 'За що він виходив на демонстрації 1989 року?', '1989’da ne için gösteri yaptı?']),
        mc('Z2', 'nach der Wiedervereinigung', I.read, `${ARCHIVAR} Was passierte nach der Wiedervereinigung?`, ['Er wurde in den Stadtrat gewählt.', 'Er zog nach Westdeutschland.', 'Er ging sofort in Rente.'],
          ['What happened after reunification?', 'Что произошло после воссоединения?', 'Що сталося після возз’єднання?', 'Yeniden birleşmeden sonra ne oldu?']),
        mc('Z2', 'heute', I.read, `${ARCHIVAR} Was macht er heute?`, ['Er führt Schulklassen durch das Archiv.', 'Er arbeitet im Stadtrat.', 'Er unterrichtet an einer Schule.'],
          ['What does he do today?', 'Чем он занимается сегодня?', 'Чим він займається сьогодні?', 'Bugün ne yapıyor?']),
        mc('Z2', '1949', I.read, `${NACHKRIEGSZEIT} Was entstand 1949 aus den drei Westzonen?`, ['Die Bundesrepublik.', 'Die DDR.', 'Die Berliner Mauer.'],
          ['What was created from the three western zones in 1949?', 'Что возникло в 1949 году из трёх западных зон?', 'Що виникло 1949 року з трьох західних зон?', '1949’da üç batı bölgesinden ne oluştu?']),
        mc('Z2', 'Arbeitskräfte', I.read, `${NACHKRIEGSZEIT} Warum kamen ab 1955 Menschen aus anderen Ländern?`, ['Weil viele Arbeitskräfte gebraucht wurden.', 'Weil sie dort studieren wollten.', 'Weil die Grenze geöffnet wurde.'],
          ['Why did people come from other countries from 1955 onwards?', 'Почему с 1955 года стали приезжать люди из других стран?', 'Чому з 1955 року почали приїжджати люди з інших країн?', '1955’ten itibaren başka ülkelerden insanlar neden geldi?']),
        mc('Z2', 'Wie lange?', I.read, `${NACHKRIEGSZEIT} Wie lange stand die Berliner Mauer?`, ['28 Jahre.', '40 Jahre.', '12 Jahre.'],
          ['How long did the Berlin Wall stand?', 'Сколько лет простояла Берлинская стена?', 'Скільки років простояв Берлінський мур?', 'Berlin Duvarı kaç yıl ayakta kaldı?']),
      ],
    },
  ],
}

export default path
