import { I, gap, mc } from '../shared.mjs'

const BAECKER = 'Reportage: „Damir Kovac kam 1993 aus Bosnien nach Stuttgart. Er war damals zwölf und sprach kein Wort Deutsch. Heute führt er die Bäckerei, in der er früher als Schüler ausgeholfen hat. Neben Brezeln verkauft er auch Burek, eine Spezialität aus seiner alten Heimat. ‚Die Kunden freuen sich darüber‘, sagt er. Nächstes Jahr wird er einen zweiten Laden eröffnen. Sein Sohn träumt davon, das Geschäft später zu übernehmen.“'

/** B1.2 · Pfad 7 · Alte und neue Heimat – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'roh', I.choose, 'Das Fleisch ist noch nicht fertig, es ist innen noch ganz …', ['roh', 'reif', 'reich'],
      ['The meat is not done yet, it is still completely … inside.', 'Мясо ещё не готово, внутри оно ещё совсем …', 'М’ясо ще не готове, всередині воно ще зовсім …', 'Et henüz pişmemiş, içi hâlâ tamamen …']),
    mc('W2', 'Hauptstadt', I.choose, 'Bern ist die … der Schweiz, obwohl Zürich viel größer ist.', ['Hauptstadt', 'Hauptsache', 'Haustür'],
      ['Bern is the … of Switzerland, although Zurich is much bigger.', 'Берн – … Швейцарии, хотя Цюрих гораздо больше.', 'Берн – … Швейцарії, хоча Цюрих набагато більший.', 'Zürih çok daha büyük olmasına rağmen İsviçre’nin … Bern’dir.']),
    mc('G1', 'der Geburtstag', I.choose, 'Welches Wort ist richtig? die Geburt + der Tag →', ['der Geburtstag', 'der Geburttag', 'die Geburtstag'],
      ['Which word is correct? die Geburt (birth) + der Tag (day) →', 'Какое слово правильное? die Geburt (рождение) + der Tag (день) →', 'Яке слово правильне? die Geburt (народження) + der Tag (день) →', 'Hangi sözcük doğru? die Geburt (doğum) + der Tag (gün) →']),
    mc('G2', 'die Einladung', I.choose, 'Welches Nomen gehört zu „einladen“?', ['die Einladung', 'der Einladung', 'das Einladung'],
      ['Which noun belongs to “einladen” (to invite)?', 'Какое существительное образовано от «einladen» (приглашать)?', 'Який іменник утворено від «einladen» (запрошувати)?', '“Einladen” (davet etmek) fiilinden türeyen isim hangisidir?']),
    mc('G3', 'warten auf', I.choose, 'Wir warten seit einer halben Stunde … das Essen.', ['auf', 'an', 'für'],
      ['We have been waiting for the food for half an hour.', 'Мы уже полчаса ждём еду.', 'Ми вже пів години чекаємо на їжу.', 'Yarım saattir yemeği bekliyoruz.']),
    mc('G4', 'gehören zu', I.choose, 'Dieses Gericht gehört … jedem Familienfest.', ['zu', 'an', 'für'],
      ['This dish is part of every family celebration.', 'Это блюдо – часть каждого семейного праздника.', 'Ця страва – частина кожного родинного свята.', 'Bu yemek her aile kutlamasının bir parçasıdır.']),
    mc('G5', 'Worüber', I.choose, '… ärgerst du dich so? – Über den Lärm der Nachbarn.', ['Worüber', 'Woran', 'Über wen'],
      ['What are you so annoyed about? – The neighbours’ noise.', 'Из-за чего ты так сердишься? – Из-за шума соседей.', 'Через що ти так сердишся? – Через шум сусідів.', 'Neye bu kadar kızıyorsun? – Komşuların gürültüsüne.']),
    mc('K1', 'eine Spezialität erklären', I.react, '„Was ist das für ein Gericht?“', ['Das ist Pilaw, eine Spezialität aus meinem Heimatland.', 'Der Termin passt mir gut.', 'Das Land grenzt an die Türkei.'],
      ['“What kind of dish is that?”', '«Что это за блюдо?»', '«Що це за страва?»', '“Bu nasıl bir yemek?”']),
    mc('K2', 'sich kümmern um', I.choose, 'Ich … mich um die Dekoration, wenn du die Einkäufe machst.', ['kümmere', 'kümmert', 'gekümmert'],
      ['I will take care of the decorations if you do the shopping.', 'Я займусь украшениями, если ты сделаешь покупки.', 'Я займуся прикрасами, якщо ти зробиш покупки.', 'Sen alışverişi yaparsan süslemelerle ben ilgilenirim.']),
    mc('K3', 'Bei dem Wort … denke ich an', I.choose, 'Bei dem Wort „Heimat“ … ich zuerst an das Haus meiner Großeltern.', ['denke', 'danke', 'dauere'],
      ['The word “Heimat” first makes me think of my grandparents’ house.', 'При слове «Heimat» я сначала думаю о доме бабушки и дедушки.', 'При слові «Heimat» я спочатку думаю про будинок бабусі й дідуся.', '“Heimat” sözcüğünü duyunca önce büyükannemle büyükbabamın evini düşünüyorum.']),
    mc('K4', 'bekannt für', I.choose, 'Italien ist bekannt … sein Essen, seine Mode und seine alten Städte.', ['für', 'an', 'zu'],
      ['Italy is known for its food, its fashion and its old towns.', 'Италия известна своей кухней, модой и старинными городами.', 'Італія відома своєю кухнею, модою і старовинними містами.', 'İtalya yemekleri, modası ve eski şehirleriyle tanınır.']),
    mc('Z1', 'Was verkauft er?', I.read, `${BAECKER} Was verkauft Damir Kovac in seiner Bäckerei?`, ['Brezeln und eine Spezialität aus Bosnien.', 'Nur deutsche Brote.', 'Nur Spezialitäten aus seiner alten Heimat.'],
      ['What does Damir Kovac sell in his bakery?', 'Что Damir Kovac продаёт в своей пекарне?', 'Що Damir Kovac продає у своїй пекарні?', 'Damir Kovac fırınında ne satıyor?']),
    gap('G5', 'Dazu', I.adverb, 'Du hast das Stipendium bekommen? ', ' gratuliere ich dir herzlich!', 'Dazu', ['Daran', 'Darüber'],
      ['You got the scholarship? I congratulate you warmly on that!', 'Ты получил стипендию? От души поздравляю тебя с этим!', 'Ти отримав стипендію? Щиро вітаю тебе з цим!', 'Bursu kazandın mı? Bunun için seni içtenlikle kutlarım!'], 'gratulieren zu'),
  ],
  size: 13,
  test: [
    mc('W1', 'Beilage', I.choose, 'Zum Schnitzel bestellen wir als … Pommes und einen kleinen Salat.', ['Beilage', 'Beratung', 'Bewerbung'],
      ['With the schnitzel we are ordering chips and a small salad as a …', 'К шницелю мы заказываем на … картофель фри и небольшой салат.', 'До шніцеля ми замовляємо на … картоплю фрі й невеликий салат.', 'Şnitzelin yanına … olarak patates kızartması ve küçük bir salata sipariş ediyoruz.']),
    mc('W2', 'Staatsangehörigkeit', I.choose, 'Nach acht Jahren in Deutschland hat er die deutsche … bekommen und darf jetzt wählen.', ['Staatsangehörigkeit', 'Sehenswürdigkeit', 'Geschwindigkeit'],
      ['After eight years in Germany he has obtained German … and is now allowed to vote.', 'Спустя восемь лет в Германии он получил немецкое … и теперь может голосовать.', 'Через вісім років у Німеччині він отримав німецьке … і тепер може голосувати.', 'Almanya’da sekiz yıl geçirdikten sonra Alman … aldı ve artık oy kullanabiliyor.']),
    mc('G1', 'die Jahreszeit', I.choose, 'Welcher Artikel ist richtig? das Jahr + die Zeit → … Jahreszeit', ['die', 'das', 'der'],
      ['Which article is correct? das Jahr + die Zeit → … Jahreszeit (season)', 'Какой артикль правильный? das Jahr + die Zeit → … Jahreszeit (время года)', 'Який артикль правильний? das Jahr + die Zeit → … Jahreszeit (пора року)', 'Hangi artikel doğru? das Jahr + die Zeit → … Jahreszeit (mevsim)']),
    mc('G1', 'das Hochzeitskleid', I.choose, 'Welches Wort ist richtig? die Hochzeit + das Kleid →', ['das Hochzeitskleid', 'das Hochzeitkleid', 'die Hochzeitskleid'],
      ['Which word is correct? die Hochzeit (wedding) + das Kleid (dress) →', 'Какое слово правильное? die Hochzeit (свадьба) + das Kleid (платье) →', 'Яке слово правильне? die Hochzeit (весілля) + das Kleid (сукня) →', 'Hangi sözcük doğru? die Hochzeit (düğün) + das Kleid (elbise) →']),
    mc('G2', 'das Schlafzimmer', I.choose, 'Welches Wort ist richtig? schlafen + das Zimmer →', ['das Schlafzimmer', 'das Schlafenzimmer', 'die Schlafzimmer'],
      ['Which word is correct? schlafen (to sleep) + das Zimmer (room) →', 'Какое слово правильное? schlafen (спать) + das Zimmer (комната) →', 'Яке слово правильне? schlafen (спати) + das Zimmer (кімната) →', 'Hangi sözcük doğru? schlafen (uyumak) + das Zimmer (oda) →']),
    mc('G2', 'die Entschuldigung', I.choose, 'Welches Nomen gehört zu „sich entschuldigen“?', ['die Entschuldigung', 'der Entschuldig', 'das Entschuldigung'],
      ['Which noun belongs to “sich entschuldigen” (to apologise)?', 'Какое существительное образовано от «sich entschuldigen» (извиняться)?', 'Який іменник утворено від «sich entschuldigen» (вибачатися)?', '“Sich entschuldigen” (özür dilemek) fiilinden türeyen isim hangisidir?']),
    mc('G3', 'sich freuen auf', I.choose, 'Ich freue mich riesig … deinen Besuch nächsten Monat!', ['auf', 'an', 'von'],
      ['I am really looking forward to your visit next month!', 'Я очень жду твоего приезда в следующем месяце!', 'Я дуже чекаю на твій приїзд наступного місяця!', 'Gelecek ayki ziyaretini dört gözle bekliyorum!']),
    mc('G3', 'sich ärgern über', I.choose, 'Opa ärgert sich jeden Tag … die Nachrichten im Fernsehen.', ['über', 'auf', 'um'],
      ['Grandad gets annoyed about the news on television every day.', 'Дедушка каждый день сердится из-за новостей по телевизору.', 'Дідусь щодня сердиться через новини по телевізору.', 'Dedem her gün televizyondaki haberlere kızıyor.']),
    mc('G4', 'sprechen mit', I.choose, 'Hast du schon … deinem Chef über den Urlaub gesprochen?', ['mit', 'zu', 'an'],
      ['Have you already talked to your boss about the holiday?', 'Ты уже говорил с начальником об отпуске?', 'Ти вже говорив із керівником про відпустку?', 'Patronunla tatil hakkında konuştun mu?']),
    mc('G4', 'erzählen von', I.choose, 'Er erzählt oft … seiner Zeit als Koch auf einem Schiff.', ['von', 'an', 'über'],
      ['He often talks about his time as a cook on a ship.', 'Он часто рассказывает о том времени, когда работал поваром на корабле.', 'Він часто розповідає про той час, коли працював кухарем на кораблі.', 'Bir gemide aşçı olarak çalıştığı dönemi sık sık anlatır.']),
    mc('G5', 'Worauf', I.choose, '… freust du dich am meisten? – Auf das Wiedersehen mit meiner Familie.', ['Worauf', 'Worüber', 'Auf wen'],
      ['What are you looking forward to most? – Seeing my family again.', 'Чего ты ждёшь больше всего? – Встречи с семьёй.', 'На що ти чекаєш найбільше? – На зустріч із родиною.', 'En çok neyi dört gözle bekliyorsun? – Ailemle yeniden görüşmeyi.']),
    mc('G5', 'Mit wem', I.choose, '… hast du gerade telefoniert? – Mit meinem Onkel in Kanada.', ['Mit wem', 'Womit', 'Mit was'],
      ['Who were you on the phone to just now? – My uncle in Canada.', 'С кем ты только что говорил по телефону? – С дядей в Канаде.', 'З ким ти щойно говорив телефоном? – З дядьком у Канаді.', 'Az önce kiminle telefonda konuştun? – Kanada’daki amcamla.']),
    mc('K1', 'Bei uns isst man …', I.react, '„Was isst man bei euch zum Frühstück?“', ['Bei uns isst man morgens gern Oliven, Käse und Brot.', 'Ich kümmere mich um das Frühstück.', 'Wovon träumst du?'],
      ['“What do people eat for breakfast in your country?”', '«Что у вас едят на завтрак?»', '«Що у вас їдять на сніданок?»', '“Sizde kahvaltıda ne yenir?”']),
    mc('K2', 'einen Termin vorschlagen', I.react, '„Welcher Termin passt euch am besten?“', ['Vielleicht der Freitagabend? Da haben die meisten Zeit.', 'Ich bringe einen Kuchen mit.', 'Bei uns isst man gern Suppe.'],
      ['“Which date suits you best?”', '«Какая дата вам подходит больше всего?»', '«Яка дата вам підходить найбільше?»', '“Size en çok hangi tarih uyar?”']),
    mc('K3', 'bedeutet für mich', I.choose, '„Heimat“ bedeutet … mich, dass ich so sein kann, wie ich bin.', ['für', 'an', 'von'],
      ['To me “Heimat” means that I can be the way I am.', '«Heimat» для меня означает, что я могу быть таким, какой я есть.', '«Heimat» для мене означає, що я можу бути таким, яким я є.', '“Heimat” benim için olduğum gibi olabilmek demek.']),
    mc('K4', 'grenzt an', I.choose, 'Österreich … an Deutschland, Italien, die Schweiz und fünf weitere Länder.', ['grenzt', 'grenzen', 'gegrenzt'],
      ['Austria borders Germany, Italy, Switzerland and five other countries.', 'Австрия граничит с Германией, Италией, Швейцарией и ещё пятью странами.', 'Австрія межує з Німеччиною, Італією, Швейцарією та ще п’ятьма країнами.', 'Avusturya’nın Almanya, İtalya, İsviçre ve beş ülke daha ile sınırı var.']),
    mc('Z1', 'Vergangenheit', I.read, `${BAECKER} Wie alt war Damir Kovac, als er nach Deutschland kam?`, ['Zwölf Jahre.', 'Zwanzig Jahre.', 'Dreißig Jahre.'],
      ['How old was Damir Kovac when he came to Germany?', 'Сколько лет было Damir Kovac, когда он приехал в Германию?', 'Скільки років було Damir Kovac, коли він приїхав до Німеччини?', 'Damir Kovac Almanya’ya geldiğinde kaç yaşındaydı?']),
    mc('Z1', 'Zukunft', I.read, `${BAECKER} Was plant er für das nächste Jahr?`, ['Er wird einen zweiten Laden eröffnen.', 'Er wird nach Bosnien zurückkehren.', 'Er wird die Bäckerei verkaufen.'],
      ['What is he planning for next year?', 'Что он планирует на следующий год?', 'Що він планує на наступний рік?', 'Gelecek yıl için ne planlıyor?']),
    mc('Z1', 'Traum des Sohnes', I.read, `${BAECKER} Wovon träumt sein Sohn?`, ['Davon, das Geschäft später zu übernehmen.', 'Davon, in Bosnien zu leben.', 'Davon, Lehrer zu werden.'],
      ['What does his son dream of?', 'О чём мечтает его сын?', 'Про що мріє його син?', 'Oğlu neyi hayal ediyor?']),
    gap('W1', 'Zutaten', I.word, 'Welche ', ' brauche ich für die Suppe? – Kartoffeln, Zwiebeln und Karotten.', 'Zutaten', ['Zeitungen', 'Zusagen'],
      ['Which ingredients do I need for the soup? – Potatoes, onions and carrots.', 'Какие ингредиенты мне нужны для супа? – Картофель, лук и морковь.', 'Які інгредієнти мені потрібні для супу? – Картопля, цибуля і морква.', 'Çorba için hangi malzemeler gerekiyor? – Patates, soğan ve havuç.'],
      ['ingredients', 'ингредиенты', 'інгредієнти', 'malzemeler']),
    gap('W2', 'Einwohner', I.word, 'Berlin hat etwa 3,7 Millionen ', ' und ist damit die größte Stadt Deutschlands.', 'Einwohner', ['Einladungen', 'Eingänge'],
      ['Berlin has about 3.7 million inhabitants and is thus the biggest city in Germany.', 'В Берлине около 3,7 миллиона жителей, и поэтому это самый большой город Германии.', 'У Берліні близько 3,7 мільйона мешканців, і тому це найбільше місто Німеччини.', 'Berlin’in yaklaşık 3,7 milyon nüfusu var ve böylece Almanya’nın en büyük şehri.'],
      ['inhabitants', 'жители', 'мешканці', 'sakinler, nüfus']),
    gap('G1', 'Feiertag', I.form, 'Der 1. Mai ist in Deutschland ein ', ': Die meisten Menschen müssen nicht arbeiten.', 'Feiertag', ['Feierstag', 'Feierntag'],
      ['1 May is a public holiday in Germany: most people do not have to work.', '1 мая в Германии праздничный день: большинству людей не нужно работать.', '1 травня в Німеччині святковий день: більшості людей не треба працювати.', '1 Mayıs Almanya’da resmî tatildir: İnsanların çoğu çalışmak zorunda değildir.'], 'die Feier + der Tag'),
    gap('G2', 'Erinnerung', I.form, 'Die ', ' an meinen ersten Schultag ist noch ganz lebendig.', 'Erinnerung', ['Erinnern', 'Erinnerte'],
      ['The memory of my first day at school is still very vivid.', 'Воспоминание о моём первом школьном дне ещё очень живо.', 'Спогад про мій перший шкільний день ще дуже живий.', 'İlk okul günümün anısı hâlâ çok canlı.'], 'sich erinnern'),
    gap('G3', 'sich erinnern an', I.prep, 'Kannst du dich noch ', ' unseren ersten Deutschlehrer erinnern?', 'an', ['auf', 'über'],
      ['Can you still remember our first German teacher?', 'Ты ещё помнишь нашего первого учителя немецкого?', 'Ти ще пам’ятаєш нашого першого вчителя німецької?', 'İlk Almanca öğretmenimizi hâlâ hatırlıyor musun?'], 'an / auf / über'),
    gap('G4', 'träumen von', I.prep, 'Ich träume ', ' einem kleinen Haus mit Garten.', 'von', ['an', 'über'],
      ['I dream of a small house with a garden.', 'Я мечтаю о маленьком доме с садом.', 'Я мрію про маленький будинок із садом.', 'Bahçeli küçük bir ev hayal ediyorum.'], 'von / an / über'),
    gap('G5', 'davon', I.adverb, 'Wir fahren im Sommer nach Kroatien. Ich träume schon seit Wochen ', '.', 'davon', ['daran', 'darauf'],
      ['We are going to Croatia in the summer. I have been dreaming of it for weeks.', 'Летом мы едем в Хорватию. Я мечтаю об этом уже несколько недель.', 'Улітку ми їдемо до Хорватії. Я мрію про це вже кілька тижнів.', 'Yazın Hırvatistan’a gidiyoruz. Haftalardır bunu hayal ediyorum.'], 'träumen von'),
    gap('K1', 'Spezialität', I.word, 'Eine ', ' aus meinem Heimatland ist Baklava: ein süßes Gebäck mit Nüssen.', 'Spezialität', ['Speisekarte', 'Spedition'],
      ['A speciality from my home country is baklava: a sweet pastry with nuts.', 'Традиционное блюдо моей родины – пахлава: сладкая выпечка с орехами.', 'Традиційна страва моєї батьківщини – пахлава: солодка випічка з горіхами.', 'Memleketimin yöresel bir lezzeti baklavadır: cevizli tatlı bir hamur işi.'],
      ['speciality', 'традиционное блюдо', 'традиційна страва', 'yöresel lezzet']),
    gap('K2', 'mitbringen', I.verb, 'Wer ', ' einen Salat mit? Ich mache schon das Brot.', 'bringt', ['bringen', 'gebracht'],
      ['Who is bringing a salad? I am already making the bread.', 'Кто принесёт салат? Я уже беру на себя хлеб.', 'Хто принесе салат? Я вже беру на себе хліб.', 'Kim salata getiriyor? Ekmeği zaten ben yapıyorum.'], 'mitbringen'),
    gap('K3', 'verbinde', I.verb, 'Mit dem Wort „Sommer“ ', ' ich Ferien bei meinen Großeltern auf dem Land.', 'verbinde', ['verbindet', 'verbunden'],
      ['I associate the word “Sommer” with holidays at my grandparents’ in the country.', 'Со словом «Sommer» я связываю каникулы у бабушки и дедушки в деревне.', 'Зі словом «Sommer» я пов’язую канікули в бабусі й дідуся в селі.', '“Sommer” sözcüğü bana köyde, büyükannemle büyükbabamın yanında geçen tatilleri çağrıştırıyor.'], 'verbinden'),
    gap('K4', 'liegt', I.verb, 'Mein Heimatland ', ' im Süden von Europa, direkt am Mittelmeer.', 'liegt', ['legt', 'liegen'],
      ['My home country lies in the south of Europe, right on the Mediterranean.', 'Моя родная страна расположена на юге Европы, прямо у Средиземного моря.', 'Моя рідна країна розташована на півдні Європи, просто біля Середземного моря.', 'Memleketim Avrupa’nın güneyinde, Akdeniz’in hemen kıyısında yer alır.'], 'liegen'),
  ],
}

export default check
