import { I, gap, mc, sb } from '../shared.mjs'

const UMFRAGE = 'Umfrage: „Ein Forschungsinstitut wollte wissen, wie sich junge Erwachsene informieren. Mehr als die Hälfte gab an, Nachrichten fast nur noch über soziale Netzwerke zu lesen. Gedruckte Zeitungen spielen kaum noch eine Rolle. Überraschend ist, dass viele Befragte den klassischen Medien trotzdem mehr vertrauen. Die Forscher erklären das damit, dass Zeitungen und Sender ihre Quellen offenlegen. Sie empfehlen den Redaktionen, ihre Arbeit noch deutlicher zu erklären.“'

/** B2.1 · Pfad 3 · Medien – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'recherchieren', I.choose, 'Bevor ein Journalist einen Artikel schreibt, muss er gründlich …', ['recherchieren', 'abonnieren', 'kommentieren'],
      ['Before a journalist writes an article, he has to … thoroughly.', 'Прежде чем журналист напишет статью, он должен тщательно …', 'Перш ніж журналіст напише статтю, він має ретельно …', 'Bir gazeteci makale yazmadan önce titizlikle … zorundadır.']),
    mc('G1', 'sich darüber beschweren', I.choose, 'Der Sender hat die Serie abgesetzt. Viele Fans haben sich … beschwert.', ['darüber', 'darauf', 'dafür'],
      ['The broadcaster has cancelled the series. Many fans have complained about it.', 'Канал снял сериал с эфира. Многие поклонники пожаловались на это.', 'Канал зняв серіал з ефіру. Багато шанувальників поскаржилися на це.', 'Kanal diziyi yayından kaldırdı. Birçok hayran bundan şikâyet etti.']),
    mc('G2', 'Wofür', I.choose, '… interessierst du dich mehr – für Politik oder für Sport?', ['Wofür', 'Worauf', 'Woran'],
      ['What are you more interested in – politics or sport?', 'Чем ты интересуешься больше – политикой или спортом?', 'Чим ти цікавишся більше – політикою чи спортом?', 'Neyle daha çok ilgileniyorsun – siyasetle mi, sporla mı?']),
    mc('G3', 'Person: auf ihn', I.choose, 'Der Reporter hat einen Preis bekommen. Die ganze Redaktion ist stolz …', ['auf ihn', 'darauf', 'worauf'],
      ['The reporter has won a prize. The whole editorial team is proud of him.', 'Репортёр получил премию. Вся редакция им гордится.', 'Репортер отримав премію. Уся редакція ним пишається.', 'Muhabir bir ödül aldı. Bütün yazı işleri onunla gurur duyuyor.'], { h: 'person' }),
    mc('G4', 'sich darauf verlassen, dass', I.choose, 'Die Leser können sich … verlassen, dass alle Angaben geprüft wurden.', ['darauf', 'daran', 'davon'],
      ['Readers can rely on all the information having been checked.', 'Читатели могут положиться на то, что все сведения были проверены.', 'Читачі можуть покластися на те, що всі відомості були перевірені.', 'Okurlar bütün bilgilerin denetlendiğine güvenebilir.']),
    mc('G5', 'zweifeln an', I.choose, 'Niemand zweifelt … der Echtheit dieser Fotos.', ['an', 'über', 'von'],
      ['Nobody doubts the authenticity of these photos.', 'Никто не сомневается в подлинности этих фотографий.', 'Ніхто не сумнівається в справжності цих фотографій.', 'Bu fotoğrafların gerçekliğinden kimse kuşku duymuyor.'], { h: 'verb' }),
    mc('G6', 'planen, … zu', I.choose, 'Der Sender plant, die Sendung künftig am Sonntagabend …', ['zu zeigen', 'zeigen', 'zeigt'],
      ['The broadcaster is planning to show the programme on Sunday evenings in future.', 'Канал планирует в дальнейшем показывать передачу в воскресенье вечером.', 'Канал планує надалі показувати передачу в неділю ввечері.', 'Kanal programı bundan sonra pazar akşamları yayımlamayı planlıyor.']),
    mc('G7', 'verschiedene Subjekte', I.sentence, 'Oleg wünscht sich etwas: Sein Sohn soll mehr lesen.', ['Oleg wünscht sich, dass sein Sohn mehr liest.', 'Oleg wünscht sich, sein Sohn mehr zu lesen.', 'Oleg wünscht sich, mehr zu lesen.'],
      ['Oleg wishes for something: his son should read more.', 'Oleg кое-чего хочет: его сын должен больше читать.', 'Oleg дечого хоче: його син має більше читати.', 'Oleg bir şey diliyor: Oğlu daha çok okusun.'], { h: 'subjekt' }),
    mc('G8', 'Wer handelt?', I.choose, 'Wer soll vorsichtig sein? „Der Experte rät den Nutzern, mit ihren Daten vorsichtig zu sein.“', ['die Nutzer', 'der Experte', 'die Daten'],
      ['Who should be careful? “Der Experte rät den Nutzern, mit ihren Daten vorsichtig zu sein.”', 'Кто должен быть осторожным? «Der Experte rät den Nutzern, mit ihren Daten vorsichtig zu sein.»', 'Хто має бути обережним? «Der Experte rät den Nutzern, mit ihren Daten vorsichtig zu sein.»', 'Kim dikkatli olmalı? “Der Experte rät den Nutzern, mit ihren Daten vorsichtig zu sein.”']),
    mc('G9', 'Modalverb ohne zu', I.choose, 'Du solltest nicht alles …, was im Internet steht.', ['glauben', 'zu glauben', 'geglaubt'],
      ['You should not believe everything that is on the internet.', 'Не стоит верить всему, что написано в интернете.', 'Не варто вірити всьому, що написано в інтернеті.', 'İnternette yazan her şeye inanmamalısın.'], { h: 'modal' }),
    mc('Z1', 'Umfrage: Vertrauen', I.read, `${UMFRAGE} Wie erklären die Forscher das Vertrauen in die klassischen Medien?`, ['damit, dass diese ihre Quellen offenlegen', 'damit, dass sie kostenlos sind', 'damit, dass sie nur gute Nachrichten bringen'],
      ['How do the researchers explain the trust in the traditional media?', 'Чем исследователи объясняют доверие к традиционным СМИ?', 'Чим дослідники пояснюють довіру до традиційних медіа?', 'Araştırmacılar geleneksel medyaya duyulan güveni neyle açıklıyor?']),
    gap('G4', 'darauf ankommen', I.word, 'Es kommt ', ' an, wer eine Nachricht geschrieben hat.', 'darauf', ['davon', 'daran'],
      ['What matters is who wrote a news item.', 'Важно то, кто написал сообщение.', 'Важливо те, хто написав повідомлення.', 'Önemli olan, bir haberi kimin yazdığıdır.'], 'ankommen auf'),
    sb('G9', 'trennbar: auszuschalten', I.order, 'Vergiss / nicht, / das Radio / auszuschalten!',
      ['Do not forget to switch off the radio!', 'Не забудь выключить радио!', 'Не забудь вимкнути радіо!', 'Radyoyu kapatmayı unutma!']),
  ],
  size: 13,
  test: [
    mc('W1', 'seriös', I.choose, 'Ein Sender, der unabhängig berichtet und seine Fehler korrigiert, gilt als …', ['seriös', 'einseitig', 'unterhaltsam'],
      ['A broadcaster that reports independently and corrects its mistakes is regarded as …', 'Канал, который сообщает независимо и исправляет свои ошибки, считается …', 'Канал, який повідомляє незалежно і виправляє свої помилки, вважається …', 'Bağımsız haber yapan ve hatalarını düzelten bir kanal … sayılır.']),
    mc('W1', 'Meinungsfreiheit', I.choose, 'Was bedeutet „Meinungsfreiheit“?', ['das Recht, die eigene Meinung öffentlich zu sagen', 'die Pflicht, eine Zeitung zu abonnieren', 'das Verbot, Kritik zu äußern'],
      ['What does “Meinungsfreiheit” mean?', 'Что означает «Meinungsfreiheit»?', 'Що означає «Meinungsfreiheit»?', '“Meinungsfreiheit” ne demek?']),
    gap('W1', 'Beitrag', I.word, 'Der kurze ', ' des Reporters aus dem Krisengebiet dauerte nur zwei Minuten.', 'Beitrag', ['Betrag', 'Vertrag'],
      ['The reporter’s short report from the crisis area lasted only two minutes.', 'Короткий сюжет репортёра из зоны кризиса длился всего две минуты.', 'Короткий сюжет репортера із зони кризи тривав лише дві хвилини.', 'Muhabirin kriz bölgesinden hazırladığı kısa haber yalnızca iki dakika sürdü.'],
      ['report, item', 'сюжет, репортаж', 'сюжет, репортаж', 'haber, yayın parçası']),
    mc('G1', 'darüber diskutieren', I.choose, 'Die Serie hat ein offenes Ende. Die Zuschauer diskutieren im Netz heftig …', ['darüber', 'daran', 'dazu'],
      ['The series has an open ending. Viewers are discussing it heatedly online.', 'У сериала открытый финал. Зрители бурно обсуждают это в сети.', 'У серіалу відкритий фінал. Глядачі бурхливо обговорюють це в мережі.', 'Dizinin sonu açık bırakılmış. İzleyiciler bunu internette hararetle tartışıyor.']),
    mc('G1', 'Bezugswort erkennen', I.choose, 'Worauf bezieht sich „daran“? „Früher gab es keine Smartphones. Mein Vater kann sich noch gut daran erinnern.“', ['auf die Zeit ohne Smartphones', 'auf meinen Vater', 'auf die Smartphones von heute'],
      ['What does “daran” refer to? “Früher gab es keine Smartphones. Mein Vater kann sich noch gut daran erinnern.”', 'К чему относится «daran»? «Früher gab es keine Smartphones. Mein Vater kann sich noch gut daran erinnern.»', 'До чого належить «daran»? «Früher gab es keine Smartphones. Mein Vater kann sich noch gut daran erinnern.»', '“daran” neyi gösteriyor? “Früher gab es keine Smartphones. Mein Vater kann sich noch gut daran erinnern.”']),
    gap('G1', 'darauf', I.word, 'Unsere Zeitung hat einen Preis für die beste Reportage gewonnen. Wir sind sehr stolz ', '.', 'darauf', ['darüber', 'dafür'],
      ['Our newspaper has won a prize for the best report. We are very proud of that.', 'Наша газета получила премию за лучший репортаж. Мы очень этим гордимся.', 'Наша газета отримала премію за найкращий репортаж. Ми дуже цим пишаємося.', 'Gazetemiz en iyi röportaj ödülünü kazandı. Bununla çok gurur duyuyoruz.'], 'stolz sein auf'),
    mc('G2', 'Worüber', I.choose, '… ärgern sich die Zuschauer am meisten? – Über die lange Werbung.', ['Worüber', 'Wofür', 'Wovon'],
      ['What annoys the viewers most? – The long commercials.', 'Что больше всего раздражает зрителей? – Долгая реклама.', 'Що найбільше дратує глядачів? – Довга реклама.', 'İzleyiciler en çok neye kızıyor? – Uzun reklamlara.']),
    mc('G2', 'Frage zur Antwort: Worauf', I.matchQuestion, 'Auf die Ergebnisse der Wahl.', ['Worauf warten alle so gespannt?', 'Worüber berichten die Sender?', 'Womit beschäftigen sich die Reporter?'],
      ['The results of the election.', 'Результатов выборов.', 'Результатів виборів.', 'Seçim sonuçlarını.']),
    gap('G2', 'worauf', I.qword, 'Kannst du mir sagen, ', ' sich dieser Artikel bezieht?', 'worauf', ['woran', 'wovon'],
      ['Can you tell me what this article refers to?', 'Ты можешь сказать мне, на что ссылается эта статья?', 'Ти можеш сказати мені, на що посилається ця стаття?', 'Bu makalenin neye dayandığını söyleyebilir misin?'], 'sich beziehen auf'),
    mc('G3', 'Person: über ihn', I.choose, 'Der Autor des Kommentars ist bekannt für seine klare Sprache. Viele Kollegen sprechen mit Respekt …', ['über ihn', 'darüber', 'worüber'],
      ['The author of the commentary is known for his clear language. Many colleagues speak about him with respect.', 'Автор комментария известен своим ясным языком. Многие коллеги говорят о нём с уважением.', 'Автор коментаря відомий своєю ясною мовою. Багато колег говорять про нього з повагою.', 'Yorumun yazarı açık diliyle tanınıyor. Birçok meslektaşı ondan saygıyla söz ediyor.'], { h: 'person' }),
    mc('G3', 'Person: Von wem', I.choose, '… hast du die Nachricht bekommen? – Von meinem Nachbarn.', ['Von wem', 'Wovon', 'Davon'],
      ['Who did you get the news from? – My neighbour.', 'От кого ты получил эту новость? – От моего соседа.', 'Від кого ти отримав цю новину? – Від мого сусіда.', 'Haberi kimden aldın? – Komşumdan.'], { h: 'person' }),
    gap('G3', 'Sache: darüber', I.word, 'Die Sendung wurde abgesetzt. Viele Zuschauer sind traurig ', '.', 'darüber', ['über sie', 'worüber'],
      ['The programme was cancelled. Many viewers are sad about it.', 'Передачу сняли с эфира. Многие зрители этим огорчены.', 'Передачу зняли з ефіру. Багато глядачів цим засмучені.', 'Program yayından kaldırıldı. Birçok izleyici buna üzülüyor.'], 'traurig sein über'),
    mc('G4', 'darauf bestehen, dass', I.choose, 'Der Sender besteht …, dass alle Interviews vor der Veröffentlichung geprüft werden.', ['darauf', 'dafür', 'damit'],
      ['The broadcaster insists that all interviews are checked before publication.', 'Канал настаивает на том, чтобы все интервью проверялись перед публикацией.', 'Канал наполягає на тому, щоб усі інтерв’ю перевірялися перед публікацією.', 'Kanal bütün röportajların yayımlanmadan önce denetlenmesinde ısrar ediyor.']),
    mc('G4', 'daran denken, dass', I.choose, 'Ich habe nicht … gedacht, dass die Sendung heute früher beginnt.', ['daran', 'darauf', 'darüber'],
      ['I did not remember that the programme starts earlier today.', 'Я не подумал о том, что передача сегодня начинается раньше.', 'Я не подумав про те, що передача сьогодні починається раніше.', 'Programın bugün daha erken başladığını düşünmedim.']),
    gap('G4', 'davon abhängen, ob', I.word, 'Der Erfolg eines Videos hängt ', ' ab, ob die ersten Sekunden spannend sind.', 'davon', ['darauf', 'daran'],
      ['The success of a video depends on whether the first seconds are exciting.', 'Успех видео зависит от того, насколько увлекательны первые секунды.', 'Успіх відео залежить від того, чи захопливі перші секунди.', 'Bir videonun başarısı ilk saniyelerin sürükleyici olup olmamasına bağlıdır.'], 'abhängen von'),
    mc('G5', 'sich informieren über', I.choose, 'Die Zuschauer können sich jederzeit … das aktuelle Programm informieren.', ['über', 'an', 'von'],
      ['Viewers can find out about the current schedule at any time.', 'Зрители могут в любое время узнать актуальную программу передач.', 'Глядачі можуть будь-коли дізнатися актуальну програму передач.', 'İzleyiciler güncel yayın akışı hakkında her zaman bilgi alabilir.']),
    mc('G5', 'hinweisen auf', I.choose, 'Der Bericht weist … hin, dass die Zahlen noch nicht bestätigt sind.', ['darauf', 'daran', 'davon'],
      ['The report points out that the figures have not yet been confirmed.', 'В сообщении указывается на то, что цифры ещё не подтверждены.', 'У повідомленні вказується на те, що цифри ще не підтверджені.', 'Haber, rakamların henüz doğrulanmadığına dikkat çekiyor.'], { h: 'verb' }),
    gap('G5', 'gehören zu', I.prep, 'Dieser Kanal gehört ', ' den beliebtesten Angeboten für junge Zuschauer.', 'zu', ['an', 'bei'],
      ['This channel is one of the most popular services for young viewers.', 'Этот канал относится к самым популярным предложениям для молодых зрителей.', 'Цей канал належить до найпопулярніших пропозицій для молодих глядачів.', 'Bu kanal genç izleyiciler için en sevilen yayınlar arasında yer alıyor.'], 'zu / an / bei'),
    mc('G6', 'hoffen, … zu', I.choose, 'Der junge Reporter hofft, bald eine feste Stelle beim Radio …', ['zu bekommen', 'bekommen', 'bekommt'],
      ['The young reporter hopes to get a permanent job in radio soon.', 'Молодой репортёр надеется скоро получить постоянное место на радио.', 'Молодий репортер сподівається невдовзі отримати постійне місце на радіо.', 'Genç muhabir yakında radyoda kalıcı bir iş bulmayı umuyor.']),
    mc('G6', 'dass-Satz → Infinitivsatz', I.sentence, 'Mateo hat vor, dass er im Sommer ein Praktikum bei einer Zeitung macht. Sage es kürzer.', ['Mateo hat vor, im Sommer ein Praktikum bei einer Zeitung zu machen.', 'Mateo hat vor, im Sommer ein Praktikum bei einer Zeitung machen.', 'Mateo hat vor, er im Sommer ein Praktikum bei einer Zeitung zu machen.'],
      ['Mateo intends to do an internship at a newspaper in the summer. Say it more briefly.', 'Mateo собирается летом пройти практику в газете. Скажите это короче.', 'Mateo збирається влітку пройти практику в газеті. Скажіть це коротше.', 'Mateo yazın bir gazetede staj yapmayı düşünüyor. Bunu daha kısa söyleyin.']),
    gap('G6', 'zu lesen', I.word, 'Es macht mir Spaß, am Wochenende in Ruhe die Zeitung ', ' lesen.', 'zu', ['um', 'für'],
      ['I enjoy reading the newspaper in peace at the weekend.', 'Мне нравится в выходные спокойно читать газету.', 'Мені подобається у вихідні спокійно читати газету.', 'Hafta sonu sakin sakin gazete okumak hoşuma gidiyor.'], 'zu / um / für'),
    mc('G7', 'Infinitivsatz nicht möglich', I.choose, 'In welchem Satz kann man den dass-Satz nicht durch einen Infinitivsatz ersetzen?', ['Der Vater möchte, dass sein Sohn das Handy weglegt.', 'Der Vater hofft, dass er heute früher nach Hause kommt.', 'Der Vater verspricht, dass er morgen Zeit hat.'],
      ['In which sentence can the dass-clause not be replaced by an infinitive clause?', 'В каком предложении dass-предложение нельзя заменить инфинитивным оборотом?', 'У якому реченні dass-речення не можна замінити інфінітивним зворотом?', 'Hangi cümlede dass’lı cümlenin yerine mastar cümlesi konamaz?'], { h: 'subjekt' }),
    mc('G7', 'nach berichten: dass', I.choose, 'Die Zeitung berichtet, … .', ['dass die Preise im Herbst steigen', 'die Preise im Herbst zu steigen', 'im Herbst die Preise steigen zu'],
      ['The newspaper reports that prices will rise in the autumn.', 'Газета сообщает, что осенью цены вырастут.', 'Газета повідомляє, що восени ціни зростуть.', 'Gazete fiyatların sonbaharda artacağını bildiriyor.']),
    gap('G7', 'dass', I.conjunction, 'Der Reporter weiß, ', ' er für diese Geschichte noch mehr Beweise braucht.', 'dass', ['zu', 'um'],
      ['The reporter knows that he needs even more evidence for this story.', 'Репортёр знает, что для этой истории ему нужно ещё больше доказательств.', 'Репортер знає, що для цієї історії йому потрібно ще більше доказів.', 'Muhabir bu haber için daha fazla kanıta ihtiyacı olduğunu biliyor.'], 'dass / zu / um'),
    mc('G8', 'raten, … fernzusehen', I.choose, 'Der Arzt rät meinem Vater, abends weniger …', ['fernzusehen', 'fernsehen', 'zu fernsehen'],
      ['The doctor advises my father to watch less television in the evenings.', 'Врач советует моему отцу меньше смотреть телевизор по вечерам.', 'Лікар радить моєму батькові менше дивитися телевізор вечорами.', 'Doktor babama akşamları daha az televizyon izlemesini öneriyor.']),
    mc('G8', 'Wer handelt?', I.choose, 'Wer soll das Passwort ändern? „Der Techniker empfiehlt allen Kunden, ihr Passwort zu ändern.“', ['die Kunden', 'der Techniker', 'niemand'],
      ['Who is to change the password? “Der Techniker empfiehlt allen Kunden, ihr Passwort zu ändern.”', 'Кто должен сменить пароль? «Der Techniker empfiehlt allen Kunden, ihr Passwort zu ändern.»', 'Хто має змінити пароль? «Der Techniker empfiehlt allen Kunden, ihr Passwort zu ändern.»', 'Parolayı kim değiştirecek? “Der Techniker empfiehlt allen Kunden, ihr Passwort zu ändern.”']),
    mc('G9', 'Modalverb ohne zu', I.choose, 'Ohne Abonnement kann man die Artikel leider nicht …', ['lesen', 'zu lesen', 'gelesen'],
      ['Unfortunately you cannot read the articles without a subscription.', 'К сожалению, без подписки статьи читать нельзя.', 'На жаль, без передплати статті читати не можна.', 'Ne yazık ki abonelik olmadan makaleler okunamıyor.'], { h: 'modal' }),
    gap('G9', 'abzubestellen', I.form, 'Wir haben beschlossen, die Zeitung zum Jahresende ', '.', 'abzubestellen', ['zu abbestellen', 'abbestellt'],
      ['We have decided to cancel the newspaper at the end of the year.', 'Мы решили отказаться от газеты в конце года.', 'Ми вирішили відмовитися від газети наприкінці року.', 'Gazete aboneliğini yıl sonunda iptal etmeye karar verdik.'], 'abbestellen'),
    mc('Z1', 'Umfrage: soziale Netzwerke', I.read, `${UMFRAGE} Wie informiert sich laut Umfrage mehr als die Hälfte der jungen Erwachsenen?`, ['fast nur noch über soziale Netzwerke', 'vor allem aus gedruckten Zeitungen', 'ausschließlich im Fernsehen'],
      ['According to the survey, how do more than half of young adults get their information?', 'Как, согласно опросу, получает информацию более половины молодых взрослых?', 'Як, згідно з опитуванням, отримує інформацію понад половина молодих дорослих?', 'Ankete göre genç yetişkinlerin yarısından fazlası nasıl bilgi ediniyor?']),
    mc('Z1', 'Umfrage: Empfehlung', I.read, `${UMFRAGE} Was empfehlen die Forscher den Redaktionen?`, ['ihre Arbeit noch deutlicher zu erklären', 'weniger Quellen zu nennen', 'keine Fehler mehr zuzugeben'],
      ['What do the researchers recommend to the editorial teams?', 'Что исследователи рекомендуют редакциям?', 'Що дослідники радять редакціям?', 'Araştırmacılar yazı işlerine ne öneriyor?']),
  ],
}

export default check
