import { I, gap, mc, sb } from '../shared.mjs'

const ARTIKEL = 'Zeitungsartikel: „Immer mehr Berufstätige klagen über Rückenschmerzen. Eine Krankenkasse hat deshalb 3000 Versicherte befragen lassen. Das Ergebnis: Fast die Hälfte sitzt täglich mehr als acht Stunden. Die meisten Beschwerden werden nach Ansicht der Fachleute durch Bewegungsmangel entstanden sein, nicht durch schwere körperliche Arbeit. Einige Firmen lassen ihre Mitarbeiter inzwischen während der Arbeitszeit an Kursen teilnehmen. Wer vorbeugen will, sollte den Aufzug stehen lassen und die Treppe nehmen.“'
const AUX = 'haben / sein'

/** B2.1 · Pfad 5 · Körperbewusstsein – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Verspannungen', I.choose, 'Der Masseur lockert die … im Rücken, die durch langes Sitzen entstanden sind.', ['Verspannungen', 'Vorsorgeuntersuchungen', 'Ernährungen'],
      ['The masseur loosens the … in the back that have been caused by sitting for a long time.', 'Массажист разминает … в спине, возникшие из-за долгого сидения.', 'Масажист розминає … у спині, що виникли через тривале сидіння.', 'Masör, uzun süre oturmaktan sırtta oluşan … gevşetiyor.']),
    mc('G1', 'Bedeutung: jemand anders handelt', I.choose, 'Was bedeutet „Ich lasse mein Blut untersuchen.“?', ['Ein Arzt oder ein Labor untersucht mein Blut.', 'Ich untersuche mein Blut selbst.', 'Ich untersuche das Blut eines Patienten.'],
      ['What does “Ich lasse mein Blut untersuchen.” mean?', 'Что означает «Ich lasse mein Blut untersuchen.»?', 'Що означає «Ich lasse mein Blut untersuchen.»?', '“Ich lasse mein Blut untersuchen.” ne demek?'], { h: 'selbst' }),
    mc('G2', 'er lässt … nicht', I.choose, 'Der Arzt … mich nach der Grippe noch nicht wieder ins Schwimmbad gehen.', ['lässt', 'lasst', 'lasse'],
      ['After my flu the doctor is not letting me go to the swimming pool again yet.', 'После гриппа врач пока не разрешает мне снова ходить в бассейн.', 'Після грипу лікар поки не дозволяє мені знову ходити до басейну.', 'Doktor gripten sonra yeniden yüzme havuzuna gitmeme henüz izin vermiyor.']),
    mc('G3', 'Bedeutung: stehen lassen', I.choose, 'Was bedeutet „Er lässt den Kuchen stehen.“?', ['Er isst den Kuchen nicht.', 'Er backt einen Kuchen.', 'Er bestellt einen Kuchen.'],
      ['What does “Er lässt den Kuchen stehen.” mean?', 'Что означает «Er lässt den Kuchen stehen.»?', 'Що означає «Er lässt den Kuchen stehen.»?', '“Er lässt den Kuchen stehen.” ne demek?']),
    mc('G4', 'Perfekt mit Infinitiv', I.choose, 'Ich habe mir gestern einen Zahn ziehen …', ['lassen', 'gelassen', 'ließ'],
      ['I had a tooth pulled yesterday.', 'Вчера мне удалили зуб.', 'Учора мені видалили зуб.', 'Dün bir dişimi çektirdim.']),
    mc('G5', 'Bedeutung: erlauben', I.choose, 'Welche Bedeutung hat „lassen“ im Satz „Der Trainer lässt uns nach dem Spiel ausschlafen.“?', ['erlauben', 'veranlassen', 'unterlassen'],
      ['What does “lassen” mean in the sentence “Der Trainer lässt uns nach dem Spiel ausschlafen.”?', 'Какое значение имеет «lassen» в предложении «Der Trainer lässt uns nach dem Spiel ausschlafen.»?', 'Яке значення має «lassen» у реченні «Der Trainer lässt uns nach dem Spiel ausschlafen.»?', '“Der Trainer lässt uns nach dem Spiel ausschlafen.” cümlesinde “lassen” ne anlama geliyor?']),
    mc('G6', 'vergessen haben', I.choose, 'Paul ist nicht gekommen. Er wird den Termin beim Zahnarzt vergessen …', ['haben', 'hat', 'gehabt'],
      ['Paul has not come. He will have forgotten his dentist’s appointment.', 'Paul не пришёл. Он, должно быть, забыл о приёме у стоматолога.', 'Paul не прийшов. Він, мабуть, забув про прийом у стоматолога.', 'Paul gelmedi. Dişçi randevusunu unutmuş olmalı.']),
    mc('G7', 'Bewegung: sein', I.choose, 'Niemand öffnet die Tür. Der Arzt wird schon nach Hause gefahren …', ['sein', 'haben', 'werden'],
      ['Nobody is opening the door. The doctor will already have gone home.', 'Никто не открывает дверь. Врач, должно быть, уже уехал домой.', 'Ніхто не відчиняє двері. Лікар, мабуть, уже поїхав додому.', 'Kapıyı açan yok. Doktor çoktan eve gitmiş olmalı.'], { h: 'perfekt' }),
    mc('G8', 'Bedeutung: Vermutung', I.choose, 'Was bedeutet „Er wird sich beim Training überanstrengt haben.“?', ['Ich vermute, dass er sich überanstrengt hat.', 'Er wird sich nächste Woche überanstrengen.', 'Er überanstrengt sich gerade.'],
      ['What does “Er wird sich beim Training überanstrengt haben.” mean?', 'Что означает «Er wird sich beim Training überanstrengt haben.»?', 'Що означає «Er wird sich beim Training überanstrengt haben.»?', '“Er wird sich beim Training überanstrengt haben.” ne demek?'], { h: 'zukunft' }),
    mc('G9', 'Vermutung: Gegenwart', I.choose, 'Worauf bezieht sich die Vermutung im Satz „Der Patient wird jetzt wohl im Wartezimmer sitzen.“?', ['auf die Gegenwart', 'auf die Vergangenheit', 'auf das nächste Jahr'],
      ['What does the assumption in the sentence “Der Patient wird jetzt wohl im Wartezimmer sitzen.” refer to?', 'К чему относится предположение в предложении «Der Patient wird jetzt wohl im Wartezimmer sitzen.»?', 'До чого належить припущення в реченні «Der Patient wird jetzt wohl im Wartezimmer sitzen.»?', '“Der Patient wird jetzt wohl im Wartezimmer sitzen.” cümlesindeki tahmin neyle ilgili?']),
    mc('Z1', 'Artikel: Ursache', I.read, `${ARTIKEL} Wodurch sind die meisten Beschwerden nach Ansicht der Fachleute entstanden?`, ['durch Bewegungsmangel', 'durch schwere körperliche Arbeit', 'durch zu viele Kurse'],
      ['In the experts’ opinion, what has caused most of the complaints?', 'Чем, по мнению специалистов, вызвано большинство жалоб?', 'Чим, на думку фахівців, спричинена більшість скарг?', 'Uzmanlara göre şikâyetlerin çoğu neden kaynaklandı?']),
    gap('G4', 'Perfekt mit Infinitiv: lassen', I.form, 'Mein Bruder hat sich endlich gegen Grippe impfen ', '.', 'lassen', ['gelassen', 'ließ'],
      ['My brother has finally had himself vaccinated against flu.', 'Мой брат наконец сделал прививку от гриппа.', 'Мій брат нарешті зробив щеплення від грипу.', 'Kardeşim sonunda grip aşısı oldu.'], 'lassen / gelassen / ließ'),
    sb('G6', 'wirst … erkältet haben', I.order, 'Du / wirst / dich / erkältet / haben.',
      ['You will have caught a cold.', 'Ты, должно быть, простудился.', 'Ти, мабуть, застудився.', 'Üşütmüş olmalısın.']),
  ],
  size: 13,
  test: [
    mc('W1', 'Schlafmangel', I.choose, 'Wer jede Nacht nur vier Stunden schläft, leidet bald unter …', ['Schlafmangel', 'Wohlbefinden', 'Ausdauer'],
      ['Anyone who sleeps only four hours a night will soon suffer from …', 'Тот, кто каждую ночь спит всего четыре часа, вскоре будет страдать от …', 'Той, хто щоночі спить лише чотири години, невдовзі потерпатиме від …', 'Her gece yalnızca dört saat uyuyan kişi çok geçmeden … çeker.']),
    mc('W1', 'sich überanstrengen', I.choose, 'Was bedeutet „sich überanstrengen“?', ['mehr tun, als der Körper verträgt', 'sich lange ausruhen', 'eine Untersuchung machen'],
      ['What does “sich überanstrengen” mean?', 'Что означает «sich überanstrengen»?', 'Що означає «sich überanstrengen»?', '“sich überanstrengen” ne demek?']),
    gap('W1', 'vorbeugen', I.word, 'Regelmäßiges Schwimmen stärkt den Rücken und beugt Schmerzen ', '.', 'vor', ['an', 'nach'],
      ['Regular swimming strengthens the back and prevents pain.', 'Регулярное плавание укрепляет спину и предотвращает боли.', 'Регулярне плавання зміцнює спину й запобігає болям.', 'Düzenli yüzmek sırtı güçlendirir ve ağrıları önler.'], 'vor / an / nach'),
    mc('G1', 'er lässt', I.choose, 'Wegen der Kopfschmerzen … Emre seine Augen beim Optiker prüfen.', ['lässt', 'lasst', 'lassen'],
      ['Because of his headaches Emre is having his eyes checked at the optician’s.', 'Из-за головных болей Emre проверяет зрение у оптика.', 'Через головні болі Emre перевіряє зір в оптика.', 'Emre baş ağrıları yüzünden gözlerini gözlükçüde kontrol ettiriyor.']),
    mc('G1', 'machen lassen', I.sentence, 'Der Zahnarzt reinigt Lukas Zähne. Luka hat dafür einen Termin gemacht.', ['Luka lässt sich die Zähne reinigen.', 'Luka reinigt dem Zahnarzt die Zähne.', 'Luka lässt den Zahnarzt die Zähne.'],
      ['The dentist cleans Luka’s teeth. Luka made an appointment for it.', 'Стоматолог чистит Luka зубы. Luka записался для этого на приём.', 'Стоматолог чистить Luka зуби. Luka записався для цього на прийом.', 'Dişçi Luka’nın dişlerini temizliyor. Luka bunun için randevu aldı.'], { h: 'selbst' }),
    gap('G1', 'er lässt sich', I.reflexive, 'Mein Bruder lässt ', ' zweimal im Jahr von einem Sportarzt beraten.', 'sich', ['ihn', 'ihm'],
      ['My brother gets advice from a sports doctor twice a year.', 'Мой брат дважды в год консультируется у спортивного врача.', 'Мій брат двічі на рік консультується у спортивного лікаря.', 'Kardeşim yılda iki kez bir spor hekimine danışıyor.'], 'er'),
    mc('G2', 'Bedeutung: erlauben', I.choose, 'Was bedeutet „Der Chef lässt uns bei Hitze früher gehen.“?', ['Der Chef erlaubt uns, früher zu gehen.', 'Der Chef geht früher als wir.', 'Der Chef schickt uns zum Arzt.'],
      ['What does “Der Chef lässt uns bei Hitze früher gehen.” mean?', 'Что означает «Der Chef lässt uns bei Hitze früher gehen.»?', 'Що означає «Der Chef lässt uns bei Hitze früher gehen.»?', '“Der Chef lässt uns bei Hitze früher gehen.” ne demek?']),
    mc('G2', 'Imperativ: Lass', I.choose, '… ihn schlafen, er hatte eine anstrengende Nachtschicht!', ['Lass', 'Lässt', 'Ließ'],
      ['Let him sleep, he had an exhausting night shift!', 'Дай ему поспать, у него была тяжёлая ночная смена!', 'Дай йому поспати, у нього була важка нічна зміна!', 'Bırak uyusun, yorucu bir gece vardiyası geçirdi!']),
    gap('G2', 'er lässt', I.verb, 'Der Arzt ', ' die Patienten erst nach einer gründlichen Untersuchung wieder trainieren.', 'lässt', ['lasst', 'lassen'],
      ['The doctor only lets the patients train again after a thorough examination.', 'Врач разрешает пациентам снова тренироваться только после тщательного обследования.', 'Лікар дозволяє пацієнтам знову тренуватися лише після ретельного обстеження.', 'Doktor hastaların yeniden antrenman yapmasına ancak ayrıntılı bir muayeneden sonra izin veriyor.'], 'lassen'),
    mc('G3', 'Bedeutung: unterlassen', I.choose, 'Was bedeutet „Du solltest den Alkohol lassen.“?', ['Du solltest keinen Alkohol mehr trinken.', 'Du solltest Alkohol kaufen.', 'Du solltest jemandem Alkohol erlauben.'],
      ['What does “Du solltest den Alkohol lassen.” mean?', 'Что означает «Du solltest den Alkohol lassen.»?', 'Що означає «Du solltest den Alkohol lassen.»?', '“Du solltest den Alkohol lassen.” ne demek?']),
    mc('G3', 'stehen lassen', I.choose, 'Heute ist es so schön, dass ich das Auto stehen … und zu Fuß gehe.', ['lasse', 'lässt', 'gelassen'],
      ['It is so lovely today that I am leaving the car and going on foot.', 'Сегодня так хорошо, что я оставляю машину и иду пешком.', 'Сьогодні так гарно, що я залишаю машину і йду пішки.', 'Bugün hava o kadar güzel ki arabayı bırakıp yürüyerek gidiyorum.']),
    gap('G3', 'offen lassen', I.imperative, 'Bitte ', ' die Fenster offen, die frische Luft tut gut.', ['lass', 'lasse', 'lasst'], ['lässt', 'ließ'],
      ['Please leave the windows open; the fresh air does you good.', 'Пожалуйста, оставь окна открытыми, свежий воздух полезен.', 'Будь ласка, залиш вікна відчиненими, свіже повітря корисне.', 'Lütfen pencereleri açık bırak, temiz hava iyi geliyor.'], 'lassen'),
    mc('G4', 'Infinitiv ohne zu', I.choose, 'Der Sportler lässt sich nach jedem Wettkampf …', ['massieren', 'zu massieren', 'massiert'],
      ['The athlete has a massage after every competition.', 'Спортсмен после каждого соревнования ходит на массаж.', 'Спортсмен після кожного змагання ходить на масаж.', 'Sporcu her yarışmadan sonra masaj yaptırıyor.'], { h: 'zu' }),
    mc('G4', 'Vollverb: gelassen', I.choose, 'Tarik hat seine Trinkflasche in der Umkleide …', ['gelassen', 'lassen', 'ließ'],
      ['Tarik has left his water bottle in the changing room.', 'Tarik оставил свою бутылку для воды в раздевалке.', 'Tarik залишив свою пляшку для води в роздягальні.', 'Tarik matarasını soyunma odasında bıraktı.']),
    gap('G4', 'Präteritum: ließ', I.verb, 'Nach dem Unfall ', ' er sich sofort ins Krankenhaus bringen.', 'ließ', ['lies', 'ließt'],
      ['After the accident he had himself taken to hospital straight away.', 'После несчастного случая он сразу попросил отвезти его в больницу.', 'Після нещасного випадку він одразу попросив відвезти його до лікарні.', 'Kazadan sonra kendini hemen hastaneye götürttü.'], 'lassen (Präteritum)'),
    mc('G5', 'Bedeutung: nicht verändern', I.choose, 'Welche Bedeutung hat „lassen“ im Satz „Wir lassen das Rezept in der Apotheke.“?', ['nicht verändern: Es bleibt dort.', 'veranlassen: Jemand macht es für uns.', 'erlauben: Jemand darf etwas tun.'],
      ['What does “lassen” mean in the sentence “Wir lassen das Rezept in der Apotheke.”?', 'Какое значение имеет «lassen» в предложении «Wir lassen das Rezept in der Apotheke.»?', 'Яке значення має «lassen» у реченні «Wir lassen das Rezept in der Apotheke.»?', '“Wir lassen das Rezept in der Apotheke.” cümlesinde “lassen” ne anlama geliyor?']),
    mc('G5', 'Umschreibung: veranlassen', I.choose, 'Welche Umschreibung passt zu „Er lässt sich krankschreiben.“?', ['Ein Arzt schreibt ihn krank.', 'Er schreibt selbst eine Krankmeldung.', 'Er erlaubt dem Arzt, krank zu sein.'],
      ['Which paraphrase matches “Er lässt sich krankschreiben.”?', 'Какое перефразирование соответствует «Er lässt sich krankschreiben.»?', 'Яке перефразування відповідає «Er lässt sich krankschreiben.»?', '“Er lässt sich krankschreiben.” cümlesine hangi açıklama uyar?']),
    mc('G5', 'erlauben erkennen', I.choose, 'In welchem Satz bedeutet „lassen“ erlauben?', ['Der Arzt lässt den Jungen wieder zur Schule gehen.', 'Der Junge lässt sein Bein röntgen.', 'Der Junge lässt die Tabletten liegen.'],
      ['In which sentence does “lassen” mean to allow?', 'В каком предложении «lassen» означает разрешать?', 'У якому реченні «lassen» означає дозволяти?', 'Hangi cümlede “lassen” izin vermek anlamına geliyor?']),
    mc('G6', 'Futur II erkennen', I.choose, 'Welcher Satz steht im Futur II?', ['Er wird zu lange in der Sonne gelegen haben.', 'Er wird zu lange in der Sonne liegen.', 'Er hat zu lange in der Sonne gelegen.'],
      ['Which sentence is in the Futur II?', 'Какое предложение стоит в Futur II?', 'Яке речення стоїть у Futur II?', 'Hangi cümle Futur II’dir?']),
    mc('G6', 'du wirst', I.choose, 'Du … dich gestern beim Tragen der Kisten verhoben haben.', ['wirst', 'wird', 'bist'],
      ['You will have strained yourself yesterday carrying the boxes.', 'Ты, должно быть, вчера надорвался, когда носил ящики.', 'Ти, мабуть, учора надірвався, коли носив ящики.', 'Dün kolileri taşırken kendini incitmiş olmalısın.']),
    gap('G6', 'erkältet haben', I.participle, 'Er hustet stark. Er wird sich im Schwimmbad ', ' haben.', 'erkältet', ['erkälten', 'erkältete'],
      ['He is coughing badly. He will have caught a cold at the swimming pool.', 'Он сильно кашляет. Он, должно быть, простудился в бассейне.', 'Він сильно кашляє. Він, мабуть, застудився в басейні.', 'Çok öksürüyor. Yüzme havuzunda üşütmüş olmalı.'], 'sich erkälten'),
    mc('G7', 'Bewegung: sein', I.choose, 'Es ist sehr spät. Die Gäste werden längst nach Hause gegangen …', ['sein', 'haben', 'worden'],
      ['It is very late. The guests will long since have gone home.', 'Уже очень поздно. Гости, должно быть, давно ушли домой.', 'Уже дуже пізно. Гості, мабуть, давно пішли додому.', 'Saat çok geç. Konuklar çoktan evlerine gitmiş olmalı.']),
    mc('G7', 'Verb mit sein', I.choose, 'Bei welchem Verb steht im Futur II „sein“?', ['einschlafen', 'sich ausruhen', 'trainieren'],
      ['Which verb takes “sein” in the Futur II?', 'С каким глаголом в Futur II употребляется «sein»?', 'З яким дієсловом у Futur II уживається «sein»?', 'Futur II’de hangi fiil “sein” ile kullanılır?'], { h: 'perfekt' }),
    gap('G7', 'gelaufen sein', I.auxiliary, 'Mein Knie tut weh. Ich werde gestern zu lange gelaufen ', '.', 'sein', ['haben', 'bin'],
      ['My knee hurts. I will have run for too long yesterday.', 'У меня болит колено. Наверное, я вчера слишком долго бегал.', 'У мене болить коліно. Мабуть, я вчора занадто довго бігав.', 'Dizim ağrıyor. Dün fazla uzun koşmuş olmalıyım.'], AUX, { h: 'perfekt' }),
    mc('G8', 'Bedeutung: Vermutung', I.choose, 'Was bedeutet „Der Arzt wird den Befund wohl schon gelesen haben.“?', ['Ich vermute, dass der Arzt den Befund schon gelesen hat.', 'Der Arzt liest den Befund morgen.', 'Der Arzt hat den Befund sicher nicht gelesen.'],
      ['What does “Der Arzt wird den Befund wohl schon gelesen haben.” mean?', 'Что означает «Der Arzt wird den Befund wohl schon gelesen haben.»?', 'Що означає «Der Arzt wird den Befund wohl schon gelesen haben.»?', '“Der Arzt wird den Befund wohl schon gelesen haben.” ne demek?'], { h: 'zukunft' }),
    mc('G8', 'Vermutung formulieren', I.sentence, 'Wahrscheinlich hat er zu wenig getrunken.', ['Er wird zu wenig getrunken haben.', 'Er wird zu wenig trinken.', 'Er wird zu wenig getrunken sein.'],
      ['He has probably not drunk enough.', 'Вероятно, он слишком мало пил.', 'Імовірно, він замало пив.', 'Büyük olasılıkla çok az su içti.']),
    mc('G9', 'abgeschlossene Zukunft', I.choose, 'Was bedeutet „Bis Montag wird der Arzt das Ergebnis bekommen haben.“?', ['Am Montag liegt das Ergebnis vor.', 'Der Arzt hat das Ergebnis vermutlich letzte Woche bekommen.', 'Der Arzt bekommt nie ein Ergebnis.'],
      ['What does “Bis Montag wird der Arzt das Ergebnis bekommen haben.” mean?', 'Что означает «Bis Montag wird der Arzt das Ergebnis bekommen haben.»?', 'Що означає «Bis Montag wird der Arzt das Ergebnis bekommen haben.»?', '“Bis Montag wird der Arzt das Ergebnis bekommen haben.” ne demek?']),
    mc('G9', 'Vermutung: Vergangenheit', I.choose, 'Worauf bezieht sich die Vermutung im Satz „Er wird wohl zu Hause geblieben sein.“?', ['auf die Vergangenheit', 'auf die Gegenwart', 'auf einen Plan'],
      ['What does the assumption in the sentence “Er wird wohl zu Hause geblieben sein.” refer to?', 'К чему относится предположение в предложении «Er wird wohl zu Hause geblieben sein.»?', 'До чого належить припущення в реченні «Er wird wohl zu Hause geblieben sein.»?', '“Er wird wohl zu Hause geblieben sein.” cümlesindeki tahmin neyle ilgili?']),
    mc('Z1', 'Artikel: Befragung', I.read, `${ARTIKEL} Was hat die Krankenkasse getan?`, ['Sie hat 3000 Versicherte befragen lassen.', 'Sie hat 3000 Versicherte selbst untersucht.', 'Sie hat allen Versicherten Kurse verboten.'],
      ['What did the health insurance company do?', 'Что сделала больничная касса?', 'Що зробила лікарняна каса?', 'Sağlık sigortası ne yaptı?']),
    mc('Z1', 'Artikel: Erlaubnis der Firmen', I.read, `${ARTIKEL} Was erlauben einige Firmen ihren Mitarbeitern?`, ['während der Arbeitszeit an Kursen teilzunehmen', 'mehr als acht Stunden zu sitzen', 'den Aufzug zu benutzen'],
      ['What do some companies allow their employees to do?', 'Что некоторые фирмы разрешают своим сотрудникам?', 'Що деякі фірми дозволяють своїм працівникам?', 'Bazı şirketler çalışanlarına neye izin veriyor?']),
  ],
}

export default check
