import { I, gap, mc, sb } from '../shared.mjs'

/** A1.2 · Pfad 1 · Beruf und Arbeit – Lektionen. Wiederholung und Test: p1-check.mjs */
const path = {
  n: 1,
  slug: 'beruf-und-arbeit',
  title: 'Beruf und Arbeit',
  t: ['Jobs and work', 'Профессия и работа', 'Професія і робота', 'Meslek ve iş'],
  objectives: {
    G1: 'Berufsbezeichnungen: weibliche Form mit -in (Arzt – Ärztin), Plural auf -innen, Sonderformen wie Hausmann – Hausfrau.',
    G2: '„als“ + Beruf und „bei“ + Firma: Ich arbeite als Köchin bei einer Firma.',
    G3: 'Zeitangaben mit „vor“ und „seit“ + Dativ: Wann? Vor einem Jahr. Seit wann? Seit zwei Monaten.',
    G4: 'Zeitdauer mit „für“ + Akkusativ: Für wie lange? Für einen Monat, für ein Jahr, für eine Woche.',
    G5: 'Präteritum von sein und haben: war, warst, waren, wart; hatte, hattest, hatten, hattet.',
    K1: 'Über den Beruf sprechen: nach dem Beruf fragen, Beruf, Ausbildung, Studium und Arbeitssituation nennen.',
    K2: 'Über das eigene Leben sprechen: Geburtsjahr und Geburtsort, frühere Wohnorte, Ankunft in Deutschland, Deutschlernen.',
    K3: 'Über Berufserfahrungen sprechen: frühere Berufe nennen, Arbeit, Chef und Kollegen bewerten.',
    K4: 'Am Telefon nach einer Stelle fragen: Anzeige, freie Stelle, Arbeitszeit, Verdienst und Termin.',
    Z1: 'Kann-Ziele: Stellenanzeigen und kurze Texte zum Thema Beruf verstehen, ein Stellengesuch formulieren.',
    W1: 'Wortschatz: Berufe und Wörter rund um Arbeit und Beruf.',
  },
  nodes: [
    {
      title: 'Berufe: er und sie',
      t: ['Jobs: he and she', 'Профессии: он и она', 'Професії: він і вона', 'Meslekler: erkek ve kadın'],
      card: {
        id: 'p1_in',
        rule: 'Berufe: Für Frauen kommt meistens -in ans Wort: der Lehrer – die Lehrerin. Oft wird a, o, u zu ä, ö, ü: der Arzt – die Ärztin, der Koch – die Köchin. Plural: die Lehrerinnen. Achtung: der Hausmann – die Hausfrau, der Krankenpfleger – die Krankenschwester.',
        examples: ['Emre ist Verkäufer. Dilara ist Verkäuferin.', 'Der Arzt und die Ärztin arbeiten im Krankenhaus.', 'Die zwei Köchinnen kochen sehr gut.'],
        highlight: null,
        t: [
          'Jobs: for women you usually add -in: der Lehrer – die Lehrerin. Often a, o, u become ä, ö, ü: der Arzt – die Ärztin, der Koch – die Köchin. Plural: die Lehrerinnen. Watch out: der Hausmann – die Hausfrau, der Krankenpfleger – die Krankenschwester.',
          'Профессии: для женщин обычно добавляется -in: der Lehrer – die Lehrerin. Часто a, o, u меняются на ä, ö, ü: der Arzt – die Ärztin, der Koch – die Köchin. Множественное число: die Lehrerinnen. Внимание: der Hausmann – die Hausfrau, der Krankenpfleger – die Krankenschwester.',
          'Професії: для жінок зазвичай додається -in: der Lehrer – die Lehrerin. Часто a, o, u змінюються на ä, ö, ü: der Arzt – die Ärztin, der Koch – die Köchin. Множина: die Lehrerinnen. Увага: der Hausmann – die Hausfrau, der Krankenpfleger – die Krankenschwester.',
          'Meslekler: Kadınlar için genellikle kelimeye -in eklenir: der Lehrer – die Lehrerin. Çoğu zaman a, o, u harfleri ä, ö, ü olur: der Arzt – die Ärztin, der Koch – die Köchin. Çoğul: die Lehrerinnen. Dikkat: der Hausmann – die Hausfrau, der Krankenpfleger – die Krankenschwester.',
        ],
        hint: ['Eine Frau? Dann meistens Beruf + -in. Achte auf den Umlaut: Arzt – Ärztin.', 'A woman? Then usually job + -in. Mind the umlaut: Arzt – Ärztin.', 'Женщина? Тогда обычно профессия + -in. Не забудьте умлаут: Arzt – Ärztin.', 'Жінка? Тоді зазвичай професія + -in. Не забудьте умлаут: Arzt – Ärztin.', 'Kadın mı? O zaman genellikle meslek + -in. Umlaut’a dikkat: Arzt – Ärztin.'],
        hints: {
          word: ['Denk an den Arbeitsort: Wer arbeitet dort?', 'Think of the workplace: who works there?', 'Подумайте о месте работы: кто там работает?', 'Подумайте про місце роботи: хто там працює?', 'Çalışma yerini düşünün: orada kim çalışır?'],
        },
      },
      ex: [
        mc('W1', 'Berufe', I.choose, 'Wer arbeitet in einer Küche und macht das Essen?', ['der Koch', 'der Friseur', 'der Busfahrer'],
          ['Who works in a kitchen and makes the food?', 'Кто работает на кухне и готовит еду?', 'Хто працює на кухні й готує їжу?', 'Kim mutfakta çalışır ve yemek yapar?'], { h: 'word' }),
        mc('W1', 'Berufe', I.choose, 'Wer repariert Autos in einer Werkstatt?', ['die Mechatronikerin', 'die Bäckerin', 'die Lehrerin'],
          ['Who repairs cars in a garage?', 'Кто ремонтирует машины в автомастерской?', 'Хто ремонтує автомобілі в майстерні?', 'Kim bir tamirhanede araba tamir eder?'], { h: 'word' }),
        mc('G1', 'weibliche Form', I.choose, 'Herr Demir ist Arzt. Seine Frau hat den gleichen Beruf. Sie ist …', ['Ärztin', 'Arztin', 'Ärzterin'],
          ['Mr Demir is a doctor. His wife has the same job. She is a …', 'Господин Demir – врач. У его жены та же профессия. Она …', 'Пан Demir – лікар. Його дружина має ту саму професію. Вона …', 'Demir Bey doktor. Eşinin de mesleği aynı. O da …']),
        mc('G1', 'Plural -innen', I.choose, 'Im Kindergarten arbeiten vier Frauen. Sie sind …', ['Erzieherinnen', 'Erzieherin', 'Erzieherinen'],
          ['Four women work at the kindergarten. They are …', 'В детском саду работают четыре женщины. Они …', 'У дитячому садку працюють чотири жінки. Вони …', 'Anaokulunda dört kadın çalışıyor. Onlar …']),
        gap('G1', 'weibliche Form', I.feminine, 'Jonas ist Verkäufer. Seine Schwester Lea ist auch ', '.', 'Verkäuferin', ['Verkäufer', 'Verkäuferinnen'],
          ['Jonas is a salesman. His sister Lea is a saleswoman too.', 'Jonas – продавец. Его сестра Lea тоже продавец.', 'Jonas – продавець. Його сестра Lea теж продавчиня.', 'Jonas satış elemanı. Kız kardeşi Lea da satış elemanı.'], 'Verkäufer'),
        gap('G1', 'weibliche Form', I.feminine, 'Mein Onkel ist Koch und meine Tante ist ', '.', 'Köchin', ['Kochin', 'Köcherin'],
          ['My uncle is a cook and my aunt is a cook.', 'Мой дядя – повар, и моя тётя – повар.', 'Мій дядько – кухар, а моя тітка – кухарка.', 'Amcam aşçı, teyzem de aşçı.'], 'Koch'),
        gap('G1', 'Sonderform', I.feminine, 'Tom ist Hausmann. Seine Nachbarin Eva ist ', '.', 'Hausfrau', ['Hausmännin', 'Hausmannin'],
          ['Tom is a house husband. His neighbour Eva is a housewife.', 'Tom – домохозяин. Его соседка Eva – домохозяйка.', 'Tom – домогосподар. Його сусідка Eva – домогосподарка.', 'Tom ev erkeği. Komşusu Eva ev hanımı.'], 'Hausmann'),
        gap('W1', 'Berufe', I.word, 'Frau Aksoy schneidet Haare. Sie ist ', ' von Beruf.', ['Friseurin', 'Frisörin'], ['Bäckerin', 'Polizistin'],
          ['Ms Aksoy cuts hair. She is a hairdresser by profession.', 'Госпожа Aksoy стрижёт волосы. По профессии она парикмахер.', 'Пані Aksoy стриже волосся. За професією вона перукарка.', 'Aksoy Hanım saç kesiyor. Mesleği kuaförlük.'],
          ['hairdresser', 'парикмахер', 'перукарка', 'kuaför'], { h: 'word' }),
      ],
    },
    {
      title: 'Was sind Sie von Beruf?',
      t: ['What is your job?', 'Кто вы по профессии?', 'Хто ви за професією?', 'Mesleğiniz ne?'],
      card: {
        id: 'p1_jobtalk',
        rule: 'Nach dem Beruf fragen: Was sind Sie von Beruf? Was machst du beruflich? Antworten: Ich bin Köchin. (ohne ein/eine!) Ich mache eine Ausbildung als Friseur. Ich studiere noch. Ich gehe noch zur Schule. Ich bin angestellt oder selbstständig. Ich arbeite zurzeit nicht. Ich bin arbeitslos.',
        examples: ['Was sind Sie von Beruf? – Ich bin Busfahrer.', 'Was machst du beruflich? – Ich mache eine Ausbildung als Köchin.', 'Ich habe eine Stelle als Verkäufer.'],
        highlight: null,
        t: [
          'Asking about someone’s job: Was sind Sie von Beruf? Was machst du beruflich? Answers: Ich bin Köchin. (no ein/eine!) Ich mache eine Ausbildung als Friseur. Ich studiere noch. Ich gehe noch zur Schule. Ich bin angestellt (employed) or selbstständig (self-employed). Ich arbeite zurzeit nicht. Ich bin arbeitslos (unemployed).',
          'Вопрос о профессии: Was sind Sie von Beruf? Was machst du beruflich? Ответы: Ich bin Köchin. (без ein/eine!) Ich mache eine Ausbildung als Friseur. Ich studiere noch. Ich gehe noch zur Schule. Ich bin angestellt (работаю по найму) или selbstständig (работаю на себя). Ich arbeite zurzeit nicht. Ich bin arbeitslos (без работы).',
          'Запитання про професію: Was sind Sie von Beruf? Was machst du beruflich? Відповіді: Ich bin Köchin. (без ein/eine!) Ich mache eine Ausbildung als Friseur. Ich studiere noch. Ich gehe noch zur Schule. Ich bin angestellt (працюю за наймом) або selbstständig (працюю на себе). Ich arbeite zurzeit nicht. Ich bin arbeitslos (без роботи).',
          'Meslek sorma: Was sind Sie von Beruf? Was machst du beruflich? Cevaplar: Ich bin Köchin. (ein/eine yok!) Ich mache eine Ausbildung als Friseur. Ich studiere noch. Ich gehe noch zur Schule. Ich bin angestellt (ücretli çalışan) ya da selbstständig (serbest çalışan). Ich arbeite zurzeit nicht. Ich bin arbeitslos (işsiz).',
        ],
        hint: ['Beim Beruf steht kein Artikel: Ich bin Lehrer.', 'No article before a job: Ich bin Lehrer (not: ein Lehrer).', 'Перед профессией нет артикля: Ich bin Lehrer.', 'Перед професією немає артикля: Ich bin Lehrer.', 'Meslekten önce artikel yoktur: Ich bin Lehrer.'],
        hints: {
          status: ['Lies die Situation genau: Arbeit, Ausbildung, Studium oder keine Arbeit?', 'Read the situation carefully: job, training, university or no work?', 'Внимательно прочитайте ситуацию: работа, обучение, учёба в вузе или нет работы?', 'Уважно прочитайте ситуацію: робота, навчання професії, університет чи немає роботи?', 'Durumu dikkatle okuyun: iş, meslek eğitimi, üniversite ya da işsizlik?'],
          ask: ['du oder Sie? Die Frage muss zur Person passen.', 'du or Sie? The question has to fit the person.', 'du или Sie? Вопрос должен подходить к собеседнику.', 'du чи Sie? Запитання має підходити до співрозмовника.', 'du mu Sie mi? Soru kişiye uygun olmalı.'],
        },
      },
      ex: [
        mc('K1', 'nach dem Beruf fragen', I.situation, 'Im Kurs lernst du Mila kennen. Ihr sagt „du“. Du möchtest ihren Beruf wissen.', ['Was machst du beruflich?', 'Was sind Sie von Beruf?', 'Wie alt bist du?'],
          ['In class you meet Mila. You say “du” to each other. You want to know her job.', 'На курсе вы знакомитесь с Mila. Вы с ней на «ты». Вы хотите узнать её профессию.', 'На курсі ви знайомитеся з Mila. Ви з нею на «ти». Ви хочете дізнатися її професію.', 'Kursta Mila ile tanışıyorsunuz. Birbirinize “du” diyorsunuz. Mesleğini öğrenmek istiyorsunuz.'], { h: 'ask' }),
        mc('K1', 'Beruf nennen', I.sentence, 'Mateo sagt seinen Beruf.', ['Ich bin Krankenpfleger.', 'Ich bin einen Krankenpfleger.', 'Ich habe Krankenpfleger.'],
          ['Mateo says what his job is.', 'Mateo называет свою профессию.', 'Mateo називає свою професію.', 'Mateo mesleğini söylüyor.']),
        mc('K1', 'Arbeitssituation', I.choose, 'Lina hat ein Café. Sie ist die Chefin und hat keinen Chef. Lina ist …', ['selbstständig', 'angestellt', 'arbeitslos'],
          ['Lina has a café. She is the boss and has no boss herself. Lina is …', 'У Lina своё кафе. Она начальница, и над ней нет начальника. Lina …', 'Lina має власне кафе. Вона керівниця й не має начальника. Lina …', 'Lina’nın bir kafesi var. Patron kendisi, onun patronu yok. Lina …'], { h: 'status' }),
        mc('K1', 'Beruf nennen', I.react, '„Was sind Sie von Beruf?“', ['Ich bin Elektriker.', 'Ich komme aus Ghana.', 'Ich bin 34 Jahre alt.'],
          ['“What is your job?”', '«Кто вы по профессии?»', '«Хто ви за професією?»', '“Mesleğiniz ne?”']),
        gap('K1', 'Ausbildung', I.word, 'Samira ist 17. Sie macht eine ', ' als Bäckerin.', 'Ausbildung', ['Arbeit', 'Schule'],
          ['Samira is 17. She is doing an apprenticeship as a baker.', 'Samira 17 лет. Она получает профессию пекаря.', 'Samira 17 років. Вона здобуває професію пекарки.', 'Samira 17 yaşında. Fırıncılık meslek eğitimi alıyor.'],
          ['apprenticeship, training', 'профессиональное обучение', 'професійне навчання', 'meslek eğitimi'], { h: 'status' }),
        gap('K1', 'arbeitslos', I.word, 'Herr Petrov hat zurzeit keine Stelle. Er ist ', '.', 'arbeitslos', ['angestellt', 'selbstständig'],
          ['Mr Petrov has no job at the moment. He is unemployed.', 'У господина Petrov сейчас нет работы. Он безработный.', 'Пан Petrov зараз не має роботи. Він безробітний.', 'Petrov Bey’in şu anda işi yok. O işsiz.'],
          ['unemployed', 'безработный', 'безробітний', 'işsiz'], { h: 'status' }),
        gap('K1', 'von Beruf', I.expression, 'Was sind Sie von ', '?', 'Beruf', ['Arbeit', 'Job'],
          ['What is your profession?', 'Кто вы по профессии?', 'Хто ви за професією?', 'Mesleğiniz ne?'],
          ['profession', 'профессия', 'професія', 'meslek'], { h: 'ask' }),
        sb('K1', 'nach dem Beruf fragen', I.question, 'Was / machen / Sie / beruflich?',
          ['What do you do for a living?', 'Кем вы работаете?', 'Ким ви працюєте?', 'Ne iş yapıyorsunuz?'], { h: 'ask' }),
      ],
    },
    {
      title: 'als und bei',
      t: ['als and bei', 'als и bei', 'als і bei', 'als ve bei'],
      card: {
  "id": "p1_alsbei",
  "rule": "als + Beruf, bei + Firma: Ich arbeite als Verkäufer. Ich arbeite bei der Bäckerei Sonnenkorn. Zusammen: Ich arbeite als Verkäufer bei Sonnenkorn. Nach als steht kein Artikel.",
  "examples": [
    "Amir arbeitet als Koch.",
    "Mateo arbeitet bei Elektro Brandt.",
    "Ich arbeite als Fahrer bei einer Spedition."
  ],
  "highlight": null,
  "t": [
    "als + job, bei + company: Ich arbeite als Verkäufer (as a salesman). Ich arbeite bei der Bäckerei Sonnenkorn (at/for the bakery). Together: Ich arbeite als Verkäufer bei Sonnenkorn. There is no article after als.",
    "als + профессия, bei + фирма: Ich arbeite als Verkäufer (продавцом). Ich arbeite bei der Bäckerei Sonnenkorn (в пекарне). Вместе: Ich arbeite als Verkäufer bei Sonnenkorn. После als артикль не ставится.",
    "als + професія, bei + фірма: Ich arbeite als Verkäufer (продавцем). Ich arbeite bei der Bäckerei Sonnenkorn (у пекарні). Разом: Ich arbeite als Verkäufer bei Sonnenkorn. Після als артикль не ставиться.",
    "als + meslek, bei + firma: Ich arbeite als Verkäufer (satış elemanı olarak). Ich arbeite bei der Bäckerei Sonnenkorn (fırında). Birlikte: Ich arbeite als Verkäufer bei Sonnenkorn. als’tan sonra artikel gelmez."
  ],
  "hint": [
    "Beruf → als. Firma → bei.",
    "Job → als. Company → bei.",
    "Профессия → als. Фирма → bei.",
    "Професія → als. Фірма → bei.",
    "Meslek → als. Firma → bei."
  ]
},
      ex: [
        mc('G2', 'als und bei', I.choose, 'Pawel ist Fahrer. Seine Firma heißt Nordweg. Was sagt er?', ['Ich arbeite als Fahrer bei Nordweg.', 'Ich arbeite bei Fahrer als Nordweg.', 'Ich arbeite als Nordweg bei Fahrer.'],
          ['Pawel is a driver. His company is called Nordweg. What does he say?', 'Pawel – водитель. Его фирма называется Nordweg. Что он говорит?', 'Pawel – водій. Його фірма називається Nordweg. Що він каже?', 'Pawel şoför. Firmasının adı Nordweg. Ne diyor?']),
        mc('G2', 'bei + Firma', I.react, '„Wo arbeiten Sie?“', ['Bei der Reinigung Blitzblank.', 'Als Reinigung Blitzblank.', 'Seit der Reinigung Blitzblank.'],
          ['“Where do you work?”', '«Где вы работаете?»', '«Де ви працюєте?»', '“Nerede çalışıyorsunuz?”']),
        gap("G2", "als + Beruf", I.prep, "Amir arbeitet ", " Kellner.", "als", ["bei","von"], ["Amir works as a waiter.","Amir работает официантом.","Amir працює офіціантом.","Amir garson olarak çalışıyor."], "als / bei", {"c":"p1_alsbei"}),
        gap('G2', 'bei + Firma', I.prep, 'Mein Bruder arbeitet ', ' Elektro Brandt.', 'bei', ['als', 'aus'],
          ['My brother works at Elektro Brandt.', 'Мой брат работает в фирме Elektro Brandt.', 'Мій брат працює у фірмі Elektro Brandt.', 'Erkek kardeşim Elektro Brandt’ta çalışıyor.'], 'als / bei'),
        gap("G2", "als + Beruf", I.prep, "Hannes hat eine Stelle ", " Erzieher.", "als", ["bei","in"], ["Hannes has a job as a nursery teacher.","У Hannes есть место воспитателя.","Hannes має посаду вихователя.","Hannes’in anaokulu öğretmeni olarak bir işi var."], "als / bei", {"c":"p1_alsbei"}),
        gap('G2', 'bei + Firma', I.prep, 'Ich arbeite als Mechaniker ', ' einer Firma in Köln.', 'bei', ['als', 'aus'],
          ['I work as a mechanic for a company in Cologne.', 'Я работаю механиком в одной фирме в Кёльне.', 'Я працюю механіком в одній фірмі в Кельні.', 'Köln’de bir firmada tamirci olarak çalışıyorum.'], 'als / bei'),
        sb('G2', 'als und bei', I.order, 'Ich / arbeite / als Verkäufer / bei Sonnenkorn.',
          ['I work as a salesman at Sonnenkorn.', 'Я работаю продавцом в Sonnenkorn.', 'Я працюю продавцем у Sonnenkorn.', 'Sonnenkorn’da satış elemanı olarak çalışıyorum.'],
          { alt: ['Ich arbeite bei Sonnenkorn als Verkäufer.', 'Als Verkäufer arbeite ich bei Sonnenkorn.', 'Bei Sonnenkorn arbeite ich als Verkäufer.'] }),
      ],
    },
    {
      title: 'war und hatte',
      t: ['war and hatte', 'war и hatte', 'war і hatte', 'war ve hatte'],
      card: {
        id: 'p1_prat',
        rule: 'Präteritum von sein und haben: So sprichst du über früher. sein: ich war, du warst, er/es/sie war, wir waren, ihr wart, sie/Sie waren. haben: ich hatte, du hattest, er/es/sie hatte, wir hatten, ihr hattet, sie/Sie hatten.',
        examples: ['Früher war ich Kellner. Heute bin ich Koch.', 'Wir hatten gestern viel Arbeit.', 'Wo warst du am Montag?'],
        highlight: 'verb',
        t: [
          'Past tense (Präteritum) of sein and haben: this is how you talk about the past. sein: ich war, du warst, er/es/sie war, wir waren, ihr wart, sie/Sie waren. haben: ich hatte, du hattest, er/es/sie hatte, wir hatten, ihr hattet, sie/Sie hatten.',
          'Прошедшее время (Präteritum) глаголов sein и haben: так говорят о прошлом. sein: ich war, du warst, er/es/sie war, wir waren, ihr wart, sie/Sie waren. haben: ich hatte, du hattest, er/es/sie hatte, wir hatten, ihr hattet, sie/Sie hatten.',
          'Минулий час (Präteritum) дієслів sein і haben: так говорять про минуле. sein: ich war, du warst, er/es/sie war, wir waren, ihr wart, sie/Sie waren. haben: ich hatte, du hattest, er/es/sie hatte, wir hatten, ihr hattet, sie/Sie hatten.',
          'sein ve haben fiillerinin geçmiş zamanı (Präteritum): Geçmişten böyle söz edilir. sein: ich war, du warst, er/es/sie war, wir waren, ihr wart, sie/Sie waren. haben: ich hatte, du hattest, er/es/sie hatte, wir hatten, ihr hattet, sie/Sie hatten.',
        ],
        hint: ['ich und er/sie haben die gleiche Form: war, hatte. Kein -t am Ende!', 'ich and er/sie share one form: war, hatte. No -t at the end!', 'У ich и er/sie одна форма: war, hatte. Без -t на конце!', 'У ich та er/sie одна форма: war, hatte. Без -t у кінці!', 'ich ve er/sie için biçim aynıdır: war, hatte. Sonda -t yok!'],
        hints: {
          choice: ['sein oder haben? Ich bin müde → ich war müde. Ich habe Zeit → ich hatte Zeit.', 'sein or haben? Ich bin müde → ich war müde. Ich habe Zeit → ich hatte Zeit.', 'sein или haben? Ich bin müde → ich war müde. Ich habe Zeit → ich hatte Zeit.', 'sein чи haben? Ich bin müde → ich war müde. Ich habe Zeit → ich hatte Zeit.', 'sein mi haben mı? Ich bin müde → ich war müde. Ich habe Zeit → ich hatte Zeit.'],
        },
      },
      ex: [
        mc('G5', 'sein', I.choose, 'Heute bin ich Köchin. Früher … ich Kellnerin.', ['war', 'hatte', 'bin'],
          ['Today I am a cook. I used to be a waitress.', 'Сегодня я повар. Раньше я была официанткой.', 'Сьогодні я кухарка. Раніше я була офіціанткою.', 'Bugün aşçıyım. Eskiden garsondum.'], { h: 'choice' }),
        mc('G5', 'haben', I.choose, 'Gestern … wir im Büro sehr viel Arbeit.', ['hatten', 'waren', 'haben'],
          ['Yesterday we had a lot of work at the office.', 'Вчера у нас в офисе было очень много работы.', 'Учора в нас в офісі було дуже багато роботи.', 'Dün ofiste çok işimiz vardı.'], { h: 'choice' }),
        gap('G5', 'sein', I.preterite, 'Wo ', ' du gestern Abend?', 'warst', ['war', 'wart'],
          ['Where were you last night?', 'Где ты был вчера вечером?', 'Де ти був учора ввечері?', 'Dün akşam neredeydin?'], 'sein'),
        gap('G5', 'haben', I.preterite, 'Meine Kollegin ', ' letzte Woche Urlaub.', 'hatte', ['hatten', 'war'],
          ['My colleague was on holiday last week.', 'У моей коллеги на прошлой неделе был отпуск.', 'У моєї колеги минулого тижня була відпустка.', 'İş arkadaşım geçen hafta izinliydi.'], 'haben'),
        gap('G5', 'sein', I.preterite, 'Ihr ', ' gestern nicht im Kurs. Was war los?', 'wart', ['waren', 'wartet'],
          ['You weren’t in class yesterday. What was wrong?', 'Вас вчера не было на курсе. Что случилось?', 'Вас учора не було на курсі. Що сталося?', 'Dün kursta yoktunuz. Ne oldu?'], 'sein'),
        gap('G5', 'haben', I.preterite, 'Herr Albers, ', ' Sie früher ein Auto?', 'hatten', ['hattet', 'hatte'],
          ['Mr Albers, did you use to have a car?', 'Господин Albers, у вас раньше была машина?', 'Пане Albers, у вас раніше була машина?', 'Albers Bey, eskiden arabanız var mıydı?'], 'haben'),
        gap('G5', 'haben', I.preterite, 'Am Montag ', ' ich keine Zeit.', 'hatte', ['hattet', 'war'],
          ['On Monday I had no time.', 'В понедельник у меня не было времени.', 'У понеділок у мене не було часу.', 'Pazartesi günü vaktim yoktu.'], 'haben'),
        gap('G5', 'sein', I.preterite, 'Die Kinder ', ' gestern sehr müde.', 'waren', ['war', 'wart'],
          ['The children were very tired yesterday.', 'Дети вчера были очень уставшими.', 'Діти вчора були дуже втомлені.', 'Çocuklar dün çok yorgundu.'], 'sein'),
        sb('G5', 'haben', I.question, 'Hattest / du / gestern / viel Arbeit?',
          ['Did you have a lot of work yesterday?', 'У тебя вчера было много работы?', 'У тебе вчора було багато роботи?', 'Dün çok işin var mıydı?']),
      ],
    },
    {
      title: 'Früher und heute',
      t: ['Then and now', 'Раньше и сегодня', 'Раніше і сьогодні', 'Eskiden ve bugün'],
      card: {
  "id": "p1_exp",
  "rule": "Über Berufserfahrungen sprechen: Ich war drei Jahre Verkäufer. Ich hatte viel Arbeit, aber auch viel Spaß. Der Job war nicht einfach. Der Chef war sehr nett. Die Kollegen waren freundlich. Noch keine Erfahrung? Ich habe noch keine Berufserfahrung.",
  "examples": [
    "Früher war ich Taxifahrer in Izmir.",
    "Die Arbeit war interessant und die Kollegen waren nett.",
    "Ich hatte wenig Arbeit und keinen Spaß."
  ],
  "highlight": null,
  "t": [
    "Talking about work experience: Ich war drei Jahre Verkäufer. Ich hatte viel Arbeit, aber auch viel Spaß (a lot of fun). Der Job war nicht einfach. Der Chef war sehr nett. Die Kollegen waren freundlich. No experience yet? Ich habe noch keine Berufserfahrung.",
    "Как говорить об опыте работы: Ich war drei Jahre Verkäufer. Ich hatte viel Arbeit, aber auch viel Spaß (много удовольствия). Der Job war nicht einfach. Der Chef war sehr nett. Die Kollegen waren freundlich. Ещё нет опыта? Ich habe noch keine Berufserfahrung.",
    "Як говорити про досвід роботи: Ich war drei Jahre Verkäufer. Ich hatte viel Arbeit, aber auch viel Spaß (багато задоволення). Der Job war nicht einfach. Der Chef war sehr nett. Die Kollegen waren freundlich. Ще немає досвіду? Ich habe noch keine Berufserfahrung.",
    "İş deneyiminden söz etme: Ich war drei Jahre Verkäufer. Ich hatte viel Arbeit, aber auch viel Spaß (çok keyif). Der Job war nicht einfach. Der Chef war sehr nett. Die Kollegen waren freundlich. Henüz deneyim yok mu? Ich habe noch keine Berufserfahrung."
  ],
  "hint": [
    "Früher = Präteritum: war, hatte. Heute = Präsens: bin, habe.",
    "Then = past: war, hatte. Now = present: bin, habe.",
    "Раньше = прошедшее время: war, hatte. Сегодня = настоящее: bin, habe.",
    "Раніше = минулий час: war, hatte. Сьогодні = теперішній: bin, habe.",
    "Eskiden = geçmiş zaman: war, hatte. Bugün = şimdiki zaman: bin, habe."
  ]
},
      ex: [
        mc('K3', 'Arbeit bewerten', I.react, '„Wie war dein Job im Hotel?“', ['Er war gut, die Kollegen waren sehr nett.', 'Ich bin im Hotel.', 'Das Hotel ist groß.'],
          ['“How was your job at the hotel?”', '«Как тебе работалось в отеле?»', '«Як тобі працювалося в готелі?»', '“Oteldeki işin nasıldı?”']),
        mc("K3", "Berufserfahrung", I.choose, "Leon sucht seine erste Stelle. Was sagt er?", ["Ich habe noch keine Berufserfahrung.","Ich hatte viele Jahre Arbeit.","Ich war zehn Jahre Chef."], ["Leon is looking for his first job. What does he say?","Leon ищет свою первую работу. Что он говорит?","Leon шукає свою першу роботу. Що він каже?","Leon ilk işini arıyor. Ne diyor?"], {"c":"p1_exp"}),
        mc('K3', 'frühere Berufe', I.read, 'Tarek schreibt: „In Syrien war ich Lehrer. Die Arbeit war schön, aber ich hatte sehr viele Schüler. Jetzt arbeite ich als Busfahrer.“ Was war Tarek früher von Beruf?', ['Lehrer', 'Busfahrer', 'Schüler'],
          ['What was Tarek’s job before?', 'Кем Tarek работал раньше?', 'Ким Tarek працював раніше?', 'Tarek eskiden ne iş yapıyordu?']),
        gap('K3', 'Arbeit bewerten', I.word, 'Die Arbeit im Café war toll. Ich hatte viel ', '.', 'Spaß', ['Chef', 'Beruf'],
          ['The work at the café was great. I had a lot of fun.', 'Работа в кафе была отличная. Мне было очень весело.', 'Робота в кафе була чудова. Мені було дуже весело.', 'Kafedeki iş harikaydı. Çok eğlendim.'],
          ['fun', 'удовольствие, веселье', 'задоволення, веселощі', 'eğlence, keyif']),
        gap('G5', 'sein', I.preterite, 'Mein Chef ', ' immer freundlich.', 'war', ['hatte', 'waren'],
          ['My boss was always friendly.', 'Мой начальник всегда был приветлив.', 'Мій начальник завжди був привітний.', 'Patronum her zaman güler yüzlüydü.'], 'sein'),
        gap('K3', 'früher und heute', I.word, 'Früher war ich Verkäufer. ', ' bin ich Koch.', 'Heute', ['Gestern', 'Früher'],
          ['I used to be a salesman. Today I am a cook.', 'Раньше я был продавцом. Сегодня я повар.', 'Раніше я був продавцем. Сьогодні я кухар.', 'Eskiden satış elemanıydım. Bugün aşçıyım.'],
          ['today', 'сегодня', 'сьогодні', 'bugün']),
        sb('K3', 'Kollegen bewerten', I.order, 'Die Kollegen / waren / sehr / nett.',
          ['The colleagues were very nice.', 'Коллеги были очень милыми.', 'Колеги були дуже милі.', 'İş arkadaşları çok iyiydi.']),
      ],
    },
    {
      title: 'vor und seit',
      t: ['vor and seit', 'vor и seit', 'vor і seit', 'vor ve seit'],
      card: {
        id: 'p1_vorseit',
        rule: 'vor und seit + Dativ. vor = ein Zeitpunkt in der Vergangenheit (Wann?): Ich bin vor einem Jahr nach Deutschland gekommen. seit = von damals bis jetzt (Seit wann? Wie lange?): Ich lerne seit einem Jahr Deutsch. Dativ: einem Monat, einem Jahr, einer Woche, zwei Monaten, zwei Jahren.',
        examples: ['Vor einer Woche hatte ich Urlaub.', 'Seit einem Monat arbeite ich bei Nordweg.', 'Wir wohnen seit drei Jahren in Kassel.'],
        highlight: null,
        t: [
          'vor and seit + dative. vor = a point in the past (When? “… ago”): Ich bin vor einem Jahr nach Deutschland gekommen. seit = from then until now (Since when? How long? “for/since”): Ich lerne seit einem Jahr Deutsch. Dative: einem Monat, einem Jahr, einer Woche, zwei Monaten, zwei Jahren.',
          'vor и seit + Dativ. vor = момент в прошлом (Когда? «… назад»): Ich bin vor einem Jahr nach Deutschland gekommen. seit = с того времени до сих пор (С каких пор? Как долго? «уже …»): Ich lerne seit einem Jahr Deutsch. Dativ: einem Monat, einem Jahr, einer Woche, zwei Monaten, zwei Jahren.',
          'vor і seit + Dativ. vor = момент у минулому (Коли? «… тому»): Ich bin vor einem Jahr nach Deutschland gekommen. seit = відтоді й дотепер (Відколи? Як довго? «вже …»): Ich lerne seit einem Jahr Deutsch. Dativ: einem Monat, einem Jahr, einer Woche, zwei Monaten, zwei Jahren.',
          'vor ve seit + Dativ. vor = geçmişte bir an (Ne zaman? “… önce”): Ich bin vor einem Jahr nach Deutschland gekommen. seit = o zamandan şimdiye kadar (Ne zamandan beri? “…dır/-dir”): Ich lerne seit einem Jahr Deutsch. Dativ: einem Monat, einem Jahr, einer Woche, zwei Monaten, zwei Jahren.',
        ],
        hint: ['Schon vorbei? → vor. Noch immer so? → seit.', 'Already over? → vor. Still going on? → seit.', 'Уже закончилось? → vor. Продолжается до сих пор? → seit.', 'Уже закінчилося? → vor. Триває й досі? → seit.', 'Bitti mi? → vor. Hâlâ sürüyor mu? → seit.'],
        hints: {
          dative: ['Nach vor und seit steht der Dativ: einem (der/das), einer (die), Plural + -n.', 'vor and seit take the dative: einem (der/das), einer (die), plural + -n.', 'После vor и seit стоит Dativ: einem (der/das), einer (die), множественное число + -n.', 'Після vor і seit стоїть Dativ: einem (der/das), einer (die), множина + -n.', 'vor ve seit’ten sonra Dativ gelir: einem (der/das), einer (die), çoğul + -n.'],
        },
      },
      ex: [
        mc('G3', 'seit', I.choose, 'Olga ist 2022 nach Berlin gekommen. Sie wohnt noch immer dort. Olga wohnt … 2022 in Berlin.', ['seit', 'vor', 'für'],
          ['Olga came to Berlin in 2022. She still lives there. Olga has lived in Berlin since 2022.', 'Olga приехала в Берлин в 2022 году. Она до сих пор там живёт. Olga живёт в Берлине с 2022 года.', 'Olga приїхала до Берліна 2022 року. Вона й досі там живе. Olga живе в Берліні з 2022 року.', 'Olga 2022’de Berlin’e geldi. Hâlâ orada oturuyor. Olga 2022’den beri Berlin’de oturuyor.']),
        mc('G3', 'vor', I.react, '„Wann hast du die Ausbildung gemacht?“', ['Vor zwei Jahren.', 'Seit zwei Jahren.', 'Zwei Jahre alt.'],
          ['“When did you do your training?”', '«Когда ты получил профессию?»', '«Коли ти здобув професію?»', '“Meslek eğitimini ne zaman yaptın?”']),
        gap('G3', 'vor', I.prep, 'Ich habe ', ' einem Monat meine Prüfung gemacht.', 'vor', ['seit', 'für'],
          ['I took my exam a month ago.', 'Я сдал экзамен месяц назад.', 'Я склав іспит місяць тому.', 'Bir ay önce sınavımı verdim.'], 'vor / seit'),
        gap('G3', 'seit', I.prep, 'Karim lernt ', ' sechs Monaten Deutsch.', 'seit', ['vor', 'bei'],
          ['Karim has been learning German for six months.', 'Karim учит немецкий уже шесть месяцев.', 'Karim вивчає німецьку вже шість місяців.', 'Karim altı aydır Almanca öğreniyor.'], 'vor / seit'),
        gap('G3', 'Dativ', I.article, 'Wir sind vor ', ' Jahr nach Hamburg gekommen.', 'einem', ['ein', 'einer'],
          ['We came to Hamburg a year ago.', 'Мы приехали в Гамбург год назад.', 'Ми приїхали до Гамбурга рік тому.', 'Bir yıl önce Hamburg’a geldik.'], 'ein', { h: 'dative' }),
        gap('G3', 'Dativ', I.article, 'Seit ', ' Woche habe ich eine neue Stelle.', 'einer', ['einem', 'eine'],
          ['I have had a new job for a week.', 'Уже неделю у меня новая работа.', 'Уже тиждень у мене нова робота.', 'Bir haftadır yeni bir işim var.'], 'ein', { h: 'dative' }),
        gap('G3', 'Dativ Plural', I.form, 'Dilara ist seit zwei ', ' selbstständig.', 'Jahren', ['Jahre', 'Jahr'],
          ['Dilara has been self-employed for two years.', 'Dilara уже два года работает на себя.', 'Dilara вже два роки працює на себе.', 'Dilara iki yıldır serbest çalışıyor.'], 'Jahr', { h: 'dative' }),
        gap('G3', 'seit', I.prep, '„', ' wann arbeitest du bei der Post?“ – „Seit März.“', 'Seit', ['Vor', 'Für'],
          ['“Since when have you been working at the post office?” – “Since March.”', '«С каких пор ты работаешь на почте?» – «С марта».', '«Відколи ти працюєш на пошті?» – «З березня».', '“Ne zamandan beri postanede çalışıyorsun?” – “Marttan beri.”'], 'vor / seit'),
        sb('G3', 'seit', I.order, 'Ich / lerne / seit einem Jahr / Deutsch.',
          ['I have been learning German for a year.', 'Я учу немецкий уже год.', 'Я вивчаю німецьку вже рік.', 'Bir yıldır Almanca öğreniyorum.'],
          { alt: ['Seit einem Jahr lerne ich Deutsch.', 'Deutsch lerne ich seit einem Jahr.'] }),
      ],
    },
    {
      title: 'Für wie lange?',
      t: ['For how long?', 'На какой срок?', 'На який термін?', 'Ne kadar süreliğine?'],
      card: {
        id: 'p1_fuer',
        rule: 'für + Akkusativ: Für wie lange? Ich suche für einen Monat Arbeit. für einen Monat (der), für ein Jahr (das), für eine Woche (die), für zwei Wochen (Plural). Nur bei „der“ wird ein zu einen.',
        examples: ['Wir fahren für eine Woche nach Wien.', 'Die Firma sucht für einen Monat eine Aushilfe.', 'Ich brauche das Auto für zwei Tage.'],
        highlight: 'article',
        t: [
          'für + accusative: For how long? Ich suche für einen Monat Arbeit. für einen Monat (der), für ein Jahr (das), für eine Woche (die), für zwei Wochen (plural). Only with “der” nouns does ein become einen.',
          'für + Akkusativ: На какой срок? Ich suche für einen Monat Arbeit. für einen Monat (der), für ein Jahr (das), für eine Woche (die), für zwei Wochen (мн. число). Только у слов с «der» ein меняется на einen.',
          'für + Akkusativ: На який термін? Ich suche für einen Monat Arbeit. für einen Monat (der), für ein Jahr (das), für eine Woche (die), für zwei Wochen (множина). Лише у слів із «der» ein змінюється на einen.',
          'für + Akkusativ: Ne kadar süreliğine? Ich suche für einen Monat Arbeit. für einen Monat (der), für ein Jahr (das), für eine Woche (die), für zwei Wochen (çoğul). Yalnızca “der” ile ein, einen olur.',
        ],
        hint: ['Nach für steht der Akkusativ: einen (der), ein (das), eine (die).', 'für takes the accusative: einen (der), ein (das), eine (die).', 'После für стоит Akkusativ: einen (der), ein (das), eine (die).', 'Після für стоїть Akkusativ: einen (der), ein (das), eine (die).', 'für’den sonra Akkusativ gelir: einen (der), ein (das), eine (die).'],
        hints: {
          prep: ['Ein Plan für eine bestimmte Zeit? → für. Von damals bis jetzt? → seit. Schon vorbei? → vor.', 'A plan for a certain time? → für. From then until now? → seit. Already over? → vor.', 'План на определённый срок? → für. С того времени до сих пор? → seit. Уже в прошлом? → vor.', 'План на певний термін? → für. Відтоді й дотепер? → seit. Уже в минулому? → vor.', 'Belirli bir süre için plan mı? → für. O zamandan şimdiye mi? → seit. Geçmişte mi kaldı? → vor.'],
        },
      },
      ex: [
        mc('G4', 'für', I.choose, 'Die Bäckerei sucht eine Aushilfe … einen Monat.', ['für', 'seit', 'vor'],
          ['The bakery is looking for a temporary helper for one month.', 'Пекарня ищет временного помощника на один месяц.', 'Пекарня шукає тимчасового помічника на один місяць.', 'Fırın bir aylığına yardımcı eleman arıyor.'], { h: 'prep' }),
        mc('G4', 'für', I.react, '„Für wie lange suchen Sie eine Wohnung?“', ['Für sechs Monate.', 'Vor sechs Monaten.', 'Seit sechs Monaten.'],
          ['“For how long are you looking for a flat?”', '«На какой срок вы ищете квартиру?»', '«На який термін ви шукаєте квартиру?»', '“Ne kadar süreliğine ev arıyorsunuz?”'], { h: 'prep' }),
        gap('G4', 'Akkusativ', I.article, 'Mateo geht für ', ' Jahr nach Spanien.', 'ein', ['einen', 'einem'],
          ['Mateo is going to Spain for a year.', 'Mateo едет в Испанию на год.', 'Mateo їде до Іспанії на рік.', 'Mateo bir yıllığına İspanya’ya gidiyor.'], 'ein / einen / eine'),
        gap('G4', 'Akkusativ', I.article, 'Ich suche für ', ' Monat ein Zimmer.', 'einen', ['einem', 'ein'],
          ['I am looking for a room for one month.', 'Я ищу комнату на один месяц.', 'Я шукаю кімнату на один місяць.', 'Bir aylığına oda arıyorum.'], 'ein'),
        gap('G4', 'Akkusativ', I.article, 'Hanna macht für ', ' Woche ein Praktikum.', 'eine', ['einer', 'einen'],
          ['Hanna is doing an internship for a week.', 'Hanna проходит практику в течение недели.', 'Hanna проходить практику протягом тижня.', 'Hanna bir haftalığına staj yapıyor.'], 'ein'),
        gap('G4', 'für', I.prep, 'Wir brauchen ', ' drei Tage einen Fahrer.', 'für', ['seit', 'vor'],
          ['We need a driver for three days.', 'Нам нужен водитель на три дня.', 'Нам потрібен водій на три дні.', 'Üç günlüğüne bir şoföre ihtiyacımız var.'], 'für / seit / vor', { h: 'prep' }),
        gap('G4', 'für', I.prep, 'Ich arbeite seit einem Jahr hier, und ich bleibe noch ', ' ein Jahr.', 'für', ['seit', 'vor'],
          ['I have worked here for a year, and I am staying for another year.', 'Я работаю здесь уже год и останусь ещё на год.', 'Я працюю тут уже рік і залишуся ще на рік.', 'Bir yıldır burada çalışıyorum ve bir yıl daha kalacağım.'], 'für / seit / vor', { h: 'prep' }),
        sb('G4', 'für', I.order, 'Sie / sucht / für einen Monat / eine Stelle.',
          ['She is looking for a job for one month.', 'Она ищет работу на один месяц.', 'Вона шукає роботу на один місяць.', 'Bir aylığına iş arıyor.'],
          { alt: ['Sie sucht eine Stelle für einen Monat.', 'Für einen Monat sucht sie eine Stelle.', 'Eine Stelle sucht sie für einen Monat.'] }),
      ],
    },
    {
      title: 'Mein Leben',
      t: ['My life', 'Моя жизнь', 'Моє життя', 'Hayatım'],
      card: {
        id: 'p1_life',
        rule: 'Über das eigene Leben sprechen: Wann bist du geboren? – 1995. Wo bist du geboren? – In Aleppo. Wo hast du gelebt? – In Aleppo und in Izmir. Wann bist du nach Deutschland gekommen? – Vor zwei Jahren. Seit wann lernst du Deutsch? – Seit einem Jahr.',
        examples: ['Ich bin 1990 in Lwiw geboren.', 'Ich habe zehn Jahre in Kiew gewohnt.', 'Vor drei Jahren bin ich nach Deutschland gekommen.'],
        highlight: null,
        t: [
          'Talking about your own life: Wann bist du geboren? (When were you born?) – 1995. Wo bist du geboren? – In Aleppo. Wo hast du gelebt? (Where did you live?) – In Aleppo und in Izmir. Wann bist du nach Deutschland gekommen? – Vor zwei Jahren. Seit wann lernst du Deutsch? – Seit einem Jahr.',
          'Как рассказать о своей жизни: Wann bist du geboren? (Когда ты родился?) – 1995. Wo bist du geboren? – In Aleppo. Wo hast du gelebt? (Где ты жил?) – In Aleppo und in Izmir. Wann bist du nach Deutschland gekommen? – Vor zwei Jahren. Seit wann lernst du Deutsch? – Seit einem Jahr.',
          'Як розповісти про своє життя: Wann bist du geboren? (Коли ти народився?) – 1995. Wo bist du geboren? – In Aleppo. Wo hast du gelebt? (Де ти жив?) – In Aleppo und in Izmir. Wann bist du nach Deutschland gekommen? – Vor zwei Jahren. Seit wann lernst du Deutsch? – Seit einem Jahr.',
          'Kendi hayatından söz etme: Wann bist du geboren? (Ne zaman doğdun?) – 1995. Wo bist du geboren? – In Aleppo. Wo hast du gelebt? (Nerede yaşadın?) – In Aleppo und in Izmir. Wann bist du nach Deutschland gekommen? – Vor zwei Jahren. Seit wann lernst du Deutsch? – Seit einem Jahr.',
        ],
        hint: ['Wann? → Jahr oder vor … Wo? → in + Stadt. Seit wann? → seit …', 'Wann? → a year or vor … Wo? → in + city. Seit wann? → seit …', 'Wann? → год или vor … Wo? → in + город. Seit wann? → seit …', 'Wann? → рік або vor … Wo? → in + місто. Seit wann? → seit …', 'Wann? → yıl ya da vor … Wo? → in + şehir. Seit wann? → seit …'],
      },
      ex: [
        mc('K2', 'Geburtsjahr', I.react, '„Wann sind Sie geboren?“', ['1988.', 'In Damaskus.', 'Seit 1988.'],
          ['“When were you born?”', '«Когда вы родились?»', '«Коли ви народилися?»', '“Ne zaman doğdunuz?”']),
        mc('K2', 'frühere Wohnorte', I.react, '„Wo hast du früher gelebt?“', ['In Ankara und in Izmir.', 'Vor fünf Jahren.', 'Ich lebe gern.'],
          ['“Where did you live before?”', '«Где ты жил раньше?»', '«Де ти жив раніше?»', '“Eskiden nerede yaşadın?”']),
        mc('K2', 'Ankunft', I.matchQuestion, '„Vor acht Monaten.“', ['Wann bist du nach Deutschland gekommen?', 'Wo bist du geboren?', 'Wie heißt deine Firma?'],
          ['“Eight months ago.”', '«Восемь месяцев назад».', '«Вісім місяців тому».', '“Sekiz ay önce.”']),
        gap('K2', 'Geburtsort', I.qword, '„', ' bist du geboren?“ – „In Odessa.“', 'Wo', ['Wann', 'Wer'],
          ['“Where were you born?” – “In Odessa.”', '«Где ты родился?» – «В Одессе».', '«Де ти народився?» – «В Одесі».', '“Nerede doğdun?” – “Odessa’da.”'],
          ['where', 'где', 'де', 'nerede']),
        gap('K2', 'geboren', I.word, 'Ich bin 1992 in Lagos ', '.', 'geboren', ['gelebt', 'gekommen'],
          ['I was born in Lagos in 1992.', 'Я родился в Лагосе в 1992 году.', 'Я народився в Лагосі 1992 року.', '1992’de Lagos’ta doğdum.'],
          ['born', 'родился', 'народився', 'doğmuş']),
        gap('G3', 'seit', I.prep, 'Yusuf lernt ', ' einem Jahr Deutsch und spricht schon gut.', 'seit', ['vor', 'für'],
          ['Yusuf has been learning German for a year and already speaks well.', 'Yusuf учит немецкий уже год и уже хорошо говорит.', 'Yusuf вивчає німецьку вже рік і вже добре говорить.', 'Yusuf bir yıldır Almanca öğreniyor ve şimdiden iyi konuşuyor.'], 'vor / seit', { c: 'p1_vorseit' }),
        gap('K2', 'frühere Wohnorte', I.verb, 'Wir haben acht Jahre in Lissabon ', '.', ['gewohnt', 'gelebt'], ['geboren', 'gekommen'],
          ['We lived in Lisbon for eight years.', 'Мы восемь лет жили в Лиссабоне.', 'Ми вісім років жили в Лісабоні.', 'Sekiz yıl Lizbon’da oturduk.'], 'wohnen'),
        sb('K2', 'Ankunft', I.question, 'Wann / bist / du / nach Deutschland / gekommen?',
          ['When did you come to Germany?', 'Когда ты приехал в Германию?', 'Коли ти приїхав до Німеччини?', 'Almanya’ya ne zaman geldin?']),
      ],
    },
    {
      title: 'Stellenanzeigen',
      t: ['Job advertisements', 'Объявления о работе', 'Оголошення про роботу', 'İş ilanları'],
      card: {
        id: 'p1_ads',
        rule: 'Stellenanzeigen lesen: Wer sucht? (Firma) Was? (Beruf, Stelle, Aushilfe) Wann? (Arbeitszeit: Vollzeit, Teilzeit, am Wochenende) Wie viel? (Verdienst, zum Beispiel 14 Euro pro Stunde) Wie? (anrufen, eine E-Mail schreiben, vorbeikommen). Suchst du selbst Arbeit? Schreib: Suche Arbeit als …',
        examples: ['Café Morgenrot sucht Kellner (m/w/d) für das Wochenende.', 'Verdienst: 14 Euro pro Stunde.', 'Suche Stelle als Fahrer. Tel. 0151 2030405.'],
        highlight: null,
        t: [
          'Reading job ads: Who is looking? (company) What? (job, position, temporary help = Aushilfe) When? (working hours: Vollzeit = full-time, Teilzeit = part-time, at the weekend) How much? (Verdienst = pay, e.g. 14 euros per hour) How? (call, write an e-mail, come by). Looking for work yourself? Write: Suche Arbeit als …',
          'Как читать объявления о работе: Кто ищет? (фирма) Что? (профессия, место, Aushilfe = временный помощник) Когда? (рабочее время: Vollzeit = полный день, Teilzeit = неполный день, по выходным) Сколько? (Verdienst = заработок, например 14 евро в час) Как? (позвонить, написать e-mail, зайти). Сами ищете работу? Напишите: Suche Arbeit als …',
          'Як читати оголошення про роботу: Хто шукає? (фірма) Що? (професія, посада, Aushilfe = тимчасовий помічник) Коли? (робочий час: Vollzeit = повний день, Teilzeit = неповний день, у вихідні) Скільки? (Verdienst = заробіток, наприклад 14 євро за годину) Як? (зателефонувати, написати e-mail, зайти). Самі шукаєте роботу? Напишіть: Suche Arbeit als …',
          'İş ilanı okuma: Kim arıyor? (firma) Ne? (meslek, pozisyon, Aushilfe = geçici yardımcı) Ne zaman? (çalışma saatleri: Vollzeit = tam zamanlı, Teilzeit = yarı zamanlı, hafta sonu) Ne kadar? (Verdienst = kazanç, örneğin saatte 14 avro) Nasıl? (aramak, e-posta yazmak, uğramak). Kendiniz mi iş arıyorsunuz? Şöyle yazın: Suche Arbeit als …',
        ],
        hint: ['Such im Text die Antwort auf die Frage: Wer? Was? Wann? Wie viel?', 'Look in the text for the answer: Who? What? When? How much?', 'Найдите в тексте ответ на вопрос: Кто? Что? Когда? Сколько?', 'Знайдіть у тексті відповідь на запитання: Хто? Що? Коли? Скільки?', 'Metinde sorunun cevabını arayın: Kim? Ne? Ne zaman? Ne kadar?'],
        hints: {
          word: ['Denk an die Wörter aus Anzeigen: Vollzeit, Teilzeit, Verdienst, Aushilfe.', 'Think of the words from ads: Vollzeit, Teilzeit, Verdienst, Aushilfe.', 'Вспомните слова из объявлений: Vollzeit, Teilzeit, Verdienst, Aushilfe.', 'Згадайте слова з оголошень: Vollzeit, Teilzeit, Verdienst, Aushilfe.', 'İlanlardaki kelimeleri düşünün: Vollzeit, Teilzeit, Verdienst, Aushilfe.'],
        },
      },
      ex: [
        mc('Z1', 'Stellenanzeige', I.read, 'Anzeige: „Gartenbau Lindner sucht ab sofort eine Aushilfe (m/w/d). Arbeitszeit: Montag bis Freitag, 7 bis 12 Uhr. Verdienst: 13,50 Euro pro Stunde. Telefon: 0561 778812.“ Wann arbeitet die Aushilfe?', ['Am Vormittag.', 'Am Abend.', 'Am Wochenende.'],
          ['When does the temporary helper work?', 'Когда работает временный помощник?', 'Коли працює тимчасовий помічник?', 'Yardımcı eleman ne zaman çalışıyor?']),
        mc('Z1', 'Stellenanzeige', I.read, 'Anzeige: „Gartenbau Lindner sucht ab sofort eine Aushilfe (m/w/d). Arbeitszeit: Montag bis Freitag, 7 bis 12 Uhr. Verdienst: 13,50 Euro pro Stunde. Telefon: 0561 778812.“ Wie viel verdient die Aushilfe?', ['13,50 Euro pro Stunde', '13,50 Euro pro Tag', '12 Euro pro Stunde'],
          ['How much does the temporary helper earn?', 'Сколько зарабатывает временный помощник?', 'Скільки заробляє тимчасовий помічник?', 'Yardımcı eleman ne kadar kazanıyor?']),
        mc('Z1', 'Stellenanzeige', I.read, 'Anzeige: „Pflegedienst Mühlbach sucht Krankenpfleger/in in Teilzeit (20 Stunden pro Woche). Berufserfahrung: mindestens zwei Jahre. Bitte schreiben Sie eine E-Mail.“ Für wen ist die Stelle?', ['Für Krankenpfleger mit Berufserfahrung.', 'Für Schüler ohne Berufserfahrung.', 'Für Ärzte in Vollzeit.'],
          ['Who is the job for?', 'Для кого эта вакансия?', 'Для кого ця вакансія?', 'Bu iş kimin için?']),
        mc('Z1', 'Stellengesuch', I.choose, 'Du suchst Arbeit und schreibst eine Anzeige. Was passt?', ['Suche Arbeit als Maler. Habe fünf Jahre Berufserfahrung.', 'Wir suchen einen Maler für unsere Firma.', 'Maler gesucht! Guter Verdienst.'],
          ['You are looking for work and write an ad. What fits?', 'Вы ищете работу и пишете объявление. Что подходит?', 'Ви шукаєте роботу й пишете оголошення. Що підходить?', 'İş arıyorsunuz ve bir ilan yazıyorsunuz. Hangisi uygun?']),
        gap('W1', 'Teilzeit', I.word, 'In der Anzeige steht: „20 Stunden pro Woche“. Das ist keine Vollzeit, das ist ', '.', 'Teilzeit', ['Freizeit', 'Arbeitszeit'],
          ['The ad says: “20 hours per week”. That is not full-time, it is part-time.', 'В объявлении написано: «20 часов в неделю». Это не полный рабочий день, а неполный.', 'В оголошенні написано: «20 годин на тиждень». Це не повний робочий день, а неповний.', 'İlanda “haftada 20 saat” yazıyor. Bu tam zamanlı değil, yarı zamanlı.'],
          ['part-time', 'неполный рабочий день', 'неповний робочий день', 'yarı zamanlı'], { h: 'word' }),
        gap('W1', 'Verdienst', I.word, 'Der ', ' ist gut: 16 Euro pro Stunde.', 'Verdienst', ['Beruf', 'Kollege'],
          ['The pay is good: 16 euros per hour.', 'Заработок хороший: 16 евро в час.', 'Заробіток добрий: 16 євро за годину.', 'Kazanç iyi: saatte 16 avro.'],
          ['pay, earnings', 'заработок', 'заробіток', 'kazanç'], { h: 'word' }),
        gap('Z1', 'Stellengesuch', I.verb, 'Meine Anzeige: „', ' Stelle als Koch. Habe Berufserfahrung.“', 'Suche', ['Finde', 'Mache'],
          ['My ad: “Looking for a job as a cook. Have work experience.”', 'Моё объявление: «Ищу работу поваром. Есть опыт работы».', 'Моє оголошення: «Шукаю роботу кухарем. Маю досвід роботи».', 'İlanım: “Aşçı olarak iş arıyorum. İş deneyimim var.”'], 'suchen'),
      ],
    },
    {
      title: 'Ist die Stelle noch frei?',
      t: ['Is the job still available?', 'Вакансия ещё свободна?', 'Вакансія ще вільна?', 'İş hâlâ boş mu?'],
      card: {
        id: 'p1_phone',
        rule: 'Am Telefon nach einer Stelle fragen: 1. Gruß und Name: Guten Tag, mein Name ist … 2. Grund: Ich habe Ihre Anzeige gelesen. Sie suchen eine Aushilfe. 3. Fragen: Ist die Stelle noch frei? Wie ist die Arbeitszeit? Wie ist der Verdienst pro Stunde? 4. Termin: Können Sie am Montag um zehn Uhr vorbeikommen?',
        examples: ['Guten Tag, mein Name ist Bondar. Ich habe Ihre Anzeige gelesen.', 'Ist die Stelle als Fahrer noch frei?', 'Wir zahlen 15 Euro pro Stunde. Kommen Sie doch mal vorbei.'],
        highlight: null,
        t: [
          'Asking about a job on the phone: 1. Greeting and name: Guten Tag, mein Name ist … 2. Reason: Ich habe Ihre Anzeige gelesen (I read your ad). Sie suchen eine Aushilfe. 3. Questions: Ist die Stelle noch frei? Wie ist die Arbeitszeit? Wie ist der Verdienst pro Stunde? 4. Appointment: Können Sie am Montag um zehn Uhr vorbeikommen (come by)?',
          'Как спросить о вакансии по телефону: 1. Приветствие и имя: Guten Tag, mein Name ist … 2. Причина: Ich habe Ihre Anzeige gelesen (я прочитал ваше объявление). Sie suchen eine Aushilfe. 3. Вопросы: Ist die Stelle noch frei? Wie ist die Arbeitszeit? Wie ist der Verdienst pro Stunde? 4. Встреча: Können Sie am Montag um zehn Uhr vorbeikommen (зайти)?',
          'Як запитати про вакансію телефоном: 1. Привітання та ім’я: Guten Tag, mein Name ist … 2. Причина: Ich habe Ihre Anzeige gelesen (я прочитав ваше оголошення). Sie suchen eine Aushilfe. 3. Запитання: Ist die Stelle noch frei? Wie ist die Arbeitszeit? Wie ist der Verdienst pro Stunde? 4. Зустріч: Können Sie am Montag um zehn Uhr vorbeikommen (зайти)?',
          'Telefonda iş sorma: 1. Selam ve isim: Guten Tag, mein Name ist … 2. Neden: Ich habe Ihre Anzeige gelesen (ilanınızı okudum). Sie suchen eine Aushilfe. 3. Sorular: Ist die Stelle noch frei? Wie ist die Arbeitszeit? Wie ist der Verdienst pro Stunde? 4. Randevu: Können Sie am Montag um zehn Uhr vorbeikommen (uğramak)?',
        ],
        hint: ['Erst der Name, dann die Anzeige, dann die Fragen zur Stelle.', 'First your name, then the ad, then your questions about the job.', 'Сначала имя, потом объявление, потом вопросы о вакансии.', 'Спочатку ім’я, потім оголошення, потім запитання про вакансію.', 'Önce isim, sonra ilan, sonra işle ilgili sorular.'],
      },
      ex: [
        mc('K4', 'nach der Stelle fragen', I.situation, 'Du rufst bei einer Firma an. Du hast die Anzeige gelesen und möchtest wissen: Suchen sie noch jemanden?', ['Ist die Stelle noch frei?', 'Sind Sie noch frei?', 'Ist die Anzeige noch neu?'],
          ['You call a company. You have read the ad and want to know: are they still looking for someone?', 'Вы звоните в фирму. Вы прочитали объявление и хотите узнать: они ещё кого-то ищут?', 'Ви телефонуєте до фірми. Ви прочитали оголошення й хочете дізнатися: вони ще когось шукають?', 'Bir firmayı arıyorsunuz. İlanı okudunuz ve öğrenmek istiyorsunuz: hâlâ birini arıyorlar mı?']),
        mc('K4', 'Arbeitszeit', I.react, '„Wie ist die Arbeitszeit?“', ['Von 8 bis 16 Uhr, Montag bis Freitag.', '15 Euro pro Stunde.', 'Die Stelle ist noch frei.'],
          ['“What are the working hours?”', '«Какой график работы?»', '«Який графік роботи?»', '“Çalışma saatleri nasıl?”']),
        mc('K4', 'Termin', I.react, '„Können Sie am Dienstag um neun Uhr vorbeikommen?“', ['Ja, gern. Am Dienstag habe ich Zeit.', 'Ja, ich habe die Anzeige gelesen.', 'Nein, ich bin Verkäufer.'],
          ['“Can you come by on Tuesday at nine?”', '«Вы можете зайти во вторник в девять часов?»', '«Ви можете зайти у вівторок о дев’ятій?»', '“Salı günü saat dokuzda uğrayabilir misiniz?”']),
        gap('K4', 'Anzeige', I.word, 'Guten Tag, ich habe Ihre ', ' gelesen. Sie suchen einen Koch.', 'Anzeige', ['Arbeitszeit', 'Ausbildung'],
          ['Hello, I have read your ad. You are looking for a cook.', 'Здравствуйте, я прочитал ваше объявление. Вы ищете повара.', 'Добрий день, я прочитав ваше оголошення. Ви шукаєте кухаря.', 'İyi günler, ilanınızı okudum. Bir aşçı arıyorsunuz.'],
          ['advertisement', 'объявление', 'оголошення', 'ilan']),
        gap('K4', 'Verdienst', I.word, 'Wie ist der Verdienst pro ', '?', 'Stunde', ['Stelle', 'Uhr'],
          ['What is the pay per hour?', 'Какой заработок в час?', 'Який заробіток за годину?', 'Saatlik kazanç ne kadar?'],
          ['hour', 'час', 'година', 'saat']),
        gap('K4', 'Verdienst', I.verb, 'Die Firma ', ' 14 Euro pro Stunde.', 'zahlt', ['zahlen', 'zahlst'],
          ['The company pays 14 euros per hour.', 'Фирма платит 14 евро в час.', 'Фірма платить 14 євро за годину.', 'Firma saatte 14 avro ödüyor.'], 'zahlen'),
        sb('K4', 'nach der Stelle fragen', I.question, 'Ist / die Stelle / noch / frei?',
          ['Is the job still available?', 'Вакансия ещё свободна?', 'Вакансія ще вільна?', 'İş hâlâ boş mu?']),
      ],
    },
  ],
}

export default path
