import { I, asChoice, gap, mc, sb } from '../shared.mjs'

/** A1.2 · Pfad 2 · Ämter und Behörden – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Familienstand', I.choose, 'Im Formular steht „Familienstand“. Was passt?', ['verheiratet', 'weiblich', 'deutsch'],
      ['The form says “Familienstand”. What fits?', 'В бланке написано «Familienstand». Что подходит?', 'У бланку написано «Familienstand». Що підходить?', 'Formda “Familienstand” yazıyor. Hangisi uygun?'], { h: 'form' }),
    mc('G3', 'man', I.choose, 'Was bedeutet „Hier muss man warten“?', ['Alle müssen hier warten.', 'Ein Mann muss hier warten.', 'Niemand muss hier warten.'],
      ['What does “Hier muss man warten” mean?', 'Что означает «Hier muss man warten»?', 'Що означає «Hier muss man warten»?', '“Hier muss man warten” ne anlama gelir?']),
    mc('K1', 'sagen, was nötig ist', I.situation, 'Du hast eine neue Adresse. Das Amt braucht diese Information. Das ist Pflicht.', ['Ich muss zum Bürgeramt gehen.', 'Ich darf nicht zum Bürgeramt gehen.', 'Ich gehe gern zum Bürgeramt.'],
      ['You have a new address. The office needs this information. It is compulsory.', 'У вас новый адрес. Учреждению нужна эта информация. Это обязательно.', 'У вас нова адреса. Установі потрібна ця інформація. Це обов’язково.', 'Yeni bir adresiniz var. Resmî dairenin bu bilgiye ihtiyacı var. Bu zorunlu.'], { h: 'need' }),
    mc('K2', 'verboten', I.react, '„Darf man hier essen?“', ['Nein, das ist leider verboten.', 'Nein, ich habe keinen Hunger.', 'Ja, man muss.'],
      ['“Is one allowed to eat here?”', '«Здесь можно есть?»', '«Тут можна їсти?»', '“Burada yemek yenir mi?”']),
    mc('K3', 'freundlich auffordern', I.situation, 'Du bist Lehrer. Die Kinder sind sehr laut. Du sagst freundlich:', ['Seid bitte leise!', 'Sei bitte leise!', 'Sind Sie leise!'],
      ['You are a teacher. The children are very loud. You say in a friendly way:', 'Вы учитель. Дети очень шумят. Вы дружелюбно говорите:', 'Ви вчитель. Діти дуже галасують. Ви привітно кажете:', 'Öğretmensiniz. Çocuklar çok gürültü yapıyor. Dostça diyorsunuz ki:'], { c: 'p2_imp_du', h: 'ihr' }),
    mc('K4', 'nach der Bedeutung fragen', I.situation, 'Du verstehst ein Wort im Brief vom Amt nicht. Du fragst deinen Nachbarn:', ['Entschuldigung, was bedeutet das Wort?', 'Entschuldigung, wo ist das Wort?', 'Entschuldigung, wie alt ist das Wort?'],
      ['You do not understand a word in the letter from the office. You ask your neighbour:', 'Вы не понимаете слово в письме из учреждения. Вы спрашиваете соседа:', 'Ви не розумієте слово в листі з установи. Ви питаєте сусіда:', 'Resmî daireden gelen mektuptaki bir kelimeyi anlamıyorsunuz. Komşunuza soruyorsunuz:'], { c: 'p2_nachfragen' }),
    mc('Z1', 'Schild', I.sign, 'Schild: „Kein Eingang! Bitte die andere Tür benutzen.“', ['Hier darf man nicht hineingehen.', 'Hier muss man hineingehen.', 'Die Tür ist kaputt.'],
      ['Sign: “No entry! Please use the other door.”', 'Табличка: «Входа нет! Пожалуйста, пользуйтесь другой дверью».', 'Табличка: «Входу немає! Будь ласка, користуйтеся іншими дверима».', 'Tabela: “Giriş yok! Lütfen diğer kapıyı kullanın.”']),
    gap('G1', 'müssen', I.modal, 'Ihr ', ' die Schuhe hier ausziehen. Das ist Pflicht.', 'müsst', ['musst', 'müssen'],
      ['You have to take your shoes off here. It is compulsory.', 'Вы должны здесь снять обувь. Это обязательно.', 'Ви мусите тут зняти взуття. Це обов’язково.', 'Ayakkabılarınızı burada çıkarmak zorundasınız. Bu zorunlu.'], 'müssen'),
    gap('G1', 'dürfen', I.modal, '', ' wir hier Fotos machen? – Ja, das ist erlaubt.', 'Dürfen', ['Dürft', 'Darf'],
      ['May we take photos here? – Yes, that is allowed.', 'Нам можно здесь фотографировать? – Да, это разрешено.', 'Нам можна тут фотографувати? – Так, це дозволено.', 'Burada fotoğraf çekebilir miyiz? – Evet, serbest.'],
      ['may, be allowed to', 'иметь разрешение, «можно»', 'мати дозвіл, «можна»', 'izinli olmak'], { c: 'p2_duerfen' }),
    gap('G4', 'Imperativ du', I.imperative, 'Lea, ', ' bitte das Fenster auf!', 'mach', ['machst', 'macht'],
      ['Lea, please open the window!', 'Lea, открой, пожалуйста, окно!', 'Lea, відчини, будь ласка, вікно!', 'Lea, lütfen pencereyi aç!'], 'aufmachen', { c: 'p2_imp_du' }),
    gap('G5', 'helfen', I.verb, 'Mein Sohn ', ' mir immer im Garten.', 'hilft', ['helft', 'hilfst'],
      ['My son always helps me in the garden.', 'Мой сын всегда помогает мне в саду.', 'Мій син завжди допомагає мені в саду.', 'Oğlum bahçede bana hep yardım ediyor.'], 'helfen', { c: 'p2_helfen' }),
    gap('K5', 'zuerst', I.word, '', ' zieht man eine Nummer. Dann wartet man.', 'Zuerst', ['Danach', 'Dann'],
      ['First you take a number. Then you wait.', 'Сначала берут номер. Потом ждут.', 'Спочатку беруть номер. Потім чекають.', 'Önce sıra numarası alınır. Sonra beklenir.'],
      ['first', 'сначала', 'спочатку', 'önce']),
    sb('G2', 'Satzklammer', I.order, 'Du / musst / den Antrag / heute / abgeben.',
      ['You have to hand in the application today.', 'Ты должен сдать заявление сегодня.', 'Ти мусиш подати заяву сьогодні.', 'Başvuruyu bugün teslim etmen gerekiyor.'],
      { alt: ['Du musst heute den Antrag abgeben.', 'Heute musst du den Antrag abgeben.', 'Den Antrag musst du heute abgeben.'] }),
  ],
  size: 13,
  test: [
    mc('G1', 'müssen', I.choose, 'Der Bus kommt in zwei Minuten. Wir … schnell gehen.', ['müssen', 'muss', 'müsst'],
      ['The bus is coming in two minutes. We have to walk fast.', 'Автобус придёт через две минуты. Нам нужно идти быстро.', 'Автобус приїде за дві хвилини. Нам треба йти швидко.', 'Otobüs iki dakika sonra geliyor. Hızlı yürümemiz gerekiyor.']),
    mc('G2', 'Satzklammer', I.sentence, 'Ein Schild im Park.', ['Hunde dürfen hier nicht spielen.', 'Hunde hier dürfen nicht spielen.', 'Hunde dürfen spielen hier nicht.'],
      ['A sign in the park.', 'Табличка в парке.', 'Табличка в парку.', 'Parkta bir tabela.']),
    mc('G3', 'man', I.choose, 'Welches Wort passt? „Im Bus muss … eine Fahrkarte haben.“', ['man', 'Mann', 'ihr'],
      ['Which word fits? “On the bus you have to have a ticket.”', 'Какое слово подходит? «В автобусе нужно иметь билет».', 'Яке слово підходить? «В автобусі треба мати квиток».', 'Hangi kelime uygun? “Otobüste bilet bulundurmak gerekir.”']),
    mc('G4', 'Imperativ von sein', I.choose, 'Du sagst zu deiner Freundin: „… bitte pünktlich!“', ['Sei', 'Seid', 'Seien Sie'],
      ['You say to your friend: “Please be on time!”', 'Вы говорите подруге: «Пожалуйста, не опаздывай!»', 'Ви кажете подрузі: «Будь ласка, не запізнюйся!»', 'Arkadaşınıza diyorsunuz ki: “Lütfen zamanında gel!”'], { c: 'p2_imp_du' }),
    mc('K1', 'sagen, was nötig ist', I.situation, 'Du bist neu in der Stadt. Die Anmeldung beim Amt ist Pflicht.', ['Ich muss zum Amt gehen und ein Formular ausfüllen.', 'Ich darf nicht zum Amt gehen.', 'Ich möchte kein Formular.'],
      ['You are new in town. Registering at the office is compulsory.', 'Вы недавно в городе. Регистрация в учреждении обязательна.', 'Ви нещодавно в місті. Реєстрація в установі обов’язкова.', 'Şehirde yenisiniz. Resmî daireye kayıt zorunlu.'], { h: 'need' }),
    mc('K2', 'verboten', I.choose, 'Im Schwimmbad ist Essen verboten. Welcher Satz passt?', ['Hier darf man nicht essen.', 'Hier muss man essen.', 'Hier darf man essen.'],
      ['Eating is forbidden at the swimming pool. Which sentence fits?', 'В бассейне есть запрещено. Какое предложение подходит?', 'У басейні їсти заборонено. Яке речення підходить?', 'Yüzme havuzunda yemek yemek yasak. Hangi cümle uygun?'], { h: 'choice' }),
    mc('K3', 'höflich auffordern', I.situation, 'Du arbeitest im Amt. Ein Mann hat seinen Ausweis vergessen. Du sagst höflich:', ['Bringen Sie bitte morgen Ihren Ausweis mit.', 'Bring morgen deinen Ausweis mit!', 'Ausweis mitbringen!'],
      ['You work at the office. A man has forgotten his ID card. You say politely:', 'Вы работаете в учреждении. Мужчина забыл удостоверение. Вы вежливо говорите:', 'Ви працюєте в установі. Чоловік забув посвідчення. Ви ввічливо кажете:', 'Resmî dairede çalışıyorsunuz. Bir adam kimliğini unutmuş. Kibarca diyorsunuz ki:']),
    mc('K4', 'um Wiederholung bitten', I.situation, 'Am Telefon sagt jemand eine Adresse. Du hast sie nicht verstanden.', ['Noch einmal, bitte.', 'Auf Wiederhören.', 'Vielen Dank, alles klar.'],
      ['On the phone someone says an address. You did not understand it.', 'По телефону кто-то называет адрес. Вы его не поняли.', 'Телефоном хтось називає адресу. Ви її не зрозуміли.', 'Telefonda biri bir adres söylüyor. Anlamadınız.'], { c: 'p2_nachfragen' }),
    mc('K5', 'Reihenfolge', I.choose, 'Was ist die richtige Reihenfolge?', ['Zuerst – dann – zum Schluss', 'Dann – zum Schluss – zuerst', 'Zum Schluss – zuerst – dann'],
      ['What is the correct order?', 'Какой порядок правильный?', 'Який порядок правильний?', 'Doğru sıra hangisi?']),
    mc('Z1', 'Schild', I.sign, 'Schild: „Bitte hier warten!“', ['Man muss hier warten.', 'Man darf hier nicht warten.', 'Man muss weitergehen.'],
      ['Sign: “Please wait here!”', 'Табличка: «Пожалуйста, подождите здесь!»', 'Табличка: «Будь ласка, зачекайте тут!»', 'Tabela: “Lütfen burada bekleyin!”']),
    mc('Z1', 'Öffnungszeiten', I.read, 'Information: „Das Bürgeramt ist am Montag und Dienstag von 8 bis 16 Uhr offen, am Donnerstag von 8 bis 18 Uhr. Am Mittwoch und Freitag ist es geschlossen.“ An welchem Tag ist das Amt am Abend offen?', ['Am Donnerstag.', 'Am Mittwoch.', 'Am Freitag.'],
      ['On which day is the office open in the evening?', 'В какой день учреждение работает вечером?', 'У який день установа працює ввечері?', 'Resmî daire hangi gün akşam açık?']),
    mc('W1', 'Unterschrift', I.choose, 'Am Ende vom Formular schreibst du deinen Namen mit der Hand. Das ist die …', ['Unterschrift', 'Auskunft', 'Anmeldung'],
      ['At the end of the form you write your name by hand. That is the …', 'В конце бланка вы пишете своё имя от руки. Это …', 'У кінці бланка ви пишете своє ім’я від руки. Це …', 'Formun sonuna adınızı elle yazarsınız. Bu …']),
    asChoice(gap('G1', 'müssen', I.modal, 'Du ', ' den Pass mitbringen. Ohne Pass geht es nicht.', 'musst', ['muss', 'müsst'],
      ['You have to bring your passport. It does not work without a passport.', 'Ты должен взять с собой паспорт. Без паспорта не получится.', 'Ти мусиш узяти з собою паспорт. Без паспорта не вийде.', 'Pasaportunu getirmen gerekiyor. Pasaportsuz olmaz.'], 'müssen')),
    gap('G1', 'dürfen', I.modal, 'Hier ', ' ihr nicht spielen. Das ist ein Parkplatz.', 'dürft', ['dürfen', 'darfst'],
      ['You must not play here. This is a car park.', 'Вам нельзя здесь играть. Это парковка.', 'Вам не можна тут гратися. Це парковка.', 'Burada oynayamazsınız. Burası otopark.'], 'dürfen', { c: 'p2_duerfen' }),
    gap('G1', 'dürfen', I.modal, 'Meine Tochter ist 16. Sie ', ' noch nicht Auto fahren.', 'darf', ['darfst', 'dürfen'],
      ['My daughter is 16. She is not yet allowed to drive a car.', 'Моей дочери 16 лет. Ей ещё нельзя водить машину.', 'Моїй доньці 16 років. Їй ще не можна керувати автомобілем.', 'Kızım 16 yaşında. Henüz araba kullanamaz.'], 'dürfen', { c: 'p2_duerfen' }),
    gap('G3', 'man + Verb', I.modal, 'In Deutschland ', ' man ab 18 wählen.', 'darf', ['dürfen', 'darfst'],
      ['In Germany you may vote from the age of 18.', 'В Германии можно голосовать с 18 лет.', 'У Німеччині можна голосувати з 18 років.', 'Almanya’da 18 yaşından itibaren oy kullanılabilir.'], 'dürfen'),
    asChoice(gap('G4', 'Imperativ Sie', I.imperative, 'Frau Lindner, ', ' Sie bitte hier!', 'warten', ['wartet', 'warte'],
      ['Ms Lindner, please wait here!', 'Госпожа Lindner, подождите, пожалуйста, здесь!', 'Пані Lindner, зачекайте, будь ласка, тут!', 'Lindner Hanım, lütfen burada bekleyin!'],
      ['wait', 'ждать', 'чекати', 'beklemek'])),
    asChoice(gap('G4', 'Imperativ ihr', I.imperative, 'Kinder, ', ' die Bücher auf!', 'macht', ['mach', 'machen'],
      ['Children, open your books!', 'Дети, откройте книги!', 'Діти, розгорніть книжки!', 'Çocuklar, kitaplarınızı açın!'], 'aufmachen', { c: 'p2_imp_du', h: 'ihr' })),
    asChoice(gap('G5', 'helfen', I.verb, 'Mein Kollege ', ' mir oft bei der Arbeit.', 'hilft', ['helft', 'hilfst'],
      ['My colleague often helps me at work.', 'Мой коллега часто помогает мне на работе.', 'Мій колега часто допомагає мені на роботі.', 'İş arkadaşım işte bana sık sık yardım ediyor.'], 'helfen', { c: 'p2_helfen' })),
    gap('G5', 'Imperativ mit Vokalwechsel', I.imperative, 'Jan, ', ' bitte den Bus um acht!', 'nimm', ['nimmst', 'nehmt'],
      ['Jan, please take the bus at eight!', 'Jan, садись, пожалуйста, на автобус в восемь!', 'Jan, сідай, будь ласка, на автобус о восьмій!', 'Jan, lütfen saat sekiz otobüsüne bin!'], 'nehmen', { h: 'vowel' }),
    asChoice(gap('K1', 'sagen, was nötig ist', I.modal, 'Der Antrag ist fertig. Jetzt ', ' ich nur noch unterschreiben.', 'muss', ['musst', 'müssen'],
      ['The application is ready. Now I only have to sign.', 'Заявление готово. Теперь мне осталось только расписаться.', 'Заява готова. Тепер мені лишилося тільки підписатися.', 'Başvuru hazır. Şimdi sadece imzalamam gerekiyor.'], 'müssen', { h: 'need' })),
    gap('K2', 'verboten', I.word, 'Parken ist hier ', '. Sie dürfen hier nicht stehen.', 'verboten', ['erlaubt', 'gültig'],
      ['Parking is forbidden here. You must not stop here.', 'Парковка здесь запрещена. Вам нельзя здесь стоять.', 'Паркування тут заборонено. Вам не можна тут стояти.', 'Burada park etmek yasak. Burada duramazsınız.'],
      ['forbidden', 'запрещено', 'заборонено', 'yasak']),
    asChoice(gap('K4', 'nach der Bedeutung fragen', I.verb, 'Entschuldigung, was ', ' „Geburtsort“?', ['bedeutet', 'heißt'], ['bedeuten', 'bedeute'],
      ['Excuse me, what does “Geburtsort” mean?', 'Извините, что означает «Geburtsort»?', 'Вибачте, що означає «Geburtsort»?', 'Affedersiniz, “Geburtsort” ne demek?'], 'bedeuten', { c: 'p2_nachfragen' })),
    gap('K5', 'dann', I.word, 'Zuerst füllt man das Formular aus. ', ' gibt man es am Schalter ab.', ['Dann', 'Danach'], ['Zuerst', 'Seit'],
      ['First you fill in the form. Then you hand it in at the counter.', 'Сначала заполняют бланк. Потом сдают его у окна.', 'Спочатку заповнюють бланк. Потім подають його біля віконця.', 'Önce form doldurulur. Sonra gişeye teslim edilir.'],
      ['then', 'потом', 'потім', 'sonra']),
    gap('W1', 'Vorname', I.word, 'Im Formular: ', ' Maria, Familienname Rojas.', 'Vorname', ['Geburtsort', 'Geschlecht'],
      ['On the form: first name Maria, surname Rojas.', 'В бланке: имя Maria, фамилия Rojas.', 'У бланку: ім’я Maria, прізвище Rojas.', 'Formda: ad Maria, soyadı Rojas.'],
      ['first name', 'имя', 'ім’я', 'ad'], { h: 'form' }),
    sb('G2', 'Satzklammer', I.order, 'Ich / muss / morgen / zum Amt / gehen.',
      ['I have to go to the office tomorrow.', 'Завтра мне нужно идти в учреждение.', 'Завтра мені треба йти до установи.', 'Yarın resmî daireye gitmem gerekiyor.'],
      { alt: ['Morgen muss ich zum Amt gehen.', 'Zum Amt muss ich morgen gehen.'] }),
    sb('G2', 'Ja/Nein-Frage', I.question, 'Darf / ich / hier / telefonieren?',
      ['May I make a phone call here?', 'Можно мне здесь позвонить?', 'Можна мені тут зателефонувати?', 'Burada telefonla konuşabilir miyim?']),
    sb('K3', 'höflich auffordern', I.request, 'Füllen / Sie / bitte / das Formular / aus!',
      ['Please fill in the form!', 'Заполните, пожалуйста, бланк!', 'Заповніть, будь ласка, бланк!', 'Lütfen formu doldurun!'],
      { alt: ['Füllen Sie das Formular bitte aus!', 'Bitte füllen Sie das Formular aus!'] }),
  ],
}

export default check
