import { I, gap, mc, sb } from '../shared.mjs'

/** A1.2 · Pfad 4 · In der Stadt unterwegs – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Orte', I.choose, 'Wo kaufst du Brot und Brötchen?', ['in der Bäckerei', 'in der Bank', 'im Rathaus'],
      ['Where do you buy bread and rolls?', 'Где вы покупаете хлеб и булочки?', 'Де ви купуєте хліб і булочки?', 'Ekmek ve küçük ekmekleri nereden alırsınız?']),
    mc('K1', 'nach dem Weg fragen', I.situation, 'Du suchst ein Hotel. Du fragst einen Mann auf der Straße.', ['Entschuldigung, gibt es hier in der Nähe ein Hotel?', 'Guten Tag, haben Sie ein Zimmer frei?', 'Hallo, wo wohnst du?'],
      ['You are looking for a hotel. You ask a man in the street.', 'Вы ищете отель. Вы спрашиваете мужчину на улице.', 'Ви шукаєте готель. Ви питаєте чоловіка на вулиці.', 'Bir otel arıyorsunuz. Sokakta bir adama soruyorsunuz.']),
    mc('K2', 'Weg beschreiben', I.react, '„Entschuldigung, wo ist die Bibliothek?“', ['Gehen Sie die zweite Straße links.', 'Die Bibliothek hat viele Bücher.', 'Ja, gern.'],
      ['“Excuse me, where is the library?”', '«Извините, где библиотека?»', '«Вибачте, де бібліотека?»', '“Affedersiniz, kütüphane nerede?”']),
    mc('K3', 'Verkehrsmittel nennen', I.react, '„Fährst du mit dem Auto zur Arbeit?“', ['Nein, ich fahre mit der U-Bahn.', 'Nein, ich arbeite im Auto.', 'Ja, zu Fuß.'],
      ['“Do you go to work by car?”', '«Ты ездишь на работу на машине?»', '«Ти їздиш на роботу машиною?»', '“İşe arabayla mı gidiyorsun?”'], { h: 'word' }),
    mc('K4', 'Fahrkarte kaufen', I.situation, 'Du möchtest nach Köln fahren und am Abend wieder zurückkommen. Was sagst du am Schalter?', ['Einmal Köln, hin und zurück, bitte.', 'Einmal Köln, einfach, bitte.', 'Ich brauche eine Auskunft.'],
      ['You want to go to Cologne and come back in the evening. What do you say at the counter?', 'Вы хотите поехать в Кёльн и вечером вернуться. Что вы скажете в кассе?', 'Ви хочете поїхати до Кельна й увечері повернутися. Що ви скажете в касі?', 'Köln’e gidip akşam geri dönmek istiyorsunuz. Gişede ne dersiniz?']),
    mc('Z1', 'Durchsage', I.read, 'Durchsage: „Der Zug nach Dresden fährt heute von Gleis 2 ab, nicht von Gleis 5.“ Von welchem Gleis fährt der Zug ab?', ['Von Gleis 2.', 'Von Gleis 5.', 'In Dresden.'],
      ['Which platform does the train leave from?', 'С какого пути отправляется поезд?', 'З якої колії відправляється поїзд?', 'Tren hangi perondan kalkıyor?']),
    gap('G1', 'mit + Dativ', I.article, 'Fahren Sie mit ', ' Straßenbahn? – Nein, mit dem Bus.', 'der', ['dem', 'den'],
      ['Are you going by tram? – No, by bus.', 'Вы едете на трамвае? – Нет, на автобусе.', 'Ви їдете трамваєм? – Ні, автобусом.', 'Tramvayla mı gidiyorsunuz? – Hayır, otobüsle.'], 'die'),
    gap('G2', 'Dativ', I.article, 'Das Café ist neben ', ' Kino.', 'dem', ['der', 'das'],
      ['The café is next to the cinema.', 'Кафе находится рядом с кинотеатром.', 'Кафе розташоване поруч із кінотеатром.', 'Kafe sinemanın yanında.'], 'das'),
    gap('G2', 'zwischen', I.prep, 'Die Haltestelle ist ', ' der Bank und der Post.', 'zwischen', ['unter', 'über'],
      ['The stop is between the bank and the post office.', 'Остановка находится между банком и почтой.', 'Зупинка розташована між банком і поштою.', 'Durak bankayla postanenin arasında.'], 'zwischen / unter / über', { h: 'place' }),
    gap('G3', 'beim', I.prep, 'Wo ist Emre? – Er ist ', ' Zahnarzt.', 'beim', ['zum', 'im'],
      ['Where is Emre? – He is at the dentist’s.', 'Где Emre? – Он у стоматолога.', 'Де Emre? – Він у стоматолога.', 'Emre nerede? – Diş hekiminde.'], 'bei + dem'),
    gap('G4', 'zum', I.prep, 'Heute Nachmittag gehe ich ', ' Supermarkt.', 'zum', ['zur', 'nach'],
      ['This afternoon I am going to the supermarket.', 'Сегодня после обеда я иду в супермаркет.', 'Сьогодні після обіду я йду до супермаркету.', 'Bu öğleden sonra süpermarkete gidiyorum.'], 'zu + dem'),
    gap('G4', 'nach + Land', I.prep, 'Im Juli fahren wir ', ' Österreich.', 'nach', ['in', 'zu'],
      ['In July we are going to Austria.', 'В июле мы едем в Австрию.', 'У липні ми їдемо до Австрії.', 'Temmuzda Avusturya’ya gidiyoruz.'], 'nach / in / zu'),
    sb('G4', 'ins', I.order, 'Am Samstag / gehen / wir / ins Kino.',
      ['On Saturday we are going to the cinema.', 'В субботу мы идём в кино.', 'У суботу ми йдемо в кіно.', 'Cumartesi günü sinemaya gidiyoruz.'],
      { alt: ['Wir gehen am Samstag ins Kino.', 'Ins Kino gehen wir am Samstag.'] }),
  ],
  size: 12,
  test: [
    mc('W1', 'Orte', I.choose, 'Ein Bus hält hier und Leute warten hier. Was ist das?', ['die Haltestelle', 'die Kreuzung', 'die Brücke'],
      ['A bus stops here and people wait here. What is it?', 'Здесь останавливается автобус и ждут люди. Что это?', 'Тут зупиняється автобус і чекають люди. Що це?', 'Burada otobüs durur ve insanlar bekler. Burası neresi?']),
    mc('G1', 'mit + Dativ', I.choose, 'Wir fahren … Taxi zum Flughafen.', ['mit dem', 'mit der', 'mit den'],
      ['We are taking a taxi to the airport.', 'Мы едем в аэропорт на такси.', 'Ми їдемо до аеропорту на таксі.', 'Havalimanına taksiyle gidiyoruz.']),
    mc('G2', 'in + Dativ', I.choose, 'Das Auto steht … Garage.', ['in der', 'in die', 'in dem'],
      ['The car is in the garage.', 'Машина стоит в гараже.', 'Машина стоїть у гаражі.', 'Araba garajda duruyor.']),
    mc("G3", "bei + Person", I.choose, "Wo ist Leon? – Er ist ___ Freund Milan.", ["bei dem","zum","in den"], ["Where is Leon? – He is at his friend Milan’s.","Где Leon? – Он у друга Milan.","Де Leon? – Він у друга Milan.","Leon nerede? – Arkadaşı Milan’da."], {"c":"p4_woist","sitovOptionOrder":["bei dem","zum","in den"]}),
    mc('G4', 'zum', I.choose, 'Ich habe Fieber. Ich muss … Arzt gehen.', ['zum', 'beim', 'im'],
      ['I have a temperature. I have to go to the doctor.', 'У меня температура. Мне нужно идти к врачу.', 'У мене температура. Мені треба йти до лікаря.', 'Ateşim var. Doktora gitmem gerekiyor.']),
    mc('K1', 'nach dem Weg fragen', I.situation, 'Du suchst eine Bank und fragst höflich:', ['Entschuldigung, wo ist hier eine Bank?', 'Wo Bank?', 'Ich will Bank.'],
      ['You are looking for a bank and ask politely:', 'Вы ищете банк и вежливо спрашиваете:', 'Ви шукаєте банк і ввічливо питаєте:', 'Bir banka arıyorsunuz ve kibarca soruyorsunuz:']),
    mc('K1', 'nicht helfen können', I.situation, 'Jemand fragt: „Entschuldigung, wo ist das Rathaus?“ Du weißt es nicht.', ['Tut mir leid, ich bin nicht von hier.', 'Ja, natürlich.', 'Das Rathaus ist alt.'],
      ['Someone asks: “Excuse me, where is the town hall?” You do not know.', 'Кто-то спрашивает: «Извините, где ратуша?» Вы не знаете.', 'Хтось питає: «Вибачте, де ратуша?» Ви не знаєте.', 'Biri soruyor: “Affedersiniz, belediye binası nerede?” Bilmiyorsunuz.']),
    mc('K2', 'Wegbeschreibung verstehen', I.read, 'Wegbeschreibung: „Gehen Sie hier nach rechts und dann immer geradeaus. Nach 200 Metern ist links der Supermarkt.“ Auf welcher Seite ist der Supermarkt?', ['Links.', 'Rechts.', 'Geradeaus.'],
      ['Which side is the supermarket on?', 'С какой стороны находится супермаркет?', 'З якого боку розташований супермаркет?', 'Süpermarket hangi tarafta?']),
    mc('K3', 'Verkehrsmittel nennen', I.react, '„Wie kommen Sie zum Deutschkurs?“', ['Ich gehe zu Fuß.', 'Ich komme aus Syrien.', 'Ich komme um neun.'],
      ['“How do you get to your German course?”', '«Как вы добираетесь на курс немецкого?»', '«Як ви добираєтеся на курс німецької?»', '“Almanca kursuna nasıl geliyorsunuz?”'], { h: 'word' }),
    mc('K4', 'Ankunft', I.react, '„Wann kommt der Zug in Hamburg an?“', ['Um 18.42 Uhr.', 'Von Gleis 12.', 'Hin und zurück.'],
      ['“When does the train arrive in Hamburg?”', '«Когда поезд прибывает в Гамбург?»', '«Коли поїзд прибуває до Гамбурга?»', '“Tren Hamburg’a ne zaman varıyor?”']),
    mc('Z1', 'Fahrplan', I.read, 'Fahrplan: „Bremen ab 7.48, Gleis 2 – Hannover an 9.05.“ Wann ist der Zug in Hannover?', ['Um 9.05 Uhr.', 'Um 7.48 Uhr.', 'Um 2 Uhr.'],
      ['When is the train in Hanover?', 'Когда поезд будет в Ганновере?', 'Коли поїзд буде в Ганновері?', 'Tren Hannover’de ne zaman olur?']),
    mc('Z1', 'Durchsage', I.read, 'Durchsage: „Der Zug nach Frankfurt hat heute 15 Minuten Verspätung.“ Was bedeutet das?', ['Der Zug kommt 15 Minuten später.', 'Der Zug fährt in 15 Minuten nach Hause.', 'Der Zug fährt heute nicht.'],
      ['What does that mean?', 'Что это значит?', 'Що це означає?', 'Bu ne anlama geliyor?']),
    gap('W1', 'Verkehrsmittel', I.word, 'Es hat zwei Räder und keinen Motor. Ich fahre gern ', '.', 'Fahrrad', ['Taxi', 'Zug'],
      ['It has two wheels and no engine. I like riding my bike.', 'У него два колеса и нет мотора. Я люблю ездить на велосипеде.', 'У нього два колеса й немає мотора. Я люблю їздити на велосипеді.', 'İki tekerleği var, motoru yok. Bisiklete binmeyi severim.'],
      ['bicycle', 'велосипед', 'велосипед', 'bisiklet'], { c: 'p4_mit', h: 'word' }),
    gap('G1', 'mit + Dativ', I.article, 'Oma fährt mit ', ' Zug nach Köln.', 'dem', ['der', 'den'],
      ['Grandma is going to Cologne by train.', 'Бабушка едет в Кёльн на поезде.', 'Бабуся їде до Кельна поїздом.', 'Büyükannem Köln’e trenle gidiyor.'], 'der'),
    gap('G1', 'mit + Dativ', I.article, 'Ich fahre heute mit ', ' U-Bahn ins Büro.', 'der', ['dem', 'den'],
      ['Today I am taking the underground to the office.', 'Сегодня я еду в офис на метро.', 'Сьогодні я їду в офіс на метро.', 'Bugün ofise metroyla gidiyorum.'], 'die'),
    gap('G2', 'Dativ', I.article, 'Der Hund liegt unter ', ' Tisch.', 'dem', ['den', 'der'],
      ['The dog is lying under the table.', 'Собака лежит под столом.', 'Собака лежить під столом.', 'Köpek masanın altında yatıyor.'], 'der'),
    gap('G2', 'hinter', I.prep, 'Zuerst kommt die Bank, dann der Park. Der Park ist ', ' der Bank.', 'hinter', ['über', 'zwischen'],
      ['First comes the bank, then the park. The park is behind the bank.', 'Сначала банк, потом парк. Парк находится за банком.', 'Спочатку банк, потім парк. Парк розташований за банком.', 'Önce banka, sonra park geliyor. Park bankanın arkasında.'], 'hinter / über / zwischen', { h: 'place' }),
    gap('G3', 'Land im Plural', I.prep, 'Mein Bruder studiert ', ' den USA.', 'in', ['nach', 'bei'],
      ['My brother is studying in the USA.', 'Мой брат учится в США.', 'Мій брат навчається у США.', 'Erkek kardeşim ABD’de okuyor.'], 'in / nach / bei'),
    gap('G3', 'zu Hause', I.prep, 'Am Sonntag bleibe ich ', ' Hause.', 'zu', ['nach', 'in'],
      ['On Sunday I am staying at home.', 'В воскресенье я остаюсь дома.', 'У неділю я залишаюся вдома.', 'Pazar günü evde kalıyorum.'], 'zu / nach', { c: 'p4_wowohin' }),
    gap('G4', 'Land mit Artikel', I.prep, 'Wir fliegen im Winter ', ' die Schweiz.', 'in', ['nach', 'zu'],
      ['In winter we are flying to Switzerland.', 'Зимой мы летим в Швейцарию.', 'Узимку ми летимо до Швейцарії.', 'Kışın İsviçre’ye uçuyoruz.'], 'in / nach / zu'),
    gap('G4', 'zur', I.prep, 'Kommst du mit ', ' Post? Ich muss ein Paket abholen.', 'zur', ['zum', 'nach'],
      ['Are you coming to the post office with me? I have to collect a parcel.', 'Пойдёшь со мной на почту? Мне нужно забрать посылку.', 'Підеш зі мною на пошту? Мені треба забрати посилку.', 'Benimle postaneye geliyor musun? Bir paket almam gerekiyor.'], 'zu + der'),
    gap('K2', 'geradeaus', I.word, 'Gehen Sie nicht nach links und nicht nach rechts. Gehen Sie immer ', '.', 'geradeaus', ['zurück', 'hinten'],
      ['Do not go left and do not go right. Keep going straight on.', 'Не идите ни налево, ни направо. Идите всё время прямо.', 'Не йдіть ні ліворуч, ні праворуч. Ідіть весь час прямо.', 'Sola da sağa da gitmeyin. Hep düz gidin.'],
      ['straight on', 'прямо', 'прямо', 'dümdüz']),
    gap('K3', 'mit', I.prep, 'Viele Leute fahren ', ' dem Fahrrad zur Arbeit.', 'mit', ['bei', 'zu'],
      ['Many people go to work by bike.', 'Многие ездят на работу на велосипеде.', 'Багато людей їздять на роботу велосипедом.', 'Birçok insan işe bisikletle gidiyor.'], 'mit / bei / zu'),
    gap('K4', 'Gleis', I.word, 'Der Zug fährt von ', ' 5 ab.', 'Gleis', ['Schalter', 'Fahrkarte'],
      ['The train leaves from platform 5.', 'Поезд отправляется с пятого пути.', 'Поїзд відправляється з п’ятої колії.', 'Tren 5. perondan kalkıyor.'],
      ['platform, track', 'путь, платформа', 'колія, платформа', 'peron']),
    sb('G2', 'neben + Dativ', I.order, 'Die Apotheke / ist / neben / der Bank.',
      ['The pharmacy is next to the bank.', 'Аптека находится рядом с банком.', 'Аптека розташована поруч із банком.', 'Eczane bankanın yanında.']),
    sb('K4', 'umsteigen', I.question, 'Muss / ich / in Hannover / umsteigen?',
      ['Do I have to change in Hanover?', 'Мне нужно делать пересадку в Ганновере?', 'Мені треба робити пересадку в Ганновері?', 'Hannover’de aktarma yapmam gerekiyor mu?']),
  ],
}

export default check
