import { I, asChoice, gap, mc, sb } from '../shared.mjs'

/** A1.2 · Pfad 5 · Kundenservice – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Geräte', I.choose, 'Du möchtest einen Brief drucken. Welches Gerät brauchst du?', ['den Drucker', 'den Herd', 'den Kühlschrank'],
      ['You want to print a letter. Which appliance do you need?', 'Вы хотите распечатать письмо. Какое устройство вам нужно?', 'Ви хочете роздрукувати лист. Який пристрій вам потрібен?', 'Bir mektup yazdırmak istiyorsunuz. Hangi cihaza ihtiyacınız var?']),
    mc('K1', 'Problem beschreiben', I.react, '„Guten Tag, was kann ich für Sie tun?“', ['Mein Drucker ist kaputt.', 'Ich kann nichts tun.', 'Auf Wiederhören.'],
      ['“Good morning, what can I do for you?”', '«Добрый день, чем могу помочь?»', '«Добрий день, чим можу допомогти?»', '“İyi günler, sizin için ne yapabilirim?”']),
    mc('K2', 'Bis wann?', I.react, '„Bis wann ist mein Handy fertig?“', ['Bis morgen Mittag.', 'Seit gestern.', 'Ja, mit Garantie.'],
      ['“By when will my mobile be ready?”', '«К какому времени будет готов мой телефон?»', '«До якого часу буде готовий мій телефон?»', '“Telefonum ne zamana kadar hazır olur?”']),
    mc('K3', 'Bitte annehmen', I.react, '„Würdest du bitte kurz warten?“', ['Natürlich, kein Problem.', 'Nichts zu danken.', 'Nein, danke, ich warte.'],
      ['“Would you wait a moment, please?”', '«Ты не подождёшь минутку, пожалуйста?»', '«Ти не зачекаєш хвилинку, будь ласка?»', '“Biraz bekler misin lütfen?”']),
    mc('K4', 'Ansage verstehen', I.choose, 'Die Ansage sagt: „Bitte hinterlassen Sie eine Nachricht.“ Was machst du?', ['Ich spreche auf die Mailbox.', 'Ich höre Musik.', 'Ich schreibe einen Brief.'],
      ['The announcement says: “Please leave a message.” What do you do?', 'Запись говорит: «Пожалуйста, оставьте сообщение». Что вы делаете?', 'Запис каже: «Будь ласка, залиште повідомлення». Що ви робите?', 'Anons diyor ki: “Lütfen mesaj bırakın.” Ne yaparsınız?']),
    mc('K5', 'Nachricht sprechen', I.choose, 'Welcher Satz passt für eine Nachricht auf der Mailbox?', ['Bitte rufen Sie zurück unter 0151 7788990.', 'Sie sind verbunden mit Familie Kaya.', 'Im Moment bin ich nicht erreichbar.'],
      ['Which sentence fits a message on a voicemail?', 'Какое предложение подходит для сообщения на автоответчике?', 'Яке речення підходить для повідомлення на автовідповідачі?', 'Telesekretere bırakılan mesaja hangi cümle uygun?'], { h: 'leave' }),
    mc('Z1', 'Gebrauchsanweisung', I.read, 'Anleitung: „Schalten Sie das Gerät nach dem Kochen aus.“ Wann schaltet man das Gerät aus?', ['Nach dem Kochen.', 'Vor dem Kochen.', 'Beim Kochen.'],
      ['When do you switch the appliance off?', 'Когда нужно выключить прибор?', 'Коли треба вимкнути прилад?', 'Cihaz ne zaman kapatılır?']),
    gap('G1', 'Dativ', I.article, 'Nach ', ' Kurs gehe ich nach Hause.', 'dem', ['der', 'den'],
      ['After the course I go home.', 'После курса я иду домой.', 'Після курсу я йду додому.', 'Kurstan sonra eve gidiyorum.'], 'der', { h: 'dative' }),
    gap('G1', 'vor', I.prep, '', ' der Arbeit frühstücke ich. Dann fahre ich ins Büro.', 'Vor', ['Nach', 'Bei'],
      ['Before work I have breakfast. Then I go to the office.', 'Перед работой я завтракаю. Потом еду в офис.', 'Перед роботою я снідаю. Потім їду в офіс.', 'İşten önce kahvaltı ediyorum. Sonra ofise gidiyorum.'], 'vor / nach / bei'),
    gap('G2', 'in', I.prep, 'Jetzt ist es zwei Uhr. ', ' einer Stunde ist es drei Uhr.', 'In', ['Vor', 'Seit'],
      ['It is two o’clock now. In an hour it will be three o’clock.', 'Сейчас два часа. Через час будет три часа.', 'Зараз друга година. Через годину буде третя.', 'Şimdi saat iki. Bir saat sonra saat üç olacak.'], 'in / vor / seit'),
    gap('G3', 'von … bis', I.prep, 'Der Kurs geht von Montag ', ' Donnerstag.', 'bis', ['ab', 'in'],
      ['The course runs from Monday to Thursday.', 'Курс идёт с понедельника по четверг.', 'Курс триває з понеділка по четвер.', 'Kurs pazartesiden perşembeye kadar sürüyor.'], 'bis / ab'),
    gap('G4', 'könnten', I.polite, '', ' Sie mir bitte Ihre Nummer geben?', ['Könnten', 'Würden'], ['Könntest', 'Kannst'],
      ['Could you give me your number, please?', 'Не могли бы вы дать мне свой номер?', 'Чи не могли б ви дати мені свій номер?', 'Bana numaranızı verebilir misiniz lütfen?'], 'können'),
    sb('K6', 'Tagesablauf', I.order, 'Vor dem Abendessen / mache / ich / Sport.',
      ['Before dinner I do sport.', 'Перед ужином я занимаюсь спортом.', 'Перед вечерею я займаюся спортом.', 'Akşam yemeğinden önce spor yapıyorum.'],
      { alt: ['Ich mache vor dem Abendessen Sport.', 'Sport mache ich vor dem Abendessen.'] }),
  ],
  size: 13,
  test: [
    mc('W1', 'Geräte', I.choose, 'Hier wäschst du deine Kleidung. Was ist das?', ['die Waschmaschine', 'der Herd', 'der Drucker'],
      ['You wash your clothes in it. What is it?', 'В ней стирают одежду. Что это?', 'У ній перуть одяг. Що це?', 'Giysilerinizi burada yıkarsınız. Bu nedir?']),
    mc('G1', 'nach', I.choose, 'Erst arbeite ich, dann mache ich Sport. Ich mache … der Arbeit Sport.', ['nach', 'vor', 'bei'],
      ['First I work, then I do sport. I do sport after work.', 'Сначала я работаю, потом занимаюсь спортом. Я занимаюсь спортом после работы.', 'Спочатку я працюю, потім займаюся спортом. Я займаюся спортом після роботи.', 'Önce çalışıyorum, sonra spor yapıyorum. İşten sonra spor yapıyorum.']),
    mc('G2', 'in + Dativ', I.choose, 'Heute ist der 1. Mai. Am 1. Juni fliege ich nach Rom. Ich fliege …', ['in einem Monat', 'vor einem Monat', 'seit einem Monat'],
      ['Today is 1 May. On 1 June I am flying to Rome. I am flying in a month.', 'Сегодня 1 мая. 1 июня я лечу в Рим. Я лечу через месяц.', 'Сьогодні 1 травня. 1 червня я лечу до Рима. Я лечу через місяць.', 'Bugün 1 Mayıs. 1 Haziran’da Roma’ya uçuyorum. Bir ay sonra uçuyorum.']),
    mc('G3', 'ab', I.react, '„Ab wann ist die Praxis wieder offen?“', ['Ab Dienstag.', 'Seit zwei Jahren.', 'In der Stadt.'],
      ['“From when is the practice open again?”', '«С какого дня практика снова открыта?»', '«З якого дня практика знову відчинена?»', '“Muayenehane ne zamandan itibaren tekrar açık?”']),
    mc('G4', 'könnten', I.choose, 'Du bittest deine Lehrerin: „… Sie das bitte noch einmal erklären?“', ['Könnten', 'Könntest', 'Kannst'],
      ['You ask your teacher: “Could you explain that once more, please?”', 'Вы просите учительницу: «Не могли бы вы объяснить это ещё раз?»', 'Ви просите вчительку: «Чи не могли б ви пояснити це ще раз?»', 'Öğretmeninizden rica ediyorsunuz: “Bunu bir kez daha açıklayabilir misiniz lütfen?”']),
    mc('K1', 'Problem beschreiben', I.situation, 'Dein neuer Fernseher funktioniert nicht. Du rufst den Kundenservice an.', ['Guten Tag, mein Fernseher funktioniert nicht.', 'Guten Tag, ich möchte einen Fernseher kaufen.', 'Guten Tag, mein Fernseher ist sehr gut.'],
      ['Your new TV does not work. You call customer service.', 'Ваш новый телевизор не работает. Вы звоните в сервисную службу.', 'Ваш новий телевізор не працює. Ви телефонуєте до сервісної служби.', 'Yeni televizyonunuz çalışmıyor. Müşteri hizmetlerini arıyorsunuz.']),
    mc('K2', 'Garantie', I.react, '„Ist die Reparatur teuer?“', ['Nein, Sie haben noch Garantie.', 'Ja, in einer Stunde.', 'Nein, bis Freitag.'],
      ['“Is the repair expensive?”', '«Ремонт дорогой?»', '«Ремонт дорогий?»', '“Tamir pahalı mı?”']),
    mc('K3', 'Bitte annehmen', I.react, '„Könnten Sie mir bitte die Tür aufmachen?“', ['Ja, natürlich.', 'Nichts zu danken.', 'Ja, bitte machen Sie das.'],
      ['“Could you open the door for me, please?”', '«Не могли бы вы открыть мне дверь?»', '«Чи не могли б ви відчинити мені двері?»', '“Bana kapıyı açabilir misiniz lütfen?”']),
    mc('K3', 'auf Dank reagieren', I.react, '„Danke für die schnelle Reparatur!“', ['Gern geschehen.', 'Das geht leider nicht.', 'Könnten Sie mir helfen?'],
      ['“Thank you for the quick repair!”', '«Спасибо за быстрый ремонт!»', '«Дякую за швидкий ремонт!»', '“Hızlı tamir için teşekkürler!”']),
    mc('K4', 'Ansage verstehen', I.read, 'Ansage: „Hier ist der Anschluss von Familie Petrov. Wir sind im Moment nicht zu Hause. Bitte sprechen Sie nach dem Ton. Wir rufen zurück.“ Was macht Familie Petrov später?', ['Sie ruft zurück.', 'Sie schreibt eine E-Mail.', 'Sie kommt vorbei.'],
      ['What will the Petrov family do later?', 'Что семья Petrov сделает позже?', 'Що родина Petrov зробить пізніше?', 'Petrov ailesi daha sonra ne yapacak?']),
    mc('K5', 'Nachricht sprechen', I.choose, 'Du sprichst auf die Mailbox. Was darf nicht fehlen?', ['Dein Name und deine Telefonnummer.', 'Dein Alter und dein Beruf.', 'Deine Adresse und dein Geburtsort.'],
      ['You leave a message on a voicemail. What must not be missing?', 'Вы оставляете сообщение на автоответчике. Что обязательно нужно сказать?', 'Ви залишаєте повідомлення на автовідповідачі. Що обов’язково треба сказати?', 'Telesekretere mesaj bırakıyorsunuz. Ne eksik olmamalı?'], { h: 'leave' }),
    mc('K6', 'Tagesablauf verstehen', I.read, 'Der Techniker erzählt: „Vor der Mittagspause repariere ich Geräte in der Werkstatt. Nach der Mittagspause fahre ich zu den Kunden.“ Wo ist er am Vormittag?', ['In der Werkstatt.', 'Bei den Kunden.', 'Zu Hause.'],
      ['Where is he in the morning?', 'Где он в первой половине дня?', 'Де він у першій половині дня?', 'Öğleden önce nerede?']),
    mc('Z1', 'Service-Anzeige', I.read, 'Anzeige: „Handy kaputt? Wir reparieren alle Marken in 60 Minuten. Montag bis Samstag, 9 bis 19 Uhr. Handy-Doktor am Bahnhof.“ Wie lange dauert die Reparatur?', ['Eine Stunde.', 'Einen Tag.', 'Eine Woche.'],
      ['How long does the repair take?', 'Сколько длится ремонт?', 'Скільки триває ремонт?', 'Tamir ne kadar sürüyor?']),
    mc('Z1', 'Gebrauchsanweisung', I.read, 'Anleitung: „Drücken Sie zuerst die Taste EIN. Wählen Sie dann das Programm. Drücken Sie zum Schluss START.“ Was macht man zum Schluss?', ['START drücken.', 'Das Programm wählen.', 'EIN drücken.'],
      ['What do you do at the end?', 'Что нужно сделать в конце?', 'Що треба зробити наприкінці?', 'En sonunda ne yapılır?']),
    gap('W1', 'Mailbox', I.word, 'Niemand geht ans Telefon. Ich höre nur die ', '.', 'Mailbox', ['Garantie', 'Reparatur'],
      ['Nobody answers the phone. I only hear the voicemail.', 'Никто не берёт трубку. Я слышу только автоответчик.', 'Ніхто не бере слухавку. Я чую лише автовідповідач.', 'Kimse telefonu açmıyor. Sadece telesekreteri duyuyorum.'],
      ['voicemail', 'автоответчик', 'автовідповідач', 'telesekreter']),
    gap('G1', 'Dativ', I.article, 'Vor ', ' Frühstück gehe ich mit dem Hund spazieren.', 'dem', ['das', 'der'],
      ['Before breakfast I take the dog for a walk.', 'Перед завтраком я гуляю с собакой.', 'Перед сніданком я гуляю з собакою.', 'Kahvaltıdan önce köpekle yürüyüşe çıkıyorum.'], 'das', { h: 'dative' }),
    gap('G1', 'beim', I.prep, '', ' Abendessen sprechen wir über den Tag.', 'Beim', ['Bei', 'Im'],
      ['At dinner we talk about the day.', 'За ужином мы говорим о прошедшем дне.', 'За вечерею ми говоримо про минулий день.', 'Akşam yemeğinde günümüzü konuşuyoruz.'], 'bei + dem'),
    asChoice(gap('G2', 'Dativ', I.article, 'In ', ' Stunde ist das Essen fertig.', 'einer', ['einem', 'eine'],
      ['The meal will be ready in an hour.', 'Еда будет готова через час.', 'Їжа буде готова через годину.', 'Yemek bir saat sonra hazır.'], 'ein')),
    gap('G2', 'vor', I.prep, 'Der Techniker war ', ' einer Stunde hier. Jetzt funktioniert alles.', 'vor', ['in', 'ab'],
      ['The technician was here an hour ago. Now everything works.', 'Мастер был здесь час назад. Теперь всё работает.', 'Майстер був тут годину тому. Тепер усе працює.', 'Teknisyen bir saat önce buradaydı. Şimdi her şey çalışıyor.'], 'in / vor / ab'),
    gap('G3', 'bis', I.prep, 'Die Bäckerei ist nur ', ' 13 Uhr offen. Danach ist sie geschlossen.', 'bis', ['ab', 'in'],
      ['The bakery is only open until 1 p.m. After that it is closed.', 'Пекарня открыта только до 13 часов. Потом она закрыта.', 'Пекарня відчинена лише до 13 години. Потім вона зачинена.', 'Fırın sadece saat 13’e kadar açık. Ondan sonra kapalı.'], 'bis / ab'),
    gap('G3', 'ab', I.prep, '', ' nächster Woche habe ich einen neuen Job.', 'Ab', ['Bis', 'Vor'],
      ['From next week I have a new job.', 'Со следующей недели у меня новая работа.', 'З наступного тижня в мене нова робота.', 'Gelecek haftadan itibaren yeni bir işim var.'], 'bis / ab'),
    gap('G4', 'könntest', I.polite, '', ' du mir bitte dein Handy geben? Ich muss kurz telefonieren.', ['Könntest', 'Würdest'], ['Könnten', 'Würden'],
      ['Could you give me your mobile, please? I need to make a quick call.', 'Ты не мог бы дать мне свой телефон? Мне нужно быстро позвонить.', 'Ти не міг би дати мені свій телефон? Мені треба швидко зателефонувати.', 'Bana telefonunu verebilir misin lütfen? Kısa bir telefon görüşmesi yapmam gerekiyor.'], 'können'),
    gap('K1', 'Kundenservice', I.word, 'Guten Tag, könnte ich bitte den ', ' sprechen? Mein Herd ist kaputt.', 'Kundenservice', ['Kühlschrank', 'Drucker'],
      ['Good morning, could I speak to customer service, please? My cooker is broken.', 'Добрый день, можно поговорить с сервисной службой? У меня сломалась плита.', 'Добрий день, чи можна поговорити із сервісною службою? У мене зламалася плита.', 'İyi günler, müşteri hizmetleriyle görüşebilir miyim lütfen? Ocağım bozuldu.'],
      ['customer service', 'сервисная служба', 'сервісна служба', 'müşteri hizmetleri']),
    gap('K2', 'Techniker', I.word, 'Wann kann der ', ' kommen? Die Heizung ist kaputt.', 'Techniker', ['Kunde', 'Drucker'],
      ['When can the technician come? The heating is broken.', 'Когда может прийти мастер? Отопление сломалось.', 'Коли може прийти майстер? Опалення зламалося.', 'Teknisyen ne zaman gelebilir? Kalorifer bozuk.'],
      ['technician', 'мастер, техник', 'майстер, технік', 'teknisyen']),
    gap('K4', 'nicht erreichbar', I.word, 'Im Moment bin ich leider nicht ', '. Bitte rufen Sie später an.', 'erreichbar', ['verbunden', 'kaputt'],
      ['Unfortunately I am not available at the moment. Please call later.', 'К сожалению, сейчас я не могу ответить. Пожалуйста, позвоните позже.', 'На жаль, зараз я не можу відповісти. Будь ласка, зателефонуйте пізніше.', 'Maalesef şu anda ulaşılamıyorum. Lütfen daha sonra arayın.'],
      ['available, reachable', 'доступен, на связи', 'доступний, на зв’язку', 'ulaşılabilir']),
    mc("K5", "Nachricht beginnen", I.choose, "Hier ___ Jonas Weber. Bitte rufen Sie zurück.", ["spricht","sprichst","sprechen"], ["This is Jonas Weber speaking. Please call back.","Говорит Jonas Weber. Пожалуйста, перезвоните.","Говорить Jonas Weber. Будь ласка, передзвоніть.","Ben Jonas Weber. Lütfen geri arayın."], {"h":"leave","c":"p5_mailbox","sitovOptionOrder":["sprichst","spricht","sprechen"]}),
    sb('G4', 'würden', I.question, 'Würden / Sie / bitte / kurz / warten?',
      ['Would you wait a moment, please?', 'Не подождёте ли вы минутку?', 'Чи не зачекаєте ви хвилинку?', 'Biraz bekler misiniz lütfen?'],
      { alt: ['Würden Sie kurz bitte warten?'] }),
    sb('K6', 'Tagesablauf', I.order, 'Nach der Mittagspause / rufe / ich / Kunden / an.',
      ['After the lunch break I call customers.', 'После обеденного перерыва я звоню клиентам.', 'Після обідньої перерви я телефоную клієнтам.', 'Öğle arasından sonra müşterileri arıyorum.'],
      { alt: ['Ich rufe nach der Mittagspause Kunden an.', 'Kunden rufe ich nach der Mittagspause an.'] }),
  ],
}

export default check
