import { I, gap, mc, sb } from '../shared.mjs'

const DAY = 'Mila erzählt: „Vor der Arbeit gehe ich joggen. Bei der Arbeit telefoniere ich viel. Nach der Arbeit kaufe ich ein und koche.“'
const ANNOUNCEMENT = 'Ansage: „Guten Tag, Sie sind verbunden mit der Praxis Dr. Weber. Im Moment sind wir nicht erreichbar. Unsere Sprechzeiten sind Montag bis Freitag von 8 bis 12 Uhr. Bitte rufen Sie später noch einmal an.“'
const AD = 'Anzeige: „Elektro-Service Falke: Reparatur von Waschmaschinen, Herden und Kühlschränken. Wir kommen in 24 Stunden. Notdienst auch am Wochenende. Anfahrt kostenlos. Telefon 0561 334455.“'
const MANUAL = 'Anleitung: „1. Stecken Sie den Stecker ein. 2. Füllen Sie Wasser ein. 3. Drücken Sie die Taste START. 4. Nach fünf Minuten ist der Kaffee fertig. 5. Schalten Sie das Gerät aus.“'

/** A1.2 · Pfad 5 · Kundenservice – Lektionen. Wiederholung und Test: p5-check.mjs */
const path = {
  n: 5,
  slug: 'kundenservice',
  title: 'Kundenservice',
  t: ['Customer service', 'Сервисная служба', 'Сервісна служба', 'Müşteri hizmetleri'],
  objectives: {
    G1: 'Temporale Präpositionen vor, nach und bei + Dativ: vor dem Kurs, nach der Arbeit, beim Training.',
    G2: '„in“ + Dativ für einen Zeitpunkt in der Zukunft: in einem Monat, in einer Woche, in drei Jahren.',
    G3: 'Temporale Präpositionen bis und ab: Wie lange? Bis morgen. Ab wann? Ab Montag.',
    G4: 'Höfliche Aufforderung mit Konjunktiv II: Könnten Sie …? Würden Sie …? Könntest du …? Würdest du …? – der Infinitiv steht am Ende.',
    K1: 'Beim Kundenservice anrufen und ein Problem beschreiben: Mein Herd funktioniert nicht. Er ist kaputt.',
    K2: 'Fragen zu Reparatur, Garantie und Termin stellen und beantworten.',
    K3: 'Höflich um etwas bitten und auf Bitten und Dank reagieren: Natürlich. Ja, gern. Das geht leider gerade nicht. Nichts zu danken.',
    K4: 'Ansagen auf der Mailbox verstehen: Sie sind verbunden mit …, nicht erreichbar, eine Nachricht hinterlassen.',
    K5: 'Eine Nachricht auf die Mailbox sprechen: Hier ist …, Bitte rufen Sie zurück unter …',
    K6: 'Tagesabläufe mit Zeitangaben beschreiben: Vor der Mittagspause mache ich Reparaturen.',
    Z1: 'Kann-Ziele: Service-Anzeigen und Gebrauchsanweisungen verstehen.',
    W1: 'Wortschatz: Kundenservice und Telekommunikation.',
  },
  nodes: [
    {
      title: 'Geräte und Service',
      t: ['Appliances and service', 'Техника и сервис', 'Техніка і сервіс', 'Cihazlar ve servis'],
      card: {
        id: 'p5_service',
        rule: 'Kundenservice: Das Gerät (die Waschmaschine, der Herd, der Kühlschrank, der Drucker) ist kaputt oder funktioniert nicht. Der Techniker macht die Reparatur. Mit Garantie kostet die Reparatur nichts. Telefon: Man wählt eine Nummer und ruft an. Niemand da? Man spricht eine Nachricht auf die Mailbox.',
        examples: ['Unsere Waschmaschine ist kaputt.', 'Das Gerät hat noch ein Jahr Garantie.', 'Der Techniker kommt morgen.'],
        highlight: null,
        t: [
          'Customer service: the appliance (die Waschmaschine = washing machine, der Herd = cooker, der Kühlschrank = fridge, der Drucker = printer) is kaputt (broken) or funktioniert nicht (does not work). The Techniker (technician) does the Reparatur (repair). With a Garantie (warranty) the repair costs nothing. Phone: you dial (wählen) a number and call. Nobody there? You leave a Nachricht (message) on the Mailbox (voicemail).',
          'Сервисная служба: прибор (die Waschmaschine = стиральная машина, der Herd = плита, der Kühlschrank = холодильник, der Drucker = принтер) kaputt (сломан) или funktioniert nicht (не работает). Techniker (мастер) делает Reparatur (ремонт). С Garantie (гарантией) ремонт бесплатный. Телефон: набирают (wählen) номер и звонят. Никого нет? Оставляют Nachricht (сообщение) на Mailbox (автоответчике).',
          'Сервісна служба: прилад (die Waschmaschine = пральна машина, der Herd = плита, der Kühlschrank = холодильник, der Drucker = принтер) kaputt (зламаний) або funktioniert nicht (не працює). Techniker (майстер) робить Reparatur (ремонт). З Garantie (гарантією) ремонт безкоштовний. Телефон: набирають (wählen) номер і телефонують. Нікого немає? Залишають Nachricht (повідомлення) на Mailbox (автовідповідачі).',
          'Müşteri hizmetleri: Cihaz (die Waschmaschine = çamaşır makinesi, der Herd = ocak, der Kühlschrank = buzdolabı, der Drucker = yazıcı) kaputt (bozuk) ya da funktioniert nicht (çalışmıyor). Techniker (teknisyen) Reparatur (tamir) yapar. Garantie (garanti) varsa tamir ücretsizdir. Telefon: Bir numara tuşlanır (wählen) ve aranır. Kimse yok mu? Mailbox’a (telesekreter) bir Nachricht (mesaj) bırakılır.',
        ],
        hint: ['Denk an die Situation: Etwas ist kaputt. Wer hilft? Was braucht man?', 'Think of the situation: something is broken. Who helps? What do you need?', 'Представьте ситуацию: что-то сломалось. Кто поможет? Что нужно?', 'Уявіть ситуацію: щось зламалося. Хто допоможе? Що потрібно?', 'Durumu düşünün: bir şey bozuldu. Kim yardım eder? Ne gerekir?'],
      },
      ex: [
        mc('W1', 'Geräte', I.choose, 'Hier bleiben Milch, Butter und Käse kalt. Was ist das?', ['der Kühlschrank', 'der Herd', 'der Drucker'],
          ['Milk, butter and cheese stay cold here. What is it?', 'Здесь молоко, масло и сыр остаются холодными. Что это?', 'Тут молоко, масло й сир залишаються холодними. Що це?', 'Süt, tereyağı ve peynir burada soğuk kalır. Bu nedir?']),
        mc('W1', 'Garantie', I.choose, 'Dein Handy ist neu, aber kaputt. Die Reparatur kostet nichts. Warum?', ['Das Handy hat noch Garantie.', 'Das Handy hat keine Nummer.', 'Das Handy ist alt.'],
          ['Your mobile is new but broken. The repair costs nothing. Why?', 'Ваш телефон новый, но сломан. Ремонт бесплатный. Почему?', 'Ваш телефон новий, але зламаний. Ремонт безкоштовний. Чому?', 'Cep telefonunuz yeni ama bozuk. Tamir ücretsiz. Neden?']),
        mc('W1', 'Techniker', I.choose, 'Wer repariert die Waschmaschine?', ['der Techniker', 'der Verkäufer', 'der Kunde'],
          ['Who repairs the washing machine?', 'Кто ремонтирует стиральную машину?', 'Хто ремонтує пральну машину?', 'Çamaşır makinesini kim tamir eder?']),
        mc('W1', 'Geräte', I.odd, 'Drei Wörter sind Geräte, ein Wort nicht.', ['Rechnung', 'Herd', 'Drucker', 'Waschmaschine'], null),
        gap('W1', 'kaputt', I.word, 'Der Drucker druckt nicht. Er ist ', '.', 'kaputt', ['neu', 'billig'],
          ['The printer is not printing. It is broken.', 'Принтер не печатает. Он сломан.', 'Принтер не друкує. Він зламаний.', 'Yazıcı yazdırmıyor. Bozuk.'],
          ['broken', 'сломан', 'зламаний', 'bozuk']),
        gap('W1', 'funktionieren', I.verb, 'Mein Computer ', ' nicht. Ich kann nicht arbeiten.', 'funktioniert', ['funktionieren', 'funktionierst'],
          ['My computer is not working. I cannot work.', 'Мой компьютер не работает. Я не могу работать.', 'Мій комп’ютер не працює. Я не можу працювати.', 'Bilgisayarım çalışmıyor. Çalışamıyorum.'], 'funktionieren'),
        gap('W1', 'Nachricht', I.word, 'Niemand ist da. Ich spreche eine ', ' auf die Mailbox.', 'Nachricht', ['Rechnung', 'Garantie'],
          ['Nobody is there. I leave a message on the voicemail.', 'Никого нет. Я оставляю сообщение на автоответчике.', 'Нікого немає. Я залишаю повідомлення на автовідповідачі.', 'Kimse yok. Telesekretere bir mesaj bırakıyorum.'],
          ['message', 'сообщение', 'повідомлення', 'mesaj']),
        gap('W1', 'wählen', I.verb, 'Zuerst muss man die Nummer ', '. Dann spricht man.', 'wählen', ['wählt', 'gewählt'],
          ['First you have to dial the number. Then you talk.', 'Сначала нужно набрать номер. Потом разговаривают.', 'Спочатку треба набрати номер. Потім розмовляють.', 'Önce numarayı tuşlamak gerekir. Sonra konuşulur.'],
          ['dial', 'набирать (номер)', 'набирати (номер)', 'tuşlamak']),
      ],
    },
    {
      title: 'vor, nach, bei',
      t: ['vor, nach, bei (before, after, during)', 'vor, nach, bei (до, после, во время)', 'vor, nach, bei (до, після, під час)', 'vor, nach, bei (önce, sonra, sırasında)'],
      card: {
        id: 'p5_vornach',
        rule: 'vor, nach, bei + Dativ (Wann?): vor = früher als etwas: vor dem Kurs, vor der Arbeit. nach = später als etwas: nach dem Kurs, nach der Arbeit. bei = in der Zeit von etwas: beim Training (bei + dem), bei der Arbeit. Dativ: der/das → dem, die → der, Plural → den: nach den Hausaufgaben.',
        examples: ['Vor dem Frühstück dusche ich.', 'Nach der Arbeit gehe ich einkaufen.', 'Beim Essen sprechen wir über den Tag.'],
        highlight: 'article',
        t: [
          'vor, nach, bei + dative (When?): vor = earlier than something (before): vor dem Kurs, vor der Arbeit. nach = later than something (after): nach dem Kurs, nach der Arbeit. bei = during something: beim Training (bei + dem), bei der Arbeit. Dative: der/das → dem, die → der, plural → den: nach den Hausaufgaben.',
          'vor, nach, bei + Dativ (Когда?): vor = раньше чего-то (до, перед): vor dem Kurs, vor der Arbeit. nach = позже чего-то (после): nach dem Kurs, nach der Arbeit. bei = во время чего-то: beim Training (bei + dem), bei der Arbeit. Dativ: der/das → dem, die → der, множественное число → den: nach den Hausaufgaben.',
          'vor, nach, bei + Dativ (Коли?): vor = раніше за щось (до, перед): vor dem Kurs, vor der Arbeit. nach = пізніше за щось (після): nach dem Kurs, nach der Arbeit. bei = під час чогось: beim Training (bei + dem), bei der Arbeit. Dativ: der/das → dem, die → der, множина → den: nach den Hausaufgaben.',
          'vor, nach, bei + Dativ (Ne zaman?): vor = bir şeyden önce: vor dem Kurs, vor der Arbeit. nach = bir şeyden sonra: nach dem Kurs, nach der Arbeit. bei = bir şey sırasında: beim Training (bei + dem), bei der Arbeit. Dativ: der/das → dem, die → der, çoğul → den: nach den Hausaufgaben.',
        ],
        hint: ['Was kommt zuerst? vor = davor, nach = danach, bei = zur gleichen Zeit.', 'What comes first? vor = before, nach = after, bei = at the same time.', 'Что идёт сначала? vor = до этого, nach = после этого, bei = в то же время.', 'Що йде спочатку? vor = до цього, nach = після цього, bei = у той самий час.', 'Önce ne geliyor? vor = önce, nach = sonra, bei = aynı anda.'],
        hints: {
          dative: ['Nach vor, nach und bei steht der Dativ: dem (der/das), der (die), den (Plural).', 'vor, nach and bei take the dative: dem (der/das), der (die), den (plural).', 'После vor, nach и bei стоит Dativ: dem (der/das), der (die), den (множественное число).', 'Після vor, nach і bei стоїть Dativ: dem (der/das), der (die), den (множина).', 'vor, nach ve bei’den sonra Dativ gelir: dem (der/das), der (die), den (çoğul).'],
        },
      },
      ex: [
        mc('G1', 'vor', I.choose, 'Zuerst frühstücke ich, dann gehe ich zur Arbeit. Ich frühstücke … der Arbeit.', ['vor', 'nach', 'bei'],
          ['First I have breakfast, then I go to work. I have breakfast before work.', 'Сначала я завтракаю, потом иду на работу. Я завтракаю до работы.', 'Спочатку я снідаю, потім іду на роботу. Я снідаю до роботи.', 'Önce kahvaltı ediyorum, sonra işe gidiyorum. İşten önce kahvaltı ediyorum.']),
        mc('G1', 'nach', I.choose, 'Der Kurs ist um zwölf zu Ende. Um halb eins esse ich. Ich esse … dem Kurs.', ['nach', 'vor', 'bei'],
          ['The course ends at twelve. At half past twelve I eat. I eat after the course.', 'Курс заканчивается в двенадцать. В половине первого я ем. Я ем после курса.', 'Курс закінчується о дванадцятій. О пів на першу я їм. Я їм після курсу.', 'Kurs on ikide bitiyor. Yarımda yemek yiyorum. Kurstan sonra yemek yiyorum.']),
        mc('G1', 'beim', I.choose, 'Ich koche und höre Musik. … Kochen höre ich Musik.', ['Beim', 'Vor dem', 'Nach dem'],
          ['I cook and listen to music. While cooking I listen to music.', 'Я готовлю и слушаю музыку. Во время готовки я слушаю музыку.', 'Я готую і слухаю музику. Під час готування я слухаю музику.', 'Yemek yapıyorum ve müzik dinliyorum. Yemek yaparken müzik dinliyorum.']),
        gap('G1', 'Dativ', I.article, 'Vor ', ' Arbeit trinke ich einen Kaffee.', 'der', ['dem', 'die'],
          ['Before work I drink a coffee.', 'Перед работой я пью кофе.', 'Перед роботою я п’ю каву.', 'İşten önce bir kahve içiyorum.'], 'die', { h: 'dative' }),
        gap('G1', 'Dativ', I.article, 'Nach ', ' Essen gehen wir spazieren.', 'dem', ['das', 'der'],
          ['After the meal we go for a walk.', 'После еды мы идём гулять.', 'Після їжі ми йдемо гуляти.', 'Yemekten sonra yürüyüşe çıkıyoruz.'], 'das', { h: 'dative' }),
        gap('G1', 'Dativ Plural', I.article, 'Nach ', ' Hausaufgaben dürfen die Kinder spielen.', 'den', ['dem', 'die'],
          ['After their homework the children may play.', 'После домашних заданий детям можно играть.', 'Після домашніх завдань дітям можна гратися.', 'Ödevlerden sonra çocuklar oynayabilir.'], 'die (Plural)', { h: 'dative' }),
        gap('G1', 'nach', I.prep, '', ' dem Training dusche ich. Ich bin dann immer sehr müde.', 'Nach', ['Vor', 'Bei'],
          ['After training I have a shower. I am always very tired then.', 'После тренировки я принимаю душ. Тогда я всегда очень уставший.', 'Після тренування я приймаю душ. Тоді я завжди дуже втомлений.', 'Antrenmandan sonra duş alıyorum. O zaman hep çok yorgun oluyorum.'], 'vor / nach / bei'),
        gap('G1', 'beim', I.prep, '', ' Frühstück lese ich Nachrichten auf dem Handy.', 'Beim', ['Bei', 'Im'],
          ['At breakfast I read the news on my phone.', 'За завтраком я читаю новости в телефоне.', 'За сніданком я читаю новини в телефоні.', 'Kahvaltıda telefonumdan haberleri okuyorum.'], 'bei + dem'),
        gap('G1', 'vor', I.prep, 'Erst lernen, dann spielen: ', ' dem Spielen machen wir die Hausaufgaben.', 'Vor', ['Nach', 'Bei'],
          ['First study, then play: before playing we do our homework.', 'Сначала учёба, потом игра: перед игрой мы делаем домашние задания.', 'Спочатку навчання, потім гра: перед грою ми робимо домашні завдання.', 'Önce ders, sonra oyun: oynamadan önce ödevleri yapıyoruz.'], 'vor / nach / bei'),
        sb('G1', 'nach', I.order, 'Nach der Arbeit / gehe / ich / einkaufen.',
          ['After work I go shopping.', 'После работы я иду за покупками.', 'Після роботи я йду по покупки.', 'İşten sonra alışverişe gidiyorum.'],
          { alt: ['Ich gehe nach der Arbeit einkaufen.'] }),
      ],
    },
    {
      title: 'Mein Tag',
      t: ['My day', 'Мой день', 'Мій день', 'Günüm'],
      card: {
        id: 'p5_tag',
        rule: 'Einen Tagesablauf beschreiben: Zeitangaben stehen oft am Satzanfang. Dann kommt das Verb auf Position 2: Vor dem Frühstück dusche ich. Nach der Mittagspause mache ich Reparaturen. Beim Abendessen sprechen wir über den Tag. Auch so: Ich dusche vor dem Frühstück.',
        examples: ['Vor der Arbeit bringe ich die Kinder zur Schule.', 'Nach dem Mittagessen rufe ich Kunden an.', 'Bei der Arbeit trage ich Arbeitskleidung.'],
        highlight: 'verb',
        t: [
          'Describing your day: time expressions often come first. Then the verb is in position 2: Vor dem Frühstück dusche ich. Nach der Mittagspause mache ich Reparaturen. Beim Abendessen sprechen wir über den Tag. Also possible: Ich dusche vor dem Frühstück.',
          'Как описать свой день: указание времени часто стоит в начале предложения. Тогда глагол идёт на 2-м месте: Vor dem Frühstück dusche ich. Nach der Mittagspause mache ich Reparaturen. Beim Abendessen sprechen wir über den Tag. Можно и так: Ich dusche vor dem Frühstück.',
          'Як описати свій день: обставина часу часто стоїть на початку речення. Тоді дієслово йде на 2-му місці: Vor dem Frühstück dusche ich. Nach der Mittagspause mache ich Reparaturen. Beim Abendessen sprechen wir über den Tag. Можна й так: Ich dusche vor dem Frühstück.',
          'Günü anlatma: Zaman ifadeleri çoğu zaman cümlenin başında durur. Sonra fiil 2. sıraya gelir: Vor dem Frühstück dusche ich. Nach der Mittagspause mache ich Reparaturen. Beim Abendessen sprechen wir über den Tag. Şöyle de olur: Ich dusche vor dem Frühstück.',
        ],
        hint: ['Zeitangabe auf Position 1 → das Verb auf Position 2 → dann das Subjekt.', 'Time expression in position 1 → the verb in position 2 → then the subject.', 'Указание времени на 1-м месте → глагол на 2-м месте → потом подлежащее.', 'Обставина часу на 1-му місці → дієслово на 2-му місці → потім підмет.', 'Zaman ifadesi 1. sırada → fiil 2. sırada → sonra özne.'],
      },
      ex: [
        mc('K6', 'Tagesablauf', I.sentence, 'Der Techniker beschreibt seinen Tag.', ['Vor der Mittagspause mache ich Reparaturen.', 'Vor der Mittagspause ich mache Reparaturen.', 'Vor der Mittagspause Reparaturen ich mache.'],
          ['The technician describes his day.', 'Мастер описывает свой день.', 'Майстер описує свій день.', 'Teknisyen gününü anlatıyor.']),
        mc('K6', 'Tagesablauf verstehen', I.read, `${DAY} Wann geht Mila joggen?`, ['Am Morgen vor der Arbeit.', 'Am Abend nach der Arbeit.', 'In der Mittagspause.'],
          ['When does Mila go jogging?', 'Когда Mila бегает?', 'Коли Mila бігає?', 'Mila ne zaman koşuya çıkıyor?']),
        mc('K6', 'Tagesablauf verstehen', I.read, `${DAY} Was macht Mila nach der Arbeit?`, ['Sie kauft ein und kocht.', 'Sie telefoniert viel.', 'Sie geht joggen.'],
          ['What does Mila do after work?', 'Что Mila делает после работы?', 'Що Mila робить після роботи?', 'Mila işten sonra ne yapıyor?']),
        gap('K6', 'nach', I.prep, 'Ich arbeite von 8 bis 12 Uhr. ', ' der Mittagspause arbeite ich noch drei Stunden.', 'Nach', ['Vor', 'Bei'],
          ['I work from 8 to 12. After the lunch break I work another three hours.', 'Я работаю с 8 до 12. После обеденного перерыва я работаю ещё три часа.', 'Я працюю з 8 до 12. Після обідньої перерви я працюю ще три години.', '8’den 12’ye kadar çalışıyorum. Öğle arasından sonra üç saat daha çalışıyorum.'], 'vor / nach / bei', { c: 'p5_vornach' }),
        gap('K6', 'Verb auf Position 2', I.verb, 'Nach dem Frühstück ', ' ich zur Arbeit.', 'fahre', ['fährt', 'fahren'],
          ['After breakfast I go to work.', 'После завтрака я еду на работу.', 'Після сніданку я їду на роботу.', 'Kahvaltıdan sonra işe gidiyorum.'], 'fahren'),
        sb('K6', 'Tagesablauf', I.order, 'Vor dem Kurs / trinke / ich / einen Kaffee.',
          ['Before the course I drink a coffee.', 'Перед курсом я пью кофе.', 'Перед курсом я п’ю каву.', 'Kurstan önce bir kahve içiyorum.'],
          { alt: ['Ich trinke vor dem Kurs einen Kaffee.', 'Einen Kaffee trinke ich vor dem Kurs.'] }),
        sb('K6', 'Tagesablauf', I.order, 'Nach dem Abendessen / sehen / wir / fern.',
          ['After dinner we watch TV.', 'После ужина мы смотрим телевизор.', 'Після вечері ми дивимося телевізор.', 'Akşam yemeğinden sonra televizyon izliyoruz.'],
          { alt: ['Wir sehen nach dem Abendessen fern.'] }),
      ],
    },
    {
      title: 'In einer Woche',
      t: ['In a week', 'Через неделю', 'Через тиждень', 'Bir hafta sonra'],
      card: {
        id: 'p5_in',
        rule: 'in + Dativ = ein Zeitpunkt in der Zukunft (Wann?): in einem Monat, in einem Jahr, in einer Woche, in zwei Tagen, in drei Jahren. Der Techniker kommt in einer Stunde. = Jetzt ist es zehn Uhr, er kommt um elf. Vergleiche: vor einer Stunde = Vergangenheit, in einer Stunde = Zukunft.',
        examples: ['In einer Stunde ist der Techniker da.', 'In einem Monat habe ich Urlaub.', 'Wir kommen in zehn Minuten.'],
        highlight: null,
        t: [
          'in + dative = a point in the future (When?): in einem Monat, in einem Jahr, in einer Woche, in zwei Tagen, in drei Jahren. Der Techniker kommt in einer Stunde. = It is ten o’clock now, he is coming at eleven. Compare: vor einer Stunde = past (an hour ago), in einer Stunde = future (in an hour).',
          'in + Dativ = момент в будущем (Когда? «через …»): in einem Monat, in einem Jahr, in einer Woche, in zwei Tagen, in drei Jahren. Der Techniker kommt in einer Stunde. = Сейчас десять часов, он придёт в одиннадцать. Сравните: vor einer Stunde = прошлое (час назад), in einer Stunde = будущее (через час).',
          'in + Dativ = момент у майбутньому (Коли? «через …»): in einem Monat, in einem Jahr, in einer Woche, in zwei Tagen, in drei Jahren. Der Techniker kommt in einer Stunde. = Зараз десята година, він прийде об одинадцятій. Порівняйте: vor einer Stunde = минуле (годину тому), in einer Stunde = майбутнє (через годину).',
          'in + Dativ = gelecekte bir an (Ne zaman? “… sonra”): in einem Monat, in einem Jahr, in einer Woche, in zwei Tagen, in drei Jahren. Der Techniker kommt in einer Stunde. = Şimdi saat on, on birde geliyor. Karşılaştırın: vor einer Stunde = geçmiş (bir saat önce), in einer Stunde = gelecek (bir saat sonra).',
        ],
        hint: ['Zukunft → in. Vergangenheit → vor. Danach steht der Dativ: einem, einer.', 'Future → in. Past → vor. Then comes the dative: einem, einer.', 'Будущее → in. Прошлое → vor. Затем стоит Dativ: einem, einer.', 'Майбутнє → in. Минуле → vor. Потім стоїть Dativ: einem, einer.', 'Gelecek → in. Geçmiş → vor. Sonra Dativ gelir: einem, einer.'],
      },
      ex: [
        mc('G2', 'in + Dativ', I.choose, 'Es ist 14 Uhr. Der Techniker kommt um 15 Uhr. Er kommt … einer Stunde.', ['in', 'vor', 'seit'],
          ['It is 2 p.m. The technician is coming at 3 p.m. He is coming in an hour.', 'Сейчас 14 часов. Мастер придёт в 15 часов. Он придёт через час.', 'Зараз 14 година. Майстер прийде о 15 годині. Він прийде через годину.', 'Saat 14. Teknisyen saat 15’te geliyor. Bir saat sonra geliyor.']),
        mc('G2', 'in + Dativ', I.choose, 'Heute ist Montag. Am nächsten Montag habe ich frei. Ich habe … frei.', ['in einer Woche', 'vor einer Woche', 'seit einer Woche'],
          ['Today is Monday. Next Monday I have the day off. I have a day off in a week.', 'Сегодня понедельник. В следующий понедельник у меня выходной. У меня выходной через неделю.', 'Сьогодні понеділок. Наступного понеділка в мене вихідний. У мене вихідний через тиждень.', 'Bugün pazartesi. Gelecek pazartesi izinliyim. Bir hafta sonra izinliyim.']),
        mc('G2', 'in + Dativ', I.react, '„Wann ist mein Handy fertig?“', ['In zwei Tagen.', 'Vor zwei Tagen.', 'Zwei Tage alt.'],
          ['“When will my mobile be ready?”', '«Когда будет готов мой телефон?»', '«Коли буде готовий мій телефон?»', '“Telefonum ne zaman hazır olur?”']),
        gap('G2', 'Dativ', I.article, 'In ', ' Monat ziehen wir um.', 'einem', ['einen', 'einer'],
          ['In a month we are moving house.', 'Через месяц мы переезжаем.', 'Через місяць ми переїжджаємо.', 'Bir ay sonra taşınıyoruz.'], 'ein'),
        gap('G2', 'Dativ', I.article, 'Die Reparatur ist in ', ' Woche fertig.', 'einer', ['einem', 'eine'],
          ['The repair will be finished in a week.', 'Ремонт будет закончен через неделю.', 'Ремонт буде закінчено через тиждень.', 'Tamir bir hafta sonra bitiyor.'], 'ein'),
        gap('G2', 'in', I.prep, 'Der Bus kommt ', ' fünf Minuten. Wir müssen noch warten.', 'in', ['vor', 'seit'],
          ['The bus is coming in five minutes. We still have to wait.', 'Автобус придёт через пять минут. Нам ещё нужно подождать.', 'Автобус приїде через п’ять хвилин. Нам ще треба зачекати.', 'Otobüs beş dakika sonra geliyor. Biraz daha beklememiz gerekiyor.'], 'in / vor / seit'),
        gap('G2', 'vor', I.prep, 'Ich habe das Gerät ', ' einem Jahr gekauft. Jetzt ist es kaputt.', 'vor', ['in', 'für'],
          ['I bought the appliance a year ago. Now it is broken.', 'Я купил этот прибор год назад. Теперь он сломан.', 'Я купив цей прилад рік тому. Тепер він зламаний.', 'Cihazı bir yıl önce aldım. Şimdi bozuldu.'], 'in / vor / für'),
        gap('G2', 'Dativ Plural', I.form, 'In drei ', ' ist meine Ausbildung zu Ende.', 'Jahren', ['Jahre', 'Jahr'],
          ['In three years my training will be finished.', 'Через три года моё обучение закончится.', 'Через три роки моє навчання закінчиться.', 'Üç yıl sonra meslek eğitimim bitiyor.'], 'Jahr'),
        sb('G2', 'in + Dativ', I.order, 'Der Techniker / kommt / in einer Stunde.',
          ['The technician is coming in an hour.', 'Мастер придёт через час.', 'Майстер прийде через годину.', 'Teknisyen bir saat sonra geliyor.'],
          { alt: ['In einer Stunde kommt der Techniker.'] }),
      ],
    },
    {
      title: 'bis und ab',
      t: ['bis and ab (until and from)', 'bis и ab (до и с)', 'bis і ab (до і з)', 'bis ve ab (-e kadar ve -den itibaren)'],
      card: {
        id: 'p5_bisab',
        rule: 'bis und ab: bis = das Ende (Wie lange? Bis wann?): Das Geschäft ist bis 18 Uhr offen. Ich bleibe bis Montag. ab = der Anfang (Ab wann?): Ab morgen habe ich Urlaub. Sie können das Gerät ab 15 Uhr abholen. Zusammen: von Montag bis Freitag.',
        examples: ['Bis morgen ist das Gerät fertig.', 'Ab Montag arbeite ich wieder.', 'Der Kundenservice ist von 8 bis 20 Uhr da.'],
        highlight: null,
        t: [
          'bis and ab: bis = the end (How long? Until when?): Das Geschäft ist bis 18 Uhr offen. Ich bleibe bis Montag. ab = the start (From when?): Ab morgen habe ich Urlaub. Sie können das Gerät ab 15 Uhr abholen. Together: von Montag bis Freitag.',
          'bis и ab: bis = конец (Как долго? До какого времени?): Das Geschäft ist bis 18 Uhr offen. Ich bleibe bis Montag. ab = начало (С какого времени?): Ab morgen habe ich Urlaub. Sie können das Gerät ab 15 Uhr abholen. Вместе: von Montag bis Freitag.',
          'bis і ab: bis = кінець (Як довго? До якого часу?): Das Geschäft ist bis 18 Uhr offen. Ich bleibe bis Montag. ab = початок (З якого часу?): Ab morgen habe ich Urlaub. Sie können das Gerät ab 15 Uhr abholen. Разом: von Montag bis Freitag.',
          'bis ve ab: bis = bitiş (Ne kadar süre? Ne zamana kadar?): Das Geschäft ist bis 18 Uhr offen. Ich bleibe bis Montag. ab = başlangıç (Ne zamandan itibaren?): Ab morgen habe ich Urlaub. Sie können das Gerät ab 15 Uhr abholen. Birlikte: von Montag bis Freitag.',
        ],
        hint: ['Anfang → ab. Ende → bis.', 'Start → ab. End → bis.', 'Начало → ab. Конец → bis.', 'Початок → ab. Кінець → bis.', 'Başlangıç → ab. Bitiş → bis.'],
      },
      ex: [
        mc('G3', 'ab', I.choose, 'Das Büro öffnet um 9 Uhr. Sie können … 9 Uhr anrufen.', ['ab', 'bis', 'seit'],
          ['The office opens at 9. You can call from 9 o’clock.', 'Офис открывается в 9 часов. Вы можете звонить с 9 часов.', 'Офіс відчиняється о 9 годині. Ви можете телефонувати з 9 години.', 'Ofis saat 9’da açılıyor. Saat 9’dan itibaren arayabilirsiniz.']),
        mc('G3', 'bis', I.choose, 'Das Geschäft schließt um 20 Uhr. Es ist … 20 Uhr offen.', ['bis', 'ab', 'in'],
          ['The shop closes at 8 p.m. It is open until 8 p.m.', 'Магазин закрывается в 20 часов. Он открыт до 20 часов.', 'Магазин зачиняється о 20 годині. Він відчинений до 20 години.', 'Dükkân saat 20’de kapanıyor. Saat 20’ye kadar açık.']),
        mc('G3', 'bis', I.react, '„Bis wann können Sie das Gerät reparieren?“', ['Bis Freitag.', 'Seit einem Jahr.', 'In der Werkstatt.'],
          ['“By when can you repair the appliance?”', '«К какому сроку вы можете починить прибор?»', '«До якого терміну ви можете полагодити прилад?»', '“Cihazı ne zamana kadar tamir edebilirsiniz?”']),
        mc('G3', 'ab', I.react, '„Ab wann haben Sie Urlaub?“', ['Ab Montag.', 'Bis Montag.', 'Vor einem Jahr.'],
          ['“From when are you on holiday?”', '«С какого дня у вас отпуск?»', '«З якого дня у вас відпустка?»', '“Ne zamandan itibaren izindesiniz?”']),
        gap('G3', 'bis', I.prep, 'Ich warte ', ' morgen. Dann rufe ich noch einmal an.', 'bis', ['ab', 'in'],
          ['I will wait until tomorrow. Then I will call again.', 'Я подожду до завтра. Потом позвоню ещё раз.', 'Я почекаю до завтра. Потім зателефоную ще раз.', 'Yarına kadar bekliyorum. Sonra bir daha arıyorum.'], 'bis / ab'),
        gap('G3', 'ab', I.prep, '', ' heute rauche ich nicht mehr!', 'Ab', ['Bis', 'Vor'],
          ['From today I am not smoking any more!', 'С сегодняшнего дня я больше не курю!', 'Від сьогодні я більше не курю!', 'Bugünden itibaren artık sigara içmiyorum!'], 'bis / ab'),
        gap('G3', 'von … bis', I.prep, 'Der Kundenservice ist von 8 ', ' 18 Uhr erreichbar.', 'bis', ['ab', 'in'],
          ['Customer service can be reached from 8 a.m. to 6 p.m.', 'Сервисная служба доступна с 8 до 18 часов.', 'Сервісна служба доступна з 8 до 18 години.', 'Müşteri hizmetlerine 8’den 18’e kadar ulaşılabilir.'], 'bis / ab'),
        gap('G3', 'ab', I.prep, 'Sie können das Gerät ', ' 16 Uhr abholen. Vorher ist es noch nicht fertig.', 'ab', ['bis', 'vor'],
          ['You can collect the appliance from 4 p.m. It will not be ready before then.', 'Вы можете забрать прибор с 16 часов. Раньше он ещё не будет готов.', 'Ви можете забрати прилад із 16 години. Раніше він ще не буде готовий.', 'Cihazı saat 16’dan itibaren alabilirsiniz. Daha önce hazır olmaz.'], 'bis / ab'),
        sb('G3', 'ab', I.order, 'Ab Montag / habe / ich / Urlaub.',
          ['From Monday I am on holiday.', 'С понедельника у меня отпуск.', 'З понеділка в мене відпустка.', 'Pazartesiden itibaren izindeyim.'],
          { alt: ['Ich habe ab Montag Urlaub.', 'Urlaub habe ich ab Montag.'] }),
      ],
    },
    {
      title: 'Könnten Sie …? Würden Sie …?',
      t: ['Could you …? Would you …?', 'Не могли бы вы …?', 'Чи не могли б ви …?', '… yapabilir misiniz? … yapar mısınız?'],
      card: {
        id: 'p5_konj',
        rule: 'Höflich bitten mit könnten und würden: Könnten Sie mir bitte helfen? Würden Sie mir bitte das Geld zurückgeben? Mit du: Könntest du mir bitte helfen? Würdest du bitte das Fenster zumachen? Könnten oder würden steht auf Position 1, der Infinitiv steht am Ende. Das ist freundlicher als der Imperativ „Helfen Sie mir!“.',
        examples: ['Könnten Sie das bitte wiederholen?', 'Würden Sie bitte hier warten?', 'Könntest du bitte später anrufen?'],
        highlight: 'verb',
        t: [
          'Asking politely with könnten and würden: Könnten Sie mir bitte helfen? (Could you help me, please?) Würden Sie mir bitte das Geld zurückgeben? (Would you give me the money back, please?) With du: Könntest du mir bitte helfen? Würdest du bitte das Fenster zumachen? Könnten or würden is in position 1, the infinitive goes to the end. This is friendlier than the imperative “Helfen Sie mir!”.',
          'Вежливая просьба с könnten и würden: Könnten Sie mir bitte helfen? (Не могли бы вы мне помочь?) Würden Sie mir bitte das Geld zurückgeben? (Не вернёте ли вы мне деньги?) С du: Könntest du mir bitte helfen? Würdest du bitte das Fenster zumachen? Könnten или würden стоит на 1-м месте, инфинитив – в конце. Это вежливее, чем императив «Helfen Sie mir!».',
          'Ввічливе прохання з könnten і würden: Könnten Sie mir bitte helfen? (Чи не могли б ви мені допомогти?) Würden Sie mir bitte das Geld zurückgeben? (Чи не повернете ви мені гроші?) З du: Könntest du mir bitte helfen? Würdest du bitte das Fenster zumachen? Könnten або würden стоїть на 1-му місці, інфінітив – у кінці. Це ввічливіше, ніж імператив «Helfen Sie mir!».',
          'könnten ve würden ile kibarca rica etme: Könnten Sie mir bitte helfen? (Bana yardım edebilir misiniz lütfen?) Würden Sie mir bitte das Geld zurückgeben? (Parayı geri verir misiniz lütfen?) du ile: Könntest du mir bitte helfen? Würdest du bitte das Fenster zumachen? Könnten ya da würden 1. sırada, mastar sonda durur. Bu, “Helfen Sie mir!” emir kipinden daha kibardır.',
        ],
        hint: ['Sie → Könnten / Würden. du → Könntest / Würdest. Der Infinitiv steht am Ende.', 'Sie → Könnten / Würden. du → Könntest / Würdest. The infinitive goes to the end.', 'Sie → Könnten / Würden. du → Könntest / Würdest. Инфинитив стоит в конце.', 'Sie → Könnten / Würden. du → Könntest / Würdest. Інфінітив стоїть у кінці.', 'Sie → Könnten / Würden. du → Könntest / Würdest. Mastar sonda durur.'],
      },
      ex: [
        mc('G4', 'höfliche Bitte', I.choose, 'Welche Bitte ist sehr höflich?', ['Könnten Sie mir bitte helfen?', 'Helfen Sie mir!', 'Sie helfen mir jetzt.'],
          ['Which request is very polite?', 'Какая просьба очень вежливая?', 'Яке прохання дуже ввічливе?', 'Hangi rica çok kibar?']),
        mc('G4', 'würdest', I.choose, 'Du bittest deinen Freund Tom: „… du bitte das Fenster zumachen?“', ['Würdest', 'Würden', 'Würde'],
          ['You ask your friend Tom: “Would you close the window, please?”', 'Вы просите своего друга Tom: «Ты не закроешь окно, пожалуйста?»', 'Ви просите свого друга Tom: «Ти не зачиниш вікно, будь ласка?»', 'Arkadaşınız Tom’dan rica ediyorsunuz: “Pencereyi kapatır mısın lütfen?”']),
        mc('G4', 'Infinitiv am Ende', I.sentence, 'Eine Bitte an die Chefin.', ['Könnten Sie mir das bitte erklären?', 'Könnten Sie mir erklären das bitte?', 'Sie könnten erklären mir das bitte?'],
          ['A request to the boss.', 'Просьба к начальнице.', 'Прохання до начальниці.', 'Patrona bir rica.']),
        gap('G4', 'könnten', I.polite, '', ' Sie mir bitte helfen? Ich finde den Ausgang nicht.', ['Könnten', 'Würden'], ['Könntest', 'Kannst'],
          ['Could you help me, please? I cannot find the exit.', 'Не могли бы вы мне помочь? Я не могу найти выход.', 'Чи не могли б ви мені допомогти? Я не можу знайти вихід.', 'Bana yardım edebilir misiniz lütfen? Çıkışı bulamıyorum.'], 'können'),
        gap('G4', 'könntest', I.polite, '', ' du bitte leise sein? Ich telefoniere.', ['Könntest', 'Würdest'], ['Könnten', 'Würden'],
          ['Could you be quiet, please? I am on the phone.', 'Ты не мог бы потише? Я разговариваю по телефону.', 'Ти не міг би тихіше? Я розмовляю телефоном.', 'Sessiz olabilir misin lütfen? Telefonla konuşuyorum.'], 'können'),
        gap('G4', 'würden', I.polite, '', ' Sie bitte heute noch die Rechnung bezahlen?', ['Würden', 'Könnten'], ['Würdest', 'Werden'],
          ['Would you please pay the bill today?', 'Не оплатите ли вы счёт ещё сегодня?', 'Чи не оплатите ви рахунок іще сьогодні?', 'Faturayı bugün öder misiniz lütfen?'], 'könnten / würden'),
        gap('G4', 'würdest', I.polite, 'Tim, ', ' du mir bitte das Geld zurückgeben?', ['würdest', 'könntest'], ['würden', 'würde'],
          ['Tim, would you please give me the money back?', 'Tim, ты не вернёшь мне деньги, пожалуйста?', 'Tim, ти не повернеш мені гроші, будь ласка?', 'Tim, parayı bana geri verir misin lütfen?'], 'könntest / würdest'),
        gap('G4', 'Infinitiv am Ende', I.verb, 'Würden Sie mir bitte die Rechnung ', '?', 'schicken', ['schickt', 'geschickt'],
          ['Would you please send me the bill?', 'Не пришлёте ли вы мне счёт?', 'Чи не надішлете ви мені рахунок?', 'Faturayı bana gönderir misiniz lütfen?'],
          ['send', 'прислать', 'надіслати', 'göndermek']),
        sb('G4', 'könnten', I.question, 'Könnten / Sie / bitte / morgen / kommen?',
          ['Could you come tomorrow, please?', 'Не могли бы вы прийти завтра?', 'Чи не могли б ви прийти завтра?', 'Yarın gelebilir misiniz lütfen?'],
          { alt: ['Könnten Sie morgen bitte kommen?'] }),
        sb('G4', 'würdest', I.question, 'Würdest / du / bitte / die Tür / zumachen?',
          ['Would you close the door, please?', 'Ты не закроешь дверь, пожалуйста?', 'Ти не зачиниш двері, будь ласка?', 'Kapıyı kapatır mısın lütfen?'],
          { alt: ['Würdest du die Tür bitte zumachen?'] }),
      ],
    },
    {
      title: 'Bitten und reagieren',
      t: ['Asking and responding', 'Просьба и ответ', 'Прохання і відповідь', 'Rica etme ve karşılık verme'],
      card: {
        id: 'p5_bitten',
        rule: 'Um etwas bitten und reagieren: Bitte: Könnten Sie mir bitte helfen? Ich brauche dringend Hilfe. Würden Sie mir das bitte erklären? Ja: Natürlich. / Ja, gern. / Kein Problem. Nein: Nein, das geht leider gerade nicht. Ich muss erst telefonieren. Nach dem Dank: Nichts zu danken. / Gern geschehen.',
        examples: ['Könnten Sie mir bitte helfen? – Ja, gern.', 'Würdest du bitte kurz warten? – Natürlich.', 'Vielen Dank! – Nichts zu danken.'],
        highlight: null,
        t: [
          'Asking for something and responding: request: Könnten Sie mir bitte helfen? Ich brauche dringend Hilfe (I urgently need help). Würden Sie mir das bitte erklären? Yes: Natürlich (of course). / Ja, gern. / Kein Problem. No: Nein, das geht leider gerade nicht (sorry, that is not possible right now). Ich muss erst telefonieren. After thanks: Nichts zu danken (don’t mention it). / Gern geschehen.',
          'Как попросить и как ответить: просьба: Könnten Sie mir bitte helfen? Ich brauche dringend Hilfe (мне срочно нужна помощь). Würden Sie mir das bitte erklären? Да: Natürlich (конечно). / Ja, gern. / Kein Problem. Нет: Nein, das geht leider gerade nicht (к сожалению, сейчас не получится). Ich muss erst telefonieren. В ответ на благодарность: Nichts zu danken (не за что). / Gern geschehen.',
          'Як попросити і як відповісти: прохання: Könnten Sie mir bitte helfen? Ich brauche dringend Hilfe (мені терміново потрібна допомога). Würden Sie mir das bitte erklären? Так: Natürlich (звичайно). / Ja, gern. / Kein Problem. Ні: Nein, das geht leider gerade nicht (на жаль, зараз не вийде). Ich muss erst telefonieren. У відповідь на подяку: Nichts zu danken (нема за що). / Gern geschehen.',
          'Rica etme ve karşılık verme: Rica: Könnten Sie mir bitte helfen? Ich brauche dringend Hilfe (acil yardıma ihtiyacım var). Würden Sie mir das bitte erklären? Evet: Natürlich (tabii ki). / Ja, gern. / Kein Problem. Hayır: Nein, das geht leider gerade nicht (maalesef şu anda olmuyor). Ich muss erst telefonieren. Teşekkürden sonra: Nichts zu danken (bir şey değil). / Gern geschehen.',
        ],
        hint: ['Ja → Natürlich. / Ja, gern. Nein → Das geht leider gerade nicht. Nach Danke → Nichts zu danken.', 'Yes → Natürlich. / Ja, gern. No → Das geht leider gerade nicht. After thanks → Nichts zu danken.', 'Да → Natürlich. / Ja, gern. Нет → Das geht leider gerade nicht. После «спасибо» → Nichts zu danken.', 'Так → Natürlich. / Ja, gern. Ні → Das geht leider gerade nicht. Після «дякую» → Nichts zu danken.', 'Evet → Natürlich. / Ja, gern. Hayır → Das geht leider gerade nicht. Teşekkürden sonra → Nichts zu danken.'],
      },
      ex: [
        mc('K3', 'Bitte annehmen', I.react, '„Könnten Sie mir bitte helfen?“', ['Ja, gern. Was kann ich für Sie tun?', 'Nichts zu danken.', 'Ja, ich brauche Hilfe.'],
          ['“Could you help me, please?”', '«Не могли бы вы мне помочь?»', '«Чи не могли б ви мені допомогти?»', '“Bana yardım edebilir misiniz lütfen?”']),
        mc('K3', 'auf Dank reagieren', I.react, '„Vielen Dank für Ihre Hilfe!“', ['Nichts zu danken.', 'Ja, bitte helfen Sie mir.', 'Das geht leider nicht.'],
          ['“Thank you very much for your help!”', '«Большое спасибо за вашу помощь!»', '«Щиро дякую за вашу допомогу!»', '“Yardımınız için çok teşekkürler!”']),
        mc('K3', 'Bitte ablehnen', I.situation, 'Ein Kollege bittet dich um Hilfe. Du hast aber gerade keine Zeit.', ['Das geht leider gerade nicht. Ich muss erst telefonieren.', 'Natürlich, sofort!', 'Nichts zu danken.'],
          ['A colleague asks you for help. But you have no time right now.', 'Коллега просит вас о помощи. Но у вас сейчас нет времени.', 'Колега просить вас про допомогу. Але у вас зараз немає часу.', 'Bir iş arkadaşınız sizden yardım istiyor. Ama şu anda vaktiniz yok.']),
        mc('K3', 'höflich bitten', I.situation, 'Du verstehst die Rechnung nicht. Du bittest die Verkäuferin höflich:', ['Würden Sie mir das bitte erklären?', 'Erklären!', 'Du erklärst mir das.'],
          ['You do not understand the bill. You ask the shop assistant politely:', 'Вы не понимаете счёт. Вы вежливо просите продавщицу:', 'Ви не розумієте рахунок. Ви ввічливо просите продавчиню:', 'Faturayı anlamıyorsunuz. Satış elemanından kibarca rica ediyorsunuz:']),
        gap('K3', 'auf Dank reagieren', I.expression, 'Vielen Dank! – Nichts zu ', '.', 'danken', ['bitten', 'helfen'],
          ['Thank you very much! – Don’t mention it.', 'Большое спасибо! – Не за что.', 'Щиро дякую! – Нема за що.', 'Çok teşekkürler! – Bir şey değil.'],
          ['thank', 'благодарить', 'дякувати', 'teşekkür etmek']),
        gap('K3', 'Bitte annehmen', I.word, 'Würdest du mir bitte helfen? – ', ', kein Problem!', 'Natürlich', ['Leider', 'Nichts'],
          ['Would you help me, please? – Of course, no problem!', 'Ты не поможешь мне, пожалуйста? – Конечно, без проблем!', 'Ти не допоможеш мені, будь ласка? – Звичайно, без проблем!', 'Bana yardım eder misin lütfen? – Tabii ki, sorun değil!'],
          ['of course', 'конечно', 'звичайно', 'tabii ki']),
        gap('K3', 'um Hilfe bitten', I.word, 'Ich brauche dringend ', '. Könnten Sie bitte kommen?', 'Hilfe', ['Garantie', 'Rechnung'],
          ['I urgently need help. Could you come, please?', 'Мне срочно нужна помощь. Не могли бы вы прийти?', 'Мені терміново потрібна допомога. Чи не могли б ви прийти?', 'Acil yardıma ihtiyacım var. Gelebilir misiniz lütfen?'],
          ['help', 'помощь', 'допомога', 'yardım']),
        sb('K3', 'Bitte ablehnen', I.order, 'Das / geht / leider / gerade / nicht.',
          ['Unfortunately that is not possible right now.', 'К сожалению, сейчас это не получится.', 'На жаль, зараз це не вийде.', 'Maalesef şu anda olmuyor.'],
          { alt: ['Das geht gerade leider nicht.', 'Leider geht das gerade nicht.'] }),
      ],
    },
    {
      title: 'Beim Kundenservice',
      t: ['Calling customer service', 'Звонок в сервисную службу', 'Дзвінок до сервісної служби', 'Müşteri hizmetlerini arama'],
      card: {
        id: 'p5_anruf',
        rule: 'Beim Kundenservice anrufen: Guten Tag, mein Name ist … Könnte ich bitte den Kundenservice sprechen? – Ja, hier sind Sie richtig. Was kann ich für Sie tun? Problem: Mein Herd funktioniert nicht. Die Waschmaschine ist kaputt. Der Drucker ist schon wieder kaputt. – Was für ein Modell ist es? – Ein Kochfix 300.',
        examples: ['Könnte ich bitte den Kundenservice sprechen?', 'Was kann ich für Sie tun?', 'Meine Waschmaschine funktioniert nicht.'],
        highlight: null,
        t: [
          'Calling customer service: Guten Tag, mein Name ist … Könnte ich bitte den Kundenservice sprechen? (Could I speak to customer service, please?) – Ja, hier sind Sie richtig (you have come to the right place). Was kann ich für Sie tun? (What can I do for you?) Problem: Mein Herd funktioniert nicht. Die Waschmaschine ist kaputt. Der Drucker ist schon wieder kaputt (broken again). – Was für ein Modell ist es? (What model is it?) – Ein Kochfix 300.',
          'Звонок в сервисную службу: Guten Tag, mein Name ist … Könnte ich bitte den Kundenservice sprechen? (Можно поговорить с сервисной службой?) – Ja, hier sind Sie richtig (вы попали куда нужно). Was kann ich für Sie tun? (Чем могу помочь?) Проблема: Mein Herd funktioniert nicht. Die Waschmaschine ist kaputt. Der Drucker ist schon wieder kaputt (снова сломан). – Was für ein Modell ist es? (Какая это модель?) – Ein Kochfix 300.',
          'Дзвінок до сервісної служби: Guten Tag, mein Name ist … Könnte ich bitte den Kundenservice sprechen? (Чи можна поговорити із сервісною службою?) – Ja, hier sind Sie richtig (ви потрапили куди треба). Was kann ich für Sie tun? (Чим можу допомогти?) Проблема: Mein Herd funktioniert nicht. Die Waschmaschine ist kaputt. Der Drucker ist schon wieder kaputt (знову зламаний). – Was für ein Modell ist es? (Яка це модель?) – Ein Kochfix 300.',
          'Müşteri hizmetlerini arama: Guten Tag, mein Name ist … Könnte ich bitte den Kundenservice sprechen? (Müşteri hizmetleriyle görüşebilir miyim lütfen?) – Ja, hier sind Sie richtig (doğru yeri aradınız). Was kann ich für Sie tun? (Sizin için ne yapabilirim?) Sorun: Mein Herd funktioniert nicht. Die Waschmaschine ist kaputt. Der Drucker ist schon wieder kaputt (yine bozuk). – Was für ein Modell ist es? (Hangi model?) – Ein Kochfix 300.',
        ],
        hint: ['Erst der Name, dann das Problem: Was ist kaputt? Was funktioniert nicht?', 'First your name, then the problem: what is broken? what does not work?', 'Сначала имя, потом проблема: что сломалось? что не работает?', 'Спочатку ім’я, потім проблема: що зламалося? що не працює?', 'Önce isim, sonra sorun: Ne bozuk? Ne çalışmıyor?'],
      },
      ex: [
        mc('K1', 'Anruf beginnen', I.situation, 'Deine Waschmaschine ist kaputt. Du rufst bei der Firma an. Wie beginnst du?', ['Guten Tag, mein Name ist Aksoy. Könnte ich bitte den Kundenservice sprechen?', 'Hallo, die Maschine ist blöd.', 'Tschüs, ich brauche Hilfe.'],
          ['Your washing machine is broken. You call the company. How do you begin?', 'Ваша стиральная машина сломалась. Вы звоните в фирму. Как вы начнёте?', 'Ваша пральна машина зламалася. Ви телефонуєте до фірми. Як ви почнете?', 'Çamaşır makineniz bozuldu. Firmayı arıyorsunuz. Nasıl başlarsınız?']),
        mc('K1', 'Problem beschreiben', I.react, '„Kundenservice Elektro Brandt. Was kann ich für Sie tun?“', ['Mein Kühlschrank funktioniert nicht.', 'Nichts zu danken.', 'Ich kann viel für Sie tun.'],
          ['“Elektro Brandt customer service. What can I do for you?”', '«Сервисная служба Elektro Brandt. Чем могу помочь?»', '«Сервісна служба Elektro Brandt. Чим можу допомогти?»', '“Elektro Brandt müşteri hizmetleri. Sizin için ne yapabilirim?”']),
        mc('K1', 'Modell nennen', I.react, '„Was für ein Modell ist es?“', ['Ein Frostika 200.', 'Seit gestern.', 'In der Küche.'],
          ['“What model is it?”', '«Какая это модель?»', '«Яка це модель?»', '“Hangi model?”']),
        mc('K1', 'richtig verbunden', I.react, '„Bin ich hier richtig beim Kundenservice?“', ['Ja, hier sind Sie richtig.', 'Ja, ich bin richtig.', 'Nein, ich bin kaputt.'],
          ['“Is this the right number for customer service?”', '«Я попал в сервисную службу?»', '«Я потрапив до сервісної служби?»', '“Müşteri hizmetleri için doğru yeri mi aradım?”']),
        gap('K1', 'schon wieder', I.word, 'Mein Herd ist schon ', ' kaputt. Das ist das zweite Mal!', 'wieder', ['immer', 'nie'],
          ['My cooker is broken again. That is the second time!', 'Моя плита снова сломалась. Это уже второй раз!', 'Моя плита знову зламалася. Це вже вдруге!', 'Ocağım yine bozuldu. Bu ikinci kez!'],
          ['again', 'снова', 'знову', 'yine']),
        gap('K1', 'Problem beschreiben', I.verb, 'Der Fernseher ', ' nicht mehr. Das Bild ist schwarz.', 'funktioniert', ['funktionieren', 'funktionierst'],
          ['The TV does not work any more. The screen is black.', 'Телевизор больше не работает. Экран чёрный.', 'Телевізор більше не працює. Екран чорний.', 'Televizyon artık çalışmıyor. Ekran siyah.'], 'funktionieren'),
        gap('K1', 'Was kann ich für Sie tun?', I.word, 'Guten Tag! Was kann ich für Sie ', '?', 'tun', ['sein', 'haben'],
          ['Good morning! What can I do for you?', 'Добрый день! Чем могу вам помочь?', 'Добрий день! Чим можу вам допомогти?', 'İyi günler! Sizin için ne yapabilirim?'],
          ['do', 'сделать', 'зробити', 'yapmak']),
        sb('K1', 'Was kann ich für Sie tun?', I.question, 'Was / kann / ich / für Sie / tun?',
          ['What can I do for you?', 'Что я могу для вас сделать?', 'Що я можу для вас зробити?', 'Sizin için ne yapabilirim?']),
      ],
    },
    {
      title: 'Reparatur und Garantie',
      t: ['Repair and warranty', 'Ремонт и гарантия', 'Ремонт і гарантія', 'Tamir ve garanti'],
      card: {
        id: 'p5_reparatur',
        rule: 'Reparatur, Garantie, Termin: Haben Sie noch Garantie? – Ja, ich habe noch sechs Monate Garantie. Bringen Sie das Gerät bitte vorbei. Wann kann der Techniker kommen? – In einer Stunde ist er bei Ihnen. Wie lange brauchen Sie für die Reparatur? – Tut mir leid, das kann ich noch nicht sagen. Bis wann können Sie das Gerät reparieren? – Bis morgen. Sie können es ab 15 Uhr abholen.',
        examples: ['Ich habe noch ein Jahr Garantie.', 'Der Techniker kommt morgen ab acht Uhr.', 'Sie können das Gerät am Freitag abholen.'],
        highlight: null,
        t: [
          'Repair, warranty, appointment: Haben Sie noch Garantie? – Ja, ich habe noch sechs Monate Garantie. Bringen Sie das Gerät bitte vorbei (please bring the appliance in). Wann kann der Techniker kommen? – In einer Stunde ist er bei Ihnen (he will be with you in an hour). Wie lange brauchen Sie für die Reparatur? – Tut mir leid, das kann ich noch nicht sagen. Bis wann können Sie das Gerät reparieren? – Bis morgen. Sie können es ab 15 Uhr abholen (collect it from 3 p.m.).',
          'Ремонт, гарантия, время: Haben Sie noch Garantie? – Ja, ich habe noch sechs Monate Garantie. Bringen Sie das Gerät bitte vorbei (привезите прибор, пожалуйста). Wann kann der Techniker kommen? – In einer Stunde ist er bei Ihnen (через час он будет у вас). Wie lange brauchen Sie für die Reparatur? – Tut mir leid, das kann ich noch nicht sagen. Bis wann können Sie das Gerät reparieren? – Bis morgen. Sie können es ab 15 Uhr abholen (забрать с 15 часов).',
          'Ремонт, гарантія, час: Haben Sie noch Garantie? – Ja, ich habe noch sechs Monate Garantie. Bringen Sie das Gerät bitte vorbei (привезіть прилад, будь ласка). Wann kann der Techniker kommen? – In einer Stunde ist er bei Ihnen (за годину він буде у вас). Wie lange brauchen Sie für die Reparatur? – Tut mir leid, das kann ich noch nicht sagen. Bis wann können Sie das Gerät reparieren? – Bis morgen. Sie können es ab 15 Uhr abholen (забрати з 15 години).',
          'Tamir, garanti, randevu: Haben Sie noch Garantie? – Ja, ich habe noch sechs Monate Garantie. Bringen Sie das Gerät bitte vorbei (cihazı lütfen getirin). Wann kann der Techniker kommen? – In einer Stunde ist er bei Ihnen (bir saat sonra yanınızda olur). Wie lange brauchen Sie für die Reparatur? – Tut mir leid, das kann ich noch nicht sagen. Bis wann können Sie das Gerät reparieren? – Bis morgen. Sie können es ab 15 Uhr abholen (saat 15’ten itibaren alabilirsiniz).',
        ],
        hint: ['Wann? → Termin. Wie lange? → Dauer. Bis wann? → Ende. Garantie → die Reparatur kostet nichts.', 'Wann? → appointment. Wie lange? → duration. Bis wann? → deadline. Garantie → the repair is free.', 'Wann? → время визита. Wie lange? → длительность. Bis wann? → срок. Garantie → ремонт бесплатный.', 'Wann? → час візиту. Wie lange? → тривалість. Bis wann? → термін. Garantie → ремонт безкоштовний.', 'Wann? → randevu. Wie lange? → süre. Bis wann? → bitiş. Garantie → tamir ücretsiz.'],
      },
      ex: [
        mc('K2', 'Termin', I.react, '„Wann kann der Techniker kommen?“', ['Morgen zwischen 8 und 12 Uhr.', 'Bis morgen fertig.', 'Ein Jahr Garantie.'],
          ['“When can the technician come?”', '«Когда может прийти мастер?»', '«Коли може прийти майстер?»', '“Teknisyen ne zaman gelebilir?”']),
        mc('K2', 'Dauer', I.react, '„Wie lange brauchen Sie für die Reparatur?“', ['Tut mir leid, das kann ich noch nicht sagen.', 'Ab Montag.', 'Ja, gern.'],
          ['“How long will the repair take you?”', '«Сколько времени вам нужно на ремонт?»', '«Скільки часу вам потрібно на ремонт?»', '“Tamir ne kadar sürer?”']),
        mc('K2', 'Garantie', I.react, '„Haben Sie noch Garantie?“', ['Ja, noch acht Monate.', 'Ja, das Gerät ist kaputt.', 'Nein, der Techniker kommt.'],
          ['“Do you still have a warranty?”', '«У вас ещё есть гарантия?»', '«У вас іще є гарантія?»', '“Garantiniz hâlâ var mı?”']),
        mc('K2', 'Gerät vorbeibringen', I.choose, 'Der Mitarbeiter sagt: „Bringen Sie das Gerät bitte vorbei.“ Was machst du?', ['Ich bringe das Gerät zum Geschäft.', 'Ich warte zu Hause.', 'Ich kaufe ein neues Gerät.'],
          ['The employee says: “Please bring the appliance in.” What do you do?', 'Сотрудник говорит: «Привезите, пожалуйста, прибор». Что вы делаете?', 'Співробітник каже: «Привезіть, будь ласка, прилад». Що ви робите?', 'Çalışan diyor ki: “Cihazı lütfen getirin.” Ne yaparsınız?']),
        gap('K2', 'Garantie', I.word, 'Das Gerät ist erst vier Monate alt. Ich habe noch ', '.', 'Garantie', ['Reparatur', 'Nachricht'],
          ['The appliance is only four months old. I still have a warranty.', 'Прибору всего четыре месяца. У меня ещё есть гарантия.', 'Приладу лише чотири місяці. У мене ще є гарантія.', 'Cihaz daha dört aylık. Hâlâ garantim var.'],
          ['warranty', 'гарантия', 'гарантія', 'garanti']),
        gap('K2', 'abholen', I.verb, 'Das Handy ist fertig. Sie können es ab 15 Uhr ', '.', 'abholen', ['abgeholt', 'holen ab'],
          ['The mobile is ready. You can collect it from 3 p.m.', 'Телефон готов. Вы можете забрать его с 15 часов.', 'Телефон готовий. Ви можете забрати його з 15 години.', 'Telefon hazır. Saat 15’ten itibaren alabilirsiniz.'],
          ['collect, pick up', 'забрать', 'забрати', 'teslim almak']),
        gap('K2', 'Bis wann?', I.prep, '', ' wann können Sie den Drucker reparieren? – Bis Donnerstag.', 'Bis', ['Ab', 'Seit'],
          ['By when can you repair the printer? – By Thursday.', 'К какому сроку вы можете починить принтер? – К четвергу.', 'До якого терміну ви можете полагодити принтер? – До четверга.', 'Yazıcıyı ne zamana kadar tamir edebilirsiniz? – Perşembeye kadar.'], 'bis / ab', { c: 'p5_bisab' }),
        sb('K2', 'Termin', I.question, 'Wann / kann / der Techniker / kommen?',
          ['When can the technician come?', 'Когда может прийти мастер?', 'Коли може прийти майстер?', 'Teknisyen ne zaman gelebilir?']),
      ],
    },
    {
      title: 'Die Mailbox',
      t: ['Voicemail', 'Автоответчик', 'Автовідповідач', 'Telesekreter'],
      card: {
        id: 'p5_mailbox',
        rule: 'Die Mailbox: Ansage hören: Hier ist der Anschluss von Familie Lindner. / Sie sind verbunden mit der Firma Nordweg. Im Moment sind wir nicht erreichbar. Bitte hinterlassen Sie eine Nachricht nach dem Ton. Wir rufen zurück. Nachricht sprechen: Hier spricht Dilara Aksoy. Bitte rufen Sie zurück unter 0561 778812. Vielen Dank und auf Wiederhören!',
        examples: ['Im Moment bin ich nicht erreichbar.', 'Bitte sprechen Sie Ihren Namen und Ihre Telefonnummer nach dem Ton.', 'Hier ist Emre Demir. Bitte rufen Sie zurück.'],
        highlight: null,
        t: [
          'Voicemail: hearing the announcement: Hier ist der Anschluss von Familie Lindner (this is the Lindner family’s line). / Sie sind verbunden mit der Firma Nordweg (you have reached Nordweg). Im Moment sind wir nicht erreichbar (we are not available at the moment). Bitte hinterlassen Sie eine Nachricht nach dem Ton (please leave a message after the tone). Wir rufen zurück (we will call back). Leaving a message: Hier spricht Dilara Aksoy. Bitte rufen Sie zurück unter 0561 778812. Vielen Dank und auf Wiederhören!',
          'Автоответчик: что говорит запись: Hier ist der Anschluss von Familie Lindner (это номер семьи Lindner). / Sie sind verbunden mit der Firma Nordweg (вы позвонили в фирму Nordweg). Im Moment sind wir nicht erreichbar (сейчас мы не можем ответить). Bitte hinterlassen Sie eine Nachricht nach dem Ton (оставьте сообщение после сигнала). Wir rufen zurück (мы перезвоним). Как оставить сообщение: Hier spricht Dilara Aksoy. Bitte rufen Sie zurück unter 0561 778812. Vielen Dank und auf Wiederhören!',
          'Автовідповідач: що каже запис: Hier ist der Anschluss von Familie Lindner (це номер родини Lindner). / Sie sind verbunden mit der Firma Nordweg (ви зателефонували до фірми Nordweg). Im Moment sind wir nicht erreichbar (зараз ми не можемо відповісти). Bitte hinterlassen Sie eine Nachricht nach dem Ton (залиште повідомлення після сигналу). Wir rufen zurück (ми передзвонимо). Як залишити повідомлення: Hier spricht Dilara Aksoy. Bitte rufen Sie zurück unter 0561 778812. Vielen Dank und auf Wiederhören!',
          'Telesekreter: Anonsu dinleme: Hier ist der Anschluss von Familie Lindner (burası Lindner ailesinin hattı). / Sie sind verbunden mit der Firma Nordweg (Nordweg firmasına ulaştınız). Im Moment sind wir nicht erreichbar (şu anda cevap veremiyoruz). Bitte hinterlassen Sie eine Nachricht nach dem Ton (lütfen sinyal sesinden sonra mesaj bırakın). Wir rufen zurück (geri arayacağız). Mesaj bırakma: Hier spricht Dilara Aksoy. Bitte rufen Sie zurück unter 0561 778812. Vielen Dank und auf Wiederhören!',
        ],
        hint: ['Ansage = die Mailbox spricht. Achte auf: Wer? Erreichbar? Was soll ich tun?', 'Announcement = the voicemail speaks. Listen for: who? available? what should I do?', 'Запись = говорит автоответчик. Обратите внимание: кто? доступен ли? что мне делать?', 'Запис = говорить автовідповідач. Зверніть увагу: хто? чи доступний? що мені робити?', 'Anons = telesekreter konuşur. Şunlara dikkat edin: Kim? Ulaşılabilir mi? Ne yapmalıyım?'],
        hints: {
          leave: ['Auf die Mailbox sprechen: Hier ist … Bitte rufen Sie zurück unter … Auf Wiederhören!', 'Leaving a message: Hier ist … Bitte rufen Sie zurück unter … Auf Wiederhören!', 'Как оставить сообщение: Hier ist … Bitte rufen Sie zurück unter … Auf Wiederhören!', 'Як залишити повідомлення: Hier ist … Bitte rufen Sie zurück unter … Auf Wiederhören!', 'Mesaj bırakma: Hier ist … Bitte rufen Sie zurück unter … Auf Wiederhören!'],
        },
      },
      ex: [
        mc('K4', 'Ansage verstehen', I.read, `${ANNOUNCEMENT} Was ist richtig?`, ['Jetzt kann niemand ans Telefon gehen.', 'Die Praxis ruft zurück.', 'Die Praxis ist am Samstag offen.'],
          ['What is correct?', 'Что правильно?', 'Що правильно?', 'Hangisi doğru?']),
        mc('K4', 'Ansage verstehen', I.read, `${ANNOUNCEMENT} Was soll man machen?`, ['Später noch einmal anrufen.', 'Eine Nachricht sprechen.', 'Eine E-Mail schreiben.'],
          ['What should you do?', 'Что нужно сделать?', 'Що треба зробити?', 'Ne yapmak gerekiyor?']),
        mc('K4', 'nicht erreichbar', I.choose, 'Was bedeutet „Im Moment bin ich nicht erreichbar“?', ['Ich kann jetzt nicht telefonieren.', 'Ich habe kein Telefon.', 'Ich rufe nie zurück.'],
          ['What does “Im Moment bin ich nicht erreichbar” mean?', 'Что означает «Im Moment bin ich nicht erreichbar»?', 'Що означає «Im Moment bin ich nicht erreichbar»?', '“Im Moment bin ich nicht erreichbar” ne anlama gelir?']),
        mc('K5', 'Nachricht beginnen', I.situation, 'Du rufst eine Firma an. Die Mailbox geht an. Wie beginnst du deine Nachricht?', ['Guten Tag, hier spricht Karim Haddad.', 'Hallo, ist da jemand?', 'Auf Wiederhören!'],
          ['You call a company. The voicemail comes on. How do you begin your message?', 'Вы звоните в фирму. Включается автоответчик. Как вы начнёте сообщение?', 'Ви телефонуєте до фірми. Вмикається автовідповідач. Як ви почнете повідомлення?', 'Bir firmayı arıyorsunuz. Telesekreter devreye giriyor. Mesajınıza nasıl başlarsınız?'], { h: 'leave' }),
        mc('K5', 'Nachricht beenden', I.choose, 'Was sagst du am Ende von deiner Nachricht auf der Mailbox?', ['Vielen Dank und auf Wiederhören!', 'Guten Tag, hier ist Rojas.', 'Was kann ich für Sie tun?'],
          ['What do you say at the end of your voicemail message?', 'Что вы скажете в конце сообщения на автоответчике?', 'Що ви скажете наприкінці повідомлення на автовідповідачі?', 'Telesekreter mesajınızın sonunda ne dersiniz?'], { h: 'leave' }),
        gap('K4', 'nach dem Ton', I.word, 'Bitte hinterlassen Sie eine Nachricht nach dem ', '.', 'Ton', ['Tag', 'Telefon'],
          ['Please leave a message after the tone.', 'Пожалуйста, оставьте сообщение после сигнала.', 'Будь ласка, залиште повідомлення після сигналу.', 'Lütfen sinyal sesinden sonra mesaj bırakın.'],
          ['tone, beep', 'сигнал', 'сигнал', 'sinyal sesi']),
        gap('K4', 'zurückrufen', I.verb, 'Im Moment sind wir nicht da. Wir ', ' zurück.', 'rufen', ['ruft', 'rufe'],
          ['We are not here at the moment. We will call back.', 'Сейчас нас нет. Мы перезвоним.', 'Зараз нас немає. Ми передзвонимо.', 'Şu anda burada değiliz. Geri arayacağız.'], 'zurückrufen'),
        gap('K5', 'Rückruf', I.word, 'Hier ist Olena Bondar. Bitte rufen Sie zurück ', ' 0171 2233445.', 'unter', ['über', 'in'],
          ['This is Olena Bondar. Please call back on 0171 2233445.', 'Это Olena Bondar. Пожалуйста, перезвоните по номеру 0171 2233445.', 'Це Olena Bondar. Будь ласка, передзвоніть за номером 0171 2233445.', 'Ben Olena Bondar. Lütfen 0171 2233445 numaralı telefondan geri arayın.'], 'unter / über / in', { h: 'leave' }),
        gap('K5', 'Telefonnummer', I.word, 'Bitte rufen Sie zurück. Meine ', ' ist 030 5550142.', 'Nummer', ['Nachricht', 'Mailbox'],
          ['Please call back. My number is 030 5550142.', 'Пожалуйста, перезвоните. Мой номер 030 5550142.', 'Будь ласка, передзвоніть. Мій номер 030 5550142.', 'Lütfen geri arayın. Numaram 030 5550142.'],
          ['number', 'номер', 'номер', 'numara'], { h: 'leave' }),
        sb('K5', 'Rückruf', I.request, 'Bitte / rufen / Sie / zurück!',
          ['Please call back!', 'Пожалуйста, перезвоните!', 'Будь ласка, передзвоніть!', 'Lütfen geri arayın!'],
          { alt: ['Rufen Sie bitte zurück!'], h: 'leave' }),
      ],
    },
    {
      title: 'Anzeigen und Anleitungen',
      t: ['Ads and instructions', 'Объявления и инструкции', 'Оголошення та інструкції', 'İlanlar ve kullanım kılavuzları'],
      card: {
        id: 'p5_anleitung',
        rule: 'Service-Anzeigen und Gebrauchsanweisungen verstehen: In Anzeigen: Reparatur aller Marken = die Firma repariert alle Geräte. Notdienst = Hilfe auch in der Nacht und am Wochenende. kostenlos = es kostet nichts. In Anleitungen stehen Schritte: 1. Stecker einstecken. 2. Gerät einschalten. 3. Taste drücken. Zum Schluss: Gerät ausschalten.',
        examples: ['Reparatur-Service: Wir kommen in zwei Stunden.', 'Drücken Sie die grüne Taste.', 'Schalten Sie das Gerät nach dem Waschen aus.'],
        highlight: null,
        t: [
          'Understanding service ads and instructions: in ads: Reparatur aller Marken = the company repairs all brands. Notdienst = help at night and at the weekend too. kostenlos = free of charge. Instructions list steps: 1. Stecker einstecken (plug in). 2. Gerät einschalten (switch on). 3. Taste drücken (press the button). Finally: Gerät ausschalten (switch off).',
          'Как понимать сервисные объявления и инструкции: в объявлениях: Reparatur aller Marken = фирма ремонтирует технику всех марок. Notdienst = помощь также ночью и в выходные. kostenlos = бесплатно. В инструкциях есть шаги: 1. Stecker einstecken (вставить вилку в розетку). 2. Gerät einschalten (включить прибор). 3. Taste drücken (нажать кнопку). В конце: Gerät ausschalten (выключить прибор).',
          'Як розуміти сервісні оголошення та інструкції: в оголошеннях: Reparatur aller Marken = фірма ремонтує техніку всіх марок. Notdienst = допомога також уночі та у вихідні. kostenlos = безкоштовно. В інструкціях є кроки: 1. Stecker einstecken (вставити вилку в розетку). 2. Gerät einschalten (увімкнути прилад). 3. Taste drücken (натиснути кнопку). Наприкінці: Gerät ausschalten (вимкнути прилад).',
          'Servis ilanlarını ve kullanım kılavuzlarını anlama: İlanlarda: Reparatur aller Marken = firma bütün markaları tamir eder. Notdienst = gece ve hafta sonu da yardım. kostenlos = ücretsiz. Kılavuzlarda adımlar yazar: 1. Stecker einstecken (fişi takmak). 2. Gerät einschalten (cihazı açmak). 3. Taste drücken (tuşa basmak). En sonunda: Gerät ausschalten (cihazı kapatmak).',
        ],
        hint: ['In Anleitungen: Schritt 1, Schritt 2 … Lies die Verben: einschalten, drücken, ausschalten.', 'In instructions: step 1, step 2 … Read the verbs: einschalten, drücken, ausschalten.', 'В инструкциях: шаг 1, шаг 2 … Читайте глаголы: einschalten, drücken, ausschalten.', 'В інструкціях: крок 1, крок 2 … Читайте дієслова: einschalten, drücken, ausschalten.', 'Kılavuzlarda: 1. adım, 2. adım … Fiilleri okuyun: einschalten, drücken, ausschalten.'],
      },
      ex: [
        mc('Z1', 'Service-Anzeige', I.read, `${AD} Was repariert die Firma nicht?`, ['Handys', 'Waschmaschinen', 'Kühlschränke'],
          ['What does the company not repair?', 'Что фирма не ремонтирует?', 'Що фірма не ремонтує?', 'Firma neyi tamir etmiyor?']),
        mc('Z1', 'Service-Anzeige', I.read, `${AD} Dein Herd ist am Sonntag kaputt. Was ist richtig?`, ['Der Service kommt auch am Wochenende.', 'Der Service kommt nur von Montag bis Freitag.', 'Die Anfahrt kostet 24 Euro.'],
          ['Your cooker breaks down on Sunday. What is correct?', 'Ваша плита сломалась в воскресенье. Что правильно?', 'Ваша плита зламалася в неділю. Що правильно?', 'Ocağınız pazar günü bozuldu. Hangisi doğru?']),
        mc('Z1', 'Gebrauchsanweisung', I.read, `${MANUAL} Was macht man zuerst?`, ['Den Stecker einstecken.', 'Die Taste START drücken.', 'Das Gerät ausschalten.'],
          ['What do you do first?', 'Что нужно сделать сначала?', 'Що треба зробити спочатку?', 'Önce ne yapılır?']),
        mc('Z1', 'Gebrauchsanweisung', I.read, `${MANUAL} Was macht man zum Schluss?`, ['Das Gerät ausschalten.', 'Wasser einfüllen.', 'Kaffee kaufen.'],
          ['What do you do at the end?', 'Что нужно сделать в конце?', 'Що треба зробити наприкінці?', 'En sonunda ne yapılır?']),
        gap('Z1', 'kostenlos', I.word, 'Die Anfahrt kostet nichts. Sie ist ', '.', 'kostenlos', ['teuer', 'kaputt'],
          ['The call-out costs nothing. It is free of charge.', 'Выезд ничего не стоит. Он бесплатный.', 'Виїзд нічого не коштує. Він безкоштовний.', 'Yol ücreti alınmıyor. Ücretsiz.'],
          ['free of charge', 'бесплатно', 'безкоштовно', 'ücretsiz']),
        gap('Z1', 'Taste drücken', I.imperative, '', ' Sie die grüne Taste. Dann startet das Gerät.', 'Drücken', ['Drückt', 'Drück'],
          ['Press the green button. Then the appliance starts.', 'Нажмите зелёную кнопку. Тогда прибор запустится.', 'Натисніть зелену кнопку. Тоді прилад запуститься.', 'Yeşil tuşa basın. O zaman cihaz çalışmaya başlar.'],
          ['press', 'нажимать', 'натискати', 'basmak']),
      ],
    },
  ],
}

export default path
