import { I, gap, mc, sb } from '../shared.mjs'

const LIKE = ['to please (gefallen = to like)', 'нравиться', 'подобатися', 'hoşuna gitmek']
const SIGN = 'Wegweiser: „2. OG: Sportkleidung, Schuhe · 1. OG: Damenkleidung, Kinderkleidung · EG: Herrenkleidung, Taschen, Information · UG: Lebensmittel“'

/** A1.2 · Pfad 6 · Neue Kleider – Lektionen. Wiederholung und Test: p6-check.mjs */
const path = {
  n: 6,
  slug: 'neue-kleider',
  title: 'Neue Kleider',
  t: ['New clothes', 'Новая одежда', 'Новий одяг', 'Yeni giysiler'],
  objectives: {
    G1: 'Demonstrativpronomen der, das, die im Nominativ und den, das, die im Akkusativ: Der ist schön. Den finde ich super.',
    G2: 'Frageartikel welcher, welches, welche und Demonstrativpronomen dieser, dieses, diese – im Akkusativ welchen und diesen.',
    G3: 'Personalpronomen im Dativ: mir, dir, ihm, ihr, uns, euch, ihnen, Ihnen.',
    G4: 'Verben mit Dativ: gefallen, gehören, passen, stehen, schmecken.',
    G5: 'Komparation von gut, gern und viel: besser – am besten, lieber – am liebsten, mehr – am meisten.',
    G6: 'Konjugation von mögen: ich mag, du magst, er mag, wir mögen, ihr mögt, sie mögen.',
    K1: 'Etwas bewerten: schön, super, toll, günstig, nicht schlecht, hässlich, langweilig, zu teuer.',
    K2: 'Über Vorlieben sprechen und zustimmen oder widersprechen: Mir auch. Mir nicht. Mir schon. Mir auch nicht.',
    K3: 'Im Kaufhaus an der Information fragen: Ich suche … Wo finde ich …? Wo gibt es …?',
    K4: 'Kleidung kaufen: nach Größe, Farbe, Preis und Kasse fragen.',
    Z1: 'Kann-Ziele: Wegweiser und Angebote im Kaufhaus verstehen.',
    W1: 'Wortschatz: Kleidungsstücke und Gegenstände.',
  },
  nodes: [
    {
      title: 'Kleidung',
      t: ['Clothes', 'Одежда', 'Одяг', 'Giysiler'],
      card: {
        id: 'p6_kleidung',
        rule: 'Kleidung: der Mantel, der Pullover, der Rock, der Gürtel, der Schal, das Hemd, das Kleid, das T-Shirt, die Jacke, die Bluse, die Hose, die Mütze. Im Plural: die Schuhe, die Stiefel. Gegenstände: der Schirm, der Koffer, die Tasche, die Brille, die Uhr. Achtung: die Hose und die Brille sind im Deutschen Singular.',
        examples: ['Im Winter trage ich einen Mantel und einen Schal.', 'Die Hose ist zu lang.', 'Bei Regen brauche ich einen Schirm.'],
        highlight: 'article',
        t: [
          'Clothes: der Mantel (coat), der Pullover, der Rock (skirt), der Gürtel (belt), der Schal (scarf), das Hemd (shirt), das Kleid (dress), das T-Shirt, die Jacke (jacket), die Bluse, die Hose (trousers), die Mütze (hat, cap). Plural: die Schuhe (shoes), die Stiefel (boots). Objects: der Schirm (umbrella), der Koffer (suitcase), die Tasche (bag), die Brille (glasses), die Uhr (watch). Careful: die Hose and die Brille are singular in German.',
          'Одежда: der Mantel (пальто), der Pullover, der Rock (юбка), der Gürtel (ремень), der Schal (шарф), das Hemd (рубашка), das Kleid (платье), das T-Shirt, die Jacke (куртка), die Bluse, die Hose (брюки), die Mütze (шапка). Во множественном числе: die Schuhe (туфли, обувь), die Stiefel (сапоги). Предметы: der Schirm (зонт), der Koffer (чемодан), die Tasche (сумка), die Brille (очки), die Uhr (часы). Внимание: die Hose и die Brille в немецком стоят в единственном числе.',
          'Одяг: der Mantel (пальто), der Pullover, der Rock (спідниця), der Gürtel (ремінь), der Schal (шарф), das Hemd (сорочка), das Kleid (сукня), das T-Shirt, die Jacke (куртка), die Bluse, die Hose (штани), die Mütze (шапка). У множині: die Schuhe (туфлі, взуття), die Stiefel (чоботи). Предмети: der Schirm (парасолька), der Koffer (валіза), die Tasche (сумка), die Brille (окуляри), die Uhr (годинник). Увага: die Hose і die Brille в німецькій стоять в однині.',
          'Giysiler: der Mantel (palto), der Pullover (kazak), der Rock (etek), der Gürtel (kemer), der Schal (atkı), das Hemd (gömlek), das Kleid (elbise), das T-Shirt, die Jacke (ceket), die Bluse (bluz), die Hose (pantolon), die Mütze (bere). Çoğul: die Schuhe (ayakkabılar), die Stiefel (çizmeler). Eşyalar: der Schirm (şemsiye), der Koffer (bavul), die Tasche (çanta), die Brille (gözlük), die Uhr (saat).',
        ],
        hint: ['Wo trägt man das: am Kopf, am Körper, an den Beinen oder an den Füßen?', 'Where do you wear it: on the head, the body, the legs or the feet?', 'Где это носят: на голове, на теле, на ногах или на ступнях?', 'Де це носять: на голові, на тілі, на ногах чи на ступнях?', 'Bu nereye giyilir: başa, vücuda, bacaklara ya da ayaklara?'],
        hints: {
          article: ['Lern Kleidung immer mit Artikel: der Rock, das Kleid, die Hose.', 'Always learn clothes with their article: der Rock, das Kleid, die Hose.', 'Учите слова об одежде сразу с артиклем: der Rock, das Kleid, die Hose.', 'Вчіть слова про одяг одразу з артиклем: der Rock, das Kleid, die Hose.', 'Giysi adlarını hep artikeliyle öğrenin: der Rock, das Kleid, die Hose.'],
        },
      },
      ex: [
        mc('W1', 'Gegenstände', I.choose, 'Es regnet. Was brauchst du?', ['den Schirm', 'die Brille', 'den Gürtel'],
          ['It is raining. What do you need?', 'Идёт дождь. Что вам нужно?', 'Іде дощ. Що вам потрібно?', 'Yağmur yağıyor. Neye ihtiyacınız var?']),
        mc('W1', 'Kleidung', I.choose, 'Was trägt man an den Füßen?', ['Schuhe', 'eine Mütze', 'einen Schal'],
          ['What do you wear on your feet?', 'Что носят на ногах?', 'Що носять на ногах?', 'Ayaklara ne giyilir?']),
        mc('W1', 'Kleidung', I.choose, 'Es ist sehr kalt. Was trägst du auf dem Kopf?', ['eine Mütze', 'einen Rock', 'einen Koffer'],
          ['It is very cold. What do you wear on your head?', 'Очень холодно. Что вы наденете на голову?', 'Дуже холодно. Що ви вдягнете на голову?', 'Hava çok soğuk. Başınıza ne takarsınız?']),
        mc('W1', 'Kleidung', I.odd, 'Drei Wörter sind Kleidungsstücke, ein Wort nicht.', ['Koffer', 'Hemd', 'Jacke', 'Rock'], null),
        gap('W1', 'Artikel', I.article, '', ' Hose ist neu.', 'Die', ['Der', 'Das'],
          ['The trousers are new.', 'Брюки новые.', 'Штани нові.', 'Pantolon yeni.'], 'der / die / das', { h: 'article' }),
        gap('W1', 'Artikel', I.article, '', ' Kleid ist rot.', 'Das', ['Der', 'Die'],
          ['The dress is red.', 'Платье красное.', 'Сукня червона.', 'Elbise kırmızı.'], 'der / die / das', { h: 'article' }),
        gap('W1', 'Artikel', I.article, '', ' Mantel ist warm.', 'Der', ['Die', 'Das'],
          ['The coat is warm.', 'Пальто тёплое.', 'Пальто тепле.', 'Palto sıcak tutuyor.'], 'der / die / das', { h: 'article' }),
        gap('W1', 'Gegenstände', I.word, 'Für die Reise packe ich meine Sachen in den ', '.', 'Koffer', ['Schirm', 'Gürtel'],
          ['For the trip I pack my things into the suitcase.', 'В поездку я складываю вещи в чемодан.', 'У подорож я складаю речі у валізу.', 'Yolculuk için eşyalarımı bavula koyuyorum.'],
          ['suitcase', 'чемодан', 'валіза', 'bavul']),
        gap('W1', 'Gegenstände', I.word, 'Ich sehe nicht gut. Ich brauche eine ', '.', 'Brille', ['Bluse', 'Mütze'],
          ['I cannot see well. I need glasses.', 'Я плохо вижу. Мне нужны очки.', 'Я погано бачу. Мені потрібні окуляри.', 'İyi göremiyorum. Gözlüğe ihtiyacım var.'],
          ['glasses', 'очки', 'окуляри', 'gözlük']),
      ],
    },
    {
      title: 'Der ist schön! Den nehme ich.',
      t: ['That one is nice! I’ll take that one.', 'Этот красивый! Его я беру.', 'Цей гарний! Його я беру.', 'Bu güzel! Bunu alıyorum.'],
      card: {
        id: 'p6_demo',
        rule: 'Demonstrativpronomen der, das, die: So zeigst du auf Sachen, ohne das Nomen zu wiederholen. Nominativ: Der Gürtel? Der ist schön. Das Hemd? Das ist schön. Die Jacke? Die ist schön. Die Schuhe? Die sind schön. Akkusativ: Den finde ich super. Das finde ich super. Die finde ich super. Nur maskulin ändert sich: der → den.',
        examples: ['Wie findest du den Mantel? – Den finde ich toll.', 'Die Jacke da! Die ist super.', 'Das Kleid? Das ist zu teuer.'],
        highlight: 'article',
        t: [
          'Demonstrative pronouns der, das, die: this is how you point at things without repeating the noun (“that one”). Nominative: Der Gürtel? Der ist schön. Das Hemd? Das ist schön. Die Jacke? Die ist schön. Die Schuhe? Die sind schön. Accusative: Den finde ich super. Das finde ich super. Die finde ich super. Only the masculine form changes: der → den.',
          'Указательные местоимения der, das, die: так указывают на вещь, не повторяя существительное («этот, эта, это»). Nominativ: Der Gürtel? Der ist schön. Das Hemd? Das ist schön. Die Jacke? Die ist schön. Die Schuhe? Die sind schön. Akkusativ: Den finde ich super. Das finde ich super. Die finde ich super. Меняется только мужской род: der → den.',
          'Вказівні займенники der, das, die: так вказують на річ, не повторюючи іменник («цей, ця, це»). Nominativ: Der Gürtel? Der ist schön. Das Hemd? Das ist schön. Die Jacke? Die ist schön. Die Schuhe? Die sind schön. Akkusativ: Den finde ich super. Das finde ich super. Die finde ich super. Змінюється лише чоловічий рід: der → den.',
          'İşaret zamirleri der, das, die: İsmi tekrar etmeden bir şeyi böyle gösterirsiniz (“bu, şu”). Nominativ: Der Gürtel? Der ist schön. Das Hemd? Das ist schön. Die Jacke? Die ist schön. Die Schuhe? Die sind schön. Akkusativ: Den finde ich super. Das finde ich super. Die finde ich super. Yalnızca eril biçim değişir: der → den.',
        ],
        hint: ['Das Pronomen ist wie der Artikel: der, das, die. Im Akkusativ: der → den.', 'The pronoun looks like the article: der, das, die. In the accusative: der → den.', 'Местоимение выглядит как артикль: der, das, die. В Akkusativ: der → den.', 'Займенник виглядає як артикль: der, das, die. В Akkusativ: der → den.', 'Zamir artikel gibidir: der, das, die. Akkusativ’te: der → den.'],
      },
      ex: [
        mc('G1', 'Nominativ', I.choose, 'Der Pullover ist schön. – Ja, … ist wirklich schön.', ['der', 'das', 'die'],
          ['The pullover is nice. – Yes, that one is really nice.', 'Свитер красивый. – Да, он действительно красивый.', 'Светр гарний. – Так, він справді гарний.', 'Kazak güzel. – Evet, o gerçekten güzel.']),
        mc('G1', 'Akkusativ', I.choose, 'Wie findest du den Rock? – … finde ich langweilig.', ['Den', 'Der', 'Das'],
          ['How do you like the skirt? – I find that one boring.', 'Как тебе эта юбка? – Она, по-моему, скучная.', 'Як тобі ця спідниця? – Вона, на мою думку, нудна.', 'Eteği nasıl buluyorsun? – Onu sıkıcı buluyorum.']),
        mc('G1', 'Plural', I.choose, 'Und die Schuhe? – … sind zu klein.', ['Die', 'Der', 'Den'],
          ['And the shoes? – Those are too small.', 'А туфли? – Они слишком малы.', 'А туфлі? – Вони замалі.', 'Ya ayakkabılar? – Onlar çok küçük.']),
        gap('G1', 'Nominativ', I.pronoun, 'Das Hemd ist günstig. – Ja, ', ' kostet nur 15 Euro.', 'das', ['der', 'die'],
          ['The shirt is cheap. – Yes, that one costs only 15 euros.', 'Рубашка недорогая. – Да, она стоит всего 15 евро.', 'Сорочка недорога. – Так, вона коштує лише 15 євро.', 'Gömlek uygun fiyatlı. – Evet, o sadece 15 avro.'], 'der / das / die'),
        gap('G1', 'Akkusativ', I.pronoun, 'Wie findest du die Bluse? – ', ' finde ich sehr schön.', 'Die', ['Den', 'Das'],
          ['How do you like the blouse? – I find that one very nice.', 'Как тебе эта блузка? – Она, по-моему, очень красивая.', 'Як тобі ця блузка? – Вона, на мою думку, дуже гарна.', 'Bluzu nasıl buluyorsun? – Onu çok güzel buluyorum.'], 'den / das / die'),
        gap('G1', 'Akkusativ', I.pronoun, 'Siehst du den Mantel dort? ', ' möchte ich kaufen.', 'Den', ['Der', 'Die'],
          ['Do you see the coat over there? I would like to buy that one.', 'Видишь вон то пальто? Его я хочу купить.', 'Бачиш он те пальто? Його я хочу купити.', 'Oradaki paltoyu görüyor musun? Onu almak istiyorum.'], 'der / den'),
        gap('G1', 'Nominativ', I.pronoun, 'Der Schal ist toll. – Findest du? ', ' ist doch viel zu lang.', 'Der', ['Den', 'Das'],
          ['The scarf is great. – Do you think so? That one is far too long.', 'Шарф классный. – Ты так считаешь? Он же слишком длинный.', 'Шарф класний. – Ти так вважаєш? Він же задовгий.', 'Atkı harika. – Öyle mi düşünüyorsun? O çok uzun ama.'], 'der / den'),
        gap('G1', 'Plural', I.pronoun, 'Die Stiefel sind schön. – Ja, aber ', ' sind sehr teuer.', 'die', ['der', 'das'],
          ['The boots are nice. – Yes, but those are very expensive.', 'Сапоги красивые. – Да, но они очень дорогие.', 'Чоботи гарні. – Так, але вони дуже дорогі.', 'Çizmeler güzel. – Evet, ama onlar çok pahalı.'], 'der / das / die'),
        sb('G1', 'Akkusativ', I.order, 'Den / finde / ich / super.',
          ['I think that one is great.', 'Он, по-моему, отличный.', 'Він, на мою думку, чудовий.', 'Onu harika buluyorum.'],
          { alt: ['Ich finde den super.'] }),
      ],
    },
    {
      title: 'Wie findest du …?',
      t: ['How do you like …?', 'Как тебе …?', 'Як тобі …?', '… nasıl buluyorsun?'],
      card: {
        id: 'p6_bewerten',
        rule: 'Etwas bewerten: Positiv: Die Jacke ist (sehr) schön / super / toll / günstig / nicht schlecht. Negativ: Die Schuhe sind hässlich / langweilig / nicht so schön / zu teuer. Mit „zu“ ist etwas mehr als gut: zu klein, zu groß, zu lang, zu kurz, zu teuer. Fragen: Wie findest du den Mantel? Wie gefällt dir die Hose?',
        examples: ['Die Jacke ist toll, aber zu teuer.', 'Der Pullover ist nicht schlecht.', 'Die Hose ist total langweilig.'],
        highlight: null,
        t: [
          'Giving an opinion: positive: Die Jacke ist (sehr) schön / super / toll (great) / günstig (cheap, good value) / nicht schlecht (not bad). Negative: Die Schuhe sind hässlich (ugly) / langweilig (boring) / nicht so schön / zu teuer. “zu” means more than is good: zu klein, zu groß, zu lang, zu kurz, zu teuer (too …). Questions: Wie findest du den Mantel? Wie gefällt dir die Hose?',
          'Как оценить вещь: положительно: Die Jacke ist (sehr) schön / super / toll (классная) / günstig (недорогая) / nicht schlecht (неплохая). Отрицательно: Die Schuhe sind hässlich (некрасивые) / langweilig (скучные) / nicht so schön / zu teuer. «zu» значит «слишком»: zu klein, zu groß, zu lang, zu kurz, zu teuer. Вопросы: Wie findest du den Mantel? Wie gefällt dir die Hose?',
          'Як оцінити річ: позитивно: Die Jacke ist (sehr) schön / super / toll (класна) / günstig (недорога) / nicht schlecht (непогана). Негативно: Die Schuhe sind hässlich (негарні) / langweilig (нудні) / nicht so schön / zu teuer. «zu» означає «занадто»: zu klein, zu groß, zu lang, zu kurz, zu teuer. Запитання: Wie findest du den Mantel? Wie gefällt dir die Hose?',
          'Bir şeyi değerlendirme: Olumlu: Die Jacke ist (sehr) schön / super / toll (harika) / günstig (uygun fiyatlı) / nicht schlecht (fena değil). Olumsuz: Die Schuhe sind hässlich (çirkin) / langweilig (sıkıcı) / nicht so schön / zu teuer. “zu” “fazla” demektir: zu klein, zu groß, zu lang, zu kurz, zu teuer. Sorular: Wie findest du den Mantel? Wie gefällt dir die Hose?',
        ],
        hint: ['Positiv: schön, toll, super, günstig. Negativ: hässlich, langweilig, zu teuer.', 'Positive: schön, toll, super, günstig. Negative: hässlich, langweilig, zu teuer.', 'Положительно: schön, toll, super, günstig. Отрицательно: hässlich, langweilig, zu teuer.', 'Позитивно: schön, toll, super, günstig. Негативно: hässlich, langweilig, zu teuer.', 'Olumlu: schön, toll, super, günstig. Olumsuz: hässlich, langweilig, zu teuer.'],
      },
      ex: [
        mc('K1', 'günstig', I.choose, 'Die Jacke kostet nur 20 Euro. Sie ist …', ['günstig', 'teuer', 'hässlich'],
          ['The jacket costs only 20 euros. It is …', 'Куртка стоит всего 20 евро. Она …', 'Куртка коштує лише 20 євро. Вона …', 'Ceket sadece 20 avro. O …']),
        mc('K1', 'negativ bewerten', I.choose, 'Du findest die Hose nicht schön. Was sagst du?', ['Die ist hässlich.', 'Die ist toll.', 'Die ist super.'],
          ['You do not think the trousers are nice. What do you say?', 'Вам не нравятся эти брюки. Что вы скажете?', 'Вам не подобаються ці штани. Що ви скажете?', 'Pantolonu güzel bulmuyorsunuz. Ne dersiniz?']),
        mc('K1', 'positiv bewerten', I.react, '„Wie findest du das Kleid?“', ['Das finde ich sehr schön.', 'Das kostet 40 Euro.', 'Das ist ein Kleid.'],
          ['“How do you like the dress?”', '«Как тебе это платье?»', '«Як тобі ця сукня?»', '“Elbiseyi nasıl buluyorsun?”']),
        mc('K1', 'zu groß', I.choose, 'Die Hose hat Größe 50, aber du brauchst Größe 46. Die Hose ist …', ['zu groß', 'zu klein', 'zu kurz'],
          ['The trousers are size 50, but you need size 46. The trousers are …', 'Брюки 50-го размера, а вам нужен 46-й. Брюки …', 'Штани 50-го розміру, а вам потрібен 46-й. Штани …', 'Pantolon 50 beden, ama size 46 beden lazım. Pantolon …']),
        gap('K1', 'zu teuer', I.word, 'Der Mantel kostet 400 Euro. Das ist zu ', '.', 'teuer', ['günstig', 'klein'],
          ['The coat costs 400 euros. That is too expensive.', 'Пальто стоит 400 евро. Это слишком дорого.', 'Пальто коштує 400 євро. Це занадто дорого.', 'Palto 400 avro. Bu çok pahalı.'],
          ['expensive', 'дорого', 'дорого', 'pahalı']),
        gap('K1', 'langweilig', I.word, 'Die Farbe ist grau, die Form ist alt. Der Pullover ist total ', '.', 'langweilig', ['toll', 'günstig'],
          ['The colour is grey, the style is old. The pullover is totally boring.', 'Цвет серый, фасон старый. Свитер совсем скучный.', 'Колір сірий, фасон старий. Светр зовсім нудний.', 'Rengi gri, modeli eski. Kazak çok sıkıcı.'],
          ['boring', 'скучный', 'нудний', 'sıkıcı']),
        gap('K1', 'nicht schlecht', I.word, 'Die Schuhe sind nicht super, aber auch nicht ', '.', 'schlecht', ['gut', 'schön'],
          ['The shoes are not great, but not bad either.', 'Туфли не супер, но и неплохие.', 'Туфлі не супер, але й непогані.', 'Ayakkabılar harika değil, ama kötü de değil.'],
          ['bad', 'плохой', 'поганий', 'kötü']),
        sb('K1', 'nach der Meinung fragen', I.question, 'Wie / findest / du / den Mantel?',
          ['How do you like the coat?', 'Как тебе это пальто?', 'Як тобі це пальто?', 'Paltoyu nasıl buluyorsun?']),
      ],
    },
    {
      title: 'mir, dir, ihm, ihr',
      t: ['mir, dir, ihm, ihr (dative pronouns)', 'mir, dir, ihm, ihr (местоимения в Dativ)', 'mir, dir, ihm, ihr (займенники в Dativ)', 'mir, dir, ihm, ihr (Dativ zamirleri)'],
      card: {
        id: 'p6_dativ',
        rule: 'Personalpronomen im Dativ: ich → mir, du → dir, er/es → ihm, sie → ihr, wir → uns, ihr → euch, sie → ihnen, Sie → Ihnen. Die Frage heißt: Wem? Die Jacke gefällt mir. Der Mantel steht dir. Das Hemd passt ihm. Die Bluse gefällt ihr.',
        examples: ['Gefällt dir die Jacke? – Ja, sie gefällt mir.', 'Das ist Emre. Der Pullover passt ihm gut.', 'Wie geht es Ihnen, Frau Kaya?'],
        highlight: null,
        t: [
          'Personal pronouns in the dative: ich → mir, du → dir, er/es → ihm, sie → ihr, wir → uns, ihr → euch, sie → ihnen, Sie → Ihnen. The question is: Wem? (to whom?) Die Jacke gefällt mir. Der Mantel steht dir. Das Hemd passt ihm. Die Bluse gefällt ihr.',
          'Личные местоимения в Dativ: ich → mir (мне), du → dir (тебе), er/es → ihm (ему), sie → ihr (ей), wir → uns (нам), ihr → euch (вам), sie → ihnen (им), Sie → Ihnen (Вам). Вопрос: Wem? (кому?) Die Jacke gefällt mir. Der Mantel steht dir. Das Hemd passt ihm. Die Bluse gefällt ihr.',
          'Особові займенники в Dativ: ich → mir (мені), du → dir (тобі), er/es → ihm (йому), sie → ihr (їй), wir → uns (нам), ihr → euch (вам), sie → ihnen (їм), Sie → Ihnen (Вам). Запитання: Wem? (кому?) Die Jacke gefällt mir. Der Mantel steht dir. Das Hemd passt ihm. Die Bluse gefällt ihr.',
          'Dativ’te kişi zamirleri: ich → mir (bana), du → dir (sana), er/es → ihm (ona, erkek), sie → ihr (ona, kadın), wir → uns (bize), ihr → euch (size), sie → ihnen (onlara), Sie → Ihnen (size, resmî). Soru: Wem? (kime?) Die Jacke gefällt mir. Der Mantel steht dir. Das Hemd passt ihm. Die Bluse gefällt ihr.',
        ],
        hint: ['Wem? → Dativ: mir, dir, ihm, ihr, uns, euch, ihnen, Ihnen.', 'Wem? → dative: mir, dir, ihm, ihr, uns, euch, ihnen, Ihnen.', 'Wem? (кому?) → Dativ: mir, dir, ihm, ihr, uns, euch, ihnen, Ihnen.', 'Wem? (кому?) → Dativ: mir, dir, ihm, ihr, uns, euch, ihnen, Ihnen.', 'Wem? (kime?) → Dativ: mir, dir, ihm, ihr, uns, euch, ihnen, Ihnen.'],
        hints: {
          who: ['Über wen sprichst du? Ein Mann → ihm, eine Frau → ihr, mehrere Personen → ihnen.', 'Who are you talking about? A man → ihm, a woman → ihr, several people → ihnen.', 'О ком вы говорите? Мужчина → ihm, женщина → ihr, несколько человек → ihnen.', 'Про кого ви говорите? Чоловік → ihm, жінка → ihr, кілька людей → ihnen.', 'Kimden söz ediyorsunuz? Erkek → ihm, kadın → ihr, birden fazla kişi → ihnen.'],
        },
      },
      ex: [
        mc('G3', 'mir', I.choose, 'Ich finde die Schuhe toll. Sie gefallen … sehr.', ['mir', 'mich', 'ich'],
          ['I think the shoes are great. I like them a lot.', 'Мне очень нравятся эти туфли.', 'Мені дуже подобаються ці туфлі.', 'Ayakkabıları harika buluyorum. Çok hoşuma gidiyorlar.']),
        mc('G3', 'ihm', I.choose, 'Das ist Jonas. Die Jacke passt … gut.', ['ihm', 'ihr', 'ihnen'],
          ['This is Jonas. The jacket fits him well.', 'Это Jonas. Куртка ему хорошо подходит.', 'Це Jonas. Куртка йому добре підходить.', 'Bu Jonas. Ceket ona iyi oluyor.'], { h: 'who' }),
        mc('G3', 'Ihnen', I.choose, 'Frau Aksoy, gefällt … das Kleid?', ['Ihnen', 'dir', 'ihr'],
          ['Ms Aksoy, do you like the dress?', 'Госпожа Aksoy, вам нравится это платье?', 'Пані Aksoy, вам подобається ця сукня?', 'Aksoy Hanım, elbise hoşunuza gidiyor mu?']),
        gap('G3', 'dir', I.pronoun, 'Du siehst toll aus! Der Mantel steht ', ' sehr gut.', 'dir', ['dich', 'du'],
          ['You look great! The coat really suits you.', 'Ты отлично выглядишь! Пальто тебе очень идёт.', 'Ти чудово виглядаєш! Пальто тобі дуже личить.', 'Harika görünüyorsun! Palto sana çok yakışıyor.'], 'du'),
        gap('G3', 'ihr', I.pronoun, 'Lena probiert eine Bluse. Die Bluse gefällt ', '.', 'ihr', ['ihm', 'sie'],
          ['Lena is trying on a blouse. She likes the blouse.', 'Lena примеряет блузку. Блузка ей нравится.', 'Lena приміряє блузку. Блузка їй подобається.', 'Lena bir bluz deniyor. Bluz hoşuna gidiyor.'], 'sie', { h: 'who' }),
        gap('G3', 'uns', I.pronoun, 'Wir kaufen die Schuhe. Sie gefallen ', '.', 'uns', ['wir', 'euch'],
          ['We are buying the shoes. We like them.', 'Мы покупаем эти туфли. Они нам нравятся.', 'Ми купуємо ці туфлі. Вони нам подобаються.', 'Ayakkabıları alıyoruz. Hoşumuza gidiyorlar.'], 'wir'),
        gap('G3', 'euch', I.pronoun, 'Tim und Mia, gefällt ', ' das Geschenk?', 'euch', ['ihr', 'uns'],
          ['Tim and Mia, do you like the present?', 'Tim и Mia, вам нравится подарок?', 'Tim і Mia, вам подобається подарунок?', 'Tim ve Mia, hediye hoşunuza gidiyor mu?'], 'ihr'),
        gap('G3', 'ihnen', I.pronoun, 'Meine Eltern mögen Fisch. Fisch schmeckt ', ' gut.', 'ihnen', ['ihm', 'sie'],
          ['My parents like fish. Fish tastes good to them.', 'Мои родители любят рыбу. Рыба им нравится.', 'Мої батьки люблять рибу. Риба їм смакує.', 'Annemle babam balığı sever. Balık onlara lezzetli geliyor.'], 'sie (Plural)', { h: 'who' }),
        gap('G3', 'ihm', I.pronoun, 'Mein Bruder ist groß. Die Hose ist ', ' zu kurz.', 'ihm', ['ihr', 'er'],
          ['My brother is tall. The trousers are too short for him.', 'Мой брат высокий. Брюки ему слишком коротки.', 'Мій брат високий. Штани йому закороткі.', 'Erkek kardeşim uzun boylu. Pantolon ona çok kısa.'], 'er', { h: 'who' }),
        sb('G3', 'mir', I.order, 'Die Jacke / gefällt / mir / sehr gut.',
          ['I like the jacket very much.', 'Куртка мне очень нравится.', 'Куртка мені дуже подобається.', 'Ceket çok hoşuma gidiyor.'],
          { alt: ['Mir gefällt die Jacke sehr gut.', 'Sehr gut gefällt mir die Jacke.'] }),
      ],
    },
    {
      title: 'gefallen, passen, stehen',
      t: ['gefallen, passen, stehen (verbs with the dative)', 'gefallen, passen, stehen (глаголы с Dativ)', 'gefallen, passen, stehen (дієслова з Dativ)', 'gefallen, passen, stehen (Dativ alan fiiller)'],
      card: {
        id: 'p6_dativverben',
        rule: 'Verben mit Dativ: gefallen, gehören, passen, stehen, schmecken. Die Sache ist das Subjekt, die Person steht im Dativ. Der Mantel gefällt mir. (= Ich finde den Mantel schön.) Die Tasche gehört mir. (= Das ist meine Tasche.) Die Hose passt mir. (= Die Größe ist richtig.) Das Kleid steht dir. (= Du siehst gut aus.) Der Käse schmeckt uns. Plural: Die Schuhe gefallen mir.',
        examples: ['Wem gehört der Schirm? – Der gehört mir.', 'Das Hemd steht dir gut.', 'Die Schuhe passen mir nicht.'],
        highlight: 'verb',
        t: [
          'Verbs with the dative: gefallen, gehören, passen, stehen, schmecken. The thing is the subject, the person is in the dative. Der Mantel gefällt mir. (= I like the coat.) Die Tasche gehört mir. (= The bag belongs to me.) Die Hose passt mir. (= It is the right size.) Das Kleid steht dir. (= It suits you.) Der Käse schmeckt uns. (= We like the taste.) Plural: Die Schuhe gefallen mir.',
          'Глаголы с Dativ: gefallen, gehören, passen, stehen, schmecken. Вещь – подлежащее, человек стоит в Dativ, как в русском «мне нравится». Der Mantel gefällt mir. (= Пальто мне нравится.) Die Tasche gehört mir. (= Сумка принадлежит мне.) Die Hose passt mir. (= Брюки мне по размеру.) Das Kleid steht dir. (= Платье тебе идёт.) Der Käse schmeckt uns. (= Сыр нам по вкусу.) Множественное число: Die Schuhe gefallen mir.',
          'Дієслова з Dativ: gefallen, gehören, passen, stehen, schmecken. Річ – підмет, людина стоїть у Dativ, як в українському «мені подобається». Der Mantel gefällt mir. (= Пальто мені подобається.) Die Tasche gehört mir. (= Сумка належить мені.) Die Hose passt mir. (= Штани мені за розміром.) Das Kleid steht dir. (= Сукня тобі личить.) Der Käse schmeckt uns. (= Сир нам смакує.) Множина: Die Schuhe gefallen mir.',
          'Dativ alan fiiller: gefallen, gehören, passen, stehen, schmecken. Eşya öznedir, kişi Dativ’te durur; Türkçedeki “hoşuma gidiyor” gibi. Der Mantel gefällt mir. (= Palto hoşuma gidiyor.) Die Tasche gehört mir. (= Çanta bana ait.) Die Hose passt mir. (= Pantolon bana oluyor.) Das Kleid steht dir. (= Elbise sana yakışıyor.) Der Käse schmeckt uns. (= Peynir bize lezzetli geliyor.) Çoğul: Die Schuhe gefallen mir.',
        ],
        hint: ['Eine Sache → gefällt, passt, steht. Mehrere Sachen → gefallen, passen, stehen.', 'One thing → gefällt, passt, steht. Several things → gefallen, passen, stehen.', 'Одна вещь → gefällt, passt, steht. Несколько вещей → gefallen, passen, stehen.', 'Одна річ → gefällt, passt, steht. Кілька речей → gefallen, passen, stehen.', 'Tek eşya → gefällt, passt, steht. Birden fazla eşya → gefallen, passen, stehen.'],
        hints: {
          meaning: ['gefallen = schön finden, gehören = es ist meins, passen = die Größe stimmt, stehen = gut aussehen, schmecken = das Essen ist gut.', 'gefallen = to find nice, gehören = it is mine, passen = the size is right, stehen = to look good on someone, schmecken = the food is good.', 'gefallen = нравиться, gehören = принадлежать, passen = подходить по размеру, stehen = идти (быть к лицу), schmecken = быть вкусным.', 'gefallen = подобатися, gehören = належати, passen = підходити за розміром, stehen = личити, schmecken = смакувати.', 'gefallen = hoşa gitmek, gehören = ait olmak, passen = bedeni uymak, stehen = yakışmak, schmecken = lezzetli gelmek.'],
        },
      },
      ex: [
        mc('G4', 'gehören', I.choose, 'Das ist meine Tasche. Die Tasche … mir.', ['gehört', 'passt', 'schmeckt'],
          ['This is my bag. The bag belongs to me.', 'Это моя сумка. Сумка принадлежит мне.', 'Це моя сумка. Сумка належить мені.', 'Bu benim çantam. Çanta bana ait.'], { h: 'meaning' }),
        mc('G4', 'passen', I.choose, 'Die Schuhe sind zu klein. Sie … mir nicht.', ['passen', 'schmecken', 'gehören'],
          ['The shoes are too small. They do not fit me.', 'Туфли слишком малы. Они мне не подходят по размеру.', 'Туфлі замалі. Вони мені не підходять за розміром.', 'Ayakkabılar çok küçük. Bana olmuyorlar.'], { h: 'meaning' }),
        mc('G4', 'schmecken', I.choose, 'Die Suppe ist sehr gut. Sie … mir.', ['schmeckt', 'steht', 'passt'],
          ['The soup is very good. I like the taste.', 'Суп очень хороший. Он мне по вкусу.', 'Суп дуже добрий. Він мені смакує.', 'Çorba çok güzel. Bana lezzetli geliyor.'], { h: 'meaning' }),
        gap('G4', 'gefallen', I.verb, 'Die Jacke ', ' mir sehr gut. Die kaufe ich.', 'gefällt', ['gefallen', 'gefällst'],
          ['I like the jacket very much. I am buying that one.', 'Куртка мне очень нравится. Её я покупаю.', 'Куртка мені дуже подобається. Її я купую.', 'Ceket çok hoşuma gidiyor. Onu alıyorum.'], 'gefallen'),
        gap('G4', 'gefallen', I.verb, 'Die Schuhe ', ' mir nicht. Die finde ich hässlich.', 'gefallen', ['gefällt', 'gefallt'],
          ['I do not like the shoes. I think they are ugly.', 'Туфли мне не нравятся. По-моему, они некрасивые.', 'Туфлі мені не подобаються. На мою думку, вони негарні.', 'Ayakkabılar hoşuma gitmiyor. Onları çirkin buluyorum.'], LIKE),
        gap('G4', 'gehören', I.verb, 'Wem ', ' der Koffer? – Mir.', 'gehört', ['gehören', 'gehörst'],
          ['Whose suitcase is this? – Mine.', 'Кому принадлежит чемодан? – Мне.', 'Кому належить валіза? – Мені.', 'Bavul kimin? – Benim.'], 'gehören'),
        gap('G4', 'stehen', I.verb, 'Das Kleid ', ' dir super! Du siehst toll aus.', 'steht', ['stehen', 'stehst'],
          ['The dress really suits you! You look great.', 'Платье тебе очень идёт! Ты отлично выглядишь.', 'Сукня тобі дуже личить! Ти чудово виглядаєш.', 'Elbise sana çok yakışıyor! Harika görünüyorsun.'], 'stehen'),
        gap('G4', 'schmecken', I.verb, 'Schmeckt dir der Kuchen? – Ja, er ', ' mir sehr gut.', 'schmeckt', ['schmecken', 'schmeckst'],
          ['Do you like the cake? – Yes, it tastes very good.', 'Тебе нравится пирог? – Да, он очень вкусный.', 'Тобі смакує пиріг? – Так, він дуже смачний.', 'Kek hoşuna gidiyor mu? – Evet, çok lezzetli.'], 'schmecken'),
        gap('G4', 'Verb + Dativ', I.pronoun, 'Die Hose passt ', ' nicht. Ich brauche Größe 40.', 'mir', ['mich', 'ich'],
          ['The trousers do not fit me. I need size 40.', 'Брюки мне не подходят по размеру. Мне нужен 40-й размер.', 'Штани мені не підходять за розміром. Мені потрібен 40-й розмір.', 'Pantolon bana olmuyor. 40 bedene ihtiyacım var.'], 'ich'),
        sb('G4', 'gehören', I.question, 'Wem / gehört / der Schirm?',
          ['Whose umbrella is this?', 'Кому принадлежит зонт?', 'Кому належить парасолька?', 'Şemsiye kimin?']),
      ],
    },
    {
      title: 'Mir auch. Mir nicht.',
      t: ['Me too. Not me.', 'Мне тоже. А мне нет.', 'Мені теж. А мені ні.', 'Benim de. Benim değil.'],
      card: {
        id: 'p6_vorlieben',
        rule: 'Über Vorlieben sprechen: Mir gefällt das Hemd. Mir gefallen die Schuhe. Mir schmeckt der Tee. Und dir? Gleiche Meinung: Mir auch. (nach einem positiven Satz) Mir auch nicht. (nach einem negativen Satz) Andere Meinung: Mir nicht. (nach einem positiven Satz) Mir schon. (nach einem negativen Satz)',
        examples: ['Mir gefällt der Mantel. – Mir auch.', 'Mir schmeckt der Kaffee nicht. – Mir schon!', 'Mir gefällt die Farbe nicht. – Mir auch nicht.'],
        highlight: null,
        t: [
          'Talking about likes: Mir gefällt das Hemd. Mir gefallen die Schuhe. Mir schmeckt der Tee. Und dir? Same opinion: Mir auch. (me too – after a positive sentence) Mir auch nicht. (me neither – after a negative sentence) Different opinion: Mir nicht. (not me – after a positive sentence) Mir schon. (I do – after a negative sentence)',
          'Как говорить о своих вкусах: Mir gefällt das Hemd. Mir gefallen die Schuhe. Mir schmeckt der Tee. Und dir? То же мнение: Mir auch. (мне тоже – после утвердительной фразы) Mir auch nicht. (мне тоже нет – после отрицательной) Другое мнение: Mir nicht. (а мне нет – после утвердительной) Mir schon. (а мне да – после отрицательной)',
          'Як говорити про свої вподобання: Mir gefällt das Hemd. Mir gefallen die Schuhe. Mir schmeckt der Tee. Und dir? Така сама думка: Mir auch. (мені теж – після стверджувальної фрази) Mir auch nicht. (мені теж ні – після заперечної) Інша думка: Mir nicht. (а мені ні – після стверджувальної) Mir schon. (а мені так – після заперечної)',
          'Beğenilerden söz etme: Mir gefällt das Hemd. Mir gefallen die Schuhe. Mir schmeckt der Tee. Und dir? Aynı görüş: Mir auch. (benim de – olumlu cümleden sonra) Mir auch nicht. (benim de gitmiyor – olumsuz cümleden sonra) Farklı görüş: Mir nicht. (benim gitmiyor – olumlu cümleden sonra) Mir schon. (benim gidiyor – olumsuz cümleden sonra)',
        ],
        hint: ['Positiv + gleiche Meinung → Mir auch. Negativ + gleiche Meinung → Mir auch nicht.', 'Positive + same opinion → Mir auch. Negative + same opinion → Mir auch nicht.', 'Утверждение + то же мнение → Mir auch. Отрицание + то же мнение → Mir auch nicht.', 'Ствердження + така сама думка → Mir auch. Заперечення + така сама думка → Mir auch nicht.', 'Olumlu + aynı görüş → Mir auch. Olumsuz + aynı görüş → Mir auch nicht.'],
        hints: {
          other: ['Andere Meinung: nach positiv → Mir nicht. Nach negativ → Mir schon.', 'Different opinion: after a positive sentence → Mir nicht. After a negative one → Mir schon.', 'Другое мнение: после утверждения → Mir nicht. После отрицания → Mir schon.', 'Інша думка: після ствердження → Mir nicht. Після заперечення → Mir schon.', 'Farklı görüş: olumludan sonra → Mir nicht. Olumsuzdan sonra → Mir schon.'],
        },
      },
      ex: [
        mc('K2', 'zustimmen', I.react, '„Mir gefällt die Jacke.“ – Du findest die Jacke auch schön.', ['Mir auch.', 'Mir auch nicht.', 'Mir schon.'],
          ['“I like the jacket.” – You think the jacket is nice too.', '«Мне нравится эта куртка». – Вам она тоже нравится.', '«Мені подобається ця куртка». – Вам вона теж подобається.', '“Ceket hoşuma gidiyor.” – Siz de ceketi güzel buluyorsunuz.']),
        mc('K2', 'widersprechen', I.react, '„Mir gefällt der Rock nicht.“ – Du findest den Rock schön.', ['Mir schon.', 'Mir auch.', 'Mir auch nicht.'],
          ['“I do not like the skirt.” – You think the skirt is nice.', '«Мне не нравится эта юбка». – А вам она нравится.', '«Мені не подобається ця спідниця». – А вам вона подобається.', '“Etek hoşuma gitmiyor.” – Siz eteği güzel buluyorsunuz.'], { h: 'other' }),
        mc('K2', 'zustimmen', I.react, '„Mir schmeckt der Fisch nicht.“ – Du findest den Fisch auch nicht gut.', ['Mir auch nicht.', 'Mir schon.', 'Mir auch.'],
          ['“I do not like the fish.” – You do not think the fish is good either.', '«Мне не нравится эта рыба». – Вам она тоже не нравится.', '«Мені не смакує ця риба». – Вам вона теж не смакує.', '“Balık hoşuma gitmiyor.” – Siz de balığı iyi bulmuyorsunuz.']),
        mc('K2', 'widersprechen', I.react, '„Mir gefallen die Stiefel.“ – Du findest die Stiefel hässlich.', ['Mir nicht.', 'Mir auch.', 'Mir schon.'],
          ['“I like the boots.” – You think the boots are ugly.', '«Мне нравятся эти сапоги». – А вам они кажутся некрасивыми.', '«Мені подобаються ці чоботи». – А вам вони здаються негарними.', '“Çizmeler hoşuma gidiyor.” – Siz çizmeleri çirkin buluyorsunuz.'], { h: 'other' }),
        gap('K2', 'Mir gefallen …', I.verb, 'Mir ', ' die Schuhe sehr gut. Und dir?', 'gefallen', ['gefällt', 'gefallt'],
          ['I like the shoes very much. And you?', 'Мне очень нравятся эти туфли. А тебе?', 'Мені дуже подобаються ці туфлі. А тобі?', 'Ayakkabılar çok hoşuma gidiyor. Ya senin?'], LIKE, { c: 'p6_dativverben' }),
        gap('K2', 'Und dir?', I.pronoun, 'Mir gefällt das Kleid. Und ', '? Wie findest du es?', 'dir', ['du', 'dich'],
          ['I like the dress. And you? What do you think of it?', 'Мне нравится это платье. А тебе? Как оно тебе?', 'Мені подобається ця сукня. А тобі? Як вона тобі?', 'Elbise hoşuma gidiyor. Ya senin? Sen nasıl buluyorsun?'], 'du', { c: 'p6_dativ' }),
        gap('K2', 'widersprechen', I.word, 'Mir schmeckt der Tee nicht. – Mir ', '! Ich trinke gern Tee.', 'schon', ['auch', 'nicht'],
          ['I do not like the tea. – I do! I like drinking tea.', 'Мне не нравится этот чай. – А мне нравится! Я люблю чай.', 'Мені не смакує цей чай. – А мені смакує! Я люблю чай.', 'Çay hoşuma gitmiyor. – Benim gidiyor! Çay içmeyi severim.'], 'auch / schon / nicht', { h: 'other' }),
        sb('K2', 'Mir gefällt … nicht', I.order, 'Mir / gefällt / das Hemd / nicht.',
          ['I do not like the shirt.', 'Мне не нравится эта рубашка.', 'Мені не подобається ця сорочка.', 'Gömlek hoşuma gitmiyor.'],
          { alt: ['Das Hemd gefällt mir nicht.'] }),
      ],
    },
    {
      title: 'Welcher? – Dieser.',
      t: ['Which one? – This one.', 'Какой? – Этот.', 'Який? – Цей.', 'Hangisi? – Bu.'],
      card: {
        id: 'p6_welch',
        rule: 'welcher? – dieser: So fragst du nach einer Sache aus einer Gruppe: Welcher Mantel? – Dieser. Welches Hemd? – Dieses. Welche Jacke? – Diese. Welche Schuhe? – Diese. Die Endung ist wie beim Artikel: der → -er, das → -es, die → -e. Im Akkusativ ist nur maskulin anders: Welchen Mantel nimmst du? – Diesen.',
        examples: ['Welcher Pullover gefällt dir? – Dieser hier.', 'Welches Kleid möchten Sie? – Dieses.', 'Welchen Koffer findest du schön? – Diesen.'],
        highlight: 'article',
        t: [
          'welcher? – dieser: this is how you ask about one thing from a group: Welcher Mantel? (which coat?) – Dieser (this one). Welches Hemd? – Dieses. Welche Jacke? – Diese. Welche Schuhe? – Diese. The ending is like the article: der → -er, das → -es, die → -e. In the accusative only the masculine changes: Welchen Mantel nimmst du? – Diesen.',
          'welcher? – dieser: так спрашивают об одной вещи из нескольких: Welcher Mantel? (какое пальто?) – Dieser (это). Welches Hemd? – Dieses. Welche Jacke? – Diese. Welche Schuhe? – Diese. Окончание как у артикля: der → -er, das → -es, die → -e. В Akkusativ меняется только мужской род: Welchen Mantel nimmst du? – Diesen.',
          'welcher? – dieser: так питають про одну річ із кількох: Welcher Mantel? (яке пальто?) – Dieser (це). Welches Hemd? – Dieses. Welche Jacke? – Diese. Welche Schuhe? – Diese. Закінчення як в артикля: der → -er, das → -es, die → -e. В Akkusativ змінюється лише чоловічий рід: Welchen Mantel nimmst du? – Diesen.',
          'welcher? – dieser: Bir gruptan bir şeyi böyle sorarsınız: Welcher Mantel? (hangi palto?) – Dieser (bu). Welches Hemd? – Dieses. Welche Jacke? – Diese. Welche Schuhe? – Diese. Ek, artikeldeki gibidir: der → -er, das → -es, die → -e. Akkusativ’te yalnızca eril değişir: Welchen Mantel nimmst du? – Diesen.',
        ],
        hint: ['Endung wie beim Artikel: der → -er, das → -es, die → -e, den → -en.', 'Ending like the article: der → -er, das → -es, die → -e, den → -en.', 'Окончание как у артикля: der → -er, das → -es, die → -e, den → -en.', 'Закінчення як в артикля: der → -er, das → -es, die → -e, den → -en.', 'Ek artikeldeki gibi: der → -er, das → -es, die → -e, den → -en.'],
      },
      ex: [
        mc('G2', 'welche', I.choose, '… Jacke gefällt dir? – Diese hier.', ['Welche', 'Welcher', 'Welches'],
          ['Which jacket do you like? – This one here.', 'Какая куртка тебе нравится? – Вот эта.', 'Яка куртка тобі подобається? – Ось ця.', 'Hangi ceket hoşuna gidiyor? – Şu.']),
        mc('G2', 'welches', I.choose, '… Hemd nimmst du? – Dieses.', ['Welches', 'Welcher', 'Welchen'],
          ['Which shirt are you taking? – This one.', 'Какую рубашку ты берёшь? – Эту.', 'Яку сорочку ти береш? – Цю.', 'Hangi gömleği alıyorsun? – Bunu.']),
        mc('G2', 'diesen', I.choose, 'Welchen Koffer möchtest du? – … hier.', ['Diesen', 'Dieser', 'Dieses'],
          ['Which suitcase would you like? – This one here.', 'Какой чемодан ты хочешь? – Вот этот.', 'Яку валізу ти хочеш? – Ось цю.', 'Hangi bavulu istiyorsun? – Şunu.']),
        gap('G2', 'welcher', I.form, '', ' Mantel ist günstig? – Dieser.', 'Welcher', ['Welches', 'Welche'],
          ['Which coat is good value? – This one.', 'Какое пальто недорогое? – Это.', 'Яке пальто недороге? – Це.', 'Hangi palto uygun fiyatlı? – Bu.'], 'welch-'),
        gap('G2', 'welche (Plural)', I.form, '', ' Schuhe gefallen dir? – Diese da.', 'Welche', ['Welcher', 'Welches'],
          ['Which shoes do you like? – Those there.', 'Какие туфли тебе нравятся? – Вон те.', 'Які туфлі тобі подобаються? – Он ті.', 'Hangi ayakkabılar hoşuna gidiyor? – Şunlar.'], 'welch-'),
        gap('G2', 'dieses', I.form, 'Welches Kleid kaufst du? – ', ' hier.', 'Dieses', ['Dieser', 'Diese'],
          ['Which dress are you buying? – This one here.', 'Какое платье ты покупаешь? – Вот это.', 'Яку сукню ти купуєш? – Ось цю.', 'Hangi elbiseyi alıyorsun? – Şunu.'], 'dies-'),
        gap('G2', 'welchen', I.form, '', ' Pullover findest du schön? – Diesen.', 'Welchen', ['Welcher', 'Welches'],
          ['Which pullover do you think is nice? – This one.', 'Какой свитер тебе кажется красивым? – Этот.', 'Який светр тобі здається гарним? – Цей.', 'Hangi kazağı güzel buluyorsun? – Bunu.'], 'welch-'),
        gap('G2', 'diese', I.form, 'Welche Tasche gehört dir? – ', '.', 'Diese', ['Dieser', 'Dieses'],
          ['Which bag belongs to you? – This one.', 'Какая сумка твоя? – Эта.', 'Яка сумка твоя? – Ця.', 'Hangi çanta senin? – Bu.'], 'dies-'),
        gap('G2', 'diesen', I.form, 'Welchen Schirm nimmst du? – ', ' hier.', 'Diesen', ['Dieser', 'Dieses'],
          ['Which umbrella are you taking? – This one here.', 'Какой зонт ты берёшь? – Вот этот.', 'Яку парасольку ти береш? – Ось цю.', 'Hangi şemsiyeyi alıyorsun? – Şunu.'], 'dies-'),
        sb('G2', 'welchen', I.question, 'Welchen / Mantel / findest / du / schön?',
          ['Which coat do you think is nice?', 'Какое пальто тебе кажется красивым?', 'Яке пальто тобі здається гарним?', 'Hangi paltoyu güzel buluyorsun?']),
      ],
    },
    {
      title: 'gut, besser, am besten',
      t: ['good, better, best', 'хорошо, лучше, лучше всего', 'добре, краще, найкраще', 'iyi, daha iyi, en iyi'],
      card: {
        id: 'p6_komp',
        rule: 'Komparation: gut – besser – am besten. gern – lieber – am liebsten. viel – mehr – am meisten. Der Mantel gefällt mir gut, die Jacke gefällt mir besser, der Pullover gefällt mir am besten. Ich trinke gern Tee, lieber Kaffee und am liebsten Wasser. Tom isst viel, Lea isst mehr, Ben isst am meisten.',
        examples: ['Die Hose steht dir besser.', 'Ich esse lieber Reis.', 'Am liebsten trage ich Jeans.'],
        highlight: null,
        t: [
          'Comparison: gut – besser – am besten (good – better – best). gern – lieber – am liebsten (like doing – prefer – like best). viel – mehr – am meisten (much – more – most). Der Mantel gefällt mir gut, die Jacke gefällt mir besser, der Pullover gefällt mir am besten. Ich trinke gern Tee, lieber Kaffee und am liebsten Wasser. Tom isst viel, Lea isst mehr, Ben isst am meisten.',
          'Степени сравнения: gut – besser – am besten (хорошо – лучше – лучше всего). gern – lieber – am liebsten (охотно – охотнее – охотнее всего). viel – mehr – am meisten (много – больше – больше всего). Der Mantel gefällt mir gut, die Jacke gefällt mir besser, der Pullover gefällt mir am besten. Ich trinke gern Tee, lieber Kaffee und am liebsten Wasser. Tom isst viel, Lea isst mehr, Ben isst am meisten.',
          'Ступені порівняння: gut – besser – am besten (добре – краще – найкраще). gern – lieber – am liebsten (охоче – охочіше – найохочіше). viel – mehr – am meisten (багато – більше – найбільше). Der Mantel gefällt mir gut, die Jacke gefällt mir besser, der Pullover gefällt mir am besten. Ich trinke gern Tee, lieber Kaffee und am liebsten Wasser. Tom isst viel, Lea isst mehr, Ben isst am meisten.',
          'Karşılaştırma: gut – besser – am besten (iyi – daha iyi – en iyi). gern – lieber – am liebsten (severek – daha çok severek – en çok severek). viel – mehr – am meisten (çok – daha çok – en çok). Der Mantel gefällt mir gut, die Jacke gefällt mir besser, der Pullover gefällt mir am besten. Ich trinke gern Tee, lieber Kaffee und am liebsten Wasser. Tom isst viel, Lea isst mehr, Ben isst am meisten.',
        ],
        hint: ['Zwei vergleichen → besser, lieber, mehr. Die Nummer eins → am besten, am liebsten, am meisten.', 'Comparing two → besser, lieber, mehr. Number one → am besten, am liebsten, am meisten.', 'Сравниваем двоих → besser, lieber, mehr. Номер один → am besten, am liebsten, am meisten.', 'Порівнюємо двох → besser, lieber, mehr. Номер один → am besten, am liebsten, am meisten.', 'İki şeyi karşılaştırma → besser, lieber, mehr. Bir numara → am besten, am liebsten, am meisten.'],
      },
      ex: [
        mc('G5', 'besser', I.choose, 'Das Hemd ist gut, aber die Bluse ist noch …', ['besser', 'guter', 'am besten'],
          ['The shirt is good, but the blouse is even better.', 'Рубашка хорошая, но блузка ещё лучше.', 'Сорочка добра, але блузка ще краща.', 'Gömlek iyi, ama bluz daha da iyi.']),
        mc('G5', 'lieber', I.choose, 'Ich trinke gern Tee, aber ich trinke … Kaffee.', ['lieber', 'gerner', 'mehr gern'],
          ['I like drinking tea, but I prefer coffee.', 'Я люблю чай, но кофе я пью охотнее.', 'Я люблю чай, але каву п’ю охочіше.', 'Çay içmeyi severim, ama kahveyi daha çok severim.']),
        mc('G5', 'mehr', I.choose, 'Tom hat zehn Hemden, Paul hat zwanzig Hemden. Paul hat … Hemden.', ['mehr', 'vieler', 'am meisten'],
          ['Tom has ten shirts, Paul has twenty shirts. Paul has more shirts.', 'У Tom десять рубашек, у Paul двадцать. У Paul больше рубашек.', 'У Tom десять сорочок, у Paul двадцять. У Paul більше сорочок.', 'Tom’un on gömleği var, Paul’un yirmi gömleği var. Paul’un daha çok gömleği var.']),
        gap('G5', 'am liebsten', I.comparison, 'Ich esse gern Pizza, lieber Nudeln und am ', ' esse ich Reis.', 'liebsten', ['lieber', 'gernsten'],
          ['I like eating pizza, I prefer pasta, and I like rice best.', 'Я люблю пиццу, макароны люблю больше, а больше всего я люблю рис.', 'Я люблю піцу, макарони люблю більше, а найбільше я люблю рис.', 'Pizzayı severim, makarnayı daha çok severim, en çok da pilavı severim.'], 'gern'),
        gap('G5', 'besser', I.comparison, 'Die Schuhe gefallen mir gut, aber die Stiefel gefallen mir ', '.', 'besser', ['guter', 'am besten'],
          ['I like the shoes, but I like the boots better.', 'Туфли мне нравятся, но сапоги нравятся больше.', 'Туфлі мені подобаються, але чоботи подобаються більше.', 'Ayakkabılar hoşuma gidiyor, ama çizmeler daha çok hoşuma gidiyor.'], 'gut'),
        gap('G5', 'am meisten', I.comparison, 'Im Kurs sprechen alle viel. Aber Emre spricht am ', '.', 'meisten', ['mehr', 'vielsten'],
          ['Everybody in the course talks a lot. But Emre talks the most.', 'На курсе все много говорят. Но Emre говорит больше всех.', 'На курсі всі багато говорять. Але Emre говорить найбільше.', 'Kursta herkes çok konuşuyor. Ama en çok Emre konuşuyor.'], 'viel'),
        gap('G5', 'am besten', I.comparison, 'Welche Jacke steht mir am ', '? – Die hier!', 'besten', ['besser', 'gutesten'],
          ['Which jacket suits me best? – This one!', 'Какая куртка идёт мне больше всего? – Вот эта!', 'Яка куртка личить мені найбільше? – Ось ця!', 'Bana en çok hangi ceket yakışıyor? – Şu!'], 'gut'),
        gap('G5', 'mehr', I.comparison, 'Ich arbeite viel, aber meine Chefin arbeitet noch ', '.', 'mehr', ['vieler', 'am meisten'],
          ['I work a lot, but my boss works even more.', 'Я много работаю, но моя начальница работает ещё больше.', 'Я багато працюю, але моя начальниця працює ще більше.', 'Çok çalışıyorum, ama patronum daha da çok çalışıyor.'], 'viel'),
        gap('G5', 'lieber', I.comparison, 'Fährst du gern Bus? – Nein, ich fahre ', ' Fahrrad.', 'lieber', ['gerner', 'am liebsten'],
          ['Do you like going by bus? – No, I prefer cycling.', 'Ты любишь ездить на автобусе? – Нет, я больше люблю велосипед.', 'Ти любиш їздити автобусом? – Ні, я більше люблю велосипед.', 'Otobüse binmeyi sever misin? – Hayır, bisiklete binmeyi tercih ederim.'], 'gern'),
        sb('G5', 'am liebsten', I.order, 'Am liebsten / trage / ich / Jeans.',
          ['I like wearing jeans best.', 'Больше всего я люблю носить джинсы.', 'Найбільше я люблю носити джинси.', 'En çok kot pantolon giymeyi severim.'],
          { alt: ['Ich trage am liebsten Jeans.', 'Jeans trage ich am liebsten.'] }),
      ],
    },
    {
      title: 'mögen',
      t: ['mögen (to like)', 'mögen (любить, нравиться)', 'mögen (любити, подобатися)', 'mögen (sevmek, hoşlanmak)'],
      card: {
        id: 'p6_moegen',
        rule: 'mögen: ich mag, du magst, er/es/sie mag, wir mögen, ihr mögt, sie/Sie mögen. Im Singular steht a, im Plural ö. ich und er/sie haben keine Endung. Nach mögen steht ein Nomen: Ich mag Rot. Magst du Fisch? Sie mag keine Röcke.',
        examples: ['Ich mag die Farbe Blau.', 'Magst du den Pullover?', 'Wir mögen keine Anzüge.'],
        highlight: 'verb',
        t: [
          'mögen (to like): ich mag, du magst, er/es/sie mag, wir mögen, ihr mögt, sie/Sie mögen. Singular has a, plural has ö. ich and er/sie have no ending. mögen is followed by a noun: Ich mag Rot. Magst du Fisch? Sie mag keine Röcke.',
          'mögen (любить, нравиться): ich mag, du magst, er/es/sie mag, wir mögen, ihr mögt, sie/Sie mögen. В единственном числе a, во множественном ö. У ich и er/sie нет окончания. После mögen стоит существительное: Ich mag Rot. Magst du Fisch? Sie mag keine Röcke.',
          'mögen (любити, подобатися): ich mag, du magst, er/es/sie mag, wir mögen, ihr mögt, sie/Sie mögen. В однині a, у множині ö. У ich та er/sie немає закінчення. Після mögen стоїть іменник: Ich mag Rot. Magst du Fisch? Sie mag keine Röcke.',
          'mögen (sevmek, hoşlanmak): ich mag, du magst, er/es/sie mag, wir mögen, ihr mögt, sie/Sie mögen. Tekilde a, çoğulda ö vardır. ich ve er/sie eksizdir. mögen’den sonra isim gelir: Ich mag Rot. Magst du Fisch? Sie mag keine Röcke.',
        ],
        hint: ['Singular mit a: mag, magst, mag. Plural mit ö: mögen, mögt, mögen.', 'Singular with a: mag, magst, mag. Plural with ö: mögen, mögt, mögen.', 'Единственное число с a: mag, magst, mag. Множественное с ö: mögen, mögt, mögen.', 'Однина з a: mag, magst, mag. Множина з ö: mögen, mögt, mögen.', 'Tekil a ile: mag, magst, mag. Çoğul ö ile: mögen, mögt, mögen.'],
      },
      ex: [
        mc('G6', 'mögen', I.choose, '… du Schokolade? – Ja, sehr!', ['Magst', 'Mag', 'Mögt'],
          ['Do you like chocolate? – Yes, very much!', 'Ты любишь шоколад? – Да, очень!', 'Ти любиш шоколад? – Так, дуже!', 'Çikolata sever misin? – Evet, çok!']),
        mc('G6', 'mögen', I.choose, 'Meine Schwester … keine Röcke. Sie trägt immer Hosen.', ['mag', 'magt', 'mögen'],
          ['My sister does not like skirts. She always wears trousers.', 'Моя сестра не любит юбки. Она всегда носит брюки.', 'Моя сестра не любить спідниці. Вона завжди носить штани.', 'Kız kardeşim etek sevmez. Hep pantolon giyer.']),
        gap('G6', 'mögen', I.verb, 'Ich ', ' die Farbe Grün.', 'mag', ['mage', 'mögen'],
          ['I like the colour green.', 'Мне нравится зелёный цвет.', 'Мені подобається зелений колір.', 'Yeşil rengi severim.'], 'mögen'),
        gap('G6', 'mögen', I.verb, 'Wir ', ' den Sommer. Dann ist es warm.', 'mögen', ['mögt', 'mag'],
          ['We like summer. Then it is warm.', 'Мы любим лето. Тогда тепло.', 'Ми любимо літо. Тоді тепло.', 'Yazı severiz. O zaman hava sıcak olur.'],
          ['like', 'любить', 'любити', 'sevmek']),
        gap('G6', 'mögen', I.verb, 'Kinder, ', ' ihr Spaghetti?', 'mögt', ['mögen', 'magst'],
          ['Children, do you like spaghetti?', 'Дети, вы любите спагетти?', 'Діти, ви любите спагеті?', 'Çocuklar, spagetti sever misiniz?'], 'mögen'),
        gap('G6', 'mögen', I.verb, 'Paul ', ' keinen Fisch. Er isst lieber Fleisch.', 'mag', ['magt', 'magst'],
          ['Paul does not like fish. He prefers meat.', 'Paul не любит рыбу. Он охотнее ест мясо.', 'Paul не любить рибу. Він охочіше їсть м’ясо.', 'Paul balık sevmez. Eti tercih eder.'], 'mögen'),
        gap('G6', 'mögen', I.verb, 'Was ', ' du lieber: Tee oder Kaffee?', 'magst', ['mag', 'mögt'],
          ['What do you prefer: tea or coffee?', 'Что ты любишь больше: чай или кофе?', 'Що ти любиш більше: чай чи каву?', 'Hangisini daha çok seversin: çay mı kahve mi?'], 'mögen'),
        sb('G6', 'mögen', I.question, 'Magst / du / die Farbe / Rot?',
          ['Do you like the colour red?', 'Тебе нравится красный цвет?', 'Тобі подобається червоний колір?', 'Kırmızı rengi sever misin?']),
      ],
    },
    {
      title: 'Im Kaufhaus',
      t: ['In the department store', 'В универмаге', 'В універмазі', 'Büyük mağazada'],
      card: {
        id: 'p6_kaufhaus',
        rule: 'Im Kaufhaus: An der Information fragst du: Entschuldigen Sie bitte, ich suche Stiefel. Wo gibt es die? Wo finde ich Kinderkleidung? Antworten: Da müssen Sie ins Obergeschoss gehen. Die finden Sie im Erdgeschoss. Schuhe gibt es im zweiten Stock. Auf dem Wegweiser steht: UG = Untergeschoss, EG = Erdgeschoss, 1. OG = erstes Obergeschoss.',
        examples: ['Entschuldigen Sie bitte, wo finde ich Mäntel?', 'Herrenkleidung finden Sie im ersten Stock.', 'Die Kasse ist im Erdgeschoss.'],
        highlight: null,
        t: [
          'In the department store: at the information desk you ask: Entschuldigen Sie bitte, ich suche Stiefel. Wo gibt es die? (Where can I get them?) Wo finde ich Kinderkleidung? Answers: Da müssen Sie ins Obergeschoss gehen (you have to go upstairs). Die finden Sie im Erdgeschoss (on the ground floor). Schuhe gibt es im zweiten Stock (on the second floor). On the store guide: UG = basement, EG = ground floor, 1. OG = first floor.',
          'В универмаге: в справочной вы спрашиваете: Entschuldigen Sie bitte, ich suche Stiefel. Wo gibt es die? (Где они продаются?) Wo finde ich Kinderkleidung? Ответы: Da müssen Sie ins Obergeschoss gehen (вам нужно подняться наверх). Die finden Sie im Erdgeschoss (на первом этаже). Schuhe gibt es im zweiten Stock (на третьем этаже по русскому счёту). На указателе: UG = подвальный этаж, EG = первый этаж, 1. OG = второй этаж.',
          'В універмазі: у довідковій ви питаєте: Entschuldigen Sie bitte, ich suche Stiefel. Wo gibt es die? (Де вони продаються?) Wo finde ich Kinderkleidung? Відповіді: Da müssen Sie ins Obergeschoss gehen (вам треба піднятися нагору). Die finden Sie im Erdgeschoss (на першому поверсі). Schuhe gibt es im zweiten Stock (на третьому поверсі за українським рахунком). На вказівнику: UG = підвальний поверх, EG = перший поверх, 1. OG = другий поверх.',
          'Büyük mağazada: Danışmada şöyle sorarsınız: Entschuldigen Sie bitte, ich suche Stiefel. Wo gibt es die? (Bunlar nerede bulunur?) Wo finde ich Kinderkleidung? Cevaplar: Da müssen Sie ins Obergeschoss gehen (üst kata çıkmanız gerekiyor). Die finden Sie im Erdgeschoss (zemin katta). Schuhe gibt es im zweiten Stock (ikinci katta). Kat tabelasında: UG = bodrum kat, EG = zemin kat, 1. OG = birinci kat.',
        ],
        hint: ['Erst höflich fragen: Entschuldigen Sie bitte, ich suche … Dann den Stock merken.', 'First ask politely: Entschuldigen Sie bitte, ich suche … Then remember the floor.', 'Сначала вежливо спросите: Entschuldigen Sie bitte, ich suche … Потом запомните этаж.', 'Спочатку ввічливо запитайте: Entschuldigen Sie bitte, ich suche … Потім запам’ятайте поверх.', 'Önce kibarca sorun: Entschuldigen Sie bitte, ich suche … Sonra katı aklınızda tutun.'],
        hints: {
          sign: ['Lies den Wegweiser: UG = unten, EG = Eingang, OG = oben.', 'Read the store guide: UG = downstairs, EG = entrance level, OG = upstairs.', 'Прочитайте указатель: UG = внизу, EG = этаж входа, OG = наверху.', 'Прочитайте вказівник: UG = унизу, EG = поверх входу, OG = нагорі.', 'Kat tabelasını okuyun: UG = aşağıda, EG = giriş katı, OG = yukarıda.'],
        },
      },
      ex: [
        mc('K3', 'an der Information fragen', I.situation, 'Du bist im Kaufhaus und suchst Schuhe. Du fragst an der Information:', ['Entschuldigen Sie bitte, wo finde ich Schuhe?', 'Hallo, Schuhe!', 'Ich finde keine Schuhe schön.'],
          ['You are in a department store looking for shoes. You ask at the information desk:', 'Вы в универмаге и ищете обувь. Вы спрашиваете в справочной:', 'Ви в універмазі й шукаєте взуття. Ви питаєте в довідковій:', 'Büyük mağazadasınız ve ayakkabı arıyorsunuz. Danışmada soruyorsunuz:']),
        mc('K3', 'Auskunft geben', I.react, '„Entschuldigung, wo gibt es hier Koffer?“', ['Die finden Sie im Untergeschoss.', 'Die kosten 80 Euro.', 'Die gefallen mir.'],
          ['“Excuse me, where can I find suitcases here?”', '«Извините, где здесь продаются чемоданы?»', '«Вибачте, де тут продаються валізи?»', '“Affedersiniz, burada bavul nerede bulunur?”']),
        mc('Z1', 'Wegweiser', I.read, `${SIGN} Du suchst eine Hose für deinen Sohn (6 Jahre). Wohin gehst du?`, ['Ins erste Obergeschoss.', 'Ins Erdgeschoss.', 'Ins Untergeschoss.'],
          ['You are looking for trousers for your son (aged 6). Where do you go?', 'Вы ищете брюки для сына (6 лет). Куда вы пойдёте?', 'Ви шукаєте штани для сина (6 років). Куди ви підете?', 'Oğlunuz (6 yaşında) için pantolon arıyorsunuz. Nereye gidersiniz?'], { h: 'sign' }),
        mc('Z1', 'Wegweiser', I.read, `${SIGN} Wo ist die Information?`, ['Im Erdgeschoss.', 'Im zweiten Obergeschoss.', 'Im Untergeschoss.'],
          ['Where is the information desk?', 'Где находится справочная?', 'Де розташована довідкова?', 'Danışma nerede?'], { h: 'sign' }),
        mc('Z1', 'Wegweiser', I.read, `${SIGN} Was gibt es im Untergeschoss?`, ['Essen und Getränke.', 'Schuhe.', 'Taschen.'],
          ['What is there in the basement?', 'Что есть на подвальном этаже?', 'Що є на підвальному поверсі?', 'Bodrum katta ne var?'], { h: 'sign' }),
        gap('K3', 'suchen', I.verb, 'Entschuldigen Sie bitte, ich ', ' einen Wintermantel. Wo gibt es den?', 'suche', ['finde', 'kaufe'],
          ['Excuse me, I am looking for a winter coat. Where can I get one?', 'Извините, я ищу зимнее пальто. Где оно продаётся?', 'Вибачте, я шукаю зимове пальто. Де воно продається?', 'Affedersiniz, kışlık bir palto arıyorum. Nerede bulunur?'], 'suchen'),
        gap('K3', 'Obergeschoss', I.word, 'Sportschuhe? Da müssen Sie nach oben gehen, ins zweite ', '.', 'Obergeschoss', ['Untergeschoss', 'Erdgeschoss'],
          ['Sports shoes? You have to go upstairs, to the second floor.', 'Спортивная обувь? Вам нужно подняться наверх, на третий этаж.', 'Спортивне взуття? Вам треба піднятися нагору, на третій поверх.', 'Spor ayakkabı mı? Yukarı, ikinci kata çıkmanız gerekiyor.'],
          ['upper floor', 'верхний этаж', 'верхній поверх', 'üst kat']),
        sb('K3', 'an der Information fragen', I.question, 'Wo / finde / ich / Kinderkleidung?',
          ['Where can I find children’s clothes?', 'Где мне найти детскую одежду?', 'Де мені знайти дитячий одяг?', 'Çocuk giysilerini nerede bulabilirim?']),
      ],
    },
    {
      title: 'Kleidung kaufen',
      t: ['Buying clothes', 'Покупка одежды', 'Купівля одягу', 'Giysi satın alma'],
      card: {
        id: 'p6_kaufen',
        rule: 'Kleidung kaufen: Größe: Haben Sie die Hose auch in Größe 40? Ist die Größe so richtig? Die Hose ist zu klein / zu groß / zu lang / zu kurz. Farbe: Haben Sie den Pullover auch in Rot? Preis: Was kostet denn die Jacke? Bezahlen: Wo ist denn die Kasse, bitte? Anprobieren: Kann ich das Hemd anprobieren?',
        examples: ['Haben Sie die Bluse auch in Größe 38?', 'Ist die Hose nicht viel zu lang?', 'Wo ist denn die Kasse, bitte?'],
        highlight: null,
        t: [
          'Buying clothes: size: Haben Sie die Hose auch in Größe 40? (Do you have these in size 40 too?) Ist die Größe so richtig? Die Hose ist zu klein / zu groß / zu lang / zu kurz. Colour: Haben Sie den Pullover auch in Rot? Price: Was kostet denn die Jacke? Paying: Wo ist denn die Kasse, bitte? (Where is the till?) Trying on: Kann ich das Hemd anprobieren?',
          'Покупка одежды: размер: Haben Sie die Hose auch in Größe 40? (У вас есть эти брюки 40-го размера?) Ist die Größe so richtig? Die Hose ist zu klein / zu groß / zu lang / zu kurz. Цвет: Haben Sie den Pullover auch in Rot? Цена: Was kostet denn die Jacke? Оплата: Wo ist denn die Kasse, bitte? (Где касса?) Примерка: Kann ich das Hemd anprobieren?',
          'Купівля одягу: розмір: Haben Sie die Hose auch in Größe 40? (У вас є ці штани 40-го розміру?) Ist die Größe so richtig? Die Hose ist zu klein / zu groß / zu lang / zu kurz. Колір: Haben Sie den Pullover auch in Rot? Ціна: Was kostet denn die Jacke? Оплата: Wo ist denn die Kasse, bitte? (Де каса?) Примірка: Kann ich das Hemd anprobieren?',
          'Giysi satın alma: Beden: Haben Sie die Hose auch in Größe 40? (Bu pantolonun 40 bedeni de var mı?) Ist die Größe so richtig? Die Hose ist zu klein / zu groß / zu lang / zu kurz. Renk: Haben Sie den Pullover auch in Rot? Fiyat: Was kostet denn die Jacke? Ödeme: Wo ist denn die Kasse, bitte? (Kasa nerede?) Deneme: Kann ich das Hemd anprobieren?',
        ],
        hint: ['Größe → in Größe 40. Farbe → in Rot. Preis → Was kostet …? Bezahlen → Kasse.', 'Size → in Größe 40. Colour → in Rot. Price → Was kostet …? Paying → Kasse.', 'Размер → in Größe 40. Цвет → in Rot. Цена → Was kostet …? Оплата → Kasse.', 'Розмір → in Größe 40. Колір → in Rot. Ціна → Was kostet …? Оплата → Kasse.', 'Beden → in Größe 40. Renk → in Rot. Fiyat → Was kostet …? Ödeme → Kasse.'],
      },
      ex: [
        mc('K4', 'nach der Größe fragen', I.situation, 'Die Hose in Größe 38 ist zu klein. Was fragst du die Verkäuferin?', ['Haben Sie die Hose auch in Größe 40?', 'Haben Sie die Hose auch in Rot?', 'Was kostet die Hose?'],
          ['The trousers in size 38 are too small. What do you ask the shop assistant?', 'Брюки 38-го размера вам малы. Что вы спросите у продавщицы?', 'Штани 38-го розміру вам замалі. Що ви запитаєте в продавчині?', '38 beden pantolon size küçük geliyor. Satış elemanına ne sorarsınız?']),
        mc('K4', 'nach der Farbe fragen', I.situation, 'Der Pullover gefällt dir, aber du magst Grün nicht. Was fragst du?', ['Haben Sie den Pullover auch in Blau?', 'Haben Sie den Pullover auch in Größe M?', 'Wo ist die Kasse?'],
          ['You like the pullover, but you do not like green. What do you ask?', 'Свитер вам нравится, но вы не любите зелёный цвет. Что вы спросите?', 'Светр вам подобається, але ви не любите зелений колір. Що ви запитаєте?', 'Kazak hoşunuza gidiyor ama yeşili sevmiyorsunuz. Ne sorarsınız?']),
        mc('K4', 'Preis', I.react, '„Was kostet denn die Jacke?“', ['59 Euro.', 'Größe 42.', 'In Schwarz.'],
          ['“How much is the jacket?”', '«Сколько стоит эта куртка?»', '«Скільки коштує ця куртка?»', '“Ceket ne kadar?”']),
        mc('K4', 'Kasse', I.react, '„Wo ist denn die Kasse, bitte?“', ['Gleich da vorne rechts.', 'Die Kasse kostet nichts.', 'In Größe 38.'],
          ['“Where is the till, please?”', '«Подскажите, пожалуйста, где касса?»', '«Підкажіть, будь ласка, де каса?»', '“Kasa nerede acaba?”']),
        gap('K4', 'Größe', I.word, 'Haben Sie das Hemd auch in ', ' 42? Dieses ist zu klein.', 'Größe', ['Farbe', 'Kasse'],
          ['Do you have the shirt in size 42 too? This one is too small.', 'У вас есть эта рубашка 42-го размера? Эта слишком мала.', 'У вас є ця сорочка 42-го розміру? Ця замала.', 'Bu gömleğin 42 bedeni de var mı? Bu çok küçük.'],
          ['size', 'размер', 'розмір', 'beden']),
        gap('K4', 'Kasse', I.word, 'Ich möchte bezahlen. Wo ist die ', '?', 'Kasse', ['Größe', 'Tasche'],
          ['I would like to pay. Where is the till?', 'Я хочу заплатить. Где касса?', 'Я хочу заплатити. Де каса?', 'Ödeme yapmak istiyorum. Kasa nerede?'],
          ['till, checkout', 'касса', 'каса', 'kasa']),
        gap('K4', 'zu lang', I.word, 'Ich bin klein. Die Hose ist zu ', '.', 'lang', ['kurz', 'teuer'],
          ['I am short. The trousers are too long.', 'Я невысокого роста. Брюки слишком длинные.', 'Я невисокого зросту. Штани задовгі.', 'Boyum kısa. Pantolon çok uzun.'],
          ['long', 'длинный', 'довгий', 'uzun']),
        sb('K4', 'nach der Farbe fragen', I.question, 'Haben / Sie / die Jacke / auch / in Rot?',
          ['Do you have the jacket in red too?', 'У вас есть эта куртка красного цвета?', 'У вас є ця куртка червоного кольору?', 'Bu ceketin kırmızısı da var mı?']),
      ],
    },
  ],
}

export default path
