import { I, asChoice, gap, mc, sb } from '../shared.mjs'

/** A1.2 · Pfad 7 · Feste – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Feste', I.choose, 'Welches Fest feiert man im Frühling mit Eiern?', ['Ostern', 'Silvester', 'Weihnachten'],
      ['Which celebration takes place in spring, with eggs?', 'Какой праздник отмечают весной с яйцами?', 'Яке свято відзначають навесні з яйцями?', 'Hangi kutlama ilkbaharda yumurtalarla yapılır?']),
    mc('K1', 'Monat', I.react, '„In welchem Monat hast du Geburtstag?“', ['Im Juli.', 'Am Juli.', 'Um Juli.'],
      ['“Which month is your birthday in?”', '«В каком месяце у тебя день рождения?»', '«У якому місяці в тебе день народження?»', '“Doğum günün hangi ayda?”']),
    mc('K2', 'Ostern', I.situation, 'Es ist Ostersonntag. Du triffst deine Nachbarin.', ['Frohe Ostern!', 'Frohe Weihnachten!', 'Herzlichen Glückwunsch zur Hochzeit!'],
      ['It is Easter Sunday. You meet your neighbour.', 'Сегодня пасхальное воскресенье. Вы встречаете соседку.', 'Сьогодні великодня неділя. Ви зустрічаєте сусідку.', 'Bugün Paskalya pazarı. Komşunuzla karşılaşıyorsunuz.']),
    mc('K3', 'Anrede formell', I.choose, 'Du schreibst an deinen Chef, Herrn Wolf. Welche Anrede ist formell?', ['Sehr geehrter Herr Wolf,', 'Lieber Wolf,', 'Hallo Wolf,'],
      ['You are writing to your boss, Mr Wolf. Which salutation is formal?', 'Вы пишете своему начальнику, господину Wolf. Какое обращение официальное?', 'Ви пишете своєму начальникові, панові Wolf. Яке звертання офіційне?', 'Patronunuz Wolf Bey’e yazıyorsunuz. Hangi hitap resmîdir?']),
    mc('K4', 'einladen', I.choose, 'Was steht in einer Einladung?', ['Ich lade dich herzlich zu meinem Geburtstag ein.', 'Leider kann ich nicht kommen.', 'Ich gratuliere zur Hochzeit.'],
      ['What does an invitation say?', 'Что пишут в приглашении?', 'Що пишуть у запрошенні?', 'Bir davetiyede ne yazar?']),
    mc('K5', 'zusagen', I.situation, 'Deine Chefin lädt dich zum Abendessen ein. Du hast Zeit und freust dich.', ['Vielen Dank für die Einladung. Ich komme gern.', 'Leider habe ich keine Zeit.', 'Nein danke, ich habe keinen Hunger.'],
      ['Your boss invites you to dinner. You have time and are pleased.', 'Начальница приглашает вас на ужин. У вас есть время, и вы рады.', 'Начальниця запрошує вас на вечерю. У вас є час, і ви раді.', 'Patronunuz sizi akşam yemeğine davet ediyor. Vaktiniz var ve seviniyorsunuz.']),
    mc('Z1', 'Einladung lesen', I.read, 'Einladung: „Wir heiraten! Am 8. Mai um 14 Uhr im Rathaus. Danach feiern wir im Hotel Seeblick. Lena und Tom“ Wo ist die Feier nach der Hochzeit?', ['Im Hotel.', 'Im Rathaus.', 'Bei Lena zu Hause.'],
      ['Where is the party after the wedding?', 'Где будет праздник после свадьбы?', 'Де буде свято після весілля?', 'Düğünden sonra kutlama nerede?']),
    gap('G1', 'Ordinalzahl', I.ordinal, 'Heute ist der ', ' November.', 'elfte', ['elfste', 'elf'],
      ['Today is 11 November.', 'Сегодня одиннадцатое ноября.', 'Сьогодні одинадцяте листопада.', 'Bugün 11 Kasım.'], '11.'),
    gap('G2', 'am + -en', I.ordinal, 'Die Party ist am ', ' Juli.', ['siebten', 'siebenten'], ['siebte', 'siebensten'],
      ['The party is on 7 July.', 'Вечеринка будет седьмого июля.', 'Вечірка буде сьомого липня.', 'Parti 7 Temmuz’da.'], '7.'),
    gap('G3', 'ihn', I.pronoun, 'Das ist mein Bruder. Kennst du ', ' schon?', 'ihn', ['er', 'ihm'],
      ['This is my brother. Do you know him already?', 'Это мой брат. Ты его уже знаешь?', 'Це мій брат. Ти його вже знаєш?', 'Bu benim erkek kardeşim. Onu tanıyor musun?'], 'er'),
    gap('G4', 'denn', I.conjunction, 'Wir bleiben heute zu Hause, ', ' es regnet.', 'denn', ['oder', 'aber'],
      ['We are staying at home today because it is raining.', 'Сегодня мы остаёмся дома, потому что идёт дождь.', 'Сьогодні ми залишаємося вдома, бо йде дощ.', 'Bugün evde kalıyoruz çünkü yağmur yağıyor.'], 'denn / oder / aber', { h: 'which' }),
    gap('G5', 'werden', I.verb, 'Meine Schwester ', ' im August 30.', 'wird', ['werdet', 'wirst'],
      ['My sister will be 30 in August.', 'Моей сестре в августе исполнится 30.', 'Моїй сестрі в серпні виповниться 30.', 'Kız kardeşim ağustosta 30 yaşına giriyor.'], 'werden'),
    sb('G4', 'denn', I.order, 'Ich bleibe zu Hause, / denn / ich / bin / müde.',
      ['I am staying at home because I am tired.', 'Я остаюсь дома, потому что я устал.', 'Я залишаюся вдома, бо я втомився.', 'Evde kalıyorum çünkü yorgunum.']),
  ],
  size: 13,
  test: [
    mc('W1', 'Feste', I.choose, 'Am 24. und 25. Dezember feiern viele Familien dieses Fest.', ['Weihnachten', 'Ostern', 'Silvester'],
      ['Many families celebrate this on 24 and 25 December.', '24 и 25 декабря многие семьи отмечают этот праздник.', '24 і 25 грудня багато родин відзначають це свято.', '24 ve 25 Aralık’ta birçok aile bu günü kutlar.']),
    mc('G1', 'Ordinalzahl', I.choose, 'Wie heißt „der 7.“ als Wort?', ['der siebte', 'der siebenste', 'der siebzigste'],
      ['How do you write “der 7.” as a word?', 'Как пишется словом «der 7.»?', 'Як пишеться словом «der 7.»?', '“der 7.” yazıyla nasıl yazılır?']),
    mc('G2', 'am + Datum', I.choose, 'Wann beginnt der Urlaub? – … dritten August.', ['Am', 'Der', 'Im'],
      ['When does the holiday start? – On 3 August.', 'Когда начинается отпуск? – Третьего августа.', 'Коли починається відпустка? – Третього серпня.', 'Tatil ne zaman başlıyor? – 3 Ağustos’ta.'], { h: 'prep' }),
    mc('G3', 'sie (Plural)', I.choose, 'Wo sind meine Schlüssel? Ich finde … nicht.', ['sie', 'ihn', 'es'],
      ['Where are my keys? I cannot find them.', 'Где мои ключи? Я не могу их найти.', 'Де мої ключі? Я не можу їх знайти.', 'Anahtarlarım nerede? Onları bulamıyorum.'], { h: 'thing' }),
    mc('G4', 'Wortstellung nach denn', I.sentence, 'Mia erklärt den Grund.', ['Ich lerne Deutsch, denn ich lebe in Deutschland.', 'Ich lerne Deutsch, denn lebe ich in Deutschland.', 'Ich lerne Deutsch, denn ich in Deutschland lebe.'],
      ['Mia explains the reason.', 'Mia объясняет причину.', 'Mia пояснює причину.', 'Mia nedenini açıklıyor.']),
    mc('G5', 'werden', I.choose, 'Mein Sohn … im Juli sechs Jahre alt.', ['wird', 'wirst', 'werdet'],
      ['My son will be six years old in July.', 'Моему сыну в июле исполнится шесть лет.', 'Моєму синові в липні виповниться шість років.', 'Oğlum temmuzda altı yaşına giriyor.']),
    mc('K1', 'Geburtstag nennen', I.react, '„Wann hast du Geburtstag?“', ['Am 2. September.', 'Im 2. September.', 'Um 2. September.'],
      ['“When is your birthday?”', '«Когда у тебя день рождения?»', '«Коли в тебе день народження?»', '“Doğum günün ne zaman?”']),
    mc('K2', 'gratulieren', I.situation, 'Deine Nachbarn haben ein Baby bekommen.', ['Herzlichen Glückwunsch!', 'Gute Besserung!', 'Frohe Ostern!'],
      ['Your neighbours have had a baby.', 'У ваших соседей родился ребёнок.', 'У ваших сусідів народилася дитина.', 'Komşularınızın bebeği oldu.']),
    mc('K3', 'Gruß informell', I.choose, 'Du schreibst eine E-Mail an deine Freundin Amira. Welcher Gruß passt am Ende?', ['Liebe Grüße, deine Sara', 'Mit freundlichen Grüßen, Frau Sara', 'Sehr geehrte Amira'],
      ['You are writing an e-mail to your friend Amira. Which closing fits at the end?', 'Вы пишете e-mail своей подруге Amira. Какое прощание подходит в конце?', 'Ви пишете e-mail своїй подрузі Amira. Яке прощання підходить у кінці?', 'Arkadaşınız Amira’ya bir e-posta yazıyorsunuz. Sonda hangi kapanış uygun?']),
    mc('K4', 'einladen', I.situation, 'Du feierst deinen Geburtstag und schreibst an Herrn und Frau Wolf. Ihr sagt „Sie“.', ['Ich lade Sie herzlich zu meiner Geburtstagsfeier ein.', 'Ich lade dich herzlich ein.', 'Ich lade euch ein, Leute!'],
      ['You are celebrating your birthday and write to Mr and Ms Wolf. You say “Sie” to them.', 'Вы празднуете день рождения и пишете господину и госпоже Wolf. Вы с ними на «вы».', 'Ви святкуєте день народження й пишете панові та пані Wolf. Ви з ними на «ви».', 'Doğum gününüzü kutluyorsunuz ve Wolf Bey ile Wolf Hanım’a yazıyorsunuz. Onlara “Sie” diyorsunuz.']),
    mc('K5', 'absagen mit Grund', I.situation, 'Du kannst nicht zur Hochzeit kommen. Du bist an dem Tag im Urlaub.', ['Leider kann ich nicht kommen, denn ich bin im Urlaub.', 'Ich komme gern, denn ich bin im Urlaub.', 'Herzlichen Glückwunsch, ich komme!'],
      ['You cannot come to the wedding. You are on holiday that day.', 'Вы не можете прийти на свадьбу. В этот день вы в отпуске.', 'Ви не можете прийти на весілля. Цього дня ви у відпустці.', 'Düğüne gelemiyorsunuz. O gün tatildesiniz.']),
    mc('Z1', 'Einladung lesen', I.read, 'Einladung: „Hallo Nachbarn! Am Samstag, 5. Juli, machen wir ab 15 Uhr ein Sommerfest im Hof. Bitte bringt Kuchen oder Salat mit. Familie Petrov“ Was sollen die Gäste mitbringen?', ['Etwas zu essen.', 'Getränke.', 'Geschenke.'],
      ['What should the guests bring?', 'Что должны принести гости?', 'Що мають принести гості?', 'Misafirler ne getirmeli?']),
    mc('Z1', 'Text über ein Fest', I.read, 'Olena schreibt: „Mein Lieblingsfest ist Weihnachten. Am Abend essen wir zwölf Gerichte. Die ganze Familie kommt und wir singen Lieder.“ Was macht die Familie?', ['Sie isst zusammen und singt.', 'Sie tanzt bis Mitternacht.', 'Sie sucht Eier im Garten.'],
      ['What does the family do?', 'Что делает семья?', 'Що робить родина?', 'Aile ne yapıyor?'], { c: 'p7_lieblingsfest' }),
    gap('W1', 'Geschenke', I.word, 'Zum Geburtstag habe ich viele ', ' bekommen: Bücher, Blumen und eine Uhr.', 'Geschenke', ['Gäste', 'Grüße'],
      ['I got lots of presents for my birthday: books, flowers and a watch.', 'На день рождения я получил много подарков: книги, цветы и часы.', 'На день народження я отримав багато подарунків: книжки, квіти й годинник.', 'Doğum günümde çok hediye aldım: kitaplar, çiçekler ve bir saat.'],
      ['presents', 'подарки', 'подарунки', 'hediyeler']),
    asChoice(gap('G1', 'Ordinalzahl ab 20', I.ordinal, 'Morgen ist der ', ' April.', 'zwanzigste', ['zwanzigte', 'zwanzig'],
      ['Tomorrow is 20 April.', 'Завтра двадцатое апреля.', 'Завтра двадцяте квітня.', 'Yarın 20 Nisan.'], '20.')),
    asChoice(gap('G1', 'Ordinalzahl', I.ordinal, 'Heute ist der ', ' Mai.', 'fünfte', ['fünfste', 'fünf'],
      ['Today is 5 May.', 'Сегодня пятое мая.', 'Сьогодні п’яте травня.', 'Bugün 5 Mayıs.'], '5.')),
    asChoice(gap('G2', 'am + -en', I.ordinal, 'Meine Mutter hat am ', ' Oktober Geburtstag.', 'zehnten', ['zehnte', 'zehnsten'],
      ['My mother’s birthday is on 10 October.', 'У моей мамы день рождения десятого октября.', 'У моєї мами день народження десятого жовтня.', 'Annemin doğum günü 10 Ekim’de.'], '10.')),
    gap('G2', 'vom … bis zum', I.prep, 'Das Geschäft ist ', ' ersten bis zum sechsten Januar geschlossen.', 'vom', ['am', 'im'],
      ['The shop is closed from 1 to 6 January.', 'Магазин закрыт с первого по шестое января.', 'Магазин зачинений з першого по шосте січня.', 'Dükkân 1’inden 6 Ocak’a kadar kapalı.'], 'am / vom / im', { h: 'prep' }),
    gap('G3', 'euch', I.pronoun, 'Hallo Lea, hallo Ben! Ich möchte ', ' zum Essen einladen.', 'euch', ['ihr', 'uns'],
      ['Hello Lea, hello Ben! I would like to invite you to a meal.', 'Привет, Lea и Ben! Я хочу пригласить вас на обед.', 'Привіт, Lea й Ben! Я хочу запросити вас на обід.', 'Merhaba Lea, merhaba Ben! Sizi yemeğe davet etmek istiyorum.'], 'ihr'),
    gap('G3', 'für + Akkusativ', I.pronoun, 'Der Kuchen ist für ', '. Ich habe heute Geburtstag!', 'mich', ['mir', 'ich'],
      ['The cake is for me. It is my birthday today!', 'Этот пирог для меня. У меня сегодня день рождения!', 'Цей пиріг для мене. У мене сьогодні день народження!', 'Kek benim için. Bugün doğum günüm!'], 'ich'),
    gap('G4', 'denn', I.conjunction, 'Ich nehme den Bus, ', ' mein Auto ist kaputt.', 'denn', ['oder', 'aber'],
      ['I am taking the bus because my car is broken.', 'Я еду на автобусе, потому что моя машина сломалась.', 'Я їду автобусом, бо моя машина зламалася.', 'Otobüse biniyorum çünkü arabam bozuk.'], 'denn / oder / aber', { h: 'which' }),
    gap('G5', 'werden', I.verb, 'Wie alt ', ' du in diesem Jahr?', 'wirst', ['wird', 'werdet'],
      ['How old will you be this year?', 'Сколько лет тебе исполнится в этом году?', 'Скільки років тобі виповниться цього року?', 'Bu yıl kaç yaşına giriyorsun?'], 'werden'),
    gap('K1', 'geboren', I.word, 'Ich bin am 5. Mai 1990 ', '.', 'geboren', ['gekommen', 'geblieben'],
      ['I was born on 5 May 1990.', 'Я родился пятого мая 1990 года.', 'Я народився п’ятого травня 1990 року.', '5 Mayıs 1990’da doğdum.'],
      ['born', 'родился', 'народився', 'doğmuş']),
    gap('K2', 'Weihnachten', I.word, '', ' Weihnachten und ein gutes neues Jahr!', 'Frohe', ['Liebe', 'Viele'],
      ['Merry Christmas and a happy New Year!', 'Счастливого Рождества и хорошего Нового года!', 'Веселого Різдва і щасливого Нового року!', 'Mutlu Noeller ve iyi yıllar!'],
      ['merry, happy', 'радостный, счастливый', 'радісний, щасливий', 'mutlu, neşeli']),
    asChoice(gap('K3', 'Anrede', I.form, '', ' Herr Albers, vielen Dank für Ihre Einladung.', ['Lieber', 'Sehr geehrter'], ['Liebe', 'Sehr geehrte'],
      ['Dear Mr Albers, thank you very much for your invitation.', 'Уважаемый господин Albers, большое спасибо за ваше приглашение.', 'Шановний пане Albers, щиро дякую за ваше запрошення.', 'Sayın Albers Bey, davetiniz için çok teşekkürler.'], 'lieb')),
    asChoice(gap('K4', 'einladen', I.verb, 'Wir machen ein Sommerfest und ', ' euch herzlich ein.', 'laden', ['ladet', 'lädt'],
      ['We are having a summer party and warmly invite you.', 'Мы устраиваем летний праздник и сердечно вас приглашаем.', 'Ми влаштовуємо літнє свято і щиро вас запрошуємо.', 'Bir yaz şenliği yapıyoruz ve sizi içtenlikle davet ediyoruz.'], 'einladen')),
    gap('K5', 'zusagen', I.word, 'Vielen Dank für die Einladung. Ich komme sehr ', '!', ['gern', 'gerne'], ['leider', 'nicht'],
      ['Thank you very much for the invitation. I would love to come!', 'Большое спасибо за приглашение. Я приду с большим удовольствием!', 'Щиро дякую за запрошення. Я прийду з великим задоволенням!', 'Davet için çok teşekkürler. Memnuniyetle gelirim!'],
      ['gladly, with pleasure', 'охотно, с удовольствием', 'охоче, із задоволенням', 'memnuniyetle']),
    sb('G5', 'werden', I.order, 'Oma / wird / am Sonntag / 80 Jahre alt.',
      ['Grandma will be 80 years old on Sunday.', 'В воскресенье бабушке исполнится 80 лет.', 'У неділю бабусі виповниться 80 років.', 'Büyükannem pazar günü 80 yaşına giriyor.'],
      { alt: ['Am Sonntag wird Oma 80 Jahre alt.'] }),
  ],
}

export default check
