import { I, gap, mc, sb } from '../shared.mjs'

const INVITE = 'Einladung: „Liebe Freunde, am 14. Juni werde ich 40! Das möchte ich feiern. Die Party beginnt um 18 Uhr im Café Morgenrot. Bitte gebt bis zum 1. Juni Bescheid. Viele Grüße, eure Dilara“'
const SUGAR = 'Karim schreibt: „Mein Lieblingsfest ist das Zuckerfest. Wir feiern drei Tage. Am ersten Tag besuchen wir meine Großeltern. Die Kinder bekommen Süßigkeiten und Geld. Meine Mutter kocht sehr viel.“'
const NEW_YEAR = 'Hanna schreibt: „Ich mag Silvester am liebsten. Am 31. Dezember kommen meine Freunde. Wir kochen zusammen, tanzen und sehen um Mitternacht das Feuerwerk.“'

/** A1.2 · Pfad 7 · Feste – Lektionen. Wiederholung und Test: p7-check.mjs */
const path = {
  n: 7,
  slug: 'feste',
  title: 'Feste',
  t: ['Celebrations', 'Праздники', 'Свята', 'Kutlamalar'],
  objectives: {
    G1: 'Ordinalzahlen: bis 19. mit -te (der erste, der dritte, der siebte), ab 20. mit -ste (der zwanzigste).',
    G2: 'Das Datum nennen: Heute ist der zweite Mai. Wann? Am zweiten Mai. Vom zweiten bis zum zwanzigsten Mai.',
    G3: 'Personalpronomen im Akkusativ: mich, dich, ihn, es, sie, uns, euch, sie, Sie – auch nach „für“.',
    G4: "Die Konjunktion „denn“ für Gründe: Wir feiern, denn Lars hat Geburtstag.",
    G5: 'Konjugation von werden: ich werde, du wirst, er wird, wir werden, ihr werdet, sie werden – Ich werde 30.',
    K1: 'Über Geburtstage und Jahrestage sprechen: Wann hast du Geburtstag? Ich bin am 19. Januar geboren.',
    K2: 'Gratulieren und Glückwünsche aussprechen: Alles Gute! Herzlichen Glückwunsch! Frohe Weihnachten!',
    K3: 'Briefe und E-Mails beginnen und beenden: Liebe/Lieber …, Viele Grüße, Mit freundlichen Grüßen.',
    K4: 'Jemanden einladen: Ich lade dich ein. Kommst du? Bitte gib bis Freitag Bescheid.',
    K5: 'Eine Einladung annehmen oder absagen und einen Grund nennen.',
    Z1: 'Kann-Ziele: Einladungen und kurze Texte über Feste verstehen.',
    W1: 'Wortschatz: Feste und Glückwünsche.',
  },
  nodes: [
    {
      title: 'Feste im Jahr',
      t: ['Celebrations of the year', 'Праздники в году', 'Свята протягом року', 'Yılın kutlamaları'],
      card: {
        id: 'p7_feste',
        rule: 'Feste: Weihnachten ist im Dezember, Silvester am 31. Dezember, Neujahr am 1. Januar, Ostern im Frühling. Private Feste: der Geburtstag, die Hochzeit. Man feiert eine Party, lädt Gäste ein, bekommt Geschenke und gratuliert.',
        examples: ['An Weihnachten besuchen wir die Familie.', 'Zum Geburtstag bekomme ich Geschenke.', 'Wir feiern Silvester mit Freunden.'],
        highlight: null,
        t: [
          'Celebrations: Weihnachten (Christmas) is in December, Silvester (New Year’s Eve) on 31 December, Neujahr (New Year’s Day) on 1 January, Ostern (Easter) in spring. Private celebrations: der Geburtstag (birthday), die Hochzeit (wedding). People have a party (feiern), invite guests (Gäste einladen), get presents (Geschenke) and congratulate (gratulieren).',
          'Праздники: Weihnachten (Рождество) – в декабре, Silvester (канун Нового года) – 31 декабря, Neujahr (Новый год) – 1 января, Ostern (Пасха) – весной. Личные праздники: der Geburtstag (день рождения), die Hochzeit (свадьба). Люди празднуют (feiern), приглашают гостей (Gäste einladen), получают подарки (Geschenke) и поздравляют (gratulieren).',
          'Свята: Weihnachten (Різдво) – у грудні, Silvester (переддень Нового року) – 31 грудня, Neujahr (Новий рік) – 1 січня, Ostern (Великдень) – навесні. Особисті свята: der Geburtstag (день народження), die Hochzeit (весілля). Люди святкують (feiern), запрошують гостей (Gäste einladen), отримують подарунки (Geschenke) і вітають (gratulieren).',
          'Kutlamalar: Weihnachten (Noel) aralıkta, Silvester (yılbaşı gecesi) 31 Aralık’ta, Neujahr (yeni yılın ilk günü) 1 Ocak’ta, Ostern (Paskalya) ilkbahardadır. Özel kutlamalar: der Geburtstag (doğum günü), die Hochzeit (düğün). İnsanlar kutlama yapar (feiern), misafir davet eder (Gäste einladen), hediye alır (Geschenke) ve tebrik eder (gratulieren).',
        ],
        hint: ['Wann ist das Fest? Was machen die Leute dann?', 'When is the celebration? What do people do then?', 'Когда этот праздник? Что люди делают в этот день?', 'Коли це свято? Що люди роблять цього дня?', 'Bu kutlama ne zaman? İnsanlar o gün ne yapar?'],
      },
      ex: [
        mc('W1', 'Feste', I.choose, 'Am 31. Dezember um Mitternacht beginnt das neue Jahr. Wie heißt dieser Tag?', ['Silvester', 'Ostern', 'Weihnachten'],
          ['On 31 December at midnight the new year begins. What is this day called?', '31 декабря в полночь начинается новый год. Как называется этот день?', '31 грудня опівночі починається новий рік. Як називається цей день?', '31 Aralık’ta gece yarısı yeni yıl başlar. Bu günün adı nedir?']),
        mc('W1', 'Feste', I.choose, 'Zwei Menschen heiraten und feiern mit Familie und Freunden. Wie heißt das Fest?', ['die Hochzeit', 'der Geburtstag', 'das Neujahr'],
          ['Two people get married and celebrate with family and friends. What is the celebration called?', 'Двое женятся и празднуют с семьёй и друзьями. Как называется этот праздник?', 'Двоє одружуються і святкують із родиною та друзями. Як називається це свято?', 'İki kişi evleniyor ve aile ve arkadaşlarıyla kutluyor. Bu kutlamanın adı nedir?']),
        mc('W1', 'Feste', I.choose, 'Welches Fest ist im Dezember?', ['Weihnachten', 'Ostern', 'Karneval'],
          ['Which celebration is in December?', 'Какой праздник бывает в декабре?', 'Яке свято буває у грудні?', 'Hangi kutlama aralık ayındadır?']),
        mc('W1', 'Feste', I.odd, 'Drei Wörter sind Feste, ein Wort nicht.', ['Geschenk', 'Ostern', 'Silvester', 'Weihnachten'], null),
        gap('W1', 'Geschenk', I.word, 'Meine Freundin hat Geburtstag. Ich kaufe ein ', '.', 'Geschenk', ['Fest', 'Jahr'],
          ['It is my friend’s birthday. I am buying a present.', 'У моей подруги день рождения. Я покупаю подарок.', 'У моєї подруги день народження. Я купую подарунок.', 'Arkadaşımın doğum günü. Bir hediye alıyorum.'],
          ['present', 'подарок', 'подарунок', 'hediye']),
        gap('W1', 'feiern', I.verb, 'Am Samstag ', ' wir meinen Geburtstag. Kommst du?', 'feiern', ['feiert', 'feiere'],
          ['On Saturday we are celebrating my birthday. Are you coming?', 'В субботу мы празднуем мой день рождения. Ты придёшь?', 'У суботу ми святкуємо мій день народження. Ти прийдеш?', 'Cumartesi günü doğum günümü kutluyoruz. Geliyor musun?'],
          ['celebrate', 'праздновать', 'святкувати', 'kutlamak']),
        gap('W1', 'Gäste', I.word, 'Zur Party kommen 20 ', '. Wir brauchen viele Stühle.', 'Gäste', ['Geschenke', 'Feste'],
          ['20 guests are coming to the party. We need a lot of chairs.', 'На вечеринку придут 20 гостей. Нам нужно много стульев.', 'На вечірку прийдуть 20 гостей. Нам потрібно багато стільців.', 'Partiye 20 misafir geliyor. Çok sandalyeye ihtiyacımız var.'],
          ['guests', 'гости', 'гості', 'misafirler']),
        gap("W1", "Einladung", I.word, "Ich habe eine ", " zur Hochzeit von Leon und Tom bekommen.", "Einladung", ["Erfahrung","Entschuldigung"], ["I have received an invitation to Leon and Tom’s wedding.","Я получил приглашение на свадьбу Leon и Tom.","Я отримав запрошення на весілля Leon і Tom.","Leon ve Tom’un düğününe bir davetiye aldım."], ["invitation","приглашение","запрошення","davetiye"], {"c":"p7_feste"}),
      ],
    },
    {
      title: 'der erste, der zweite, der dritte',
      t: ['first, second, third', 'первый, второй, третий', 'перший, другий, третій', 'birinci, ikinci, üçüncü'],
      card: {
        id: 'p7_ordinal',
        rule: 'Ordinalzahlen: Von 1 bis 19 kommt -te an die Zahl: der zweite, der vierte, der fünfte, der zehnte, der neunzehnte. Besondere Formen: der erste, der dritte, der siebte, der achte. Ab 20 kommt -ste: der zwanzigste, der einundzwanzigste, der dreißigste. Mit Ziffern schreibt man einen Punkt: der 1. Mai = der erste Mai.',
        examples: ['Heute ist der erste Mai.', 'Der dritte Oktober ist ein Feiertag.', 'Morgen ist der einunddreißigste Dezember.'],
        highlight: null,
        t: [
          'Ordinal numbers: from 1 to 19 add -te to the number: der zweite, der vierte, der fünfte, der zehnte, der neunzehnte. Special forms: der erste (1st), der dritte (3rd), der siebte (7th), der achte (8th). From 20 add -ste: der zwanzigste, der einundzwanzigste, der dreißigste. In figures you write a full stop: der 1. Mai = der erste Mai.',
          'Порядковые числительные: от 1 до 19 к числу добавляется -te: der zweite, der vierte, der fünfte, der zehnte, der neunzehnte. Особые формы: der erste (1-й), der dritte (3-й), der siebte (7-й), der achte (8-й). С 20 добавляется -ste: der zwanzigste, der einundzwanzigste, der dreißigste. Цифрами пишут с точкой: der 1. Mai = der erste Mai.',
          'Порядкові числівники: від 1 до 19 до числа додається -te: der zweite, der vierte, der fünfte, der zehnte, der neunzehnte. Особливі форми: der erste (1-й), der dritte (3-й), der siebte (7-й), der achte (8-й). Від 20 додається -ste: der zwanzigste, der einundzwanzigste, der dreißigste. Цифрами пишуть із крапкою: der 1. Mai = der erste Mai.',
          'Sıra sayıları: 1’den 19’a kadar sayıya -te eklenir: der zweite, der vierte, der fünfte, der zehnte, der neunzehnte. Özel biçimler: der erste (1.), der dritte (3.), der siebte (7.), der achte (8.). 20’den itibaren -ste eklenir: der zwanzigste, der einundzwanzigste, der dreißigste. Rakamla yazarken nokta konur: der 1. Mai = der erste Mai.',
        ],
        hint: ['1.–19. → -te (Achtung: erste, dritte, siebte, achte). Ab 20. → -ste.', '1st–19th → -te (careful: erste, dritte, siebte, achte). From 20th → -ste.', '1–19 → -te (внимание: erste, dritte, siebte, achte). С 20 → -ste.', '1–19 → -te (увага: erste, dritte, siebte, achte). Від 20 → -ste.', '1.–19. → -te (dikkat: erste, dritte, siebte, achte). 20.’den itibaren → -ste.'],
      },
      ex: [
        mc('G1', 'Ordinalzahl', I.choose, 'Wie heißt „der 3.“ als Wort?', ['der dritte', 'der dreite', 'der dreiste'],
          ['How do you write “der 3.” as a word?', 'Как пишется словом «der 3.»?', 'Як пишеться словом «der 3.»?', '“der 3.” yazıyla nasıl yazılır?']),
        mc('G1', 'Ordinalzahl ab 20', I.choose, 'Wie heißt „der 20.“ als Wort?', ['der zwanzigste', 'der zwanzigte', 'der zwanziger'],
          ['How do you write “der 20.” as a word?', 'Как пишется словом «der 20.»?', 'Як пишеться словом «der 20.»?', '“der 20.” yazıyla nasıl yazılır?']),
        mc('G1', 'Ordinalzahl', I.choose, 'Wie heißt „der 1.“ als Wort?', ['der erste', 'der einste', 'der einte'],
          ['How do you write “der 1.” as a word?', 'Как пишется словом «der 1.»?', 'Як пишеться словом «der 1.»?', '“der 1.” yazıyla nasıl yazılır?']),
        gap('G1', 'Ordinalzahl', I.ordinal, 'Heute ist der ', ' Mai.', 'zweite', ['zweiste', 'zwei'],
          ['Today is 2 May.', 'Сегодня второе мая.', 'Сьогодні друге травня.', 'Bugün 2 Mayıs.'], '2.'),
        gap('G1', 'Ordinalzahl', I.ordinal, 'Morgen ist der ', ' Juni.', ['siebte', 'siebente'], ['siebenste', 'sieben'],
          ['Tomorrow is 7 June.', 'Завтра седьмое июня.', 'Завтра сьоме червня.', 'Yarın 7 Haziran.'], '7.'),
        gap('G1', 'Ordinalzahl', I.ordinal, 'Der ', ' Januar ist Neujahr.', 'erste', ['einte', 'einste'],
          ['1 January is New Year’s Day.', 'Первое января – Новый год.', 'Перше січня – Новий рік.', '1 Ocak yeni yılın ilk günüdür.'], '1.'),
        gap('G1', 'Ordinalzahl ab 20', I.ordinal, 'Der ', ' Dezember ist Silvester.', 'einunddreißigste', ['einunddreißigte', 'einunddreißig'],
          ['31 December is New Year’s Eve.', 'Тридцать первое декабря – канун Нового года.', 'Тридцять перше грудня – переддень Нового року.', '31 Aralık yılbaşı gecesidir.'], '31.'),
        gap('G1', 'Ordinalzahl', I.ordinal, 'Übermorgen ist der ', ' März.', 'achte', ['achtte', 'achtste'],
          ['The day after tomorrow is 8 March.', 'Послезавтра восьмое марта.', 'Післязавтра восьме березня.', 'Öbür gün 8 Mart.'], '8.'),
        gap('G1', 'Ordinalzahl', I.ordinal, 'Heute ist der ', ' August. Ich habe Geburtstag!', 'zwölfte', ['zwölfste', 'zwölf'],
          ['Today is 12 August. It is my birthday!', 'Сегодня двенадцатое августа. У меня день рождения!', 'Сьогодні дванадцяте серпня. У мене день народження!', 'Bugün 12 Ağustos. Doğum günüm!'], '12.'),
        gap('G1', 'Ordinalzahl', I.ordinal, 'Der ', ' Oktober ist in Deutschland ein Feiertag.', 'dritte', ['dreite', 'dritste'],
          ['3 October is a public holiday in Germany.', 'Третье октября – праздничный день в Германии.', 'Третє жовтня – святковий день у Німеччині.', '3 Ekim Almanya’da resmî tatildir.'], '3.'),
      ],
    },
    {
      title: 'Am zweiten Mai',
      t: ['On the second of May', 'Второго мая', 'Другого травня', '2 Mayıs’ta'],
      card: {
        id: 'p7_datum',
        rule: 'Das Datum: Welcher Tag ist heute? – Heute ist der zweite Mai. (der + -e) Wann? – Am zweiten Mai. (am + -en) Wie lange? – Vom zweiten bis zum zwanzigsten Mai. (vom … bis zum + -en) Nach am, vom und bis zum hat die Ordinalzahl immer -en.',
        examples: ['Heute ist der zehnte Juli.', 'Ich habe am zehnten Juli Geburtstag.', 'Wir sind vom ersten bis zum fünfzehnten August im Urlaub.'],
        highlight: null,
        t: [
          'The date: what day is it today? – Heute ist der zweite Mai. (der + -e) When? – Am zweiten Mai. (am + -en = on the …) How long? – Vom zweiten bis zum zwanzigsten Mai. (vom … bis zum + -en = from the … to the …) After am, vom and bis zum the ordinal number always ends in -en.',
          'Дата: какое сегодня число? – Heute ist der zweite Mai. (der + -e) Когда? – Am zweiten Mai. (am + -en = второго мая) Как долго? – Vom zweiten bis zum zwanzigsten Mai. (vom … bis zum + -en = со второго по двадцатое) После am, vom и bis zum порядковое числительное всегда оканчивается на -en.',
          'Дата: яке сьогодні число? – Heute ist der zweite Mai. (der + -e) Коли? – Am zweiten Mai. (am + -en = другого травня) Як довго? – Vom zweiten bis zum zwanzigsten Mai. (vom … bis zum + -en = з другого по двадцяте) Після am, vom і bis zum порядковий числівник завжди закінчується на -en.',
          'Tarih: Bugün ayın kaçı? – Heute ist der zweite Mai. (der + -e) Ne zaman? – Am zweiten Mai. (am + -en = 2 Mayıs’ta) Ne kadar süre? – Vom zweiten bis zum zwanzigsten Mai. (vom … bis zum + -en = 2’sinden 20’sine kadar) am, vom ve bis zum’dan sonra sıra sayısı her zaman -en ile biter.',
        ],
        hint: ['der + -e (der zweite). am / vom / bis zum + -en (am zweiten).', 'der + -e (der zweite). am / vom / bis zum + -en (am zweiten = on the second).', 'der + -e (der zweite). am / vom / bis zum + -en (am zweiten) – как «второго».', 'der + -e (der zweite). am / vom / bis zum + -en (am zweiten) – як «другого».', 'der + -e (der zweite). am / vom / bis zum + -en (am zweiten) – “2’sinde”.'],
        hints: {
          prep: ['Ein Tag → am. Von Tag A bis Tag B → vom … bis zum … Ein Monat → im.', 'One day → am. From day A to day B → vom … bis zum … A month → im.', 'Один день → am. С дня А по день Б → vom … bis zum … Месяц → im.', 'Один день → am. З дня А по день Б → vom … bis zum … Місяць → im.', 'Tek gün → am. A gününden B gününe → vom … bis zum … Ay → im.'],
        },
      },
      ex: [
        mc('G2', 'am + Datum', I.choose, 'Wann ist die Party? – … zwölften Mai.', ['Am', 'Der', 'Im'],
          ['When is the party? – On 12 May.', 'Когда вечеринка? – Двенадцатого мая.', 'Коли вечірка? – Дванадцятого травня.', 'Parti ne zaman? – 12 Mayıs’ta.'], { h: 'prep' }),
        mc('G2', 'der + Datum', I.choose, 'Welcher Tag ist heute? – Heute ist … neunte April.', ['der', 'am', 'den'],
          ['What is the date today? – Today is 9 April.', 'Какое сегодня число? – Сегодня девятое апреля.', 'Яке сьогодні число? – Сьогодні дев’яте квітня.', 'Bugün ayın kaçı? – Bugün 9 Nisan.']),
        mc('G2', 'vom … bis zum', I.choose, 'Die Praxis ist … ersten bis zum zehnten August geschlossen.', ['vom', 'am', 'der'],
          ['The practice is closed from 1 to 10 August.', 'Практика закрыта с первого по десятое августа.', 'Практика зачинена з першого по десяте серпня.', 'Muayenehane 1’inden 10 Ağustos’a kadar kapalı.'], { h: 'prep' }),
        gap('G2', 'am + -en', I.ordinal, 'Der Kurs beginnt am ', ' September.', 'ersten', ['erste', 'einsten'],
          ['The course starts on 1 September.', 'Курс начинается первого сентября.', 'Курс починається першого вересня.', 'Kurs 1 Eylül’de başlıyor.'], '1.'),
        gap("G2", "am + -en", I.ordinal, "Leon hat am ", " März Geburtstag.", "dritten", ["dritte","dreiten"], ["Leon’s birthday is on 3 March.","У Leon день рождения третьего марта.","У Leon день народження третього березня.","Leon’un doğum günü 3 Mart’ta."], "3.", {"c":"p7_datum"}),
        gap('G2', 'der + -e', I.ordinal, 'Heute ist der ', ' Februar.', 'vierzehnte', ['vierzehnten', 'vierzehnste'],
          ['Today is 14 February.', 'Сегодня четырнадцатое февраля.', 'Сьогодні чотирнадцяте лютого.', 'Bugün 14 Şubat.'], '14.'),
        gap('G2', 'am + -en', I.ordinal, 'Wir heiraten am ', ' Juni.', 'zwanzigsten', ['zwanzigste', 'zwanzigten'],
          ['We are getting married on 20 June.', 'Мы женимся двадцатого июня.', 'Ми одружуємося двадцятого червня.', '20 Haziran’da evleniyoruz.'], '20.'),
        gap('G2', 'vom … bis zum', I.prep, 'Ich bin ', ' fünften bis zum zwölften Juli in Wien.', 'vom', ['am', 'im'],
          ['I am in Vienna from 5 to 12 July.', 'Я в Вене с пятого по двенадцатое июля.', 'Я у Відні з п’ятого по дванадцяте липня.', '5’inden 12 Temmuz’a kadar Viyana’dayım.'], 'am / vom / im', { h: 'prep' }),
        gap('G2', 'am + Datum', I.prep, 'Die Hochzeit ist ', ' achten Mai.', 'am', ['vom', 'im'],
          ['The wedding is on 8 May.', 'Свадьба будет восьмого мая.', 'Весілля буде восьмого травня.', 'Düğün 8 Mayıs’ta.'], 'am / vom / im', { h: 'prep' }),
        sb('G2', 'am + Datum', I.order, 'Am zweiten Mai / habe / ich / Geburtstag.',
          ['My birthday is on 2 May.', 'У меня день рождения второго мая.', 'У мене день народження другого травня.', 'Doğum günüm 2 Mayıs’ta.'],
          { alt: ['Ich habe am zweiten Mai Geburtstag.'] }),
      ],
    },
    {
      title: 'Wann hast du Geburtstag?',
      t: ['When is your birthday?', 'Когда у тебя день рождения?', 'Коли в тебе день народження?', 'Doğum günün ne zaman?'],
      card: {
        id: 'p7_geburtstag',
        rule: 'Über Geburtstage sprechen: Wann hast du Geburtstag? – Am dreizehnten März. / Ich habe am vierten Januar Geburtstag. Wann bist du geboren? – Ich bin am neunzehnten Januar 1995 geboren. In welchem Monat? – Im Mai. Jahre nennt man ohne „in“: Ich bin 1995 geboren.',
        examples: ['Wann hast du Geburtstag? – Am 4. Januar.', 'Ich bin am 19. Januar geboren.', 'Mein Sohn hat im Mai Geburtstag.'],
        highlight: null,
        t: [
          'Talking about birthdays: Wann hast du Geburtstag? (When is your birthday?) – Am dreizehnten März. / Ich habe am vierten Januar Geburtstag. Wann bist du geboren? – Ich bin am neunzehnten Januar 1995 geboren. In which month? – Im Mai. Years are given without “in”: Ich bin 1995 geboren.',
          'Как говорить о днях рождения: Wann hast du Geburtstag? (Когда у тебя день рождения?) – Am dreizehnten März. / Ich habe am vierten Januar Geburtstag. Wann bist du geboren? – Ich bin am neunzehnten Januar 1995 geboren. В каком месяце? – Im Mai. Год называют без «in»: Ich bin 1995 geboren.',
          'Як говорити про дні народження: Wann hast du Geburtstag? (Коли в тебе день народження?) – Am dreizehnten März. / Ich habe am vierten Januar Geburtstag. Wann bist du geboren? – Ich bin am neunzehnten Januar 1995 geboren. У якому місяці? – Im Mai. Рік називають без «in»: Ich bin 1995 geboren.',
          'Doğum günlerinden söz etme: Wann hast du Geburtstag? (Doğum günün ne zaman?) – Am dreizehnten März. / Ich habe am vierten Januar Geburtstag. Wann bist du geboren? – Ich bin am neunzehnten Januar 1995 geboren. Hangi ayda? – Im Mai. Yıllar “in” olmadan söylenir: Ich bin 1995 geboren.',
        ],
        hint: ['Tag → am. Monat → im. Jahr → ohne Präposition.', 'Day → am. Month → im. Year → no preposition.', 'День → am. Месяц → im. Год → без предлога.', 'День → am. Місяць → im. Рік → без прийменника.', 'Gün → am. Ay → im. Yıl → edatsız.'],
      },
      ex: [
        mc('K1', 'Geburtstag nennen', I.react, '„Wann hast du Geburtstag?“', ['Am 13. März.', 'Im 13. März.', '13 Jahre.'],
          ['“When is your birthday?”', '«Когда у тебя день рождения?»', '«Коли в тебе день народження?»', '“Doğum günün ne zaman?”']),
        mc('K1', 'Geburtsdatum nennen', I.react, '„Wann sind Sie geboren?“', ['Am 19. Januar 1988.', 'In Januar 1988.', 'Seit 1988.'],
          ['“When were you born?”', '«Когда вы родились?»', '«Коли ви народилися?»', '“Ne zaman doğdunuz?”']),
        mc('K1', 'Monat', I.matchQuestion, '„Im Oktober.“', ['In welchem Monat hast du Geburtstag?', 'Wie alt bist du?', 'Wo bist du geboren?'],
          ['“In October.”', '«В октябре».', '«У жовтні».', '“Ekimde.”']),
        gap('K1', 'am + Tag', I.prep, 'Meine Tochter hat ', ' 4. Juli Geburtstag.', 'am', ['im', 'um'],
          ['My daughter’s birthday is on 4 July.', 'У моей дочери день рождения четвёртого июля.', 'У моєї доньки день народження четвертого липня.', 'Kızımın doğum günü 4 Temmuz’da.'], 'am / im / um'),
        gap('K1', 'im + Monat', I.prep, 'Ich habe ', ' Dezember Geburtstag.', 'im', ['am', 'um'],
          ['My birthday is in December.', 'У меня день рождения в декабре.', 'У мене день народження у грудні.', 'Doğum günüm aralıkta.'], 'am / im / um'),
        gap('K1', 'Geburtstag', I.word, 'Wann hast du ', '? – Am 2. Mai.', 'Geburtstag', ['Hochzeit', 'Einladung'],
          ['When is your birthday? – On 2 May.', 'Когда у тебя день рождения? – Второго мая.', 'Коли в тебе день народження? – Другого травня.', 'Doğum günün ne zaman? – 2 Mayıs’ta.'],
          ['birthday', 'день рождения', 'день народження', 'doğum günü']),
        sb('K1', 'nach dem Geburtstag fragen', I.question, 'Wann / hast / du / Geburtstag?',
          ['When is your birthday?', 'Когда у тебя день рождения?', 'Коли в тебе день народження?', 'Doğum günün ne zaman?']),
        sb('K1', 'Geburtsdatum nennen', I.order, 'Ich / bin / am ersten April / geboren.',
          ['I was born on 1 April.', 'Я родился первого апреля.', 'Я народився першого квітня.', '1 Nisan’da doğdum.'],
          { alt: ['Am ersten April bin ich geboren.'] }),
      ],
    },
    {
      title: 'werden',
      t: ['werden (to become, to turn)', 'werden (становиться, исполняться)', 'werden (ставати, виповнюватися)', 'werden (olmak, yaşına girmek)'],
      card: {
        id: 'p7_werden',
        rule: 'werden: ich werde, du wirst, er/es/sie wird, wir werden, ihr werdet, sie/Sie werden. Bei du und er/sie wird e zu i. Mit werden sagst du dein neues Alter: Am Samstag werde ich 30. Mein Sohn wird morgen sechs Jahre alt.',
        examples: ['Ich werde im Mai 25.', 'Wie alt wirst du?', 'Oma wird am Sonntag 80 Jahre alt.'],
        highlight: 'verb',
        t: [
          'werden (to become): ich werde, du wirst, er/es/sie wird, wir werden, ihr werdet, sie/Sie werden. With du and er/sie the e becomes i. With werden you say your new age: Am Samstag werde ich 30 (I will be 30 on Saturday). Mein Sohn wird morgen sechs Jahre alt.',
          'werden (становиться): ich werde, du wirst, er/es/sie wird, wir werden, ihr werdet, sie/Sie werden. У du и er/sie e меняется на i. С werden называют новый возраст: Am Samstag werde ich 30 (в субботу мне исполнится 30). Mein Sohn wird morgen sechs Jahre alt.',
          'werden (ставати): ich werde, du wirst, er/es/sie wird, wir werden, ihr werdet, sie/Sie werden. У du та er/sie e змінюється на i. З werden називають новий вік: Am Samstag werde ich 30 (у суботу мені виповниться 30). Mein Sohn wird morgen sechs Jahre alt.',
          'werden (olmak): ich werde, du wirst, er/es/sie wird, wir werden, ihr werdet, sie/Sie werden. du ve er/sie ile e, i olur. werden ile yeni yaşınızı söylersiniz: Am Samstag werde ich 30 (cumartesi günü 30 yaşına giriyorum). Mein Sohn wird morgen sechs Jahre alt.',
        ],
        hint: ['du wirst, er/sie wird – mit i. Alle anderen Formen mit e.', 'du wirst, er/sie wird – with i. All other forms with e.', 'du wirst, er/sie wird – с i. Все остальные формы с e.', 'du wirst, er/sie wird – з i. Усі інші форми з e.', 'du wirst, er/sie wird – i ile. Diğer bütün biçimler e ile.'],
      },
      ex: [
        mc('G5', 'werden', I.choose, 'Morgen hat Lea Geburtstag. Sie … zehn Jahre alt.', ['wird', 'werdet', 'wirst'],
          ['Tomorrow is Lea’s birthday. She will be ten years old.', 'Завтра у Lea день рождения. Ей исполнится десять лет.', 'Завтра в Lea день народження. Їй виповниться десять років.', 'Yarın Lea’nın doğum günü. On yaşına giriyor.']),
        mc('G5', 'werden', I.choose, 'Wie alt … du im Mai?', ['wirst', 'wird', 'werdest'],
          ['How old will you be in May?', 'Сколько лет тебе исполнится в мае?', 'Скільки років тобі виповниться у травні?', 'Mayısta kaç yaşına giriyorsun?']),
        gap('G5', 'werden', I.verb, 'Am Freitag ', ' ich 40. Das feiern wir!', 'werde', ['wirst', 'werden'],
          ['On Friday I will be 40. We are going to celebrate that!', 'В пятницу мне исполнится 40. Мы это отпразднуем!', 'У п’ятницю мені виповниться 40. Ми це відсвяткуємо!', 'Cuma günü 40 yaşına giriyorum. Bunu kutlayacağız!'], 'werden'),
        gap('G5', 'werden', I.verb, 'Mein Opa ', ' nächste Woche 90 Jahre alt.', 'wird', ['werdet', 'wirt'],
          ['My grandpa will be 90 years old next week.', 'На следующей неделе моему дедушке исполнится 90 лет.', 'Наступного тижня моєму дідусеві виповниться 90 років.', 'Dedem gelecek hafta 90 yaşına giriyor.'], 'werden'),
        gap('G5', 'werden', I.verb, 'Die Zwillinge ', ' am Sonntag fünf.', 'werden', ['werdet', 'wird'],
          ['The twins will be five on Sunday.', 'В воскресенье близнецам исполнится пять.', 'У неділю близнюкам виповниться п’ять.', 'İkizler pazar günü beş yaşına giriyor.'],
          ['become, turn (an age)', 'становиться, исполняться (о возрасте)', 'ставати, виповнюватися (про вік)', 'olmak, … yaşına girmek']),
        gap('G5', 'werden', I.verb, 'Ihr ', ' im Juni beide 18, oder?', 'werdet', ['werden', 'wird'],
          ['You will both be 18 in June, won’t you?', 'Вам обоим в июне исполнится 18, да?', 'Вам обом у червні виповниться 18, так?', 'Haziranda ikiniz de 18 yaşına giriyorsunuz, değil mi?'], 'werden'),
        gap('G5', 'werden', I.verb, 'Du ', ' bald 30. Machst du eine Party?', 'wirst', ['wird', 'werdest'],
          ['You will soon be 30. Are you having a party?', 'Тебе скоро исполнится 30. Ты устроишь вечеринку?', 'Тобі скоро виповниться 30. Ти влаштуєш вечірку?', 'Yakında 30 yaşına giriyorsun. Parti yapacak mısın?'], 'werden'),
        sb('G5', 'werden', I.question, 'Wie alt / wirst / du / am Samstag?',
          ['How old will you be on Saturday?', 'Сколько лет тебе исполнится в субботу?', 'Скільки років тобі виповниться в суботу?', 'Cumartesi günü kaç yaşına giriyorsun?']),
        sb('G5', 'werden', I.order, 'Am Montag / werde / ich / 25 Jahre alt.',
          ['On Monday I will be 25 years old.', 'В понедельник мне исполнится 25 лет.', 'У понеділок мені виповниться 25 років.', 'Pazartesi günü 25 yaşına giriyorum.'],
          { alt: ['Ich werde am Montag 25 Jahre alt.'] }),
      ],
    },
    {
      title: 'mich, dich, ihn',
      t: ['mich, dich, ihn (accusative pronouns)', 'mich, dich, ihn (местоимения в Akkusativ)', 'mich, dich, ihn (займенники в Akkusativ)', 'mich, dich, ihn (Akkusativ zamirleri)'],
      card: {
        id: 'p7_akk',
        rule: 'Personalpronomen im Akkusativ: ich → mich, du → dich, er → ihn, es → es, sie → sie, wir → uns, ihr → euch, sie → sie, Sie → Sie. Die Frage heißt: Wen oder was? Ich liebe dich. Kannst du mich anrufen? Der Kuchen ist lecker. Ich esse ihn. Nach für steht der Akkusativ: für mich, für dich, für ihn, für sie, für uns.',
        examples: ['Ich habe dich sehr lieb.', 'Der Stuhl ist kaputt. Kannst du ihn reparieren?', 'Das Geschenk ist für euch.'],
        highlight: null,
        t: [
          'Personal pronouns in the accusative: ich → mich, du → dich, er → ihn, es → es, sie → sie, wir → uns, ihr → euch, sie → sie, Sie → Sie. The question is: Wen oder was? (whom or what?) Ich liebe dich. Kannst du mich anrufen? Der Kuchen ist lecker. Ich esse ihn. After für comes the accusative: für mich, für dich, für ihn, für sie, für uns.',
          'Личные местоимения в Akkusativ: ich → mich (меня), du → dich (тебя), er → ihn (его), es → es, sie → sie (её), wir → uns (нас), ihr → euch (вас), sie → sie (их), Sie → Sie (Вас). Вопрос: Wen oder was? (кого или что?) Ich liebe dich. Kannst du mich anrufen? Der Kuchen ist lecker. Ich esse ihn. После für стоит Akkusativ: für mich, für dich, für ihn, für sie, für uns.',
          'Особові займенники в Akkusativ: ich → mich (мене), du → dich (тебе), er → ihn (його), es → es, sie → sie (її), wir → uns (нас), ihr → euch (вас), sie → sie (їх), Sie → Sie (Вас). Запитання: Wen oder was? (кого або що?) Ich liebe dich. Kannst du mich anrufen? Der Kuchen ist lecker. Ich esse ihn. Після für стоїть Akkusativ: für mich, für dich, für ihn, für sie, für uns.',
          'Akkusativ’te kişi zamirleri: ich → mich (beni), du → dich (seni), er → ihn (onu, eril), es → es, sie → sie (onu, dişil), wir → uns (bizi), ihr → euch (sizi), sie → sie (onları), Sie → Sie (sizi, resmî). Soru: Wen oder was? (kimi ya da neyi?) Ich liebe dich. Kannst du mich anrufen? Der Kuchen ist lecker. Ich esse ihn. für’den sonra Akkusativ gelir: für mich, für dich, für ihn, für sie, für uns.',
        ],
        hint: ['Wen oder was? → Akkusativ: mich, dich, ihn, es, sie, uns, euch, sie.', 'Wen oder was? → accusative: mich, dich, ihn, es, sie, uns, euch, sie.', 'Wen oder was? (кого или что?) → Akkusativ: mich, dich, ihn, es, sie, uns, euch, sie.', 'Wen oder was? (кого або що?) → Akkusativ: mich, dich, ihn, es, sie, uns, euch, sie.', 'Wen oder was? (kimi ya da neyi?) → Akkusativ: mich, dich, ihn, es, sie, uns, euch, sie.'],
        hints: {
          thing: ['Auch Sachen haben ein Pronomen: der → ihn, das → es, die → sie.', 'Things have pronouns too: der → ihn, das → es, die → sie.', 'У предметов тоже есть местоимения: der → ihn, das → es, die → sie.', 'У предметів теж є займенники: der → ihn, das → es, die → sie.', 'Eşyaların da zamiri vardır: der → ihn, das → es, die → sie.'],
        },
      },
      ex: [
        mc('G3', 'mich', I.choose, 'Ich habe morgen Geburtstag. Rufst du … an?', ['mich', 'mir', 'ich'],
          ['It is my birthday tomorrow. Will you call me?', 'У меня завтра день рождения. Ты мне позвонишь?', 'У мене завтра день народження. Ти мені зателефонуєш?', 'Yarın doğum günüm. Beni arar mısın?']),
        mc('G3', 'ihn', I.choose, 'Der Kuchen ist lecker. Hast du … gebacken?', ['ihn', 'er', 'ihm'],
          ['The cake is delicious. Did you bake it?', 'Пирог очень вкусный. Это ты его испекла?', 'Пиріг дуже смачний. Це ти його спекла?', 'Kek çok lezzetli. Onu sen mi yaptın?'], { h: 'thing' }),
        mc('G3', 'für + Akkusativ', I.choose, 'Das Geschenk ist für …, Papa. Alles Gute!', ['dich', 'dir', 'du'],
          ['The present is for you, Dad. All the best!', 'Этот подарок для тебя, папа. Всего хорошего!', 'Цей подарунок для тебе, тату. Усього найкращого!', 'Hediye senin için, baba. Her şey gönlünce olsun!']),
        gap('G3', 'ihn', I.pronoun, 'Wo ist Paul? Ich sehe ', ' nicht.', 'ihn', ['er', 'ihm'],
          ['Where is Paul? I cannot see him.', 'Где Paul? Я его не вижу.', 'Де Paul? Я його не бачу.', 'Paul nerede? Onu göremiyorum.'], 'er'),
        gap('G3', 'sie', I.pronoun, 'Die Blumen sind schön. Ich kaufe ', ' für Oma.', 'sie', ['ihn', 'ihnen'],
          ['The flowers are lovely. I am buying them for Grandma.', 'Цветы красивые. Я покупаю их для бабушки.', 'Квіти гарні. Я купую їх для бабусі.', 'Çiçekler güzel. Onları büyükannem için alıyorum.'], 'ihn / es / sie', { h: 'thing' }),
        gap('G3', 'uns', I.pronoun, 'Wir machen eine Party. Besucht ihr ', '?', 'uns', ['wir', 'euch'],
          ['We are having a party. Are you coming to see us?', 'Мы устраиваем вечеринку. Вы к нам придёте?', 'Ми влаштовуємо вечірку. Ви до нас прийдете?', 'Bir parti veriyoruz. Bizi ziyaret eder misiniz?'], 'wir'),
        gap("G3", "euch", I.pronoun, "Tim und Milan, ich lade ", " zu meiner Party ein.", "euch", ["ihr","uns"], ["Tim and Milan, I am inviting you to my party.","Tim и Milan, я приглашаю вас на свою вечеринку.","Tim і Milan, я запрошую вас на свою вечірку.","Tim ve Milan, sizi partime davet ediyorum."], "ihr", {"c":"p7_akk"}),
        gap('G3', 'es', I.pronoun, 'Das Fahrrad ist kaputt. Kannst du ', ' bitte reparieren?', 'es', ['ihn', 'sie'],
          ['The bike is broken. Can you repair it, please?', 'Велосипед сломался. Ты можешь его починить, пожалуйста?', 'Велосипед зламався. Ти можеш його полагодити, будь ласка?', 'Bisiklet bozuk. Onu tamir edebilir misin lütfen?'], 'ihn / es / sie', { h: 'thing' }),
        gap("G3", "für + Akkusativ", I.pronoun, "Hier ist ein Brief für ", ", Herr Kaya.", "Sie", ["Ihnen","dich"], ["Here is a letter for you, Mr Kaya.","Вот письмо для вас, господин Kaya.","Ось лист для вас, пане Kaya.","Burada sizin için bir mektup var, Kaya Bey."], "Sie / Ihnen", {"c":"p7_akk"}),
        sb('G3', 'dich', I.order, 'Ich / habe / dich / sehr lieb.',
          ['I love you very much.', 'Я тебя очень люблю.', 'Я тебе дуже люблю.', 'Seni çok seviyorum.']),
      ],
    },
    {
      title: 'denn',
      t: ['denn (because)', 'denn (потому что)', 'denn (бо, тому що)', 'denn (çünkü)'],
      card: {
  "id": "p7_denn",
  "rule": "denn = ein Grund. denn verbindet zwei Hauptsätze. Vor denn steht ein Komma. Nach denn bleibt die Wortstellung normal: Subjekt, dann Verb. Wir feiern. Lars hat Geburtstag. → Wir feiern, denn Lars hat Geburtstag. Ich kann nicht kommen, denn ich muss arbeiten.",
  "examples": [
    "Ich komme nicht, denn ich bin krank.",
    "Wir kaufen Blumen, denn Opa hat Geburtstag.",
    "Er lernt viel, denn er hat morgen eine Prüfung."
  ],
  "highlight": null,
  "t": [
    "denn = a reason (because). denn joins two main clauses. There is a comma before denn. After denn the word order stays normal: subject, then verb. Wir feiern. Lars hat Geburtstag. → Wir feiern, denn Lars hat Geburtstag. Ich kann nicht kommen, denn ich muss arbeiten.",
    "denn = причина (потому что). denn соединяет два главных предложения. Перед denn ставится запятая. После denn порядок слов обычный: подлежащее, потом глагол. Wir feiern. Lars hat Geburtstag. → Wir feiern, denn Lars hat Geburtstag. Ich kann nicht kommen, denn ich muss arbeiten.",
    "denn = причина (бо, тому що). denn з’єднує два головні речення. Перед denn ставиться кома. Після denn порядок слів звичайний: підмет, потім дієслово. Wir feiern. Lars hat Geburtstag. → Wir feiern, denn Lars hat Geburtstag. Ich kann nicht kommen, denn ich muss arbeiten.",
    "denn = bir neden (çünkü). denn iki ana cümleyi bağlar. denn’den önce virgül konur. denn’den sonra kelime sırası değişmez: özne, sonra fiil. Wir feiern. Lars hat Geburtstag. → Wir feiern, denn Lars hat Geburtstag. Ich kann nicht kommen, denn ich muss arbeiten."
  ],
  "hint": [
    "denn + Subjekt + Verb: …, denn ich habe keine Zeit.",
    "denn + subject + verb: …, denn ich habe keine Zeit.",
    "denn + подлежащее + глагол: …, denn ich habe keine Zeit.",
    "denn + підмет + дієслово: …, denn ich habe keine Zeit.",
    "denn + özne + fiil: …, denn ich habe keine Zeit."
  ],
  "hints": {
    "which": [
      "Ein Grund → denn. Ein Gegensatz → aber. Zwei Möglichkeiten → oder.",
      "A reason → denn. A contrast → aber. Two options → oder.",
      "Причина → denn. Противопоставление → aber. Два варианта → oder.",
      "Причина → denn. Протиставлення → aber. Два варіанти → oder.",
      "Neden → denn. Karşıtlık → aber. İki seçenek → oder."
    ]
  }
},
      ex: [
        mc('G4', 'denn', I.choose, 'Ich kann nicht zur Party kommen, … ich bin krank.', ['denn', 'oder', 'aber'],
          ['I cannot come to the party because I am ill.', 'Я не могу прийти на вечеринку, потому что я болею.', 'Я не можу прийти на вечірку, бо я хворію.', 'Partiye gelemiyorum çünkü hastayım.'], { h: 'which' }),
        mc('G4', 'Wortstellung nach denn', I.sentence, 'Emre sagt ab.', ['Ich komme nicht, denn ich muss arbeiten.', 'Ich komme nicht, denn muss ich arbeiten.', 'Ich komme nicht, denn ich arbeiten muss.'],
          ['Emre says he cannot come.', 'Emre отказывается от приглашения.', 'Emre відмовляється від запрошення.', 'Emre gelemeyeceğini söylüyor.']),
        mc("G4", "Grund nennen", I.choose, "Welcher Satz nennt einen Grund?", ["Wir feiern, denn Milan wird 18.","Wir feiern, aber Milan ist müde.","Wir feiern und Milan tanzt."], ["Which sentence gives a reason?","В каком предложении названа причина?","У якому реченні названо причину?","Hangi cümle bir neden bildiriyor?"], {"h":"which","c":"p7_denn","sitovOptionOrder":["Wir feiern, denn Milan wird 18.","Wir feiern, aber Milan ist müde.","Wir feiern und Milan tanzt."]}),
        gap('G4', 'denn', I.conjunction, 'Ich kaufe Blumen, ', ' meine Mutter hat Geburtstag.', 'denn', ['aber', 'oder'],
          ['I am buying flowers because it is my mother’s birthday.', 'Я покупаю цветы, потому что у моей мамы день рождения.', 'Я купую квіти, бо в моєї мами день народження.', 'Çiçek alıyorum çünkü annemin doğum günü.'], 'denn / aber / oder', { h: 'which' }),
        gap('G4', 'aber', I.conjunction, 'Ich möchte kommen, ', ' ich habe leider keine Zeit.', 'aber', ['denn', 'oder'],
          ['I would like to come, but unfortunately I have no time.', 'Я хотел бы прийти, но, к сожалению, у меня нет времени.', 'Я хотів би прийти, але, на жаль, у мене немає часу.', 'Gelmek isterim ama maalesef vaktim yok.'], 'denn / aber / oder', { h: 'which' }),
        gap("G4", "denn", I.conjunction, "Leon ist glücklich, ", " er hat viele Geschenke bekommen.", "denn", ["aber","oder"], ["Leon is happy because he got lots of presents.","Leon счастлив, потому что получил много подарков.","Leon щасливий, бо отримав багато подарунків.","Leon mutlu çünkü çok hediye aldı."], "denn / aber / oder", {"h":"which","c":"p7_denn"}),
        gap('G4', 'Wortstellung nach denn', I.verb, 'Wir bleiben zu Hause, denn es ', ' sehr kalt.', 'ist', ['sein', 'sind'],
          ['We are staying at home because it is very cold.', 'Мы остаёмся дома, потому что очень холодно.', 'Ми залишаємося вдома, бо дуже холодно.', 'Evde kalıyoruz çünkü hava çok soğuk.'], 'sein'),
        sb('G4', 'denn', I.order, 'Ich komme nicht, / denn / ich / bin / krank.',
          ['I am not coming because I am ill.', 'Я не приду, потому что я болею.', 'Я не прийду, бо я хворію.', 'Gelmiyorum çünkü hastayım.']),
        sb('G4', 'denn', I.order, 'Wir feiern, / denn / Opa / wird / 80.',
          ['We are celebrating because Grandpa is turning 80.', 'Мы празднуем, потому что дедушке исполняется 80.', 'Ми святкуємо, бо дідусеві виповнюється 80.', 'Kutlama yapıyoruz çünkü dedem 80 yaşına giriyor.']),
      ],
    },
    {
      title: 'Alles Gute!',
      t: ['All the best!', 'Всего хорошего!', 'Усього найкращого!', 'Her şey gönlünce olsun!'],
      card: {
        id: 'p7_glueck',
        rule: 'Glückwünsche: Geburtstag: Alles Gute zum Geburtstag! Alles Liebe! Herzlichen Glückwunsch! Hochzeit: Ich gratuliere zur Hochzeit. Wir wünschen euch viel Glück. Weihnachten: Frohe Weihnachten! Ostern: Frohe Ostern! Silvester und Neujahr: Ein gutes neues Jahr! Wünsche: Ich wünsche dir viel Glück, Freude und Gesundheit.',
        examples: ['Herzlichen Glückwunsch zum Geburtstag!', 'Wir gratulieren zur Hochzeit.', 'Frohe Weihnachten und ein gutes neues Jahr!'],
        highlight: null,
        t: [
          'Good wishes: birthday: Alles Gute zum Geburtstag! Alles Liebe! Herzlichen Glückwunsch! (Congratulations!) Wedding: Ich gratuliere zur Hochzeit. Wir wünschen euch viel Glück. Christmas: Frohe Weihnachten! Easter: Frohe Ostern! New Year: Ein gutes neues Jahr! Wishes: Ich wünsche dir viel Glück, Freude und Gesundheit (luck, joy and health).',
          'Поздравления: день рождения: Alles Gute zum Geburtstag! Alles Liebe! Herzlichen Glückwunsch! (Поздравляю!) Свадьба: Ich gratuliere zur Hochzeit. Wir wünschen euch viel Glück. Рождество: Frohe Weihnachten! Пасха: Frohe Ostern! Новый год: Ein gutes neues Jahr! Пожелания: Ich wünsche dir viel Glück, Freude und Gesundheit (счастья, радости и здоровья).',
          'Вітання: день народження: Alles Gute zum Geburtstag! Alles Liebe! Herzlichen Glückwunsch! (Вітаю!) Весілля: Ich gratuliere zur Hochzeit. Wir wünschen euch viel Glück. Різдво: Frohe Weihnachten! Великдень: Frohe Ostern! Новий рік: Ein gutes neues Jahr! Побажання: Ich wünsche dir viel Glück, Freude und Gesundheit (щастя, радості та здоров’я).',
          'İyi dilekler: Doğum günü: Alles Gute zum Geburtstag! Alles Liebe! Herzlichen Glückwunsch! (Tebrikler!) Düğün: Ich gratuliere zur Hochzeit. Wir wünschen euch viel Glück. Noel: Frohe Weihnachten! Paskalya: Frohe Ostern! Yeni yıl: Ein gutes neues Jahr! Dilekler: Ich wünsche dir viel Glück, Freude und Gesundheit (mutluluk, sevinç ve sağlık).',
        ],
        hint: ['Welches Fest ist es? Geburtstag, Hochzeit, Weihnachten, Ostern oder Neujahr?', 'Which celebration is it? Birthday, wedding, Christmas, Easter or New Year?', 'Какой это праздник? День рождения, свадьба, Рождество, Пасха или Новый год?', 'Яке це свято? День народження, весілля, Різдво, Великдень чи Новий рік?', 'Hangi kutlama? Doğum günü, düğün, Noel, Paskalya ya da yeni yıl?'],
      },
      ex: [
        mc('K2', 'zum Geburtstag gratulieren', I.situation, 'Deine Kollegin hat heute Geburtstag.', ['Herzlichen Glückwunsch zum Geburtstag!', 'Frohe Weihnachten!', 'Gute Besserung!'],
          ['It is your colleague’s birthday today.', 'У вашей коллеги сегодня день рождения.', 'У вашої колеги сьогодні день народження.', 'İş arkadaşınızın bugün doğum günü.']),
        mc('K2', 'Weihnachten', I.situation, 'Es ist der 24. Dezember. Du triffst deinen Nachbarn.', ['Frohe Weihnachten!', 'Frohe Ostern!', 'Alles Gute zum Geburtstag!'],
          ['It is 24 December. You meet your neighbour.', 'Сегодня 24 декабря. Вы встречаете соседа.', 'Сьогодні 24 грудня. Ви зустрічаєте сусіда.', 'Bugün 24 Aralık. Komşunuzla karşılaşıyorsunuz.']),
        mc('K2', 'zur Hochzeit gratulieren', I.situation, 'Deine Freunde heiraten.', ['Ich gratuliere zur Hochzeit!', 'Ein gutes neues Jahr!', 'Gute Reise!'],
          ['Your friends are getting married.', 'Ваши друзья женятся.', 'Ваші друзі одружуються.', 'Arkadaşlarınız evleniyor.']),
        mc('K2', 'Neujahr', I.situation, 'Es ist der 1. Januar. Was sagst du?', ['Ein gutes neues Jahr!', 'Frohe Ostern!', 'Gute Nacht!'],
          ['It is 1 January. What do you say?', 'Сегодня 1 января. Что вы скажете?', 'Сьогодні 1 січня. Що ви скажете?', 'Bugün 1 Ocak. Ne dersiniz?']),
        gap('K2', 'Alles Gute', I.word, 'Alles ', ' zum Geburtstag!', ['Gute', 'Liebe'], ['Frohe', 'Herzliche'],
          ['Happy birthday! All the best!', 'Всего хорошего в день рождения!', 'Усього найкращого в день народження!', 'Doğum günün kutlu olsun!'],
          ['good (all the best)', 'хорошее (всего хорошего)', 'добре (усього найкращого)', 'iyi (her şey gönlünce olsun)']),
        gap('K2', 'Herzlichen Glückwunsch', I.word, 'Herzlichen ', ' zur Hochzeit!', 'Glückwunsch', ['Geburtstag', 'Gesundheit'],
          ['Congratulations on your wedding!', 'Поздравляю со свадьбой!', 'Вітаю з весіллям!', 'Düğününüz için tebrikler!'],
          ['congratulations', 'поздравление', 'привітання', 'tebrik']),
        gap('K2', 'Wünsche', I.word, 'Ich wünsche dir viel Glück und ', '. Bleib gesund!', 'Gesundheit', ['Geburtstag', 'Hochzeit'],
          ['I wish you lots of luck and good health. Stay healthy!', 'Желаю тебе счастья и здоровья. Не болей!', 'Бажаю тобі щастя та здоров’я. Не хворій!', 'Sana bol şans ve sağlık diliyorum. Sağlıklı kal!'],
          ['health', 'здоровье', 'здоров’я', 'sağlık']),
        gap('K2', 'gratulieren', I.verb, 'Wir ', ' zum Geburtstag! Alles Liebe!', 'gratulieren', ['gratuliert', 'gratuliere'],
          ['We congratulate you on your birthday! Lots of love!', 'Поздравляем с днём рождения! Всего самого доброго!', 'Вітаємо з днем народження! Усього найкращого!', 'Doğum gününü kutluyoruz! Sevgilerle!'],
          ['congratulate', 'поздравлять', 'вітати', 'tebrik etmek']),
      ],
    },
    {
      title: "Liebe …, lieber …",
      t: ["Dear …, dear …","Дорогая …, дорогой …","Люба …, любий …","Sevgili …, sevgili …"],
      card: {
  "id": "p7_brief",
  "rule": "Briefe und E-Mails: Anrede informell: Liebe …, / Lieber …, / Hallo Milan, Anrede formell: Sehr geehrte Frau …, / Sehr geehrter Herr …, Nach der Anrede schreibt man klein weiter. Gruß informell: Viele Grüße / Herzliche Grüße / Liebe Grüße. Gruß formell: Mit freundlichen Grüßen.",
  "examples": [
    "Liebe Oma, vielen Dank für das Geschenk!",
    "Sehr geehrter Herr Brandt, ich lade Sie herzlich ein.",
    "Viele Grüße, dein Leon"
  ],
  "highlight": null,
  "t": [
    "Letters and e-mails: informal salutation: Liebe …, / Lieber …, / Hallo Milan, Formal salutation: Sehr geehrte Frau …, / Sehr geehrter Herr …, After the salutation you continue in lower case. Informal closing: Viele Grüße / Herzliche Grüße / Liebe Grüße. Formal closing: Mit freundlichen Grüßen.",
    "Письма и e-mail: неформальное обращение: Liebe …, / Lieber …, / Hallo Milan, Официальное обращение: Sehr geehrte Frau …, / Sehr geehrter Herr …, После обращения текст продолжают с маленькой буквы. Неформальное прощание: Viele Grüße / Herzliche Grüße / Liebe Grüße. Официальное: Mit freundlichen Grüßen.",
    "Листи та e-mail: неформальне звертання: Liebe …, / Lieber …, / Hallo Milan, Офіційне звертання: Sehr geehrte Frau …, / Sehr geehrter Herr …, Після звертання текст продовжують із малої літери. Неформальне прощання: Viele Grüße / Herzliche Grüße / Liebe Grüße. Офіційне: Mit freundlichen Grüßen.",
    "Mektuplar ve e-postalar: Samimi hitap: Liebe …, / Lieber …, / Hallo Milan, Resmî hitap: Sehr geehrte Frau …, / Sehr geehrter Herr …, Hitaptan sonra küçük harfle devam edilir. Samimi kapanış: Viele Grüße / Herzliche Grüße / Liebe Grüße. Resmî kapanış: Mit freundlichen Grüßen."
  ],
  "hint": [
    "Frau → Liebe … Mann → Lieber … Formell → Sehr geehrte/r … und Mit freundlichen Grüßen.",
    "Woman → Liebe … Man → Lieber … Formal → Sehr geehrte/r … and Mit freundlichen Grüßen.",
    "Женщина → Liebe … Мужчина → Lieber … Официально → Sehr geehrte/r … и Mit freundlichen Grüßen.",
    "Жінка → Liebe … Чоловік → Lieber … Офіційно → Sehr geehrte/r … і Mit freundlichen Grüßen.",
    "Kadın → Liebe … Erkek → Lieber … Resmî → Sehr geehrte/r … ve Mit freundlichen Grüßen."
  ]
},
      ex: [
        mc('K3', 'Anrede', I.choose, 'Du schreibst eine E-Mail an deinen Freund Jonas. Wie beginnst du?', ['Lieber Jonas,', 'Liebe Jonas,', 'Sehr geehrter Herr Jonas,'],
          ['You are writing an e-mail to your friend Jonas. How do you begin?', 'Вы пишете e-mail своему другу Jonas. Как вы начнёте?', 'Ви пишете e-mail своєму другові Jonas. Як ви почнете?', 'Arkadaşınız Jonas’a bir e-posta yazıyorsunuz. Nasıl başlarsınız?']),
        mc('K3', 'Gruß formell', I.choose, 'Du schreibst einen Brief an das Bürgeramt. Wie endet der Brief?', ['Mit freundlichen Grüßen', 'Liebe Grüße und Küsse', 'Tschüs, bis bald'],
          ['You are writing a letter to the citizens’ office. How does the letter end?', 'Вы пишете письмо в бюргерамт. Как заканчивается письмо?', 'Ви пишете лист до бюргерамту. Як закінчується лист?', 'Vatandaşlık bürosuna bir mektup yazıyorsunuz. Mektup nasıl biter?']),
        mc('K3', 'Anrede', I.choose, 'Du schreibst eine Karte an deine Tante Olga. Welche Anrede passt?', ['Liebe Olga,', 'Lieber Olga,', 'Sehr geehrte Frau,'],
          ['You are writing a card to your aunt Olga. Which salutation fits?', 'Вы пишете открытку своей тёте Olga. Какое обращение подходит?', 'Ви пишете листівку своїй тітці Olga. Яке звертання підходить?', 'Teyzeniz Olga’ya bir kart yazıyorsunuz. Hangi hitap uygun?']),
        gap('K3', 'Lieber', I.form, '', ' Paul, vielen Dank für deine Einladung!', 'Lieber', ['Liebe', 'Liebes'],
          ['Dear Paul, thank you very much for your invitation!', 'Дорогой Paul, большое спасибо за приглашение!', 'Любий Paul, щиро дякую за запрошення!', 'Sevgili Paul, davetin için çok teşekkürler!'], 'lieb'),
        gap("K3", "Liebe", I.form, "Die weibliche Form der informellen Anrede „Lieber“ lautet: ", ".", "Liebe", ["Lieber","Lieben"], ["The female form of the informal salutation Lieber is …","Женская форма неофициального обращения Lieber — …","Жіноча форма неофіційного звертання Lieber — …","Samimi hitap Lieber sözcüğünün kadın biçimi …"], "lieb", {"c":"p7_brief"}),
        gap("K3", "Gruß informell", I.word, "Bis bald und viele ", ", dein Milan", "Grüße", ["Gäste","Geschenke"], ["See you soon and best wishes, your Milan","До скорой встречи и большой привет, твой Milan","До скорої зустрічі й щирі вітання, твій Milan","Yakında görüşmek üzere, selamlar, Milan’ın"], ["greetings, regards","приветы","вітання","selamlar"], {"c":"p7_brief"}),
        gap("K3", "Gruß formell", I.form, "Sehr geehrter Herr Lindner, vielen Dank für Ihre E-Mail. Mit freundlichen ", ", Emre Demir", "Grüßen", ["Grüße","Gruß"], ["Dear Mr Lindner, thank you for your e-mail. Yours sincerely, Emre Demir","Уважаемый господин Lindner, спасибо за ваш e-mail. С уважением, Emre Demir","Шановний пане Lindner, дякую за ваш e-mail. З повагою, Emre Demir","Sayın Lindner Bey, e-postanız için teşekkürler. Saygılarımla, Emre Demir"], "Gruß", {"c":"p7_brief"}),
      ],
    },
    {
      title: 'Ich lade dich ein',
      t: ['I am inviting you', 'Я тебя приглашаю', 'Я тебе запрошую', 'Seni davet ediyorum'],
      card: {
        id: 'p7_einladen',
        rule: 'Einladen: Ich habe Geburtstag. Am Samstag werde ich 30. Ich möchte meinen Geburtstag feiern und lade dich herzlich ein. Ich lade Sie zu meiner Party ein. Kommst du? Kannst du kommen? Ich würde mich freuen. Wir freuen uns auf viele Gäste. Bitte antworte bis Freitag. Bitte gib Bescheid.',
        examples: ['Ich lade dich zu meinem Geburtstag ein.', 'Die Party beginnt um 19 Uhr.', 'Bitte gib bis Mittwoch Bescheid.'],
        highlight: null,
        t: [
          'Inviting: Ich habe Geburtstag. Am Samstag werde ich 30. Ich möchte meinen Geburtstag feiern und lade dich herzlich ein (I warmly invite you). Ich lade Sie zu meiner Party ein. Kommst du? Kannst du kommen? Ich würde mich freuen (I would be pleased). Wir freuen uns auf viele Gäste. Bitte antworte bis Freitag (please reply by Friday). Bitte gib Bescheid (please let me know).',
          'Как пригласить: Ich habe Geburtstag. Am Samstag werde ich 30. Ich möchte meinen Geburtstag feiern und lade dich herzlich ein (сердечно приглашаю тебя). Ich lade Sie zu meiner Party ein. Kommst du? Kannst du kommen? Ich würde mich freuen (я был бы рад). Wir freuen uns auf viele Gäste. Bitte antworte bis Freitag (ответь, пожалуйста, до пятницы). Bitte gib Bescheid (дай, пожалуйста, знать).',
          'Як запросити: Ich habe Geburtstag. Am Samstag werde ich 30. Ich möchte meinen Geburtstag feiern und lade dich herzlich ein (щиро запрошую тебе). Ich lade Sie zu meiner Party ein. Kommst du? Kannst du kommen? Ich würde mich freuen (я був би радий). Wir freuen uns auf viele Gäste. Bitte antworte bis Freitag (відповідай, будь ласка, до п’ятниці). Bitte gib Bescheid (дай, будь ласка, знати).',
          'Davet etme: Ich habe Geburtstag. Am Samstag werde ich 30. Ich möchte meinen Geburtstag feiern und lade dich herzlich ein (seni içtenlikle davet ediyorum). Ich lade Sie zu meiner Party ein. Kommst du? Kannst du kommen? Ich würde mich freuen (sevinirim). Wir freuen uns auf viele Gäste. Bitte antworte bis Freitag (lütfen cumaya kadar cevap ver). Bitte gib Bescheid (lütfen haber ver).',
        ],
        hint: ['In einer Einladung steht: Was? Wann? Wo? Antwort bis wann?', 'An invitation says: what? when? where? reply by when?', 'В приглашении есть: что? когда? где? до какого числа ответить?', 'У запрошенні є: що? коли? де? до якого числа відповісти?', 'Bir davetiyede şunlar yazar: Ne? Ne zaman? Nerede? Ne zamana kadar cevap?'],
      },
      ex: [
        mc('K4', 'einladen', I.situation, 'Du machst eine Party und möchtest deine Kollegin Hanna einladen. Ihr sagt „du“.', ['Ich lade dich herzlich zu meiner Party ein.', 'Ich lade Sie herzlich zu meiner Party ein.', 'Du lädst mich zu deiner Party ein.'],
          ['You are having a party and want to invite your colleague Hanna. You say “du” to each other.', 'Вы устраиваете вечеринку и хотите пригласить коллегу Hanna. Вы с ней на «ты».', 'Ви влаштовуєте вечірку й хочете запросити колегу Hanna. Ви з нею на «ти».', 'Bir parti veriyorsunuz ve iş arkadaşınız Hanna’yı davet etmek istiyorsunuz. Birbirinize “du” diyorsunuz.']),
        mc('K4', 'um Antwort bitten', I.choose, 'Du möchtest wissen: Wer kommt zur Party? Was schreibst du in die Einladung?', ['Bitte gib bis Freitag Bescheid.', 'Bitte komm nicht.', 'Bitte bring die Rechnung mit.'],
          ['You want to know who is coming to the party. What do you write in the invitation?', 'Вы хотите знать, кто придёт на вечеринку. Что вы напишете в приглашении?', 'Ви хочете знати, хто прийде на вечірку. Що ви напишете в запрошенні?', 'Partiye kimin geleceğini öğrenmek istiyorsunuz. Davetiyeye ne yazarsınız?']),
        mc('Z1', 'Einladung lesen', I.read, `${INVITE} Was feiert Dilara?`, ['Ihren Geburtstag.', 'Ihre Hochzeit.', 'Weihnachten.'],
          ['What is Dilara celebrating?', 'Что празднует Dilara?', 'Що святкує Dilara?', 'Dilara neyi kutluyor?']),
        mc('Z1', 'Einladung lesen', I.read, `${INVITE} Bis wann soll man antworten?`, ['Bis zum 1. Juni.', 'Bis zum 14. Juni.', 'Bis 18 Uhr.'],
          ['By when should you reply?', 'До какого числа нужно ответить?', 'До якого числа треба відповісти?', 'Ne zamana kadar cevap vermek gerekiyor?']),
        mc('Z1', 'Einladung lesen', I.read, `${INVITE} Wo ist die Party?`, ['In einem Café.', 'Bei Dilara zu Hause.', 'Im Büro.'],
          ['Where is the party?', 'Где будет вечеринка?', 'Де буде вечірка?', 'Parti nerede?']),
        gap('K4', 'einladen', I.verb, 'Ich ', ' dich zu meinem Geburtstag ein.', 'lade', ['lädst', 'laden'],
          ['I am inviting you to my birthday.', 'Я приглашаю тебя на свой день рождения.', 'Я запрошую тебе на свій день народження.', 'Seni doğum günüme davet ediyorum.'], 'einladen'),
        gap('K4', 'Bescheid geben', I.word, 'Kommst du? Bitte gib bis Montag ', '.', 'Bescheid', ['Besuch', 'Geburtstag'],
          ['Are you coming? Please let me know by Monday.', 'Ты придёшь? Пожалуйста, дай знать до понедельника.', 'Ти прийдеш? Будь ласка, дай знати до понеділка.', 'Geliyor musun? Lütfen pazartesiye kadar haber ver.'],
          ['Bescheid geben = to let someone know', 'Bescheid geben = дать знать', 'Bescheid geben = дати знати', 'Bescheid geben = haber vermek']),
        gap('G3', 'mich', I.pronoun, 'Kannst du kommen? Ich würde ', ' sehr freuen.', 'mich', ['mir', 'ich'],
          ['Can you come? I would be very pleased.', 'Ты сможешь прийти? Я был бы очень рад.', 'Ти зможеш прийти? Я був би дуже радий.', 'Gelebilir misin? Çok sevinirim.'], 'ich', { c: 'p7_akk' }),
        sb('K4', 'einladen', I.order, 'Ich / lade / euch / herzlich / ein.',
          ['I warmly invite you all.', 'Я сердечно вас приглашаю.', 'Я щиро вас запрошую.', 'Sizi içtenlikle davet ediyorum.'],
          { alt: ['Herzlich lade ich euch ein.'] }),
      ],
    },
    {
      title: 'Zusagen und absagen',
      t: ['Accepting and declining', 'Согласие и отказ', 'Згода і відмова', 'Kabul etme ve reddetme'],
      card: {
        id: 'p7_zusagen',
        rule: 'Auf eine Einladung antworten: Dank: Vielen Dank für die Einladung. Zusage: Ich komme gern! Wir kommen sehr gern. Absage: Leider kann ich nicht kommen. Tut mir leid, aber ich habe keine Zeit. Grund mit denn: Ich kann leider nicht kommen, denn ich muss arbeiten.',
        examples: ['Vielen Dank für die Einladung. Ich komme gern!', 'Leider kann ich nicht kommen, denn mein Flug geht am Freitag.', 'Tut mir leid, aber ich habe keine Zeit.'],
        highlight: null,
        t: [
          'Replying to an invitation: thanks: Vielen Dank für die Einladung. Accepting: Ich komme gern! Wir kommen sehr gern. Declining: Leider kann ich nicht kommen. Tut mir leid, aber ich habe keine Zeit. Reason with denn: Ich kann leider nicht kommen, denn ich muss arbeiten.',
          'Как ответить на приглашение: благодарность: Vielen Dank für die Einladung. Согласие: Ich komme gern! Wir kommen sehr gern. Отказ: Leider kann ich nicht kommen. Tut mir leid, aber ich habe keine Zeit. Причина с denn: Ich kann leider nicht kommen, denn ich muss arbeiten.',
          'Як відповісти на запрошення: подяка: Vielen Dank für die Einladung. Згода: Ich komme gern! Wir kommen sehr gern. Відмова: Leider kann ich nicht kommen. Tut mir leid, aber ich habe keine Zeit. Причина з denn: Ich kann leider nicht kommen, denn ich muss arbeiten.',
          'Bir davete cevap verme: Teşekkür: Vielen Dank für die Einladung. Kabul: Ich komme gern! Wir kommen sehr gern. Ret: Leider kann ich nicht kommen. Tut mir leid, aber ich habe keine Zeit. denn ile neden: Ich kann leider nicht kommen, denn ich muss arbeiten.',
        ],
        hint: ['Erst danken. Dann: Ich komme gern. / Leider kann ich nicht kommen, denn …', 'Say thank you first. Then: Ich komme gern. / Leider kann ich nicht kommen, denn …', 'Сначала поблагодарите. Потом: Ich komme gern. / Leider kann ich nicht kommen, denn …', 'Спочатку подякуйте. Потім: Ich komme gern. / Leider kann ich nicht kommen, denn …', 'Önce teşekkür edin. Sonra: Ich komme gern. / Leider kann ich nicht kommen, denn …'],
      },
      ex: [
        mc('K5', 'zusagen', I.situation, 'Du bekommst eine Einladung und möchtest kommen.', ['Vielen Dank für die Einladung. Ich komme gern!', 'Leider kann ich nicht kommen.', 'Tut mir leid, ich habe keine Zeit.'],
          ['You get an invitation and would like to come.', 'Вы получили приглашение и хотите прийти.', 'Ви отримали запрошення й хочете прийти.', 'Bir davet aldınız ve gitmek istiyorsunuz.']),
        mc('K5', 'absagen mit Grund', I.situation, 'Du bekommst eine Einladung, aber du bist an dem Tag in Berlin.', ['Leider kann ich nicht kommen, denn ich bin in Berlin.', 'Ich komme gern, denn ich bin in Berlin.', 'Vielen Dank, ich komme!'],
          ['You get an invitation, but you are in Berlin on that day.', 'Вы получили приглашение, но в этот день вы в Берлине.', 'Ви отримали запрошення, але цього дня ви в Берліні.', 'Bir davet aldınız ama o gün Berlin’desiniz.']),
        mc('K5', 'zusagen', I.react, '„Kommst du am Samstag zu meiner Party?“', ['Ja, sehr gern! Wann beginnt sie?', 'Ja, ich lade dich ein.', 'Herzlichen Glückwunsch!'],
          ['“Are you coming to my party on Saturday?”', '«Ты придёшь в субботу на мою вечеринку?»', '«Ти прийдеш у суботу на мою вечірку?»', '“Cumartesi günü partime geliyor musun?”']),
        mc('K5', 'absagen', I.choose, 'Welcher Satz ist eine Absage?', ['Tut mir leid, aber ich habe keine Zeit.', 'Ich komme sehr gern.', 'Ich freue mich schon.'],
          ['Which sentence declines an invitation?', 'Какое предложение – отказ?', 'Яке речення – відмова?', 'Hangi cümle bir ret cevabıdır?']),
        gap('K5', 'für die Einladung danken', I.word, 'Vielen Dank für die ', '! Wir kommen gern.', 'Einladung', ['Entschuldigung', 'Erfahrung'],
          ['Thank you very much for the invitation! We would love to come.', 'Большое спасибо за приглашение! Мы с удовольствием придём.', 'Щиро дякуємо за запрошення! Ми із задоволенням прийдемо.', 'Davet için çok teşekkürler! Memnuniyetle geliriz.'],
          ['invitation', 'приглашение', 'запрошення', 'davet']),
        gap('K5', 'absagen', I.word, '', ' kann ich nicht kommen, denn ich bin krank.', 'Leider', ['Gern', 'Natürlich'],
          ['Unfortunately I cannot come because I am ill.', 'К сожалению, я не могу прийти, потому что я болею.', 'На жаль, я не можу прийти, бо я хворію.', 'Maalesef gelemiyorum çünkü hastayım.'],
          ['unfortunately', 'к сожалению', 'на жаль', 'maalesef']),
        gap('K5', 'Grund nennen', I.conjunction, 'Ich kann nicht mitkommen, ', ' mein Zug fährt schon um 16 Uhr.', 'denn', ['oder', 'und'],
          ['I cannot come along because my train leaves at 4 p.m.', 'Я не могу пойти с вами, потому что мой поезд уходит уже в 16 часов.', 'Я не можу піти з вами, бо мій поїзд відправляється вже о 16 годині.', 'Sizinle gelemiyorum çünkü trenim saat 16’da kalkıyor.'], 'denn / oder / und', { c: 'p7_denn', h: 'which' }),
        sb('K5', 'absagen', I.order, 'Leider / kann / ich / nicht / mitkommen.',
          ['Unfortunately I cannot come along.', 'К сожалению, я не могу пойти с вами.', 'На жаль, я не можу піти з вами.', 'Maalesef sizinle gelemiyorum.'],
          { alt: ['Ich kann leider nicht mitkommen.'] }),
      ],
    },
    {
      title: 'Mein Lieblingsfest',
      t: ['My favourite celebration', 'Мой любимый праздник', 'Моє улюблене свято', 'En sevdiğim kutlama'],
      card: {
        id: 'p7_lieblingsfest',
        rule: 'Texte über Feste verstehen: Achte auf: Welches Fest? Wann? Mit wem? Was machen die Leute? (essen, tanzen, Geschenke bekommen, die Familie besuchen) Wie findet die Person das Fest?',
        examples: ['Mein Lieblingsfest ist Silvester, denn dann feiern wir mit Freunden.', 'An Ostern suchen die Kinder Eier im Garten.', 'An Weihnachten essen wir zusammen und singen Lieder.'],
        highlight: null,
        t: [
          'Understanding texts about celebrations: look for: which celebration? when? with whom? what do people do? (eat, dance, get presents, visit the family) How does the person like the celebration?',
          'Как понимать тексты о праздниках: обратите внимание: какой праздник? когда? с кем? что делают люди? (едят, танцуют, получают подарки, навещают семью) Как человек относится к этому празднику?',
          'Як розуміти тексти про свята: зверніть увагу: яке свято? коли? з ким? що роблять люди? (їдять, танцюють, отримують подарунки, відвідують родину) Як людина ставиться до цього свята?',
          'Kutlamalarla ilgili metinleri anlama: Şunlara dikkat edin: Hangi kutlama? Ne zaman? Kiminle? İnsanlar ne yapıyor? (yemek yemek, dans etmek, hediye almak, aileyi ziyaret etmek) Kişi bu kutlamayı nasıl buluyor?',
        ],
        hint: ['Such im Text: Welches Fest? Wann? Mit wem? Was machen die Leute?', 'Look in the text: which celebration? when? with whom? what do people do?', 'Найдите в тексте: какой праздник? когда? с кем? что делают люди?', 'Знайдіть у тексті: яке свято? коли? з ким? що роблять люди?', 'Metinde arayın: Hangi kutlama? Ne zaman? Kiminle? İnsanlar ne yapıyor?'],
      },
      ex: [
        mc('Z1', 'Text über ein Fest', I.read, `${SUGAR} Wie lange feiert Karims Familie?`, ['Drei Tage.', 'Einen Tag.', 'Eine Woche.'],
          ['How long does Karim’s family celebrate?', 'Сколько дней празднует семья Karim?', 'Скільки днів святкує родина Karim?', 'Karim’in ailesi kaç gün kutlama yapıyor?']),
        mc('Z1', 'Text über ein Fest', I.read, `${SUGAR} Was bekommen die Kinder?`, ['Süßigkeiten und Geld.', 'Bücher und Blumen.', 'Kleidung.'],
          ['What do the children get?', 'Что получают дети?', 'Що отримують діти?', 'Çocuklar ne alıyor?']),
        mc('Z1', 'Text über ein Fest', I.read, `${NEW_YEAR} Mit wem feiert Hanna?`, ['Mit ihren Freunden.', 'Mit ihren Großeltern.', 'Allein.'],
          ['Who does Hanna celebrate with?', 'С кем празднует Hanna?', 'З ким святкує Hanna?', 'Hanna kiminle kutluyor?']),
        mc('Z1', 'Text über ein Fest', I.read, `${NEW_YEAR} Was macht Hanna um Mitternacht?`, ['Sie sieht das Feuerwerk.', 'Sie geht ins Bett.', 'Sie kocht.'],
          ['What does Hanna do at midnight?', 'Что Hanna делает в полночь?', 'Що Hanna робить опівночі?', 'Hanna gece yarısı ne yapıyor?']),
        gap('W1', 'Ostern', I.word, 'An Ostern suchen die Kinder ', ' im Garten.', 'Eier', ['Gäste', 'Feste'],
          ['At Easter the children look for eggs in the garden.', 'На Пасху дети ищут яйца в саду.', 'На Великдень діти шукають яйця в саду.', 'Paskalyada çocuklar bahçede yumurta arar.'],
          ['eggs', 'яйца', 'яйця', 'yumurtalar'], { c: 'p7_feste' }),
        gap('Z1', 'Lieblingsfest', I.word, 'Weihnachten ist mein ', '. Ich mag es am liebsten.', 'Lieblingsfest', ['Geburtstag', 'Geschenk'],
          ['Christmas is my favourite celebration. I like it best.', 'Рождество – мой любимый праздник. Я люблю его больше всего.', 'Різдво – моє улюблене свято. Я люблю його найбільше.', 'Noel en sevdiğim kutlama. En çok onu severim.'],
          ['favourite celebration', 'любимый праздник', 'улюблене свято', 'en sevilen kutlama']),
      ],
    },
  ],
}

export default path
