import { I, gap, mc, sb } from '../shared.mjs'

const KII = 'sein / haben / werden (Konjunktiv II)'
const TANZKURS = 'Veranstaltungstipp: „Tanzkurs für Anfänger im Jugendzentrum. Der Kurs beginnt am 4. Mai und findet immer montags um 18 Uhr statt. Die Teilnahme kostet 20 Euro im Monat. Bitte bis Ende April anmelden.“'
const KONZERT = 'Veranstaltungstipp: „Sommerkonzert im Stadtpark am Freitag ab 19 Uhr. Es spielt die Band ‚Nordwind‘. Der Eintritt ist frei. Bringen Sie eine Decke mit! Getränke kann man im Park kaufen.“'

/** A2.2 · Pfad 1 · Am Wochenende – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'ausschlafen', I.choose, 'Du schläfst am Sonntag bis elf Uhr. Was machst du?', ['Ich schlafe aus.', 'Ich wandere.', 'Ich mache einen Ausflug.'],
      ['On Sunday you sleep until eleven o’clock. What are you doing?', 'В воскресенье вы спите до одиннадцати. Что вы делаете?', 'У неділю ви спите до одинадцятої. Що ви робите?', 'Pazar günü saat on bire kadar uyuyorsunuz. Ne yapıyorsunuz?']),
    mc('W2', 'Anmeldung nicht nötig', I.sign, 'Auf dem Plakat steht: „Anmeldung nicht nötig“.', ['Man kann einfach kommen.', 'Man muss vorher anrufen.', 'Es gibt keine Plätze mehr.'],
      ['The poster says: “Anmeldung nicht nötig”.', 'На афише написано: «Anmeldung nicht nötig».', 'На афіші написано: «Anmeldung nicht nötig».', 'Afişte “Anmeldung nicht nötig” yazıyor.']),
    mc('G3', 'hätte gern', I.choose, 'Samir hat keinen Garten. Er … gern einen Garten.', ['hätte', 'wäre', 'würde'],
      ['Samir has no garden. He would like to have a garden.', 'У Samir нет сада. Он хотел бы иметь сад.', 'У Samir немає саду. Він хотів би мати сад.', 'Samir’in bahçesi yok. Bir bahçesi olsun isterdi.']),
    mc('G4', 'ihr könntet', I.choose, 'Ihr sucht eine Idee für Sonntag? Ihr … in den Zoo gehen.', ['könntet', 'könntest', 'könnte'],
      ['Are you (plural) looking for an idea for Sunday? You could go to the zoo.', 'Вы ищете идею на воскресенье? Вы могли бы сходить в зоопарк.', 'Ви шукаєте ідею на неділю? Ви могли б сходити до зоопарку.', 'Pazar için bir fikir mi arıyorsunuz? Hayvanat bahçesine gidebilirsiniz.']),
    mc('K1', 'Was würden Sie gern lernen?', I.react, '„Was würden Sie gern lernen?“', ['Ich würde gern Italienisch lernen.', 'Ich wäre gern in Italien.', 'Ich hätte gern eine Pizza.'],
      ['“What would you like to learn?”', '«Что вы хотели бы изучать?»', '«Що ви хотіли б вивчати?»', '“Ne öğrenmek isterdiniz?”']),
    mc('K2', 'Wie wäre es mit …?', I.situation, 'Du möchtest mit deinem Nachbarn grillen. Was schlägst du vor?', ['Wie wäre es mit einem Grillabend am Freitag?', 'Am Freitag habe ich gegrillt.', 'Ich grille nicht gern.'],
      ['You would like to have a barbecue with your neighbour. What do you suggest?', 'Вы хотите пожарить мясо на гриле вместе с соседом. Что вы предложите?', 'Ви хочете посмажити м’ясо на грилі разом із сусідом. Що ви запропонуєте?', 'Komşunuzla mangal yapmak istiyorsunuz. Ne önerirsiniz?']),
    mc('K3', 'Ja, gern.', I.react, '„Wollen wir morgen zusammen frühstücken?“ – Du möchtest gern.', ['Ja, gern. Wann treffen wir uns?', 'Schade, das geht leider nicht.', 'Ich frühstücke nie.'],
      ['“Shall we have breakfast together tomorrow?” – You would like to.', '«Позавтракаем завтра вместе?» – Вы хотите.', '«Поснідаємо завтра разом?» – Ви хочете.', '“Yarın birlikte kahvaltı yapalım mı?” – İstiyorsunuz.']),
    mc('Z1', 'Wie oft?', I.read, `${TANZKURS} Wie oft ist der Kurs?`, ['Einmal pro Woche.', 'Einmal im Monat.', 'Jeden Tag.'],
      ['How often is the course?', 'Как часто проходит курс?', 'Як часто відбувається курс?', 'Kurs ne sıklıkta yapılıyor?']),
    gap('G1', 'ihr hättet', I.verb, 'Ihr ', ' gern mehr Urlaub, oder?', 'hättet', ['hätten', 'hättest'],
      ['You (plural) would like to have more holiday, wouldn’t you?', 'Вы хотели бы больше отпуска, да?', 'Ви хотіли б більше відпустки, так?', 'Daha çok izniniz olsun isterdiniz, değil mi?'], 'haben'),
    gap('G1', 'ihr wärt', I.verb, 'Wo ', ' ihr jetzt gern?', 'wärt', ['wären', 'wärst'],
      ['Where would you (plural) like to be now?', 'Где вы хотели бы сейчас быть?', 'Де ви хотіли б зараз бути?', 'Şimdi nerede olmak isterdiniz?'], 'sein'),
    gap('G2', 'ich würde', I.verb, 'Ich ', ' gern einmal nach Japan reisen.', 'würde', ['würdest', 'würden'],
      ['I would like to travel to Japan one day.', 'Я хотел бы когда-нибудь поехать в Японию.', 'Я хотів би колись поїхати до Японії.', 'Bir gün Japonya’ya gitmek isterdim.'], 'werden (Konjunktiv II)'),
    gap('K4', 'leider', I.word, 'Ich würde gern kommen, aber ich habe ', ' keine Zeit.', 'leider', ['gern', 'trotzdem'],
      ['I would love to come, but unfortunately I have no time.', 'Я бы с удовольствием пришёл, но у меня, к сожалению, нет времени.', 'Я б охоче прийшов, але в мене, на жаль, немає часу.', 'Gelmeyi çok isterdim ama maalesef vaktim yok.'],
      ['unfortunately', 'к сожалению', 'на жаль', 'maalesef']),
    sb('G5', 'Trotzdem auf Position 1', I.order, 'Trotzdem / fährt / sie / mit dem Fahrrad.',
      ['She is going by bike anyway.', 'Она всё равно едет на велосипеде.', 'Вона все одно їде на велосипеді.', 'Yine de bisikletle gidiyor.'],
      { alt: ['Sie fährt trotzdem mit dem Fahrrad.'] }),
  ],
  size: 13,
  test: [
    mc('W1', 'Ausflug', I.choose, 'Ihr wandert, besucht eine Burg und kommt am Abend zurück. Was macht ihr?', ['einen Ausflug', 'einen Flohmarkt', 'einen Vortrag'],
      ['You go hiking, visit a castle and come back in the evening. What are you doing?', 'Вы идёте в поход, посещаете замок и вечером возвращаетесь. Что вы делаете?', 'Ви йдете в похід, відвідуєте замок і ввечері повертаєтеся. Що ви робите?', 'Yürüyüş yapıyor, bir kaleyi geziyor ve akşam dönüyorsunuz. Ne yapıyorsunuz?']),
    mc('W2', 'Ausstellung', I.choose, 'Im Rathaus sind zwei Wochen lang Bilder von jungen Malern zu sehen. Das ist eine …', ['Ausstellung', 'Anmeldung', 'Führung'],
      ['For two weeks pictures by young painters can be seen at the town hall. That is an …', 'В ратуше две недели можно увидеть картины молодых художников. Это …', 'У ратуші два тижні можна побачити картини молодих художників. Це …', 'Belediye binasında iki hafta boyunca genç ressamların resimleri görülebiliyor. Bu bir …']),
    mc('G1', 'ich wäre', I.choose, 'Ich … jetzt gern bei meiner Familie.', ['wäre', 'wären', 'wärst'],
      ['I would like to be with my family now.', 'Я хотел бы сейчас быть со своей семьёй.', 'Я хотів би зараз бути зі своєю родиною.', 'Şimdi ailemin yanında olmak isterdim.']),
    mc('G2', 'er würde', I.choose, 'Mein Bruder … gern in Berlin studieren.', ['würde', 'würden', 'würdest'],
      ['My brother would like to study in Berlin.', 'Мой брат хотел бы учиться в Берлине.', 'Мій брат хотів би навчатися в Берліні.', 'Erkek kardeşim Berlin’de okumak isterdi.']),
    mc("G3", "wäre gern", I.choose, "Es ist heiß. Leon … jetzt gern im Schwimmbad.", ["wäre","hätte","würde"], ["It is hot. Leon would like to be at the swimming pool now.","Жарко. Leon хотел бы сейчас быть в бассейне.","Спекотно. Leon хотів би зараз бути в басейні.","Hava sıcak. Leon şimdi yüzme havuzunda olmak isterdi."], {"c":"p1_wunsch"}),
    mc('G3', 'würde gern', I.choose, 'Ich kann nicht kochen. Ich … gern einen Kochkurs machen.', ['würde', 'hätte', 'wäre'],
      ['I cannot cook. I would like to do a cookery course.', 'Я не умею готовить. Я хотел бы пойти на кулинарные курсы.', 'Я не вмію готувати. Я хотів би піти на кулінарні курси.', 'Yemek yapmayı bilmiyorum. Bir yemek kursuna gitmek isterdim.']),
    mc('G4', 'Infinitiv am Ende', I.sentence, 'Jonas hat eine Idee für das Wochenende.', ['Wir könnten am See grillen.', 'Wir könnten grillen am See.', 'Wir am See könnten grillen.'],
      ['Jonas has an idea for the weekend.', 'У Jonas есть идея на выходные.', 'У Jonas є ідея на вихідні.', 'Jonas’ın hafta sonu için bir fikri var.']),
    mc('G5', 'Trotzdem', I.choose, 'Tom hat Fieber. … geht er zum Fußballtraining.', ['Trotzdem', 'Weil', 'Dass'],
      ['Tom has a temperature. He is going to football training anyway.', 'У Tom температура. Он всё равно идёт на футбольную тренировку.', 'У Tom температура. Він усе одно йде на футбольне тренування.', 'Tom’un ateşi var. Yine de futbol antrenmanına gidiyor.']),
    mc('G5', 'Verb auf Position 2', I.sentence, 'Das Restaurant ist teuer.', ['Trotzdem essen wir dort.', 'Trotzdem wir essen dort.', 'Trotzdem dort wir essen.'],
      ['The restaurant is expensive.', 'Ресторан дорогой.', 'Ресторан дорогий.', 'Restoran pahalı.']),
    mc('K1', 'Wo wären Sie gern?', I.react, '„Wo wären Sie jetzt gern?“', ['Am liebsten wäre ich jetzt an der Ostsee.', 'Ich hätte gern einen Tee.', 'Ich würde gern lesen.'],
      ['“Where would you like to be now?”', '«Где вы хотели бы сейчас быть?»', '«Де ви хотіли б зараз бути?»', '“Şimdi nerede olmak isterdiniz?”']),
    mc('K2', 'mit einem', I.choose, 'Wie wäre es mit … Konzert am Freitag?', ['einem', 'einen', 'einer'],
      ['How about a concert on Friday?', 'Как насчёт концерта в пятницу?', 'Як щодо концерту в п’ятницю?', 'Cuma günü bir konser nasıl olur?']),
    mc('K2', 'nach Plänen fragen', I.situation, 'Du möchtest wissen, was deine Freundin am Freitagabend gern macht. Was fragst du?', ['Was machst du gern am Freitagabend?', 'Was hast du am Freitagabend gemacht?', 'Wo warst du am Freitagabend?'],
      ['You want to know what your friend likes doing on Friday evenings. What do you ask?', 'Вы хотите узнать, чем ваша подруга любит заниматься в пятницу вечером. Что вы спросите?', 'Ви хочете дізнатися, чим ваша подруга любить займатися в п’ятницю ввечері. Що ви запитаєте?', 'Arkadaşınızın cuma akşamları ne yapmayı sevdiğini öğrenmek istiyorsunuz. Ne sorarsınız?']),
    mc('K3', 'annehmen', I.react, '„Wir könnten zusammen kochen.“ – Du findest das gut.', ['Gute Idee. Das machen wir!', 'Schade, das geht nicht.', 'Ich würde lieber allein kochen.'],
      ['“We could cook together.” – You like that.', '«Мы могли бы вместе приготовить еду.» – Вам это нравится.', '«Ми могли б разом приготувати їжу.» – Вам це подобається.', '“Birlikte yemek yapabiliriz.” – Bunu beğeniyorsunuz.']),
    mc('K4', 'ablehnen', I.react, '„Hast du Lust auf einen Spaziergang?“ – Du bist erkältet.', ['Ich würde gern mitkommen, aber ich bin erkältet.', 'Einverstanden. Wann geht es los?', 'Warum nicht? Ich komme mit.'],
      ['“Do you feel like going for a walk?” – You have a cold.', '«Хочешь прогуляться?» – Вы простужены.', '«Хочеш прогулятися?» – Ви застуджені.', '“Yürüyüşe çıkmak ister misin?” – Üşütmüşsünüz.']),
    mc('K4', 'absagen', I.choose, 'Mit welchem Satz sagst du Nein zu einem Vorschlag?', ['Da kann ich leider nicht.', 'Das geht bei mir.', 'Ich mache gern mit.'],
      ['Which sentence do you use to say no to a suggestion?', 'Каким предложением вы отказываетесь?', 'Яким реченням ви відмовляєтеся?', 'Bir öneriye hangi cümleyle hayır dersiniz?']),
    mc('Z1', 'Was kostet es?', I.read, `${KONZERT} Was kostet das Konzert?`, ['Nichts.', '19 Euro.', 'Man zahlt für die Decke.'],
      ['How much does the concert cost?', 'Сколько стоит концерт?', 'Скільки коштує концерт?', 'Konser ne kadar?']),
    mc('Z1', 'Was mitbringen?', I.read, `${KONZERT} Was soll man mitbringen?`, ['Eine Decke.', 'Getränke.', 'Eine Eintrittskarte.'],
      ['What should you bring?', 'Что нужно взять с собой?', 'Що треба взяти із собою?', 'Yanınızda ne getirmelisiniz?']),
    mc('Z1', 'Bis wann?', I.read, `${TANZKURS} Bis wann muss man sich anmelden?`, ['Bis Ende April.', 'Bis zum 4. Mai.', 'Bis Montag um 18 Uhr.'],
      ['By when do you have to register?', 'До какого срока нужно записаться?', 'До якого терміну треба записатися?', 'En geç ne zamana kadar kaydolmak gerekiyor?']),
    gap('W1', 'ausschlafen', I.verb, 'Am Sonntag stehe ich nicht früh auf. Ich möchte endlich einmal ', '.', 'ausschlafen', ['aufstehen', 'ausgehen'],
      ['On Sunday I am not getting up early. I would finally like to have a lie-in.', 'В воскресенье я не встаю рано. Хочу наконец-то выспаться.', 'У неділю я не встаю рано. Хочу нарешті виспатися.', 'Pazar günü erken kalkmıyorum. Nihayet uykumu almak istiyorum.'],
      ['have a lie-in', 'выспаться', 'виспатися', 'uykusunu almak']),
    gap('W2', 'Ermäßigung', I.word, 'Kinder und Studenten bekommen eine ', ' und zahlen nur die Hälfte.', 'Ermäßigung', ['Anmeldung', 'Ausstellung'],
      ['Children and students get a discount and pay only half.', 'Дети и студенты получают скидку и платят только половину.', 'Діти й студенти отримують знижку і платять лише половину.', 'Çocuklar ve öğrenciler indirim alıyor ve sadece yarısını ödüyor.'],
      ['discount', 'скидка', 'знижка', 'indirim']),
    gap('G1', 'du hättest', I.verb, 'Du ', ' gern eine Schwester, stimmt das?', 'hättest', ['hätte', 'hättet'],
      ['You would like to have a sister, is that right?', 'Ты хотел бы иметь сестру, это правда?', 'Ти хотів би мати сестру, це правда?', 'Bir kız kardeşin olsun isterdin, doğru mu?'], 'haben'),
    gap('G1', 'ihr könntet', I.modal, 'Ihr ', ' am Samstag mit uns Fußball spielen.', 'könntet', ['könnten', 'könntest'],
      ['You (plural) could play football with us on Saturday.', 'В субботу вы могли бы сыграть с нами в футбол.', 'У суботу ви могли б зіграти з нами у футбол.', 'Cumartesi günü bizimle futbol oynayabilirsiniz.'], 'können (Konjunktiv II)', { c: 'p1_koennte' }),
    gap('G2', 'wir würden', I.verb, 'Wir ', ' gern öfter ins Theater gehen.', 'würden', ['würde', 'würdet'],
      ['We would like to go to the theatre more often.', 'Мы хотели бы чаще ходить в театр.', 'Ми хотіли б частіше ходити до театру.', 'Tiyatroya daha sık gitmek isterdik.'], 'werden (Konjunktiv II)'),
    gap('G3', 'hätten gern', I.verb, 'Unsere Wohnung ist klein. Wir ', ' gern ein Zimmer mehr.', 'hätten', ['wären', 'würden'],
      ['Our flat is small. We would like to have one more room.', 'Наша квартира маленькая. Мы хотели бы иметь ещё одну комнату.', 'Наша квартира маленька. Ми хотіли б мати ще одну кімнату.', 'Dairemiz küçük. Bir odamız daha olsun isterdik.'], KII),
    gap('G4', 'du könntest', I.modal, 'Du suchst ein Geschenk für Opa? Du ', ' ihm ein Buch kaufen.', 'könntest', ['könnte', 'könnten'],
      ['Are you looking for a present for Grandad? You could buy him a book.', 'Ты ищешь подарок для дедушки? Ты мог бы купить ему книгу.', 'Ти шукаєш подарунок для дідуся? Ти міг би купити йому книжку.', 'Dedene hediye mi arıyorsun? Ona bir kitap alabilirsin.'], 'können (Konjunktiv II)'),
    gap('K1', 'würdet', I.verb, 'Was ', ' ihr gern machen? – Wir würden gern eine Stadtführung machen.', 'würdet', ['würden', 'wärt'],
      ['What would you (plural) like to do? – We would like to go on a guided tour of the town.', 'Что вы хотели бы делать? – Мы хотели бы пойти на экскурсию по городу.', 'Що ви хотіли б робити? – Ми хотіли б піти на екскурсію містом.', 'Ne yapmak isterdiniz? – Rehberli bir şehir turuna katılmak isterdik.'], 'werden (Konjunktiv II)'),
    gap('K3', 'Das geht bei mir.', I.verb, 'Ja, das ', ' bei mir. Am Samstag habe ich Zeit.', 'geht', ['kommt', 'macht'],
      ['Yes, that works for me. I am free on Saturday.', 'Да, мне это подходит. В субботу у меня есть время.', 'Так, мені це підходить. У суботу в мене є час.', 'Evet, bana uyar. Cumartesi vaktim var.'], 'gehen'),
    gap('K4', 'Schade', I.expression, '', ', das geht leider nicht. Ich habe schon etwas vor.', 'Schade', ['Gern', 'Super'],
      ['What a pity, I am afraid that is not possible. I already have plans.', 'Жаль, к сожалению, не получится. У меня уже есть планы.', 'Шкода, на жаль, не вийде. У мене вже є плани.', 'Ne yazık, maalesef olmuyor. Başka bir planım var.'],
      ['what a pity', 'жаль', 'шкода', 'ne yazık']),
    sb('G2', 'würde + Infinitiv', I.order, 'Ich / würde / gern / mehr Sport / machen.',
      ['I would like to do more sport.', 'Я хотел бы больше заниматься спортом.', 'Я хотів би більше займатися спортом.', 'Daha çok spor yapmak isterdim.'],
      { alt: ['Gern würde ich mehr Sport machen.', 'Mehr Sport würde ich gern machen.'] }),
    sb('G5', 'trotzdem nach dem Verb', I.order, 'Er / kommt / trotzdem / zu spät.',
      ['He is late anyway.', 'Он всё равно опаздывает.', 'Він усе одно запізнюється.', 'Yine de geç kalıyor.'],
      { alt: ['Trotzdem kommt er zu spät.'] }),
  ],
}

export default check
