import { I, gap, mc, sb } from '../shared.mjs'

const KII = 'sein / haben / werden (Konjunktiv II)'
const KINO = 'Veranstaltungstipp: „Neu im Programm: Kinderkino im Kulturhaus. Jeden Sonntag um 15 Uhr zeigen wir einen Film für Kinder ab sechs Jahren. Eintritt: 3 Euro. Eltern zahlen nichts. Nach dem Film gibt es Kuchen und Saft.“'
const FLOHMARKT = 'Veranstaltungstipp: „Großer Flohmarkt auf dem Marktplatz am Samstag von 8 bis 16 Uhr. Sie möchten selbst etwas verkaufen? Dann melden Sie sich bis Donnerstag im Rathaus an. Bei Regen findet der Flohmarkt in der Sporthalle statt.“'

/** A2.2 · Pfad 1 · Am Wochenende – Lektionen. Wiederholung und Test: p1-check.mjs */
const path = {
  n: 1,
  slug: 'am-wochenende',
  title: 'Am Wochenende',
  t: ['At the weekend', 'В выходные', 'У вихідні', 'Hafta sonunda'],
  objectives: {
    G1: 'Konjunktiv II von sein, haben und können: ich wäre, du wärst, wir wären – ich hätte, du hättest – ich könnte, du könntest.',
    G2: 'Konjunktiv II mit würde + Infinitiv: Ich würde gern Gitarre spielen. Der Infinitiv steht am Satzende.',
    G3: 'Wünsche ausdrücken: Ich wäre gern am Meer. Sie hätte gern mehr Freizeit. Wir würden gern tanzen.',
    G4: 'Vorschläge mit könnte: Du könntest ins Kino gehen. Wir könnten eine Radtour machen.',
    G5: 'Gegensätze ausdrücken mit trotzdem: Es regnet. Trotzdem gehe ich spazieren. Das Verb steht auf Position 2.',
    K1: 'Über Wünsche sprechen und danach fragen: Wo wären Sie jetzt gern? Was hätten Sie gern? Was würden Sie gern machen?',
    K2: 'Vorschläge machen und über Pläne sprechen: Wie wäre es mit …? Hast du Lust? Was machst du am Samstag?',
    K3: 'Einen Vorschlag annehmen: Gute Idee. Einverstanden. Warum nicht? Ich komme gern mit.',
    K4: 'Einen Vorschlag ablehnen und Bedauern ausdrücken: Schade, das geht leider nicht. Ich würde gern kommen, aber …',
    Z1: 'Kann-Ziele: Veranstaltungstipps und Programmhinweise verstehen.',
    W1: 'Wortschatz: Freizeitaktivitäten am Wochenende.',
    W2: 'Wortschatz: Veranstaltungen und Kurse.',
  },
  nodes: [
    {
      title: 'Freizeit am Wochenende',
      t: ['Free time at the weekend', 'Свободное время в выходные', 'Вільний час у вихідні', 'Hafta sonu boş zaman'],
      card: {
        id: 'p1_freizeit',
        rule: 'Freizeit am Wochenende: eine Radtour machen, einen Ausflug machen, wandern, ein Picknick machen, ins Kino oder ins Konzert gehen, Freunde treffen, auf den Flohmarkt gehen, im See schwimmen, grillen, faulenzen (= nichts tun), ausschlafen (= lange schlafen). Merke: Man macht eine Radtour, einen Ausflug und ein Picknick. Man geht ins Kino, ins Museum, auf den Flohmarkt.',
        examples: ['Am Samstag machen wir eine Radtour.', 'Sonntags schlafe ich gern aus.', 'Wir grillen heute im Garten.'],
        highlight: null,
        t: [
          'Free time at the weekend: eine Radtour machen (go on a bike ride), einen Ausflug machen (go on a trip), wandern (hike), ein Picknick machen (have a picnic), ins Kino oder ins Konzert gehen, Freunde treffen (meet friends), auf den Flohmarkt gehen (go to the flea market), im See schwimmen, grillen (have a barbecue), faulenzen (laze around = do nothing), ausschlafen (have a lie-in = sleep late). Remember: with Radtour, Ausflug and Picknick you use machen. With ins Kino, ins Museum, auf den Flohmarkt you use gehen.',
          'Свободное время в выходные: eine Radtour machen (отправиться на велопрогулку), einen Ausflug machen (поехать на экскурсию, на природу), wandern (ходить в поход), ein Picknick machen (устроить пикник), ins Kino oder ins Konzert gehen, Freunde treffen (встречаться с друзьями), auf den Flohmarkt gehen (идти на блошиный рынок), im See schwimmen, grillen (жарить на гриле), faulenzen (бездельничать = ничего не делать), ausschlafen (выспаться = долго спать). Запомните: с Radtour, Ausflug и Picknick используется machen. С ins Kino, ins Museum, auf den Flohmarkt – gehen.',
          'Вільний час у вихідні: eine Radtour machen (вирушити на велопрогулянку), einen Ausflug machen (поїхати на екскурсію, на природу), wandern (ходити в похід), ein Picknick machen (влаштувати пікнік), ins Kino oder ins Konzert gehen, Freunde treffen (зустрічатися з друзями), auf den Flohmarkt gehen (йти на блошиний ринок), im See schwimmen, grillen (смажити на грилі), faulenzen (байдикувати = нічого не робити), ausschlafen (виспатися = довго спати). Запам’ятайте: з Radtour, Ausflug і Picknick уживають machen. З ins Kino, ins Museum, auf den Flohmarkt – gehen.',
          'Hafta sonu boş zaman: eine Radtour machen (bisiklet turu yapmak), einen Ausflug machen (gezi yapmak), wandern (doğa yürüyüşü yapmak), ein Picknick machen (piknik yapmak), ins Kino oder ins Konzert gehen, Freunde treffen (arkadaşlarla buluşmak), auf den Flohmarkt gehen (bit pazarına gitmek), im See schwimmen, grillen (mangal yapmak), faulenzen (tembellik etmek = hiçbir şey yapmamak), ausschlafen (uykusunu almak = geç saate kadar uyumak). Unutmayın: Radtour, Ausflug ve Picknick ile machen kullanılır. ins Kino, ins Museum, auf den Flohmarkt ile gehen kullanılır.',
        ],
        hint: ['Radtour, Ausflug, Picknick: machen. Kino, Konzert, Flohmarkt: gehen. faulenzen = nichts tun. ausschlafen = lange schlafen.', 'Radtour, Ausflug, Picknick: machen. Kino, Konzert, Flohmarkt: gehen. faulenzen = do nothing. ausschlafen = sleep late.', 'Radtour, Ausflug, Picknick: machen. Kino, Konzert, Flohmarkt: gehen. faulenzen = ничего не делать. ausschlafen = долго спать.', 'Radtour, Ausflug, Picknick: machen. Kino, Konzert, Flohmarkt: gehen. faulenzen = нічого не робити. ausschlafen = довго спати.', 'Radtour, Ausflug, Picknick: machen. Kino, Konzert, Flohmarkt: gehen. faulenzen = hiçbir şey yapmamak. ausschlafen = geç saate kadar uyumak.'],
      },
      ex: [
        mc('W1', 'Radtour', I.choose, 'Du fährst mit Freunden den ganzen Tag Fahrrad. Was macht ihr?', ['eine Radtour', 'ein Picknick', 'einen Flohmarkt'],
          ['You are cycling with friends all day. What are you doing?', 'Вы с друзьями целый день катаетесь на велосипедах. Что вы делаете?', 'Ви з друзями цілий день катаєтеся на велосипедах. Що ви робите?', 'Arkadaşlarınızla bütün gün bisiklet sürüyorsunuz. Ne yapıyorsunuz?']),
        mc('W1', 'ausschlafen', I.choose, 'Was bedeutet „ausschlafen“?', ['lange schlafen, bis man nicht mehr müde ist', 'früh aufstehen', 'am Abend früh ins Bett gehen'],
          ['What does “ausschlafen” mean?', 'Что значит «ausschlafen»?', 'Що означає «ausschlafen»?', '“ausschlafen” ne demek?']),
        mc('W1', 'Picknick', I.choose, 'Ihr sitzt im Park auf einer Decke und esst Brot, Obst und Kuchen. Was macht ihr?', ['ein Picknick', 'eine Radtour', 'einen Kinoabend'],
          ['You are sitting on a blanket in the park, eating bread, fruit and cake. What are you doing?', 'Вы сидите в парке на пледе и едите хлеб, фрукты и пирог. Что вы делаете?', 'Ви сидите в парку на пледі та їсте хліб, фрукти й пиріг. Що ви робите?', 'Parkta bir örtünün üstünde oturmuş ekmek, meyve ve kek yiyorsunuz. Ne yapıyorsunuz?']),
        mc('W1', 'Freizeit', I.odd, 'Drei Wörter passen zur Freizeit, ein Wort nicht.', ['Überstunde', 'Ausflug', 'Picknick', 'Radtour'], null),
        mc('W1', 'faulenzen', I.choose, 'Am Sonntag macht Paul gar nichts. Er liegt nur auf dem Sofa. Er …', ['faulenzt', 'wandert', 'grillt'],
          ['On Sunday Paul does nothing at all. He just lies on the sofa. He …', 'В воскресенье Paul совсем ничего не делает. Он просто лежит на диване. Он …', 'У неділю Paul зовсім нічого не робить. Він просто лежить на дивані. Він …', 'Paul pazar günü hiçbir şey yapmıyor. Sadece kanepede yatıyor. O …']),
        gap('W1', 'wandern', I.verb, 'In den Bergen kann man gut ', '. Man braucht nur gute Schuhe.', 'wandern', ['schwimmen', 'grillen'],
          ['In the mountains you can go hiking. You only need good shoes.', 'В горах хорошо ходить в походы. Нужна только хорошая обувь.', 'У горах добре ходити в походи. Потрібне лише добре взуття.', 'Dağlarda güzel yürüyüş yapılır. Sadece iyi ayakkabı gerekir.'],
          ['hike', 'ходить в поход', 'ходити в похід', 'doğa yürüyüşü yapmak']),
        gap('W1', 'Flohmarkt', I.word, 'Auf dem ', ' kann man alte Sachen billig kaufen.', 'Flohmarkt', ['Ausflug', 'Picknick'],
          ['At the flea market you can buy old things cheaply.', 'На блошином рынке можно дёшево купить старые вещи.', 'На блошиному ринку можна дешево купити старі речі.', 'Bit pazarında eski eşyalar ucuza alınabilir.'],
          ['flea market', 'блошиный рынок', 'блошиний ринок', 'bit pazarı']),
        gap('W1', 'einen Ausflug machen', I.verb, 'Am Sonntag ', ' wir einen Ausflug an den See.', 'machen', ['gehen', 'fahren'],
          ['On Sunday we are going on a trip to the lake.', 'В воскресенье мы едем на озеро.', 'У неділю ми їдемо на озеро.', 'Pazar günü göle gezi yapıyoruz.'], 'machen / gehen / fahren'),
        gap('W1', 'grillen', I.verb, 'Das Wetter ist schön. Wir ', ' heute Würstchen und Gemüse im Garten.', 'grillen', ['wandern', 'faulenzen'],
          ['The weather is lovely. Today we are barbecuing sausages and vegetables in the garden.', 'Погода хорошая. Сегодня мы жарим в саду сосиски и овощи на гриле.', 'Погода гарна. Сьогодні ми смажимо в саду сосиски й овочі на грилі.', 'Hava güzel. Bugün bahçede sosis ve sebze mangal yapıyoruz.'],
          ['barbecue', 'жарить на гриле', 'смажити на грилі', 'mangal yapmak']),
        sb('W1', 'Freunde treffen', I.order, 'Am Wochenende / treffe / ich / meine Freunde.',
          ['At the weekend I meet my friends.', 'В выходные я встречаюсь с друзьями.', 'У вихідні я зустрічаюся з друзями.', 'Hafta sonu arkadaşlarımla buluşuyorum.'],
          { alt: ['Ich treffe am Wochenende meine Freunde.', 'Ich treffe meine Freunde am Wochenende.', 'Meine Freunde treffe ich am Wochenende.'] }),
      ],
    },
    {
      title: 'ich wäre, ich hätte',
      t: ['ich wäre, ich hätte (I would be, I would have)', 'ich wäre, ich hätte (я был бы, у меня было бы)', 'ich wäre, ich hätte (я був би, у мене було б)', 'ich wäre, ich hätte (olurdum, sahip olurdum)'],
      card: {
        id: 'p1_waere',
        rule: 'Konjunktiv II von sein und haben: ich wäre, du wärst, er/es/sie wäre, wir wären, ihr wärt, sie/Sie wären – ich hätte, du hättest, er/es/sie hätte, wir hätten, ihr hättet, sie/Sie hätten. Damit sagt man, was nicht wirklich so ist, aber schön wäre: Ich bin im Büro. Ich wäre jetzt gern am Meer. Ich habe kein Auto. Ich hätte gern ein Auto.',
        examples: ['Ich wäre jetzt gern zu Hause.', 'Hättest du gern einen Hund?', 'Wir hätten gern mehr Zeit.'],
        highlight: 'verb',
        t: [
          'Konjunktiv II of sein and haben: ich wäre, du wärst, er/es/sie wäre, wir wären, ihr wärt, sie/Sie wären – ich hätte, du hättest, er/es/sie hätte, wir hätten, ihr hättet, sie/Sie hätten. You use it for something that is not real but would be nice: Ich bin im Büro. Ich wäre jetzt gern am Meer. (I would like to be at the seaside now.) Ich habe kein Auto. Ich hätte gern ein Auto. (I would like to have a car.)',
          'Konjunktiv II глаголов sein и haben: ich wäre, du wärst, er/es/sie wäre, wir wären, ihr wärt, sie/Sie wären – ich hätte, du hättest, er/es/sie hätte, wir hätten, ihr hättet, sie/Sie hätten. Так говорят о том, чего на самом деле нет, но было бы хорошо: Ich bin im Büro. Ich wäre jetzt gern am Meer. (Я хотел бы сейчас быть на море.) Ich habe kein Auto. Ich hätte gern ein Auto. (Я хотел бы иметь машину.)',
          'Konjunktiv II дієслів sein і haben: ich wäre, du wärst, er/es/sie wäre, wir wären, ihr wärt, sie/Sie wären – ich hätte, du hättest, er/es/sie hätte, wir hätten, ihr hättet, sie/Sie hätten. Так кажуть про те, чого насправді немає, але було б добре: Ich bin im Büro. Ich wäre jetzt gern am Meer. (Я хотів би зараз бути на морі.) Ich habe kein Auto. Ich hätte gern ein Auto. (Я хотів би мати машину.)',
          'sein ve haben fiillerinin Konjunktiv II biçimi: ich wäre, du wärst, er/es/sie wäre, wir wären, ihr wärt, sie/Sie wären – ich hätte, du hättest, er/es/sie hätte, wir hätten, ihr hättet, sie/Sie hätten. Gerçek olmayan ama güzel olacak şeyler böyle söylenir: Ich bin im Büro. Ich wäre jetzt gern am Meer. (Şimdi deniz kenarında olmak isterdim.) Ich habe kein Auto. Ich hätte gern ein Auto. (Bir arabam olsun isterdim.)',
        ],
        hint: ['sein → wäre, wärst, wäre, wären, wärt, wären. haben → hätte, hättest, hätte, hätten, hättet, hätten.', 'sein → wäre, wärst, wäre, wären, wärt, wären. haben → hätte, hättest, hätte, hätten, hättet, hätten. (Always with an umlaut.)', 'sein → wäre, wärst, wäre, wären, wärt, wären. haben → hätte, hättest, hätte, hätten, hättet, hätten. (Всегда с умлаутом.)', 'sein → wäre, wärst, wäre, wären, wärt, wären. haben → hätte, hättest, hätte, hätten, hättet, hätten. (Завжди з умлаутом.)', 'sein → wäre, wärst, wäre, wären, wärt, wären. haben → hätte, hättest, hätte, hätten, hättet, hätten. (Her zaman umlaut ile.)'],
      },
      ex: [
        mc('G1', 'du wärst', I.choose, '… du jetzt gern am Strand?', ['Wärst', 'Wäre', 'Wären'],
          ['Would you like to be on the beach now?', 'Ты хотел бы сейчас быть на пляже?', 'Ти хотів би зараз бути на пляжі?', 'Şimdi plajda olmak ister miydin?']),
        mc('G1', 'wir hätten', I.choose, 'Wir … gern einen Garten.', ['hätten', 'hättet', 'hätte'],
          ['We would like to have a garden.', 'Мы хотели бы иметь сад.', 'Ми хотіли б мати сад.', 'Bir bahçemiz olsun isterdik.']),
        mc('G1', 'er wäre', I.choose, 'Jonas muss heute arbeiten. Er … lieber im Schwimmbad.', ['wäre', 'wärst', 'wären'],
          ['Jonas has to work today. He would rather be at the swimming pool.', 'Jonas сегодня должен работать. Он предпочёл бы быть в бассейне.', 'Jonas сьогодні мусить працювати. Він волів би бути в басейні.', 'Jonas bugün çalışmak zorunda. Yüzme havuzunda olmayı tercih ederdi.']),
        mc('G1', 'ihr hättet', I.choose, '… ihr gern mehr Freizeit?', ['Hättet', 'Hätten', 'Hättest'],
          ['Would you (plural) like to have more free time?', 'Вы хотели бы иметь больше свободного времени?', 'Ви хотіли б мати більше вільного часу?', 'Daha çok boş zamanınız olsun ister miydiniz?']),
        mc('G1', 'sein oder haben', I.choose, 'Ich … gern einen Bruder.', ['hätte', 'wäre', 'hätten'],
          ['I would like to have a brother.', 'Я хотел бы иметь брата.', 'Я хотів би мати брата.', 'Bir erkek kardeşim olsun isterdim.']),
        gap('G1', 'ich wäre', I.verb, 'Es ist kalt und grau. Ich ', ' jetzt gern in Spanien.', 'wäre', ['wären', 'wärst'],
          ['It is cold and grey. I would like to be in Spain now.', 'Холодно и пасмурно. Я хотел бы сейчас быть в Испании.', 'Холодно й похмуро. Я хотів би зараз бути в Іспанії.', 'Hava soğuk ve kapalı. Şimdi İspanya’da olmak isterdim.'], 'sein'),
        gap('G1', 'sie hätten', I.verb, 'Meine Eltern ', ' gern ein Haus am See.', 'hätten', ['hätte', 'hättet'],
          ['My parents would like to have a house by the lake.', 'Мои родители хотели бы иметь дом у озера.', 'Мої батьки хотіли б мати будинок біля озера.', 'Annemle babam göl kenarında bir evleri olsun isterdi.'], 'haben'),
        gap('G1', 'du hättest', I.verb, '', ' du gern mehr Geld?', 'Hättest', ['Hätte', 'Hättet'],
          ['Would you like to have more money?', 'Ты хотел бы иметь больше денег?', 'Ти хотів би мати більше грошей?', 'Daha çok paran olsun ister miydin?'], 'haben'),
        gap('G1', 'Sie wären', I.verb, 'Wo ', ' Sie jetzt gern, Frau Weber?', 'wären', ['wäre', 'wärt'],
          ['Where would you like to be now, Ms Weber?', 'Где вы хотели бы сейчас быть, госпожа Weber?', 'Де ви хотіли б зараз бути, пані Weber?', 'Şimdi nerede olmak isterdiniz, Weber Hanım?'], 'sein'),
        sb('G1', 'hätte gern', I.order, 'Ich / hätte / gern / einen Hund.',
          ['I would like to have a dog.', 'Я хотел бы иметь собаку.', 'Я хотів би мати собаку.', 'Bir köpeğim olsun isterdim.'],
          { alt: ['Einen Hund hätte ich gern.', 'Gern hätte ich einen Hund.'] }),
      ],
    },
    {
      title: 'würde + Infinitiv',
      t: ['würde + infinitive', 'würde + инфинитив', 'würde + інфінітив', 'würde + mastar'],
      card: {
        id: 'p1_wuerde',
        rule: 'Für fast alle anderen Verben nimmt man würde + Infinitiv: ich würde, du würdest, er/es/sie würde, wir würden, ihr würdet, sie/Sie würden. würde steht auf Position 2, der Infinitiv am Satzende: Ich würde gern Gitarre spielen. Wir würden am Wochenende gern wandern. In der Frage steht würde vorn: Würdest du gern mitkommen?',
        examples: ['Ich würde gern tanzen gehen.', 'Würdest du gern Klavier spielen?', 'Meine Kinder würden gern einen Film sehen.'],
        highlight: 'verb',
        t: [
          'For almost all other verbs you use würde + infinitive: ich würde, du würdest, er/es/sie würde, wir würden, ihr würdet, sie/Sie würden. würde is in position 2, the infinitive at the end of the sentence: Ich würde gern Gitarre spielen. (I would like to play the guitar.) Wir würden am Wochenende gern wandern. In a question würde comes first: Würdest du gern mitkommen?',
          'Почти со всеми остальными глаголами используют würde + инфинитив: ich würde, du würdest, er/es/sie würde, wir würden, ihr würdet, sie/Sie würden. würde стоит на втором месте, инфинитив – в конце предложения: Ich würde gern Gitarre spielen. (Я хотел бы играть на гитаре.) Wir würden am Wochenende gern wandern. В вопросе würde стоит в начале: Würdest du gern mitkommen?',
          'Майже з усіма іншими дієсловами вживають würde + інфінітив: ich würde, du würdest, er/es/sie würde, wir würden, ihr würdet, sie/Sie würden. würde стоїть на другому місці, інфінітив – у кінці речення: Ich würde gern Gitarre spielen. (Я хотів би грати на гітарі.) Wir würden am Wochenende gern wandern. У запитанні würde стоїть на початку: Würdest du gern mitkommen?',
          'Diğer fiillerin neredeyse hepsinde würde + mastar kullanılır: ich würde, du würdest, er/es/sie würde, wir würden, ihr würdet, sie/Sie würden. würde ikinci sırada, mastar cümlenin sonunda durur: Ich würde gern Gitarre spielen. (Gitar çalmak isterdim.) Wir würden am Wochenende gern wandern. Soruda würde başa gelir: Würdest du gern mitkommen?',
        ],
        hint: ['würde auf Position 2, Infinitiv am Ende: Ich würde gern … spielen.', 'würde in position 2, infinitive at the end: Ich würde gern … spielen.', 'würde на втором месте, инфинитив в конце: Ich würde gern … spielen.', 'würde на другому місці, інфінітив у кінці: Ich würde gern … spielen.', 'würde ikinci sırada, mastar sonda: Ich würde gern … spielen.'],
      },
      ex: [
        mc('G2', 'du würdest', I.choose, 'Was … du am Wochenende gern machen?', ['würdest', 'würde', 'würdet'],
          ['What would you like to do at the weekend?', 'Что ты хотел бы делать в выходные?', 'Що ти хотів би робити у вихідні?', 'Hafta sonu ne yapmak isterdin?']),
        mc('G2', 'wir würden', I.choose, 'Wir … gern eine Radtour machen.', ['würden', 'würdet', 'würdest'],
          ['We would like to go on a bike ride.', 'Мы хотели бы отправиться на велопрогулку.', 'Ми хотіли б вирушити на велопрогулянку.', 'Bir bisiklet turu yapmak isterdik.']),
        mc("G2", "Infinitiv am Ende", I.sentence, "Leon hat heute keine Zeit für Sport.", ["Er würde gern schwimmen gehen.","Er gern würde schwimmen gehen.","Er würde gern gehen schwimmen."], ["Leon has no time for sport today.","У Leon сегодня нет времени на спорт.","У Leon сьогодні немає часу на спорт.","Leon’un bugün spora vakti yok."], {"c":"p1_wuerde","sitovOptionOrder":["Er würde gern schwimmen gehen.","Er gern würde schwimmen gehen.","Er würde gern gehen schwimmen."]}),
        mc('G2', 'Infinitiv', I.choose, 'Ich würde gern besser Deutsch …', ['sprechen', 'spreche', 'gesprochen'],
          ['I would like to speak German better.', 'Я хотел бы лучше говорить по-немецки.', 'Я хотів би краще говорити німецькою.', 'Almancayı daha iyi konuşmak isterdim.']),
        gap('G2', 'er würde', I.verb, 'Paul ', ' gern in einer Band singen.', 'würde', ['würden', 'würdest'],
          ['Paul would like to sing in a band.', 'Paul хотел бы петь в группе.', 'Paul хотів би співати в гурті.', 'Paul bir grupta şarkı söylemek isterdi.'], 'werden (Konjunktiv II)'),
        gap('G2', 'ich würde', I.verb, 'Ich ', ' am Samstag gern ausschlafen.', 'würde', ['würdest', 'würdet'],
          ['I would like to have a lie-in on Saturday.', 'В субботу я хотел бы выспаться.', 'У суботу я хотів би виспатися.', 'Cumartesi günü uykumu almak isterdim.'], 'werden (Konjunktiv II)'),
        gap('G2', 'sie würden', I.verb, 'Meine Freunde ', ' gern ans Meer fahren.', 'würden', ['würde', 'würdet'],
          ['My friends would like to go to the seaside.', 'Мои друзья хотели бы поехать на море.', 'Мої друзі хотіли б поїхати на море.', 'Arkadaşlarım denize gitmek isterdi.'], 'werden (Konjunktiv II)'),
        gap('G2', 'Infinitiv am Ende', I.verb, 'Wir würden heute Abend gern ins Kino ', '.', 'gehen', ['geht', 'gegangen'],
          ['We would like to go to the cinema this evening.', 'Сегодня вечером мы хотели бы пойти в кино.', 'Сьогодні ввечері ми хотіли б піти в кіно.', 'Bu akşam sinemaya gitmek isterdik.'],
          ['go', 'пойти', 'піти', 'gitmek']),
        sb('G2', 'würde + Infinitiv', I.order, 'Ich / würde / gern / Gitarre / spielen.',
          ['I would like to play the guitar.', 'Я хотел бы играть на гитаре.', 'Я хотів би грати на гітарі.', 'Gitar çalmak isterdim.'],
          { alt: ['Gern würde ich Gitarre spielen.', 'Gitarre würde ich gern spielen.'] }),
        sb('G2', 'Frage mit würde', I.question, 'Würdest / du / gern / mitkommen?',
          ['Would you like to come along?', 'Ты хотел бы пойти с нами?', 'Ти хотів би піти з нами?', 'Sen de gelmek ister miydin?']),
      ],
    },
    {
      title: 'Ich wäre gern …',
      t: ['I would like to be …', 'Я хотел бы быть …', 'Я хотів би бути …', '… olmak isterdim'],
      card: {
  "id": "p1_wunsch",
  "rule": "Wünsche: Die Wirklichkeit ist anders. Mit gern sagt man, was man sich wünscht. wäre gern + Ort oder Adjektiv: Ich wäre gern am Meer. Er wäre gern reich. hätte gern + Nomen im Akkusativ: Er hätte gern einen Garten. würde gern + Infinitiv: Wir würden gern reisen. Noch stärker ist am liebsten: Am liebsten würde ich jetzt schlafen.",
  "examples": [
    "Ich wäre jetzt gern im Urlaub.",
    "Milan hätte gern eine Katze.",
    "Wir würden gern länger bleiben."
  ],
  "highlight": "verb",
  "t": [
    "Wishes: reality is different. With gern you say what you wish for. wäre gern + place or adjective: Ich wäre gern am Meer. Er wäre gern reich. (He would like to be rich.) hätte gern + noun in the accusative: Er hätte gern einen Garten. würde gern + infinitive: Wir würden gern reisen. (We would like to travel.) Even stronger is am liebsten: Am liebsten würde ich jetzt schlafen. (Most of all I would like to sleep now.)",
    "Желания: в действительности всё иначе. С gern говорят о том, чего хочется. wäre gern + место или прилагательное: Ich wäre gern am Meer. Er wäre gern reich. (Он хотел бы быть богатым.) hätte gern + существительное в Akkusativ: Er hätte gern einen Garten. würde gern + инфинитив: Wir würden gern reisen. (Мы хотели бы путешествовать.) Ещё сильнее am liebsten: Am liebsten würde ich jetzt schlafen. (Больше всего мне сейчас хотелось бы спать.)",
    "Бажання: насправді все інакше. З gern кажуть про те, чого хочеться. wäre gern + місце або прикметник: Ich wäre gern am Meer. Er wäre gern reich. (Він хотів би бути багатим.) hätte gern + іменник в Akkusativ: Er hätte gern einen Garten. würde gern + інфінітив: Wir würden gern reisen. (Ми хотіли б подорожувати.) Ще сильніше am liebsten: Am liebsten würde ich jetzt schlafen. (Найбільше мені зараз хотілося б спати.)",
    "Dilekler: Gerçek başka. gern ile insan ne dilediğini söyler. wäre gern + yer ya da sıfat: Ich wäre gern am Meer. Er wäre gern reich. (Zengin olmak isterdi.) hätte gern + Akkusativ halinde isim: Er hätte gern einen Garten. würde gern + mastar: Wir würden gern reisen. (Seyahat etmek isterdik.) Daha güçlüsü am liebsten: Am liebsten würde ich jetzt schlafen. (En çok şimdi uyumak isterdim.)"
  ],
  "hint": [
    "Ort oder Adjektiv → wäre gern. Nomen (eine Sache) → hätte gern. Verb (etwas tun) → würde gern + Infinitiv.",
    "Place or adjective → wäre gern. Noun (a thing) → hätte gern. Verb (doing something) → würde gern + infinitive.",
    "Место или прилагательное → wäre gern. Существительное (вещь) → hätte gern. Глагол (что-то делать) → würde gern + инфинитив.",
    "Місце або прикметник → wäre gern. Іменник (річ) → hätte gern. Дієслово (щось робити) → würde gern + інфінітив.",
    "Yer ya da sıfat → wäre gern. İsim (bir şey) → hätte gern. Fiil (bir şey yapmak) → würde gern + mastar."
  ]
},
      ex: [
        mc('G3', 'wäre gern', I.choose, 'Ich bin im Büro. Ich … jetzt gern am See.', ['wäre', 'hätte', 'würde'],
          ['I am at the office. I would like to be by the lake now.', 'Я в офисе. Я хотел бы сейчас быть у озера.', 'Я в офісі. Я хотів би зараз бути біля озера.', 'Ofisteyim. Şimdi göl kenarında olmak isterdim.']),
        mc('G3', 'hätte gern', I.choose, 'Emre hat kein Fahrrad. Er … gern ein Fahrrad.', ['hätte', 'wäre', 'würde'],
          ['Emre has no bike. He would like to have a bike.', 'У Emre нет велосипеда. Он хотел бы иметь велосипед.', 'У Emre немає велосипеда. Він хотів би мати велосипед.', 'Emre’nin bisikleti yok. Bir bisikleti olsun isterdi.']),
        mc("G3", "würde gern", I.choose, "Dilaver kann nicht tanzen. Er … gern tanzen lernen.", ["würde","wäre","hätte"], ["Dilaver cannot dance. He would like to learn to dance.","Dilaver не умеет танцевать. Он хотел бы научиться танцевать.","Dilaver не вміє танцювати. Він хотів би навчитися танцювати.","Dilaver dans edemiyor. Dans etmeyi öğrenmek isterdi."], {"c":"p1_wunsch"}),
        mc('G3', 'Wunsch', I.sentence, 'Tom hat wenig Freizeit. Was wünscht er sich?', ['Er hätte gern mehr Freizeit.', 'Er hat gern mehr Freizeit.', 'Er wäre gern mehr Freizeit.'],
          ['Tom has little free time. What does he wish for?', 'У Tom мало свободного времени. Чего он хочет?', 'У Tom мало вільного часу. Чого він хоче?', 'Tom’un boş zamanı az. Ne diliyor?']),
        mc('G3', 'am liebsten', I.choose, 'Ich bin so müde. Am liebsten … ich jetzt ins Bett gehen.', ['würde', 'wäre', 'hätte'],
          ['I am so tired. Most of all I would like to go to bed now.', 'Я так устал. Больше всего мне сейчас хотелось бы лечь спать.', 'Я такий утомлений. Найбільше мені зараз хотілося б лягти спати.', 'Çok yorgunum. En çok şimdi yatmak isterdim.']),
        gap('G3', 'hätten gern', I.verb, 'Wir wohnen im vierten Stock. Wir ', ' gern einen Balkon.', 'hätten', ['wären', 'würden'],
          ['We live on the fourth floor. We would like to have a balcony.', 'Мы живём на пятом этаже. Мы хотели бы иметь балкон.', 'Ми живемо на п’ятому поверсі. Ми хотіли б мати балкон.', 'Dördüncü katta oturuyoruz. Bir balkonumuz olsun isterdik.'], KII),
        gap("G3", "wäre gern", I.verb, "Oleg ist krank. Er ", " gern wieder gesund.", "wäre", ["hätte","würde"], ["Oleg is ill. He would like to be well again.","Oleg болен. Он хотел бы снова быть здоровым.","Oleg хворий. Він хотів би знову бути здоровим.","Oleg hasta. Yeniden sağlıklı olmak isterdi."], "sein / haben / werden (Konjunktiv II)", {"c":"p1_wunsch"}),
        gap('G3', 'würde lieber', I.verb, 'Ich muss arbeiten. Ich ', ' lieber mit euch feiern.', 'würde', ['wäre', 'hätte'],
          ['I have to work. I would rather celebrate with you.', 'Мне нужно работать. Я бы лучше праздновал с вами.', 'Мені треба працювати. Я б краще святкував із вами.', 'Çalışmak zorundayım. Sizinle kutlamayı tercih ederdim.'], KII),
        gap('G3', 'gern', I.word, 'Samir hätte ', ' ein neues Handy. Das ist sein Wunsch.', 'gern', ['viel', 'sehr'],
          ['Samir would like a new mobile. That is his wish.', 'Samir хотел бы новый телефон. Это его желание.', 'Samir хотів би новий телефон. Це його бажання.', 'Samir yeni bir cep telefonu isterdi. Bu onun dileği.'],
          ['gladly (would like)', 'охотно (хотел бы)', 'охоче (хотів би)', 'seve seve (isterdi)']),
        sb('G3', 'wäre gern', I.order, 'Wir / wären / gern / im Urlaub.',
          ['We would like to be on holiday.', 'Мы хотели бы быть в отпуске.', 'Ми хотіли б бути у відпустці.', 'Tatilde olmak isterdik.'],
          { alt: ['Im Urlaub wären wir gern.', 'Gern wären wir im Urlaub.'] }),
      ],
    },
    {
      title: 'Was würden Sie gern machen?',
      t: ['What would you like to do?', 'Что бы вы хотели делать?', 'Що б ви хотіли робити?', 'Ne yapmak isterdiniz?'],
      card: {
        id: 'p1_wuensche',
        rule: 'Über Wünsche sprechen: Wo wären Sie jetzt gern? – Ich wäre jetzt gern am Meer. Was hätten Sie gern? – Ich hätte gern mehr Freizeit. Was würden Sie gern machen oder lernen? – Ich würde gern Gitarre spielen. Mit du: Wo wärst du jetzt gern? Was hättest du gern? Was würdest du gern machen?',
        examples: ['Wo wärst du jetzt gern? – In den Bergen.', 'Was hätten Sie gern? – Ein eigenes Haus.', 'Was würdest du gern lernen? – Spanisch.'],
        highlight: null,
        t: [
          'Talking about wishes: Wo wären Sie jetzt gern? (Where would you like to be now?) – Ich wäre jetzt gern am Meer. Was hätten Sie gern? (What would you like to have?) – Ich hätte gern mehr Freizeit. Was würden Sie gern machen oder lernen? (What would you like to do or learn?) – Ich würde gern Gitarre spielen. With du: Wo wärst du jetzt gern? Was hättest du gern? Was würdest du gern machen?',
          'Как говорить о желаниях: Wo wären Sie jetzt gern? (Где вы хотели бы сейчас быть?) – Ich wäre jetzt gern am Meer. Was hätten Sie gern? (Что вы хотели бы иметь?) – Ich hätte gern mehr Freizeit. Was würden Sie gern machen oder lernen? (Что вы хотели бы делать или изучать?) – Ich würde gern Gitarre spielen. С du: Wo wärst du jetzt gern? Was hättest du gern? Was würdest du gern machen?',
          'Як говорити про бажання: Wo wären Sie jetzt gern? (Де ви хотіли б зараз бути?) – Ich wäre jetzt gern am Meer. Was hätten Sie gern? (Що ви хотіли б мати?) – Ich hätte gern mehr Freizeit. Was würden Sie gern machen oder lernen? (Що ви хотіли б робити або вивчати?) – Ich würde gern Gitarre spielen. З du: Wo wärst du jetzt gern? Was hättest du gern? Was würdest du gern machen?',
          'Dileklerden söz etmek: Wo wären Sie jetzt gern? (Şimdi nerede olmak isterdiniz?) – Ich wäre jetzt gern am Meer. Was hätten Sie gern? (Neyiniz olsun isterdiniz?) – Ich hätte gern mehr Freizeit. Was würden Sie gern machen oder lernen? (Ne yapmak ya da öğrenmek isterdiniz?) – Ich würde gern Gitarre spielen. du ile: Wo wärst du jetzt gern? Was hättest du gern? Was würdest du gern machen?',
        ],
        hint: ['Wo …? → Ich wäre gern … Was hättest du gern? → Ich hätte gern … Was würdest du gern machen? → Ich würde gern …', 'Wo …? (where) → Ich wäre gern … Was hättest du gern? → Ich hätte gern … Was würdest du gern machen? → Ich würde gern …', 'Wo …? (где) → Ich wäre gern … Was hättest du gern? → Ich hätte gern … Was würdest du gern machen? → Ich würde gern …', 'Wo …? (де) → Ich wäre gern … Was hättest du gern? → Ich hätte gern … Was würdest du gern machen? → Ich würde gern …', 'Wo …? (nerede) → Ich wäre gern … Was hättest du gern? → Ich hätte gern … Was würdest du gern machen? → Ich würde gern …'],
      },
      ex: [
        mc('K1', 'Wo wärst du gern?', I.react, '„Wo wärst du jetzt gern?“', ['Ich wäre jetzt gern in Italien.', 'Ich hätte gern ein Eis.', 'Ich würde gern kochen.'],
          ['“Where would you like to be now?”', '«Где ты хотел бы сейчас быть?»', '«Де ти хотів би зараз бути?»', '“Şimdi nerede olmak isterdin?”']),
        mc('K1', 'Was hätten Sie gern?', I.react, '„Was hätten Sie gern?“', ['Ich hätte gern mehr Zeit für meine Familie.', 'Ich wäre gern am Meer.', 'Ich würde gern verreisen.'],
          ['“What would you like to have?”', '«Что вы хотели бы иметь?»', '«Що ви хотіли б мати?»', '“Neyiniz olsun isterdiniz?”']),
        mc('K1', 'Frage zum Wunsch', I.matchQuestion, '„Ich würde gern Klavier spielen.“', ['Was würdest du gern lernen?', 'Wo wärst du jetzt gern?', 'Was hättest du gern?'],
          ['“I would like to play the piano.”', '«Я хотел бы играть на пианино.»', '«Я хотів би грати на піаніно.»', '“Piyano çalmak isterdim.”']),
        mc('K1', 'höflich fragen', I.situation, 'Du möchtest wissen, was dein Kollege Herr Novak gern in seiner Freizeit tun möchte. Was fragst du?', ['Was würden Sie gern machen?', 'Wo wären Sie gern?', 'Was hätten Sie gern?'],
          ['You want to know what your colleague Mr Novak would like to do in his free time. What do you ask?', 'Вы хотите узнать, чем ваш коллега господин Novak хотел бы заниматься в свободное время. Что вы спросите?', 'Ви хочете дізнатися, чим ваш колега пан Novak хотів би займатися у вільний час. Що ви запитаєте?', 'İş arkadaşınız Novak Bey’in boş zamanında ne yapmak istediğini öğrenmek istiyorsunuz. Ne sorarsınız?']),
        mc('K1', 'Was würdest du gern machen?', I.react, '„Was würdest du am Sonntag gern machen?“', ['Ich würde gern lange frühstücken.', 'Ich wäre gern reich.', 'Ich hätte gern einen Hund.'],
          ['“What would you like to do on Sunday?”', '«Что ты хотел бы делать в воскресенье?»', '«Що ти хотів би робити в неділю?»', '“Pazar günü ne yapmak isterdin?”']),
        gap('K1', 'wärst', I.verb, 'Wo ', ' du jetzt gern? – Am liebsten in den Bergen.', 'wärst', ['wäre', 'hättest'],
          ['Where would you like to be now? – In the mountains, most of all.', 'Где ты хотел бы сейчас быть? – Больше всего в горах.', 'Де ти хотів би зараз бути? – Найбільше в горах.', 'Şimdi nerede olmak isterdin? – En çok dağlarda.'], 'sein'),
        gap('K1', 'hättest', I.verb, 'Was ', ' du gern zum Geburtstag? – Ein neues Fahrrad.', 'hättest', ['wärst', 'hätte'],
          ['What would you like for your birthday? – A new bike.', 'Что ты хотел бы на день рождения? – Новый велосипед.', 'Що ти хотів би на день народження? – Новий велосипед.', 'Doğum gününde ne isterdin? – Yeni bir bisiklet.'], 'haben'),
        gap('K1', 'würden', I.verb, 'Was ', ' Sie gern lernen, Herr Kaya? – Ich würde gern Englisch lernen.', 'würden', ['würde', 'wären'],
          ['What would you like to learn, Mr Kaya? – I would like to learn English.', 'Что вы хотели бы изучать, господин Kaya? – Я хотел бы учить английский.', 'Що ви хотіли б вивчати, пане Kaya? – Я хотів би вчити англійську.', 'Ne öğrenmek isterdiniz, Kaya Bey? – İngilizce öğrenmek isterdim.'], 'werden (Konjunktiv II)'),
        gap('K1', 'Wo?', I.qword, '', ' wären Sie jetzt gern? – An einem See.', 'Wo', ['Was', 'Wer'],
          ['Where would you like to be now? – By a lake.', 'Где вы хотели бы сейчас быть? – У озера.', 'Де ви хотіли б зараз бути? – Біля озера.', 'Şimdi nerede olmak isterdiniz? – Bir göl kenarında.'], 'Wo / Was / Wer'),
        sb('K1', 'Frage nach Wünschen', I.question, 'Was / würdest / du / gern / machen?',
          ['What would you like to do?', 'Что бы ты хотел делать?', 'Що б ти хотів робити?', 'Ne yapmak isterdin?']),
      ],
    },
    {
      title: 'Du könntest …',
      t: ['You could …', 'Ты мог бы …', 'Ти міг би …', '… yapabilirsin'],
      card: {
        id: 'p1_koennte',
        rule: 'Vorschläge mit könnte: ich könnte, du könntest, er/es/sie könnte, wir könnten, ihr könntet, sie/Sie könnten. könnte steht auf Position 2, der Infinitiv am Satzende: Du könntest ins Kino gehen. Wir könnten am Samstag eine Radtour machen. Ein Vorschlag mit könnte ist freundlich: Es ist eine Idee, kein Muss.',
        examples: ['Du könntest heute Abend ins Kino gehen.', 'Wir könnten zusammen kochen.', 'Ihr könntet doch mitkommen.'],
        highlight: 'verb',
        t: [
          'Suggestions with könnte (could): ich könnte, du könntest, er/es/sie könnte, wir könnten, ihr könntet, sie/Sie könnten. könnte is in position 2, the infinitive at the end of the sentence: Du könntest ins Kino gehen. (You could go to the cinema.) Wir könnten am Samstag eine Radtour machen. A suggestion with könnte is friendly: it is an idea, not a must.',
          'Предложения с könnte (мог бы): ich könnte, du könntest, er/es/sie könnte, wir könnten, ihr könntet, sie/Sie könnten. könnte стоит на втором месте, инфинитив – в конце предложения: Du könntest ins Kino gehen. (Ты мог бы пойти в кино.) Wir könnten am Samstag eine Radtour machen. Предложение с könnte звучит дружелюбно: это идея, а не обязанность.',
          'Пропозиції з könnte (міг би): ich könnte, du könntest, er/es/sie könnte, wir könnten, ihr könntet, sie/Sie könnten. könnte стоїть на другому місці, інфінітив – у кінці речення: Du könntest ins Kino gehen. (Ти міг би піти в кіно.) Wir könnten am Samstag eine Radtour machen. Пропозиція з könnte звучить приязно: це ідея, а не обов’язок.',
          'könnte ile öneriler: ich könnte, du könntest, er/es/sie könnte, wir könnten, ihr könntet, sie/Sie könnten. könnte ikinci sırada, mastar cümlenin sonunda durur: Du könntest ins Kino gehen. (Sinemaya gidebilirsin.) Wir könnten am Samstag eine Radtour machen. könnte ile yapılan öneri naziktir: Bir fikirdir, zorunluluk değildir.',
        ],
        hint: ['könnte auf Position 2, Infinitiv am Ende: Wir könnten … machen. du könntest, wir könnten, ihr könntet.', 'könnte in position 2, infinitive at the end: Wir könnten … machen. du könntest, wir könnten, ihr könntet.', 'könnte на втором месте, инфинитив в конце: Wir könnten … machen. du könntest, wir könnten, ihr könntet.', 'könnte на другому місці, інфінітив у кінці: Wir könnten … machen. du könntest, wir könnten, ihr könntet.', 'könnte ikinci sırada, mastar sonda: Wir könnten … machen. du könntest, wir könnten, ihr könntet.'],
      },
      ex: [
        mc('G4', 'du könntest', I.choose, 'Dir ist langweilig? Du … doch ein Buch lesen.', ['könntest', 'könnte', 'könntet'],
          ['Are you bored? You could read a book.', 'Тебе скучно? Ты мог бы почитать книгу.', 'Тобі нудно? Ти міг би почитати книжку.', 'Canın mı sıkılıyor? Bir kitap okuyabilirsin.']),
        mc('G4', 'wir könnten', I.choose, 'Wir … am Sonntag einen Ausflug machen.', ['könnten', 'könntet', 'könntest'],
          ['We could go on a trip on Sunday.', 'В воскресенье мы могли бы поехать на экскурсию.', 'У неділю ми могли б поїхати на екскурсію.', 'Pazar günü bir gezi yapabiliriz.']),
        mc("G4", "Infinitiv am Ende", I.sentence, "Milan macht einen Vorschlag für den Abend.", ["Wir könnten zusammen einen Film sehen.","Wir könnten zusammen sehen einen Film.","Wir zusammen könnten einen Film sehen."], ["Milan is making a suggestion for the evening.","Milan предлагает, чем заняться вечером.","Milan пропонує, чим зайнятися ввечері.","Milan akşam için bir öneride bulunuyor."], {"c":"p1_koennte"}),
        mc('G4', 'Vorschlag', I.choose, 'Welcher Satz ist ein Vorschlag?', ['Du könntest mal wieder schwimmen gehen.', 'Du musst sofort schwimmen gehen.', 'Du bist gestern schwimmen gegangen.'],
          ['Which sentence is a suggestion?', 'В каком предложении что-то предлагают?', 'У якому реченні щось пропонують?', 'Hangi cümle bir öneridir?']),
        mc('G1', 'ihr könntet', I.choose, 'Ihr habt am Samstag Zeit? Ihr … uns besuchen.', ['könntet', 'könnten', 'könntest'],
          ['Are you (plural) free on Saturday? You could visit us.', 'У вас есть время в субботу? Вы могли бы прийти к нам в гости.', 'У вас є час у суботу? Ви могли б прийти до нас у гості.', 'Cumartesi vaktiniz var mı? Bizi ziyaret edebilirsiniz.']),
        gap('G1', 'du könntest', I.modal, 'Du ', ' am Wochenende deine Oma besuchen.', 'könntest', ['könnte', 'könntet'],
          ['You could visit your grandma at the weekend.', 'В выходные ты мог бы навестить бабушку.', 'У вихідні ти міг би відвідати бабусю.', 'Hafta sonu büyükanneni ziyaret edebilirsin.'], 'können (Konjunktiv II)'),
        gap('G1', 'wir könnten', I.modal, 'Das Wetter ist schön. Wir ', ' im Park ein Picknick machen.', 'könnten', ['könntet', 'könnte'],
          ['The weather is lovely. We could have a picnic in the park.', 'Погода хорошая. Мы могли бы устроить пикник в парке.', 'Погода гарна. Ми могли б улаштувати пікнік у парку.', 'Hava güzel. Parkta piknik yapabiliriz.'], 'können (Konjunktiv II)'),
        gap('G1', 'er könnte', I.modal, 'Tom hat morgen frei. Er ', ' mit uns wandern.', 'könnte', ['könntest', 'könnten'],
          ['Tom is off tomorrow. He could go hiking with us.', 'У Tom завтра выходной. Он мог бы пойти с нами в поход.', 'У Tom завтра вихідний. Він міг би піти з нами в похід.', 'Tom yarın izinli. Bizimle yürüyüşe gelebilir.'], 'können (Konjunktiv II)'),
        gap('G4', 'Infinitiv am Ende', I.verb, 'Wir könnten heute Abend zusammen Pizza ', '.', 'essen', ['isst', 'gegessen'],
          ['We could eat pizza together this evening.', 'Сегодня вечером мы могли бы вместе поесть пиццу.', 'Сьогодні ввечері ми могли б разом поїсти піцу.', 'Bu akşam birlikte pizza yiyebiliriz.'],
          ['eat', 'поесть', 'поїсти', 'yemek']),
        sb('G4', 'Vorschlag mit könnten', I.order, 'Wir / könnten / am Samstag / tanzen gehen.',
          ['We could go dancing on Saturday.', 'В субботу мы могли бы пойти потанцевать.', 'У суботу ми могли б піти потанцювати.', 'Cumartesi günü dansa gidebiliriz.'],
          { alt: ['Am Samstag könnten wir tanzen gehen.'] }),
      ],
    },
    {
      title: 'Wie wäre es mit …?',
      t: ['How about …?', 'Как насчёт …?', 'Як щодо …?', '… nasıl olur?'],
      card: {
        id: 'p1_vorschlag',
        rule: 'Vorschläge machen und über Pläne sprechen: Wir könnten am Samstag mal wieder ins Kino gehen. Wie wäre es mit einem Picknick? (mit + Dativ) Ich würde gern schwimmen gehen. Hast du Lust? Nach Plänen fragen: Was machst du gern am Freitagabend? Wofür nimmst du dir am Samstag Zeit? Und am Sonntag, was machst du da?',
        examples: ['Wie wäre es mit einer Radtour?', 'Ich würde gern ins Konzert gehen. Hast du Lust?', 'Wofür nimmst du dir am Wochenende Zeit?'],
        highlight: null,
        t: [
          'Making suggestions and talking about plans: Wir könnten am Samstag mal wieder ins Kino gehen. (We could go to the cinema again on Saturday.) Wie wäre es mit einem Picknick? (How about a picnic? – mit + dative) Ich würde gern schwimmen gehen. Hast du Lust? (Do you feel like it?) Asking about plans: Was machst du gern am Freitagabend? Wofür nimmst du dir am Samstag Zeit? (What do you make time for on Saturday?) Und am Sonntag, was machst du da?',
          'Как предлагать и говорить о планах: Wir könnten am Samstag mal wieder ins Kino gehen. (В субботу мы могли бы снова сходить в кино.) Wie wäre es mit einem Picknick? (Как насчёт пикника? – mit + Dativ) Ich würde gern schwimmen gehen. Hast du Lust? (Хочешь?) Как спросить о планах: Was machst du gern am Freitagabend? Wofür nimmst du dir am Samstag Zeit? (На что ты находишь время в субботу?) Und am Sonntag, was machst du da?',
          'Як пропонувати й говорити про плани: Wir könnten am Samstag mal wieder ins Kino gehen. (У суботу ми могли б знову сходити в кіно.) Wie wäre es mit einem Picknick? (Як щодо пікніка? – mit + Dativ) Ich würde gern schwimmen gehen. Hast du Lust? (Хочеш?) Як запитати про плани: Was machst du gern am Freitagabend? Wofür nimmst du dir am Samstag Zeit? (На що ти знаходиш час у суботу?) Und am Sonntag, was machst du da?',
          'Öneride bulunmak ve planlardan söz etmek: Wir könnten am Samstag mal wieder ins Kino gehen. (Cumartesi yine sinemaya gidebiliriz.) Wie wäre es mit einem Picknick? (Bir piknik nasıl olur? – mit + Dativ) Ich würde gern schwimmen gehen. Hast du Lust? (İster misin?) Planları sormak: Was machst du gern am Freitagabend? Wofür nimmst du dir am Samstag Zeit? (Cumartesi neye vakit ayırıyorsun?) Und am Sonntag, was machst du da?',
        ],
        hint: ['Wie wäre es mit + Dativ: mit einem Ausflug, mit einer Radtour. Hast du Lust? = Möchtest du mitmachen?', 'Wie wäre es mit (how about) + dative: mit einem Ausflug, mit einer Radtour. Hast du Lust? = would you like to join in?', 'Wie wäre es mit (как насчёт) + Dativ: mit einem Ausflug, mit einer Radtour. Hast du Lust? = хочешь присоединиться?', 'Wie wäre es mit (як щодо) + Dativ: mit einem Ausflug, mit einer Radtour. Hast du Lust? = хочеш приєднатися?', 'Wie wäre es mit (… nasıl olur) + Dativ: mit einem Ausflug, mit einer Radtour. Hast du Lust? = katılmak ister misin?'],
      },
      ex: [
        mc("K2", "Vorschlag machen", I.situation, "Du möchtest am Samstag mit einem Freund ins Museum gehen. Wie machst du einen Vorschlag?", ["Wir könnten am Samstag ins Museum gehen. Hast du Lust?","Das Museum ist am Samstag geschlossen.","Ich war am Samstag im Museum."], ["You would like to go to the museum with a friend on Saturday. How do you make a suggestion?","Вы хотите в субботу пойти с другом в музей. Как вы это предложите?","Ви хочете в суботу піти з другом до музею. Як ви це запропонуєте?","Cumartesi günü bir arkadaşınızla müzeye gitmek istiyorsunuz. Nasıl öneride bulunursunuz?"], {"c":"p1_vorschlag"}),
        mc('K2', 'mit einem', I.choose, 'Wie wäre es mit … Ausflug an den See?', ['einem', 'einen', 'ein'],
          ['How about a trip to the lake?', 'Как насчёт поездки на озеро?', 'Як щодо поїздки на озеро?', 'Göle bir gezi nasıl olur?']),
        mc('K2', 'mit einer', I.choose, 'Wie wäre es mit … Radtour?', ['einer', 'eine', 'einem'],
          ['How about a bike ride?', 'Как насчёт велопрогулки?', 'Як щодо велопрогулянки?', 'Bir bisiklet turu nasıl olur?']),
        mc('K2', 'Hast du Lust?', I.choose, 'Was bedeutet „Hast du Lust?“', ['Möchtest du das auch machen?', 'Hast du Hunger?', 'Bist du müde?'],
          ['What does “Hast du Lust?” mean?', 'Что значит «Hast du Lust?»', 'Що означає «Hast du Lust?»', '“Hast du Lust?” ne demek?']),
        mc('K2', 'Wofür nimmst du dir Zeit?', I.react, '„Wofür nimmst du dir am Samstag Zeit?“', ['Für meine Familie. Wir machen einen Ausflug.', 'Um zehn Uhr.', 'Ja, gern.'],
          ['“What do you make time for on Saturday?”', '«На что ты находишь время в субботу?»', '«На що ти знаходиш час у суботу?»', '“Cumartesi günü neye vakit ayırıyorsun?”']),
        gap('K2', 'Wie wäre es …?', I.verb, 'Wie ', ' es mit einem Kinoabend?', 'wäre', ['hätte', 'würde'],
          ['How about an evening at the cinema?', 'Как насчёт вечера в кино?', 'Як щодо вечора в кіно?', 'Bir sinema akşamı nasıl olur?'], KII),
        gap('K2', 'Lust', I.word, 'Wir gehen heute Abend tanzen. Hast du ', '?', 'Lust', ['Hunger', 'Angst'],
          ['We are going dancing this evening. Do you feel like coming?', 'Сегодня вечером мы идём танцевать. Хочешь с нами?', 'Сьогодні ввечері ми йдемо танцювати. Хочеш із нами?', 'Bu akşam dansa gidiyoruz. İster misin?'],
          ['desire (to do it)', 'желание', 'бажання', 'istek']),
        gap('K2', 'Wofür?', I.qword, '', ' nimmst du dir am Sonntag Zeit? – Für meine Hobbys.', 'Wofür', ['Worauf', 'Womit'],
          ['What do you make time for on Sunday? – For my hobbies.', 'На что ты находишь время в воскресенье? – На свои хобби.', 'На що ти знаходиш час у неділю? – На свої хобі.', 'Pazar günü neye vakit ayırıyorsun? – Hobilerime.'], 'für + was'),
        gap('K2', 'mit', I.prep, 'Wie wäre es ', ' einem Spaziergang im Park?', 'mit', ['für', 'von'],
          ['How about a walk in the park?', 'Как насчёт прогулки в парке?', 'Як щодо прогулянки в парку?', 'Parkta bir yürüyüş nasıl olur?'], 'mit / für / von'),
        sb('K2', 'Wie wäre es mit …?', I.question, 'Wie / wäre / es / mit einem Picknick?',
          ['How about a picnic?', 'Как насчёт пикника?', 'Як щодо пікніка?', 'Bir piknik nasıl olur?']),
      ],
    },
    {
      title: 'Gute Idee!',
      t: ['Good idea!', 'Хорошая идея!', 'Гарна ідея!', 'İyi fikir!'],
      card: {
        id: 'p1_annehmen',
        rule: 'Einen Vorschlag annehmen: Ja, gern. Warum nicht? Gute Idee. Das machen wir! Einverstanden. In Ordnung. Ja, das geht bei mir. Ich komme gern mit. Ich mache gern mit. Dann fragt man nach Zeit und Ort: Um wie viel Uhr treffen wir uns? Wann geht es los? Und zum Schluss: Dann bis Samstag!',
        examples: ['Wollen wir schwimmen gehen? – Gute Idee. Das machen wir!', 'Ja, das geht bei mir. Um wie viel Uhr?', 'Einverstanden. Dann bis morgen!'],
        highlight: null,
        t: [
          'Accepting a suggestion: Ja, gern. Warum nicht? (Why not?) Gute Idee. Das machen wir! (Let’s do that!) Einverstanden. (Agreed.) In Ordnung. (All right.) Ja, das geht bei mir. (Yes, that works for me.) Ich komme gern mit. Ich mache gern mit. (I would love to join in.) Then you ask about time and place: Um wie viel Uhr treffen wir uns? Wann geht es los? (When does it start?) And finally: Dann bis Samstag! (See you on Saturday then!)',
          'Как принять предложение: Ja, gern. Warum nicht? (Почему бы и нет?) Gute Idee. Das machen wir! (Так и сделаем!) Einverstanden. (Согласен.) In Ordnung. (Хорошо.) Ja, das geht bei mir. (Да, мне это подходит.) Ich komme gern mit. Ich mache gern mit. (С удовольствием присоединюсь.) Затем спрашивают о времени и месте: Um wie viel Uhr treffen wir uns? Wann geht es los? (Когда начинаем?) И в конце: Dann bis Samstag! (Тогда до субботы!)',
          'Як прийняти пропозицію: Ja, gern. Warum nicht? (Чому б і ні?) Gute Idee. Das machen wir! (Так і зробимо!) Einverstanden. (Згоден.) In Ordnung. (Гаразд.) Ja, das geht bei mir. (Так, мені це підходить.) Ich komme gern mit. Ich mache gern mit. (Охоче приєднаюся.) Потім запитують про час і місце: Um wie viel Uhr treffen wir uns? Wann geht es los? (Коли починаємо?) І наприкінці: Dann bis Samstag! (Тоді до суботи!)',
          'Bir öneriyi kabul etmek: Ja, gern. Warum nicht? (Neden olmasın?) Gute Idee. Das machen wir! (Öyle yapalım!) Einverstanden. (Anlaştık.) In Ordnung. (Tamam.) Ja, das geht bei mir. (Evet, bana uyar.) Ich komme gern mit. Ich mache gern mit. (Seve seve katılırım.) Sonra saat ve yer sorulur: Um wie viel Uhr treffen wir uns? Wann geht es los? (Ne zaman başlıyor?) Ve en sonda: Dann bis Samstag! (O zaman cumartesi görüşürüz!)',
        ],
        hint: ['Einverstanden = Ja, das ist okay für mich. Das geht bei mir = Ich habe Zeit.', 'Einverstanden = yes, that is okay for me. Das geht bei mir = I have time.', 'Einverstanden = да, меня это устраивает. Das geht bei mir = у меня есть время.', 'Einverstanden = так, мене це влаштовує. Das geht bei mir = у мене є час.', 'Einverstanden = evet, benim için uygun. Das geht bei mir = vaktim var.'],
      },
      ex: [
        mc('K3', 'annehmen', I.react, '„Wir könnten am Sonntag wandern. Hast du Lust?“ – Du findest die Idee gut.', ['Gute Idee. Ich komme gern mit.', 'Schade, das geht leider nicht.', 'Ich würde eigentlich lieber zu Hause bleiben.'],
          ['“We could go hiking on Sunday. Do you feel like it?” – You like the idea.', '«В воскресенье мы могли бы пойти в поход. Хочешь?» – Вам нравится идея.', '«У неділю ми могли б піти в похід. Хочеш?» – Вам подобається ідея.', '“Pazar günü yürüyüşe çıkabiliriz. İster misin?” – Fikri beğeniyorsunuz.']),
        mc('K3', 'Einverstanden', I.choose, 'Was bedeutet „Einverstanden“?', ['Ja, das ist okay für mich.', 'Nein, das möchte ich nicht.', 'Ich weiß es noch nicht.'],
          ['What does “Einverstanden” mean?', 'Что значит «Einverstanden»?', 'Що означає «Einverstanden»?', '“Einverstanden” ne demek?']),
        mc('K3', 'Warum nicht?', I.react, '„Wie wäre es mit einem Kaffee am Nachmittag?“ – Du hast Zeit und Lust.', ['Warum nicht? Um wie viel Uhr?', 'Tut mir leid, da kann ich nicht.', 'Ich trinke nie Kaffee.'],
          ['“How about a coffee in the afternoon?” – You have time and you feel like it.', '«Как насчёт кофе после обеда?» – У вас есть время и желание.', '«Як щодо кави після обіду?» – У вас є час і бажання.', '“Öğleden sonra bir kahve nasıl olur?” – Vaktiniz ve isteğiniz var.']),
        mc('K3', 'Dann bis …', I.choose, 'Ihr habt alles geplant. Was sagst du zum Schluss?', ['In Ordnung. Dann bis Samstag!', 'Wie wäre es mit Samstag?', 'Hast du am Samstag Zeit?'],
          ['You have planned everything. What do you say at the end?', 'Вы обо всём договорились. Что вы скажете в конце?', 'Ви про все домовилися. Що ви скажете наприкінці?', 'Her şeyi planladınız. En sonda ne dersiniz?']),
        mc('K3', 'zusagen', I.choose, 'Mit welchem Satz sagst du Ja zu einem Vorschlag?', ['Das machen wir!', 'Da kann ich leider nicht.', 'Ich habe leider keine Zeit.'],
          ['Which sentence do you use to say yes to a suggestion?', 'Каким предложением вы соглашаетесь?', 'Яким реченням ви погоджуєтеся?', 'Bir öneriye hangi cümleyle evet dersiniz?']),
        gap('K3', 'Gute Idee', I.word, 'Ins Kino gehen? Gute ', '! Das machen wir.', 'Idee', ['Zeit', 'Lust'],
          ['Go to the cinema? Good idea! Let’s do that.', 'Пойти в кино? Хорошая идея! Так и сделаем.', 'Піти в кіно? Гарна ідея! Так і зробимо.', 'Sinemaya gitmek mi? İyi fikir! Öyle yapalım.'],
          ['idea', 'идея', 'ідея', 'fikir']),
        gap('K3', 'mitkommen', I.word, 'Ihr geht schwimmen? Ich komme gern ', '.', 'mit', ['zu', 'an'],
          ['You are going swimming? I would love to come along.', 'Вы идёте плавать? Я с удовольствием пойду с вами.', 'Ви йдете плавати? Я охоче піду з вами.', 'Yüzmeye mi gidiyorsunuz? Seve seve gelirim.'], 'mitkommen'),
        gap('K3', 'Einverstanden', I.expression, 'Treffen wir uns um acht vor dem Kino? – ', '. Dann bis acht!', 'Einverstanden', ['Schade', 'Leider'],
          ['Shall we meet at eight in front of the cinema? – Agreed. See you at eight then!', 'Встретимся в восемь перед кинотеатром? – Договорились. Тогда до восьми!', 'Зустрінемося о восьмій перед кінотеатром? – Домовилися. Тоді до восьмої!', 'Saat sekizde sinemanın önünde buluşalım mı? – Anlaştık. O zaman sekizde görüşürüz!'],
          ['agreed', 'согласен, договорились', 'згоден, домовилися', 'anlaştık']),
        gap('K3', 'Um wie viel Uhr?', I.word, 'Ja, das geht bei mir. Um wie viel ', ' treffen wir uns?', 'Uhr', ['Zeit', 'Stunde'],
          ['Yes, that works for me. What time shall we meet?', 'Да, мне подходит. Во сколько встречаемся?', 'Так, мені підходить. О котрій зустрічаємося?', 'Evet, bana uyar. Saat kaçta buluşuyoruz?'],
          ['o’clock (what time)', 'час (во сколько)', 'година (о котрій)', 'saat (kaçta)']),
        sb('K3', 'Ich komme gern mit.', I.order, 'Ich / komme / gern / mit.',
          ['I would love to come along.', 'Я с удовольствием пойду с вами.', 'Я охоче піду з вами.', 'Seve seve gelirim.'],
          { alt: ['Gern komme ich mit.'] }),
      ],
    },
    {
      title: 'Schade, das geht leider nicht.',
      t: ['What a pity, that is not possible.', 'Жаль, к сожалению, не получится.', 'Шкода, на жаль, не вийде.', 'Ne yazık, maalesef olmuyor.'],
      card: {
        id: 'p1_ablehnen',
        rule: 'Einen Vorschlag ablehnen und Bedauern ausdrücken: Schade, das geht leider nicht. Tut mir leid, aber ich muss arbeiten. Da kann ich leider nicht. Ich habe leider keine Zeit. Ich würde gern kommen, aber ich bin krank. Höflich ist ein anderer Vorschlag: Aber am Sonntag habe ich Zeit. Ich würde eigentlich lieber ins Kino gehen.',
        examples: ['Tut mir leid, aber am Freitag kann ich nicht.', 'Ich würde gern mitmachen, aber ich muss lernen.', 'Ich würde eigentlich lieber zu Hause bleiben.'],
        highlight: null,
        t: [
          'Turning down a suggestion and expressing regret: Schade, das geht leider nicht. (What a pity, that is not possible.) Tut mir leid, aber ich muss arbeiten. Da kann ich leider nicht. (I am afraid I cannot make it then.) Ich habe leider keine Zeit. Ich würde gern kommen, aber ich bin krank. (I would love to come, but …) A different suggestion is polite: Aber am Sonntag habe ich Zeit. Ich würde eigentlich lieber ins Kino gehen. (Actually I would rather go to the cinema.)',
          'Как отказаться и выразить сожаление: Schade, das geht leider nicht. (Жаль, к сожалению, не получится.) Tut mir leid, aber ich muss arbeiten. Da kann ich leider nicht. (В это время я, к сожалению, не могу.) Ich habe leider keine Zeit. Ich würde gern kommen, aber ich bin krank. (Я бы с удовольствием пришёл, но …) Вежливо предложить другое: Aber am Sonntag habe ich Zeit. Ich würde eigentlich lieber ins Kino gehen. (Вообще-то я бы лучше пошёл в кино.)',
          'Як відмовитися й висловити жаль: Schade, das geht leider nicht. (Шкода, на жаль, не вийде.) Tut mir leid, aber ich muss arbeiten. Da kann ich leider nicht. (У цей час я, на жаль, не можу.) Ich habe leider keine Zeit. Ich würde gern kommen, aber ich bin krank. (Я б охоче прийшов, але …) Ввічливо запропонувати інше: Aber am Sonntag habe ich Zeit. Ich würde eigentlich lieber ins Kino gehen. (Узагалі я б краще пішов у кіно.)',
          'Bir öneriyi reddetmek ve üzüntü bildirmek: Schade, das geht leider nicht. (Ne yazık, maalesef olmuyor.) Tut mir leid, aber ich muss arbeiten. Da kann ich leider nicht. (O zaman maalesef gelemem.) Ich habe leider keine Zeit. Ich würde gern kommen, aber ich bin krank. (Gelmeyi çok isterdim ama …) Başka bir öneri sunmak kibardır: Aber am Sonntag habe ich Zeit. Ich würde eigentlich lieber ins Kino gehen. (Aslında sinemaya gitmeyi tercih ederdim.)',
        ],
        hint: ['Erst Bedauern (Schade. Tut mir leid.), dann der Grund mit aber: …, aber ich habe keine Zeit.', 'First regret (Schade. Tut mir leid.), then the reason with aber: …, aber ich habe keine Zeit.', 'Сначала сожаление (Schade. Tut mir leid.), затем причина с aber: …, aber ich habe keine Zeit.', 'Спочатку жаль (Schade. Tut mir leid.), потім причина з aber: …, aber ich habe keine Zeit.', 'Önce üzüntü (Schade. Tut mir leid.), sonra aber ile neden: …, aber ich habe keine Zeit.'],
      },
      ex: [
        mc('K4', 'ablehnen', I.react, '„Kommst du am Freitag zu meiner Party?“ – Du musst am Freitag arbeiten.', ['Tut mir leid, aber am Freitag muss ich arbeiten.', 'Gute Idee. Das machen wir!', 'Ja, das geht bei mir.'],
          ['“Are you coming to my party on Friday?” – You have to work on Friday.', '«Ты придёшь в пятницу на мою вечеринку?» – В пятницу вам нужно работать.', '«Ти прийдеш у п’ятницю на мою вечірку?» – У п’ятницю вам треба працювати.', '“Cuma günü partime geliyor musun?” – Cuma günü çalışmak zorundasınız.']),
        mc('K4', 'lieber', I.situation, 'Deine Kollegin möchte mit dir joggen gehen. Du möchtest lieber schwimmen. Was sagst du?', ['Ich würde eigentlich lieber schwimmen gehen.', 'Einverstanden. Ich komme gern mit.', 'Joggen ist eine gute Idee.'],
          ['Your colleague wants to go jogging with you. You would rather go swimming. What do you say?', 'Ваша коллега хочет пойти с вами на пробежку. Вы предпочли бы поплавать. Что вы скажете?', 'Ваша колега хоче піти з вами на пробіжку. Ви воліли б поплавати. Що ви скажете?', 'İş arkadaşınız sizinle koşuya çıkmak istiyor. Siz yüzmeyi tercih edersiniz. Ne dersiniz?']),
        mc('K4', 'höflich ablehnen', I.choose, 'Du kannst nicht mitkommen. Welche Antwort ist höflich?', ['Schade, das geht leider nicht. Aber am Sonntag habe ich Zeit.', 'Nein.', 'Das ist mir egal.'],
          ['You cannot come along. Which answer is polite?', 'Вы не можете пойти. Какой ответ вежливый?', 'Ви не можете піти. Яка відповідь ввічлива?', 'Gelemiyorsunuz. Hangi cevap kibardır?']),
        mc('K4', 'Ich würde gern …, aber …', I.choose, 'Ich … gern kommen, aber ich bin krank.', ['würde', 'wäre', 'hätte'],
          ['I would love to come, but I am ill.', 'Я бы с удовольствием пришёл, но я болен.', 'Я б охоче прийшов, але я хворий.', 'Gelmeyi çok isterdim ama hastayım.']),
        mc('K4', 'Da kann ich leider nicht.', I.choose, 'Was bedeutet „Da kann ich leider nicht“?', ['Ich habe an diesem Tag keine Zeit.', 'Ich komme gern mit.', 'Ich weiß nicht, wo das ist.'],
          ['What does “Da kann ich leider nicht” mean?', 'Что значит «Da kann ich leider nicht»?', 'Що означає «Da kann ich leider nicht»?', '“Da kann ich leider nicht” ne demek?']),
        gap('K4', 'leider', I.word, 'Schade, das geht ', ' nicht. Ich muss am Samstag arbeiten.', 'leider', ['gern', 'bitte'],
          ['What a pity, I am afraid that is not possible. I have to work on Saturday.', 'Жаль, к сожалению, не получится. В субботу мне нужно работать.', 'Шкода, на жаль, не вийде. У суботу мені треба працювати.', 'Ne yazık, maalesef olmuyor. Cumartesi çalışmak zorundayım.'],
          ['unfortunately', 'к сожалению', 'на жаль', 'maalesef']),
        gap('K4', 'aber', I.conjunction, 'Ich würde gern mitkommen, ', ' ich habe keine Zeit.', 'aber', ['und', 'oder'],
          ['I would love to come along, but I have no time.', 'Я бы с удовольствием пошёл, но у меня нет времени.', 'Я б охоче пішов, але в мене немає часу.', 'Gelmeyi çok isterdim ama vaktim yok.'], 'aber / und / oder'),
        gap('K4', 'lieber', I.comparison, 'Kino? Ich würde eigentlich ', ' ins Theater gehen.', 'lieber', ['liebsten', 'lieb'],
          ['The cinema? Actually I would rather go to the theatre.', 'Кино? Вообще-то я бы лучше пошёл в театр.', 'Кіно? Узагалі я б краще пішов до театру.', 'Sinema mı? Aslında tiyatroya gitmeyi tercih ederdim.'], 'gern'),
        gap('K4', 'Tut mir leid', I.word, 'Tut mir ', ', aber heute kann ich nicht.', 'leid', ['schade', 'gern'],
          ['I am sorry, but I cannot make it today.', 'Мне жаль, но сегодня я не могу.', 'Мені шкода, але сьогодні я не можу.', 'Üzgünüm ama bugün gelemem.'],
          ['sorry', 'жаль', 'шкода', 'üzgünüm']),
        sb('K4', 'keine Zeit', I.order, 'Ich / habe / leider / keine Zeit.',
          ['Unfortunately I have no time.', 'К сожалению, у меня нет времени.', 'На жаль, у мене немає часу.', 'Maalesef vaktim yok.'],
          { alt: ['Leider habe ich keine Zeit.'] }),
      ],
    },
    {
      title: 'trotzdem',
      t: ['trotzdem (nevertheless)', 'trotzdem (всё равно, тем не менее)', 'trotzdem (все одно, попри це)', 'trotzdem (yine de)'],
      card: {
        id: 'p1_trotzdem',
        rule: 'trotzdem verbindet zwei Sätze mit einem Gegensatz: Etwas spricht dagegen, aber man macht es. Es regnet. Trotzdem machen wir eine Radtour. trotzdem steht auf Position 1, dann kommt sofort das Verb (Position 2), danach das Subjekt. trotzdem kann auch nach dem Verb stehen: Wir machen trotzdem eine Radtour.',
        examples: ['Ich bin müde. Trotzdem gehe ich zum Sport.', 'Eva hat keine Zeit. Sie kommt trotzdem mit.', 'Das Wetter ist schlecht. Trotzdem grillen wir.'],
        highlight: null,
        t: [
          'trotzdem (nevertheless, anyway) links two sentences that contrast: something speaks against it, but you do it. Es regnet. Trotzdem machen wir eine Radtour. (It is raining. We are going on a bike ride anyway.) trotzdem is in position 1, then the verb follows straight away (position 2), then the subject. trotzdem can also come after the verb: Wir machen trotzdem eine Radtour.',
          'trotzdem (всё равно, тем не менее) соединяет два предложения с противопоставлением: что-то мешает, но это всё равно делают. Es regnet. Trotzdem machen wir eine Radtour. (Идёт дождь. Мы всё равно едем на велопрогулку.) trotzdem стоит на первом месте, сразу за ним – глагол (второе место), затем подлежащее. trotzdem может стоять и после глагола: Wir machen trotzdem eine Radtour.',
          'trotzdem (все одно, попри це) поєднує два речення з протиставленням: щось заважає, але це все одно роблять. Es regnet. Trotzdem machen wir eine Radtour. (Іде дощ. Ми все одно їдемо на велопрогулянку.) trotzdem стоїть на першому місці, одразу за ним – дієслово (друге місце), потім підмет. trotzdem може стояти й після дієслова: Wir machen trotzdem eine Radtour.',
          'trotzdem (yine de) karşıtlık içeren iki cümleyi bağlar: Bir şey buna engeldir ama insan yine de yapar. Es regnet. Trotzdem machen wir eine Radtour. (Yağmur yağıyor. Yine de bisiklet turu yapıyoruz.) trotzdem birinci sırada durur, hemen ardından fiil (ikinci sıra), sonra özne gelir. trotzdem fiilden sonra da durabilir: Wir machen trotzdem eine Radtour.',
        ],
        hint: ['Trotzdem + Verb + Subjekt: Trotzdem gehe ich … Oder: Ich gehe trotzdem …', 'Trotzdem + verb + subject: Trotzdem gehe ich … Or: Ich gehe trotzdem …', 'Trotzdem + глагол + подлежащее: Trotzdem gehe ich … Или: Ich gehe trotzdem …', 'Trotzdem + дієслово + підмет: Trotzdem gehe ich … Або: Ich gehe trotzdem …', 'Trotzdem + fiil + özne: Trotzdem gehe ich … Ya da: Ich gehe trotzdem …'],
      },
      ex: [
        mc('G5', 'Verb auf Position 2', I.sentence, 'Es ist sehr kalt.', ['Trotzdem gehen wir spazieren.', 'Trotzdem wir gehen spazieren.', 'Trotzdem wir spazieren gehen.'],
          ['It is very cold.', 'Очень холодно.', 'Дуже холодно.', 'Hava çok soğuk.']),
        mc('G5', 'trotzdem', I.choose, 'Ich habe wenig Geld. … fahre ich in den Urlaub.', ['Trotzdem', 'Weil', 'Dass'],
          ['I have little money. I am going on holiday anyway.', 'У меня мало денег. Я всё равно еду в отпуск.', 'У мене мало грошей. Я все одно їду у відпустку.', 'Param az. Yine de tatile gidiyorum.']),
        mc('G5', 'Gegensatz', I.choose, 'Welcher Satz passt? „Paul ist erkältet. Trotzdem …“', ['geht er zur Arbeit.', 'bleibt er im Bett.', 'trinkt er heißen Tee.'],
          ['Which sentence fits? “Paul has a cold. Nevertheless …”', 'Какое продолжение подходит? «Paul простужен. Тем не менее …»', 'Яке продовження підходить? «Paul застуджений. Попри це …»', 'Hangi cümle uygun? “Paul üşütmüş. Yine de …”']),
        mc('G5', 'trotzdem nach dem Verb', I.sentence, 'Der Film ist langweilig.', ['Wir sehen ihn trotzdem bis zum Ende.', 'Wir trotzdem sehen ihn bis zum Ende.', 'Trotzdem wir sehen ihn bis zum Ende.'],
          ['The film is boring.', 'Фильм скучный.', 'Фільм нудний.', 'Film sıkıcı.']),
        gap('G5', 'Verb auf Position 2', I.verb, 'Es regnet stark. Trotzdem ', ' die Kinder draußen.', 'spielen', ['spielt', 'gespielt'],
          ['It is raining heavily. The children are playing outside anyway.', 'Идёт сильный дождь. Дети всё равно играют на улице.', 'Іде сильний дощ. Діти все одно граються надворі.', 'Çok yağmur yağıyor. Çocuklar yine de dışarıda oynuyor.'],
          ['play', 'играть', 'гратися', 'oynamak']),
        gap('G5', 'Trotzdem', I.conjunction, 'Ich habe schon gegessen. ', ' esse ich noch ein Stück Kuchen.', 'Trotzdem', ['Weil', 'Aber'],
          ['I have already eaten. I am having another piece of cake anyway.', 'Я уже поел. Всё равно я съем ещё кусочек пирога.', 'Я вже поїв. Усе одно я з’їм іще шматочок пирога.', 'Yemek yedim bile. Yine de bir dilim kek daha yiyorum.'], 'trotzdem / weil / aber'),
        gap("G5", "Subjekt nach dem Verb", I.pronoun, "Ergänze das Personalpronomen für „eine Frau“: Trotzdem geht ", " noch ins Fitnessstudio.", "sie", ["ihr","ihn"], ["Complete the personal pronoun for eine Frau: Trotzdem geht … noch ins Fitnessstudio.","Дополните личное местоимение для eine Frau: Trotzdem geht … noch ins Fitnessstudio.","Доповніть особовий займенник для eine Frau: Trotzdem geht … noch ins Fitnessstudio.","eine Frau için kişi zamirini tamamlayın: Trotzdem geht … noch ins Fitnessstudio."], "eine Frau", {"c":"p1_trotzdem"}),
        gap('G5', 'trotzdem', I.word, 'Der Kurs ist teuer. Ich melde mich ', ' an.', 'trotzdem', ['weil', 'dass'],
          ['The course is expensive. I am signing up anyway.', 'Курс дорогой. Я всё равно записываюсь.', 'Курс дорогий. Я все одно записуюся.', 'Kurs pahalı. Yine de kaydoluyorum.'],
          ['nevertheless, anyway', 'всё равно, тем не менее', 'все одно, попри це', 'yine de']),
        sb('G5', 'Trotzdem auf Position 1', I.order, 'Trotzdem / machen / wir / eine Radtour.',
          ['We are going on a bike ride anyway.', 'Мы всё равно едем на велопрогулку.', 'Ми все одно їдемо на велопрогулянку.', 'Yine de bisiklet turu yapıyoruz.'],
          { alt: ['Wir machen trotzdem eine Radtour.'] }),
        sb('G5', 'trotzdem nach dem Verb', I.order, 'Ich / gehe / trotzdem / zur Arbeit.',
          ['I am going to work anyway.', 'Я всё равно иду на работу.', 'Я все одно йду на роботу.', 'Yine de işe gidiyorum.'],
          { alt: ['Trotzdem gehe ich zur Arbeit.'] }),
      ],
    },
    {
      title: 'Veranstaltungen und Kurse',
      t: ['Events and courses', 'Мероприятия и курсы', 'Заходи й курси', 'Etkinlikler ve kurslar'],
      card: {
        id: 'p1_veranstaltungen',
        rule: 'Veranstaltungen und Kurse: die Veranstaltung (ein Konzert, ein Fest, ein Vortrag), das Programm, der Kurs, der Vortrag (jemand spricht über ein Thema), die Führung (jemand zeigt ein Museum oder die Stadt), die Ausstellung (Bilder oder Fotos im Museum), die Anmeldung (sich anmelden), die Teilnahme (teilnehmen = mitmachen), der Eintritt (Eintritt frei = es kostet nichts), die Ermäßigung (ein kleinerer Preis für Kinder oder Studenten).',
        examples: ['Der Eintritt ist frei.', 'Die Teilnahme kostet fünf Euro.', 'Die Anmeldung ist bis Freitag möglich.'],
        highlight: 'article',
        t: [
          'Events and courses: die Veranstaltung (event: a concert, a party, a talk), das Programm (programme), der Kurs (course), der Vortrag (talk: someone speaks about a subject), die Führung (guided tour: someone shows you a museum or the town), die Ausstellung (exhibition: pictures or photos in a museum), die Anmeldung (registration; sich anmelden = sign up), die Teilnahme (participation; teilnehmen = take part), der Eintritt (admission; Eintritt frei = it costs nothing), die Ermäßigung (discount: a lower price for children or students).',
          'Мероприятия и курсы: die Veranstaltung (мероприятие: концерт, праздник, доклад), das Programm (программа), der Kurs (курс), der Vortrag (доклад: кто-то рассказывает на тему), die Führung (экскурсия: кто-то показывает музей или город), die Ausstellung (выставка: картины или фотографии в музее), die Anmeldung (запись; sich anmelden = записаться), die Teilnahme (участие; teilnehmen = участвовать), der Eintritt (вход; Eintritt frei = бесплатно), die Ermäßigung (скидка: цена ниже для детей или студентов).',
          'Заходи й курси: die Veranstaltung (захід: концерт, свято, доповідь), das Programm (програма), der Kurs (курс), der Vortrag (доповідь: хтось розповідає на тему), die Führung (екскурсія: хтось показує музей або місто), die Ausstellung (виставка: картини чи фотографії в музеї), die Anmeldung (запис; sich anmelden = записатися), die Teilnahme (участь; teilnehmen = брати участь), der Eintritt (вхід; Eintritt frei = безкоштовно), die Ermäßigung (знижка: нижча ціна для дітей або студентів).',
          'Etkinlikler ve kurslar: die Veranstaltung (etkinlik: konser, kutlama, konuşma), das Programm (program), der Kurs (kurs), der Vortrag (konuşma: biri bir konu hakkında konuşur), die Führung (rehberli gezi: biri müzeyi ya da şehri gezdirir), die Ausstellung (sergi: müzede resimler ya da fotoğraflar), die Anmeldung (kayıt; sich anmelden = kaydolmak), die Teilnahme (katılım; teilnehmen = katılmak), der Eintritt (giriş; Eintritt frei = ücretsiz), die Ermäßigung (indirim: çocuklar ya da öğrenciler için daha düşük fiyat).',
        ],
        hint: ['Eintritt = Geld für den Eingang. Teilnahme = mitmachen. Anmeldung = vorher Bescheid sagen. Führung = jemand zeigt alles.', 'Eintritt = money you pay at the entrance. Teilnahme = taking part. Anmeldung = signing up beforehand. Führung = someone shows you round.', 'Eintritt = плата за вход. Teilnahme = участие. Anmeldung = предварительная запись. Führung = экскурсия.', 'Eintritt = плата за вхід. Teilnahme = участь. Anmeldung = попередній запис. Führung = екскурсія.', 'Eintritt = giriş ücreti. Teilnahme = katılım. Anmeldung = önceden kayıt. Führung = rehberli gezi.'],
      },
      ex: [
        mc('W2', 'Eintritt frei', I.sign, 'Auf einem Plakat steht: „Eintritt frei“.', ['Man muss nichts bezahlen.', 'Man braucht eine Anmeldung.', 'Die Veranstaltung fällt aus.'],
          ['A poster says: “Eintritt frei”.', 'На афише написано: «Eintritt frei».', 'На афіші написано: «Eintritt frei».', 'Bir afişte “Eintritt frei” yazıyor.']),
        mc('W2', 'Führung', I.choose, 'Im Museum zeigt eine Frau den Besuchern die Bilder und erklärt sie. Das ist eine …', ['Führung', 'Anmeldung', 'Ermäßigung'],
          ['In the museum a woman shows the visitors the pictures and explains them. That is a …', 'В музее женщина показывает посетителям картины и рассказывает о них. Это …', 'У музеї жінка показує відвідувачам картини й розповідає про них. Це …', 'Müzede bir kadın ziyaretçilere resimleri gösterip açıklıyor. Bu bir …']),
        mc('W2', 'teilnehmen', I.choose, 'Was bedeutet „an einem Kurs teilnehmen“?', ['bei einem Kurs mitmachen', 'einen Kurs bezahlen', 'einen Kurs absagen'],
          ['What does “an einem Kurs teilnehmen” mean?', 'Что значит «an einem Kurs teilnehmen»?', 'Що означає «an einem Kurs teilnehmen»?', '“an einem Kurs teilnehmen” ne demek?']),
        mc('W2', 'Veranstaltungen', I.odd, 'Drei Wörter sind Veranstaltungen, ein Wort nicht.', ['Ermäßigung', 'Konzert', 'Vortrag', 'Ausstellung'], null),
        mc('W2', 'Ermäßigung', I.choose, 'Studenten zahlen nur vier Euro, alle anderen acht Euro. Studenten bekommen eine …', ['Ermäßigung', 'Führung', 'Anmeldung'],
          ['Students pay only four euros, everyone else eight euros. Students get a …', 'Студенты платят только четыре евро, все остальные – восемь. Студенты получают …', 'Студенти платять лише чотири євро, усі інші – вісім. Студенти отримують …', 'Öğrenciler sadece dört avro, diğerleri sekiz avro ödüyor. Öğrenciler … alıyor.']),
        gap('W2', 'Anmeldung', I.word, 'Der Kurs hat nur zehn Plätze. Eine ', ' ist nötig.', 'Anmeldung', ['Ausstellung', 'Ermäßigung'],
          ['The course has only ten places. You need to register.', 'На курсе только десять мест. Нужна запись.', 'На курсі лише десять місць. Потрібен запис.', 'Kursta sadece on yer var. Kayıt gerekiyor.'],
          ['registration', 'запись, регистрация', 'запис, реєстрація', 'kayıt']),
        gap('W2', 'Vortrag', I.word, 'Heute Abend hält Frau Dr. Albers einen ', ' über gesunde Ernährung.', 'Vortrag', ['Eintritt', 'Kurs'],
          ['This evening Dr Albers is giving a talk about healthy eating.', 'Сегодня вечером доктор Albers читает доклад о здоровом питании.', 'Сьогодні ввечері докторка Albers читає доповідь про здорове харчування.', 'Bu akşam Dr. Albers sağlıklı beslenme hakkında bir konuşma yapıyor.'],
          ['talk, lecture', 'доклад, лекция', 'доповідь, лекція', 'konuşma, sunum']),
        gap('W2', 'Ausstellung', I.word, 'Im Stadtmuseum gibt es eine neue ', ' mit alten Fotos.', 'Ausstellung', ['Anmeldung', 'Teilnahme'],
          ['At the town museum there is a new exhibition of old photos.', 'В городском музее новая выставка старых фотографий.', 'У міському музеї нова виставка старих фотографій.', 'Şehir müzesinde eski fotoğraflardan oluşan yeni bir sergi var.'],
          ['exhibition', 'выставка', 'виставка', 'sergi']),
        gap('W2', 'Eintritt', I.word, 'Der ', ' kostet sechs Euro, für Kinder drei Euro.', 'Eintritt', ['Eingang', 'Einkauf'],
          ['Admission costs six euros, three euros for children.', 'Вход стоит шесть евро, для детей – три евро.', 'Вхід коштує шість євро, для дітей – три євро.', 'Giriş altı avro, çocuklar için üç avro.'],
          ['admission', 'входной билет, вход', 'вхідний квиток, вхід', 'giriş ücreti']),
        sb('W2', 'Teilnahme', I.order, 'Die Teilnahme / ist / für Kinder / kostenlos.',
          ['Taking part is free for children.', 'Для детей участие бесплатное.', 'Для дітей участь безкоштовна.', 'Katılım çocuklar için ücretsiz.'],
          { alt: ['Für Kinder ist die Teilnahme kostenlos.'] }),
      ],
    },
    {
      title: 'Neu im Programm',
      t: ['New in the programme', 'Новое в программе', 'Нове в програмі', 'Programda yeni'],
      card: {
        id: 'p1_tipps',
        rule: 'Veranstaltungstipps verstehen: Such im Text die wichtigen Informationen. Was? (Kinderkino, Flohmarkt, Konzert) Wann? (jeden Sonntag, am Samstag, ab 19 Uhr) Wo? (im Kulturhaus, auf dem Marktplatz) Was kostet es? (Eintritt frei, 3 Euro) Für wen? (für Kinder ab sechs Jahren) Muss man sich anmelden? (Anmeldung bis Donnerstag) Achtung: bei Regen = wenn es regnet.',
        examples: ['Jeden Sonntag um 15 Uhr: Kinderkino.', 'Eintritt frei, Anmeldung nicht nötig.', 'Bei Regen findet das Fest in der Halle statt.'],
        highlight: null,
        t: [
          'Understanding event tips: look for the important information in the text. What? (Kinderkino, Flohmarkt, Konzert) When? (jeden Sonntag = every Sunday, am Samstag, ab 19 Uhr = from 7 pm) Where? (im Kulturhaus, auf dem Marktplatz) How much? (Eintritt frei, 3 Euro) Who for? (für Kinder ab sechs Jahren = for children aged six and over) Do you have to register? (Anmeldung bis Donnerstag = by Thursday) Note: bei Regen = if it rains.',
          'Как понимать афиши и анонсы: найдите в тексте важную информацию. Что? (Kinderkino, Flohmarkt, Konzert) Когда? (jeden Sonntag = каждое воскресенье, am Samstag, ab 19 Uhr = с 19 часов) Где? (im Kulturhaus, auf dem Marktplatz) Сколько стоит? (Eintritt frei, 3 Euro) Для кого? (für Kinder ab sechs Jahren = для детей от шести лет) Нужно ли записываться? (Anmeldung bis Donnerstag = до четверга) Внимание: bei Regen = если идёт дождь.',
          'Як розуміти афіші й анонси: знайдіть у тексті важливу інформацію. Що? (Kinderkino, Flohmarkt, Konzert) Коли? (jeden Sonntag = щонеділі, am Samstag, ab 19 Uhr = з 19 години) Де? (im Kulturhaus, auf dem Marktplatz) Скільки коштує? (Eintritt frei, 3 Euro) Для кого? (für Kinder ab sechs Jahren = для дітей від шести років) Чи треба записуватися? (Anmeldung bis Donnerstag = до четверга) Увага: bei Regen = якщо йде дощ.',
          'Etkinlik duyurularını anlamak: Metinde önemli bilgileri arayın. Ne? (Kinderkino, Flohmarkt, Konzert) Ne zaman? (jeden Sonntag = her pazar, am Samstag, ab 19 Uhr = saat 19’dan itibaren) Nerede? (im Kulturhaus, auf dem Marktplatz) Ne kadar? (Eintritt frei, 3 Euro) Kimler için? (für Kinder ab sechs Jahren = altı yaş ve üstü çocuklar için) Kayıt gerekli mi? (Anmeldung bis Donnerstag = perşembeye kadar) Dikkat: bei Regen = yağmur yağarsa.',
        ],
        hint: ['Such die Antwort im Text: Wann? Wo? Was kostet es? Für wen?', 'Look for the answer in the text: when? where? how much? who is it for?', 'Найдите ответ в тексте: когда? где? сколько стоит? для кого?', 'Знайдіть відповідь у тексті: коли? де? скільки коштує? для кого?', 'Cevabı metinde arayın: Ne zaman? Nerede? Ne kadar? Kimler için?'],
      },
      ex: [
        mc('Z1', 'Wann?', I.read, `${KINO} Wann ist das Kinderkino?`, ['Jeden Sonntag am Nachmittag.', 'Jeden Samstag am Abend.', 'Nur an einem Sonntag im Jahr.'],
          ['When is the children’s cinema?', 'Когда проходит детский киносеанс?', 'Коли відбувається дитячий кіносеанс?', 'Çocuk sineması ne zaman?']),
        mc('Z1', 'Wer zahlt nichts?', I.read, `${KINO} Wer muss keinen Eintritt bezahlen?`, ['Die Eltern.', 'Die Kinder.', 'Niemand.'],
          ['Who does not have to pay for admission?', 'Кто не должен платить за вход?', 'Хто не мусить платити за вхід?', 'Kim giriş ücreti ödemek zorunda değil?']),
        mc('Z1', 'Was gibt es?', I.read, `${KINO} Was gibt es nach dem Film?`, ['Etwas zu essen und zu trinken.', 'Einen zweiten Film.', 'Ein Geschenk für die Eltern.'],
          ['What is there after the film?', 'Что будет после фильма?', 'Що буде після фільму?', 'Filmden sonra ne var?']),
        mc('Z1', 'Wo?', I.read, `${FLOHMARKT} Wo ist der Flohmarkt bei schönem Wetter?`, ['Auf dem Marktplatz.', 'In der Sporthalle.', 'Im Rathaus.'],
          ['Where is the flea market in good weather?', 'Где проходит блошиный рынок в хорошую погоду?', 'Де відбувається блошиний ринок у гарну погоду?', 'Güzel havada bit pazarı nerede?']),
        mc('Z1', 'Anmeldung', I.read, `${FLOHMARKT} Was muss man tun, wenn man etwas verkaufen möchte?`, ['Man muss sich bis Donnerstag anmelden.', 'Man muss um 16 Uhr kommen.', 'Man muss Eintritt bezahlen.'],
          ['What do you have to do if you want to sell something?', 'Что нужно сделать, если хочешь что-то продать?', 'Що треба зробити, якщо хочеш щось продати?', 'Bir şey satmak isteyen ne yapmalı?']),
        mc('Z1', 'bei Regen', I.read, `${FLOHMARKT} Was passiert bei Regen?`, ['Der Flohmarkt ist in der Sporthalle.', 'Der Flohmarkt fällt aus.', 'Der Flohmarkt ist am Sonntag.'],
          ['What happens if it rains?', 'Что будет, если пойдёт дождь?', 'Що буде, якщо піде дощ?', 'Yağmur yağarsa ne olur?']),
        gap('Z1', 'bei Regen', I.word, 'Bei ', ' findet das Sommerfest im Saal statt, nicht im Garten.', 'Regen', ['Sonne', 'Eintritt'],
          ['If it rains, the summer party takes place in the hall, not in the garden.', 'В случае дождя летний праздник пройдёт в зале, а не в саду.', 'У разі дощу літнє свято відбудеться в залі, а не в саду.', 'Yağmur yağarsa yaz şenliği bahçede değil, salonda yapılacak.'],
          ['rain', 'дождь', 'дощ', 'yağmur']),
      ],
    },
  ],
}

export default path
