import { I, gap, mc, sb } from '../shared.mjs'

const SOFA = 'Anzeige: „Verschenke braunes Sofa, fünf Jahre alt, sehr bequem. Es hat einen kleinen Fleck. Abholung am Wochenende in Bonn. Bitte anrufen: 0151 5550199.“'
const NACHHILFE = 'Anzeige: „Biete Nachhilfe in Mathematik für Schüler bis zur 10. Klasse. Ich bin Studentin und habe viel Erfahrung. 12 Euro pro Stunde, die erste Stunde ist kostenlos.“'

/** A2.2 · Pfad 2 · Warenwelt – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Leder', I.choose, 'Woraus ist eine Geldbörse oft?', ['aus Leder', 'aus Glas', 'aus Holz'],
      ['What is a purse often made of?', 'Из чего часто делают кошельки?', 'З чого часто роблять гаманці?', 'Cüzdan çoğu zaman neden yapılır?']),
    mc('G3', 'einer -en', I.choose, 'Die Blumen stehen in einer … Vase.', ['blauen', 'blaue', 'blauer'],
      ['The flowers are in a blue vase.', 'Цветы стоят в синей вазе.', 'Квіти стоять у синій вазі.', 'Çiçekler mavi bir vazoda duruyor.']),
    mc('G5', 'als', I.choose, 'Leder ist teurer … Plastik.', ['als', 'wie', 'so'],
      ['Leather is more expensive than plastic.', 'Кожа дороже, чем пластик.', 'Шкіра дорожча, ніж пластик.', 'Deri plastikten daha pahalı.']),
    mc('G6', 'kostenlos', I.choose, 'Was bedeutet „kostenlos“?', ['Es kostet nichts.', 'Es kostet viel.', 'Es kostet wenig.'],
      ['What does “kostenlos” mean?', 'Что значит «kostenlos»?', 'Що означає «kostenlos»?', '“kostenlos” ne demek?']),
    mc('K1', 'Tja, ich weiß nicht.', I.react, '„Dieser Hut steht mir super, oder?“ – Du bist nicht überzeugt.', ['Tja, ich weiß nicht.', 'Ja, super!', 'Er ist kostenlos.'],
      ['“This hat really suits me, doesn’t it?” – You are not convinced.', '«Эта шляпа мне очень идёт, правда?» – Вы в этом не уверены.', '«Цей капелюх мені дуже личить, правда?» – Ви в цьому не впевнені.', '“Bu şapka bana çok yakışıyor, değil mi?” – İkna olmadınız.']),
    mc('K2', 'sparen', I.choose, 'Wofür gibst du nicht viel Geld aus? – Für Möbel. Da … ich.', ['spare', 'kaufe', 'zahle'],
      ['What do you not spend much money on? – On furniture. I save there.', 'На что ты тратишь не много денег? – На мебель. На этом я экономлю.', 'На що ти витрачаєш не багато грошей? – На меблі. На цьому я заощаджую.', 'Neye çok para harcamıyorsun? – Mobilyaya. Orada tasarruf ediyorum.']),
    mc('K4', 'Dieses', I.choose, '… Bild hat mir mein Vater geschenkt.', ['Dieses', 'Diesen', 'Dieser'],
      ['My father gave me this picture.', 'Эту картину мне подарил отец.', 'Цю картину мені подарував батько.', 'Bu resmi bana babam hediye etti.']),
    mc('Z1', 'Verschenke', I.read, `${SOFA} Was kostet das Sofa?`, ['Nichts.', 'Fünf Euro.', 'Das muss man am Telefon fragen.'],
      ['How much is the sofa?', 'Сколько стоит диван?', 'Скільки коштує диван?', 'Kanepe ne kadar?']),
    gap('G1', 'ein -er (der)', I.ending, 'Das ist ein ', ' Schirm. Er hat viele Farben.', 'bunter', ['buntes', 'bunte'],
      ['That is a colourful umbrella. It has lots of colours.', 'Это разноцветный зонт. На нём много цветов.', 'Це різнокольорова парасолька. На ній багато кольорів.', 'Bu rengârenk bir şemsiye. Üzerinde birçok renk var.'], 'bunt'),
    gap('G2', 'einen -en', I.ending, 'Ich brauche einen ', ' Topf für die Suppe.', 'großen', ['großer', 'großes'],
      ['I need a big pot for the soup.', 'Мне нужна большая кастрюля для супа.', 'Мені потрібна велика каструля для супу.', 'Çorba için büyük bir tencereye ihtiyacım var.'], 'groß'),
    gap('G4', 'am besten', I.comparison, 'Das Buch ist gut, der Film ist besser, aber das Theaterstück ist am ', '.', 'besten', ['guten', 'bessern'],
      ['The book is good, the film is better, but the play is the best.', 'Книга хорошая, фильм лучше, но спектакль лучше всех.', 'Книжка добра, фільм кращий, але вистава найкраща.', 'Kitap iyi, film daha iyi ama tiyatro oyunu en iyisi.'], 'gut'),
    gap('K3', 'Mir sind … wichtig', I.verb, 'Mir ', ' meine Freunde sehr wichtig.', 'sind', ['ist', 'seid'],
      ['My friends are very important to me.', 'Мои друзья для меня очень важны.', 'Мої друзі для мене дуже важливі.', 'Arkadaşlarım benim için çok önemli.'], 'sein'),
    sb('G3', 'einer -en', I.order, 'Sie / wohnt / in einer / schönen / Wohnung.',
      ['She lives in a lovely flat.', 'Она живёт в красивой квартире.', 'Вона живе в гарній квартирі.', 'Güzel bir dairede oturuyor.'],
      { alt: ['In einer schönen Wohnung wohnt sie.'] }),
  ],
  size: 13,
  test: [
    mc('W1', 'Taschenmesser', I.choose, 'Du bist im Wald und möchtest ein Brot schneiden. Was hast du in der Hosentasche?', ['ein Taschenmesser', 'eine Kerze', 'einen Schlüsselanhänger'],
      ['You are in the forest and want to cut some bread. What do you have in your trouser pocket?', 'Вы в лесу и хотите нарезать хлеб. Что у вас в кармане брюк?', 'Ви в лісі й хочете нарізати хліб. Що у вас у кишені штанів?', 'Ormandasınız ve ekmek kesmek istiyorsunuz. Pantolon cebinizde ne var?']),
    mc('G1', 'eine -e (die)', I.choose, 'Das ist eine … Idee!', ['gute', 'guter', 'gutes'],
      ['That is a good idea!', 'Это хорошая идея!', 'Це добра ідея!', 'Bu iyi bir fikir!']),
    mc('G1', 'kein -er (der)', I.choose, 'Das ist kein … Preis. Das ist viel zu teuer.', ['guter', 'gutes', 'gute'],
      ['That is not a good price. That is far too expensive.', 'Это не хорошая цена. Это слишком дорого.', 'Це не добра ціна. Це занадто дорого.', 'Bu iyi bir fiyat değil. Çok fazla pahalı.']),
    mc('G2', 'einen -en', I.choose, 'Samir trägt einen … Mantel.', ['langen', 'langer', 'langes'],
      ['Samir is wearing a long coat.', 'На Samir длинное пальто.', 'На Samir довге пальто.', 'Samir uzun bir palto giyiyor.']),
    mc('G2', 'keine -en (Plural)', I.choose, 'Ich habe keine … Schuhe für den Winter.', ['warmen', 'warme', 'warmer'],
      ['I have no warm shoes for the winter.', 'У меня нет тёплой обуви на зиму.', 'У мене немає теплого взуття на зиму.', 'Kış için sıcak tutan ayakkabım yok.']),
    mc('G3', 'meiner -en', I.choose, 'Das Geschenk ist von meiner … Kollegin.', ['netten', 'nette', 'netter'],
      ['The present is from my nice colleague.', 'Подарок от моей приятной коллеги.', 'Подарунок від моєї приємної колеги.', 'Hediye cana yakın iş arkadaşımdan.']),
    mc('G4', 'am besten', I.choose, 'Welche Form ist richtig? gut – besser – …', ['am besten', 'am gutesten', 'am bessten'],
      ['Which form is correct? gut – besser – …', 'Какая форма правильная? gut – besser – …', 'Яка форма правильна? gut – besser – …', 'Hangi biçim doğru? gut – besser – …']),
    mc('G5', 'nicht so … wie', I.choose, 'Der Bus ist nicht so schnell … die U-Bahn.', ['wie', 'als', 'dass'],
      ['The bus is not as fast as the underground.', 'Автобус не такой быстрый, как метро.', 'Автобус не такий швидкий, як метро.', 'Otobüs metro kadar hızlı değil.']),
    mc('G5', 'billiger als', I.sentence, 'Ein Kaffee kostet 3 Euro, ein Tee kostet 2 Euro.', ['Der Tee ist billiger als der Kaffee.', 'Der Tee ist billiger wie der Kaffee.', 'Der Tee ist so billig wie der Kaffee.'],
      ['A coffee costs 3 euros, a tea costs 2 euros.', 'Кофе стоит 3 евро, чай – 2 евро.', 'Кава коштує 3 євро, чай – 2 євро.', 'Bir kahve 3 avro, bir çay 2 avro.']),
    mc('G6', 'arbeitslos', I.choose, 'Mein Nachbar sucht seit Monaten eine Stelle. Er ist …', ['arbeitslos', 'fehlerlos', 'kostenlos'],
      ['My neighbour has been looking for a job for months. He is …', 'Мой сосед уже несколько месяцев ищет работу. Он …', 'Мій сусід уже кілька місяців шукає роботу. Він …', 'Komşum aylardır iş arıyor. O …']),
    mc('K1', 'Na ja, geht so.', I.react, '„Das Sofa ist doch sehr bequem!“ – Du hast eine andere Meinung, sagst es aber vorsichtig.', ['Na ja, geht so.', 'Ja, total bequem!', 'Stimmt genau.'],
      ['“The sofa is very comfortable!” – You have a different opinion but say so carefully.', '«Диван ведь очень удобный!» – У вас другое мнение, но вы говорите об этом осторожно.', '«Диван же дуже зручний!» – У вас інша думка, але ви кажете про це обережно.', '“Kanepe çok rahat ama!” – Siz farklı düşünüyorsunuz ama bunu dikkatli söylüyorsunuz.']),
    mc('K2', 'am meisten', I.choose, 'Lena kauft sehr oft Bücher. Sie sagt: „Am … gebe ich für Bücher aus.“', ['meisten', 'liebsten', 'besten'],
      ['Lena buys books very often. She says: “I spend most on books.”', 'Lena очень часто покупает книги. Она говорит: «Больше всего я трачу на книги».', 'Lena дуже часто купує книжки. Вона каже: «Найбільше я витрачаю на книжки».', 'Lena çok sık kitap alıyor. Diyor ki: “En çok kitaplara para harcıyorum.”']),
    mc('K3', 'auch wichtig, aber …', I.react, '„Mir ist ein gutes Gehalt wichtig. Und dir?“', ['Das ist mir auch wichtig, aber nicht sehr wichtig.', 'Ich verdiene 2000 Euro.', 'Ich gebe viel Geld aus.'],
      ['“A good salary is important to me. And to you?”', '«Для меня важна хорошая зарплата. А для тебя?»', '«Для мене важлива добра зарплата. А для тебе?»', '“Benim için iyi bir maaş önemli. Ya senin için?”']),
    mc('K4', 'von + Dativ', I.choose, 'Diese Schüssel habe ich … meiner Nachbarin bekommen.', ['von', 'aus', 'bei'],
      ['I got this bowl from my neighbour.', 'Эту миску я получил от соседки.', 'Цю миску я отримав від сусідки.', 'Bu kâseyi komşumdan aldım.']),
    mc('Z1', 'Problem', I.read, `${SOFA} Was ist das Problem mit dem Sofa?`, ['Es hat einen Fleck.', 'Es ist nicht bequem.', 'Es ist zu teuer.'],
      ['What is the problem with the sofa?', 'Какой у дивана недостаток?', 'Який у дивана недолік?', 'Kanepenin sorunu ne?']),
    mc('Z1', 'Wann?', I.read, `${SOFA} Wann kann man das Sofa abholen?`, ['Am Samstag oder Sonntag.', 'Nur am Montag.', 'Jeden Tag ab 18 Uhr.'],
      ['When can you collect the sofa?', 'Когда можно забрать диван?', 'Коли можна забрати диван?', 'Kanepe ne zaman alınabilir?']),
    mc('Z1', 'kostenlos', I.read, `${NACHHILFE} Was kostet die erste Stunde?`, ['Nichts.', '12 Euro.', '10 Euro.'],
      ['How much is the first lesson?', 'Сколько стоит первое занятие?', 'Скільки коштує перше заняття?', 'İlk ders ne kadar?']),
    gap('W1', 'Kerze', I.word, 'Der Abend ist dunkel. Wir machen eine ', ' an.', 'Kerze', ['Kette', 'Schüssel'],
      ['The evening is dark. We are lighting a candle.', 'Вечер тёмный. Мы зажигаем свечу.', 'Вечір темний. Ми запалюємо свічку.', 'Akşam karanlık. Bir mum yakıyoruz.'],
      ['candle', 'свеча', 'свічка', 'mum']),
    gap('G1', 'ein -es (das)', I.ending, 'Hier ist ein ', ' Café. Es hat erst seit gestern geöffnet.', 'neues', ['neuer', 'neue'],
      ['There is a new café here. It has only been open since yesterday.', 'Здесь новое кафе. Оно открыто только со вчерашнего дня.', 'Тут нове кафе. Воно відчинене лише від учора.', 'Burada yeni bir kafe var. Daha dün açıldı.'], 'neu'),
    gap('G2', 'ein -es', I.ending, 'Wir suchen ein ', ' Sofa für das Wohnzimmer.', 'bequemes', ['bequemen', 'bequemer'],
      ['We are looking for a comfortable sofa for the living room.', 'Мы ищем удобный диван для гостиной.', 'Ми шукаємо зручний диван для вітальні.', 'Oturma odası için rahat bir kanepe arıyoruz.'], 'bequem'),
    gap('G3', 'einem -en', I.ending, 'Die Kinder spielen mit einem ', ' Ball.', 'bunten', ['bunter', 'buntes'],
      ['The children are playing with a colourful ball.', 'Дети играют разноцветным мячом.', 'Діти граються різнокольоровим м’ячем.', 'Çocuklar renkli bir topla oynuyor.'], 'bunt'),
    gap('G3', 'einem -en', I.ending, 'Er wohnt in einem ', ' Haus am Stadtrand.', 'alten', ['altes', 'alter'],
      ['He lives in an old house on the edge of town.', 'Он живёт в старом доме на окраине города.', 'Він живе в старому будинку на околиці міста.', 'Şehrin kenarında eski bir evde oturuyor.'], 'alt'),
    gap('G4', 'länger', I.comparison, 'Im Sommer sind die Tage ', ' als im Winter.', 'länger', ['langer', 'längsten'],
      ['In summer the days are longer than in winter.', 'Летом дни длиннее, чем зимой.', 'Улітку дні довші, ніж узимку.', 'Yazın günler kışa göre daha uzun.'], 'lang'),
    gap('G4', 'am höchsten', I.comparison, 'Der Berg ist 2000 Meter hoch. Von allen Bergen hier ist er am ', '.', 'höchsten', ['höher', 'hochsten'],
      ['The mountain is 2,000 metres high. Of all the mountains here it is the highest.', 'Высота горы – 2000 метров. Из всех здешних гор она самая высокая.', 'Висота гори – 2000 метрів. З усіх тутешніх гір вона найвища.', 'Dağ 2000 metre yüksekliğinde. Buradaki bütün dağların en yükseği o.'], 'hoch'),
    gap('G5', 'genauso … wie', I.word, 'Meine Schwester kocht genauso gut ', ' meine Mutter.', 'wie', ['als', 'so'],
      ['My sister cooks just as well as my mother.', 'Моя сестра готовит так же хорошо, как мама.', 'Моя сестра готує так само добре, як мама.', 'Kız kardeşim annem kadar iyi yemek yapıyor.'], 'als / wie'),
    gap('G6', 'fehlerlos', I.form, 'Ihre Hausaufgabe hat null Fehler. Sie ist ', '.', 'fehlerlos', ['fehlen', 'fehlerhaft'],
      ['Her homework has zero mistakes. It is flawless.', 'В её домашнем задании ноль ошибок. Оно безошибочное.', 'У її домашньому завданні нуль помилок. Воно безпомилкове.', 'Ödevinde sıfır hata var. Hatasız.'], 'der Fehler'),
    gap('K1', 'Ja, wirklich?', I.word, 'Das ist das beste Angebot in der Stadt. – Ja, ', '? Das glaube ich nicht.', 'wirklich', ['natürlich', 'genau'],
      ['That is the best offer in town. – Really? I do not believe that.', 'Это лучшее предложение в городе. – Правда? Я в это не верю.', 'Це найкраща пропозиція в місті. – Справді? Я в це не вірю.', 'Bu şehirdeki en iyi teklif. – Gerçekten mi? Buna inanmıyorum.'],
      ['really', 'правда, действительно', 'справді', 'gerçekten']),
    gap('K2', 'ausgeben für', I.prep, 'Wir geben viel Geld ', ' Lebensmittel aus.', 'für', ['mit', 'an'],
      ['We spend a lot of money on food.', 'Мы тратим много денег на продукты.', 'Ми витрачаємо багато грошей на продукти.', 'Gıdaya çok para harcıyoruz.'], 'für / mit / an'),
    gap('K3', 'Wie wichtig …?', I.word, 'Wie ', ' ist Ihnen ein großer Garten, Frau Albers?', 'wichtig', ['wichtiger', 'wichtigsten'],
      ['How important is a big garden to you, Ms Albers?', 'Насколько для вас важен большой сад, госпожа Albers?', 'Наскільки для вас важливий великий сад, пані Albers?', 'Büyük bir bahçe sizin için ne kadar önemli, Albers Hanım?'],
      ['important', 'важен', 'важливий', 'önemli']),
    gap('K4', 'geschenkt', I.participle, 'Dieses Feuerzeug hat mir mein Onkel ', '.', 'geschenkt', ['geschenken', 'schenkt'],
      ['My uncle gave me this lighter.', 'Эту зажигалку мне подарил дядя.', 'Цю запальничку мені подарував дядько.', 'Bu çakmağı bana amcam hediye etti.'], 'schenken'),
  ],
}

export default check
