import { I, gap, mc, sb } from '../shared.mjs'

const SCHUESSEL = 'Anzeige: „Verkaufe eine neue Salatschüssel aus Glas, 15 Euro. Dazu gibt es zwei kleine Schüsseln kostenlos. Nur Abholung in Köln. Tel. 0170 5550142, ab 18 Uhr.“'
const KINDERWAGEN = 'Anzeige: „Suche einen gebrauchten Kinderwagen in gutem Zustand, nicht älter als drei Jahre. Zahle bis 80 Euro. Bitte nur Angebote mit Foto per E-Mail.“'

/** A2.2 · Pfad 2 · Warenwelt – Lektionen. Wiederholung und Test: p2-check.mjs */
const path = {
  n: 2,
  slug: 'warenwelt',
  title: 'Warenwelt',
  t: ['The world of goods', 'Мир вещей и покупок', 'Світ речей і покупок', 'Eşyalar ve alışveriş dünyası'],
  objectives: {
    G1: 'Adjektive nach ein, kein, mein im Nominativ: ein neuer Laden, ein schönes Licht, eine schöne Wohnung, braune Möbel – aber: meine braunen Möbel.',
    G2: 'Adjektive nach ein, kein, mein im Akkusativ: einen neuen Laden, ein schönes Licht, eine schöne Wohnung.',
    G3: 'Adjektive nach ein, kein, mein im Dativ: einem neuen Laden, einer schönen Wohnung, braunen Möbeln – immer -en.',
    G4: 'Komparativ und Superlativ: schön – schöner – am schönsten; groß – größer – am größten; hoch – höher – am höchsten.',
    G5: 'Vergleichen mit als und wie: schöner als … – genauso schön wie …',
    G6: 'Wortbildung: Nomen + -los = Adjektiv: die Arbeit → arbeitslos (ohne Arbeit).',
    K1: 'Skeptisch reagieren: Tja, ich weiß nicht. Hm, findest du? Na ja, geht so. Bist du sicher?',
    K2: 'Vorlieben und Konsumverhalten ausdrücken: Am meisten gebe ich für … aus. Ich kaufe am liebsten … Da spare ich.',
    K3: 'Wichtigkeit ausdrücken: Mir ist … wichtig. Wie wichtig ist dir …? Das ist mir überhaupt nicht wichtig.',
    K4: "Von einem Gegenstand erzählen: Diese Kette habe ich von meinem Opa bekommen. Sie ist mir besonders wichtig, weil …",
    Z1: 'Kann-Ziele: Kleinanzeigen verstehen.',
    W1: 'Wortschatz: Gegenstände und Materialien.',
  },
  nodes: [
    {
      title: 'Gegenstände und Materialien',
      t: ['Objects and materials', 'Предметы и материалы', 'Предмети й матеріали', 'Eşyalar ve malzemeler'],
      card: {
        id: 'p2_sachen',
        rule: 'Gegenstände: die Geldbörse (für Geld), die Brieftasche (für Geld und Papiere), der Schirm, der Rucksack, die Kette, der Ring, die Kerze, das Feuerzeug, der Topf, die Schüssel, das Taschenmesser, der Schlüsselanhänger. Materialien: das Holz, das Metall, das Glas, das Plastik, das Leder, der Stoff, das Papier, das Silber, das Gold. Man sagt aus + Material ohne Artikel: ein Tisch aus Holz, eine Tasche aus Leder.',
        examples: ['Die Schüssel ist aus Glas.', 'Ich suche eine Geldbörse aus Leder.', 'Der Topf ist aus Metall.'],
        highlight: 'article',
        t: [
          'Objects: die Geldbörse (purse, for money), die Brieftasche (wallet, for money and papers), der Schirm (umbrella), der Rucksack (rucksack), die Kette (necklace), der Ring, die Kerze (candle), das Feuerzeug (lighter), der Topf (pot), die Schüssel (bowl), das Taschenmesser (penknife), der Schlüsselanhänger (key ring). Materials: das Holz (wood), das Metall (metal), das Glas (glass), das Plastik (plastic), das Leder (leather), der Stoff (fabric), das Papier (paper), das Silber (silver), das Gold. You say aus + material without an article: ein Tisch aus Holz, eine Tasche aus Leder.',
          'Предметы: die Geldbörse (кошелёк для денег), die Brieftasche (бумажник для денег и документов), der Schirm (зонт), der Rucksack (рюкзак), die Kette (цепочка), der Ring (кольцо), die Kerze (свеча), das Feuerzeug (зажигалка), der Topf (кастрюля), die Schüssel (миска), das Taschenmesser (перочинный нож), der Schlüsselanhänger (брелок). Материалы: das Holz (дерево), das Metall (металл), das Glas (стекло), das Plastik (пластик), das Leder (кожа), der Stoff (ткань), das Papier (бумага), das Silber (серебро), das Gold (золото). Говорят aus + материал без артикля: ein Tisch aus Holz, eine Tasche aus Leder.',
          'Предмети: die Geldbörse (гаманець для грошей), die Brieftasche (портмоне для грошей і документів), der Schirm (парасолька), der Rucksack (рюкзак), die Kette (ланцюжок), der Ring (перстень), die Kerze (свічка), das Feuerzeug (запальничка), der Topf (каструля), die Schüssel (миска), das Taschenmesser (складаний ніж), der Schlüsselanhänger (брелок). Матеріали: das Holz (дерево), das Metall (метал), das Glas (скло), das Plastik (пластик), das Leder (шкіра), der Stoff (тканина), das Papier (папір), das Silber (срібло), das Gold (золото). Кажуть aus + матеріал без артикля: ein Tisch aus Holz, eine Tasche aus Leder.',
          'Eşyalar: die Geldbörse (para cüzdanı), die Brieftasche (para ve belgeler için cüzdan), der Schirm (şemsiye), der Rucksack (sırt çantası), die Kette (kolye), der Ring (yüzük), die Kerze (mum), das Feuerzeug (çakmak), der Topf (tencere), die Schüssel (kâse), das Taschenmesser (çakı), der Schlüsselanhänger (anahtarlık). Malzemeler: das Holz (ahşap), das Metall (metal), das Glas (cam), das Plastik (plastik), das Leder (deri), der Stoff (kumaş), das Papier (kâğıt), das Silber (gümüş), das Gold (altın). aus + malzeme artikelsiz söylenir: ein Tisch aus Holz, eine Tasche aus Leder.',
        ],
        hint: ['aus + Material: aus Holz, aus Glas, aus Leder, aus Metall, aus Plastik, aus Stoff.', 'aus + material: aus Holz (wood), aus Glas (glass), aus Leder (leather), aus Metall (metal), aus Plastik (plastic), aus Stoff (fabric).', 'aus + материал: aus Holz (дерево), aus Glas (стекло), aus Leder (кожа), aus Metall (металл), aus Plastik (пластик), aus Stoff (ткань).', 'aus + матеріал: aus Holz (дерево), aus Glas (скло), aus Leder (шкіра), aus Metall (метал), aus Plastik (пластик), aus Stoff (тканина).', 'aus + malzeme: aus Holz (ahşap), aus Glas (cam), aus Leder (deri), aus Metall (metal), aus Plastik (plastik), aus Stoff (kumaş).'],
      },
      ex: [
        mc('W1', 'Geldbörse', I.choose, 'Wo ist dein Geld, wenn du einkaufen gehst?', ['in der Geldbörse', 'in der Schüssel', 'in der Kerze'],
          ['Where is your money when you go shopping?', 'Где лежат ваши деньги, когда вы идёте за покупками?', 'Де лежать ваші гроші, коли ви йдете по покупки?', 'Alışverişe giderken paranız nerededir?']),
        mc('W1', 'Schirm', I.choose, 'Es regnet. Was brauchst du?', ['einen Schirm', 'ein Feuerzeug', 'einen Topf'],
          ['It is raining. What do you need?', 'Идёт дождь. Что вам нужно?', 'Іде дощ. Що вам потрібно?', 'Yağmur yağıyor. Neye ihtiyacınız var?']),
        mc('W1', 'Glas', I.choose, 'Woraus ist ein Fenster?', ['aus Glas', 'aus Stoff', 'aus Leder'],
          ['What is a window made of?', 'Из чего сделано окно?', 'З чого зроблене вікно?', 'Pencere neden yapılır?']),
        mc('W1', 'Materialien', I.odd, 'Drei Wörter sind Materialien, ein Wort nicht.', ['Kerze', 'Holz', 'Leder', 'Metall'], null),
        mc('W1', 'Feuerzeug', I.choose, 'Womit macht man eine Kerze an?', ['mit einem Feuerzeug', 'mit einem Schirm', 'mit einer Schüssel'],
          ['What do you light a candle with?', 'Чем зажигают свечу?', 'Чим запалюють свічку?', 'Mum neyle yakılır?']),
        gap('W1', 'Topf', I.word, 'Ich koche die Suppe in einem großen ', '.', 'Topf', ['Schirm', 'Ring'],
          ['I am cooking the soup in a big pot.', 'Я варю суп в большой кастрюле.', 'Я варю суп у великій каструлі.', 'Çorbayı büyük bir tencerede pişiriyorum.'],
          ['pot, saucepan', 'кастрюля', 'каструля', 'tencere']),
        gap('W1', 'Holz', I.word, 'Der Stuhl ist nicht aus Plastik. Er ist aus ', ', von einem Baum.', 'Holz', ['Glas', 'Stoff'],
          ['The chair is not made of plastic. It is made of wood, from a tree.', 'Стул не из пластика. Он из дерева.', 'Стілець не з пластику. Він із дерева.', 'Sandalye plastikten değil. Ahşaptan, bir ağaçtan yapılmış.'],
          ['wood', 'дерево (материал)', 'дерево (матеріал)', 'ahşap']),
        gap('W1', 'aus + Material', I.prep, 'Meine neue Tasche ist ', ' Leder.', 'aus', ['von', 'mit'],
          ['My new bag is made of leather.', 'Моя новая сумка из кожи.', 'Моя нова сумка зі шкіри.', 'Yeni çantam deriden.'], 'aus / von / mit'),
        gap('W1', 'Schüssel', I.word, 'Salat macht man in einer großen ', '.', 'Schüssel', ['Kerze', 'Kette'],
          ['You make salad in a big bowl.', 'Салат готовят в большой миске.', 'Салат готують у великій мисці.', 'Salata büyük bir kâsede yapılır.'],
          ['bowl', 'миска', 'миска', 'kâse']),
        sb('W1', 'aus Silber', I.order, 'Die Kette / ist / aus / Silber.',
          ['The necklace is made of silver.', 'Цепочка из серебра.', 'Ланцюжок зі срібла.', 'Kolye gümüşten.']),
      ],
    },
    {
      title: 'ein neuer Laden',
      t: ['ein neuer Laden (adjective endings: nominative)', 'ein neuer Laden (окончания прилагательных: Nominativ)', 'ein neuer Laden (закінчення прикметників: Nominativ)', 'ein neuer Laden (sıfat ekleri: Nominativ)'],
      card: {
        id: 'p2_nominativ',
        rule: 'Adjektive vor dem Nomen bekommen eine Endung. Nach ein, kein, mein im Nominativ zeigt das Adjektiv das Genus: der → ein neuer Laden (-er), das → ein schönes Licht (-es), die → eine schöne Wohnung (-e). Plural ohne Artikel: braune Möbel (-e). Aber nach meine, keine im Plural: meine braunen Möbel, keine neuen Schuhe (-en).',
        examples: ['Das ist ein alter Stift.', 'Das ist ein kleines Messer.', 'Das ist eine große Geldbörse.', 'Das sind meine neuen Schuhe.'],
        highlight: null,
        t: [
          'Adjectives in front of a noun get an ending. After ein, kein, mein in the nominative the adjective shows the gender: der → ein neuer Laden (-er), das → ein schönes Licht (-es), die → eine schöne Wohnung (-e). Plural without an article: braune Möbel (-e). But after meine, keine in the plural: meine braunen Möbel, keine neuen Schuhe (-en).',
          'Прилагательные перед существительным получают окончание. После ein, kein, mein в Nominativ прилагательное показывает род: der → ein neuer Laden (-er), das → ein schönes Licht (-es), die → eine schöne Wohnung (-e). Множественное число без артикля: braune Möbel (-e). Но после meine, keine во множественном числе: meine braunen Möbel, keine neuen Schuhe (-en).',
          'Прикметники перед іменником отримують закінчення. Після ein, kein, mein у Nominativ прикметник показує рід: der → ein neuer Laden (-er), das → ein schönes Licht (-es), die → eine schöne Wohnung (-e). Множина без артикля: braune Möbel (-e). Але після meine, keine у множині: meine braunen Möbel, keine neuen Schuhe (-en).',
          'İsimden önce gelen sıfatlar ek alır. Nominativ’de ein, kein, mein sözcüklerinden sonra sıfat cinsiyeti gösterir: der → ein neuer Laden (-er), das → ein schönes Licht (-es), die → eine schöne Wohnung (-e). Artikelsiz çoğul: braune Möbel (-e). Ama çoğulda meine, keine sözcüklerinden sonra: meine braunen Möbel, keine neuen Schuhe (-en).',
        ],
        hint: ['der → -er, das → -es, die → -e: ein großer Topf, ein großes Bild, eine große Kerze. Plural mit meine/keine: -en.', 'der → -er, das → -es, die → -e: ein großer Topf, ein großes Bild, eine große Kerze. Plural with meine/keine: -en.', 'der → -er, das → -es, die → -e: ein großer Topf, ein großes Bild, eine große Kerze. Множественное число с meine/keine: -en.', 'der → -er, das → -es, die → -e: ein großer Topf, ein großes Bild, eine große Kerze. Множина з meine/keine: -en.', 'der → -er, das → -es, die → -e: ein großer Topf, ein großes Bild, eine große Kerze. meine/keine ile çoğul: -en.'],
      },
      ex: [
        mc('G1', 'ein -er (der)', I.choose, 'Das ist ein … Laden.', ['neuer', 'neues', 'neue'],
          ['That is a new shop.', 'Это новый магазин.', 'Це новий магазин.', 'Bu yeni bir dükkân.']),
        mc('G1', 'ein -es (das)', I.choose, 'Das ist ein … Bild.', ['schönes', 'schöner', 'schöne'],
          ['That is a beautiful picture.', 'Это красивая картина.', 'Це гарна картина.', 'Bu güzel bir resim.']),
        mc('G1', 'eine -e (die)', I.choose, 'Das ist eine … Kette.', ['goldene', 'goldener', 'goldenes'],
          ['That is a gold necklace.', 'Это золотая цепочка.', 'Це золотий ланцюжок.', 'Bu altın bir kolye.']),
        mc('G1', 'meine -en (Plural)', I.choose, 'Das sind meine … Schuhe.', ['neuen', 'neue', 'neuer'],
          ['These are my new shoes.', 'Это мои новые туфли.', 'Це мої нові туфлі.', 'Bunlar benim yeni ayakkabılarım.']),
        mc('G1', 'ein -er (der)', I.sentence, 'Paul zeigt seinen Rucksack.', ['Das ist ein praktischer Rucksack.', 'Das ist ein praktisches Rucksack.', 'Das ist ein praktische Rucksack.'],
          ['Paul is showing his rucksack.', 'Paul показывает свой рюкзак.', 'Paul показує свій рюкзак.', 'Paul sırt çantasını gösteriyor.']),
        gap('G1', 'ein -er (der)', I.ending, 'Auf dem Tisch steht ein ', ' Topf.', 'großer', ['großes', 'große'],
          ['There is a big pot on the table.', 'На столе стоит большая кастрюля.', 'На столі стоїть велика каструля.', 'Masanın üstünde büyük bir tencere duruyor.'], 'groß'),
        gap('G1', 'ein -es (das)', I.ending, 'Das ist ein ', ' Feuerzeug.', 'kleines', ['kleiner', 'kleine'],
          ['That is a small lighter.', 'Это маленькая зажигалка.', 'Це маленька запальничка.', 'Bu küçük bir çakmak.'], 'klein'),
        gap('G1', 'eine -e (die)', I.ending, 'In meiner Tasche ist eine ', ' Geldbörse.', 'alte', ['alter', 'altes'],
          ['There is an old purse in my bag.', 'В моей сумке лежит старый кошелёк.', 'У моїй сумці лежить старий гаманець.', 'Çantamda eski bir cüzdan var.'], 'alt'),
        gap('G1', 'keine -en (Plural)', I.ending, 'Das sind keine ', ' Möbel. Sie sind schon alt.', 'neuen', ['neue', 'neues'],
          ['That is not new furniture. It is already old.', 'Это не новая мебель. Она уже старая.', 'Це не нові меблі. Вони вже старі.', 'Bunlar yeni mobilya değil. Artık eskimişler.'], 'neu'),
        sb('G1', 'ein -er (der)', I.order, 'Das / ist / ein / schöner / Ring.',
          ['That is a beautiful ring.', 'Это красивое кольцо.', 'Це гарний перстень.', 'Bu güzel bir yüzük.']),
      ],
    },
    {
      title: 'einen neuen Laden',
      t: ['einen neuen Laden (adjective endings: accusative)', 'einen neuen Laden (окончания прилагательных: Akkusativ)', 'einen neuen Laden (закінчення прикметників: Akkusativ)', 'einen neuen Laden (sıfat ekleri: Akkusativ)'],
      card: {
  "id": "p2_akkusativ",
  "rule": "Im Akkusativ ändert sich nur maskulin: einen neuen Laden (-en). Neutral, feminin und Plural bleiben wie im Nominativ: ein schönes Licht, eine schöne Wohnung, braune Möbel. Nach meine, keine im Plural: meine braunen Möbel. Der Akkusativ steht nach Verben wie haben, kaufen, suchen, brauchen, finden und nach für und ohne.",
  "examples": [
    "Ich suche einen warmen Pullover.",
    "Er kauft ein neues Handy.",
    "Wir haben eine kleine Küche."
  ],
  "highlight": null,
  "t": [
    "In the accusative only the masculine changes: einen neuen Laden (-en). Neuter, feminine and plural stay as in the nominative: ein schönes Licht, eine schöne Wohnung, braune Möbel. After meine, keine in the plural: meine braunen Möbel. The accusative follows verbs such as haben, kaufen, suchen, brauchen, finden and the prepositions für and ohne.",
    "В Akkusativ меняется только мужской род: einen neuen Laden (-en). Средний, женский род и множественное число остаются как в Nominativ: ein schönes Licht, eine schöne Wohnung, braune Möbel. После meine, keine во множественном числе: meine braunen Möbel. Akkusativ стоит после глаголов haben, kaufen, suchen, brauchen, finden и после für и ohne.",
    "В Akkusativ змінюється лише чоловічий рід: einen neuen Laden (-en). Середній, жіночий рід і множина залишаються як у Nominativ: ein schönes Licht, eine schöne Wohnung, braune Möbel. Після meine, keine у множині: meine braunen Möbel. Akkusativ стоїть після дієслів haben, kaufen, suchen, brauchen, finden і після für та ohne.",
    "Akkusativ’de yalnızca eril değişir: einen neuen Laden (-en). Nötr, dişil ve çoğul Nominativ’deki gibi kalır: ein schönes Licht, eine schöne Wohnung, braune Möbel. Çoğulda meine, keine sözcüklerinden sonra: meine braunen Möbel. Akkusativ haben, kaufen, suchen, brauchen, finden gibi fiillerden ve für ile ohne edatlarından sonra gelir."
  ],
  "hint": [
    "Akkusativ: der → einen …-en. das → ein …-es. die → eine …-e.",
    "Accusative: der → einen …-en. das → ein …-es. die → eine …-e.",
    "Akkusativ (кого? что?): der → einen …-en. das → ein …-es. die → eine …-e.",
    "Akkusativ (кого? що?): der → einen …-en. das → ein …-es. die → eine …-e.",
    "Akkusativ (kimi? neyi?): der → einen …-en. das → ein …-es. die → eine …-e."
  ]
},
      ex: [
        mc('G2', 'einen -en', I.choose, 'Ich suche einen … Rucksack.', ['großen', 'großer', 'großes'],
          ['I am looking for a big rucksack.', 'Я ищу большой рюкзак.', 'Я шукаю великий рюкзак.', 'Büyük bir sırt çantası arıyorum.']),
        mc("G2", "ein -es", I.choose, "Leon kauft ein ___ Kleid.", ["rotes","roten","roter"], ["Leon is buying a red dress.","Leon покупает красное платье.","Leon купує червону сукню.","Leon kırmızı bir elbise alıyor."], {"c":"p2_akkusativ"}),
        mc('G2', 'eine -e', I.choose, 'Wir brauchen eine … Schüssel.', ['neue', 'neuen', 'neues'],
          ['We need a new bowl.', 'Нам нужна новая миска.', 'Нам потрібна нова миска.', 'Yeni bir kâseye ihtiyacımız var.']),
        mc('G2', 'einen -en', I.choose, 'Emre hat … Schirm gekauft.', ['einen schwarzen', 'ein schwarzer', 'einen schwarzer'],
          ['Emre has bought a black umbrella.', 'Emre купил чёрный зонт.', 'Emre купив чорну парасольку.', 'Emre siyah bir şemsiye aldı.']),
        mc('G2', 'einen -en', I.sentence, 'Was hast du auf dem Flohmarkt gefunden?', ['Ich habe einen alten Topf gefunden.', 'Ich habe ein alter Topf gefunden.', 'Ich habe einen alter Topf gefunden.'],
          ['What did you find at the flea market?', 'Что ты нашёл на блошином рынке?', 'Що ти знайшов на блошиному ринку?', 'Bit pazarında ne buldun?']),
        gap('G2', 'einen -en', I.ending, 'Ich möchte einen ', ' Ring kaufen.', 'silbernen', ['silberner', 'silbernes'],
          ['I would like to buy a silver ring.', 'Я хочу купить серебряное кольцо.', 'Я хочу купити срібний перстень.', 'Gümüş bir yüzük almak istiyorum.'], 'silbern'),
        gap('G2', 'ein -es', I.ending, 'Hast du ein ', ' Taschenmesser?', 'scharfes', ['scharfen', 'scharfer'],
          ['Do you have a sharp penknife?', 'У тебя есть острый перочинный нож?', 'У тебе є гострий складаний ніж?', 'Keskin bir çakın var mı?'], 'scharf'),
        gap("G2", "eine -e", I.ending, "Milan trägt heute eine ", " Kette.", "lange", ["langen","langes"], ["Milan is wearing a long necklace today.","Сегодня на Milan длинная цепочка.","Сьогодні на Milan довгий ланцюжок.","Milan bugün uzun bir kolye takıyor."], "lang", {"c":"p2_akkusativ"}),
        gap('G2', 'für + Akkusativ', I.ending, 'Für meinen ', ' Bruder suche ich ein Geschenk.', 'kleinen', ['kleiner', 'kleine'],
          ['I am looking for a present for my little brother.', 'Я ищу подарок для младшего брата.', 'Я шукаю подарунок для молодшого брата.', 'Küçük erkek kardeşim için bir hediye arıyorum.'], 'klein'),
        sb('G2', 'einen -en', I.order, 'Ich / suche / einen / neuen / Schirm.',
          ['I am looking for a new umbrella.', 'Я ищу новый зонт.', 'Я шукаю нову парасольку.', 'Yeni bir şemsiye arıyorum.'],
          { alt: ['Einen neuen Schirm suche ich.'] }),
      ],
    },
    {
      title: 'in einem neuen Laden',
      t: ['in einem neuen Laden (adjective endings: dative)', 'in einem neuen Laden (окончания прилагательных: Dativ)', 'in einem neuen Laden (закінчення прикметників: Dativ)', 'in einem neuen Laden (sıfat ekleri: Dativ)'],
      card: {
        id: 'p2_dativ',
        rule: 'Im Dativ ist die Adjektivendung nach ein, kein, mein immer -en: in einem neuen Laden, mit einem schönen Licht, in einer schönen Wohnung, mit meinen alten Freunden. Ohne Artikel im Plural: mit braunen Möbeln. Der Dativ steht nach mit, von, bei, aus, zu, nach, seit und auf die Frage Wo?',
        examples: ['Ich kaufe in einem kleinen Laden ein.', 'Sie kommt mit einer großen Tasche.', 'Er spielt mit seinen neuen Freunden.'],
        highlight: null,
        t: [
          'In the dative the adjective ending after ein, kein, mein is always -en: in einem neuen Laden, mit einem schönen Licht, in einer schönen Wohnung, mit meinen alten Freunden. Without an article in the plural: mit braunen Möbeln. The dative follows mit, von, bei, aus, zu, nach, seit and answers the question Wo? (where?)',
          'В Dativ окончание прилагательного после ein, kein, mein всегда -en: in einem neuen Laden, mit einem schönen Licht, in einer schönen Wohnung, mit meinen alten Freunden. Без артикля во множественном числе: mit braunen Möbeln. Dativ стоит после mit, von, bei, aus, zu, nach, seit и отвечает на вопрос Wo? (где?)',
          'У Dativ закінчення прикметника після ein, kein, mein завжди -en: in einem neuen Laden, mit einem schönen Licht, in einer schönen Wohnung, mit meinen alten Freunden. Без артикля у множині: mit braunen Möbeln. Dativ стоїть після mit, von, bei, aus, zu, nach, seit і відповідає на запитання Wo? (де?)',
          'Dativ’de ein, kein, mein sözcüklerinden sonra sıfat eki her zaman -en olur: in einem neuen Laden, mit einem schönen Licht, in einer schönen Wohnung, mit meinen alten Freunden. Çoğulda artikelsiz: mit braunen Möbeln. Dativ mit, von, bei, aus, zu, nach, seit edatlarından sonra ve Wo? (nerede?) sorusunda kullanılır.',
        ],
        hint: ['Dativ: immer -en. mit einem alten …, mit einer alten …, mit meinen alten …', 'Dative: always -en. mit einem alten …, mit einer alten …, mit meinen alten …', 'Dativ: всегда -en. mit einem alten …, mit einer alten …, mit meinen alten …', 'Dativ: завжди -en. mit einem alten …, mit einer alten …, mit meinen alten …', 'Dativ: her zaman -en. mit einem alten …, mit einer alten …, mit meinen alten …'],
      },
      ex: [
        mc('G3', 'einer -en', I.choose, 'Wir wohnen in einer … Wohnung.', ['kleinen', 'kleine', 'kleiner'],
          ['We live in a small flat.', 'Мы живём в маленькой квартире.', 'Ми живемо в маленькій квартирі.', 'Küçük bir dairede oturuyoruz.']),
        mc('G3', 'einem -en', I.choose, 'Ich schreibe mit einem … Stift.', ['roten', 'roter', 'rotes'],
          ['I am writing with a red pen.', 'Я пишу красной ручкой.', 'Я пишу червоною ручкою.', 'Kırmızı bir kalemle yazıyorum.']),
        mc('G3', 'ihrem -en', I.choose, 'Sie fährt mit ihrem … Fahrrad.', ['neuen', 'neues', 'neue'],
          ['She is riding her new bike.', 'Она едет на своём новом велосипеде.', 'Вона їде на своєму новому велосипеді.', 'Yeni bisikletiyle gidiyor.']),
        mc('G3', 'seinen -en (Plural)', I.choose, 'Er spricht mit seinen … Kollegen.', ['netten', 'nette', 'netter'],
          ['He is talking to his nice colleagues.', 'Он разговаривает со своими приятными коллегами.', 'Він розмовляє зі своїми приємними колегами.', 'Cana yakın iş arkadaşlarıyla konuşuyor.']),
        mc('G3', 'einem -en', I.sentence, 'Wo hast du die Kerze gekauft?', ['In einem kleinen Geschäft.', 'In einem kleines Geschäft.', 'In einem kleine Geschäft.'],
          ['Where did you buy the candle?', 'Где ты купил свечу?', 'Де ти купив свічку?', 'Mumu nereden aldın?']),
        gap('G3', 'einem -en', I.ending, 'Die Suppe ist in einem ', ' Topf.', 'großen', ['großer', 'großem'],
          ['The soup is in a big pot.', 'Суп в большой кастрюле.', 'Суп у великій каструлі.', 'Çorba büyük bir tencerede.'], 'groß'),
        gap('G3', 'einer -en', I.ending, 'Ich habe das Bild von einer ', ' Freundin bekommen.', 'guten', ['gute', 'guter'],
          ['I got the picture from a good friend.', 'Я получил картину от хорошей подруги.', 'Я отримав картину від доброї подруги.', 'Resmi iyi bir arkadaşımdan aldım.'], 'gut'),
        gap('G3', 'ihrem -en', I.ending, 'Olga geht mit ihrem ', ' Hund spazieren.', 'kleinen', ['kleiner', 'kleinem'],
          ['Olga is going for a walk with her little dog.', 'Olga гуляет со своей маленькой собакой.', 'Olga гуляє зі своїм маленьким собакою.', 'Olga küçük köpeğiyle yürüyüşe çıkıyor.'], 'klein'),
        gap('G3', 'einem -en', I.ending, 'Seit einem ', ' Jahr sammle ich alte Postkarten.', 'halben', ['halbes', 'halber'],
          ['I have been collecting old postcards for half a year.', 'Уже полгода я собираю старые открытки.', 'Уже пів року я збираю старі листівки.', 'Yarım yıldır eski kartpostal biriktiriyorum.'], 'halb'),
        sb('G3', 'einem -en', I.order, 'Wir / essen / in einem / kleinen / Restaurant.',
          ['We are eating in a small restaurant.', 'Мы едим в маленьком ресторане.', 'Ми їмо в маленькому ресторані.', 'Küçük bir restoranda yemek yiyoruz.'],
          { alt: ['In einem kleinen Restaurant essen wir.'] }),
      ],
    },
    {
      title: 'schöner, am schönsten',
      t: ['schöner, am schönsten (comparing)', 'schöner, am schönsten (степени сравнения)', 'schöner, am schönsten (ступені порівняння)', 'schöner, am schönsten (karşılaştırma)'],
      card: {
        id: 'p2_komparation',
        rule: 'Vergleichen in drei Stufen: schön – schöner – am schönsten. Komparativ: Adjektiv + -er. Superlativ: am + Adjektiv + -sten. Nach -d, -t, -s, -ß, -z heißt es -esten: interessant – am interessantesten. Oft mit Umlaut: groß – größer – am größten, lang – länger – am längsten, alt – älter – am ältesten, dumm – dümmer – am dümmsten. Besondere Formen: hoch – höher – am höchsten, gut – besser – am besten, gern – lieber – am liebsten, viel – mehr – am meisten.',
        examples: ['Der Rucksack ist praktischer.', 'Dieses Bild ist am schönsten.', 'Der Turm ist höher.'],
        highlight: null,
        t: [
          'Comparing in three steps: schön – schöner – am schönsten (beautiful – more beautiful – most beautiful). Comparative: adjective + -er. Superlative: am + adjective + -sten. After -d, -t, -s, -ß, -z it is -esten: interessant – am interessantesten. Often with an umlaut: groß – größer – am größten, lang – länger – am längsten, alt – älter – am ältesten, dumm – dümmer – am dümmsten. Special forms: hoch – höher – am höchsten, gut – besser – am besten, gern – lieber – am liebsten, viel – mehr – am meisten.',
          'Три степени сравнения: schön – schöner – am schönsten (красивый – красивее – красивее всех). Сравнительная степень: прилагательное + -er. Превосходная: am + прилагательное + -sten. После -d, -t, -s, -ß, -z будет -esten: interessant – am interessantesten. Часто с умлаутом: groß – größer – am größten, lang – länger – am längsten, alt – älter – am ältesten, dumm – dümmer – am dümmsten. Особые формы: hoch – höher – am höchsten, gut – besser – am besten, gern – lieber – am liebsten, viel – mehr – am meisten.',
          'Три ступені порівняння: schön – schöner – am schönsten (гарний – гарніший – найгарніший). Вищий ступінь: прикметник + -er. Найвищий: am + прикметник + -sten. Після -d, -t, -s, -ß, -z буде -esten: interessant – am interessantesten. Часто з умлаутом: groß – größer – am größten, lang – länger – am längsten, alt – älter – am ältesten, dumm – dümmer – am dümmsten. Особливі форми: hoch – höher – am höchsten, gut – besser – am besten, gern – lieber – am liebsten, viel – mehr – am meisten.',
          'Üç basamakta karşılaştırma: schön – schöner – am schönsten (güzel – daha güzel – en güzel). Karşılaştırma: sıfat + -er. Üstünlük: am + sıfat + -sten. -d, -t, -s, -ß, -z harflerinden sonra -esten olur: interessant – am interessantesten. Çoğu zaman umlaut alır: groß – größer – am größten, lang – länger – am längsten, alt – älter – am ältesten, dumm – dümmer – am dümmsten. Özel biçimler: hoch – höher – am höchsten, gut – besser – am besten, gern – lieber – am liebsten, viel – mehr – am meisten.',
        ],
        hint: ['Komparativ: -er (schöner, größer). Superlativ: am …-sten (am schönsten, am größten). hoch → höher, gut → besser, viel → mehr.', 'Comparative: -er (schöner, größer). Superlative: am …-sten (am schönsten, am größten). hoch → höher, gut → besser, viel → mehr.', 'Сравнительная степень: -er (schöner, größer). Превосходная: am …-sten (am schönsten, am größten). hoch → höher, gut → besser, viel → mehr.', 'Вищий ступінь: -er (schöner, größer). Найвищий: am …-sten (am schönsten, am größten). hoch → höher, gut → besser, viel → mehr.', 'Karşılaştırma: -er (schöner, größer). Üstünlük: am …-sten (am schönsten, am größten). hoch → höher, gut → besser, viel → mehr.'],
      },
      ex: [
        mc('G4', 'größer', I.choose, 'Wie heißt der Komparativ von „groß“?', ['größer', 'großer', 'am größten'],
          ['What is the comparative of “groß”?', 'Как образуется сравнительная степень от «groß»?', 'Як утворюється вищий ступінь від «groß»?', '“groß” sıfatının karşılaştırma biçimi nedir?']),
        mc('G4', 'am höchsten', I.choose, 'Das Hotel ist hoch, die Kirche ist höher, aber der Fernsehturm ist …', ['am höchsten', 'am höhsten', 'am hochsten'],
          ['The hotel is tall, the church is taller, but the TV tower is …', 'Отель высокий, церковь выше, но телебашня …', 'Готель високий, церква вища, але телевежа …', 'Otel yüksek, kilise daha yüksek ama televizyon kulesi …']),
        mc('G4', 'am interessantesten', I.choose, 'Wie heißt der Superlativ von „interessant“?', ['am interessantesten', 'am interessantsten', 'am interessanter'],
          ['What is the superlative of “interessant”?', 'Как образуется превосходная степень от «interessant»?', 'Як утворюється найвищий ступінь від «interessant»?', '“interessant” sıfatının üstünlük biçimi nedir?']),
        mc('G4', 'wärmer', I.choose, 'Heute ist es warm. Morgen ist es noch …', ['wärmer', 'warmer', 'am wärmsten'],
          ['It is warm today. Tomorrow it will be even …', 'Сегодня тепло. Завтра будет ещё …', 'Сьогодні тепло. Завтра буде ще …', 'Bugün hava ılık. Yarın daha da …']),
        gap('G4', 'schöner', I.comparison, 'Der blaue Schirm ist schön, aber der rote ist noch ', '.', 'schöner', ['schönsten', 'schön'],
          ['The blue umbrella is nice, but the red one is even nicer.', 'Синий зонт красивый, но красный ещё красивее.', 'Синя парасолька гарна, але червона ще гарніша.', 'Mavi şemsiye güzel ama kırmızısı daha da güzel.'], 'schön'),
        gap('G4', 'älter', I.comparison, 'Mein Bruder ist 20, ich bin 25. Ich bin ', '.', 'älter', ['alter', 'ältesten'],
          ['My brother is 20, I am 25. I am older.', 'Моему брату 20, мне 25. Я старше.', 'Моєму братові 20, мені 25. Я старший.', 'Erkek kardeşim 20, ben 25 yaşındayım. Ben daha büyüğüm.'], 'alt'),
        gap('G4', 'am größten', I.comparison, 'Von allen Taschen ist diese am ', '.', 'größten', ['größer', 'großen'],
          ['Of all the bags this one is the biggest.', 'Из всех сумок эта самая большая.', 'З усіх сумок ця найбільша.', 'Bütün çantaların içinde en büyüğü bu.'], 'groß'),
        gap('G4', 'kürzer', I.comparison, 'Der Weg durch den Park ist kurz, aber der Weg über den Platz ist noch ', '.', 'kürzer', ['kurzer', 'kürzesten'],
          ['The way through the park is short, but the way across the square is even shorter.', 'Путь через парк короткий, но путь через площадь ещё короче.', 'Шлях через парк короткий, але шлях через площу ще коротший.', 'Parktan geçen yol kısa ama meydandan geçen yol daha da kısa.'], 'kurz'),
        gap('G4', 'mehr', I.comparison, 'Ein Fahrrad kostet viel, aber ein Auto kostet ', '.', 'mehr', ['mehrer', 'vieler'],
          ['A bike costs a lot, but a car costs more.', 'Велосипед стоит дорого, но машина стоит больше.', 'Велосипед коштує дорого, але машина коштує більше.', 'Bisiklet pahalı ama araba daha pahalı.'], 'viel'),
        sb('G4', 'am besten', I.order, 'Dieser Ring / gefällt / mir / am besten.',
          ['I like this ring best.', 'Это кольцо нравится мне больше всего.', 'Цей перстень подобається мені найбільше.', 'En çok bu yüzüğü beğeniyorum.'],
          { alt: ['Am besten gefällt mir dieser Ring.', 'Mir gefällt dieser Ring am besten.'] }),
      ],
    },
    {
      title: 'als oder wie?',
      t: ['als or wie? (than / as … as)', 'als или wie? (чем / так же … как)', 'als чи wie? (ніж / так само … як)', 'als mı, wie mi? (-den daha / … kadar)'],
      card: {
        id: 'p2_als_wie',
        rule: 'Vergleichen mit als und wie. Ungleich: Komparativ + als – Der Rucksack ist praktischer als die Tasche. Dorina mag Rockmusik lieber als Jazz. Gleich: (genau)so + Adjektiv + wie – Der Schal ist genauso warm wie die Jacke. Sie geht genauso gern ins Kino wie ins Theater. Auch: nicht so … wie – Das Buch ist nicht so teuer wie der Film.',
        examples: ['Glas ist schwerer als Plastik.', 'Mein Handy ist genauso alt wie dein Handy.', 'Tee trinke ich lieber als Kaffee.'],
        highlight: null,
        t: [
          'Comparing with als and wie. Not equal: comparative + als (than) – Der Rucksack ist praktischer als die Tasche. Dorina mag Rockmusik lieber als Jazz. Equal: (genau)so + adjective + wie (just as … as) – Der Schal ist genauso warm wie die Jacke. Sie geht genauso gern ins Kino wie ins Theater. Also: nicht so … wie (not as … as) – Das Buch ist nicht so teuer wie der Film.',
          'Сравнение с als и wie. Неравенство: сравнительная степень + als (чем) – Der Rucksack ist praktischer als die Tasche. Dorina mag Rockmusik lieber als Jazz. Равенство: (genau)so + прилагательное + wie (такой же … как) – Der Schal ist genauso warm wie die Jacke. Sie geht genauso gern ins Kino wie ins Theater. Также: nicht so … wie (не такой … как) – Das Buch ist nicht so teuer wie der Film.',
          'Порівняння з als і wie. Нерівність: вищий ступінь + als (ніж) – Der Rucksack ist praktischer als die Tasche. Dorina mag Rockmusik lieber als Jazz. Рівність: (genau)so + прикметник + wie (такий самий … як) – Der Schal ist genauso warm wie die Jacke. Sie geht genauso gern ins Kino wie ins Theater. Також: nicht so … wie (не такий … як) – Das Buch ist nicht so teuer wie der Film.',
          'als ve wie ile karşılaştırma. Eşit değil: karşılaştırma biçimi + als (-den daha) – Der Rucksack ist praktischer als die Tasche. Dorina mag Rockmusik lieber als Jazz. Eşit: (genau)so + sıfat + wie (… kadar) – Der Schal ist genauso warm wie die Jacke. Sie geht genauso gern ins Kino wie ins Theater. Ayrıca: nicht so … wie (… kadar değil) – Das Buch ist nicht so teuer wie der Film.',
        ],
        hint: ['Komparativ (-er) → als. so / genauso → wie.', 'Comparative (-er) → als (than). so / genauso → wie (as … as).', 'Сравнительная степень (-er) → als (чем). so / genauso → wie (так же … как).', 'Вищий ступінь (-er) → als (ніж). so / genauso → wie (так само … як).', 'Karşılaştırma (-er) → als (-den daha). so / genauso → wie (… kadar).'],
      },
      ex: [
        mc('G5', 'als', I.choose, 'Der Topf ist größer … die Schüssel.', ['als', 'wie', 'so'],
          ['The pot is bigger than the bowl.', 'Кастрюля больше, чем миска.', 'Каструля більша, ніж миска.', 'Tencere kâseden daha büyük.']),
        mc('G5', 'wie', I.choose, 'Mein Rucksack ist genauso schwer … dein Rucksack.', ['wie', 'als', 'dass'],
          ['My rucksack is just as heavy as your rucksack.', 'Мой рюкзак такой же тяжёлый, как твой.', 'Мій рюкзак такий самий важкий, як твій.', 'Benim sırt çantam seninki kadar ağır.']),
        mc('G5', 'lieber als', I.choose, 'Ich fahre lieber Fahrrad … Auto.', ['als', 'wie', 'wenn'],
          ['I prefer cycling to driving.', 'Я больше люблю ездить на велосипеде, чем на машине.', 'Я більше люблю їздити на велосипеді, ніж на машині.', 'Araba yerine bisiklet sürmeyi tercih ederim.']),
        mc('G5', 'genauso … wie', I.sentence, 'Die Kette kostet 50 Euro. Der Ring kostet auch 50 Euro.', ['Die Kette ist genauso teuer wie der Ring.', 'Die Kette ist teurer als der Ring.', 'Die Kette ist genauso teuer als der Ring.'],
          ['The necklace costs 50 euros. The ring costs 50 euros too.', 'Цепочка стоит 50 евро. Кольцо тоже стоит 50 евро.', 'Ланцюжок коштує 50 євро. Перстень теж коштує 50 євро.', 'Kolye 50 avro. Yüzük de 50 avro.']),
        mc('G5', 'größer als', I.sentence, 'Tom ist 1,80 m groß. Paul ist 1,90 m groß.', ['Paul ist größer als Tom.', 'Paul ist größer wie Tom.', 'Paul ist so groß wie Tom.'],
          ['Tom is 1.80 m tall. Paul is 1.90 m tall.', 'Рост Tom – 1,80 м. Рост Paul – 1,90 м.', 'Зріст Tom – 1,80 м. Зріст Paul – 1,90 м.', 'Tom 1,80 m boyunda. Paul 1,90 m boyunda.']),
        gap('G5', 'als', I.word, 'Holz ist leichter ', ' Metall.', 'als', ['wie', 'so'],
          ['Wood is lighter than metal.', 'Дерево легче, чем металл.', 'Дерево легше, ніж метал.', 'Ahşap metalden daha hafif.'], 'als / wie'),
        gap('G5', 'nicht so … wie', I.word, 'Die Kerze ist nicht so teuer ', ' die Lampe.', 'wie', ['als', 'dass'],
          ['The candle is not as expensive as the lamp.', 'Свеча не такая дорогая, как лампа.', 'Свічка не така дорога, як лампа.', 'Mum lamba kadar pahalı değil.'], 'als / wie'),
        gap('G5', 'Komparativ + als', I.comparison, 'Ein Zug ist ', ' als ein Fahrrad.', 'schneller', ['schnell', 'schnellsten'],
          ['A train is faster than a bike.', 'Поезд быстрее, чем велосипед.', 'Потяг швидший, ніж велосипед.', 'Tren bisikletten daha hızlı.'], 'schnell'),
        gap('G5', 'genauso', I.word, 'Der Film ist ', ' spannend wie das Buch. Beide sind toll.', ['genauso', 'so'], ['mehr', 'besser'],
          ['The film is just as exciting as the book. Both are great.', 'Фильм такой же увлекательный, как книга. Оба отличные.', 'Фільм такий самий захопливий, як книжка. Обидва чудові.', 'Film kitap kadar sürükleyici. İkisi de harika.'],
          ['just as', 'так же', 'так само', 'aynı derecede']),
        sb('G5', 'älter als', I.order, 'Mein Bruder / ist / älter / als / ich.',
          ['My brother is older than me.', 'Мой брат старше меня.', 'Мій брат старший за мене.', 'Erkek kardeşim benden büyük.']),
      ],
    },
    {
      title: 'arbeitslos',
      t: ['arbeitslos (adjectives with -los)', 'arbeitslos (прилагательные на -los)', 'arbeitslos (прикметники на -los)', 'arbeitslos (-los ile sıfatlar)'],
      card: {
        id: 'p2_los',
        rule: 'Wortbildung: Nomen + -los = Adjektiv. -los bedeutet „ohne“: die Arbeit → arbeitslos (ohne Arbeit), der Fehler → fehlerlos (ohne Fehler), der Schlaf → schlaflos, der Wunsch → wunschlos, die Wolke → wolkenlos, das Herz → herzlos, das Ende → endlos, die Farbe → farblos, die Kosten → kostenlos (es kostet nichts). Adjektive schreibt man klein.',
        examples: ['Mein Onkel ist seit einem Jahr arbeitslos.', 'Der Himmel ist heute wolkenlos.', 'Der Eintritt ist kostenlos.'],
        highlight: null,
        t: [
          'Word formation: noun + -los = adjective. -los means “without”: die Arbeit → arbeitslos (unemployed, without work), der Fehler → fehlerlos (flawless, without mistakes), der Schlaf → schlaflos (sleepless), der Wunsch → wunschlos (wanting nothing), die Wolke → wolkenlos (cloudless), das Herz → herzlos (heartless), das Ende → endlos (endless), die Farbe → farblos (colourless), die Kosten → kostenlos (free of charge). Adjectives are written with a small letter.',
          'Словообразование: существительное + -los = прилагательное. -los значит «без»: die Arbeit → arbeitslos (безработный), der Fehler → fehlerlos (безошибочный), der Schlaf → schlaflos (бессонный), der Wunsch → wunschlos (без желаний), die Wolke → wolkenlos (безоблачный), das Herz → herzlos (бессердечный), das Ende → endlos (бесконечный), die Farbe → farblos (бесцветный), die Kosten → kostenlos (бесплатный). Прилагательные пишутся с маленькой буквы.',
          'Словотворення: іменник + -los = прикметник. -los означає «без»: die Arbeit → arbeitslos (безробітний), der Fehler → fehlerlos (безпомилковий), der Schlaf → schlaflos (безсонний), der Wunsch → wunschlos (без бажань), die Wolke → wolkenlos (безхмарний), das Herz → herzlos (безсердечний), das Ende → endlos (нескінченний), die Farbe → farblos (безбарвний), die Kosten → kostenlos (безкоштовний). Прикметники пишуться з малої літери.',
          'Sözcük türetme: isim + -los = sıfat. -los “-sız/-siz” demektir: die Arbeit → arbeitslos (işsiz), der Fehler → fehlerlos (hatasız), der Schlaf → schlaflos (uykusuz), der Wunsch → wunschlos (dileksiz), die Wolke → wolkenlos (bulutsuz), das Herz → herzlos (kalpsiz), das Ende → endlos (sonsuz), die Farbe → farblos (renksiz), die Kosten → kostenlos (ücretsiz). Sıfatlar küçük harfle yazılır.',
        ],
        hint: ['-los = ohne: arbeitslos = ohne Arbeit, fehlerlos = ohne Fehler, kostenlos = ohne Kosten.', '-los = without: arbeitslos = ohne Arbeit, fehlerlos = ohne Fehler, kostenlos = ohne Kosten.', '-los = без: arbeitslos = ohne Arbeit, fehlerlos = ohne Fehler, kostenlos = ohne Kosten.', '-los = без: arbeitslos = ohne Arbeit, fehlerlos = ohne Fehler, kostenlos = ohne Kosten (безкоштовно).', '-los = -sız/-siz: arbeitslos = ohne Arbeit, fehlerlos = ohne Fehler, kostenlos = ohne Kosten.'],
      },
      ex: [
        mc('G6', 'arbeitslos', I.choose, 'Was bedeutet „arbeitslos“?', ['ohne Arbeit', 'mit viel Arbeit', 'bei der Arbeit'],
          ['What does “arbeitslos” mean?', 'Что значит «arbeitslos»?', 'Що означає «arbeitslos»?', '“arbeitslos” ne demek?']),
        mc('G6', 'wolkenlos', I.choose, 'Am Himmel ist keine Wolke. Der Himmel ist …', ['wolkenlos', 'wolkig', 'farblos'],
          ['There is not a cloud in the sky. The sky is …', 'На небе ни облачка. Небо …', 'На небі жодної хмаринки. Небо …', 'Gökyüzünde tek bir bulut yok. Gökyüzü …']),
        mc('G6', 'fehlerlos', I.choose, 'Dein Text hat keinen Fehler. Er ist …', ['fehlerlos', 'herzlos', 'endlos'],
          ['Your text has no mistakes. It is …', 'В твоём тексте нет ни одной ошибки. Он …', 'У твоєму тексті немає жодної помилки. Він …', 'Metninde hiç hata yok. Metin …']),
        mc('G6', 'schlaflos', I.choose, 'Wie heißt das Adjektiv? ohne Schlaf = …', ['schlaflos', 'wunschlos', 'farblos'],
          ['What is the adjective? without sleep = …', 'Как будет прилагательное? без сна = …', 'Як буде прикметник? без сну = …', 'Sıfat nasıl olur? uykusuz = …']),
        mc('G6', 'kostenlos', I.choose, 'Das Museum kostet heute nichts. Der Eintritt ist …', ['kostenlos', 'arbeitslos', 'endlos'],
          ['The museum costs nothing today. Admission is …', 'Сегодня музей ничего не стоит. Вход …', 'Сьогодні музей нічого не коштує. Вхід …', 'Müze bugün ücretsiz. Giriş …']),
        gap('G6', 'arbeitslos', I.form, 'Herr Novak hat keine Arbeit. Er ist ', '.', 'arbeitslos', ['arbeitsam', 'arbeiten'],
          ['Mr Novak has no job. He is unemployed.', 'У господина Novak нет работы. Он безработный.', 'У пана Novak немає роботи. Він безробітний.', 'Novak Bey’in işi yok. O işsiz.'], 'die Arbeit'),
        gap('G6', 'schlaflos', I.form, 'Ich konnte die ganze Nacht nicht schlafen. Es war eine ', ' Nacht.', 'schlaflose', ['schlaflos', 'schlaflosen'],
          ['I could not sleep all night. It was a sleepless night.', 'Я не мог спать всю ночь. Это была бессонная ночь.', 'Я не міг спати всю ніч. Це була безсонна ніч.', 'Bütün gece uyuyamadım. Uykusuz bir geceydi.'], 'der Schlaf'),
        gap('G6', 'endlos', I.form, 'Der Film hört nicht auf. Er ist ', ' lang!', 'endlos', ['endlich', 'enden'],
          ['The film just does not stop. It is endlessly long!', 'Фильм всё не заканчивается. Он бесконечно длинный!', 'Фільм усе не закінчується. Він нескінченно довгий!', 'Film bir türlü bitmiyor. Sonsuz uzun!'], 'das Ende'),
        gap('G6', 'farblos', I.form, 'Wasser hat keine Farbe. Es ist ', '.', 'farblos', ['farbig', 'farben'],
          ['Water has no colour. It is colourless.', 'У воды нет цвета. Она бесцветная.', 'Вода не має кольору. Вона безбарвна.', 'Suyun rengi yoktur. Renksizdir.'], 'die Farbe'),
        sb('G6', 'wolkenlos', I.order, 'Der Himmel / ist / heute / wolkenlos.',
          ['The sky is cloudless today.', 'Сегодня небо безоблачное.', 'Сьогодні небо безхмарне.', 'Bugün gökyüzü bulutsuz.'],
          { alt: ['Heute ist der Himmel wolkenlos.'] }),
      ],
    },
    {
      title: 'Tja, ich weiß nicht.',
      t: ['Well, I am not sure.', 'Ну, не знаю.', 'Ну, не знаю.', 'Valla, bilmiyorum.'],
      card: {
        id: 'p2_skeptisch',
        rule: 'Skeptisch reagieren: Man ist nicht sicher oder findet etwas nicht so gut, sagt es aber vorsichtig. Tja, ich weiß nicht. Hm, findest du? Ja, wirklich? Bist du sicher? Na ja, geht so. Also, ich weiß nicht … Das Gegenteil ist Zustimmung: Ja, das finde ich auch. Stimmt, du hast recht.',
        examples: ['Der Hut steht mir gut, oder? – Hm, findest du?', 'Heute ist ein guter Einkaufstag. – Na ja, geht so.', 'Das ist ein tolles Angebot! – Bist du sicher?'],
        highlight: null,
        t: [
          'Reacting sceptically: you are not sure or do not like something much, but you say so carefully. Tja, ich weiß nicht. (Well, I do not know.) Hm, findest du? (Hm, do you think so?) Ja, wirklich? (Really?) Bist du sicher? (Are you sure?) Na ja, geht so. (Well, so-so.) Also, ich weiß nicht … The opposite is agreement: Ja, das finde ich auch. Stimmt, du hast recht. (True, you are right.)',
          'Как реагировать скептически: вы не уверены или вам что-то не очень нравится, но вы говорите об этом осторожно. Tja, ich weiß nicht. (Ну, не знаю.) Hm, findest du? (Хм, ты так считаешь?) Ja, wirklich? (Правда?) Bist du sicher? (Ты уверен?) Na ja, geht so. (Ну, так себе.) Also, ich weiß nicht … Противоположность – согласие: Ja, das finde ich auch. Stimmt, du hast recht. (Верно, ты прав.)',
          'Як реагувати скептично: ви не впевнені або вам щось не дуже подобається, але ви кажете про це обережно. Tja, ich weiß nicht. (Ну, не знаю.) Hm, findest du? (Гм, ти так вважаєш?) Ja, wirklich? (Справді?) Bist du sicher? (Ти впевнений?) Na ja, geht so. (Ну, так собі.) Also, ich weiß nicht … Протилежність – згода: Ja, das finde ich auch. Stimmt, du hast recht. (Правильно, ти маєш рацію.)',
          'Şüpheyle tepki vermek: Emin değilsiniz ya da bir şeyi pek beğenmiyorsunuz ama bunu dikkatli söylüyorsunuz. Tja, ich weiß nicht. (Valla, bilmiyorum.) Hm, findest du? (Hım, öyle mi düşünüyorsun?) Ja, wirklich? (Gerçekten mi?) Bist du sicher? (Emin misin?) Na ja, geht so. (Eh, idare eder.) Also, ich weiß nicht … Bunun tersi onaylamaktır: Ja, das finde ich auch. Stimmt, du hast recht. (Doğru, haklısın.)',
        ],
        hint: ['Skeptisch = nicht sicher: Tja … Hm, findest du? Na ja, geht so. Bist du sicher?', 'Sceptical = not sure: Tja … Hm, findest du? Na ja, geht so. Bist du sicher?', 'Скептически = неуверенно: Tja … Hm, findest du? Na ja, geht so. Bist du sicher?', 'Скептично = невпевнено: Tja … Hm, findest du? Na ja, geht so. Bist du sicher?', 'Şüpheci = emin değil: Tja … Hm, findest du? Na ja, geht so. Bist du sicher?'],
      },
      ex: [
        mc('K1', 'Hm, findest du?', I.react, '„Die Lampe ist doch wunderschön!“ – Du findest sie nicht so schön.', ['Hm, findest du?', 'Ja, sie ist wunderschön!', 'Das finde ich auch.'],
          ['“The lamp is really beautiful!” – You do not find it that beautiful.', '«Лампа ведь очень красивая!» – Вам она не очень нравится.', '«Лампа ж дуже гарна!» – Вам вона не дуже подобається.', '“Lamba çok güzel ama!” – Siz o kadar güzel bulmuyorsunuz.']),
        mc('K1', 'Na ja, geht so.', I.react, '„Heute ist ein richtig guter Einkaufstag, oder?“ – Du bist nicht begeistert.', ['Na ja, geht so.', 'Ja, super!', 'Stimmt, du hast recht.'],
          ['“Today is a really good day for shopping, isn’t it?” – You are not enthusiastic.', '«Сегодня отличный день для покупок, правда?» – Вы не в восторге.', '«Сьогодні чудовий день для покупок, правда?» – Ви не в захваті.', '“Bugün alışveriş için gerçekten iyi bir gün, değil mi?” – Pek hevesli değilsiniz.']),
        mc('K1', 'geht so', I.choose, 'Was bedeutet „Na ja, geht so“?', ['Es ist nicht besonders gut.', 'Es ist ausgezeichnet.', 'Es ist sehr schlecht.'],
          ['What does “Na ja, geht so” mean?', 'Что значит «Na ja, geht so»?', 'Що означає «Na ja, geht so»?', '“Na ja, geht so” ne demek?']),
        mc('K1', 'skeptisch', I.choose, 'Welche Reaktion ist skeptisch?', ['Bist du sicher?', 'Ja, genau!', 'Das stimmt.'],
          ['Which reaction is sceptical?', 'Какая реакция скептическая?', 'Яка реакція скептична?', 'Hangi tepki şüphecidir?']),
        mc('K1', 'Tja, ich weiß nicht.', I.situation, 'Dein Freund möchte einen sehr teuren Rucksack kaufen. Du bist nicht überzeugt. Was sagst du?', ['Tja, ich weiß nicht. Der ist ziemlich teuer.', 'Super, kauf ihn sofort!', 'Der ist am billigsten.'],
          ['Your friend wants to buy a very expensive rucksack. You are not convinced. What do you say?', 'Ваш друг хочет купить очень дорогой рюкзак. Вы не уверены, что это хорошая идея. Что вы скажете?', 'Ваш друг хоче купити дуже дорогий рюкзак. Ви не впевнені, що це добра ідея. Що ви скажете?', 'Arkadaşınız çok pahalı bir sırt çantası almak istiyor. İkna olmadınız. Ne dersiniz?']),
        gap('K1', 'findest du?', I.verb, 'Das Bild passt gut ins Wohnzimmer. – Hm, ', ' du?', 'findest', ['findet', 'finden'],
          ['The picture goes well in the living room. – Hm, do you think so?', 'Картина хорошо подходит к гостиной. – Хм, ты так считаешь?', 'Картина добре пасує до вітальні. – Гм, ти так вважаєш?', 'Resim oturma odasına çok yakışıyor. – Hım, öyle mi düşünüyorsun?'], 'finden'),
        gap('K1', 'ich weiß nicht', I.verb, 'Tja, ich ', ' nicht. Die Farbe gefällt mir nicht so.', 'weiß', ['weißt', 'wissen'],
          ['Well, I do not know. I do not like the colour that much.', 'Ну, не знаю. Цвет мне не очень нравится.', 'Ну, не знаю. Колір мені не дуже подобається.', 'Valla, bilmiyorum. Rengi pek hoşuma gitmiyor.'], 'wissen'),
        gap('K1', 'Bist du sicher?', I.word, 'Der Mantel ist billig und gut. – Bist du ', '?', 'sicher', ['fertig', 'müde'],
          ['The coat is cheap and good. – Are you sure?', 'Пальто дешёвое и хорошее. – Ты уверен?', 'Пальто дешеве й добре. – Ти впевнений?', 'Palto ucuz ve iyi. – Emin misin?'],
          ['sure', 'уверен', 'упевнений', 'emin']),
        gap('K1', 'geht so', I.verb, 'Wie war der Flohmarkt? – Na ja, ', ' so.', 'geht', ['kommt', 'macht'],
          ['How was the flea market? – Well, so-so.', 'Как тебе блошиный рынок? – Ну, так себе.', 'Як тобі блошиний ринок? – Ну, так собі.', 'Bit pazarı nasıldı? – Eh, idare eder.'], 'gehen'),
        sb('K1', 'Also, ich weiß nicht.', I.order, 'Also, / ich / weiß / nicht.',
          ['Well, I do not know.', 'Ну, я не знаю.', 'Ну, я не знаю.', 'Yani, bilmiyorum.']),
      ],
    },
    {
      title: 'Am meisten gebe ich für … aus.',
      t: ['I spend most on …', 'Больше всего я трачу на …', 'Найбільше я витрачаю на …', 'En çok … için para harcıyorum'],
      card: {
        id: 'p2_konsum',
        rule: 'Über Einkaufen und Geld sprechen: Geld ausgeben für + Akkusativ – Am meisten gebe ich für meine Miete aus. Ich gebe viel Geld für Kleidung aus. Ich gebe nicht viel für Möbel aus. Da spare ich. Ich kaufe am liebsten auf dem Markt ein. Vergleichen: Ich finde Rucksäcke praktischer als Taschen. Am praktischsten finde ich einen kleinen Rucksack.',
        examples: ['Am meisten gebe ich für Lebensmittel aus.', 'Für Kleidung gebe ich nicht viel aus. Da spare ich.', 'Am liebsten kaufe ich im Internet.'],
        highlight: null,
        t: [
          'Talking about shopping and money: Geld ausgeben für + accusative (spend money on) – Am meisten gebe ich für meine Miete aus. (I spend most on my rent.) Ich gebe viel Geld für Kleidung aus. Ich gebe nicht viel für Möbel aus. Da spare ich. (I save there.) Ich kaufe am liebsten auf dem Markt ein. (I like shopping at the market best.) Comparing: Ich finde Rucksäcke praktischer als Taschen. Am praktischsten finde ich einen kleinen Rucksack.',
          'Как говорить о покупках и деньгах: Geld ausgeben für + Akkusativ (тратить деньги на) – Am meisten gebe ich für meine Miete aus. (Больше всего я трачу на аренду.) Ich gebe viel Geld für Kleidung aus. Ich gebe nicht viel für Möbel aus. Da spare ich. (На этом я экономлю.) Ich kaufe am liebsten auf dem Markt ein. (Больше всего я люблю покупать на рынке.) Сравнение: Ich finde Rucksäcke praktischer als Taschen. Am praktischsten finde ich einen kleinen Rucksack.',
          'Як говорити про покупки й гроші: Geld ausgeben für + Akkusativ (витрачати гроші на) – Am meisten gebe ich für meine Miete aus. (Найбільше я витрачаю на оренду.) Ich gebe viel Geld für Kleidung aus. Ich gebe nicht viel für Möbel aus. Da spare ich. (На цьому я заощаджую.) Ich kaufe am liebsten auf dem Markt ein. (Найбільше я люблю купувати на ринку.) Порівняння: Ich finde Rucksäcke praktischer als Taschen. Am praktischsten finde ich einen kleinen Rucksack.',
          'Alışveriş ve paradan söz etmek: Geld ausgeben für + Akkusativ (… için para harcamak) – Am meisten gebe ich für meine Miete aus. (En çok kiraya para harcıyorum.) Ich gebe viel Geld für Kleidung aus. Ich gebe nicht viel für Möbel aus. Da spare ich. (Orada tasarruf ediyorum.) Ich kaufe am liebsten auf dem Markt ein. (En çok pazardan alışveriş yapmayı severim.) Karşılaştırma: Ich finde Rucksäcke praktischer als Taschen. Am praktischsten finde ich einen kleinen Rucksack.',
        ],
        hint: ['Geld ausgeben für + Akkusativ. viel – mehr – am meisten. sparen = wenig Geld ausgeben.', 'Geld ausgeben für (spend money on) + accusative. viel – mehr – am meisten. sparen = spend little money.', 'Geld ausgeben für (тратить деньги на) + Akkusativ. viel – mehr – am meisten. sparen = тратить мало денег.', 'Geld ausgeben für (витрачати гроші на) + Akkusativ. viel – mehr – am meisten. sparen = витрачати мало грошей.', 'Geld ausgeben für (… için para harcamak) + Akkusativ. viel – mehr – am meisten. sparen = az para harcamak.'],
      },
      ex: [
        mc('K2', 'Am meisten gebe ich für … aus.', I.react, '„Wofür gibst du am meisten Geld aus?“', ['Am meisten gebe ich für meine Wohnung aus.', 'Ich kaufe am liebsten im Supermarkt.', 'Ja, ich spare viel.'],
          ['“What do you spend most money on?”', '«На что ты тратишь больше всего денег?»', '«На що ти витрачаєш найбільше грошей?»', '“En çok neye para harcıyorsun?”']),
        mc('K2', 'sparen', I.choose, 'Was bedeutet „Da spare ich“?', ['Dafür gebe ich wenig Geld aus.', 'Dafür gebe ich viel Geld aus.', 'Das kaufe ich jeden Tag.'],
          ['What does “Da spare ich” mean?', 'Что значит «Da spare ich»?', 'Що означає «Da spare ich»?', '“Da spare ich” ne demek?']),
        mc('K2', 'ausgeben für', I.choose, 'Ich gebe viel Geld … Bücher aus.', ['für', 'auf', 'mit'],
          ['I spend a lot of money on books.', 'Я трачу много денег на книги.', 'Я витрачаю багато грошей на книжки.', 'Kitaplara çok para harcıyorum.']),
        mc('K2', 'am liebsten', I.situation, 'Du kaufst Obst und Gemüse immer auf dem Markt. Das magst du mehr als alles andere. Was sagst du?', ['Ich kaufe am liebsten auf dem Markt ein.', 'Ich kaufe nie auf dem Markt ein.', 'Auf dem Markt spare ich nicht.'],
          ['You always buy fruit and vegetables at the market. You like that more than anything else. What do you say?', 'Вы всегда покупаете фрукты и овощи на рынке. Это нравится вам больше всего. Что вы скажете?', 'Ви завжди купуєте фрукти й овочі на ринку. Це подобається вам найбільше. Що ви скажете?', 'Meyve ve sebzeyi hep pazardan alıyorsunuz. Bunu her şeyden çok seviyorsunuz. Ne dersiniz?']),
        mc("K2", "praktischer als", I.choose, "Leon findet: Taschen sind okay, aber Rucksäcke sind besser. Was stimmt?", ["Er findet Rucksäcke praktischer als Taschen.","Er findet Taschen praktischer als Rucksäcke.","Er findet Rucksäcke so praktisch wie Taschen."], ["Leon thinks bags are okay, but rucksacks are better. What is true?","Leon считает: сумки – нормально, но рюкзаки лучше. Что верно?","Leon вважає: сумки – нормально, але рюкзаки кращі. Що правильно?","Leon’a göre çantalar fena değil ama sırt çantaları daha iyi. Hangisi doğru?"], {"c":"p2_konsum","sitovOptionOrder":["Er findet Rucksäcke praktischer als Taschen.","Er findet Taschen praktischer als Rucksäcke.","Er findet Rucksäcke so praktisch wie Taschen."]}),
        gap('K2', 'am meisten', I.comparison, 'Am ', ' gebe ich für mein Auto aus: fast 300 Euro im Monat.', 'meisten', ['mehr', 'vielen'],
          ['I spend most on my car: almost 300 euros a month.', 'Больше всего я трачу на машину: почти 300 евро в месяц.', 'Найбільше я витрачаю на машину: майже 300 євро на місяць.', 'En çok arabama para harcıyorum: ayda neredeyse 300 avro.'], 'viel'),
        gap('K2', 'ausgeben', I.verb, 'Für Kleidung ', ' ich nicht viel Geld aus.', 'gebe', ['gibt', 'gehe'],
          ['I do not spend much money on clothes.', 'На одежду я трачу не много денег.', 'На одяг я витрачаю не багато грошей.', 'Giyime çok para harcamıyorum.'], 'ausgeben'),
        gap('K2', 'sparen', I.verb, 'Ich kaufe keine teuren Schuhe. Da ', ' ich lieber.', 'spare', ['zahle', 'kaufe'],
          ['I do not buy expensive shoes. I prefer to save there.', 'Я не покупаю дорогую обувь. На этом я предпочитаю экономить.', 'Я не купую дороге взуття. На цьому я волію заощаджувати.', 'Pahalı ayakkabı almıyorum. Orada tasarruf etmeyi tercih ediyorum.'],
          ['save', 'экономить', 'заощаджувати', 'tasarruf etmek']),
        gap('K2', 'am liebsten', I.comparison, 'Am ', ' kaufe ich in kleinen Läden ein. Das mag ich sehr.', 'liebsten', ['lieber', 'lieb'],
          ['I like shopping in small shops best. I like that very much.', 'Больше всего я люблю делать покупки в маленьких магазинах. Мне это очень нравится.', 'Найбільше я люблю робити покупки в маленьких крамницях. Мені це дуже подобається.', 'En çok küçük dükkânlardan alışveriş yapmayı severim. Bunu çok seviyorum.'], 'gern'),
        sb('K2', 'Geld ausgeben für', I.order, 'Ich / gebe / viel Geld / für Musik / aus.',
          ['I spend a lot of money on music.', 'Я трачу много денег на музыку.', 'Я витрачаю багато грошей на музику.', 'Müziğe çok para harcıyorum.'],
          { alt: ['Für Musik gebe ich viel Geld aus.', 'Viel Geld gebe ich für Musik aus.'] }),
      ],
    },
    {
      title: 'Mir ist … wichtig.',
      t: ['… is important to me.', 'Для меня важно …', 'Для мене важливо …', 'Benim için … önemli'],
      card: {
        id: 'p2_wichtig',
        rule: 'Wichtigkeit ausdrücken: Mir ist ein sicherer Arbeitsplatz wichtig. Mir sind gute Freunde wichtig (Plural: sind). Und dir? Wie wichtig ist dir Mode? – Sehr wichtig. Das ist mir auch wichtig, aber nicht sehr wichtig. Teure Kleidung ist mir überhaupt nicht wichtig. Steigern: wichtig – noch wichtiger – am wichtigsten.',
        examples: ['Mir ist Zeit mit der Familie wichtig.', 'Wie wichtig ist dir Geld?', 'Ein teures Auto ist mir überhaupt nicht wichtig.'],
        highlight: null,
        t: [
          'Saying how important something is: Mir ist ein sicherer Arbeitsplatz wichtig. (A secure job is important to me.) Mir sind gute Freunde wichtig (plural: sind). Und dir? (And to you?) Wie wichtig ist dir Mode? (How important is fashion to you?) – Sehr wichtig. Das ist mir auch wichtig, aber nicht sehr wichtig. Teure Kleidung ist mir überhaupt nicht wichtig. (… not important to me at all.) Grading: wichtig – noch wichtiger – am wichtigsten.',
          'Как сказать, насколько что-то важно: Mir ist ein sicherer Arbeitsplatz wichtig. (Для меня важна надёжная работа.) Mir sind gute Freunde wichtig (множественное число: sind). Und dir? (А для тебя?) Wie wichtig ist dir Mode? (Насколько для тебя важна мода?) – Sehr wichtig. Das ist mir auch wichtig, aber nicht sehr wichtig. Teure Kleidung ist mir überhaupt nicht wichtig. (… для меня совсем не важна.) Степени: wichtig – noch wichtiger – am wichtigsten.',
          'Як сказати, наскільки щось важливе: Mir ist ein sicherer Arbeitsplatz wichtig. (Для мене важлива надійна робота.) Mir sind gute Freunde wichtig (множина: sind). Und dir? (А для тебе?) Wie wichtig ist dir Mode? (Наскільки для тебе важлива мода?) – Sehr wichtig. Das ist mir auch wichtig, aber nicht sehr wichtig. Teure Kleidung ist mir überhaupt nicht wichtig. (… для мене зовсім не важливий.) Ступені: wichtig – noch wichtiger – am wichtigsten.',
          'Bir şeyin ne kadar önemli olduğunu söylemek: Mir ist ein sicherer Arbeitsplatz wichtig. (Benim için güvenli bir iş önemli.) Mir sind gute Freunde wichtig (çoğul: sind). Und dir? (Ya senin için?) Wie wichtig ist dir Mode? (Moda senin için ne kadar önemli?) – Sehr wichtig. Das ist mir auch wichtig, aber nicht sehr wichtig. Teure Kleidung ist mir überhaupt nicht wichtig. (… benim için hiç önemli değil.) Dereceler: wichtig – noch wichtiger – am wichtigsten.',
        ],
        hint: ['Mir ist … wichtig (eine Sache). Mir sind … wichtig (Plural). überhaupt nicht = gar nicht.', 'Mir ist … wichtig (one thing). Mir sind … wichtig (plural). überhaupt nicht = not at all.', 'Mir ist … wichtig (одна вещь). Mir sind … wichtig (множественное число). überhaupt nicht = совсем не.', 'Mir ist … wichtig (одна річ). Mir sind … wichtig (множина). überhaupt nicht = зовсім не.', 'Mir ist … wichtig (tek şey). Mir sind … wichtig (çoğul). überhaupt nicht = hiç.'],
      },
      ex: [
        mc('K3', 'überhaupt nicht wichtig', I.react, '„Wie wichtig ist dir Mode?“ – Mode interessiert dich gar nicht.', ['Mode ist mir überhaupt nicht wichtig.', 'Mode ist mir am wichtigsten.', 'Mir ist Mode sehr wichtig.'],
          ['“How important is fashion to you?” – You are not interested in fashion at all.', '«Насколько для тебя важна мода?» – Мода вас совсем не интересует.', '«Наскільки для тебе важлива мода?» – Мода вас зовсім не цікавить.', '“Moda senin için ne kadar önemli?” – Moda sizi hiç ilgilendirmiyor.']),
        mc('K3', 'Mir sind … wichtig', I.choose, 'Mir … gute Freunde wichtig.', ['sind', 'ist', 'bin'],
          ['Good friends are important to me.', 'Для меня важны хорошие друзья.', 'Для мене важливі добрі друзі.', 'Benim için iyi arkadaşlar önemli.']),
        mc('K3', 'Mir', I.choose, '… ist ein interessanter Beruf wichtig. Und dir?', ['Mir', 'Mich', 'Ich'],
          ['An interesting job is important to me. And to you?', 'Для меня важна интересная профессия. А для тебя?', 'Для мене важлива цікава професія. А для тебе?', 'Benim için ilginç bir meslek önemli. Ya senin için?']),
        mc('K3', 'Wie wichtig ist dir …?', I.situation, 'Du möchtest wissen: Ist Geld für deinen Freund wichtig? Was fragst du?', ['Wie wichtig ist dir Geld?', 'Wie viel Geld hast du?', 'Was kostet das?'],
          ['You want to know: is money important to your friend? What do you ask?', 'Вы хотите узнать, важны ли деньги для вашего друга. Что вы спросите?', 'Ви хочете дізнатися, чи важливі гроші для вашого друга. Що ви запитаєте?', 'Öğrenmek istiyorsunuz: Para arkadaşınız için önemli mi? Ne sorarsınız?']),
        mc('K3', 'überhaupt nicht', I.choose, 'Was bedeutet „überhaupt nicht wichtig“?', ['gar nicht wichtig', 'sehr wichtig', 'ein bisschen wichtig'],
          ['What does “überhaupt nicht wichtig” mean?', 'Что значит «überhaupt nicht wichtig»?', 'Що означає «überhaupt nicht wichtig»?', '“überhaupt nicht wichtig” ne demek?']),
        gap('K3', 'dir', I.pronoun, 'Wie wichtig ist ', ' ein großes Auto, Paul? – Nicht sehr wichtig.', 'dir', ['dich', 'du'],
          ['How important is a big car to you, Paul? – Not very important.', 'Насколько для тебя важна большая машина, Paul? – Не очень важна.', 'Наскільки для тебе важлива велика машина, Paul? – Не дуже важлива.', 'Büyük bir araba senin için ne kadar önemli, Paul? – Çok önemli değil.'], 'du'),
        gap('K3', 'Mir ist … wichtig', I.verb, 'Mir ', ' meine Gesundheit sehr wichtig.', 'ist', ['sind', 'bin'],
          ['My health is very important to me.', 'Для меня очень важно моё здоровье.', 'Для мене дуже важливе моє здоров’я.', 'Sağlığım benim için çok önemli.'], 'sein'),
        gap('K3', 'wichtiger', I.comparison, 'Geld ist mir wichtig, aber meine Familie ist mir noch ', '.', 'wichtiger', ['wichtig', 'wichtigsten'],
          ['Money is important to me, but my family is even more important to me.', 'Деньги для меня важны, но семья ещё важнее.', 'Гроші для мене важливі, але родина ще важливіша.', 'Para benim için önemli ama ailem daha da önemli.'], 'wichtig'),
        gap('K3', 'überhaupt nicht', I.word, 'Teure Uhren sind mir ', ' nicht wichtig. Ich brauche keine.', 'überhaupt', ['sehr', 'viel'],
          ['Expensive watches are not important to me at all. I do not need one.', 'Дорогие часы для меня совсем не важны. Мне они не нужны.', 'Дорогі годинники для мене зовсім не важливі. Мені вони не потрібні.', 'Pahalı saatler benim için hiç önemli değil. İhtiyacım yok.'],
          ['at all', 'вообще, совсем', 'взагалі, зовсім', 'hiç']),
        sb('K3', 'Mir ist … wichtig', I.order, 'Mir / ist / ein sicherer Arbeitsplatz / wichtig.',
          ['A secure job is important to me.', 'Для меня важна надёжная работа.', 'Для мене важлива надійна робота.', 'Benim için güvenli bir iş önemli.'],
          { alt: ['Ein sicherer Arbeitsplatz ist mir wichtig.'] }),
      ],
    },
    {
      title: 'Diese Kette habe ich von …',
      t: ['I got this necklace from …', 'Эту цепочку мне подарил(а) …', 'Цей ланцюжок мені подарував / подарувала …', 'Bu kolyeyi … verdi'],
      card: {
  "id": "p2_gegenstand",
  "rule": "Von einem Gegenstand erzählen: Diesen Ring habe ich von meiner Oma bekommen. Dieses Messer habe ich in der Schweiz gekauft. Diese Kette hat mir mein Mann geschenkt. Er/Es/Sie ist mir besonders wichtig, weil … Er gefällt mir so gut, denn er ist sehr alt. Im Akkusativ: diesen (der), dieses (das), diese (die).",
  "examples": [
    "Diesen Schal hat mir mein Onkel geschenkt.",
    "Dieses Bild habe ich auf dem Flohmarkt gekauft.",
    "Die Uhr ist mir besonders wichtig, weil sie von meinem Opa ist."
  ],
  "highlight": null,
  "t": [
    "Talking about an object: Diesen Ring habe ich von meiner Oma bekommen. (I got this ring from my grandma.) Dieses Messer habe ich in der Schweiz gekauft. Diese Kette hat mir mein Mann geschenkt. (My husband gave me this necklace.) Er/Es/Sie ist mir besonders wichtig, weil … (It is especially important to me because …) Er gefällt mir so gut, denn er ist sehr alt. In the accusative: diesen (der), dieses (das), diese (die).",
    "Как рассказать о предмете: Diesen Ring habe ich von meiner Oma bekommen. (Это кольцо я получил от бабушки.) Dieses Messer habe ich in der Schweiz gekauft. Diese Kette hat mir mein Mann geschenkt. (Эту цепочку мне подарил муж.) Er/Es/Sie ist mir besonders wichtig, weil … (Он/она мне особенно дорог(а), потому что …) Er gefällt mir so gut, denn er ist sehr alt. В Akkusativ: diesen (der), dieses (das), diese (die).",
    "Як розповісти про предмет: Diesen Ring habe ich von meiner Oma bekommen. (Цей перстень я отримав від бабусі.) Dieses Messer habe ich in der Schweiz gekauft. Diese Kette hat mir mein Mann geschenkt. (Цей ланцюжок мені подарував чоловік.) Er/Es/Sie ist mir besonders wichtig, weil … (Він/вона мені особливо дорогий/дорога, бо …) Er gefällt mir so gut, denn er ist sehr alt. В Akkusativ: diesen (der), dieses (das), diese (die).",
    "Bir eşyayı anlatmak: Diesen Ring habe ich von meiner Oma bekommen. (Bu yüzüğü büyükannemden aldım.) Dieses Messer habe ich in der Schweiz gekauft. Diese Kette hat mir mein Mann geschenkt. (Bu kolyeyi bana kocam hediye etti.) Er/Es/Sie ist mir besonders wichtig, weil … (Benim için özellikle önemli, çünkü …) Er gefällt mir so gut, denn er ist sehr alt. Akkusativ’de: diesen (der), dieses (das), diese (die)."
  ],
  "hint": [
    "der → diesen (Akkusativ), das → dieses, die → diese. von + Dativ: von meiner Oma, von meinem Opa.",
    "der → diesen (accusative), das → dieses, die → diese. von + dative: von meiner Oma, von meinem Opa.",
    "der → diesen (Akkusativ), das → dieses, die → diese. von + Dativ (от кого): von meiner Oma, von meinem Opa.",
    "der → diesen (Akkusativ), das → dieses, die → diese. von + Dativ (від кого): von meiner Oma, von meinem Opa.",
    "der → diesen (Akkusativ), das → dieses, die → diese. von + Dativ (kimden): von meiner Oma, von meinem Opa."
  ]
},
      ex: [
        mc('K4', 'Diesen', I.choose, '… Ring habe ich von meiner Mutter bekommen.', ['Diesen', 'Dieser', 'Dieses'],
          ['I got this ring from my mother.', 'Это кольцо я получил от мамы.', 'Цей перстень я отримав від мами.', 'Bu yüzüğü annemden aldım.']),
        mc('K4', 'Diese', I.choose, '… Kette hat mir meine Schwester geschenkt.', ['Diese', 'Diesen', 'Dieses'],
          ['My sister gave me this necklace.', 'Эту цепочку мне подарила сестра.', 'Цей ланцюжок мені подарувала сестра.', 'Bu kolyeyi bana kız kardeşim hediye etti.']),
        mc('K4', 'Woher?', I.react, '„Woher hast du dieses schöne Messer?“', ['Das habe ich in der Schweiz gekauft.', 'Das ist mir nicht wichtig.', 'Das ist aus Metall.'],
          ['“Where did you get this lovely knife?”', '«Откуда у тебя этот красивый нож?»', '«Звідки в тебе цей гарний ніж?»', '“Bu güzel bıçağı nereden aldın?”']),
        mc('K4', 'besonders wichtig, weil …', I.situation, 'Du zeigst eine alte Uhr von deinem Opa. Sie bedeutet dir viel. Was sagst du?', ['Diese Uhr ist mir besonders wichtig, weil sie von meinem Opa ist.', 'Diese Uhr ist mir überhaupt nicht wichtig.', 'Diese Uhr möchte ich verkaufen.'],
          ['You are showing an old watch from your grandad. It means a lot to you. What do you say?', 'Вы показываете старые часы от дедушки. Они много для вас значат. Что вы скажете?', 'Ви показуєте старий годинник від дідуся. Він багато для вас означає. Що ви скажете?', 'Dedenizden kalma eski bir saati gösteriyorsunuz. Sizin için çok şey ifade ediyor. Ne dersiniz?']),
        mc("K4", "Den hat mir … geschenkt.", I.sentence, "Milan erzählt von seinem Schal.", ["Den hat mir mein Onkel geschenkt.","Der hat mir mein Onkel geschenkt.","Den hat mein Onkel mir geschenken."], ["Milan is talking about his scarf.","Milan рассказывает о своём шарфе.","Milan розповідає про свій шарф.","Milan atkısını anlatıyor."], {"c":"p2_gegenstand","sitovOptionOrder":["Der hat mir mein Onkel geschenkt.","Den hat mein Onkel mir geschenken.","Den hat mir mein Onkel geschenkt."]}),
        gap('K4', 'Diesen', I.form, '', ' Rucksack habe ich in Italien gekauft.', 'Diesen', ['Dieser', 'Dieses'],
          ['I bought this rucksack in Italy.', 'Этот рюкзак я купил в Италии.', 'Цей рюкзак я купив в Італії.', 'Bu sırt çantasını İtalya’da aldım.'], 'dieser'),
        gap('K4', 'bekommen', I.participle, 'Die Kerze habe ich von einer Freundin ', '.', 'bekommen', ['gebekommt', 'bekommt'],
          ['I got the candle from a friend.', 'Свечу я получил от подруги.', 'Свічку я отримав від подруги.', 'Mumu bir arkadaşımdan aldım.'],
          ['got, received', 'получил', 'отримав', 'aldım']),
        gap('K4', 'weil', I.conjunction, 'Der Ring ist mir wichtig, ', ' er von meiner Oma ist.', 'weil', ['denn', 'aber'],
          ['The ring is important to me because it is from my grandma.', 'Это кольцо мне дорого, потому что оно от бабушки.', 'Цей перстень мені дорогий, бо він від бабусі.', 'Yüzük benim için önemli, çünkü büyükannemden.'], 'weil / denn / aber'),
        gap('K4', 'es', I.pronoun, 'Das Buch ist toll. Meine Lehrerin hat ', ' mir geschenkt.', 'es', ['ihn', 'sie'],
          ['The book is great. My teacher gave it to me.', 'Книга отличная. Мне её подарила учительница.', 'Книжка чудова. Мені її подарувала вчителька.', 'Kitap harika. Onu bana öğretmenim hediye etti.'], 'das Buch'),
        sb('K4', '… hat mir … geschenkt.', I.order, 'Diese Tasche / hat / mir / mein Bruder / geschenkt.',
          ['My brother gave me this bag.', 'Эту сумку мне подарил брат.', 'Цю сумку мені подарував брат.', 'Bu çantayı bana erkek kardeşim hediye etti.'],
          { alt: ['Mein Bruder hat mir diese Tasche geschenkt.'] }),
      ],
    },
    {
      title: 'Kleinanzeigen',
      t: ['Small ads', 'Объявления', 'Оголошення', 'Küçük ilanlar'],
      card: {
        id: 'p2_anzeigen',
        rule: 'Kleinanzeigen verstehen: In Anzeigen fehlen oft Wörter. Verkaufe … = Ich verkaufe … Suche … = Ich suche … Biete … = Ich biete … Wichtige Wörter: neu, gebraucht (nicht neu), in gutem Zustand (nicht kaputt), günstig (billig), Abholung (man holt die Sache selbst), Versand (man schickt die Sache mit der Post), VB = Verhandlungsbasis (über den Preis kann man sprechen).',
        examples: ['Verkaufe eine neue Salatschüssel aus Plastik.', 'Suche gebrauchtes Fahrrad, bis 100 Euro.', 'Nur Abholung, kein Versand.'],
        highlight: null,
        t: [
          'Understanding small ads: words are often left out in ads. Verkaufe … = Ich verkaufe … (for sale) Suche … = Ich suche … (wanted) Biete … = Ich biete … (I offer) Important words: neu (new), gebraucht (second-hand, not new), in gutem Zustand (in good condition, not broken), günstig (cheap), Abholung (collection: you fetch the item yourself), Versand (postage: the item is sent by post), VB = Verhandlungsbasis (the price is negotiable).',
          'Как понимать объявления: в объявлениях часто пропускают слова. Verkaufe … = Ich verkaufe … (продаю) Suche … = Ich suche … (ищу) Biete … = Ich biete … (предлагаю) Важные слова: neu (новый), gebraucht (подержанный, не новый), in gutem Zustand (в хорошем состоянии, не сломан), günstig (недорого), Abholung (самовывоз: вещь забирают сами), Versand (доставка: вещь отправляют почтой), VB = Verhandlungsbasis (цена договорная).',
          'Як розуміти оголошення: в оголошеннях часто пропускають слова. Verkaufe … = Ich verkaufe … (продаю) Suche … = Ich suche … (шукаю) Biete … = Ich biete … (пропоную) Важливі слова: neu (новий), gebraucht (уживаний, не новий), in gutem Zustand (у доброму стані, не зламаний), günstig (недорого), Abholung (самовивіз: річ забирають самі), Versand (доставка: річ надсилають поштою), VB = Verhandlungsbasis (ціна договірна).',
          'Küçük ilanları anlamak: İlanlarda çoğu zaman kelimeler atlanır. Verkaufe … = Ich verkaufe … (satıyorum) Suche … = Ich suche … (arıyorum) Biete … = Ich biete … (sunuyorum) Önemli kelimeler: neu (yeni), gebraucht (ikinci el, yeni değil), in gutem Zustand (iyi durumda, bozuk değil), günstig (uygun fiyatlı), Abholung (elden teslim: eşyayı kendiniz alırsınız), Versand (kargo: eşya postayla gönderilir), VB = Verhandlungsbasis (fiyatta pazarlık payı var).',
        ],
        hint: ['Verkaufe = jemand möchte Geld für die Sache. Suche = jemand möchte die Sache haben. gebraucht = nicht neu.', 'Verkaufe = someone wants money for the item. Suche = someone wants to have the item. gebraucht = not new.', 'Verkaufe = кто-то хочет получить за вещь деньги. Suche = кто-то хочет получить вещь. gebraucht = не новый.', 'Verkaufe = хтось хоче отримати за річ гроші. Suche = хтось хоче отримати річ. gebraucht = не новий.', 'Verkaufe = biri eşya için para istiyor. Suche = biri eşyayı almak istiyor. gebraucht = yeni değil.'],
      },
      ex: [
        mc('Z1', 'Preis', I.read, `${SCHUESSEL} Was kostet die Salatschüssel?`, ['15 Euro.', 'Nichts.', '18 Euro.'],
          ['How much is the salad bowl?', 'Сколько стоит салатница?', 'Скільки коштує салатниця?', 'Salata kâsesi ne kadar?']),
        mc('Z1', 'kostenlos', I.read, `${SCHUESSEL} Was bekommt man kostenlos dazu?`, ['Zwei kleine Schüsseln.', 'Eine zweite Salatschüssel.', 'Den Versand.'],
          ['What do you get free with it?', 'Что дают бесплатно в придачу?', 'Що дають безкоштовно на додачу?', 'Yanında ücretsiz ne veriliyor?']),
        mc('Z1', 'Abholung', I.read, `${SCHUESSEL} Wie bekommt man die Schüssel?`, ['Man muss sie in Köln abholen.', 'Sie kommt mit der Post.', 'Der Verkäufer bringt sie.'],
          ['How do you get the bowl?', 'Как можно получить миску?', 'Як можна отримати миску?', 'Kâse nasıl teslim alınıyor?']),
        mc('Z1', 'Suche', I.read, `${KINDERWAGEN} Was möchte die Person?`, ['Sie möchte einen Kinderwagen kaufen.', 'Sie möchte einen Kinderwagen verkaufen.', 'Sie möchte einen Kinderwagen verschenken.'],
          ['What does the person want?', 'Чего хочет этот человек?', 'Чого хоче ця людина?', 'Bu kişi ne istiyor?']),
        mc('Z1', 'nicht älter als', I.read, `${KINDERWAGEN} Wie alt darf der Kinderwagen sein?`, ['Höchstens drei Jahre.', 'Mindestens drei Jahre.', 'Das ist egal.'],
          ['How old may the pram be?', 'Сколько лет может быть коляске?', 'Скільки років може бути візочку?', 'Bebek arabası kaç yaşında olabilir?']),
        mc('Z1', 'antworten', I.read, `${KINDERWAGEN} Wie soll man antworten?`, ['Mit einer E-Mail und einem Foto.', 'Mit einem Anruf ab 18 Uhr.', 'Mit einem Brief.'],
          ['How should you reply?', 'Как нужно ответить?', 'Як треба відповісти?', 'Nasıl cevap verilmeli?']),
        gap('Z1', 'gebraucht', I.word, 'Das Fahrrad ist nicht neu, es ist ', '. Aber es fährt noch gut.', 'gebraucht', ['kostenlos', 'günstig'],
          ['The bike is not new, it is second-hand. But it still rides well.', 'Велосипед не новый, он подержанный. Но ездит ещё хорошо.', 'Велосипед не новий, він уживаний. Але їздить іще добре.', 'Bisiklet yeni değil, ikinci el. Ama hâlâ iyi gidiyor.'],
          ['second-hand, used', 'подержанный', 'уживаний', 'ikinci el']),
      ],
    },
  ],
}

export default path
