import { I, gap, mc } from '../shared.mjs'

const WERDEN = 'wird / werden'
const ELEKTRO = 'Nachricht auf der Mailbox: „Guten Tag, Herr Kaya, hier ist die Firma Elektro Braun. Ihr Fernseher ist repariert. Sie können ihn ab morgen abholen. Wir haben von 9 bis 17 Uhr geöffnet. Auf Wiederhören!“'
const MAMA = 'Nachricht auf der Mailbox: „Hallo Lena, hier ist Mama. Ich stehe vor deiner Tür, aber du bist nicht da. Ich habe dein Päckchen bei der Nachbarin im ersten Stock abgegeben. Ruf mich bitte heute Abend an!“'

/** A2.2 · Pfad 3 · Post und Telefon – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Empfänger', I.choose, 'Wer bekommt den Brief?', ['der Empfänger', 'der Absender', 'der Schalter'],
      ['Who receives the letter?', 'Кто получает письмо?', 'Хто отримує лист?', 'Mektubu kim alır?']),
    mc('W2', 'Mailbox', I.choose, 'Niemand geht ans Telefon. Wo kannst du eine Nachricht sprechen?', ['auf die Mailbox', 'in den Briefkasten', 'auf die Briefmarke'],
      ['Nobody answers the phone. Where can you leave a spoken message?', 'Никто не берёт трубку. Где можно оставить голосовое сообщение?', 'Ніхто не бере слухавку. Де можна залишити голосове повідомлення?', 'Kimse telefonu açmıyor. Nereye sesli mesaj bırakabilirsiniz?']),
    mc('G2', 'Was für ein (das)', I.choose, 'Was für … Paket ist das? – Ein Paket aus der Türkei.', ['ein', 'einen', 'eine'],
      ['What kind of parcel is that? – A parcel from Turkey.', 'Что это за посылка? – Посылка из Турции.', 'Що це за посилка? – Посилка з Туреччини.', 'Bu ne tür bir koli? – Türkiye’den gelen bir koli.']),
    mc('G4', 'dem -en', I.choose, 'Wir fahren mit dem … Auto von meinem Bruder.', ['neuen', 'neue', 'neues'],
      ['We are going in my brother’s new car.', 'Мы едем на новой машине моего брата.', 'Ми їдемо на новій машині мого брата.', 'Erkek kardeşimin yeni arabasıyla gidiyoruz.']),
    mc('G5', 'die Bestellung', I.choose, 'Wie heißt das Nomen zu „bestellen“?', ['die Bestellung', 'der Bestellung', 'das Bestellung'],
      ['What is the noun for “bestellen”?', 'Какое существительное образуется от «bestellen»?', 'Який іменник утворюється від «bestellen»?', '“bestellen” fiilinin ismi nedir?']),
    mc('K1', 'Zollerklärung', I.situation, 'Du arbeitest am Schalter. Eine Kundin will ein Paket nach Brasilien schicken. Was sagst du?', ['Bitte füllen Sie diese Zollerklärung aus.', 'Bitte holen Sie Ihren Ausweis ab.', 'Was für Briefmarken möchten Sie?'],
      ['You work at the counter. A customer wants to send a parcel to Brazil. What do you say?', 'Вы работаете за стойкой. Клиентка хочет отправить посылку в Бразилию. Что вы скажете?', 'Ви працюєте за стійкою. Клієнтка хоче надіслати посилку до Бразилії. Що ви скажете?', 'Gişede çalışıyorsunuz. Bir müşteri Brezilya’ya koli göndermek istiyor. Ne dersiniz?']),
    mc('K2', 'Das ist erstaunlich!', I.react, '„In Deutschland gibt es mehr Handys als Menschen.“ – Das hast du nicht gewusst.', ['Das ist erstaunlich!', 'Das überrascht mich nicht.', 'Das weiß ich schon lange.'],
      ['“In Germany there are more mobiles than people.” – You did not know that.', '«В Германии мобильных телефонов больше, чем людей.» – Вы этого не знали.', '«У Німеччині мобільних телефонів більше, ніж людей.» – Ви цього не знали.', '“Almanya’da insandan çok cep telefonu var.” – Bunu bilmiyordunuz.']),
    mc('K4', 'Gute Besserung', I.choose, 'Deine Nachbarin hat sich das Bein gebrochen. Was schreibst du ihr?', ['Gute Besserung!', 'Viel Spaß!', 'Guten Flug!'],
      ['Your neighbour has broken her leg. What do you write to her?', 'Ваша соседка сломала ногу. Что вы ей напишете?', 'Ваша сусідка зламала ногу. Що ви їй напишете?', 'Komşunuz bacağını kırdı. Ona ne yazarsınız?']),
    mc('K5', 'lieber schreiben', I.react, '„Telefonierst du gern?“', ['Nein, ich schreibe lieber eine Nachricht.', 'Ja, ich habe eine Mailbox.', 'Nein, ich bin Postbote.'],
      ['“Do you like talking on the phone?”', '«Ты любишь разговаривать по телефону?»', '«Ти любиш розмовляти телефоном?»', '“Telefonla konuşmayı sever misin?”']),
    mc('Z1', 'Was ist passiert?', I.read, `${ELEKTRO} Was ist mit dem Fernseher?`, ['Er ist fertig.', 'Er ist noch kaputt.', 'Er ist verkauft.'],
      ['What about the TV?', 'Что с телевизором?', 'Що з телевізором?', 'Televizyonun durumu ne?']),
    gap('G1', 'wird', I.verb, 'Die Post ', ' um 18 Uhr geschlossen.', 'wird', ['werden', 'wirst'],
      ['The post office is closed at 6 pm.', 'Почту закрывают в 18 часов.', 'Пошту зачиняють о 18 годині.', 'Postane saat 18’de kapatılır.'], WERDEN),
    gap('G3', 'den -en', I.ending, 'Ich nehme den ', ' Schal, nicht den blauen.', 'roten', ['rote', 'roter'],
      ['I will take the red scarf, not the blue one.', 'Я возьму красный шарф, а не синий.', 'Я візьму червоний шарф, а не синій.', 'Mavi olanı değil, kırmızı atkıyı alıyorum.'], 'rot'),
    gap('K3', 'Es tut mir leid', I.verb, 'Es ', ' mir sehr leid, dass ich den Termin vergessen habe.', 'tut', ['tue', 'macht'],
      ['I am very sorry that I forgot the appointment.', 'Мне очень жаль, что я забыл о встрече.', 'Мені дуже шкода, що я забув про зустріч.', 'Randevuyu unuttuğum için çok üzgünüm.'], 'tun'),
  ],
  size: 13,
  test: [
    mc('W1', 'Absender', I.choose, 'Auf dem Umschlag stehen oben links dein Name und deine Adresse. Du bist …', ['der Absender', 'der Empfänger', 'der Schalter'],
      ['Your name and address are at the top left of the envelope. You are …', 'На конверте вверху слева стоят ваше имя и адрес. Вы …', 'На конверті вгорі ліворуч стоять ваше ім’я й адреса. Ви …', 'Zarfın sol üstünde adınız ve adresiniz yazıyor. Siz …']),
    mc('W2', 'soziales Netzwerk', I.choose, 'Was ist ein soziales Netzwerk?', ['eine Seite im Internet, auf der man Kontakt zu Freunden hat', 'ein Telefon ohne Kabel', 'ein Brief mit Unterschrift'],
      ['What is a social network?', 'Что такое социальная сеть?', 'Що таке соціальна мережа?', 'Sosyal ağ nedir?']),
    mc('G1', 'werden (Plural)', I.choose, 'In dieser Firma … Autos gebaut.', ['werden', 'wird', 'haben'],
      ['Cars are built in this company.', 'На этом предприятии собирают автомобили.', 'На цьому підприємстві складають автомобілі.', 'Bu şirkette araba üretilir.']),
    mc('G1', 'Aktiv → Passiv', I.choose, 'Wie heißt der Satz im Passiv? „Man schließt das Büro um 17 Uhr.“', ['Das Büro wird um 17 Uhr geschlossen.', 'Das Büro wird um 17 Uhr schließen.', 'Das Büro hat um 17 Uhr geschlossen.'],
      ['What is the sentence in the passive? “The office is closed at 5 pm.”', 'Как будет это предложение в Passiv? «Офис закрывают в 17 часов.»', 'Як буде це речення в Passiv? «Офіс зачиняють о 17 годині.»', 'Bu cümle Passiv’de nasıl olur? “Ofis saat 17’de kapatılır.”']),
    mc('G2', 'Was für einen (der)', I.choose, 'Was für … Schal suchst du? – Einen warmen.', ['einen', 'ein', 'eine'],
      ['What kind of scarf are you looking for? – A warm one.', 'Какой шарф ты ищешь? – Тёплый.', 'Який шарф ти шукаєш? – Теплий.', 'Ne tür bir atkı arıyorsun? – Sıcak tutan bir atkı.']),
    mc('G3', 'die -e', I.choose, 'Die … Uhr gefällt mir am besten.', ['goldene', 'goldenen', 'goldener'],
      ['I like the gold watch best.', 'Золотые часы нравятся мне больше всего.', 'Золотий годинник подобається мені найбільше.', 'En çok altın saati beğeniyorum.']),
    mc('G3', 'den -en', I.choose, 'Siehst du den … Mann am Schalter?', ['alten', 'alte', 'alter'],
      ['Can you see the old man at the counter?', 'Ты видишь пожилого мужчину у стойки?', 'Ти бачиш літнього чоловіка біля стійки?', 'Gişedeki yaşlı adamı görüyor musun?']),
    mc('G4', 'der -en', I.choose, 'Ich helfe der … Frau mit dem Paket.', ['alten', 'alte', 'alter'],
      ['I am helping the old woman with the parcel.', 'Я помогаю пожилой женщине с посылкой.', 'Я допомагаю літній жінці з посилкою.', 'Yaşlı kadına koliyi taşımasında yardım ediyorum.']),
    mc('G5', 'unwichtig', I.choose, 'Was ist das Gegenteil von „wichtig“?', ['unwichtig', 'wichtiglos', 'nichtwichtig'],
      ['What is the opposite of “wichtig”?', 'Какое слово противоположно по значению слову «wichtig»?', 'Яке слово протилежне за значенням слову «wichtig»?', '“wichtig” kelimesinin zıt anlamlısı nedir?']),
    mc('K1', 'als Einschreiben', I.react, '„Ich möchte diesen Brief ganz sicher verschicken.“ – Du arbeitest am Schalter.', ['Dann senden Sie ihn am besten als Einschreiben.', 'Dann holen Sie ihn morgen ab.', 'Dann füllen Sie Ihren Ausweis aus.'],
      ['“I want to send this letter really safely.” – You work at the counter.', '«Я хочу отправить это письмо совсем надёжно.» – Вы работаете за стойкой.', '«Я хочу надіслати цей лист цілком надійно.» – Ви працюєте за стійкою.', '“Bu mektubu çok güvenli göndermek istiyorum.” – Gişede çalışıyorsunuz.']),
    mc('K2', 'Erstaunen', I.choose, 'Mit welchem Satz zeigst du Erstaunen?', ['Das habe ich nicht gedacht!', 'Das habe ich gewusst.', 'Das ist mir egal.'],
      ['Which sentence do you use to show surprise?', 'Каким предложением вы выражаете удивление?', 'Яким реченням ви висловлюєте подив?', 'Hangi cümleyle şaşkınlığınızı gösterirsiniz?']),
    mc('K3', 'sich entschuldigen', I.situation, 'Du hast einen Termin beim Friseur vergessen. Was sprichst du auf die Mailbox?', ['Entschuldigen Sie bitte! Ich habe den Termin leider vergessen.', 'Vielen Dank für den Termin.', 'Alles Gute für den Termin!'],
      ['You forgot an appointment at the hairdresser’s. What message do you leave on the voicemail?', 'Вы забыли о записи к парикмахеру. Что вы скажете на голосовую почту?', 'Ви забули про запис до перукаря. Що ви скажете на голосову пошту?', 'Kuaför randevunuzu unuttunuz. Sesli mesaja ne söylersiniz?']),
    mc('K4', 'Alles Gute', I.choose, 'Deine Freundin hat morgen eine wichtige Prüfung. Was schreibst du?', ['Alles Gute für morgen!', 'Gute Besserung für morgen!', 'Vielen Dank für morgen!'],
      ['Your friend has an important exam tomorrow. What do you write?', 'У вашей подруги завтра важный экзамен. Что вы напишете?', 'У вашої подруги завтра важливий іспит. Що ви напишете?', 'Arkadaşınızın yarın önemli bir sınavı var. Ne yazarsınız?']),
    mc('K5', 'soziales Netzwerk', I.situation, 'Du möchtest wissen, wie dein Kollege mit Freunden in Kontakt bleibt. Was fragst du?', ['Bist du in einem sozialen Netzwerk?', 'Bist du bei der Post?', 'Hast du einen Ausweis?'],
      ['You want to know how your colleague keeps in touch with friends. What do you ask?', 'Вы хотите узнать, как ваш коллега поддерживает связь с друзьями. Что вы спросите?', 'Ви хочете дізнатися, як ваш колега підтримує зв’язок із друзями. Що ви запитаєте?', 'İş arkadaşınızın arkadaşlarıyla nasıl iletişimde kaldığını öğrenmek istiyorsunuz. Ne sorarsınız?']),
    mc('Z1', 'Ab wann?', I.read, `${ELEKTRO} Ab wann kann Herr Kaya den Fernseher abholen?`, ['Ab morgen.', 'Ab heute um 17 Uhr.', 'Erst nächste Woche.'],
      ['From when can Mr Kaya collect the TV?', 'С какого дня господин Kaya может забрать телевизор?', 'Від якого дня пан Kaya може забрати телевізор?', 'Kaya Bey televizyonu ne zamandan itibaren alabilir?']),
    mc('Z1', 'Wo?', I.read, `${MAMA} Wo ist das Päckchen jetzt?`, ['Bei der Nachbarin.', 'Auf der Post.', 'Bei der Mutter.'],
      ['Where is the packet now?', 'Где сейчас пакет?', 'Де зараз пакунок?', 'Paket şimdi nerede?']),
    mc('Z1', 'Was tun?', I.read, `${MAMA} Was soll Lena tun?`, ['Sie soll ihre Mutter am Abend anrufen.', 'Sie soll zur Post gehen.', 'Sie soll die Tür aufmachen.'],
      ['What should Lena do?', 'Что должна сделать Lena?', 'Що має зробити Lena?', 'Lena ne yapmalı?']),
    gap('W1', 'Briefmarke', I.word, 'Ein Brief ins Ausland kostet mehr. Sie brauchen noch eine ', ' für 40 Cent.', 'Briefmarke', ['Postkarte', 'Verpackung'],
      ['A letter abroad costs more. You need another stamp for 40 cents.', 'Письмо за границу стоит дороже. Вам нужна ещё одна марка за 40 центов.', 'Лист за кордон коштує дорожче. Вам потрібна ще одна марка за 40 центів.', 'Yurt dışına mektup daha pahalı. 40 sentlik bir pul daha gerekiyor.'],
      ['stamp', 'почтовая марка', 'поштова марка', 'pul']),
    gap('W2', 'zurückrufen', I.word, 'Ich bin gerade im Kino. Ich rufe dich später ', '.', ['zurück', 'an'], ['aus', 'weg'],
      ['I am at the cinema at the moment. I will call you back later.', 'Я сейчас в кино. Я перезвоню тебе позже.', 'Я зараз у кіно. Я передзвоню тобі пізніше.', 'Şu an sinemadayım. Seni sonra geri ararım.'], 'zurückrufen'),
    gap('G1', 'geliefert', I.participle, 'Der Fernseher wird am Freitag ', '.', 'geliefert', ['liefern', 'geliefern'],
      ['The TV will be delivered on Friday.', 'Телевизор доставят в пятницу.', 'Телевізор доставлять у п’ятницю.', 'Televizyon cuma günü teslim edilecek.'], 'liefern'),
    gap('G2', 'Was für eine (die)', I.article, 'Was für ', ' Tasche hast du gekauft? – Eine kleine aus Leder.', 'eine', ['einen', 'ein'],
      ['What kind of bag did you buy? – A small leather one.', 'Какую сумку ты купил? – Маленькую кожаную.', 'Яку сумку ти купив? – Маленьку шкіряну.', 'Ne tür bir çanta aldın? – Deriden küçük bir çanta.'], 'die Tasche'),
    gap('G3', 'das -e', I.ending, 'Das ', ' Formular ist für Pakete ins Ausland.', 'grüne', ['grünen', 'grünes'],
      ['The green form is for parcels going abroad.', 'Зелёный бланк – для посылок за границу.', 'Зелений бланк – для посилок за кордон.', 'Yeşil form yurt dışına gidecek koliler için.'], 'grün'),
    gap('G4', 'den -en (Plural)', I.ending, 'Wir spielen mit den ', ' Karten.', 'neuen', ['neue', 'neuer'],
      ['We are playing with the new cards.', 'Мы играем новыми картами.', 'Ми граємо новими картами.', 'Yeni kartlarla oynuyoruz.'], 'neu'),
    gap('G4', 'der -en', I.ending, 'Der Schlüssel ist in der ', ' Tasche.', 'schwarzen', ['schwarze', 'schwarzer'],
      ['The key is in the black bag.', 'Ключ лежит в чёрной сумке.', 'Ключ лежить у чорній сумці.', 'Anahtar siyah çantada.'], 'schwarz'),
    gap('G5', 'die Rechnung', I.form, 'Ich habe viel bestellt. Jetzt kommt die ', ': 120 Euro!', 'Rechnung', ['Rechnen', 'Rechner'],
      ['I ordered a lot. Now the bill is coming: 120 euros!', 'Я много заказал. Теперь пришёл счёт: 120 евро!', 'Я багато замовив. Тепер прийшов рахунок: 120 євро!', 'Çok şey sipariş ettim. Şimdi fatura geliyor: 120 avro!'], 'rechnen'),
    gap('K1', 'abholen', I.verb, 'Ich möchte ein Paket ', '. Hier ist die Karte von der Post.', 'abholen', ['ausfüllen', 'anrufen'],
      ['I would like to collect a parcel. Here is the card from the post office.', 'Я хочу забрать посылку. Вот извещение с почты.', 'Я хочу забрати посилку. Ось повідомлення з пошти.', 'Bir koli teslim almak istiyorum. İşte postanenin kartı.'],
      ['collect', 'забрать', 'забрати', 'teslim almak']),
    gap('K2', 'Das finde ich komisch.', I.verb, 'Viele Kinder haben schon ein Handy. Das ', ' ich komisch.', 'finde', ['findet', 'denke'],
      ['Lots of children already have a mobile. I find that strange.', 'У многих детей уже есть мобильный телефон. По-моему, это странно.', 'Багато дітей уже мають мобільний телефон. На мою думку, це дивно.', 'Birçok çocuğun şimdiden cep telefonu var. Bunu tuhaf buluyorum.'], 'finden'),
    gap('K3', 'wollte', I.modalPast, 'Ich ', ' dich anrufen, aber mein Handy war leer.', 'wollte', ['wollten', 'will'],
      ['I wanted to call you, but my mobile was dead.', 'Я хотел тебе позвонить, но мой телефон разрядился.', 'Я хотів тобі зателефонувати, але мій телефон розрядився.', 'Seni aramak istedim ama cep telefonumun şarjı bitmişti.'], 'wollen'),
    gap('K4', 'Vielen Dank', I.word, 'Hallo Mia, vielen ', ' für deine Nachricht!', 'Dank', ['Danke', 'Gruß'],
      ['Hello Mia, many thanks for your message!', 'Привет, Mia, большое спасибо за твоё сообщение!', 'Привіт, Mia, щиро дякую за твоє повідомлення!', 'Merhaba Mia, mesajın için çok teşekkürler!'],
      ['thanks', 'благодарность (большое спасибо)', 'подяка (щиро дякую)', 'teşekkür']),
    gap('K5', 'Briefe schreiben', I.verb, 'Meine Oma hat kein Handy. Sie ', ' lieber Briefe.', 'schreibt', ['schreibe', 'schreiben'],
      ['My grandma has no mobile. She prefers writing letters.', 'У моей бабушки нет мобильного телефона. Она предпочитает писать письма.', 'У моєї бабусі немає мобільного телефона. Вона воліє писати листи.', 'Büyükannemin cep telefonu yok. Mektup yazmayı tercih ediyor.'], 'schreiben'),
  ],
}

export default check
