import { I, gap, mc, sb } from '../shared.mjs'

const WERDEN = 'wird / werden'
const PAUL = 'Nachricht auf der Mailbox: „Hallo Emre, hier ist Paul. Es tut mir leid, ich schaffe es heute nicht zum Training. Mein Zug hat eine Stunde Verspätung. Ich melde mich morgen wieder. Tschüs!“'

/** A2.2 · Pfad 3 · Post und Telefon – Lektionen. Wiederholung und Test: p3-check.mjs */
const path = {
  n: 3,
  slug: 'post-und-telefon',
  title: 'Post und Telefon',
  t: ['Post and telephone', 'Почта и телефон', 'Пошта й телефон', 'Posta ve telefon'],
  objectives: {
    G1: 'Passiv Präsens: wird / werden + Partizip – Das Paket wird abgeholt. Die Briefe werden sortiert. = Man holt das Paket ab.',
    G2: 'Frageartikel Was für ein …?: Was für ein Formular? Was für einen Aufkleber? Was für eine Verpackung? Was für Briefmarken?',
    G3: 'Adjektive nach dem bestimmten Artikel im Nominativ und Akkusativ: der grüne Schal, das alte Handy, die große Uhr – den grünen Schal.',
    G4: 'Adjektive nach dem bestimmten Artikel im Dativ und im Plural: mit dem grünen Schal, mit der großen Uhr, die verschiedenen Karten – immer -en.',
    G5: 'Wortbildung: Verb → Nomen mit -ung (senden → die Sendung) und Adjektive mit un- (interessant → uninteressant).',
    K1: 'Gespräche auf der Post führen: Ich möchte ein Päckchen abholen. Was für eine Möglichkeit gibt es denn da?',
    K2: 'Erstaunen ausdrücken: Ich habe gedacht, dass … Das überrascht mich. Das finde ich komisch. Das ist erstaunlich.',
    K3: 'Sich am Telefon entschuldigen: Es tut mir sehr leid, dass … Ich konnte nicht …, weil … Könnten wir den Termin verschieben?',
    K4: 'Dank und gute Wünsche schreiben: Vielen Dank für deine Nachricht. Alles Gute! Gute Besserung!',
    K5: 'Über Kommunikationsverhalten sprechen: Bist du in einem sozialen Netzwerk? Ich schreibe lieber Nachrichten.',
    Z1: 'Kann-Ziele: Nachrichten auf der Mailbox verstehen.',
    W1: 'Wortschatz: Post.',
    W2: 'Wortschatz: Kommunikation und Telefon.',
  },
  nodes: [
    {
      title: 'Auf der Post',
      t: ['At the post office', 'На почте', 'На пошті', 'Postanede'],
      card: {
        id: 'p3_post',
        rule: 'Auf der Post: der Brief, der Briefumschlag, die Briefmarke, die Postkarte, das Päckchen (klein), das Paket (groß), die Sendung (alles, was man schickt), der Absender (wer schickt), der Empfänger (wer bekommt), das Einschreiben (ein wichtiger Brief mit Unterschrift), der Schalter (dort arbeiten die Leute von der Post), der Briefkasten, der Aufkleber, die Verpackung, das Formular. Verben: schicken, senden, verschicken, abholen, aufgeben (zur Post bringen), ausfüllen.',
        examples: ['Ich gebe das Paket am Schalter auf.', 'Der Absender steht oben links auf dem Umschlag.', 'Auf den Brief kommt eine Briefmarke.'],
        highlight: 'article',
        t: [
          'At the post office: der Brief (letter), der Briefumschlag (envelope), die Briefmarke (stamp), die Postkarte (postcard), das Päckchen (small parcel), das Paket (parcel), die Sendung (item of post: anything you send), der Absender (sender), der Empfänger (recipient), das Einschreiben (registered letter: an important letter that is signed for), der Schalter (counter), der Briefkasten (letterbox), der Aufkleber (sticker, label), die Verpackung (packaging), das Formular (form). Verbs: schicken, senden, verschicken (send), abholen (collect), aufgeben (post: take to the post office), ausfüllen (fill in).',
          'На почте: der Brief (письмо), der Briefumschlag (конверт), die Briefmarke (марка), die Postkarte (открытка), das Päckchen (небольшая посылка), das Paket (посылка), die Sendung (отправление: всё, что отправляют), der Absender (отправитель), der Empfänger (получатель), das Einschreiben (заказное письмо: важное письмо под подпись), der Schalter (окошко, стойка), der Briefkasten (почтовый ящик), der Aufkleber (наклейка), die Verpackung (упаковка), das Formular (бланк). Глаголы: schicken, senden, verschicken (отправлять), abholen (забирать), aufgeben (сдавать на почту), ausfüllen (заполнять).',
          'На пошті: der Brief (лист), der Briefumschlag (конверт), die Briefmarke (марка), die Postkarte (листівка), das Päckchen (невелика посилка), das Paket (посилка), die Sendung (відправлення: усе, що надсилають), der Absender (відправник), der Empfänger (одержувач), das Einschreiben (рекомендований лист: важливий лист під підпис), der Schalter (віконце, стійка), der Briefkasten (поштова скринька), der Aufkleber (наліпка), die Verpackung (упаковка), das Formular (бланк). Дієслова: schicken, senden, verschicken (надсилати), abholen (забирати), aufgeben (здавати на пошту), ausfüllen (заповнювати).',
          'Postanede: der Brief (mektup), der Briefumschlag (zarf), die Briefmarke (pul), die Postkarte (kartpostal), das Päckchen (küçük paket), das Paket (koli), die Sendung (gönderi: gönderilen her şey), der Absender (gönderen), der Empfänger (alıcı), das Einschreiben (taahhütlü mektup: imza karşılığı teslim edilen önemli mektup), der Schalter (gişe), der Briefkasten (posta kutusu), der Aufkleber (etiket), die Verpackung (ambalaj), das Formular (form). Fiiller: schicken, senden, verschicken (göndermek), abholen (teslim almak), aufgeben (postaya vermek), ausfüllen (doldurmak).',
        ],
        hint: ['Absender = schickt. Empfänger = bekommt. Päckchen = klein, Paket = groß. Einschreiben = wichtiger Brief mit Unterschrift.', 'Absender = sends. Empfänger = receives. Päckchen = small, Paket = big. Einschreiben = important letter that is signed for.', 'Absender = отправляет. Empfänger = получает. Päckchen = маленькая, Paket = большая. Einschreiben = важное письмо под подпись.', 'Absender = надсилає. Empfänger = отримує. Päckchen = маленька, Paket = велика. Einschreiben = важливий лист під підпис.', 'Absender = gönderir. Empfänger = alır. Päckchen = küçük, Paket = büyük. Einschreiben = imza karşılığı teslim edilen önemli mektup.'],
      },
      ex: [
        mc('W1', 'Absender', I.choose, 'Wer schickt den Brief?', ['der Absender', 'der Empfänger', 'der Schalter'],
          ['Who sends the letter?', 'Кто отправляет письмо?', 'Хто надсилає лист?', 'Mektubu kim gönderir?']),
        mc('W1', 'Briefmarke', I.choose, 'Was klebt man auf einen Brief?', ['eine Briefmarke', 'ein Formular', 'einen Briefkasten'],
          ['What do you stick on a letter?', 'Что наклеивают на письмо?', 'Що наклеюють на лист?', 'Mektubun üzerine ne yapıştırılır?']),
        mc('W1', 'Einschreiben', I.choose, 'Du schickst einen sehr wichtigen Brief. Der Empfänger muss unterschreiben. Das ist ein …', ['Einschreiben', 'Päckchen', 'Aufkleber'],
          ['You are sending a very important letter. The recipient has to sign for it. That is a …', 'Вы отправляете очень важное письмо. Получатель должен расписаться. Это …', 'Ви надсилаєте дуже важливий лист. Одержувач має розписатися. Це …', 'Çok önemli bir mektup gönderiyorsunuz. Alıcının imza atması gerekiyor. Bu bir …']),
        mc('W1', 'Post', I.odd, 'Drei Wörter passen zur Post, ein Wort nicht.', ['Kerze', 'Briefmarke', 'Paket', 'Absender'], null),
        mc('W1', 'Briefkasten', I.choose, 'Wo wirft man eine Postkarte ein?', ['in den Briefkasten', 'in den Briefumschlag', 'in die Verpackung'],
          ['Where do you post a postcard?', 'Куда опускают открытку?', 'Куди вкидають листівку?', 'Kartpostal nereye atılır?']),
        gap('W1', 'Empfänger', I.word, 'Herr Kaya bekommt das Paket. Er ist der ', '.', 'Empfänger', ['Absender', 'Schalter'],
          ['Mr Kaya receives the parcel. He is the recipient.', 'Господин Kaya получает посылку. Он получатель.', 'Пан Kaya отримує посилку. Він одержувач.', 'Koliyi Kaya Bey alıyor. O alıcı.'],
          ['recipient', 'получатель', 'одержувач', 'alıcı']),
        gap('W1', 'Briefumschlag', I.word, 'Ich stecke den Brief in einen ', ' und klebe ihn zu.', ['Briefumschlag', 'Umschlag'], ['Briefkasten', 'Aufkleber'],
          ['I put the letter in an envelope and seal it.', 'Я кладу письмо в конверт и заклеиваю его.', 'Я кладу лист у конверт і заклеюю його.', 'Mektubu bir zarfa koyup yapıştırıyorum.'],
          ['envelope', 'конверт', 'конверт', 'zarf']),
        gap('W1', 'abholen', I.verb, 'Der Postbote war da, aber ich war nicht zu Hause. Jetzt muss ich das Paket auf der Post ', '.', 'abholen', ['aufgeben', 'ausfüllen'],
          ['The postman came, but I was not at home. Now I have to collect the parcel from the post office.', 'Почтальон приходил, но меня не было дома. Теперь мне нужно забрать посылку на почте.', 'Листоноша приходив, але мене не було вдома. Тепер мені треба забрати посилку на пошті.', 'Postacı geldi ama evde değildim. Şimdi koliyi postaneden almam gerekiyor.'],
          ['collect', 'забрать', 'забрати', 'teslim almak']),
        gap('W1', 'Päckchen', I.word, 'Das ist kein großes Paket. Es ist nur ein kleines ', '.', 'Päckchen', ['Formular', 'Einschreiben'],
          ['That is not a big parcel. It is only a small packet.', 'Это не большая посылка. Это всего лишь маленький пакет.', 'Це не велика посилка. Це лише маленький пакунок.', 'Bu büyük bir koli değil. Sadece küçük bir paket.'],
          ['small parcel', 'небольшая посылка', 'невелика посилка', 'küçük paket']),
        sb('W1', 'schicken', I.order, 'Ich / möchte / diesen Brief / nach Spanien / schicken.',
          ['I would like to send this letter to Spain.', 'Я хочу отправить это письмо в Испанию.', 'Я хочу надіслати цей лист до Іспанії.', 'Bu mektubu İspanya’ya göndermek istiyorum.'],
          { alt: ['Diesen Brief möchte ich nach Spanien schicken.', 'Nach Spanien möchte ich diesen Brief schicken.'] }),
      ],
    },
    {
      title: 'Das wird reingeschrieben.',
      t: ['That is written in here. (passive)', 'Это вписывают сюда. (Passiv)', 'Це вписують сюди. (Passiv)', 'Bu buraya yazılır. (Passiv)'],
      card: {
        id: 'p3_passiv',
        rule: 'Das Passiv im Präsens: werden + Partizip am Satzende. Im Singular: wird – Das Formular wird ausgefüllt. Die Adresse wird hier reingeschrieben. Beim Passiv ist wichtig, was passiert – nicht, wer es macht. Im Aktiv mit man heißt das: Man füllt das Formular aus. Man schreibt die Adresse hier rein.',
        examples: ['Das Paket wird morgen abgeholt.', 'Hier wird die Adresse reingeschrieben.', 'Der Brief wird heute verschickt.'],
        highlight: 'verb',
        t: [
          'The passive in the present tense: werden + past participle at the end of the sentence. In the singular: wird – Das Formular wird ausgefüllt. (The form is filled in.) Die Adresse wird hier reingeschrieben. In the passive what matters is what happens – not who does it. In the active with man you say: Man füllt das Formular aus. Man schreibt die Adresse hier rein.',
          'Passiv в настоящем времени: werden + Partizip II в конце предложения. В единственном числе: wird – Das Formular wird ausgefüllt. (Бланк заполняют.) Die Adresse wird hier reingeschrieben. В Passiv важно, что происходит, а не кто это делает. В активном залоге с man говорят: Man füllt das Formular aus. Man schreibt die Adresse hier rein.',
          'Passiv у теперішньому часі: werden + Partizip II у кінці речення. В однині: wird – Das Formular wird ausgefüllt. (Бланк заповнюють.) Die Adresse wird hier reingeschrieben. У Passiv важливо, що відбувається, а не хто це робить. В активному стані з man кажуть: Man füllt das Formular aus. Man schreibt die Adresse hier rein.',
          'Şimdiki zamanda Passiv: werden + cümlenin sonunda Partizip II. Tekilde: wird – Das Formular wird ausgefüllt. (Form doldurulur.) Die Adresse wird hier reingeschrieben. Passiv’de önemli olan ne olduğudur, kimin yaptığı değil. man ile etken cümle şöyle olur: Man füllt das Formular aus. Man schreibt die Adresse hier rein.',
        ],
        hint: ['Passiv: wird (Position 2) + Partizip (Ende): Das Paket wird abgeholt.', 'Passive: wird (position 2) + past participle (end): Das Paket wird abgeholt.', 'Passiv: wird (второе место) + Partizip II (в конце): Das Paket wird abgeholt.', 'Passiv: wird (друге місце) + Partizip II (у кінці): Das Paket wird abgeholt.', 'Passiv: wird (ikinci sıra) + Partizip II (sonda): Das Paket wird abgeholt.'],
      },
      ex: [
        mc('G1', 'wird + Partizip', I.choose, 'Das Paket … morgen abgeholt.', ['wird', 'ist', 'hat'],
          ['The parcel will be collected tomorrow.', 'Посылку заберут завтра.', 'Посилку заберуть завтра.', 'Koli yarın teslim alınacak.']),
        mc('G1', 'Partizip am Ende', I.choose, 'Die Adresse wird hier …', ['reingeschrieben', 'reinschreiben', 'schreibt rein'],
          ['The address is written in here.', 'Адрес вписывают сюда.', 'Адресу вписують сюди.', 'Adres buraya yazılır.']),
        mc('G1', 'Aktiv → Passiv', I.choose, 'Wie heißt der Satz im Passiv? „Man öffnet die Post um acht Uhr.“', ['Die Post wird um acht Uhr geöffnet.', 'Die Post wird um acht Uhr öffnen.', 'Die Post ist um acht Uhr öffnen.'],
          ['What is the sentence in the passive? “The post office is opened at eight o’clock.”', 'Как будет это предложение в Passiv? «Почту открывают в восемь часов.»', 'Як буде це речення в Passiv? «Пошту відчиняють о восьмій годині.»', 'Bu cümle Passiv’de nasıl olur? “Postane saat sekizde açılır.”']),
        mc('G1', 'Passiv = man', I.choose, 'Was bedeutet „Das Formular wird ausgefüllt“?', ['Man füllt das Formular aus.', 'Das Formular füllt etwas aus.', 'Man hat kein Formular.'],
          ['What does “Das Formular wird ausgefüllt” mean?', 'Что значит «Das Formular wird ausgefüllt»?', 'Що означає «Das Formular wird ausgefüllt»?', '“Das Formular wird ausgefüllt” ne demek?']),
        mc('G1', 'Wortstellung', I.sentence, 'Die Frau am Schalter zeigt auf das Formular.', ['Hier wird der Absender reingeschrieben.', 'Hier wird reingeschrieben der Absender.', 'Hier der Absender wird reingeschrieben.'],
          ['The woman at the counter is pointing to the form.', 'Женщина за стойкой показывает на бланк.', 'Жінка за стійкою показує на бланк.', 'Gişedeki kadın formu gösteriyor.']),
        gap('G1', 'wird', I.verb, 'Der Brief ', ' heute noch verschickt.', 'wird', ['werden', 'wirst'],
          ['The letter will be sent today.', 'Письмо отправят ещё сегодня.', 'Лист надішлють іще сьогодні.', 'Mektup bugün gönderilecek.'], 'werden'),
        gap('G1', 'abgeholt', I.participle, 'Das Päckchen wird am Schalter ', '.', 'abgeholt', ['abholen', 'abgeholen'],
          ['The packet is collected at the counter.', 'Пакет забирают у стойки.', 'Пакунок забирають біля стійки.', 'Paket gişeden teslim alınır.'], 'abholen'),
        gap('G1', 'geschickt', I.participle, 'Die Rechnung wird per Post ', '.', 'geschickt', ['schicken', 'geschicken'],
          ['The bill is sent by post.', 'Счёт отправляют по почте.', 'Рахунок надсилають поштою.', 'Fatura postayla gönderilir.'], 'schicken'),
        gap('G1', 'geschlossen', I.participle, 'Das Fenster wird jeden Abend ', '.', 'geschlossen', ['schließen', 'geschließt'],
          ['The window is closed every evening.', 'Окно закрывают каждый вечер.', 'Вікно зачиняють щовечора.', 'Pencere her akşam kapatılır.'], 'schließen'),
        sb('G1', 'wird … geliefert', I.order, 'Das Paket / wird / morgen / geliefert.',
          ['The parcel will be delivered tomorrow.', 'Посылку доставят завтра.', 'Посилку доставлять завтра.', 'Koli yarın teslim edilecek.'],
          { alt: ['Morgen wird das Paket geliefert.'] }),
      ],
    },
    {
      title: 'Die Pakete werden abgeholt.',
      t: ['The parcels are collected. (passive: plural)', 'Посылки забирают. (Passiv: множественное число)', 'Посилки забирають. (Passiv: множина)', 'Koliler teslim alınır. (Passiv: çoğul)'],
      card: {
        id: 'p3_passiv2',
        rule: 'Passiv im Plural: werden + Partizip – Die Briefe werden sortiert. Die Pakete werden abgeholt. Singular oder Plural? Das Subjekt entscheidet: Der Fernseher wird geliefert. Die Fernseher werden geliefert. In der Frage: Wann wird der Fernseher endlich geliefert? Werden die Pakete heute noch abgeholt? Aktiv mit man: Man sortiert die Briefe.',
        examples: ['Die Briefe werden am Morgen sortiert.', 'Wann wird die Kamera repariert?', 'Hier werden Briefmarken verkauft.'],
        highlight: 'verb',
        t: [
          'The passive in the plural: werden + past participle – Die Briefe werden sortiert. (The letters are sorted.) Die Pakete werden abgeholt. Singular or plural? The subject decides: Der Fernseher wird geliefert. Die Fernseher werden geliefert. In a question: Wann wird der Fernseher endlich geliefert? Werden die Pakete heute noch abgeholt? Active with man: Man sortiert die Briefe.',
          'Passiv во множественном числе: werden + Partizip II – Die Briefe werden sortiert. (Письма сортируют.) Die Pakete werden abgeholt. Единственное или множественное число? Это определяет подлежащее: Der Fernseher wird geliefert. Die Fernseher werden geliefert. В вопросе: Wann wird der Fernseher endlich geliefert? Werden die Pakete heute noch abgeholt? Активный залог с man: Man sortiert die Briefe.',
          'Passiv у множині: werden + Partizip II – Die Briefe werden sortiert. (Листи сортують.) Die Pakete werden abgeholt. Однина чи множина? Це визначає підмет: Der Fernseher wird geliefert. Die Fernseher werden geliefert. У запитанні: Wann wird der Fernseher endlich geliefert? Werden die Pakete heute noch abgeholt? Активний стан із man: Man sortiert die Briefe.',
          'Çoğulda Passiv: werden + Partizip II – Die Briefe werden sortiert. (Mektuplar ayrılır.) Die Pakete werden abgeholt. Tekil mi, çoğul mu? Buna özne karar verir: Der Fernseher wird geliefert. Die Fernseher werden geliefert. Soruda: Wann wird der Fernseher endlich geliefert? Werden die Pakete heute noch abgeholt? man ile etken cümle: Man sortiert die Briefe.',
        ],
        hint: ['Ein Ding → wird. Mehrere Dinge → werden. Das Partizip steht am Ende.', 'One thing → wird. Several things → werden. The participle goes at the end.', 'Один предмет → wird. Несколько предметов → werden. Partizip II стоит в конце.', 'Один предмет → wird. Кілька предметів → werden. Partizip II стоїть у кінці.', 'Tek şey → wird. Birden çok şey → werden. Partizip II sonda durur.'],
      },
      ex: [
        mc('G1', 'werden (Plural)', I.choose, 'Die Briefe … am Morgen sortiert.', ['werden', 'wird', 'werdet'],
          ['The letters are sorted in the morning.', 'Письма сортируют утром.', 'Листи сортують уранці.', 'Mektuplar sabah ayrılır.']),
        mc('G1', 'wird (Singular)', I.choose, 'Wann … der Fernseher endlich geliefert?', ['wird', 'werden', 'wirst'],
          ['When will the TV finally be delivered?', 'Когда же наконец доставят телевизор?', 'Коли ж нарешті доставлять телевізор?', 'Televizyon nihayet ne zaman teslim edilecek?']),
        mc('G1', 'werden (Plural)', I.choose, 'Hier … Briefmarken verkauft.', ['werden', 'wird', 'sind'],
          ['Stamps are sold here.', 'Здесь продают марки.', 'Тут продають марки.', 'Burada pul satılır.']),
        mc('G1', 'Aktiv → Passiv', I.choose, 'Wie heißt der Satz im Passiv? „Man repariert die Kameras in der Werkstatt.“', ['Die Kameras werden in der Werkstatt repariert.', 'Die Kameras wird in der Werkstatt repariert.', 'Die Kameras werden in der Werkstatt reparieren.'],
          ['What is the sentence in the passive? “The cameras are repaired in the workshop.”', 'Как будет это предложение в Passiv? «Камеры ремонтируют в мастерской.»', 'Як буде це речення в Passiv? «Камери ремонтують у майстерні.»', 'Bu cümle Passiv’de nasıl olur? “Kameralar atölyede tamir edilir.”']),
        mc('G1', 'Passiv → Aktiv', I.choose, 'Wie heißt der Satz im Aktiv? „Die Rechnungen werden per E-Mail geschickt.“', ['Man schickt die Rechnungen per E-Mail.', 'Man wird die Rechnungen per E-Mail.', 'Die Rechnungen schicken per E-Mail.'],
          ['What is the sentence in the active? “The bills are sent by e-mail.”', 'Как будет это предложение в активном залоге? «Счета отправляют по электронной почте.»', 'Як буде це речення в активному стані? «Рахунки надсилають електронною поштою.»', 'Bu cümle etken çatıda nasıl olur? “Faturalar e-postayla gönderilir.”']),
        gap('G1', 'werden (Plural)', I.verb, 'Die Pakete ', ' um 17 Uhr abgeholt.', 'werden', ['wird', 'werdet'],
          ['The parcels are collected at 5 pm.', 'Посылки забирают в 17 часов.', 'Посилки забирають о 17 годині.', 'Koliler saat 17’de teslim alınır.'], WERDEN),
        gap('G1', 'wird (Singular)', I.verb, 'Wann ', ' die Rechnung geschickt?', 'wird', ['werden', 'werdet'],
          ['When will the bill be sent?', 'Когда отправят счёт?', 'Коли надішлють рахунок?', 'Fatura ne zaman gönderilecek?'], WERDEN),
        gap('G1', 'repariert', I.participle, 'In dieser Firma werden Handys ', '.', 'repariert', ['gerepariert', 'reparieren'],
          ['Mobile phones are repaired in this company.', 'В этой фирме ремонтируют телефоны.', 'У цій фірмі ремонтують телефони.', 'Bu şirkette cep telefonları tamir edilir.'], 'reparieren'),
        gap('G1', 'ausgefüllt', I.participle, 'Die Formulare werden am Schalter ', '.', 'ausgefüllt', ['ausfüllen', 'ausgefüllen'],
          ['The forms are filled in at the counter.', 'Бланки заполняют у стойки.', 'Бланки заповнюють біля стійки.', 'Formlar gişede doldurulur.'], 'ausfüllen'),
        sb('G1', 'Frage im Passiv', I.question, 'Wann / wird / der Fernseher / geliefert?',
          ['When will the TV be delivered?', 'Когда доставят телевизор?', 'Коли доставлять телевізор?', 'Televizyon ne zaman teslim edilecek?']),
      ],
    },
    {
      title: 'Was für ein …?',
      t: ['What kind of …?', 'Какой …? Что за …?', 'Який …? Що за …?', 'Ne tür bir …?'],
      card: {
        id: 'p3_wasfuer',
        rule: 'Mit Was für ein …? fragt man nach der Art oder Sorte. Nominativ: Was für ein Aufkleber ist das? Was für ein Formular? Was für eine Verpackung? Akkusativ: Was für einen Aufkleber brauchen Sie? Was für ein Formular? Was für eine Verpackung? Im Plural ohne Artikel: Was für Briefmarken möchten Sie? Die Antwort hat oft ein Adjektiv: Einen großen. Eine stabile. Schöne, bitte.',
        examples: ['Was für ein Paket ist das? – Ein kleines.', 'Was für einen Brief möchten Sie schicken? – Einen wichtigen.', 'Was für Briefmarken möchten Sie?'],
        highlight: 'article',
        t: [
          'With Was für ein …? (what kind of …?) you ask about the type or sort. Nominative: Was für ein Aufkleber ist das? Was für ein Formular? Was für eine Verpackung? Accusative: Was für einen Aufkleber brauchen Sie? Was für ein Formular? Was für eine Verpackung? In the plural without an article: Was für Briefmarken möchten Sie? The answer often has an adjective: Einen großen. Eine stabile. Schöne, bitte.',
          'Вопросом Was für ein …? (какой? что за?) спрашивают о виде или сорте. Nominativ: Was für ein Aufkleber ist das? Was für ein Formular? Was für eine Verpackung? Akkusativ: Was für einen Aufkleber brauchen Sie? Was für ein Formular? Was für eine Verpackung? Во множественном числе без артикля: Was für Briefmarken möchten Sie? В ответе часто стоит прилагательное: Einen großen. Eine stabile. Schöne, bitte.',
          'Запитанням Was für ein …? (який? що за?) питають про вид або сорт. Nominativ: Was für ein Aufkleber ist das? Was für ein Formular? Was für eine Verpackung? Akkusativ: Was für einen Aufkleber brauchen Sie? Was für ein Formular? Was für eine Verpackung? У множині без артикля: Was für Briefmarken möchten Sie? У відповіді часто стоїть прикметник: Einen großen. Eine stabile. Schöne, bitte.',
          'Was für ein …? (ne tür bir …?) ile türü ya da çeşidi sorulur. Nominativ: Was für ein Aufkleber ist das? Was für ein Formular? Was für eine Verpackung? Akkusativ: Was für einen Aufkleber brauchen Sie? Was für ein Formular? Was für eine Verpackung? Çoğulda artikelsiz: Was für Briefmarken möchten Sie? Cevapta çoğu zaman bir sıfat bulunur: Einen großen. Eine stabile. Schöne, bitte.',
        ],
        hint: ['Was für + ein/einen (der), ein (das), eine (die), Plural ohne Artikel. Nach brauchen, möchten, haben: Akkusativ.', 'Was für + ein/einen (der), ein (das), eine (die), plural without an article. After brauchen, möchten, haben: accusative.', 'Was für + ein/einen (der), ein (das), eine (die), множественное число без артикля. После brauchen, möchten, haben: Akkusativ.', 'Was für + ein/einen (der), ein (das), eine (die), множина без артикля. Після brauchen, möchten, haben: Akkusativ.', 'Was für + ein/einen (der), ein (das), eine (die), çoğul artikelsiz. brauchen, möchten, haben fiillerinden sonra: Akkusativ.'],
      },
      ex: [
        mc('G2', 'Was für ein (das)', I.choose, 'Was für … Formular brauche ich?', ['ein', 'einen', 'eine'],
          ['What kind of form do I need?', 'Какой бланк мне нужен?', 'Який бланк мені потрібен?', 'Ne tür bir forma ihtiyacım var?']),
        mc('G2', 'Was für einen (der)', I.choose, 'Was für … Aufkleber möchten Sie?', ['einen', 'ein', 'eine'],
          ['What kind of sticker would you like?', 'Какую наклейку вы хотите?', 'Яку наліпку ви хочете?', 'Ne tür bir etiket istersiniz?']),
        mc('G2', 'Was für eine (die)', I.choose, 'Was für … Verpackung nehmen wir?', ['eine', 'einen', 'ein'],
          ['What kind of packaging shall we take?', 'Какую упаковку мы возьмём?', 'Яку упаковку ми візьмемо?', 'Ne tür bir ambalaj alalım?']),
        mc('G2', 'Plural ohne Artikel', I.choose, 'Was für … möchten Sie? – Sondermarken, bitte.', ['Briefmarken', 'eine Briefmarken', 'einen Briefmarken'],
          ['What kind of stamps would you like? – Special stamps, please.', 'Какие марки вы хотите? – Коллекционные, пожалуйста.', 'Які марки ви хочете? – Колекційні, будь ласка.', 'Ne tür pul istersiniz? – Özel pul lütfen.']),
        mc('G2', 'Frage und Antwort', I.matchQuestion, '„Ein Einschreiben.“', ['Was für einen Brief möchten Sie schicken?', 'Wann möchten Sie den Brief schicken?', 'Wohin möchten Sie den Brief schicken?'],
          ['“A registered letter.”', '«Заказное письмо.»', '«Рекомендований лист.»', '“Taahhütlü bir mektup.”']),
        gap('G2', 'Was für ein (das)', I.article, 'Was für ', ' Handy hast du?', 'ein', ['einen', 'eine'],
          ['What kind of mobile do you have?', 'Какой у тебя телефон?', 'Який у тебе телефон?', 'Ne tür bir cep telefonun var?'], 'das Handy'),
        gap('G2', 'Was für einen (der)', I.article, 'Was für ', ' Umschlag brauchen Sie: groß oder klein?', 'einen', ['ein', 'eine'],
          ['What kind of envelope do you need: big or small?', 'Какой конверт вам нужен: большой или маленький?', 'Який конверт вам потрібен: великий чи маленький?', 'Ne tür bir zarfa ihtiyacınız var: büyük mü, küçük mü?'], 'der Umschlag'),
        gap('G2', 'Was für eine (die)', I.article, 'Was für ', ' Karte schickst du deiner Oma?', 'eine', ['einen', 'ein'],
          ['What kind of card are you sending your grandma?', 'Какую открытку ты отправишь бабушке?', 'Яку листівку ти надішлеш бабусі?', 'Büyükannene ne tür bir kart gönderiyorsun?'], 'die Karte'),
        gap('G2', 'Was für …?', I.word, 'Was ', ' ein Paket ist das? – Ein Paket aus Polen.', 'für', ['von', 'mit'],
          ['What kind of parcel is that? – A parcel from Poland.', 'Что это за посылка? – Посылка из Польши.', 'Що це за посилка? – Посилка з Польщі.', 'Bu ne tür bir koli? – Polonya’dan gelen bir koli.'], 'für / von / mit'),
        sb('G2', 'Was für eine …?', I.question, 'Was für / eine Möglichkeit / gibt / es / da?',
          ['What option is there?', 'Какая здесь есть возможность?', 'Яка тут є можливість?', 'Burada nasıl bir imkân var?']),
      ],
    },
    {
      title: 'der grüne Schal',
      t: ['der grüne Schal (adjectives after der, das, die)', 'der grüne Schal (прилагательные после der, das, die)', 'der grüne Schal (прикметники після der, das, die)', 'der grüne Schal (der, das, die’den sonra sıfatlar)'],
      card: {
        id: 'p3_adj_nomakk',
        rule: 'Adjektive nach der, das, die: Im Nominativ Singular ist die Endung immer -e: der grüne Schal, das alte Handy, die große Uhr. Im Akkusativ ändert sich nur maskulin: den grünen Schal. Neutral und feminin bleiben: das alte Handy, die große Uhr. Im Plural ist die Endung immer -en: die verschiedenen Karten. Genauso nach dieser, dieses, diese.',
        examples: ['Der grüne Schal ist von meiner Oma.', 'Ich nehme den grünen Schal.', 'Das alte Handy funktioniert noch.', 'Die neuen Briefmarken sind schön.'],
        highlight: null,
        t: [
          'Adjectives after der, das, die: in the nominative singular the ending is always -e: der grüne Schal, das alte Handy, die große Uhr. In the accusative only the masculine changes: den grünen Schal. Neuter and feminine stay the same: das alte Handy, die große Uhr. In the plural the ending is always -en: die verschiedenen Karten. The same applies after dieser, dieses, diese.',
          'Прилагательные после der, das, die: в Nominativ единственного числа окончание всегда -e: der grüne Schal, das alte Handy, die große Uhr. В Akkusativ меняется только мужской род: den grünen Schal. Средний и женский род остаются: das alte Handy, die große Uhr. Во множественном числе окончание всегда -en: die verschiedenen Karten. Так же после dieser, dieses, diese.',
          'Прикметники після der, das, die: у Nominativ однини закінчення завжди -e: der grüne Schal, das alte Handy, die große Uhr. В Akkusativ змінюється лише чоловічий рід: den grünen Schal. Середній і жіночий рід залишаються: das alte Handy, die große Uhr. У множині закінчення завжди -en: die verschiedenen Karten. Так само після dieser, dieses, diese.',
          'der, das, die’den sonra sıfatlar: Nominativ tekilde ek her zaman -e olur: der grüne Schal, das alte Handy, die große Uhr. Akkusativ’de yalnızca eril değişir: den grünen Schal. Nötr ve dişil aynı kalır: das alte Handy, die große Uhr. Çoğulda ek her zaman -en olur: die verschiedenen Karten. dieser, dieses, diese sözcüklerinden sonra da aynıdır.',
        ],
        hint: ['Nominativ: der/das/die + -e. Akkusativ: den + -en, das/die + -e. Plural: -en.', 'Nominative: der/das/die + -e. Accusative: den + -en, das/die + -e. Plural: -en.', 'Nominativ: der/das/die + -e. Akkusativ: den + -en, das/die + -e. Множественное число: -en.', 'Nominativ: der/das/die + -e. Akkusativ: den + -en, das/die + -e. Множина: -en.', 'Nominativ: der/das/die + -e. Akkusativ: den + -en, das/die + -e. Çoğul: -en.'],
      },
      ex: [
        mc('G3', 'der -e', I.choose, 'Der … Schal ist von meiner Oma.', ['grüne', 'grüner', 'grünen'],
          ['The green scarf is from my grandma.', 'Зелёный шарф – от моей бабушки.', 'Зелений шарф – від моєї бабусі.', 'Yeşil atkı büyükannemden.']),
        mc('G3', 'das -e', I.choose, 'Das … Handy ist kaputt.', ['alte', 'altes', 'alten'],
          ['The old mobile is broken.', 'Старый телефон сломан.', 'Старий телефон зламаний.', 'Eski cep telefonu bozuk.']),
        mc('G3', 'den -en', I.choose, 'Ich nehme den … Umschlag.', ['großen', 'große', 'großer'],
          ['I will take the big envelope.', 'Я возьму большой конверт.', 'Я візьму великий конверт.', 'Büyük zarfı alıyorum.']),
        mc('G3', 'die -en (Plural)', I.choose, 'Wo sind die … Briefmarken?', ['neuen', 'neue', 'neuer'],
          ['Where are the new stamps?', 'Где новые марки?', 'Де нові марки?', 'Yeni pullar nerede?']),
        mc('G3', 'die -e', I.sentence, 'Welche Uhr gefällt dir?', ['Die große Uhr gefällt mir.', 'Die großen Uhr gefällt mir.', 'Die großer Uhr gefällt mir.'],
          ['Which clock do you like?', 'Какие часы тебе нравятся?', 'Який годинник тобі подобається?', 'Hangi saat hoşuna gidiyor?']),
        gap('G3', 'die -e', I.ending, 'Die ', ' Postkarte ist aus Italien.', 'bunte', ['bunten', 'bunter'],
          ['The colourful postcard is from Italy.', 'Яркая открытка – из Италии.', 'Яскрава листівка – з Італії.', 'Renkli kartpostal İtalya’dan.'], 'bunt'),
        gap('G3', 'den -en', I.ending, 'Hast du den ', ' Brief schon gelesen?', 'langen', ['lange', 'langer'],
          ['Have you read the long letter yet?', 'Ты уже прочитал длинное письмо?', 'Ти вже прочитав довгий лист?', 'Uzun mektubu okudun mu?'], 'lang'),
        gap('G3', 'das -e', I.ending, 'Ich finde das ', ' Paket nicht.', 'kleine', ['kleinen', 'kleines'],
          ['I cannot find the small parcel.', 'Я не могу найти маленькую посылку.', 'Я не можу знайти маленьку посилку.', 'Küçük koliyi bulamıyorum.'], 'klein'),
        gap('G3', 'der -e', I.ending, 'Der ', ' Postbote kommt immer um zehn Uhr.', 'nette', ['netter', 'netten'],
          ['The nice postman always comes at ten o’clock.', 'Приветливый почтальон всегда приходит в десять часов.', 'Привітний листоноша завжди приходить о десятій годині.', 'Cana yakın postacı hep saat onda geliyor.'], 'nett'),
        sb('G3', 'den -en', I.order, 'Ich / kaufe / den / blauen / Schal.',
          ['I am buying the blue scarf.', 'Я покупаю синий шарф.', 'Я купую синій шарф.', 'Mavi atkıyı alıyorum.'],
          { alt: ['Den blauen Schal kaufe ich.'] }),
      ],
    },
    {
      title: 'mit dem grünen Schal',
      t: ['mit dem grünen Schal (dative and plural: -en)', 'mit dem grünen Schal (Dativ и множественное число: -en)', 'mit dem grünen Schal (Dativ і множина: -en)', 'mit dem grünen Schal (Dativ ve çoğul: -en)'],
      card: {
        id: 'p3_adj_dat',
        rule: 'Adjektive nach dem bestimmten Artikel im Dativ: Die Endung ist immer -en. mit dem grünen Schal, mit dem tollen Handy, mit der großen Uhr, mit den verschiedenen Karten. Auch im Plural ist die Endung immer -en: die neuen Nachbarn (Nominativ und Akkusativ), den neuen Nachbarn (Dativ).',
        examples: ['Ich telefoniere mit dem neuen Handy.', 'Das Paket ist von der netten Nachbarin.', 'Er hilft den alten Leuten.'],
        highlight: null,
        t: [
          'Adjectives after the definite article in the dative: the ending is always -en. mit dem grünen Schal, mit dem tollen Handy, mit der großen Uhr, mit den verschiedenen Karten. In the plural the ending is always -en too: die neuen Nachbarn (nominative and accusative), den neuen Nachbarn (dative).',
          'Прилагательные после определённого артикля в Dativ: окончание всегда -en. mit dem grünen Schal, mit dem tollen Handy, mit der großen Uhr, mit den verschiedenen Karten. Во множественном числе окончание тоже всегда -en: die neuen Nachbarn (Nominativ и Akkusativ), den neuen Nachbarn (Dativ).',
          'Прикметники після означеного артикля в Dativ: закінчення завжди -en. mit dem grünen Schal, mit dem tollen Handy, mit der großen Uhr, mit den verschiedenen Karten. У множині закінчення теж завжди -en: die neuen Nachbarn (Nominativ і Akkusativ), den neuen Nachbarn (Dativ).',
          'Belirli artikelden sonra Dativ’de sıfatlar: Ek her zaman -en olur. mit dem grünen Schal, mit dem tollen Handy, mit der großen Uhr, mit den verschiedenen Karten. Çoğulda da ek her zaman -en olur: die neuen Nachbarn (Nominativ ve Akkusativ), den neuen Nachbarn (Dativ).',
        ],
        hint: ['Dativ: dem/der/den + -en. Plural: immer -en.', 'Dative: dem/der/den + -en. Plural: always -en.', 'Dativ: dem/der/den + -en. Множественное число: всегда -en.', 'Dativ: dem/der/den + -en. Множина: завжди -en.', 'Dativ: dem/der/den + -en. Çoğul: her zaman -en.'],
      },
      ex: [
        mc('G4', 'dem -en', I.choose, 'Ich schreibe mit dem … Stift.', ['roten', 'rote', 'roter'],
          ['I am writing with the red pen.', 'Я пишу красной ручкой.', 'Я пишу червоною ручкою.', 'Kırmızı kalemle yazıyorum.']),
        mc('G4', 'der -en', I.choose, 'Das Päckchen ist von der … Kollegin.', ['netten', 'nette', 'netter'],
          ['The packet is from the nice colleague.', 'Пакет – от приятной коллеги.', 'Пакунок – від приємної колеги.', 'Paket cana yakın iş arkadaşından.']),
        mc('G4', 'den -en (Plural)', I.choose, 'Wir sprechen mit den … Nachbarn.', ['neuen', 'neue', 'neuer'],
          ['We are talking to the new neighbours.', 'Мы разговариваем с новыми соседями.', 'Ми розмовляємо з новими сусідами.', 'Yeni komşularla konuşuyoruz.']),
        mc('G4', 'dem -en', I.choose, 'Die Briefmarke klebt auf dem … Umschlag.', ['weißen', 'weiße', 'weißer'],
          ['The stamp is stuck on the white envelope.', 'Марка наклеена на белый конверт.', 'Марка наклеєна на білий конверт.', 'Pul beyaz zarfın üzerinde yapışık.']),
        mc('G4', 'dem -en', I.sentence, 'Mit welchem Handy telefonierst du?', ['Mit dem alten Handy.', 'Mit dem alte Handy.', 'Mit dem altes Handy.'],
          ['Which mobile are you phoning with?', 'С какого телефона ты звонишь?', 'З якого телефона ти дзвониш?', 'Hangi cep telefonuyla arıyorsun?']),
        gap('G4', 'dem -en', I.ending, 'Der Brief liegt in dem ', ' Briefkasten.', 'gelben', ['gelbe', 'gelber'],
          ['The letter is in the yellow letterbox.', 'Письмо лежит в жёлтом почтовом ящике.', 'Лист лежить у жовтій поштовій скриньці.', 'Mektup sarı posta kutusunda.'], 'gelb'),
        gap('G4', 'der -en', I.ending, 'Sie spricht mit der ', ' Frau am Schalter.', 'freundlichen', ['freundliche', 'freundlicher'],
          ['She is talking to the friendly woman at the counter.', 'Она разговаривает с приветливой женщиной за стойкой.', 'Вона розмовляє з привітною жінкою за стійкою.', 'Gişedeki güler yüzlü kadınla konuşuyor.'], 'freundlich'),
        gap('G4', 'die -en (Plural)', I.ending, 'Die ', ' Formulare liegen auf dem Tisch.', 'neuen', ['neue', 'neues'],
          ['The new forms are on the table.', 'Новые бланки лежат на столе.', 'Нові бланки лежать на столі.', 'Yeni formlar masanın üzerinde.'], 'neu'),
        gap('G4', 'den -en (Plural)', I.ending, 'Ich habe von den ', ' Kindern eine Karte bekommen.', 'kleinen', ['kleine', 'kleiner'],
          ['I got a card from the little children.', 'Я получил открытку от малышей.', 'Я отримав листівку від малюків.', 'Küçük çocuklardan bir kart aldım.'], 'klein'),
        sb('G4', 'dem -en', I.order, 'Er / fährt / mit dem / neuen / Fahrrad.',
          ['He is riding the new bike.', 'Он едет на новом велосипеде.', 'Він їде на новому велосипеді.', 'Yeni bisikletle gidiyor.'],
          { alt: ['Mit dem neuen Fahrrad fährt er.'] }),
      ],
    },
    {
      title: 'die Sendung, uninteressant',
      t: ['die Sendung, uninteressant (word formation)', 'die Sendung, uninteressant (словообразование)', 'die Sendung, uninteressant (словотворення)', 'die Sendung, uninteressant (sözcük türetme)'],
      card: {
        id: 'p3_wortbildung',
        rule: 'Wortbildung. Verb → Nomen mit -ung: senden → die Sendung, verpacken → die Verpackung, bestellen → die Bestellung, rechnen → die Rechnung, einladen → die Einladung, entschuldigen → die Entschuldigung, wohnen → die Wohnung. Nomen auf -ung haben immer den Artikel die. Adjektive mit un- bedeuten das Gegenteil: interessant → uninteressant, freundlich → unfreundlich, höflich → unhöflich, wichtig → unwichtig, pünktlich → unpünktlich, glücklich → unglücklich.',
        examples: ['Die Sendung kommt aus Ägypten.', 'Die Verpackung ist kaputt.', 'Der Film war uninteressant.'],
        highlight: 'article',
        t: [
          'Word formation. Verb → noun with -ung: senden → die Sendung (item of post), verpacken → die Verpackung (packaging), bestellen → die Bestellung (order), rechnen → die Rechnung (bill), einladen → die Einladung (invitation), entschuldigen → die Entschuldigung (apology), wohnen → die Wohnung (flat). Nouns ending in -ung always take the article die. Adjectives with un- mean the opposite: interessant → uninteressant, freundlich → unfreundlich, höflich → unhöflich (impolite), wichtig → unwichtig, pünktlich → unpünktlich (unpunctual), glücklich → unglücklich (unhappy).',
          'Словообразование. Глагол → существительное на -ung: senden → die Sendung (отправление), verpacken → die Verpackung (упаковка), bestellen → die Bestellung (заказ), rechnen → die Rechnung (счёт), einladen → die Einladung (приглашение), entschuldigen → die Entschuldigung (извинение), wohnen → die Wohnung (квартира). Существительные на -ung всегда имеют артикль die. Прилагательные с un- означают противоположное: interessant → uninteressant, freundlich → unfreundlich, höflich → unhöflich (невежливый), wichtig → unwichtig, pünktlich → unpünktlich (непунктуальный), glücklich → unglücklich (несчастный).',
          'Словотворення. Дієслово → іменник на -ung: senden → die Sendung (відправлення), verpacken → die Verpackung (упаковка), bestellen → die Bestellung (замовлення), rechnen → die Rechnung (рахунок), einladen → die Einladung (запрошення), entschuldigen → die Entschuldigung (вибачення), wohnen → die Wohnung (квартира). Іменники на -ung завжди мають артикль die. Прикметники з un- означають протилежне: interessant → uninteressant, freundlich → unfreundlich, höflich → unhöflich (неввічливий), wichtig → unwichtig, pünktlich → unpünktlich (непунктуальний), glücklich → unglücklich (нещасний).',
          'Sözcük türetme. Fiil → -ung ile isim: senden → die Sendung (gönderi), verpacken → die Verpackung (ambalaj), bestellen → die Bestellung (sipariş), rechnen → die Rechnung (fatura), einladen → die Einladung (davet), entschuldigen → die Entschuldigung (özür), wohnen → die Wohnung (daire). -ung ile biten isimlerin artikeli her zaman die’dir. un- ile başlayan sıfatlar zıt anlam taşır: interessant → uninteressant, freundlich → unfreundlich, höflich → unhöflich (kaba), wichtig → unwichtig, pünktlich → unpünktlich (dakik olmayan), glücklich → unglücklich (mutsuz).',
        ],
        hint: ['Verb ohne -en + -ung = Nomen mit die: bestellen → die Bestellung. un- = nicht: unfreundlich = nicht freundlich.', 'Verb without -en + -ung = noun with die: bestellen → die Bestellung. un- = not: unfreundlich = nicht freundlich.', 'Глагол без -en + -ung = существительное с die: bestellen → die Bestellung. un- = не: unfreundlich = nicht freundlich.', 'Дієслово без -en + -ung = іменник із die: bestellen → die Bestellung. un- = не: unfreundlich = nicht freundlich.', '-en’siz fiil + -ung = die ile isim: bestellen → die Bestellung. un- = değil: unfreundlich = nicht freundlich.'],
      },
      ex: [
        mc('G5', 'die Verpackung', I.choose, 'Wie heißt das Nomen zu „verpacken“?', ['die Verpackung', 'das Verpackung', 'der Verpackung'],
          ['What is the noun for “verpacken”?', 'Какое существительное образуется от «verpacken»?', 'Який іменник утворюється від «verpacken»?', '“verpacken” fiilinin ismi nedir?']),
        mc('G5', 'unfreundlich', I.choose, 'Was ist das Gegenteil von „freundlich“?', ['unfreundlich', 'freundlos', 'nichtfreundlich'],
          ['What is the opposite of “freundlich”?', 'Какое слово противоположно по значению слову «freundlich»?', 'Яке слово протилежне за значенням слову «freundlich»?', '“freundlich” kelimesinin zıt anlamlısı nedir?']),
        mc('G5', '-ung → die', I.choose, 'Welchen Artikel haben Nomen mit -ung?', ['die', 'der', 'das'],
          ['Which article do nouns ending in -ung take?', 'Какой артикль у существительных на -ung?', 'Який артикль мають іменники на -ung?', '-ung ile biten isimler hangi artikeli alır?']),
        mc('G5', 'uninteressant', I.choose, 'Der Text war langweilig. Er war …', ['uninteressant', 'unpünktlich', 'unhöflich'],
          ['The text was boring. It was …', 'Текст был скучным. Он был …', 'Текст був нудним. Він був …', 'Metin sıkıcıydı. Metin …']),
        mc('G5', 'die Bestellung', I.choose, 'Ich habe im Internet Schuhe bestellt. Meine … kommt morgen.', ['Bestellung', 'Bestellen', 'Bestellt'],
          ['I have ordered shoes online. My order is coming tomorrow.', 'Я заказал обувь в интернете. Мой заказ придёт завтра.', 'Я замовив взуття в інтернеті. Моє замовлення прийде завтра.', 'İnternetten ayakkabı sipariş ettim. Siparişim yarın geliyor.']),
        gap('G5', 'die Wohnung', I.form, 'Wir wohnen hier. Das ist unsere ', '.', 'Wohnung', ['Wohnen', 'Wohner'],
          ['We live here. This is our flat.', 'Мы здесь живём. Это наша квартира.', 'Ми тут живемо. Це наша квартира.', 'Burada oturuyoruz. Burası bizim dairemiz.'], 'wohnen'),
        gap('G5', 'die Einladung', I.form, 'Du bist eingeladen! Hier ist die ', ' zu meiner Party.', 'Einladung', ['Einladen', 'Eingeladen'],
          ['You are invited! Here is the invitation to my party.', 'Ты приглашён! Вот приглашение на мою вечеринку.', 'Тебе запрошено! Ось запрошення на мою вечірку.', 'Davetlisin! İşte partimin davetiyesi.'], 'einladen'),
        gap('G5', 'unpünktlich', I.form, 'Paul kommt immer zu spät. Er ist sehr ', '.', 'unpünktlich', ['pünktlich', 'pünktlos'],
          ['Paul is always late. He is very unpunctual.', 'Paul всегда опаздывает. Он очень непунктуальный.', 'Paul завжди запізнюється. Він дуже непунктуальний.', 'Paul hep geç kalıyor. Hiç dakik değil.'], 'pünktlich'),
        gap('G5', 'unhöflich', I.form, 'Die Verkäuferin hat nicht „Guten Tag“ gesagt. Das war ', '.', 'unhöflich', ['höflich', 'höflos'],
          ['The shop assistant did not say “Guten Tag”. That was impolite.', 'Продавщица не сказала «Guten Tag». Это было невежливо.', 'Продавчиня не сказала «Guten Tag». Це було неввічливо.', 'Satıcı “Guten Tag” demedi. Bu kabalıktı.'], 'höflich'),
        sb('G5', 'die Sendung', I.order, 'Die Sendung / kommt / aus / Ägypten.',
          ['The item comes from Egypt.', 'Отправление пришло из Египта.', 'Відправлення прийшло з Єгипту.', 'Gönderi Mısır’dan geliyor.']),
      ],
    },
    {
      title: 'Am Schalter',
      t: ['At the counter', 'У почтовой стойки', 'Біля поштової стійки', 'Gişede'],
      card: {
        id: 'p3_schalter',
        rule: 'Gespräche auf der Post: Ich möchte einen wichtigen Brief verschicken. Was für eine Möglichkeit gibt es denn da? – Dann müssen Sie den Brief als Einschreiben senden. Ich möchte ein Päckchen abholen. – Haben Sie die Benachrichtigungskarte und Ihren Ausweis dabei? Ich brauche Briefmarken. – Was für Briefmarken möchten Sie? Ich habe hier eine Sendung nach Ägypten. – Da müssen Sie diese Zollerklärung ausfüllen.',
        examples: ['Ich möchte ein Päckchen abholen.', 'Haben Sie Ihren Ausweis dabei?', 'Was kostet ein Brief nach Polen?'],
        highlight: null,
        t: [
          'Conversations at the post office: Ich möchte einen wichtigen Brief verschicken. Was für eine Möglichkeit gibt es denn da? (What options are there?) – Dann müssen Sie den Brief als Einschreiben senden. (… as a registered letter) Ich möchte ein Päckchen abholen. – Haben Sie die Benachrichtigungskarte und Ihren Ausweis dabei? (Do you have the notification card and your ID with you?) Ich brauche Briefmarken. – Was für Briefmarken möchten Sie? Ich habe hier eine Sendung nach Ägypten. – Da müssen Sie diese Zollerklärung ausfüllen. (… fill in this customs declaration)',
          'Разговоры на почте: Ich möchte einen wichtigen Brief verschicken. Was für eine Möglichkeit gibt es denn da? (Какие есть варианты?) – Dann müssen Sie den Brief als Einschreiben senden. (… заказным письмом) Ich möchte ein Päckchen abholen. – Haben Sie die Benachrichtigungskarte und Ihren Ausweis dabei? (У вас с собой извещение и удостоверение личности?) Ich brauche Briefmarken. – Was für Briefmarken möchten Sie? Ich habe hier eine Sendung nach Ägypten. – Da müssen Sie diese Zollerklärung ausfüllen. (… заполнить таможенную декларацию)',
          'Розмови на пошті: Ich möchte einen wichtigen Brief verschicken. Was für eine Möglichkeit gibt es denn da? (Які є варіанти?) – Dann müssen Sie den Brief als Einschreiben senden. (… рекомендованим листом) Ich möchte ein Päckchen abholen. – Haben Sie die Benachrichtigungskarte und Ihren Ausweis dabei? (Чи маєте ви із собою повідомлення й посвідчення особи?) Ich brauche Briefmarken. – Was für Briefmarken möchten Sie? Ich habe hier eine Sendung nach Ägypten. – Da müssen Sie diese Zollerklärung ausfüllen. (… заповнити митну декларацію)',
          'Postanede konuşmalar: Ich möchte einen wichtigen Brief verschicken. Was für eine Möglichkeit gibt es denn da? (Ne gibi seçenekler var?) – Dann müssen Sie den Brief als Einschreiben senden. (… taahhütlü olarak) Ich möchte ein Päckchen abholen. – Haben Sie die Benachrichtigungskarte und Ihren Ausweis dabei? (Bildirim kartınız ve kimliğiniz yanınızda mı?) Ich brauche Briefmarken. – Was für Briefmarken möchten Sie? Ich habe hier eine Sendung nach Ägypten. – Da müssen Sie diese Zollerklärung ausfüllen. (… bu gümrük beyannamesini doldurmanız gerekiyor)',
        ],
        hint: ['abholen: Karte + Ausweis. wichtiger Brief: als Einschreiben. Sendung ins Ausland: Zollerklärung ausfüllen.', 'abholen (collect): card + ID. Important letter: als Einschreiben. Item going abroad: Zollerklärung ausfüllen.', 'abholen (забрать): извещение + удостоверение. Важное письмо: als Einschreiben. Отправление за границу: Zollerklärung ausfüllen.', 'abholen (забрати): повідомлення + посвідчення. Важливий лист: als Einschreiben. Відправлення за кордон: Zollerklärung ausfüllen.', 'abholen (teslim almak): kart + kimlik. Önemli mektup: als Einschreiben. Yurt dışına gönderi: Zollerklärung ausfüllen.'],
      },
      ex: [
        mc('K1', 'abholen', I.situation, 'Du hast eine Benachrichtigungskarte im Briefkasten gefunden. Was sagst du auf der Post?', ['Ich möchte ein Päckchen abholen.', 'Ich möchte ein Päckchen verschicken.', 'Ich brauche Briefmarken.'],
          ['You have found a notification card in your letterbox. What do you say at the post office?', 'Вы нашли в почтовом ящике извещение. Что вы скажете на почте?', 'Ви знайшли в поштовій скриньці повідомлення. Що ви скажете на пошті?', 'Posta kutunuzda bir bildirim kartı buldunuz. Postanede ne dersiniz?']),
        mc('K1', 'Ausweis', I.react, '„Ich möchte ein Paket abholen.“ – Du arbeitest am Schalter.', ['Haben Sie die Karte und Ihren Ausweis dabei?', 'Was für Briefmarken möchten Sie?', 'Das macht drei Euro.'],
          ['“I would like to collect a parcel.” – You work at the counter.', '«Я хочу забрать посылку.» – Вы работаете за стойкой.', '«Я хочу забрати посилку.» – Ви працюєте за стійкою.', '“Bir koli teslim almak istiyorum.” – Gişede çalışıyorsunuz.']),
        mc('K1', 'Was für eine Möglichkeit …?', I.situation, 'Du willst einen wichtigen Brief sicher schicken und fragst nach den Möglichkeiten. Was sagst du?', ['Was für eine Möglichkeit gibt es denn da?', 'Was für ein Wetter ist heute?', 'Wo ist der Briefkasten?'],
          ['You want to send an important letter safely and ask about the options. What do you say?', 'Вы хотите надёжно отправить важное письмо и спрашиваете о вариантах. Что вы скажете?', 'Ви хочете надійно надіслати важливий лист і питаєте про варіанти. Що ви скажете?', 'Önemli bir mektubu güvenli göndermek istiyor ve seçenekleri soruyorsunuz. Ne dersiniz?']),
        mc('K1', 'Was für Briefmarken?', I.react, '„Ich brauche Briefmarken.“', ['Was für Briefmarken möchten Sie?', 'Haben Sie Ihren Ausweis dabei?', 'Sie müssen das Paket abholen.'],
          ['“I need stamps.”', '«Мне нужны марки.»', '«Мені потрібні марки.»', '“Pula ihtiyacım var.”']),
        mc('K1', 'Zollerklärung', I.react, '„Ich habe hier eine Sendung nach Ägypten.“', ['Da müssen Sie diese Zollerklärung ausfüllen.', 'Da müssen Sie Ihren Ausweis abholen.', 'Die Sendung ist kostenlos.'],
          ['“I have an item here to go to Egypt.”', '«У меня отправление в Египет.»', '«У мене відправлення до Єгипту.»', '“Mısır’a bir gönderim var.”']),
        gap('K1', 'als Einschreiben', I.word, 'Ich möchte diesen Brief als ', ' senden. Er ist sehr wichtig.', 'Einschreiben', ['Päckchen', 'Formular'],
          ['I would like to send this letter by registered post. It is very important.', 'Я хочу отправить это письмо заказным. Оно очень важное.', 'Я хочу надіслати цей лист рекомендованим. Він дуже важливий.', 'Bu mektubu taahhütlü göndermek istiyorum. Çok önemli.'],
          ['registered letter', 'заказное письмо', 'рекомендований лист', 'taahhütlü mektup']),
        gap('K1', 'Ausweis', I.word, 'Haben Sie Ihren ', ' dabei? Ich muss Ihren Namen prüfen.', 'Ausweis', ['Absender', 'Aufkleber'],
          ['Do you have your ID with you? I have to check your name.', 'У вас с собой удостоверение личности? Мне нужно проверить ваше имя.', 'Чи маєте ви із собою посвідчення особи? Мені треба перевірити ваше ім’я.', 'Kimliğiniz yanınızda mı? Adınızı kontrol etmem gerekiyor.'],
          ['ID card', 'удостоверение личности', 'посвідчення особи', 'kimlik']),
        gap('K1', 'ausfüllen', I.verb, 'Bitte ', ' Sie dieses Formular aus.', 'füllen', ['fühlen', 'fallen'],
          ['Please fill in this form.', 'Пожалуйста, заполните этот бланк.', 'Будь ласка, заповніть цей бланк.', 'Lütfen bu formu doldurun.'], 'ausfüllen'),
        gap('K1', 'Was kostet …?', I.verb, 'Was ', ' ein Brief nach Italien?', 'kostet', ['kosten', 'kostest'],
          ['How much is a letter to Italy?', 'Сколько стоит письмо в Италию?', 'Скільки коштує лист до Італії?', 'İtalya’ya bir mektup ne kadar?'], 'kosten'),
        sb('K1', 'abholen', I.order, 'Ich / möchte / ein Päckchen / abholen.',
          ['I would like to collect a packet.', 'Я хочу забрать пакет.', 'Я хочу забрати пакунок.', 'Bir paket teslim almak istiyorum.'],
          { alt: ['Ein Päckchen möchte ich abholen.'] }),
      ],
    },
    {
      title: 'Handy, Mailbox, Netzwerk',
      t: ['Mobile, voicemail, network', 'Телефон, голосовая почта, соцсеть', 'Телефон, голосова пошта, соцмережа', 'Cep telefonu, sesli mesaj, sosyal ağ'],
      card: {
        id: 'p3_kommunikation',
        rule: 'Kommunikation: das Handy, das Smartphone, die Mailbox (dort spricht man eine Nachricht nach dem Signalton), die Nachricht, die SMS, die E-Mail, der Anruf (anrufen), der Rückruf (zurückrufen), das soziale Netzwerk, das Profil, erreichbar sein (man kann mich anrufen). Über Kommunikation sprechen: Bist du in einem sozialen Netzwerk? Wie oft schreibst du Nachrichten? Ich telefoniere nicht gern, ich schreibe lieber. Ich bin immer erreichbar.',
        examples: ['Ich habe dir auf die Mailbox gesprochen.', 'Bist du in einem sozialen Netzwerk?', 'Ich schreibe lieber Nachrichten.'],
        highlight: null,
        t: [
          'Communication: das Handy (mobile), das Smartphone, die Mailbox (voicemail: you leave a message there after the tone), die Nachricht (message), die SMS (text message), die E-Mail, der Anruf (call; anrufen = to call), der Rückruf (return call; zurückrufen = to call back), das soziale Netzwerk (social network), das Profil (profile), erreichbar sein (to be reachable: people can call me). Talking about communication: Bist du in einem sozialen Netzwerk? Wie oft schreibst du Nachrichten? Ich telefoniere nicht gern, ich schreibe lieber. (I prefer writing.) Ich bin immer erreichbar.',
          'Общение: das Handy (мобильный телефон), das Smartphone, die Mailbox (голосовая почта: там оставляют сообщение после сигнала), die Nachricht (сообщение), die SMS, die E-Mail, der Anruf (звонок; anrufen = звонить), der Rückruf (ответный звонок; zurückrufen = перезвонить), das soziale Netzwerk (социальная сеть), das Profil (профиль), erreichbar sein (быть на связи: мне можно позвонить). Как говорить об общении: Bist du in einem sozialen Netzwerk? Wie oft schreibst du Nachrichten? Ich telefoniere nicht gern, ich schreibe lieber. (Мне больше нравится писать.) Ich bin immer erreichbar.',
          'Спілкування: das Handy (мобільний телефон), das Smartphone, die Mailbox (голосова пошта: там залишають повідомлення після сигналу), die Nachricht (повідомлення), die SMS, die E-Mail, der Anruf (дзвінок; anrufen = телефонувати), der Rückruf (дзвінок у відповідь; zurückrufen = передзвонити), das soziale Netzwerk (соціальна мережа), das Profil (профіль), erreichbar sein (бути на зв’язку: мені можна зателефонувати). Як говорити про спілкування: Bist du in einem sozialen Netzwerk? Wie oft schreibst du Nachrichten? Ich telefoniere nicht gern, ich schreibe lieber. (Мені більше подобається писати.) Ich bin immer erreichbar.',
          'İletişim: das Handy (cep telefonu), das Smartphone, die Mailbox (sesli mesaj: sinyal sesinden sonra mesaj bırakılır), die Nachricht (mesaj), die SMS, die E-Mail, der Anruf (arama; anrufen = aramak), der Rückruf (geri arama; zurückrufen = geri aramak), das soziale Netzwerk (sosyal ağ), das Profil (profil), erreichbar sein (ulaşılabilir olmak: beni arayabilirler). İletişimden söz etmek: Bist du in einem sozialen Netzwerk? Wie oft schreibst du Nachrichten? Ich telefoniere nicht gern, ich schreibe lieber. (Yazmayı tercih ederim.) Ich bin immer erreichbar.',
        ],
        hint: ['Mailbox = dort hinterlässt man eine Nachricht. zurückrufen = später selbst anrufen. erreichbar = man kann mich anrufen.', 'Mailbox = you leave a message there. zurückrufen = call back later yourself. erreichbar = people can call me.', 'Mailbox = там оставляют сообщение. zurückrufen = перезвонить позже. erreichbar = мне можно позвонить.', 'Mailbox = там залишають повідомлення. zurückrufen = передзвонити пізніше. erreichbar = мені можна зателефонувати.', 'Mailbox = oraya mesaj bırakılır. zurückrufen = sonra geri aramak. erreichbar = beni arayabilirler.'],
      },
      ex: [
        mc('W2', 'Mailbox', I.choose, 'Du rufst an, aber niemand antwortet. Du hörst: „Bitte sprechen Sie nach dem Signalton.“ Was ist das?', ['die Mailbox', 'das Profil', 'das Netzwerk'],
          ['You call, but nobody answers. You hear: “Please speak after the tone.” What is that?', 'Вы звоните, но никто не отвечает. Вы слышите: «Говорите после сигнала». Что это?', 'Ви телефонуєте, але ніхто не відповідає. Ви чуєте: «Говоріть після сигналу». Що це?', 'Arıyorsunuz ama kimse cevap vermiyor. “Lütfen sinyal sesinden sonra konuşun” diye duyuyorsunuz. Bu nedir?']),
        mc('W2', 'zurückrufen', I.choose, 'Was bedeutet „zurückrufen“?', ['später selbst anrufen', 'nicht ans Telefon gehen', 'eine Postkarte schicken'],
          ['What does “zurückrufen” mean?', 'Что значит «zurückrufen»?', 'Що означає «zurückrufen»?', '“zurückrufen” ne demek?']),
        mc('W2', 'erreichbar', I.choose, 'Mein Handy ist immer an. Man kann mich immer anrufen. Ich bin immer …', ['erreichbar', 'arbeitslos', 'unhöflich'],
          ['My mobile is always on. People can always call me. I am always …', 'Мой телефон всегда включён. Мне всегда можно позвонить. Я всегда …', 'Мій телефон завжди ввімкнений. Мені завжди можна зателефонувати. Я завжди …', 'Cep telefonum hep açık. Beni her zaman arayabilirler. Ben her zaman …']),
        mc('K5', 'soziales Netzwerk', I.react, '„Bist du in einem sozialen Netzwerk?“', ['Ja, aber ich schreibe dort nicht viel.', 'Ja, ich arbeite bei der Post.', 'Nein, ich habe kein Formular.'],
          ['“Are you on a social network?”', '«Ты есть в какой-нибудь социальной сети?»', '«Ти є в якійсь соціальній мережі?»', '“Bir sosyal ağda var mısın?”']),
        mc('K5', 'lieber schreiben', I.situation, 'Du telefonierst nicht gern. Du schickst lieber Textnachrichten. Was sagst du?', ['Ich schreibe lieber Nachrichten.', 'Ich telefoniere am liebsten.', 'Ich bin nie erreichbar.'],
          ['You do not like phoning. You prefer sending text messages. What do you say?', 'Вы не любите звонить. Вы предпочитаете отправлять текстовые сообщения. Что вы скажете?', 'Ви не любите телефонувати. Ви волієте надсилати текстові повідомлення. Що ви скажете?', 'Telefonla konuşmayı sevmiyorsunuz. Mesaj göndermeyi tercih ediyorsunuz. Ne dersiniz?']),
        mc('K5', 'Wie oft?', I.react, '„Wie oft schreibst du E-Mails?“', ['Fast jeden Tag, vor allem bei der Arbeit.', 'Mit dem Handy.', 'In einem sozialen Netzwerk.'],
          ['“How often do you write e-mails?”', '«Как часто ты пишешь электронные письма?»', '«Як часто ти пишеш електронні листи?»', '“Ne sıklıkta e-posta yazıyorsun?”']),
        gap('W2', 'Nachricht', I.word, 'Tom ist nicht da. Ich spreche ihm eine ', ' auf die Mailbox.', 'Nachricht', ['Rechnung', 'Sendung'],
          ['Tom is not there. I am leaving him a message on his voicemail.', 'Tom нет на месте. Я оставлю ему сообщение на голосовой почте.', 'Tom немає на місці. Я залишу йому повідомлення на голосовій пошті.', 'Tom yok. Ona sesli mesaj bırakıyorum.'],
          ['message', 'сообщение', 'повідомлення', 'mesaj']),
        gap('W2', 'Anruf', I.word, 'Hast du meinen ', ' gestern nicht gehört? Ich habe dreimal angerufen.', 'Anruf', ['Ausweis', 'Absender'],
          ['Did you not hear my call yesterday? I rang three times.', 'Ты вчера не слышал мой звонок? Я звонил три раза.', 'Ти вчора не чув мій дзвінок? Я телефонував тричі.', 'Dün aramamı duymadın mı? Üç kez aradım.'],
          ['call', 'звонок', 'дзвінок', 'arama']),
        gap('K5', 'lieber', I.comparison, 'Telefonieren mag ich nicht so. Ich schreibe ', ' eine Nachricht.', 'lieber', ['liebsten', 'lieb'],
          ['I do not like phoning that much. I prefer to write a message.', 'Звонить я не очень люблю. Я лучше напишу сообщение.', 'Телефонувати я не дуже люблю. Я краще напишу повідомлення.', 'Telefonla konuşmayı pek sevmem. Mesaj yazmayı tercih ederim.'], 'gern'),
        sb('K5', 'in einem sozialen Netzwerk', I.question, 'Bist / du / in einem / sozialen Netzwerk?',
          ['Are you on a social network?', 'Ты есть в социальной сети?', 'Ти є в соціальній мережі?', 'Bir sosyal ağda var mısın?']),
      ],
    },
    {
      title: 'Das überrascht mich.',
      t: ['That surprises me.', 'Это меня удивляет.', 'Це мене дивує.', 'Bu beni şaşırtıyor.'],
      card: {
        id: 'p3_erstaunen',
        rule: 'Erstaunen ausdrücken: Ich habe gedacht, dass alle ein Handy haben. Ich habe geglaubt, dass … Das überrascht mich. Das überrascht mich nicht. Das finde ich komisch. Das finde ich interessant. Das ist erstaunlich. Wirklich? Schade. Nach dass steht das Verb am Ende.',
        examples: ['Ich habe gedacht, dass junge Leute mehr telefonieren.', 'Nur wenige schreiben noch Briefe. – Das überrascht mich nicht.', 'Das ist erstaunlich!'],
        highlight: null,
        t: [
          'Expressing surprise: Ich habe gedacht, dass alle ein Handy haben. (I thought that everyone had a mobile.) Ich habe geglaubt, dass … (I believed that …) Das überrascht mich. (That surprises me.) Das überrascht mich nicht. Das finde ich komisch. (I find that strange.) Das finde ich interessant. Das ist erstaunlich. (That is astonishing.) Wirklich? (Really?) Schade. (What a pity.) After dass the verb goes at the end.',
          'Как выразить удивление: Ich habe gedacht, dass alle ein Handy haben. (Я думал, что у всех есть мобильный телефон.) Ich habe geglaubt, dass … (Я считал, что …) Das überrascht mich. (Это меня удивляет.) Das überrascht mich nicht. Das finde ich komisch. (По-моему, это странно.) Das finde ich interessant. Das ist erstaunlich. (Это удивительно.) Wirklich? (Правда?) Schade. (Жаль.) После dass глагол стоит в конце.',
          'Як висловити подив: Ich habe gedacht, dass alle ein Handy haben. (Я думав, що в усіх є мобільний телефон.) Ich habe geglaubt, dass … (Я вважав, що …) Das überrascht mich. (Це мене дивує.) Das überrascht mich nicht. Das finde ich komisch. (На мою думку, це дивно.) Das finde ich interessant. Das ist erstaunlich. (Це дивовижно.) Wirklich? (Справді?) Schade. (Шкода.) Після dass дієслово стоїть у кінці.',
          'Şaşkınlık bildirmek: Ich habe gedacht, dass alle ein Handy haben. (Herkesin cep telefonu var sanıyordum.) Ich habe geglaubt, dass … (… sanmıştım.) Das überrascht mich. (Bu beni şaşırtıyor.) Das überrascht mich nicht. Das finde ich komisch. (Bunu tuhaf buluyorum.) Das finde ich interessant. Das ist erstaunlich. (Bu şaşırtıcı.) Wirklich? (Gerçekten mi?) Schade. (Yazık.) dass’tan sonra fiil sonda durur.',
        ],
        hint: ['Das überrascht mich = Das habe ich nicht gedacht. Ich habe gedacht, dass … + Verb am Ende.', 'Das überrascht mich = I did not expect that. Ich habe gedacht, dass … + verb at the end.', 'Das überrascht mich = я этого не ожидал. Ich habe gedacht, dass … + глагол в конце.', 'Das überrascht mich = я цього не очікував. Ich habe gedacht, dass … + дієслово в кінці.', 'Das überrascht mich = bunu beklemiyordum. Ich habe gedacht, dass … + fiil sonda.'],
      },
      ex: [
        mc('K2', 'Das überrascht mich.', I.react, '„Mein Opa ist 85 und hat drei Handys.“ – Das hast du nicht erwartet.', ['Wirklich? Das überrascht mich.', 'Das überrascht mich nicht.', 'Das ist langweilig.'],
          ['“My grandad is 85 and has three mobiles.” – You did not expect that.', '«Моему дедушке 85, и у него три мобильных телефона.» – Вы этого не ожидали.', '«Моєму дідусеві 85, і в нього три мобільні телефони.» – Ви цього не очікували.', '“Dedem 85 yaşında ve üç cep telefonu var.” – Bunu beklemiyordunuz.']),
        mc('K2', 'überraschen', I.choose, 'Was bedeutet „Das überrascht mich“?', ['Das habe ich nicht gedacht.', 'Das habe ich schon gewusst.', 'Das ist mir egal.'],
          ['What does “Das überrascht mich” mean?', 'Что значит «Das überrascht mich»?', 'Що означає «Das überrascht mich»?', '“Das überrascht mich” ne demek?']),
        mc('K2', 'Ich habe gedacht, dass …', I.sentence, 'Nur wenige Leute schreiben noch Briefe. Du hast eine andere Zahl erwartet.', ['Ich habe gedacht, dass mehr Leute Briefe schreiben.', 'Ich habe gedacht, dass mehr Leute schreiben Briefe.', 'Ich habe gedacht, mehr Leute dass Briefe schreiben.'],
          ['Only a few people still write letters. You expected a different number.', 'Лишь немногие ещё пишут письма. Вы ожидали другую цифру.', 'Лише небагато людей іще пишуть листи. Ви очікували іншу цифру.', 'Artık çok az kişi mektup yazıyor. Siz başka bir sayı bekliyordunuz.']),
        mc('K2', 'Das finde ich komisch.', I.react, '„Kinder haben heute schon mit sechs Jahren ein Handy.“ – Du findest das seltsam.', ['Das finde ich komisch.', 'Das finde ich normal.', 'Das finde ich lecker.'],
          ['“Children today have a mobile at the age of six.” – You find that odd.', '«Сегодня у детей уже в шесть лет есть мобильный телефон.» – Вам это кажется странным.', '«Сьогодні діти вже в шість років мають мобільний телефон.» – Вам це здається дивним.', '“Bugün çocukların altı yaşında cep telefonu var.” – Bunu tuhaf buluyorsunuz.']),
        mc('K2', 'Das überrascht mich nicht.', I.choose, 'Du hast das schon gewusst. Was sagst du?', ['Das überrascht mich nicht.', 'Das ist erstaunlich.', 'Wirklich?'],
          ['You already knew that. What do you say?', 'Вы это уже знали. Что вы скажете?', 'Ви це вже знали. Що ви скажете?', 'Bunu zaten biliyordunuz. Ne dersiniz?']),
        gap('K2', 'Ich habe gedacht', I.participle, 'Ich habe ', ', dass die Post am Samstag geschlossen ist. Aber sie ist geöffnet!', ['gedacht', 'geglaubt'], ['gedenkt', 'denken'],
          ['I thought the post office was closed on Saturdays. But it is open!', 'Я думал, что почта в субботу закрыта. А она открыта!', 'Я думав, що пошта в суботу зачинена. А вона відчинена!', 'Postanenin cumartesi kapalı olduğunu sanıyordum. Ama açıkmış!'], 'denken'),
        gap('K2', 'überrascht', I.verb, 'Nur zehn Prozent schreiben noch Briefe? Das ', ' mich.', 'überrascht', ['überraschen', 'überraschst'],
          ['Only ten per cent still write letters? That surprises me.', 'Только десять процентов ещё пишут письма? Это меня удивляет.', 'Лише десять відсотків іще пишуть листи? Це мене дивує.', 'Sadece yüzde on mu hâlâ mektup yazıyor? Bu beni şaşırtıyor.'], 'überraschen'),
        gap('K2', 'erstaunlich', I.word, 'Fast alle haben ein Smartphone. Das ist ', '!', 'erstaunlich', ['erreichbar', 'unhöflich'],
          ['Almost everyone has a smartphone. That is astonishing!', 'Почти у всех есть смартфон. Это удивительно!', 'Майже всі мають смартфон. Це дивовижно!', 'Neredeyse herkesin akıllı telefonu var. Bu şaşırtıcı!'],
          ['astonishing', 'удивительно', 'дивовижно', 'şaşırtıcı']),
        gap('K2', 'dass', I.conjunction, 'Ich habe geglaubt, ', ' alte Leute nicht im Internet sind.', 'dass', ['weil', 'wenn'],
          ['I believed that old people were not on the internet.', 'Я считал, что пожилые люди не пользуются интернетом.', 'Я вважав, що літні люди не користуються інтернетом.', 'Yaşlıların internette olmadığını sanıyordum.'], 'dass / weil / wenn'),
        sb('K2', 'Das überrascht mich nicht.', I.order, 'Das / überrascht / mich / nicht.',
          ['That does not surprise me.', 'Это меня не удивляет.', 'Це мене не дивує.', 'Bu beni şaşırtmıyor.'],
          { alt: ['Mich überrascht das nicht.'] }),
      ],
    },
    {
      title: 'Es tut mir leid, dass …',
      t: ['I am sorry that …', 'Мне жаль, что …', 'Мені шкода, що …', '… için üzgünüm'],
      card: {
        id: 'p3_entschuldigen',
        rule: 'Sich am Telefon entschuldigen: Es tut mir sehr leid, dass ich nicht gekommen bin. Entschuldigung! Entschuldige! Entschuldigen Sie! Ich konnte nicht kommen, weil ich krank war. Ich wollte anrufen, aber mein Handy war aus. Ich hoffe, du bist nicht sauer. Ich melde mich wieder. Könnten Sie mich bitte zurückrufen? Könnten wir den Termin verschieben? Dank und gute Wünsche: Vielen Dank für deine Nachricht. Alles Gute! Gute Besserung!',
        examples: ['Es tut mir schrecklich leid, dass ich zu spät bin.', 'Könnten wir den Termin verschieben?', 'Vielen Dank für Ihre Nachricht. Gute Besserung!'],
        highlight: null,
        t: [
          'Apologising on the phone: Es tut mir sehr leid, dass ich nicht gekommen bin. (I am very sorry that I did not come.) Entschuldigung! Entschuldige! Entschuldigen Sie! Ich konnte nicht kommen, weil ich krank war. Ich wollte anrufen, aber mein Handy war aus. Ich hoffe, du bist nicht sauer. (I hope you are not cross.) Ich melde mich wieder. (I will be in touch again.) Könnten Sie mich bitte zurückrufen? Könnten wir den Termin verschieben? (Could we postpone the appointment?) Thanks and good wishes: Vielen Dank für deine Nachricht. Alles Gute! (All the best!) Gute Besserung! (Get well soon!)',
          'Как извиниться по телефону: Es tut mir sehr leid, dass ich nicht gekommen bin. (Мне очень жаль, что я не пришёл.) Entschuldigung! Entschuldige! Entschuldigen Sie! Ich konnte nicht kommen, weil ich krank war. Ich wollte anrufen, aber mein Handy war aus. Ich hoffe, du bist nicht sauer. (Надеюсь, ты не сердишься.) Ich melde mich wieder. (Я ещё свяжусь.) Könnten Sie mich bitte zurückrufen? Könnten wir den Termin verschieben? (Не могли бы мы перенести встречу?) Благодарность и пожелания: Vielen Dank für deine Nachricht. Alles Gute! (Всего хорошего!) Gute Besserung! (Выздоравливай!)',
          'Як вибачитися телефоном: Es tut mir sehr leid, dass ich nicht gekommen bin. (Мені дуже шкода, що я не прийшов.) Entschuldigung! Entschuldige! Entschuldigen Sie! Ich konnte nicht kommen, weil ich krank war. Ich wollte anrufen, aber mein Handy war aus. Ich hoffe, du bist nicht sauer. (Сподіваюся, ти не сердишся.) Ich melde mich wieder. (Я ще зв’яжуся.) Könnten Sie mich bitte zurückrufen? Könnten wir den Termin verschieben? (Чи могли б ми перенести зустріч?) Подяка й побажання: Vielen Dank für deine Nachricht. Alles Gute! (Усього найкращого!) Gute Besserung! (Одужуй!)',
          'Telefonda özür dilemek: Es tut mir sehr leid, dass ich nicht gekommen bin. (Gelmediğim için çok üzgünüm.) Entschuldigung! Entschuldige! Entschuldigen Sie! Ich konnte nicht kommen, weil ich krank war. Ich wollte anrufen, aber mein Handy war aus. Ich hoffe, du bist nicht sauer. (Umarım kızgın değilsindir.) Ich melde mich wieder. (Yine haber veririm.) Könnten Sie mich bitte zurückrufen? Könnten wir den Termin verschieben? (Randevuyu erteleyebilir miyiz?) Teşekkür ve iyi dilekler: Vielen Dank für deine Nachricht. Alles Gute! (Her şey gönlünce olsun!) Gute Besserung! (Geçmiş olsun!)',
        ],
        hint: ['Es tut mir leid, dass … (Verb am Ende). Grund: weil … sauer = böse. Gute Besserung = für Kranke.', 'Es tut mir leid, dass … (verb at the end). Reason: weil … sauer = cross. Gute Besserung = for someone who is ill.', 'Es tut mir leid, dass … (глагол в конце). Причина: weil … sauer = сердитый. Gute Besserung = для больных.', 'Es tut mir leid, dass … (дієслово в кінці). Причина: weil … sauer = сердитий. Gute Besserung = для хворих.', 'Es tut mir leid, dass … (fiil sonda). Neden: weil … sauer = kızgın. Gute Besserung = hastalar için.'],
      },
      ex: [
        mc('K3', 'Es tut mir leid, dass …', I.situation, 'Du hast den Geburtstag von deiner Freundin vergessen. Du rufst sie an. Was sagst du?', ['Es tut mir so leid, dass ich deinen Geburtstag vergessen habe.', 'Vielen Dank für deine Nachricht.', 'Das überrascht mich nicht.'],
          ['You forgot your friend’s birthday. You call her. What do you say?', 'Вы забыли о дне рождения подруги. Вы звоните ей. Что вы скажете?', 'Ви забули про день народження подруги. Ви телефонуєте їй. Що ви скажете?', 'Arkadaşınızın doğum gününü unuttunuz. Onu arıyorsunuz. Ne dersiniz?']),
        mc('K3', 'sauer', I.choose, 'Was bedeutet „Ich hoffe, du bist nicht sauer“?', ['Ich hoffe, du bist nicht böse auf mich.', 'Ich hoffe, du bist nicht krank.', 'Ich hoffe, du bist nicht müde.'],
          ['What does “Ich hoffe, du bist nicht sauer” mean?', 'Что значит «Ich hoffe, du bist nicht sauer»?', 'Що означає «Ich hoffe, du bist nicht sauer»?', '“Ich hoffe, du bist nicht sauer” ne demek?']),
        mc('K3', 'Termin verschieben', I.situation, 'Du kannst morgen nicht zum Termin kommen und sprichst auf die Mailbox der Praxis. Was sagst du?', ['Könnten wir den Termin verschieben?', 'Könnten Sie den Termin vergessen?', 'Ich habe keinen Termin.'],
          ['You cannot come to your appointment tomorrow and leave a message on the surgery’s voicemail. What do you say?', 'Вы не можете прийти завтра на приём и оставляете сообщение на голосовой почте клиники. Что вы скажете?', 'Ви не можете прийти завтра на прийом і залишаєте повідомлення на голосовій пошті клініки. Що ви скажете?', 'Yarın randevuya gelemiyorsunuz ve muayenehanenin sesli mesajına konuşuyorsunuz. Ne dersiniz?']),
        mc('K4', 'Gute Besserung', I.situation, 'Dein Kollege ist krank und hat dir geschrieben. Wie beendest du deine Antwort?', ['Gute Besserung!', 'Guten Appetit!', 'Herzlichen Glückwunsch!'],
          ['Your colleague is ill and has written to you. How do you end your reply?', 'Ваш коллега болен и написал вам. Как вы закончите ответ?', 'Ваш колега хворий і написав вам. Як ви закінчите відповідь?', 'İş arkadaşınız hasta ve size yazdı. Cevabınızı nasıl bitirirsiniz?']),
        mc('K4', 'Vielen Dank für deine Nachricht', I.choose, 'Wie beginnt eine Antwort auf eine Nachricht?', ['Hallo Jonas, vielen Dank für deine Nachricht.', 'Hallo Jonas, gute Besserung für deine Nachricht.', 'Hallo Jonas, alles Gute für deine Nachricht.'],
          ['How does a reply to a message begin?', 'Как начинается ответ на сообщение?', 'Як починається відповідь на повідомлення?', 'Bir mesaja verilen cevap nasıl başlar?']),
        gap('K3', 'dass', I.conjunction, 'Es tut mir leid, ', ' ich gestern nicht angerufen habe.', 'dass', ['aber', 'denn'],
          ['I am sorry that I did not call yesterday.', 'Мне жаль, что я вчера не позвонил.', 'Мені шкода, що я вчора не зателефонував.', 'Dün aramadığım için üzgünüm.'], 'dass / aber / denn'),
        gap('K3', 'konnte', I.modalPast, 'Ich ', ' nicht kommen, weil mein Auto kaputt war.', 'konnte', ['konnten', 'kann'],
          ['I could not come because my car had broken down.', 'Я не смог приехать, потому что моя машина сломалась.', 'Я не зміг приїхати, бо моя машина зламалася.', 'Arabam bozuk olduğu için gelemedim.'], 'können'),
        gap('K3', 'sich melden', I.verb, 'Ich bin gerade im Zug. Ich ', ' mich heute Abend wieder.', 'melde', ['meldet', 'höre'],
          ['I am on the train at the moment. I will be in touch again this evening.', 'Я сейчас в поезде. Я свяжусь сегодня вечером.', 'Я зараз у потязі. Я зв’яжуся сьогодні ввечері.', 'Şu an trendeyim. Bu akşam yine haber veririm.'], 'sich melden'),
        gap('K4', 'Alles Gute', I.word, 'Du hast eine neue Stelle? Ich wünsche dir alles ', '!', 'Gute', ['Gut', 'Guten'],
          ['You have a new job? I wish you all the best!', 'У тебя новая работа? Желаю тебе всего хорошего!', 'У тебе нова робота? Бажаю тобі всього найкращого!', 'Yeni bir işin mi var? Sana her şeyin en iyisini diliyorum!'],
          ['good (all the best)', 'хорошего (всего хорошего)', 'доброго (усього найкращого)', 'iyilik (her şeyin en iyisi)']),
        sb('K3', 'zurückrufen', I.question, 'Könnten / Sie / mich / bitte / zurückrufen?',
          ['Could you call me back, please?', 'Не могли бы вы мне перезвонить?', 'Чи не могли б ви мені передзвонити?', 'Beni geri arayabilir misiniz lütfen?'],
          { alt: ['Könnten Sie mich zurückrufen, bitte?'] }),
      ],
    },
    {
      title: 'Nachrichten auf der Mailbox',
      t: ['Messages on voicemail', 'Сообщения на голосовой почте', 'Повідомлення на голосовій пошті', 'Sesli mesajlar'],
      card: {
        id: 'p3_mailbox',
        rule: 'Nachrichten auf der Mailbox verstehen: Wer spricht? (Hier ist …) Für wen ist die Nachricht? Was ist das Problem? (Der Termin fällt aus. Ich schaffe es nicht.) Was soll ich tun? (Bitte rufen Sie zurück. Kommen Sie bitte um zehn.) Bis wann? (Wir sind bis 18 Uhr erreichbar.) ausfallen = nicht stattfinden. es schaffen = es ist möglich. die Verspätung = man kommt zu spät.',
        examples: ['Hier ist die Praxis Dr. Sommer.', 'Ihr Termin fällt leider aus.', 'Bitte rufen Sie uns zurück.'],
        highlight: null,
        t: [
          'Understanding voicemail messages: who is speaking? (Hier ist … = This is …) Who is the message for? What is the problem? (Der Termin fällt aus. = The appointment is cancelled. Ich schaffe es nicht. = I cannot make it.) What should I do? (Bitte rufen Sie zurück. Kommen Sie bitte um zehn.) By when? (Wir sind bis 18 Uhr erreichbar.) ausfallen = not take place. es schaffen = manage it. die Verspätung = delay: someone is late.',
          'Как понимать сообщения на голосовой почте: кто говорит? (Hier ist … = Это …) Для кого сообщение? В чём проблема? (Der Termin fällt aus. = Приём отменяется. Ich schaffe es nicht. = Я не успеваю.) Что нужно сделать? (Bitte rufen Sie zurück. Kommen Sie bitte um zehn.) До какого времени? (Wir sind bis 18 Uhr erreichbar.) ausfallen = не состояться. es schaffen = успеть, суметь. die Verspätung = опоздание.',
          'Як розуміти повідомлення на голосовій пошті: хто говорить? (Hier ist … = Це …) Для кого повідомлення? У чому проблема? (Der Termin fällt aus. = Прийом скасовано. Ich schaffe es nicht. = Я не встигаю.) Що треба зробити? (Bitte rufen Sie zurück. Kommen Sie bitte um zehn.) До котрої години? (Wir sind bis 18 Uhr erreichbar.) ausfallen = не відбутися. es schaffen = встигнути, зуміти. die Verspätung = запізнення.',
          'Sesli mesajları anlamak: Kim konuşuyor? (Hier ist … = Ben …) Mesaj kime? Sorun ne? (Der Termin fällt aus. = Randevu iptal. Ich schaffe es nicht. = Yetişemiyorum.) Ne yapmalıyım? (Bitte rufen Sie zurück. Kommen Sie bitte um zehn.) Saat kaça kadar? (Wir sind bis 18 Uhr erreichbar.) ausfallen = yapılmamak. es schaffen = başarmak, yetişmek. die Verspätung = gecikme.',
        ],
        hint: ['Wer ruft an? Was ist passiert? Was soll man tun? ausfallen = findet nicht statt.', 'Who is calling? What has happened? What should you do? ausfallen = does not take place.', 'Кто звонит? Что случилось? Что нужно сделать? ausfallen = не состоится.', 'Хто телефонує? Що сталося? Що треба зробити? ausfallen = не відбудеться.', 'Kim arıyor? Ne oldu? Ne yapmak gerekiyor? ausfallen = yapılmıyor.'],
      },
      ex: [
        mc("Z1", "Wer?", I.read, "Nachricht auf der Mailbox: „Guten Tag, Herr Weber, hier ist die Praxis Dr. Sommer. Ihr Termin am Dienstag um neun Uhr fällt leider aus, weil der Arzt krank ist. Bitte rufen Sie uns zurück. Wir sind heute bis 18 Uhr erreichbar.“ Wer hat angerufen?", ["Eine Arztpraxis.","Herr Weber.","Eine Schule."], ["Who called?","Кто звонил?","Хто телефонував?","Kim aradı?"], {"c":"p3_mailbox","sitovOptionOrder":["Herr Weber.","Eine Schule.","Eine Arztpraxis."]}),
        mc("Z1", "ausfallen", I.read, "Nachricht auf der Mailbox: „Guten Tag, Herr Weber, hier ist die Praxis Dr. Sommer. Ihr Termin am Dienstag um neun Uhr fällt leider aus, weil der Arzt krank ist. Bitte rufen Sie uns zurück. Wir sind heute bis 18 Uhr erreichbar.“ Was ist mit dem Termin am Dienstag?", ["Er findet nicht statt.","Er dauert bis 18 Uhr.","Er ist eine Stunde später."], ["What about the appointment on Tuesday?","Что с приёмом во вторник?","Що з прийомом у вівторок?","Salı günkü randevuya ne oldu?"], {"c":"p3_mailbox"}),
        mc("Z1", "Was tun?", I.read, "Nachricht auf der Mailbox: „Guten Tag, Herr Weber, hier ist die Praxis Dr. Sommer. Ihr Termin am Dienstag um neun Uhr fällt leider aus, weil der Arzt krank ist. Bitte rufen Sie uns zurück. Wir sind heute bis 18 Uhr erreichbar.“ Was soll Herr Weber tun?", ["Er soll die Praxis anrufen.","Er soll am Dienstag kommen.","Er soll eine E-Mail schreiben."], ["What should Mr Weber do?","Что должен сделать господин Weber?","Що має зробити пан Weber?","Weber Bey ne yapmalı?"], {"c":"p3_mailbox"}),
        mc('Z1', 'Warum?', I.read, `${PAUL} Warum kommt Paul nicht zum Training?`, ['Sein Zug kommt zu spät.', 'Er ist krank.', 'Er hat keine Lust.'],
          ['Why is Paul not coming to training?', 'Почему Paul не придёт на тренировку?', 'Чому Paul не прийде на тренування?', 'Paul neden antrenmana gelmiyor?']),
        mc('Z1', 'Wann?', I.read, `${PAUL} Wann meldet sich Paul wieder?`, ['Am nächsten Tag.', 'In einer Stunde.', 'Heute Abend.'],
          ['When will Paul be in touch again?', 'Когда Paul снова свяжется?', 'Коли Paul знову зв’яжеться?', 'Paul ne zaman yine haber verecek?']),
        mc('Z1', 'Entschuldigung', I.read, `${PAUL} Wie beginnt Paul seine Entschuldigung?`, ['Mit „Es tut mir leid“.', 'Mit „Vielen Dank“.', 'Mit „Gute Besserung“.'],
          ['How does Paul begin his apology?', 'С чего Paul начинает извинение?', 'З чого Paul починає вибачення?', 'Paul özrüne nasıl başlıyor?']),
        gap('Z1', 'ausfallen', I.word, 'Der Kurs findet heute nicht statt. Er fällt ', '.', 'aus', ['ab', 'an'],
          ['The course is not taking place today. It is cancelled.', 'Занятие сегодня не состоится. Оно отменяется.', 'Заняття сьогодні не відбудеться. Його скасовано.', 'Kurs bugün yapılmıyor. İptal oldu.'], 'ausfallen'),
      ],
    },
  ],
}

export default path
