import { I, gap, mc, sb } from '../shared.mjs'

const A7 = 'Verkehrsnachrichten: „Auf der A7 zwischen Kassel und Göttingen ist die Straße nach einem Unfall mit einem Lastwagen gesperrt. Die Sperrung dauert bis etwa 15 Uhr. Eine Umleitung ist ausgeschildert.“'
const STADTFEST = 'Verkehrsnachrichten: „In der Innenstadt ist die Hauptstraße bis Sonntagabend gesperrt, weil dort das Stadtfest stattfindet. Die Busse fahren eine Umleitung und halten nicht am Marktplatz. Bitte benutzen Sie die Haltestelle am Bahnhof.“'
const NEBEL = 'Wetterbericht: „Am Morgen gibt es im Süden dichten Nebel. Fahren Sie bitte vorsichtig! Ab Mittag scheint die Sonne. Die Temperaturen steigen auf 12 Grad. Im Norden ist es den ganzen Tag wolkig, aber trocken.“'
const NORDSEE = 'Wetterbericht: „Heute Nacht kommt ein Sturm von der Nordsee. An der Küste ist es sehr windig. Bleiben Sie bitte zu Hause! Morgen Mittag ist der Sturm vorbei, dann regnet es nur noch leicht.“'

/** A2.2 · Pfad 4 · Unterwegs – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Gewitter', I.choose, 'Blitz und Donner gehören zu einem …', ['Gewitter', 'Stau', 'Nebel'],
      ['Lightning and thunder are part of a …', 'Молния и гром бывают во время …', 'Блискавка й грім бувають під час …', 'Şimşek ve gök gürültüsü bir … parçasıdır.']),
    mc('W2', 'Kreisverkehr', I.choose, 'Die Autos fahren im Kreis um eine Insel in der Mitte. Das ist ein …', ['Kreisverkehr', 'Stau', 'Führerschein'],
      ['The cars drive in a circle round an island in the middle. That is a …', 'Машины едут по кругу вокруг островка в центре. Это …', 'Машини їдуть по колу навколо острівця в центрі. Це …', 'Arabalar ortadaki adanın etrafında daire çizerek gidiyor. Bu bir …']),
    mc('G1', 'aus dem', I.choose, 'Ich komme gerade … Supermarkt.', ['aus dem', 'von der', 'aus der'],
      ['I have just come out of the supermarket.', 'Я только что из супермаркета.', 'Я щойно із супермаркету.', 'Şimdi süpermarketten geliyorum.']),
    mc('G3', 'gegenüber + Dativ', I.choose, 'Die Post ist gegenüber … Bahnhof.', ['dem', 'den', 'der'],
      ['The post office is opposite the station.', 'Почта находится напротив вокзала.', 'Пошта розташована навпроти вокзалу.', 'Postane istasyonun karşısında.']),
    mc('G5', 'trinkbar', I.choose, 'Das Wasser kann man trinken. Es ist …', ['trinkbar', 'trinkig', 'trinkisch'],
      ['You can drink the water. It is …', 'Эту воду можно пить. Она …', 'Цю воду можна пити. Вона …', 'Bu su içilebilir. Su …']),
    mc('K1', 'bis zur Ampel', I.situation, 'Jemand sucht die Apotheke. Sie ist nach der Ampel auf der linken Straßenseite. Was sagst du?', ['Gehen Sie bis zur Ampel und dann nach links.', 'Gehen Sie durch die Ampel.', 'Steigen Sie an der Ampel aus dem Bus.'],
      ['Someone is looking for the chemist’s. It is after the traffic lights on the left-hand side of the street. What do you say?', 'Кто-то ищет аптеку. Она находится после светофора на левой стороне улицы. Что вы скажете?', 'Хтось шукає аптеку. Вона розташована після світлофора на лівому боці вулиці. Що ви скажете?', 'Biri eczaneyi arıyor. Eczane trafik ışığından sonra caddenin sol tarafında. Ne dersiniz?']),
    mc('K2', 'weniger … als', I.situation, 'In deiner Heimat gibt es nicht so viele Fahrräder. Was sagst du?', ['Bei uns gibt es weniger Fahrräder als hier.', 'Bei uns gibt es mehr Fahrräder als hier.', 'Bei uns ist das genauso wie hier.'],
      ['In your home country there are not as many bikes. What do you say?', 'На вашей родине не так много велосипедов. Что вы скажете?', 'На вашій батьківщині не так багато велосипедів. Що ви скажете?', 'Memleketinizde o kadar çok bisiklet yok. Ne dersiniz?']),
    mc('Z1', 'Wie lange?', I.read, `${A7} Wie lange ist die Autobahn gesperrt?`, ['Bis ungefähr 15 Uhr.', '15 Minuten.', 'Den ganzen Tag.'],
      ['How long is the motorway closed?', 'До какого времени перекрыта автомагистраль?', 'До котрої години перекрито автомагістраль?', 'Otoyol ne zamana kadar kapalı?']),
    mc('Z2', 'Wann?', I.read, `${NEBEL} Wann ist es im Süden neblig?`, ['Am Morgen.', 'Ab Mittag.', 'Den ganzen Tag.'],
      ['When is it foggy in the south?', 'Когда на юге туман?', 'Коли на півдні туман?', 'Güneyde hava ne zaman sisli?']),
    gap("G1", "vom Training", I.prep, "Milan kommt gerade ", " Training. Er ist sehr müde.", "vom", ["beim","aus"], ["Milan has just come from training. He is very tired.","Milan только что с тренировки. Он очень устал.","Milan щойно з тренування. Він дуже втомився.","Milan şimdi antrenmandan geliyor. Çok yorgun."], "von + dem", {"c":"p4_woher"}),
    gap('G2', 'über', I.prep, 'Gehen Sie ', ' die Brücke und dann nach rechts.', 'über', ['aus', 'von'],
      ['Go across the bridge and then right.', 'Идите через мост, а потом направо.', 'Ідіть через міст, а потім праворуч.', 'Köprüyü geçin, sonra sağa dönün.'], 'über / aus / von'),
    gap('G4', 'Verb auf Position 2', I.verb, 'Der Bus kommt nicht. Deshalb ', ' wir zu Fuß.', 'gehen', ['geht', 'gegangen'],
      ['The bus is not coming. That is why we are walking.', 'Автобус не едет. Поэтому мы идём пешком.', 'Автобус не їде. Тому ми йдемо пішки.', 'Otobüs gelmiyor. Bu yüzden yürüyerek gidiyoruz.'],
      ['go', 'идти', 'іти', 'gitmek']),
    sb('G4', 'deshalb nach dem Verb', I.order, 'Ich / nehme / deshalb / das Fahrrad.',
      ['That is why I am taking the bike.', 'Поэтому я еду на велосипеде.', 'Тому я їду на велосипеді.', 'Bu yüzden bisikletle gidiyorum.'],
      { alt: ['Deshalb nehme ich das Fahrrad.'] }),
  ],
  size: 13,
  test: [
    mc('W1', 'stürmisch', I.choose, 'Der Wind ist heute sehr stark. Das Wetter ist …', ['stürmisch', 'sonnig', 'neblig'],
      ['The wind is very strong today. The weather is …', 'Сегодня очень сильный ветер. Погода …', 'Сьогодні дуже сильний вітер. Погода …', 'Bugün rüzgâr çok kuvvetli. Hava …']),
    mc('W2', 'Führerschein', I.choose, 'Was braucht man, wenn man Auto fahren will?', ['einen Führerschein', 'eine Umleitung', 'eine Baustelle'],
      ['What do you need if you want to drive a car?', 'Что нужно, чтобы водить машину?', 'Що потрібно, щоб водити машину?', 'Araba kullanmak isteyen kişiye ne gerekir?']),
    mc('G1', 'aus dem Zug', I.choose, 'Wir steigen … Zug aus.', ['aus dem', 'vom', 'aus der'],
      ['We are getting off the train.', 'Мы выходим из поезда.', 'Ми виходимо з потяга.', 'Trenden iniyoruz.']),
    mc('G1', 'von der Arbeit', I.choose, 'Woher kommst du so spät? – … Arbeit.', ['Von der', 'Aus der', 'Vom'],
      ['Where are you coming from so late? – From work.', 'Откуда ты так поздно? – С работы.', 'Звідки ти так пізно? – З роботи.', 'Bu kadar geç nereden geliyorsun? – İşten.']),
    mc('G2', 'durch', I.choose, 'Der Hund läuft … den Garten.', ['durch', 'gegenüber', 'vorbei'],
      ['The dog is running through the garden.', 'Собака бежит через сад.', 'Собака біжить через сад.', 'Köpek bahçenin içinden koşuyor.']),
    mc('G2', 'um + Akkusativ', I.choose, 'Wir fahren um … See herum.', ['den', 'dem', 'der'],
      ['We are driving round the lake.', 'Мы едем вокруг озера.', 'Ми їдемо навколо озера.', 'Gölün etrafından dolaşıyoruz.']),
    mc('G3', 'an + Dativ … vorbei', I.choose, 'Wir fahren an … Schule vorbei.', ['der', 'die', 'den'],
      ['We are driving past the school.', 'Мы проезжаем мимо школы.', 'Ми проїжджаємо повз школу.', 'Okulun önünden geçiyoruz.']),
    mc('G4', 'Deshalb', I.choose, 'Ich habe verschlafen. … komme ich zu spät zur Arbeit.', ['Deshalb', 'Trotzdem', 'Weil'],
      ['I overslept. That is why I am late for work.', 'Я проспал. Поэтому я опаздываю на работу.', 'Я проспав. Тому я запізнююся на роботу.', 'Uyuyakalmışım. Bu yüzden işe geç kalıyorum.']),
    mc('G4', 'Verb auf Position 2', I.sentence, 'Es gibt Glatteis.', ['Deshalb fahren alle Autos langsam.', 'Deshalb alle Autos fahren langsam.', 'Deshalb alle Autos langsam fahren.'],
      ['There is black ice.', 'На дорогах гололёд.', 'На дорогах ожеледиця.', 'Yollarda buzlanma var.']),
    mc('G5', 'regnerisch', I.choose, 'Wie heißt das Adjektiv zu „der Regen“?', ['regnerisch', 'regenbar', 'regenlich'],
      ['What is the adjective for “der Regen”?', 'Какое прилагательное образуется от «der Regen»?', 'Який прикметник утворюється від «der Regen»?', '“der Regen” isminin sıfatı nedir?']),
    mc('K1', 'Wo ist …?', I.react, '„Entschuldigung, wo ist die nächste Tankstelle?“', ['Fahren Sie geradeaus und nach der Brücke rechts.', 'Die Tankstelle ist sehr teuer.', 'Ich komme von der Tankstelle.'],
      ['“Excuse me, where is the nearest petrol station?”', '«Извините, где ближайшая заправка?»', '«Перепрошую, де найближча заправка?»', '“Affedersiniz, en yakın benzin istasyonu nerede?”']),
    mc('K1', 'mit der Bahn', I.choose, 'Du erklärst den Weg mit der Bahn. Was passt?', ['Nimm die S3 und fahr bis zum Marktplatz.', 'Geh durch die S3 bis zum Marktplatz.', 'Bieg an der S3 ab.'],
      ['You are explaining the way by train. What fits?', 'Вы объясняете, как доехать на электричке. Что подходит?', 'Ви пояснюєте, як доїхати електричкою. Що підходить?', 'Trenle nasıl gidileceğini anlatıyorsunuz. Hangisi uygun?']),
    mc('K2', 'Mir ist aufgefallen', I.react, '„Was ist Ihnen in Deutschland aufgefallen?“', ['Mir ist aufgefallen, dass die Leute sehr pünktlich sind.', 'Ich bin gestern gefallen.', 'Mir gefällt das Auto.'],
      ['“What have you noticed in Germany?”', '«Что вы заметили в Германии?»', '«Що ви помітили в Німеччині?»', '“Almanya’da dikkatinizi ne çekti?”']),
    mc('Z1', 'Was ist passiert?', I.read, `${A7} Was ist auf der A7 passiert?`, ['Ein Lastwagen hatte einen Unfall.', 'Es gibt eine Baustelle.', 'Es gibt dichten Nebel.'],
      ['What has happened on the A7?', 'Что произошло на трассе A7?', 'Що сталося на трасі A7?', 'A7’de ne oldu?']),
    mc('Z1', 'Warum?', I.read, `${STADTFEST} Warum ist die Hauptstraße gesperrt?`, ['Dort ist ein Fest.', 'Dort ist ein Unfall passiert.', 'Dort ist eine Baustelle.'],
      ['Why is the main street closed?', 'Почему перекрыта главная улица?', 'Чому перекрито головну вулицю?', 'Ana cadde neden kapalı?']),
    mc('Z1', 'Wo einsteigen?', I.read, `${STADTFEST} Wo sollen die Leute in den Bus steigen?`, ['Am Bahnhof.', 'Am Marktplatz.', 'In der Hauptstraße.'],
      ['Where should people get on the bus?', 'Где людям нужно садиться в автобус?', 'Де людям треба сідати в автобус?', 'İnsanlar otobüse nereden binmeli?']),
    mc('Z2', 'im Norden', I.read, `${NEBEL} Wie ist das Wetter im Norden?`, ['Wolkig, aber ohne Regen.', 'Sonnig und warm.', 'Neblig und nass.'],
      ['What is the weather like in the north?', 'Какая погода на севере?', 'Яка погода на півночі?', 'Kuzeyde hava nasıl?']),
    mc('Z2', 'Was tun?', I.read, `${NORDSEE} Was soll man in der Nacht tun?`, ['Man soll nicht nach draußen gehen.', 'Man soll an die Küste fahren.', 'Man soll die Fenster öffnen.'],
      ['What should you do during the night?', 'Что нужно делать ночью?', 'Що треба робити вночі?', 'Gece ne yapmak gerekiyor?']),
    mc('Z2', 'morgen Mittag', I.read, `${NORDSEE} Wie ist das Wetter morgen Mittag?`, ['Es regnet ein bisschen.', 'Es ist stürmisch.', 'Es schneit.'],
      ['What is the weather like at midday tomorrow?', 'Какая погода будет завтра в полдень?', 'Яка погода буде завтра опівдні?', 'Yarın öğlen hava nasıl?']),
    gap('W1', 'Nebel', I.word, 'Ich sehe die Straße kaum. Der ', ' ist heute sehr dicht.', 'Nebel', ['Sturm', 'Schnee'],
      ['I can hardly see the road. The fog is very thick today.', 'Я почти не вижу дорогу. Сегодня очень густой туман.', 'Я майже не бачу дороги. Сьогодні дуже густий туман.', 'Yolu zor görüyorum. Bugün sis çok yoğun.'],
      ['fog', 'туман', 'туман', 'sis']),
    gap('W2', 'Ausfahrt', I.word, 'An der nächsten ', ' fahren wir von der Autobahn ab.', 'Ausfahrt', ['Ampel', 'Brücke'],
      ['At the next exit we leave the motorway.', 'На следующем съезде мы съезжаем с автомагистрали.', 'На наступному з’їзді ми з’їжджаємо з автомагістралі.', 'Bir sonraki çıkışta otoyoldan ayrılıyoruz.'],
      ['exit', 'съезд', 'з’їзд', 'çıkış']),
    gap('G1', 'aus dem Kühlschrank', I.prep, 'Nimm bitte die Milch ', ' dem Kühlschrank.', 'aus', ['von', 'nach'],
      ['Please take the milk out of the fridge.', 'Достань, пожалуйста, молоко из холодильника.', 'Дістань, будь ласка, молоко з холодильника.', 'Lütfen sütü buzdolabından çıkar.'], 'aus / von / nach'),
    gap('G2', 'entlang', I.word, 'Gehen Sie den Fluss ', ' bis zum Museum.', 'entlang', ['herum', 'vorbei'],
      ['Walk along the river as far as the museum.', 'Идите вдоль реки до музея.', 'Ідіть уздовж річки до музею.', 'Nehir boyunca müzeye kadar yürüyün.'],
      ['along', 'вдоль', 'уздовж', 'boyunca']),
    gap('G3', 'bis zum', I.prep, 'Gehen Sie bis ', ' Rathaus und dann nach links.', 'zum', ['zur', 'zu'],
      ['Go as far as the town hall and then left.', 'Идите до ратуши, а потом налево.', 'Ідіть до ратуші, а потім ліворуч.', 'Belediye binasına kadar gidin, sonra sola dönün.'], 'zu + dem'),
    gap('G3', 'gegenüber', I.prep, 'Die Bank ist direkt ', ' der Bäckerei, auf der anderen Straßenseite.', 'gegenüber', ['entlang', 'herum'],
      ['The bank is directly opposite the bakery, on the other side of the street.', 'Банк находится прямо напротив пекарни, на другой стороне улицы.', 'Банк розташований просто навпроти пекарні, на іншому боці вулиці.', 'Banka fırının tam karşısında, caddenin öbür tarafında.'],
      ['opposite', 'напротив', 'навпроти', 'karşısında']),
    gap('G5', 'erreichbar', I.form, 'Du kannst mich immer anrufen. Ich bin immer ', '.', 'erreichbar', ['erreichig', 'erreichen'],
      ['You can always call me. I am always reachable.', 'Ты всегда можешь мне позвонить. Я всегда на связи.', 'Ти завжди можеш мені зателефонувати. Я завжди на зв’язку.', 'Beni her zaman arayabilirsin. Her zaman ulaşılabilirim.'], 'erreichen'),
    gap('G5', 'neblig', I.form, 'Heute gibt es viel Nebel. Es ist sehr ', '.', 'neblig', ['neblisch', 'nebelbar'],
      ['There is a lot of fog today. It is very foggy.', 'Сегодня сильный туман. Очень туманно.', 'Сьогодні сильний туман. Дуже туманно.', 'Bugün çok sis var. Hava çok sisli.'], 'der Nebel'),
    gap('K1', 'abbiegen', I.verb, 'Nach der Brücke müssen Sie links ', '.', 'abbiegen', ['aussteigen', 'ankommen'],
      ['After the bridge you have to turn left.', 'После моста вам нужно повернуть налево.', 'Після мосту вам треба повернути ліворуч.', 'Köprüden sonra sola dönmeniz gerekiyor.'],
      ['turn', 'повернуть', 'повернути', 'dönmek']),
    gap('K2', 'genauso wie', I.word, 'In meiner Heimat ist das genauso ', ' hier.', 'wie', ['als', 'so'],
      ['In my home country it is just the same as here.', 'На моей родине это так же, как здесь.', 'На моїй батьківщині це так само, як тут.', 'Memleketimde de bu buradaki gibi.'], 'als / wie'),
    sb('G4', 'Deshalb auf Position 1', I.order, 'Deshalb / bleiben / wir / zu Hause.',
      ['That is why we are staying at home.', 'Поэтому мы остаёмся дома.', 'Тому ми залишаємося вдома.', 'Bu yüzden evde kalıyoruz.'],
      { alt: ['Wir bleiben deshalb zu Hause.'] }),
  ],
}

export default check
