import { I, gap, mc, sb } from '../shared.mjs'

const PENSION = 'Anzeige: „Kleine Pension in zentraler Lage, nur fünf Minuten vom Bahnhof. Zimmer mit eigener Dusche ab 55 Euro pro Nacht. Frühstück kostet 8 Euro extra. Kostenloser Parkplatz hinter dem Haus.“'
const BAUERNHOF = 'Anzeige: „Urlaub auf dem Bauernhof! Gemütliche Ferienwohnungen für vier Personen in schöner Lage auf dem Land. Kinder können bei den Tieren helfen. Frische Eier und Milch gibt es jeden Morgen. Preis: 70 Euro pro Nacht.“'

/** A2.2 · Pfad 5 · Reisen – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Küste', I.choose, 'Wo treffen sich Land und Meer?', ['an der Küste', 'in der Wüste', 'im Gebirge'],
      ['Where do the land and the sea meet?', 'Где встречаются суша и море?', 'Де зустрічаються суша й море?', 'Kara ile deniz nerede buluşur?']),
    mc('W2', 'Ferienwohnung', I.choose, 'In welcher Unterkunft gibt es eine eigene Küche?', ['in der Ferienwohnung', 'im Einzelzimmer', 'im Zelt'],
      ['Which kind of accommodation has its own kitchen?', 'В каком жилье есть собственная кухня?', 'У якому житлі є власна кухня?', 'Hangi konaklama yerinde kendi mutfağı vardır?']),
    mc('G1', 'auf der Insel', I.choose, 'Wir machen dieses Jahr Urlaub … Insel Rügen.', ['auf der', 'auf die', 'in der'],
      ['This year we are on holiday on the island of Rügen.', 'В этом году мы отдыхаем на острове Рюген.', 'Цього року ми відпочиваємо на острові Рюген.', 'Bu yıl tatilimizi Rügen adasında geçiriyoruz.']),
    mc('G3', '-es (das)', I.choose, 'Wir bieten … Frühstück mit Kaffee und Tee.', ['reichhaltiges', 'reichhaltiger', 'reichhaltige'],
      ['We offer a generous breakfast with coffee and tea.', 'Мы предлагаем обильный завтрак с кофе и чаем.', 'Ми пропонуємо ситний сніданок із кавою та чаєм.', 'Kahve ve çayla zengin bir kahvaltı sunuyoruz.']),
    mc('G5', 'über', I.choose, 'Der Zug hatte … zwei Stunden Verspätung. Es waren fast drei Stunden!', ['über', 'ohne', 'von'],
      ['The train was over two hours late. It was almost three hours!', 'Поезд опоздал больше чем на два часа. Почти на три!', 'Потяг запізнився більше ніж на дві години. Майже на три!', 'Tren iki saatten fazla gecikti. Neredeyse üç saat oldu!']),
    mc('G6', 'ohne', I.choose, 'Ich trinke meinen Tee immer … Milch.', ['ohne', 'über', 'aus'],
      ['I always drink my tea without milk.', 'Я всегда пью чай без молока.', 'Я завжди п’ю чай без молока.', 'Çayımı hep sütsüz içerim.']),
    mc('K1', 'Was kostet die Reise?', I.react, '„Was kostet die Reise?“', ['Das macht 320 Euro pro Person.', 'Die Fahrt dauert sechs Stunden.', 'Sie müssen in Ulm umsteigen.'],
      ['“How much is the trip?”', '«Сколько стоит поездка?»', '«Скільки коштує поїздка?»', '“Seyahat ne kadar?”']),
    mc('K2', 'Einladung', I.choose, 'Welcher Satz passt in eine Einladung?', ['Ich möchte Dir so gern meine neue Wohnung zeigen.', 'Der Termin ist leider ausgebucht.', 'Ich bin dagegen.'],
      ['Which sentence belongs in an invitation?', 'Какое предложение подходит для приглашения?', 'Яке речення підходить для запрошення?', 'Hangi cümle bir davete uygun?']),
    mc('Z1', 'extra', I.read, `${PENSION} Was ist im Zimmerpreis nicht dabei?`, ['Das Frühstück.', 'Die Dusche.', 'Der Parkplatz.'],
      ['What is not included in the room price?', 'Что не входит в стоимость номера?', 'Що не входить у вартість номера?', 'Oda fiyatına ne dahil değil?']),
    gap('G2', 'ans Meer', I.prep, 'Im August fahren wir ', ' Meer.', 'ans', ['am', 'im'],
      ['In August we are going to the sea.', 'В августе мы едем на море.', 'У серпні ми їдемо на море.', 'Ağustosta denize gidiyoruz.'], 'an + das'),
    gap('G4', '-em (der)', I.ending, 'Ferienwohnung mit ', ' Balkon zu vermieten.', 'großem', ['großer', 'großen'],
      ['Holiday flat with a big balcony to let.', 'Сдаётся квартира для отдыха с большим балконом.', 'Здається квартира для відпочинку з великим балконом.', 'Büyük balkonlu tatil dairesi kiralıktır.'], 'groß'),
    gap('K3', 'dafür', I.word, 'Wir fahren mit dem Zug? Gute Idee, ich bin ', '.', 'dafür', ['dagegen', 'darauf'],
      ['We are going by train? Good idea, I am in favour.', 'Мы едем на поезде? Хорошая идея, я за.', 'Ми їдемо потягом? Гарна ідея, я за.', 'Trenle mi gidiyoruz? İyi fikir, ben varım.'],
      ['in favour', 'за', 'за', 'taraftarım']),
    sb('G2', 'aufs Land', I.order, 'Am Wochenende / fahren / wir / aufs Land.',
      ['At the weekend we are going to the countryside.', 'В выходные мы едем за город.', 'У вихідні ми їдемо за місто.', 'Hafta sonu kırsala gidiyoruz.'],
      { alt: ['Wir fahren am Wochenende aufs Land.', 'Aufs Land fahren wir am Wochenende.'] }),
  ],
  size: 13,
  test: [
    mc('W1', 'Strand', I.choose, 'Sand, Sonne, Meer: Wir sind am …', ['Strand', 'Gebirge', 'Wald'],
      ['Sand, sun, sea: we are on the …', 'Песок, солнце, море: мы на …', 'Пісок, сонце, море: ми на …', 'Kum, güneş, deniz: Biz …']),
    mc('W2', 'Doppelzimmer', I.choose, 'Zwei Personen reisen zusammen und möchten ein Zimmer. Sie buchen ein …', ['Doppelzimmer', 'Einzelzimmer', 'Zelt'],
      ['Two people are travelling together and would like one room. They book a …', 'Два человека путешествуют вместе и хотят один номер. Они бронируют …', 'Двоє людей подорожують разом і хочуть один номер. Вони бронюють …', 'İki kişi birlikte seyahat ediyor ve tek bir oda istiyor. Şunu ayırtıyorlar: …']),
    mc('G1', 'im Gebirge', I.choose, 'Wo liegt das Hotel? – … Gebirge.', ['Im', 'Ins', 'In den'],
      ['Where is the hotel? – In the mountains.', 'Где находится отель? – В горах.', 'Де розташований готель? – У горах.', 'Otel nerede? – Dağlarda.']),
    mc('G1', 'am See', I.choose, 'Meine Eltern haben ein Haus … See.', ['am', 'ans', 'im'],
      ['My parents have a house by the lake.', 'У моих родителей есть дом у озера.', 'У моїх батьків є будинок біля озера.', 'Annemle babamın göl kenarında bir evi var.']),
    mc('G2', 'auf die Insel', I.choose, 'Wohin fliegt ihr? – … Insel Kreta.', ['Auf die', 'Auf der', 'In der'],
      ['Where are you flying to? – To the island of Crete.', 'Куда вы летите? – На остров Крит.', 'Куди ви летите? – На острів Крит.', 'Nereye uçuyorsunuz? – Girit adasına.']),
    mc('G2', 'in den Schwarzwald', I.choose, 'Nächsten Sommer fahren wir … Schwarzwald.', ['in den', 'im', 'in dem'],
      ['Next summer we are going to the Black Forest.', 'Следующим летом мы едем в Шварцвальд.', 'Наступного літа ми їдемо до Шварцвальду.', 'Gelecek yaz Kara Orman’a gidiyoruz.']),
    mc('G3', '-e (die)', I.choose, 'Im Dorf gibt es … Luft und viel Ruhe.', ['frische', 'frischer', 'frisches'],
      ['In the village there is fresh air and lots of peace and quiet.', 'В деревне свежий воздух и много тишины.', 'У селі свіже повітря й багато тиші.', 'Köyde temiz hava ve bol sessizlik var.']),
    mc('G3', '-en (Akkusativ maskulin)', I.choose, 'Das Café bietet … Kuchen und guten Kaffee.', ['leckeren', 'leckerer', 'leckeres'],
      ['The café offers delicious cake and good coffee.', 'Кафе предлагает вкусный пирог и хороший кофе.', 'Кафе пропонує смачний пиріг і добру каву.', 'Kafe lezzetli kek ve iyi kahve sunuyor.']),
    mc('G4', '-em (das)', I.choose, 'Zimmer mit … Bad und Balkon.', ['eigenem', 'eigener', 'eigenen'],
      ['Room with its own bathroom and balcony.', 'Номер с собственной ванной и балконом.', 'Номер із власною ванною й балконом.', 'Kendi banyosu ve balkonu olan oda.']),
    mc('G4', '-er (die)', I.choose, 'Hotel in … Lage direkt am Marktplatz.', ['zentraler', 'zentralem', 'zentralen'],
      ['Hotel in a central location right on the market square.', 'Отель в центре, прямо на рыночной площади.', 'Готель у центрі, просто на ринковій площі.', 'Tam pazar meydanında, merkezî konumda otel.']),
    mc('G5', 'von … an', I.choose, 'Von nächster Woche … bin ich im Urlaub.', ['an', 'aus', 'bis'],
      ['From next week on I am on holiday.', 'Со следующей недели я в отпуске.', 'Від наступного тижня я у відпустці.', 'Gelecek haftadan itibaren tatildeyim.']),
    mc('G6', 'ohne + Akkusativ', I.choose, 'Im Urlaub möchte ich Ruhe: ein Hotel ohne … Musik.', ['laute', 'lauter', 'lautem'],
      ['On holiday I want peace and quiet: a hotel without loud music.', 'В отпуске я хочу покоя: отель без громкой музыки.', 'У відпустці я хочу спокою: готель без гучної музики.', 'Tatilde huzur istiyorum: yüksek sesli müzik olmayan bir otel.']),
    mc('K1', 'Wie lange dauert …?', I.react, '„Wie lange dauert denn die Fahrt?“', ['Etwa fünf Stunden. Sie sind um 15 Uhr am Ziel.', 'Etwa 200 Euro.', 'Für drei Personen.'],
      ['“How long does the journey take?”', '«Сколько длится поездка?»', '«Скільки триває поїздка?»', '“Yolculuk ne kadar sürüyor?”']),
    mc('K1', 'Direktverbindung', I.situation, 'Du möchtest wissen: Muss ich umsteigen? Was fragst du?', ['Ist das eine Direktverbindung?', 'Ist das eine Ferienwohnung?', 'Ist der Termin ausgebucht?'],
      ['You want to know: do I have to change? What do you ask?', 'Вы хотите узнать, нужно ли делать пересадку. Что вы спросите?', 'Ви хочете дізнатися, чи треба робити пересадку. Що ви запитаєте?', 'Öğrenmek istiyorsunuz: Aktarma yapmam gerekiyor mu? Ne sorarsınız?']),
    mc('K2', 'Lust auf', I.choose, 'Hast Du Lust … einen Stadtbummel?', ['auf', 'für', 'an'],
      ['Do you fancy a stroll round town?', 'Хочешь прогуляться по городу?', 'Хочеш прогулятися містом?', 'Şehirde biraz dolaşmak ister misin?']),
    mc('K3', 'Darf ich einen Vorschlag machen?', I.react, '„Darf ich einen Vorschlag machen?“', ['Ja, gern. Was denn?', 'Nein, ich bin dafür.', 'Ich freue mich auf Dich.'],
      ['“May I make a suggestion?”', '«Можно мне кое-что предложить?»', '«Можна мені дещо запропонувати?»', '“Bir öneride bulunabilir miyim?”']),
    mc('Z1', 'Wie weit?', I.read, `${PENSION} Wie weit ist es zum Bahnhof?`, ['Fünf Minuten.', '55 Minuten.', 'Acht Minuten.'],
      ['How far is it to the station?', 'Как далеко до вокзала?', 'Як далеко до вокзалу?', 'İstasyon ne kadar uzakta?']),
    mc('Z1', 'Für wie viele?', I.read, `${BAUERNHOF} Für wie viele Personen ist eine Ferienwohnung?`, ['Für vier.', 'Für zwei.', 'Für sieben.'],
      ['How many people is a holiday flat for?', 'На сколько человек рассчитана квартира?', 'На скільки осіб розрахована квартира?', 'Bir tatil dairesi kaç kişilik?']),
    mc('Z1', 'Was machen?', I.read, `${BAUERNHOF} Was können Kinder dort machen?`, ['Sie können bei den Tieren helfen.', 'Sie können im Meer schwimmen.', 'Sie können ins Kino gehen.'],
      ['What can children do there?', 'Чем там могут заняться дети?', 'Чим там можуть зайнятися діти?', 'Çocuklar orada ne yapabilir?']),
    gap('W1', 'Insel', I.word, 'Sylt ist eine ', ' in der Nordsee.', 'Insel', ['Wüste', 'Küste'],
      ['Sylt is an island in the North Sea.', 'Зильт – остров в Северном море.', 'Зильт – острів у Північному морі.', 'Sylt Kuzey Denizi’nde bir adadır.'],
      ['island', 'остров', 'острів', 'ada']),
    gap('W2', 'Zelt', I.word, 'Wir haben ein ', ' und schlafen auf dem Campingplatz.', 'Zelt', ['Hotel', 'Zimmer'],
      ['We have a tent and sleep on the campsite.', 'У нас есть палатка, и мы ночуем в кемпинге.', 'У нас є намет, і ми ночуємо в кемпінгу.', 'Bir çadırımız var ve kamp alanında uyuyoruz.'],
      ['tent', 'палатка', 'намет', 'çadır']),
    gap('G1', 'in der Wüste', I.prep, 'Wir waren letztes Jahr ', ' der Wüste.', 'in', ['an', 'auf'],
      ['Last year we were in the desert.', 'В прошлом году мы были в пустыне.', 'Минулого року ми були в пустелі.', 'Geçen yıl çöldeydik.'], 'in / an / auf'),
    gap('G2', 'aufs Land', I.prep, 'Am Sonntag fahren wir ', ' Land zu Oma und Opa.', 'aufs', ['auf', 'am'],
      ['On Sunday we are going to the countryside to see Grandma and Grandad.', 'В воскресенье мы едем в деревню к бабушке и дедушке.', 'У неділю ми їдемо в село до бабусі й дідуся.', 'Pazar günü kırsala, büyükannemle büyükbabama gidiyoruz.'], 'auf + das'),
    gap('G3', '-es (das)', I.ending, '', ' Hotel direkt am Strand!', 'Kleines', ['Kleiner', 'Kleine'],
      ['Small hotel right on the beach!', 'Небольшой отель прямо на пляже!', 'Невеликий готель просто на пляжі!', 'Tam plajın yanında küçük otel!'], 'klein'),
    gap('G4', '-en (Plural)', I.ending, 'Wir kochen nur mit ', ' Produkten aus der Region.', 'frischen', ['frischer', 'frischem'],
      ['We cook only with fresh produce from the region.', 'Мы готовим только из свежих местных продуктов.', 'Ми готуємо лише зі свіжих місцевих продуктів.', 'Sadece bölgeden gelen taze ürünlerle yemek yapıyoruz.'], 'frisch'),
    gap('G5', 'über', I.prep, 'Wir haben ', ' drei Stunden am Flughafen gewartet – fast vier!', 'über', ['unter', 'ohne'],
      ['We waited at the airport for over three hours – almost four!', 'Мы прождали в аэропорту больше трёх часов – почти четыре!', 'Ми прочекали в аеропорту понад три години – майже чотири!', 'Havalimanında üç saatten fazla bekledik – neredeyse dört!'], 'über / unter / ohne'),
    gap('G6', 'ohne + Akkusativ', I.possessive, 'Ohne ', ' Pass kannst du nicht fliegen.', 'deinen', ['deinem', 'dein'],
      ['You cannot fly without your passport.', 'Без паспорта ты не сможешь полететь.', 'Без паспорта ти не зможеш полетіти.', 'Pasaportun olmadan uçamazsın.'], 'dein'),
    gap('K1', 'ausgebucht', I.word, 'Der Bus ist leider schon ', '. Es gibt keinen Platz mehr.', 'ausgebucht', ['ausgefüllt', 'ausgegeben'],
      ['Unfortunately the coach is already fully booked. There are no seats left.', 'К сожалению, в автобусе уже нет мест. Свободных мест не осталось.', 'На жаль, в автобусі вже немає місць. Вільних місць не залишилося.', 'Otobüs maalesef dolmuş. Boş yer kalmadı.'],
      ['fully booked', 'все места заняты', 'усі місця зайняті', 'tamamen dolu']),
    gap('K2', 'zeigen', I.verb, 'Ich möchte Dir so gern den neuen Zoo ', '.', 'zeigen', ['sehen', 'probieren'],
      ['I would so like to show you the new zoo.', 'Мне так хочется показать тебе новый зоопарк.', 'Мені так хочеться показати тобі новий зоопарк.', 'Sana yeni hayvanat bahçesini göstermeyi çok istiyorum.'],
      ['show', 'показать', 'показати', 'göstermek']),
    gap('K3', 'keine Lust', I.word, 'Ach nein, darauf habe ich keine ', '. Ich möchte lieber zu Hause bleiben.', 'Lust', ['Idee', 'Angst'],
      ['Oh no, I do not feel like that. I would rather stay at home.', 'Ой нет, этого мне не хочется. Я лучше останусь дома.', 'Ой ні, цього мені не хочеться. Я краще залишуся вдома.', 'Yok ya, hiç canım istemiyor. Evde kalmayı tercih ederim.'],
      ['desire', 'желание', 'бажання', 'istek']),
  ],
}

export default check
