import { I, gap, mc, sb } from '../shared.mjs'

const HOTEL = 'Anzeige: „Familienfreundliches Hotel in ruhiger Lage am Bodensee. Große Zimmer mit schönem Blick auf den See. Reichhaltiges Frühstück mit regionalen Produkten. Kinder unter sechs Jahren schlafen kostenlos. Von Oktober an günstige Preise!“'
const CAMPING = 'Anzeige: „Campingplatz ‚Waldblick‘ im Schwarzwald. Ruhige Plätze für Zelte und Wohnwagen direkt am Wald. Kleiner Laden mit frischen Brötchen. Hunde sind willkommen. Geöffnet von April bis Oktober.“'

/** A2.2 · Pfad 5 · Reisen – Lektionen. Wiederholung und Test: p5-check.mjs */
const path = {
  n: 5,
  slug: 'reisen',
  title: 'Reisen',
  t: ['Travelling', 'Путешествия', 'Подорожі', 'Seyahat'],
  objectives: {
    G1: 'Wo? + Dativ: am Meer, an der Küste, auf dem Land, auf der Insel, im Gebirge, in der Wüste, in den Bergen.',
    G2: 'Wohin? + Akkusativ: ans Meer, an die Küste, aufs Land, auf die Insel, ins Gebirge, in die Wüste, in die Berge.',
    G3: 'Adjektive ohne Artikel im Nominativ und Akkusativ: schöner Blick, leckeres Frühstück, schöne Lage, regionale Produkte – schönen Blick.',
    G4: 'Adjektive ohne Artikel im Dativ: mit schönem Blick, mit leckerem Frühstück, in schöner Lage, mit regionalen Produkten.',
    G5: 'Zeitangaben mit von … an (+ Dativ) und über (+ Akkusativ): von Oktober an, über eine Stunde.',
    G6: 'ohne + Akkusativ: ohne lauten Verkehr, ohne mein Handy, ohne meine Familie.',
    K1: 'Eine Reise buchen: Ich möchte eine Reise nach … buchen. Für zwei Personen. Was kostet die Reise? Ist das eine Direktverbindung?',
    K2: 'Eine Einladung schreiben: Komm doch mal nach … Du bist herzlich eingeladen. Ich möchte Dir so gern … zeigen. Ich freue mich auf Dich!',
    K3: 'Einen Ausflug planen und auf Vorschläge reagieren: Wollen wir …? Lass uns doch … Ich bin dafür. Ich bin dagegen.',
    Z1: 'Kann-Ziele: Anzeigen für Hotels und Unterkünfte verstehen.',
    W1: 'Wortschatz: Regionen und Landschaften.',
    W2: 'Wortschatz: Unterkünfte.',
  },
  nodes: [
    {
      title: 'Landschaften',
      t: ['Landscapes', 'Природа и регионы', 'Природа й регіони', 'Bölgeler ve doğa'],
      card: {
        id: 'p5_landschaft',
        rule: 'Regionen und Landschaften: das Meer, der Strand, die Küste (dort trifft das Land auf das Meer), die Insel (Land mitten im Wasser), der See, der Fluss, der Berg, die Berge, das Gebirge (viele hohe Berge), der Wald, die Wüste (heiß und trocken, viel Sand), der Dschungel (ein dichter, warmer Wald), das Land (nicht die Stadt), der Atlantik, die Nordsee, die Ostsee, der Schwarzwald.',
        examples: ['Im Sommer fahren wir ans Meer.', 'In der Wüste regnet es fast nie.', 'Die Insel Rügen liegt in der Ostsee.'],
        highlight: 'article',
        t: [
          'Regions and landscapes: das Meer (sea), der Strand (beach), die Küste (coast: where the land meets the sea), die Insel (island: land in the middle of the water), der See (lake), der Fluss (river), der Berg (mountain), die Berge (mountains), das Gebirge (mountain range: many high mountains), der Wald (forest), die Wüste (desert: hot and dry, lots of sand), der Dschungel (jungle: a dense, warm forest), das Land (the countryside, not the town), der Atlantik (the Atlantic), die Nordsee (the North Sea), die Ostsee (the Baltic), der Schwarzwald (the Black Forest).',
          'Регионы и природа: das Meer (море), der Strand (пляж), die Küste (побережье: там суша встречается с морем), die Insel (остров: суша посреди воды), der See (озеро), der Fluss (река), der Berg (гора), die Berge (горы), das Gebirge (горный массив: много высоких гор), der Wald (лес), die Wüste (пустыня: жарко и сухо, много песка), der Dschungel (джунгли: густой тёплый лес), das Land (сельская местность, не город), der Atlantik (Атлантика), die Nordsee (Северное море), die Ostsee (Балтийское море), der Schwarzwald (Шварцвальд).',
          'Регіони й природа: das Meer (море), der Strand (пляж), die Küste (узбережжя: там суша зустрічається з морем), die Insel (острів: суша посеред води), der See (озеро), der Fluss (річка), der Berg (гора), die Berge (гори), das Gebirge (гірський масив: багато високих гір), der Wald (ліс), die Wüste (пустеля: спекотно й сухо, багато піску), der Dschungel (джунглі: густий теплий ліс), das Land (сільська місцевість, не місто), der Atlantik (Атлантика), die Nordsee (Північне море), die Ostsee (Балтійське море), der Schwarzwald (Шварцвальд).',
          'Bölgeler ve doğa: das Meer (deniz), der Strand (plaj), die Küste (kıyı: karayla denizin buluştuğu yer), die Insel (ada: suyun ortasındaki kara), der See (göl), der Fluss (nehir), der Berg (dağ), die Berge (dağlar), das Gebirge (sıradağlar: birçok yüksek dağ), der Wald (orman), die Wüste (çöl: sıcak ve kuru, çok kum), der Dschungel (yağmur ormanı: sık, sıcak bir orman), das Land (kırsal, şehir değil), der Atlantik (Atlas Okyanusu), die Nordsee (Kuzey Denizi), die Ostsee (Baltık Denizi), der Schwarzwald (Kara Orman).',
        ],
        hint: ['Insel = Land im Wasser. Küste = Land am Meer. Gebirge = viele Berge. Wüste = heiß, trocken, Sand.', 'Insel = land in the water. Küste = land by the sea. Gebirge = many mountains. Wüste = hot, dry, sand.', 'Insel = суша в воде. Küste = суша у моря. Gebirge = много гор. Wüste = жарко, сухо, песок.', 'Insel = суша у воді. Küste = суша біля моря. Gebirge = багато гір. Wüste = спекотно, сухо, пісок.', 'Insel = suyun içindeki kara. Küste = deniz kenarındaki kara. Gebirge = birçok dağ. Wüste = sıcak, kuru, kum.'],
      },
      ex: [
        mc('W1', 'Insel', I.choose, 'Ein Stück Land mitten im Meer ist eine …', ['Insel', 'Wüste', 'Küste'],
          ['A piece of land in the middle of the sea is an …', 'Участок суши посреди моря – это …', 'Ділянка суші посеред моря – це …', 'Denizin ortasındaki kara parçası bir …']),
        mc('W1', 'Wüste', I.choose, 'Wo ist es sehr heiß und trocken und es gibt viel Sand?', ['in der Wüste', 'im Gebirge', 'im Wald'],
          ['Where is it very hot and dry, with lots of sand?', 'Где очень жарко и сухо и много песка?', 'Де дуже спекотно й сухо і багато піску?', 'Nerede hava çok sıcak ve kuru, her yer kumdur?']),
        mc('W1', 'Gebirge', I.choose, 'Viele hohe Berge zusammen sind ein …', ['Gebirge', 'Strand', 'See'],
          ['Many high mountains together are a …', 'Много высоких гор вместе – это …', 'Багато високих гір разом – це …', 'Birçok yüksek dağ bir arada bir …']),
        mc('W1', 'Landschaften', I.odd, 'Drei Wörter sind Landschaften, ein Wort nicht.', ['Führerschein', 'Wüste', 'Küste', 'Gebirge'], null),
        mc('W1', 'auf dem Land', I.choose, 'Was bedeutet „auf dem Land leben“?', ['in einem Dorf leben, nicht in der Stadt', 'auf einer Insel leben', 'in einem anderen Land leben'],
          ['What does “auf dem Land leben” mean?', 'Что значит «auf dem Land leben»?', 'Що означає «auf dem Land leben»?', '“auf dem Land leben” ne demek?']),
        gap('W1', 'Strand', I.word, 'Wir liegen in der Sonne am ', ' und hören das Meer.', 'Strand', ['Wald', 'Berg'],
          ['We are lying in the sun on the beach, listening to the sea.', 'Мы лежим на солнце на пляже и слушаем море.', 'Ми лежимо на сонці на пляжі й слухаємо море.', 'Plajda güneşin altında yatıp denizi dinliyoruz.'],
          ['beach', 'пляж', 'пляж', 'plaj']),
        gap('W1', 'Wald', I.word, 'Im ', ' stehen viele Bäume. Dort kann man gut wandern.', 'Wald', ['Strand', 'See'],
          ['There are lots of trees in the forest. It is a good place for hiking.', 'В лесу много деревьев. Там хорошо ходить в походы.', 'У лісі багато дерев. Там добре ходити в походи.', 'Ormanda çok ağaç var. Orada güzel yürüyüş yapılır.'],
          ['forest', 'лес', 'ліс', 'orman']),
        gap('W1', 'Küste', I.word, 'Hamburg liegt nicht direkt am Meer, aber die ', ' ist nicht weit.', 'Küste', ['Wüste', 'Insel'],
          ['Hamburg is not right by the sea, but the coast is not far away.', 'Гамбург находится не у самого моря, но побережье недалеко.', 'Гамбург розташований не біля самого моря, але узбережжя недалеко.', 'Hamburg tam deniz kenarında değil ama kıyı uzak değil.'],
          ['coast', 'побережье', 'узбережжя', 'kıyı']),
        gap('W1', 'See', I.word, 'Der Bodensee ist ein großer ', ' im Süden von Deutschland.', 'See', ['Fluss', 'Berg'],
          ['Lake Constance is a large lake in the south of Germany.', 'Боденское озеро – большое озеро на юге Германии.', 'Боденське озеро – велике озеро на півдні Німеччини.', 'Konstanz Gölü Almanya’nın güneyinde büyük bir göldür.'],
          ['lake', 'озеро', 'озеро', 'göl']),
        sb('W1', 'Insel', I.order, 'Die Insel / liegt / in der / Nordsee.',
          ['The island is in the North Sea.', 'Остров находится в Северном море.', 'Острів розташований у Північному морі.', 'Ada Kuzey Denizi’nde.']),
      ],
    },
    {
      title: 'Wo? – Am Meer.',
      t: ['Where? – By the sea.', 'Где? – На море.', 'Де? – На морі.', 'Nerede? – Deniz kenarında.'],
      card: {
        id: 'p5_wo',
        rule: 'Wo bist du im Urlaub? Wo? + Dativ. an: am Atlantik, am Meer, am See, an der Küste (Wasser und Ufer). auf: auf dem Land, auf der Insel. in: im Schwarzwald, im Gebirge, im Wald, in der Wüste, in den Bergen. Merke: an + dem = am, in + dem = im. Im Plural bekommt das Nomen ein -n: in den Bergen.',
        examples: ['Wir machen Urlaub am Meer.', 'Meine Großeltern leben auf dem Land.', 'Im Winter sind wir in den Bergen.'],
        highlight: null,
        t: [
          'Where are you on holiday? Wo? (where?) + dative. an: am Atlantik, am Meer, am See, an der Küste (water and shores). auf: auf dem Land (in the countryside), auf der Insel. in: im Schwarzwald, im Gebirge, im Wald, in der Wüste, in den Bergen. Remember: an + dem = am, in + dem = im. In the plural the noun gets an -n: in den Bergen.',
          'Где вы в отпуске? Wo? (где?) + Dativ. an: am Atlantik, am Meer, am See, an der Küste (вода и берег). auf: auf dem Land (в деревне), auf der Insel. in: im Schwarzwald, im Gebirge, im Wald, in der Wüste, in den Bergen. Запомните: an + dem = am, in + dem = im. Во множественном числе существительное получает -n: in den Bergen.',
          'Де ви у відпустці? Wo? (де?) + Dativ. an: am Atlantik, am Meer, am See, an der Küste (вода й берег). auf: auf dem Land (у селі), auf der Insel. in: im Schwarzwald, im Gebirge, im Wald, in der Wüste, in den Bergen. Запам’ятайте: an + dem = am, in + dem = im. У множині іменник отримує -n: in den Bergen.',
          'Tatilde neredesiniz? Wo? (nerede?) + Dativ. an: am Atlantik, am Meer, am See, an der Küste (su ve kıyı). auf: auf dem Land (kırsalda), auf der Insel. in: im Schwarzwald, im Gebirge, im Wald, in der Wüste, in den Bergen. Unutmayın: an + dem = am, in + dem = im. Çoğulda isim -n alır: in den Bergen.',
        ],
        hint: ['Wo? → Dativ. Wasser: am Meer, an der Küste. auf dem Land, auf der Insel. im Gebirge, in der Wüste, in den Bergen.', 'Wo? (where?) → dative. Water: am Meer, an der Küste. auf dem Land, auf der Insel. im Gebirge, in der Wüste, in den Bergen.', 'Wo? (где?) → Dativ. Вода: am Meer, an der Küste. auf dem Land, auf der Insel. im Gebirge, in der Wüste, in den Bergen.', 'Wo? (де?) → Dativ. Вода: am Meer, an der Küste. auf dem Land, auf der Insel. im Gebirge, in der Wüste, in den Bergen.', 'Wo? (nerede?) → Dativ. Su: am Meer, an der Küste. auf dem Land, auf der Insel. im Gebirge, in der Wüste, in den Bergen.'],
      },
      ex: [
        mc('G1', 'am Meer', I.choose, 'Wo macht ihr Urlaub? – … Meer.', ['Am', 'Ans', 'Im'],
          ['Where are you going on holiday? – By the sea.', 'Где вы проводите отпуск? – На море.', 'Де ви проводите відпустку? – На морі.', 'Tatili nerede geçiriyorsunuz? – Deniz kenarında.']),
        mc('G1', 'auf dem Land', I.choose, 'Meine Tante hat einen Bauernhof. Sie wohnt … Land.', ['auf dem', 'aufs', 'am'],
          ['My aunt has a farm. She lives in the countryside.', 'У моей тёти ферма. Она живёт в деревне.', 'У моєї тітки ферма. Вона живе в селі.', 'Teyzemin bir çiftliği var. Kırsalda yaşıyor.']),
        mc('G1', 'in den Bergen', I.choose, 'Im Winter sind wir gern … Bergen.', ['in den', 'in die', 'im'],
          ['In winter we like being in the mountains.', 'Зимой мы любим бывать в горах.', 'Узимку ми любимо бувати в горах.', 'Kışın dağlarda olmayı severiz.']),
        mc('G1', 'an der Küste', I.choose, 'Das Hotel liegt … Küste.', ['an der', 'an die', 'in der'],
          ['The hotel is on the coast.', 'Отель находится на побережье.', 'Готель розташований на узбережжі.', 'Otel kıyıda.']),
        mc('G1', 'im Schwarzwald', I.choose, 'Unser Hotel ist … Schwarzwald.', ['im', 'in den', 'am'],
          ['Our hotel is in the Black Forest.', 'Наш отель находится в Шварцвальде.', 'Наш готель розташований у Шварцвальді.', 'Otelimiz Kara Orman’da.']),
        gap('G1', 'auf der Insel', I.prep, 'Lena ist gerade im Urlaub ', ' der Insel Sylt.', 'auf', ['an', 'in'],
          ['Lena is on holiday on the island of Sylt at the moment.', 'Lena сейчас в отпуске на острове Зильт.', 'Lena зараз у відпустці на острові Зильт.', 'Lena şu an Sylt adasında tatilde.'], 'auf / an / in'),
        gap('G1', 'in der Wüste', I.article, 'Die Familie macht Ferien in ', ' Wüste.', 'der', ['die', 'den'],
          ['The family is on holiday in the desert.', 'Семья проводит каникулы в пустыне.', 'Родина проводить канікули в пустелі.', 'Aile tatilini çölde geçiriyor.'], 'die Wüste'),
        gap('G1', 'am See', I.prep, 'Wir sitzen ', ' See und essen ein Eis.', 'am', ['an', 'ans'],
          ['We are sitting by the lake, eating an ice cream.', 'Мы сидим у озера и едим мороженое.', 'Ми сидимо біля озера й їмо морозиво.', 'Göl kenarında oturmuş dondurma yiyoruz.'], 'an + dem'),
        gap('G1', 'in den Bergen', I.form, 'Im Sommer ist es in den ', ' schön kühl.', 'Bergen', ['Berge', 'Berg'],
          ['In summer it is nice and cool in the mountains.', 'Летом в горах приятно прохладно.', 'Улітку в горах приємно прохолодно.', 'Yazın dağlarda hava güzel ve serin olur.'], 'der Berg (Plural)'),
        sb('G1', 'am Atlantik', I.order, 'Wir / machen / Urlaub / am Atlantik.',
          ['We are on holiday on the Atlantic coast.', 'Мы проводим отпуск на Атлантике.', 'Ми проводимо відпустку на Атлантиці.', 'Tatilimizi Atlas Okyanusu kıyısında geçiriyoruz.'],
          { alt: ['Am Atlantik machen wir Urlaub.', 'Urlaub machen wir am Atlantik.'] }),
      ],
    },
    {
      title: 'Wohin? – Ans Meer.',
      t: ['Where to? – To the sea.', 'Куда? – На море.', 'Куди? – На море.', 'Nereye? – Denize.'],
      card: {
        id: 'p5_wohin',
        rule: 'Wohin fährst du? Wohin? + Akkusativ. an: an den Atlantik, ans Meer, an den See, an die Küste. auf: aufs Land, auf die Insel. in: in den Schwarzwald, ins Gebirge, in den Wald, in die Wüste, in die Berge. Merke: an + das = ans, auf + das = aufs, in + das = ins. Aber bei Städten und Ländern ohne Artikel: nach Hamburg, nach Italien.',
        examples: ['Im Sommer fahren wir ans Meer.', 'Am Wochenende fahre ich aufs Land.', 'Wir fliegen auf die Insel Kreta.'],
        highlight: null,
        t: [
          'Where are you going? Wohin? (where to?) + accusative. an: an den Atlantik, ans Meer, an den See, an die Küste. auf: aufs Land, auf die Insel. in: in den Schwarzwald, ins Gebirge, in den Wald, in die Wüste, in die Berge. Remember: an + das = ans, auf + das = aufs, in + das = ins. But with towns and countries without an article: nach Hamburg, nach Italien.',
          'Куда ты едешь? Wohin? (куда?) + Akkusativ. an: an den Atlantik, ans Meer, an den See, an die Küste. auf: aufs Land, auf die Insel. in: in den Schwarzwald, ins Gebirge, in den Wald, in die Wüste, in die Berge. Запомните: an + das = ans, auf + das = aufs, in + das = ins. Но с городами и странами без артикля: nach Hamburg, nach Italien.',
          'Куди ти їдеш? Wohin? (куди?) + Akkusativ. an: an den Atlantik, ans Meer, an den See, an die Küste. auf: aufs Land, auf die Insel. in: in den Schwarzwald, ins Gebirge, in den Wald, in die Wüste, in die Berge. Запам’ятайте: an + das = ans, auf + das = aufs, in + das = ins. Але з містами й країнами без артикля: nach Hamburg, nach Italien.',
          'Nereye gidiyorsun? Wohin? (nereye?) + Akkusativ. an: an den Atlantik, ans Meer, an den See, an die Küste. auf: aufs Land, auf die Insel. in: in den Schwarzwald, ins Gebirge, in den Wald, in die Wüste, in die Berge. Unutmayın: an + das = ans, auf + das = aufs, in + das = ins. Ama artikelsiz şehir ve ülkelerde: nach Hamburg, nach Italien.',
        ],
        hint: ['Wohin? → Akkusativ. ans Meer, an die Küste, aufs Land, auf die Insel, ins Gebirge, in die Wüste, in die Berge.', 'Wohin? (where to?) → accusative. ans Meer, an die Küste, aufs Land, auf die Insel, ins Gebirge, in die Wüste, in die Berge.', 'Wohin? (куда?) → Akkusativ. ans Meer, an die Küste, aufs Land, auf die Insel, ins Gebirge, in die Wüste, in die Berge.', 'Wohin? (куди?) → Akkusativ. ans Meer, an die Küste, aufs Land, auf die Insel, ins Gebirge, in die Wüste, in die Berge.', 'Wohin? (nereye?) → Akkusativ. ans Meer, an die Küste, aufs Land, auf die Insel, ins Gebirge, in die Wüste, in die Berge.'],
      },
      ex: [
        mc('G2', 'ans Meer', I.choose, 'Wohin fahrt ihr im Sommer? – … Meer.', ['Ans', 'Am', 'Im'],
          ['Where are you going in the summer? – To the sea.', 'Куда вы едете летом? – На море.', 'Куди ви їдете влітку? – На море.', 'Yazın nereye gidiyorsunuz? – Denize.']),
        mc('G2', 'aufs Land', I.choose, 'Am Wochenende fahren wir … Land.', ['aufs', 'auf dem', 'im'],
          ['At the weekend we are going to the countryside.', 'В выходные мы едем за город.', 'У вихідні ми їдемо за місто.', 'Hafta sonu kırsala gidiyoruz.']),
        mc('G2', 'auf die Insel', I.choose, 'Wir fliegen … Insel Mallorca.', ['auf die', 'auf der', 'in der'],
          ['We are flying to the island of Majorca.', 'Мы летим на остров Майорка.', 'Ми летимо на острів Майорка.', 'Mallorca adasına uçuyoruz.']),
        mc('G2', 'in die Berge', I.choose, 'Im Winter fahre ich … Berge.', ['in die', 'in den', 'im'],
          ['In winter I go to the mountains.', 'Зимой я езжу в горы.', 'Узимку я їжджу в гори.', 'Kışın dağlara giderim.']),
        mc('G2', 'an die Küste', I.choose, 'Wo oder wohin? „Wir fahren … Küste.“', ['an die', 'an der', 'auf der'],
          ['Where or where to? “We are driving to the coast.”', 'Где или куда? «Мы едем на побережье.»', 'Де чи куди? «Ми їдемо на узбережжя.»', 'Nerede mi, nereye mi? “Kıyıya gidiyoruz.”']),
        gap('G2', 'ins Gebirge', I.prep, 'Morgen fahren wir ', ' Gebirge. Dort wollen wir wandern.', 'ins', ['im', 'in'],
          ['Tomorrow we are going to the mountains. We want to go hiking there.', 'Завтра мы едем в горы. Там мы хотим ходить в походы.', 'Завтра ми їдемо в гори. Там ми хочемо ходити в походи.', 'Yarın dağlara gidiyoruz. Orada yürüyüş yapmak istiyoruz.'], 'in + das'),
        gap('G2', 'in die Wüste', I.article, 'Dieses Jahr reisen wir in ', ' Wüste.', 'die', ['der', 'den'],
          ['This year we are travelling to the desert.', 'В этом году мы едем в пустыню.', 'Цього року ми їдемо в пустелю.', 'Bu yıl çöle seyahat ediyoruz.'], 'die Wüste'),
        gap('G2', 'an den See', I.prep, 'Die Kinder laufen ', ' den See. Sie wollen schwimmen.', 'an', ['am', 'ans'],
          ['The children are running to the lake. They want to swim.', 'Дети бегут к озеру. Они хотят плавать.', 'Діти біжать до озера. Вони хочуть плавати.', 'Çocuklar göle koşuyor. Yüzmek istiyorlar.'], 'an / am / ans'),
        gap('G2', 'an den Atlantik', I.prep, 'Fahrt ihr dieses Jahr wieder ', ' Atlantik?', 'an den', ['am', 'ans'],
          ['Are you going to the Atlantic again this year?', 'Вы в этом году опять едете на Атлантику?', 'Ви цього року знову їдете на Атлантику?', 'Bu yıl yine Atlas Okyanusu’na mı gidiyorsunuz?'], 'an + der Atlantik'),
        sb('G2', 'ans Meer', I.order, 'Wir / fahren / im Sommer / ans Meer.',
          ['In the summer we are going to the sea.', 'Летом мы едем на море.', 'Улітку ми їдемо на море.', 'Yazın denize gidiyoruz.'],
          { alt: ['Im Sommer fahren wir ans Meer.', 'Ans Meer fahren wir im Sommer.'] }),
      ],
    },
    {
      title: 'Unterkünfte',
      t: ['Places to stay', 'Где остановиться', 'Де зупинитися', 'Konaklama yerleri'],
      card: {
        id: 'p5_unterkunft',
        rule: 'Unterkünfte: das Hotel, die Pension (ein kleines, einfaches Hotel, oft von einer Familie), die Jugendherberge (günstig, viele Betten in einem Zimmer), die Ferienwohnung (eine Wohnung mit Küche für den Urlaub), der Campingplatz (für Zelt oder Wohnwagen), das Zelt, der Bauernhof. Wichtige Wörter: das Einzelzimmer, das Doppelzimmer, die Halbpension (Frühstück und Abendessen), die Vollpension (alle Mahlzeiten), die Übernachtung, der Blick, die Lage, ruhig, zentral.',
        examples: ['Wir schlafen im Zelt auf dem Campingplatz.', 'Die Ferienwohnung hat eine kleine Küche.', 'Das Zimmer kostet 60 Euro mit Frühstück.'],
        highlight: 'article',
        t: [
          'Places to stay: das Hotel, die Pension (guest house: a small, simple hotel, often run by a family), die Jugendherberge (youth hostel: cheap, many beds in one room), die Ferienwohnung (holiday flat with a kitchen), der Campingplatz (campsite for a tent or caravan), das Zelt (tent), der Bauernhof (farm). Important words: das Einzelzimmer (single room), das Doppelzimmer (double room), die Halbpension (half board: breakfast and evening meal), die Vollpension (full board: all meals), die Übernachtung (overnight stay), der Blick (view), die Lage (location), ruhig (quiet), zentral (central).',
          'Где остановиться: das Hotel, die Pension (пансион: маленькая простая гостиница, часто семейная), die Jugendherberge (хостел: недорого, много кроватей в одной комнате), die Ferienwohnung (квартира для отдыха с кухней), der Campingplatz (кемпинг для палатки или автодома), das Zelt (палатка), der Bauernhof (ферма). Важные слова: das Einzelzimmer (одноместный номер), das Doppelzimmer (двухместный номер), die Halbpension (полупансион: завтрак и ужин), die Vollpension (полный пансион: все приёмы пищи), die Übernachtung (ночёвка), der Blick (вид), die Lage (расположение), ruhig (тихий), zentral (в центре).',
          'Де зупинитися: das Hotel, die Pension (пансіон: маленький простий готель, часто родинний), die Jugendherberge (хостел: недорого, багато ліжок в одній кімнаті), die Ferienwohnung (квартира для відпочинку з кухнею), der Campingplatz (кемпінг для намету чи автобудинку), das Zelt (намет), der Bauernhof (ферма). Важливі слова: das Einzelzimmer (одномісний номер), das Doppelzimmer (двомісний номер), die Halbpension (напівпансіон: сніданок і вечеря), die Vollpension (повний пансіон: усі прийоми їжі), die Übernachtung (ночівля), der Blick (вид), die Lage (розташування), ruhig (тихий), zentral (у центрі).',
          'Konaklama yerleri: das Hotel, die Pension (pansiyon: çoğu zaman bir ailenin işlettiği küçük, sade otel), die Jugendherberge (gençlik hosteli: uygun fiyatlı, bir odada çok yatak), die Ferienwohnung (mutfaklı tatil dairesi), der Campingplatz (çadır ya da karavan için kamp alanı), das Zelt (çadır), der Bauernhof (çiftlik). Önemli kelimeler: das Einzelzimmer (tek kişilik oda), das Doppelzimmer (çift kişilik oda), die Halbpension (yarım pansiyon: kahvaltı ve akşam yemeği), die Vollpension (tam pansiyon: bütün öğünler), die Übernachtung (geceleme), der Blick (manzara), die Lage (konum), ruhig (sakin), zentral (merkezî).',
        ],
        hint: ['Pension = kleines Hotel. Jugendherberge = günstig, viele Betten. Ferienwohnung = mit Küche. Campingplatz = Zelt.', 'Pension = small hotel. Jugendherberge = cheap, many beds. Ferienwohnung = with a kitchen. Campingplatz = tent.', 'Pension = маленькая гостиница. Jugendherberge = недорого, много кроватей. Ferienwohnung = с кухней. Campingplatz = палатка.', 'Pension = маленький готель. Jugendherberge = недорого, багато ліжок. Ferienwohnung = з кухнею. Campingplatz = намет.', 'Pension = küçük otel. Jugendherberge = uygun fiyatlı, çok yatak. Ferienwohnung = mutfaklı. Campingplatz = çadır.'],
      },
      ex: [
        mc('W2', 'Campingplatz', I.choose, 'Wo schläft man in einem Zelt?', ['auf dem Campingplatz', 'in der Pension', 'in der Ferienwohnung'],
          ['Where do you sleep in a tent?', 'Где спят в палатке?', 'Де сплять у наметі?', 'Çadırda nerede uyunur?']),
        mc('W2', 'Ferienwohnung', I.choose, 'Ihr möchtet im Urlaub selbst kochen und braucht eine Küche. Was mietet ihr?', ['eine Ferienwohnung', 'ein Einzelzimmer', 'ein Doppelzimmer'],
          ['You want to cook for yourselves on holiday and need a kitchen. What do you rent?', 'Вы хотите в отпуске готовить сами, и вам нужна кухня. Что вы снимете?', 'Ви хочете у відпустці готувати самі, і вам потрібна кухня. Що ви винаймете?', 'Tatilde kendiniz yemek yapmak istiyorsunuz ve mutfağa ihtiyacınız var. Ne kiralarsınız?']),
        mc('W2', 'Halbpension', I.choose, 'Was bedeutet „Halbpension“?', ['Frühstück und Abendessen sind im Preis.', 'Nur das Frühstück ist im Preis.', 'Das Zimmer kostet nur die Hälfte.'],
          ['What does “Halbpension” mean?', 'Что значит «Halbpension»?', 'Що означає «Halbpension»?', '“Halbpension” ne demek?']),
        mc('W2', 'Unterkünfte', I.odd, 'Drei Wörter sind Unterkünfte, ein Wort nicht.', ['Wüste', 'Pension', 'Jugendherberge', 'Campingplatz'], null),
        mc('W2', 'Jugendherberge', I.choose, 'Eine Schulklasse sucht eine günstige Unterkunft mit vielen Betten. Was passt?', ['eine Jugendherberge', 'ein Doppelzimmer', 'eine Ferienwohnung'],
          ['A school class is looking for cheap accommodation with lots of beds. What fits?', 'Школьный класс ищет недорогое жильё с большим количеством кроватей. Что подходит?', 'Шкільний клас шукає недороге житло з багатьма ліжками. Що підходить?', 'Bir okul sınıfı çok yataklı, uygun fiyatlı bir konaklama yeri arıyor. Hangisi uygun?']),
        gap('W2', 'Einzelzimmer', I.word, 'Ich reise allein. Ich brauche nur ein ', '.', 'Einzelzimmer', ['Doppelzimmer', 'Zelt'],
          ['I am travelling alone. I only need a single room.', 'Я путешествую один. Мне нужен только одноместный номер.', 'Я подорожую сам. Мені потрібен лише одномісний номер.', 'Yalnız seyahat ediyorum. Sadece tek kişilik bir odaya ihtiyacım var.'],
          ['single room', 'одноместный номер', 'одномісний номер', 'tek kişilik oda']),
        gap('W2', 'Pension', I.word, 'Die ', ' ist klein und einfach. Familie Huber führt sie seit 30 Jahren.', 'Pension', ['Wüste', 'Lage'],
          ['The guest house is small and simple. The Huber family has been running it for 30 years.', 'Пансион маленький и простой. Семья Huber управляет им уже 30 лет.', 'Пансіон маленький і простий. Родина Huber керує ним уже 30 років.', 'Pansiyon küçük ve sade. Huber ailesi burayı 30 yıldır işletiyor.'],
          ['guest house', 'пансион', 'пансіон', 'pansiyon']),
        gap('W2', 'Blick', I.word, 'Vom Balkon hat man einen schönen ', ' auf den See.', 'Blick', ['Platz', 'Strand'],
          ['From the balcony you have a lovely view of the lake.', 'С балкона открывается красивый вид на озеро.', 'З балкона відкривається гарний вид на озеро.', 'Balkondan göle güzel bir manzara var.'],
          ['view', 'вид', 'вид', 'manzara']),
        gap('W2', 'Übernachtung', I.word, 'Wir bleiben drei Nächte. Eine ', ' kostet 45 Euro.', 'Übernachtung', ['Unterkunft', 'Halbpension'],
          ['We are staying three nights. One night costs 45 euros.', 'Мы останемся на три ночи. Одна ночёвка стоит 45 евро.', 'Ми залишимося на три ночі. Одна ночівля коштує 45 євро.', 'Üç gece kalıyoruz. Bir geceleme 45 avro.'],
          ['overnight stay', 'ночёвка', 'ночівля', 'geceleme']),
        sb('W2', 'Zelt', I.order, 'Wir / schlafen / im Zelt / auf dem Campingplatz.',
          ['We are sleeping in a tent on the campsite.', 'Мы спим в палатке в кемпинге.', 'Ми спимо в наметі в кемпінгу.', 'Kamp alanında çadırda uyuyoruz.'],
          { alt: ['Auf dem Campingplatz schlafen wir im Zelt.'] }),
      ],
    },
    {
      title: 'schöner Blick',
      t: ['schöner Blick (adjectives without an article)', 'schöner Blick (прилагательные без артикля)', 'schöner Blick (прикметники без артикля)', 'schöner Blick (artikelsiz sıfatlar)'],
      card: {
        id: 'p5_adj_ohne',
        rule: 'Adjektive ohne Artikel: Das Adjektiv bekommt die Endung vom bestimmten Artikel. Nominativ: der Blick → schöner Blick, das Frühstück → leckeres Frühstück, die Lage → schöne Lage, die Produkte → regionale Produkte. Akkusativ: Nur maskulin ändert sich – schönen Blick. Neutral, feminin und Plural bleiben: leckeres Frühstück, schöne Lage, regionale Produkte. So schreibt man oft in Anzeigen.',
        examples: ['Schöner Blick auf die Berge!', 'Wir bieten leckeres Frühstück.', 'Ich mag lange Spaziergänge.'],
        highlight: null,
        t: [
          'Adjectives without an article: the adjective takes the ending of the definite article. Nominative: der Blick → schöner Blick, das Frühstück → leckeres Frühstück, die Lage → schöne Lage, die Produkte → regionale Produkte. Accusative: only the masculine changes – schönen Blick. Neuter, feminine and plural stay the same: leckeres Frühstück, schöne Lage, regionale Produkte. This is how people often write in ads.',
          'Прилагательные без артикля: прилагательное получает окончание определённого артикля. Nominativ: der Blick → schöner Blick, das Frühstück → leckeres Frühstück, die Lage → schöne Lage, die Produkte → regionale Produkte. Akkusativ: меняется только мужской род – schönen Blick. Средний, женский род и множественное число остаются: leckeres Frühstück, schöne Lage, regionale Produkte. Так часто пишут в объявлениях.',
          'Прикметники без артикля: прикметник отримує закінчення означеного артикля. Nominativ: der Blick → schöner Blick, das Frühstück → leckeres Frühstück, die Lage → schöne Lage, die Produkte → regionale Produkte. Akkusativ: змінюється лише чоловічий рід – schönen Blick. Середній, жіночий рід і множина залишаються: leckeres Frühstück, schöne Lage, regionale Produkte. Так часто пишуть в оголошеннях.',
          'Artikelsiz sıfatlar: Sıfat belirli artikelin ekini alır. Nominativ: der Blick → schöner Blick, das Frühstück → leckeres Frühstück, die Lage → schöne Lage, die Produkte → regionale Produkte. Akkusativ: Yalnızca eril değişir – schönen Blick. Nötr, dişil ve çoğul aynı kalır: leckeres Frühstück, schöne Lage, regionale Produkte. İlanlarda çoğu zaman böyle yazılır.',
        ],
        hint: ['Ohne Artikel: der → -er, das → -es, die → -e, Plural → -e. Akkusativ maskulin: -en.', 'Without an article: der → -er, das → -es, die → -e, plural → -e. Accusative masculine: -en.', 'Без артикля: der → -er, das → -es, die → -e, множественное число → -e. Akkusativ мужского рода: -en.', 'Без артикля: der → -er, das → -es, die → -e, множина → -e. Akkusativ чоловічого роду: -en.', 'Artikelsiz: der → -er, das → -es, die → -e, çoğul → -e. Eril Akkusativ: -en.'],
      },
      ex: [
        mc('G3', '-e (die)', I.choose, 'Hotel mit Garten: … Lage am See!', ['Ruhige', 'Ruhiger', 'Ruhiges'],
          ['Hotel with garden: quiet location by the lake!', 'Отель с садом: тихое место у озера!', 'Готель із садом: тихе місце біля озера!', 'Bahçeli otel: göl kenarında sakin konum!']),
        mc('G3', '-es (das)', I.choose, 'Jeden Morgen gibt es … Frühstück.', ['leckeres', 'leckerer', 'leckere'],
          ['Every morning there is a delicious breakfast.', 'Каждое утро подают вкусный завтрак.', 'Щоранку подають смачний сніданок.', 'Her sabah lezzetli bir kahvaltı var.']),
        mc('G3', '-er (der)', I.choose, '… Blick auf das Meer!', ['Schöner', 'Schönes', 'Schöne'],
          ['Lovely view of the sea!', 'Красивый вид на море!', 'Гарний вид на море!', 'Güzel deniz manzarası!']),
        mc('G3', '-e (Plural)', I.choose, 'Ich mag … Spaziergänge am Strand.', ['lange', 'langer', 'langes'],
          ['I like long walks on the beach.', 'Я люблю долгие прогулки по пляжу.', 'Я люблю довгі прогулянки пляжем.', 'Plajda uzun yürüyüşleri severim.']),
        mc('G3', '-en (Akkusativ maskulin)', I.choose, 'Das Hotel bietet … Service.', ['guten', 'guter', 'gutes'],
          ['The hotel offers good service.', 'Отель предлагает хорошее обслуживание.', 'Готель пропонує добре обслуговування.', 'Otel iyi hizmet sunuyor.']),
        gap('G3', '-en (Akkusativ maskulin)', I.ending, 'Im Restaurant gibt es ', ' Fisch aus der Region.', 'frischen', ['frischer', 'frisches'],
          ['The restaurant serves fresh fish from the region.', 'В ресторане подают свежую местную рыбу.', 'У ресторані подають свіжу місцеву рибу.', 'Restoranda bölgeden gelen taze balık var.'], 'frisch'),
        gap('G3', '-es (das)', I.ending, '', ' Wetter! Wir gehen sofort an den Strand.', 'Schönes', ['Schöner', 'Schöne'],
          ['Lovely weather! We are going to the beach straight away.', 'Прекрасная погода! Мы сразу идём на пляж.', 'Чудова погода! Ми одразу йдемо на пляж.', 'Hava çok güzel! Hemen plaja gidiyoruz.'], 'schön'),
        gap('G3', '-e (Plural)', I.ending, 'Die Pension hat ', ' Zimmer mit Balkon.', 'helle', ['heller', 'helles'],
          ['The guest house has bright rooms with a balcony.', 'В пансионе светлые номера с балконом.', 'У пансіоні світлі номери з балконом.', 'Pansiyonun balkonlu, aydınlık odaları var.'], 'hell'),
        gap('G3', '-en (Akkusativ maskulin)', I.ending, 'Wir trinken ', ' Kaffee auf der Terrasse.', 'heißen', ['heißer', 'heißes'],
          ['We are drinking hot coffee on the terrace.', 'Мы пьём горячий кофе на террасе.', 'Ми п’ємо гарячу каву на терасі.', 'Terasta sıcak kahve içiyoruz.'], 'heiß'),
        sb('G3', '-e (Plural)', I.order, 'Ich / mag / lange / Spaziergänge.',
          ['I like long walks.', 'Я люблю долгие прогулки.', 'Я люблю довгі прогулянки.', 'Uzun yürüyüşleri severim.'],
          { alt: ['Lange Spaziergänge mag ich.'] }),
      ],
    },
    {
      title: 'mit schönem Blick',
      t: ['mit schönem Blick (without an article: dative)', 'mit schönem Blick (без артикля: Dativ)', 'mit schönem Blick (без артикля: Dativ)', 'mit schönem Blick (artikelsiz: Dativ)'],
      card: {
        id: 'p5_adj_ohne_dat',
        rule: 'Adjektive ohne Artikel im Dativ: Auch hier nimmt das Adjektiv die Endung vom Artikel. dem → -em: mit schönem Blick, mit leckerem Frühstück. der → -er: in schöner Lage, mit großer Terrasse. Plural den → -en: mit regionalen Produkten, mit freundlichen Mitarbeitern. Der Dativ steht nach mit, bei, von, aus, nach, zu und nach in auf die Frage Wo?',
        examples: ['Zimmer mit schönem Blick auf den See.', 'Hotel in ruhiger Lage.', 'Frühstück mit regionalen Produkten.'],
        highlight: null,
        t: [
          'Adjectives without an article in the dative: here too the adjective takes the ending of the article. dem → -em: mit schönem Blick, mit leckerem Frühstück. der → -er: in schöner Lage, mit großer Terrasse. Plural den → -en: mit regionalen Produkten, mit freundlichen Mitarbeitern. The dative follows mit, bei, von, aus, nach, zu, and in when the question is Wo? (where?)',
          'Прилагательные без артикля в Dativ: и здесь прилагательное получает окончание артикля. dem → -em: mit schönem Blick, mit leckerem Frühstück. der → -er: in schöner Lage, mit großer Terrasse. Множественное число den → -en: mit regionalen Produkten, mit freundlichen Mitarbeitern. Dativ стоит после mit, bei, von, aus, nach, zu и после in на вопрос Wo? (где?)',
          'Прикметники без артикля в Dativ: і тут прикметник отримує закінчення артикля. dem → -em: mit schönem Blick, mit leckerem Frühstück. der → -er: in schöner Lage, mit großer Terrasse. Множина den → -en: mit regionalen Produkten, mit freundlichen Mitarbeitern. Dativ стоїть після mit, bei, von, aus, nach, zu і після in на запитання Wo? (де?)',
          'Dativ’de artikelsiz sıfatlar: Burada da sıfat artikelin ekini alır. dem → -em: mit schönem Blick, mit leckerem Frühstück. der → -er: in schöner Lage, mit großer Terrasse. Çoğul den → -en: mit regionalen Produkten, mit freundlichen Mitarbeitern. Dativ mit, bei, von, aus, nach, zu edatlarından ve Wo? (nerede?) sorusunda in edatından sonra gelir.',
        ],
        hint: ['Dativ ohne Artikel: dem → -em (mit schönem Blick), der → -er (in ruhiger Lage), Plural → -en (mit netten Leuten).', 'Dative without an article: dem → -em (mit schönem Blick), der → -er (in ruhiger Lage), plural → -en (mit netten Leuten).', 'Dativ без артикля: dem → -em (mit schönem Blick), der → -er (in ruhiger Lage), множественное число → -en (mit netten Leuten).', 'Dativ без артикля: dem → -em (mit schönem Blick), der → -er (in ruhiger Lage), множина → -en (mit netten Leuten).', 'Artikelsiz Dativ: dem → -em (mit schönem Blick), der → -er (in ruhiger Lage), çoğul → -en (mit netten Leuten).'],
      },
      ex: [
        mc('G4', '-em (der)', I.choose, 'Hotel mit … Blick auf die Berge.', ['schönem', 'schöner', 'schönen'],
          ['Hotel with a lovely view of the mountains.', 'Отель с красивым видом на горы.', 'Готель із гарним видом на гори.', 'Güzel dağ manzaralı otel.']),
        mc('G4', '-er (die)', I.choose, 'Pension in … Lage.', ['ruhiger', 'ruhigem', 'ruhigen'],
          ['Guest house in a quiet location.', 'Пансион в тихом месте.', 'Пансіон у тихому місці.', 'Sakin konumda pansiyon.']),
        mc('G4', '-en (Plural)', I.choose, 'Frühstück mit … Produkten.', ['regionalen', 'regionaler', 'regionalem'],
          ['Breakfast with regional produce.', 'Завтрак из местных продуктов.', 'Сніданок із місцевих продуктів.', 'Yöresel ürünlerle kahvaltı.']),
        mc('G4', '-em (der)', I.choose, 'Ferienwohnung mit … Garten.', ['großem', 'großer', 'großen'],
          ['Holiday flat with a big garden.', 'Квартира для отдыха с большим садом.', 'Квартира для відпочинку з великим садом.', 'Büyük bahçeli tatil dairesi.']),
        mc('G4', '-er (die)', I.choose, 'Zimmer mit … Dusche und WC.', ['eigener', 'eigenem', 'eigenen'],
          ['Room with its own shower and toilet.', 'Номер с собственным душем и туалетом.', 'Номер із власним душем і туалетом.', 'Kendi duşu ve tuvaleti olan oda.']),
        gap('G4', '-em (das)', I.ending, 'Wir suchen ein Hotel mit ', ' Schwimmbad.', 'großem', ['großer', 'großen'],
          ['We are looking for a hotel with a big swimming pool.', 'Мы ищем отель с большим бассейном.', 'Ми шукаємо готель із великим басейном.', 'Büyük yüzme havuzu olan bir otel arıyoruz.'], 'groß'),
        gap('G4', '-er (die)', I.ending, 'Das Haus liegt in ', ' Lage, nur fünf Minuten vom Bahnhof.', 'zentraler', ['zentralem', 'zentralen'],
          ['The house is in a central location, only five minutes from the station.', 'Дом расположен в центре, всего в пяти минутах от вокзала.', 'Будинок розташований у центрі, лише за п’ять хвилин від вокзалу.', 'Ev merkezî bir konumda, istasyona sadece beş dakika.'], 'zentral'),
        gap('G4', '-en (Plural)', I.ending, 'Die Pension ist bekannt für Kuchen aus ', ' Äpfeln.', 'frischen', ['frischer', 'frischem'],
          ['The guest house is known for cakes made from fresh apples.', 'Пансион славится пирогами из свежих яблок.', 'Пансіон відомий пирогами зі свіжих яблук.', 'Pansiyon taze elmadan yapılan kekleriyle tanınıyor.'], 'frisch'),
        gap('G4', '-em (das)', I.ending, 'Bei ', ' Wetter frühstücken wir auf der Terrasse.', 'gutem', ['guter', 'guten'],
          ['In good weather we have breakfast on the terrace.', 'В хорошую погоду мы завтракаем на террасе.', 'У гарну погоду ми снідаємо на терасі.', 'Hava güzelse terasta kahvaltı ediyoruz.'], 'gut'),
        sb('G4', '-em (der)', I.order, 'Wir / suchen / ein Zimmer / mit / schönem Blick.',
          ['We are looking for a room with a lovely view.', 'Мы ищем номер с красивым видом.', 'Ми шукаємо номер із гарним видом.', 'Güzel manzaralı bir oda arıyoruz.']),
      ],
    },
    {
      title: 'von … an, über, ohne',
      t: ['von … an, über, ohne (from … on, over, without)', 'von … an, über, ohne (начиная с, более, без)', 'von … an, über, ohne (починаючи з, понад, без)', 'von … an, über, ohne (-den itibaren, -den fazla, -sız)'],
      card: {
        id: 'p5_zeit_ohne',
        rule: 'Zeit: von … an + Dativ nennt den Anfang – Von Oktober an gibt es wieder freie Plätze. Von morgen an habe ich Urlaub. Vom ersten Mai an ist das Schwimmbad geöffnet. über + Akkusativ bedeutet „mehr als“: Er hat über eine Stunde Aufenthalt. Die Fahrt dauert über drei Stunden. ohne + Akkusativ: ohne lauten Verkehr, ohne mein Handy, ohne dich. Ohne Artikel hat das Adjektiv die Endung -en (der), -es (das), -e (die).',
        examples: ['Von Montag an bin ich im Urlaub.', 'Wir haben über zwei Stunden gewartet.', 'Ein Urlaub ohne lauten Verkehr ist schön.'],
        highlight: null,
        t: [
          'Time: von … an (from … on) + dative gives the starting point – Von Oktober an gibt es wieder freie Plätze. Von morgen an habe ich Urlaub. Vom ersten Mai an ist das Schwimmbad geöffnet. über + accusative means “more than”: Er hat über eine Stunde Aufenthalt. Die Fahrt dauert über drei Stunden. ohne (without) + accusative: ohne lauten Verkehr, ohne mein Handy, ohne dich. Without an article the adjective has the ending -en (der), -es (das), -e (die).',
          'Время: von … an (начиная с) + Dativ называет начало – Von Oktober an gibt es wieder freie Plätze. Von morgen an habe ich Urlaub. Vom ersten Mai an ist das Schwimmbad geöffnet. über + Akkusativ значит «больше чем»: Er hat über eine Stunde Aufenthalt. Die Fahrt dauert über drei Stunden. ohne (без) + Akkusativ: ohne lauten Verkehr, ohne mein Handy, ohne dich. Без артикля прилагательное имеет окончание -en (der), -es (das), -e (die).',
          'Час: von … an (починаючи з) + Dativ називає початок – Von Oktober an gibt es wieder freie Plätze. Von morgen an habe ich Urlaub. Vom ersten Mai an ist das Schwimmbad geöffnet. über + Akkusativ означає «більше ніж»: Er hat über eine Stunde Aufenthalt. Die Fahrt dauert über drei Stunden. ohne (без) + Akkusativ: ohne lauten Verkehr, ohne mein Handy, ohne dich. Без артикля прикметник має закінчення -en (der), -es (das), -e (die).',
          'Zaman: von … an (-den itibaren) + Dativ başlangıcı bildirir – Von Oktober an gibt es wieder freie Plätze. Von morgen an habe ich Urlaub. Vom ersten Mai an ist das Schwimmbad geöffnet. über + Akkusativ “-den fazla” demektir: Er hat über eine Stunde Aufenthalt. Die Fahrt dauert über drei Stunden. ohne (-sız, olmadan) + Akkusativ: ohne lauten Verkehr, ohne mein Handy, ohne dich. Artikelsiz kullanımda sıfat -en (der), -es (das), -e (die) ekini alır.',
        ],
        hint: ['von … an = ab diesem Zeitpunkt. über = mehr als. ohne + Akkusativ: ohne einen, ohne mein, ohne meine.', 'von … an = from that point on. über = more than. ohne + accusative: ohne einen, ohne mein, ohne meine.', 'von … an = начиная с этого момента. über = больше чем. ohne + Akkusativ: ohne einen, ohne mein, ohne meine.', 'von … an = починаючи з цього моменту. über = більше ніж. ohne + Akkusativ: ohne einen, ohne mein, ohne meine.', 'von … an = o andan itibaren. über = -den fazla. ohne + Akkusativ: ohne einen, ohne mein, ohne meine.'],
      },
      ex: [
        mc('G5', 'von … an', I.choose, 'Was bedeutet „von Oktober an“?', ['ab Oktober', 'bis Oktober', 'vor Oktober'],
          ['What does “von Oktober an” mean?', 'Что значит «von Oktober an»?', 'Що означає «von Oktober an»?', '“von Oktober an” ne demek?']),
        mc('G5', 'über', I.choose, 'Was bedeutet „über eine Stunde“?', ['mehr als eine Stunde', 'weniger als eine Stunde', 'genau eine Stunde'],
          ['What does “über eine Stunde” mean?', 'Что значит «über eine Stunde»?', 'Що означає «über eine Stunde»?', '“über eine Stunde” ne demek?']),
        mc('G5', 'von … an', I.choose, 'Von Juli … haben wir wieder freie Zimmer.', ['an', 'aus', 'bis'],
          ['From July on we have rooms available again.', 'Начиная с июля у нас снова есть свободные номера.', 'Починаючи з липня в нас знову є вільні номери.', 'Temmuzdan itibaren yine boş odamız var.']),
        mc('G6', 'ohne', I.choose, 'Ich fahre nie … mein Handy in den Urlaub.', ['ohne', 'über', 'von'],
          ['I never go on holiday without my mobile.', 'Я никогда не езжу в отпуск без телефона.', 'Я ніколи не їжджу у відпустку без телефона.', 'Tatile asla cep telefonumu almadan gitmem.']),
        mc('G6', 'ohne + Akkusativ', I.choose, 'Wir möchten Urlaub ohne … Verkehr.', ['lauten', 'lauter', 'lautem'],
          ['We would like a holiday without noisy traffic.', 'Мы хотим отдохнуть без шумного транспорта.', 'Ми хочемо відпочити без гучного транспорту.', 'Gürültülü trafik olmayan bir tatil istiyoruz.']),
        gap('G5', 'über', I.prep, 'Die Fahrt nach Wien dauert ', ' acht Stunden. Das ist sehr lang.', 'über', ['unter', 'ohne'],
          ['The journey to Vienna takes over eight hours. That is very long.', 'Дорога до Вены занимает больше восьми часов. Это очень долго.', 'Дорога до Відня триває понад вісім годин. Це дуже довго.', 'Viyana yolculuğu sekiz saatten fazla sürüyor. Bu çok uzun.'], 'über / unter / ohne'),
        gap('G5', 'von … an', I.prep, '', ' morgen an arbeite ich in einer neuen Firma.', 'Von', ['Bis', 'Über'],
          ['From tomorrow on I will be working at a new company.', 'С завтрашнего дня я работаю в новой фирме.', 'Від завтра я працюю в новій фірмі.', 'Yarından itibaren yeni bir şirkette çalışıyorum.'], 'von / bis / über'),
        gap('G6', 'ohne + Akkusativ', I.possessive, 'Paul reist dieses Jahr ohne ', ' Freundin. Sie muss arbeiten.', 'seine', ['seiner', 'seinem'],
          ['This year Paul is travelling without his girlfriend. She has to work.', 'В этом году Paul едет без своей девушки. Ей нужно работать.', 'Цього року Paul їде без своєї дівчини. Їй треба працювати.', 'Paul bu yıl kız arkadaşı olmadan seyahat ediyor. Onun çalışması gerekiyor.'], 'sein'),
        gap('G6', 'ohne', I.prep, 'Einen Kaffee ', ' Zucker, bitte. Ich mag es nicht süß.', 'ohne', ['über', 'von'],
          ['A coffee without sugar, please. I do not like it sweet.', 'Кофе без сахара, пожалуйста. Я не люблю сладкое.', 'Каву без цукру, будь ласка. Я не люблю солодке.', 'Şekersiz bir kahve lütfen. Tatlı sevmem.'], 'ohne / über / von'),
        sb('G6', 'ohne + Akkusativ', I.order, 'Ich / reise / nie / ohne / meinen Hund.',
          ['I never travel without my dog.', 'Я никогда не путешествую без своей собаки.', 'Я ніколи не подорожую без свого собаки.', 'Köpeğim olmadan asla seyahat etmem.'],
          { alt: ['Ohne meinen Hund reise ich nie.', 'Nie reise ich ohne meinen Hund.'] }),
      ],
    },
    {
      title: 'Eine Reise buchen',
      t: ['Booking a trip', 'Бронируем поездку', 'Бронюємо поїздку', 'Seyahat rezervasyonu'],
      card: {
        id: 'p5_buchen',
        rule: 'Eine Reise buchen: Ich möchte eine Reise nach Hamburg buchen. – Für wie viele Personen? Wann? – Für zwei Personen, vom 3. bis zum 10. Mai. – Der Termin ist leider schon ausgebucht. Aber vom 12. Mai an haben wir wieder freie Plätze. Was kostet die Reise? – Das macht 240 Euro. Wie lange dauert die Fahrt? – Sie können um 8 Uhr abfahren und sind um 14 Uhr am Ziel. Ist das eine Direktverbindung? – Nein, Sie müssen in Kassel umsteigen und haben 20 Minuten Aufenthalt.',
        examples: ['Ich möchte den Bus nach Prag buchen.', 'Es ist leider kein Platz mehr frei.', 'Sie müssen in Köln umsteigen.'],
        highlight: null,
        t: [
          'Booking a trip: Ich möchte eine Reise nach Hamburg buchen. (I would like to book a trip to Hamburg.) – Für wie viele Personen? Wann? – Für zwei Personen, vom 3. bis zum 10. Mai. – Der Termin ist leider schon ausgebucht. (That date is already fully booked.) Aber vom 12. Mai an haben wir wieder freie Plätze. Was kostet die Reise? – Das macht 240 Euro. Wie lange dauert die Fahrt? (How long does the journey take?) – Sie können um 8 Uhr abfahren und sind um 14 Uhr am Ziel. (… and reach your destination at 2 pm.) Ist das eine Direktverbindung? (Is that a direct connection?) – Nein, Sie müssen in Kassel umsteigen und haben 20 Minuten Aufenthalt. (… change in Kassel and have a 20-minute wait.)',
          'Как забронировать поездку: Ich möchte eine Reise nach Hamburg buchen. (Я хочу забронировать поездку в Гамбург.) – Für wie viele Personen? Wann? – Für zwei Personen, vom 3. bis zum 10. Mai. – Der Termin ist leider schon ausgebucht. (На эти даты мест уже нет.) Aber vom 12. Mai an haben wir wieder freie Plätze. Was kostet die Reise? – Das macht 240 Euro. Wie lange dauert die Fahrt? (Сколько длится поездка?) – Sie können um 8 Uhr abfahren und sind um 14 Uhr am Ziel. (… и в 14 часов будете на месте.) Ist das eine Direktverbindung? (Это прямой рейс?) – Nein, Sie müssen in Kassel umsteigen und haben 20 Minuten Aufenthalt. (… пересадка в Касселе и 20 минут ожидания.)',
          'Як забронювати поїздку: Ich möchte eine Reise nach Hamburg buchen. (Я хочу забронювати поїздку до Гамбурга.) – Für wie viele Personen? Wann? – Für zwei Personen, vom 3. bis zum 10. Mai. – Der Termin ist leider schon ausgebucht. (На ці дати місць уже немає.) Aber vom 12. Mai an haben wir wieder freie Plätze. Was kostet die Reise? – Das macht 240 Euro. Wie lange dauert die Fahrt? (Скільки триває поїздка?) – Sie können um 8 Uhr abfahren und sind um 14 Uhr am Ziel. (… і о 14 годині будете на місці.) Ist das eine Direktverbindung? (Це прямий рейс?) – Nein, Sie müssen in Kassel umsteigen und haben 20 Minuten Aufenthalt. (… пересадка в Касселі й 20 хвилин очікування.)',
          'Seyahat rezervasyonu yaptırmak: Ich möchte eine Reise nach Hamburg buchen. (Hamburg’a bir seyahat rezervasyonu yaptırmak istiyorum.) – Für wie viele Personen? Wann? – Für zwei Personen, vom 3. bis zum 10. Mai. – Der Termin ist leider schon ausgebucht. (O tarih maalesef dolu.) Aber vom 12. Mai an haben wir wieder freie Plätze. Was kostet die Reise? – Das macht 240 Euro. Wie lange dauert die Fahrt? (Yolculuk ne kadar sürüyor?) – Sie können um 8 Uhr abfahren und sind um 14 Uhr am Ziel. (… saat 14’te varmış olursunuz.) Ist das eine Direktverbindung? (Bu direkt sefer mi?) – Nein, Sie müssen in Kassel umsteigen und haben 20 Minuten Aufenthalt. (… Kassel’de aktarma yapıp 20 dakika bekleyeceksiniz.)',
        ],
        hint: ['ausgebucht = kein Platz mehr frei. Direktverbindung = ohne Umsteigen. Aufenthalt = Wartezeit beim Umsteigen.', 'ausgebucht = no places left. Direktverbindung = without changing. Aufenthalt = waiting time when changing.', 'ausgebucht = свободных мест нет. Direktverbindung = без пересадки. Aufenthalt = время ожидания при пересадке.', 'ausgebucht = вільних місць немає. Direktverbindung = без пересадки. Aufenthalt = час очікування під час пересадки.', 'ausgebucht = boş yer kalmadı. Direktverbindung = aktarmasız. Aufenthalt = aktarmadaki bekleme süresi.'],
      },
      ex: [
        mc('K1', 'buchen', I.situation, 'Du bist im Reisebüro und willst nach Wien fahren. Was sagst du?', ['Ich möchte eine Reise nach Wien buchen.', 'Ich möchte eine Reise nach Wien absagen.', 'Ich war schon in Wien.'],
          ['You are at the travel agent’s and want to go to Vienna. What do you say?', 'Вы в турагентстве и хотите поехать в Вену. Что вы скажете?', 'Ви в турагенції й хочете поїхати до Відня. Що ви скажете?', 'Seyahat acentesindesiniz ve Viyana’ya gitmek istiyorsunuz. Ne dersiniz?']),
        mc('K1', 'Für wie viele Personen?', I.react, '„Für wie viele Personen?“', ['Für zwei Erwachsene und ein Kind.', 'Für 240 Euro.', 'Für eine Woche im Mai.'],
          ['“For how many people?”', '«На сколько человек?»', '«На скільки осіб?»', '“Kaç kişi için?”']),
        mc('K1', 'ausgebucht', I.choose, 'Was bedeutet „Der Termin ist ausgebucht“?', ['Es gibt keinen freien Platz mehr.', 'Die Reise ist sehr billig.', 'Die Reise beginnt heute.'],
          ['What does “Der Termin ist ausgebucht” mean?', 'Что значит «Der Termin ist ausgebucht»?', 'Що означає «Der Termin ist ausgebucht»?', '“Der Termin ist ausgebucht” ne demek?']),
        mc('K1', 'Direktverbindung', I.react, '„Ist das eine Direktverbindung?“', ['Nein, Sie müssen in Kassel umsteigen.', 'Nein, die Fahrt kostet 80 Euro.', 'Ja, Sie haben eine Stunde Aufenthalt.'],
          ['“Is that a direct connection?”', '«Это прямой рейс?»', '«Це прямий рейс?»', '“Bu direkt sefer mi?”']),
        mc('K1', 'Direktverbindung', I.choose, 'Was ist eine Direktverbindung?', ['eine Fahrt ohne Umsteigen', 'eine Fahrt mit dem Flugzeug', 'eine sehr schnelle Fahrt'],
          ['What is a “Direktverbindung”?', 'Что такое «Direktverbindung»?', 'Що таке «Direktverbindung»?', '“Direktverbindung” nedir?']),
        gap('K1', 'buchen', I.verb, 'Ich möchte den Bus nach Prag für den 5. Juni ', '.', 'buchen', ['besuchen', 'suchen'],
          ['I would like to book the coach to Prague for 5 June.', 'Я хочу забронировать автобус в Прагу на 5 июня.', 'Я хочу забронювати автобус до Праги на 5 червня.', '5 Haziran için Prag otobüsüne rezervasyon yaptırmak istiyorum.'],
          ['book', 'забронировать', 'забронювати', 'rezervasyon yaptırmak']),
        gap('K1', 'Aufenthalt', I.word, 'In Kassel haben Sie 20 Minuten ', '. Dann fährt der nächste Zug.', 'Aufenthalt', ['Ausfahrt', 'Ankunft'],
          ['In Kassel you have a 20-minute wait. Then the next train leaves.', 'В Касселе у вас 20 минут ожидания. Потом отправляется следующий поезд.', 'У Касселі у вас 20 хвилин очікування. Потім відправляється наступний потяг.', 'Kassel’de 20 dakika bekleyeceksiniz. Sonra bir sonraki tren kalkıyor.'],
          ['stopover, wait', 'остановка, время ожидания', 'зупинка, час очікування', 'bekleme süresi']),
        gap('K1', 'dauern', I.verb, 'Wie lange ', ' denn die Fahrt? – Sechs Stunden.', 'dauert', ['dauern', 'kostet'],
          ['How long does the journey take? – Six hours.', 'Сколько длится поездка? – Шесть часов.', 'Скільки триває поїздка? – Шість годин.', 'Yolculuk ne kadar sürüyor? – Altı saat.'], 'dauern'),
        gap('K1', 'kein Platz mehr frei', I.word, 'Es tut mir leid. Für Samstag ist kein Platz mehr ', '.', 'frei', ['voll', 'leer'],
          ['I am sorry. There are no places left for Saturday.', 'Мне жаль. На субботу свободных мест больше нет.', 'Мені шкода. На суботу вільних місць більше немає.', 'Üzgünüm. Cumartesi için boş yer kalmadı.'],
          ['free, available', 'свободно', 'вільно', 'boş']),
        sb('K1', 'Was kostet …?', I.question, 'Was / kostet / die Reise / für zwei Personen?',
          ['How much is the trip for two people?', 'Сколько стоит поездка на двоих?', 'Скільки коштує поїздка на двох?', 'İki kişilik seyahat ne kadar?']),
      ],
    },
    {
      title: 'Komm doch mal nach …!',
      t: ['Do come to …!', 'Приезжай как-нибудь в …!', 'Приїжджай якось до …!', '… şehrine bir gelsene!'],
      card: {
        id: 'p5_einladung',
        rule: 'Eine Einladung schreiben: Wann hast Du Zeit? Komm doch mal nach Leipzig! Du bist herzlich eingeladen. Wir könnten in den Zoo gehen, an den See fahren, die Altstadt besichtigen, ein Museum anschauen. Ich möchte Dir so gern die Stadt zeigen. Du musst unbedingt den Markt sehen. Hast Du Lust auf ein Konzert? Du kannst unseren Kuchen probieren. Der schmeckt super. Bis bald! Ich freue mich auf Dich! In Briefen kann man Du, Dir, Dich großschreiben.',
        examples: ['Komm doch mal nach Dresden!', 'Ich möchte Dir so gern den Hafen zeigen.', 'Ich freue mich auf Dich!'],
        highlight: null,
        t: [
          'Writing an invitation: Wann hast Du Zeit? Komm doch mal nach Leipzig! (Do come to Leipzig some time!) Du bist herzlich eingeladen. (You are warmly invited.) Wir könnten in den Zoo gehen, an den See fahren, die Altstadt besichtigen (look round the old town), ein Museum anschauen. Ich möchte Dir so gern die Stadt zeigen. (I would so like to show you the town.) Du musst unbedingt den Markt sehen. (You really must see the market.) Hast Du Lust auf ein Konzert? Du kannst unseren Kuchen probieren. Der schmeckt super. Bis bald! Ich freue mich auf Dich! (See you soon! I am looking forward to seeing you!) In letters you may write Du, Dir, Dich with a capital letter.',
          'Как написать приглашение: Wann hast Du Zeit? Komm doch mal nach Leipzig! (Приезжай как-нибудь в Лейпциг!) Du bist herzlich eingeladen. (Сердечно приглашаю тебя.) Wir könnten in den Zoo gehen, an den See fahren, die Altstadt besichtigen (осмотреть старый город), ein Museum anschauen. Ich möchte Dir so gern die Stadt zeigen. (Мне так хочется показать тебе город.) Du musst unbedingt den Markt sehen. (Тебе обязательно нужно увидеть рынок.) Hast Du Lust auf ein Konzert? Du kannst unseren Kuchen probieren. Der schmeckt super. Bis bald! Ich freue mich auf Dich! (До скорого! Жду тебя с нетерпением!) В письмах Du, Dir, Dich можно писать с большой буквы.',
          'Як написати запрошення: Wann hast Du Zeit? Komm doch mal nach Leipzig! (Приїжджай якось до Лейпцига!) Du bist herzlich eingeladen. (Щиро запрошую тебе.) Wir könnten in den Zoo gehen, an den See fahren, die Altstadt besichtigen (оглянути старе місто), ein Museum anschauen. Ich möchte Dir so gern die Stadt zeigen. (Мені так хочеться показати тобі місто.) Du musst unbedingt den Markt sehen. (Тобі обов’язково треба побачити ринок.) Hast Du Lust auf ein Konzert? Du kannst unseren Kuchen probieren. Der schmeckt super. Bis bald! Ich freue mich auf Dich! (До скорого! Чекаю на тебе з нетерпінням!) У листах Du, Dir, Dich можна писати з великої літери.',
          'Davet yazmak: Wann hast Du Zeit? Komm doch mal nach Leipzig! (Leipzig’e bir gelsene!) Du bist herzlich eingeladen. (İçtenlikle davetlisin.) Wir könnten in den Zoo gehen, an den See fahren, die Altstadt besichtigen (eski şehri gezmek), ein Museum anschauen. Ich möchte Dir so gern die Stadt zeigen. (Sana şehri göstermeyi çok istiyorum.) Du musst unbedingt den Markt sehen. (Pazarı mutlaka görmelisin.) Hast Du Lust auf ein Konzert? Du kannst unseren Kuchen probieren. Der schmeckt super. Bis bald! Ich freue mich auf Dich! (Yakında görüşürüz! Seni dört gözle bekliyorum!) Mektuplarda Du, Dir, Dich büyük harfle yazılabilir.',
        ],
        hint: ['Einladen: Komm doch mal …! Du bist herzlich eingeladen. Am Ende: Bis bald! Ich freue mich auf Dich!', 'Inviting: Komm doch mal …! Du bist herzlich eingeladen. At the end: Bis bald! Ich freue mich auf Dich!', 'Приглашение: Komm doch mal …! Du bist herzlich eingeladen. В конце: Bis bald! Ich freue mich auf Dich!', 'Запрошення: Komm doch mal …! Du bist herzlich eingeladen. Наприкінці: Bis bald! Ich freue mich auf Dich!', 'Davet: Komm doch mal …! Du bist herzlich eingeladen. Sonda: Bis bald! Ich freue mich auf Dich!'],
      },
      ex: [
        mc('K2', 'einladen', I.situation, 'Du lädst einen Freund in deine Stadt ein. Was schreibst du?', ['Komm doch mal nach Bremen! Du bist herzlich eingeladen.', 'Ich komme nicht nach Bremen.', 'Bremen ist ausgebucht.'],
          ['You are inviting a friend to your town. What do you write?', 'Вы приглашаете друга в свой город. Что вы напишете?', 'Ви запрошуєте друга до свого міста. Що ви напишете?', 'Bir arkadaşınızı şehrinize davet ediyorsunuz. Ne yazarsınız?']),
        mc('K2', 'Schluss', I.choose, 'Wie endet eine Einladung an eine Freundin?', ['Bis bald! Ich freue mich auf Dich!', 'Mit freundlichen Grüßen', 'Gute Besserung!'],
          ['How does an invitation to a friend end?', 'Как заканчивается приглашение подруге?', 'Як закінчується запрошення подрузі?', 'Bir arkadaşa yazılan davet nasıl biter?']),
        mc('K2', 'unbedingt', I.choose, 'Du musst … den Dom sehen. Er ist wunderschön!', ['unbedingt', 'leider', 'trotzdem'],
          ['You really must see the cathedral. It is wonderful!', 'Тебе обязательно нужно увидеть собор. Он прекрасен!', 'Тобі обов’язково треба побачити собор. Він чудовий!', 'Katedrali mutlaka görmelisin. Harika!']),
        mc('K2', 'Hast Du Lust auf …?', I.react, '„Hast Du Lust auf einen Ausflug an den See?“', ['Ja, sehr gern! Das klingt toll.', 'Nein, der See ist ausgebucht.', 'Ich freue mich auf Dich.'],
          ['“Do you fancy a trip to the lake?”', '«Хочешь съездить на озеро?»', '«Хочеш з’їздити на озеро?»', '“Göle bir gezi yapmak ister misin?”']),
        mc('K2', 'Dir', I.choose, 'Ich möchte … so gern meine Stadt zeigen.', ['Dir', 'Dich', 'Du'],
          ['I would so like to show you my town.', 'Мне так хочется показать тебе мой город.', 'Мені так хочеться показати тобі моє місто.', 'Sana şehrimi göstermeyi çok istiyorum.']),
        gap('K2', 'besichtigen', I.verb, 'Wir könnten zusammen die Altstadt ', '.', 'besichtigen', ['buchen', 'bestellen'],
          ['We could look round the old town together.', 'Мы могли бы вместе осмотреть старый город.', 'Ми могли б разом оглянути старе місто.', 'Eski şehri birlikte gezebiliriz.'],
          ['look round, visit', 'осмотреть', 'оглянути', 'gezmek']),
        gap('K2', 'herzlich eingeladen', I.word, 'Du bist ', ' eingeladen. Wir haben ein Gästezimmer.', 'herzlich', ['leider', 'unbedingt'],
          ['You are warmly invited. We have a guest room.', 'Сердечно приглашаю тебя. У нас есть комната для гостей.', 'Щиро запрошую тебе. У нас є кімната для гостей.', 'İçtenlikle davetlisin. Bir misafir odamız var.'],
          ['warmly', 'сердечно', 'щиро', 'içtenlikle']),
        gap('K2', 'sich freuen auf', I.pronoun, 'Bis bald! Ich freue mich auf ', '!', 'Dich', ['Dir', 'Du'],
          ['See you soon! I am looking forward to seeing you!', 'До скорого! Жду тебя с нетерпением!', 'До скорого! Чекаю на тебе з нетерпінням!', 'Yakında görüşürüz! Seni dört gözle bekliyorum!'], 'du'),
        gap('K2', 'probieren', I.verb, 'Du kannst unseren Apfelkuchen ', '. Er schmeckt sehr gut.', 'probieren', ['besichtigen', 'zeigen'],
          ['You can try our apple cake. It tastes very good.', 'Ты можешь попробовать наш яблочный пирог. Он очень вкусный.', 'Ти можеш скуштувати наш яблучний пиріг. Він дуже смачний.', 'Elmalı kekimizi tadabilirsin. Çok lezzetli.'],
          ['try, taste', 'попробовать', 'скуштувати', 'tatmak']),
        sb('K2', 'Komm doch mal …!', I.request, 'Komm / doch / mal / nach Leipzig!',
          ['Do come to Leipzig some time!', 'Приезжай как-нибудь в Лейпциг!', 'Приїжджай якось до Лейпцига!', 'Leipzig’e bir gelsene!']),
      ],
    },
    {
      title: 'Wollen wir …?',
      t: ['Shall we …?', 'Давай …?', 'Може, …?', '… yapalım mı?'],
      card: {
        id: 'p5_ausflug',
        rule: 'Einen Ausflug planen: Wollen wir am Wochenende in die Berge fahren? Lass uns doch an den See fahren! Ich habe da einen Vorschlag. Ich habe eine Idee. Darf ich einen Vorschlag machen? Zustimmen: Ja, gut, machen wir es so. Super. Das ist eine gute Idee. Ich bin dafür. Ablehnen: Ach nein, darauf habe ich keine Lust. Das ist aber keine gute Idee. Ich bin dagegen. Unsicher: Also, ich weiß nicht.',
        examples: ['Wollen wir am Samstag wandern gehen?', 'Lass uns doch ans Meer fahren!', 'Ich bin dafür. Machen wir es so.'],
        highlight: null,
        t: [
          'Planning a trip: Wollen wir am Wochenende in die Berge fahren? (Shall we go to the mountains at the weekend?) Lass uns doch an den See fahren! (Let’s go to the lake!) Ich habe da einen Vorschlag. (I have a suggestion.) Ich habe eine Idee. Darf ich einen Vorschlag machen? (May I make a suggestion?) Agreeing: Ja, gut, machen wir es so. (Yes, fine, let’s do it that way.) Super. Das ist eine gute Idee. Ich bin dafür. (I am in favour.) Declining: Ach nein, darauf habe ich keine Lust. (Oh no, I do not feel like that.) Das ist aber keine gute Idee. Ich bin dagegen. (I am against it.) Unsure: Also, ich weiß nicht.',
          'Как планировать поездку: Wollen wir am Wochenende in die Berge fahren? (Поедем в выходные в горы?) Lass uns doch an den See fahren! (Давай поедем на озеро!) Ich habe da einen Vorschlag. (У меня есть предложение.) Ich habe eine Idee. Darf ich einen Vorschlag machen? (Можно мне предложить?) Согласие: Ja, gut, machen wir es so. (Да, хорошо, так и сделаем.) Super. Das ist eine gute Idee. Ich bin dafür. (Я за.) Отказ: Ach nein, darauf habe ich keine Lust. (Ой нет, этого мне не хочется.) Das ist aber keine gute Idee. Ich bin dagegen. (Я против.) Сомнение: Also, ich weiß nicht.',
          'Як планувати поїздку: Wollen wir am Wochenende in die Berge fahren? (Поїдемо у вихідні в гори?) Lass uns doch an den See fahren! (Поїдьмо на озеро!) Ich habe da einen Vorschlag. (У мене є пропозиція.) Ich habe eine Idee. Darf ich einen Vorschlag machen? (Можна мені запропонувати?) Згода: Ja, gut, machen wir es so. (Так, добре, так і зробимо.) Super. Das ist eine gute Idee. Ich bin dafür. (Я за.) Відмова: Ach nein, darauf habe ich keine Lust. (Ой ні, цього мені не хочеться.) Das ist aber keine gute Idee. Ich bin dagegen. (Я проти.) Сумнів: Also, ich weiß nicht.',
          'Gezi planlamak: Wollen wir am Wochenende in die Berge fahren? (Hafta sonu dağlara gidelim mi?) Lass uns doch an den See fahren! (Hadi göle gidelim!) Ich habe da einen Vorschlag. (Bir önerim var.) Ich habe eine Idee. Darf ich einen Vorschlag machen? (Bir öneride bulunabilir miyim?) Kabul etmek: Ja, gut, machen wir es so. (Evet, tamam, öyle yapalım.) Super. Das ist eine gute Idee. Ich bin dafür. (Ben varım.) Reddetmek: Ach nein, darauf habe ich keine Lust. (Yok ya, hiç canım istemiyor.) Das ist aber keine gute Idee. Ich bin dagegen. (Ben karşıyım.) Kararsız: Also, ich weiß nicht.',
        ],
        hint: ['Vorschlag: Wollen wir …? Lass uns doch …! dafür = Ja. dagegen = Nein.', 'Suggestion: Wollen wir …? Lass uns doch …! dafür = yes. dagegen = no.', 'Предложение: Wollen wir …? Lass uns doch …! dafür = за. dagegen = против.', 'Пропозиція: Wollen wir …? Lass uns doch …! dafür = за. dagegen = проти.', 'Öneri: Wollen wir …? Lass uns doch …! dafür = evet. dagegen = hayır.'],
      },
      ex: [
        mc('K3', 'Wollen wir …?', I.situation, 'Du möchtest mit Freunden einen Ausflug an die Ostsee machen. Was schlägst du vor?', ['Wollen wir am Wochenende an die Ostsee fahren?', 'Wir sind am Wochenende an die Ostsee gefahren.', 'Ich fahre nie an die Ostsee.'],
          ['You would like to go on a trip to the Baltic with friends. What do you suggest?', 'Вы хотите съездить с друзьями на Балтийское море. Что вы предложите?', 'Ви хочете з’їздити з друзями на Балтійське море. Що ви запропонуєте?', 'Arkadaşlarınızla Baltık Denizi’ne bir gezi yapmak istiyorsunuz. Ne önerirsiniz?']),
        mc('K3', 'dafür', I.choose, 'Was bedeutet „Ich bin dafür“?', ['Ich finde den Vorschlag gut.', 'Ich finde den Vorschlag schlecht.', 'Ich habe keine Meinung.'],
          ['What does “Ich bin dafür” mean?', 'Что значит «Ich bin dafür»?', 'Що означає «Ich bin dafür»?', '“Ich bin dafür” ne demek?']),
        mc('K3', 'ablehnen', I.react, '„Lass uns doch in die Berge fahren!“ – Du magst die Berge nicht.', ['Ach nein, darauf habe ich keine Lust.', 'Super. Das ist eine gute Idee.', 'Ja, gut, machen wir es so.'],
          ['“Let’s go to the mountains!” – You do not like the mountains.', '«Давай поедем в горы!» – Вы не любите горы.', '«Поїдьмо в гори!» – Ви не любите гори.', '“Hadi dağlara gidelim!” – Dağları sevmiyorsunuz.']),
        mc('K3', 'zustimmen', I.react, '„Wollen wir ein Zelt mitnehmen?“ – Du findest die Idee gut.', ['Ja, gut, machen wir es so.', 'Ich bin dagegen.', 'Das ist aber keine gute Idee.'],
          ['“Shall we take a tent?” – You like the idea.', '«Возьмём с собой палатку?» – Вам нравится идея.', '«Візьмемо із собою намет?» – Вам подобається ідея.', '“Yanımıza çadır alalım mı?” – Fikri beğeniyorsunuz.']),
        mc('K3', 'höflich vorschlagen', I.choose, 'Du möchtest höflich etwas vorschlagen. Was sagst du?', ['Darf ich einen Vorschlag machen?', 'Ich bin dagegen.', 'Das ist keine gute Idee.'],
          ['You want to suggest something politely. What do you say?', 'Вы хотите вежливо что-то предложить. Что вы скажете?', 'Ви хочете ввічливо щось запропонувати. Що ви скажете?', 'Kibarca bir şey önermek istiyorsunuz. Ne dersiniz?']),
        gap('K3', 'Lass uns …', I.pronoun, 'Lass ', ' doch am Sonntag eine Radtour machen!', 'uns', ['wir', 'unser'],
          ['Let’s go on a bike ride on Sunday!', 'Давай в воскресенье поедем на велопрогулку!', 'Поїдьмо в неділю на велопрогулянку!', 'Hadi pazar günü bisiklet turu yapalım!'], 'wir'),
        gap('K3', 'dagegen', I.word, 'Camping im Regen? Nein, ich bin ', '.', 'dagegen', ['dafür', 'darauf'],
          ['Camping in the rain? No, I am against it.', 'Кемпинг под дождём? Нет, я против.', 'Кемпінг під дощем? Ні, я проти.', 'Yağmurda kamp mı? Hayır, ben karşıyım.'],
          ['against it', 'против', 'проти', 'karşıyım']),
        gap('K3', 'Wollen wir …?', I.modal, 'Was machen wir morgen? ', ' wir ins Museum gehen?', 'Wollen', ['Wollt', 'Will'],
          ['What shall we do tomorrow? Shall we go to the museum?', 'Что будем делать завтра? Пойдём в музей?', 'Що робитимемо завтра? Підемо до музею?', 'Yarın ne yapıyoruz? Müzeye gidelim mi?'], 'wollen (wir)'),
        gap('K3', 'Vorschlag', I.word, 'Ich habe da einen ', ': Wir fahren mit dem Zug und nicht mit dem Auto.', 'Vorschlag', ['Aufenthalt', 'Ausflug'],
          ['I have a suggestion: we go by train and not by car.', 'У меня есть предложение: мы поедем на поезде, а не на машине.', 'У мене є пропозиція: ми поїдемо потягом, а не машиною.', 'Bir önerim var: Arabayla değil, trenle gidelim.'],
          ['suggestion', 'предложение', 'пропозиція', 'öneri']),
        sb('K3', 'Lass uns doch …!', I.request, 'Lass / uns / doch / ans Meer / fahren!',
          ['Let’s go to the sea!', 'Давай поедем на море!', 'Поїдьмо на море!', 'Hadi denize gidelim!']),
      ],
    },
    {
      title: 'Familienfreundliches Hotel',
      t: ['Family-friendly hotel', 'Отель для отдыха с детьми', 'Готель для відпочинку з дітьми', 'Aile dostu otel'],
      card: {
        id: 'p5_hotelanzeigen',
        rule: 'Anzeigen für Unterkünfte verstehen: Wo liegt die Unterkunft? (in ruhiger Lage, zentral, direkt am See) Was gibt es? (Zimmer mit Balkon, Frühstück, Schwimmbad, Parkplatz) Für wen? (familienfreundlich = gut für Familien mit Kindern, Hunde willkommen) Was kostet es? (ab 50 Euro pro Nacht, Kinder kostenlos) Wann? (geöffnet von April bis Oktober, von Oktober an günstige Preise) reichhaltig = es gibt sehr viel.',
        examples: ['Familienfreundliches Hotel mit großem Garten.', 'Zimmer ab 45 Euro pro Nacht.', 'Geöffnet von Mai bis September.'],
        highlight: null,
        t: [
          'Understanding ads for accommodation: where is the place? (in ruhiger Lage = in a quiet location, zentral, direkt am See = right by the lake) What is there? (Zimmer mit Balkon, Frühstück, Schwimmbad, Parkplatz) Who for? (familienfreundlich = good for families with children, Hunde willkommen = dogs welcome) How much? (ab 50 Euro pro Nacht = from 50 euros a night, Kinder kostenlos) When? (geöffnet von April bis Oktober, von Oktober an günstige Preise) reichhaltig = there is a great deal of it.',
          'Как понимать объявления о жилье: где находится жильё? (in ruhiger Lage = в тихом месте, zentral, direkt am See = прямо у озера) Что там есть? (Zimmer mit Balkon, Frühstück, Schwimmbad, Parkplatz) Для кого? (familienfreundlich = удобно для семей с детьми, Hunde willkommen = можно с собаками) Сколько стоит? (ab 50 Euro pro Nacht = от 50 евро за ночь, Kinder kostenlos) Когда? (geöffnet von April bis Oktober, von Oktober an günstige Preise) reichhaltig = всего очень много.',
          'Як розуміти оголошення про житло: де розташоване житло? (in ruhiger Lage = у тихому місці, zentral, direkt am See = просто біля озера) Що там є? (Zimmer mit Balkon, Frühstück, Schwimmbad, Parkplatz) Для кого? (familienfreundlich = зручно для родин із дітьми, Hunde willkommen = можна із собаками) Скільки коштує? (ab 50 Euro pro Nacht = від 50 євро за ніч, Kinder kostenlos) Коли? (geöffnet von April bis Oktober, von Oktober an günstige Preise) reichhaltig = усього дуже багато.',
          'Konaklama ilanlarını anlamak: Yer nerede? (in ruhiger Lage = sakin bir konumda, zentral, direkt am See = tam göl kenarında) Neler var? (Zimmer mit Balkon, Frühstück, Schwimmbad, Parkplatz) Kimler için? (familienfreundlich = çocuklu aileler için uygun, Hunde willkommen = köpekler kabul edilir) Ne kadar? (ab 50 Euro pro Nacht = geceliği 50 avrodan başlayan, Kinder kostenlos) Ne zaman? (geöffnet von April bis Oktober, von Oktober an günstige Preise) reichhaltig = çok zengin, bol çeşitli.',
        ],
        hint: ['Such im Text: Wo? Was gibt es? Für wen? Was kostet es? Wann geöffnet?', 'Look in the text: where? what is there? who for? how much? when is it open?', 'Найдите в тексте: где? что там есть? для кого? сколько стоит? когда открыто?', 'Знайдіть у тексті: де? що там є? для кого? скільки коштує? коли відчинено?', 'Metinde arayın: Nerede? Neler var? Kimler için? Ne kadar? Ne zaman açık?'],
      },
      ex: [
        mc('Z1', 'Wo?', I.read, `${HOTEL} Wo liegt das Hotel?`, ['An einem See.', 'Im Gebirge.', 'In der Stadtmitte.'],
          ['Where is the hotel?', 'Где находится отель?', 'Де розташований готель?', 'Otel nerede?']),
        mc('Z1', 'Für wen?', I.read, `${HOTEL} Für wen ist das Hotel besonders gut?`, ['Für Familien mit Kindern.', 'Für Geschäftsleute.', 'Für Gäste mit Hund.'],
          ['Who is the hotel especially good for?', 'Кому этот отель подходит больше всего?', 'Кому цей готель підходить найбільше?', 'Otel özellikle kimler için uygun?']),
        mc('Z1', 'von Oktober an', I.read, `${HOTEL} Wann sind die Preise günstig?`, ['Ab Oktober.', 'Bis Oktober.', 'Nur im Sommer.'],
          ['When are the prices low?', 'Когда цены низкие?', 'Коли ціни низькі?', 'Fiyatlar ne zaman uygun?']),
        mc('Z1', 'kostenlos', I.read, `${HOTEL} Was zahlt ein Kind mit vier Jahren?`, ['Nichts.', 'Die Hälfte.', 'Den vollen Preis.'],
          ['What does a four-year-old child pay?', 'Сколько платят за четырёхлетнего ребёнка?', 'Скільки платять за чотирирічну дитину?', 'Dört yaşındaki bir çocuk ne kadar öder?']),
        mc('Z1', 'Was gibt es?', I.read, `${CAMPING} Was kann man auf dem Campingplatz kaufen?`, ['Brötchen.', 'Zelte.', 'Wohnwagen.'],
          ['What can you buy at the campsite?', 'Что можно купить в кемпинге?', 'Що можна купити в кемпінгу?', 'Kamp alanında ne satın alınabilir?']),
        mc('Z1', 'Wann geschlossen?', I.read, `${CAMPING} Wann ist der Campingplatz geschlossen?`, ['Im Winter.', 'Im Sommer.', 'Im Mai.'],
          ['When is the campsite closed?', 'Когда кемпинг закрыт?', 'Коли кемпінг зачинений?', 'Kamp alanı ne zaman kapalı?']),
        gap('Z1', 'familienfreundlich', I.word, 'Das Hotel ist ', ': Es gibt einen Spielplatz und ein Kinderprogramm.', 'familienfreundlich', ['ausgebucht', 'reichhaltig'],
          ['The hotel is family-friendly: there is a playground and a children’s programme.', 'Отель удобен для семей: там есть детская площадка и программа для детей.', 'Готель зручний для родин: там є дитячий майданчик і програма для дітей.', 'Otel aile dostu: Bir oyun alanı ve çocuk programı var.'],
          ['family-friendly', 'удобный для семей', 'зручний для родин', 'aile dostu']),
      ],
    },
  ],
}

export default path
