import { I, gap, mc, sb } from '../shared.mjs'

const KII = 'sein / haben / werden (Konjunktiv II)'
const LASSEN_DONE = ['have (it done)', 'поручить, дать сделать', 'доручити, дати зробити', 'yaptırmak']
const RATGEBER = 'Ratgeber: „Sie haben Ihre Bankkarte verloren? Dann sollten Sie die Karte sofort sperren lassen. Rufen Sie die Nummer 116 116 an. Der Anruf ist kostenlos und Tag und Nacht möglich. Gehen Sie danach zur Polizei. Eine neue Karte bekommen Sie nach etwa einer Woche von Ihrer Bank.“'
const SPENDE = 'Auf der Straße: „Guten Tag! Eine kleine Spende für die Kinderhilfe? Mit fünf Euro bekommt ein Kind eine Woche lang ein warmes Mittagessen. Sie können bar spenden oder Geld überweisen. Die Bankverbindung steht auf diesem Blatt.“'

/** A2.2 · Pfad 6 · Rund ums Geld – Lektionen. Wiederholung und Test: p6-check.mjs */
const path = {
  n: 6,
  slug: 'rund-ums-geld',
  title: 'Rund ums Geld',
  t: ['All about money', 'Всё о деньгах', 'Усе про гроші', 'Para hakkında her şey'],
  objectives: {
    G1: 'Indirekte Fragen mit Fragewort: Können Sie mir sagen, was ich da tun muss? Wissen Sie, wo man Geld abheben kann? Das Verb steht am Ende.',
    G2: 'Indirekte Fragen bei Ja/Nein-Fragen mit ob: Darf ich fragen, ob Sie Ihren Ausweis dabeihaben?',
    G3: 'Das Verb lassen: ich lasse, du lässt, er lässt, wir lassen, ihr lasst, sie lassen.',
    G4: 'lassen + Infinitiv am Satzende: Sie lässt ihr Konto prüfen. Sie sollten die Reifen wechseln lassen.',
    K1: 'Höflich fragen: Können Sie mir sagen, …? Wissen Sie, …? Ich würde gern wissen, … Darf ich fragen, …?',
    K2: 'Um Hilfe bitten: Können Sie mir helfen? Würden Sie mir das bitte erklären? Was soll ich denn jetzt machen?',
    K3: 'Unkenntnis äußern: Keine Ahnung! Ich kenne mich damit überhaupt nicht aus. Ich weiß nicht, was ich jetzt tun soll.',
    K4: 'Jemanden warnen: Pass auf! Vorsicht! Dann musst du besser aufpassen.',
    K5: 'Gespräche in der Bank führen: Ich möchte gern ein Konto eröffnen. Ich habe meine Geheimzahl vergessen.',
    Z1: 'Kann-Ziele: Ratgebertexte und kurze Texte rund ums Geld verstehen.',
    W1: 'Wortschatz: Bank und Geld.',
  },
  nodes: [
    {
      title: 'Bank und Geld',
      t: ['Bank and money', 'Банк и деньги', 'Банк і гроші', 'Banka ve para'],
      card: {
        id: 'p6_bank',
        rule: 'Bank und Geld: das Konto (das Girokonto), die Bankkarte, die Kreditkarte, die Geheimzahl (die PIN), der Geldautomat, das Bargeld (Münzen und Scheine), die Münze, der Schein, die Überweisung, der Kontoauszug (dort sieht man alle Zahlungen), die Zinsen (Plural), die Gebühr, der Kredit, die Rate (man zahlt jeden Monat einen Teil), die Spende (Geld für einen guten Zweck), die Bankverbindung (IBAN).',
        examples: ['Am Geldautomaten braucht man die Geheimzahl.', 'Ich zahle lieber bar als mit Karte.', 'Auf dem Kontoauszug sehe ich meine Miete.'],
        highlight: 'article',
        t: [
          'Bank and money: das Konto (account; das Girokonto = current account), die Bankkarte (bank card), die Kreditkarte (credit card), die Geheimzahl (PIN), der Geldautomat (cash machine), das Bargeld (cash: coins and notes), die Münze (coin), der Schein (note), die Überweisung (bank transfer), der Kontoauszug (bank statement: it shows all payments), die Zinsen (interest, plural), die Gebühr (fee), der Kredit (loan), die Rate (instalment: you pay part of it every month), die Spende (donation: money for a good cause), die Bankverbindung (bank details, IBAN).',
          'Банк и деньги: das Konto (счёт; das Girokonto = текущий счёт), die Bankkarte (банковская карта), die Kreditkarte (кредитная карта), die Geheimzahl (ПИН-код), der Geldautomat (банкомат), das Bargeld (наличные: монеты и купюры), die Münze (монета), der Schein (купюра), die Überweisung (перевод), der Kontoauszug (выписка со счёта: там видны все платежи), die Zinsen (проценты, множественное число), die Gebühr (комиссия), der Kredit (кредит), die Rate (взнос: каждый месяц платят часть), die Spende (пожертвование: деньги на доброе дело), die Bankverbindung (банковские реквизиты, IBAN).',
          'Банк і гроші: das Konto (рахунок; das Girokonto = поточний рахунок), die Bankkarte (банківська картка), die Kreditkarte (кредитна картка), die Geheimzahl (ПІН-код), der Geldautomat (банкомат), das Bargeld (готівка: монети й купюри), die Münze (монета), der Schein (купюра), die Überweisung (переказ), der Kontoauszug (виписка з рахунку: там видно всі платежі), die Zinsen (відсотки, множина), die Gebühr (комісія), der Kredit (кредит), die Rate (внесок: щомісяця платять частину), die Spende (пожертва: гроші на добру справу), die Bankverbindung (банківські реквізити, IBAN).',
          'Banka ve para: das Konto (hesap; das Girokonto = vadesiz hesap), die Bankkarte (banka kartı), die Kreditkarte (kredi kartı), die Geheimzahl (şifre, PIN), der Geldautomat (bankamatik), das Bargeld (nakit: madeni ve kâğıt para), die Münze (madeni para), der Schein (banknot), die Überweisung (havale), der Kontoauszug (hesap özeti: bütün ödemeler orada görünür), die Zinsen (faiz, çoğul), die Gebühr (ücret), der Kredit (kredi), die Rate (taksit: her ay bir kısmı ödenir), die Spende (bağış: iyi bir amaç için para), die Bankverbindung (banka bilgileri, IBAN).',
        ],
        hint: ['Bargeld = Münzen und Scheine. Geheimzahl = PIN. Kontoauszug = Liste von allen Zahlungen. Rate = jeden Monat ein Teil.', 'Bargeld = coins and notes. Geheimzahl = PIN. Kontoauszug = list of all payments. Rate = a part every month.', 'Bargeld = монеты и купюры. Geheimzahl = ПИН-код. Kontoauszug = список всех платежей. Rate = часть суммы каждый месяц.', 'Bargeld = монети й купюри. Geheimzahl = ПІН-код. Kontoauszug = список усіх платежів. Rate = частина суми щомісяця.', 'Bargeld = madeni ve kâğıt para. Geheimzahl = PIN. Kontoauszug = bütün ödemelerin listesi. Rate = her ay bir kısmı.'],
      },
      ex: [
        mc('W1', 'Geldautomat', I.choose, 'Wo bekommt man auch am Sonntag Bargeld?', ['am Geldautomaten', 'am Kontoauszug', 'an der Geheimzahl'],
          ['Where can you get cash on a Sunday too?', 'Где можно получить наличные даже в воскресенье?', 'Де можна отримати готівку навіть у неділю?', 'Pazar günü bile nereden nakit alınabilir?']),
        mc('W1', 'Geheimzahl', I.choose, 'Vier Zahlen, die nur du kennst. Du brauchst sie für deine Bankkarte. Das ist die …', ['Geheimzahl', 'Gebühr', 'Spende'],
          ['Four digits that only you know. You need them for your bank card. That is the …', 'Четыре цифры, которые знаете только вы. Они нужны для банковской карты. Это …', 'Чотири цифри, які знаєте лише ви. Вони потрібні для банківської картки. Це …', 'Yalnızca sizin bildiğiniz dört rakam. Banka kartınız için gerekiyor. Bu …']),
        mc('W1', 'Bargeld', I.choose, 'Was ist Bargeld?', ['Münzen und Scheine', 'eine Kreditkarte', 'eine Überweisung'],
          ['What is “Bargeld”?', 'Что такое «Bargeld»?', 'Що таке «Bargeld»?', '“Bargeld” nedir?']),
        mc('W1', 'Bank', I.odd, 'Drei Wörter passen zur Bank, ein Wort nicht.', ['Gewitter', 'Konto', 'Zinsen', 'Kredit'], null),
        mc('W1', 'Raten', I.choose, 'Du kaufst ein Sofa und zahlst jeden Monat 50 Euro. Du zahlst in …', ['Raten', 'Zinsen', 'Münzen'],
          ['You buy a sofa and pay 50 euros every month. You are paying in …', 'Вы покупаете диван и каждый месяц платите по 50 евро. Вы платите …', 'Ви купуєте диван і щомісяця платите по 50 євро. Ви платите …', 'Bir kanepe alıyor ve her ay 50 avro ödüyorsunuz. Ödemeyi … yapıyorsunuz.']),
        gap('W1', 'Kontoauszug', I.word, 'Auf dem ', ' sehe ich, wie viel Geld ich im Mai ausgegeben habe.', 'Kontoauszug', ['Geldautomat', 'Bargeld'],
          ['On my bank statement I can see how much money I spent in May.', 'В выписке со счёта я вижу, сколько денег потратил в мае.', 'У виписці з рахунку я бачу, скільки грошей витратив у травні.', 'Hesap özetinde mayıs ayında ne kadar para harcadığımı görüyorum.'],
          ['bank statement', 'выписка со счёта', 'виписка з рахунку', 'hesap özeti']),
        gap('W1', 'Münze', I.word, 'Ein Euro ist eine ', ', zehn Euro sind ein Schein.', 'Münze', ['Rate', 'Gebühr'],
          ['One euro is a coin, ten euros are a note.', 'Один евро – это монета, десять евро – купюра.', 'Один євро – це монета, десять євро – купюра.', 'Bir avro madeni paradır, on avro ise banknottur.'],
          ['coin', 'монета', 'монета', 'madeni para']),
        gap('W1', 'Spende', I.word, 'Wir geben jedes Jahr eine ', ' für arme Kinder.', 'Spende', ['Gebühr', 'Rate'],
          ['Every year we make a donation for poor children.', 'Каждый год мы делаем пожертвование для бедных детей.', 'Щороку ми робимо пожертву для бідних дітей.', 'Her yıl yoksul çocuklar için bağış yapıyoruz.'],
          ['donation', 'пожертвование', 'пожертва', 'bağış']),
        gap('W1', 'Gebühr', I.word, 'Für das Konto zahle ich jeden Monat eine ', ' von drei Euro.', 'Gebühr', ['Spende', 'Münze'],
          ['I pay a fee of three euros a month for the account.', 'За счёт я каждый месяц плачу комиссию три евро.', 'За рахунок я щомісяця плачу комісію три євро.', 'Hesap için her ay üç avro ücret ödüyorum.'],
          ['fee, charge', 'комиссия, сбор', 'комісія, збір', 'ücret']),
        sb('W1', 'Geheimzahl', I.order, 'Ich / habe / meine Geheimzahl / vergessen.',
          ['I have forgotten my PIN.', 'Я забыл свой ПИН-код.', 'Я забув свій ПІН-код.', 'Şifremi unuttum.'],
          { alt: ['Meine Geheimzahl habe ich vergessen.'] }),
      ],
    },
    {
      title: 'abheben, überweisen, einzahlen',
      t: ['abheben, überweisen, einzahlen (withdraw, transfer, pay in)', 'abheben, überweisen, einzahlen (снять, перевести, внести)', 'abheben, überweisen, einzahlen (зняти, переказати, внести)', 'abheben, überweisen, einzahlen (çekmek, havale etmek, yatırmak)'],
      card: {
        id: 'p6_geldverben',
        rule: 'Verben rund ums Geld: Geld abheben (vom Konto holen), Geld einzahlen (auf das Konto legen), Geld überweisen (von Konto zu Konto schicken), ein Konto eröffnen (ein neues Konto bekommen), bar zahlen oder mit Karte zahlen, Geld sparen, Geld leihen (für kurze Zeit geben oder bekommen), Geld wechseln (Euro in Dollar), Geld verdienen, Geld ausgeben, die Karte sperren (niemand kann sie mehr benutzen).',
        examples: ['Ich hebe 100 Euro am Automaten ab.', 'Die Miete überweise ich am ersten Tag im Monat.', 'Kann ich hier mit Karte zahlen?'],
        highlight: 'verb',
        t: [
          'Verbs to do with money: Geld abheben (withdraw money from your account), Geld einzahlen (pay money into your account), Geld überweisen (transfer money from one account to another), ein Konto eröffnen (open an account), bar zahlen (pay in cash) or mit Karte zahlen (pay by card), Geld sparen (save money), Geld leihen (lend or borrow for a short time), Geld wechseln (change money: euros into dollars), Geld verdienen (earn money), Geld ausgeben (spend money), die Karte sperren (block the card: nobody can use it any more).',
          'Глаголы о деньгах: Geld abheben (снять деньги со счёта), Geld einzahlen (внести деньги на счёт), Geld überweisen (перевести деньги со счёта на счёт), ein Konto eröffnen (открыть счёт), bar zahlen (платить наличными) или mit Karte zahlen (платить картой), Geld sparen (копить, экономить), Geld leihen (одолжить или взять в долг на короткое время), Geld wechseln (обменять деньги: евро на доллары), Geld verdienen (зарабатывать), Geld ausgeben (тратить), die Karte sperren (заблокировать карту: ею больше никто не сможет пользоваться).',
          'Дієслова про гроші: Geld abheben (зняти гроші з рахунку), Geld einzahlen (внести гроші на рахунок), Geld überweisen (переказати гроші з рахунку на рахунок), ein Konto eröffnen (відкрити рахунок), bar zahlen (платити готівкою) або mit Karte zahlen (платити карткою), Geld sparen (заощаджувати), Geld leihen (позичити на короткий час), Geld wechseln (обміняти гроші: євро на долари), Geld verdienen (заробляти), Geld ausgeben (витрачати), die Karte sperren (заблокувати картку: нею більше ніхто не зможе користуватися).',
          'Parayla ilgili fiiller: Geld abheben (hesaptan para çekmek), Geld einzahlen (hesaba para yatırmak), Geld überweisen (bir hesaptan diğerine havale etmek), ein Konto eröffnen (hesap açmak), bar zahlen (nakit ödemek) ya da mit Karte zahlen (kartla ödemek), Geld sparen (para biriktirmek), Geld leihen (kısa süreliğine borç vermek ya da almak), Geld wechseln (para bozdurmak: avroyu dolara), Geld verdienen (para kazanmak), Geld ausgeben (para harcamak), die Karte sperren (kartı bloke etmek: artık kimse kullanamaz).',
        ],
        hint: ['abheben = Geld vom Konto holen. einzahlen = Geld auf das Konto legen. überweisen = Geld auf ein anderes Konto schicken.', 'abheben = take money out of your account. einzahlen = put money into your account. überweisen = send money to another account.', 'abheben = снять деньги со счёта. einzahlen = внести деньги на счёт. überweisen = отправить деньги на другой счёт.', 'abheben = зняти гроші з рахунку. einzahlen = внести гроші на рахунок. überweisen = надіслати гроші на інший рахунок.', 'abheben = hesaptan para çekmek. einzahlen = hesaba para yatırmak. überweisen = başka bir hesaba para göndermek.'],
      },
      ex: [
        mc('W1', 'abheben', I.choose, 'Du brauchst Bargeld und gehst zum Automaten. Was machst du?', ['Ich hebe Geld ab.', 'Ich zahle Geld ein.', 'Ich überweise Geld.'],
          ['You need cash and go to the cash machine. What do you do?', 'Вам нужны наличные, и вы идёте к банкомату. Что вы делаете?', 'Вам потрібна готівка, і ви йдете до банкомата. Що ви робите?', 'Nakde ihtiyacınız var ve bankamatiğe gidiyorsunuz. Ne yapıyorsunuz?']),
        mc('W1', 'überweisen', I.choose, 'Was bedeutet „Geld überweisen“?', ['Geld von einem Konto auf ein anderes Konto schicken', 'Geld am Automaten holen', 'Geld in Münzen wechseln'],
          ['What does “Geld überweisen” mean?', 'Что значит «Geld überweisen»?', 'Що означає «Geld überweisen»?', '“Geld überweisen” ne demek?']),
        mc('W1', 'sperren', I.choose, 'Deine Bankkarte ist weg. Was musst du sofort tun?', ['die Karte sperren lassen', 'ein Konto eröffnen', 'Geld einzahlen'],
          ['Your bank card has gone. What must you do straight away?', 'Ваша банковская карта пропала. Что нужно сделать немедленно?', 'Ваша банківська картка зникла. Що треба зробити негайно?', 'Banka kartınız kayboldu. Hemen ne yapmalısınız?']),
        mc('W1', 'mit Karte zahlen', I.situation, 'Du hast kein Bargeld dabei. Was fragst du an der Kasse?', ['Kann ich mit Karte zahlen?', 'Kann ich Geld einzahlen?', 'Kann ich ein Konto eröffnen?'],
          ['You have no cash on you. What do you ask at the till?', 'У вас нет с собой наличных. Что вы спросите на кассе?', 'У вас немає із собою готівки. Що ви запитаєте на касі?', 'Yanınızda nakit yok. Kasada ne sorarsınız?']),
        mc('W1', 'einzahlen', I.choose, 'Emre bringt 500 Euro in bar zur Bank auf sein Konto. Was macht er?', ['Er zahlt Geld ein.', 'Er hebt Geld ab.', 'Er leiht Geld.'],
          ['Emre takes 500 euros in cash to the bank and puts it into his account. What is he doing?', 'Emre несёт 500 евро наличными в банк на свой счёт. Что он делает?', 'Emre несе 500 євро готівкою до банку на свій рахунок. Що він робить?', 'Emre 500 avro nakdi bankaya, hesabına götürüyor. Ne yapıyor?']),
        gap('W1', 'eröffnen', I.verb, 'Ich bin neu in Deutschland und möchte ein Konto ', '.', 'eröffnen', ['abheben', 'überweisen'],
          ['I am new in Germany and would like to open an account.', 'Я недавно в Германии и хочу открыть счёт.', 'Я нещодавно в Німеччині й хочу відкрити рахунок.', 'Almanya’da yeniyim ve bir hesap açmak istiyorum.'],
          ['open', 'открыть', 'відкрити', 'açmak']),
        gap('W1', 'überweisen', I.verb, 'Bitte ', ' Sie die Miete bis zum dritten Tag im Monat auf mein Konto.', 'überweisen', ['abheben', 'wechseln'],
          ['Please transfer the rent to my account by the third day of the month.', 'Пожалуйста, переводите арендную плату на мой счёт до третьего числа месяца.', 'Будь ласка, переказуйте орендну плату на мій рахунок до третього числа місяця.', 'Lütfen kirayı ayın üçüne kadar hesabıma havale edin.'],
          ['transfer', 'перевести', 'переказати', 'havale etmek']),
        gap('W1', 'bar', I.word, 'Zahlen Sie mit Karte oder ', '?', 'bar', ['teuer', 'billig'],
          ['Are you paying by card or in cash?', 'Вы платите картой или наличными?', 'Ви платите карткою чи готівкою?', 'Kartla mı ödüyorsunuz, nakit mi?'],
          ['in cash', 'наличными', 'готівкою', 'nakit']),
        gap("W1", "sparen", I.verb, "Leon möchte ein Auto kaufen. Er ", " jeden Monat 200 Euro.", "spart", ["spare","sparen"], ["Leon wants to buy a car. He saves 200 euros every month.","Leon хочет купить машину. Каждый месяц он откладывает 200 евро.","Leon хоче купити машину. Щомісяця він відкладає 200 євро.","Leon araba almak istiyor. Her ay 200 avro biriktiriyor."], "sparen", {"c":"p6_geldverben"}),
        sb('W1', 'abheben', I.order, 'Ich / hebe / am Automaten / 100 Euro / ab.',
          ['I am withdrawing 100 euros from the cash machine.', 'Я снимаю в банкомате 100 евро.', 'Я знімаю в банкоматі 100 євро.', 'Bankamatikten 100 avro çekiyorum.'],
          { alt: ['Am Automaten hebe ich 100 Euro ab.', 'Ich hebe 100 Euro am Automaten ab.', '100 Euro hebe ich am Automaten ab.'] }),
      ],
    },
    {
      title: 'Können Sie mir sagen, wo …?',
      t: ['Can you tell me where …?', 'Вы не подскажете, где …?', 'Ви не підкажете, де …?', '… nerede, söyleyebilir misiniz?'],
      card: {
        id: 'p6_indirekt',
        rule: 'Indirekte Fragen mit Fragewort sind höflicher als direkte Fragen. Direkt: Wo kann man Geld abheben? Indirekt: Können Sie mir sagen, wo man Geld abheben kann? Die indirekte Frage ist ein Nebensatz: Das Fragewort (was, wo, wann, wie, warum, wer) steht am Anfang, das Verb am Ende. Wissen Sie, wann die Bank öffnet? Ich weiß nicht, was ich tun muss. Vor dem Fragewort steht ein Komma.',
        examples: ['Können Sie mir sagen, wo der Geldautomat ist?', 'Wissen Sie, wann die Bank öffnet?', 'Ich weiß nicht, wie das funktioniert.'],
        highlight: 'verb',
        t: [
          'Indirect questions with a question word are more polite than direct questions. Direct: Wo kann man Geld abheben? Indirect: Können Sie mir sagen, wo man Geld abheben kann? (Can you tell me where you can withdraw money?) The indirect question is a subordinate clause: the question word (was, wo, wann, wie, warum, wer) comes first, the verb goes at the end. Wissen Sie, wann die Bank öffnet? Ich weiß nicht, was ich tun muss. There is a comma before the question word.',
          'Косвенные вопросы с вопросительным словом вежливее прямых. Прямой: Wo kann man Geld abheben? Косвенный: Können Sie mir sagen, wo man Geld abheben kann? (Вы не подскажете, где можно снять деньги?) Косвенный вопрос – это придаточное предложение: вопросительное слово (was, wo, wann, wie, warum, wer) стоит в начале, глагол – в конце. Wissen Sie, wann die Bank öffnet? Ich weiß nicht, was ich tun muss. Перед вопросительным словом ставится запятая.',
          'Непрямі запитання з питальним словом ввічливіші за прямі. Пряме: Wo kann man Geld abheben? Непряме: Können Sie mir sagen, wo man Geld abheben kann? (Ви не підкажете, де можна зняти гроші?) Непряме запитання – це підрядне речення: питальне слово (was, wo, wann, wie, warum, wer) стоїть на початку, дієслово – у кінці. Wissen Sie, wann die Bank öffnet? Ich weiß nicht, was ich tun muss. Перед питальним словом ставиться кома.',
          'Soru kelimeli dolaylı sorular doğrudan sorulardan daha kibardır. Doğrudan: Wo kann man Geld abheben? Dolaylı: Können Sie mir sagen, wo man Geld abheben kann? (Nereden para çekilebileceğini söyleyebilir misiniz?) Dolaylı soru bir yan cümledir: Soru kelimesi (was, wo, wann, wie, warum, wer) başta, fiil sonda durur. Wissen Sie, wann die Bank öffnet? Ich weiß nicht, was ich tun muss. Soru kelimesinden önce virgül konur.',
        ],
        hint: ['Einleitung + Komma + Fragewort … Verb am Ende: Wissen Sie, wo die Bank ist?', 'Opening phrase + comma + question word … verb at the end: Wissen Sie, wo die Bank ist?', 'Вводная фраза + запятая + вопросительное слово … глагол в конце: Wissen Sie, wo die Bank ist?', 'Вступна фраза + кома + питальне слово … дієслово в кінці: Wissen Sie, wo die Bank ist?', 'Giriş cümlesi + virgül + soru kelimesi … fiil sonda: Wissen Sie, wo die Bank ist?'],
      },
      ex: [
        mc('G1', 'Verb am Ende', I.choose, 'Wie heißt die Frage höflicher? „Wo ist die Bank?“', ['Können Sie mir sagen, wo die Bank ist?', 'Können Sie mir sagen, wo ist die Bank?', 'Können Sie mir sagen, die Bank wo ist?'],
          ['What is the more polite form of the question? “Where is the bank?”', 'Как задать этот вопрос вежливее? «Где находится банк?»', 'Як поставити це запитання ввічливіше? «Де розташований банк?»', 'Bu soru daha kibar nasıl sorulur? “Banka nerede?”']),
        mc('G1', 'wann', I.choose, 'Wissen Sie, … die Bank heute schließt?', ['wann', 'wer', 'was'],
          ['Do you know when the bank closes today?', 'Вы не знаете, когда сегодня закрывается банк?', 'Ви не знаєте, коли сьогодні зачиняється банк?', 'Bankanın bugün ne zaman kapandığını biliyor musunuz?']),
        mc('G1', 'Verb am Ende', I.sentence, 'Samir fragt am Schalter.', ['Wissen Sie, wann der Chef kommt?', 'Wissen Sie, wann kommt der Chef?', 'Wissen Sie, der Chef wann kommt?'],
          ['Samir is asking at the counter.', 'Samir спрашивает у стойки.', 'Samir питає біля стійки.', 'Samir gişede soruyor.']),
        mc('G1', 'wo', I.choose, 'Können Sie mir sagen, … ich das Formular abgeben muss? – Am Schalter 3.', ['wo', 'was', 'wer'],
          ['Can you tell me where I have to hand in the form? – At counter 3.', 'Вы не подскажете, куда нужно сдать бланк? – В окошко 3.', 'Ви не підкажете, куди треба здати бланк? – У віконце 3.', 'Formu nereye teslim etmem gerektiğini söyleyebilir misiniz? – 3 numaralı gişeye.']),
        mc('G1', 'direkt → indirekt', I.choose, 'Wie heißt die indirekte Frage? „Was kostet ein Konto?“', ['Ich möchte wissen, was ein Konto kostet.', 'Ich möchte wissen, was kostet ein Konto.', 'Ich möchte wissen, ein Konto was kostet.'],
          ['What is the indirect question? “How much does an account cost?”', 'Как будет косвенный вопрос? «Сколько стоит счёт?»', 'Як буде непряме запитання? «Скільки коштує рахунок?»', 'Dolaylı soru nasıl olur? “Bir hesap ne kadar?”']),
        gap('G1', 'Verb am Ende', I.modal, 'Können Sie mir sagen, wo ich Geld abheben ', '?', 'kann', ['können', 'könnt'],
          ['Can you tell me where I can withdraw money?', 'Вы не подскажете, где я могу снять деньги?', 'Ви не підкажете, де я можу зняти гроші?', 'Nereden para çekebileceğimi söyleyebilir misiniz?'], 'können'),
        gap('G1', 'wo', I.qword, 'Wissen Sie, ', ' der Geldautomat ist? – Gleich neben dem Eingang.', 'wo', ['was', 'wann'],
          ['Do you know where the cash machine is? – Right next to the entrance.', 'Вы не знаете, где банкомат? – Сразу рядом со входом.', 'Ви не знаєте, де банкомат? – Одразу біля входу.', 'Bankamatiğin nerede olduğunu biliyor musunuz? – Girişin hemen yanında.'], 'wo / was / wann'),
        gap('G1', 'Verb am Ende', I.verb, 'Ich weiß nicht, wann die Bank ', '.', 'öffnet', ['öffnen', 'geöffnet'],
          ['I do not know when the bank opens.', 'Я не знаю, когда открывается банк.', 'Я не знаю, коли відчиняється банк.', 'Bankanın ne zaman açıldığını bilmiyorum.'], 'öffnen'),
        gap('G1', 'wie', I.qword, 'Können Sie mir erklären, ', ' ich dieses Formular ausfülle?', 'wie', ['wer', 'wo'],
          ['Can you explain to me how I fill in this form?', 'Вы не могли бы объяснить, как заполнить этот бланк?', 'Чи не могли б ви пояснити, як заповнити цей бланк?', 'Bu formu nasıl dolduracağımı açıklayabilir misiniz?'], 'wie / wer / wo'),
        sb('G1', 'indirekte Frage', I.question, 'Wissen / Sie, / wo / die Bank / ist?',
          ['Do you know where the bank is?', 'Вы не знаете, где банк?', 'Ви не знаєте, де банк?', 'Bankanın nerede olduğunu biliyor musunuz?']),
      ],
    },
    {
      title: 'Wissen Sie, ob …?',
      t: ['Do you know whether …?', 'Вы не знаете, … ли …?', 'Ви не знаєте, чи …?', '… olup olmadığını biliyor musunuz?'],
      card: {
        id: 'p6_ob',
        rule: 'Indirekte Ja/Nein-Fragen beginnen mit ob. Direkt: Haben Sie Ihren Ausweis dabei? Indirekt: Darf ich fragen, ob Sie Ihren Ausweis dabeihaben? Direkt: Kann ich mit Karte zahlen? Indirekt: Wissen Sie, ob ich mit Karte zahlen kann? Nach ob steht das Verb am Ende. Trennbare Verben schreibt man am Ende zusammen: dabeihaben, anrufen. Können Sie mal nachsehen, ob das Geld angekommen ist?',
        examples: ['Wissen Sie, ob die Bank am Samstag geöffnet hat?', 'Darf ich fragen, ob Sie einen Termin haben?', 'Ich weiß nicht, ob er heute kommt.'],
        highlight: 'verb',
        t: [
          'Indirect yes/no questions begin with ob (whether, if). Direct: Haben Sie Ihren Ausweis dabei? Indirect: Darf ich fragen, ob Sie Ihren Ausweis dabeihaben? (May I ask whether you have your ID with you?) Direct: Kann ich mit Karte zahlen? Indirect: Wissen Sie, ob ich mit Karte zahlen kann? After ob the verb goes at the end. Separable verbs are written as one word at the end: dabeihaben, anrufen. Können Sie mal nachsehen, ob das Geld angekommen ist? (Could you check whether the money has arrived?)',
          'Косвенные вопросы, на которые отвечают «да» или «нет», начинаются с ob (ли). Прямой: Haben Sie Ihren Ausweis dabei? Косвенный: Darf ich fragen, ob Sie Ihren Ausweis dabeihaben? (Можно спросить, с собой ли у вас удостоверение?) Прямой: Kann ich mit Karte zahlen? Косвенный: Wissen Sie, ob ich mit Karte zahlen kann? После ob глагол стоит в конце. Отделяемые глаголы в конце пишутся слитно: dabeihaben, anrufen. Können Sie mal nachsehen, ob das Geld angekommen ist? (Вы не могли бы проверить, пришли ли деньги?)',
          'Непрямі запитання, на які відповідають «так» або «ні», починаються з ob (чи). Пряме: Haben Sie Ihren Ausweis dabei? Непряме: Darf ich fragen, ob Sie Ihren Ausweis dabeihaben? (Можна запитати, чи маєте ви із собою посвідчення?) Пряме: Kann ich mit Karte zahlen? Непряме: Wissen Sie, ob ich mit Karte zahlen kann? Після ob дієслово стоїть у кінці. Відокремлювані дієслова в кінці пишуться разом: dabeihaben, anrufen. Können Sie mal nachsehen, ob das Geld angekommen ist? (Чи не могли б ви перевірити, чи надійшли гроші?)',
          'Evet/hayır cevaplı dolaylı sorular ob ile başlar. Doğrudan: Haben Sie Ihren Ausweis dabei? Dolaylı: Darf ich fragen, ob Sie Ihren Ausweis dabeihaben? (Kimliğinizin yanınızda olup olmadığını sorabilir miyim?) Doğrudan: Kann ich mit Karte zahlen? Dolaylı: Wissen Sie, ob ich mit Karte zahlen kann? ob’dan sonra fiil sonda durur. Ayrılabilen fiiller sonda bitişik yazılır: dabeihaben, anrufen. Können Sie mal nachsehen, ob das Geld angekommen ist? (Paranın gelip gelmediğine bakabilir misiniz?)',
        ],
        hint: ['Ja/Nein-Frage → ob … Verb am Ende: Wissen Sie, ob die Bank geöffnet hat?', 'Yes/no question → ob … verb at the end: Wissen Sie, ob die Bank geöffnet hat?', 'Вопрос с ответом да/нет → ob … глагол в конце: Wissen Sie, ob die Bank geöffnet hat?', 'Запитання з відповіддю так/ні → ob … дієслово в кінці: Wissen Sie, ob die Bank geöffnet hat?', 'Evet/hayır sorusu → ob … fiil sonda: Wissen Sie, ob die Bank geöffnet hat?'],
      },
      ex: [
        mc('G2', 'ob … Verb am Ende', I.choose, 'Wie heißt die Frage höflicher? „Ist die Bank heute geöffnet?“', ['Wissen Sie, ob die Bank heute geöffnet ist?', 'Wissen Sie, ob ist die Bank heute geöffnet?', 'Wissen Sie, dass die Bank heute geöffnet ist?'],
          ['What is the more polite form of the question? “Is the bank open today?”', 'Как задать этот вопрос вежливее? «Банк сегодня открыт?»', 'Як поставити це запитання ввічливіше? «Банк сьогодні відчинений?»', 'Bu soru daha kibar nasıl sorulur? “Banka bugün açık mı?”']),
        mc('G2', 'ob', I.choose, 'Können Sie mal nachsehen, … das Geld schon da ist?', ['ob', 'wenn', 'dass'],
          ['Could you check whether the money is there yet?', 'Вы не могли бы проверить, пришли ли уже деньги?', 'Чи не могли б ви перевірити, чи вже надійшли гроші?', 'Paranın gelip gelmediğine bakabilir misiniz?']),
        mc('G2', 'ob … Verb am Ende', I.sentence, 'Die Bankangestellte fragt nach dem Ausweis.', ['Darf ich fragen, ob Sie Ihren Ausweis dabeihaben?', 'Darf ich fragen, ob haben Sie Ihren Ausweis dabei?', 'Darf ich fragen, ob Sie haben Ihren Ausweis dabei?'],
          ['The bank clerk is asking about the ID.', 'Сотрудница банка спрашивает об удостоверении.', 'Працівниця банку питає про посвідчення.', 'Banka görevlisi kimliği soruyor.']),
        mc('G2', 'ob', I.choose, 'Ich weiß nicht, … ich genug Geld auf dem Konto habe.', ['ob', 'was', 'wer'],
          ['I do not know whether I have enough money in my account.', 'Я не знаю, достаточно ли у меня денег на счёте.', 'Я не знаю, чи достатньо в мене грошей на рахунку.', 'Hesabımda yeterli para olup olmadığını bilmiyorum.']),
        mc('G2', 'direkt → indirekt', I.choose, 'Wie heißt die indirekte Frage? „Kann ich hier Geld wechseln?“', ['Ich möchte wissen, ob ich hier Geld wechseln kann.', 'Ich möchte wissen, ob kann ich hier Geld wechseln.', 'Ich möchte wissen, ob ich kann hier Geld wechseln.'],
          ['What is the indirect question? “Can I change money here?”', 'Как будет косвенный вопрос? «Можно ли здесь обменять деньги?»', 'Як буде непряме запитання? «Чи можна тут обміняти гроші?»', 'Dolaylı soru nasıl olur? “Burada para bozdurabilir miyim?”']),
        gap('G2', 'ob', I.conjunction, 'Wissen Sie, ', ' man hier mit Kreditkarte zahlen kann?', 'ob', ['dass', 'weil'],
          ['Do you know whether you can pay by credit card here?', 'Вы не знаете, можно ли здесь заплатить кредитной картой?', 'Ви не знаєте, чи можна тут заплатити кредитною карткою?', 'Burada kredi kartıyla ödenip ödenemeyeceğini biliyor musunuz?'], 'ob / dass / weil'),
        gap('G2', 'Verb am Ende', I.verb, 'Können Sie mir sagen, ob der Automat ', '? Ich bekomme kein Geld.', 'funktioniert', ['funktionieren', 'funktionierst'],
          ['Can you tell me whether the machine is working? I am not getting any money.', 'Вы не подскажете, работает ли банкомат? Я не могу получить деньги.', 'Ви не підкажете, чи працює банкомат? Я не можу отримати гроші.', 'Bankamatiğin çalışıp çalışmadığını söyleyebilir misiniz? Para alamıyorum.'], 'funktionieren'),
        gap('G2', 'Verb am Ende', I.verb, 'Ich frage mal, ob die Bank am Samstag geöffnet ', '.', ['hat', 'ist'], ['haben', 'hast'],
          ['I will ask whether the bank is open on Saturdays.', 'Я спрошу, открыт ли банк в субботу.', 'Я запитаю, чи відчинений банк у суботу.', 'Bankanın cumartesi açık olup olmadığını bir sorayım.'], 'haben'),
        gap('G2', 'ob', I.conjunction, 'Darf ich fragen, ', ' Sie schon ein Konto bei uns haben?', 'ob', ['wenn', 'dass'],
          ['May I ask whether you already have an account with us?', 'Можно спросить, есть ли у вас уже счёт в нашем банке?', 'Можна запитати, чи маєте ви вже рахунок у нашому банку?', 'Bizde bir hesabınız olup olmadığını sorabilir miyim?'], 'ob / wenn / dass'),
        sb('G2', 'ob … Verb am Ende', I.order, 'Ich / weiß / nicht, / ob / er / heute / kommt.',
          ['I do not know whether he is coming today.', 'Я не знаю, придёт ли он сегодня.', 'Я не знаю, чи прийде він сьогодні.', 'Bugün gelip gelmeyeceğini bilmiyorum.']),
      ],
    },
    {
      title: 'ob oder Fragewort?',
      t: ['ob or a question word?', 'ob или вопросительное слово?', 'ob чи питальне слово?', 'ob mu, soru kelimesi mi?'],
      card: {
        id: 'p6_ob_oder_w',
        rule: 'ob oder Fragewort? Hat die direkte Frage ein Fragewort (wann, wo, was, wie, warum, wer), bleibt es: Wann kommt der Bus? → Weißt du, wann der Bus kommt? Beginnt die direkte Frage mit dem Verb (Antwort: Ja oder Nein), nimmt man ob: Kommt der Bus? → Weißt du, ob der Bus kommt? In beiden Fällen steht das Verb am Ende.',
        examples: ['Wo ist die Kasse? → Wissen Sie, wo die Kasse ist?', 'Ist die Kasse offen? → Wissen Sie, ob die Kasse offen ist?', 'Ich frage, wie viel es kostet und ob es einen Rabatt gibt.'],
        highlight: null,
        t: [
          'ob or a question word? If the direct question has a question word (wann, wo, was, wie, warum, wer), it stays: Wann kommt der Bus? → Weißt du, wann der Bus kommt? If the direct question begins with the verb (answer: yes or no), you use ob: Kommt der Bus? → Weißt du, ob der Bus kommt? In both cases the verb goes at the end.',
          'ob или вопросительное слово? Если в прямом вопросе есть вопросительное слово (wann, wo, was, wie, warum, wer), оно остаётся: Wann kommt der Bus? → Weißt du, wann der Bus kommt? Если прямой вопрос начинается с глагола (ответ: да или нет), используют ob: Kommt der Bus? → Weißt du, ob der Bus kommt? В обоих случаях глагол стоит в конце.',
          'ob чи питальне слово? Якщо в прямому запитанні є питальне слово (wann, wo, was, wie, warum, wer), воно залишається: Wann kommt der Bus? → Weißt du, wann der Bus kommt? Якщо пряме запитання починається з дієслова (відповідь: так або ні), вживають ob: Kommt der Bus? → Weißt du, ob der Bus kommt? В обох випадках дієслово стоїть у кінці.',
          'ob mu, soru kelimesi mi? Doğrudan soruda bir soru kelimesi varsa (wann, wo, was, wie, warum, wer) o kalır: Wann kommt der Bus? → Weißt du, wann der Bus kommt? Doğrudan soru fiille başlıyorsa (cevap: evet ya da hayır) ob kullanılır: Kommt der Bus? → Weißt du, ob der Bus kommt? Her iki durumda da fiil sonda durur.',
        ],
        hint: ['Mit Fragewort → Fragewort bleibt. Ohne Fragewort (Ja/Nein) → ob. Verb immer am Ende.', 'With a question word → it stays. Without a question word (yes/no) → ob. The verb always goes at the end.', 'С вопросительным словом → оно остаётся. Без вопросительного слова (да/нет) → ob. Глагол всегда в конце.', 'З питальним словом → воно залишається. Без питального слова (так/ні) → ob. Дієслово завжди в кінці.', 'Soru kelimesi varsa → kalır. Soru kelimesi yoksa (evet/hayır) → ob. Fiil her zaman sonda.'],
      },
      ex: [
        mc('G1', 'wann', I.choose, 'Wann beginnt der Kurs? → Weißt du, … der Kurs beginnt?', ['wann', 'ob', 'dass'],
          ['When does the course start? → Do you know when the course starts?', 'Когда начинается курс? → Ты не знаешь, когда начинается курс?', 'Коли починається курс? → Ти не знаєш, коли починається курс?', 'Kurs ne zaman başlıyor? → Kursun ne zaman başladığını biliyor musun?']),
        mc('G2', 'ob', I.choose, 'Beginnt der Kurs heute? → Weißt du, … der Kurs heute beginnt?', ['ob', 'wann', 'was'],
          ['Does the course start today? → Do you know whether the course starts today?', 'Курс начинается сегодня? → Ты не знаешь, начинается ли курс сегодня?', 'Курс починається сьогодні? → Ти не знаєш, чи починається курс сьогодні?', 'Kurs bugün mü başlıyor? → Kursun bugün başlayıp başlamadığını biliyor musun?']),
        mc('G1', 'was', I.choose, 'Was kostet die Karte? → Können Sie mir sagen, … die Karte kostet?', ['was', 'ob', 'wer'],
          ['How much is the card? → Can you tell me how much the card costs?', 'Сколько стоит карта? → Вы не подскажете, сколько стоит карта?', 'Скільки коштує картка? → Ви не підкажете, скільки коштує картка?', 'Kart ne kadar? → Kartın ne kadar olduğunu söyleyebilir misiniz?']),
        mc('G2', 'ob', I.choose, 'Kostet die Karte etwas? → Können Sie mir sagen, … die Karte etwas kostet?', ['ob', 'was', 'wie'],
          ['Does the card cost anything? → Can you tell me whether the card costs anything?', 'Карта платная? → Вы не подскажете, платная ли карта?', 'Картка платна? → Ви не підкажете, чи платна картка?', 'Kart ücretli mi? → Kartın ücretli olup olmadığını söyleyebilir misiniz?']),
        mc('G2', 'Ja/Nein-Frage', I.choose, 'Welche Frage kann man mit Ja oder Nein beantworten?', ['Ist das Konto kostenlos?', 'Was kostet das Konto?', 'Wo ist die Bank?'],
          ['Which question can be answered with yes or no?', 'На какой вопрос можно ответить «да» или «нет»?', 'На яке запитання можна відповісти «так» або «ні»?', 'Hangi soruya evet ya da hayır diye cevap verilebilir?']),
        gap('G1', 'warum', I.qword, 'Warum ist der Automat kaputt? – Ich weiß nicht, ', ' der Automat kaputt ist.', 'warum', ['ob', 'wann'],
          ['Why is the machine out of order? – I do not know why the machine is out of order.', 'Почему банкомат не работает? – Я не знаю, почему банкомат не работает.', 'Чому банкомат не працює? – Я не знаю, чому банкомат не працює.', 'Bankamatik neden bozuk? – Bankamatiğin neden bozuk olduğunu bilmiyorum.'], 'warum / ob / wann'),
        gap('G2', 'ob', I.conjunction, 'Ist der Automat kaputt? – Ich weiß nicht, ', ' der Automat kaputt ist.', 'ob', ['warum', 'wo'],
          ['Is the machine out of order? – I do not know whether the machine is out of order.', 'Банкомат не работает? – Я не знаю, работает ли банкомат.', 'Банкомат не працює? – Я не знаю, чи працює банкомат.', 'Bankamatik bozuk mu? – Bankamatiğin bozuk olup olmadığını bilmiyorum.'], 'ob / warum / wo'),
        gap('G1', 'wer', I.qword, 'Wer hilft mir? – Können Sie mir sagen, ', ' mir helfen kann?', 'wer', ['ob', 'was'],
          ['Who will help me? – Can you tell me who can help me?', 'Кто мне поможет? – Вы не подскажете, кто может мне помочь?', 'Хто мені допоможе? – Ви не підкажете, хто може мені допомогти?', 'Bana kim yardım edecek? – Bana kimin yardım edebileceğini söyleyebilir misiniz?'], 'wer / ob / was'),
        gap('G2', 'ob', I.conjunction, 'Hast du Zeit? – Ich möchte wissen, ', ' du Zeit hast.', 'ob', ['wie', 'was'],
          ['Do you have time? – I would like to know whether you have time.', 'У тебя есть время? – Я хочу знать, есть ли у тебя время.', 'У тебе є час? – Я хочу знати, чи є в тебе час.', 'Vaktin var mı? – Vaktin olup olmadığını öğrenmek istiyorum.'], 'ob / wie / was'),
        sb('G1', 'indirekte Frage', I.question, 'Weißt / du, / wann / der Film / beginnt?',
          ['Do you know when the film starts?', 'Ты не знаешь, когда начинается фильм?', 'Ти не знаєш, коли починається фільм?', 'Filmin ne zaman başladığını biliyor musun?']),
      ],
    },
    {
      title: 'Höflich fragen',
      t: ['Asking politely', 'Как вежливо спросить', 'Як ввічливо запитати', 'Kibarca sormak'],
      card: {
        id: 'p6_hoeflich',
        rule: 'Höflich fragen: Mit einer Einleitung klingt eine Frage freundlicher. Können Sie mir sagen, …? Wissen Sie, …? Könnten Sie mal nachsehen, ob …? Darf ich fragen, …? Ich wollte fragen, … Ich würde gern wissen, … Zum Beispiel: Können Sie mir sagen, wie man dieses Formular ausfüllt? Wissen Sie, wann die Bank geöffnet hat? Ich würde gern wissen, ob ich mit Kreditkarte zahlen kann.',
        examples: ['Darf ich fragen, wie lange das dauert?', 'Ich würde gern wissen, was das kostet.', 'Könnten Sie mal nachsehen, ob mein Geld da ist?'],
        highlight: null,
        t: [
          'Asking politely: with an opening phrase a question sounds friendlier. Können Sie mir sagen, …? (Can you tell me …?) Wissen Sie, …? (Do you know …?) Könnten Sie mal nachsehen, ob …? (Could you check whether …?) Darf ich fragen, …? (May I ask …?) Ich wollte fragen, … (I wanted to ask …) Ich würde gern wissen, … (I would like to know …) For example: Können Sie mir sagen, wie man dieses Formular ausfüllt? Wissen Sie, wann die Bank geöffnet hat? Ich würde gern wissen, ob ich mit Kreditkarte zahlen kann.',
          'Как вежливо спросить: с вводной фразой вопрос звучит дружелюбнее. Können Sie mir sagen, …? (Вы не подскажете, …?) Wissen Sie, …? (Вы не знаете, …?) Könnten Sie mal nachsehen, ob …? (Вы не могли бы посмотреть, … ли …?) Darf ich fragen, …? (Можно спросить, …?) Ich wollte fragen, … (Я хотел спросить, …) Ich würde gern wissen, … (Я хотел бы узнать, …) Например: Können Sie mir sagen, wie man dieses Formular ausfüllt? Wissen Sie, wann die Bank geöffnet hat? Ich würde gern wissen, ob ich mit Kreditkarte zahlen kann.',
          'Як ввічливо запитати: зі вступною фразою запитання звучить приязніше. Können Sie mir sagen, …? (Ви не підкажете, …?) Wissen Sie, …? (Ви не знаєте, …?) Könnten Sie mal nachsehen, ob …? (Чи не могли б ви подивитися, чи …?) Darf ich fragen, …? (Можна запитати, …?) Ich wollte fragen, … (Я хотів запитати, …) Ich würde gern wissen, … (Я хотів би дізнатися, …) Наприклад: Können Sie mir sagen, wie man dieses Formular ausfüllt? Wissen Sie, wann die Bank geöffnet hat? Ich würde gern wissen, ob ich mit Kreditkarte zahlen kann.',
          'Kibarca sormak: Bir giriş cümlesiyle soru daha nazik olur. Können Sie mir sagen, …? (… söyleyebilir misiniz?) Wissen Sie, …? (… biliyor musunuz?) Könnten Sie mal nachsehen, ob …? (… olup olmadığına bakabilir misiniz?) Darf ich fragen, …? (… sorabilir miyim?) Ich wollte fragen, … (… sormak istemiştim.) Ich würde gern wissen, … (… öğrenmek isterdim.) Örneğin: Können Sie mir sagen, wie man dieses Formular ausfüllt? Wissen Sie, wann die Bank geöffnet hat? Ich würde gern wissen, ob ich mit Kreditkarte zahlen kann.',
        ],
        hint: ['Höfliche Einleitung + Komma + ob / Fragewort … Verb am Ende.', 'Polite opening + comma + ob / question word … verb at the end.', 'Вежливая вводная фраза + запятая + ob / вопросительное слово … глагол в конце.', 'Ввічлива вступна фраза + кома + ob / питальне слово … дієслово в кінці.', 'Kibar giriş + virgül + ob / soru kelimesi … fiil sonda.'],
      },
      ex: [
        mc('K1', 'Können Sie mir sagen, …?', I.situation, 'Du bist in der Bank und möchtest höflich nach den Öffnungszeiten fragen. Was sagst du?', ['Können Sie mir sagen, wann die Bank geöffnet hat?', 'Wann hat die Bank auf?', 'Sagen Sie die Öffnungszeiten!'],
          ['You are at the bank and want to ask politely about the opening hours. What do you say?', 'Вы в банке и хотите вежливо спросить о часах работы. Что вы скажете?', 'Ви в банку й хочете ввічливо запитати про години роботи. Що ви скажете?', 'Bankadasınız ve çalışma saatlerini kibarca sormak istiyorsunuz. Ne dersiniz?']),
        mc('K1', 'Darf ich fragen, …?', I.choose, 'Welche Frage ist am höflichsten?', ['Darf ich fragen, wie viel das kostet?', 'Wie viel kostet das?', 'Was kostet das? Schnell!'],
          ['Which question is the most polite?', 'Какой вопрос самый вежливый?', 'Яке запитання найввічливіше?', 'Hangi soru en kibar olanıdır?']),
        mc('K1', 'Wissen Sie, wie …?', I.situation, 'Du weißt nicht, wie man das Formular ausfüllt. Wie fragst du höflich?', ['Wissen Sie, wie man das Formular ausfüllt?', 'Füllen Sie das Formular aus!', 'Das Formular ist schlecht.'],
          ['You do not know how to fill in the form. How do you ask politely?', 'Вы не знаете, как заполнить бланк. Как вы вежливо спросите?', 'Ви не знаєте, як заповнити бланк. Як ви ввічливо запитаєте?', 'Formun nasıl doldurulduğunu bilmiyorsunuz. Kibarca nasıl sorarsınız?']),
        mc('K1', 'nachsehen', I.react, '„Könnten Sie mal nachsehen, ob meine Karte fertig ist?“', ['Einen Moment, bitte. Ich sehe sofort nach.', 'Ja, ich würde gern wissen.', 'Nein, ich frage nicht.'],
          ['“Could you check whether my card is ready?”', '«Вы не могли бы посмотреть, готова ли моя карта?»', '«Чи не могли б ви подивитися, чи готова моя картка?»', '“Kartımın hazır olup olmadığına bakabilir misiniz?”']),
        mc('K1', 'Ich würde gern wissen, …', I.choose, 'Ich würde gern …, ob das Konto kostenlos ist.', ['wissen', 'weiß', 'gewusst'],
          ['I would like to know whether the account is free of charge.', 'Я хотел бы узнать, бесплатный ли счёт.', 'Я хотів би дізнатися, чи безкоштовний рахунок.', 'Hesabın ücretsiz olup olmadığını öğrenmek isterdim.']),
        gap('K1', 'Darf ich fragen', I.verb, 'Darf ich ', ', wo die Toilette ist?', 'fragen', ['sagen', 'fragt'],
          ['May I ask where the toilet is?', 'Можно спросить, где туалет?', 'Можна запитати, де туалет?', 'Tuvaletin nerede olduğunu sorabilir miyim?'],
          ['ask', 'спросить', 'запитати', 'sormak']),
        gap('K1', 'mir', I.pronoun, 'Können Sie ', ' sagen, wie ich zum Schalter 5 komme?', 'mir', ['mich', 'ich'],
          ['Can you tell me how to get to counter 5?', 'Вы не подскажете, как пройти к окошку 5?', 'Ви не підкажете, як пройти до віконця 5?', '5 numaralı gişeye nasıl gideceğimi söyleyebilir misiniz?'], 'ich'),
        gap('K1', 'Ich würde gern wissen', I.verb, 'Ich ', ' gern wissen, wann ich die neue Karte bekomme.', 'würde', ['wäre', 'hätte'],
          ['I would like to know when I will get the new card.', 'Я хотел бы узнать, когда получу новую карту.', 'Я хотів би дізнатися, коли отримаю нову картку.', 'Yeni kartı ne zaman alacağımı öğrenmek isterdim.'], KII),
        gap('K1', 'Könnten Sie …?', I.polite, '', ' Sie mal nachsehen, ob das Geld schon da ist?', ['Könnten', 'Können', 'Würden'], ['Könntest', 'Kannst'],
          ['Could you check whether the money is there yet?', 'Вы не могли бы посмотреть, пришли ли уже деньги?', 'Чи не могли б ви подивитися, чи вже надійшли гроші?', 'Paranın gelip gelmediğine bakabilir misiniz?'], 'können (Sie)'),
        sb('K1', 'Ich würde gern wissen, …', I.order, 'Ich / würde / gern / wissen, / was / das / kostet.',
          ['I would like to know how much that costs.', 'Я хотел бы узнать, сколько это стоит.', 'Я хотів би дізнатися, скільки це коштує.', 'Bunun ne kadar olduğunu öğrenmek isterdim.']),
      ],
    },
    {
      title: 'ich lasse, du lässt',
      t: ['ich lasse, du lässt (the verb lassen)', 'ich lasse, du lässt (глагол lassen)', 'ich lasse, du lässt (дієслово lassen)', 'ich lasse, du lässt (lassen fiili)'],
      card: {
  "id": "p6_lassen",
  "rule": "Das Verb lassen: ich lasse, du lässt, er/es/sie lässt, wir lassen, ihr lasst, sie/Sie lassen. Bei du und er/es/sie wird a zu ä. lassen + Infinitiv bedeutet: Man macht etwas nicht selbst, eine andere Person macht es. Ich repariere das Auto nicht selbst. Ich lasse das Auto reparieren. Mein Bruder schneidet seine Haare nicht selbst. Er lässt seine Haare schneiden.",
  "examples": [
    "Ich lasse mein Fahrrad reparieren.",
    "Lässt du deine Haare schneiden?",
    "Wir lassen die Wohnung streichen."
  ],
  "highlight": "verb",
  "t": [
    "The verb lassen: ich lasse, du lässt, er/es/sie lässt, wir lassen, ihr lasst, sie/Sie lassen. With du and er/es/sie the a becomes ä. lassen + infinitive means: you do not do something yourself, another person does it. Ich repariere das Auto nicht selbst. Ich lasse das Auto reparieren. (I am having the car repaired.) Mein Bruder schneidet seine Haare nicht selbst. Er lässt seine Haare schneiden. (He has his hair cut.)",
    "Глагол lassen: ich lasse, du lässt, er/es/sie lässt, wir lassen, ihr lasst, sie/Sie lassen. С du и er/es/sie a меняется на ä. lassen + инфинитив значит: человек делает что-то не сам, это делает другой. Ich repariere das Auto nicht selbst. Ich lasse das Auto reparieren. (Я отдаю машину в ремонт.) Mein Bruder schneidet seine Haare nicht selbst. Er lässt seine Haare schneiden. (Он стрижётся у парикмахера.)",
    "Дієслово lassen: ich lasse, du lässt, er/es/sie lässt, wir lassen, ihr lasst, sie/Sie lassen. З du та er/es/sie a змінюється на ä. lassen + інфінітив означає: людина робить щось не сама, це робить хтось інший. Ich repariere das Auto nicht selbst. Ich lasse das Auto reparieren. (Я віддаю машину в ремонт.) Mein Bruder schneidet seine Haare nicht selbst. Er lässt seine Haare schneiden. (Він стрижеться в перукаря.)",
    "lassen fiili: ich lasse, du lässt, er/es/sie lässt, wir lassen, ihr lasst, sie/Sie lassen. du ve er/es/sie ile a harfi ä olur. lassen + mastar şu anlama gelir: İnsan bir işi kendisi yapmaz, başka biri yapar. Ich repariere das Auto nicht selbst. Ich lasse das Auto reparieren. (Arabayı tamir ettiriyorum.) Mein Bruder schneidet seine Haare nicht selbst. Er lässt seine Haare schneiden. (Saçını kestiriyor.)"
  ],
  "hint": [
    "lassen: ich lasse, du lässt, er lässt, wir lassen, ihr lasst, sie lassen. du und er: a → ä.",
    "lassen: ich lasse, du lässt, er lässt, wir lassen, ihr lasst, sie lassen. du and er: a → ä.",
    "lassen: ich lasse, du lässt, er lässt, wir lassen, ihr lasst, sie lassen. du и er: a → ä.",
    "lassen: ich lasse, du lässt, er lässt, wir lassen, ihr lasst, sie lassen. du та er: a → ä.",
    "lassen: ich lasse, du lässt, er lässt, wir lassen, ihr lasst, sie lassen. du ve er: a → ä."
  ]
},
      ex: [
        mc("G3", "er lässt", I.choose, "Milan ___ sein Auto in der Werkstatt reparieren.", ["lässt","lasst","lasse"], ["Milan is having his car repaired at the garage.","Milan ремонтирует машину в автосервисе.","Milan ремонтує машину в автосервісі.","Milan arabasını serviste tamir ettiriyor."], {"c":"p6_lassen"}),
        mc("G3", "wir lassen", I.choose, "Wir ___ die Fenster putzen.", ["lassen","lässt","lasst"], ["We are having the windows cleaned.","Нам моют окна (мы это заказали).","Нам миють вікна (ми це замовили).","Camları sildiriyoruz."], {"c":"p6_lassen"}),
        mc("G3", "du lässt", I.choose, "___ du deine Haare beim Friseur schneiden?", ["Lässt","Lasst","Lasse"], ["Do you have your hair cut at the hairdresser’s?","Ты стрижёшься у парикмахера?","Ти стрижешся в перукаря?","Saçını kuaförde mi kestiriyorsun?"], {"c":"p6_lassen"}),
        mc('G3', 'lassen = nicht selbst machen', I.choose, 'Was bedeutet „Ich lasse mein Fahrrad reparieren“?', ['Eine andere Person repariert mein Fahrrad.', 'Ich repariere mein Fahrrad selbst.', 'Mein Fahrrad ist nicht kaputt.'],
          ['What does “Ich lasse mein Fahrrad reparieren” mean?', 'Что значит «Ich lasse mein Fahrrad reparieren»?', 'Що означає «Ich lasse mein Fahrrad reparieren»?', '“Ich lasse mein Fahrrad reparieren” ne demek?']),
        mc("G3", "ihr lasst", I.choose, "___ ihr eure Pässe verlängern?", ["Lasst","Lassen","Lässt"], ["Are you (plural) having your passports renewed?","Вы продлеваете свои паспорта?","Ви продовжуєте свої паспорти?","Pasaportlarınızı uzattırıyor musunuz?"], {"c":"p6_lassen"}),
        gap('G3', 'ich lasse', I.verb, 'Ich ', ' meine Bluse reinigen.', 'lasse', ['lässt', 'lasst'],
          ['I am having my blouse cleaned.', 'Я отдаю блузку в чистку.', 'Я віддаю блузку в чистку.', 'Bluzumu temizletiyorum.'], 'lassen'),
        gap('G3', 'er lässt', I.verb, 'Herr Kaya ', ' sein Konto prüfen.', 'lässt', ['lasst', 'lassen'],
          ['Mr Kaya is having his account checked.', 'Господин Kaya просит проверить его счёт.', 'Пан Kaya просить перевірити його рахунок.', 'Kaya Bey hesabını kontrol ettiriyor.'], 'lassen'),
        gap('G3', 'sie lassen', I.verb, 'Meine Eltern ', ' das Dach reparieren.', 'lassen', ['lässt', 'lasst'],
          ['My parents are having the roof repaired.', 'Мои родители ремонтируют крышу (её чинят мастера).', 'Мої батьки ремонтують дах (його лагодять майстри).', 'Annemle babam çatıyı tamir ettiriyor.'], 'lassen (Plural)'),
        gap('G3', 'ihr lasst', I.verb, 'Ihr ', ' euch die Pizza nach Hause bringen, oder?', 'lasst', ['lässt', 'lassen'],
          ['You (plural) are having the pizza delivered, aren’t you?', 'Вы заказываете пиццу на дом, да?', 'Ви замовляєте піцу додому, так?', 'Pizzayı eve getirtiyorsunuz, değil mi?'], 'lassen'),
        sb('G3', 'ich lasse', I.order, 'Ich / lasse / mein Fahrrad / reparieren.',
          ['I am having my bike repaired.', 'Я отдаю велосипед в ремонт.', 'Я віддаю велосипед у ремонт.', 'Bisikletimi tamir ettiriyorum.'],
          { alt: ['Mein Fahrrad lasse ich reparieren.'] }),
      ],
    },
    {
      title: 'Sie lässt ihr Konto prüfen.',
      t: ['She is having her account checked.', 'Она просит проверить свой счёт.', 'Вона просить перевірити свій рахунок.', 'Hesabını kontrol ettiriyor.'],
      card: {
        id: 'p6_lassen_satz',
        rule: 'lassen im Satz: lassen steht auf Position 2, der Infinitiv am Satzende: Sie lässt ihr Konto prüfen. Mit Modalverb steht lassen als Infinitiv ganz am Ende, hinter dem anderen Verb: Sie sollten vor dem Winter die Reifen wechseln lassen. Ich muss meinen Pass verlängern lassen. Ich würde gern mein Auto waschen lassen.',
        examples: ['Er lässt die Waschmaschine reparieren.', 'Sie sollten Ihre Karte sofort sperren lassen.', 'Ich möchte mir die Haare schneiden lassen.'],
        highlight: 'verb',
        t: [
          'lassen in a sentence: lassen is in position 2, the infinitive at the end of the sentence: Sie lässt ihr Konto prüfen. With a modal verb lassen goes right at the end as an infinitive, after the other verb: Sie sollten vor dem Winter die Reifen wechseln lassen. (You should have the tyres changed before the winter.) Ich muss meinen Pass verlängern lassen. Ich würde gern mein Auto waschen lassen.',
          'lassen в предложении: lassen стоит на втором месте, инфинитив – в конце предложения: Sie lässt ihr Konto prüfen. С модальным глаголом lassen стоит в самом конце в инфинитиве, после другого глагола: Sie sollten vor dem Winter die Reifen wechseln lassen. (Перед зимой вам следует поменять шины в мастерской.) Ich muss meinen Pass verlängern lassen. Ich würde gern mein Auto waschen lassen.',
          'lassen у реченні: lassen стоїть на другому місці, інфінітив – у кінці речення: Sie lässt ihr Konto prüfen. З модальним дієсловом lassen стоїть у самому кінці в інфінітиві, після іншого дієслова: Sie sollten vor dem Winter die Reifen wechseln lassen. (Перед зимою вам слід поміняти шини в майстерні.) Ich muss meinen Pass verlängern lassen. Ich würde gern mein Auto waschen lassen.',
          'Cümlede lassen: lassen ikinci sırada, mastar cümlenin sonunda durur: Sie lässt ihr Konto prüfen. Kip fiiliyle birlikte lassen mastar olarak en sonda, öbür fiilin arkasında durur: Sie sollten vor dem Winter die Reifen wechseln lassen. (Kıştan önce lastikleri değiştirtmelisiniz.) Ich muss meinen Pass verlängern lassen. Ich würde gern mein Auto waschen lassen.',
        ],
        hint: ['lassen (Position 2) … Infinitiv (Ende). Mit Modalverb: … Infinitiv + lassen am Ende.', 'lassen (position 2) … infinitive (end). With a modal verb: … infinitive + lassen at the end.', 'lassen (второе место) … инфинитив (в конце). С модальным глаголом: … инфинитив + lassen в конце.', 'lassen (друге місце) … інфінітив (у кінці). З модальним дієсловом: … інфінітив + lassen у кінці.', 'lassen (ikinci sıra) … mastar (sonda). Kip fiiliyle: … mastar + lassen sonda.'],
      },
      ex: [
        mc('G4', 'Infinitiv am Ende', I.sentence, 'Die Heizung ist kaputt.', ['Wir lassen die Heizung reparieren.', 'Wir lassen reparieren die Heizung.', 'Wir reparieren lassen die Heizung.'],
          ['The heating is broken.', 'Отопление сломалось.', 'Опалення зламалося.', 'Kalorifer bozuk.']),
        mc('G4', 'Modalverb + lassen', I.sentence, 'Ein Tipp vor dem Winter:', ['Sie sollten die Reifen wechseln lassen.', 'Sie sollten die Reifen lassen wechseln.', 'Sie sollten lassen die Reifen wechseln.'],
          ['A tip before the winter:', 'Совет перед зимой:', 'Порада перед зимою:', 'Kıştan önce bir tavsiye:']),
        mc('G4', 'lassen am Ende', I.choose, 'Ich muss meinen Pass verlängern …', ['lassen', 'lässt', 'gelassen'],
          ['I have to have my passport renewed.', 'Мне нужно продлить паспорт.', 'Мені треба продовжити паспорт.', 'Pasaportumu uzattırmam gerekiyor.']),
        mc('G4', 'Modalverb + lassen', I.sentence, 'Paul hat lange Haare. Morgen geht er zum Friseur.', ['Er möchte sich die Haare schneiden lassen.', 'Er möchte sich die Haare lassen schneiden.', 'Er möchte lassen sich die Haare schneiden.'],
          ['Paul has long hair. Tomorrow he is going to the hairdresser’s.', 'У Paul длинные волосы. Завтра он идёт к парикмахеру.', 'У Paul довге волосся. Завтра він іде до перукаря.', 'Paul’un saçları uzun. Yarın kuaföre gidiyor.']),
        gap('G4', 'sperren lassen', I.verb, 'Meine Karte ist weg! Ich muss sie sofort sperren ', '.', 'lassen', ['lässt', 'gelassen'],
          ['My card has gone! I have to have it blocked straight away.', 'Моя карта пропала! Её нужно срочно заблокировать.', 'Моя картка зникла! Її треба негайно заблокувати.', 'Kartım kayboldu! Hemen bloke ettirmem gerekiyor.'], LASSEN_DONE),
        gap('G4', 'Infinitiv am Ende', I.verb, 'Wir lassen unsere Wohnung von einem Maler ', '.', 'streichen', ['streicht', 'gestrichen'],
          ['We are having our flat painted by a decorator.', 'Нашу квартиру красит маляр.', 'Нашу квартиру фарбує маляр.', 'Dairemizi bir boyacıya boyatıyoruz.'],
          ['paint', 'покрасить', 'пофарбувати', 'boyamak']),
        gap('G4', 'lässt', I.verb, 'Olga ', ' ihren Computer von einem Fachmann reparieren.', 'lässt', ['lasst', 'lassen'],
          ['Olga is having her computer repaired by a specialist.', 'Olga отдаёт компьютер в ремонт специалисту.', 'Olga віддає комп’ютер у ремонт фахівцеві.', 'Olga bilgisayarını bir uzmana tamir ettiriyor.'], 'lassen'),
        gap('G4', 'waschen lassen', I.verb, 'Ich würde gern mein Auto waschen ', '.', 'lassen', ['lasse', 'lässt'],
          ['I would like to have my car washed.', 'Я хотел бы помыть машину на автомойке.', 'Я хотів би помити машину на автомийці.', 'Arabamı yıkatmak isterdim.'], LASSEN_DONE),
        sb('G4', 'lassen + Infinitiv', I.order, 'Sie / lässt / ihr Konto / prüfen.',
          ['She is having her account checked.', 'Она просит проверить свой счёт.', 'Вона просить перевірити свій рахунок.', 'Hesabını kontrol ettiriyor.'],
          { alt: ['Ihr Konto lässt sie prüfen.'] }),
        sb('G4', 'Modalverb + lassen', I.order, 'Ich / muss / meinen Pass / verlängern / lassen.',
          ['I have to have my passport renewed.', 'Мне нужно продлить паспорт.', 'Мені треба продовжити паспорт.', 'Pasaportumu uzattırmam gerekiyor.'],
          { alt: ['Meinen Pass muss ich verlängern lassen.'] }),
      ],
    },
    {
      title: 'In der Bank',
      t: ['At the bank', 'В банке', 'У банку', 'Bankada'],
      card: {
        id: 'p6_bankgespraech',
        rule: 'Gespräche in der Bank: Ich möchte gern ein Konto eröffnen. – Gern. Haben Sie Ihren Ausweis dabei? Was für ein Konto möchten Sie? Ich möchte 200 Euro abheben. Ich möchte Geld überweisen. Ich habe meine Geheimzahl vergessen. Was soll ich denn jetzt machen? – Wir schicken Ihnen eine neue Geheimzahl. Meine Karte ist weg. – Dann lassen wir die Karte sofort sperren. Der Automat hat meine Karte eingezogen (nicht zurückgegeben).',
        examples: ['Ich möchte gern ein Konto eröffnen.', 'Ich habe meine Geheimzahl vergessen.', 'Könnten Sie meine Karte bitte sperren?'],
        highlight: null,
        t: [
          'Conversations at the bank: Ich möchte gern ein Konto eröffnen. (I would like to open an account.) – Gern. Haben Sie Ihren Ausweis dabei? Was für ein Konto möchten Sie? Ich möchte 200 Euro abheben. Ich möchte Geld überweisen. Ich habe meine Geheimzahl vergessen. Was soll ich denn jetzt machen? (What should I do now?) – Wir schicken Ihnen eine neue Geheimzahl. Meine Karte ist weg. – Dann lassen wir die Karte sofort sperren. (Then we will have the card blocked straight away.) Der Automat hat meine Karte eingezogen. (The machine has kept my card.)',
          'Разговоры в банке: Ich möchte gern ein Konto eröffnen. (Я хотел бы открыть счёт.) – Gern. Haben Sie Ihren Ausweis dabei? Was für ein Konto möchten Sie? Ich möchte 200 Euro abheben. Ich möchte Geld überweisen. Ich habe meine Geheimzahl vergessen. Was soll ich denn jetzt machen? (Что же мне теперь делать?) – Wir schicken Ihnen eine neue Geheimzahl. Meine Karte ist weg. – Dann lassen wir die Karte sofort sperren. (Тогда мы сразу заблокируем карту.) Der Automat hat meine Karte eingezogen. (Банкомат не вернул мою карту.)',
          'Розмови в банку: Ich möchte gern ein Konto eröffnen. (Я хотів би відкрити рахунок.) – Gern. Haben Sie Ihren Ausweis dabei? Was für ein Konto möchten Sie? Ich möchte 200 Euro abheben. Ich möchte Geld überweisen. Ich habe meine Geheimzahl vergessen. Was soll ich denn jetzt machen? (Що ж мені тепер робити?) – Wir schicken Ihnen eine neue Geheimzahl. Meine Karte ist weg. – Dann lassen wir die Karte sofort sperren. (Тоді ми одразу заблокуємо картку.) Der Automat hat meine Karte eingezogen. (Банкомат не повернув мою картку.)',
          'Bankada konuşmalar: Ich möchte gern ein Konto eröffnen. (Bir hesap açmak istiyorum.) – Gern. Haben Sie Ihren Ausweis dabei? Was für ein Konto möchten Sie? Ich möchte 200 Euro abheben. Ich möchte Geld überweisen. Ich habe meine Geheimzahl vergessen. Was soll ich denn jetzt machen? (Şimdi ne yapmalıyım?) – Wir schicken Ihnen eine neue Geheimzahl. Meine Karte ist weg. – Dann lassen wir die Karte sofort sperren. (O zaman kartı hemen bloke ettirelim.) Der Automat hat meine Karte eingezogen. (Bankamatik kartımı yuttu.)',
        ],
        hint: ['Konto eröffnen: Ausweis mitbringen. Karte weg: sofort sperren lassen. Geheimzahl vergessen: neue bekommen.', 'Opening an account: bring your ID. Card gone: have it blocked at once. PIN forgotten: get a new one.', 'Открыть счёт: взять удостоверение. Карта пропала: сразу заблокировать. Забыли ПИН-код: получить новый.', 'Відкрити рахунок: взяти посвідчення. Картка зникла: одразу заблокувати. Забули ПІН-код: отримати новий.', 'Hesap açmak: kimlik getirin. Kart kayıp: hemen bloke ettirin. Şifre unutuldu: yenisini alın.'],
      },
      ex: [
        mc('K5', 'Konto eröffnen', I.situation, 'Du bist neu in der Stadt und brauchst ein Bankkonto. Was sagst du in der Bank?', ['Ich möchte gern ein Konto eröffnen.', 'Ich möchte meine Karte sperren.', 'Ich habe meine Geheimzahl vergessen.'],
          ['You are new in town and need a bank account. What do you say at the bank?', 'Вы недавно в городе, и вам нужен банковский счёт. Что вы скажете в банке?', 'Ви нещодавно в місті, і вам потрібен банківський рахунок. Що ви скажете в банку?', 'Şehirde yenisiniz ve bir banka hesabına ihtiyacınız var. Bankada ne dersiniz?']),
        mc('K5', 'Ausweis', I.react, '„Ich möchte ein Konto eröffnen.“ – Du arbeitest in der Bank.', ['Gern. Haben Sie Ihren Ausweis dabei?', 'Der Automat ist kaputt.', 'Das macht drei Euro Gebühr.'],
          ['“I would like to open an account.” – You work at the bank.', '«Я хочу открыть счёт.» – Вы работаете в банке.', '«Я хочу відкрити рахунок.» – Ви працюєте в банку.', '“Bir hesap açmak istiyorum.” – Bankada çalışıyorsunuz.']),
        mc('K5', 'Karte sperren', I.situation, 'Du hast deine Bankkarte verloren. Was sagst du am Telefon?', ['Meine Karte ist weg. Könnten Sie sie bitte sofort sperren?', 'Ich möchte Geld einzahlen.', 'Wo ist der nächste Geldautomat?'],
          ['You have lost your bank card. What do you say on the phone?', 'Вы потеряли банковскую карту. Что вы скажете по телефону?', 'Ви загубили банківську картку. Що ви скажете телефоном?', 'Banka kartınızı kaybettiniz. Telefonda ne dersiniz?']),
        mc('K5', 'Geheimzahl vergessen', I.react, '„Ich habe meine Geheimzahl vergessen. Was soll ich denn jetzt machen?“', ['Kein Problem. Wir schicken Ihnen eine neue Geheimzahl.', 'Dann müssen Sie ein Konto eröffnen.', 'Dann zahlen Sie bitte bar.'],
          ['“I have forgotten my PIN. What should I do now?”', '«Я забыл свой ПИН-код. Что же мне теперь делать?»', '«Я забув свій ПІН-код. Що ж мені тепер робити?»', '“Şifremi unuttum. Şimdi ne yapmalıyım?”']),
        mc('K5', 'eingezogen', I.choose, 'Was bedeutet „Der Automat hat meine Karte eingezogen“?', ['Der Automat gibt die Karte nicht zurück.', 'Der Automat gibt kein Geld.', 'Der Automat ist sehr langsam.'],
          ['What does “Der Automat hat meine Karte eingezogen” mean?', 'Что значит «Der Automat hat meine Karte eingezogen»?', 'Що означає «Der Automat hat meine Karte eingezogen»?', '“Der Automat hat meine Karte eingezogen” ne demek?']),
        gap('K5', 'Geheimzahl', I.word, 'Ich habe meine ', ' vergessen und kann kein Geld abheben.', 'Geheimzahl', ['Gebühr', 'Spende'],
          ['I have forgotten my PIN and cannot withdraw any money.', 'Я забыл ПИН-код и не могу снять деньги.', 'Я забув ПІН-код і не можу зняти гроші.', 'Şifremi unuttum ve para çekemiyorum.'],
          ['PIN', 'ПИН-код', 'ПІН-код', 'şifre (PIN)']),
        gap('K5', 'überweisen', I.verb, 'Ich möchte 300 Euro auf das Konto von meinem Vermieter ', '.', 'überweisen', ['abheben', 'eröffnen'],
          ['I would like to transfer 300 euros to my landlord’s account.', 'Я хочу перевести 300 евро на счёт арендодателя.', 'Я хочу переказати 300 євро на рахунок орендодавця.', 'Ev sahibimin hesabına 300 avro havale etmek istiyorum.'],
          ['transfer', 'перевести', 'переказати', 'havale etmek']),
        gap('K5', 'Ausweis', I.word, 'Für ein neues Konto brauchen wir Ihren ', ' und Ihre Adresse.', 'Ausweis', ['Automaten', 'Auszug'],
          ['For a new account we need your ID and your address.', 'Для нового счёта нам нужны ваше удостоверение и адрес.', 'Для нового рахунку нам потрібні ваше посвідчення й адреса.', 'Yeni bir hesap için kimliğinize ve adresinize ihtiyacımız var.'],
          ['ID card', 'удостоверение личности', 'посвідчення особи', 'kimlik']),
        gap('K5', 'sperren', I.verb, 'Meine Karte ist weg. Bitte ', ' Sie die Karte sofort!', 'sperren', ['sparen', 'spenden'],
          ['My card has gone. Please block the card straight away!', 'Моя карта пропала. Пожалуйста, сразу заблокируйте её!', 'Моя картка зникла. Будь ласка, одразу заблокуйте її!', 'Kartım kayboldu. Lütfen kartı hemen bloke edin!'],
          ['block', 'заблокировать', 'заблокувати', 'bloke etmek']),
        sb('K5', 'Konto eröffnen', I.order, 'Ich / möchte / gern / ein Konto / eröffnen.',
          ['I would like to open an account.', 'Я хотел бы открыть счёт.', 'Я хотів би відкрити рахунок.', 'Bir hesap açmak istiyorum.'],
          { alt: ['Gern möchte ich ein Konto eröffnen.', 'Ein Konto möchte ich gern eröffnen.'] }),
      ],
    },
    {
      title: 'Keine Ahnung! Pass auf!',
      t: ['No idea! Watch out!', 'Понятия не имею! Осторожно!', 'Гадки не маю! Обережно!', 'Hiçbir fikrim yok! Dikkat et!'],
      card: {
        id: 'p6_hilfe',
        rule: 'Um Hilfe bitten: Können Sie mir helfen? Würden Sie mir das bitte erklären? Was soll ich denn jetzt machen? Können Sie mir zeigen, wie das geht? Unkenntnis äußern: Keine Ahnung! Ich kenne mich damit überhaupt nicht aus. Ich weiß nicht, was ich jetzt tun soll. Jemanden warnen: Pass auf! Vorsicht! Dann musst du besser aufpassen. Passen Sie auf Ihre Tasche auf!',
        examples: ['Würden Sie mir das bitte erklären?', 'Keine Ahnung! Ich kenne mich damit nicht aus.', 'Pass auf! Da kommt ein Auto.'],
        highlight: null,
        t: [
          'Asking for help: Können Sie mir helfen? Würden Sie mir das bitte erklären? (Would you explain that to me, please?) Was soll ich denn jetzt machen? Können Sie mir zeigen, wie das geht? (Can you show me how that works?) Saying you do not know: Keine Ahnung! (No idea!) Ich kenne mich damit überhaupt nicht aus. (I do not know anything about that at all.) Ich weiß nicht, was ich jetzt tun soll. Warning someone: Pass auf! (Watch out!) Vorsicht! (Careful!) Dann musst du besser aufpassen. (Then you must take more care.) Passen Sie auf Ihre Tasche auf! (Keep an eye on your bag!)',
          'Как попросить о помощи: Können Sie mir helfen? Würden Sie mir das bitte erklären? (Вы не могли бы мне это объяснить?) Was soll ich denn jetzt machen? Können Sie mir zeigen, wie das geht? (Вы можете показать, как это делается?) Как сказать, что вы не знаете: Keine Ahnung! (Понятия не имею!) Ich kenne mich damit überhaupt nicht aus. (Я в этом совсем не разбираюсь.) Ich weiß nicht, was ich jetzt tun soll. Как предупредить: Pass auf! (Осторожно!) Vorsicht! (Внимание!) Dann musst du besser aufpassen. (Тогда тебе нужно быть внимательнее.) Passen Sie auf Ihre Tasche auf! (Следите за своей сумкой!)',
          'Як попросити про допомогу: Können Sie mir helfen? Würden Sie mir das bitte erklären? (Чи не могли б ви мені це пояснити?) Was soll ich denn jetzt machen? Können Sie mir zeigen, wie das geht? (Чи можете ви показати, як це робиться?) Як сказати, що ви не знаєте: Keine Ahnung! (Гадки не маю!) Ich kenne mich damit überhaupt nicht aus. (Я на цьому зовсім не знаюся.) Ich weiß nicht, was ich jetzt tun soll. Як попередити: Pass auf! (Обережно!) Vorsicht! (Увага!) Dann musst du besser aufpassen. (Тоді тобі треба бути уважнішим.) Passen Sie auf Ihre Tasche auf! (Пильнуйте свою сумку!)',
          'Yardım istemek: Können Sie mir helfen? Würden Sie mir das bitte erklären? (Bunu bana açıklar mısınız lütfen?) Was soll ich denn jetzt machen? Können Sie mir zeigen, wie das geht? (Bunun nasıl yapıldığını gösterebilir misiniz?) Bilmediğini söylemek: Keine Ahnung! (Hiçbir fikrim yok!) Ich kenne mich damit überhaupt nicht aus. (Bundan hiç anlamam.) Ich weiß nicht, was ich jetzt tun soll. Birini uyarmak: Pass auf! (Dikkat et!) Vorsicht! (Dikkat!) Dann musst du besser aufpassen. (O zaman daha dikkatli olmalısın.) Passen Sie auf Ihre Tasche auf! (Çantanıza dikkat edin!)',
        ],
        hint: ['Hilfe: Können Sie mir helfen? Nichts wissen: Keine Ahnung! Warnen: Pass auf! Vorsicht!', 'Help: Können Sie mir helfen? Not knowing: Keine Ahnung! Warning: Pass auf! Vorsicht!', 'Помощь: Können Sie mir helfen? Не знаю: Keine Ahnung! Предупреждение: Pass auf! Vorsicht!', 'Допомога: Können Sie mir helfen? Не знаю: Keine Ahnung! Попередження: Pass auf! Vorsicht!', 'Yardım: Können Sie mir helfen? Bilmemek: Keine Ahnung! Uyarı: Pass auf! Vorsicht!'],
      },
      ex: [
        mc('K2', 'um Hilfe bitten', I.situation, 'Du verstehst den Automaten nicht. Eine Bankangestellte steht neben dir. Was sagst du?', ['Würden Sie mir das bitte erklären?', 'Pass auf!', 'Keine Ahnung!'],
          ['You do not understand the machine. A bank clerk is standing next to you. What do you say?', 'Вы не понимаете, как пользоваться банкоматом. Рядом стоит сотрудница банка. Что вы скажете?', 'Ви не розумієте, як користуватися банкоматом. Поруч стоїть працівниця банку. Що ви скажете?', 'Bankamatiği anlamıyorsunuz. Yanınızda bir banka görevlisi duruyor. Ne dersiniz?']),
        mc('K2', 'auf eine Bitte reagieren', I.react, '„Können Sie mir helfen? Ich finde den Schalter nicht.“', ['Natürlich. Kommen Sie, ich zeige es Ihnen.', 'Keine Ahnung, was Sie wollen.', 'Passen Sie besser auf!'],
          ['“Can you help me? I cannot find the counter.”', '«Вы не могли бы мне помочь? Я не могу найти нужное окошко.»', '«Чи не могли б ви мені допомогти? Я не можу знайти потрібне віконце.»', '“Bana yardım edebilir misiniz? Gişeyi bulamıyorum.”']),
        mc('K3', 'sich nicht auskennen', I.choose, 'Was bedeutet „Ich kenne mich damit nicht aus“?', ['Ich weiß nicht, wie das funktioniert.', 'Ich kenne diese Person nicht.', 'Ich finde das nicht gut.'],
          ['What does “Ich kenne mich damit nicht aus” mean?', 'Что значит «Ich kenne mich damit nicht aus»?', 'Що означає «Ich kenne mich damit nicht aus»?', '“Ich kenne mich damit nicht aus” ne demek?']),
        mc('K3', 'Keine Ahnung!', I.react, '„Weißt du, wie man ein Konto online eröffnet?“ – Du weißt es nicht.', ['Keine Ahnung! Damit kenne ich mich nicht aus.', 'Ja, pass auf!', 'Ja, das mache ich jeden Tag.'],
          ['“Do you know how to open an account online?” – You do not know.', '«Ты знаешь, как открыть счёт онлайн?» – Вы не знаете.', '«Ти знаєш, як відкрити рахунок онлайн?» – Ви не знаєте.', '“İnternetten nasıl hesap açıldığını biliyor musun?” – Bilmiyorsunuz.']),
        mc('K4', 'Pass auf!', I.situation, 'Dein Freund lässt seine Geldbörse offen auf dem Tisch im Café liegen. Was sagst du?', ['Pass auf! Deine Geldbörse liegt offen da.', 'Keine Ahnung!', 'Würden Sie mir das erklären?'],
          ['Your friend leaves his purse lying open on the table in the café. What do you say?', 'Ваш друг оставляет кошелёк открытым на столе в кафе. Что вы скажете?', 'Ваш друг залишає гаманець відкритим на столі в кафе. Що ви скажете?', 'Arkadaşınız cüzdanını kafede masanın üstünde açık bırakıyor. Ne dersiniz?']),
        mc('K4', 'besser aufpassen', I.react, '„Jemand hat mein Handy aus der Tasche gestohlen!“', ['Oh nein! Dann musst du besser aufpassen.', 'Gute Idee!', 'Herzlichen Glückwunsch!'],
          ['“Someone has stolen my mobile from my bag!”', '«У меня из сумки украли телефон!»', '«У мене із сумки вкрали телефон!»', '“Biri çantamdan cep telefonumu çalmış!”']),
        gap('K2', 'mir zeigen', I.pronoun, 'Können Sie ', ' zeigen, wie man hier Geld überweist?', 'mir', ['mich', 'ich'],
          ['Can you show me how to transfer money here?', 'Вы можете показать мне, как здесь перевести деньги?', 'Чи можете ви показати мені, як тут переказати гроші?', 'Burada nasıl havale yapıldığını bana gösterebilir misiniz?'], 'ich'),
        gap('K2', 'Was soll ich machen?', I.modal, 'Der Automat gibt meine Karte nicht zurück. Was ', ' ich denn jetzt machen?', 'soll', ['sollst', 'sollen'],
          ['The machine is not giving my card back. What should I do now?', 'Банкомат не возвращает мою карту. Что же мне теперь делать?', 'Банкомат не повертає мою картку. Що ж мені тепер робити?', 'Bankamatik kartımı geri vermiyor. Şimdi ne yapmalıyım?'], 'sollen'),
        gap('K3', 'Keine Ahnung', I.word, 'Wie funktioniert das? – Keine ', '! Frag lieber Paul.', 'Ahnung', ['Angst', 'Lust'],
          ['How does that work? – No idea! You had better ask Paul.', 'Как это работает? – Понятия не имею! Лучше спроси Paul.', 'Як це працює? – Гадки не маю! Краще запитай Paul.', 'Bu nasıl çalışıyor? – Hiçbir fikrim yok! En iyisi Paul’a sor.'],
          ['idea (no idea)', 'понятие (понятия не имею)', 'гадка (гадки не маю)', 'fikir (hiçbir fikrim yok)']),
        gap('K4', 'Passen Sie auf!', I.imperative, 'Vorsicht! ', ' Sie auf Ihre Tasche auf! Hier gibt es Diebe.', 'Passen', ['Passt', 'Pass'],
          ['Careful! Keep an eye on your bag! There are thieves here.', 'Осторожно! Следите за своей сумкой! Здесь есть воры.', 'Обережно! Пильнуйте свою сумку! Тут є злодії.', 'Dikkat! Çantanıza dikkat edin! Burada hırsızlar var.'], 'aufpassen (Sie)'),
      ],
    },
    {
      title: 'Ratgeber: Geld',
      t: ['Advice column: money', 'Советы: деньги', 'Поради: гроші', 'Tavsiyeler: para'],
      card: {
        id: 'p6_ratgeber',
        rule: 'Ratgeber und kurze Texte rund ums Geld verstehen: Ein Ratgeber gibt Tipps. Typisch sind sollten und lassen: Sie sollten die Karte sperren lassen. Sie sollten vor dem Winter die Reifen wechseln lassen. Achte auf: Was ist das Problem? Was soll man tun? Wo oder bei wem? Was kostet es? Wichtige Wörter: kostenlos, die Spende, spenden (Geld für einen guten Zweck geben), bar, überweisen.',
        examples: ['Sie sollten Ihre Karte sofort sperren lassen.', 'Der Anruf ist kostenlos.', 'Eine kleine Spende für die Kinderhilfe!'],
        highlight: null,
        t: [
          'Understanding advice columns and short texts about money: an advice column gives tips. sollten and lassen are typical: Sie sollten die Karte sperren lassen. (You should have the card blocked.) Sie sollten vor dem Winter die Reifen wechseln lassen. Look for: what is the problem? What should you do? Where or with whom? How much does it cost? Important words: kostenlos (free of charge), die Spende (donation), spenden (donate: give money for a good cause), bar (in cash), überweisen (transfer).',
          'Как понимать советы и короткие тексты о деньгах: в таких текстах дают советы. Типичны sollten и lassen: Sie sollten die Karte sperren lassen. (Вам следует заблокировать карту.) Sie sollten vor dem Winter die Reifen wechseln lassen. Обращайте внимание: в чём проблема? что нужно сделать? где или у кого? сколько это стоит? Важные слова: kostenlos (бесплатно), die Spende (пожертвование), spenden (жертвовать: давать деньги на доброе дело), bar (наличными), überweisen (переводить).',
          'Як розуміти поради й короткі тексти про гроші: у таких текстах дають поради. Типові sollten і lassen: Sie sollten die Karte sperren lassen. (Вам слід заблокувати картку.) Sie sollten vor dem Winter die Reifen wechseln lassen. Звертайте увагу: у чому проблема? що треба зробити? де або в кого? скільки це коштує? Важливі слова: kostenlos (безкоштовно), die Spende (пожертва), spenden (жертвувати: давати гроші на добру справу), bar (готівкою), überweisen (переказувати).',
          'Tavsiye yazılarını ve parayla ilgili kısa metinleri anlamak: Tavsiye yazısı ipuçları verir. sollten ve lassen çok kullanılır: Sie sollten die Karte sperren lassen. (Kartı bloke ettirmelisiniz.) Sie sollten vor dem Winter die Reifen wechseln lassen. Şunlara dikkat edin: Sorun ne? Ne yapmak gerekiyor? Nerede ya da kimde? Ne kadar? Önemli kelimeler: kostenlos (ücretsiz), die Spende (bağış), spenden (bağış yapmak: iyi bir amaç için para vermek), bar (nakit), überweisen (havale etmek).',
        ],
        hint: ['Ratgeber = Tipps: Sie sollten … Such: Was ist das Problem? Was soll man tun?', 'Ratgeber = tips: Sie sollten … Look for: what is the problem? What should you do?', 'Ratgeber = советы: Sie sollten … Найдите: в чём проблема? что нужно сделать?', 'Ratgeber = поради: Sie sollten … Знайдіть: у чому проблема? що треба зробити?', 'Ratgeber = tavsiyeler: Sie sollten … Arayın: Sorun ne? Ne yapmak gerekiyor?'],
      },
      ex: [
        mc('Z1', 'Was zuerst?', I.read, `${RATGEBER} Was soll man zuerst tun, wenn die Karte weg ist?`, ['Man soll die Karte sperren lassen.', 'Man soll zur Polizei gehen.', 'Man soll eine Woche warten.'],
          ['What should you do first if your card has gone?', 'Что нужно сделать в первую очередь, если карта пропала?', 'Що треба зробити насамперед, якщо картка зникла?', 'Kart kaybolursa ilk olarak ne yapmak gerekir?']),
        mc('Z1', 'kostenlos', I.read, `${RATGEBER} Was kostet der Anruf?`, ['Nichts.', '116 Euro.', 'Das steht nicht im Text.'],
          ['How much does the call cost?', 'Сколько стоит звонок?', 'Скільки коштує дзвінок?', 'Arama ne kadar?']),
        mc('Z1', 'Tag und Nacht', I.read, `${RATGEBER} Wann kann man anrufen?`, ['Immer, auch in der Nacht.', 'Nur am Tag.', 'Nur in der ersten Woche.'],
          ['When can you call?', 'Когда можно позвонить?', 'Коли можна зателефонувати?', 'Ne zaman aranabilir?']),
        mc('Z1', 'neue Karte', I.read, `${RATGEBER} Wann kommt die neue Karte?`, ['Nach ungefähr einer Woche.', 'Am nächsten Tag.', 'Sofort bei der Polizei.'],
          ['When does the new card arrive?', 'Когда придёт новая карта?', 'Коли надійде нова картка?', 'Yeni kart ne zaman geliyor?']),
        mc('Z1', 'Wofür?', I.read, `${SPENDE} Wofür sammelt die Person Geld?`, ['Für Essen für Kinder.', 'Für eine neue Bank.', 'Für ein Kinderfest.'],
          ['What is the person collecting money for?', 'На что этот человек собирает деньги?', 'На що ця людина збирає гроші?', 'Bu kişi ne için para topluyor?']),
        mc('Z1', 'Wie spenden?', I.read, `${SPENDE} Wie kann man spenden?`, ['Bar oder mit einer Überweisung.', 'Nur mit Kreditkarte.', 'Nur mit einem Kredit.'],
          ['How can you donate?', 'Как можно сделать пожертвование?', 'Як можна зробити пожертву?', 'Nasıl bağış yapılabilir?']),
        gap('Z1', 'spenden', I.verb, 'Wir sammeln Geld für das Tierheim. Möchten Sie auch etwas ', '?', 'spenden', ['sperren', 'sparen'],
          ['We are collecting money for the animal shelter. Would you like to donate something too?', 'Мы собираем деньги для приюта для животных. Вы тоже хотите что-нибудь пожертвовать?', 'Ми збираємо гроші для притулку для тварин. Ви теж хочете щось пожертвувати?', 'Hayvan barınağı için para topluyoruz. Siz de bir şey bağışlamak ister misiniz?'],
          ['donate', 'пожертвовать', 'пожертвувати', 'bağış yapmak']),
      ],
    },
  ],
}

export default path
