/** Shared by the Next server and native Node worker; no browser or framework dependency. */
export const MAIL_LOCALES = ['de', 'en', 'ru', 'uk', 'tr']
export const MAIL_KINDS = ['registration_received', 'registration_confirmed', 'booking_cancelled', 'cancellation_requested', 'trial_confirmed', 'trial_cancelled', 'new_enrollment', 'feedback_available']
const copy = {
  de: { hello:'Hallo', eyebrow:'DEIN NÄCHSTES KAPITEL', open:'Lernraum öffnen', admin:'Registrierungen ansehen', fallback:'Falls der Button nicht funktioniert, öffne diesen Link:', courses:'Deine Kurse', total:'Gesamtbetrag', start:'Beginn', end:'Ende', contact:'Bei Fragen antworte einfach auf diese E-Mail.', office:'Sitz der Sprachschule', classroom:'Präsenzunterricht', imprint:'Impressum', privacy:'Datenschutz', terms:'AGB', received:['Deine Anmeldung ist angekommen.','Vielen Dank für deine Kursanmeldung. Wir prüfen deine Angaben und melden uns mit der Bestätigung. Dein Kursplatz ist noch nicht bestätigt.'], confirmed:['Dein Kursplatz ist bestätigt.','Wir freuen uns auf dich! Deine Anmeldung wurde angenommen. Du erhältst deine Rechnung separat. Der Unterricht wird im Voraus bezahlt.'], cancelled:['Deine Kursbuchung wurde beendet.','Wir bestätigen die Beendigung deiner Kursbuchung. Die vereinbarten Vertrags- und Zahlungsbedingungen bleiben maßgeblich. Bei Fragen helfen wir dir gerne weiter.'], cancellation:['Deine Anfrage ist angekommen.','Wir haben deine Kündigungsanfrage erhalten und prüfen sie. Diese Nachricht bestätigt den Eingang; die Bestätigung des Beendigungsdatums folgt separat.'], trial:['Deine Probestunde ist bestätigt.','Wir freuen uns darauf, dich kennenzulernen. Die Angaben zu deiner Probestunde findest du unten.'], trialCancelled:['Deine Probestunde wurde abgesagt.','Deine Probestunde findet zu diesem Termin nicht statt. Antworte uns gerne, wenn du einen neuen Termin vereinbaren möchtest.'], enrollment:['Eine neue Anmeldung wartet.','Eine neue Kursanmeldung ist eingegangen. Prüfe die Angaben und den Kurswunsch im Lehrerbereich.'], feedback:['Dein Feedback ist da.','Deine Lehrkraft hat dir eine neue Rückmeldung hinterlassen. Öffne den Lernraum, höre sie dir an und antworte in deinem Gespräch.'] },
  en: { hello:'Hello', eyebrow:'YOUR NEXT CHAPTER', open:'Open learning space', admin:'View registrations', fallback:'If the button does not work, open this link:', courses:'Your courses', total:'Total amount', start:'Start', end:'End', contact:'If you have questions, simply reply to this email.', office:'School office', classroom:'In-person lessons', imprint:'Legal notice', privacy:'Privacy', terms:'Terms', received:['We have received your registration.','Thank you for registering for a course. We will review your details and send you a confirmation. Your place is not confirmed yet.'], confirmed:['Your course place is confirmed.','We look forward to seeing you! Your registration has been accepted. Your invoice will arrive separately. Tuition is paid in advance.'], cancelled:['Your course booking has ended.','We confirm the end of your course booking. The agreed contract and payment terms still apply. Please contact us if you have questions.'], cancellation:['We have received your request.','We have received your cancellation request and will review it. This message confirms receipt; confirmation of the end date will follow separately.'], trial:['Your trial lesson is confirmed.','We look forward to meeting you. You can find the details of your trial lesson below.'], trialCancelled:['Your trial lesson has been cancelled.','Your trial lesson will not take place at this time. Reply to us if you would like to arrange another date.'], enrollment:['A new registration is waiting.','A new course registration has arrived. Review the details and requested courses in the teacher area.'], feedback:['Your feedback is ready.','Your teacher has left you new feedback. Open your learning space, listen to it and reply in your conversation.'] },
  ru: { hello:'Здравствуйте', eyebrow:'ВАША НОВАЯ ГЛАВА', open:'Открыть учебный кабинет', admin:'Посмотреть заявки', fallback:'Если кнопка не работает, откройте эту ссылку:', courses:'Ваши курсы', total:'Общая сумма', start:'Начало', end:'Окончание', contact:'Если у вас есть вопросы, просто ответьте на это письмо.', office:'Адрес школы', classroom:'Очные занятия', imprint:'Реквизиты', privacy:'Конфиденциальность', terms:'Условия', received:['Ваша заявка получена.','Спасибо за запись на курс. Мы проверим ваши данные и отправим подтверждение. Ваше место пока не подтверждено.'], confirmed:['Ваше место на курсе подтверждено.','Будем рады вас видеть! Ваша заявка принята. Счёт будет отправлен отдельно. Обучение оплачивается заранее.'], cancelled:['Ваша запись на курс завершена.','Подтверждаем прекращение вашей записи на курс. Согласованные условия договора и оплаты остаются действительными. Если у вас есть вопросы, свяжитесь с нами.'], cancellation:['Ваш запрос получен.','Мы получили ваш запрос на расторжение договора и рассмотрим его. Это письмо подтверждает получение запроса; подтверждение даты окончания будет отправлено отдельно.'], trial:['Ваш пробный урок подтверждён.','Будем рады познакомиться с вами. Информация о вашем пробном уроке указана ниже.'], trialCancelled:['Ваш пробный урок отменён.','Пробный урок в это время не состоится. Ответьте нам, если хотите согласовать другую дату.'], enrollment:['Поступила новая заявка.','Получена новая заявка на курс. Проверьте данные и выбранные курсы в кабинете преподавателя.'], feedback:['Ваш отзыв готов.','Преподаватель оставил вам новую обратную связь. Откройте учебный кабинет, прослушайте её и ответьте в вашем диалоге.'] },
  uk: { hello:'Вітаємо', eyebrow:'ВАШ НОВИЙ РОЗДІЛ', open:'Відкрити навчальний кабінет', admin:'Переглянути заявки', fallback:'Якщо кнопка не працює, відкрийте це посилання:', courses:'Ваші курси', total:'Загальна сума', start:'Початок', end:'Завершення', contact:'Якщо у вас є запитання, просто дайте відповідь на цей лист.', office:'Адреса школи', classroom:'Очні заняття', imprint:'Реквізити', privacy:'Конфіденційність', terms:'Умови', received:['Вашу заявку отримано.','Дякуємо за запис на курс. Ми перевіримо ваші дані та надішлемо підтвердження. Ваше місце ще не підтверджено.'], confirmed:['Ваше місце на курсі підтверджено.','Будемо раді вас бачити! Вашу заявку прийнято. Рахунок надійде окремо. Навчання оплачується заздалегідь.'], cancelled:['Ваш запис на курс завершено.','Підтверджуємо припинення вашого запису на курс. Узгоджені умови договору та оплати залишаються чинними. Звертайтеся до нас із запитаннями.'], cancellation:['Ваш запит отримано.','Ми отримали ваш запит на розірвання договору та розглянемо його. Цей лист підтверджує отримання; підтвердження дати завершення надійде окремо.'], trial:['Ваш пробний урок підтверджено.','Будемо раді познайомитися з вами. Інформацію про ваш пробний урок наведено нижче.'], trialCancelled:['Ваш пробний урок скасовано.','Пробний урок у цей час не відбудеться. Напишіть нам, якщо бажаєте узгодити іншу дату.'], enrollment:['Надійшла нова заявка.','Отримано нову заявку на курс. Перевірте дані й обрані курси в кабінеті викладача.'], feedback:['Ваш відгук готовий.','Викладач залишив вам новий зворотний зв’язок. Відкрийте навчальний кабінет, прослухайте його та дайте відповідь у вашому діалозі.'] },
  tr: { hello:'Merhaba', eyebrow:'YENİ BÖLÜMÜNÜZ', open:'Öğrenme alanını aç', admin:'Kayıtları görüntüle', fallback:'Düğme çalışmazsa bu bağlantıyı açın:', courses:'Kurslarınız', total:'Toplam tutar', start:'Başlangıç', end:'Bitiş', contact:'Sorularınız varsa bu e-postayı yanıtlayabilirsiniz.', office:'Okulun resmî adresi', classroom:'Yüz yüze dersler', imprint:'Yasal bilgiler', privacy:'Gizlilik', terms:'Koşullar', received:['Kaydınız bize ulaştı.','Kurs kaydınız için teşekkür ederiz. Bilgilerinizi inceleyip size onay göndereceğiz. Kurs yeriniz henüz onaylanmadı.'], confirmed:['Kurs yeriniz onaylandı.','Sizi görmekten mutluluk duyacağız! Kaydınız kabul edildi. Faturanız ayrıca gönderilecektir. Ders ücreti peşin ödenir.'], cancelled:['Kurs kaydınız sona erdi.','Kurs kaydınızın sona erdiğini onaylıyoruz. Kararlaştırılan sözleşme ve ödeme koşulları geçerliliğini korur. Sorularınız varsa bize ulaşın.'], cancellation:['Talebiniz bize ulaştı.','İptal talebinizi aldık ve inceleyeceğiz. Bu mesaj talebinizin alındığını onaylar; bitiş tarihi ayrıca onaylanacaktır.'], trial:['Deneme dersiniz onaylandı.','Sizinle tanışmayı sabırsızlıkla bekliyoruz. Deneme dersinizin ayrıntılarını aşağıda bulabilirsiniz.'], trialCancelled:['Deneme dersiniz iptal edildi.','Deneme dersiniz bu tarihte yapılmayacaktır. Yeni bir tarih belirlemek isterseniz bu e-postayı yanıtlayın.'], enrollment:['Yeni bir kayıt bekliyor.','Yeni bir kurs kaydı alındı. Öğretmen alanından bilgileri ve seçilen kursları inceleyin.'], feedback:['Geri bildiriminiz hazır.','Öğretmeniniz size yeni bir geri bildirim bıraktı. Öğrenme alanınızı açın, dinleyin ve konuşmanızda yanıtlayın.'] },
}
const eventCopy = { registration_received:'received', registration_confirmed:'confirmed', booking_cancelled:'cancelled', cancellation_requested:'cancellation', trial_confirmed:'trial', trial_cancelled:'trialCancelled', new_enrollment:'enrollment', feedback_available:'feedback' }
export function escapeHtml(value) { return String(value).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[c]) }
export function mailSiteOrigin(siteUrl) {
  const url = new URL(siteUrl)
  if (!['http:','https:'].includes(url.protocol) || url.username || url.password) throw new Error('invalid_site_url')
  return url.origin
}
export function mailLink(siteUrl, path, locale='de') {
  const origin = mailSiteOrigin(siteUrl)
  const safePath = typeof path === 'string' && path.startsWith('/') && !path.startsWith('//') ? path : `/${locale}/dashboard`
  const url = new URL(safePath, origin)
  if (url.origin !== origin) throw new Error('invalid_mail_path')
  return url.href
}
export function renderTransactionalEmail(kind, locale, payload, siteUrl) {
  if (!MAIL_KINDS.includes(kind)) throw new Error('unsupported_mail_kind')
  const lang = MAIL_LOCALES.includes(locale) ? locale : 'de'
  const c = copy[lang], [title, description] = c[eventCopy[kind]]
  const origin = mailSiteOrigin(siteUrl)
  const link = mailLink(origin, payload.path ?? (kind === 'new_enrollment' ? `/${lang}/admin/registrations` : `/${lang}/dashboard`), lang)
  const name = typeof payload.name === 'string' ? payload.name.slice(0,150) : ''
  const money = value => new Intl.NumberFormat(lang, { style:'currency', currency:'EUR' }).format(value)
  const rows = Array.isArray(payload.courses) ? payload.courses.filter(row => row && typeof row.title === 'string').slice(0,30) : []
  const details = rows.map(row => `${row.title}${typeof row.price === 'number' && Number.isFinite(row.price) ? ` — ${money(row.price)}` : ''}`)
  if (typeof payload.total === 'number' && Number.isFinite(payload.total)) details.push(`${c.total}: ${money(payload.total)}`)
  if (typeof payload.startDate === 'string') details.push(`${c.start}: ${payload.startDate.slice(0,60)}`)
  if (typeof payload.endDate === 'string') details.push(`${c.end}: ${payload.endDate.slice(0,60)}`)
  const button = kind === 'new_enrollment' ? c.admin : c.open
  const text = `${title}\n\n${c.hello}${name ? ` ${name}` : ''},\n\n${description}\n\n${details.join('\n')}${typeof payload.message === 'string' ? `\n\n${payload.message.slice(0,5000)}` : ''}\n\n${button}: ${link}\n\n${c.contact}\n\nSitov Academy\n${c.office}: Hüttenstraße 24a, 30165 Hannover\n${c.classroom}: Freizeitheim Vahrenwald, Vahrenwalder Str. 92, 30165 Hannover\ninfo@sitov-academy.com · +49 171 4758620\n${origin}/${lang}/imprint · ${origin}/${lang}/privacy · ${origin}/${lang}/agb`
  const html = `<!DOCTYPE html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title></head><body style="margin:0;background:#f7f5ef;color:#24272b;font-family:Arial,Helvetica,sans-serif"><div style="display:none;max-height:0;overflow:hidden">${escapeHtml(description)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f7f5ef;padding:28px 12px"><tr><td align="center"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;background:#fffefa;border:1px solid #d7d6ce;border-radius:24px"><tr><td style="padding:32px 28px;border-bottom:1px solid #d7d6ce"><img src="${origin}/Bilder/favicon.png" alt="" width="48" height="48" style="vertical-align:middle;border-radius:12px;margin-right:12px"><span style="font-size:25px;font-weight:bold;vertical-align:middle">Sitov Academy</span></td></tr><tr><td style="padding:32px 28px;font-size:18px;line-height:1.7"><p style="margin:0 0 12px;color:#6942a0;font-size:14px;font-weight:bold;letter-spacing:1px">${c.eyebrow}</p><h1 style="font-size:30px;line-height:1.25;margin:0 0 24px">${escapeHtml(title)}</h1><p>${c.hello}${name ? ` ${escapeHtml(name)}` : ''},</p><p>${escapeHtml(description)}</p>${details.length ? `<div style="padding:20px;background:#ece9e1;border-radius:16px;margin:24px 0"><strong>${c.courses}</strong>${details.map(row=>`<p style="margin:8px 0;font-size:17px">${escapeHtml(row)}</p>`).join('')}</div>` : ''}${typeof payload.message === 'string' ? `<p style="white-space:pre-line">${escapeHtml(payload.message.slice(0,5000))}</p>` : ''}<p style="margin:28px 0"><a href="${escapeHtml(link)}" style="display:inline-block;min-height:48px;line-height:1.5;padding:14px 26px;background:#bd3510;border-radius:999px;color:#fffefa;text-decoration:none;font-size:18px;font-weight:bold">${button}</a></p><p>${c.contact}</p><p style="font-size:15px;color:#62645f;margin-top:28px">${c.fallback}<br><a href="${escapeHtml(link)}" style="color:#6942a0;word-break:break-all">${escapeHtml(link)}</a></p></td></tr></table><div style="max-width:600px;margin:24px auto;font-size:15px;line-height:1.7;color:#62645f;text-align:left"><strong>Sitov Academy</strong><p><strong>${c.office}</strong><br>Hüttenstraße 24a · 30165 Hannover</p><p><strong>${c.classroom}</strong><br>Freizeitheim Vahrenwald<br>Vahrenwalder Str. 92 · 30165 Hannover</p><p><a href="mailto:info@sitov-academy.com" style="color:#62645f">info@sitov-academy.com</a><br><a href="tel:+491714758620" style="color:#62645f">+49 171 4758620</a></p><p><a href="${origin}/${lang}/imprint" style="color:#6942a0">${c.imprint}</a> · <a href="${origin}/${lang}/privacy" style="color:#6942a0">${c.privacy}</a> · <a href="${origin}/${lang}/agb" style="color:#6942a0">${c.terms}</a></p></div></td></tr></table></body></html>`
  return { subject:`${title} · Sitov Academy`, html, text }
}
