import { expect, test, type Page } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
const base64=(v:object)=>Buffer.from(JSON.stringify(v)).toString('base64url')
const fixture='http://127.0.0.1:54330'
const browserErrors=new WeakMap<Page,string[]>()
async function signIn(page:Page,teacher=false){
 const uid=`00000000-0000-4000-8000-00000000000${teacher?2:1}`,expires=Math.floor(Date.now()/1000)+3600
 const user={id:uid,aud:'authenticated',role:'authenticated',email:teacher?'teacher@example.invalid':'demo@example.invalid',email_confirmed_at:'2026-01-01T00:00:00Z',app_metadata:{provider:'email'},user_metadata:{}}
 const session={access_token:`${base64({alg:'HS256',typ:'JWT'})}.${base64({sub:uid,aud:'authenticated',role:'authenticated',exp:expires})}.local-fixture-only`,refresh_token:'local-fixture-only',token_type:'bearer',expires_in:3600,expires_at:expires,user}
 await page.context().addCookies([{name:'sb-sitov-auth-token',value:`base64-${base64(session)}`,domain:'127.0.0.1',path:'/',httpOnly:false,secure:false,sameSite:'Lax'}])
 await page.addInitScript(()=>{localStorage.setItem('theme','light');localStorage.setItem('sitov-consent',JSON.stringify({version:1,marketing:false,decidedAt:new Date().toISOString()}))})
 await page.route('**/*',route=>['127.0.0.1','localhost'].includes(new URL(route.request().url()).hostname)?route.continue():route.abort())
}
async function screenshot(page:Page,name:string){await page.evaluate(()=>window.scrollTo(0,0));await mkdir('/tmp/sitov-certificates-qa',{recursive:true});await page.screenshot({path:`/tmp/sitov-certificates-qa/${test.info().project.name}-${name}.png`,fullPage:true})}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)}
test.beforeEach(async({request,page})=>{await request.get(`${fixture}/__certificates/reset`);const errors:string[]=[];browserErrors.set(page,errors);page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text())})})
test.afterEach(async({page})=>{expect(browserErrors.get(page)??[]).toEqual([])})

test('student: merged paid blocks, gaps, blocked months, history and profile anchor',async({page})=>{
 await signIn(page)
 await page.goto('/de/dashboard/profile#certificates')
 await expect(page.getByRole('heading',{name:'Teilnahmebescheinigungen',exact:true})).toBeVisible()
 await expect(page.getByText('15.01.2026 – 28.02.2026')).toBeVisible()
 await expect(page.getByText('01.04.2026 – 30.04.2026')).toBeVisible()
 await expect(page.getByText('Die Zahlung ist noch nicht vollständig als beglichen erfasst.')).toBeVisible()
 await expect(page.getByText('Deine Teilnahme wird noch bestätigt.')).toBeVisible()
 await expect(page.getByRole('link',{name:'Bescheinigung herunterladen',exact:true})).toHaveCount(1)
 const revoked=page.getByRole('listitem').filter({hasText:'DEMO-SA-REVOKED'})
 await expect(revoked.getByRole('link')).toHaveCount(0)
 await noOverflow(page);await screenshot(page,'student-all')
 await page.getByRole('combobox',{name:'Zeitraum',exact:true}).selectOption('2026-05')
 await expect(page.getByRole('button',{name:'PDF herunterladen',exact:true})).toBeDisabled()
 await page.getByRole('combobox',{name:'Zeitraum',exact:true}).selectOption('2026-01')
 await expect(page.getByText('15.01.2026 – 31.01.2026')).toBeVisible()
 await expect(page.getByRole('button',{name:'PDF herunterladen',exact:true})).toBeEnabled()
 await page.getByRole('link',{name:'Prüfe deinen Namen und deine Anschrift. Diese Angaben erscheinen auf der Bescheinigung.'}).click()
 await expect(page).toHaveURL(/#details$/)
 await expect(page.locator('#details')).toBeVisible()
 await expect(page.locator('#certificates')).toHaveCount(0)
 await noOverflow(page);await screenshot(page,'profile-details')
})

test('teacher: keyboard tabs, upload preview, customer clarification and attendance confirmation',async({page,request})=>{
 await signIn(page,true)
 await page.goto('/de/admin/finance/certificates')
 await expect(page.getByRole('heading',{name:'Teilnahmebescheinigungen',exact:true})).toBeVisible()
 await expect(page.getByRole('tab')).toHaveCount(4)
 await page.getByRole('tab',{name:'Importieren',exact:true}).focus();await page.keyboard.press('ArrowRight')
 await expect(page.getByRole('tab',{name:'Klärfälle',exact:true})).toBeFocused()
 await expect(page.getByRole('tab',{name:'Klärfälle',exact:true})).toHaveAttribute('aria-selected','true')
 await expect(page.getByText('Demo Klärfall',{exact:false}).first()).toBeVisible()
 await noOverflow(page);await screenshot(page,'teacher-clarification')
 await page.locator('summary').filter({hasText:'Demo Klärfall'}).click()
 await page.getByRole('combobox',{name:'Schüler',exact:true}).selectOption('00000000-0000-4000-8000-000000000010')
 await page.getByRole('button',{name:'Verbinden',exact:true}).click()
 await expect(page.getByText('Demo Klärfall',{exact:false})).toHaveCount(0)
 await page.getByRole('tab',{name:'Importieren',exact:true}).click()
 await page.getByLabel('CSV-Datei',{exact:true}).setInputFiles({name:'demo-customers.csv',mimeType:'text/csv',buffer:Buffer.from('Name;Kontaktart;Kunden-/Lieferantennr.;E-Mail\nDemo Neu;Kunde;DEMO-NEW;new@example.invalid\n')})
 await page.getByLabel('Stand des Exports (lokale Zeit)',{exact:true}).fill('2026-09-01T12:00')
 await page.getByRole('button',{name:'Vorschau erstellen',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Importvorschau',exact:true})).toBeVisible()
 await expect(page.getByRole('cell',{name:'DEMO-NEW',exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'Import übernehmen',exact:true})).toBeEnabled()
 await screenshot(page,'teacher-preview');await noOverflow(page)
 await page.getByRole('button',{name:'Import übernehmen',exact:true}).click()
 await expect(page.getByRole('status').filter({hasText:'Änderung gespeichert.'})).toBeVisible()
 await page.getByRole('tab',{name:'Teilnahme',exact:true}).click()
 await page.getByLabel('Monat',{exact:true}).fill('2026-03')
 await expect(page.getByRole('heading',{name:'Zu bestätigende Teilnahme (1)',exact:true})).toBeVisible()
 await page.getByRole('checkbox',{name:'Alle sichtbaren auswählen',exact:true}).check()
 await page.getByRole('button',{name:'Ausgewählte Teilnahme bestätigen (1)',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Zu bestätigende Teilnahme (0)',exact:true})).toBeVisible()
 await expect(page.getByRole('heading',{name:'Erfasste Teilnahme (1)',exact:true})).toBeVisible()
 await noOverflow(page);await screenshot(page,'teacher-attendance')
 await page.getByRole('tab',{name:'Bescheinigungen',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Freigabe eines Schülers prüfen',exact:true})).toBeVisible()
 await noOverflow(page)
 const commands=await (await request.get(`${fixture}/__certificates/commands`)).json()
 expect(commands.map((c:{p_command:string})=>c.p_command)).toEqual(['resolve_customer','stage_import','apply_import','confirm_participation'])
})
