import { toUiLocale } from './locale-routing'
const de = {
  decline: "Anmeldung ablehnen", decline_title: "Kursanmeldung ablehnen?", decline_trial_title: "Probestunden-Anfrage ablehnen?", decline_description: "Diese offene Anfrage wird abgelehnt. Eine Absage wird per E-Mail an die unten genannte Adresse verschickt.", decline_confirm: "Ablehnen und Absage senden", decline_success: "Anfrage abgelehnt. Die Absage wurde für den E-Mail-Versand vorgemerkt.", keep_pending: "Anfrage behalten", trial: "Probestunden-Anfrage", decline_changed: "Diese Anfrage wurde inzwischen geändert. Bitte lade die Ansicht neu.",
  registrations_title: 'Anmeldungen', invoices_title: 'Rechnungen',
  registrations_intro: 'Prüfe die Angaben und die Kursauswahl. Mit der Annahme bestätigst du die Buchung.',
  invoices_intro: 'Rechnungen erstellst du zum Monatsende in papierkram.de für den folgenden Unterrichtsmonat in Vorkasse.',
  invoice_note: '„Rechnung erstellt“ dokumentiert nur deine manuelle Erstellung. Der Status bestätigt weder Versand noch Zahlung.',
  pending: 'Annahme offen', confirmed: 'Bestätigt', cancelled: 'Pausiert / storniert', rejected: 'Abgelehnt', all: 'Alle',
  outstanding: 'Rechnung offen', created: 'Rechnung erstellt', accept: 'Anmeldung annehmen', accepted: 'Anmeldung bestätigt',
  saving: 'Wird gespeichert …', save: 'Als erstellt markieren', reopen: 'Wieder als offen markieren',
  reference: 'Rechnungsnummer (optional)', month: 'Unterrichtsmonat', search: 'Name oder E-Mail suchen',
  empty: 'Hier gibt es aktuell keine Einträge.', failed: 'Die Daten konnten nicht geladen werden. Bitte versuche es erneut.',
  save_failed: 'Die Änderung konnte nicht gespeichert werden. Bitte lade die Ansicht neu.', reload: 'Neu laden',
  courses: 'Gebuchte Kurse', contact: 'Persönliche Angaben', birthday: 'Geburtsdatum', start: 'Unterricht ab',
  registered: 'Angemeldet am', total: 'Angegebener Monatsbetrag', consent: 'Erteilte Einwilligungen',
  privacy: 'Datenschutz', terms: 'AGB', revocation: 'Vorzeitiger Unterrichtsbeginn', recording: 'Unterrichtsaufzeichnung',
  yes: 'Ja', no: 'Nein', unspecified: 'Nicht angegeben', monthly: 'Monatsbuchung', registration: 'Kursanmeldung',
  open_papierkram: 'papierkram.de öffnen', saved: 'Rechnungsstatus gespeichert', history_title: 'Deine Kursanmeldungen',
  history_intro: 'Diese Buchungen gehören zu deinem verifizierten Konto.',
  identity_unresolved: 'Die Zuordnung einer Anmeldung zu deinem Konto ist noch offen. Bitte kontaktiere die Sprachschule, damit wir die Angaben persönlich prüfen können.',
  history_empty: 'Zu deinem Konto sind noch keine Kursanmeldungen hinterlegt.', history_failed: 'Deine bisherigen Kursanmeldungen konnten gerade nicht geladen werden.',
  home: 'Zur Homepage', learning: 'Dein Lernraum', auth_headline: 'Dein Deutsch. Dein nächster Schritt.',
  auth_intro: 'Vokabeln wiederholen, Grammatik verstehen und sicherer sprechen – alles an einem Ort.',
  auth_security: 'Vorhandene Schülerdaten erscheinen erst nach Bestätigung deiner E-Mail-Adresse und erfolgreicher Anmeldung.',
  auth_existing: 'Schon bei uns angemeldet? Nutze dieselbe E-Mail-Adresse. Bei einem bestehenden Lernraum-Konto hilft „Passwort vergessen“.',
  auth_email_sent: 'Bitte prüfe dein Postfach. Falls eine Bestätigung erforderlich ist, erhältst du einen Link. Hast du bereits ein Konto, melde dich an oder nutze „Passwort vergessen“.',
} as const
export type RegistrationLabels = { [K in keyof typeof de]: string }
const en: RegistrationLabels = {
  decline: "Decline registration", decline_title: "Decline this course registration?", decline_trial_title: "Decline this trial lesson request?", decline_description: "This pending request will be declined. A notification will be emailed to the address below.", decline_confirm: "Decline and send notification", decline_success: "Request declined. The email notification has been queued.", keep_pending: "Keep request", trial: "Trial lesson request", decline_changed: "This request has changed. Please reload the page.",
  registrations_title:'Registrations',invoices_title:'Invoices',registrations_intro:'Review personal details and course choices. Accepting confirms the booking.',invoices_intro:'At the end of each month, create invoices in papierkram.de for the next teaching month, payable in advance.',invoice_note:'“Invoice created” records manual preparation only. It does not confirm delivery or payment.',pending:'Awaiting acceptance',confirmed:'Confirmed',cancelled:'Paused / cancelled',rejected:'Declined',all:'All',outstanding:'Invoice outstanding',created:'Invoice created',accept:'Accept registration',accepted:'Registration confirmed',saving:'Saving …',save:'Mark as created',reopen:'Mark as outstanding',reference:'Invoice number (optional)',month:'Teaching month',search:'Search name or email',empty:'There are no entries here yet.',failed:'The data could not be loaded. Please try again.',save_failed:'The change could not be saved. Please reload.',reload:'Reload',courses:'Booked courses',contact:'Personal details',birthday:'Date of birth',start:'Teaching starts',registered:'Registered on',total:'Submitted monthly amount',consent:'Consents given',privacy:'Privacy',terms:'Terms',revocation:'Early start of teaching',recording:'Lesson recording',yes:'Yes',no:'No',unspecified:'Not provided',monthly:'Monthly booking',registration:'Course registration',open_papierkram:'Open papierkram.de',saved:'Invoice status saved',history_title:'Your course registrations',history_intro:'These bookings belong to your verified account.',identity_unresolved:'A registration still needs to be linked to your account. Please contact the school so we can check the details personally.',history_empty:'No course registrations are linked to your account yet.',history_failed:'Your previous course registrations could not be loaded.',home:'Back to homepage',learning:'Your learning space',auth_headline:'Your German. Your next step.',auth_intro:'Review vocabulary, understand grammar and speak with confidence – all in one place.',auth_security:'Existing student details appear only after email verification and successful sign-in.',auth_existing:'Already registered with us? Use the same email address. For an existing learning account, use “Forgot password”.',auth_email_sent:'Please check your inbox. If confirmation is required, you will receive a link. If you already have an account, sign in or use “Forgot password”.',
}
const ru: RegistrationLabels = {
  decline: "Отклонить заявку", decline_title: "Отклонить заявку на курс?", decline_trial_title: "Отклонить заявку на пробный урок?", decline_description: "Эта неподтверждённая заявка будет отклонена. Уведомление будет отправлено на указанный ниже адрес электронной почты.", decline_confirm: "Отклонить и отправить уведомление", decline_success: "Заявка отклонена. Уведомление поставлено в очередь отправки.", keep_pending: "Оставить заявку", trial: "Заявка на пробный урок", decline_changed: "Эта заявка уже изменилась. Обновите страницу.",
  registrations_title:'Заявки',invoices_title:'Счета',registrations_intro:'Проверьте личные данные и выбранные курсы. Принятие заявки подтверждает бронирование.',invoices_intro:'В конце месяца создавайте счета в papierkram.de за следующий учебный месяц на условиях предоплаты.',invoice_note:'«Счёт создан» означает только ручное оформление. Статус не подтверждает отправку или оплату.',pending:'Ожидает принятия',confirmed:'Подтверждено',cancelled:'Приостановлено / отменено',rejected:'Отклонено',all:'Все',outstanding:'Счёт не создан',created:'Счёт создан',accept:'Принять заявку',accepted:'Заявка подтверждена',saving:'Сохранение …',save:'Отметить как созданный',reopen:'Снова отметить как открытый',reference:'Номер счёта (необязательно)',month:'Учебный месяц',search:'Поиск по имени или почте',empty:'Здесь пока нет записей.',failed:'Не удалось загрузить данные. Попробуйте снова.',save_failed:'Не удалось сохранить изменение. Обновите страницу.',reload:'Обновить',courses:'Забронированные курсы',contact:'Личные данные',birthday:'Дата рождения',start:'Начало занятий',registered:'Дата заявки',total:'Указанная сумма за месяц',consent:'Предоставленные согласия',privacy:'Защита данных',terms:'Условия',revocation:'Раннее начало занятий',recording:'Запись занятий',yes:'Да',no:'Нет',unspecified:'Не указано',monthly:'Бронирование на месяц',registration:'Заявка на курс',open_papierkram:'Открыть papierkram.de',saved:'Статус счёта сохранён',history_title:'Твои заявки на курсы',history_intro:'Эти бронирования связаны с твоим подтверждённым аккаунтом.',identity_unresolved:'Привязка одной из заявок к твоему аккаунту ещё не завершена. Свяжись со школой, чтобы мы лично проверили данные.',history_empty:'У твоего аккаунта пока нет заявок на курсы.',history_failed:'Не удалось загрузить предыдущие заявки на курсы.',home:'На главную',learning:'Твоё учебное пространство',auth_headline:'Твой немецкий. Твой следующий шаг.',auth_intro:'Повторяй слова, разбирайся в грамматике и говори увереннее — всё в одном месте.',auth_security:'Данные ученика появятся только после подтверждения почты и успешного входа.',auth_existing:'Уже учишься у нас? Используй ту же почту. Для существующего учебного аккаунта выбери «Забыли пароль».',auth_email_sent:'Проверь почту. Если требуется подтверждение, ты получишь ссылку. Если аккаунт уже есть, войди или выбери «Забыли пароль».',
}
const uk: RegistrationLabels = {
  decline: "Відхилити заявку", decline_title: "Відхилити заявку на курс?", decline_trial_title: "Відхилити заявку на пробний урок?", decline_description: "Цю непідтверджену заявку буде відхилено. Повідомлення буде надіслано на вказану нижче електронну адресу.", decline_confirm: "Відхилити й надіслати повідомлення", decline_success: "Заявку відхилено. Повідомлення додано до черги надсилання.", keep_pending: "Залишити заявку", trial: "Заявка на пробний урок", decline_changed: "Ця заявка вже змінилася. Оновіть сторінку.",
  registrations_title:'Заявки',invoices_title:'Рахунки',registrations_intro:'Перевірте особисті дані та вибрані курси. Прийняття заявки підтверджує бронювання.',invoices_intro:'Наприкінці місяця створюйте рахунки в papierkram.de за наступний навчальний місяць на умовах передоплати.',invoice_note:'«Рахунок створено» означає лише ручне оформлення. Статус не підтверджує надсилання чи оплату.',pending:'Очікує прийняття',confirmed:'Підтверджено',cancelled:'Призупинено / скасовано',rejected:'Відхилено',all:'Усі',outstanding:'Рахунок не створено',created:'Рахунок створено',accept:'Прийняти заявку',accepted:'Заявку підтверджено',saving:'Збереження …',save:'Позначити як створений',reopen:'Знову позначити як відкритий',reference:'Номер рахунку (необов’язково)',month:'Навчальний місяць',search:'Пошук за ім’ям або поштою',empty:'Тут поки немає записів.',failed:'Не вдалося завантажити дані. Спробуйте ще раз.',save_failed:'Не вдалося зберегти зміну. Оновіть сторінку.',reload:'Оновити',courses:'Заброньовані курси',contact:'Особисті дані',birthday:'Дата народження',start:'Початок занять',registered:'Дата заявки',total:'Зазначена сума за місяць',consent:'Надані згоди',privacy:'Захист даних',terms:'Умови',revocation:'Ранній початок занять',recording:'Запис занять',yes:'Так',no:'Ні',unspecified:'Не зазначено',monthly:'Бронювання на місяць',registration:'Заявка на курс',open_papierkram:'Відкрити papierkram.de',saved:'Статус рахунку збережено',history_title:'Твої заявки на курси',history_intro:'Ці бронювання належать твоєму підтвердженому акаунту.',identity_unresolved:'Прив’язку однієї із заявок до твого акаунта ще не завершено. Зв’яжися зі школою, щоб ми особисто перевірили дані.',history_empty:'До твого акаунта поки не прив’язано заявок на курси.',history_failed:'Не вдалося завантажити попередні заявки на курси.',home:'На головну',learning:'Твій навчальний простір',auth_headline:'Твоя німецька. Твій наступний крок.',auth_intro:'Повторюй слова, розумій граматику та говори впевненіше — усе в одному місці.',auth_security:'Дані учня з’являться лише після підтвердження пошти та успішного входу.',auth_existing:'Уже навчаєшся в нас? Використовуй ту саму пошту. Для наявного навчального акаунта вибери «Забули пароль».',auth_email_sent:'Перевір пошту. Якщо потрібне підтвердження, ти отримаєш посилання. Якщо акаунт уже є, увійди або вибери «Забули пароль».',
}
const tr: RegistrationLabels = {
  decline: "Kaydı reddet", decline_title: "Kurs başvurusu reddedilsin mi?", decline_trial_title: "Deneme dersi başvurusu reddedilsin mi?", decline_description: "Bu bekleyen başvuru reddedilecek. Aşağıdaki e-posta adresine bir bildirim gönderilecek.", decline_confirm: "Reddet ve bildirim gönder", decline_success: "Başvuru reddedildi. E-posta bildirimi gönderim kuyruğuna alındı.", keep_pending: "Başvuruyu koru", trial: "Deneme dersi başvurusu", decline_changed: "Bu başvuru değişti. Lütfen sayfayı yenileyin.",
  registrations_title:'Kayıtlar',invoices_title:'Faturalar',registrations_intro:'Kişisel bilgileri ve kurs seçimlerini kontrol edin. Kabul etmek rezervasyonu onaylar.',invoices_intro:'Her ayın sonunda, gelecek eğitim ayı için peşin ödemeli faturaları papierkram.de üzerinden hazırlayın.',invoice_note:'“Fatura oluşturuldu” yalnızca elle hazırlamayı belirtir. Gönderildiğini veya ödendiğini onaylamaz.',pending:'Kabul bekliyor',confirmed:'Onaylandı',cancelled:'Ara verildi / iptal edildi',rejected:'Reddedildi',all:'Tümü',outstanding:'Fatura bekliyor',created:'Fatura oluşturuldu',accept:'Kaydı kabul et',accepted:'Kayıt onaylandı',saving:'Kaydediliyor …',save:'Oluşturuldu olarak işaretle',reopen:'Yeniden bekliyor olarak işaretle',reference:'Fatura numarası (isteğe bağlı)',month:'Eğitim ayı',search:'Ad veya e-posta ara',empty:'Burada henüz kayıt yok.',failed:'Veriler yüklenemedi. Lütfen yeniden deneyin.',save_failed:'Değişiklik kaydedilemedi. Lütfen sayfayı yenileyin.',reload:'Yenile',courses:'Kayıtlı kurslar',contact:'Kişisel bilgiler',birthday:'Doğum tarihi',start:'Eğitim başlangıcı',registered:'Kayıt tarihi',total:'Belirtilen aylık tutar',consent:'Verilen onaylar',privacy:'Veri koruma',terms:'Koşullar',revocation:'Eğitime erken başlama',recording:'Ders kaydı',yes:'Evet',no:'Hayır',unspecified:'Belirtilmedi',monthly:'Aylık rezervasyon',registration:'Kurs kaydı',open_papierkram:'papierkram.de aç',saved:'Fatura durumu kaydedildi',history_title:'Kurs kayıtların',history_intro:'Bu rezervasyonlar doğrulanmış hesabına aittir.',identity_unresolved:'Bir kaydın hesabına bağlantısı henüz tamamlanmadı. Bilgileri şahsen kontrol edebilmemiz için okulla iletişime geç.',history_empty:'Hesabına bağlı kurs kaydı henüz yok.',history_failed:'Önceki kurs kayıtların yüklenemedi.',home:'Ana sayfaya dön',learning:'Öğrenme alanın',auth_headline:'Senin Almancan. Bir sonraki adımın.',auth_intro:'Kelime tekrarı yap, dil bilgisini anla ve daha güvenle konuş — hepsi bir yerde.',auth_security:'Mevcut öğrenci bilgileri ancak e-posta doğrulamasından ve başarılı girişten sonra görünür.',auth_existing:'Zaten öğrencimiz misin? Aynı e-posta adresini kullan. Mevcut öğrenme hesabın için “Şifremi unuttum” seçeneğini kullan.',auth_email_sent:'Lütfen gelen kutunu kontrol et. Onay gerekiyorsa bir bağlantı alacaksın. Hesabın zaten varsa giriş yap veya “Şifremi unuttum” seçeneğini kullan.',
}
export const registrationLabels = (lang: string): RegistrationLabels => ({de,en,ru,uk,tr})[toUiLocale(lang)]
