const de = {
  title: 'Lernmedien', intro: 'Videos und Präsentationen nach Niveau. Schüler mit Freigabe für das jeweilige Niveau können die Medien sehen.', folders: 'Ordner', newFolder: 'Ordner anlegen',
  name: 'Name', level: 'Niveau', order: 'Reihenfolge', save: 'Speichern', edit: 'Ordner bearbeiten',
  videos: 'Videos', presentations: 'Präsentationen', upload: 'Datei hochladen', choose: 'Datei auswählen', fileTitle: 'Medientitel',
  hint: 'MP4, WebM, PDF, PPTX oder KEY · höchstens 512 MiB. Nach einer Unterbrechung dieselbe Datei erneut auswählen.',
  start: 'Hochladen / fortsetzen', pause: 'Pausieren', resume: 'Fortsetzen', retry: 'Erneut versuchen', uploading: 'Wird hochgeladen', finalizing: 'Wird gespeichert',
  paused: 'Upload pausiert', saved: 'Gespeichert', failed: 'Nicht gespeichert. Bitte erneut versuchen.', invalid: 'Dateityp oder Dateigröße ist ungültig.',
  empty: 'Noch keine Medien vorhanden.', noFolders: 'Noch keine Ordner vorhanden.', open: 'Öffnen', download: 'Herunterladen', close: 'Schließen',
  accessFailed: 'Dieses Medium ist derzeit nicht verfügbar. Bitte erneut öffnen.', expired: 'Der Zugriff ist abgelaufen. Bitte erneut öffnen.',
  back: 'Zurück zum Niveau', selectFolder: 'Ordner auswählen', loading: 'Wird geladen',
}
type Copy = typeof de
const en: Copy = { title:'Learning media',intro:'Videos and presentations by level. Students with access to a level can view its media.',folders:'Folders',newFolder:'Create folder',name:'Name',level:'Level',order:'Order',save:'Save',edit:'Edit folder',videos:'Videos',presentations:'Presentations',upload:'Upload file',choose:'Choose file',fileTitle:'Media title',hint:'MP4, WebM, PDF, PPTX or KEY · up to 512 MiB. Select the same file again after an interruption.',start:'Upload / resume',pause:'Pause',resume:'Resume',retry:'Try again',uploading:'Uploading',finalizing:'Saving',paused:'Upload paused',saved:'Saved',failed:'Could not save. Please try again.',invalid:'Invalid file type or size.',empty:'No media yet.',noFolders:'No folders yet.',open:'Open',download:'Download',close:'Close',accessFailed:'This file is currently unavailable. Please open it again.',expired:'Access expired. Please open the file again.',back:'Back to level',selectFolder:'Select folder',loading:'Loading' }
const ru: Copy = { title:'Учебные материалы',intro:'Видео и презентации по уровням. Материалы доступны ученикам, которым открыт соответствующий уровень.',folders:'Папки',newFolder:'Создать папку',name:'Название',level:'Уровень',order:'Порядок',save:'Сохранить',edit:'Изменить папку',videos:'Видео',presentations:'Презентации',upload:'Загрузить файл',choose:'Выбрать файл',fileTitle:'Название материала',hint:'MP4, WebM, PDF, PPTX или KEY · до 512 МиБ. После прерывания выберите тот же файл.',start:'Загрузить / продолжить',pause:'Приостановить',resume:'Продолжить',retry:'Повторить',uploading:'Загрузка',finalizing:'Сохранение',paused:'Загрузка приостановлена',saved:'Сохранено',failed:'Не удалось сохранить. Повторите попытку.',invalid:'Неверный тип или размер файла.',empty:'Материалов пока нет.',noFolders:'Папок пока нет.',open:'Открыть',download:'Скачать',close:'Закрыть',accessFailed:'Материал сейчас недоступен. Откройте его ещё раз.',expired:'Срок доступа истёк. Откройте файл ещё раз.',back:'К уровню',selectFolder:'Выберите папку',loading:'Загрузка' }
const uk: Copy = { title:'Навчальні матеріали',intro:'Відео та презентації за рівнями. Матеріали доступні учням, яким відкрито відповідний рівень.',folders:'Папки',newFolder:'Створити папку',name:'Назва',level:'Рівень',order:'Порядок',save:'Зберегти',edit:'Змінити папку',videos:'Відео',presentations:'Презентації',upload:'Завантажити файл',choose:'Вибрати файл',fileTitle:'Назва матеріалу',hint:'MP4, WebM, PDF, PPTX або KEY · до 512 МіБ. Після переривання виберіть той самий файл.',start:'Завантажити / продовжити',pause:'Призупинити',resume:'Продовжити',retry:'Повторити',uploading:'Завантаження',finalizing:'Збереження',paused:'Завантаження призупинено',saved:'Збережено',failed:'Не вдалося зберегти. Спробуйте ще раз.',invalid:'Неприпустимий тип або розмір файлу.',empty:'Матеріалів поки немає.',noFolders:'Папок поки немає.',open:'Відкрити',download:'Завантажити',close:'Закрити',accessFailed:'Матеріал зараз недоступний. Відкрийте його знову.',expired:'Термін доступу минув. Відкрийте файл знову.',back:'До рівня',selectFolder:'Виберіть папку',loading:'Завантаження' }
const tr: Copy = { title:'Öğrenme materyalleri',intro:'Seviyelere göre videolar ve sunumlar. Öğrenciler, erişim izni verilen seviyenin materyallerini görebilir.',folders:'Klasörler',newFolder:'Klasör oluştur',name:'Ad',level:'Seviye',order:'Sıra',save:'Kaydet',edit:'Klasörü düzenle',videos:'Videolar',presentations:'Sunumlar',upload:'Dosya yükle',choose:'Dosya seç',fileTitle:'Materyal başlığı',hint:'MP4, WebM, PDF, PPTX veya KEY · en fazla 512 MiB. Kesintiden sonra aynı dosyayı tekrar seçin.',start:'Yükle / devam et',pause:'Duraklat',resume:'Devam et',retry:'Tekrar dene',uploading:'Yükleniyor',finalizing:'Kaydediliyor',paused:'Yükleme duraklatıldı',saved:'Kaydedildi',failed:'Kaydedilemedi. Tekrar deneyin.',invalid:'Geçersiz dosya türü veya boyutu.',empty:'Henüz materyal yok.',noFolders:'Henüz klasör yok.',open:'Aç',download:'İndir',close:'Kapat',accessFailed:'Bu materyal şu anda kullanılamıyor. Tekrar açın.',expired:'Erişim süresi doldu. Dosyayı tekrar açın.',back:'Seviyeye dön',selectFolder:'Klasör seç',loading:'Yükleniyor' }
export function mediaCopy(lang: string): Copy { return ({ de, en, ru, uk, tr } as Record<string, Copy>)[lang] ?? de }
