const de = {
  title: 'Lernmedien', intro: 'Videos, Präsentationen und Links nach Niveau – für YouTube-Videos und Websites genügt ein Link. Schüler mit Freigabe für das jeweilige Niveau können die Medien sehen.', folders: 'Ordner', newFolder: 'Ordner anlegen',
  visibility: 'Für Schüler sichtbar', visible: 'Sichtbar', hidden: 'Ausgeblendet', name: 'Name', level: 'Niveau', order: 'Reihenfolge', save: 'Speichern', edit: 'Ordner bearbeiten',
  videos: 'Videos', presentations: 'Präsentationen', upload: 'Datei hochladen', choose: 'Datei auswählen', fileTitle: 'Medientitel',
  hint: 'MP4, WebM, PDF, PPTX oder KEY · höchstens 512 MiB. Nach einer Unterbrechung dieselbe Datei erneut auswählen.',
  start: 'Hochladen / fortsetzen', pause: 'Pausieren', resume: 'Fortsetzen', retry: 'Erneut versuchen', uploading: 'Wird hochgeladen', finalizing: 'Wird gespeichert',
  paused: 'Upload pausiert', saved: 'Gespeichert', failed: 'Nicht gespeichert. Bitte erneut versuchen.', invalid: 'Dateityp oder Dateigröße ist ungültig.',
  empty: 'Noch keine Medien vorhanden.', noFolders: 'Noch keine Ordner vorhanden.', open: 'Öffnen', download: 'Herunterladen', close: 'Schließen',
  accessFailed: 'Dieses Medium ist derzeit nicht verfügbar. Bitte erneut öffnen.', expired: 'Der Zugriff ist abgelaufen. Bitte erneut öffnen.',
  back: 'Zurück zum Niveau', selectFolder: 'Ordner auswählen', loading: 'Wird geladen',
  addContent: 'Inhalt hinzufügen',
  addFile: 'Datei hochladen',
  addLink: 'Link hinzufügen',
  links: 'Links',
  linkUrl: 'Link (YouTube, Video oder Website)',
  linkUrlHint: 'Beginnt mit https:// – YouTube-Links werden automatisch vereinheitlicht. Schüler öffnen den Link in einem neuen Tab.',
  linkTitle: 'Titel',
  linkDescription: 'Beschreibung (optional)',
  linkVisible: 'Für Schüler sichtbar',
  linkEdit: 'Link bearbeiten',
  linkSave: 'Link speichern',
  cancel: 'Abbrechen',
  editLink: 'Bearbeiten',
  remove: 'Entfernen',
  confirmRemove: 'Diesen Link wirklich entfernen?',
  linkInvalid: 'Bitte gib einen vollständigen Link ein, z. B. https://www.youtube.com/watch?v=…',
  linkFolder: 'Ordner',
  looseLinks: 'Links ohne Ordner',
  looseHint: 'Diese Links stammen aus der früheren Video-Verwaltung und erscheinen bei Schülern unter „Videos im Internet“. Ordne sie über „Bearbeiten“ einem Ordner zu.',
  website: 'Website',
}
type Copy = typeof de
const en: Copy = { title:'Learning media',intro:'Videos, presentations and links by level – a link is enough for YouTube videos and websites. Students with access to a level can view its media.',folders:'Folders',newFolder:'Create folder',visibility:'Visible to students',visible:'Visible',hidden:'Hidden',name:'Name',level:'Level',order:'Order',save:'Save',edit:'Edit folder',videos:'Videos',presentations:'Presentations',upload:'Upload file',choose:'Choose file',fileTitle:'Media title',hint:'MP4, WebM, PDF, PPTX or KEY · up to 512 MiB. Select the same file again after an interruption.',start:'Upload / resume',pause:'Pause',resume:'Resume',retry:'Try again',uploading:'Uploading',finalizing:'Saving',paused:'Upload paused',saved:'Saved',failed:'Could not save. Please try again.',invalid:'Invalid file type or size.',empty:'No media yet.',noFolders:'No folders yet.',open:'Open',download:'Download',close:'Close',accessFailed:'This file is currently unavailable. Please open it again.',expired:'Access expired. Please open the file again.',back:'Back to level',selectFolder:'Select folder',loading:'Loading',addContent:'Add content',addFile:'Upload file',addLink:'Add link',links:'Links',linkUrl:'Link (YouTube, video or website)',linkUrlHint:'Starts with https:// – YouTube links are normalised automatically. Students open the link in a new tab.',linkTitle:'Title',linkDescription:'Description (optional)',linkVisible:'Visible to students',linkEdit:'Edit link',linkSave:'Save link',cancel:'Cancel',editLink:'Edit',remove:'Remove',confirmRemove:'Remove this link?',linkInvalid:'Please enter a complete link, e.g. https://www.youtube.com/watch?v=…',linkFolder:'Folder',looseLinks:'Links without a folder',looseHint:'These links come from the former video management and appear to students under “Videos on the web”. Use “Edit” to move them into a folder.',website:'Website' }
const ru: Copy = { title:'Учебные материалы',intro:'Видео, презентации и ссылки по уровням — для видео с YouTube и сайтов достаточно ссылки. Материалы доступны ученикам, которым открыт соответствующий уровень.',folders:'Папки',newFolder:'Создать папку',visibility:'Видно ученикам',visible:'Видно',hidden:'Скрыто',name:'Название',level:'Уровень',order:'Порядок',save:'Сохранить',edit:'Изменить папку',videos:'Видео',presentations:'Презентации',upload:'Загрузить файл',choose:'Выбрать файл',fileTitle:'Название материала',hint:'MP4, WebM, PDF, PPTX или KEY · до 512 МиБ. После прерывания выберите тот же файл.',start:'Загрузить / продолжить',pause:'Приостановить',resume:'Продолжить',retry:'Повторить',uploading:'Загрузка',finalizing:'Сохранение',paused:'Загрузка приостановлена',saved:'Сохранено',failed:'Не удалось сохранить. Повторите попытку.',invalid:'Неверный тип или размер файла.',empty:'Материалов пока нет.',noFolders:'Папок пока нет.',open:'Открыть',download:'Скачать',close:'Закрыть',accessFailed:'Материал сейчас недоступен. Откройте его ещё раз.',expired:'Срок доступа истёк. Откройте файл ещё раз.',back:'К уровню',selectFolder:'Выберите папку',loading:'Загрузка',addContent:'Добавить материал',addFile:'Загрузить файл',addLink:'Добавить ссылку',links:'Ссылки',linkUrl:'Ссылка (YouTube, видео или сайт)',linkUrlHint:'Начинается с https:// — ссылки YouTube автоматически приводятся к единому виду. Ученики открывают ссылку в новой вкладке.',linkTitle:'Название',linkDescription:'Описание (необязательно)',linkVisible:'Видно ученикам',linkEdit:'Изменить ссылку',linkSave:'Сохранить ссылку',cancel:'Отмена',editLink:'Изменить',remove:'Удалить',confirmRemove:'Удалить эту ссылку?',linkInvalid:'Введите полную ссылку, например https://www.youtube.com/watch?v=…',linkFolder:'Папка',looseLinks:'Ссылки без папки',looseHint:'Эти ссылки перенесены из прежнего раздела видео и видны ученикам в блоке «Видео в интернете». Через «Изменить» их можно поместить в папку.',website:'Сайт' }
const uk: Copy = { title:'Навчальні матеріали',intro:'Відео, презентації та посилання за рівнями — для відео з YouTube і сайтів достатньо посилання. Матеріали доступні учням, яким відкрито відповідний рівень.',folders:'Папки',newFolder:'Створити папку',visibility:'Видно учням',visible:'Видно',hidden:'Приховано',name:'Назва',level:'Рівень',order:'Порядок',save:'Зберегти',edit:'Змінити папку',videos:'Відео',presentations:'Презентації',upload:'Завантажити файл',choose:'Вибрати файл',fileTitle:'Назва матеріалу',hint:'MP4, WebM, PDF, PPTX або KEY · до 512 МіБ. Після переривання виберіть той самий файл.',start:'Завантажити / продовжити',pause:'Призупинити',resume:'Продовжити',retry:'Повторити',uploading:'Завантаження',finalizing:'Збереження',paused:'Завантаження призупинено',saved:'Збережено',failed:'Не вдалося зберегти. Спробуйте ще раз.',invalid:'Неприпустимий тип або розмір файлу.',empty:'Матеріалів поки немає.',noFolders:'Папок поки немає.',open:'Відкрити',download:'Завантажити',close:'Закрити',accessFailed:'Матеріал зараз недоступний. Відкрийте його знову.',expired:'Термін доступу минув. Відкрийте файл знову.',back:'До рівня',selectFolder:'Виберіть папку',loading:'Завантаження',addContent:'Додати матеріал',addFile:'Завантажити файл',addLink:'Додати посилання',links:'Посилання',linkUrl:'Посилання (YouTube, відео або сайт)',linkUrlHint:'Починається з https:// — посилання YouTube автоматично зводяться до єдиного вигляду. Учні відкривають посилання в новій вкладці.',linkTitle:'Назва',linkDescription:'Опис (необов’язково)',linkVisible:'Видно учням',linkEdit:'Змінити посилання',linkSave:'Зберегти посилання',cancel:'Скасувати',editLink:'Змінити',remove:'Видалити',confirmRemove:'Видалити це посилання?',linkInvalid:'Введіть повне посилання, наприклад https://www.youtube.com/watch?v=…',linkFolder:'Папка',looseLinks:'Посилання без папки',looseHint:'Ці посилання перенесено з колишнього розділу відео; учні бачать їх у блоці «Відео в інтернеті». Через «Змінити» їх можна перемістити в папку.',website:'Сайт' }
const tr: Copy = { title:'Öğrenme materyalleri',intro:'Seviyelere göre videolar, sunumlar ve bağlantılar – YouTube videoları ve web siteleri için bir bağlantı yeterlidir. Öğrenciler, erişim izni verilen seviyenin materyallerini görebilir.',folders:'Klasörler',newFolder:'Klasör oluştur',visibility:'Öğrencilere görünür',visible:'Görünür',hidden:'Gizli',name:'Ad',level:'Seviye',order:'Sıra',save:'Kaydet',edit:'Klasörü düzenle',videos:'Videolar',presentations:'Sunumlar',upload:'Dosya yükle',choose:'Dosya seç',fileTitle:'Materyal başlığı',hint:'MP4, WebM, PDF, PPTX veya KEY · en fazla 512 MiB. Kesintiden sonra aynı dosyayı tekrar seçin.',start:'Yükle / devam et',pause:'Duraklat',resume:'Devam et',retry:'Tekrar dene',uploading:'Yükleniyor',finalizing:'Kaydediliyor',paused:'Yükleme duraklatıldı',saved:'Kaydedildi',failed:'Kaydedilemedi. Tekrar deneyin.',invalid:'Geçersiz dosya türü veya boyutu.',empty:'Henüz materyal yok.',noFolders:'Henüz klasör yok.',open:'Aç',download:'İndir',close:'Kapat',accessFailed:'Bu materyal şu anda kullanılamıyor. Tekrar açın.',expired:'Erişim süresi doldu. Dosyayı tekrar açın.',back:'Seviyeye dön',selectFolder:'Klasör seç',loading:'Yükleniyor',addContent:'İçerik ekle',addFile:'Dosya yükle',addLink:'Bağlantı ekle',links:'Bağlantılar',linkUrl:'Bağlantı (YouTube, video veya web sitesi)',linkUrlHint:'https:// ile başlar – YouTube bağlantıları otomatik olarak düzenlenir. Öğrenciler bağlantıyı yeni bir sekmede açar.',linkTitle:'Başlık',linkDescription:'Açıklama (isteğe bağlı)',linkVisible:'Öğrencilere görünür',linkEdit:'Bağlantıyı düzenle',linkSave:'Bağlantıyı kaydet',cancel:'İptal',editLink:'Düzenle',remove:'Kaldır',confirmRemove:'Bu bağlantı kaldırılsın mı?',linkInvalid:'Lütfen tam bir bağlantı girin, ör. https://www.youtube.com/watch?v=…',linkFolder:'Klasör',looseLinks:'Klasörsüz bağlantılar',looseHint:'Bu bağlantılar eski video yönetiminden geliyor ve öğrencilere “İnternetteki videolar” bölümünde görünür. “Düzenle” ile bir klasöre taşıyabilirsiniz.',website:'Web sitesi' }
export function mediaCopy(lang: string): Copy { return ({ de, en, ru, uk, tr } as Record<string, Copy>)[lang] ?? de }
