import { toUiLocale } from './locale-routing'
import type { SitovPronunciationPretestError } from './sitov-pronunciation-pretest-contract'

const sitovPretestCopy = {
  de: { title: 'Vortest', start: 'Vortest starten', resume: 'Vortest fortsetzen', open: 'Zum Sprechtext', retry: 'Erneut versuchen', next: 'Speichern und weiter', previous: 'Zurück', submit: 'Antworten prüfen', selected: 'Antwort ausgewählt', saved: 'Antworten gespeichert', working: 'Wird gespeichert …', loading: 'Wird geladen …', passed: 'Vortest bestanden', failed: 'Noch nicht bestanden', unavailable: 'Dieser Vortest ist noch nicht verfügbar.', changed: 'Die Version hat sich geändert. Lade die Textauswahl neu.', refresh: 'Textauswahl neu laden', instruction: 'Wähle eine Antwort. Das Ergebnis erhältst du nach der Abgabe.', help: 'Hilfe', helpTitle: 'Dein Vortest zu diesem Text', helpBody: 'Deine Antworten werden beim Weitergehen gespeichert. Du kannst sie vor der Abgabe ändern. Nur der Server bestätigt das Ergebnis für genau diesen Text.', progress: 'Aufgabe {current} von {total}', score: '{correct} von {total} richtig', unsaved: 'Auswahl noch nicht gespeichert', learning: 'Passend weiterlernen', vocabulary: 'Wörter üben', verbs: 'Verbformen üben', learning_path: 'Satzübungen', connection: 'Verbindung unterbrochen. Deine Auswahl bleibt hier erhalten.', conflict: 'Der Versuch wurde geändert. Lade den gespeicherten Stand erneut.', auth: 'Melde dich erneut an.', invalid: 'Die Antwort konnte nicht gespeichert werden. Lade den Versuch erneut.', rate: 'Bitte versuche es in Kürze erneut.', missing: 'Dieser Text ist gerade nicht verfügbar.' },
  en: { title: 'Pretest', start: 'Start pretest', resume: 'Resume pretest', open: 'Open speaking text', retry: 'Try again', next: 'Save and continue', previous: 'Back', submit: 'Check answers', selected: 'Answer selected', saved: 'Answers saved', working: 'Saving …', loading: 'Loading …', passed: 'Pretest passed', failed: 'Not passed yet', unavailable: 'This pretest is not available yet.', changed: 'The version has changed. Reload the text list.', refresh: 'Reload text list', instruction: 'Choose one answer. You receive the result after submitting.', help: 'Help', helpTitle: 'Your pretest for this text', helpBody: 'Your answers are saved when you continue. You can change them before submitting. Only the server confirms the result for this exact text.', progress: 'Question {current} of {total}', score: '{correct} of {total} correct', unsaved: 'Selection not saved yet', learning: 'Keep learning', vocabulary: 'Practise words', verbs: 'Practise verb forms', learning_path: 'Sentence practice', connection: 'Connection lost. Your selection is kept here.', conflict: 'This attempt has changed. Reload your saved answers.', auth: 'Please sign in again.', invalid: 'The answer could not be saved. Reload the attempt.', rate: 'Please try again shortly.', missing: 'This text is currently unavailable.' },
  ru: { title: 'Предварительный тест', start: 'Начать тест', resume: 'Продолжить тест', open: 'К тексту для произношения', retry: 'Попробовать снова', next: 'Сохранить и продолжить', previous: 'Назад', submit: 'Проверить ответы', selected: 'Ответ выбран', saved: 'Ответы сохранены', working: 'Сохранение …', loading: 'Загрузка …', passed: 'Тест пройден', failed: 'Пока не пройден', unavailable: 'Этот тест пока недоступен.', changed: 'Версия изменилась. Обнови список текстов.', refresh: 'Обновить список текстов', instruction: 'Выбери один ответ. Результат появится после отправки.', help: 'Помощь', helpTitle: 'Тест к этому тексту', helpBody: 'Ответы сохраняются при переходе дальше. Их можно изменить до отправки. Результат для этого текста подтверждает только сервер.', progress: 'Задание {current} из {total}', score: 'Правильно: {correct} из {total}', unsaved: 'Выбор ещё не сохранён', learning: 'Продолжить обучение', vocabulary: 'Повторить слова', verbs: 'Повторить формы глаголов', learning_path: 'Упражнения с предложениями', connection: 'Соединение прервано. Твой выбор сохранён здесь.', conflict: 'Попытка изменилась. Загрузи сохранённые ответы.', auth: 'Войди в аккаунт снова.', invalid: 'Не удалось сохранить ответ. Загрузи попытку снова.', rate: 'Попробуй ещё раз чуть позже.', missing: 'Этот текст сейчас недоступен.' },
  uk: { title: 'Попередній тест', start: 'Почати тест', resume: 'Продовжити тест', open: 'До тексту для вимови', retry: 'Спробувати знову', next: 'Зберегти й продовжити', previous: 'Назад', submit: 'Перевірити відповіді', selected: 'Відповідь вибрано', saved: 'Відповіді збережено', working: 'Збереження …', loading: 'Завантаження …', passed: 'Тест пройдено', failed: 'Ще не пройдено', unavailable: 'Цей тест ще недоступний.', changed: 'Версія змінилася. Онови список текстів.', refresh: 'Оновити список текстів', instruction: 'Вибери одну відповідь. Результат з’явиться після надсилання.', help: 'Допомога', helpTitle: 'Тест до цього тексту', helpBody: 'Відповіді зберігаються під час переходу далі. Їх можна змінити до надсилання. Результат для цього тексту підтверджує лише сервер.', progress: 'Завдання {current} з {total}', score: 'Правильно: {correct} з {total}', unsaved: 'Вибір ще не збережено', learning: 'Продовжити навчання', vocabulary: 'Повторити слова', verbs: 'Повторити форми дієслів', learning_path: 'Вправи з реченнями', connection: 'З’єднання перервано. Твій вибір збережено тут.', conflict: 'Спроба змінилася. Завантаж збережені відповіді.', auth: 'Увійди в обліковий запис знову.', invalid: 'Не вдалося зберегти відповідь. Завантаж спробу знову.', rate: 'Спробуй знову трохи пізніше.', missing: 'Цей текст зараз недоступний.' },
  tr: { title: 'Ön test', start: 'Ön testi başlat', resume: 'Ön teste devam et', open: 'Konuşma metnini aç', retry: 'Tekrar dene', next: 'Kaydet ve devam et', previous: 'Geri', submit: 'Yanıtları kontrol et', selected: 'Yanıt seçildi', saved: 'Yanıtlar kaydedildi', working: 'Kaydediliyor …', loading: 'Yükleniyor …', passed: 'Ön test geçildi', failed: 'Henüz geçilmedi', unavailable: 'Bu ön test henüz kullanılamıyor.', changed: 'Sürüm değişti. Metin listesini yeniden yükle.', refresh: 'Metin listesini yeniden yükle', instruction: 'Bir yanıt seç. Sonucu gönderdikten sonra göreceksin.', help: 'Yardım', helpTitle: 'Bu metnin ön testi', helpBody: 'Devam ettiğinde yanıtların kaydedilir. Göndermeden önce değiştirebilirsin. Bu metnin sonucunu yalnızca sunucu onaylar.', progress: 'Soru {current} / {total}', score: '{total} sorudan {correct} doğru', unsaved: 'Seçim henüz kaydedilmedi', learning: 'Öğrenmeye devam et', vocabulary: 'Kelime çalış', verbs: 'Fiil biçimlerini çalış', learning_path: 'Cümle alıştırmaları', connection: 'Bağlantı kesildi. Seçimin burada korunuyor.', conflict: 'Bu deneme değişti. Kayıtlı yanıtlarını yeniden yükle.', auth: 'Lütfen tekrar giriş yap.', invalid: 'Yanıt kaydedilemedi. Denemeyi yeniden yükle.', rate: 'Lütfen biraz sonra tekrar dene.', missing: 'Bu metin şu anda kullanılamıyor.' },
} as const

export function sitovPronunciationPretestCopy(lang: string) { return sitovPretestCopy[toUiLocale(lang)] }
export function sitovPretestText(text: string, values: Record<string, number>) { return text.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? '')) }
export function sitovPretestErrorCopy(lang: string, error: SitovPronunciationPretestError) {
  const copy = sitovPronunciationPretestCopy(lang)
  switch (error) {
    case 'authentication_required': return copy.auth
    case 'version_conflict': return copy.changed
    case 'not_found': return copy.missing
    case 'authoring_not_ready': case 'test_required': return copy.unavailable
    case 'attempt_conflict': case 'request_conflict': return copy.conflict
    case 'rate_limited': return copy.rate
    case 'invalid_input': case 'invalid_answer': case 'incomplete_attempt': return copy.invalid
    default: return copy.connection
  }
}
