import { toUiLocale } from '@/lib/locale-routing'

const sitovCopy = {
  de: {
    title:'Konto zusätzlich sichern', description:'Schütze den Zugriff auf Schülerdaten mit einer Authenticator-App.', loading:'Sicherheitsstatus wird geladen …', setup:'Authenticator einrichten', setupHint:'Scanne den QR-Code mit deiner Authenticator-App. Alternativ kannst du diesen Schlüssel manuell eingeben.', qrAlt:'QR-Code zum Einrichten der Authenticator-App', secret:'Einrichtungsschlüssel', code:'Sechsstelliger Bestätigungscode', codeHint:'Gib den aktuellen Code aus deiner Authenticator-App ein.', verify:'Bestätigen und fortfahren', working:'Code wird geprüft …', failed:'Der Code konnte nicht bestätigt werden. Prüfe den aktuellen Code und versuche es erneut.', loadFailed:'Der Sicherheitsstatus konnte nicht geladen werden. Lade diese Seite erneut.', setupFailed:'Die Einrichtung ist derzeit nicht verfügbar. Bitte kontaktiere die Schulverwaltung.', factor:'Authenticator auswählen', protected:'Dein Konto ist durch die zweite Anmeldung geschützt.', continue:'Zur Verwaltung', cancel:'Einrichtung abbrechen', logout:'Abmelden', recovery:'Kein Zugriff auf deinen Authenticator? Kontaktiere die Schulverwaltung, damit dein Zugang geprüft und wiederhergestellt werden kann.', mandatory:'Für den Zugriff auf Schülerdaten ist die zweite Anmeldung erforderlich.', optional:'Nach der Bestätigung ist die zweite Anmeldung für dieses Konto bei jeder neuen Sitzung erforderlich.',
  },
  en: {
    title:'Add account protection', description:'Protect access to student data with an authenticator app.', loading:'Loading security status …', setup:'Set up authenticator', setupHint:'Scan the QR code with your authenticator app. You can also enter this key manually.', qrAlt:'QR code to set up your authenticator app', secret:'Setup key', code:'Six-digit verification code', codeHint:'Enter the current code from your authenticator app.', verify:'Verify and continue', working:'Verifying code …', failed:'The code could not be verified. Check the current code and try again.', loadFailed:'Security status could not be loaded. Reload this page.', setupFailed:'Setup is currently unavailable. Please contact the school administration.', factor:'Choose authenticator', protected:'Your account is protected by two-factor authentication.', continue:'Open administration', cancel:'Cancel setup', logout:'Sign out', recovery:'Cannot access your authenticator? Contact the school administration to verify and recover your access.', mandatory:'Two-factor authentication is required to access student data.', optional:'After verification, this account will require two-factor authentication in every new session.',
  },
  ru: {
    title:'Дополнительная защита аккаунта', description:'Защитите доступ к данным учеников с помощью приложения-аутентификатора.', loading:'Загружается статус защиты …', setup:'Настроить аутентификатор', setupHint:'Отсканируйте QR-код в приложении-аутентификаторе. Этот ключ также можно ввести вручную.', qrAlt:'QR-код для настройки аутентификатора', secret:'Ключ настройки', code:'Шестизначный код подтверждения', codeHint:'Введите текущий код из приложения-аутентификатора.', verify:'Подтвердить и продолжить', working:'Проверяем код …', failed:'Не удалось подтвердить код. Проверьте текущий код и повторите попытку.', loadFailed:'Не удалось загрузить статус защиты. Обновите страницу.', setupFailed:'Настройка сейчас недоступна. Обратитесь в администрацию школы.', factor:'Выберите аутентификатор', protected:'Ваш аккаунт защищён двухфакторной аутентификацией.', continue:'Перейти к управлению', cancel:'Отменить настройку', logout:'Выйти', recovery:'Нет доступа к аутентификатору? Обратитесь в администрацию школы для проверки и восстановления доступа.', mandatory:'Для доступа к данным учеников требуется двухфакторная аутентификация.', optional:'После подтверждения для каждого нового сеанса этого аккаунта потребуется двухфакторная аутентификация.',
  },
  uk: {
    title:'Додатковий захист облікового запису', description:'Захистіть доступ до даних учнів за допомогою застосунку-автентифікатора.', loading:'Завантаження стану захисту …', setup:'Налаштувати автентифікатор', setupHint:'Відскануйте QR-код у застосунку-автентифікаторі. Цей ключ також можна ввести вручну.', qrAlt:'QR-код для налаштування автентифікатора', secret:'Ключ налаштування', code:'Шестизначний код підтвердження', codeHint:'Введіть поточний код із застосунку-автентифікатора.', verify:'Підтвердити й продовжити', working:'Перевіряємо код …', failed:'Не вдалося підтвердити код. Перевірте поточний код і повторіть спробу.', loadFailed:'Не вдалося завантажити стан захисту. Оновіть сторінку.', setupFailed:'Налаштування наразі недоступне. Зверніться до адміністрації школи.', factor:'Виберіть автентифікатор', protected:'Ваш обліковий запис захищено двофакторною автентифікацією.', continue:'Перейти до керування', cancel:'Скасувати налаштування', logout:'Вийти', recovery:'Немає доступу до автентифікатора? Зверніться до адміністрації школи для перевірки та відновлення доступу.', mandatory:'Для доступу до даних учнів потрібна двофакторна автентифікація.', optional:'Після підтвердження кожен новий сеанс цього облікового запису потребуватиме двофакторної автентифікації.',
  },
  tr: {
    title:'Hesabınızı ek korumayla güvenceye alın', description:'Öğrenci verilerine erişimi bir kimlik doğrulama uygulamasıyla koruyun.', loading:'Güvenlik durumu yükleniyor …', setup:'Kimlik doğrulayıcı kur', setupHint:'QR kodunu kimlik doğrulama uygulamanızla tarayın. Bu anahtarı elle de girebilirsiniz.', qrAlt:'Kimlik doğrulama uygulamasını kurmak için QR kodu', secret:'Kurulum anahtarı', code:'Altı haneli doğrulama kodu', codeHint:'Kimlik doğrulama uygulamanızdaki güncel kodu girin.', verify:'Doğrula ve devam et', working:'Kod doğrulanıyor …', failed:'Kod doğrulanamadı. Güncel kodu kontrol edip yeniden deneyin.', loadFailed:'Güvenlik durumu yüklenemedi. Sayfayı yeniden yükleyin.', setupFailed:'Kurulum şu anda kullanılamıyor. Lütfen okul yönetimiyle iletişime geçin.', factor:'Kimlik doğrulayıcı seç', protected:'Hesabınız iki faktörlü kimlik doğrulamayla korunuyor.', continue:'Yönetime git', cancel:'Kurulumu iptal et', logout:'Çıkış yap', recovery:'Kimlik doğrulayıcınıza erişemiyor musunuz? Erişiminizi doğrulatmak ve kurtarmak için okul yönetimiyle iletişime geçin.', mandatory:'Öğrenci verilerine erişmek için iki faktörlü kimlik doğrulama gerekir.', optional:'Doğrulamadan sonra bu hesabın her yeni oturumunda iki faktörlü kimlik doğrulama gerekecektir.',
  },
}
export function sitovStaffMfaCopy(lang: string) { return sitovCopy[toUiLocale(lang)] }
export type SitovStaffMfaCopy = ReturnType<typeof sitovStaffMfaCopy>
