import { I, gap, mc, sb } from '../shared.mjs'

const PROTOKOLL = 'Aus dem Protokoll einer Betriebsversammlung: „Es nahmen rund hundertfünfzig Beschäftigte teil. Der Vorsitzende des Betriebsrats, Herr Demir, bezeichnete es als dringend notwendig, das Angebot an Fortbildungen auszubauen; es mangele vor allem an Kursen für erfahrene Kräfte. Die Geschäftsleitung begrüßte es, dass der Vorschlag so sachlich vorgetragen wurde, hielt ihn aber für vergleichsweise kostspielig. Es wurde lange darüber diskutiert, ob befristete Verträge künftig schneller entfristet werden können. Einig war man sich darin, dass es auf eine gründliche Einarbeitung ankommt. Die Stimmung war ausgesprochen konstruktiv, wenngleich einige Redner tief enttäuscht über die bisherigen Ergebnisse waren. Es bleibt abzuwarten, ob den Worten Taten folgen.“'
const SEHR = ['äußerst', 'überaus', 'höchst', 'ungemein', 'außerordentlich', 'ausgesprochen']

/** C1.1 · Pfad 4 · Meine Arbeitsstelle – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Vorgesetzter', I.choose, 'Wer ist der „Vorgesetzte“?', ['die Person, die einem im Betrieb Anweisungen geben darf', 'ein Kollege, der am selben Tag angefangen hat', 'der jüngste Mitarbeiter einer Abteilung'],
      ['Who is the “Vorgesetzte”?', 'Кто такой «Vorgesetzter»?', 'Хто такий «Vorgesetzter»?', '“Vorgesetzter” kimdir?']),
    mc('G1', 'ging es um', I.choose, 'In der Besprechung … um die Urlaubsplanung für den Sommer.', ['ging es', 'ging', 'es ging'],
      ['The meeting was about holiday planning for the summer.', 'На совещании речь шла о планировании отпусков на лето.', 'На нараді йшлося про планування відпусток на літо.', 'Toplantıda yaz için izin planlaması ele alındı.'], { h: 'nichtStreichen' }),
    mc('G2', 'Platzhalter fällt weg', I.choose, 'Es sind noch drei Plätze frei. = Noch …', ['sind drei Plätze frei.', 'sind es drei Plätze frei.', 'ist drei Plätze frei.'],
      ['There are still three places free.', 'Свободны ещё три места.', 'Вільні ще три місця.', 'Hâlâ üç yer boş.'], { h: 'vorfeld' }),
    mc('G3', 'Nebensatz vorn → kein es', I.choose, 'Es steht noch nicht fest, wer die Abteilung übernimmt. = Wer die Abteilung übernimmt, …', ['steht noch nicht fest.', 'steht es noch nicht fest.', 'es steht noch nicht fest.'],
      ['It has not yet been decided who will take over the department.', 'Пока не решено, кто возглавит отдел.', 'Поки що не вирішено, хто очолить відділ.', 'Bölümü kimin devralacağı henüz belli değil.'], { h: 'vorangestellt' }),
    mc('G4', 'es schätzen', I.choose, 'Der neue Kollege schätzt … sehr, dass ihm alle so geduldig helfen.', ['es', 'sich', 'ihn'],
      ['The new colleague greatly appreciates the fact that everyone helps him so patiently.', 'Новый коллега очень ценит то, что все так терпеливо ему помогают.', 'Новий колега дуже цінує те, що всі так терпляче йому допомагають.', 'Yeni çalışma arkadaşı herkesin ona bu kadar sabırla yardım etmesini çok takdir ediyor.'], { h: 'verben' }),
    mc('G5', 'das statt es auf Position 1', I.sentence, 'Welcher Satz ist richtig?', ['Das habe ich gestern erst erfahren.', 'Es habe ich gestern erst erfahren.', 'Gestern es habe ich erst erfahren.'],
      ['Which sentence is correct?', 'Какое предложение правильное?', 'Яке речення правильне?', 'Hangi cümle doğru?'], { h: 'vorfeld' }),
    mc('G6', 'Platzhalter erkennen', I.choose, 'Welche Funktion hat „es“? „Es bewarben sich auch viele Quereinsteiger.“', ['Platzhalter auf Position 1', 'Pronomen für ein Nomen im Neutrum', 'Korrelat zu einem Nebensatz'],
      ['What is the function of “es”? “Es bewarben sich auch viele Quereinsteiger.”', 'Какую функцию выполняет «es»? «Es bewarben sich auch viele Quereinsteiger.»', 'Яку функцію виконує «es»? «Es bewarben sich auch viele Quereinsteiger.»', '“es” hangi işlevi görüyor? “Es bewarben sich auch viele Quereinsteiger.”'], { h: 'test' }),
    mc('G7', 'grundfalsch', I.choose, 'Was bedeutet „grundfalsch“?', ['völlig falsch', 'im Grunde richtig', 'aus gutem Grund falsch'],
      ['What does “grundfalsch” mean?', 'Что означает «grundfalsch»?', 'Що означає «grundfalsch»?', '“grundfalsch” ne demek?'], { h: 'bedeutung' }),
    mc('G8', 'abschwächendes Wort', I.choose, 'Welches Wort schwächt ab?', ['einigermaßen', 'überaus', 'ungemein'],
      ['Which word weakens the adjective?', 'Какое слово ослабляет значение?', 'Яке слово послаблює значення?', 'Hangi sözcük anlamı zayıflatır?'], { h: 'schwach' }),
    mc('G9', 'optimal', I.choose, 'Welche Formulierung ist richtig?', ['die optimale Lösung', 'die optimalste Lösung', 'die sehr optimale Lösung'],
      ['Which wording is correct?', 'Какая формулировка правильная?', 'Яке формулювання правильне?', 'Hangi ifade doğru?'], { h: 'absolut' }),
    mc('Z1', 'Protokoll: Forderung', I.read, `${PROTOKOLL} Was bezeichnete Herr Demir als dringend notwendig?`, ['das Angebot an Fortbildungen auszubauen', 'befristete Verträge ganz abzuschaffen', 'die Betriebsversammlung zu verkürzen'],
      ['What did Mr Demir describe as urgently necessary?', 'Что господин Demir назвал крайне необходимым?', 'Що пан Demir назвав украй необхідним?', 'Bay Demir neyi acilen gerekli olarak nitelendirdi?']),
    gap('G3', 'es im Mittelfeld', I.word, 'Für uns ist ', ' selbstverständlich, dass Überstunden bezahlt werden.', 'es', ['sich', 'ihm'],
      ['For us it goes without saying that overtime is paid.', 'Для нас само собой разумеется, что сверхурочные оплачиваются.', 'Для нас само собою зрозуміло, що понаднормові оплачуються.', 'Fazla mesainin ödenmesi bizim için doğal bir şeydir.'], 'es / sich / ihm', { h: 'mittelfeld' }),
    sb('G4', 'es ablehnen + zu', I.order, 'Er / lehnt / es / ab, / am Wochenende / zu arbeiten.',
      ['He refuses to work at the weekend.', 'Он отказывается работать по выходным.', 'Він відмовляється працювати у вихідні.', 'Hafta sonu çalışmayı reddediyor.']),
  ],
  size: 13,
  test: [
    mc('W1', 'befristet', I.choose, 'Die Stelle ist zunächst auf ein Jahr …; danach wird über eine Verlängerung entschieden.', ['befristet', 'befreit', 'befragt'],
      ['The position is initially … to one year; after that a decision is made about an extension.', 'Должность пока … одним годом; затем будет решаться вопрос о продлении.', 'Посаду поки що … одним роком; потім вирішуватиметься питання про продовження.', 'Kadro şimdilik bir yılla …; sonra uzatılıp uzatılmayacağına karar verilecek.']),
    mc('W1', 'Belegschaft', I.choose, 'Was ist die „Belegschaft“?', ['alle Beschäftigten eines Betriebs', 'die Leitung eines Betriebs', 'die Kundschaft eines Betriebs'],
      ['What is the “Belegschaft”?', 'Что такое «Belegschaft»?', 'Що таке «Belegschaft»?', '“Belegschaft” nedir?']),
    gap('W1', 'Aufgabengebiet', I.word, 'Zu seinem ', ' gehören die Betreuung der Kunden und die Planung der Lieferungen.', 'Aufgabengebiet', ['Aufgabenblatt', 'Ausgabenplan'],
      ['His remit includes looking after customers and planning deliveries.', 'В круг его обязанностей входят работа с клиентами и планирование поставок.', 'До кола його обов’язків належать робота з клієнтами та планування поставок.', 'Görev alanına müşterilerle ilgilenmek ve teslimatları planlamak giriyor.'],
      ['area of responsibility, remit', 'круг обязанностей', 'коло обов’язків', 'görev alanı']),
    mc('G1', 'es kommt auf … an', I.choose, 'Was bedeutet: „Bei diesem Projekt kommt es auf Genauigkeit an.“?', ['Genauigkeit ist bei diesem Projekt entscheidend.', 'Genauigkeit kommt in diesem Projekt selten vor.', 'Das Projekt kommt ohne Genauigkeit aus.'],
      ['What does this mean: “Bei diesem Projekt kommt es auf Genauigkeit an.”?', 'Что означает: «Bei diesem Projekt kommt es auf Genauigkeit an.»?', 'Що означає: «Bei diesem Projekt kommt es auf Genauigkeit an.»?', 'Şu ne demek: “Bei diesem Projekt kommt es auf Genauigkeit an.”?'], { h: 'wendung' }),
    mc('G1', 'gibt es', I.sentence, 'Welcher Satz ist richtig?', ['Seit Montag gibt es in der Firma eine neue Regelung.', 'Seit Montag gibt in der Firma eine neue Regelung.', 'Seit Montag es gibt in der Firma eine neue Regelung.'],
      ['Which sentence is correct?', 'Какое предложение правильное?', 'Яке речення правильне?', 'Hangi cümle doğru?'], { h: 'nichtStreichen' }),
    gap('G1', 'es mangelt an', I.prep, 'Dem Team mangelt es ', ' Erfahrung mit internationalen Kunden.', 'an', ['auf', 'um'],
      ['The team lacks experience with international customers.', 'Команде не хватает опыта работы с международными клиентами.', 'Команді бракує досвіду роботи з міжнародними клієнтами.', 'Ekibin uluslararası müşterilerle deneyimi eksik.'], 'an / auf / um', { h: 'wendung' }),
    mc('G2', 'Verb im Plural', I.choose, 'Es … gestern drei neue Kollegen vorgestellt.', ['wurden', 'wurde', 'geworden'],
      ['Three new colleagues were introduced yesterday.', 'Вчера представили троих новых коллег.', 'Учора представили трьох нових колег.', 'Dün üç yeni çalışma arkadaşı tanıtıldı.'], { h: 'kongruenz' }),
    mc('G2', 'anderes Satzglied vorn', I.choose, 'Es herrscht große Unruhe in der Abteilung. = In der Abteilung …', ['herrscht große Unruhe.', 'herrscht es große Unruhe.', 'es herrscht große Unruhe.'],
      ['There is great unrest in the department.', 'В отделе царит большое беспокойство.', 'У відділі панує великий неспокій.', 'Bölümde büyük bir huzursuzluk var.'], { h: 'vorfeld' }),
    gap('G2', 'wird (ohne es)', I.form, 'Es wird in dieser Firma viel Wert auf Pünktlichkeit gelegt. = In dieser Firma ', ' viel Wert auf Pünktlichkeit gelegt.', 'wird', ['wird es', 'es wird'],
      ['Great importance is attached to punctuality in this company.', 'В этой фирме придают большое значение пунктуальности.', 'У цій фірмі надають великого значення пунктуальності.', 'Bu şirkette dakikliğe büyük önem verilir.'], 'wird / wird es / es wird', { h: 'passiv' }),
    mc('G3', 'Funktion erkennen', I.choose, 'Welche Funktion hat „es“? „Es ist nicht üblich, Kollegen ohne Termin zu stören.“', ['Es weist auf den Infinitivsatz voraus.', 'Es steht für ein Nomen im Neutrum.', 'Es gehört fest zum Verb wie in „es schneit“.'],
      ['What is the function of “es”? “Es ist nicht üblich, Kollegen ohne Termin zu stören.”', 'Какую функцию выполняет «es»? «Es ist nicht üblich, Kollegen ohne Termin zu stören.»', 'Яку функцію виконує «es»? «Es ist nicht üblich, Kollegen ohne Termin zu stören.»', '“es” hangi işlevi görüyor? “Es ist nicht üblich, Kollegen ohne Termin zu stören.”'], { h: 'ausdruecke' }),
    mc('G3', 'dass-Satz nach hinten', I.choose, 'Dass die Löhne steigen, ist erfreulich. = …', ['Es ist erfreulich, dass die Löhne steigen.', 'Es ist es erfreulich, dass die Löhne steigen.', 'Erfreulich es ist, dass die Löhne steigen.'],
      ['It is pleasing that wages are rising.', 'Радует, что зарплаты растут.', 'Тішить, що зарплати зростають.', 'Ücretlerin artması sevindirici.'], { h: 'vorangestellt' }),
    gap('G3', 'Mich ärgert es', I.word, 'Mich ärgert ', ', dass meine Vorschläge nie beachtet werden.', 'es', ['sich', 'mich'],
      ['It annoys me that my suggestions are never taken into account.', 'Меня раздражает, что мои предложения никогда не учитывают.', 'Мене дратує, що моїх пропозицій ніколи не враховують.', 'Önerilerimin hiç dikkate alınmaması beni kızdırıyor.'], 'es / sich / mich', { h: 'mittelfeld' }),
    mc('G4', 'es sich leisten können', I.choose, 'Die Firma kann … sich nicht leisten, erfahrene Kräfte zu verlieren.', ['es', 'das es', 'ihn'],
      ['The company cannot afford to lose experienced staff.', 'Фирма не может позволить себе терять опытных работников.', 'Фірма не може дозволити собі втрачати досвідчених працівників.', 'Şirket deneyimli çalışanlarını kaybetmeyi göze alamaz.'], { h: 'verben' }),
    mc('G4', 'glauben ohne es', I.choose, 'Welcher Satz ist ohne „es“ korrekt?', ['Ich glaube, dass er die Stelle bekommt.', 'Ich halte für sicher, dass er die Stelle bekommt.', 'Ich finde schön, dass er die Stelle bekommt.'],
      ['Which sentence is correct without “es”?', 'Какое предложение правильно без «es»?', 'Яке речення правильне без «es»?', 'Hangi cümle “es” olmadan doğrudur?'], { h: 'ohne' }),
    gap('G4', 'es für unnötig halten', I.word, 'Der Vorgesetzte hält ', ' für unnötig, jede Entscheidung schriftlich zu begründen.', 'es', ['sich', 'ihn'],
      ['The superior considers it unnecessary to justify every decision in writing.', 'Начальник считает излишним письменно обосновывать каждое решение.', 'Керівник вважає зайвим письмово обґрунтовувати кожне рішення.', 'Amir her kararı yazılı olarak gerekçelendirmeyi gereksiz buluyor.'], 'es / sich / ihn', { h: 'verben' }),
    mc('G5', 'es für ein Adjektiv', I.choose, 'Worauf bezieht sich „es“? „Mein Kollege ist sehr hilfsbereit. Der neue Praktikant ist es leider nicht.“', ['auf „hilfsbereit“', 'auf „mein Kollege“', 'auf „der neue Praktikant“'],
      ['What does “es” refer to? “Mein Kollege ist sehr hilfsbereit. Der neue Praktikant ist es leider nicht.”', 'К чему относится «es»? «Mein Kollege ist sehr hilfsbereit. Der neue Praktikant ist es leider nicht.»', 'Чого стосується «es»? «Mein Kollege ist sehr hilfsbereit. Der neue Praktikant ist es leider nicht.»', '“es” neye gönderme yapıyor? “Mein Kollege ist sehr hilfsbereit. Der neue Praktikant ist es leider nicht.”'], { h: 'bezug' }),
    mc('G5', 'davon', I.choose, 'Die Regelung ist ganz neu. Viele Kollegen haben noch nichts … gehört.', ['davon', 'von es', 'es davon'],
      ['The regulation is completely new. Many colleagues have not heard anything about it yet.', 'Правило совсем новое. Многие коллеги ещё ничего о нём не слышали.', 'Правило зовсім нове. Багато колег ще нічого про нього не чули.', 'Düzenleme çok yeni. Birçok çalışma arkadaşı bundan henüz haberdar değil.'], { h: 'praep' }),
    gap('G5', 'ihn (der Vertrag)', I.pronoun, 'Der Vertrag liegt bereit. Bitte unterschreiben Sie ', ' bis Freitag.', 'ihn', ['es', 'sie'],
      ['The contract is ready. Please sign it by Friday.', 'Договор готов. Пожалуйста, подпишите его до пятницы.', 'Договір готовий. Будь ласка, підпишіть його до п’ятниці.', 'Sözleşme hazır. Lütfen cumaya kadar imzalayın.'], 'es / ihn / sie', { h: 'bezug' }),
    mc('G6', 'nicht streichbar', I.choose, 'In welchem Satz bleibt „es“ auch dann erhalten, wenn man den Satz umstellt?', ['Es handelt sich um einen Fehler in der Abrechnung.', 'Es wurde ein Fehler in der Abrechnung gefunden.', 'Es sind mehrere Fehler in der Abrechnung aufgefallen.'],
      ['In which sentence does “es” remain even when you rearrange the sentence?', 'В каком предложении «es» сохраняется, даже если изменить порядок слов?', 'У якому реченні «es» зберігається, навіть якщо змінити порядок слів?', 'Hangi cümlede, cümle yeniden düzenlense bile “es” kalır?'], { h: 'test' }),
    mc('G6', 'Umstellung', I.choose, 'Es fanden mehrere Gespräche statt. → In der letzten Woche …', ['fanden mehrere Gespräche statt.', 'fanden es mehrere Gespräche statt.', 'es fanden mehrere Gespräche statt.'],
      ['Several talks took place. → Several talks took place last week.', 'Состоялось несколько бесед. → На прошлой неделе состоялось несколько бесед.', 'Відбулося кілька розмов. → Минулого тижня відбулося кілька розмов.', 'Birkaç görüşme yapıldı. → Geçen hafta birkaç görüşme yapıldı.'], { h: 'test' }),
    mc('G7', 'todlangweilig', I.choose, 'Die Präsentation dauerte drei Stunden und war …', ['todlangweilig', 'brandlangweilig', 'hochlangweilig'],
      ['The presentation lasted three hours and was …', 'Презентация длилась три часа и была …', 'Презентація тривала три години й була …', 'Sunum üç saat sürdü ve …'], { h: 'fest' }),
    mc('G7', 'blitzschnell', I.choose, 'Was bedeutet „blitzschnell“?', ['sehr schnell', 'nur bei Gewitter schnell', 'schneller als erlaubt'],
      ['What does “blitzschnell” mean?', 'Что означает «blitzschnell»?', 'Що означає «blitzschnell»?', '“blitzschnell” ne demek?'], { h: 'bedeutung' }),
    gap('G7', 'hochmotivierte Bewerber', I.ending, 'Für die neue Abteilung suchen wir ', ' Bewerber mit Auslandserfahrung.', 'hochmotivierte', ['hochmotiviert', 'hochmotivierter'],
      ['For the new department we are looking for highly motivated applicants with experience abroad.', 'Для нового отдела мы ищем высокомотивированных соискателей с опытом работы за рубежом.', 'Для нового відділу ми шукаємо високомотивованих кандидатів із досвідом роботи за кордоном.', 'Yeni bölüm için yurt dışı deneyimi olan çok istekli adaylar arıyoruz.'], 'hochmotiviert', { h: 'schreibung' }),
    mc('G8', 'Register: Geschäftsbericht', I.choose, 'Welche Formulierung passt in einen Geschäftsbericht?', ['Das vergangene Jahr war außerordentlich erfolgreich.', 'Das vergangene Jahr war wahnsinnig erfolgreich.', 'Das vergangene Jahr war irre erfolgreich.'],
      ['Which wording fits in an annual report?', 'Какая формулировка подходит для годового отчёта?', 'Яке формулювання підходить для річного звіту?', 'Hangi ifade bir faaliyet raporuna uyar?'], { h: 'register' }),
    mc('G8', 'einigermaßen', I.choose, 'Was bedeutet: „Ich bin mit dem Ergebnis einigermaßen zufrieden.“?', ['Ich bin mittelmäßig zufrieden.', 'Ich bin begeistert.', 'Ich bin überhaupt nicht zufrieden.'],
      ['What does this mean: “Ich bin mit dem Ergebnis einigermaßen zufrieden.”?', 'Что означает: «Ich bin mit dem Ergebnis einigermaßen zufrieden.»?', 'Що означає: «Ich bin mit dem Ergebnis einigermaßen zufrieden.»?', 'Şu ne demek: “Ich bin mit dem Ergebnis einigermaßen zufrieden.”?'], { h: 'schwach' }),
    gap('G8', 'äußerst schwierig', I.adverb, 'Die Verhandlungen waren ', ' schwierig und zogen sich über Monate hin.', SEHR, ['äußerste', 'äußersten'],
      ['The negotiations were extremely difficult and dragged on for months.', 'Переговоры были крайне трудными и тянулись месяцами.', 'Переговори були вкрай важкими й тяглися місяцями.', 'Görüşmeler son derece zordu ve aylarca sürdü.'], 'äußerst / äußerste / äußersten', { h: 'stellung' }),
    mc('G9', 'keine doppelte Verstärkung', I.choose, 'Welche Formulierung ist richtig?', ['ein uraltes Gebäude', 'ein sehr uraltes Gebäude', 'ein uralteres Gebäude'],
      ['Which wording is correct?', 'Какая формулировка правильная?', 'Яке формулювання правильне?', 'Hangi ifade doğru?'], { h: 'doppelt' }),
    mc('G9', 'verstärken oder vergleichen', I.choose, 'Was ist der Unterschied? „Er ist äußerst zuverlässig.“ – „Er ist am zuverlässigsten.“', ['Der erste Satz verstärkt, der zweite vergleicht ihn mit anderen.', 'Beide Sätze vergleichen ihn mit anderen.', 'Der zweite Satz ist nur höflicher als der erste.'],
      ['What is the difference? “Er ist äußerst zuverlässig.” – “Er ist am zuverlässigsten.”', 'В чём разница? «Er ist äußerst zuverlässig.» – «Er ist am zuverlässigsten.»', 'У чому різниця? «Er ist äußerst zuverlässig.» – «Er ist am zuverlässigsten.»', 'Fark nedir? “Er ist äußerst zuverlässig.” – “Er ist am zuverlässigsten.”'], { h: 'komparation' }),
    mc('Z1', 'Protokoll: Mangel', I.read, `${PROTOKOLL} Woran mangelt es nach Herrn Demir vor allem?`, ['an Kursen für erfahrene Kräfte', 'an befristeten Verträgen', 'an Rednern auf der Versammlung'],
      ['According to Mr Demir, what is lacking above all?', 'Чего, по словам господина Demir, не хватает прежде всего?', 'Чого, за словами пана Demir, бракує насамперед?', 'Bay Demir’e göre en çok ne eksik?']),
    mc('Z1', 'Protokoll: Haltung der Geschäftsleitung', I.read, `${PROTOKOLL} Wie beurteilte die Geschäftsleitung den Vorschlag?`, ['Sie begrüßte den sachlichen Vortrag, hielt den Vorschlag aber für recht teuer.', 'Sie lehnte ihn ab, ohne auf den Vortrag überhaupt einzugehen.', 'Sie nahm ihn sofort an und sagte die nötigen Mittel zu.'],
      ['How did the management judge the proposal?', 'Как руководство оценило это предложение?', 'Як керівництво оцінило цю пропозицію?', 'Yönetim öneriyi nasıl değerlendirdi?']),
  ],
}

export default check
