'use client'
import {useState,useTransition,type ReactNode} from 'react'
import {useRouter} from 'next/navigation'
import {Plus,Pencil,Archive,CalendarDays,Loader2} from 'lucide-react'
import AdminDialog from './AdminDialog'
import {courseCmsCopy} from '@/lib/course-cms-i18n'
import {courseEditorSchema,type CourseEditor} from '@/lib/business-courses'
import {saveCourse} from '@/app/actions/course-cms'
const control='min-h-12 w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-base text-[var(--foreground)] focus-visible:outline-2 focus-visible:outline-[var(--accent)]'
const button='inline-flex min-h-12 min-w-12 items-center justify-center gap-2 rounded-xl border border-[var(--border)] px-4 py-2 font-semibold disabled:opacity-50'
const fresh=():CourseEditor=>({slug:`course-${crypto.randomUUID().slice(0,8)}`,title:'',description:'',type:'presence',category:'german',level:'',price:0,unit_duration:45,instructor:'standard',start_date:'',end_date:'',trial_lessons:true,sort_order:110,archived:false,schedules:[],translations:[],exceptions:[]})
function Field({label,children}:{label:string;children:ReactNode}){return <label className="grid min-w-0 gap-2 text-base"><span className="font-semibold">{label}</span>{children}</label>}
export default function CourseCMS({initial,lang,failed}:{initial:CourseEditor[];lang:string;failed:boolean}){
 const t=courseCmsCopy(lang),router=useRouter()
 const [editor,setEditor]=useState<CourseEditor|null>(null),[showArchived,setShowArchived]=useState(false)
 const [error,setError]=useState(false),[saving,startTransition]=useTransition()
 const set=<K extends keyof CourseEditor>(key:K,value:CourseEditor[K])=>setEditor(current=>current?{...current,[key]:value}:null)
 function save(){if(!editor||saving)return;setError(false);const parsed=courseEditorSchema.safeParse(editor);if(!parsed.success){setError(true);return}
 startTransition(async()=>{try{const result=await saveCourse(parsed.data);if(!result.success)throw new Error('save_failed');setEditor(null);router.refresh()}catch{setError(true)}})}
 const weekday=(day:number)=>new Intl.DateTimeFormat(lang,{weekday:'long',timeZone:'UTC'}).format(new Date(Date.UTC(2024,0,day)))
 return <div className="mx-auto max-w-6xl space-y-6 text-[var(--foreground)]">
  <header className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><h1 className="text-3xl font-bold">{t.title}</h1><p className="mt-3 max-w-3xl text-lg leading-relaxed text-[var(--muted)]">{t.intro}</p><button className={`${button} mt-5 bg-[var(--accent)] text-[var(--accent-foreground)]`} onClick={()=>{setError(false);setEditor(fresh())}}><Plus size={20}/>{t.add}</button></header>
  <label className="flex min-h-12 items-center gap-3"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)} className="h-6 w-6 accent-[var(--accent)]"/>{t.showArchived}</label>
  {failed?<p role="alert">{t.failed} <button onClick={()=>router.refresh()} className={button}>{t.reload}</button></p>:initial.filter(c=>showArchived||!c.archived).length===0?<p className="rounded-2xl border border-dashed border-[var(--border)] p-8">{t.empty}</p>:<div className="grid gap-4 md:grid-cols-2">{initial.filter(c=>showArchived||!c.archived).map(course=><article key={course.id} className="flex flex-col gap-4 rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-[var(--violet)]">{course.level} · {t[course.type]}</p><h2 className="mt-2 text-xl font-bold">{course.title}</h2></div>{course.archived&&<span className="flex items-center gap-2 text-[var(--muted)]"><Archive size={18}/>{t.archived}</span>}</div><p className="text-[var(--muted)]">{new Intl.NumberFormat(lang,{style:'currency',currency:'EUR'}).format(course.price)} / {course.unit_duration} min</p><ul className="space-y-2">{course.schedules.map((s,i)=><li className="flex items-center gap-2" key={i}><CalendarDays size={18}/>{weekday(s.weekday)} {s.start_time}–{s.end_time}</li>)}</ul>{!course.schedules.length&&<p>{t.noTimes}</p>}<button className={`${button} mt-auto self-start`} onClick={()=>{setError(false);setEditor(structuredClone(course))}}><Pencil size={18}/>{t.edit}</button></article>)}</div>}
  {editor&&<AdminDialog title={editor.id?t.edit:t.add} subtitle={editor.title} onClose={()=>setEditor(null)} dismissible={!saving}>
   <form onSubmit={e=>{e.preventDefault();save()}} className="flex min-h-0 flex-1 flex-col">
    <div className="min-h-0 flex-1 space-y-6 overflow-y-auto overscroll-contain p-5 sm:p-6" data-lenis-prevent>
     <fieldset disabled={saving} className="grid gap-4 sm:grid-cols-2">
      <Field label={t.name}><input required className={control} value={editor.title} maxLength={180} onChange={e=>set('title',e.target.value)}/></Field>
      <Field label={t.slug}><input required className={control} value={editor.slug} pattern="[a-z0-9][a-z0-9_-]{1,99}" onChange={e=>set('slug',e.target.value)}/></Field>
      <Field label={t.type}><select className={control} value={editor.type} onChange={e=>set('type',e.target.value==='online'?'online':'presence')}><option value="presence">{t.presence}</option><option value="online">{t.online}</option></select></Field>
      <Field label={t.category}><select className={control} value={editor.category} onChange={e=>set('category',e.target.value as CourseEditor['category'])}>{(['german','speaking','online','private'] as const).map(value=><option key={value} value={value}>{t[value]}</option>)}</select></Field>
      <Field label={t.level}><input className={control} value={editor.level} maxLength={30} onChange={e=>set('level',e.target.value)}/></Field>
      <Field label={t.order}><input required className={control} type="number" min={0} value={editor.sort_order} onChange={e=>set('sort_order',Number(e.target.value))}/></Field>
      <Field label={t.price}><input required className={control} type="number" min={0} step="0.01" value={editor.price} onChange={e=>set('price',Number(e.target.value))}/></Field>
      <Field label={t.minutes}><input required className={control} type="number" min={15} max={180} value={editor.unit_duration} onChange={e=>set('unit_duration',Number(e.target.value))}/></Field>
      <Field label={t.start}><input className={control} type="date" value={editor.start_date} onChange={e=>set('start_date',e.target.value)}/></Field>
      <Field label={t.end}><input className={control} type="date" value={editor.end_date} min={editor.start_date} onChange={e=>set('end_date',e.target.value)}/></Field>
      <div className="sm:col-span-2"><Field label={t.description}><textarea className={control} rows={4} maxLength={3000} value={editor.description} onChange={e=>set('description',e.target.value)}/></Field></div>
      <label className="flex min-h-12 items-center gap-3"><input type="checkbox" className="h-6 w-6" checked={editor.trial_lessons} onChange={e=>set('trial_lessons',e.target.checked)}/>{t.trial}</label>
      <label className="flex min-h-12 items-center gap-3"><input type="checkbox" className="h-6 w-6" checked={editor.archived} onChange={e=>set('archived',e.target.checked)}/>{t.archive}</label><p className="text-[var(--muted)] sm:col-span-2">{t.archiveHint}</p>
     </fieldset>
     <section className="space-y-4"><h3 className="text-xl font-bold">{t.schedules}</h3>{editor.schedules.map((s,index)=><div key={index} className="grid gap-3 rounded-2xl border border-[var(--border)] p-4 sm:grid-cols-2">
      <Field label={t.weekday}><select className={control} value={s.weekday} onChange={e=>set('schedules',editor.schedules.map((item,i)=>i===index?{...item,weekday:Number(e.target.value)}:item))}>{[1,2,3,4,5,6,7].map(day=><option key={day} value={day}>{weekday(day)}</option>)}</select></Field>
      <div className="grid grid-cols-2 gap-3">{(['start_time','end_time'] as const).map(key=><Field key={key} label={key==='start_time'?t.from:t.until}><input required type="time" className={control} value={s[key]} onChange={e=>set('schedules',editor.schedules.map((item,i)=>i===index?{...item,[key]:e.target.value}:item))}/></Field>)}</div>
      <button type="button" className={`${button} justify-self-start`} onClick={()=>set('schedules',editor.schedules.filter((_,i)=>i!==index))}>{t.remove}</button>
     </div>)}<button type="button" className={button} onClick={()=>set('schedules',[...editor.schedules,{weekday:1,start_time:'09:00',end_time:'10:30',alternate_start_time:'',alternate_end_time:''}])}><Plus size={18}/>{t.addTime}</button></section>
     <section className="space-y-4"><h3 className="text-xl font-bold">{t.translations}</h3><p className="text-[var(--muted)]">{t.translationHint}</p>{(['en','ru','uk','tr'] as const).map(locale=>{const translation=editor.translations.find(item=>item.locale===locale)??{locale,title:'',description:''};const change=(field:'title'|'description',value:string)=>{const next={...translation,[field]:value};set('translations',[...editor.translations.filter(item=>item.locale!==locale),...(next.title?[next]:[])])};return <details key={locale} className="rounded-2xl border border-[var(--border)] px-4"><summary className="flex min-h-12 cursor-pointer items-center font-semibold">{new Intl.DisplayNames(lang,{type:'language'}).of(locale)}</summary><div className="space-y-3 pb-4"><Field label={`${t.name} (${new Intl.DisplayNames(lang,{type:'language'}).of(locale)})`}><input className={control} value={translation.title} onChange={e=>change('title',e.target.value)}/></Field><Field label={`${t.description} (${new Intl.DisplayNames(lang,{type:'language'}).of(locale)})`}><textarea className={control} rows={3} value={translation.description} onChange={e=>change('description',e.target.value)}/></Field></div></details>})}</section>
     <section className="space-y-4"><h3 className="text-xl font-bold">{t.exceptions}</h3>{editor.exceptions.map((exception,index)=><div key={index} className="grid gap-3 rounded-2xl border border-[var(--border)] p-4 sm:grid-cols-2"><Field label={t.date}><input required type="date" className={control} value={exception.date} onChange={e=>set('exceptions',editor.exceptions.map((item,i)=>i===index?{...item,date:e.target.value}:item))}/></Field><Field label={t.reason}><input required className={control} value={exception.reason} onChange={e=>set('exceptions',editor.exceptions.map((item,i)=>i===index?{...item,reason:e.target.value}:item))}/></Field><button type="button" className={`${button} justify-self-start`} onClick={()=>set('exceptions',editor.exceptions.filter((_,i)=>i!==index))}>{t.remove}</button></div>)}<button type="button" className={button} onClick={()=>set('exceptions',[...editor.exceptions,{date:'',reason:''}])}><Plus size={18}/>{t.addException}</button></section>
    </div>
    <footer className="shrink-0 space-y-3 border-t border-[var(--border)] p-5">{error&&<p role="alert" className="text-red-700 dark:text-red-300">{t.error}</p>}<div className="flex justify-end gap-3"><button type="button" disabled={saving} className={button} onClick={()=>setEditor(null)}>{t.cancel}</button><button type="submit" disabled={saving} className={`${button} bg-[var(--accent)] text-[var(--accent-foreground)]`}>{saving&&<Loader2 className="animate-spin" size={18}/>}{saving?t.saving:t.save}</button></div></footer>
   </form>
  </AdminDialog>}
 </div>
}
