import Link from 'next/link'
import type { ReactNode } from 'react'
import type { TeacherDetailData } from '@/lib/teacher-dashboard-contract'
import { teacherDistribution } from '@/lib/teacher-dashboard-contract'
import { teacherDashboardT } from '@/lib/teacher-dashboard-i18n'
import type { VocabularyTranslations } from '@/lib/vocabulary-i18n'
import PhaseDistributionChart from '@/components/vocabulary/PhaseDistributionChart'
import { displayDate, studyTime, dashboardPanel as panel } from './TeacherDashboardShared'
import { Badge, StatTile, adminButton } from './ui'

function Section({ title, children }: { title: string; children: ReactNode }) {
  return <section className={panel}><h2 className="mb-4 text-sm font-semibold">{title}</h2>{children}</section>
}
export function TeacherStudentVocabulary({ data, lang, translations }: { data: TeacherDetailData['vocabulary']; lang: string; translations: VocabularyTranslations }) {
  const t = teacherDashboardT(lang)
  return <div className="space-y-5">
    <p className={`${panel} text-sm text-[var(--muted)]`}>{t('privateWords', { count: data.ownWordCount })}</p>
    <Section title={t('byLevel')}><div className="grid gap-5 lg:grid-cols-2">{data.byLevel.map(item => <div key={item.level} className="rounded-lg border border-[var(--admin-line)] p-4"><h3 className="mb-3 text-sm font-semibold">{item.level}</h3><PhaseDistributionChart distribution={teacherDistribution(item.phases, item.totalCards)} translations={translations} /></div>)}</div>{!data.byLevel.length && <p>{t('empty')}</p>}</Section>
    <Section title={t('byLesson')}><div className="space-y-2">{data.byLesson.map(item => <details key={item.id} className="rounded-lg border border-[var(--admin-line)]"><summary className="flex min-h-12 cursor-pointer items-center px-4 text-sm font-medium">{item.level} · {item.title}</summary><div className="p-4"><PhaseDistributionChart distribution={teacherDistribution(item.phases, item.totalCards)} translations={translations} /></div></details>)}</div>{!data.byLesson.length && <p>{t('empty')}</p>}</Section>
    <div className="grid items-start gap-5 lg:grid-cols-2"><Section title={t('halfKnown')}>{data.halfKnown.length ? <ul className="space-y-2 text-sm">{data.halfKnown.map(item => <li key={item.id} className="break-words"><strong>{item.word}</strong> · {item.level} · {item.boxes.map(phase => t('phase', { phase })).join(' / ')}</li>)}</ul> : <p>{t('empty')}</p>}</Section><Section title={t('hardest')}>{data.hardest.length ? <ol className="space-y-2 text-sm">{data.hardest.map(item => <li key={item.id} className="break-words"><strong>{item.word}</strong> · {item.level} · {item.regressions}</li>)}</ol> : <p>{t('empty')}</p>}</Section></div>
    <Section title={t('recentAnswers')}>{data.recentAnswers.length ? <ol className="divide-y divide-[var(--admin-line)]">{data.recentAnswers.map(item => <li key={item.id} className="flex min-w-0 flex-wrap items-start justify-between gap-x-4 gap-y-1 break-words py-2.5 text-sm first:pt-0 last:pb-0"><div className="min-w-0"><p className="font-semibold">{item.word} <span className="font-normal text-[var(--muted)]">· {item.level}</span></p><p className="mt-0.5 text-[var(--muted)]">{t('answer')}: {item.typedAnswer ?? '—'}</p></div><div className="flex shrink-0 flex-col items-end gap-1"><Badge tone={item.correct ? 'success' : 'warning'}>{t(item.correct ? 'correct' : 'incorrect')}</Badge><span className="text-xs tabular-nums text-[var(--muted)]">{displayDate(item.createdAt, lang)}</span></div></li>)}</ol> : <p>{t('empty')}</p>}</Section>
    <div className="grid gap-5 lg:grid-cols-2"><Section title={t('paused')}>{data.pausedLessons.length ? <ul className="space-y-2 text-sm">{data.pausedLessons.map(item => <li key={item.id}>{item.level} · {item.title}</li>)}</ul> : <p>{t('empty')}</p>}</Section><Section title={t('carryover')}>{data.carryover.length ? <ul className="space-y-2 text-sm">{data.carryover.map(item => <li key={item.level}><strong>{item.level}</strong> · {t(item.enabled ? 'enabled' : 'disabled')} · {item.count}</li>)}</ul> : <p>{t('empty')}</p>}</Section></div>
  </div>
}
export function TeacherStudentPronunciation({ data, lang }: { data: TeacherDetailData['pronunciation']; lang: string }) {
  const t = teacherDashboardT(lang)
  return <div className="space-y-5"><div className="grid grid-cols-2 gap-3"><StatTile label={t('openRecordings')} value={data.conversations.filter(item => item.status === 'pending').length} /><StatTile label={t('unanswered')} value={data.conversations.reduce((sum, item) => sum + item.unansweredCount, 0)} /></div><Section title={t('pronunciation')}>{!data.conversations.length ? <p>{t('empty')}</p> : <ul className="divide-y divide-[var(--admin-line)]">{data.conversations.map(item => <li key={item.id} className="flex flex-col gap-3 py-3 first:pt-0 last:pb-0 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0 text-sm"><p className="font-semibold tabular-nums">{displayDate(item.lastMessageAt ?? item.createdAt, lang)}</p><p className="mt-0.5 text-[var(--muted)]">{t('messages')}: {item.messageCount} · {t('unanswered')}: {item.unansweredCount}</p><Badge tone={item.status === 'pending' ? 'accent' : 'success'} className="mt-1.5">{t(item.status === 'pending' ? 'in_progress' : 'completed')}</Badge></div><Link className={adminButton('secondary', 'sm', 'w-full sm:w-auto')} href={`/${lang}/admin/submissions?conversation=${item.id}`}>{t('openConversation')}</Link></li>)}</ul>}</Section></div>
}
export function TeacherStudentActivity({ data, lang }: { data: TeacherDetailData['activity']; lang: string }) {
  const t = teacherDashboardT(lang)
  const maximum = Math.max(1, ...data.days.map(day => day.seconds))
  return <div className="space-y-5"><p className={`${panel} text-sm text-[var(--muted)]`}>{t('timeHint')}</p><Section title={t('calendar')}><ul className="grid grid-cols-5 gap-2 sm:grid-cols-7">{data.days.map(day => <li key={day.date} className="min-w-0 rounded-md border border-[var(--admin-line)] p-1.5 text-center" style={{ background: day.active ? `color-mix(in srgb, var(--success) ${Math.round(10 + day.seconds / maximum * 20)}%, var(--surface))` : 'var(--surface-muted)' }}><time dateTime={day.date} className="block text-xs font-semibold">{new Date(`${day.date}T12:00:00Z`).toLocaleDateString(lang, { day: 'numeric', month: 'short' })}</time><span className="mt-0.5 block text-xs tabular-nums">{studyTime(day.seconds, lang)}</span><span className="sr-only">{t('answers')}: {day.answers}</span></li>)}</ul></Section>
    <Section title={t('modes')}><dl className="grid grid-cols-2 gap-3 sm:grid-cols-4">{data.byMode.map(item => <div key={item.mode} className="rounded-lg bg-[var(--surface-muted)] p-3"><dt className="text-xs text-[var(--muted)]">{t(item.mode === 'exercises' || item.mode === 'exercise' || item.mode === 'path' ? 'path' : item.mode === 'pronunciation' ? 'pronunciation' : item.mode === 'videos' || item.mode === 'media' ? 'media' : 'vocabulary')}</dt><dd className="mt-1 text-lg font-semibold tabular-nums">{studyTime(item.seconds, lang)}</dd></div>)}</dl>{!data.byMode.length && <p>{t('empty')}</p>}</Section>
    <Section title={t('history')}><table className="w-full table-fixed text-left text-sm"><thead><tr><th scope="col" className="pb-2 text-xs font-semibold text-[var(--muted)]">{t('date')}</th><th scope="col" className="pb-2 text-xs font-semibold text-[var(--muted)]">{t('time30')}</th><th scope="col" className="pb-2 text-xs font-semibold text-[var(--muted)]">{t('answers')}</th></tr></thead><tbody>{data.days.map(day => <tr key={day.date} className="border-t border-[var(--admin-line)]"><th scope="row" className="py-2 font-normal tabular-nums">{new Date(`${day.date}T12:00:00Z`).toLocaleDateString(lang)}</th><td className="py-2"><span className="block tabular-nums">{studyTime(day.seconds, lang)}</span><span aria-hidden="true" className="mt-2 block h-2 rounded-full bg-[var(--success)]" style={{ width: `${day.seconds / maximum * 100}%` }} /></td><td className="py-2 tabular-nums">{day.answers}</td></tr>)}</tbody></table></Section>
  </div>
}
