import {
  BarChart3,
  BookOpen,
  CalendarClock,
  CalendarRange,
  CalendarX2,
  CreditCard,
  ClipboardList,
  ClipboardCheck,
  FileBadge,
  FileUp,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  LibraryBig,
  type LucideIcon,
  MessageSquareText,
  Mic,
  Receipt,
  Route,
  UserPlus,
  Users,
} from 'lucide-react'
import type { AdminNavIcon } from '@/lib/admin-navigation'

/** Einheitliche Symbole für Seitenleiste, Unterreiter, Tab-Leiste und Übersicht. */
export const ADMIN_NAV_ICONS: Record<AdminNavIcon, LucideIcon> = {
  overview: LayoutDashboard,
  newStudents: UserPlus,
  students: Users,
  corrections: MessageSquareText,
  examSimulation: ClipboardCheck,
  analytics: BarChart3,
  courses: BookOpen,
  cancellations: CalendarX2,
  vocabulary: Languages,
  path: Route,
  media: LibraryBig,
  pronunciation: Mic,
  finance: CalendarRange,
  registrations: ClipboardList,
  invoices: Receipt,
  bookings: CalendarClock,
  certificates: FileBadge,
  imports: FileUp,
  sitovBilling: CreditCard,
  menu: LayoutGrid,
}
