import json

data = [
{"idx":0,"id":"007000bc-30f5-4373-b388-77a7cae0b268","lesson":"Lektion 4","word_de":"Bett","article":"das","plural":"Betten","translation_ru":"кровать","translation_tr":"yatak","translation_en":"bed","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:43:46.573139+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Das Bett steht im Schlafzimmer.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":1,"id":"00b2795a-a8a2-4178-9d80-a1f4af952b21","lesson":"Lektion 5","word_de":"Hausaufgabe","article":"die","plural":"Hausaufgaben","translation_ru":"домашнее задание","translation_tr":"ödev","translation_en":"homework","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:45:39.30596+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich mache meine Hausaufgabe.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":2,"id":"0342f0ed-e858-4b3d-8354-7d0654885a51","lesson":"Lektion 5","word_de":"besuchen","article":"none","plural":None,"translation_ru":"посещать; навещать","translation_tr":"ziyaret etmek","translation_en":"to visit","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:45:39.30596+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Am Sonntag besuche ich meine Eltern.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":3,"id":"0351e914-3c71-4904-ad78-cff039ed192d","lesson":"Lektion 1","word_de":"was?","article":"none","plural":None,"translation_ru":"что?","translation_tr":"ne?","translation_en":"what?","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/7c1443d7464060896c4da1ac143e92cac24d76a12ab6ddbacd798e2c95c1dec7.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:17:55.147835+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Was machen Sie heute?","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":4,"id":"03901e6b-ef94-4150-a3fc-aff88d2d2e98","lesson":"Lektion 5","word_de":"anfangen","article":"none","plural":None,"translation_ru":"начинать","translation_tr":"başlamak","translation_en":"to start","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:45:39.30596+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wann fängt der Kurs an?","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":5,"id":"054dcd28-6231-4530-84fa-5130a5fe2bc8","lesson":"Lektion 2","word_de":"zwei","article":"none","plural":None,"translation_ru":"два","translation_tr":"iki","translation_en":"two","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:16.594264+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich habe zwei Kinder.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":6,"id":"062ba7b1-099b-4d53-a42e-531b5d8dce6e","lesson":"Lektion 6","word_de":"Temperatur","article":"die","plural":"Temperaturen","translation_ru":"температура","translation_tr":"sıcaklık","translation_en":"temperature","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Die Temperatur steigt auf zwanzig Grad.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":7,"id":"0751c7c0-997c-4fc2-99b0-478c796a08d0","lesson":"Lektion 4","word_de":"Monat","article":"der","plural":"Monate","translation_ru":"месяц","translation_tr":"ay","translation_en":"month","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:43:46.573139+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Die Miete kostet sechshundert Euro im Monat.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":8,"id":"0928b22d-451e-4bc3-bcf0-ae0ebc1b699d","lesson":"Lektion 3","word_de":"Mineralwasser","article":"das","plural":None,"translation_ru":"минеральная вода","translation_tr":"maden suyu","translation_en":"mineral water","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/b065389605788fa6e5815e36d9bfdd690ee10877953eb073e42156ce6bf7fe2b.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:49.914413+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich möchte ein Mineralwasser, bitte.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":9,"id":"09b853cd-ce60-4dab-908b-982219b29e5f","lesson":"Lektion 2","word_de":"Wie geht es dir?","article":"none","plural":None,"translation_ru":"Как у тебя дела?","translation_tr":"Nasılsın?","translation_en":"How are you? (informal)","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:19:09.972544+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wie geht es dir?","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":10,"id":"09beac3b-bde7-4c12-9b2a-632c46136d02","lesson":"Lektion 6","word_de":"plus / minus","article":"none","plural":None,"translation_ru":"плюс / минус","translation_tr":"artı / eksi","translation_en":"plus / minus","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Heute sind es minus zwei Grad.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":11,"id":"09c21566-126b-49fb-9f1a-b653245fd580","lesson":"Lektion 7","word_de":"prima / super","article":"none","plural":None,"translation_ru":"отлично; супер","translation_tr":"harika / süper","translation_en":"great / super","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/44f6e9400fee8cc444cd0eb2695cb431fe27a13b2216f7b8f074518a645d3cf0.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:55:19.635119+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Das hast du prima gemacht!","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":12,"id":"09d0bcdf-fb8c-4c36-87d0-1ebffd4bd950","lesson":"Lektion 6","word_de":"Freunde treffen","article":"none","plural":None,"translation_ru":"встречаться с друзьями","translation_tr":"arkadaşlarla buluşmak","translation_en":"to meet friends","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Am Wochenende treffe ich Freunde.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":13,"id":"0b167e28-cf9a-4c1b-8681-8ca17719db13","lesson":"Lektion 5","word_de":"spazieren gehen","article":"none","plural":None,"translation_ru":"идти гулять","translation_tr":"yürüyüşe çıkmak","translation_en":"to go for a walk","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:45:39.30596+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wir gehen im Park spazieren.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":14,"id":"0c47ae6d-aaa2-4289-9b14-2fadb136670c","lesson":"Lektion 1","word_de":"Spanien","article":"none","plural":None,"translation_ru":"Испания","translation_tr":"İspanya","translation_en":"Spain","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/7457be5a10d8576319c32fa0066806e6d62280f95f9ae8ff4b89d78c75ceeb02.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:18:29.981724+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wir machen Urlaub in Spanien.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":15,"id":"0c935b6f-4999-411e-bb7e-49ccbd7ab1b4","lesson":"Lektion 5","word_de":"lange","article":"none","plural":None,"translation_ru":"долго","translation_tr":"uzun süre","translation_en":"for a long time","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:45:39.30596+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wie lange dauert der Kurs?","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":16,"id":"0d1e78a9-a2ee-47e7-8a53-8c9c496fede4","lesson":"Lektion 6","word_de":"singen","article":"none","plural":None,"translation_ru":"петь","translation_tr":"şarkı söylemek","translation_en":"to sing","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Meine Tochter singt gern.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":17,"id":"0e0e0fa4-ab98-4e29-a9c4-0981809f708d","lesson":"Lektion 6","word_de":"bringen","article":"none","plural":None,"translation_ru":"приносить; привозить","translation_tr":"getirmek","translation_en":"to bring","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich bringe einen Salat mit.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":18,"id":"0e418b9e-c02d-4148-b262-a608d369cadb","lesson":"Lektion 1","word_de":"Telefonnummer","article":"die","plural":"Telefonnummern","translation_ru":"номер телефона","translation_tr":"telefon numarası","translation_en":"phone number","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/509e68d91add2bd846917c7f28e000627e0385eee7c50bb4edf27c16b860ba6c.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:18:44.431659+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wie ist Ihre Telefonnummer?","context_sentence_en":"What is your telephone number?","context_sentence_ru":"Какой у вас номер телефона?","context_sentence_uk":"Який у вас номер телефону?","context_sentence_tr":"Telefon numaranız nedir?","sentence_practice":True,"alternative_answers_de":[]},
{"idx":19,"id":"0ebd6ebf-4db5-42d0-be98-fd4a3ae8ef4a","lesson":"Lektion 3","word_de":"kaufen","article":"none","plural":None,"translation_ru":"покупать","translation_tr":"satın almak","translation_en":"to buy","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/aa883d1c3fff87911d61015719fe8996517bac7e523b0e8380bf57a24c4867d0.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:21:30.947211+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich kaufe Milch im Supermarkt.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":20,"id":"0ee0ded4-cd1b-41dd-9ffa-e04021a5e3a3","lesson":"Lektion 1","word_de":"Auf Wiedersehen","article":"none","plural":None,"translation_ru":"до свидания","translation_tr":"hoşça kalın","translation_en":"goodbye","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/e4f1efd7466ca7bc8b666af6933cdf43d5f2a93923f05e7f5d687e3619b0a28a.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:17:55.147835+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Auf Wiedersehen, bis morgen!","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":21,"id":"0f88b902-7e86-47f2-b977-9f50e15f601f","lesson":"Lektion 2","word_de":"Es geht.","article":"none","plural":None,"translation_ru":"Нормально. / Пойдёт.","translation_tr":"İdare eder.","translation_en":"So-so.","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:19:09.972544+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wie geht es dir? Es geht.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":22,"id":"0fb28677-cb44-4949-b554-f5abf4c99997","lesson":"Lektion 5","word_de":"kochen","article":"none","plural":None,"translation_ru":"готовить","translation_tr":"yemek pişirmek","translation_en":"to cook","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:45:39.30596+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Heute koche ich das Abendessen.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":23,"id":"10131cb9-266d-402e-b727-11ecd0571275","lesson":"Lektion 7","word_de":"pünktlich","article":"none","plural":None,"translation_ru":"пунктуальный; вовремя","translation_tr":"dakik; zamanında","translation_en":"punctual; on time","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/3aeef32d520c83a68de89be57d29a9ed27e0385eee7c50bb4edf27c16b860ba6c.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:55:19.635119+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Bitte kommen Sie pünktlich.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":24,"id":"1037a031-34eb-4699-b40a-254676c2c17b","lesson":"Lektion 7","word_de":"Unterricht","article":"der","plural":"-","translation_ru":"занятие; урок","translation_tr":"ders","translation_en":"lesson; class","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/b0a70239c2252952140293de97f966ab488c3fdea119dc3aaefa5ef5b974a79a.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:55:19.635119+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Der Unterricht beginnt um neun Uhr.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":25,"id":"1132ba29-7114-40a6-a4ae-c1ddc519351e","lesson":"Lektion 3","word_de":"Pfannkuchen","article":"der","plural":"Pfannkuchen","translation_ru":"блин / оладья","translation_tr":"krep / pankek","translation_en":"pancake","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/6ef0e56419ca32409ced5f663e69c51bf840d1733747d14d3478d2e6d16b54dc.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:49.914413+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Heute machen wir Pfannkuchen.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":26,"id":"114ed40c-e13e-4c80-80e0-f9dfc91a31bb","lesson":"Lektion 5","word_de":"einkaufen (kauft … ein)","article":"none","plural":None,"translation_ru":"делать покупки","translation_tr":"alışveriş yapmak","translation_en":"to shop","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:45:39.30596+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Sie kauft im Supermarkt ein.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":27,"id":"115a9692-dbe2-40f3-985d-39a4cf7f2b6a","lesson":"Lektion 2","word_de":"Lehrer","article":"der","plural":"Lehrer","translation_ru":"учитель","translation_tr":"öğretmen (erkek)","translation_en":"teacher (male)","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/a115d9d88da5822b65c5f9b89c186e9bb56ccc81b77b7b58336077068ce3eb93.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:19:09.972544+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Unser Lehrer erklärt die Aufgabe.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":28,"id":"11a55dd5-4e89-49d5-bda0-bb976072d5c3","lesson":"Lektion 6","word_de":"Ich tanze gern. / Ich lese gern.","article":"none","plural":None,"translation_ru":"Я люблю танцевать. / Я люблю читать.","translation_tr":"Dans etmeyi severim. / Okumayı severim.","translation_en":"I like dancing. / I like reading.","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich tanze gern.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":29,"id":"131a458d-0143-4f13-ba26-67bcb160e7a6","lesson":"Lektion 4","word_de":"Handy","article":"das","plural":"Handys","translation_ru":"мобильный телефон","translation_tr":"cep telefonu","translation_en":"mobile phone","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/95c5bc634a89a139850941eac0310c5bf36543ba4948fd0edbe82f403ce1df4a.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:43:46.573139+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Mein Handy liegt auf dem Tisch.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":30,"id":"1372440c-48c0-4406-8534-61be44e7690f","lesson":"Lektion 2","word_de":"Das ist meine Mutter.","article":"none","plural":None,"translation_ru":"Это моя мама.","translation_tr":"Bu benim annem.","translation_en":"This is my mother.","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:27.780587+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Das ist meine Mutter.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":31,"id":"13f5967b-9591-4cad-950e-f39018d1be83","lesson":"Lektion 4","word_de":"Schrank","article":"der","plural":"Schränke","translation_ru":"шкаф","translation_tr":"dolap","translation_en":"cupboard; wardrobe","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:43:46.573139+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Meine Kleidung liegt im Schrank.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":32,"id":"144fadbe-df61-4fbb-be66-bdb1d6a7d870","lesson":"Lektion 7","word_de":"reiten","article":"none","plural":None,"translation_ru":"ездить верхом","translation_tr":"ata binmek","translation_en":"to ride a horse","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/0dba9e050d2c50ee7420d8a3fbb572ad1f66e2745c6059f78df5b47f4b556d30.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:55:19.635119+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Meine Tochter reitet gern.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":33,"id":"14b46a4e-cf6d-4c35-bd90-ec926482c11e","lesson":"Lektion 2","word_de":"Wo lebt deine Familie? – Meine Familie lebt in …","article":"none","plural":None,"translation_ru":"Где живёт твоя семья? – Моя семья живёт в …","translation_tr":"Ailen nerede yaşıyor? – Ailem ...de yaşıyor.","translation_en":"Where does your family live? – My family lives in …","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:27.780587+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wo lebt deine Familie? Meine Familie lebt in Berlin.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":34,"id":"14eb942b-48eb-4820-bf63-283d5902e722","lesson":"Lektion 2","word_de":"sie (Plural)","article":"none","plural":None,"translation_ru":"они","translation_tr":"onlar","translation_en":"they","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:16.594264+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Sie lernen zusammen Deutsch.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":35,"id":"154abffd-41be-4d67-af60-e9daa1d2c566","lesson":"Lektion 6","word_de":"Herbst","article":"der","plural":"-","translation_ru":"осень","translation_tr":"sonbahar","translation_en":"autumn","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Im Herbst regnet es oft.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":36,"id":"156b2087-bf7f-4f20-93fb-214062e48c85","lesson":"Lektion 3","word_de":"Spinat","article":"der","plural":None,"translation_ru":"шпинат","translation_tr":"ıspanak","translation_en":"spinach","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/640f8ab5ee44bfa5aa4a8e0aa83e430f148fafd739cdf59da5008a70de922d80.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:49.914413+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Heute gibt es Kartoffeln mit Spinat.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":37,"id":"1713a14f-f024-46a5-acbc-599dbd1dcf54","lesson":"Lektion 7","word_de":"gestern","article":"none","plural":None,"translation_ru":"вчера","translation_tr":"dün","translation_en":"yesterday","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/d4c2eefcfcb6315b046aa08ffa2db5de37f89365d3431d064a0013d9c73d41b9.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:55:19.635119+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Gestern war ich im Deutschkurs.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":38,"id":"17b37259-9cc4-41fe-b9a5-71befcd9fdb3","lesson":"Lektion 2","word_de":"vierzehn","article":"none","plural":None,"translation_ru":"четырнадцать","translation_tr":"on dört","translation_en":"fourteen","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:27.780587+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Meine Tochter ist vierzehn Jahre alt.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":39,"id":"17e827f4-9a73-42e8-9961-030e37013c07","lesson":"Lektion 2","word_de":"Papa","article":"der","plural":"Papas","translation_ru":"папа","translation_tr":"baba","translation_en":"dad","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:19:09.972544+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Papa kocht das Abendessen.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":40,"id":"17f8f8c6-1f88-44ef-a106-acaed351801c","lesson":"Lektion 3","word_de":"Schokolade","article":"die","plural":"Schokoladen","translation_ru":"шоколад","translation_tr":"çikolata","translation_en":"chocolate","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/7b2f4557780dd645855e4fe00e7eebe055ecdc60f2ac3782794d6a19d6b1a0a5.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:49.914413+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich esse gern Schokolade.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":41,"id":"180d8cd1-96d3-4e93-9eb3-6e7411a2ac6b","lesson":"Lektion 3","word_de":"Käse","article":"der","plural":"Käse","translation_ru":"сыр","translation_tr":"peynir","translation_en":"cheese","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/50e4935b897275d1be5c71b0a43fcca73481ebc60987b02fafe1436fd43f5b90.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:49.914413+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich esse gern Brot mit Käse.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":42,"id":"182603e5-d4e9-4741-ba04-eaaf1685d686","lesson":"Lektion 2","word_de":"achtzehn","article":"none","plural":None,"translation_ru":"восемнадцать","translation_tr":"on sekiz","translation_en":"eighteen","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/e1692fe8ef1bd4c30a79b34748c7bef22abbaed1ec0fb8db4a3b2d2e7af3b2da.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:27.780587+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Meine Tochter ist achtzehn Jahre alt.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":43,"id":"18ed05ce-a766-4b5d-b65c-0096f2d99be2","lesson":"Lektion 4","word_de":"schwarz","article":"none","plural":None,"translation_ru":"чёрный","translation_tr":"siyah","translation_en":"black","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:43:46.573139+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Der Fernseher ist schwarz.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":44,"id":"18fcfce1-8d2c-4b8f-a274-261744c11744","lesson":"Lektion 1","word_de":"Guten Abend","article":"none","plural":None,"translation_ru":"добрый вечер","translation_tr":"iyi akşamlar","translation_en":"good evening","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/85671dece1ea0ae58ea9b10ebee75621980a29d41cd156095bd1904210a96b9b.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:17:55.147835+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Guten Abend, Frau Müller!","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":45,"id":"19aa355b-3910-4ea3-92fd-08dbf47b251c","lesson":"Lektion 6","word_de":"Freizeit","article":"die","plural":"-","translation_ru":"свободное время","translation_tr":"boş zaman","translation_en":"free time","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Was machen Sie in Ihrer Freizeit?","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":46,"id":"19b6b0db-0a4b-4b77-9fee-bced6147464a","lesson":"Lektion 1","word_de":"Hallo","article":"none","plural":None,"translation_ru":"привет","translation_tr":"merhaba","translation_en":"hello","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/5b21e94006e8952de30686e57e79d6486d28d03b851c2af28c684df57002cc63.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:17:55.147835+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Hallo, wie geht es dir?","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":47,"id":"1a03578f-3e9b-42a1-a45f-a60c4152df15","lesson":"Lektion 2","word_de":"lernen","article":"none","plural":None,"translation_ru":"учить / учиться","translation_tr":"öğrenmek","translation_en":"to learn","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:16.594264+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wir lernen zusammen Deutsch.","context_sentence_en":"We are learning German together.","context_sentence_ru":"Мы вместе учим немецкий.","context_sentence_uk":"Ми разом вчимо німецьку.","context_sentence_tr":"Birlikte Almanca öğreniyoruz.","sentence_practice":True,"alternative_answers_de":[]},
{"idx":48,"id":"1a251809-c2d9-4fa4-a55c-33308d91d48a","lesson":"Lektion 4","word_de":"gelb","article":"none","plural":None,"translation_ru":"жёлтый","translation_tr":"sarı","translation_en":"yellow","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:43:46.573139+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Die Wand ist gelb.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":49,"id":"1ae10e1c-52d9-4f0d-b832-557d10abd3ff","lesson":"Lektion 3","word_de":"Wein","article":"der","plural":"Weine","translation_ru":"вино","translation_tr":"şarap","translation_en":"wine","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/4d1ab0695f81154f223f315818a410e50b863654e86fe4bfc05953d695bbc1ce.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:49.914413+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Zum Essen trinke ich ein Glas Wein.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":50,"id":"1b03a32b-c272-4bc3-8918-63dc6c5bcd4e","lesson":"Lektion 4","word_de":"Haus","article":"das","plural":"Häuser","translation_ru":"дом","translation_tr":"ev","translation_en":"house","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:43:46.573139+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wir wohnen in einem Haus mit Garten.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":51,"id":"1d4da7c5-601a-4311-ae58-64f383efae62","lesson":"Lektion 5","word_de":"zusammen","article":"none","plural":None,"translation_ru":"вместе","translation_tr":"birlikte","translation_en":"together","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:45:39.30596+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wir lernen zusammen.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":52,"id":"1d595041-ca9b-4af4-b2e9-efbd90167f9f","lesson":"Lektion 6","word_de":"Ich treffe am Wochenende Freunde.","article":"none","plural":None,"translation_ru":"Я встречаюсь с друзьями на выходных.","translation_tr":"Hafta sonunda arkadaşlarımla buluşuyorum.","translation_en":"I meet friends at the weekend.","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich treffe am Wochenende Freunde.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":53,"id":"1dd53266-155c-467f-8af2-cfab5317c4d6","lesson":"Lektion 1","word_de":"Dame","article":"die","plural":"Damen","translation_ru":"дама","translation_tr":"hanımefendi","translation_en":"lady","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/989498ebb0d18cb49df017fee0e897fa4e0056e76f6e36cb74de965e49b2dd7c.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:17:55.147835+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Die Dame wartet an der Haltestelle.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":54,"id":"1dd9cd0b-10be-45b1-a0c5-998d954ed5d3","lesson":"Lektion 3","word_de":"Bäckerei","article":"die","plural":"Bäckereien","translation_ru":"пекарня","translation_tr":"fırın / pastane","translation_en":"bakery","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/ecd96eeec6cf3783a84c67de16410919fd0f384f3f887a4b1c29cf2216ea82d3.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:21:30.947211+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich kaufe Brot in der Bäckerei.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":55,"id":"1e1961d8-dc7b-49b3-bc98-a8ee3f7d458c","lesson":"Lektion 1","word_de":"aha","article":"none","plural":None,"translation_ru":"ага / понятно","translation_tr":"anladım","translation_en":"I see","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/387f598529a0656c2ebfdfa71232b256362be1163b0a535dfb015c6c839bf29e.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:18:29.981724+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Aha, jetzt verstehe ich das.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":56,"id":"1f5272e5-d3de-496f-9081-ad269026782e","lesson":"Lektion 6","word_de":"bleiben","article":"none","plural":None,"translation_ru":"оставаться","translation_tr":"kalmak","translation_en":"to stay","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Heute bleibe ich zu Hause.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":57,"id":"1f9e25db-587f-4aef-903d-dd2de6917ba9","lesson":"Lektion 3","word_de":"Haben wir Zucker?","article":"none","plural":None,"translation_ru":"У нас есть сахар?","translation_tr":"Şekerimiz var mı?","translation_en":"Do we have sugar?","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/b199e5c237851b92dfb41c3507ae9a1e8b9e97abcfee75a8a5dbbfffbf725080.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:21:30.947211+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Haben wir Zucker?","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":58,"id":"201d1b2e-b256-4dd7-91c5-de65955268eb","lesson":"Lektion 4","word_de":"Badezimmer","article":"das","plural":"-","translation_ru":"ванная комната","translation_tr":"banyo odası","translation_en":"bathroom","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:43:46.573139+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Das Badezimmer ist klein.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":59,"id":"20675dd1-9dd0-434f-aae4-1fd1c731bf93","lesson":"Lektion 1","word_de":"Stadt","article":"die","plural":"Städte","translation_ru":"город","translation_tr":"şehir","translation_en":"city","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/30a76cac9093d07669c29411ed86c2b4467073a00054407908f910f591c6e250.mp3","is_hard_for_ru":True,"is_hard_for_tr":True,"created_at":"2026-09-02 20:18:44.431659+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Hannover ist eine große Stadt.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":60,"id":"20b27b17-3407-4af7-8759-1f075b3196b4","lesson":"Lektion 7","word_de":"krank","article":"none","plural":None,"translation_ru":"больной; больна","translation_tr":"hasta","translation_en":"ill; sick","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/3d9d05ee2c5932802be848187e7f00c52970fae04eb731e458b4bcfe71b66b59.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:55:19.635119+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich bin heute krank.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":61,"id":"20dd2336-d1c6-4bdd-b858-285f42c4b702","lesson":"Lektion 7","word_de":"lernen","article":"none","plural":None,"translation_ru":"учить; учиться","translation_tr":"öğrenmek; çalışmak","translation_en":"to learn; study","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/f572c9b3f2cf5bfc57646e46e03c7b0b47231358f71fc8dc51574ae5eb8aa9fa.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:55:19.635119+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wir lernen zusammen Deutsch.","context_sentence_en":"We are learning German together.","context_sentence_ru":"Мы вместе учим немецкий.","context_sentence_uk":"Ми разом вчимо німецьку.","context_sentence_tr":"Birlikte Almanca öğreniyoruz.","sentence_practice":True,"alternative_answers_de":[]},
{"idx":62,"id":"21a501ff-3013-46d4-8ee3-059f2150718e","lesson":"Lektion 3","word_de":"Ich möchte …","article":"none","plural":None,"translation_ru":"Я хотел(а) бы …","translation_tr":"… istiyorum.","translation_en":"I would like …","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/2ebbbf49a5f7903399b1f179546bdb9c4ff4158670005be5c1e1ac0266d166da.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:21:30.947211+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich möchte einen Kaffee, bitte.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":63,"id":"22d779e6-4c15-4b97-ad09-497b06e272d5","lesson":"Lektion 1","word_de":"Gute Nacht","article":"none","plural":None,"translation_ru":"спокойной ночи","translation_tr":"iyi geceler","translation_en":"good night","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/ef52ad7f06ad736beae6bbd2c59f0661f5f5b716c5de9783fc5bc2ae99775f67.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:17:55.147835+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Gute Nacht, schlaf gut!","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":64,"id":"251400c9-898a-41c9-bef1-19472a61994c","lesson":"Lektion 3","word_de":"finden","article":"none","plural":None,"translation_ru":"находить (Wo finde ich …?)","translation_tr":"bulmak (Nerede bulabilirim …?)","translation_en":"to find","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/5b25d840cc077c4cadebc356c2a8a73e04747c7acd1d404f93308082a8936c96.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:21:30.947211+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wo finde ich die Milch?","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":65,"id":"254a6a31-f9ba-443b-bd1b-1e8d6cd451c4","lesson":"Lektion 4","word_de":"Das gefällt mir. / Das gefällt mir nicht.","article":"none","plural":None,"translation_ru":"Мне это нравится. / Мне это не нравится.","translation_tr":"Bu hoşuma gidiyor. / Bu hoşuma gitmiyor.","translation_en":"I like that. / I don't like that.","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:43:46.573139+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Das gefällt mir sehr gut.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":66,"id":"25907484-1b7d-45cd-9c92-dec74bc18402","lesson":"Lektion 2","word_de":"keine","article":"none","plural":None,"translation_ru":"никакие / нет (Ich habe keine Geschwister.)","translation_tr":"hiç / yok (Kardeşim yok.)","translation_en":"no / none","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:16.594264+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich habe keine Geschwister.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":67,"id":"27f735ba-2fc3-48b0-a454-576e6d20bd76","lesson":"Lektion 3","word_de":"Tee","article":"der","plural":"Tees","translation_ru":"чай","translation_tr":"çay","translation_en":"tea","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/bdeaa0dcff1a83b878e9428798f6ab5abfffc4468e30d826601a53276993f3d8.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:49.914413+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich trinke abends Tee.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":68,"id":"28fffcb7-35e4-4ab9-a20e-8e64f5985a3a","lesson":"Lektion 2","word_de":"getrennt","article":"none","plural":None,"translation_ru":"в раздельном проживании","translation_tr":"ayrı","translation_en":"separated","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/73298d6063b2415a7702d64f0d22653bfad1950fd3cd6e48c948e5f9e23eda56.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:16.594264+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wir leben seit einem Jahr getrennt.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":69,"id":"295925a1-c0d9-4039-b538-01efa633bd63","lesson":"Lektion 3","word_de":"Ich brauche …","article":"none","plural":None,"translation_ru":"Мне нужно …","translation_tr":"… ihtiyacım var.","translation_en":"I need …","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/7af5f0741c173b0707db705ce9745e3fc47360a74e3e370ffec050e3c3b5a5ee.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:21:30.947211+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich brauche eine Flasche Wasser.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":70,"id":"29949d50-1dfd-4f59-b506-79f36681391d","lesson":"Lektion 4","word_de":"Ach so!","article":"none","plural":None,"translation_ru":"А, понятно!","translation_tr":"Aa, anladım!","translation_en":"Oh, I see!","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:43:46.573139+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ach so! Jetzt verstehe ich das.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":71,"id":"2aa2d6e5-3c47-4e0c-b425-2b365f8cd1a9","lesson":"Lektion 1","word_de":"Wer ist das? – Das ist …","article":"none","plural":None,"translation_ru":"Кто это? – Это …","translation_tr":"Bu kim? – Bu …","translation_en":"Who is that? – That is …","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/7260cdc5a97a4cff746a32cc5db1004b9a5bd18b1ad6a09f0e7022deecb332c0.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:18:44.431659+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wer ist das? Das ist meine Schwester.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":72,"id":"2ad0f4dc-7dbc-423d-87b8-aa67f2c94114","lesson":"Lektion 5","word_de":"arbeiten","article":"none","plural":None,"translation_ru":"работать","translation_tr":"çalışmak","translation_en":"to work","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:45:39.30596+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich arbeite von Montag bis Freitag.","context_sentence_en":"I work from Monday to Friday.","context_sentence_ru":"Я работаю с понедельника по пятницу.","context_sentence_uk":"Я працюю з понеділка до п’ятниці.","context_sentence_tr":"Pazartesiden cumaya kadar çalışıyorum.","sentence_practice":True,"alternative_answers_de":[]},
{"idx":73,"id":"2aff0c5c-0fbd-420d-8abf-c70ea88dc615","lesson":"Lektion 6","word_de":"Gitarre","article":"die","plural":"Gitarren","translation_ru":"гитара","translation_tr":"gitar","translation_en":"guitar","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Meine Gitarre steht im Wohnzimmer.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":74,"id":"2b5181e7-3471-4f3d-8696-cd994f99aff4","lesson":"Lektion 2","word_de":"vier","article":"none","plural":None,"translation_ru":"четыре","translation_tr":"dört","translation_en":"four","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:16.594264+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wir sind vier Personen.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":75,"id":"2bf934c3-8cd0-441b-96cf-9f49811242e5","lesson":"Lektion 4","word_de":"Stuhl","article":"der","plural":"Stühle","translation_ru":"стул","translation_tr":"sandalye","translation_en":"chair","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:43:46.573139+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Bitte nehmen Sie auf dem Stuhl Platz.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":76,"id":"2bfd60e6-06e5-4195-a20f-5fab72952d3f","lesson":"Lektion 3","word_de":"Fisch","article":"der","plural":"Fische","translation_ru":"рыба","translation_tr":"balık","translation_en":"fish","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/bcbccfef65b9ce10b68005bd73b868e057abb98221a279f3bfc00c6a60b53cf8.mp3","is_hard_for_ru":True,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:49.914413+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Am Freitag essen wir Fisch.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":77,"id":"2c0e0b2c-d125-4dc4-9d26-dcb0a10ed2e3","lesson":"Lektion 2","word_de":"Eltern","article":"die","plural":None,"translation_ru":"родители","translation_tr":"anne baba / ebeveynler","translation_en":"parents","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/7478b804ee114b30f0ac23099fc6e814660893aba6e526e1998260887e839886.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:19:09.972544+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Meine Eltern wohnen in Hannover.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":78,"id":"2c16e19d-424b-46d2-9d0e-0a50d6d90ffd","lesson":"Lektion 1","word_de":"Ich spreche ein bisschen Deutsch","article":"none","plural":None,"translation_ru":"Я немного говорю по-немецки","translation_tr":"Biraz Almanca konuşuyorum","translation_en":"I speak a little German","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/866db86b855f4cb8f9a5505a8a9d03a0e3b30cf7413c6791d84410e56c5fea5d.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:18:44.431659+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich spreche ein bisschen Deutsch.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":79,"id":"2c1b3e1c-6ba5-498f-992f-7d95db97a14e","lesson":"Lektion 7","word_de":"wollen (will, willst, wollen)","article":"none","plural":None,"translation_ru":"хотеть","translation_tr":"istemek","translation_en":"to want","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/0827650a7bd47799e932eb13f56047e0804a047b8ce807b456c9f1cd3d676ce7.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:55:19.635119+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich will Deutsch lernen.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":80,"id":"2c48e69d-fe4a-46a7-9eb5-dde5d4bbf599","lesson":"Lektion 1","word_de":"Sie","article":"none","plural":None,"translation_ru":"Вы (вежливая форма)","translation_tr":"siz (resmi)","translation_en":"you (formal)","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/5a6e7d80fe26a0458a6c6ee5ab87f0d80cac3143e826ed8cab59ec911abc2b99.mp3","is_hard_for_ru":False,"is_hard_for_tr":True,"created_at":"2026-09-02 20:17:55.147835+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Woher kommen Sie?","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":81,"id":"2d13dc47-fa57-4ac2-985a-5409c789b1f8","lesson":"Lektion 5","word_de":"Morgen","article":"der","plural":"-","translation_ru":"утро","translation_tr":"sabah","translation_en":"morning","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:45:39.30596+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Am Morgen frühstücke ich zu Hause.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":82,"id":"2e5636a7-08a2-4c15-9dee-7399baca2a43","lesson":"Lektion 5","word_de":"machen","article":"none","plural":None,"translation_ru":"делать","translation_tr":"yapmak","translation_en":"to do; make","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:45:39.30596+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Was machen Sie am Wochenende?","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":83,"id":"2f187bc6-1dba-4960-aee0-53a26a12a6bb","lesson":"Lektion 3","word_de":"Gemüse","article":"das","plural":None,"translation_ru":"овощи","translation_tr":"sebze","translation_en":"vegetables","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/aa09074b62c2102d71a6d229cd20c97aceb0a9258c47cc197a1a50de7a792c50.mp3","is_hard_for_ru":True,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:49.914413+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wir kaufen frisches Gemüse.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":84,"id":"2f217657-f2a2-479c-99a0-cea609687b81","lesson":"Lektion 7","word_de":"Ich kann nicht in die Schule gehen. Ich bin krank.","article":"none","plural":None,"translation_ru":"Я не могу идти в школу. Я болен / больна.","translation_tr":"Okula gidemem. Hastayım.","translation_en":"I can't go to school. I am ill.","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/5a657ad434e812f5b4871a53432151312a85064f1de1366d90f01a6315fd5baa.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:55:19.635119+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich kann nicht in die Schule gehen. Ich bin krank.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":85,"id":"2f49142f-8b2b-4133-90c0-f6e031e23913","lesson":"Lektion 3","word_de":"Orange","article":"die","plural":"Orangen","translation_ru":"апельсин","translation_tr":"portakal","translation_en":"orange","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/87039046374f58238d34c7d83a68f10dd384f1b5bf496778148141280d83279e.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:49.914413+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich esse eine Orange.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":86,"id":"306b2e18-fda8-482e-abc4-0664cd4c5508","lesson":"Lektion 3","word_de":"sonst","article":"none","plural":None,"translation_ru":"ещё / иначе (Sonst noch etwas?)","translation_tr":"başka (Başka bir şey?)","translation_en":"otherwise / else","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/07f69b4ba227db39a6d3b09ef894ecd59b1a9446c1da1e395ee97892a0eafac2.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:21:30.947211+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Brauchen Sie sonst noch etwas?","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":87,"id":"30967266-e51f-42be-9960-5eeddd0b8d31","lesson":"Lektion 6","word_de":"überall","article":"none","plural":None,"translation_ru":"везде","translation_tr":"her yerde","translation_en":"everywhere","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Im Frühling blühen überall Blumen.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":88,"id":"310d63de-ba08-41c0-8152-f74828d6b8dd","lesson":"Lektion 4","word_de":"billig","article":"none","plural":None,"translation_ru":"дешёвый","translation_tr":"ucuz","translation_en":"cheap","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:43:46.573139+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Der Tisch ist billig.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":89,"id":"31df0144-1afe-4dd3-8c71-4c63b82582ed","lesson":"Lektion 5","word_de":"Präsentation","article":"die","plural":"Präsentationen","translation_ru":"презентация","translation_tr":"sunum","translation_en":"presentation","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:45:39.30596+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich mache eine Präsentation im Deutschkurs.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":90,"id":"3301c509-dffd-4258-b27d-819b4d24abc7","lesson":"Lektion 2","word_de":"Enkel","article":"der","plural":"Enkel","translation_ru":"внук","translation_tr":"erkek torun","translation_en":"grandson","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/97db647456643b2cc24b1487f85c7714a8a9296f9bc62684573809ae7d1d26dc.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:19:09.972544+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Mein Enkel geht in die Schule.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":91,"id":"3425a2fc-1c39-4f9f-aa15-0c2a5fe5e2e8","lesson":"Lektion 6","word_de":"heiß","article":"none","plural":None,"translation_ru":"жаркий; горячий","translation_tr":"sıcak","translation_en":"hot","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Im Sommer ist es oft heiß.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":92,"id":"343df964-9479-4004-8124-f8bfdcbd627b","lesson":"Lektion 3","word_de":"Supermarkt","article":"der","plural":"Supermärkte","translation_ru":"супермаркет","translation_tr":"süpermarket","translation_en":"supermarket","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/f71cfd54f56c77b8675c66601689fb6090894bdd78732b416563e41c8f3a198c.mp3","is_hard_for_ru":True,"is_hard_for_tr":True,"created_at":"2026-09-02 20:21:30.947211+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Der Supermarkt ist bis acht Uhr geöffnet.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":93,"id":"3470ef89-e9bc-402e-9ffd-4b4791278735","lesson":"Lektion 3","word_de":"Mehl","article":"das","plural":None,"translation_ru":"мука","translation_tr":"un","translation_en":"flour","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/5b7735319e7bf351a231e614629a2594867f616f47b804f94bd42d06982a370f.mp3","is_hard_for_ru":True,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:49.914413+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Für den Kuchen brauchen wir Mehl.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":94,"id":"3513cd08-b25b-4600-88c6-135c24629526","lesson":"Lektion 6","word_de":"Regen","article":"der","plural":"-","translation_ru":"дождь","translation_tr":"yağmur","translation_en":"rain","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:49:03.406866+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Wir bleiben bei Regen zu Hause.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":95,"id":"36cbc3eb-751f-4a87-b9fd-dbc81dde6d02","lesson":"Lektion 7","word_de":"auf jeden Fall","article":"none","plural":None,"translation_ru":"в любом случае; обязательно","translation_tr":"her hâlükârda; kesinlikle","translation_en":"in any case; definitely","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/fc83718f6157bac6d7a11a73de8bfb6c8415e689cb9a029bc320da710a3b598d.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:55:19.635119+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich komme auf jeden Fall.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":96,"id":"375c69bf-45bd-4821-840b-bf96f4347cb2","lesson":"Lektion 5","word_de":"mit","article":"none","plural":None,"translation_ru":"с","translation_tr":"ile","translation_en":"with","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-03 20:45:39.30596+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich gehe mit meiner Freundin spazieren.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":97,"id":"378d8e17-6a77-40bb-bee6-88250c931d4e","lesson":"Lektion 2","word_de":"Ich habe keine Geschwister.","article":"none","plural":None,"translation_ru":"У меня нет братьев и сестёр.","translation_tr":"Kardeşim yok.","translation_en":"I have no siblings.","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:27.780587+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Ich habe keine Geschwister.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":98,"id":"38841dcc-f2dd-4a39-8858-610a12fd14b3","lesson":"Lektion 2","word_de":"acht","article":"none","plural":None,"translation_ru":"восемь","translation_tr":"sekiz","translation_en":"eight","image_url":None,"audio_url":"https://wcaslabeiwtvygxtzcio.supabase.co/storage/v1/object/public/audio_cache/edge-v1/de/4b9b1bcd4aed1c7c2b785a57110733cedd35e34fa62372db4c7e3b3710316011.mp3","is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:20:16.594264+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Der Kurs beginnt um acht Uhr.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]},
{"idx":99,"id":"38d02ff1-bf69-406f-b51a-b27d03b03de4","lesson":"Lektion 2","word_de":"sehr gut","article":"none","plural":None,"translation_ru":"очень хорошо","translation_tr":"çok iyi","translation_en":"very good","image_url":None,"audio_url":None,"is_hard_for_ru":False,"is_hard_for_tr":False,"created_at":"2026-09-02 20:19:09.972544+00","level":"A1.1","translation_uk":None,"context_sentence_de":"Das Essen schmeckt sehr gut.","context_sentence_en":None,"context_sentence_ru":None,"context_sentence_uk":None,"context_sentence_tr":None,"sentence_practice":False,"alternative_answers_de":[]}
]

number_map = {
    'zwei': '2',
    'drei': '3',
    'vier': '4',
    'fünf': '5',
    'sechs': '6',
    'sieben': '7',
    'acht': '8',
    'neun': '9',
    'zehn': '10',
    'elf': '11',
    'zwölf': '12',
    'dreizehn': '13',
    'vierzehn': '14',
    'fünfzehn': '15',
    'sechzehn': '16',
    'siebzehn': '17',
    'achtzehn': '18',
    'neunzehn': '19',
    'zwanzig': '20',
    'sechshundert': '600',
}

def generate_alternatives(sentence):
    alts = set()
    
    # 1. Number replacements
    tokens = sentence.split()
    for i, t in enumerate(tokens):
        clean_t = ''.join(c for c in t if c.isalnum()).lower()
        if clean_t in number_map:
            new_tokens = list(tokens)
            new_tokens[i] = new_tokens[i].replace(t[:len(clean_t)], number_map[clean_t])
            # also handle case where it's uppercase
            alts.add(' '.join(new_tokens))
    
    # 2. Punctuation replacements
    if '?' in sentence and ' ' in sentence[sentence.index('?')+1:]:
        # like: Wo lebt deine Familie? Meine Familie lebt in Berlin.
        # we can add dashes
        idx = sentence.index('?')
        alt = sentence[:idx+1] + ' -' + sentence[idx+1:]
        alts.add(alt)
        alt2 = sentence[:idx+1] + ' –' + sentence[idx+1:]
        alts.add(alt2)
        
    return list(alts)

# some manual overrides based on `word_de`
manual_overrides = {
    "prima / super": ["Das hast du super gemacht!"],
    "minus": ["Heute sind es -2 Grad.", "Heute sind es minus 2 Grad."],
    "Ich tanze gern. / Ich lese gern.": ["Ich lese gern."],
}

sql_statements = []

for row in data:
    sid = row["id"]
    sentence = row["context_sentence_de"]
    word = row["word_de"]
    
    alts = generate_alternatives(sentence)
    
    # manual overrides based on substring matching
    if "prima / super" in word:
        alts.append("Das hast du super gemacht!")
    if "Ich tanze gern. / Ich lese gern." in word:
        alts.append("Ich lese gern.")
    if "minus" in word:
        alts.extend(["Heute sind es -2 Grad.", "Heute sind es minus 2 Grad."])
        
    if alts:
        # distinct and remove original
        alts = list(set([a for a in alts if a != sentence]))
        if alts:
            arr_str = "ARRAY[" + ", ".join(f"'{a.replace(chr(39), chr(39)+chr(39))}'" for a in alts) + "]::text[]"
            sql = f"UPDATE vocabulary_cards SET alternative_answers_de = {arr_str} WHERE id = '{sid}';"
            sql_statements.append(sql)

with open("/Users/denniskostjuk/Documents/SitovAcademy/SmartGerman/supabase/migrations/update_alternatives.sql", "w") as f:
    f.write("-- Auto-generated update script for alternative answers\n")
    f.write("BEGIN;\n\n")
    for s in sql_statements:
        f.write(s + "\n")
    f.write("\nCOMMIT;\n")

print("Generated update_alternatives.sql")
