import { I, gap, mc } from '../shared.mjs'

const AUX_PAST = 'haben / sein (Präteritum)'
const ALS_WENN = 'als / wenn'
const FINDER = 'Zeitungsmeldung: „Ein ehrlicher Finder machte in Bremen einen Studenten glücklich. Der junge Mann hatte am Bahnhof seinen Rucksack mit Laptop und Ausweis vergessen. Ein Taxifahrer fand den Rucksack und brachte ihn noch am selben Abend zur Polizei. Der Student bedankte sich bei ihm mit einem Blumenstrauß.“'
const GEWITTER = 'Zeitungsmeldung: „Glück im Unglück hatte ein Ehepaar aus Freiburg. Bei einem Gewitter am Sonntagabend fiel ein großer Baum auf ihr Auto. Die beiden waren gerade ausgestiegen und standen schon vor der Haustür. Niemand wurde verletzt, aber das Auto ist völlig kaputt. ‚Wir hatten einen Schutzengel‘, sagte der Mann.“'

/** B1.1 · Pfad 1 · Glück im Alltag – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Pechvogel', I.choose, 'Tom hat schon wieder sein Handy verloren, und gestern hat ihm auch noch jemand das Fahrrad gestohlen. Er ist wirklich ein …', ['Pechvogel', 'Glückspilz', 'Glücksbringer'],
      ['Tom has lost his phone yet again, and yesterday somebody stole his bike as well. He really is a …', 'Tom опять потерял телефон, а вчера у него ещё и украли велосипед. Он действительно …', 'Tom знову загубив телефон, а вчора в нього ще й украли велосипед. Він справді …', 'Tom yine telefonunu kaybetti, dün de biri bisikletini çaldı. O gerçekten bir …']),
    mc('G1', 'arbeitete', I.choose, 'Von 2010 bis 2015 … meine Mutter als Köchin in einem Hotel am See.', ['arbeitete', 'arbeiteten', 'arbeitet'],
      ['From 2010 to 2015 my mother worked as a cook in a hotel by the lake.', 'С 2010 по 2015 год моя мама работала поваром в отеле у озера.', 'З 2010 до 2015 року моя мама працювала кухаркою в готелі біля озера.', '2010’dan 2015’e kadar annem göl kenarındaki bir otelde aşçı olarak çalıştı.']),
    mc('G2', 'blieb', I.choose, 'Weil es stark schneite, … die ganze Familie am Sonntag zu Hause.', ['blieb', 'bleibte', 'blieben'],
      ['Because it was snowing heavily, the whole family stayed at home on Sunday.', 'Из-за сильного снегопада вся семья в воскресенье осталась дома.', 'Через сильний снігопад уся родина в неділю залишилася вдома.', 'Yoğun kar yağdığı için bütün aile pazar günü evde kaldı.']),
    mc('G3', 'dachten', I.choose, 'Wir …, dass das Museum montags geöffnet ist, aber es war leider geschlossen.', ['dachten', 'denkten', 'dachte'],
      ['We thought the museum was open on Mondays, but unfortunately it was closed.', 'Мы думали, что музей по понедельникам открыт, но, к сожалению, он был закрыт.', 'Ми думали, що музей у понеділок відчинений, але, на жаль, він був зачинений.', 'Müzenin pazartesi günleri açık olduğunu sanıyorduk ama ne yazık ki kapalıydı.']),
    mc('G4', 'Präteritum im Bericht', I.choose, 'Welcher Satz stammt aus einem Zeitungsbericht?', ['Der Dieb floh mit einem Fahrrad.', 'Stell dir vor, der Dieb ist mit einem Fahrrad geflohen!', 'Du, der Dieb ist echt mit dem Fahrrad weg!'],
      ['Which sentence comes from a newspaper report?', 'Какое предложение взято из газетной заметки?', 'Яке речення взято з газетної замітки?', 'Hangi cümle bir gazete haberinden alınmıştır?']),
    mc('G5', 'als', I.choose, '… wir letztes Jahr in Rom waren, haben wir jeden Tag Eis gegessen.', ['Als', 'Wenn', 'Wann'],
      ['When we were in Rome last year, we ate ice cream every day.', 'Когда мы в прошлом году были в Риме, мы каждый день ели мороженое.', 'Коли ми торік були в Римі, ми щодня їли морозиво.', 'Geçen yıl Roma’dayken her gün dondurma yedik.']),
    mc('G6', 'waren ausgezogen', I.choose, 'Die Wohnung war leer. Die Nachbarn … schon vor einer Woche ausgezogen.', ['waren', 'hatten', 'sind'],
      ['The flat was empty. The neighbours had already moved out a week earlier.', 'Квартира была пуста. Соседи выехали ещё неделю назад.', 'Квартира була порожня. Сусіди виїхали ще тиждень тому.', 'Daire boştu. Komşular bir hafta önce taşınmıştı.']),
    mc('K1', 'sich erinnern an', I.react, '„Erinnerst du dich noch an unsere alte Lehrerin?“', ['Ja, natürlich! An sie kann ich mich noch gut erinnern.', 'Ja, ich wünsche ihr gute Besserung.', 'Nein, der Unfall ist erst gestern passiert.'],
      ['“Do you still remember our old teacher?”', '«Ты ещё помнишь нашу старую учительницу?»', '«Ти ще пам’ятаєш нашу стару вчительку?»', '“Eski öğretmenimizi hâlâ hatırlıyor musun?”']),
    mc('K2', 'wurde verletzt', I.choose, 'Bei dem Unfall auf der Autobahn … zum Glück niemand verletzt.', ['wurde', 'hatte', 'machte'],
      ['Luckily nobody was hurt in the accident on the motorway.', 'К счастью, в аварии на автобане никто не пострадал.', 'На щастя, в аварії на автобані ніхто не постраждав.', 'Neyse ki otobandaki kazada kimse yaralanmadı.']),
    mc('Z1', 'Was vergessen?', I.read, `${FINDER} Was hatte der Student am Bahnhof vergessen?`, ['Seinen Rucksack mit Laptop und Ausweis.', 'Einen Blumenstrauß.', 'Sein Taxi.'],
      ['What had the student left behind at the station?', 'Что студент забыл на вокзале?', 'Що студент забув на вокзалі?', 'Öğrenci istasyonda ne unutmuştu?']),
    gap('K3', 'glauben an', I.prep, 'Meine Schwester glaubt fest ', ' ihren Glücksbringer, eine alte Münze.', 'an', ['auf', 'für'],
      ['My sister firmly believes in her lucky charm, an old coin.', 'Моя сестра твёрдо верит в свой талисман – старую монету.', 'Моя сестра твердо вірить у свій талісман – стару монету.', 'Kız kardeşim uğur getiren eski madeni parasına sıkı sıkıya inanıyor.'], 'an / auf / für'),
    gap('K4', 'dir', I.pronoun, 'Du hast morgen deine Führerscheinprüfung? Dann wünsche ich ', ' viel Erfolg!', 'dir', ['dich', 'du'],
      ['You have your driving test tomorrow? Then I wish you every success!', 'У тебя завтра экзамен на права? Тогда желаю тебе успеха!', 'У тебе завтра іспит на права? Тоді бажаю тобі успіху!', 'Yarın ehliyet sınavın mı var? O zaman sana başarılar dilerim!'], 'du'),
    gap('G2', 'verlor', I.verb, 'Auf dem Weg zur Arbeit ', ' ich meinen Geldbeutel, aber eine Frau brachte ihn mir zurück.', 'verlor', ['verlierte', 'verloren'],
      ['On the way to work I lost my purse, but a woman brought it back to me.', 'По дороге на работу я потерял кошелёк, но одна женщина вернула его мне.', 'Дорогою на роботу я загубив гаманець, але одна жінка повернула його мені.', 'İşe giderken cüzdanımı kaybettim ama bir kadın onu bana geri getirdi.'], 'verlieren (Präteritum)'),
  ],
  size: 13,
  test: [
    mc('W1', 'Zufall', I.choose, 'Niemand hat das geplant: Wir haben am selben Tag genau dasselbe Kleid gekauft. Das war ein lustiger …', ['Zufall', 'Schaden', 'Zeuge'],
      ['Nobody planned it: we bought exactly the same dress on the same day. That was a funny …', 'Никто этого не планировал: мы в один день купили совершенно одинаковые платья. Это было забавное …', 'Ніхто цього не планував: ми того самого дня купили однаковісінькі сукні. Це був кумедний …', 'Bunu kimse planlamadı: Aynı gün tıpatıp aynı elbiseyi aldık. Bu komik bir …']),
    mc('G1', 'redeten', I.choose, 'Nach dem Abendessen … wir noch lange über unsere gemeinsame Schulzeit.', ['redeten', 'redten', 'geredet'],
      ['After dinner we talked for a long time about our school days together.', 'После ужина мы ещё долго говорили о наших общих школьных годах.', 'Після вечері ми ще довго говорили про наші спільні шкільні роки.', 'Akşam yemeğinden sonra birlikte geçirdiğimiz okul yılları hakkında uzun uzun konuştuk.']),
    mc('G1', 'übtest', I.choose, '… du früher wirklich jeden Tag drei Stunden Klavier?', ['Übtest', 'Übte', 'Übten'],
      ['Did you really use to practise the piano for three hours every day?', 'Ты раньше правда каждый день по три часа занимался на пианино?', 'Ти раніше справді щодня по три години займався на піаніно?', 'Eskiden gerçekten her gün üç saat piyano çalışır mıydın?']),
    mc('G2', 'begann', I.choose, 'Der Film … um acht Uhr und dauerte fast drei Stunden.', ['begann', 'beginnte', 'begannt'],
      ['The film started at eight o’clock and lasted almost three hours.', 'Фильм начался в восемь часов и шёл почти три часа.', 'Фільм почався о восьмій годині і тривав майже три години.', 'Film saat sekizde başladı ve neredeyse üç saat sürdü.']),
    mc('G2', 'trafen', I.choose, 'Wir … uns zufällig im Supermarkt und redeten eine halbe Stunde vor dem Regal.', ['trafen', 'trefften', 'traf'],
      ['We met by chance in the supermarket and talked for half an hour in front of the shelf.', 'Мы случайно встретились в супермаркете и полчаса проговорили у полки.', 'Ми випадково зустрілися в супермаркеті й пів години проговорили біля полиці.', 'Süpermarkette tesadüfen karşılaştık ve rafın önünde yarım saat konuştuk.']),
    mc('G3', 'kannte', I.choose, 'Meine Großmutter … jeden Baum und jede Blume in ihrem Garten beim Namen.', ['kannte', 'kennte', 'kannten'],
      ['My grandmother knew every tree and every flower in her garden by name.', 'Моя бабушка знала по названию каждое дерево и каждый цветок в своём саду.', 'Моя бабуся знала на назву кожне дерево і кожну квітку у своєму саду.', 'Büyükannem bahçesindeki her ağacı ve her çiçeği adıyla bilirdi.']),
    mc('G3', 'rannte', I.choose, 'Als das Telefon klingelte, … er sofort in den Flur.', ['rannte', 'rennte', 'rannt'],
      ['When the phone rang, he ran into the hall at once.', 'Когда зазвонил телефон, он сразу побежал в коридор.', 'Коли задзвонив телефон, він одразу побіг у коридор.', 'Telefon çaldığında hemen koridora koştu.']),
    mc('G4', 'Perfekt in der Nachricht', I.choose, 'Welcher Satz passt in eine kurze Nachricht an einen guten Freund?', ['Ich habe gestern endlich meine Prüfung bestanden!', 'Der Student bestand gestern seine Prüfung.', 'Der Prüfling verließ gegen Mittag das Gebäude.'],
      ['Which sentence fits in a short message to a good friend?', 'Какое предложение подходит для короткого сообщения хорошему другу?', 'Яке речення підходить для короткого повідомлення доброму другові?', 'Hangi cümle iyi bir arkadaşa yazılan kısa bir mesaja uyar?']),
    mc('G5', 'wenn', I.choose, 'Immer … es im Sommer sehr heiß war, schliefen wir auf dem Balkon.', ['wenn', 'als', 'wann'],
      ['Whenever it was very hot in summer, we slept on the balcony.', 'Всегда, когда летом было очень жарко, мы спали на балконе.', 'Завжди, коли влітку було дуже спекотно, ми спали на балконі.', 'Yazın hava ne zaman çok sıcak olsa balkonda uyurduk.']),
    mc('G5', 'als + Verb am Ende', I.sentence, 'Sara erzählt, wie sie ihren Mann getroffen hat.', ['Als ich in Köln studierte, lernte ich ihn kennen.', 'Wenn ich in Köln studierte, lernte ich ihn kennen.', 'Als ich studierte in Köln, lernte ich ihn kennen.'],
      ['Sara is telling how she met her husband.', 'Sara рассказывает, как она встретила своего мужа.', 'Sara розповідає, як вона зустріла свого чоловіка.', 'Sara kocasıyla nasıl tanıştığını anlatıyor.']),
    mc('G6', 'vergessen hatte', I.choose, 'Ich konnte die Rechnung nicht bezahlen, weil ich mein Geld zu Hause … hatte.', ['vergessen', 'vergaß', 'vergesse'],
      ['I could not pay the bill because I had left my money at home.', 'Я не мог оплатить счёт, потому что забыл деньги дома.', 'Я не міг оплатити рахунок, бо забув гроші вдома.', 'Hesabı ödeyemedim çünkü paramı evde unutmuştum.']),
    mc('G6', 'war geflohen', I.choose, 'Als die Polizei endlich ankam, … der Dieb schon lange geflohen.', ['war', 'hatte', 'wurde'],
      ['When the police finally arrived, the thief had long since fled.', 'Когда полиция наконец приехала, вор уже давно сбежал.', 'Коли поліція нарешті приїхала, злодій уже давно втік.', 'Polis sonunda geldiğinde hırsız çoktan kaçmıştı.']),
    mc('K1', 'fand', I.choose, 'Als Kind … ich es schrecklich, wenn ich schon um sieben ins Bett musste.', ['fand', 'findete', 'dachte'],
      ['As a child I hated it when I had to go to bed as early as seven.', 'В детстве я терпеть не мог, когда приходилось ложиться спать уже в семь.', 'У дитинстві я терпіти не міг, коли доводилося лягати спати вже о сьомій.', 'Çocukken saat yedide yatmak zorunda kalmaktan nefret ederdim.']),
    mc('K2', 'Unfall schildern', I.situation, 'Du erzählst der Polizei von einem Unfall. Womit beginnst du am besten?', ['Der Unfall ist heute gegen zehn Uhr vor dem Bahnhof passiert.', 'Ich glaube nicht an Glücksbringer.', 'Als Kind war ich oft bei meiner Oma.'],
      ['You are telling the police about an accident. What is the best way to begin?', 'Вы рассказываете полиции об аварии. С чего лучше всего начать?', 'Ви розповідаєте поліції про аварію. З чого найкраще почати?', 'Polise bir kazayı anlatıyorsunuz. Nasıl başlamak en iyisidir?']),
    mc('K3', 'Glück bringen', I.choose, 'Opa trägt immer ein Kleeblatt in der Jackentasche. Er sagt, es bringt ihm …', ['Glück', 'Pech', 'Schaden'],
      ['Grandad always carries a clover leaf in his jacket pocket. He says it brings him …', 'Дедушка всегда носит в кармане куртки лист клевера. Он говорит, что тот приносит ему …', 'Дідусь завжди носить у кишені куртки листок конюшини. Він каже, що той приносить йому …', 'Dedem ceketinin cebinde hep bir yonca yaprağı taşır. Onun kendisine … getirdiğini söylüyor.']),
    mc('K4', 'Ich wünsche dir, dass …', I.situation, 'Deine Freundin zieht nächste Woche für ein Jahr nach Kanada. Was sagst du zum Abschied?', ['Ich wünsche dir, dass du dich dort schnell wohlfühlst.', 'Ich wünsche dir gute Besserung.', 'Ich glaube nicht an so etwas.'],
      ['Your friend is moving to Canada for a year next week. What do you say when you say goodbye?', 'Ваша подруга на следующей неделе уезжает на год в Канаду. Что вы скажете на прощание?', 'Ваша подруга наступного тижня їде на рік до Канади. Що ви скажете на прощання?', 'Arkadaşınız gelecek hafta bir yıllığına Kanada’ya taşınıyor. Vedalaşırken ne dersiniz?']),
    mc('Z1', 'Was passierte?', I.read, `${GEWITTER} Was passierte bei dem Gewitter?`, ['Ein Baum fiel auf das Auto.', 'Das Ehepaar verletzte sich.', 'Das Haus wurde beschädigt.'],
      ['What happened in the thunderstorm?', 'Что произошло во время грозы?', 'Що сталося під час грози?', 'Fırtınada ne oldu?']),
    mc('Z1', 'Glück im Unglück', I.read, `${GEWITTER} Warum hatte das Ehepaar „Glück im Unglück“?`, ['Die beiden saßen nicht mehr im Auto.', 'Das Auto blieb ganz.', 'Der Baum fiel auf die Straße.'],
      ['Why was the couple “lucky in their misfortune”?', 'Почему супругам «повезло в несчастье»?', 'Чому подружжю «пощастило в нещасті»?', 'Çift neden “şanssızlık içinde şanslıydı”?']),
    mc('Z1', 'Was machte der Finder?', I.read, `${FINDER} Was machte der Taxifahrer mit dem Rucksack?`, ['Er brachte ihn zur Polizei.', 'Er behielt den Laptop.', 'Er ließ ihn am Bahnhof liegen.'],
      ['What did the taxi driver do with the rucksack?', 'Что таксист сделал с рюкзаком?', 'Що таксист зробив із рюкзаком?', 'Taksi şoförü sırt çantasını ne yaptı?']),
    gap('W1', 'Unfall', I.word, 'Zwei Autos sind an der Kreuzung zusammengestoßen. Der ', ' ist kurz nach sieben Uhr passiert.', 'Unfall', ['Zufall', 'Gewinn'],
      ['Two cars collided at the crossroads. The accident happened shortly after seven o’clock.', 'Две машины столкнулись на перекрёстке. Авария произошла вскоре после семи часов.', 'Дві машини зіткнулися на перехресті. Аварія сталася невдовзі після сьомої години.', 'İki araba kavşakta çarpıştı. Kaza saat yediyi biraz geçe oldu.'],
      ['accident', 'авария', 'аварія', 'kaza']),
    gap('G1', 'spielten', I.verb, 'Die Kinder ', ' den ganzen Nachmittag im Garten, bis es dunkel wurde.', 'spielten', ['spielte', 'spieltet'],
      ['The children played in the garden all afternoon until it got dark.', 'Дети играли в саду всю вторую половину дня, пока не стемнело.', 'Діти гралися в саду всю другу половину дня, доки не стемніло.', 'Çocuklar hava kararana kadar bütün öğleden sonra bahçede oynadı.'], 'spielen (Präteritum)'),
    gap('G2', 'gab', I.verb, 'Sie ', ' ihm die Hand und sagte freundlich „Guten Tag“.', 'gab', ['gebte', 'gabt'],
      ['She shook his hand and said “Guten Tag” in a friendly way.', 'Она подала ему руку и приветливо сказала «Guten Tag».', 'Вона подала йому руку і привітно сказала «Guten Tag».', 'Ona elini uzattı ve güler yüzle “Guten Tag” dedi.'], 'geben (Präteritum)'),
    gap('G3', 'brachte … mit', I.verb, 'Zu jeder Familienfeier ', ' meine Tante einen Apfelkuchen mit.', 'brachte', ['bringte', 'gebracht'],
      ['My aunt brought an apple cake to every family celebration.', 'На каждый семейный праздник моя тётя приносила яблочный пирог.', 'На кожне родинне свято моя тітка приносила яблучний пиріг.', 'Teyzem her aile kutlamasına bir elmalı kek getirirdi.'], 'mitbringen (Präteritum)'),
    gap('G4', 'hat geschrieben → schrieb', I.verb, 'Im Gespräch: „Sie hat einen langen Brief geschrieben.“ Im Bericht: „Sie ', ' einen langen Brief.“', 'schrieb', ['schreibte', 'schrieben'],
      ['In conversation: “Sie hat einen langen Brief geschrieben.” In a report: “She wrote a long letter.”', 'В разговоре: «Sie hat einen langen Brief geschrieben.» В отчёте: «Она написала длинное письмо.»', 'У розмові: «Sie hat einen langen Brief geschrieben.» У звіті: «Вона написала довгого листа.»', 'Konuşmada: “Sie hat einen langen Brief geschrieben.” Raporda: “Uzun bir mektup yazdı.”'], 'schreiben (Präteritum)'),
    gap('G5', 'als', I.conjunction, 'Ich war erst fünf Jahre alt, ', ' wir nach Deutschland zogen.', 'als', ['wenn', 'wann'],
      ['I was only five years old when we moved to Germany.', 'Мне было всего пять лет, когда мы переехали в Германию.', 'Мені було лише п’ять років, коли ми переїхали до Німеччини.', 'Almanya’ya taşındığımızda daha beş yaşındaydım.'], ALS_WENN),
    gap('G6', 'hatte gegessen', I.auxiliary, 'Paul hatte am Abend Bauchschmerzen. Er ', ' vorher zu viele Kirschen gegessen.', 'hatte', ['war', 'hat'],
      ['Paul had a stomach ache in the evening. He had eaten too many cherries beforehand.', 'Вечером у Paul болел живот. До этого он съел слишком много вишен.', 'Увечері в Paul болів живіт. Перед тим він з’їв забагато вишень.', 'Paul’un akşam karnı ağrıyordu. Daha önce çok fazla kiraz yemişti.'], AUX_PAST),
    gap('K1', 'sich erinnern', I.word, 'Daran kann ich mich leider nicht mehr ', '. Es ist einfach zu lange her.', 'erinnern', ['wünschen', 'verletzen'],
      ['Unfortunately I can no longer remember that. It is simply too long ago.', 'К сожалению, я этого уже не могу вспомнить. Это было слишком давно.', 'На жаль, я цього вже не можу згадати. Це було надто давно.', 'Ne yazık ki bunu artık hatırlayamıyorum. Üzerinden çok zaman geçti.'],
      ['remember', 'вспомнить', 'згадати', 'hatırlamak']),
    gap('K2', 'bemerkte', I.verb, 'Der Fahrer ', ' leider nicht, dass ein Kind auf die Straße lief.', 'bemerkte', ['bemerkt', 'bemerkten'],
      ['Unfortunately the driver did not notice that a child was running into the road.', 'К сожалению, водитель не заметил, что на дорогу выбежал ребёнок.', 'На жаль, водій не помітив, що на дорогу вибігла дитина.', 'Sürücü ne yazık ki bir çocuğun yola koştuğunu fark etmedi.'], 'bemerken (Präteritum)'),
    gap('K3', 'Glücksbringer', I.word, 'Ein Hufeisen über der Tür ist für viele Menschen ein ', '.', 'Glücksbringer', ['Pechvogel', 'Zeuge'],
      ['For many people a horseshoe above the door is a lucky charm.', 'Подкова над дверью для многих людей – талисман.', 'Підкова над дверима для багатьох людей – талісман.', 'Kapının üstündeki at nalı birçok insan için uğur getiren bir şeydir.'],
      ['lucky charm', 'талисман', 'талісман', 'uğur getiren şey']),
    gap('K4', 'dass … werdet', I.verb, 'Wir wünschen euch, dass ihr in eurem neuen Haus glücklich ', '.', 'werdet', ['werden', 'wird'],
      ['We hope that you will be happy in your new house.', 'Желаем вам, чтобы вы были счастливы в своём новом доме.', 'Бажаємо вам, щоб ви були щасливі у своєму новому домі.', 'Yeni evinizde mutlu olmanızı dileriz.'], 'werden'),
  ],
}

export default check
