import { I, gap, mc, sb } from '../shared.mjs'

const AUX_PAST = 'haben / sein (Präteritum)'
const ALS_WENN = 'als / wenn'
const LOTTO = 'Zeitungsmeldung: „Großes Glück für eine Rentnerin aus Kassel: Die 68-Jährige kaufte am Freitag wie jede Woche ein Los und gewann eine halbe Million Euro. Als sie von dem Gewinn erfuhr, konnte sie es zuerst nicht glauben. Sie rief sofort ihre Tochter an. Mit dem Geld möchte sie eine lange Reise machen und ihren Enkeln helfen.“'
const RADFAHRER = 'Polizeibericht: „Am Dienstagmorgen passierte in der Gartenstraße ein Unfall. Ein Radfahrer wollte nach links abbiegen und übersah ein Auto. Der Autofahrer bremste sofort, konnte aber nicht mehr anhalten. Der Radfahrer stürzte und verletzte sich leicht am Arm. Ein Krankenwagen brachte ihn ins Krankenhaus. Am Auto entstand nur ein kleiner Schaden.“'

/** B1.1 · Pfad 1 · Glück im Alltag – Lektionen. Wiederholung und Test: p1-check.mjs */
const path = {
  n: 1,
  slug: 'glueck-im-alltag',
  title: 'Glück im Alltag',
  t: ['Everyday luck', 'Счастье в повседневной жизни', 'Щастя в повсякденному житті', 'Gündelik hayatta şans'],
  objectives: {
    G1: 'Präteritum der regelmäßigen Verben: tanken → tankte, landen → landete; ich und er/es/sie haben die gleiche Form.',
    G2: 'Präteritum der unregelmäßigen Verben: lassen → ließ, kommen → kam, gehen → ging, finden → fand; ich und er/es/sie ohne Endung.',
    G3: 'Präteritum der Mischverben: bringen → brachte, denken → dachte, kennen → kannte, wissen → wusste.',
    G4: 'Perfekt oder Präteritum: Im Gespräch erzählt man meist im Perfekt, in Berichten und Nachrichten steht das Präteritum; war, hatte und die Modalverben stehen fast immer im Präteritum.',
    G5: 'als oder wenn in der Vergangenheit: als = einmal (Als ich zehn war, …), wenn = jedes Mal (Immer wenn wir Ferien hatten, …).',
    G6: 'Plusquamperfekt: hatte oder war + Partizip für das, was vorher passiert ist (Ich war müde, weil ich schlecht geschlafen hatte).',
    K1: 'Über die Vergangenheit und die Kindheit reden: Als Kind war ich … Ich kann mich noch gut daran erinnern. Damals …',
    K2: 'Einen Unfall schildern: Der Unfall ist am … in … passiert. Ich bemerkte leider nicht, dass … Zur gleichen Zeit … Daraufhin …',
    K3: 'Über Glücksbringer und Rituale reden: Ich glaube an … Das bringt mir Glück. Ich glaube nicht an so etwas.',
    K4: 'Jemandem etwas wünschen: Ich wünsche dir viel Erfolg. Ich wünsche dir, dass du eine gute Stelle findest.',
    Z1: 'Kann-Ziele: kurze Zeitungsmeldungen und Berichte über Glück, Pech und Unfälle verstehen.',
    W1: 'Wortschatz: Glück, Pech und Unfall.',
  },
  nodes: [
    {
      title: 'Glück und Pech',
      t: ['Good luck and bad luck', 'Удача и невезение', 'Удача і невдача', 'Şans ve şanssızlık'],
      card: {
        id: 'p1_glueck',
        rule: 'Glück und Pech: das Glück ↔ das Pech. Wer oft Glück hat, ist ein Glückspilz; wer oft Pech hat, ist ein Pechvogel. Beim Gewinnspiel kauft man ein Los und hofft auf einen Gewinn: gewinnen ↔ verlieren. Der Zufall: Etwas passiert ohne Plan (zufällig). Rund um den Unfall: Ein Unfall passiert. Der Schaden = etwas ist kaputt. sich verletzen, die Verletzung. Der Zeuge / die Zeugin hat alles gesehen. stürzen = hinfallen, bremsen = langsamer werden oder anhalten, zusammenstoßen = gegeneinander fahren.',
        examples: ['So ein Glück! Ich habe beim Gewinnspiel eine Reise gewonnen.', 'Wir haben uns ganz zufällig am Bahnhof getroffen.', 'Bei dem Unfall hat sich zum Glück niemand verletzt.'],
        highlight: null,
        t: [
          'Good luck and bad luck: das Glück (luck, happiness) ↔ das Pech (bad luck). Someone who is often lucky is a Glückspilz; someone who is often unlucky is a Pechvogel. In a prize draw you buy ein Los (a ticket) and hope for einen Gewinn (a prize): gewinnen (win) ↔ verlieren (lose). Der Zufall (coincidence): something happens without a plan (zufällig = by chance). Around an accident: ein Unfall passiert (an accident happens). Der Schaden (damage) = something is broken. sich verletzen (to get hurt), die Verletzung (injury). Der Zeuge / die Zeugin (witness) saw everything. stürzen = to fall, bremsen = to brake, zusammenstoßen = to collide.',
          'Удача и невезение: das Glück (удача, счастье) ↔ das Pech (невезение). Кому часто везёт, тот Glückspilz (счастливчик); кому часто не везёт, тот Pechvogel (неудачник). В розыгрыше покупают ein Los (лотерейный билет) и надеются на einen Gewinn (выигрыш): gewinnen (выигрывать) ↔ verlieren (проигрывать, терять). Der Zufall (случайность): что-то происходит без плана (zufällig = случайно). Слова об аварии: ein Unfall passiert (происходит авария, несчастный случай). Der Schaden (ущерб) = что-то сломано. sich verletzen (получить травму), die Verletzung (травма). Der Zeuge / die Zeugin (свидетель, свидетельница) всё видел(а). stürzen = упасть, bremsen = тормозить, zusammenstoßen = столкнуться.',
          'Удача і невдача: das Glück (удача, щастя) ↔ das Pech (невдача, невезіння). Кому часто щастить, той Glückspilz (щасливчик); кому часто не щастить, той Pechvogel (невдаха). У розіграші купують ein Los (лотерейний квиток) і сподіваються на einen Gewinn (виграш): gewinnen (вигравати) ↔ verlieren (програвати, губити). Der Zufall (випадковість): щось стається без плану (zufällig = випадково). Слова про аварію: ein Unfall passiert (стається аварія, нещасний випадок). Der Schaden (шкода, збитки) = щось зламано. sich verletzen (травмуватися), die Verletzung (травма). Der Zeuge / die Zeugin (свідок, свідка) все бачив (бачила). stürzen = впасти, bremsen = гальмувати, zusammenstoßen = зіткнутися.',
          'Şans ve şanssızlık: das Glück (şans, mutluluk) ↔ das Pech (şanssızlık). Sık sık şansı yaver giden kişi Glückspilz, sık sık şanssızlık yaşayan kişi Pechvogel’dir. Çekilişte ein Los (bilet) alınır ve einen Gewinn (ikramiye) umulur: gewinnen (kazanmak) ↔ verlieren (kaybetmek). Der Zufall (tesadüf): Bir şey plansız olur (zufällig = tesadüfen). Kazayla ilgili kelimeler: ein Unfall passiert (bir kaza olur). Der Schaden (hasar) = bir şey bozuk. sich verletzen (yaralanmak), die Verletzung (yaralanma). Der Zeuge / die Zeugin (tanık) her şeyi görmüştür. stürzen = düşmek, bremsen = fren yapmak, zusammenstoßen = çarpışmak.',
        ],
        hint: ['Glück ↔ Pech, gewinnen ↔ verlieren. Zufall = ohne Plan. Schaden = etwas ist kaputt. Zeuge = hat es gesehen.', 'Glück ↔ Pech, gewinnen ↔ verlieren. Zufall = without a plan. Schaden = something is broken. Zeuge = saw it happen.', 'Glück ↔ Pech, gewinnen ↔ verlieren. Zufall = без плана. Schaden = что-то сломано. Zeuge = тот, кто это видел.', 'Glück ↔ Pech, gewinnen ↔ verlieren. Zufall = без плану. Schaden = щось зламано. Zeuge = той, хто це бачив.', 'Glück ↔ Pech, gewinnen ↔ verlieren. Zufall = plansız. Schaden = bir şey bozuk. Zeuge = olayı gören kişi.'],
      },
      ex: [
        mc('W1', 'Glückspilz', I.choose, 'Mia findet auf der Straße 50 Euro und gewinnt am selben Tag eine Reise. Sie ist ein richtiger …', ['Glückspilz', 'Pechvogel', 'Zeuge'],
          ['Mia finds 50 euros in the street and wins a trip on the same day. She is a real …', 'Mia находит на улице 50 евро и в тот же день выигрывает путешествие. Она настоящий …', 'Mia знаходить на вулиці 50 євро і того ж дня виграє подорож. Вона справжній …', 'Mia sokakta 50 avro buluyor ve aynı gün bir gezi kazanıyor. O gerçek bir …']),
        mc('W1', 'Pech', I.choose, 'Erst verpasst Jonas den Bus, dann verliert er auch noch seinen Schlüssel. Heute hat er wirklich …', ['Pech', 'Glück', 'Gewinn'],
          ['First Jonas misses the bus, then he loses his key as well. Today he really has …', 'Сначала Jonas опаздывает на автобус, потом ещё и теряет ключ. Сегодня у него действительно …', 'Спочатку Jonas запізнюється на автобус, потім ще й губить ключ. Сьогодні йому справді …', 'Jonas önce otobüsü kaçırıyor, sonra bir de anahtarını kaybediyor. Bugün gerçekten …']),
        mc('W1', 'Zufall', I.choose, 'Wir hatten uns nicht verabredet. Dass wir im selben Zug saßen, war reiner …', ['Zufall', 'Schaden', 'Unfall'],
          ['We had not arranged to meet. The fact that we were sitting on the same train was pure …', 'Мы не договаривались о встрече. То, что мы сидели в одном поезде, было чистой …', 'Ми не домовлялися про зустріч. Те, що ми сиділи в одному поїзді, було чистою …', 'Buluşmak için sözleşmemiştik. Aynı trende oturmamız tamamen …']),
        mc('W1', 'Unfall', I.odd, 'Drei Wörter passen zum Thema Unfall, ein Wort nicht.', ['das Los', 'der Schaden', 'die Verletzung', 'der Zeuge'], null),
        mc('W1', 'Zeugin', I.choose, 'Frau Berger hat den Unfall genau gesehen und erzählt der Polizei, was passiert ist. Sie ist eine …', ['Zeugin', 'Gewinnerin', 'Verkäuferin'],
          ['Ms Berger saw the accident clearly and tells the police what happened. She is a …', 'Госпожа Berger хорошо видела аварию и рассказывает полиции, что произошло. Она …', 'Пані Berger добре бачила аварію і розповідає поліції, що сталося. Вона …', 'Bayan Berger kazayı net olarak gördü ve polise ne olduğunu anlatıyor. O bir …']),
        gap('W1', 'Los', I.word, 'Für das Gewinnspiel habe ich ein ', ' gekauft, aber leider nichts gewonnen.', 'Los', ['Pech', 'Glück'],
          ['I bought a ticket for the prize draw, but unfortunately I won nothing.', 'Я купил лотерейный билет для розыгрыша, но, к сожалению, ничего не выиграл.', 'Я купив лотерейний квиток для розіграшу, але, на жаль, нічого не виграв.', 'Çekiliş için bir bilet aldım ama ne yazık ki hiçbir şey kazanmadım.'],
          ['lottery ticket', 'лотерейный билет', 'лотерейний квиток', 'piyango bileti']),
        gap('W1', 'Schaden', I.word, 'Nach dem Unfall war die Tür kaputt. Der ', ' am Auto kostet etwa 800 Euro.', 'Schaden', ['Zufall', 'Gewinn'],
          ['After the accident the door was broken. The damage to the car costs about 800 euros.', 'После аварии дверь была сломана. Ущерб автомобилю составляет около 800 евро.', 'Після аварії двері були зламані. Шкода автомобілю становить близько 800 євро.', 'Kazadan sonra kapı bozuktu. Arabadaki hasar yaklaşık 800 avro tutuyor.'],
          ['damage', 'ущерб', 'шкода, збитки', 'hasar']),
        gap('W1', 'verletzt', I.word, 'Der Radfahrer ist gestürzt und hat sich am Knie ', '.', 'verletzt', ['verloren', 'gewonnen'],
          ['The cyclist fell and hurt his knee.', 'Велосипедист упал и травмировал колено.', 'Велосипедист упав і травмував коліно.', 'Bisikletli düştü ve dizini yaraladı.'],
          ['hurt, injured', 'травмировал, поранил', 'травмував, поранив', 'yaraladı']),
        gap('W1', 'gewonnen', I.participle, 'Stell dir vor: Mein Onkel hat im Lotto 10 000 Euro ', '!', 'gewonnen', ['gewinnt', 'gewinnen'],
          ['Just imagine: my uncle has won 10,000 euros in the lottery!', 'Представь себе: мой дядя выиграл в лотерею 10 000 евро!', 'Уяви собі: мій дядько виграв у лотерею 10 000 євро!', 'Düşünsene: Amcam lotoda 10.000 avro kazandı!'], 'gewinnen'),
        sb('W1', 'zum Glück', I.order, 'Zum Glück / hat / sich / niemand / verletzt.',
          ['Luckily nobody got hurt.', 'К счастью, никто не пострадал.', 'На щастя, ніхто не постраждав.', 'Neyse ki kimse yaralanmadı.'],
          { alt: ['Niemand hat sich zum Glück verletzt.'] }),
      ],
    },
    {
      title: 'tankte, landete, wartete',
      t: ['tankte, landete, wartete (Präteritum of regular verbs)', 'tankte, landete, wartete (Präteritum правильных глаголов)', 'tankte, landete, wartete (Präteritum правильних дієслів)', 'tankte, landete, wartete (düzenli fiillerin Präteritum’u)'],
      card: {
        id: 'p1_regelmaessig',
        rule: 'Präteritum der regelmäßigen Verben: Verbstamm + -te + Endung. tanken → ich tankte, du tanktest, er/es/sie tankte, wir tankten, ihr tanktet, sie/Sie tankten. ich und er/es/sie haben die gleiche Form. Endet der Stamm auf -d oder -t, kommt ein e dazu: landen → landete, warten → wartete, arbeiten → arbeitete. Trennbare Verben werden getrennt: einkaufen → er kaufte ein. Das Präteritum liest man vor allem in Berichten, in der Zeitung und in Büchern.',
        examples: ['Der Mann tankte und fuhr dann weiter.', 'Das Flugzeug landete pünktlich in Wien.', 'Wir warteten zwei Stunden auf den Zug.'],
        highlight: 'verb',
        t: [
          'Präteritum (simple past) of regular verbs: verb stem + -te + ending. tanken (to fill up) → ich tankte, du tanktest, er/es/sie tankte, wir tankten, ihr tanktet, sie/Sie tankten. ich and er/es/sie have the same form. If the stem ends in -d or -t, an e is added: landen → landete, warten → wartete, arbeiten → arbeitete. Separable verbs are split: einkaufen → er kaufte ein. You mostly read the Präteritum in reports, newspapers and books.',
          'Präteritum правильных глаголов: основа глагола + -te + окончание. tanken (заправляться) → ich tankte, du tanktest, er/es/sie tankte, wir tankten, ihr tanktet, sie/Sie tankten. У ich и er/es/sie одинаковая форма. Если основа оканчивается на -d или -t, добавляется e: landen → landete, warten → wartete, arbeiten → arbeitete. Отделяемые глаголы разделяются: einkaufen → er kaufte ein. Präteritum встречается прежде всего в сообщениях, газетах и книгах.',
          'Präteritum правильних дієслів: основа дієслова + -te + закінчення. tanken (заправлятися) → ich tankte, du tanktest, er/es/sie tankte, wir tankten, ihr tanktet, sie/Sie tankten. В ich та er/es/sie однакова форма. Якщо основа закінчується на -d або -t, додається e: landen → landete, warten → wartete, arbeiten → arbeitete. Відокремлювані дієслова розділяються: einkaufen → er kaufte ein. Präteritum трапляється передусім у повідомленнях, газетах і книжках.',
          'Düzenli fiillerin Präteritum’u (geçmiş zaman): fiil kökü + -te + çekim eki. tanken (benzin almak) → ich tankte, du tanktest, er/es/sie tankte, wir tankten, ihr tanktet, sie/Sie tankten. ich ve er/es/sie aynı biçimi alır. Kök -d ya da -t ile bitiyorsa araya e girer: landen → landete, warten → wartete, arbeiten → arbeitete. Ayrılabilen fiiller ayrılır: einkaufen → er kaufte ein. Präteritum özellikle haberlerde, gazetelerde ve kitaplarda okunur.',
        ],
        hint: ['Stamm + -te: tankte, tanktest, tankte, tankten, tanktet, tankten. Nach d/t: -ete (landete, wartete).', 'Stem + -te: tankte, tanktest, tankte, tankten, tanktet, tankten. After d/t: -ete (landete, wartete).', 'Основа + -te: tankte, tanktest, tankte, tankten, tanktet, tankten. После d/t: -ete (landete, wartete).', 'Основа + -te: tankte, tanktest, tankte, tankten, tanktet, tankten. Після d/t: -ete (landete, wartete).', 'Kök + -te: tankte, tanktest, tankte, tankten, tanktet, tankten. d/t’den sonra: -ete (landete, wartete).'],
      },
      ex: [
        mc('G1', 'tankte', I.choose, 'Letzten Sommer … Herr Wolf jeden Montag an derselben Tankstelle.', ['tankte', 'tankten', 'getankt'],
          ['Last summer Mr Wolf filled up at the same petrol station every Monday.', 'Прошлым летом господин Wolf каждый понедельник заправлялся на одной и той же заправке.', 'Минулого літа пан Wolf щопонеділка заправлявся на тій самій заправці.', 'Geçen yaz Bay Wolf her pazartesi aynı benzin istasyonundan benzin aldı.']),
        mc('G1', 'landete', I.choose, 'Das Flugzeug aus Istanbul … gestern mit zwei Stunden Verspätung.', ['landete', 'landte', 'landeten'],
          ['The plane from Istanbul landed two hours late yesterday.', 'Самолёт из Стамбула вчера приземлился с опозданием на два часа.', 'Літак зі Стамбула вчора приземлився із запізненням на дві години.', 'İstanbul’dan gelen uçak dün iki saat gecikmeyle indi.']),
        mc('G1', 'arbeiteten', I.choose, 'Meine Großeltern … früher beide in einer Fabrik am Stadtrand.', ['arbeiteten', 'arbeitete', 'arbeitetet'],
          ['My grandparents both used to work in a factory on the edge of town.', 'Мои бабушка и дедушка раньше оба работали на фабрике на окраине города.', 'Мої бабуся й дідусь раніше обоє працювали на фабриці на околиці міста.', 'Büyükannemle büyükbabam eskiden ikisi de şehrin kenarındaki bir fabrikada çalışırdı.']),
        mc('G1', 'wohntest', I.choose, 'Du … doch früher auch in Leipzig, oder?', ['wohntest', 'wohnte', 'wohntet'],
          ['You used to live in Leipzig too, didn’t you?', 'Ты ведь раньше тоже жил в Лейпциге, да?', 'Ти ж раніше теж жив у Лейпцигу, так?', 'Sen de eskiden Leipzig’de oturuyordun, değil mi?']),
        mc('G1', 'trennbar: kaufte … ein', I.sentence, 'Olga schreibt über ihren Samstag.', ['Am Samstag kaufte sie auf dem Markt ein.', 'Am Samstag einkaufte sie auf dem Markt.', 'Am Samstag kaufte ein sie auf dem Markt.'],
          ['Olga is writing about her Saturday.', 'Olga пишет о своей субботе.', 'Olga пише про свою суботу.', 'Olga cumartesi gününü yazıyor.']),
        gap('G1', 'wartete', I.verb, 'Ich ', ' fast eine Stunde im Regen, aber der Bus kam nicht.', 'wartete', ['wartet', 'warteten'],
          ['I waited in the rain for almost an hour, but the bus did not come.', 'Я ждал под дождём почти час, но автобус так и не пришёл.', 'Я чекав під дощем майже годину, але автобус так і не приїхав.', 'Yağmurda neredeyse bir saat bekledim ama otobüs gelmedi.'], 'warten (Präteritum)'),
        gap('G1', 'machten', I.verb, 'In den Ferien ', ' wir jeden Tag eine lange Wanderung durch den Wald.', 'machten', ['machte', 'machtet'],
          ['During the holidays we went on a long hike through the forest every day.', 'На каникулах мы каждый день ходили в долгий поход по лесу.', 'На канікулах ми щодня ходили в довгий похід лісом.', 'Tatilde her gün ormanda uzun bir yürüyüş yapardık.'], 'machen (Präteritum)'),
        gap('G1', 'lernte … kennen', I.verb, 'Auf dieser Reise ', ' mein Bruder seine spätere Frau kennen.', 'lernte', ['lernten', 'lernt'],
          ['On this trip my brother met his future wife.', 'В этой поездке мой брат познакомился со своей будущей женой.', 'У цій подорожі мій брат познайомився зі своєю майбутньою дружиною.', 'Kardeşim bu gezide müstakbel eşiyle tanıştı.'], 'kennenlernen (Präteritum)'),
        gap('G1', 'öffnete', I.verb, 'Die Verkäuferin ', ' die Tür und begrüßte die ersten Kunden.', 'öffnete', ['öffnte', 'öffneten'],
          ['The shop assistant opened the door and greeted the first customers.', 'Продавщица открыла дверь и поприветствовала первых покупателей.', 'Продавчиня відчинила двері й привітала перших покупців.', 'Satıcı kapıyı açtı ve ilk müşterileri selamladı.'], 'öffnen (Präteritum)'),
        sb('G1', 'holte', I.order, 'Nach dem Essen / holte / der Kellner / die Rechnung.',
          ['After the meal the waiter fetched the bill.', 'После еды официант принёс счёт.', 'Після їжі офіціант приніс рахунок.', 'Yemekten sonra garson hesabı getirdi.'],
          { alt: ['Der Kellner holte nach dem Essen die Rechnung.', 'Der Kellner holte die Rechnung nach dem Essen.', 'Die Rechnung holte der Kellner nach dem Essen.'] }),
      ],
    },
    {
      title: 'ließ, kam, fand',
      t: ['ließ, kam, fand (Präteritum of irregular verbs)', 'ließ, kam, fand (Präteritum неправильных глаголов)', 'ließ, kam, fand (Präteritum неправильних дієслів)', 'ließ, kam, fand (düzensiz fiillerin Präteritum’u)'],
      card: {
        id: 'p1_unregelmaessig',
        rule: 'Präteritum der unregelmäßigen Verben: Der Vokal im Stamm ändert sich, es gibt kein -te. ich und er/es/sie haben keine Endung: lassen → ich ließ, du ließest, er ließ, wir ließen, ihr ließt, sie ließen. Wichtige Formen: kommen → kam, gehen → ging, finden → fand, gewinnen → gewann, fallen → fiel, sehen → sah, fahren → fuhr, rufen → rief, lesen → las, bleiben → blieb, nehmen → nahm, geben → gab, schreiben → schrieb, beginnen → begann, treffen → traf, verlieren → verlor. Diese Formen muss man lernen.',
        examples: ['Er ließ den Schlüssel fallen.', 'Wir kamen erst nach Mitternacht nach Hause.', 'Sie fand das Geld auf der Straße.'],
        highlight: 'verb',
        t: [
          'Präteritum of irregular verbs: the vowel of the stem changes and there is no -te. ich and er/es/sie have no ending: lassen → ich ließ, du ließest, er ließ, wir ließen, ihr ließt, sie ließen. Important forms: kommen → kam, gehen → ging, finden → fand, gewinnen → gewann, fallen → fiel, sehen → sah, fahren → fuhr, rufen → rief, lesen → las, bleiben → blieb, nehmen → nahm, geben → gab, schreiben → schrieb, beginnen → begann, treffen → traf, verlieren → verlor. These forms have to be learned by heart.',
          'Präteritum неправильных глаголов: гласная в основе меняется, суффикса -te нет. У ich и er/es/sie нет окончания: lassen → ich ließ, du ließest, er ließ, wir ließen, ihr ließt, sie ließen. Важные формы: kommen → kam, gehen → ging, finden → fand, gewinnen → gewann, fallen → fiel, sehen → sah, fahren → fuhr, rufen → rief, lesen → las, bleiben → blieb, nehmen → nahm, geben → gab, schreiben → schrieb, beginnen → begann, treffen → traf, verlieren → verlor. Эти формы нужно выучить.',
          'Präteritum неправильних дієслів: голосна в основі змінюється, суфікса -te немає. В ich та er/es/sie немає закінчення: lassen → ich ließ, du ließest, er ließ, wir ließen, ihr ließt, sie ließen. Важливі форми: kommen → kam, gehen → ging, finden → fand, gewinnen → gewann, fallen → fiel, sehen → sah, fahren → fuhr, rufen → rief, lesen → las, bleiben → blieb, nehmen → nahm, geben → gab, schreiben → schrieb, beginnen → begann, treffen → traf, verlieren → verlor. Ці форми треба вивчити.',
          'Düzensiz fiillerin Präteritum’u: Kökteki ünlü değişir, -te eki gelmez. ich ve er/es/sie ek almaz: lassen → ich ließ, du ließest, er ließ, wir ließen, ihr ließt, sie ließen. Önemli biçimler: kommen → kam, gehen → ging, finden → fand, gewinnen → gewann, fallen → fiel, sehen → sah, fahren → fuhr, rufen → rief, lesen → las, bleiben → blieb, nehmen → nahm, geben → gab, schreiben → schrieb, beginnen → begann, treffen → traf, verlieren → verlor. Bu biçimlerin ezberlenmesi gerekir.',
        ],
        hint: ['Neuer Vokal, kein -te: kam, ging, fand, ließ, fiel. ich = er: ohne Endung. wir/sie: -en (kamen).', 'New vowel, no -te: kam, ging, fand, ließ, fiel. ich = er: no ending. wir/sie: -en (kamen).', 'Новая гласная, без -te: kam, ging, fand, ließ, fiel. ich = er: без окончания. wir/sie: -en (kamen).', 'Нова голосна, без -te: kam, ging, fand, ließ, fiel. ich = er: без закінчення. wir/sie: -en (kamen).', 'Yeni ünlü, -te yok: kam, ging, fand, ließ, fiel. ich = er: eksiz. wir/sie: -en (kamen).'],
      },
      ex: [
        mc('G2', 'ließ', I.choose, 'Der Dieb … die Tasche fallen und lief schnell weg.', ['ließ', 'lasste', 'ließt'],
          ['The thief dropped the bag and ran away quickly.', 'Вор уронил сумку и быстро убежал.', 'Злодій упустив сумку і швидко втік.', 'Hırsız çantayı düşürdü ve hızla kaçtı.']),
        mc('G2', 'kam', I.choose, 'Als der Zug endlich …, waren wir schon ganz durchgefroren.', ['kam', 'kamte', 'kommte'],
          ['When the train finally came, we were already frozen through.', 'Когда поезд наконец пришёл, мы уже совсем замёрзли.', 'Коли поїзд нарешті приїхав, ми вже зовсім змерзли.', 'Tren sonunda geldiğinde iyice donmuştuk.']),
        mc('G2', 'fand', I.choose, 'Ich … den Ring erst nach einer Stunde unter dem Sofa.', ['fand', 'findete', 'fandet'],
          ['I only found the ring under the sofa after an hour.', 'Я нашёл кольцо под диваном только через час.', 'Я знайшов каблучку під диваном лише за годину.', 'Yüzüğü ancak bir saat sonra kanepenin altında buldum.']),
        mc('G2', 'gingen', I.choose, 'Wir … schon um sechs Uhr los, weil der Weg zum Gipfel so weit war.', ['gingen', 'gingt', 'gehten'],
          ['We set off as early as six o’clock because the way to the summit was so long.', 'Мы вышли уже в шесть часов, потому что путь до вершины был очень далёким.', 'Ми вирушили вже о шостій, бо шлях до вершини був дуже далекий.', 'Zirveye giden yol çok uzun olduğu için saat altıda yola çıktık.']),
        mc('G2', 'sahst', I.choose, 'Warum … du mich gestern auf dem Marktplatz nicht? Ich habe dir doch gewinkt!', ['sahst', 'sah', 'sehtest'],
          ['Why didn’t you see me in the market square yesterday? I waved at you!', 'Почему ты вчера не увидел меня на рыночной площади? Я же тебе махал!', 'Чому ти вчора не побачив мене на ринковій площі? Я ж тобі махав!', 'Dün pazar meydanında beni neden görmedin? Sana el salladım ya!']),
        gap('G2', 'gewann', I.verb, 'Die Mannschaft ', ' das Spiel mit 3:1 und alle feierten bis in die Nacht.', 'gewann', ['gewinnte', 'gewonnen'],
          ['The team won the match 3–1 and everyone celebrated late into the night.', 'Команда выиграла матч со счётом 3:1, и все праздновали до ночи.', 'Команда виграла матч із рахунком 3:1, і всі святкували до ночі.', 'Takım maçı 3-1 kazandı ve herkes gece yarısına kadar kutlama yaptı.'], 'gewinnen (Präteritum)'),
        gap('G2', 'fiel', I.verb, 'Der Junge ', ' vom Fahrrad, stand aber sofort wieder auf.', 'fiel', ['fallte', 'fielt'],
          ['The boy fell off his bike but got up again straight away.', 'Мальчик упал с велосипеда, но сразу же встал.', 'Хлопчик упав із велосипеда, але одразу підвівся.', 'Çocuk bisikletten düştü ama hemen ayağa kalktı.'], 'fallen (Präteritum)'),
        gap('G2', 'las', I.verb, 'Mein Großvater ', ' jeden Morgen eine Stunde lang die Zeitung.', 'las', ['leste', 'lies'],
          ['My grandfather read the newspaper for an hour every morning.', 'Мой дедушка каждое утро целый час читал газету.', 'Мій дідусь щоранку цілу годину читав газету.', 'Dedem her sabah bir saat boyunca gazete okurdu.'], 'lesen (Präteritum)'),
        gap('G2', 'fuhren', I.verb, 'Nach dem Konzert ', ' wir mit dem letzten Bus nach Hause.', 'fuhren', ['fahrten', 'fuhrt'],
          ['After the concert we took the last bus home.', 'После концерта мы поехали домой на последнем автобусе.', 'Після концерту ми поїхали додому останнім автобусом.', 'Konserden sonra son otobüsle eve gittik.'], 'fahren (Präteritum)'),
        sb('G2', 'rief … an', I.order, 'Am Abend / rief / mich / meine Schwester / an.',
          ['In the evening my sister called me.', 'Вечером мне позвонила сестра.', 'Увечері мені зателефонувала сестра.', 'Akşam kız kardeşim beni aradı.'],
          { alt: ['Meine Schwester rief mich am Abend an.', 'Am Abend rief meine Schwester mich an.'] }),
      ],
    },
    {
      title: 'brachte, dachte, wusste',
      t: ['brachte, dachte, wusste (Präteritum of mixed verbs)', 'brachte, dachte, wusste (Präteritum смешанных глаголов)', 'brachte, dachte, wusste (Präteritum мішаних дієслів)', 'brachte, dachte, wusste (karma fiillerin Präteritum’u)'],
      card: {
        id: 'p1_mischverben',
        rule: 'Präteritum der Mischverben: Der Vokal ändert sich wie bei den unregelmäßigen Verben, aber die Endung ist -te wie bei den regelmäßigen. bringen → ich brachte, du brachtest, er brachte, wir brachten, ihr brachtet, sie brachten. Ebenso: denken → dachte, kennen → kannte, nennen → nannte, rennen → rannte, brennen → brannte, wissen → wusste, verbringen → verbrachte, mitbringen → brachte … mit.',
        examples: ['Sie brachte mir einen Kaffee.', 'Ich dachte, du bist schon zu Hause.', 'Wir wussten nicht, wo der Bahnhof war.'],
        highlight: 'verb',
        t: [
          'Präteritum of mixed verbs: the vowel changes as with irregular verbs, but the ending is -te as with regular verbs. bringen (bring) → ich brachte, du brachtest, er brachte, wir brachten, ihr brachtet, sie brachten. Likewise: denken (think) → dachte, kennen (know) → kannte, nennen (call, name) → nannte, rennen (run) → rannte, brennen (burn) → brannte, wissen (know) → wusste, verbringen (spend time) → verbrachte, mitbringen → brachte … mit.',
          'Präteritum смешанных глаголов: гласная меняется, как у неправильных глаголов, но окончание -te, как у правильных. bringen (приносить) → ich brachte, du brachtest, er brachte, wir brachten, ihr brachtet, sie brachten. Так же: denken (думать) → dachte, kennen (знать) → kannte, nennen (называть) → nannte, rennen (бежать) → rannte, brennen (гореть) → brannte, wissen (знать) → wusste, verbringen (проводить время) → verbrachte, mitbringen → brachte … mit.',
          'Präteritum мішаних дієслів: голосна змінюється, як у неправильних дієслів, але закінчення -te, як у правильних. bringen (приносити) → ich brachte, du brachtest, er brachte, wir brachten, ihr brachtet, sie brachten. Так само: denken (думати) → dachte, kennen (знати) → kannte, nennen (називати) → nannte, rennen (бігти) → rannte, brennen (горіти) → brannte, wissen (знати) → wusste, verbringen (проводити час) → verbrachte, mitbringen → brachte … mit.',
          'Karma fiillerin Präteritum’u: Ünlü, düzensiz fiillerdeki gibi değişir, ama ek düzenli fiillerdeki gibi -te’dir. bringen (getirmek) → ich brachte, du brachtest, er brachte, wir brachten, ihr brachtet, sie brachten. Aynı şekilde: denken (düşünmek) → dachte, kennen (tanımak) → kannte, nennen (adlandırmak) → nannte, rennen (koşmak) → rannte, brennen (yanmak) → brannte, wissen (bilmek) → wusste, verbringen (zaman geçirmek) → verbrachte, mitbringen → brachte … mit.',
        ],
        hint: ['Neuer Vokal + -te: brachte, dachte, kannte, nannte, rannte, wusste.', 'New vowel + -te: brachte, dachte, kannte, nannte, rannte, wusste.', 'Новая гласная + -te: brachte, dachte, kannte, nannte, rannte, wusste.', 'Нова голосна + -te: brachte, dachte, kannte, nannte, rannte, wusste.', 'Yeni ünlü + -te: brachte, dachte, kannte, nannte, rannte, wusste.'],
      },
      ex: [
        mc('G3', 'brachte', I.choose, 'Der Kellner … uns die falsche Suppe, aber sie schmeckte trotzdem gut.', ['brachte', 'bringte', 'brang'],
          ['The waiter brought us the wrong soup, but it tasted good all the same.', 'Официант принёс нам не тот суп, но он всё равно был вкусным.', 'Офіціант приніс нам не той суп, але він усе одно був смачний.', 'Garson bize yanlış çorbayı getirdi ama yine de lezzetliydi.']),
        mc('G3', 'dachte', I.choose, 'Ich …, dass der Kurs erst um neun beginnt, und kam deshalb zu spät.', ['dachte', 'denkte', 'dacht'],
          ['I thought the course did not start until nine, and so I arrived late.', 'Я думал, что курс начинается только в девять, и поэтому опоздал.', 'Я думав, що курс починається лише о дев’ятій, і тому запізнився.', 'Kursun ancak dokuzda başladığını sanıyordum, bu yüzden geç kaldım.']),
        mc('G3', 'wusste', I.choose, 'Niemand im Büro …, wo der Schlüssel für den Besprechungsraum war.', ['wusste', 'wisste', 'weißte'],
          ['Nobody in the office knew where the key to the meeting room was.', 'Никто в офисе не знал, где ключ от переговорной.', 'Ніхто в офісі не знав, де ключ від кімнати для нарад.', 'Ofiste kimse toplantı odasının anahtarının nerede olduğunu bilmiyordu.']),
        mc('G3', 'kannte', I.choose, 'Als Kind … ich alle Lieder aus dem Radio auswendig.', ['kannte', 'kennte', 'kannt'],
          ['As a child I knew all the songs on the radio by heart.', 'В детстве я знал наизусть все песни, которые звучали по радио.', 'У дитинстві я знав напам’ять усі пісні, що звучали по радіо.', 'Çocukken radyodaki bütün şarkıları ezbere bilirdim.']),
        mc('G3', 'rannten', I.sentence, 'Plötzlich begann es stark zu regnen. Was machten die Kinder?', ['Die Kinder rannten schnell ins Haus.', 'Die Kinder rennten schnell ins Haus.', 'Die Kinder gerannt schnell ins Haus.'],
          ['Suddenly it started to rain heavily. What did the children do?', 'Вдруг начался сильный дождь. Что сделали дети?', 'Раптом почався сильний дощ. Що зробили діти?', 'Birden şiddetli yağmur başladı. Çocuklar ne yaptı?']),
        gap('G3', 'verbrachten', I.verb, 'Wir ', ' den ganzen Sommer bei unseren Großeltern auf dem Land.', 'verbrachten', ['verbringten', 'verbracht'],
          ['We spent the whole summer with our grandparents in the country.', 'Мы провели всё лето у бабушки и дедушки в деревне.', 'Ми провели все літо в бабусі й дідуся в селі.', 'Bütün yazı köyde büyükannemle büyükbabamın yanında geçirdik.'], 'verbringen (Präteritum)'),
        gap('G3', 'nannten', I.verb, 'Meine Eltern ', ' mich Katharina, aber alle sagten nur Kati zu mir.', 'nannten', ['nennten', 'genannt'],
          ['My parents named me Katharina, but everyone just called me Kati.', 'Родители назвали меня Katharina, но все звали меня просто Kati.', 'Батьки назвали мене Katharina, але всі казали на мене просто Kati.', 'Annemle babam bana Katharina adını verdi ama herkes bana sadece Kati derdi.'], 'nennen (Präteritum)'),
        gap('G3', 'wusste', I.verb, 'Entschuldigung, ich ', ' nicht, dass dieser Platz schon besetzt ist.', 'wusste', ['wisste', 'wussten'],
          ['Sorry, I did not know that this seat is already taken.', 'Извините, я не знал, что это место уже занято.', 'Вибачте, я не знав, що це місце вже зайняте.', 'Affedersiniz, bu yerin dolu olduğunu bilmiyordum.'], 'wissen (Präteritum)'),
        gap('G3', 'brannte', I.verb, 'In der Küche ', ' noch Licht, also war sicher jemand zu Hause.', 'brannte', ['brennte', 'gebrannt'],
          ['The light was still on in the kitchen, so somebody was surely at home.', 'На кухне ещё горел свет, значит, кто-то точно был дома.', 'На кухні ще горіло світло, отже, хтось точно був удома.', 'Mutfakta hâlâ ışık yanıyordu, demek ki evde kesinlikle biri vardı.'], 'brennen (Präteritum)'),
        sb('G3', 'brachte … mit', I.order, 'Jeden Sonntag / brachte / er / seiner Mutter Blumen / mit.',
          ['Every Sunday he brought his mother flowers.', 'Каждое воскресенье он приносил маме цветы.', 'Щонеділі він приносив мамі квіти.', 'Her pazar annesine çiçek getirirdi.'],
          { alt: ['Er brachte jeden Sonntag seiner Mutter Blumen mit.', 'Er brachte seiner Mutter Blumen jeden Sonntag mit.'] }),
      ],
    },
    {
      title: 'Erzählen oder berichten?',
      t: ['Telling or reporting? (Perfekt or Präteritum)', 'Рассказ или сообщение? (Perfekt или Präteritum)', 'Розповідь чи повідомлення? (Perfekt чи Präteritum)', 'Anlatmak mı, bildirmek mi? (Perfekt ya da Präteritum)'],
      card: {
        id: 'p1_perfekt_praeteritum',
        rule: 'Perfekt oder Präteritum? Beide Zeiten sprechen über die Vergangenheit. Im Gespräch, in Chats und in persönlichen E-Mails benutzt man meistens das Perfekt: Ich habe geholfen. Wir sind gekommen. In der Zeitung, in den Nachrichten, in Berichten und in Büchern steht meistens das Präteritum: Er half. Sie kamen. Bei sein, haben und den Modalverben nimmt man auch im Gespräch fast immer das Präteritum: ich war, ich hatte, ich wollte, ich konnte, ich musste.',
        examples: ['Im Gespräch: Gestern habe ich im Supermarkt meinen alten Lehrer getroffen.', 'In der Zeitung: Die Polizei fand das Auto am Abend.', 'Immer so: Ich war krank und konnte nicht kommen.'],
        highlight: 'verb',
        t: [
          'Perfekt or Präteritum? Both tenses talk about the past. In conversation, in chats and in personal e-mails people mostly use the Perfekt: Ich habe geholfen. Wir sind gekommen. In newspapers, in the news, in reports and in books you mostly find the Präteritum: Er half. Sie kamen. With sein, haben and the modal verbs the Präteritum is almost always used in conversation too: ich war, ich hatte, ich wollte, ich konnte, ich musste.',
          'Perfekt или Präteritum? Оба времени говорят о прошлом. В разговоре, в чатах и личных письмах обычно используют Perfekt: Ich habe geholfen. Wir sind gekommen. В газетах, новостях, отчётах и книгах обычно стоит Präteritum: Er half. Sie kamen. С sein, haben и модальными глаголами почти всегда используют Präteritum даже в разговоре: ich war, ich hatte, ich wollte, ich konnte, ich musste.',
          'Perfekt чи Präteritum? Обидва часи говорять про минуле. У розмові, чатах і особистих листах зазвичай уживають Perfekt: Ich habe geholfen. Wir sind gekommen. У газетах, новинах, звітах і книжках зазвичай стоїть Präteritum: Er half. Sie kamen. Із sein, haben і модальними дієсловами майже завжди вживають Präteritum навіть у розмові: ich war, ich hatte, ich wollte, ich konnte, ich musste.',
          'Perfekt mi, Präteritum mu? İki zaman da geçmişi anlatır. Konuşmada, sohbetlerde ve kişisel e-postalarda çoğunlukla Perfekt kullanılır: Ich habe geholfen. Wir sind gekommen. Gazetede, haberlerde, raporlarda ve kitaplarda çoğunlukla Präteritum bulunur: Er half. Sie kamen. sein, haben ve kip fiillerinde konuşmada da neredeyse her zaman Präteritum kullanılır: ich war, ich hatte, ich wollte, ich konnte, ich musste.',
        ],
        hint: ['Gespräch: Perfekt (hat gefunden). Zeitung und Bericht: Präteritum (fand). war, hatte, wollte, konnte: immer Präteritum.', 'Conversation: Perfekt (hat gefunden). Newspaper and report: Präteritum (fand). war, hatte, wollte, konnte: always Präteritum.', 'Разговор: Perfekt (hat gefunden). Газета и отчёт: Präteritum (fand). war, hatte, wollte, konnte: всегда Präteritum.', 'Розмова: Perfekt (hat gefunden). Газета і звіт: Präteritum (fand). war, hatte, wollte, konnte: завжди Präteritum.', 'Konuşma: Perfekt (hat gefunden). Gazete ve rapor: Präteritum (fand). war, hatte, wollte, konnte: her zaman Präteritum.'],
      },
      ex: [
        mc('G4', 'Präteritum in der Zeitung', I.choose, 'Wo liest man diesen Satz am ehesten? „Der Minister besuchte gestern eine Schule in Dresden.“', ['in der Zeitung', 'in einer Nachricht an eine Freundin', 'auf einem Einkaufszettel'],
          ['Where are you most likely to read this sentence? “The minister visited a school in Dresden yesterday.”', 'Где скорее всего можно прочитать это предложение? «Министр вчера посетил школу в Дрездене.»', 'Де найімовірніше можна прочитати це речення? «Міністр учора відвідав школу в Дрездені.»', 'Bu cümle en çok nerede okunur? “Bakan dün Dresden’de bir okulu ziyaret etti.”']),
        mc('G4', 'Perfekt im Gespräch', I.situation, 'Du erzählst einer Freundin am Telefon vom Wochenende. Welcher Satz klingt im Gespräch natürlich?', ['Wir haben am Samstag einen Ausflug gemacht.', 'Wir machten am Samstag einen Ausflug.', 'Wir hatten am Samstag einen Ausflug gemacht.'],
          ['You are telling a friend about the weekend on the phone. Which sentence sounds natural in conversation?', 'Вы рассказываете подруге по телефону о выходных. Какое предложение звучит естественно в разговоре?', 'Ви розповідаєте подрузі телефоном про вихідні. Яке речення звучить природно в розмові?', 'Bir arkadaşınıza telefonda hafta sonunu anlatıyorsunuz. Hangi cümle konuşmada doğal durur?']),
        mc('G4', 'fand → hat gefunden', I.choose, 'Im Bericht steht: „Die Polizei fand das Auto.“ Wie sagt man das im Gespräch?', ['Die Polizei hat das Auto gefunden.', 'Die Polizei hat das Auto gefindet.', 'Die Polizei ist das Auto gefunden.'],
          ['The report says: “The police found the car.” How do you say that in conversation?', 'В отчёте написано: «Полиция нашла автомобиль.» Как это сказать в разговоре?', 'У звіті написано: «Поліція знайшла автомобіль.» Як це сказати в розмові?', 'Raporda şöyle yazıyor: “Polis arabayı buldu.” Bu, konuşmada nasıl söylenir?']),
        mc('G4', 'ist angekommen → kam an', I.choose, 'Im Gespräch: „Der Zug ist zu spät angekommen.“ Im Zeitungsbericht: „Der Zug … zu spät an.“', ['kam', 'kommte', 'gekommen'],
          ['In conversation: “The train arrived late.” In a newspaper report: “Der Zug … zu spät an.”', 'В разговоре: «Поезд прибыл с опозданием.» В газетной заметке: «Der Zug … zu spät an.»', 'У розмові: «Поїзд прибув із запізненням.» У газетній замітці: «Der Zug … zu spät an.»', 'Konuşmada: “Tren geç geldi.” Gazete haberinde: “Der Zug … zu spät an.”']),
        mc('G4', 'war und konnte', I.sentence, 'Du erklärst einem Kollegen, warum du gestern gefehlt hast.', ['Ich war gestern krank und konnte nicht kommen.', 'Ich bin gestern krank und kann nicht gekommen.', 'Ich habe gestern krank gewesen und nicht kommen gekonnt.'],
          ['You are explaining to a colleague why you were absent yesterday.', 'Вы объясняете коллеге, почему вчера отсутствовали.', 'Ви пояснюєте колезі, чому вчора були відсутні.', 'Bir iş arkadaşınıza dün neden gelmediğinizi açıklıyorsunuz.']),
        gap('G4', 'verlor → hat verloren', I.participle, 'Im Bericht: „Sie verlor ihre Tasche.“ Im Gespräch: „Sie hat ihre Tasche ', '.“', 'verloren', ['verliert', 'verlor'],
          ['In a report: “Sie verlor ihre Tasche.” In conversation: “She has lost her bag.”', 'В отчёте: «Sie verlor ihre Tasche.» В разговоре: «Она потеряла сумку.»', 'У звіті: «Sie verlor ihre Tasche.» У розмові: «Вона загубила сумку.»', 'Raporda: “Sie verlor ihre Tasche.” Konuşmada: “Çantasını kaybetti.”'], 'verlieren'),
        gap('G4', 'hat geschlafen → schlief', I.verb, 'Im Gespräch: „Er hat lange geschlafen.“ Im Bericht: „Er ', ' lange.“', 'schlief', ['schlaf', 'schlafte'],
          ['In conversation: “Er hat lange geschlafen.” In a report: “He slept for a long time.”', 'В разговоре: «Er hat lange geschlafen.» В отчёте: «Он долго спал.»', 'У розмові: «Er hat lange geschlafen.» У звіті: «Він довго спав.»', 'Konuşmada: “Er hat lange geschlafen.” Raporda: “Uzun süre uyudu.”'], 'schlafen (Präteritum)'),
        gap('G4', 'sind gegangen → gingen', I.verb, 'Im Gespräch: „Wir sind nach Hause gegangen.“ Im Bericht: „Wir ', ' nach Hause.“', 'gingen', ['gehten', 'gegangen'],
          ['In conversation: “Wir sind nach Hause gegangen.” In a report: “We went home.”', 'В разговоре: «Wir sind nach Hause gegangen.» В отчёте: «Мы пошли домой.»', 'У розмові: «Wir sind nach Hause gegangen.» У звіті: «Ми пішли додому.»', 'Konuşmada: “Wir sind nach Hause gegangen.” Raporda: “Eve gittik.”'], 'gehen (Präteritum)'),
        gap('G4', 'kam → ist gekommen', I.auxiliary, 'Im Bericht: „Die Feuerwehr kam nach fünf Minuten.“ Im Gespräch: „Die Feuerwehr ', ' nach fünf Minuten gekommen.“', 'ist', ['hat', 'sind'],
          ['In a report: “Die Feuerwehr kam nach fünf Minuten.” In conversation: “The fire brigade came after five minutes.”', 'В отчёте: «Die Feuerwehr kam nach fünf Minuten.» В разговоре: «Пожарные приехали через пять минут.»', 'У звіті: «Die Feuerwehr kam nach fünf Minuten.» У розмові: «Пожежники приїхали за п’ять хвилин.»', 'Raporda: “Die Feuerwehr kam nach fünf Minuten.” Konuşmada: “İtfaiye beş dakika sonra geldi.”'], 'haben / sein'),
        sb('G4', 'Perfekt im Gespräch', I.order, 'Gestern / habe / ich / im Zug / eine alte Freundin / getroffen.',
          ['Yesterday I met an old friend on the train.', 'Вчера я встретил в поезде старую подругу.', 'Учора я зустрів у поїзді давню подругу.', 'Dün trende eski bir arkadaşımla karşılaştım.'],
          { alt: ['Ich habe gestern im Zug eine alte Freundin getroffen.', 'Im Zug habe ich gestern eine alte Freundin getroffen.', 'Eine alte Freundin habe ich gestern im Zug getroffen.'] }),
      ],
    },
    {
      title: 'als oder wenn?',
      t: ['als or wenn? (when in the past)', 'als или wenn? (когда в прошлом)', 'als чи wenn? (коли в минулому)', 'als mı, wenn mi? (geçmişte “-diğinde”)'],
      card: {
        id: 'p1_als_wenn',
        rule: 'als oder wenn? Beide Wörter leiten einen Nebensatz ein, das Verb steht am Ende. als: Etwas ist einmal in der Vergangenheit passiert oder es geht um eine Zeit im Leben: Als ich sechs war, kam ich in die Schule. wenn: Etwas ist in der Vergangenheit mehr als einmal passiert, oft mit immer oder jedes Mal: Immer wenn mein Opa zu Besuch kam, brachte er Schokolade mit. In der Gegenwart und in der Zukunft steht immer wenn. Steht der Nebensatz am Anfang, beginnt der Hauptsatz mit dem Verb.',
        examples: ['Als ich zum ersten Mal in Berlin war, hat es nur geregnet.', 'Immer wenn wir Ferien hatten, fuhren wir ans Meer.', 'Wenn ich morgen Zeit habe, rufe ich dich an.'],
        highlight: null,
        t: [
          'als or wenn? Both words introduce a subordinate clause; the verb goes at the end. als: something happened once in the past, or it is about a period of your life: Als ich sechs war, kam ich in die Schule. (When I was six, I started school.) wenn: something happened more than once in the past, often with immer or jedes Mal: Immer wenn mein Opa zu Besuch kam, brachte er Schokolade mit. (Whenever my grandad came to visit, he brought chocolate.) In the present and the future you always use wenn. If the subordinate clause comes first, the main clause begins with the verb.',
          'als или wenn? Оба слова вводят придаточное предложение, глагол стоит в конце. als: что-то произошло в прошлом один раз или речь идёт о периоде жизни: Als ich sechs war, kam ich in die Schule. (Когда мне было шесть, я пошёл в школу.) wenn: что-то происходило в прошлом не один раз, часто с immer или jedes Mal: Immer wenn mein Opa zu Besuch kam, brachte er Schokolade mit. (Каждый раз, когда дедушка приезжал в гости, он привозил шоколад.) В настоящем и будущем всегда стоит wenn. Если придаточное стоит в начале, главное предложение начинается с глагола.',
          'als чи wenn? Обидва слова вводять підрядне речення, дієслово стоїть у кінці. als: щось сталося в минулому один раз або йдеться про період життя: Als ich sechs war, kam ich in die Schule. (Коли мені було шість, я пішов до школи.) wenn: щось відбувалося в минулому не один раз, часто з immer або jedes Mal: Immer wenn mein Opa zu Besuch kam, brachte er Schokolade mit. (Щоразу, коли дідусь приїжджав у гості, він привозив шоколад.) У теперішньому й майбутньому завжди стоїть wenn. Якщо підрядне речення стоїть на початку, головне починається з дієслова.',
          'als mı, wenn mi? İki kelime de bir yan cümle başlatır, fiil sonda durur. als: Bir şey geçmişte bir kez olmuştur ya da hayatın bir döneminden söz edilir: Als ich sechs war, kam ich in die Schule. (Altı yaşındayken okula başladım.) wenn: Bir şey geçmişte birden fazla kez olmuştur, çoğunlukla immer ya da jedes Mal ile: Immer wenn mein Opa zu Besuch kam, brachte er Schokolade mit. (Dedem ne zaman ziyarete gelse çikolata getirirdi.) Şimdiki ve gelecek zamanda her zaman wenn kullanılır. Yan cümle başta ise ana cümle fiille başlar.',
        ],
        hint: ['als = einmal in der Vergangenheit. wenn = jedes Mal (immer wenn) oder Gegenwart/Zukunft. Verb am Ende.', 'als = once in the past. wenn = every time (immer wenn) or present/future. Verb at the end.', 'als = один раз в прошлом. wenn = каждый раз (immer wenn) или настоящее/будущее. Глагол в конце.', 'als = один раз у минулому. wenn = щоразу (immer wenn) або теперішнє/майбутнє. Дієслово в кінці.', 'als = geçmişte bir kez. wenn = her seferinde (immer wenn) ya da şimdiki/gelecek zaman. Fiil sonda.'],
      },
      ex: [
        mc('G5', 'als', I.choose, '… ich 18 Jahre alt war, machte ich sofort den Führerschein.', ['Als', 'Wenn', 'Wann'],
          ['When I was 18, I got my driving licence straight away.', 'Когда мне было 18 лет, я сразу получил водительские права.', 'Коли мені було 18 років, я одразу отримав водійські права.', '18 yaşındayken hemen ehliyet aldım.']),
        mc('G5', 'wenn', I.choose, 'Jedes Mal, … wir ans Meer fuhren, sammelte ich am Strand Muscheln.', ['wenn', 'als', 'wann'],
          ['Every time we went to the seaside, I collected shells on the beach.', 'Каждый раз, когда мы ездили на море, я собирал на пляже ракушки.', 'Щоразу, коли ми їздили на море, я збирав на пляжі мушлі.', 'Denize her gidişimizde sahilde deniz kabuğu toplardım.']),
        mc('G5', 'als', I.choose, 'Was hast du gedacht, … du zum ersten Mal Schnee gesehen hast?', ['als', 'wenn', 'dass'],
          ['What did you think when you saw snow for the first time?', 'Что ты подумал, когда впервые увидел снег?', 'Що ти подумав, коли вперше побачив сніг?', 'İlk kez kar gördüğünde ne düşündün?']),
        mc('G5', 'wenn (Zukunft)', I.choose, '… ich nächste Woche mehr Zeit habe, helfe ich dir gern beim Umzug.', ['Wenn', 'Als', 'Wann'],
          ['If I have more time next week, I will gladly help you move.', 'Если на следующей неделе у меня будет больше времени, я с удовольствием помогу тебе с переездом.', 'Якщо наступного тижня я матиму більше часу, я охоче допоможу тобі з переїздом.', 'Gelecek hafta daha çok vaktim olursa taşınmana seve seve yardım ederim.']),
        mc('G5', 'Verb am Ende', I.sentence, 'Ben erzählt von seinem ersten Schultag.', ['Als ich in die Schule kam, konnte ich schon lesen.', 'Als ich kam in die Schule, konnte ich schon lesen.', 'Als ich in die Schule kam, ich konnte schon lesen.'],
          ['Ben is talking about his first day at school.', 'Ben рассказывает о своём первом школьном дне.', 'Ben розповідає про свій перший шкільний день.', 'Ben okuldaki ilk gününü anlatıyor.']),
        gap('G5', 'wenn', I.conjunction, 'Immer ', ' meine Oma Kuchen backte, roch das ganze Haus nach Zimt.', 'wenn', ['als', 'wann'],
          ['Whenever my grandma baked a cake, the whole house smelled of cinnamon.', 'Всегда, когда бабушка пекла пирог, весь дом пах корицей.', 'Завжди, коли бабуся пекла пиріг, увесь будинок пахнув корицею.', 'Büyükannem ne zaman kek yapsa bütün ev tarçın kokardı.'], ALS_WENN),
        gap('G5', 'als', I.conjunction, 'Wir wohnten noch in Hamburg, ', ' meine kleine Schwester geboren wurde.', 'als', ['wenn', 'wann'],
          ['We were still living in Hamburg when my little sister was born.', 'Мы ещё жили в Гамбурге, когда родилась моя младшая сестра.', 'Ми ще жили в Гамбурзі, коли народилася моя молодша сестра.', 'Küçük kız kardeşim doğduğunda hâlâ Hamburg’da oturuyorduk.'], ALS_WENN),
        gap('G5', 'als', I.conjunction, 'Ich habe mich riesig gefreut, ', ' ich letztes Jahr die Prüfung bestanden habe.', 'als', ['wenn', 'ob'],
          ['I was absolutely delighted when I passed the exam last year.', 'Я был ужасно рад, когда в прошлом году сдал экзамен.', 'Я дуже зрадів, коли торік склав іспит.', 'Geçen yıl sınavı geçtiğimde çok sevindim.'], ALS_WENN),
        gap('G5', 'Verb am Ende', I.verb, 'Als ich gestern nach Hause ', ', stand ein großes Paket vor der Tür.', 'kam', ['kommen', 'kamen'],
          ['When I came home yesterday, there was a big parcel outside the door.', 'Когда я вчера пришёл домой, перед дверью стояла большая посылка.', 'Коли я вчора прийшов додому, перед дверима стояла велика посилка.', 'Dün eve geldiğimde kapının önünde büyük bir paket duruyordu.'], 'kommen (Präteritum)'),
        sb('G5', 'als', I.order, 'Als ich klein war, / hatten / wir / einen Hund.',
          ['When I was little, we had a dog.', 'Когда я был маленьким, у нас была собака.', 'Коли я був малим, у нас був собака.', 'Ben küçükken bir köpeğimiz vardı.']),
      ],
    },
    {
      title: 'hatte trainiert, war geflohen',
      t: ['hatte trainiert, war geflohen (Plusquamperfekt: past perfect)', 'hatte trainiert, war geflohen (Plusquamperfekt: предпрошедшее время)', 'hatte trainiert, war geflohen (Plusquamperfekt: передминулий час)', 'hatte trainiert, war geflohen (Plusquamperfekt: geçmişin geçmişi)'],
      card: {
        id: 'p1_plusquamperfekt',
        rule: 'Plusquamperfekt: Präteritum von haben oder sein + Partizip am Satzende. ich hatte trainiert, du hattest trainiert, er hatte trainiert, wir hatten trainiert … / ich war geflohen, du warst geflohen, er war geflohen, wir waren geflohen … sein steht wie im Perfekt bei Bewegung und Veränderung. Man benutzt das Plusquamperfekt, wenn etwas vor einem anderen Ereignis in der Vergangenheit passiert ist: Ich musste zusehen (Vergangenheit), denn ich hatte mir den Fuß gebrochen (noch früher).',
        examples: ['Ich hatte Bauchschmerzen, weil ich zu viel Eis gegessen hatte.', 'Als wir am Bahnhof ankamen, war der Zug schon abgefahren.', 'Sie war glücklich: Sie hatte die Prüfung bestanden.'],
        highlight: 'verb',
        t: [
          'Plusquamperfekt (past perfect): Präteritum of haben or sein + past participle at the end of the clause. ich hatte trainiert, du hattest trainiert, er hatte trainiert, wir hatten trainiert … / ich war geflohen, du warst geflohen, er war geflohen, wir waren geflohen … As in the Perfekt, sein is used for movement and change of state. You use the Plusquamperfekt when something happened before another event in the past: Ich musste zusehen (past), denn ich hatte mir den Fuß gebrochen (even earlier). (I had to watch because I had broken my foot.)',
          'Plusquamperfekt (предпрошедшее время): Präteritum глагола haben или sein + Partizip II в конце предложения. ich hatte trainiert, du hattest trainiert, er hatte trainiert, wir hatten trainiert … / ich war geflohen, du warst geflohen, er war geflohen, wir waren geflohen … sein, как и в Perfekt, используется при движении и изменении состояния. Plusquamperfekt нужен, когда что-то произошло раньше другого события в прошлом: Ich musste zusehen (прошлое), denn ich hatte mir den Fuß gebrochen (ещё раньше). (Мне пришлось только смотреть, потому что я сломал ногу.)',
          'Plusquamperfekt (передминулий час): Präteritum дієслова haben або sein + Partizip II у кінці речення. ich hatte trainiert, du hattest trainiert, er hatte trainiert, wir hatten trainiert … / ich war geflohen, du warst geflohen, er war geflohen, wir waren geflohen … sein, як і в Perfekt, уживається для руху та зміни стану. Plusquamperfekt потрібен, коли щось сталося раніше за іншу подію в минулому: Ich musste zusehen (минуле), denn ich hatte mir den Fuß gebrochen (ще раніше). (Мені довелося тільки дивитися, бо я зламав ногу.)',
          'Plusquamperfekt (geçmişin geçmişi): haben ya da sein fiilinin Präteritum’u + cümlenin sonunda Partizip II. ich hatte trainiert, du hattest trainiert, er hatte trainiert, wir hatten trainiert … / ich war geflohen, du warst geflohen, er war geflohen, wir waren geflohen … Perfekt’te olduğu gibi hareket ve durum değişikliğinde sein kullanılır. Plusquamperfekt, geçmişteki başka bir olaydan önce olan şeyler için kullanılır: Ich musste zusehen (geçmiş), denn ich hatte mir den Fuß gebrochen (daha da önce). (Sadece izlemek zorunda kaldım, çünkü ayağımı kırmıştım.)',
        ],
        hint: ['hatte / war + Partizip: Das ist noch früher passiert. Bewegung und Veränderung: war (war gegangen, war abgefahren).', 'hatte / war + participle: this happened even earlier. Movement and change: war (war gegangen, war abgefahren).', 'hatte / war + Partizip II: это произошло ещё раньше. Движение и изменение: war (war gegangen, war abgefahren).', 'hatte / war + Partizip II: це сталося ще раніше. Рух і зміна: war (war gegangen, war abgefahren).', 'hatte / war + Partizip II: Bu daha da önce oldu. Hareket ve değişim: war (war gegangen, war abgefahren).'],
      },
      ex: [
        mc('G6', 'geschlafen hatte', I.choose, 'Ich war todmüde, weil ich die ganze Nacht nicht … hatte.', ['geschlafen', 'schlief', 'schlafen'],
          ['I was dead tired because I had not slept all night.', 'Я был смертельно уставшим, потому что не спал всю ночь.', 'Я був смертельно втомлений, бо не спав усю ніч.', 'Bütün gece uyumadığım için yorgunluktan ölüyordum.']),
        mc('G6', 'hatte begonnen', I.choose, 'Als wir im Kino ankamen, … der Film schon begonnen.', ['hatte', 'war', 'hat'],
          ['When we arrived at the cinema, the film had already started.', 'Когда мы пришли в кино, фильм уже начался.', 'Коли ми прийшли в кіно, фільм уже почався.', 'Sinemaya vardığımızda film çoktan başlamıştı.']),
        mc('G6', 'war abgefahren', I.choose, 'Der Zug … schon abgefahren, als ich endlich am Gleis stand.', ['war', 'hatte', 'ist'],
          ['The train had already left when I finally stood on the platform.', 'Поезд уже ушёл, когда я наконец оказался на платформе.', 'Поїзд уже поїхав, коли я нарешті опинився на платформі.', 'Sonunda perona vardığımda tren çoktan kalkmıştı.']),
        mc('G6', 'Was war zuerst?', I.choose, 'Was ist zuerst passiert? „Lena konnte nicht ins Haus, weil sie ihren Schlüssel vergessen hatte.“', ['Lena hat den Schlüssel vergessen.', 'Lena konnte nicht ins Haus.', 'Beides ist gleichzeitig passiert.'],
          ['What happened first? “Lena could not get into the house because she had forgotten her key.”', 'Что произошло сначала? «Lena не могла попасть в дом, потому что забыла ключ.»', 'Що сталося спочатку? «Lena не могла потрапити в будинок, бо забула ключ.»', 'Önce ne oldu? “Lena eve giremedi çünkü anahtarını unutmuştu.”']),
        mc('G6', 'hatte gegessen', I.sentence, 'Tarik erklärt, warum er am Abend so hungrig war.', ['Ich hatte den ganzen Tag nichts gegessen.', 'Ich war den ganzen Tag nichts gegessen.', 'Ich hatte den ganzen Tag nichts essen.'],
          ['Tarik is explaining why he was so hungry in the evening.', 'Tarik объясняет, почему вечером он был таким голодным.', 'Tarik пояснює, чому ввечері він був такий голодний.', 'Tarik akşam neden bu kadar aç olduğunu açıklıyor.']),
        gap('G6', 'gemacht hatte', I.auxiliary, 'Ich war so glücklich, weil meine Familie mir ein schönes Fest gemacht ', '.', 'hatte', ['war', 'hat'],
          ['I was so happy because my family had thrown a lovely party for me.', 'Я был так счастлив, потому что семья устроила мне чудесный праздник.', 'Я був такий щасливий, бо родина влаштувала мені чудове свято.', 'Çok mutluydum çünkü ailem benim için güzel bir kutlama yapmıştı.'], AUX_PAST),
        gap('G6', 'hatte geregnet', I.auxiliary, 'Am Morgen war die Straße ganz nass. In der Nacht ', ' es stark geregnet.', 'hatte', ['war', 'hattet'],
          ['In the morning the road was completely wet. It had rained heavily during the night.', 'Утром дорога была совсем мокрой. Ночью шёл сильный дождь.', 'Уранці дорога була зовсім мокра. Уночі йшов сильний дощ.', 'Sabah yol sırılsıklamdı. Gece şiddetli yağmur yağmıştı.'], AUX_PAST),
        gap('G6', 'waren gegangen', I.auxiliary, 'Emre kam viel zu spät zur Feier. Die meisten Gäste ', ' schon nach Hause gegangen.', 'waren', ['hatten', 'war'],
          ['Emre arrived at the party far too late. Most of the guests had already gone home.', 'Emre пришёл на праздник слишком поздно. Большинство гостей уже ушли домой.', 'Emre прийшов на свято надто пізно. Більшість гостей уже пішли додому.', 'Emre kutlamaya çok geç geldi. Konukların çoğu çoktan eve gitmişti.'], AUX_PAST),
        gap('G6', 'hatten gegessen', I.participle, 'Wir hatten großen Hunger, denn wir hatten seit dem Frühstück nichts ', '.', 'gegessen', ['geesst', 'aßen'],
          ['We were very hungry because we had not eaten anything since breakfast.', 'Мы были очень голодны, потому что ничего не ели с завтрака.', 'Ми були дуже голодні, бо нічого не їли від сніданку.', 'Çok açtık çünkü kahvaltıdan beri hiçbir şey yememiştik.'], 'essen'),
        sb('G6', 'war abgefahren', I.order, 'Als ich ankam, / war / der Bus / schon / abgefahren.',
          ['When I arrived, the bus had already left.', 'Когда я пришёл, автобус уже уехал.', 'Коли я прийшов, автобус уже поїхав.', 'Ben vardığımda otobüs çoktan kalkmıştı.']),
      ],
    },
    {
      title: 'Früher …',
      t: ['In the old days …', 'Раньше …', 'Раніше …', 'Eskiden …'],
      card: {
        id: 'p1_frueher',
        rule: 'Über die Vergangenheit und die Kindheit reden: Als Kind war ich immer sehr neugierig. Mit zehn Jahren bekam ich mein erstes Fahrrad. Damals gab es noch keine Handys. Ich fand es immer toll, wenn … Das hat mir immer gut gefallen. Meine Eltern waren sehr zufrieden mit mir. sich erinnern an + Akkusativ: Ich kann mich noch gut an meinen ersten Schultag erinnern. Daran erinnere ich mich gern. Ich erinnere mich nicht mehr = Ich habe es vergessen.',
        examples: ['Als Kind war ich oft bei meinen Großeltern.', 'Ich kann mich noch gut an unseren ersten Urlaub erinnern.', 'Damals hatten wir kein Auto.'],
        highlight: null,
        t: [
          'Talking about the past and your childhood: Als Kind war ich immer sehr neugierig. (As a child I was always very curious.) Mit zehn Jahren bekam ich mein erstes Fahrrad. (At the age of ten I got my first bike.) Damals gab es noch keine Handys. (Back then there were no mobile phones.) Ich fand es immer toll, wenn … (I always loved it when …) Das hat mir immer gut gefallen. Meine Eltern waren sehr zufrieden mit mir. (My parents were very pleased with me.) sich erinnern an + accusative (to remember): Ich kann mich noch gut an meinen ersten Schultag erinnern. Daran erinnere ich mich gern. Ich erinnere mich nicht mehr = I have forgotten it.',
          'Как говорить о прошлом и о детстве: Als Kind war ich immer sehr neugierig. (В детстве я всегда был очень любопытным.) Mit zehn Jahren bekam ich mein erstes Fahrrad. (В десять лет я получил свой первый велосипед.) Damals gab es noch keine Handys. (Тогда ещё не было мобильных телефонов.) Ich fand es immer toll, wenn … (Мне всегда очень нравилось, когда …) Das hat mir immer gut gefallen. Meine Eltern waren sehr zufrieden mit mir. (Родители были мной очень довольны.) sich erinnern an + Akkusativ (помнить, вспоминать): Ich kann mich noch gut an meinen ersten Schultag erinnern. Daran erinnere ich mich gern. Ich erinnere mich nicht mehr = я это забыл.',
          'Як говорити про минуле і дитинство: Als Kind war ich immer sehr neugierig. (У дитинстві я завжди був дуже допитливим.) Mit zehn Jahren bekam ich mein erstes Fahrrad. (У десять років я отримав свій перший велосипед.) Damals gab es noch keine Handys. (Тоді ще не було мобільних телефонів.) Ich fand es immer toll, wenn … (Мені завжди дуже подобалося, коли …) Das hat mir immer gut gefallen. Meine Eltern waren sehr zufrieden mit mir. (Батьки були мною дуже задоволені.) sich erinnern an + Akkusativ (пам’ятати, згадувати): Ich kann mich noch gut an meinen ersten Schultag erinnern. Daran erinnere ich mich gern. Ich erinnere mich nicht mehr = я це забув.',
          'Geçmiş ve çocukluk hakkında konuşmak: Als Kind war ich immer sehr neugierig. (Çocukken hep çok meraklıydım.) Mit zehn Jahren bekam ich mein erstes Fahrrad. (On yaşında ilk bisikletimi aldım.) Damals gab es noch keine Handys. (O zamanlar henüz cep telefonu yoktu.) Ich fand es immer toll, wenn … (… olduğunda hep çok hoşuma giderdi.) Das hat mir immer gut gefallen. Meine Eltern waren sehr zufrieden mit mir. (Annemle babam benden çok memnundu.) sich erinnern an + Akkusativ (hatırlamak): Ich kann mich noch gut an meinen ersten Schultag erinnern. Daran erinnere ich mich gern. Ich erinnere mich nicht mehr = Unuttum.',
        ],
        hint: ['Als Kind … Mit zehn Jahren … Damals … sich erinnern an + Akkusativ: Ich erinnere mich an den Tag.', 'Als Kind … Mit zehn Jahren … Damals … sich erinnern an + accusative: Ich erinnere mich an den Tag.', 'Als Kind … Mit zehn Jahren … Damals … sich erinnern an + Akkusativ (винительный падеж): Ich erinnere mich an den Tag.', 'Als Kind … Mit zehn Jahren … Damals … sich erinnern an + Akkusativ (знахідний відмінок): Ich erinnere mich an den Tag.', 'Als Kind … Mit zehn Jahren … Damals … sich erinnern an + Akkusativ (belirtme durumu): Ich erinnere mich an den Tag.'],
      },
      ex: [
        mc('K1', 'Als Kind …', I.react, '„Wie war deine Kindheit?“', ['Als Kind war ich oft bei meinen Großeltern. Daran erinnere ich mich gern.', 'Ich wünsche dir eine schöne Kindheit.', 'Der Unfall ist am Montag passiert.'],
          ['“What was your childhood like?”', '«Каким было твоё детство?»', '«Яким було твоє дитинство?»', '“Çocukluğun nasıldı?”']),
        mc('K1', 'sich erinnern an', I.choose, 'Ich kann mich noch gut … meinen ersten Schultag erinnern.', ['an', 'auf', 'über'],
          ['I can still remember my first day at school very well.', 'Я до сих пор хорошо помню свой первый школьный день.', 'Я досі добре пам’ятаю свій перший шкільний день.', 'Okuldaki ilk günümü hâlâ çok iyi hatırlıyorum.']),
        mc('K1', 'Damals', I.choose, '… gab es noch keine Handys. Wir haben uns einfach nachmittags auf dem Spielplatz getroffen.', ['Damals', 'Bald', 'Übermorgen'],
          ['Back then there were no mobile phones. We simply met at the playground in the afternoon.', 'Тогда ещё не было мобильных телефонов. Мы просто встречались после обеда на детской площадке.', 'Тоді ще не було мобільних телефонів. Ми просто зустрічалися після обіду на дитячому майданчику.', 'O zamanlar henüz cep telefonu yoktu. Öğleden sonra oyun parkında buluşurduk.']),
        mc('K1', 'Mit zehn Jahren', I.choose, '… zehn Jahren bekam ich mein erstes eigenes Fahrrad.', ['Mit', 'Bei', 'Als'],
          ['At the age of ten I got my first bike of my own.', 'В десять лет я получил свой первый собственный велосипед.', 'У десять років я отримав свій перший власний велосипед.', 'On yaşında ilk kendi bisikletime sahip oldum.']),
        mc('K1', 'Ich erinnere mich nicht mehr.', I.choose, 'Was bedeutet „Daran erinnere ich mich leider nicht mehr.“?', ['Ich habe es vergessen.', 'Ich weiß es noch ganz genau.', 'Ich möchte nicht darüber reden.'],
          ['What does “Daran erinnere ich mich leider nicht mehr.” mean?', 'Что означает «Daran erinnere ich mich leider nicht mehr.»?', 'Що означає «Daran erinnere ich mich leider nicht mehr.»?', '“Daran erinnere ich mich leider nicht mehr.” ne demek?']),
        gap('K1', 'sich erinnern', I.reflexive, 'Erinnerst du ', ' noch an unseren Urlaub in Kroatien vor zehn Jahren?', 'dich', ['dir', 'du'],
          ['Do you still remember our holiday in Croatia ten years ago?', 'Ты ещё помнишь наш отпуск в Хорватии десять лет назад?', 'Ти ще пам’ятаєш нашу відпустку в Хорватії десять років тому?', 'On yıl önce Hırvatistan’daki tatilimizi hâlâ hatırlıyor musun?'], 'sich'),
        gap('K1', 'fand', I.verb, 'Als Kind ', ' ich es immer toll, wenn es im Winter schneite.', 'fand', ['fande', 'findete'],
          ['As a child I always loved it when it snowed in winter.', 'В детстве мне всегда очень нравилось, когда зимой шёл снег.', 'У дитинстві мені завжди дуже подобалося, коли взимку йшов сніг.', 'Çocukken kışın kar yağması hep çok hoşuma giderdi.'], 'finden (Präteritum)'),
        gap('K1', 'zufrieden mit', I.prep, 'Meine Lehrerin war immer sehr zufrieden ', ' meinen Hausaufgaben.', 'mit', ['von', 'über'],
          ['My teacher was always very pleased with my homework.', 'Моя учительница всегда была очень довольна моими домашними заданиями.', 'Моя вчителька завжди була дуже задоволена моїми домашніми завданнями.', 'Öğretmenim ödevlerimden her zaman çok memnundu.'], 'mit / von / über'),
        gap('K1', 'erinnere', I.verb, 'An meinen ersten Lehrer ', ' ich mich leider überhaupt nicht mehr.', 'erinnere', ['erinnern', 'erinnert'],
          ['Unfortunately I do not remember my first teacher at all any more.', 'К сожалению, своего первого учителя я уже совсем не помню.', 'На жаль, свого першого вчителя я вже зовсім не пам’ятаю.', 'Ne yazık ki ilk öğretmenimi artık hiç hatırlamıyorum.'], 'sich erinnern'),
        sb('K1', 'Als Kind', I.order, 'Als Kind / war / ich / immer / sehr neugierig.',
          ['As a child I was always very curious.', 'В детстве я всегда был очень любопытным.', 'У дитинстві я завжди був дуже допитливим.', 'Çocukken hep çok meraklıydım.'],
          { alt: ['Ich war als Kind immer sehr neugierig.', 'Ich war immer sehr neugierig als Kind.'] }),
      ],
    },
    {
      title: 'Ein Unfall',
      t: ['An accident', 'Авария', 'Аварія', 'Bir kaza'],
      card: {
        id: 'p1_unfall',
        rule: 'Einen Unfall schildern: Sag zuerst, wann und wo: Der Unfall ist am Montag gegen acht Uhr an der Kreuzung passiert. Dann erzähl der Reihe nach: Ich fuhr gerade los. Zur gleichen Zeit kam von rechts ein Motorrad. Ich bemerkte leider nicht, dass die Ampel rot war. Versehentlich (= ohne Absicht) habe ich die Ampel übersehen. Daraufhin / Dann bremste der Fahrer. Dabei stürzte er. Zum Schluss: Niemand wurde verletzt. Der Schaden ist klein. Einen Unfall melden: Ich möchte einen Unfall melden.',
        examples: ['Der Unfall ist gestern Abend in der Bahnhofstraße passiert.', 'Ich bemerkte leider nicht, dass das Auto schon so nah war.', 'Daraufhin fuhr der Radfahrer gegen die Tür.'],
        highlight: null,
        t: [
          'Describing an accident: first say when and where: Der Unfall ist am Montag gegen acht Uhr an der Kreuzung passiert. (The accident happened on Monday at about eight o’clock at the crossroads.) Then tell it in order: Ich fuhr gerade los. (I was just setting off.) Zur gleichen Zeit kam von rechts ein Motorrad. (At the same time a motorbike came from the right.) Ich bemerkte leider nicht, dass die Ampel rot war. (Unfortunately I did not notice that the lights were red.) Versehentlich (= by mistake) habe ich die Ampel übersehen (overlooked). Daraufhin / Dann (thereupon / then) bremste der Fahrer. Dabei (in doing so) stürzte er. Finally: Niemand wurde verletzt. (Nobody was hurt.) Der Schaden ist klein. Reporting an accident: Ich möchte einen Unfall melden.',
          'Как описать аварию: сначала скажите, когда и где: Der Unfall ist am Montag gegen acht Uhr an der Kreuzung passiert. (Авария произошла в понедельник около восьми часов на перекрёстке.) Затем рассказывайте по порядку: Ich fuhr gerade los. (Я как раз трогался с места.) Zur gleichen Zeit kam von rechts ein Motorrad. (В это же время справа ехал мотоцикл.) Ich bemerkte leider nicht, dass die Ampel rot war. (К сожалению, я не заметил, что горел красный.) Versehentlich (= нечаянно) habe ich die Ampel übersehen (не заметил). Daraufhin / Dann (после этого / затем) bremste der Fahrer. Dabei (при этом) stürzte er. В конце: Niemand wurde verletzt. (Никто не пострадал.) Der Schaden ist klein. Сообщить об аварии: Ich möchte einen Unfall melden.',
          'Як описати аварію: спочатку скажіть, коли і де: Der Unfall ist am Montag gegen acht Uhr an der Kreuzung passiert. (Аварія сталася в понеділок близько восьмої години на перехресті.) Потім розповідайте по черзі: Ich fuhr gerade los. (Я саме рушав.) Zur gleichen Zeit kam von rechts ein Motorrad. (У цей самий час праворуч їхав мотоцикл.) Ich bemerkte leider nicht, dass die Ampel rot war. (На жаль, я не помітив, що горіло червоне світло.) Versehentlich (= ненавмисно) habe ich die Ampel übersehen (не помітив). Daraufhin / Dann (після цього / потім) bremste der Fahrer. Dabei (при цьому) stürzte er. Наприкінці: Niemand wurde verletzt. (Ніхто не постраждав.) Der Schaden ist klein. Повідомити про аварію: Ich möchte einen Unfall melden.',
          'Bir kazayı anlatmak: Önce ne zaman ve nerede olduğunu söyleyin: Der Unfall ist am Montag gegen acht Uhr an der Kreuzung passiert. (Kaza pazartesi günü saat sekiz sularında kavşakta oldu.) Sonra sırayla anlatın: Ich fuhr gerade los. (Tam yola çıkıyordum.) Zur gleichen Zeit kam von rechts ein Motorrad. (Aynı anda sağdan bir motosiklet geldi.) Ich bemerkte leider nicht, dass die Ampel rot war. (Ne yazık ki ışığın kırmızı olduğunu fark etmedim.) Versehentlich (= yanlışlıkla) habe ich die Ampel übersehen (gözden kaçırdım). Daraufhin / Dann (bunun üzerine / sonra) bremste der Fahrer. Dabei (bu sırada) stürzte er. Son olarak: Niemand wurde verletzt. (Kimse yaralanmadı.) Der Schaden ist klein. Kaza bildirmek: Ich möchte einen Unfall melden.',
        ],
        hint: ['Wann? Wo? Was ist passiert? Zur gleichen Zeit … Daraufhin … Dabei … versehentlich = ohne Absicht.', 'When? Where? What happened? Zur gleichen Zeit … Daraufhin … Dabei … versehentlich = by mistake.', 'Когда? Где? Что случилось? Zur gleichen Zeit … Daraufhin … Dabei … versehentlich = нечаянно.', 'Коли? Де? Що сталося? Zur gleichen Zeit … Daraufhin … Dabei … versehentlich = ненавмисно.', 'Ne zaman? Nerede? Ne oldu? Zur gleichen Zeit … Daraufhin … Dabei … versehentlich = yanlışlıkla.'],
      },
      ex: [
        mc('K2', 'passiert', I.choose, 'Der Unfall ist am Montag gegen acht Uhr an der Kreuzung vor der Schule …', ['passiert', 'gemacht', 'gewesen'],
          ['The accident happened on Monday at about eight o’clock at the crossroads in front of the school.', 'Авария произошла в понедельник около восьми часов на перекрёстке перед школой.', 'Аварія сталася в понеділок близько восьмої години на перехресті перед школою.', 'Kaza pazartesi günü saat sekiz sularında okulun önündeki kavşakta oldu.']),
        mc('K2', 'versehentlich', I.choose, 'Der Fahrer hat … die rote Ampel übersehen. Das wollte er natürlich nicht.', ['versehentlich', 'absichtlich', 'pünktlich'],
          ['The driver accidentally overlooked the red light. Of course he did not mean to.', 'Водитель нечаянно не заметил красный свет. Он, конечно, этого не хотел.', 'Водій ненавмисно не помітив червоне світло. Він, звісно, цього не хотів.', 'Sürücü kırmızı ışığı yanlışlıkla görmedi. Elbette bunu istememişti.']),
        mc('K2', 'Zur gleichen Zeit', I.choose, 'Ich fuhr gerade aus der Garage. Zur gleichen … kam von rechts ein Motorrad.', ['Zeit', 'Uhr', 'Tag'],
          ['I was just driving out of the garage. At the same time a motorbike came from the right.', 'Я как раз выезжал из гаража. В это же время справа ехал мотоцикл.', 'Я саме виїжджав із гаража. У цей самий час праворуч їхав мотоцикл.', 'Tam garajdan çıkıyordum. Aynı anda sağdan bir motosiklet geldi.']),
        mc('K2', 'einen Unfall melden', I.situation, 'Du hast einen Unfall gesehen und rufst die Polizei an. Was sagst du zuerst?', ['Guten Tag, ich möchte einen Unfall melden.', 'Guten Tag, ich wünsche Ihnen viel Glück.', 'Guten Tag, ich glaube an Glücksbringer.'],
          ['You have seen an accident and call the police. What do you say first?', 'Вы видели аварию и звоните в полицию. Что вы скажете сначала?', 'Ви бачили аварію і телефонуєте в поліцію. Що ви скажете спочатку?', 'Bir kaza gördünüz ve polisi arıyorsunuz. İlk olarak ne dersiniz?']),
        mc('K2', 'Daraufhin', I.choose, 'Das Auto vor mir bremste plötzlich. … fuhr ich leider hinten auf.', ['Daraufhin', 'Damals', 'Vorher'],
          ['The car in front of me braked suddenly. As a result I unfortunately drove into the back of it.', 'Машина передо мной резко затормозила. После этого я, к сожалению, въехал в неё сзади.', 'Машина переді мною різко загальмувала. Після цього я, на жаль, в’їхав у неї ззаду.', 'Önümdeki araba aniden fren yaptı. Bunun üzerine ne yazık ki arkadan çarptım.']),
        gap('K2', 'bemerkte nicht, dass', I.conjunction, 'Ich bemerkte leider nicht, ', ' die Ampel schon rot war.', 'dass', ['weil', 'wenn'],
          ['Unfortunately I did not notice that the lights were already red.', 'К сожалению, я не заметил, что уже горел красный.', 'На жаль, я не помітив, що вже горіло червоне світло.', 'Ne yazık ki ışığın çoktan kırmızı olduğunu fark etmedim.'], 'dass / weil / wenn'),
        gap('K2', 'stürzte', I.verb, 'Die Frau stieg aus dem Bus und ', ' dabei auf der nassen Treppe.', 'stürzte', ['stürzt', 'stürzten'],
          ['The woman got off the bus and fell on the wet steps as she did so.', 'Женщина выходила из автобуса и при этом упала на мокрых ступеньках.', 'Жінка виходила з автобуса і при цьому впала на мокрих сходах.', 'Kadın otobüsten indi ve bu sırada ıslak basamaklarda düştü.'], 'stürzen (Präteritum)'),
        gap('K2', 'gerufen', I.participle, 'Zum Glück hat eine Zeugin sofort den Krankenwagen ', '.', 'gerufen', ['geruft', 'rief'],
          ['Luckily a witness called the ambulance straight away.', 'К счастью, свидетельница сразу вызвала скорую помощь.', 'На щастя, свідка одразу викликала швидку допомогу.', 'Neyse ki bir tanık hemen ambulans çağırdı.'], 'rufen'),
        gap('K2', 'stießen zusammen', I.verb, 'Beide Autos fuhren zu schnell und ', ' an der Ecke zusammen.', 'stießen', ['stoßen', 'stoßten'],
          ['Both cars were going too fast and collided at the corner.', 'Обе машины ехали слишком быстро и столкнулись на углу.', 'Обидві машини їхали надто швидко і зіткнулися на розі.', 'İki araba da çok hızlı gidiyordu ve köşede çarpıştı.'], 'zusammenstoßen (Präteritum)'),
        sb('K2', 'ist passiert', I.order, 'Der Unfall / ist / gestern Abend / in der Bahnhofstraße / passiert.',
          ['The accident happened in Bahnhofstraße yesterday evening.', 'Авария произошла вчера вечером на улице Bahnhofstraße.', 'Аварія сталася вчора ввечері на вулиці Bahnhofstraße.', 'Kaza dün akşam Bahnhofstraße’de oldu.'],
          { alt: ['Gestern Abend ist der Unfall in der Bahnhofstraße passiert.', 'In der Bahnhofstraße ist gestern Abend der Unfall passiert.', 'Der Unfall ist in der Bahnhofstraße gestern Abend passiert.', 'Gestern Abend ist in der Bahnhofstraße der Unfall passiert.', 'In der Bahnhofstraße ist der Unfall gestern Abend passiert.'] }),
      ],
    },
    {
      title: 'Glücksbringer und gute Wünsche',
      t: ['Lucky charms and good wishes', 'Талисманы и добрые пожелания', 'Талісмани і добрі побажання', 'Uğur getiren şeyler ve iyi dilekler'],
      card: {
        id: 'p1_wuensche',
        rule: 'Über Glücksbringer reden: Ein Glücksbringer ist ein Gegenstand, der Glück bringen soll, zum Beispiel ein Kleeblatt, ein Hufeisen oder ein Stein. glauben an + Akkusativ: Ich glaube an Glücksbringer. Ich glaube nicht an so etwas. Die Kette bringt mir Glück. Sie beschützt mich vor Unfällen. Ein Ritual = etwas, was man immer gleich macht. Jemandem etwas wünschen (Dativ): Ich wünsche dir viel Glück / viel Erfolg / alles Gute / gute Besserung. Mit Nebensatz: Ich wünsche dir, dass du schnell wieder gesund wirst.',
        examples: ['Mein Glücksbringer ist eine Muschel vom Meer.', 'Ich glaube nicht an so etwas.', 'Ich wünsche dir, dass du die Stelle bekommst.'],
        highlight: null,
        t: [
          'Talking about lucky charms: a Glücksbringer is an object that is supposed to bring luck, for example ein Kleeblatt (a clover leaf), ein Hufeisen (a horseshoe) or a stone. glauben an + accusative (believe in): Ich glaube an Glücksbringer. Ich glaube nicht an so etwas. (I do not believe in that kind of thing.) Die Kette bringt mir Glück. (The necklace brings me luck.) Sie beschützt mich vor Unfällen. (It protects me from accidents.) Ein Ritual = something you always do in the same way. Wishing somebody something (dative): Ich wünsche dir viel Glück / viel Erfolg (success) / alles Gute (all the best) / gute Besserung (get well soon). With a clause: Ich wünsche dir, dass du schnell wieder gesund wirst.',
          'Как говорить о талисманах: Glücksbringer – это предмет, который должен приносить удачу, например ein Kleeblatt (лист клевера), ein Hufeisen (подкова) или камень. glauben an + Akkusativ (верить в): Ich glaube an Glücksbringer. Ich glaube nicht an so etwas. (Я в такое не верю.) Die Kette bringt mir Glück. (Цепочка приносит мне удачу.) Sie beschützt mich vor Unfällen. (Она защищает меня от несчастных случаев.) Ein Ritual = то, что всегда делают одинаково. Пожелать кому-то (Dativ): Ich wünsche dir viel Glück / viel Erfolg (успехов) / alles Gute (всего хорошего) / gute Besserung (выздоравливай). С придаточным: Ich wünsche dir, dass du schnell wieder gesund wirst.',
          'Як говорити про талісмани: Glücksbringer – це предмет, який має приносити удачу, наприклад ein Kleeblatt (листок конюшини), ein Hufeisen (підкова) або камінь. glauben an + Akkusativ (вірити в): Ich glaube an Glücksbringer. Ich glaube nicht an so etwas. (Я в таке не вірю.) Die Kette bringt mir Glück. (Ланцюжок приносить мені удачу.) Sie beschützt mich vor Unfällen. (Він захищає мене від нещасних випадків.) Ein Ritual = те, що завжди роблять однаково. Побажати комусь (Dativ): Ich wünsche dir viel Glück / viel Erfolg (успіхів) / alles Gute (усього найкращого) / gute Besserung (одужуй). З підрядним реченням: Ich wünsche dir, dass du schnell wieder gesund wirst.',
          'Uğur getiren şeyler hakkında konuşmak: Glücksbringer, şans getirdiğine inanılan bir nesnedir; örneğin ein Kleeblatt (yonca yaprağı), ein Hufeisen (at nalı) ya da bir taş. glauben an + Akkusativ (bir şeye inanmak): Ich glaube an Glücksbringer. Ich glaube nicht an so etwas. (Ben böyle şeylere inanmam.) Die Kette bringt mir Glück. (Kolye bana şans getiriyor.) Sie beschützt mich vor Unfällen. (Beni kazalardan koruyor.) Ein Ritual = her zaman aynı şekilde yapılan şey. Birine bir şey dilemek (Dativ): Ich wünsche dir viel Glück / viel Erfolg (başarılar) / alles Gute (her şey gönlünce olsun) / gute Besserung (geçmiş olsun). Yan cümleyle: Ich wünsche dir, dass du schnell wieder gesund wirst.',
        ],
        hint: ['glauben an + Akkusativ. Das bringt mir Glück. Ich wünsche dir (Dativ) viel Erfolg / …, dass + Verb am Ende.', 'glauben an + accusative. Das bringt mir Glück. Ich wünsche dir (dative) viel Erfolg / …, dass + verb at the end.', 'glauben an + Akkusativ (винительный падеж). Das bringt mir Glück. Ich wünsche dir (Dativ) viel Erfolg / …, dass + глагол в конце.', 'glauben an + Akkusativ (знахідний відмінок). Das bringt mir Glück. Ich wünsche dir (Dativ) viel Erfolg / …, dass + дієслово в кінці.', 'glauben an + Akkusativ (belirtme durumu). Das bringt mir Glück. Ich wünsche dir (Dativ) viel Erfolg / …, dass + fiil sonda.'],
      },
      ex: [
        mc('K3', 'Glück bringen', I.choose, 'Vor jeder Prüfung trägt Nina dieselbe Kette. Sie sagt: „Die Kette … mir Glück.“', ['bringt', 'nimmt', 'wünscht'],
          ['Nina wears the same necklace before every exam. She says: “The necklace … me luck.”', 'Перед каждым экзаменом Nina надевает одну и ту же цепочку. Она говорит: «Цепочка … мне удачу.»', 'Перед кожним іспитом Nina одягає той самий ланцюжок. Вона каже: «Ланцюжок … мені удачу.»', 'Nina her sınavdan önce aynı kolyeyi takıyor. Şöyle diyor: “Kolye bana şans …”']),
        mc('K3', 'glauben an', I.choose, 'Glaubst du eigentlich … Glücksbringer?', ['an', 'auf', 'für'],
          ['Do you actually believe in lucky charms?', 'Ты вообще веришь в талисманы?', 'Ти взагалі віриш у талісмани?', 'Sen uğur getiren şeylere inanır mısın?']),
        mc('K3', 'Ich glaube nicht an so etwas.', I.react, '„Hast du einen Glücksbringer?“ – Du hast keinen und findest so etwas unnötig.', ['Nein, ich glaube nicht an so etwas.', 'Ja, mein Glücksbringer ist ein Stein vom Meer.', 'Ich wünsche dir viel Glück.'],
          ['“Have you got a lucky charm?” – You have not got one and think such things are unnecessary.', '«У тебя есть талисман?» – У вас его нет, и вы считаете это ненужным.', '«У тебе є талісман?» – У вас його немає, і ви вважаєте це непотрібним.', '“Uğur getiren bir şeyin var mı?” – Sizde yok ve böyle şeyleri gereksiz buluyorsunuz.']),
        mc('K3', 'Ritual', I.choose, 'Vor jedem Spiel zieht der Torwart zuerst den linken Schuh an. Das ist sein …', ['Ritual', 'Schaden', 'Zufall'],
          ['Before every match the goalkeeper puts on his left boot first. That is his …', 'Перед каждой игрой вратарь сначала надевает левую бутсу. Это его …', 'Перед кожною грою воротар спочатку взуває ліву бутсу. Це його …', 'Kaleci her maçtan önce ilk olarak sol ayakkabısını giyer. Bu onun …']),
        mc('K4', 'viel Erfolg', I.situation, 'Deine Kollegin hat morgen ein wichtiges Vorstellungsgespräch. Was wünschst du ihr?', ['Ich wünsche dir viel Erfolg!', 'Ich wünsche dir gute Besserung!', 'Ich wünsche dir guten Appetit!'],
          ['Your colleague has an important job interview tomorrow. What do you wish her?', 'У вашей коллеги завтра важное собеседование. Что вы ей пожелаете?', 'У вашої колеги завтра важлива співбесіда. Що ви їй побажаєте?', 'İş arkadaşınızın yarın önemli bir iş görüşmesi var. Ona ne dilersiniz?']),
        mc('K4', 'gute Besserung', I.situation, 'Dein Nachbar liegt seit drei Tagen mit Grippe im Bett. Was sagst du?', ['Gute Besserung! Ich wünsche Ihnen, dass Sie bald wieder gesund sind.', 'Herzlichen Glückwunsch! Ich wünsche Ihnen viel Erfolg.', 'Viel Spaß! Ich wünsche Ihnen eine gute Reise.'],
          ['Your neighbour has been in bed with flu for three days. What do you say?', 'Ваш сосед уже три дня лежит с гриппом. Что вы скажете?', 'Ваш сусід уже три дні лежить із грипом. Що ви скажете?', 'Komşunuz üç gündür gripten yatıyor. Ne dersiniz?']),
        gap('K4', 'dir', I.pronoun, 'Liebe Oma, wir wünschen ', ' alles Gute zum Geburtstag und vor allem Gesundheit!', 'dir', ['dich', 'du'],
          ['Dear Grandma, we wish you all the best for your birthday and above all good health!', 'Дорогая бабушка, мы желаем тебе всего самого доброго в день рождения и прежде всего здоровья!', 'Люба бабусю, ми бажаємо тобі всього найкращого в день народження і передусім здоров’я!', 'Sevgili büyükanne, doğum gününde sana her şeyin en iyisini ve özellikle sağlık diliyoruz!'], 'du'),
        gap('K4', 'dass … findet', I.verb, 'Ich wünsche dir, dass deine Tochter bald eine gute Stelle ', '.', 'findet', ['finden', 'gefunden'],
          ['I hope that your daughter finds a good job soon.', 'Желаю тебе, чтобы твоя дочь скоро нашла хорошую работу.', 'Бажаю тобі, щоб твоя донька скоро знайшла добру роботу.', 'Kızının yakında iyi bir iş bulmasını dilerim.'], 'finden'),
        gap('K3', 'beschützt', I.verb, 'Dieser kleine Stein ', ' mich vor Unfällen – das glaube ich jedenfalls.', 'beschützt', ['beschützen', 'beschütze'],
          ['This little stone protects me from accidents – at least that is what I believe.', 'Этот маленький камень защищает меня от несчастных случаев – по крайней мере, я в это верю.', 'Цей маленький камінь захищає мене від нещасних випадків – принаймні я в це вірю.', 'Bu küçük taş beni kazalardan koruyor – en azından ben buna inanıyorum.'], 'beschützen'),
        sb('K4', 'Ich wünsche dir, dass …', I.order, 'Ich / wünsche / dir, / dass / du / die Prüfung / bestehst.',
          ['I hope that you pass the exam.', 'Желаю тебе сдать экзамен.', 'Бажаю тобі скласти іспит.', 'Sınavı geçmeni dilerim.']),
      ],
    },
    {
      title: 'Zeitungsmeldungen',
      t: ['News items', 'Газетные заметки', 'Газетні замітки', 'Gazete haberleri'],
      card: {
        id: 'p1_meldungen',
        rule: 'Zeitungsmeldungen und Berichte verstehen: Solche Texte stehen im Präteritum (kaufte, gewann, stürzte, brachte). Achte auf die W-Fragen: Wer? Was ist passiert? Wann? Wo? Warum? Was war die Folge? Typische Wörter: die Meldung, der Bericht, erfahren (= eine Information bekommen), übersehen (= nicht sehen), entstehen (Es entstand ein Schaden), leicht / schwer verletzt.',
        examples: ['Die 68-Jährige gewann eine halbe Million Euro.', 'Ein Radfahrer übersah ein Auto und stürzte.', 'Am Auto entstand nur ein kleiner Schaden.'],
        highlight: null,
        t: [
          'Understanding news items and reports: such texts are written in the Präteritum (kaufte, gewann, stürzte, brachte). Look for the wh-questions: who? what happened? when? where? why? what was the result? Typical words: die Meldung (news item), der Bericht (report), erfahren (= to get a piece of information, to learn), übersehen (= not to see, to overlook), entstehen (Es entstand ein Schaden = damage was caused), leicht / schwer verletzt (slightly / seriously injured).',
          'Как понимать газетные заметки и сообщения: такие тексты написаны в Präteritum (kaufte, gewann, stürzte, brachte). Обращайте внимание на вопросы: кто? что произошло? когда? где? почему? каким был результат? Типичные слова: die Meldung (заметка, сообщение), der Bericht (отчёт, сообщение), erfahren (= получить информацию, узнать), übersehen (= не увидеть, не заметить), entstehen (Es entstand ein Schaden = был причинён ущерб), leicht / schwer verletzt (легко / тяжело ранен).',
          'Як розуміти газетні замітки та повідомлення: такі тексти написані в Präteritum (kaufte, gewann, stürzte, brachte). Звертайте увагу на запитання: хто? що сталося? коли? де? чому? яким був наслідок? Типові слова: die Meldung (замітка, повідомлення), der Bericht (звіт, повідомлення), erfahren (= отримати інформацію, дізнатися), übersehen (= не побачити, не помітити), entstehen (Es entstand ein Schaden = було завдано шкоди), leicht / schwer verletzt (легко / тяжко поранений).',
          'Gazete haberlerini ve raporları anlamak: Bu tür metinler Präteritum ile yazılır (kaufte, gewann, stürzte, brachte). Şu sorulara dikkat edin: Kim? Ne oldu? Ne zaman? Nerede? Neden? Sonuç ne oldu? Tipik kelimeler: die Meldung (haber), der Bericht (rapor), erfahren (= bir bilgi almak, öğrenmek), übersehen (= görmemek, gözden kaçırmak), entstehen (Es entstand ein Schaden = hasar oluştu), leicht / schwer verletzt (hafif / ağır yaralı).',
        ],
        hint: ['Meldungen stehen im Präteritum. Such: Wer? Was? Wann? Wo? Warum? Was war die Folge?', 'News items are in the Präteritum. Look for: who? what? when? where? why? what was the result?', 'Заметки пишут в Präteritum. Найдите: кто? что? когда? где? почему? каким был результат?', 'Замітки пишуть у Präteritum. Знайдіть: хто? що? коли? де? чому? яким був наслідок?', 'Haberler Präteritum ile yazılır. Arayın: Kim? Ne? Ne zaman? Nerede? Neden? Sonuç ne oldu?'],
      },
      ex: [
        mc('Z1', 'Was gewonnen?', I.read, `${LOTTO} Was hat die Frau gewonnen?`, ['Eine halbe Million Euro.', 'Eine lange Reise.', 'Ein Los für jede Woche.'],
          ['What did the woman win?', 'Что выиграла женщина?', 'Що виграла жінка?', 'Kadın ne kazandı?']),
        mc('Z1', 'erste Reaktion', I.read, `${LOTTO} Wie reagierte die Frau zuerst auf die Nachricht?`, ['Sie konnte es nicht glauben.', 'Sie buchte sofort eine Reise.', 'Sie kaufte gleich noch ein Los.'],
          ['How did the woman react to the news at first?', 'Как женщина сначала отреагировала на новость?', 'Як жінка спочатку відреагувала на новину?', 'Kadın habere ilk olarak nasıl tepki verdi?']),
        mc('Z1', 'Pläne', I.read, `${LOTTO} Was hat die Frau mit dem Geld vor?`, ['Sie will reisen und ihre Enkel unterstützen.', 'Sie will ein Haus in Kassel kaufen.', 'Sie will alles ihrer Tochter schenken.'],
          ['What does the woman plan to do with the money?', 'Что женщина собирается делать с деньгами?', 'Що жінка збирається робити з грошима?', 'Kadın parayla ne yapmayı düşünüyor?']),
        mc('Z1', 'Ursache', I.read, `${RADFAHRER} Warum passierte der Unfall?`, ['Der Radfahrer sah das Auto nicht.', 'Der Autofahrer bremste nicht.', 'Die Straße war nass.'],
          ['Why did the accident happen?', 'Почему произошла авария?', 'Чому сталася аварія?', 'Kaza neden oldu?']),
        mc('Z1', 'Folge für den Radfahrer', I.read, `${RADFAHRER} Was passierte mit dem Radfahrer?`, ['Er verletzte sich leicht und kam ins Krankenhaus.', 'Er blieb unverletzt und fuhr weiter.', 'Er verletzte sich schwer am Kopf.'],
          ['What happened to the cyclist?', 'Что случилось с велосипедистом?', 'Що сталося з велосипедистом?', 'Bisikletliye ne oldu?']),
        mc('Z1', 'Schaden am Auto', I.read, `${RADFAHRER} Was erfährt man über das Auto?`, ['Es hat nur einen kleinen Schaden.', 'Es ist völlig kaputt.', 'Es wurde gar nicht beschädigt.'],
          ['What do you learn about the car?', 'Что мы узнаём об автомобиле?', 'Що ми дізнаємося про автомобіль?', 'Araba hakkında ne öğreniyoruz?']),
        gap('Z1', 'beobachtet', I.word, 'Die Polizei sucht noch Zeugen: Wer hat den Unfall am Dienstagmorgen ', '?', 'beobachtet', ['bezahlt', 'besucht'],
          ['The police are still looking for witnesses: who observed the accident on Tuesday morning?', 'Полиция ещё ищет свидетелей: кто видел аварию во вторник утром?', 'Поліція ще шукає свідків: хто бачив аварію у вівторок уранці?', 'Polis hâlâ tanık arıyor: Salı sabahı kazayı kim gördü?'],
          ['observed, watched', 'наблюдал, видел', 'спостерігав, бачив', 'gözlemledi, gördü']),
      ],
    },
  ],
}

export default path
