import { I, gap, mc } from '../shared.mjs'

const OWT = 'obwohl / weil / trotzdem'
const PROGRAMM = 'Programmhinweis: „Heute Abend um 20.15 Uhr startet die dritte Staffel. Viele Zuschauer warten seit einem Jahr auf die Serie. Die Hauptfigur, eine junge Anwältin, kehrt in ihre Heimatstadt zurück, obwohl sie dort niemand mehr erwartet. Die ersten beiden Folgen laufen direkt nacheinander. Wer sie verpasst, kann sie eine Woche lang im Internet ansehen.“'
const LESERBRIEF = 'Leserbrief: „Ich verstehe nicht, warum im Fernsehen so viele Krimis laufen. Fast jeden Abend gibt es einen Mord, den ein Kommissar aufklären muss. Meine Kinder, die erst acht und zehn sind, sollen so etwas nicht sehen. Ich wünsche mir mehr Sendungen, bei denen die ganze Familie lachen kann.“'

/** B1.1 · Pfad 2 · Unterhaltung – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Staffel', I.choose, 'Die erste … hatte zwölf Folgen, die zweite hat nur acht.', ['Staffel', 'Handlung', 'Hauptfigur'],
      ['The first … had twelve episodes, the second has only eight.', 'В первом … было двенадцать серий, во втором только восемь.', 'У першому … було дванадцять серій, у другому лише вісім.', 'İlk … on iki bölümdü, ikincisi yalnızca sekiz bölüm.']),
    mc('G1', 'obwohl', I.choose, 'Wir haben den Film im Kino gesehen, … er nächste Woche auch im Fernsehen läuft.', ['obwohl', 'weil', 'deshalb'],
      ['We saw the film at the cinema although it is also on television next week.', 'Мы посмотрели фильм в кино, хотя на следующей неделе его покажут и по телевизору.', 'Ми подивилися фільм у кіно, хоча наступного тижня його покажуть і по телевізору.', 'Film gelecek hafta televizyonda da gösterileceği halde onu sinemada izledik.']),
    mc('G1', 'Trotzdem', I.choose, 'Ich kannte das Ende schon aus dem Buch. … habe ich am Schluss geweint.', ['Trotzdem', 'Obwohl', 'Weil'],
      ['I already knew the ending from the book. Nevertheless I cried at the end.', 'Я уже знал конец по книге. Тем не менее в конце я плакал.', 'Я вже знав кінець із книжки. Попри це наприкінці я плакав.', 'Sonunu kitaptan zaten biliyordum. Buna rağmen sonunda ağladım.'], { c: 'p2_obwohl_weil' }),
    mc('G2', 'echt', I.choose, 'Welcher Satz drückt die größte Begeisterung aus?', ['Das Konzert war echt toll!', 'Das Konzert war nicht so toll.', 'Das Konzert war gar nicht toll.'],
      ['Which sentence expresses the greatest enthusiasm?', 'Какое предложение выражает наибольший восторг?', 'Яке речення виражає найбільший захват?', 'Hangi cümle en büyük hayranlığı ifade eder?']),
    mc('G3', 'die', I.choose, 'Wo ist denn die Fernbedienung, … gestern noch auf dem Sofa lag?', ['die', 'der', 'den'],
      ['Where is the remote control that was still lying on the sofa yesterday?', 'Где же пульт, который ещё вчера лежал на диване?', 'Де ж пульт, який ще вчора лежав на дивані?', 'Dün hâlâ kanepenin üstünde duran kumanda nerede?']),
    mc('G4', 'den', I.choose, 'Der Schauspieler, … ich am liebsten mag, spielt in diesem Film nur eine kleine Rolle.', ['den', 'der', 'dem'],
      ['The actor I like best plays only a small part in this film.', 'Актёр, который мне нравится больше всех, играет в этом фильме лишь небольшую роль.', 'Актор, який мені подобається найбільше, грає в цьому фільмі лише невелику роль.', 'En sevdiğim oyuncu bu filmde yalnızca küçük bir rol oynuyor.']),
    mc('G5', 'von der', I.choose, 'Das ist die Freundin, von … ich dir schon so viel erzählt habe.', ['der', 'die', 'dem'],
      ['That is the friend I have already told you so much about.', 'Это подруга, о которой я тебе уже так много рассказывал.', 'Це подруга, про яку я тобі вже так багато розповідав.', 'Bu, sana hakkında çok şey anlattığım arkadaşım.']),
    mc('K1', 'handelt von', I.choose, 'Der Film … von zwei Schwestern, die sich nach zwanzig Jahren wiedersehen.', ['handelt', 'geht', 'spielt'],
      ['The film is about two sisters who see each other again after twenty years.', 'Фильм рассказывает о двух сёстрах, которые встречаются снова через двадцать лет.', 'Фільм розповідає про двох сестер, які зустрічаються знову через двадцять років.', 'Film, yirmi yıl sonra yeniden buluşan iki kız kardeşi anlatıyor.']),
    mc('K2', 'Gegenvorschlag', I.situation, 'Deine Freunde wollen ins Kino, aber du hast eine andere Idee. Was sagst du?', ['Ich würde lieber zu Hause einen Film schauen.', 'Da hast du völlig recht.', 'Einverstanden!'],
      ['Your friends want to go to the cinema, but you have another idea. What do you say?', 'Ваши друзья хотят в кино, но у вас другая идея. Что вы скажете?', 'Ваші друзі хочуть у кіно, але у вас інша ідея. Що ви скажете?', 'Arkadaşlarınız sinemaya gitmek istiyor ama sizin başka bir fikriniz var. Ne dersiniz?']),
    mc('K4', 'guter Vorschlag', I.react, '„Wollen wir heute den Dokumentarfilm über Wale sehen?“ – Du findest die Idee prima.', ['Das ist ein guter Vorschlag!', 'Das kommt für mich nicht infrage.', 'Auf keinen Fall!'],
      ['“Shall we watch the documentary about whales today?” – You think the idea is great.', '«Посмотрим сегодня документальный фильм о китах?» – Вам очень нравится эта идея.', '«Подивимося сьогодні документальний фільм про китів?» – Вам дуже подобається ця ідея.', '“Bugün balinalarla ilgili belgeseli izleyelim mi?” – Fikri çok beğeniyorsunuz.']),
    mc('Z1', 'verpasste Folgen', I.read, `${PROGRAMM} Wo kann man die Folgen noch sehen, wenn man sie verpasst hat?`, ['Eine Woche lang im Internet.', 'Am nächsten Abend im Fernsehen.', 'Gar nicht mehr.'],
      ['Where can you still watch the episodes if you missed them?', 'Где ещё можно посмотреть серии, если вы их пропустили?', 'Де ще можна подивитися серії, якщо ви їх пропустили?', 'Bölümleri kaçırdıysanız onları nerede izleyebilirsiniz?']),
    gap('K3', 'auf keinen Fall', I.ending, 'Drei Stunden nur Werbung schauen? Nein, auf ', ' Fall!', 'keinen', ['kein', 'keinem'],
      ['Watch nothing but adverts for three hours? No, definitely not!', 'Три часа смотреть одну рекламу? Нет, ни в коем случае!', 'Три години дивитися саму рекламу? Ні, у жодному разі!', 'Üç saat boyunca yalnızca reklam mı izleyelim? Hayır, kesinlikle olmaz!'], 'kein'),
    gap('G5', 'mit denen', I.pronoun, 'Die Leute, mit ', ' ich gestern im Kino war, kannte ich vorher gar nicht.', 'denen', ['den', 'die'],
      ['I did not know the people I went to the cinema with yesterday at all before.', 'Людей, с которыми я вчера был в кино, я раньше совсем не знал.', 'Людей, із якими я вчора був у кіно, я раніше зовсім не знав.', 'Dün birlikte sinemaya gittiğim insanları daha önce hiç tanımıyordum.'], 'den / denen / die'),
  ],
  size: 13,
  test: [
    mc('W1', 'Werbung', I.choose, 'Vor dem Film läuft im Kino oft zwanzig Minuten lang … für Autos, Getränke und Handys.', ['Werbung', 'Handlung', 'Hauptfigur'],
      ['Before the film there are often twenty minutes of … for cars, drinks and mobile phones at the cinema.', 'Перед фильмом в кинотеатре часто двадцать минут идёт … автомобилей, напитков и телефонов.', 'Перед фільмом у кінотеатрі часто двадцять хвилин іде … автомобілів, напоїв і телефонів.', 'Sinemada filmden önce çoğu zaman yirmi dakika boyunca araba, içecek ve telefon … gösterilir.']),
    mc('G1', 'Obwohl', I.choose, '… ich den Schauspieler nicht besonders mag, finde ich seinen neuen Film gelungen.', ['Obwohl', 'Weil', 'Trotzdem'],
      ['Although I do not particularly like the actor, I think his new film is a success.', 'Хотя этот актёр мне не особенно нравится, его новый фильм я считаю удачным.', 'Хоча цей актор мені не особливо подобається, його новий фільм я вважаю вдалим.', 'Oyuncuyu pek sevmediğim halde yeni filmini başarılı buluyorum.']),
    mc('G1', 'Verb am Ende', I.sentence, 'Der Eintritt war teuer. Wir sind ins Konzert gegangen.', ['Wir sind ins Konzert gegangen, obwohl der Eintritt teuer war.', 'Wir sind ins Konzert gegangen, obwohl der Eintritt war teuer.', 'Wir sind ins Konzert gegangen, obwohl teuer der Eintritt war.'],
      ['The tickets were expensive. We went to the concert.', 'Вход был дорогим. Мы пошли на концерт.', 'Вхід був дорогий. Ми пішли на концерт.', 'Giriş pahalıydı. Konsere gittik.']),
    mc('G1', 'weil', I.choose, 'Die Serie bekam nur eine Staffel, … die Produktion viel zu teuer war.', ['weil', 'obwohl', 'trotzdem'],
      ['The series only got one season because the production was far too expensive.', 'У сериала был только один сезон, потому что производство было слишком дорогим.', 'У серіалу був лише один сезон, бо виробництво було надто дороге.', 'Yapım çok pahalı olduğu için dizi yalnızca bir sezon sürdü.'], { c: 'p2_obwohl_weil' }),
    mc('G2', 'gar nicht', I.choose, 'Das Buch hat mir … nicht gefallen. Ich habe nach dreißig Seiten aufgehört.', ['gar', 'ziemlich', 'total'],
      ['I did not like the book at all. I stopped after thirty pages.', 'Книга мне совсем не понравилась. Я бросил её через тридцать страниц.', 'Книжка мені зовсім не сподобалася. Я кинув її через тридцять сторінок.', 'Kitabı hiç beğenmedim. Otuz sayfadan sonra bıraktım.']),
    mc('G2', 'ziemlich', I.choose, 'Was bedeutet „Der Film war ziemlich gut.“?', ['Er war gut, aber nicht perfekt.', 'Er war überhaupt nicht gut.', 'Er war der schlechteste Film.'],
      ['What does “Der Film war ziemlich gut.” mean?', 'Что означает «Der Film war ziemlich gut.»?', 'Що означає «Der Film war ziemlich gut.»?', '“Der Film war ziemlich gut.” ne demek?']),
    mc('G3', 'der', I.choose, 'Wer ist eigentlich der Mann, … dort neben der Regisseurin sitzt?', ['der', 'den', 'dem'],
      ['Who is the man who is sitting next to the director over there?', 'Кто этот мужчина, который сидит там рядом с режиссёром?', 'Хто цей чоловік, який сидить там поруч із режисеркою?', 'Orada yönetmenin yanında oturan adam kim?']),
    mc('G3', 'die (Plural)', I.choose, 'Ich mag Geschichten, … am Ende gut ausgehen.', ['die', 'das', 'der'],
      ['I like stories that turn out well in the end.', 'Мне нравятся истории, которые хорошо заканчиваются.', 'Мені подобаються історії, які добре закінчуються.', 'Sonu iyi biten hikâyeleri severim.']),
    mc('G4', 'den', I.choose, 'Das ist genau der Krimi, … ich schon lange lesen wollte.', ['den', 'der', 'dem'],
      ['That is exactly the crime novel that I have wanted to read for a long time.', 'Это именно тот детектив, который я давно хотел прочитать.', 'Це саме той детектив, який я давно хотів прочитати.', 'Bu tam da uzun zamandır okumak istediğim polisiye.']),
    mc('G4', 'Relativsatz bilden', I.sentence, 'Wir haben gestern eine Komödie gesehen. Sie war gar nicht lustig.', ['Die Komödie, die wir gestern gesehen haben, war gar nicht lustig.', 'Die Komödie, der wir gestern gesehen haben, war gar nicht lustig.', 'Die Komödie, die wir haben gestern gesehen, war gar nicht lustig.'],
      ['We saw a comedy yesterday. It was not funny at all.', 'Вчера мы посмотрели комедию. Она была совсем не смешной.', 'Учора ми подивилися комедію. Вона була зовсім не смішна.', 'Dün bir komedi izledik. Hiç komik değildi.']),
    mc('G5', 'dem', I.choose, 'Der Kollege, … ich die Kinokarten gegeben habe, hat sich sehr gefreut.', ['dem', 'den', 'der'],
      ['The colleague to whom I gave the cinema tickets was very pleased.', 'Коллега, которому я отдал билеты в кино, очень обрадовался.', 'Колега, якому я віддав квитки в кіно, дуже зрадів.', 'Sinema biletlerini verdiğim iş arkadaşım çok sevindi.']),
    mc('G5', 'in der', I.choose, 'Das ist die Stadt, in … die ganze Serie gedreht wurde.', ['der', 'die', 'dem'],
      ['That is the town in which the whole series was filmed.', 'Это город, в котором снимали весь сериал.', 'Це місто, у якому знімали весь серіал.', 'Bu, bütün dizinin çekildiği şehir.']),
    mc('K1', 'Hauptfigur', I.react, '„Wer ist denn die Hauptfigur in dem Film?“', ['Eine alte Dame, die allein auf einer Insel lebt.', 'Er dauert ungefähr zwei Stunden.', 'Er läuft im Kino am Markt.'],
      ['“So who is the main character in the film?”', '«А кто главный герой в фильме?»', '«А хто головний герой у фільмі?»', '“Filmdeki ana karakter kim?”']),
    mc('K1', 'es geht um', I.choose, 'In dem Roman … es um eine Freundschaft, die ein ganzes Leben hält.', ['geht', 'handelt', 'spielt'],
      ['The novel is about a friendship that lasts a whole lifetime.', 'В романе речь идёт о дружбе, которая длится всю жизнь.', 'У романі йдеться про дружбу, яка триває все життя.', 'Roman, bir ömür süren bir dostluğu anlatıyor.']),
    mc('K2', 'Wie wäre es, wenn …?', I.choose, 'Wie … es, wenn wir uns den Film am Sonntag zusammen ansehen?', ['wäre', 'hätte', 'würde'],
      ['How about watching the film together on Sunday?', 'Как насчёт того, чтобы посмотреть фильм вместе в воскресенье?', 'Як щодо того, щоб подивитися фільм разом у неділю?', 'Filmi pazar günü birlikte izlesek nasıl olur?']),
    mc('K3', 'Das möchte ich wirklich nicht.', I.react, '„Wir könnten uns heute Abend die Talkshow ansehen.“ – Du findest Talkshows schrecklich.', ['Das möchte ich wirklich nicht.', 'Einverstanden, das machen wir.', 'Da bin ich auch dafür.'],
      ['“We could watch the talk show tonight.” – You think talk shows are awful.', '«Мы могли бы сегодня вечером посмотреть ток-шоу.» – Вы считаете ток-шоу ужасными.', '«Ми могли б сьогодні ввечері подивитися ток-шоу.» – Ви вважаєте ток-шоу жахливими.', '“Bu akşam talk show’u izleyebiliriz.” – Talk show’ları berbat buluyorsunuz.']),
    mc('K4', 'Da hast du völlig recht.', I.react, '„Wir sollten die Karten schon heute kaufen. Morgen sind sie vielleicht weg.“ – Du bist derselben Meinung.', ['Da hast du völlig recht.', 'Auf keinen Fall!', 'Das kommt nicht infrage.'],
      ['“We should buy the tickets today. Tomorrow they may be gone.” – You are of the same opinion.', '«Нам стоит купить билеты уже сегодня. Завтра их может не быть.» – Вы того же мнения.', '«Нам варто купити квитки вже сьогодні. Завтра їх може не бути.» – Ви тієї самої думки.', '“Biletleri bugünden almalıyız. Yarın belki kalmaz.” – Siz de aynı görüştesiniz.']),
    mc('Z1', 'Was stört die Person?', I.read, `${LESERBRIEF} Was stört die Person?`, ['Dass im Fernsehen zu viele Krimis laufen.', 'Dass ihre Kinder zu viel lachen.', 'Dass der Kommissar zu alt ist.'],
      ['What bothers the person?', 'Что не нравится этому человеку?', 'Що не подобається цій людині?', 'Bu kişiyi rahatsız eden ne?']),
    mc('Z1', 'Hauptfigur', I.read, `${PROGRAMM} Was erfährt man über die Hauptfigur?`, ['Sie kommt in ihre Heimatstadt zurück.', 'Sie wartet seit einem Jahr.', 'Sie verpasst zwei Folgen.'],
      ['What do you learn about the main character?', 'Что мы узнаём о главной героине?', 'Що ми дізнаємося про головну героїню?', 'Ana karakter hakkında ne öğreniyoruz?']),
    gap('W1', 'Zuschauer', I.word, 'Der Film lief vor fast leerem Saal: Nur fünf ', ' waren gekommen.', 'Zuschauer', ['Untertitel', 'Folgen'],
      ['The film was shown to an almost empty auditorium: only five viewers had come.', 'Фильм шёл почти в пустом зале: пришли только пять зрителей.', 'Фільм ішов майже в порожній залі: прийшли лише п’ять глядачів.', 'Film neredeyse boş bir salonda gösterildi: Yalnızca beş izleyici gelmişti.'],
      ['viewers', 'зрители', 'глядачі', 'izleyiciler']),
    gap('G1', 'obwohl', I.conjunction, 'Sie sieht sich jeden Abend die Nachrichten an, ', ' sie danach oft schlechte Laune hat.', 'obwohl', ['weil', 'trotzdem'],
      ['She watches the news every evening although she is often in a bad mood afterwards.', 'Она каждый вечер смотрит новости, хотя после этого у неё часто плохое настроение.', 'Вона щовечора дивиться новини, хоча після цього в неї часто поганий настрій.', 'Sonrasında çoğu zaman morali bozulduğu halde her akşam haberleri izliyor.'], OWT),
    gap('G2', 'ziemlich', I.word, 'Der Regisseur ist ', ' bekannt, fast jeder kennt seinen Namen.', 'ziemlich', ['gar nicht', 'nicht so'],
      ['The director is quite well known; almost everyone knows his name.', 'Режиссёр довольно известен, почти все знают его имя.', 'Режисер досить відомий, майже всі знають його ім’я.', 'Yönetmen oldukça tanınıyor, neredeyse herkes adını biliyor.'], 'ziemlich / gar nicht / nicht so'),
    gap('G3', 'der', I.pronoun, 'Das ist ein Film, ', ' auch kleinen Kindern Spaß macht.', 'der', ['den', 'dem'],
      ['That is a film that small children enjoy too.', 'Это фильм, который нравится и маленьким детям.', 'Це фільм, який подобається й маленьким дітям.', 'Bu, küçük çocukların da hoşuna giden bir film.'], 'der / den / dem'),
    gap('G4', 'die', I.pronoun, 'Die Schauspielerin, ', ' wir gestern im Restaurant gesehen haben, ist sehr berühmt.', 'die', ['der', 'den'],
      ['The actress whom we saw in the restaurant yesterday is very famous.', 'Актриса, которую мы вчера видели в ресторане, очень знаменита.', 'Акторка, яку ми вчора бачили в ресторані, дуже відома.', 'Dün restoranda gördüğümüz kadın oyuncu çok ünlü.'], 'die / der / den'),
    gap('G5', 'dem', I.pronoun, 'Der Freund, ', ' ich die Serie empfohlen habe, hat sie in drei Tagen geschaut.', 'dem', ['den', 'der'],
      ['The friend to whom I recommended the series watched it in three days.', 'Друг, которому я посоветовал сериал, посмотрел его за три дня.', 'Друг, якому я порадив серіал, подивився його за три дні.', 'Diziyi önerdiğim arkadaşım onu üç günde izledi.'], 'der / den / dem'),
    gap('G5', 'denen', I.pronoun, 'Die Zuschauer, ', ' der Film nicht gefallen hat, haben ihr Geld zurückbekommen.', 'denen', ['die', 'den'],
      ['The viewers who did not like the film got their money back.', 'Зрители, которым фильм не понравился, получили деньги обратно.', 'Глядачі, яким фільм не сподобався, отримали гроші назад.', 'Filmi beğenmeyen izleyiciler paralarını geri aldı.'], 'die / den / denen'),
    gap('K1', 'spielt', I.verb, 'Die Serie ', ' in einem kleinen Dorf an der Nordsee, in dem jeder jeden kennt.', 'spielt', ['handelt', 'dreht'],
      ['The series is set in a small village on the North Sea where everybody knows everybody.', 'Действие сериала происходит в маленькой деревне на Северном море, где все друг друга знают.', 'Дія серіалу відбувається в маленькому селі на Північному морі, де всі одне одного знають.', 'Dizi, herkesin birbirini tanıdığı Kuzey Denizi kıyısındaki küçük bir köyde geçiyor.'], 'spielen / handeln / drehen'),
    gap('K2', 'Lass uns …', I.pronoun, 'Lass ', ' doch am Freitag zusammen kochen und danach einen Film sehen!', 'uns', ['wir', 'unser'],
      ['Let’s cook together on Friday and watch a film afterwards!', 'Давай в пятницу вместе приготовим ужин, а потом посмотрим фильм!', 'Приготуймо в п’ятницю разом вечерю, а потім подивімося фільм!', 'Hadi cuma günü birlikte yemek yapalım, sonra da bir film izleyelim!'], 'wir'),
    gap('K3', 'auf keinen Fall', I.expression, 'Noch eine Folge? Nein, auf keinen ', '! Ich muss morgen um sechs aufstehen.', 'Fall', ['Weg', 'Tag'],
      ['Another episode? No, definitely not! I have to get up at six tomorrow.', 'Ещё одну серию? Нет, ни в коем случае! Мне завтра вставать в шесть.', 'Ще одну серію? Ні, у жодному разі! Мені завтра вставати о шостій.', 'Bir bölüm daha mı? Hayır, kesinlikle olmaz! Yarın altıda kalkmam gerekiyor.'],
      ['case (auf keinen Fall = on no account)', 'случай (auf keinen Fall = ни в коем случае)', 'випадок (auf keinen Fall = у жодному разі)', 'durum (auf keinen Fall = asla)']),
    gap('K4', 'dafür sein', I.word, 'Ich bin auch ', ', dass wir zuerst essen und dann den Film schauen. So machen wir es!', 'dafür', ['dagegen', 'darum'],
      ['I am also in favour of eating first and then watching the film. That is what we will do!', 'Я тоже за то, чтобы мы сначала поели, а потом посмотрели фильм. Так и сделаем!', 'Я теж за те, щоб ми спочатку поїли, а потім подивилися фільм. Так і зробимо!', 'Ben de önce yemek yiyip sonra filmi izlememizden yanayım. Öyle yapalım!'],
      ['in favour', 'за', 'за', 'bundan yana']),
  ],
}

export default check
