import { I, gap, mc, sb } from '../shared.mjs'

const OWT = 'obwohl / weil / trotzdem'
const STATISTIK = 'Umfrage: „Wie viel Zeit verbringen die Menschen in Deutschland vor dem Bildschirm? Im Durchschnitt sehen Erwachsene täglich etwa dreieinhalb Stunden fern. Menschen über 60 schauen am meisten, nämlich mehr als fünf Stunden. Jugendliche sitzen nur noch etwa eine Stunde vor dem Fernseher, obwohl sie insgesamt viel Zeit mit Filmen verbringen: Sie schauen Serien lieber im Internet. Jeder Dritte sagt, dass er beim Fernsehen gleichzeitig das Handy benutzt.“'
const KINO = 'Aus einem Stadtmagazin: „Das kleine Kino am Markt, das vor zwei Jahren fast schließen musste, ist wieder voll. Die neue Besitzerin zeigt jeden Donnerstag Filme in Originalsprache mit Untertiteln. Besonders beliebt sind die Abende, an denen nach dem Film über das Thema diskutiert wird. Die Karten kosten nicht besonders viel: sieben Euro, für Schüler fünf.“'

/** B1.1 · Pfad 2 · Unterhaltung – Lektionen. Wiederholung und Test: p2-check.mjs */
const path = {
  n: 2,
  slug: 'unterhaltung',
  title: 'Unterhaltung',
  t: ['Entertainment', 'Развлечения', 'Розваги', 'Eğlence'],
  objectives: {
    G1: "Gegensatz mit obwohl: Leo schaut den Film noch einmal, obwohl er das Ende schon kennt. Das Verb steht im Nebensatz am Ende; Unterschied zu weil und trotzdem.",
    G2: 'Gradpartikeln: echt, total, besonders – ziemlich, wirklich – nicht so, nicht besonders – gar nicht, überhaupt nicht.',
    G3: 'Relativpronomen im Nominativ: der Mann, der …; das Kind, das …; die Frau, die …; die Leute, die …',
    G4: 'Relativpronomen im Akkusativ: der Film, den ich mag; das Buch, das ich lese; die Serie, die wir schauen.',
    G5: 'Relativpronomen im Dativ und mit Präposition: der Freund, dem ich helfe; die Kollegin, mit der ich arbeite; die Leute, bei denen ich wohne.',
    K1: 'Die Lieblingsserie oder den Lieblingsfilm beschreiben: In der Serie geht es um … Sie handelt von … Die Hauptfigur ist … Die Serie spielt in …',
    K2: 'Etwas vorschlagen und einen Gegenvorschlag machen: Lass uns doch … Wie wäre es, wenn …? Ich würde lieber …',
    K3: 'Etwas ablehnen: Das kommt für mich nicht infrage. Das möchte ich wirklich nicht. Nein, auf keinen Fall.',
    K4: 'Zustimmen und sich einigen: Das ist ein guter Vorschlag! Da hast du völlig recht. Einverstanden!',
    Z1: 'Kann-Ziele: eine Statistik und kurze Texte über Fernsehen, Kino und Medien verstehen.',
    W1: 'Wortschatz: Kino und Fernsehen.',
  },
  nodes: [
    {
      title: 'Kino und Fernsehen',
      t: ['Cinema and television', 'Кино и телевидение', 'Кіно і телебачення', 'Sinema ve televizyon'],
      card: {
        id: 'p2_kino',
        rule: 'Kino und Fernsehen: Eine Serie besteht aus Staffeln, eine Staffel aus Folgen. Die Hauptfigur ist die wichtigste Person in der Geschichte, die Handlung ist das, was passiert. Der Schauspieler / die Schauspielerin spielt eine Rolle, der Regisseur / die Regisseurin leitet die Arbeit am Film. Arten: der Krimi, die Komödie (lustig), der Liebesfilm, der Dokumentarfilm, die Nachrichten, die Sendung. Der Zuschauer / die Zuschauerin sieht zu. Der Sender zeigt das Programm. Mit Untertiteln kann man den Text mitlesen. Mit der Fernbedienung schaltet man um. spannend ↔ langweilig.',
        examples: ['Die zweite Staffel hat nur acht Folgen.', 'Die Hauptfigur ist eine junge Ärztin.', 'Ich schaue Filme am liebsten mit Untertiteln.'],
        highlight: 'article',
        t: [
          'Cinema and television: a series (die Serie) consists of seasons (Staffeln), a season of episodes (Folgen). Die Hauptfigur is the most important person in the story (main character), die Handlung is what happens (plot). Der Schauspieler / die Schauspielerin (actor / actress) plays a role, der Regisseur / die Regisseurin (director) leads the work on the film. Types: der Krimi (crime story), die Komödie (comedy: funny), der Liebesfilm (romantic film), der Dokumentarfilm (documentary), die Nachrichten (news), die Sendung (programme). Der Zuschauer / die Zuschauerin (viewer) watches. Der Sender (channel) shows das Programm. With Untertitel (subtitles) you can read along. With die Fernbedienung (remote control) you change channel. spannend (exciting) ↔ langweilig (boring).',
          'Кино и телевидение: сериал (die Serie) состоит из сезонов (Staffeln), сезон – из серий (Folgen). Die Hauptfigur – самый важный человек в истории (главный герой), die Handlung – то, что происходит (сюжет). Der Schauspieler / die Schauspielerin (актёр / актриса) играет роль, der Regisseur / die Regisseurin (режиссёр) руководит работой над фильмом. Жанры: der Krimi (детектив), die Komödie (комедия: смешно), der Liebesfilm (фильм о любви), der Dokumentarfilm (документальный фильм), die Nachrichten (новости), die Sendung (передача). Der Zuschauer / die Zuschauerin (зритель / зрительница) смотрит. Der Sender (канал) показывает das Programm. С Untertitel (субтитрами) можно читать текст. С помощью die Fernbedienung (пульта) переключают каналы. spannend (увлекательный) ↔ langweilig (скучный).',
          'Кіно і телебачення: серіал (die Serie) складається із сезонів (Staffeln), сезон – із серій (Folgen). Die Hauptfigur – найважливіша людина в історії (головний герой), die Handlung – те, що відбувається (сюжет). Der Schauspieler / die Schauspielerin (актор / акторка) грає роль, der Regisseur / die Regisseurin (режисер / режисерка) керує роботою над фільмом. Жанри: der Krimi (детектив), die Komödie (комедія: смішно), der Liebesfilm (фільм про кохання), der Dokumentarfilm (документальний фільм), die Nachrichten (новини), die Sendung (передача). Der Zuschauer / die Zuschauerin (глядач / глядачка) дивиться. Der Sender (канал) показує das Programm. З Untertitel (субтитрами) можна читати текст. За допомогою die Fernbedienung (пульта) перемикають канали. spannend (захопливий) ↔ langweilig (нудний).',
          'Sinema ve televizyon: Bir dizi (die Serie) sezonlardan (Staffeln), bir sezon bölümlerden (Folgen) oluşur. Die Hauptfigur hikâyedeki en önemli kişidir (ana karakter), die Handlung ise olup bitenlerdir (olay örgüsü). Der Schauspieler / die Schauspielerin (oyuncu) bir rol oynar, der Regisseur / die Regisseurin (yönetmen) filmin çalışmalarını yönetir. Türler: der Krimi (polisiye), die Komödie (komedi: komik), der Liebesfilm (aşk filmi), der Dokumentarfilm (belgesel), die Nachrichten (haberler), die Sendung (program). Der Zuschauer / die Zuschauerin (izleyici) izler. Der Sender (kanal) das Programm’ı gösterir. Untertitel (altyazı) ile metin okunabilir. Die Fernbedienung (kumanda) ile kanal değiştirilir. spannend (sürükleyici) ↔ langweilig (sıkıcı).',
        ],
        hint: ['Serie → Staffel → Folge. Hauptfigur = wichtigste Person. Handlung = was passiert. Zuschauer = wer zusieht.', 'Serie → Staffel → Folge. Hauptfigur = most important person. Handlung = what happens. Zuschauer = the person watching.', 'Serie → Staffel → Folge. Hauptfigur = самый важный человек. Handlung = то, что происходит. Zuschauer = тот, кто смотрит.', 'Serie → Staffel → Folge. Hauptfigur = найважливіша людина. Handlung = те, що відбувається. Zuschauer = той, хто дивиться.', 'Serie → Staffel → Folge. Hauptfigur = en önemli kişi. Handlung = olup bitenler. Zuschauer = izleyen kişi.'],
      },
      ex: [
        mc('W1', 'Folgen', I.choose, 'Die neue Serie hat zwei Staffeln. Jede Staffel besteht aus zehn …', ['Folgen', 'Sendern', 'Zuschauern'],
          ['The new series has two seasons. Each season consists of ten …', 'В новом сериале два сезона. Каждый сезон состоит из десяти …', 'У новому серіалі два сезони. Кожен сезон складається з десяти …', 'Yeni dizinin iki sezonu var. Her sezon on … oluşuyor.']),
        mc('W1', 'Hauptfigur', I.choose, 'Die wichtigste Person in einem Film oder in einem Roman nennt man die …', ['Hauptfigur', 'Handlung', 'Fernbedienung'],
          ['The most important person in a film or a novel is called the …', 'Самого важного человека в фильме или романе называют …', 'Найважливішу людину у фільмі чи романі називають …', 'Bir filmdeki ya da romandaki en önemli kişiye … denir.']),
        mc('W1', 'Komödie', I.choose, 'Bei einer … lacht man viel, bei einem Krimi möchte man wissen, wer der Täter ist.', ['Komödie', 'Nachrichtensendung', 'Staffel'],
          ['In a … you laugh a lot; in a crime story you want to know who did it.', 'На … много смеются, а в детективе хочется узнать, кто преступник.', 'На … багато сміються, а в детективі хочеться дізнатися, хто злочинець.', 'Bir … çok gülünür, bir polisiyede ise suçlunun kim olduğu merak edilir.']),
        mc('W1', 'Personen beim Film', I.odd, 'Drei Wörter bezeichnen Personen, ein Wort nicht.', ['die Handlung', 'der Regisseur', 'die Schauspielerin', 'der Zuschauer'], null),
        mc('W1', 'Untertitel', I.choose, 'Ich verstehe den Film auf Englisch nicht so gut. Deshalb schalte ich die deutschen … ein.', ['Untertitel', 'Zuschauer', 'Schauspieler'],
          ['I do not understand the film in English very well. So I switch on the German …', 'Я не очень хорошо понимаю фильм на английском. Поэтому я включаю немецкие …', 'Я не дуже добре розумію фільм англійською. Тому я вмикаю німецькі …', 'Filmi İngilizce pek iyi anlamıyorum. Bu yüzden Almanca … açıyorum.']),
        gap('W1', 'Fernbedienung', I.word, 'Wo ist denn die ', '? Ich möchte den Fernseher lauter machen.', 'Fernbedienung', ['Handlung', 'Hauptfigur'],
          ['Where is the remote control? I want to turn the television up.', 'Где же пульт? Я хочу сделать телевизор погромче.', 'Де ж пульт? Я хочу зробити телевізор гучніше.', 'Kumanda nerede? Televizyonun sesini açmak istiyorum.'],
          ['remote control', 'пульт', 'пульт', 'kumanda']),
        gap('W1', 'spannend', I.word, 'Der Krimi war so ', ', dass ich bis zwei Uhr nachts weitergeschaut habe.', 'spannend', ['langweilig', 'leise'],
          ['The crime series was so gripping that I kept watching until two in the morning.', 'Детектив был таким увлекательным, что я смотрел его до двух часов ночи.', 'Детектив був такий захопливий, що я дивився його до другої години ночі.', 'Polisiye o kadar sürükleyiciydi ki gece ikiye kadar izlemeye devam ettim.'],
          ['exciting, gripping', 'увлекательный, захватывающий', 'захопливий', 'sürükleyici, heyecanlı']),
        gap('W1', 'Handlung', I.word, 'Die ', ' von diesem Film ist kompliziert: Am Anfang versteht man gar nicht, was passiert.', 'Handlung', ['Folge', 'Werbung'],
          ['The plot of this film is complicated: at the beginning you do not understand at all what is happening.', 'Сюжет этого фильма сложный: вначале совсем не понимаешь, что происходит.', 'Сюжет цього фільму складний: спочатку зовсім не розумієш, що відбувається.', 'Bu filmin olay örgüsü karmaşık: Başta ne olduğunu hiç anlamıyorsunuz.'],
          ['plot', 'сюжет', 'сюжет', 'olay örgüsü']),
        gap('W1', 'Regisseur', I.word, 'Der ', ' hat schon viele berühmte Filme gedreht. Er sagt den Schauspielern, was sie tun sollen.', 'Regisseur', ['Zuschauer', 'Sender'],
          ['The director has already made many famous films. He tells the actors what to do.', 'Режиссёр снял уже много знаменитых фильмов. Он говорит актёрам, что им делать.', 'Режисер зняв уже багато відомих фільмів. Він каже акторам, що їм робити.', 'Yönetmen şimdiye kadar birçok ünlü film çekti. Oyunculara ne yapmaları gerektiğini söyler.'],
          ['director', 'режиссёр', 'режисер', 'yönetmen']),
        sb('W1', 'Staffel', I.order, 'Am Wochenende / schauen / wir / oft / eine ganze Staffel.',
          ['At the weekend we often watch a whole season.', 'В выходные мы часто смотрим целый сезон.', 'На вихідних ми часто дивимося цілий сезон.', 'Hafta sonu sık sık bütün bir sezonu izliyoruz.'],
          { alt: ['Wir schauen am Wochenende oft eine ganze Staffel.', 'Wir schauen oft am Wochenende eine ganze Staffel.', 'Oft schauen wir am Wochenende eine ganze Staffel.'] }),
      ],
    },
    {
      title: 'obwohl',
      t: ['obwohl (although)', 'obwohl (хотя)', 'obwohl (хоча)', 'obwohl (-diği halde)'],
      card: {
        id: 'p2_obwohl',
        rule: 'obwohl verbindet zwei Aussagen, die eigentlich nicht zusammenpassen: Etwas spricht dagegen, aber es passiert doch. obwohl leitet einen Nebensatz ein, das Verb steht am Ende: Lea schaut den Film, obwohl sie das Ende schon kennt. Bei Perfekt und Modalverb steht das konjugierte Verb ganz am Ende: …, obwohl sie ihn schon gesehen hat. …, obwohl sie früh aufstehen muss. Steht der obwohl-Satz am Anfang, beginnt der Hauptsatz mit dem Verb: Obwohl es regnet, gehen wir ins Kino.',
        examples: ['Ich schaue die Serie weiter, obwohl ich sehr müde bin.', 'Obwohl der Film alt ist, gefällt er mir.', 'Er kam mit, obwohl er keine Lust hatte.'],
        highlight: 'verb',
        t: [
          'obwohl (although) links two statements that do not really fit together: something speaks against it, but it happens anyway. obwohl introduces a subordinate clause; the verb goes at the end: Lea schaut den Film, obwohl sie das Ende schon kennt. (Lea watches the film although she already knows the ending.) With the Perfekt and modal verbs the conjugated verb comes last: …, obwohl sie ihn schon gesehen hat. …, obwohl sie früh aufstehen muss. If the obwohl clause comes first, the main clause begins with the verb: Obwohl es regnet, gehen wir ins Kino.',
          'obwohl (хотя) соединяет два высказывания, которые как будто не сочетаются: что-то говорит против, но это всё равно происходит. obwohl вводит придаточное предложение, глагол стоит в конце: Lea schaut den Film, obwohl sie das Ende schon kennt. (Lea смотрит фильм, хотя уже знает конец.) В Perfekt и с модальным глаголом спрягаемый глагол стоит в самом конце: …, obwohl sie ihn schon gesehen hat. …, obwohl sie früh aufstehen muss. Если придаточное с obwohl стоит в начале, главное предложение начинается с глагола: Obwohl es regnet, gehen wir ins Kino.',
          'obwohl (хоча) поєднує два висловлювання, які ніби не пасують одне до одного: щось говорить проти, але це все одно відбувається. obwohl вводить підрядне речення, дієслово стоїть у кінці: Lea schaut den Film, obwohl sie das Ende schon kennt. (Lea дивиться фільм, хоча вже знає кінець.) У Perfekt і з модальним дієсловом відмінюване дієслово стоїть у самому кінці: …, obwohl sie ihn schon gesehen hat. …, obwohl sie früh aufstehen muss. Якщо підрядне з obwohl стоїть на початку, головне речення починається з дієслова: Obwohl es regnet, gehen wir ins Kino.',
          'obwohl (-diği halde, -mesine rağmen) aslında birbirine uymayan iki ifadeyi bağlar: Bir şey buna engeldir ama yine de olur. obwohl bir yan cümle başlatır, fiil sonda durur: Lea schaut den Film, obwohl sie das Ende schon kennt. (Lea sonunu bildiği halde filmi izliyor.) Perfekt’te ve kip fiilleriyle çekimli fiil en sonda durur: …, obwohl sie ihn schon gesehen hat. …, obwohl sie früh aufstehen muss. obwohl cümlesi başta ise ana cümle fiille başlar: Obwohl es regnet, gehen wir ins Kino.',
        ],
        hint: ['obwohl = Gegensatz. Verb am Ende: …, obwohl ich müde bin. Am Anfang: Obwohl …, + Verb + Subjekt.', 'obwohl = contrast. Verb at the end: …, obwohl ich müde bin. At the start: Obwohl …, + verb + subject.', 'obwohl = противопоставление. Глагол в конце: …, obwohl ich müde bin. В начале: Obwohl …, + глагол + подлежащее.', 'obwohl = протиставлення. Дієслово в кінці: …, obwohl ich müde bin. На початку: Obwohl …, + дієслово + підмет.', 'obwohl = karşıtlık. Fiil sonda: …, obwohl ich müde bin. Başta: Obwohl …, + fiil + özne.'],
      },
      ex: [
        mc('G1', 'obwohl', I.choose, 'Ich sehe mir die Serie an, … ich heute eigentlich überhaupt keine Zeit habe.', ['obwohl', 'weil', 'dass'],
          ['I am watching the series although I really have no time at all today.', 'Я смотрю сериал, хотя сегодня у меня вообще нет времени.', 'Я дивлюся серіал, хоча сьогодні в мене взагалі немає часу.', 'Bugün aslında hiç vaktim olmadığı halde diziyi izliyorum.']),
        mc('G1', 'Verb am Ende', I.sentence, 'Tim ist sehr müde. Er schaut aber noch einen Film.', ['Tim schaut noch einen Film, obwohl er sehr müde ist.', 'Tim schaut noch einen Film, obwohl er ist sehr müde.', 'Tim schaut noch einen Film, obwohl ist er sehr müde.'],
          ['Tim is very tired. But he watches another film.', 'Tim очень устал. Но он смотрит ещё один фильм.', 'Tim дуже втомився. Але він дивиться ще один фільм.', 'Tim çok yorgun. Ama bir film daha izliyor.']),
        mc('G1', 'obwohl am Satzanfang', I.sentence, 'Der Film hat schlechte Kritiken bekommen. Das Kino ist voll.', ['Obwohl der Film schlechte Kritiken bekommen hat, ist das Kino voll.', 'Obwohl der Film schlechte Kritiken bekommen hat, das Kino ist voll.', 'Obwohl hat der Film schlechte Kritiken bekommen, ist das Kino voll.'],
          ['The film got bad reviews. The cinema is full.', 'Фильм получил плохие отзывы. Кинотеатр полон.', 'Фільм отримав погані відгуки. Кінотеатр повний.', 'Film kötü eleştiriler aldı. Sinema dolu.']),
        mc('G1', 'Gegensatz erkennen', I.choose, 'Was passt? „Wir sind zu Fuß zum Kino gegangen, obwohl …“', ['es stark geregnet hat.', 'die Sonne geschienen hat.', 'das Kino ganz in der Nähe ist.'],
          ['What fits? “We walked to the cinema although …”', 'Что подходит? «Мы пошли в кино пешком, хотя …»', 'Що підходить? «Ми пішли в кіно пішки, хоча …»', 'Hangisi uygun? “Sinemaya yürüyerek gittik, … halde.”']),
        mc('G1', 'mag', I.choose, 'Obwohl Mira den Hauptdarsteller überhaupt nicht …, hat ihr der Film gut gefallen.', ['mag', 'mögen', 'gemocht'],
          ['Although Mira does not like the leading actor at all, she enjoyed the film.', 'Хотя Mira совсем не любит исполнителя главной роли, фильм ей понравился.', 'Хоча Mira зовсім не любить виконавця головної ролі, фільм їй сподобався.', 'Mira başrol oyuncusunu hiç sevmediği halde filmi beğendi.']),
        gap('G1', 'obwohl', I.conjunction, 'Ich habe das Buch bis zum Ende gelesen, ', ' es ziemlich langweilig war.', 'obwohl', ['weil', 'wenn'],
          ['I read the book to the end although it was rather boring.', 'Я дочитал книгу до конца, хотя она была довольно скучной.', 'Я дочитав книжку до кінця, хоча вона була досить нудна.', 'Kitap oldukça sıkıcı olduğu halde sonuna kadar okudum.'], 'obwohl / weil / wenn'),
        gap('G1', 'bestellt hatten', I.auxiliary, 'Obwohl wir die Karten schon vor Wochen bestellt ', ', bekamen wir schlechte Plätze.', 'hatten', ['hatte', 'waren'],
          ['Although we had ordered the tickets weeks earlier, we got bad seats.', 'Хотя мы заказали билеты ещё несколько недель назад, нам достались плохие места.', 'Хоча ми замовили квитки ще кілька тижнів тому, нам дісталися погані місця.', 'Biletleri haftalar önce sipariş ettiğimiz halde kötü yerler aldık.'], 'haben / sein (Präteritum)'),
        gap('G1', 'Verb am Ende', I.verb, 'Paul geht heute Abend ins Kino, obwohl er morgen früh eine wichtige Prüfung ', '.', 'hat', ['haben', 'hatte'],
          ['Paul is going to the cinema tonight although he has an important exam tomorrow morning.', 'Paul идёт сегодня вечером в кино, хотя завтра утром у него важный экзамен.', 'Paul іде сьогодні ввечері в кіно, хоча завтра вранці в нього важливий іспит.', 'Paul yarın sabah önemli bir sınavı olduğu halde bu akşam sinemaya gidiyor.'], 'haben'),
        gap('G1', 'aufstehen muss', I.modal, 'Obwohl sie jeden Tag um fünf Uhr aufstehen ', ', schaut Jana abends immer drei Folgen.', 'muss', ['müssen', 'musst'],
          ['Although she has to get up at five every day, Jana always watches three episodes in the evening.', 'Хотя Jana каждый день приходится вставать в пять часов, вечером она всегда смотрит три серии.', 'Хоча Jana щодня доводиться вставати о п’ятій, увечері вона завжди дивиться три серії.', 'Jana her gün saat beşte kalkmak zorunda olduğu halde akşamları hep üç bölüm izliyor.'], 'müssen'),
        sb('G1', 'Obwohl …, + Verb', I.order, 'Obwohl es spät war, / schauten / wir / noch eine Folge.',
          ['Although it was late, we watched another episode.', 'Хотя было поздно, мы посмотрели ещё одну серию.', 'Хоча було пізно, ми подивилися ще одну серію.', 'Geç olduğu halde bir bölüm daha izledik.']),
      ],
    },
    {
      title: 'obwohl, weil oder trotzdem?',
      t: ['obwohl, weil or trotzdem?', 'obwohl, weil или trotzdem?', 'obwohl, weil чи trotzdem?', 'obwohl, weil ya da trotzdem?'],
      card: {
        id: 'p2_obwohl_weil',
        rule: 'obwohl, weil oder trotzdem? weil nennt den Grund: Ich bleibe zu Hause, weil ich krank bin. obwohl nennt etwas, was dagegen spricht: Ich gehe arbeiten, obwohl ich krank bin. trotzdem bedeutet das Gleiche wie obwohl, steht aber im anderen Satz, einem Hauptsatz: Ich bin krank. Trotzdem gehe ich arbeiten. Nach trotzdem kommt sofort das Verb. Nach obwohl und weil steht das Verb am Ende.',
        examples: ['Ich mag den Film, weil die Musik so schön ist.', 'Ich mag den Film, obwohl er sehr lang ist.', 'Der Film ist sehr lang. Trotzdem mag ich ihn.'],
        highlight: null,
        t: [
          'obwohl, weil or trotzdem? weil (because) gives the reason: Ich bleibe zu Hause, weil ich krank bin. obwohl (although) names something that speaks against it: Ich gehe arbeiten, obwohl ich krank bin. trotzdem (nevertheless) means the same as obwohl, but it stands in the other sentence, a main clause: Ich bin krank. Trotzdem gehe ich arbeiten. The verb comes straight after trotzdem. After obwohl and weil the verb goes at the end.',
          'obwohl, weil или trotzdem? weil (потому что) называет причину: Ich bleibe zu Hause, weil ich krank bin. obwohl (хотя) называет то, что этому противоречит: Ich gehe arbeiten, obwohl ich krank bin. trotzdem (несмотря на это, всё равно) значит то же, что obwohl, но стоит в другом, главном предложении: Ich bin krank. Trotzdem gehe ich arbeiten. После trotzdem сразу идёт глагол. После obwohl и weil глагол стоит в конце.',
          'obwohl, weil чи trotzdem? weil (тому що) називає причину: Ich bleibe zu Hause, weil ich krank bin. obwohl (хоча) називає те, що цьому суперечить: Ich gehe arbeiten, obwohl ich krank bin. trotzdem (попри це, все одно) означає те саме, що obwohl, але стоїть в іншому, головному реченні: Ich bin krank. Trotzdem gehe ich arbeiten. Після trotzdem одразу йде дієслово. Після obwohl і weil дієслово стоїть у кінці.',
          'obwohl, weil ya da trotzdem? weil (çünkü) nedeni bildirir: Ich bleibe zu Hause, weil ich krank bin. obwohl (-diği halde) buna engel olan şeyi bildirir: Ich gehe arbeiten, obwohl ich krank bin. trotzdem (buna rağmen) obwohl ile aynı anlama gelir ama öteki cümlede, bir ana cümlede durur: Ich bin krank. Trotzdem gehe ich arbeiten. trotzdem’den hemen sonra fiil gelir. obwohl ve weil’den sonra fiil sonda durur.',
        ],
        hint: ['weil = Grund. obwohl = Gegensatz, Verb am Ende. Trotzdem = Gegensatz im Hauptsatz: Trotzdem + Verb.', 'weil = reason. obwohl = contrast, verb at the end. Trotzdem = contrast in a main clause: Trotzdem + verb.', 'weil = причина. obwohl = противопоставление, глагол в конце. Trotzdem = противопоставление в главном предложении: Trotzdem + глагол.', 'weil = причина. obwohl = протиставлення, дієслово в кінці. Trotzdem = протиставлення в головному реченні: Trotzdem + дієслово.', 'weil = neden. obwohl = karşıtlık, fiil sonda. Trotzdem = ana cümlede karşıtlık: Trotzdem + fiil.'],
      },
      ex: [
        mc('G1', 'weil', I.choose, 'Ich mag diesen Film sehr, … die Musik so schön ist.', ['weil', 'obwohl', 'trotzdem'],
          ['I like this film very much because the music is so beautiful.', 'Мне очень нравится этот фильм, потому что музыка такая красивая.', 'Мені дуже подобається цей фільм, бо музика така гарна.', 'Bu filmi çok seviyorum çünkü müziği çok güzel.']),
        mc('G1', 'Trotzdem', I.choose, 'Der Film dauert über drei Stunden. … war mir keine Minute langweilig.', ['Trotzdem', 'Obwohl', 'Weil'],
          ['The film lasts over three hours. Nevertheless I was not bored for a single minute.', 'Фильм идёт больше трёх часов. Тем не менее мне не было скучно ни минуты.', 'Фільм триває понад три години. Попри це мені не було нудно жодної хвилини.', 'Film üç saatten uzun sürüyor. Buna rağmen bir dakika bile sıkılmadım.']),
        mc('G1', 'weil', I.choose, 'Meine Schwester schaut abends keine Krimis, … sie danach schlecht schläft.', ['weil', 'obwohl', 'trotzdem'],
          ['My sister does not watch crime series in the evening because she sleeps badly afterwards.', 'Моя сестра не смотрит по вечерам детективы, потому что потом плохо спит.', 'Моя сестра не дивиться вечорами детективи, бо потім погано спить.', 'Kız kardeşim akşamları polisiye izlemiyor çünkü sonrasında kötü uyuyor.']),
        mc('G1', 'trotzdem = obwohl', I.choose, 'Welcher Satz bedeutet das Gleiche? „Es ist schon Mitternacht. Trotzdem schaue ich weiter.“', ['Ich schaue weiter, obwohl es schon Mitternacht ist.', 'Ich schaue weiter, weil es schon Mitternacht ist.', 'Ich schaue weiter, wenn es schon Mitternacht ist.'],
          ['Which sentence means the same? “It is already midnight. Nevertheless I keep watching.”', 'Какое предложение значит то же самое? «Уже полночь. Тем не менее я продолжаю смотреть.»', 'Яке речення означає те саме? «Уже північ. Попри це я дивлюся далі.»', 'Hangi cümle aynı anlama gelir? “Saat gece yarısı oldu. Buna rağmen izlemeye devam ediyorum.”']),
        mc('G1', 'Trotzdem + Verb', I.sentence, 'Die Karten sind teuer. Das Konzert ist ausverkauft.', ['Die Karten sind teuer. Trotzdem ist das Konzert ausverkauft.', 'Die Karten sind teuer. Trotzdem das Konzert ist ausverkauft.', 'Die Karten sind teuer. Trotzdem ausverkauft ist das Konzert.'],
          ['The tickets are expensive. The concert is sold out.', 'Билеты дорогие. Все билеты на концерт проданы.', 'Квитки дорогі. Усі квитки на концерт продано.', 'Biletler pahalı. Konserin biletleri tükendi.']),
        gap('G1', 'obwohl', I.conjunction, 'Er hat die Hauptrolle bekommen, ', ' er noch nie in einem Film mitgespielt hat.', 'obwohl', ['weil', 'trotzdem'],
          ['He got the leading role although he has never acted in a film before.', 'Он получил главную роль, хотя ещё никогда не снимался в кино.', 'Він отримав головну роль, хоча ще ніколи не знімався в кіно.', 'Daha önce hiçbir filmde oynamadığı halde başrolü aldı.'], OWT),
        gap('G1', 'weil', I.conjunction, 'Wir gehen heute doch nicht ins Kino, ', ' unser Sohn plötzlich krank geworden ist.', 'weil', ['obwohl', 'trotzdem'],
          ['We are not going to the cinema today after all because our son has suddenly fallen ill.', 'Сегодня мы всё-таки не идём в кино, потому что наш сын внезапно заболел.', 'Сьогодні ми все-таки не йдемо в кіно, бо наш син раптом захворів.', 'Oğlumuz birden hastalandığı için bugün sinemaya gitmiyoruz.'], OWT),
        gap('G1', 'Trotzdem', I.conjunction, 'Die Schauspielerin war stark erkältet. ', ' stand sie am Abend auf der Bühne.', 'Trotzdem', ['Obwohl', 'Weil'],
          ['The actress had a bad cold. Nevertheless she was on stage in the evening.', 'Актриса была сильно простужена. Тем не менее вечером она стояла на сцене.', 'Акторка була сильно застуджена. Попри це ввечері вона стояла на сцені.', 'Oyuncu fena halde üşütmüştü. Buna rağmen akşam sahnedeydi.'], OWT),
        gap('G1', 'obwohl', I.conjunction, 'Ich verstehe fast alles, ', ' die Schauspieler in dieser Serie sehr schnell sprechen.', 'obwohl', ['weil', 'trotzdem'],
          ['I understand almost everything although the actors in this series speak very fast.', 'Я понимаю почти всё, хотя актёры в этом сериале говорят очень быстро.', 'Я розумію майже все, хоча актори в цьому серіалі говорять дуже швидко.', 'Bu dizideki oyuncular çok hızlı konuştuğu halde neredeyse her şeyi anlıyorum.'], OWT),
        sb('G1', 'Trotzdem + Verb', I.order, 'Trotzdem / hat / mir / der Film / gut gefallen.',
          ['Nevertheless I enjoyed the film.', 'Тем не менее фильм мне понравился.', 'Попри це фільм мені сподобався.', 'Buna rağmen filmi beğendim.'],
          { alt: ['Der Film hat mir trotzdem gut gefallen.', 'Mir hat der Film trotzdem gut gefallen.', 'Trotzdem hat der Film mir gut gefallen.'] }),
      ],
    },
    {
      title: 'echt gut, gar nicht gut',
      t: ['echt gut, gar nicht gut (really good, not good at all)', 'echt gut, gar nicht gut (очень хорошо, совсем не хорошо)', 'echt gut, gar nicht gut (дуже добре, зовсім не добре)', 'echt gut, gar nicht gut (gerçekten iyi, hiç iyi değil)'],
      card: {
        id: 'p2_gradpartikeln',
        rule: 'Gradpartikeln machen ein Adjektiv stärker oder schwächer. Sehr stark (++): echt, total, besonders – Der Film ist echt spannend. Stark (+): ziemlich, wirklich – Die Serie ist ziemlich lustig. Schwach (–): nicht so, nicht besonders – Das Ende war nicht besonders gut. Negativ (– –): gar nicht, überhaupt nicht – Der Krimi war überhaupt nicht spannend. Die Gradpartikel steht direkt vor dem Adjektiv. echt und total hört man vor allem im Gespräch.',
        examples: ['Die neue Staffel ist total spannend.', 'Der Film war ziemlich lang.', 'Das Ende hat mir gar nicht gefallen.'],
        highlight: null,
        t: [
          'Gradpartikeln (intensifiers) make an adjective stronger or weaker. Very strong (++): echt, total, besonders (really, totally, especially) – Der Film ist echt spannend. Strong (+): ziemlich, wirklich (quite, really) – Die Serie ist ziemlich lustig. Weak (–): nicht so, nicht besonders (not so, not particularly) – Das Ende war nicht besonders gut. Negative (– –): gar nicht, überhaupt nicht (not at all) – Der Krimi war überhaupt nicht spannend. The intensifier comes directly before the adjective. echt and total are mainly heard in conversation.',
          'Gradpartikeln (усилительные частицы) делают прилагательное сильнее или слабее. Очень сильно (++): echt, total, besonders (реально, совершенно, особенно) – Der Film ist echt spannend. Сильно (+): ziemlich, wirklich (довольно, действительно) – Die Serie ist ziemlich lustig. Слабо (–): nicht so, nicht besonders (не так, не особенно) – Das Ende war nicht besonders gut. Отрицательно (– –): gar nicht, überhaupt nicht (совсем не, вообще не) – Der Krimi war überhaupt nicht spannend. Частица стоит прямо перед прилагательным. echt и total звучат прежде всего в разговоре.',
          'Gradpartikeln (підсилювальні частки) роблять прикметник сильнішим або слабшим. Дуже сильно (++): echt, total, besonders (реально, цілком, особливо) – Der Film ist echt spannend. Сильно (+): ziemlich, wirklich (досить, справді) – Die Serie ist ziemlich lustig. Слабко (–): nicht so, nicht besonders (не так, не особливо) – Das Ende war nicht besonders gut. Заперечно (– –): gar nicht, überhaupt nicht (зовсім не, взагалі не) – Der Krimi war überhaupt nicht spannend. Частка стоїть безпосередньо перед прикметником. echt і total звучать передусім у розмові.',
          'Gradpartikeln (derece bildiren sözcükler) bir sıfatı güçlendirir ya da zayıflatır. Çok güçlü (++): echt, total, besonders (gerçekten, tamamen, özellikle) – Der Film ist echt spannend. Güçlü (+): ziemlich, wirklich (oldukça, gerçekten) – Die Serie ist ziemlich lustig. Zayıf (–): nicht so, nicht besonders (o kadar değil, pek değil) – Das Ende war nicht besonders gut. Olumsuz (– –): gar nicht, überhaupt nicht (hiç değil) – Der Krimi war überhaupt nicht spannend. Bu sözcük sıfatın hemen önünde durur. echt ve total daha çok konuşmada duyulur.',
        ],
        hint: ['++ echt, total, besonders / + ziemlich, wirklich / – nicht so, nicht besonders / – – gar nicht, überhaupt nicht.', '++ echt, total, besonders / + ziemlich, wirklich / – nicht so, nicht besonders / – – gar nicht, überhaupt nicht (not at all).', '++ echt, total, besonders / + ziemlich, wirklich / – nicht so, nicht besonders / – – gar nicht, überhaupt nicht (совсем не).', '++ echt, total, besonders / + ziemlich, wirklich / – nicht so, nicht besonders / – – gar nicht, überhaupt nicht (зовсім не).', '++ echt, total, besonders / + ziemlich, wirklich / – nicht so, nicht besonders / – – gar nicht, überhaupt nicht (hiç değil).'],
      },
      ex: [
        mc('G2', 'total', I.choose, 'Welcher Satz ist am positivsten?', ['Die Serie ist total spannend.', 'Die Serie ist ziemlich spannend.', 'Die Serie ist nicht besonders spannend.'],
          ['Which sentence is the most positive?', 'Какое предложение самое положительное?', 'Яке речення найпозитивніше?', 'Hangi cümle en olumlu?']),
        mc('G2', 'überhaupt nicht', I.choose, 'Welcher Satz ist am negativsten?', ['Der Film war überhaupt nicht lustig.', 'Der Film war nicht so lustig.', 'Der Film war ziemlich lustig.'],
          ['Which sentence is the most negative?', 'Какое предложение самое отрицательное?', 'Яке речення найнегативніше?', 'Hangi cümle en olumsuz?']),
        mc("G2", "echt", I.choose, "Leon ist begeistert: „Der Schauspieler ist ___ gut! So etwas habe ich noch nie gesehen.“", ["echt","gar nicht","nicht so"], ["Leon is thrilled: “The actor is … good! I have never seen anything like it.”","Leon в восторге: «Актёр … хорош! Я такого ещё никогда не видел.»","Leon в захваті: «Актор … гарний! Я такого ще ніколи не бачив.»","Leon hayran kalmış: “Oyuncu … iyi! Böyle bir şeyi hiç görmemiştim.”"], {"c":"p2_gradpartikeln","sitovOptionOrder":["echt","gar nicht","nicht so"]}),
        mc('G2', 'überhaupt nicht', I.choose, 'Jan ist enttäuscht: „Das Ende war … nicht logisch. Ich habe nichts verstanden.“', ['überhaupt', 'ziemlich', 'besonders'],
          ['Jan is disappointed: “The ending was not logical … I did not understand anything.”', 'Jan разочарован: «Конец был … не логичным. Я ничего не понял.»', 'Jan розчарований: «Кінець був … не логічний. Я нічого не зрозумів.»', 'Jan hayal kırıklığına uğramış: “Son … mantıklı değildi. Hiçbir şey anlamadım.”']),
        mc('G2', 'nicht besonders', I.choose, 'Was bedeutet „Der Film war nicht besonders gut.“?', ['Der Film war eher schwach.', 'Der Film war ausgezeichnet.', 'Der Film war der beste im ganzen Jahr.'],
          ['What does “Der Film war nicht besonders gut.” mean?', 'Что означает «Der Film war nicht besonders gut.»?', 'Що означає «Der Film war nicht besonders gut.»?', '“Der Film war nicht besonders gut.” ne demek?']),
        mc('G2', 'Stellung vor dem Adjektiv', I.sentence, 'Mia findet die Filmmusik sehr schön.', ['Die Musik ist wirklich schön.', 'Die Musik wirklich ist schön.', 'Die Musik ist schön wirklich.'],
          ['Mia thinks the film music is very beautiful.', 'Mia считает музыку к фильму очень красивой.', 'Mia вважає музику до фільму дуже гарною.', 'Mia film müziğini çok güzel buluyor.']),
        gap('G2', 'nicht besonders', I.word, 'Der Dokumentarfilm war nicht ', ' interessant. Ich bin fast eingeschlafen.', 'besonders', ['total', 'echt'],
          ['The documentary was not particularly interesting. I almost fell asleep.', 'Документальный фильм был не особенно интересным. Я чуть не заснул.', 'Документальний фільм був не особливо цікавий. Я мало не заснув.', 'Belgesel pek ilginç değildi. Neredeyse uyuyakalacaktım.'], 'besonders / total / echt'),
        gap('G2', 'total', I.word, 'Ich habe den Film schon fünfmal gesehen. Er gefällt mir ', ' gut!', 'total', ['gar nicht', 'nicht so'],
          ['I have already seen the film five times. I like it a lot!', 'Я смотрел этот фильм уже пять раз. Он мне ужасно нравится!', 'Я дивився цей фільм уже п’ять разів. Він мені страшенно подобається!', 'Filmi şimdiden beş kez izledim. Onu çok beğeniyorum!'], 'total / gar nicht / nicht so'),
        gap('G2', 'gar nicht', I.word, 'Die Komödie war gar ', ' lustig. Niemand im Kino hat gelacht.', 'nicht', ['sehr', 'ziemlich'],
          ['The comedy was not funny at all. Nobody in the cinema laughed.', 'Комедия была совсем не смешной. Никто в зале не смеялся.', 'Комедія була зовсім не смішна. Ніхто в залі не сміявся.', 'Komedi hiç komik değildi. Sinemada kimse gülmedi.'], 'nicht / sehr / ziemlich'),
        sb('G2', 'ziemlich', I.order, 'Die neue Staffel / ist / ziemlich / spannend.',
          ['The new season is quite exciting.', 'Новый сезон довольно увлекательный.', 'Новий сезон досить захопливий.', 'Yeni sezon oldukça sürükleyici.']),
      ],
    },
    {
      title: 'der Schauspieler, der …',
      t: ['der Schauspieler, der … (relative clauses: nominative)', 'der Schauspieler, der … (придаточные определительные: Nominativ)', 'der Schauspieler, der … (підрядні означальні: Nominativ)', 'der Schauspieler, der … (ilgi cümlesi: Nominativ)'],
      card: {
        id: 'p2_relativ_nom',
        rule: 'Der Relativsatz beschreibt ein Nomen genauer. Er steht direkt hinter dem Nomen, zwischen Kommas, und das Verb steht am Ende. Das Relativpronomen im Nominativ sieht aus wie der bestimmte Artikel: der Mann, der gut kochen kann – das Kind, das dort spielt – die Frau, die nebenan wohnt – die Leute, die hier arbeiten. Genus und Zahl kommen vom Nomen davor. Nominativ steht, wenn das Relativpronomen das Subjekt im Relativsatz ist.',
        examples: ['Das ist der Schauspieler, der den Kommissar spielt.', 'Ich suche ein Kino, das Filme mit Untertiteln zeigt.', 'Die Leute, die neben uns saßen, haben laut gelacht.'],
        highlight: 'article',
        t: [
          'A relative clause describes a noun more precisely. It comes directly after the noun, between commas, and the verb goes at the end. The relative pronoun in the nominative looks like the definite article: der Mann, der gut kochen kann (the man who can cook well) – das Kind, das dort spielt – die Frau, die nebenan wohnt – die Leute, die hier arbeiten. Gender and number come from the noun before it. The nominative is used when the relative pronoun is the subject of the relative clause.',
          'Придаточное определительное (Relativsatz) точнее описывает существительное. Оно стоит сразу после существительного, между запятыми, а глагол стоит в конце. Относительное местоимение в Nominativ выглядит как определённый артикль: der Mann, der gut kochen kann (мужчина, который хорошо готовит) – das Kind, das dort spielt – die Frau, die nebenan wohnt – die Leute, die hier arbeiten. Род и число берутся от существительного перед ним. Nominativ стоит, когда относительное местоимение – подлежащее в придаточном.',
          'Підрядне означальне речення (Relativsatz) точніше описує іменник. Воно стоїть одразу після іменника, між комами, а дієслово стоїть у кінці. Відносний займенник у Nominativ має вигляд означеного артикля: der Mann, der gut kochen kann (чоловік, який добре готує) – das Kind, das dort spielt – die Frau, die nebenan wohnt – die Leute, die hier arbeiten. Рід і число беруться від іменника перед ним. Nominativ стоїть, коли відносний займенник – підмет у підрядному реченні.',
          'İlgi cümlesi (Relativsatz) bir ismi daha ayrıntılı anlatır. İsmin hemen arkasında, virgüller arasında durur ve fiil sonda bulunur. Nominativ’deki ilgi zamiri belirli artikel gibi görünür: der Mann, der gut kochen kann (iyi yemek yapabilen adam) – das Kind, das dort spielt – die Frau, die nebenan wohnt – die Leute, die hier arbeiten. Cinsiyet ve sayı, önündeki isimden gelir. İlgi zamiri ilgi cümlesinin öznesiyse Nominativ kullanılır.',
        ],
        hint: ['Nominativ: der → der, das → das, die → die, Plural → die. Verb am Ende, Komma vor dem Relativpronomen.', 'Nominative: der → der, das → das, die → die, plural → die. Verb at the end, comma before the relative pronoun.', 'Nominativ: der → der, das → das, die → die, множественное число → die. Глагол в конце, перед местоимением запятая.', 'Nominativ: der → der, das → das, die → die, множина → die. Дієслово в кінці, перед займенником кома.', 'Nominativ: der → der, das → das, die → die, çoğul → die. Fiil sonda, ilgi zamirinden önce virgül.'],
      },
      ex: [
        mc('G3', 'der', I.choose, 'Das ist der Schauspieler, … in der neuen Serie den Arzt spielt.', ['der', 'den', 'dem'],
          ['That is the actor who plays the doctor in the new series.', 'Это актёр, который играет врача в новом сериале.', 'Це актор, який грає лікаря в новому серіалі.', 'Bu, yeni dizide doktoru oynayan oyuncu.']),
        mc('G3', 'die', I.choose, 'Kennst du die Frau, … dort an der Kinokasse steht?', ['die', 'der', 'das'],
          ['Do you know the woman who is standing at the box office over there?', 'Ты знаешь женщину, которая стоит там у кассы кинотеатра?', 'Ти знаєш жінку, яка стоїть там біля каси кінотеатру?', 'Orada sinema gişesinde duran kadını tanıyor musun?']),
        mc('G3', 'das', I.choose, 'Ich suche ein Kino, … auch Filme in Originalsprache zeigt.', ['das', 'der', 'die'],
          ['I am looking for a cinema that also shows films in the original language.', 'Я ищу кинотеатр, который показывает фильмы и на языке оригинала.', 'Я шукаю кінотеатр, який показує фільми й мовою оригіналу.', 'Filmleri orijinal dilinde de gösteren bir sinema arıyorum.']),
        mc('G3', 'die (Plural)', I.choose, 'Die Zuschauer, … zu spät kamen, durften nicht mehr in den Saal.', ['die', 'der', 'denen'],
          ['The viewers who arrived late were no longer allowed into the auditorium.', 'Зрителей, которые опоздали, уже не пустили в зал.', 'Глядачів, які запізнилися, уже не пустили до зали.', 'Geç gelen izleyicilerin artık salona girmesine izin verilmedi.']),
        mc('G3', 'Relativsatz bilden', I.sentence, 'Der Film läuft heute Abend. Er hat drei Preise gewonnen.', ['Der Film, der drei Preise gewonnen hat, läuft heute Abend.', 'Der Film, der hat drei Preise gewonnen, läuft heute Abend.', 'Der Film läuft heute Abend, das drei Preise gewonnen hat.'],
          ['The film is on tonight. It has won three awards.', 'Фильм идёт сегодня вечером. Он получил три премии.', 'Фільм іде сьогодні ввечері. Він отримав три премії.', 'Film bu akşam gösteriliyor. Üç ödül kazandı.']),
        gap('G3', 'der', I.pronoun, 'Mein Bruder ist ein Mensch, ', ' über jeden Witz lachen kann.', 'der', ['den', 'das'],
          ['My brother is a person who can laugh at any joke.', 'Мой брат – человек, который может смеяться над любой шуткой.', 'Мій брат – людина, яка може сміятися з будь-якого жарту.', 'Kardeşim her şakaya gülebilen bir insandır.'], 'der / den / das'),
        gap('G3', 'das', I.pronoun, 'Wie heißt das Lied, ', ' am Ende vom Film gespielt wird?', 'das', ['der', 'die'],
          ['What is the name of the song that is played at the end of the film?', 'Как называется песня, которая звучит в конце фильма?', 'Як називається пісня, яка звучить наприкінці фільму?', 'Filmin sonunda çalan şarkının adı ne?'], 'der / das / die'),
        gap('G3', 'die', I.pronoun, 'Die Regisseurin, ', ' diesen Film gemacht hat, kommt aus Wien.', 'die', ['der', 'das'],
          ['The director who made this film comes from Vienna.', 'Режиссёр, которая сняла этот фильм, родом из Вены.', 'Режисерка, яка зняла цей фільм, родом із Відня.', 'Bu filmi çeken kadın yönetmen Viyanalı.'], 'der / das / die'),
        gap('G3', 'die (Plural)', I.pronoun, 'Ich mag vor allem Serien, ', ' in der heutigen Zeit spielen.', 'die', ['der', 'das'],
          ['Above all I like series that are set in the present day.', 'Мне нравятся прежде всего сериалы, действие которых происходит в наше время.', 'Мені подобаються передусім серіали, дія яких відбувається в наш час.', 'Özellikle günümüzde geçen dizileri seviyorum.'], 'der / das / die'),
        sb('G3', 'die … spielt', I.order, 'Das ist / die Schauspielerin, / die / die Hauptrolle / spielt.',
          ['That is the actress who plays the leading role.', 'Это актриса, которая играет главную роль.', 'Це акторка, яка грає головну роль.', 'Bu, başrolü oynayan kadın oyuncu.']),
      ],
    },
    {
      title: 'der Film, den …',
      t: ['der Film, den … (relative clauses: accusative)', 'der Film, den … (придаточные определительные: Akkusativ)', 'der Film, den … (підрядні означальні: Akkusativ)', 'der Film, den … (ilgi cümlesi: Akkusativ)'],
      card: {
        id: 'p2_relativ_akk',
        rule: 'Relativpronomen im Akkusativ: Nur maskulin ändert sich. der Film, den ich gestern gesehen habe – das Buch, das ich lese – die Serie, die ich mag – die Filme, die wir kennen. Akkusativ steht, wenn das Relativpronomen im Relativsatz das Objekt ist; das Subjekt ist dann ein anderes Wort (ich, wir, mein Bruder …). Vergleiche: der Mann, der mich kennt (er kennt mich) – der Mann, den ich kenne (ich kenne ihn).',
        examples: ['Das ist der Film, den ich dir empfohlen habe.', 'Das Buch, das ich gerade lese, ist echt spannend.', 'Die Serie, die wir schauen, hat fünf Staffeln.'],
        highlight: 'article',
        t: [
          'Relative pronouns in the accusative: only the masculine changes. der Film, den ich gestern gesehen habe (the film that I saw yesterday) – das Buch, das ich lese – die Serie, die ich mag – die Filme, die wir kennen. The accusative is used when the relative pronoun is the object in the relative clause; the subject is then another word (ich, wir, mein Bruder …). Compare: der Mann, der mich kennt (he knows me) – der Mann, den ich kenne (I know him).',
          'Относительные местоимения в Akkusativ: меняется только мужской род. der Film, den ich gestern gesehen habe (фильм, который я вчера посмотрел) – das Buch, das ich lese – die Serie, die ich mag – die Filme, die wir kennen. Akkusativ стоит, когда относительное местоимение – дополнение в придаточном; подлежащим тогда является другое слово (ich, wir, mein Bruder …). Сравните: der Mann, der mich kennt (он знает меня) – der Mann, den ich kenne (я знаю его).',
          'Відносні займенники в Akkusativ: змінюється тільки чоловічий рід. der Film, den ich gestern gesehen habe (фільм, який я вчора подивився) – das Buch, das ich lese – die Serie, die ich mag – die Filme, die wir kennen. Akkusativ стоїть, коли відносний займенник – додаток у підрядному реченні; підметом тоді є інше слово (ich, wir, mein Bruder …). Порівняйте: der Mann, der mich kennt (він знає мене) – der Mann, den ich kenne (я знаю його).',
          'Akkusativ’de ilgi zamirleri: Yalnızca eril değişir. der Film, den ich gestern gesehen habe (dün izlediğim film) – das Buch, das ich lese – die Serie, die ich mag – die Filme, die wir kennen. İlgi zamiri ilgi cümlesinde nesne ise Akkusativ kullanılır; özne o zaman başka bir kelimedir (ich, wir, mein Bruder …). Karşılaştırın: der Mann, der mich kennt (o beni tanıyor) – der Mann, den ich kenne (ben onu tanıyorum).',
        ],
        hint: ['Akkusativ: der → den, das → das, die → die, Plural → die. Im Relativsatz gibt es schon ein Subjekt (ich, du, wir …).', 'Accusative: der → den, das → das, die → die, plural → die. The relative clause already has a subject (ich, du, wir …).', 'Akkusativ: der → den, das → das, die → die, множественное число → die. В придаточном уже есть подлежащее (ich, du, wir …).', 'Akkusativ: der → den, das → das, die → die, множина → die. У підрядному реченні вже є підмет (ich, du, wir …).', 'Akkusativ: der → den, das → das, die → die, çoğul → die. İlgi cümlesinde zaten bir özne vardır (ich, du, wir …).'],
      },
      ex: [
        mc('G4', 'den', I.choose, 'Wie heißt der Film, … du mir letzte Woche empfohlen hast?', ['den', 'der', 'dem'],
          ['What is the name of the film that you recommended to me last week?', 'Как называется фильм, который ты посоветовал мне на прошлой неделе?', 'Як називається фільм, який ти порадив мені минулого тижня?', 'Geçen hafta bana önerdiğin filmin adı ne?']),
        mc('G4', 'den', I.choose, 'Das ist ein Schauspieler, … man vor allem aus der Werbung kennt.', ['den', 'der', 'das'],
          ['That is an actor whom people know mainly from advertising.', 'Это актёр, которого знают прежде всего по рекламе.', 'Це актор, якого знають передусім із реклами.', 'Bu, daha çok reklamlardan tanınan bir oyuncu.']),
        mc('G4', 'der oder den?', I.choose, 'Das ist der Nachbar, … mich jeden Morgen so freundlich grüßt.', ['der', 'den', 'dem'],
          ['That is the neighbour who greets me in such a friendly way every morning.', 'Это сосед, который каждое утро так приветливо со мной здоровается.', 'Це сусід, який щоранку так привітно зі мною вітається.', 'Bu, her sabah beni çok güler yüzle selamlayan komşu.']),
        mc('G4', 'die', I.choose, 'Die Serie, … wir gerade schauen, spielt in Island.', ['die', 'der', 'den'],
          ['The series that we are watching at the moment is set in Iceland.', 'Сериал, который мы сейчас смотрим, происходит в Исландии.', 'Серіал, який ми зараз дивимося, відбувається в Ісландії.', 'Şu anda izlediğimiz dizi İzlanda’da geçiyor.']),
        mc('G4', 'Relativsatz bilden', I.sentence, 'Ich habe einen Krimi gelesen. Er war sehr spannend.', ['Der Krimi, den ich gelesen habe, war sehr spannend.', 'Der Krimi, der ich gelesen habe, war sehr spannend.', 'Der Krimi, den ich habe gelesen, war sehr spannend.'],
          ['I read a crime novel. It was very exciting.', 'Я прочитал детектив. Он был очень увлекательным.', 'Я прочитав детектив. Він був дуже захопливий.', 'Bir polisiye okudum. Çok sürükleyiciydi.']),
        gap('G4', 'den', I.pronoun, 'Der Regisseur, ', ' ich am meisten bewundere, dreht nur einen Film in fünf Jahren.', 'den', ['der', 'dem'],
          ['The director whom I admire most makes only one film in five years.', 'Режиссёр, которым я больше всего восхищаюсь, снимает всего один фильм за пять лет.', 'Режисер, яким я найбільше захоплююся, знімає лише один фільм за п’ять років.', 'En çok hayran olduğum yönetmen beş yılda yalnızca bir film çekiyor.'], 'der / den / dem'),
        gap('G4', 'das', I.pronoun, 'Hast du das Buch schon gelesen, ', ' ich dir zum Geburtstag geschenkt habe?', 'das', ['den', 'die'],
          ['Have you already read the book that I gave you for your birthday?', 'Ты уже прочитал книгу, которую я подарил тебе на день рождения?', 'Ти вже прочитав книжку, яку я подарував тобі на день народження?', 'Sana doğum gününde hediye ettiğim kitabı okudun mu?'], 'den / das / die'),
        gap('G4', 'die (Plural)', I.pronoun, 'Die Filme, ', ' meine Eltern mögen, finde ich meistens ziemlich langweilig.', 'die', ['den', 'das'],
          ['I usually find the films that my parents like rather boring.', 'Фильмы, которые нравятся моим родителям, я обычно нахожу довольно скучными.', 'Фільми, які подобаються моїм батькам, я зазвичай вважаю досить нудними.', 'Annemle babamın sevdiği filmleri çoğunlukla oldukça sıkıcı buluyorum.'], 'den / das / die'),
        gap('G4', 'den', I.pronoun, 'Ist das der Kollege, ', ' du auf der Party von Selin kennengelernt hast?', 'den', ['der', 'dem'],
          ['Is that the colleague whom you met at Selin’s party?', 'Это тот коллега, с которым ты познакомился на вечеринке у Selin?', 'Це той колега, з яким ти познайомився на вечірці в Selin?', 'Selin’in partisinde tanıştığın iş arkadaşı bu mu?'], 'der / den / dem'),
        sb('G4', 'den ich … empfehlen möchte', I.order, 'Das ist / der Film, / den / ich / dir / empfehlen möchte.',
          ['That is the film that I would like to recommend to you.', 'Это фильм, который я хочу тебе посоветовать.', 'Це фільм, який я хочу тобі порадити.', 'Sana önermek istediğim film bu.']),
      ],
    },
    {
      title: 'die Freundin, mit der …',
      t: ['die Freundin, mit der … (relative clauses: dative and prepositions)', 'die Freundin, mit der … (придаточные определительные: Dativ и предлоги)', 'die Freundin, mit der … (підрядні означальні: Dativ і прийменники)', 'die Freundin, mit der … (ilgi cümlesi: Dativ ve edatlar)'],
      card: {
        id: 'p2_relativ_dat',
        rule: 'Relativpronomen im Dativ: der Freund, dem ich helfe – das Kind, dem das Buch gehört – die Kollegin, der ich vertraue – die Leute, denen ich danke. Achtung: Im Plural heißt es denen (nicht den). Mit Präposition: Die Präposition steht vor dem Relativpronomen und bestimmt den Kasus. Dativ: der Job, mit dem er Geld verdient – die Freundin, mit der ich im Kino war – die Leute, bei denen ich wohne. Akkusativ: der Film, über den alle reden – die Serie, auf die ich warte.',
        examples: ['Das ist der Freund, dem ich mein Auto geliehen habe.', 'Die Kollegin, mit der ich arbeite, kommt aus Polen.', 'Die Nachbarn, bei denen wir gefeiert haben, sind sehr nett.'],
        highlight: 'article',
        t: [
          'Relative pronouns in the dative: der Freund, dem ich helfe (the friend whom I help) – das Kind, dem das Buch gehört – die Kollegin, der ich vertraue (the colleague whom I trust) – die Leute, denen ich danke. Note: in the plural it is denen (not den). With a preposition: the preposition comes before the relative pronoun and decides the case. Dative: der Job, mit dem er Geld verdient – die Freundin, mit der ich im Kino war (the friend I went to the cinema with) – die Leute, bei denen ich wohne. Accusative: der Film, über den alle reden (the film everyone is talking about) – die Serie, auf die ich warte.',
          'Относительные местоимения в Dativ: der Freund, dem ich helfe (друг, которому я помогаю) – das Kind, dem das Buch gehört – die Kollegin, der ich vertraue (коллега, которой я доверяю) – die Leute, denen ich danke. Внимание: во множественном числе denen (не den). С предлогом: предлог стоит перед относительным местоимением и определяет падеж. Dativ: der Job, mit dem er Geld verdient – die Freundin, mit der ich im Kino war (подруга, с которой я был в кино) – die Leute, bei denen ich wohne. Akkusativ: der Film, über den alle reden (фильм, о котором все говорят) – die Serie, auf die ich warte.',
          'Відносні займенники в Dativ: der Freund, dem ich helfe (друг, якому я допомагаю) – das Kind, dem das Buch gehört – die Kollegin, der ich vertraue (колега, якій я довіряю) – die Leute, denen ich danke. Увага: у множині denen (не den). З прийменником: прийменник стоїть перед відносним займенником і визначає відмінок. Dativ: der Job, mit dem er Geld verdient – die Freundin, mit der ich im Kino war (подруга, з якою я був у кіно) – die Leute, bei denen ich wohne. Akkusativ: der Film, über den alle reden (фільм, про який усі говорять) – die Serie, auf die ich warte.',
          'Dativ’de ilgi zamirleri: der Freund, dem ich helfe (yardım ettiğim arkadaş) – das Kind, dem das Buch gehört – die Kollegin, der ich vertraue (güvendiğim iş arkadaşı) – die Leute, denen ich danke. Dikkat: Çoğulda denen kullanılır (den değil). Edatla: Edat ilgi zamirinin önünde durur ve durumu belirler. Dativ: der Job, mit dem er Geld verdient – die Freundin, mit der ich im Kino war (birlikte sinemaya gittiğim arkadaş) – die Leute, bei denen ich wohne. Akkusativ: der Film, über den alle reden (herkesin konuştuğu film) – die Serie, auf die ich warte.',
        ],
        hint: ['Dativ: dem, dem, der, denen. Mit Präposition: mit dem / mit der / bei denen (Dativ), über den / auf die (Akkusativ).', 'Dative: dem, dem, der, denen. With a preposition: mit dem / mit der / bei denen (dative), über den / auf die (accusative).', 'Dativ: dem, dem, der, denen. С предлогом: mit dem / mit der / bei denen (Dativ), über den / auf die (Akkusativ).', 'Dativ: dem, dem, der, denen. З прийменником: mit dem / mit der / bei denen (Dativ), über den / auf die (Akkusativ).', 'Dativ: dem, dem, der, denen. Edatla: mit dem / mit der / bei denen (Dativ), über den / auf die (Akkusativ).'],
      },
      ex: [
        mc('G5', 'dem', I.choose, 'Das ist der Freund, … ich meine alten DVDs geschenkt habe.', ['dem', 'den', 'der'],
          ['That is the friend to whom I gave my old DVDs.', 'Это друг, которому я подарил свои старые DVD.', 'Це друг, якому я подарував свої старі DVD.', 'Bu, eski DVD’lerimi hediye ettiğim arkadaş.']),
        mc('G5', 'mit der', I.choose, 'Die Kollegin, mit … ich gestern im Kino war, liebt alte Liebesfilme.', ['der', 'die', 'dem'],
          ['The colleague I went to the cinema with yesterday loves old romantic films.', 'Коллега, с которой я вчера был в кино, обожает старые фильмы о любви.', 'Колега, з якою я вчора був у кіно, обожнює старі фільми про кохання.', 'Dün birlikte sinemaya gittiğim iş arkadaşım eski aşk filmlerine bayılır.']),
        mc('G5', 'denen', I.choose, 'Die Schauspieler, … das Publikum lange applaudierte, kamen noch einmal auf die Bühne.', ['denen', 'den', 'die'],
          ['The actors, whom the audience applauded for a long time, came back on stage once more.', 'Актёры, которым публика долго аплодировала, ещё раз вышли на сцену.', 'Актори, яким публіка довго аплодувала, ще раз вийшли на сцену.', 'Seyircinin uzun süre alkışladığı oyuncular bir kez daha sahneye çıktı.']),
        mc('G5', 'über den', I.choose, 'Wie heißt eigentlich der Film, über … gerade alle reden?', ['den', 'dem', 'der'],
          ['What is the name of the film that everyone is talking about at the moment?', 'Как же называется фильм, о котором сейчас все говорят?', 'Як же називається фільм, про який зараз усі говорять?', 'Şu sıralar herkesin konuştuğu filmin adı ne?']),
        mc('G5', 'dem', I.choose, 'Das Kind, … dieses Fahrrad gehört, wohnt im dritten Stock.', ['dem', 'das', 'den'],
          ['The child to whom this bike belongs lives on the third floor.', 'Ребёнок, которому принадлежит этот велосипед, живёт на третьем этаже.', 'Дитина, якій належить цей велосипед, живе на третьому поверсі.', 'Bu bisikletin sahibi olan çocuk üçüncü katta oturuyor.']),
        gap('G5', 'bei denen', I.pronoun, 'Die Freunde, bei ', ' wir Silvester gefeiert haben, besitzen einen riesigen Fernseher.', 'denen', ['den', 'die'],
          ['The friends at whose place we celebrated New Year’s Eve own a huge television.', 'У друзей, у которых мы праздновали Новый год, огромный телевизор.', 'У друзів, у яких ми святкували Новий рік, величезний телевізор.', 'Yılbaşını evlerinde kutladığımız arkadaşların kocaman bir televizyonu var.'], 'den / denen / die'),
        gap('G5', 'der', I.pronoun, 'Das ist die Nachbarin, ', ' ich oft beim Einkaufen helfe.', 'der', ['die', 'dem'],
          ['That is the neighbour whom I often help with the shopping.', 'Это соседка, которой я часто помогаю с покупками.', 'Це сусідка, якій я часто допомагаю з покупками.', 'Bu, alışverişte sık sık yardım ettiğim komşu.'], 'die / der / dem'),
        gap('G5', 'in dem', I.pronoun, 'Der Sessel, in ', ' Opa jeden Abend fernsieht, ist schon dreißig Jahre alt.', 'dem', ['den', 'der'],
          ['The armchair in which Grandad watches television every evening is already thirty years old.', 'Креслу, в котором дедушка каждый вечер смотрит телевизор, уже тридцать лет.', 'Кріслу, у якому дідусь щовечора дивиться телевізор, уже тридцять років.', 'Dedemin her akşam içinde televizyon izlediği koltuk otuz yaşında.'], 'den / dem / der'),
        gap('G5', 'auf die', I.pronoun, 'Die Serie, auf ', ' ich seit Monaten warte, beginnt endlich nächste Woche.', 'die', ['der', 'den'],
          ['The series that I have been waiting for for months finally starts next week.', 'Сериал, которого я жду уже несколько месяцев, наконец начинается на следующей неделе.', 'Серіал, на який я чекаю вже кілька місяців, нарешті починається наступного тижня.', 'Aylardır beklediğim dizi nihayet gelecek hafta başlıyor.'], 'die / der / den'),
        sb('G5', 'mit dem', I.order, 'Das ist / der Kollege, / mit dem / ich / im Büro / sitze.',
          ['That is the colleague I share an office with.', 'Это коллега, с которым я сижу в одном кабинете.', 'Це колега, з яким я сиджу в одному кабінеті.', 'Bu, aynı ofiste oturduğum iş arkadaşım.']),
      ],
    },
    {
      title: 'der, den oder dem?',
      t: ['der, den or dem? (which relative pronoun?)', 'der, den или dem? (какое относительное местоимение?)', 'der, den чи dem? (який відносний займенник?)', 'der, den ya da dem? (hangi ilgi zamiri?)'],
      card: {
        id: 'p2_relativ_mix',
        rule: 'Welches Relativpronomen? Zwei Fragen helfen. 1. Welches Genus und welche Zahl hat das Nomen vor dem Komma? 2. Welche Rolle hat das Relativpronomen im Relativsatz? Subjekt → Nominativ (der, das, die, die). Akkusativobjekt → Akkusativ (den, das, die, die). Dativobjekt → Dativ (dem, dem, der, denen). Nach einer Präposition bestimmt die Präposition den Kasus. Der Relativsatz kann auch in der Mitte stehen: Der Mann, den ich meine, trägt einen Hut.',
        examples: ['Ich habe einen Freund, der Filme dreht.', 'Ich habe einen Freund, den ich seit der Schule kenne.', 'Ich habe einen Freund, dem ich alles erzählen kann.'],
        highlight: 'article',
        t: [
          'Which relative pronoun? Two questions help. 1. What gender and number has the noun before the comma? 2. What role does the relative pronoun play in the relative clause? Subject → nominative (der, das, die, die). Accusative object → accusative (den, das, die, die). Dative object → dative (dem, dem, der, denen). After a preposition, the preposition decides the case. The relative clause can also stand in the middle: Der Mann, den ich meine, trägt einen Hut. (The man I mean is wearing a hat.)',
          'Какое относительное местоимение? Помогут два вопроса. 1. Какого рода и числа существительное перед запятой? 2. Какую роль играет относительное местоимение в придаточном? Подлежащее → Nominativ (der, das, die, die). Прямое дополнение → Akkusativ (den, das, die, die). Дополнение в дательном падеже → Dativ (dem, dem, der, denen). После предлога падеж определяет предлог. Придаточное может стоять и в середине: Der Mann, den ich meine, trägt einen Hut. (Мужчина, которого я имею в виду, носит шляпу.)',
          'Який відносний займенник? Допоможуть два запитання. 1. Якого роду й числа іменник перед комою? 2. Яку роль відіграє відносний займенник у підрядному реченні? Підмет → Nominativ (der, das, die, die). Прямий додаток → Akkusativ (den, das, die, die). Додаток у давальному відмінку → Dativ (dem, dem, der, denen). Після прийменника відмінок визначає прийменник. Підрядне речення може стояти й у середині: Der Mann, den ich meine, trägt einen Hut. (Чоловік, якого я маю на увазі, носить капелюх.)',
          'Hangi ilgi zamiri? İki soru yardımcı olur. 1. Virgülden önceki ismin cinsiyeti ve sayısı ne? 2. İlgi zamiri ilgi cümlesinde hangi görevde? Özne → Nominativ (der, das, die, die). Akkusativ nesnesi → Akkusativ (den, das, die, die). Dativ nesnesi → Dativ (dem, dem, der, denen). Bir edattan sonra durumu edat belirler. İlgi cümlesi ortada da durabilir: Der Mann, den ich meine, trägt einen Hut. (Kastettiğim adam şapka takıyor.)',
        ],
        hint: ['Subjekt → der/das/die/die. Akkusativ → den/das/die/die. Dativ → dem/dem/der/denen. Präposition bestimmt den Kasus.', 'Subject → der/das/die/die. Accusative → den/das/die/die. Dative → dem/dem/der/denen. A preposition decides the case.', 'Подлежащее → der/das/die/die. Akkusativ → den/das/die/die. Dativ → dem/dem/der/denen. Предлог определяет падеж.', 'Підмет → der/das/die/die. Akkusativ → den/das/die/die. Dativ → dem/dem/der/denen. Прийменник визначає відмінок.', 'Özne → der/das/die/die. Akkusativ → den/das/die/die. Dativ → dem/dem/der/denen. Edat durumu belirler.'],
      },
      ex: [
        mc('G3', 'der (Subjekt)', I.choose, 'Hast du einen Freund, … sich gut mit Computern auskennt?', ['der', 'den', 'dem'],
          ['Have you got a friend who knows a lot about computers?', 'У тебя есть друг, который хорошо разбирается в компьютерах?', 'У тебе є друг, який добре розуміється на комп’ютерах?', 'Bilgisayarlardan iyi anlayan bir arkadaşın var mı?']),
        mc('G4', 'den (Objekt)', I.choose, 'Hast du einen Freund, … ich um Hilfe bitten kann?', ['den', 'der', 'dem'],
          ['Have you got a friend whom I can ask for help?', 'У тебя есть друг, которого я могу попросить о помощи?', 'У тебе є друг, якого я можу попросити про допомогу?', 'Yardım isteyebileceğim bir arkadaşın var mı?']),
        mc('G5', 'dem (Dativ)', I.choose, 'Hast du einen Freund, … man wirklich alles erzählen kann?', ['dem', 'den', 'der'],
          ['Have you got a friend to whom you can really tell everything?', 'У тебя есть друг, которому действительно можно всё рассказать?', 'У тебе є друг, якому справді можна все розповісти?', 'Gerçekten her şeyi anlatabileceğin bir arkadaşın var mı?']),
        mc('G5', 'mit dem', I.choose, 'Gibt es hier jemanden, mit … ich über meinen Vertrag sprechen kann?', ['dem', 'den', 'der'],
          ['Is there anybody here with whom I can talk about my contract?', 'Есть ли здесь кто-нибудь, с кем я могу поговорить о своём договоре?', 'Чи є тут хтось, із ким я можу поговорити про свій договір?', 'Burada sözleşmem hakkında konuşabileceğim biri var mı?']),
        mc('G3', 'Relativsatz in der Mitte', I.sentence, 'Die Frau wohnt neben uns. Sie arbeitet beim Fernsehen.', ['Die Frau, die neben uns wohnt, arbeitet beim Fernsehen.', 'Die Frau, die wohnt neben uns, arbeitet beim Fernsehen.', 'Die Frau arbeitet beim Fernsehen, der neben uns wohnt.'],
          ['The woman lives next door to us. She works in television.', 'Эта женщина живёт рядом с нами. Она работает на телевидении.', 'Ця жінка живе поруч із нами. Вона працює на телебаченні.', 'Kadın yanımızda oturuyor. Televizyonda çalışıyor.']),
        gap('G4', 'den', I.pronoun, 'Erinnerst du dich an den Lehrer, ', ' wir in der achten Klasse hatten?', 'den', ['der', 'dem'],
          ['Do you remember the teacher we had in year eight?', 'Ты помнишь учителя, который был у нас в восьмом классе?', 'Ти пам’ятаєш учителя, який був у нас у восьмому класі?', 'Sekizinci sınıftaki öğretmenimizi hatırlıyor musun?'], 'der / den / dem'),
        gap('G3', 'der', I.pronoun, 'Das ist ein Musiker, ', ' in ganz Europa bekannt ist.', 'der', ['den', 'dem'],
          ['That is a musician who is known all over Europe.', 'Это музыкант, который известен во всей Европе.', 'Це музикант, який відомий у всій Європі.', 'Bu, bütün Avrupa’da tanınan bir müzisyen.'], 'der / den / dem'),
        gap('G5', 'denen', I.pronoun, 'Die Kinder, ', ' der Film zu lang war, sind schon in der Pause gegangen.', 'denen', ['die', 'den'],
          ['The children for whom the film was too long left at the interval.', 'Дети, для которых фильм оказался слишком длинным, ушли уже в перерыве.', 'Діти, для яких фільм виявився задовгим, пішли вже в перерві.', 'Filmi fazla uzun bulan çocuklar daha arada çıkıp gitti.'], 'die / den / denen'),
        gap('G4', 'den', I.pronoun, 'Kennst du jemanden, ', ' ich nach dem Weg zum Kino fragen könnte?', 'den', ['der', 'dem'],
          ['Do you know anybody I could ask the way to the cinema?', 'Ты знаешь кого-нибудь, у кого я мог бы спросить дорогу к кинотеатру?', 'Ти знаєш когось, у кого я міг би спитати дорогу до кінотеатру?', 'Sinemanın yolunu sorabileceğim birini tanıyor musun?'], 'der / den / dem'),
        sb('G5', 'mit der', I.order, 'Die Freundin, / mit der / ich / zusammenwohne, / ist / Schauspielerin.',
          ['The friend I share a flat with is an actress.', 'Подруга, с которой я живу вместе, – актриса.', 'Подруга, з якою я живу разом, – акторка.', 'Birlikte oturduğum arkadaşım oyuncu.']),
      ],
    },
    {
      title: 'Meine Lieblingsserie',
      t: ['My favourite series', 'Мой любимый сериал', 'Мій улюблений серіал', 'En sevdiğim dizi'],
      card: {
        id: 'p2_serie',
        rule: 'Eine Serie oder einen Film beschreiben: Meine Lieblingsserie heißt … Sie kommt aus Schweden. Sie wurde in Kanada gedreht. Die Hauptfigur ist eine junge Ärztin. Die Serie spielt in der heutigen Zeit / vor hundert Jahren / in Berlin. Worum geht es? – In der Serie geht es um eine Familie (es geht um + Akkusativ). Die Serie handelt von einer Familie (handeln von + Dativ). Die eigene Meinung: Besonders spannend finde ich … Obwohl ich Krimis eigentlich nicht mag, …',
        examples: ['In dem Film geht es um zwei Brüder.', 'Die Serie handelt von einer Lehrerin in Hamburg.', 'Die Geschichte spielt im Jahr 1960.'],
        highlight: null,
        t: [
          'Describing a series or a film: Meine Lieblingsserie heißt … (My favourite series is called …) Sie kommt aus Schweden. Sie wurde in Kanada gedreht. (It was filmed in Canada.) Die Hauptfigur ist eine junge Ärztin. Die Serie spielt in der heutigen Zeit / vor hundert Jahren / in Berlin. (The series is set in the present day / a hundred years ago / in Berlin.) Worum geht es? (What is it about?) – In der Serie geht es um eine Familie (es geht um + accusative). Die Serie handelt von einer Familie (handeln von + dative). Your own opinion: Besonders spannend finde ich … Obwohl ich Krimis eigentlich nicht mag, …',
          'Как описать сериал или фильм: Meine Lieblingsserie heißt … (Мой любимый сериал называется …) Sie kommt aus Schweden. Sie wurde in Kanada gedreht. (Его снимали в Канаде.) Die Hauptfigur ist eine junge Ärztin. Die Serie spielt in der heutigen Zeit / vor hundert Jahren / in Berlin. (Действие сериала происходит в наше время / сто лет назад / в Берлине.) Worum geht es? (О чём он?) – In der Serie geht es um eine Familie (es geht um + Akkusativ). Die Serie handelt von einer Familie (handeln von + Dativ). Своё мнение: Besonders spannend finde ich … Obwohl ich Krimis eigentlich nicht mag, …',
          'Як описати серіал або фільм: Meine Lieblingsserie heißt … (Мій улюблений серіал називається …) Sie kommt aus Schweden. Sie wurde in Kanada gedreht. (Його знімали в Канаді.) Die Hauptfigur ist eine junge Ärztin. Die Serie spielt in der heutigen Zeit / vor hundert Jahren / in Berlin. (Дія серіалу відбувається в наш час / сто років тому / у Берліні.) Worum geht es? (Про що він?) – In der Serie geht es um eine Familie (es geht um + Akkusativ). Die Serie handelt von einer Familie (handeln von + Dativ). Власна думка: Besonders spannend finde ich … Obwohl ich Krimis eigentlich nicht mag, …',
          'Bir diziyi ya da filmi anlatmak: Meine Lieblingsserie heißt … (En sevdiğim dizinin adı …) Sie kommt aus Schweden. Sie wurde in Kanada gedreht. (Kanada’da çekildi.) Die Hauptfigur ist eine junge Ärztin. Die Serie spielt in der heutigen Zeit / vor hundert Jahren / in Berlin. (Dizi günümüzde / yüz yıl önce / Berlin’de geçiyor.) Worum geht es? (Konusu ne?) – In der Serie geht es um eine Familie (es geht um + Akkusativ). Die Serie handelt von einer Familie (handeln von + Dativ). Kendi görüşünüz: Besonders spannend finde ich … Obwohl ich Krimis eigentlich nicht mag, …',
        ],
        hint: ['Es geht um + Akkusativ. Die Serie handelt von + Dativ. Sie spielt in … Die Hauptfigur ist …', 'Es geht um + accusative. Die Serie handelt von + dative. Sie spielt in … Die Hauptfigur ist …', 'Es geht um + Akkusativ (винительный падеж). Die Serie handelt von + Dativ. Sie spielt in … Die Hauptfigur ist …', 'Es geht um + Akkusativ (знахідний відмінок). Die Serie handelt von + Dativ. Sie spielt in … Die Hauptfigur ist …', 'Es geht um + Akkusativ (belirtme durumu). Die Serie handelt von + Dativ. Sie spielt in … Die Hauptfigur ist …'],
      },
      ex: [
        mc('K1', 'es geht um', I.choose, 'In dem Film geht es … einen Jungen, der seinen Vater sucht.', ['um', 'von', 'über'],
          ['The film is about a boy who is looking for his father.', 'В фильме речь идёт о мальчике, который ищет своего отца.', 'У фільмі йдеться про хлопчика, який шукає свого батька.', 'Film, babasını arayan bir çocuğu anlatıyor.']),
        mc('K1', 'handeln von', I.choose, 'Die Serie handelt … einer Familie, die ein kleines Hotel in den Bergen führt.', ['von', 'um', 'über'],
          ['The series is about a family that runs a small hotel in the mountains.', 'Сериал рассказывает о семье, которая держит небольшой отель в горах.', 'Серіал розповідає про родину, яка тримає невеликий готель у горах.', 'Dizi, dağlarda küçük bir otel işleten bir aileyi konu alıyor.']),
        mc('K1', 'spielt', I.choose, 'Der Film … im Jahr 1920 in Wien, als es dort noch Pferdewagen gab.', ['spielt', 'handelt', 'geht'],
          ['The film is set in Vienna in 1920, when there were still horse-drawn carts there.', 'Действие фильма происходит в 1920 году в Вене, когда там ещё ездили на повозках.', 'Дія фільму відбувається 1920 року у Відні, коли там ще їздили возами.', 'Film 1920 yılında, at arabalarının hâlâ kullanıldığı Viyana’da geçiyor.']),
        mc('K1', 'Worum geht es?', I.react, '„Worum geht es denn in deiner Lieblingsserie?“', ['Es geht um vier Freunde, die zusammen in einer Wohnung leben.', 'Sie läuft jeden Dienstag um 20 Uhr.', 'Ich schaue sie am liebsten mit meiner Schwester.'],
          ['“So what is your favourite series about?”', '«Так о чём же твой любимый сериал?»', '«То про що ж твій улюблений серіал?»', '“En sevdiğin dizinin konusu ne?”']),
        mc('K1', 'gedreht', I.choose, 'Die Serie wurde in Kanada …, aber die Geschichte spielt in Alaska.', ['gedreht', 'gespielt', 'gehandelt'],
          ['The series was filmed in Canada, but the story is set in Alaska.', 'Сериал снимали в Канаде, но действие происходит на Аляске.', 'Серіал знімали в Канаді, але дія відбувається на Алясці.', 'Dizi Kanada’da çekildi ama hikâye Alaska’da geçiyor.']),
        gap('K1', 'Hauptfigur', I.word, 'Die ', ' ist ein Polizist, der kurz vor der Rente steht und noch einen letzten Fall lösen will.', 'Hauptfigur', ['Handlung', 'Staffel'],
          ['The main character is a policeman who is about to retire and wants to solve one last case.', 'Главный герой – полицейский, который скоро выходит на пенсию и хочет раскрыть последнее дело.', 'Головний герой – поліцейський, який невдовзі виходить на пенсію і хоче розкрити останню справу.', 'Ana karakter, emekliliği yaklaşan ve son bir davayı çözmek isteyen bir polis.'],
          ['main character', 'главный герой', 'головний герой', 'ana karakter']),
        gap('K1', 'Worum geht es?', I.verb, 'Worum ', ' es in dem Buch, das du gerade liest? – Um eine Reise durch Afrika.', 'geht', ['handelt', 'spielt'],
          ['What is the book you are reading about? – A journey through Africa.', 'О чём книга, которую ты сейчас читаешь? – О путешествии по Африке.', 'Про що книжка, яку ти зараз читаєш? – Про подорож Африкою.', 'Şu an okuduğun kitabın konusu ne? – Afrika’da bir yolculuk.'], 'gehen / handeln / spielen'),
        gap('K1', 'in der heutigen Zeit', I.word, 'Die Geschichte spielt in der heutigen ', ', nicht in der Vergangenheit.', 'Zeit', ['Folge', 'Rolle'],
          ['The story is set in the present day, not in the past.', 'Действие происходит в наше время, а не в прошлом.', 'Дія відбувається в наш час, а не в минулому.', 'Hikâye geçmişte değil, günümüzde geçiyor.'],
          ['time, era', 'время, эпоха', 'час, епоха', 'zaman, dönem']),
        gap('K1', 'von einer', I.form, 'Der Film handelt von ', ' Musikerin, die plötzlich ihre Stimme verliert.', 'einer', ['eine', 'einem'],
          ['The film is about a musician who suddenly loses her voice.', 'Фильм рассказывает о музыкантше, которая внезапно теряет голос.', 'Фільм розповідає про музикантку, яка раптом втрачає голос.', 'Film, sesini birden kaybeden bir kadın müzisyeni anlatıyor.'], 'eine'),
        sb('K1', 'es geht um', I.order, 'In der Serie / geht / es / um eine Ärztin.',
          ['The series is about a doctor.', 'В сериале речь идёт о женщине-враче.', 'У серіалі йдеться про лікарку.', 'Dizi bir kadın doktoru anlatıyor.'],
          { alt: ['Es geht in der Serie um eine Ärztin.', 'Um eine Ärztin geht es in der Serie.'] }),
      ],
    },
    {
      title: 'Vorschlagen, ablehnen, sich einigen',
      t: ['Suggesting, declining, reaching agreement', 'Предложить, отказаться, договориться', 'Запропонувати, відмовитися, домовитися', 'Önermek, reddetmek, anlaşmak'],
      card: {
        id: 'p2_einigen',
        rule: 'Sich in einer Diskussion einigen. Vorschlagen: Lass uns doch ins Kino gehen. Wir könnten doch … Wie wäre es, wenn wir …? Habt ihr Lust auf …? Ich habe da einen Vorschlag: … Ablehnen: Das kommt für mich nicht infrage. Das möchte ich wirklich nicht. Nein, auf keinen Fall. Ich finde das keine so gute Idee. Das Thema interessiert mich nicht so. Gegenvorschlag: Ich würde lieber … Ich finde … besser, weil … Zustimmen und sich einigen: Das ist ein guter Vorschlag! Da hast du völlig recht. Einverstanden! Okay, das machen wir. Ich bin auch dafür.',
        examples: ['Wie wäre es, wenn wir heute einen Film schauen?', 'Das kommt für mich nicht infrage.', 'Einverstanden, das machen wir!'],
        highlight: null,
        t: [
          'Reaching agreement in a discussion. Suggesting: Lass uns doch ins Kino gehen. (Let’s go to the cinema.) Wir könnten doch … Wie wäre es, wenn wir …? (How about if we …?) Habt ihr Lust auf …? Ich habe da einen Vorschlag: … (I have a suggestion.) Declining: Das kommt für mich nicht infrage. (That is out of the question for me.) Das möchte ich wirklich nicht. Nein, auf keinen Fall. (No, definitely not.) Ich finde das keine so gute Idee. Das Thema interessiert mich nicht so. Counter-suggestion: Ich würde lieber … (I would rather …) Ich finde … besser, weil … Agreeing: Das ist ein guter Vorschlag! Da hast du völlig recht. (You are absolutely right.) Einverstanden! (Agreed!) Okay, das machen wir. Ich bin auch dafür. (I am in favour too.)',
          'Как договориться в дискуссии. Предложить: Lass uns doch ins Kino gehen. (Давай пойдём в кино.) Wir könnten doch … Wie wäre es, wenn wir …? (Как насчёт того, чтобы мы …?) Habt ihr Lust auf …? Ich habe da einen Vorschlag: … (У меня есть предложение.) Отказаться: Das kommt für mich nicht infrage. (Для меня это исключено.) Das möchte ich wirklich nicht. Nein, auf keinen Fall. (Нет, ни в коем случае.) Ich finde das keine so gute Idee. Das Thema interessiert mich nicht so. Встречное предложение: Ich würde lieber … (Я бы лучше …) Ich finde … besser, weil … Согласиться: Das ist ein guter Vorschlag! Da hast du völlig recht. (Тут ты совершенно прав.) Einverstanden! (Согласен!) Okay, das machen wir. Ich bin auch dafür. (Я тоже за.)',
          'Як домовитися в дискусії. Запропонувати: Lass uns doch ins Kino gehen. (Ходімо в кіно.) Wir könnten doch … Wie wäre es, wenn wir …? (Як щодо того, щоб ми …?) Habt ihr Lust auf …? Ich habe da einen Vorschlag: … (У мене є пропозиція.) Відмовитися: Das kommt für mich nicht infrage. (Для мене це виключено.) Das möchte ich wirklich nicht. Nein, auf keinen Fall. (Ні, у жодному разі.) Ich finde das keine so gute Idee. Das Thema interessiert mich nicht so. Зустрічна пропозиція: Ich würde lieber … (Я б радше …) Ich finde … besser, weil … Погодитися: Das ist ein guter Vorschlag! Da hast du völlig recht. (Тут ти цілком маєш рацію.) Einverstanden! (Згода!) Okay, das machen wir. Ich bin auch dafür. (Я теж за.)',
          'Bir tartışmada anlaşmak. Önermek: Lass uns doch ins Kino gehen. (Hadi sinemaya gidelim.) Wir könnten doch … Wie wäre es, wenn wir …? (… yapsak nasıl olur?) Habt ihr Lust auf …? Ich habe da einen Vorschlag: … (Bir önerim var.) Reddetmek: Das kommt für mich nicht infrage. (Bu benim için söz konusu olamaz.) Das möchte ich wirklich nicht. Nein, auf keinen Fall. (Hayır, kesinlikle olmaz.) Ich finde das keine so gute Idee. Das Thema interessiert mich nicht so. Karşı öneri: Ich würde lieber … (Ben … tercih ederim.) Ich finde … besser, weil … Katılmak ve anlaşmak: Das ist ein guter Vorschlag! Da hast du völlig recht. (Bu konuda tamamen haklısın.) Einverstanden! (Anlaştık!) Okay, das machen wir. Ich bin auch dafür. (Ben de bundan yanayım.)',
        ],
        hint: ['Vorschlag: Lass uns … / Wie wäre es, wenn …? Nein: Das kommt nicht infrage. Ja: Einverstanden! Da hast du recht.', 'Suggestion: Lass uns … / Wie wäre es, wenn …? No: Das kommt nicht infrage. Yes: Einverstanden! Da hast du recht.', 'Предложение: Lass uns … / Wie wäre es, wenn …? Нет: Das kommt nicht infrage. Да: Einverstanden! Da hast du recht.', 'Пропозиція: Lass uns … / Wie wäre es, wenn …? Ні: Das kommt nicht infrage. Так: Einverstanden! Da hast du recht.', 'Öneri: Lass uns … / Wie wäre es, wenn …? Hayır: Das kommt nicht infrage. Evet: Einverstanden! Da hast du recht.'],
      },
      ex: [
        mc('K2', 'Wie wäre es, wenn …?', I.situation, 'Du möchtest mit deinen Freunden am Samstag einen Filmabend machen. Wie schlägst du das vor?', ['Wie wäre es, wenn wir am Samstag einen Filmabend machen?', 'Das kommt für mich nicht infrage.', 'Da hast du völlig recht.'],
          ['You would like to have a film night with your friends on Saturday. How do you suggest it?', 'Вы хотите в субботу устроить с друзьями вечер кино. Как вы это предложите?', 'Ви хочете в суботу влаштувати з друзями вечір кіно. Як ви це запропонуєте?', 'Cumartesi günü arkadaşlarınızla bir film gecesi yapmak istiyorsunuz. Bunu nasıl önerirsiniz?']),
        mc('K2', 'Lass uns …', I.choose, '… uns doch heute Abend den neuen Krimi anschauen!', ['Lass', 'Lässt', 'Lassen'],
          ['Let’s watch the new crime film tonight!', 'Давай сегодня вечером посмотрим новый детектив!', 'Подивімося сьогодні ввечері новий детектив!', 'Hadi bu akşam yeni polisiyeyi izleyelim!']),
        mc('K2', 'Gegenvorschlag', I.react, '„Wir könnten heute einen Horrorfilm sehen.“ – Du magst keine Horrorfilme und hast eine andere Idee.', ['Ich würde lieber eine Komödie sehen.', 'Einverstanden, das machen wir.', 'Das ist ein guter Vorschlag!'],
          ['“We could watch a horror film today.” – You do not like horror films and have another idea.', '«Мы могли бы сегодня посмотреть фильм ужасов.» – Вы не любите фильмы ужасов, и у вас другая идея.', '«Ми могли б сьогодні подивитися фільм жахів.» – Ви не любите фільми жахів і маєте іншу ідею.', '“Bugün bir korku filmi izleyebiliriz.” – Korku filmlerini sevmiyorsunuz ve başka bir fikriniz var.']),
        mc('K3', 'nicht infrage kommen', I.react, '„Lass uns die ganze Nacht Serien schauen!“ – Du musst morgen früh arbeiten und willst das auf keinen Fall.', ['Nein, das kommt für mich nicht infrage.', 'Ja, da bin ich auch dafür.', 'Gute Idee, dann machen wir das so.'],
          ['“Let’s watch series all night!” – You have to work early tomorrow and definitely do not want to.', '«Давай всю ночь смотреть сериалы!» – Вам завтра рано на работу, и вы этого ни в коем случае не хотите.', '«Дивімося серіали всю ніч!» – Вам завтра рано на роботу, і ви цього в жодному разі не хочете.', '“Hadi bütün gece dizi izleyelim!” – Yarın sabah erken çalışmanız gerekiyor ve bunu kesinlikle istemiyorsunuz.']),
        mc('K3', 'auf keinen Fall', I.choose, 'Schon wieder Fußball im Fernsehen? Nein, auf keinen …! Das hatten wir gestern schon.', ['Fall', 'Punkt', 'Weg'],
          ['Football on television again? No, definitely not! We had that yesterday already.', 'Опять футбол по телевизору? Нет, ни в коем случае! Это было уже вчера.', 'Знову футбол по телевізору? Ні, у жодному разі! Це було вже вчора.', 'Yine mi televizyonda futbol? Hayır, kesinlikle olmaz! Dün zaten izledik.']),
        mc('K4', 'Da hast du völlig recht.', I.react, '„Der Film ist zu lang für die Kinder. Wir sollten etwas Kürzeres aussuchen.“ – Du siehst das genauso.', ['Da hast du völlig recht.', 'Das möchte ich wirklich nicht.', 'Muss das sein?'],
          ['“The film is too long for the children. We should choose something shorter.” – You see it the same way.', '«Фильм слишком длинный для детей. Нам стоит выбрать что-нибудь покороче.» – Вы думаете так же.', '«Фільм задовгий для дітей. Нам варто вибрати щось коротше.» – Ви думаєте так само.', '“Film çocuklar için fazla uzun. Daha kısa bir şey seçmeliyiz.” – Siz de aynı fikirdesiniz.']),
        mc('K4', 'Einverstanden!', I.choose, 'Welche Reaktion bedeutet, dass man zustimmt?', ['Einverstanden!', 'Auf keinen Fall!', 'Das interessiert mich nicht so.'],
          ['Which response means that you agree?', 'Какая реакция означает согласие?', 'Яка реакція означає згоду?', 'Hangi tepki aynı fikirde olduğunuzu gösterir?']),
        gap('K3', 'nicht infrage kommen', I.verb, 'Einen Film mit Untertiteln? Das ', ' für mich nicht infrage, da muss ich zu viel lesen.', 'kommt', ['geht', 'steht'],
          ['A film with subtitles? That is out of the question for me; I have to read too much.', 'Фильм с субтитрами? Для меня это исключено, там слишком много читать.', 'Фільм із субтитрами? Для мене це виключено, там забагато читати.', 'Altyazılı bir film mi? Bu benim için söz konusu olamaz, çok fazla okumam gerekiyor.'], 'kommen / gehen / stehen'),
        gap('K2', 'Vorschlag', I.word, 'Ich habe da einen ', ': Wollen wir nicht mal wieder zusammen ins Theater gehen?', 'Vorschlag', ['Fall', 'Zuschauer'],
          ['I have a suggestion: why don’t we go to the theatre together again some time?', 'У меня есть предложение: не сходить ли нам снова вместе в театр?', 'У мене є пропозиція: чи не сходити нам знову разом до театру?', 'Bir önerim var: Yine birlikte tiyatroya gitsek mi?'],
          ['suggestion', 'предложение', 'пропозиція', 'öneri']),
        gap('K4', 'einverstanden', I.word, 'Gut, dann schauen wir heute deinen Film und morgen meinen. Bist du damit ', '?', 'einverstanden', ['langweilig', 'spannend'],
          ['All right, then we will watch your film today and mine tomorrow. Do you agree to that?', 'Хорошо, тогда сегодня смотрим твой фильм, а завтра мой. Ты согласен?', 'Добре, тоді сьогодні дивимося твій фільм, а завтра мій. Ти згоден?', 'Peki, o zaman bugün senin filmini, yarın benimkini izleriz. Buna razı mısın?'],
          ['in agreement', 'согласен', 'згоден', 'razı, kabul']),
      ],
    },
    {
      title: 'Statistik: Fernsehen',
      t: ['Statistics: television', 'Статистика: телевидение', 'Статистика: телебачення', 'İstatistik: televizyon'],
      card: {
        id: 'p2_statistik',
        rule: 'Eine Statistik und Texte über Medien verstehen. Wichtige Wörter: täglich = jeden Tag, durchschnittlich / im Durchschnitt = im Mittel, die Befragten = die Personen, die geantwortet haben, die meisten, mehr als / weniger als, fast, etwa, nur. Zahlen: dreieinhalb Stunden = 3,5 Stunden, jeder Dritte = eine Person von drei. Achte darauf: Wer? Wie viel? Wie lange? Mehr oder weniger als andere?',
        examples: ['Die Deutschen sehen täglich dreieinhalb Stunden fern.', 'Jeder Dritte benutzt dabei das Handy.', 'Jugendliche schauen weniger fern als ältere Menschen.'],
        highlight: null,
        t: [
          'Understanding statistics and texts about media. Important words: täglich = every day, durchschnittlich / im Durchschnitt = on average, die Befragten = the people who answered (respondents), die meisten (most), mehr als / weniger als (more than / less than), fast (almost), etwa (about), nur (only). Numbers: dreieinhalb Stunden = 3.5 hours, jeder Dritte = one person in three. Look for: who? how much? how long? more or less than others?',
          'Как понимать статистику и тексты о медиа. Важные слова: täglich = каждый день, durchschnittlich / im Durchschnitt = в среднем, die Befragten = люди, которые отвечали (опрошенные), die meisten (большинство), mehr als / weniger als (больше чем / меньше чем), fast (почти), etwa (примерно), nur (только). Числа: dreieinhalb Stunden = 3,5 часа, jeder Dritte = один человек из трёх. Обращайте внимание: кто? сколько? как долго? больше или меньше, чем другие?',
          'Як розуміти статистику і тексти про медіа. Важливі слова: täglich = щодня, durchschnittlich / im Durchschnitt = у середньому, die Befragten = люди, які відповідали (опитані), die meisten (більшість), mehr als / weniger als (більше ніж / менше ніж), fast (майже), etwa (приблизно), nur (лише). Числа: dreieinhalb Stunden = 3,5 години, jeder Dritte = одна людина з трьох. Звертайте увагу: хто? скільки? як довго? більше чи менше, ніж інші?',
          'İstatistikleri ve medya ile ilgili metinleri anlamak. Önemli kelimeler: täglich = her gün, durchschnittlich / im Durchschnitt = ortalama olarak, die Befragten = cevap veren kişiler (ankete katılanlar), die meisten (çoğu), mehr als / weniger als (-den fazla / -den az), fast (neredeyse), etwa (yaklaşık), nur (yalnızca). Sayılar: dreieinhalb Stunden = 3,5 saat, jeder Dritte = üç kişiden biri. Şunlara dikkat edin: Kim? Ne kadar? Ne kadar süre? Diğerlerinden çok mu, az mı?',
        ],
        hint: ['täglich = jeden Tag. im Durchschnitt = im Mittel. jeder Dritte = einer von drei. dreieinhalb = 3,5.', 'täglich = every day. im Durchschnitt = on average. jeder Dritte = one in three. dreieinhalb = 3.5.', 'täglich = каждый день. im Durchschnitt = в среднем. jeder Dritte = один из трёх. dreieinhalb = 3,5.', 'täglich = щодня. im Durchschnitt = у середньому. jeder Dritte = один із трьох. dreieinhalb = 3,5.', 'täglich = her gün. im Durchschnitt = ortalama olarak. jeder Dritte = üç kişiden biri. dreieinhalb = 3,5.'],
      },
      ex: [
        mc('Z1', 'Durchschnitt', I.read, `${STATISTIK} Wie lange sehen Erwachsene durchschnittlich pro Tag fern?`, ['Ungefähr dreieinhalb Stunden.', 'Mehr als fünf Stunden.', 'Nur eine Stunde.'],
          ['How long do adults watch television per day on average?', 'Сколько в среднем взрослые смотрят телевизор в день?', 'Скільки в середньому дорослі дивляться телевізор на день?', 'Yetişkinler günde ortalama ne kadar televizyon izliyor?']),
        mc('Z1', 'Wer am meisten?', I.read, `${STATISTIK} Wer sieht am meisten fern?`, ['Menschen über 60.', 'Jugendliche.', 'Kleine Kinder.'],
          ['Who watches the most television?', 'Кто смотрит телевизор больше всех?', 'Хто дивиться телевізор найбільше?', 'En çok kim televizyon izliyor?']),
        mc('Z1', 'Jugendliche', I.read, `${STATISTIK} Warum sitzen Jugendliche so wenig vor dem Fernseher?`, ['Sie schauen Serien lieber im Internet.', 'Sie interessieren sich nicht für Filme.', 'Sie besitzen kein Handy.'],
          ['Why do young people spend so little time in front of the television?', 'Почему подростки так мало сидят перед телевизором?', 'Чому підлітки так мало сидять перед телевізором?', 'Gençler neden televizyonun karşısında bu kadar az oturuyor?']),
        mc('Z1', 'jeder Dritte', I.read, `${STATISTIK} Was bedeutet „jeder Dritte“?`, ['Eine Person von drei.', 'Drei Personen von vier.', 'Die dritte Person auf der Liste.'],
          ['What does “jeder Dritte” mean?', 'Что означает «jeder Dritte»?', 'Що означає «jeder Dritte»?', '“jeder Dritte” ne demek?']),
        mc('Z1', 'Donnerstag', I.read, `${KINO} Was ist an den Donnerstagen besonders?`, ['Die Filme laufen in Originalsprache.', 'Der Eintritt ist frei.', 'Das Kino bleibt geschlossen.'],
          ['What is special about Thursdays?', 'Что особенного по четвергам?', 'Що особливого по четвергах?', 'Perşembe günlerinin özelliği ne?']),
        mc('Z1', 'Wie geht es dem Kino?', I.read, `${KINO} Wie geht es dem Kino heute?`, ['Es hat wieder viele Besucher.', 'Es muss bald schließen.', 'Es zeigt keine Filme mehr.'],
          ['How is the cinema doing today?', 'Как сегодня идут дела у кинотеатра?', 'Як сьогодні йдуть справи в кінотеатру?', 'Sinemanın bugünkü durumu nasıl?']),
        gap('Z1', 'täglich', I.word, 'Viele Menschen sehen ', ' mehrere Stunden fern, also jeden Tag.', 'täglich', ['selten', 'nie'],
          ['Many people watch television for several hours daily, that is, every day.', 'Многие люди ежедневно смотрят телевизор по несколько часов, то есть каждый день.', 'Багато людей щодня дивляться телевізор по кілька годин, тобто кожного дня.', 'Birçok insan her gün birkaç saat televizyon izliyor.'],
          ['daily', 'ежедневно', 'щоденно', 'günlük, her gün']),
      ],
    },
  ],
}

export default path
