import { I, gap, mc } from '../shared.mjs'

const SCHLAF = 'Ratgeber: „Viele Menschen schlafen schlecht, weil sie abends zu lange auf einen Bildschirm schauen. Das Licht des Bildschirms hält das Gehirn wach. Der Fernseher und das Handy sollten deshalb eine Stunde vor dem Schlafen ausgeschaltet werden. Besser ist ein Buch oder ruhige Musik. Auch ein kurzer Spaziergang am Abend kann helfen.“'
const BETRIEB = 'Aushang in der Firma: „Liebe Kolleginnen und Kollegen, ab Mai bietet die Firma in der Mittagspause einen Gymnastikkurs an. Eine Trainerin zeigt einfache Übungen für Nacken, Schultern und Rücken. Die Teilnahme ist freiwillig und kostenlos. Wer mitmachen möchte, trägt sich bitte bis Freitag in die Liste am Empfang ein.“'

/** B1.1 · Pfad 3 · Gesund bleiben – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'vorbeugen', I.choose, 'Wer sich regelmäßig bewegt und gesund isst, kann vielen Krankheiten …', ['vorbeugen', 'abnehmen', 'verzichten'],
      ['If you exercise regularly and eat healthily, you can … many illnesses.', 'Тот, кто регулярно двигается и правильно питается, может … многие болезни.', 'Той, хто регулярно рухається і здорово харчується, може … багатьом хворобам.', 'Düzenli hareket eden ve sağlıklı beslenen kişi birçok hastalığı …']),
    mc('W2', 'beugen', I.choose, 'Der Arzt sagt: „Beugen Sie bitte das rechte Knie.“ Was soll man tun?', ['Das Bein im Knie krumm machen.', 'Das Bein ganz gerade machen.', 'Das Bein nach oben heben.'],
      ['The doctor says: “Please bend your right knee.” What are you supposed to do?', 'Врач говорит: «Согните, пожалуйста, правое колено.» Что нужно сделать?', 'Лікар каже: «Зігніть, будь ласка, праве коліно.» Що треба зробити?', 'Doktor şöyle diyor: “Lütfen sağ dizinizi bükün.” Ne yapmak gerekir?']),
    mc('G1', 'müssen … werden', I.choose, 'Die Tabletten … immer mit einem großen Glas Wasser genommen werden.', ['müssen', 'muss', 'müsst'],
      ['The tablets must always be taken with a large glass of water.', 'Таблетки всегда нужно принимать, запивая большим стаканом воды.', 'Таблетки завжди треба приймати, запиваючи великою склянкою води.', 'Tabletler her zaman büyük bir bardak suyla alınmalıdır.']),
    mc('G1', 'darf nicht … werden', I.choose, 'In der Sauna … nicht gegessen werden. Das ist dort verboten.', ['darf', 'will', 'hat'],
      ['Eating is not allowed in the sauna. It is forbidden there.', 'В сауне нельзя есть. Там это запрещено.', 'У сауні не можна їсти. Там це заборонено.', 'Saunada yemek yenmez. Orada bu yasaktır.'], { c: 'p3_passiv_modal2' }),
    mc('G2', 'der Behandlung', I.choose, 'Die Dauer … Behandlung hängt von der Verletzung ab.', ['der', 'des', 'dem'],
      ['The length of the treatment depends on the injury.', 'Продолжительность лечения зависит от травмы.', 'Тривалість лікування залежить від травми.', 'Tedavinin süresi yaralanmaya bağlıdır.']),
    mc('G3', 'meines', I.choose, 'Ich habe leider die Telefonnummer … Zahnarztes verloren.', ['meines', 'meiner', 'meinem'],
      ['Unfortunately I have lost my dentist’s telephone number.', 'К сожалению, я потерял номер телефона своего стоматолога.', 'На жаль, я загубив номер телефону свого стоматолога.', 'Ne yazık ki diş hekimimin telefon numarasını kaybettim.']),
    mc('K1', 'nach Erfahrungen fragen', I.situation, 'Du möchtest wissen, ob jemand im Kurs Erfahrung mit Yoga hat. Was fragst du?', ['Hat jemand von euch schon mal Yoga gemacht?', 'Ich würde an eurer Stelle Yoga machen.', 'Yoga soll wirklich helfen.'],
      ['You want to know whether anyone on the course has experience of yoga. What do you ask?', 'Вы хотите узнать, есть ли у кого-то в группе опыт занятий йогой. Что вы спросите?', 'Ви хочете дізнатися, чи має хтось у групі досвід занять йогою. Що ви спитаєте?', 'Kursta yoga deneyimi olan biri var mı, öğrenmek istiyorsunuz. Ne sorarsınız?']),
    mc('K2', 'Es ist am besten, wenn …', I.react, '„Mein Nacken tut seit Tagen weh. Was soll ich nur machen?“', ['Es ist am besten, wenn du zum Arzt gehst.', 'Kannst du mir einen Rat geben?', 'Darum werde ich mich kümmern.'],
      ['“My neck has been hurting for days. What on earth should I do?”', '«У меня уже несколько дней болит шея. Что же мне делать?»', '«У мене вже кілька днів болить шия. Що ж мені робити?»', '“Ensem günlerdir ağrıyor. Ne yapsam ki?”']),
    mc('K3', 'drei Viertel', I.choose, 'Fünfzehn von zwanzig Kursteilnehmern trinken morgens Kaffee. Das sind …', ['drei Viertel.', 'ein Drittel.', 'die Hälfte.'],
      ['Fifteen out of twenty course participants drink coffee in the morning. That is …', 'Пятнадцать из двадцати участников курса пьют утром кофе. Это …', 'П’ятнадцять із двадцяти учасників курсу п’ють уранці каву. Це …', 'Yirmi kursiyerden on beşi sabahları kahve içiyor. Bu …']),
    mc('K4', 'auf Krankmeldung reagieren', I.react, '„Guten Morgen, hier ist Ivana Kraus. Ich habe Grippe und kann heute nicht arbeiten.“', ['Oh, das tut mir leid. Werden Sie erst mal wieder gesund!', 'Wie schön! Dann bis gleich im Büro.', 'Was würden Sie mir empfehlen?'],
      ['“Good morning, this is Ivana Kraus. I have flu and cannot work today.”', '«Доброе утро, это Ivana Kraus. У меня грипп, и я не могу сегодня работать.»', '«Доброго ранку, це Ivana Kraus. У мене грип, і я не можу сьогодні працювати.»', '“Günaydın, ben Ivana Kraus. Grip oldum ve bugün çalışamıyorum.”']),
    mc('Z1', 'Ursache', I.read, `${SCHLAF} Warum schlafen viele Menschen schlecht?`, ['Weil sie abends zu lange auf einen Bildschirm schauen.', 'Weil sie abends zu viel lesen.', 'Weil sie zu oft spazieren gehen.'],
      ['Why do many people sleep badly?', 'Почему многие люди плохо спят?', 'Чому багато людей погано сплять?', 'Birçok insan neden kötü uyuyor?']),
    gap('K5', 'Wären Sie so nett …?', I.word, 'Wären Sie vielleicht so ', ' und bringen die Briefe heute noch zur Post?', 'nett', ['gern', 'dringend'],
      ['Would you perhaps be so kind as to take the letters to the post office today?', 'Не будете ли вы так любезны отнести письма на почту ещё сегодня?', 'Чи не будете ви такі ласкаві віднести листи на пошту ще сьогодні?', 'Zahmet olmazsa mektupları bugün postaya götürür müsünüz?'],
      ['kind', 'любезны', 'ласкаві', 'nazik']),
    gap('G3', 'unserer', I.possessive, 'Das ist das Büro ', ' Chefin. Bitte klopfen Sie vorher an.', 'unserer', ['unseres', 'unserem'],
      ['That is our boss’s office. Please knock first.', 'Это кабинет нашей начальницы. Пожалуйста, сначала постучите.', 'Це кабінет нашої начальниці. Будь ласка, спочатку постукайте.', 'Burası müdiremizin ofisi. Lütfen önce kapıyı çalın.'], 'unser'),
  ],
  size: 13,
  test: [
    mc('W1', 'sich erholen', I.choose, 'Nach der Grippe braucht der Körper Zeit. Er muss sich erst wieder …', ['erholen', 'verzichten', 'vorbeugen'],
      ['After flu the body needs time. It first has to …', 'После гриппа организму нужно время. Сначала он должен …', 'Після грипу організму потрібен час. Спочатку він має …', 'Gripten sonra vücudun zamana ihtiyacı vardır. Önce yeniden …']),
    mc('W2', 'Gelenk', I.choose, 'Welches Körperteil ist ein Gelenk?', ['das Knie', 'der Bauch', 'der Rücken'],
      ['Which part of the body is a joint?', 'Какая часть тела является суставом?', 'Яка частина тіла є суглобом?', 'Hangi vücut bölümü bir eklemdir?']),
    mc('G1', 'werden am Ende', I.choose, 'Der Verband am Arm muss alle zwei Tage gewechselt …', ['werden', 'geworden', 'wurde'],
      ['The bandage on the arm must be changed every two days.', 'Повязку на руке нужно менять каждые два дня.', 'Пов’язку на руці треба міняти кожні два дні.', 'Koldaki sargı iki günde bir değiştirilmelidir.']),
    mc('G1', 'Aktiv → Passiv', I.sentence, 'Man kann die Übungen auch zu Hause machen.', ['Die Übungen können auch zu Hause gemacht werden.', 'Die Übungen kann auch zu Hause gemacht werden.', 'Die Übungen können auch zu Hause machen werden.'],
      ['You can also do the exercises at home.', 'Упражнения можно делать и дома.', 'Вправи можна робити й удома.', 'Egzersizler evde de yapılabilir.']),
    mc('G1', 'darf nicht … werden', I.choose, 'Was bedeutet „Im Krankenhaus darf nicht geraucht werden.“?', ['Rauchen ist dort verboten.', 'Rauchen ist dort möglich.', 'Rauchen wird dort empfohlen.'],
      ['What does “Im Krankenhaus darf nicht geraucht werden.” mean?', 'Что означает «Im Krankenhaus darf nicht geraucht werden.»?', 'Що означає «Im Krankenhaus darf nicht geraucht werden.»?', '“Im Krankenhaus darf nicht geraucht werden.” ne demek?'], { c: 'p3_passiv_modal2' }),
    mc('G1', 'Frage im Passiv', I.choose, '… der Fuß nach dem Unfall geröntgt werden?', ['Muss', 'Müssen', 'Musst'],
      ['Does the foot have to be X-rayed after the accident?', 'Нужно ли после аварии делать рентген стопы?', 'Чи треба після аварії робити рентген стопи?', 'Kazadan sonra ayağın röntgeninin çekilmesi gerekiyor mu?'], { c: 'p3_passiv_modal2' }),
    mc('G2', 'der Tabletten', I.choose, 'Die Farbe … Tabletten ist egal, wichtig ist nur die Wirkung.', ['der', 'des', 'den'],
      ['The colour of the tablets does not matter; only the effect is important.', 'Цвет таблеток не важен, важно только действие.', 'Колір таблеток не важливий, важлива лише дія.', 'Tabletlerin rengi önemli değil, önemli olan yalnızca etkisi.']),
    mc('G2', 'des Problems', I.choose, 'Die Ursache … ist meistens zu viel Stress bei der Arbeit.', ['des Problems', 'des Problem', 'der Problems'],
      ['The cause of the problem is usually too much stress at work.', 'Причина проблемы – чаще всего слишком большой стресс на работе.', 'Причина проблеми – найчастіше забагато стресу на роботі.', 'Sorunun nedeni çoğunlukla işteki aşırı stres.']),
    mc('G3', 'unseres', I.choose, 'Die Übungen … Trainers sind anstrengend, aber sie helfen wirklich.', ['unseres', 'unserer', 'unserem'],
      ['Our trainer’s exercises are strenuous, but they really help.', 'Упражнения нашего тренера тяжёлые, но они действительно помогают.', 'Вправи нашого тренера важкі, але вони справді допомагають.', 'Antrenörümüzün egzersizleri yorucu ama gerçekten işe yarıyor.']),
    mc('G3', 'einer', I.choose, 'Das ist die Meinung … Expertin, die seit zwanzig Jahren Patienten berät.', ['einer', 'eines', 'einem'],
      ['That is the opinion of an expert who has been advising patients for twenty years.', 'Это мнение эксперта, которая уже двадцать лет консультирует пациентов.', 'Це думка експертки, яка вже двадцять років консультує пацієнтів.', 'Bu, yirmi yıldır hastalara danışmanlık yapan bir uzmanın görüşü.']),
    mc('K1', 'um Rat bitten', I.choose, 'Mit welchem Satz bittet man um einen Rat?', ['Was können Sie mir raten?', 'Ich empfehle Ihnen mehr Bewegung.', 'Sie sollten weniger arbeiten.'],
      ['Which sentence do you use to ask for advice?', 'Каким предложением просят совета?', 'Яким реченням просять поради?', 'Hangi cümleyle tavsiye istenir?']),
    mc('K2', 'Dagegen musst du etwas tun!', I.situation, 'Dein Kollege hat seit Tagen starke Kopfschmerzen, geht aber nicht zum Arzt. Was sagst du?', ['Dagegen musst du unbedingt etwas tun!', 'Kannst du mir etwas empfehlen?', 'Hat jemand von euch ein Mittel?'],
      ['Your colleague has had bad headaches for days but does not go to the doctor. What do you say?', 'У вашего коллеги уже несколько дней сильно болит голова, но он не идёт к врачу. Что вы скажете?', 'У вашого колеги вже кілька днів сильно болить голова, але він не йде до лікаря. Що ви скажете?', 'İş arkadaşınızın günlerdir şiddetli baş ağrısı var ama doktora gitmiyor. Ne dersiniz?']),
    mc('K3', 'zwei Drittel', I.choose, 'Was bedeutet „Zwei Drittel der Deutschen bewegen sich zu wenig.“?', ['Etwa 67 Prozent bewegen sich zu wenig.', 'Etwa 25 Prozent bewegen sich zu wenig.', 'Genau die Hälfte bewegt sich zu wenig.'],
      ['What does “Zwei Drittel der Deutschen bewegen sich zu wenig.” mean?', 'Что означает «Zwei Drittel der Deutschen bewegen sich zu wenig.»?', 'Що означає «Zwei Drittel der Deutschen bewegen sich zu wenig.»?', '“Zwei Drittel der Deutschen bewegen sich zu wenig.” ne demek?']),
    mc('K3', 'nur wenige', I.choose, 'Drei von dreißig Personen rauchen. Was passt?', ['Nur wenige rauchen.', 'Die meisten rauchen.', 'Die Hälfte raucht.'],
      ['Three out of thirty people smoke. What fits?', 'Три человека из тридцати курят. Что подходит?', 'Три людини з тридцяти курять. Що підходить?', 'Otuz kişiden üçü sigara içiyor. Hangisi uygun?']),
    mc('K4', 'krankgeschrieben', I.situation, 'Du bist krank und warst schon beim Arzt. Was sagst du deinem Chef am Telefon?', ['Der Arzt hat mich bis Mittwoch krankgeschrieben.', 'Ich wünsche Ihnen gute Besserung.', 'Das mache ich doch gern.'],
      ['You are ill and have already been to the doctor. What do you tell your boss on the phone?', 'Вы заболели и уже были у врача. Что вы скажете начальнику по телефону?', 'Ви захворіли і вже були в лікаря. Що ви скажете начальникові телефоном?', 'Hastasınız ve doktora gittiniz. Patronunuza telefonda ne dersiniz?']),
    mc('K5', 'auf eine Bitte reagieren', I.react, '„Wären Sie so nett und kontrollieren heute Abend die Kasse?“', ['Ja, natürlich. Darum kümmere ich mich.', 'Was würden Sie mir empfehlen?', 'Gute Besserung!'],
      ['“Would you be so kind as to check the till this evening?”', '«Будьте добры, проверьте сегодня вечером кассу.»', '«Будьте ласкаві, перевірте сьогодні ввечері касу.»', '“Zahmet olmazsa bu akşam kasayı kontrol eder misiniz?”']),
    mc('Z1', 'Angebot der Firma', I.read, `${BETRIEB} Was bietet die Firma an?`, ['Einen Gymnastikkurs in der Mittagspause.', 'Einen Yogakurs am Wochenende.', 'Einen Besuch beim Arzt.'],
      ['What is the company offering?', 'Что предлагает фирма?', 'Що пропонує фірма?', 'Şirket ne sunuyor?']),
    mc('Z1', 'freiwillig', I.read, `${BETRIEB} Müssen alle Mitarbeiter teilnehmen?`, ['Nein, die Teilnahme ist freiwillig.', 'Ja, alle müssen mitmachen.', 'Nur die Kollegen am Empfang.'],
      ['Do all employees have to take part?', 'Должны ли участвовать все сотрудники?', 'Чи мають брати участь усі працівники?', 'Bütün çalışanların katılması gerekiyor mu?']),
    gap('W1', 'Vorsorge', I.word, 'Ich möchte gesund bleiben. Deshalb gehe ich einmal im Jahr zur ', '.', 'Vorsorge', ['Ursache', 'Ernährung'],
      ['I want to stay healthy. That is why I go for a preventive check-up once a year.', 'Я хочу оставаться здоровым. Поэтому раз в год я хожу на профилактический осмотр.', 'Я хочу залишатися здоровим. Тому раз на рік я ходжу на профілактичний огляд.', 'Sağlıklı kalmak istiyorum. Bu yüzden yılda bir kez koruyucu muayeneye gidiyorum.'],
      ['preventive check-up', 'профилактический осмотр', 'профілактичний огляд', 'koruyucu muayene']),
    gap('W2', 'Rücken', I.word, 'Beim Heben von schweren Kisten sollte der ', ' möglichst gerade bleiben.', 'Rücken', ['Bauch', 'Muskel'],
      ['When lifting heavy boxes the back should stay as straight as possible.', 'При подъёме тяжёлых ящиков спина должна оставаться как можно более прямой.', 'Під час піднімання важких ящиків спина має залишатися якомога рівнішою.', 'Ağır kutuları kaldırırken sırt olabildiğince düz kalmalıdır.'],
      ['back', 'спина', 'спина', 'sırt']),
    gap('G1', 'abgegeben werden', I.participle, 'Das Rezept muss in der Apotheke ', ' werden.', 'abgegeben', ['abgeben', 'abgibt'],
      ['The prescription must be handed in at the pharmacy.', 'Рецепт нужно сдать в аптеке.', 'Рецепт треба віддати в аптеці.', 'Reçete eczaneye teslim edilmelidir.'], 'abgeben'),
    gap('G2', 'der Praxis', I.article, 'Die Öffnungszeiten ', ' Praxis stehen auf dem Schild an der Tür.', 'der', ['des', 'dem'],
      ['The opening hours of the surgery are on the sign on the door.', 'Часы работы кабинета врача указаны на табличке на двери.', 'Години роботи кабінету лікаря вказано на табличці на дверях.', 'Muayenehanenin çalışma saatleri kapıdaki tabelada yazıyor.'], 'die Praxis'),
    gap('G2', 'des Körpers', I.ending, 'Die Trainerin erklärt uns die wichtigsten Muskeln des ', '.', 'Körpers', ['Körper', 'Körpern'],
      ['The trainer explains the most important muscles of the body to us.', 'Тренер объясняет нам самые важные мышцы тела.', 'Тренерка пояснює нам найважливіші м’язи тіла.', 'Antrenör bize vücudun en önemli kaslarını anlatıyor.'], 'der Körper'),
    gap('G3', 'einer', I.article, 'Der Rücken ', ' Kollegin von mir tut schon seit Monaten weh.', 'einer', ['eines', 'einem'],
      ['The back of a colleague of mine has been hurting for months.', 'У одной моей коллеги спина болит уже несколько месяцев.', 'В однієї моєї колеги спина болить уже кілька місяців.', 'Bir iş arkadaşımın sırtı aylardır ağrıyor.'], 'eine'),
    gap('G3', 'meiner (Plural)', I.possessive, 'Die Gesundheit ', ' Kinder ist mir wichtiger als alles andere.', 'meiner', ['meines', 'meinen'],
      ['My children’s health is more important to me than anything else.', 'Здоровье моих детей для меня важнее всего остального.', 'Здоров’я моїх дітей для мене важливіше за все інше.', 'Çocuklarımın sağlığı benim için her şeyden önemli.'], 'mein'),
    gap('K1', 'Rat', I.word, 'Können Sie mir bitte einen ', ' geben? Ich weiß wirklich nicht mehr weiter.', 'Rat', ['Raum', 'Rest'],
      ['Could you please give me some advice? I really do not know what to do any more.', 'Не могли бы вы дать мне совет? Я уже действительно не знаю, что делать.', 'Чи не могли б ви дати мені пораду? Я вже справді не знаю, що робити.', 'Bana bir tavsiye verebilir misiniz lütfen? Gerçekten ne yapacağımı bilmiyorum.'],
      ['piece of advice', 'совет', 'порада', 'tavsiye']),
    gap('K2', 'empfehle', I.verb, 'Ich ', ' Ihnen dieses Buch über gesunde Ernährung. Es hat mir sehr geholfen.', 'empfehle', ['empfiehlt', 'empfehlen'],
      ['I recommend this book about healthy eating to you. It helped me a lot.', 'Я рекомендую вам эту книгу о здоровом питании. Она мне очень помогла.', 'Я рекомендую вам цю книжку про здорове харчування. Вона мені дуже допомогла.', 'Size sağlıklı beslenmeyle ilgili bu kitabı öneririm. Bana çok yardımcı oldu.'], 'empfehlen'),
    gap('K3', 'die Hälfte', I.word, 'Die ', ' der Teilnehmer, also 50 Prozent, macht nie Sport.', 'Hälfte', ['Viertel', 'Drittel'],
      ['Half of the participants, that is 50 per cent, never do any sport.', 'Половина участников, то есть 50 процентов, никогда не занимается спортом.', 'Половина учасників, тобто 50 відсотків, ніколи не займається спортом.', 'Katılımcıların yarısı, yani yüzde 50’si, hiç spor yapmıyor.'], 'Hälfte / Drittel / Viertel'),
    gap('K4', 'Gute Besserung', I.word, 'Gute ', '! Ich hoffe, es geht Ihnen bald wieder besser.', 'Besserung', ['Ernährung', 'Bewegung'],
      ['Get well soon! I hope you will feel better again soon.', 'Выздоравливайте! Надеюсь, вам скоро станет лучше.', 'Одужуйте! Сподіваюся, вам скоро стане краще.', 'Geçmiş olsun! Umarım yakında kendinizi daha iyi hissedersiniz.'],
      ['recovery (get well soon)', 'выздоровление', 'одужання', 'iyileşme (geçmiş olsun)']),
    gap('K5', 'sich kümmern um', I.word, 'Die Briefe sind noch nicht fertig? Kein Problem, ', ' kümmere ich mich.', 'darum', ['daran', 'dafür'],
      ['The letters are not finished yet? No problem, I will take care of that.', 'Письма ещё не готовы? Не проблема, я этим займусь.', 'Листи ще не готові? Не проблема, я цим займуся.', 'Mektuplar henüz hazır değil mi? Sorun değil, onunla ben ilgilenirim.'], 'sich kümmern um'),
  ],
}

export default check
