import { I, gap, mc } from '../shared.mjs'

const WERDEN_K2 = 'werden (Konjunktiv II)'
const SEIN_K2 = 'sein (Konjunktiv II)'
const TANDEM = 'Anzeige: „Sprachtandem gesucht! Ich heiße Daniel, bin 28 und komme aus Leipzig. Seit einem Jahr lerne ich Türkisch, weil meine Freundin aus Izmir kommt. Ich suche jemanden, der Türkisch als Muttersprache spricht und sein Deutsch verbessern möchte. Wir könnten uns einmal pro Woche in einem Café treffen: eine halbe Stunde Deutsch, eine halbe Stunde Türkisch.“'
const FARID = 'Farid erzählt: „Mein Großvater sprach vier Sprachen, obwohl er nie eine Schule besucht hat. Er war Händler und musste sich mit vielen Menschen verständigen. Ich bin in Deutschland geboren und spreche leider nur Deutsch und ein wenig Persisch. Wenn mein Großvater noch leben würde, könnte er mir so viel beibringen. Deshalb mache ich jetzt einen Persischkurs.“'

/** B1.1 · Pfad 4 · Sprachen – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Akzent', I.choose, 'Man hört sofort, dass er aus Frankreich kommt. Er hat einen starken …', ['Akzent', 'Wortschatz', 'Sprachkurs'],
      ['You can hear at once that he comes from France. He has a strong …', 'Сразу слышно, что он из Франции. У него сильный …', 'Одразу чути, що він із Франції. У нього сильний …', 'Fransa’dan geldiği hemen duyuluyor. Güçlü bir … var.']),
    mc('G1', 'würde', I.choose, 'An Ihrer Stelle … ich zuerst einen Einstufungstest machen.', ['würde', 'wurde', 'wäre'],
      ['If I were you, I would take a placement test first.', 'На вашем месте я бы сначала прошёл тест на определение уровня.', 'На вашому місці я б спочатку пройшов тест на визначення рівня.', 'Sizin yerinizde olsam önce bir seviye belirleme sınavına girerdim.']),
    mc('G1', 'könnten', I.choose, 'Wenn wir früher Feierabend hätten, … wir zusammen den Abendkurs besuchen.', ['könnten', 'konnten', 'können'],
      ['If we finished work earlier, we could attend the evening course together.', 'Если бы мы раньше заканчивали работу, мы могли бы вместе ходить на вечерний курс.', 'Якби ми раніше закінчували роботу, ми могли б разом ходити на вечірній курс.', 'İşten daha erken çıksak akşam kursuna birlikte gidebilirdik.'], { c: 'p4_konj2_modal' }),
    mc('G2', 'irreale Bedingung bilden', I.sentence, 'Anna hat wenig Geld. Sie macht keinen teuren Sprachkurs.', ['Wenn Anna mehr Geld hätte, würde sie einen teuren Sprachkurs machen.', 'Wenn Anna mehr Geld hat, würde sie einen teuren Sprachkurs gemacht.', 'Wenn Anna hätte mehr Geld, sie würde einen teuren Sprachkurs machen.'],
      ['Anna has little money. She is not doing an expensive language course.', 'У Anna мало денег. Она не ходит на дорогой языковой курс.', 'У Anna мало грошей. Вона не ходить на дорогий мовний курс.', 'Anna’nın az parası var. Pahalı bir dil kursuna gitmiyor.']),
    mc('G3', 'irreal erkennen', I.choose, 'Welcher Satz beschreibt etwas, was nicht wirklich ist?', ['Wenn ich ein Vogel wäre, würde ich nach Süden fliegen.', 'Wenn ich Zeit habe, komme ich mit.', 'Wenn es regnet, nehme ich den Bus.'],
      ['Which sentence describes something that is not real?', 'Какое предложение описывает то, чего на самом деле нет?', 'Яке речення описує те, чого насправді немає?', 'Hangi cümle gerçek olmayan bir şeyi anlatıyor?']),
    mc('G4', 'wegen eines Staus', I.choose, 'Wegen … Staus kam der Lehrer heute zwanzig Minuten zu spät.', ['eines', 'einer', 'einen'],
      ['Because of a traffic jam the teacher arrived twenty minutes late today.', 'Из-за пробки учитель сегодня опоздал на двадцать минут.', 'Через затор учитель сьогодні запізнився на двадцять хвилин.', 'Bir trafik sıkışıklığı yüzünden öğretmen bugün yirmi dakika geç geldi.']),
    mc('K1', 'Wichtigkeit begründen', I.react, '„Warum machst du denn jeden Abend Grammatikübungen?“', ['Weil es für mich wichtig ist, dass ich keine Fehler mache.', 'Wie war bitte Ihr Name?', 'Ich bin zweisprachig aufgewachsen.'],
      ['“Why on earth do you do grammar exercises every evening?”', '«Зачем ты каждый вечер делаешь упражнения по грамматике?»', '«Навіщо ти щовечора робиш вправи з граматики?»', '“Neden her akşam dil bilgisi alıştırması yapıyorsun?”']),
    mc('K2', 'Können Sie mir sagen, wo …?', I.choose, 'Entschuldigung, können Sie mir sagen, … ich das Formular abgeben muss?', ['wo', 'wer', 'weil'],
      ['Excuse me, can you tell me where I have to hand in the form?', 'Извините, вы не подскажете, куда нужно сдать формуляр?', 'Вибачте, ви не підкажете, куди треба здати формуляр?', 'Affedersiniz, formu nereye teslim etmem gerektiğini söyleyebilir misiniz?']),
    mc('K4', 'um Wiederholung bitten', I.situation, 'Du hast die Telefonnummer nicht verstanden. Was sagst du?', ['Könnten Sie die Nummer bitte wiederholen?', 'Was meinen Sie mit „Nummer“?', 'Darum mache ich einen Kurs.'],
      ['You did not catch the telephone number. What do you say?', 'Вы не расслышали номер телефона. Что вы скажете?', 'Ви не розчули номер телефону. Що ви скажете?', 'Telefon numarasını anlamadınız. Ne dersiniz?']),
    mc('K5', 'Muttersprache', I.choose, 'Ich bin in Kiew geboren und aufgewachsen. Meine … ist Ukrainisch.', ['Muttersprache', 'Fremdsprache', 'Aussprache'],
      ['I was born and grew up in Kyiv. My … is Ukrainian.', 'Я родился и вырос в Киеве. Мой … – украинский.', 'Я народився і виріс у Києві. Моя … – українська.', 'Kiev’de doğdum ve büyüdüm. Benim … Ukraynaca.']),
    mc('Z1', 'Was sucht Daniel?', I.read, `${TANDEM} Was sucht Daniel?`, ['Eine Person, mit der er Türkisch üben kann.', 'Einen Türkischkurs in Izmir.', 'Ein Café in Leipzig.'],
      ['What is Daniel looking for?', 'Что ищет Daniel?', 'Що шукає Daniel?', 'Daniel ne arıyor?']),
    gap('K3', 'Was bedeutet …?', I.verb, 'Entschuldigung, was ', ' dieses Wort? Ich habe es noch nie gehört.', 'bedeutet', ['bedeuten', 'bedeutest'],
      ['Excuse me, what does this word mean? I have never heard it before.', 'Извините, что значит это слово? Я его ещё никогда не слышал.', 'Вибачте, що означає це слово? Я його ще ніколи не чув.', 'Affedersiniz, bu kelime ne demek? Daha önce hiç duymadım.'], 'bedeuten'),
    gap('G2', 'Wenn ich du wäre', I.verb, 'Wenn ich du ', ', würde ich die Prüfung erst im Herbst machen.', 'wäre', ['war', 'hätte'],
      ['If I were you, I would not take the exam until the autumn.', 'На твоём месте я бы сдавал экзамен только осенью.', 'На твоєму місці я б складав іспит лише восени.', 'Senin yerinde olsam sınava ancak sonbaharda girerdim.'], SEIN_K2),
  ],
  size: 13,
  test: [
    mc('W1', 'Übersetzung', I.choose, 'Auf Deutsch sagt man „Haus“, auf Englisch „house“. Das ist die englische … von dem Wort.', ['Übersetzung', 'Aussprache', 'Schrift'],
      ['In German you say “Haus”, in English “house”. That is the English … of the word.', 'По-немецки говорят «Haus», по-английски «house». Это английский … слова.', 'Німецькою кажуть «Haus», англійською «house». Це англійський … слова.', 'Almancada “Haus”, İngilizcede “house” denir. Bu, kelimenin İngilizce …']),
    mc('G1', 'würden', I.choose, 'Wir … gern öfter ins Theater gehen, aber die Karten sind einfach zu teuer.', ['würden', 'wurden', 'werden'],
      ['We would like to go to the theatre more often, but the tickets are simply too expensive.', 'Мы бы с удовольствием чаще ходили в театр, но билеты просто слишком дорогие.', 'Ми б охоче частіше ходили до театру, але квитки просто надто дорогі.', 'Tiyatroya daha sık gitmek isterdik ama biletler çok pahalı.']),
    mc('G1', 'würdest', I.choose, 'Wenn du mehr lesen …, hättest du bald einen größeren Wortschatz.', ['würdest', 'würde', 'wurdest'],
      ['If you read more, you would soon have a larger vocabulary.', 'Если бы ты больше читал, у тебя скоро был бы больший словарный запас.', 'Якби ти більше читав, ти б невдовзі мав більший словниковий запас.', 'Daha çok okusan kısa sürede daha geniş bir kelime dağarcığın olurdu.']),
    mc('G1', 'müsste', I.choose, 'Wenn ich nicht arbeiten …, würde ich den ganzen Tag Sprachen lernen.', ['müsste', 'musste', 'müssen'],
      ['If I did not have to work, I would learn languages all day.', 'Если бы мне не нужно было работать, я бы целыми днями учил языки.', 'Якби мені не треба було працювати, я б цілими днями вчив мови.', 'Çalışmak zorunda olmasam bütün gün dil öğrenirdim.'], { c: 'p4_konj2_modal' }),
    mc('G2', 'leben würden', I.choose, 'Wenn wir in Spanien leben …, könnten unsere Kinder perfekt Spanisch.', ['würden', 'werden', 'wurden'],
      ['If we lived in Spain, our children would speak perfect Spanish.', 'Если бы мы жили в Испании, наши дети в совершенстве знали бы испанский.', 'Якби ми жили в Іспанії, наші діти досконало знали б іспанську.', 'İspanya’da yaşasak çocuklarımız mükemmel İspanyolca bilirdi.']),
    mc('G2', 'Wortstellung', I.sentence, 'Tom ist krank. Deshalb kommt er nicht zum Kurs.', ['Wenn Tom nicht krank wäre, würde er zum Kurs kommen.', 'Wenn Tom nicht krank wäre, er würde zum Kurs kommen.', 'Wenn Tom nicht wäre krank, würde er zum Kurs kommen.'],
      ['Tom is ill. That is why he is not coming to the course.', 'Tom болен. Поэтому он не придёт на курс.', 'Tom хворий. Тому він не прийде на курс.', 'Tom hasta. Bu yüzden kursa gelmiyor.']),
    mc('G2', 'wenn', I.choose, 'Was würdest du sagen, … dein Chef plötzlich Chinesisch mit dir sprechen würde?', ['wenn', 'dann', 'ob'],
      ['What would you say if your boss suddenly spoke Chinese to you?', 'Что бы ты сказал, если бы начальник вдруг заговорил с тобой по-китайски?', 'Що б ти сказав, якби начальник раптом заговорив із тобою китайською?', 'Patronun birden seninle Çince konuşsa ne derdin?'], { c: 'p4_irreal2' }),
    mc('G3', 'reale Bedingung verstehen', I.choose, '„Wenn ich Zeit habe, helfe ich dir beim Lernen.“ Was bedeutet das?', ['Vielleicht helfe ich dir wirklich.', 'Ich helfe dir ganz sicher nicht.', 'Ich habe dir gestern geholfen.'],
      ['“If I have time, I will help you study.” What does that mean?', '«Если у меня будет время, я помогу тебе с учёбой.» Что это значит?', '«Якщо я матиму час, я допоможу тобі з навчанням.» Що це означає?', '“Vaktim olursa ders çalışmana yardım ederim.” Bu ne demek?']),
    mc('G3', 'irreal: hätte', I.choose, 'Ich habe leider kein Geld dabei. Wenn ich Geld dabei …, würde ich dir das Wörterbuch kaufen.', ['hätte', 'habe', 'hatte'],
      ['Unfortunately I have no money on me. If I had money on me, I would buy you the dictionary.', 'К сожалению, у меня нет с собой денег. Если бы были, я бы купил тебе словарь.', 'На жаль, я не маю при собі грошей. Якби мав, я б купив тобі словник.', 'Ne yazık ki yanımda para yok. Olsaydı sana sözlüğü alırdım.']),
    mc('G4', 'Wegen', I.choose, '… meiner Arbeit kann ich leider nur am Wochenende lernen.', ['Wegen', 'Weil', 'Deshalb'],
      ['Because of my work I can unfortunately only study at the weekend.', 'Из-за работы я, к сожалению, могу заниматься только по выходным.', 'Через роботу я, на жаль, можу вчитися лише на вихідних.', 'İşim yüzünden ne yazık ki yalnızca hafta sonu ders çalışabiliyorum.']),
    mc('G4', 'wegen der Prüfung', I.choose, 'Wegen … Prüfung in der nächsten Woche bin ich ziemlich nervös.', ['der', 'des', 'den'],
      ['Because of the exam next week I am rather nervous.', 'Из-за экзамена на следующей неделе я довольно сильно нервничаю.', 'Через іспит наступного тижня я досить сильно нервую.', 'Gelecek haftaki sınav yüzünden oldukça gerginim.']),
    mc('K1', 'Darum', I.choose, 'Ein großer Wortschatz ist mir wichtig. … lese ich jeden Tag die Zeitung.', ['Darum', 'Denn', 'Weil'],
      ['A large vocabulary is important to me. That is why I read the newspaper every day.', 'Для меня важен большой словарный запас. Поэтому я каждый день читаю газету.', 'Для мене важливий великий словниковий запас. Тому я щодня читаю газету.', 'Geniş bir kelime dağarcığı benim için önemli. Bu yüzden her gün gazete okuyorum.']),
    mc('K1', 'wichtig, weil …', I.choose, 'In welchem Satz wird begründet, warum etwas wichtig ist?', ['Das ist mir wichtig, weil ich im Beruf viel schreiben muss.', 'Könnten Sie das bitte wiederholen?', 'Meine Muttersprache ist Arabisch.'],
      ['Which sentence gives a reason why something is important?', 'В каком предложении объясняется, почему что-то важно?', 'У якому реченні пояснюється, чому щось важливо?', 'Hangi cümlede bir şeyin neden önemli olduğu açıklanıyor?']),
    mc('K2', 'ob', I.situation, 'Du möchtest höflich wissen, ob der Kurs noch freie Plätze hat. Was fragst du?', ['Können Sie mir sagen, ob es noch freie Plätze gibt?', 'Gibt es Plätze oder nicht?', 'Ich weiß, dass es keine Plätze gibt.'],
      ['You would like to know politely whether the course still has free places. What do you ask?', 'Вы хотите вежливо узнать, есть ли на курсе ещё свободные места. Что вы спросите?', 'Ви хочете ввічливо дізнатися, чи є на курсі ще вільні місця. Що ви спитаєте?', 'Kursta hâlâ boş yer olup olmadığını kibarca öğrenmek istiyorsunuz. Ne sorarsınız?']),
    mc('K3', 'Was bedeutet das?', I.situation, 'Dein Kollege sagt: „Das ist Jacke wie Hose.“ Du verstehst das nicht. Was fragst du?', ['Was bedeutet das?', 'Wie war bitte dein Name?', 'Deswegen lerne ich Deutsch.'],
      ['Your colleague says: “Das ist Jacke wie Hose.” You do not understand it. What do you ask?', 'Ваш коллега говорит: «Das ist Jacke wie Hose.» Вы этого не понимаете. Что вы спросите?', 'Ваш колега каже: «Das ist Jacke wie Hose.» Ви цього не розумієте. Що ви спитаєте?', 'İş arkadaşınız şöyle diyor: “Das ist Jacke wie Hose.” Bunu anlamıyorsunuz. Ne sorarsınız?']),
    mc('K4', 'wiederholen', I.choose, 'Entschuldigung, ich habe Sie nicht verstanden. Könnten Sie das bitte …?', ['wiederholen', 'bedeuten', 'meinen'],
      ['Sorry, I did not understand you. Could you … that, please?', 'Извините, я вас не понял. Не могли бы вы это …?', 'Вибачте, я вас не зрозумів. Чи не могли б ви це …?', 'Affedersiniz, sizi anlamadım. Bunu … misiniz lütfen?']),
    mc('K5', 'fließend', I.choose, 'Ich habe drei Jahre in Madrid gelebt. Deshalb spreche ich … Spanisch.', ['fließend', 'zweisprachig', 'schriftlich'],
      ['I lived in Madrid for three years. That is why I speak Spanish …', 'Я три года жил в Мадриде. Поэтому я … говорю по-испански.', 'Я три роки жив у Мадриді. Тому я … говорю іспанською.', 'Üç yıl Madrid’de yaşadım. Bu yüzden … İspanyolca konuşuyorum.']),
    mc('Z1', 'Großvater', I.read, `${FARID} Warum sprach Farids Großvater so viele Sprachen?`, ['Er brauchte sie für seinen Beruf als Händler.', 'Er hat sie in der Schule gelernt.', 'Er ist in Deutschland geboren.'],
      ['Why did Farid’s grandfather speak so many languages?', 'Почему дедушка Farid говорил на стольких языках?', 'Чому дідусь Farid говорив стількома мовами?', 'Farid’in dedesi neden bu kadar çok dil konuşuyordu?']),
    mc('Z1', 'Sprachtandem', I.read, `${TANDEM} Wie soll das Sprachtandem funktionieren?`, ['Jede Woche eine halbe Stunde Deutsch und eine halbe Stunde Türkisch.', 'Jeden Tag eine Stunde Türkisch am Telefon.', 'Ein Jahr lang nur Deutsch in einem Kurs.'],
      ['How is the language tandem supposed to work?', 'Как должен проходить языковой тандем?', 'Як має відбуватися мовний тандем?', 'Dil tandemi nasıl işleyecek?']),
    gap('W1', 'Aussprache', I.word, 'Seine ', ' ist sehr gut: Man versteht jedes Wort, das er auf Deutsch sagt.', 'Aussprache', ['Schrift', 'Übersetzung'],
      ['His pronunciation is very good: you understand every word he says in German.', 'У него очень хорошее произношение: понятно каждое слово, которое он говорит по-немецки.', 'У нього дуже добра вимова: зрозуміле кожне слово, яке він каже німецькою.', 'Telaffuzu çok iyi: Almanca söylediği her kelime anlaşılıyor.'],
      ['pronunciation', 'произношение', 'вимова', 'telaffuz']),
    gap('G1', 'wäre', I.verb, 'Es ', ' wirklich schön, wenn du mir bei der Übersetzung helfen könntest.', 'wäre', ['hätte', 'würde'],
      ['It would be really nice if you could help me with the translation.', 'Было бы очень хорошо, если бы ты смог помочь мне с переводом.', 'Було б дуже добре, якби ти зміг допомогти мені з перекладом.', 'Çeviride bana yardım edebilirsen gerçekten çok güzel olur.'], SEIN_K2),
    gap('G2', 'gewinnen würde', I.verb, 'Wenn ich im Lotto gewinnen ', ', würde ich ein ganzes Jahr lang reisen.', 'würde', ['werde', 'würdet'],
      ['If I won the lottery, I would travel for a whole year.', 'Если бы я выиграл в лотерею, я бы целый год путешествовал.', 'Якби я виграв у лотерею, я б цілий рік подорожував.', 'Lotoyu kazansam bütün bir yıl seyahat ederdim.'], WERDEN_K2),
    gap('G3', 'real: scheint', I.verb, 'Morgen ist Feiertag. Wenn die Sonne ', ', machen wir ein Picknick am See.', 'scheint', ['schiene', 'schien'],
      ['Tomorrow is a public holiday. If the sun shines, we will have a picnic by the lake.', 'Завтра праздник. Если будет светить солнце, мы устроим пикник у озера.', 'Завтра свято. Якщо світитиме сонце, ми влаштуємо пікнік біля озера.', 'Yarın resmî tatil. Güneş açarsa göl kenarında piknik yapacağız.'], 'scheinen'),
    gap('G4', 'wegen eines Fehlers', I.article, 'Wegen ', ' Fehlers im Computer konnte ich mich gestern nicht anmelden.', 'eines', ['einer', 'einen'],
      ['Because of an error in the computer I could not register yesterday.', 'Из-за ошибки в компьютере я вчера не смог записаться.', 'Через помилку в комп’ютері я вчора не зміг записатися.', 'Bilgisayardaki bir hata yüzünden dün kaydolamadım.'], 'ein'),
    gap('G4', 'wegen meiner Tochter', I.possessive, 'Warum warst du gestern nicht im Kurs? – Wegen ', ' Tochter. Sie war krank.', 'meiner', ['meines', 'meinen'],
      ['Why were you not in class yesterday? – Because of my daughter. She was ill.', 'Почему тебя вчера не было на курсе? – Из-за дочери. Она болела.', 'Чому тебе вчора не було на курсі? – Через доньку. Вона хворіла.', 'Dün neden kursta değildin? – Kızım yüzünden. Hastaydı.'], 'mein'),
    gap('K1', 'wichtig', I.word, 'Ich finde es sehr ', ', dass man im Kurs viel spricht. Nur so lernt man die Sprache richtig.', 'wichtig', ['wenig', 'weit'],
      ['I think it is very important that you speak a lot in class. That is the only way to learn the language properly.', 'Я считаю очень важным, чтобы на занятиях много говорили. Только так можно по-настоящему выучить язык.', 'Я вважаю дуже важливим, щоб на заняттях багато говорили. Тільки так можна по-справжньому вивчити мову.', 'Kursta çok konuşulmasını çok önemli buluyorum. Dil ancak böyle doğru dürüst öğrenilir.'],
      ['important', 'важно', 'важливо', 'önemli']),
    gap('K2', 'wann', I.qword, 'Wissen Sie, ', ' der Kurs am Montag anfängt? – Um 18 Uhr.', 'wann', ['wer', 'was'],
      ['Do you know when the course starts on Monday? – At 6 p.m.', 'Вы не знаете, когда курс начинается в понедельник? – В 18 часов.', 'Ви не знаєте, коли курс починається в понеділок? – О 18 годині.', 'Kursun pazartesi günü ne zaman başladığını biliyor musunuz? – Saat 18’de.'], 'wann / wer / was'),
    gap('K3', 'nicht verstanden', I.participle, 'Dieses Wort habe ich leider nicht ', '. Können Sie es mir bitte erklären?', 'verstanden', ['verstehen', 'versteht'],
      ['Unfortunately I did not understand this word. Can you explain it to me, please?', 'К сожалению, я не понял это слово. Не могли бы вы мне его объяснить?', 'На жаль, я не зрозумів цього слова. Чи не могли б ви мені його пояснити?', 'Ne yazık ki bu kelimeyi anlamadım. Bana açıklar mısınız lütfen?'], 'verstehen'),
    gap('K4', 'buchstabieren', I.word, 'Mein Nachname ist ziemlich lang und schwierig. Soll ich ihn ', '?', 'buchstabieren', ['bedeuten', 'besuchen'],
      ['My surname is rather long and difficult. Shall I spell it?', 'У меня довольно длинная и сложная фамилия. Произнести её по буквам?', 'У мене досить довге і складне прізвище. Сказати його по літерах?', 'Soyadım oldukça uzun ve zor. Harf harf söyleyeyim mi?'],
      ['spell', 'произнести по буквам', 'сказати по літерах', 'harf harf söylemek']),
    gap('K5', 'zweisprachig', I.word, 'Ich bin mit Deutsch und Griechisch aufgewachsen. Ich bin also ', '.', 'zweisprachig', ['fließend', 'schriftlich'],
      ['I grew up with German and Greek. So I am bilingual.', 'Я вырос с немецким и греческим. То есть я двуязычный.', 'Я виріс із німецькою та грецькою. Тобто я двомовний.', 'Almanca ve Yunancayla büyüdüm. Yani iki dilliyim.'],
      ['bilingual', 'двуязычный', 'двомовний', 'iki dilli']),
  ],
}

export default check
