import { I, gap, mc } from '../shared.mjs'

const UM_DAMIT = 'um / damit'
const SOU = 'statt / ohne / um'
const FAHRRAD = 'Zeitungsartikel: „Drei Studenten aus Münster hatten eine einfache Idee: Sie reparieren Fahrräder direkt vor der Haustür. Die Kunden müssen ihr Rad nicht mehr in die Werkstatt bringen, sondern buchen online einen Termin. Ein Mechaniker kommt dann mit dem Lastenrad vorbei. Kleine Reparaturen dauern nur eine halbe Stunde. Besonders Berufstätige nutzen den Service, um Zeit zu sparen.“'
const STAUBSAUGER = 'Aus einer Reklamation: „Sehr geehrte Damen und Herren, am 2. März habe ich bei Ihnen einen Staubsauger bestellt. Bei der Lieferung musste ich leider feststellen, dass das Kabel beschädigt ist. Ich habe Ihnen sofort eine E-Mail geschrieben, aber keine Antwort erhalten. Ich möchte Sie bitten, mir innerhalb von zwei Wochen ein neues Gerät zu schicken. Andernfalls werde ich den Kaufpreis zurückfordern.“'

/** B1.1 · Pfad 6 · Dienstleistung – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'reklamieren', I.choose, 'Der Staubsauger war schon nach drei Tagen kaputt. Ich habe ihn sofort im Geschäft …', ['reklamiert', 'geliefert', 'bestellt'],
      ['The vacuum cleaner was broken after only three days. I … about it at the shop at once.', 'Пылесос сломался уже через три дня. Я сразу … в магазине.', 'Пилосос зламався вже через три дні. Я одразу … у крамниці.', 'Elektrikli süpürge daha üç gün sonra bozuldu. Hemen mağazaya …']),
    mc('G1', 'es gibt', I.choose, 'In diesem Stadtteil … es leider keinen einzigen Supermarkt.', ['gibt', 'ist', 'hat'],
      ['Unfortunately there is not a single supermarket in this part of town.', 'В этом районе, к сожалению, нет ни одного супермаркета.', 'У цьому районі, на жаль, немає жодного супермаркету.', 'Bu semtte ne yazık ki tek bir süpermarket bile yok.']),
    mc('G2', 'um … zu', I.choose, 'Ich habe die Hotline angerufen, … nach meiner Bestellung zu fragen.', ['um', 'damit', 'statt'],
      ['I called the hotline to ask about my order.', 'Я позвонил на горячую линию, чтобы спросить о своём заказе.', 'Я зателефонував на гарячу лінію, щоб спитати про своє замовлення.', 'Siparişimi sormak için yardım hattını aradım.']),
    mc('G3', 'damit', I.choose, 'Bitte schreiben Sie Ihre Telefonnummer auf, … wir Sie zurückrufen können.', ['damit', 'um', 'ohne'],
      ['Please write down your telephone number so that we can call you back.', 'Пожалуйста, запишите свой номер телефона, чтобы мы могли вам перезвонить.', 'Будь ласка, запишіть свій номер телефону, щоб ми могли вам передзвонити.', 'Sizi geri arayabilmemiz için lütfen telefon numaranızı yazın.']),
    mc('G4', 'statt … zu', I.choose, 'Ruf doch einfach an, … stundenlang auf eine E-Mail zu warten!', ['statt', 'ohne', 'damit'],
      ['Just call instead of waiting for an e-mail for hours!', 'Просто позвони, вместо того чтобы часами ждать электронного письма!', 'Просто зателефонуй, замість того щоб годинами чекати на електронний лист!', 'Saatlerce e-posta beklemek yerine doğrudan ara!']),
    mc('G5', 'ohne … zu', I.choose, 'Sie hat das Paket angenommen, … den Inhalt zu prüfen.', ['ohne', 'statt', 'damit'],
      ['She accepted the parcel without checking the contents.', 'Она приняла посылку, не проверив содержимое.', 'Вона прийняла посилку, не перевіривши вміст.', 'İçindekileri kontrol etmeden paketi teslim aldı.']),
    mc('K1', 'Es wäre schön, … zu', I.choose, 'Es wäre schön, einen eigenen kleinen Laden … haben.', ['zu', 'um', 'damit'],
      ['It would be nice to have a little shop of my own.', 'Было бы хорошо иметь собственный маленький магазин.', 'Було б добре мати власну маленьку крамницю.', 'Kendime ait küçük bir dükkânım olsa güzel olurdu.']),
    mc('K2', 'Dürfte ich Sie etwas fragen?', I.situation, 'Du brauchst im Geschäft Hilfe und sprichst einen Verkäufer an. Was sagst du?', ['Entschuldigung, dürfte ich Sie etwas fragen?', 'Sie wünschen?', 'Zahlen Sie bar oder mit Karte?'],
      ['You need help in a shop and approach a sales assistant. What do you say?', 'Вам нужна помощь в магазине, и вы обращаетесь к продавцу. Что вы скажете?', 'Вам потрібна допомога в крамниці, і ви звертаєтеся до продавця. Що ви скажете?', 'Mağazada yardıma ihtiyacınız var ve bir satıcıya sesleniyorsunuz. Ne dersiniz?']),
    mc('K3', 'An deiner Stelle …', I.react, '„Mein neues Handy geht nach zwei Tagen nicht mehr an.“', ['An deiner Stelle würde ich es sofort umtauschen.', 'Das muss ich mir noch überlegen.', 'Mein Traum wäre ein neues Handy.'],
      ['“My new mobile will not switch on after two days.”', '«Мой новый телефон через два дня перестал включаться.»', '«Мій новий телефон за два дні перестав вмикатися.»', '“Yeni telefonum iki gün sonra artık açılmıyor.”']),
    mc('K4', 'Leider musste ich feststellen, …', I.choose, 'Welcher Satz passt in eine Reklamation?', ['Leider musste ich feststellen, dass der Bildschirm beschädigt ist.', 'Mein Traum wäre ein großer Bildschirm.', 'Sie wünschen einen Bildschirm?'],
      ['Which sentence fits in a complaint?', 'Какое предложение подходит для рекламации?', 'Яке речення підходить для рекламації?', 'Hangi cümle bir şikâyet yazısına uyar?']),
    mc('Z1', 'Idee', I.read, `${FAHRRAD} Was ist die Idee der drei Studenten?`, ['Sie reparieren Fahrräder bei den Kunden vor der Tür.', 'Sie verkaufen Fahrräder im Internet.', 'Sie bringen Fahrräder in eine Werkstatt.'],
      ['What is the three students’ idea?', 'В чём идея трёх студентов?', 'У чому ідея трьох студентів?', 'Üç öğrencinin fikri ne?']),
    gap('G3', 'damit', I.conjunction, 'Ich lege dir die Quittung auf den Tisch, ', ' du sie nicht suchen musst.', 'damit', ['um', 'statt'],
      ['I will put the receipt on the table for you so that you do not have to look for it.', 'Я положу тебе чек на стол, чтобы тебе не пришлось его искать.', 'Я покладу тобі чек на стіл, щоб тобі не довелося його шукати.', 'Aramak zorunda kalmayasın diye fişi masaya koyuyorum.'], UM_DAMIT),
    gap('G2', 'Wozu? – Um … zu', I.conjunction, 'Wozu brauchst du die Quittung? – ', ' die Schuhe umzutauschen.', 'Um', ['Damit', 'Statt'],
      ['What do you need the receipt for? – To exchange the shoes.', 'Зачем тебе чек? – Чтобы обменять туфли.', 'Навіщо тобі чек? – Щоб обміняти туфлі.', 'Fiş ne için lazım? – Ayakkabıları değiştirmek için.'], UM_DAMIT, { c: 'p6_umzu_damit' }),
  ],
  size: 13,
  test: [
    mc('W1', 'Rechnung', I.choose, 'Auf diesem Papier steht, was man gekauft hat und wie viel man bezahlen muss. Es ist die …', ['Rechnung', 'Garantie', 'Lieferung'],
      ['This paper states what you have bought and how much you have to pay. It is the …', 'В этом документе указано, что вы купили и сколько нужно заплатить. Это …', 'У цьому документі зазначено, що ви купили і скільки треба заплатити. Це …', 'Bu kâğıtta ne aldığınız ve ne kadar ödemeniz gerektiği yazar. Bu …']),
    mc('W1', 'Garantie', I.choose, 'Der Fernseher ist zwei Jahre alt und schon kaputt. Zum Glück habe ich drei Jahre …', ['Garantie', 'Lieferung', 'Quittung'],
      ['The television is two years old and already broken. Luckily I have a three-year …', 'Телевизору два года, и он уже сломался. К счастью, у меня три года …', 'Телевізору два роки, і він уже зламався. На щастя, я маю три роки …', 'Televizyon iki yaşında ve şimdiden bozuldu. Neyse ki üç yıl … var.']),
    mc('G1', 'es schneit', I.choose, 'Heute … den ganzen Tag. Wir bleiben lieber zu Hause.', ['schneit es', 'schneit', 'es schneit'],
      ['It is snowing all day today. We would rather stay at home.', 'Сегодня весь день идёт снег. Мы лучше останемся дома.', 'Сьогодні весь день іде сніг. Ми краще залишимося вдома.', 'Bugün bütün gün kar yağıyor. Evde kalmayı tercih ederiz.']),
    mc('G1', 'Lohnt es sich?', I.choose, 'Lohnt … sich wirklich, für zwei Brötchen so weit zu fahren?', ['es', 'er', 'sie'],
      ['Is it really worth driving so far for two rolls?', 'Неужели стоит ехать так далеко ради двух булочек?', 'Невже варто їхати так далеко заради двох булочок?', 'İki küçük ekmek için bu kadar uzağa gitmeye gerçekten değer mi?']),
    mc('G2', 'um … zu bilden', I.sentence, 'Tom fährt zum Baumarkt. Sein Ziel: Farbe für die Küche kaufen.', ['Tom fährt zum Baumarkt, um Farbe für die Küche zu kaufen.', 'Tom fährt zum Baumarkt, um er Farbe für die Küche zu kaufen.', 'Tom fährt zum Baumarkt, um Farbe für die Küche kaufen.'],
      ['Tom is driving to the DIY store. His aim: to buy paint for the kitchen.', 'Tom едет в строительный магазин. Его цель: купить краску для кухни.', 'Tom їде до будівельного магазину. Його мета: купити фарбу для кухні.', 'Tom yapı markete gidiyor. Amacı: mutfak için boya almak.']),
    mc('G2', 'um nichts zu vergessen', I.choose, 'Ich schreibe mir vor dem Einkauf alles auf, um nichts … vergessen.', ['zu', 'um', 'damit'],
      ['Before going shopping I write everything down so as not to forget anything.', 'Перед походом в магазин я всё записываю, чтобы ничего не забыть.', 'Перед походом до крамниці я все записую, щоб нічого не забути.', 'Alışverişten önce hiçbir şeyi unutmamak için her şeyi yazıyorum.']),
    mc('G3', 'damit', I.choose, 'Wir haben einen Tisch reserviert, … unsere Gäste nicht warten müssen.', ['damit', 'um', 'statt'],
      ['We have booked a table so that our guests do not have to wait.', 'Мы забронировали столик, чтобы нашим гостям не пришлось ждать.', 'Ми забронювали столик, щоб нашим гостям не довелося чекати.', 'Misafirlerimiz beklemek zorunda kalmasın diye masa ayırttık.']),
    mc('G3', 'damit + Verb am Ende', I.sentence, 'Die Verkäuferin packt die Vase gut ein. Die Vase soll nicht kaputtgehen.', ['Die Verkäuferin packt die Vase gut ein, damit sie nicht kaputtgeht.', 'Die Verkäuferin packt die Vase gut ein, damit sie geht nicht kaputt.', 'Die Verkäuferin packt die Vase gut ein, um sie nicht kaputtgeht.'],
      ['The sales assistant wraps the vase up well. The vase must not get broken.', 'Продавщица хорошо упаковывает вазу. Ваза не должна разбиться.', 'Продавчиня добре пакує вазу. Ваза не має розбитися.', 'Satıcı vazoyu iyice paketliyor. Vazo kırılmamalı.']),
    mc('G4', 'statt … zu verstehen', I.choose, 'Was bedeutet „Er repariert das Rad selbst, statt es in die Werkstatt zu bringen.“?', ['Er bringt das Rad nicht in die Werkstatt.', 'Er bringt das Rad zuerst in die Werkstatt.', 'Er kann das Rad nicht reparieren.'],
      ['What does “Er repariert das Rad selbst, statt es in die Werkstatt zu bringen.” mean?', 'Что означает «Er repariert das Rad selbst, statt es in die Werkstatt zu bringen.»?', 'Що означає «Er repariert das Rad selbst, statt es in die Werkstatt zu bringen.»?', '“Er repariert das Rad selbst, statt es in die Werkstatt zu bringen.” ne demek?']),
    mc('G4', 'Statt', I.choose, '… sich laut zu beschweren, sollte man lieber höflich nachfragen.', ['Statt', 'Ohne', 'Damit'],
      ['Instead of complaining loudly, it is better to ask politely.', 'Вместо того чтобы громко жаловаться, лучше вежливо переспросить.', 'Замість того щоб голосно скаржитися, краще ввічливо перепитати.', 'Yüksek sesle şikâyet etmek yerine kibarca sormak daha iyidir.']),
    mc('G5', 'ohne', I.choose, 'Man sollte nie einen Vertrag unterschreiben, … das Kleingedruckte zu lesen.', ['ohne', 'statt', 'um'],
      ['You should never sign a contract without reading the small print.', 'Никогда не следует подписывать договор, не прочитав мелкий шрифт.', 'Ніколи не слід підписувати договір, не прочитавши дрібний шрифт.', 'Küçük harflerle yazılanları okumadan asla sözleşme imzalanmamalıdır.']),
    mc('G5', 'ohne … zu bilden', I.sentence, 'Der Kunde ist aus dem Restaurant gegangen. Er hat nicht bezahlt.', ['Der Kunde ist aus dem Restaurant gegangen, ohne zu bezahlen.', 'Der Kunde ist aus dem Restaurant gegangen, ohne bezahlen zu.', 'Der Kunde ist aus dem Restaurant gegangen, ohne er zu bezahlen.'],
      ['The customer left the restaurant. He did not pay.', 'Клиент ушёл из ресторана. Он не заплатил.', 'Клієнт пішов із ресторану. Він не заплатив.', 'Müşteri restorandan çıktı. Hesabı ödemedi.']),
    mc('K1', 'Es wäre schön, …', I.react, '„Wie würdest du denn gern leben?“', ['Es wäre schön, auf dem Land zu wohnen und einen kleinen Hofladen zu haben.', 'Ich möchte Sie bitten, mir das Geld zurückzuzahlen.', 'Zahlen Sie bar oder mit Karte?'],
      ['“So how would you like to live?”', '«А как бы ты хотел жить?»', '«А як би ти хотів жити?»', '“Peki nasıl yaşamak isterdin?”']),
    mc('K2', 'sich etwas überlegen', I.choose, 'Diese Schuhe gefallen mir, aber ich bin nicht sicher. Das muss ich mir noch …', ['überlegen', 'bestätigen', 'umtauschen'],
      ['I like these shoes, but I am not sure. I need to … it.', 'Эти туфли мне нравятся, но я не уверен. Мне нужно ещё …', 'Ці туфлі мені подобаються, але я не впевнений. Мені треба ще …', 'Bu ayakkabıları beğendim ama emin değilim. Bunu biraz daha … gerek.']),
    mc('K2', 'Ist es möglich, … umzutauschen?', I.situation, 'Du möchtest wissen, ob man das Gerät zurückgeben und ein anderes bekommen kann. Was fragst du?', ['Ist es möglich, das Gerät umzutauschen?', 'Kann ich sonst noch etwas für Sie tun?', 'Haben Sie einen bestimmten Wunsch?'],
      ['You would like to know whether you can return the appliance and get another one. What do you ask?', 'Вы хотите узнать, можно ли вернуть прибор и получить другой. Что вы спросите?', 'Ви хочете дізнатися, чи можна повернути прилад і отримати інший. Що ви спитаєте?', 'Cihazı geri verip başka bir tane alıp alamayacağınızı öğrenmek istiyorsunuz. Ne sorarsınız?']),
    mc('K3', 'höflicher Ratschlag', I.choose, 'Welcher Satz ist ein höflicher Ratschlag?', ['Was halten Sie davon, zuerst die Preise zu vergleichen?', 'Vergleichen Sie endlich die Preise!', 'Sie haben die Preise nicht verglichen.'],
      ['Which sentence is a polite piece of advice?', 'Какое предложение – вежливый совет?', 'Яке речення – ввічлива порада?', 'Hangi cümle kibar bir tavsiyedir?']),
    mc('K4', 'schriftlich bestätigen', I.choose, 'Bitte bestätigen Sie mir … bis zum 15. Juni, dass Sie die Ware abholen.', ['schriftlich', 'ärgerlich', 'defekt'],
      ['Please confirm … by 15 June that you will collect the goods.', 'Пожалуйста, подтвердите … до 15 июня, что вы заберёте товар.', 'Будь ласка, підтвердьте … до 15 червня, що ви заберете товар.', 'Lütfen malı alacağınızı 15 Haziran’a kadar … teyit edin.']),
    mc('K4', 'Anfang der Reklamation', I.choose, 'Was schreibt man in einer Reklamation zuerst?', ['Was man wann gekauft oder bestellt hat.', 'Dass man den Kaufpreis zurückfordert.', 'Mit freundlichen Grüßen.'],
      ['What do you write first in a complaint?', 'Что пишут в рекламации в первую очередь?', 'Що пишуть у рекламації насамперед?', 'Bir şikâyet yazısında ilk olarak ne yazılır?']),
    mc('Z1', 'Problem', I.read, `${STAUBSAUGER} Was ist das Problem mit dem Staubsauger?`, ['Das Kabel ist beschädigt.', 'Er wurde nicht geliefert.', 'Er ist zu teuer.'],
      ['What is the problem with the vacuum cleaner?', 'В чём проблема с пылесосом?', 'У чому проблема з пилососом?', 'Elektrikli süpürgenin sorunu ne?']),
    mc('Z1', 'Kunden', I.read, `${FAHRRAD} Wer nutzt den Service besonders oft?`, ['Menschen, die arbeiten und wenig Zeit haben.', 'Studenten aus Münster.', 'Mechaniker mit einer eigenen Werkstatt.'],
      ['Who uses the service particularly often?', 'Кто особенно часто пользуется этой услугой?', 'Хто особливо часто користується цією послугою?', 'Bu hizmeti en çok kimler kullanıyor?']),
    gap('W1', 'umtauschen', I.word, 'Die Schuhe passen leider nicht. Ich möchte sie gegen ein anderes Paar ', '.', 'umtauschen', ['umziehen', 'umsteigen'],
      ['Unfortunately the shoes do not fit. I would like to exchange them for another pair.', 'Туфли, к сожалению, не подходят. Я хотел бы обменять их на другую пару.', 'Туфлі, на жаль, не підходять. Я хотів би обміняти їх на іншу пару.', 'Ayakkabılar ne yazık ki olmadı. Onları başka bir çiftle değiştirmek istiyorum.'],
      ['exchange', 'обменять', 'обміняти', 'değiştirmek']),
    gap('G1', 'es regnet', I.verb, 'In Hamburg ', ' es im Herbst sehr oft.', 'regnet', ['regnen', 'geregnet'],
      ['In Hamburg it rains very often in autumn.', 'В Гамбурге осенью очень часто идёт дождь.', 'У Гамбурзі восени дуже часто йде дощ.', 'Hamburg’da sonbaharda çok sık yağmur yağar.'], 'regnen'),
    gap('G2', 'um', I.conjunction, 'Sie macht einen Computerkurs, ', ' bessere Chancen bei der Bewerbung zu haben.', 'um', ['damit', 'ohne'],
      ['She is doing a computer course in order to have a better chance when applying for jobs.', 'Она ходит на компьютерные курсы, чтобы иметь больше шансов при поиске работы.', 'Вона ходить на комп’ютерні курси, щоб мати більше шансів під час пошуку роботи.', 'İş başvurularında daha çok şansı olsun diye bilgisayar kursuna gidiyor.'], UM_DAMIT),
    gap('G3', 'damit … sind', I.verb, 'Der Händler gibt drei Jahre Garantie, damit seine Kunden zufrieden ', '.', 'sind', ['sein', 'ist'],
      ['The dealer gives a three-year guarantee so that his customers are satisfied.', 'Продавец даёт три года гарантии, чтобы его клиенты были довольны.', 'Продавець дає три роки гарантії, щоб його клієнти були задоволені.', 'Satıcı, müşterileri memnun olsun diye üç yıl garanti veriyor.'], 'sein'),
    gap('G4', 'statt', I.conjunction, 'Ich gehe lieber zu Fuß, ', ' mit dem Auto eine Stunde im Stau zu stehen.', ['statt', 'anstatt'], ['ohne', 'damit'],
      ['I prefer to walk instead of sitting in a traffic jam for an hour in the car.', 'Я лучше пойду пешком, чем буду час стоять в пробке на машине.', 'Я краще піду пішки, ніж годину стоятиму в заторі на машині.', 'Arabayla bir saat trafikte beklemek yerine yürümeyi tercih ederim.'], SOU),
    gap('G5', 'ohne … nachzudenken', I.form, 'Er hat die teure Uhr gekauft, ohne lange ', '.', 'nachzudenken', ['nachdenken', 'zu nachdenken'],
      ['He bought the expensive watch without thinking about it for long.', 'Он купил дорогие часы, долго не раздумывая.', 'Він купив дорогий годинник, довго не роздумуючи.', 'Pahalı saati uzun uzun düşünmeden satın aldı.'], 'nachdenken'),
    gap('K1', 'Mein Traum wäre …', I.word, 'Mein ', ' wäre ein kleines Restaurant mit Essen aus meiner Heimat.', 'Traum', ['Kunde', 'Kauf'],
      ['My dream would be a small restaurant with food from my home country.', 'Моя мечта – маленький ресторан с блюдами моей родины.', 'Моя мрія – маленький ресторан зі стравами моєї батьківщини.', 'Hayalim memleketimin yemeklerini sunan küçük bir restoran olurdu.'],
      ['dream', 'мечта', 'мрія', 'hayal']),
    gap('K2', 'Ich hätte gern …', I.polite, 'Guten Tag! Ich ', ' gern ein Kilo Äpfel und zwei Zitronen.', 'hätte', ['wäre', 'würde'],
      ['Hello! I would like a kilo of apples and two lemons.', 'Здравствуйте! Мне, пожалуйста, килограмм яблок и два лимона.', 'Добрий день! Мені, будь ласка, кілограм яблук і два лимони.', 'İyi günler! Bir kilo elma ve iki limon rica ediyorum.'], 'haben (Konjunktiv II)'),
    gap('K3', 'An Ihrer Stelle', I.expression, 'An Ihrer ', ' würde ich die Rechnung noch einmal genau prüfen.', 'Stelle', ['Seite', 'Sache'],
      ['If I were you, I would check the invoice carefully once more.', 'На вашем месте я бы ещё раз внимательно проверил счёт.', 'На вашому місці я б ще раз уважно перевірив рахунок.', 'Sizin yerinizde olsam faturayı bir kez daha dikkatlice kontrol ederdim.'],
      ['place (an Ihrer Stelle = if I were you)', 'место (an Ihrer Stelle = на вашем месте)', 'місце (an Ihrer Stelle = на вашому місці)', 'yer (an Ihrer Stelle = sizin yerinizde)']),
    gap('K4', 'Ich möchte Sie bitten, …', I.word, 'Ich möchte Sie ', ', mir so schnell wie möglich ein neues Gerät zu schicken.', 'bitten', ['bieten', 'beten'],
      ['I would ask you to send me a new appliance as quickly as possible.', 'Прошу вас как можно скорее прислать мне новый прибор.', 'Прошу вас якомога швидше надіслати мені новий прилад.', 'Bana en kısa sürede yeni bir cihaz göndermenizi rica ediyorum.'],
      ['ask, request', 'попросить', 'попросити', 'rica etmek']),
  ],
}

export default check
