import { I, gap, mc } from '../shared.mjs'

const AUX_K2 = 'haben / sein (Konjunktiv II)'
const SOMMERFEST = 'Aushang im Treppenhaus: „Liebe Nachbarinnen und Nachbarn, am Samstag, dem 14. Juni, feiern wir im Hof unser Sommerfest. Jeder bringt entweder einen Salat oder einen Kuchen mit, für Getränke sorgt der Hausmeister. Wir feiern nicht nur mit Musik, sondern auch mit Spielen für die Kinder. Um 22 Uhr machen wir Schluss, damit niemand gestört wird. Wer beim Aufbauen helfen möchte, meldet sich bitte bei Familie Hoffmann im zweiten Stock.“'
const MIETEN = 'Zeitungsbericht: „Die Mieten in der Stadt sind in fünf Jahren um ein Drittel gestiegen. Besonders Familien und Studenten finden kaum noch bezahlbare Wohnungen. Trotz der hohen Preise ziehen jedes Jahr Tausende in die Stadt, weil es hier Arbeit gibt. Die Stadt will deshalb bis zum nächsten Jahr zweitausend neue Wohnungen bauen. Viele Bürger zweifeln daran, dass das reicht.“'

/** B1.1 · Pfad 7 · Rund ums Wohnen – Wiederholung und Testpool. */
const check = {
  review: [
    mc('W1', 'Mieter', I.choose, 'Wer in einer Wohnung wohnt und dafür jeden Monat Geld bezahlt, ist ein …', ['Mieter', 'Vermieter', 'Hausmeister'],
      ['Someone who lives in a flat and pays money for it every month is a …', 'Тот, кто живёт в квартире и каждый месяц платит за неё, – это …', 'Той, хто живе у квартирі й щомісяця платить за неї, – це …', 'Bir dairede oturup bunun için her ay para ödeyen kişi …']),
    mc('G1', 'sondern auch', I.choose, 'Das Haus hat nicht nur einen Garten, … auch eine große Terrasse.', ['sondern', 'aber', 'oder'],
      ['The house has not only a garden but also a large terrace.', 'У дома есть не только сад, но и большая терраса.', 'Будинок має не тільки сад, а й велику терасу.', 'Evin yalnızca bahçesi değil, aynı zamanda büyük bir terası da var.']),
    mc('G1', 'zwar …, aber', I.choose, 'Die Wohnung liegt … mitten im Zentrum, aber sie ist trotzdem sehr ruhig.', ['zwar', 'entweder', 'nicht nur'],
      ['The flat is right in the centre, it is true, but it is nevertheless very quiet.', 'Квартира хоть и находится в самом центре, но всё равно очень тихая.', 'Квартира хоч і розташована в самому центрі, але все одно дуже тиха.', 'Daire gerçi tam merkezde ama yine de çok sessiz.'], { c: 'p7_zwar_entweder' }),
    mc('G2', 'hätten gekauft', I.choose, 'Wir … die Wohnung fast gekauft, aber dann war sie uns doch zu teuer.', ['hätten', 'wären', 'haben'],
      ['We almost bought the flat, but then it was too expensive for us after all.', 'Мы чуть было не купили эту квартиру, но потом она всё-таки оказалась для нас слишком дорогой.', 'Ми мало не купили цю квартиру, але потім вона все-таки виявилася для нас надто дорогою.', 'Daireyi neredeyse satın alacaktık ama sonra bize yine de pahalı geldi.']),
    mc('G3', 'irrealer Wunsch', I.choose, 'Lisa hat die Kaution nicht rechtzeitig bezahlt und die Wohnung verloren. Was denkt sie?', ['Hätte ich das Geld doch früher überwiesen!', 'Wäre ich das Geld doch früher überwiesen!', 'Hätte ich das Geld doch später überwiesen!'],
      ['Lisa did not pay the deposit in time and lost the flat. What is she thinking?', 'Lisa не заплатила залог вовремя и потеряла квартиру. Что она думает?', 'Lisa не заплатила заставу вчасно і втратила квартиру. Що вона думає?', 'Lisa depozitoyu zamanında ödemedi ve daireyi kaybetti. Ne düşünüyor?']),
    mc('G4', 'sich gewöhnen an', I.choose, 'Ich habe mich sehr schnell … die neue Umgebung gewöhnt.', ['an', 'auf', 'über'],
      ['I got used to the new surroundings very quickly.', 'Я очень быстро привык к новому окружению.', 'Я дуже швидко звик до нового оточення.', 'Yeni çevreye çok çabuk alıştım.']),
    mc('G4', 'Worauf', I.choose, '… wartest du denn so ungeduldig? – Auf den Brief vom Vermieter.', ['Worauf', 'Auf wen', 'Wofür'],
      ['What are you waiting for so impatiently? – The letter from the landlord.', 'Чего ты так нетерпеливо ждёшь? – Письма от хозяина квартиры.', 'Чого ти так нетерпляче чекаєш? – Листа від власника квартири.', 'Neyi bu kadar sabırsızlıkla bekliyorsun? – Ev sahibinden gelecek mektubu.'], { c: 'p7_woran' }),
    mc('G5', 'trotz der Kritik', I.choose, 'Trotz … Kritik der Nachbarn baut er weiter an seiner Garage.', ['der', 'des', 'dem'],
      ['In spite of the neighbours’ criticism he carries on building his garage.', 'Несмотря на критику соседей, он продолжает строить гараж.', 'Попри критику сусідів, він і далі будує гараж.', 'Komşuların eleştirisine rağmen garajını yapmaya devam ediyor.']),
    mc('K1', 'üblich', I.choose, 'Bei uns war es …, dass die ganze Familie am Sonntag zusammen isst.', ['üblich', 'verboten', 'bezahlbar'],
      ['In our family it was … for the whole family to eat together on Sundays.', 'У нас было …, что по воскресеньям вся семья ест вместе.', 'У нас було …, що в неділю вся родина їсть разом.', 'Bizde bütün ailenin pazar günü birlikte yemek yemesi …']),
    mc('K2', 'höflich Kritik äußern', I.situation, 'Dein Nachbar parkt immer direkt vor deiner Garage. Wie sagst du das höflich?', ['Es wäre schön, wenn Sie etwas Rücksicht nehmen könnten.', 'Das ist ja lächerlich!', 'Meinetwegen.'],
      ['Your neighbour always parks right in front of your garage. How do you say that politely?', 'Ваш сосед всегда паркуется прямо перед вашим гаражом. Как вежливо сказать ему об этом?', 'Ваш сусід завжди паркується просто перед вашим гаражем. Як ввічливо сказати йому про це?', 'Komşunuz hep garajınızın tam önüne park ediyor. Bunu kibarca nasıl söylersiniz?']),
    mc('K3', 'freundlich reagieren', I.react, '„Ihre Kinder sind am Sonntagmorgen sehr laut.“ – Du reagierst freundlich.', ['Das tut mir schrecklich leid. Wir passen besser auf.', 'Das geht Sie gar nichts an!', 'Das ist ja wohl eine Frechheit!'],
      ['“Your children are very noisy on Sunday mornings.” – You respond in a friendly way.', '«Ваши дети очень шумят в воскресенье утром.» – Вы реагируете доброжелательно.', '«Ваші діти дуже шумлять у неділю вранці.» – Ви реагуєте доброзичливо.', '“Çocuklarınız pazar sabahları çok gürültü yapıyor.” – Dostça karşılık veriyorsunuz.']),
    mc('Z1', 'Sommerfest', I.read, `${SOMMERFEST} Was sollen die Nachbarn zum Fest mitbringen?`, ['Einen Salat oder einen Kuchen.', 'Getränke für alle.', 'Musik und Spiele.'],
      ['What should the neighbours bring to the party?', 'Что соседи должны принести на праздник?', 'Що сусіди мають принести на свято?', 'Komşular şenliğe ne getirmeli?']),
    gap('K4', 'träumen von', I.verb, 'Ich wohne noch bei meinen Eltern, aber ich ', ' von einer eigenen Wohnung.', 'träume', ['träumt', 'träumen'],
      ['I still live with my parents, but I dream of a flat of my own.', 'Я ещё живу у родителей, но мечтаю о собственной квартире.', 'Я ще живу в батьків, але мрію про власну квартиру.', 'Hâlâ ailemin yanında oturuyorum ama kendi dairemi hayal ediyorum.'], 'träumen'),
  ],
  size: 13,
  test: [
    mc('W1', 'Hausmeister', I.choose, 'Er kümmert sich um das Haus, repariert das Licht im Flur und pflegt den Garten. Er ist der …', ['Hausmeister', 'Mieter', 'Bewerber'],
      ['He looks after the building, repairs the light in the hall and tends the garden. He is the …', 'Он следит за домом, чинит свет в коридоре и ухаживает за садом. Он …', 'Він дбає про будинок, лагодить світло в коридорі й доглядає сад. Він …', 'Binayla ilgileniyor, koridordaki ışığı tamir ediyor ve bahçeye bakıyor. O …']),
    mc('G1', 'nicht nur', I.choose, 'Der neue Mieter spielt nicht … Klavier, sondern auch Schlagzeug.', ['nur', 'kein', 'nie'],
      ['The new tenant plays not only the piano but also the drums.', 'Новый жилец играет не только на пианино, но и на ударных.', 'Новий мешканець грає не тільки на піаніно, а й на ударних.', 'Yeni kiracı yalnızca piyano değil, aynı zamanda bateri de çalıyor.']),
    mc('G1', 'entweder … oder', I.choose, 'Du musst dich entscheiden: Entweder du kommst mit zur Besichtigung, … du bleibst zu Hause.', ['oder', 'aber', 'sondern'],
      ['You have to decide: either you come along to the viewing, or you stay at home.', 'Тебе нужно решить: либо ты идёшь с нами на просмотр, либо остаёшься дома.', 'Тобі треба вирішити: або ти йдеш із нами на перегляд, або залишаєшся вдома.', 'Karar vermelisin: Ya bizimle daireyi görmeye gelirsin ya da evde kalırsın.'], { c: 'p7_zwar_entweder' }),
    mc('G1', 'zwar …, aber', I.sentence, 'Das Zimmer ist dunkel. Es ist dafür billig.', ['Das Zimmer ist zwar dunkel, aber billig.', 'Das Zimmer ist entweder dunkel, aber billig.', 'Das Zimmer ist zwar dunkel, sondern billig.'],
      ['The room is dark. On the other hand it is cheap.', 'Комната тёмная. Зато она дешёвая.', 'Кімната темна. Зате вона дешева.', 'Oda karanlık. Buna karşılık ucuz.'], { c: 'p7_zwar_entweder' }),
    mc("G2", "hätten gefunden", I.choose, "Ohne den Tipp von Herrn Kurz ___ wir diese Wohnung nie gefunden.", ["hätten","würden","wären"], ["Without Mr Kurz’s tip we would never have found this flat.","Без подсказки господина Kurz мы бы никогда не нашли эту квартиру.","Без підказки пана Kurz ми б ніколи не знайшли цю квартиру.","Kurz Bey’in tavsiyesi olmasa bu daireyi asla bulamazdık."], {"c":"p7_konj2_verg","sitovOptionOrder":["würden","wären","hätten"]}),
    mc('G2', 'wäre geblieben', I.choose, 'An Ihrer Stelle … ich in so einer lauten Wohnung nicht so lange geblieben.', ['wäre', 'hätte', 'würde'],
      ['If I had been you, I would not have stayed in such a noisy flat for so long.', 'На вашем месте я бы не оставался так долго в такой шумной квартире.', 'На вашому місці я б не залишався так довго в такій галасливій квартирі.', 'Sizin yerinizde olsam bu kadar gürültülü bir dairede o kadar uzun kalmazdım.']),
    mc('G3', 'Hätten', I.choose, '… wir bloß früher mit der Wohnungssuche angefangen!', ['Hätten', 'Wären', 'Haben'],
      ['If only we had started looking for a flat earlier!', 'Если бы мы только раньше начали искать квартиру!', 'Якби ми тільки раніше почали шукати квартиру!', 'Keşke daire aramaya daha önce başlasaydık!']),
    mc('G3', 'Wunsch verstehen', I.choose, 'Was ist wirklich passiert? „Wäre ich doch nicht umgezogen!“', ['Ich bin umgezogen und finde das jetzt schlecht.', 'Ich bin nicht umgezogen.', 'Ich möchte bald umziehen.'],
      ['What really happened? “If only I had not moved!”', 'Что произошло на самом деле? «Если бы я только не переезжал!»', 'Що сталося насправді? «Якби я тільки не переїжджав!»', 'Gerçekte ne oldu? “Keşke taşınmasaydım!”']),
    mc('G4', 'Über wen?', I.choose, 'Über … hast du dich denn beschwert? – Über den Mann im ersten Stock.', ['wen', 'was', 'wem'],
      ['Who did you complain about? – The man on the first floor.', 'На кого же ты пожаловался? – На мужчину со второго этажа.', 'На кого ж ти поскаржився? – На чоловіка з другого поверху.', 'Kimden şikâyet ettin? – Birinci kattaki adamdan.'], { c: 'p7_woran' }),
    mc('G4', 'Darüber', I.choose, 'Die Miete steigt schon wieder. … ärgern sich alle Mieter im Haus.', ['Darüber', 'Daran', 'Darum'],
      ['The rent is going up yet again. All the tenants in the building are annoyed about that.', 'Арендная плата снова растёт. Из-за этого злятся все жильцы дома.', 'Орендна плата знову зростає. Через це сердяться всі мешканці будинку.', 'Kira yine artıyor. Binadaki bütün kiracılar buna kızıyor.']),
    mc('G5', 'trotz verstehen', I.choose, 'Was bedeutet „Trotz der Ruhezeit bohrt der Nachbar um 22 Uhr.“?', ['Es ist Ruhezeit, aber er bohrt.', 'Er bohrt, weil Ruhezeit ist.', 'Er bohrt nie in der Ruhezeit.'],
      ['What does “Trotz der Ruhezeit bohrt der Nachbar um 22 Uhr.” mean?', 'Что означает «Trotz der Ruhezeit bohrt der Nachbar um 22 Uhr.»?', 'Що означає «Trotz der Ruhezeit bohrt der Nachbar um 22 Uhr.»?', '“Trotz der Ruhezeit bohrt der Nachbar um 22 Uhr.” ne demek?']),
    mc('G5', 'Trotz … + Verb', I.sentence, 'Es gab sehr viele Bewerber. Wir haben die Wohnung bekommen.', ['Trotz der vielen Bewerber haben wir die Wohnung bekommen.', 'Trotz der vielen Bewerber wir haben die Wohnung bekommen.', 'Trotz die vielen Bewerber haben wir die Wohnung bekommen.'],
      ['There were a great many applicants. We got the flat.', 'Было очень много желающих. Квартира досталась нам.', 'Було дуже багато охочих. Квартира дісталася нам.', 'Çok fazla başvuran vardı. Daireyi biz aldık.']),
    mc('K1', 'über Regeln sprechen', I.react, '„Durfte man bei euch im Treppenhaus spielen?“', ['Nein, das war bei uns streng verboten.', 'Ja, ich hätte da eine Bitte.', 'Tatsächlich? Das ist ja merkwürdig.'],
      ['“Were you allowed to play in the stairwell where you lived?”', '«А у вас разрешали играть в подъезде?»', '«А у вас дозволяли гратися в під’їзді?»', '“Sizde apartman merdiveninde oynamaya izin var mıydı?”']),
    mc('K2', 'abgemacht, dass', I.choose, 'Wir hatten doch abgemacht, … Sie den Müll am Montag nach unten bringen.', ['dass', 'ob', 'weil'],
      ['We had agreed that you would take the rubbish down on Monday.', 'Мы ведь договаривались, что вы выносите мусор в понедельник.', 'Ми ж домовлялися, що ви виносите сміття в понеділок.', 'Çöpü pazartesi günü sizin aşağı indireceğiniz konusunda anlaşmıştık.']),
    mc('K3', 'erstaunt reagieren', I.react, '„Ihr Auto steht schon wieder auf meinem Parkplatz!“ – Du bist erstaunt.', ['Tatsächlich? Das ist ja merkwürdig.', 'Das ist ja lächerlich!', 'Meinetwegen.'],
      ['“Your car is in my parking space yet again!” – You are surprised.', '«Ваша машина опять стоит на моём парковочном месте!» – Вы удивлены.', '«Ваша машина знову стоїть на моєму паркомісці!» – Ви здивовані.', '“Arabanız yine benim park yerimde duruyor!” – Şaşırıyorsunuz.']),
    mc('K3', 'freundliche Reaktion', I.choose, 'Welche Reaktion auf Kritik ist freundlich?', ['Klar, geht in Ordnung.', 'Das ist ja wohl eine Frechheit!', 'Das geht Sie gar nichts an!'],
      ['Which response to criticism is friendly?', 'Какая реакция на критику доброжелательная?', 'Яка реакція на критику доброзичлива?', 'Eleştiriye verilen hangi tepki dostçadır?']),
    mc('K4', 'Wohngemeinschaft', I.choose, 'Ich wohne mit drei Freunden zusammen. Jeder hat ein Zimmer, Küche und Bad teilen wir. Ich wohne in einer …', ['Wohngemeinschaft', 'Hausordnung', 'Besichtigung'],
      ['I live with three friends. Everyone has a room; we share the kitchen and bathroom. I live in a …', 'Я живу вместе с тремя друзьями. У каждого своя комната, а кухня и ванная общие. Я живу в …', 'Я живу разом із трьома друзями. Кожен має свою кімнату, а кухня і ванна спільні. Я живу в …', 'Üç arkadaşımla birlikte oturuyorum. Herkesin bir odası var, mutfağı ve banyoyu paylaşıyoruz. Ben bir …']),
    mc('Z1', 'Grund', I.read, `${MIETEN} Warum ziehen trotzdem viele Menschen in die Stadt?`, ['Weil es dort Arbeit gibt.', 'Weil die Mieten sinken.', 'Weil es dort viele freie Wohnungen gibt.'],
      ['Why do many people move to the city all the same?', 'Почему многие люди всё равно переезжают в город?', 'Чому багато людей усе одно переїжджають до міста?', 'Birçok insan yine de neden şehre taşınıyor?']),
    mc('Z1', 'Ende des Festes', I.read, `${SOMMERFEST} Warum endet das Fest um 22 Uhr?`, ['Damit niemand gestört wird.', 'Weil der Hausmeister müde ist.', 'Weil es dann keine Getränke mehr gibt.'],
      ['Why does the party end at 10 p.m.?', 'Почему праздник заканчивается в 22 часа?', 'Чому свято закінчується о 22 годині?', 'Şenlik neden saat 22’de bitiyor?']),
    gap('W1', 'Kaution', I.word, 'Für die Wohnung müssen wir 2400 Euro ', ' bezahlen. Beim Auszug bekommen wir das Geld zurück.', 'Kaution', ['Miete', 'Beschwerde'],
      ['For the flat we have to pay a deposit of 2,400 euros. We will get the money back when we move out.', 'За квартиру нам нужно внести залог 2400 евро. При выезде эти деньги нам вернут.', 'За квартиру нам треба внести заставу 2400 євро. Під час виїзду ці гроші нам повернуть.', 'Daire için 2400 avro depozito ödememiz gerekiyor. Çıkarken parayı geri alacağız.'],
      ['deposit', 'залог', 'застава', 'depozito']),
    gap('G1', 'sondern', I.conjunction, 'Die Wohnung ist nicht nur teuer, ', ' auch viel zu klein für unsere Familie.', 'sondern', ['aber', 'oder'],
      ['The flat is not only expensive but also far too small for our family.', 'Квартира не только дорогая, но и слишком маленькая для нашей семьи.', 'Квартира не тільки дорога, а й надто мала для нашої родини.', 'Daire yalnızca pahalı değil, aynı zamanda ailemiz için çok küçük.'], 'sondern / aber / oder'),
    gap('G2', 'wäre gekommen', I.auxiliary, 'Ich ', ' gestern gern zur Besichtigung gekommen, aber ich musste arbeiten.', 'wäre', ['hätte', 'war'],
      ['I would have liked to come to the viewing yesterday, but I had to work.', 'Вчера я бы с удовольствием пришёл на просмотр, но мне нужно было работать.', 'Учора я б охоче прийшов на перегляд, але мені треба було працювати.', 'Dün daireyi görmeye gelmek isterdim ama çalışmam gerekiyordu.'], AUX_K2),
    gap('G3', 'Hätte … geschlossen', I.participle, 'Hätte ich doch die Fenster ', '! Jetzt ist der ganze Teppich nass.', 'geschlossen', ['schließen', 'schloss'],
      ['If only I had closed the windows! Now the whole carpet is wet.', 'Если бы я только закрыл окна! Теперь весь ковёр мокрый.', 'Якби я тільки зачинив вікна! Тепер увесь килим мокрий.', 'Keşke pencereleri kapatsaydım! Şimdi bütün halı ıslak.'], 'schließen'),
    gap('G4', 'sich kümmern um', I.prep, 'Unsere Vermieterin kümmert sich immer sofort ', ' jedes Problem.', 'um', ['an', 'über'],
      ['Our landlady always deals with every problem straight away.', 'Наша хозяйка всегда сразу занимается каждой проблемой.', 'Наша власниця завжди одразу береться за кожну проблему.', 'Ev sahibemiz her sorunla hemen ilgileniyor.'], 'um / an / über'),
    gap('G4', 'Wovon', I.qword, '', ' träumst du? – Von einer Wohnung mit Garten.', 'Wovon', ['Woran', 'Worüber'],
      ['What do you dream of? – A flat with a garden.', 'О чём ты мечтаешь? – О квартире с садом.', 'Про що ти мрієш? – Про квартиру із садом.', 'Neyi hayal ediyorsun? – Bahçeli bir daireyi.'], 'träumen von', { c: 'p7_woran' }),
    gap('G5', 'trotz des Regens', I.article, 'Trotz ', ' Regens haben die Kinder den ganzen Nachmittag im Hof gespielt.', 'des', ['der', 'dem'],
      ['In spite of the rain the children played in the yard all afternoon.', 'Несмотря на дождь, дети всю вторую половину дня играли во дворе.', 'Попри дощ, діти всю другу половину дня гралися у дворі.', 'Yağmura rağmen çocuklar bütün öğleden sonra avluda oynadı.'], 'der Regen'),
    gap('K1', 'durfte nicht', I.modalPast, 'Bei uns ', ' man am Sonntag nicht laut sein. Das war streng verboten.', 'durfte', ['musste', 'wollte'],
      ['In our family you were not allowed to be noisy on Sundays. That was strictly forbidden.', 'У нас по воскресеньям нельзя было шуметь. Это было строго запрещено.', 'У нас у неділю не можна було шуміти. Це було суворо заборонено.', 'Bizde pazar günleri gürültü yapmak yasaktı. Bu kesinlikle yasaktı.'], 'dürfen'),
    gap('K2', 'Rücksicht nehmen', I.word, 'Es wäre schön, wenn Sie etwas mehr ', ' auf die anderen Mieter nehmen könnten.', 'Rücksicht', ['Kaution', 'Miete'],
      ['It would be nice if you could show a little more consideration for the other tenants.', 'Было бы хорошо, если бы вы немного больше считались с другими жильцами.', 'Було б добре, якби ви трохи більше зважали на інших мешканців.', 'Diğer kiracılara biraz daha saygı gösterebilirseniz güzel olur.'],
      ['consideration', 'внимание к другим', 'увага до інших', 'saygı, anlayış']),
    gap('K3', 'Das tut mir schrecklich leid.', I.word, 'Oh, Entschuldigung! Das tut mir ', ' leid. Es kommt nicht wieder vor.', 'schrecklich', ['lächerlich', 'merkwürdig'],
      ['Oh, sorry! I am terribly sorry. It will not happen again.', 'Ой, извините! Мне ужасно жаль. Больше такого не повторится.', 'Ой, вибачте! Мені страшенно шкода. Більше такого не повториться.', 'Ah, affedersiniz! Çok ama çok üzgünüm. Bir daha olmayacak.'],
      ['terribly', 'ужасно', 'страшенно', 'çok, son derece']),
    gap('K4', 'bezahlbar', I.ending, 'Seit Monaten suche ich eine ', ' Wohnung, aber alles ist viel zu teuer.', 'bezahlbare', ['bezahlbar', 'bezahlbaren'],
      ['I have been looking for an affordable flat for months, but everything is far too expensive.', 'Я уже несколько месяцев ищу доступную по цене квартиру, но всё слишком дорого.', 'Я вже кілька місяців шукаю доступну за ціною квартиру, але все надто дороге.', 'Aylardır uygun fiyatlı bir daire arıyorum ama her şey çok pahalı.'], 'bezahlbar'),
  ],
}

export default check
