-- Additive upgrade: original submissions, feedback and public files remain intact.
ALTER TABLE public.pronunciation_prompts ADD COLUMN IF NOT EXISTS level text
  CHECK (level IN ('A1.1','A1.2','A2.1','A2.2','B1.1','B1.2'));
ALTER TABLE public.pronunciation_prompts ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.pronunciation_prompts ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
CREATE INDEX IF NOT EXISTS pronunciation_prompts_level_active_idx ON public.pronunciation_prompts (level, sort_order) WHERE is_active;
ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS prompt_id uuid REFERENCES public.pronunciation_prompts(id) ON DELETE SET NULL;
ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS prompt_title text;
CREATE INDEX IF NOT EXISTS submissions_prompt_id_idx ON public.submissions(prompt_id);
CREATE SCHEMA IF NOT EXISTS pronunciation_private;
REVOKE ALL ON SCHEMA pronunciation_private FROM PUBLIC, anon;
GRANT USAGE ON SCHEMA pronunciation_private TO authenticated;
CREATE OR REPLACE FUNCTION pronunciation_private.can_access_submission(p_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
 SELECT (SELECT auth.uid()) IS NOT NULL AND EXISTS (
   SELECT 1 FROM public.submissions s WHERE s.id = p_id AND
   (s.user_id = (SELECT auth.uid()) OR (SELECT monthly_booking_private.current_profile_role()) IN ('teacher','admin'))
 );
$$;
REVOKE ALL ON FUNCTION pronunciation_private.can_access_submission(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION pronunciation_private.can_access_submission(uuid) TO authenticated;
CREATE TABLE public.pronunciation_messages (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 submission_id uuid NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
 sender_id uuid NOT NULL REFERENCES public.profiles(id),
 sender_role text NOT NULL DEFAULT 'student' CHECK (sender_role IN ('student','teacher','admin')),
 text_content text NOT NULL DEFAULT '' CHECK (char_length(text_content) <= 5000),
 audio_path text,
 created_at timestamptz NOT NULL DEFAULT now(),
 seen_at timestamptz,
 CONSTRAINT pronunciation_message_not_empty CHECK (length(btrim(text_content)) > 0 OR audio_path IS NOT NULL)
);
CREATE INDEX pronunciation_messages_thread_created_idx ON public.pronunciation_messages(submission_id,created_at,id);
CREATE INDEX pronunciation_messages_sender_idx ON public.pronunciation_messages(sender_id);
CREATE INDEX pronunciation_messages_unseen_idx ON public.pronunciation_messages(submission_id) WHERE seen_at IS NULL;
ALTER TABLE public.pronunciation_messages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.pronunciation_messages FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON public.pronunciation_messages TO authenticated;
CREATE POLICY "Conversation participants read messages" ON public.pronunciation_messages FOR SELECT TO authenticated
 USING ((SELECT pronunciation_private.can_access_submission(submission_id)));
CREATE POLICY "Participants send their own messages" ON public.pronunciation_messages FOR INSERT TO authenticated
 WITH CHECK (sender_id = (SELECT auth.uid()) AND (SELECT pronunciation_private.can_access_submission(submission_id)));
INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
 VALUES('pronunciation_audio','pronunciation_audio',false,26214400,ARRAY['audio/webm','audio/mp4','audio/ogg','audio/wav','audio/mpeg'])
 ON CONFLICT(id) DO NOTHING;
CREATE POLICY "Pronunciation owners upload" ON storage.objects FOR INSERT TO authenticated
 WITH CHECK (bucket_id = 'pronunciation_audio' AND (storage.foldername(name))[1] = (SELECT auth.uid())::text);
CREATE POLICY "Pronunciation participants listen" ON storage.objects FOR SELECT TO authenticated USING (
 bucket_id = 'pronunciation_audio' AND (
 (storage.foldername(name))[1] = (SELECT auth.uid())::text
 OR (SELECT monthly_booking_private.current_profile_role()) IN ('teacher','admin')
 OR EXISTS(SELECT 1 FROM public.pronunciation_messages m WHERE m.audio_path = 'storage://pronunciation_audio/' || name AND pronunciation_private.can_access_submission(m.submission_id))
 ));
CREATE OR REPLACE FUNCTION pronunciation_private.validate_message()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE actor uuid := (SELECT auth.uid()); actual_role text;
BEGIN
 IF actor IS NULL OR NEW.sender_id <> actor OR NOT pronunciation_private.can_access_submission(NEW.submission_id) THEN
   RAISE EXCEPTION 'Not authorized';
 END IF;
 actual_role := (SELECT p.role FROM public.profiles p WHERE p.id = actor);
 NEW.sender_role := CASE WHEN actual_role IN ('teacher','admin') THEN actual_role ELSE 'student' END;
 NEW.created_at := now(); NEW.seen_at := NULL;
 IF NEW.audio_path IS NOT NULL AND (
   NEW.audio_path NOT LIKE 'storage://pronunciation_audio/' || actor::text || '/%'
   OR NOT EXISTS(SELECT 1 FROM storage.objects o WHERE o.bucket_id = 'pronunciation_audio' AND 'storage://pronunciation_audio/' || o.name = NEW.audio_path)
 ) THEN RAISE EXCEPTION 'Invalid recording'; END IF;
 RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION pronunciation_private.validate_message() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER pronunciation_message_validate BEFORE INSERT ON public.pronunciation_messages
 FOR EACH ROW EXECUTE FUNCTION pronunciation_private.validate_message();
CREATE OR REPLACE FUNCTION pronunciation_private.update_conversation_status()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
BEGIN
 IF (SELECT auth.uid()) IS NULL OR NEW.sender_id <> (SELECT auth.uid()) THEN RAISE EXCEPTION 'Not authorized'; END IF;
 UPDATE public.submissions SET status = CASE WHEN NEW.sender_role IN ('teacher','admin') THEN 'reviewed' ELSE 'pending' END WHERE id = NEW.submission_id;
 RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION pronunciation_private.update_conversation_status() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER pronunciation_message_status AFTER INSERT ON public.pronunciation_messages
 FOR EACH ROW EXECUTE FUNCTION pronunciation_private.update_conversation_status();
CREATE OR REPLACE FUNCTION pronunciation_private.mark_seen(p_submission_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
BEGIN
 IF NOT pronunciation_private.can_access_submission(p_submission_id) THEN RAISE EXCEPTION 'Not authorized'; END IF;
 UPDATE public.pronunciation_messages SET seen_at = now()
 WHERE submission_id = p_submission_id AND sender_id <> (SELECT auth.uid()) AND seen_at IS NULL
 AND (CASE WHEN (SELECT monthly_booking_private.current_profile_role()) IN ('teacher','admin') THEN sender_role = 'student' ELSE sender_role IN ('teacher','admin') END);
END;
$$;
REVOKE ALL ON FUNCTION pronunciation_private.mark_seen(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION pronunciation_private.mark_seen(uuid) TO authenticated;
CREATE OR REPLACE FUNCTION public.mark_pronunciation_seen(p_submission_id uuid)
RETURNS void LANGUAGE sql SECURITY INVOKER SET search_path = '' AS $$ SELECT pronunciation_private.mark_seen(p_submission_id); $$;
REVOKE ALL ON FUNCTION public.mark_pronunciation_seen(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mark_pronunciation_seen(uuid) TO authenticated;
-- Exact level access also applies to REST reads. Legacy family texts stay available to staff.
DROP POLICY IF EXISTS "Nutzer können Übungssätze sehen" ON public.pronunciation_prompts;
CREATE POLICY "Readers access released pronunciation levels" ON public.pronunciation_prompts FOR SELECT TO authenticated USING (
 (SELECT monthly_booking_private.current_profile_role()) IN ('teacher','admin') OR
 (is_active AND level = ANY(COALESCE((SELECT p.allowed_levels FROM public.profiles p WHERE p.id = (SELECT auth.uid())), ARRAY[]::text[])))
);
ALTER POLICY "Admins und Lehrer dürfen Übungssätze einfügen" ON public.pronunciation_prompts TO authenticated
 WITH CHECK ((SELECT monthly_booking_private.current_profile_role()) IN ('teacher','admin'));
ALTER POLICY "Admins und Lehrer dürfen Übungssätze bearbeiten" ON public.pronunciation_prompts TO authenticated
 USING ((SELECT monthly_booking_private.current_profile_role()) IN ('teacher','admin'))
 WITH CHECK ((SELECT monthly_booking_private.current_profile_role()) IN ('teacher','admin'));
ALTER POLICY "Admins und Lehrer dürfen Übungssätze löschen" ON public.pronunciation_prompts TO authenticated
 USING ((SELECT monthly_booking_private.current_profile_role()) IN ('teacher','admin'));

-- Sixty original continuous reading texts, ten per existing course level.
INSERT INTO public.pronunciation_prompts(id,cefr_level,level,title,sentence_de,focus,sort_order,is_active) VALUES
('6d2f8e95-6f87-510b-b244-0631733f8ff9','A1','A1.1','Guten Tag, das bin ich','Guten Tag, ich heiße Anna. Ich komme aus Polen und wohne jetzt in Hannover. Ich bin dreißig Jahre alt. Meine Familie ist klein. Mein Mann heißt Paul. Wir lernen zusammen Deutsch. Am Abend trinken wir Tee und lesen ein Buch.','ie und ch; kurze Satzpausen',1,true),
('d7280df2-9f87-5729-bd8f-19c9b47c9488','A1','A1.1','Mein Frühstück','Es ist sieben Uhr. Ich sitze in der Küche und frühstücke. Auf dem Tisch stehen Brot, Käse und eine Tasse Tee. Mein Sohn trinkt Milch. Er isst einen Apfel. Das Brot ist frisch. Wir haben Zeit und sprechen ein bisschen.','ü und st; Aufzählungen',2,true),
('25bdcac1-9272-5294-893f-c2063b4838b9','A1','A1.1','Unser Kursraum','Das ist unser Kursraum. Er ist hell und groß. Hier stehen zwölf Stühle und sechs Tische. An der Wand ist eine Tafel. Mein Heft liegt auf dem Tisch. Die Lehrerin kommt und sagt guten Morgen. Jetzt beginnt unser Deutschkurs.','sch und lange Vokale',3,true),
('b73f6228-c6c7-591b-ac83-2bae82a3b163','A1','A1.1','Eine neue Nachbarin','Ich wohne in der Gartenstraße. Meine Nachbarin heißt Leyla. Sie ist neu hier. Heute treffen wir uns vor dem Haus. Ich sage Hallo und frage: Wie geht es Ihnen? Leyla lächelt. Es geht ihr gut. Wir trinken später zusammen Kaffee.','ei und eu; Fragen',4,true),
('fd1297a1-999f-5759-b0d9-1f77c381d114','A1','A1.1','Am Samstag im Park','Heute ist Samstag. Die Sonne scheint. Mein Freund und ich gehen in den Park. Dort sind viele Bäume und Blumen. Wir sitzen auf einer Bank. Ein kleiner Hund spielt im Gras. Wir hören Musik und essen unser Brot.','a und r; ruhiger Rhythmus',5,true),
('a218b88e-9369-5472-b5fe-34c99d1ced76','A1','A1.1','Mein Zimmer','Mein Zimmer ist nicht groß, aber schön. Links steht mein Bett. Am Fenster steht ein Tisch. Auf dem Tisch liegt mein Deutschbuch. Der Stuhl ist blau. Ich lese hier gern. Am Abend mache ich die Lampe an und lerne neue Wörter.','z und sch; Wortbetonung',6,true),
('15c29bec-e14e-5f27-8f12-ea9e45145e97','A1','A1.1','Im kleinen Laden','Ich bin im Laden. Ich brauche Milch, Brot und drei Äpfel. Die Verkäuferin ist freundlich. Sie zeigt mir das Brot. Es kostet zwei Euro. Ich nehme auch Wasser. Dann bezahle ich und sage danke. Meine Tasche ist jetzt voll.','ä und ch; Zahlen',7,true),
('610e3f81-2a6f-5794-bb78-ef06cb7ece17','A1','A1.1','Meine Familie','Das ist ein Foto von meiner Familie. Meine Mutter heißt Maria. Sie kocht gern. Mein Vater heißt Oleg. Er hört gern Musik. Meine Schwester ist zwanzig Jahre alt. Sie lernt Deutsch wie ich. Wir telefonieren oft und lachen viel.','ie und ö; Namen deutlich sprechen',8,true),
('c8055fa7-7bb0-5027-9f3e-13d001eb728b','A1','A1.1','Der Weg zum Kurs','Mein Kurs beginnt um neun Uhr. Ich gehe um acht Uhr aus dem Haus. Die Haltestelle ist nah. Ich fahre mit dem Bus. Am Bahnhof steige ich aus. Die Schule ist rechts. Vor der Tür wartet mein Freund. Wir gehen zusammen hinein.','w und k; Satzende',9,true),
('4a6f7008-9439-5c6e-9d60-113e8945f800','A1','A1.1','Ein ruhiger Abend','Es ist Abend. Ich bin zu Hause. Mein Handy liegt auf dem Tisch. Heute lese ich ein kleines Buch. Meine Katze schläft auf dem Sofa. Ich trinke Wasser und höre leise Musik. Um zehn Uhr gehe ich ins Bett. Gute Nacht!','au und ng; gleichmäßiges Tempo',10,true),
('1b5c02d4-7217-56e0-8abb-906c20784e30','A1','A1.2','Ein Termin beim Arzt','Seit gestern tut mein Hals weh. Ich rufe in der Praxis an und möchte einen Termin machen. Die Mitarbeiterin fragt nach meinem Namen. Ich buchstabiere ihn langsam. Am Nachmittag ist ein Termin frei. Ich kann um drei Uhr kommen. Meine Versichertenkarte nehme ich mit. Danach bleibe ich zu Hause und trinke warmen Tee.','ch und ts; höfliche Fragen',1,true),
('add5b212-15af-55b5-b224-6282b5c39c13','A1','A1.2','Wir kochen zusammen','Am Freitag kommen zwei Freunde zu mir. Wir möchten zusammen eine Suppe kochen. Zuerst kaufen wir Gemüse auf dem Markt. Dann waschen wir die Karotten und schneiden die Kartoffeln. Meine Freundin kocht Wasser. Ich decke den Tisch. Die Suppe schmeckt gut, und wir essen noch Brot dazu. Später räumen wir die Küche auf.','sch und ü; Arbeitsfolge',2,true),
('924ee488-8b97-5070-ba23-eea0f03992e6','A1','A1.2','Ein Besuch im Schwimmbad','Meine Tochter kann schon gut schwimmen. Am Sonntag gehen wir ins Schwimmbad. Ich packe zwei Handtücher und unsere Badesachen ein. An der Kasse kaufen wir zwei Karten. Das Wasser ist angenehm warm. Meine Tochter schwimmt, und ich übe mit ihr. Nach einer Stunde machen wir eine Pause. Wir haben Hunger und essen eine Banane.','schw und au; Satzmelodie',3,true),
('6e15b015-d482-58e4-9fa2-25ba0c8dea72','A1','A1.2','Die Einladung','Nächste Woche habe ich Geburtstag. Ich möchte mit meinen Nachbarn feiern. Die Feier beginnt am Samstag um vier Uhr. Ich schreibe eine kurze Einladung und lege sie in ihre Briefkästen. Jeder kann etwas zu essen mitbringen. Ich kaufe Getränke und backe einen Kuchen. Wir können im Garten sitzen. Bei Regen feiern wir in meiner Wohnung.','ei und ü; Betonung von Zeitangaben',4,true),
('93e4a1ed-cb70-5f0a-9dd2-cf6b2a9c9699','A1','A1.2','Auf dem Wochenmarkt','Am Mittwoch ist Markt auf dem großen Platz. Ich gehe mit meinem Korb dorthin. An einem Stand gibt es frische Äpfel und Birnen. Ich möchte ein Kilo Äpfel kaufen. Die Verkäuferin lässt mich einen Apfel probieren. Er schmeckt süß. Am nächsten Stand kaufe ich Kartoffeln. Zum Schluss hole ich Blumen für meine Küche.','ö und pf; Mengenangaben',5,true),
('5b3316e2-4a9f-5689-ba11-e5d0dc420f2b','A1','A1.2','Eine Wohnung besichtigen','Wir suchen eine neue Wohnung. Unsere Wohnung ist zu klein. Heute sehen wir uns eine Wohnung in der Nordstraße an. Sie hat drei Zimmer und einen Balkon. Die Küche ist hell. Neben dem Haus ist ein Spielplatz. Die Miete ist für uns etwas hoch. Wir möchten noch eine Nacht darüber schlafen und morgen anrufen.','w und ü; sinnvolle Pausen',6,true),
('00cedd4e-cf66-50ae-a181-e687d85a8379','A1','A1.2','Ein Ausflug mit dem Zug','Morgen besuchen wir meine Schwester in Bremen. Unser Zug fährt um halb zehn. Wir müssen früh aufstehen und die Taschen packen. Am Bahnhof kaufen wir noch ein Brötchen. Auf der Anzeige steht Gleis sieben. Im Zug sitzen wir am Fenster. Meine Schwester wartet am Bahnhof auf uns. Zusammen fahren wir mit der Straßenbahn zu ihr.','z und ü; Zahlen und Uhrzeiten',7,true),
('0022c931-279a-5050-ac2d-459c1e978cd1','A1','A1.2','In der Bibliothek','Ich möchte mehr auf Deutsch lesen. Deshalb gehe ich heute in die Bibliothek. Eine Mitarbeiterin erklärt mir die Anmeldung. Ich brauche meinen Ausweis und bekomme eine Karte. Im ersten Stock finde ich leichte Bücher. Ich nehme eine kurze Geschichte mit vielen Bildern. Das Buch darf ich vier Wochen behalten. Nächste Woche möchte ich wiederkommen.','b und ch; Fragesätze',8,true),
('b3fd31c6-efa8-5a64-85d9-7d419b4c42f4','A1','A1.2','Ein verlorener Schlüssel','Ich stehe vor meiner Haustür und suche meinen Schlüssel. Er ist nicht in meiner Jacke. Auch in meiner Tasche finde ich ihn nicht. Ich rufe meinen Mann an. Er ist noch bei der Arbeit. Zum Glück hat unsere Nachbarin einen zweiten Schlüssel. Sie öffnet mir die Tür. Mein Schlüssel liegt auf dem Küchentisch.','schl und ü; Hauptakzente',9,true),
('8cd6b9c9-8eaf-5a08-863b-27e712dbc484','A1','A1.2','Der neue Stundenplan','Unser Deutschkurs hat ab Montag neue Zeiten. Wir lernen jetzt am Vormittag von neun bis zwölf Uhr. Am Dienstag üben wir besonders viel Sprechen. Am Donnerstag lesen wir kurze Texte. Die Lehrerin erklärt den Stundenplan langsam. Ich schreibe die Zeiten in meinen Kalender. Nach dem Kurs kann ich meine Tochter von der Schule abholen. Das passt gut für mich.','st und sp; Satzverbindungen',10,true),
('b2ae5915-20dd-5018-8921-6afe5be0f1fd','A2','A2.1','Mein erster Arbeitstag','Gestern hatte ich meinen ersten Arbeitstag in einer Bäckerei. Ich war ein bisschen nervös und bin sehr früh losgefahren. Meine Kollegin hat mir zuerst die Küche gezeigt. Danach haben wir zusammen die Brötchen sortiert. An der Kasse musste ich oft nachfragen, weil die Kunden schnell gesprochen haben. Meine Kollegin war geduldig und hat mir geholfen. Am Abend war ich müde, aber auch stolz. Heute kenne ich schon mehr Wörter für meine Arbeit.','ei und ar; Vergangenheitsformen',1,true),
('acb54d47-e197-56ca-9eb7-a890abce63f6','A2','A2.1','Das Fahrrad ist kaputt','Auf dem Weg zum Kurs ist mein Fahrrad kaputtgegangen. Der hintere Reifen war plötzlich leer. Ich habe das Rad bis zur nächsten Werkstatt geschoben. Der Mechaniker hat ein kleines Loch gefunden. Er konnte den Reifen noch am selben Vormittag reparieren. Deshalb bin ich mit dem Bus zur Schule gefahren. Meiner Lehrerin habe ich eine kurze Nachricht geschickt. Nach dem Kurs habe ich mein Fahrrad abgeholt und bin vorsichtig nach Hause gefahren.','f und pf; Begründungen',2,true),
('2c6b8ac4-28e2-556d-950e-9937d7da0da9','A2','A2.1','Ein Paket für die Nachbarin','Als ich gestern nach Hause kam, klingelte der Paketbote. Meine Nachbarin war nicht da, und ich habe ihr Paket angenommen. Am Abend habe ich einen Zettel an ihre Tür gehängt. Darauf stand, dass sie bei mir klingeln kann. Eine Stunde später kam sie vorbei. In dem Paket waren Bücher für ihre Tochter. Wir haben kurz über die Schule gesprochen. Zum Dank hat sie mich am Wochenende zum Kaffee eingeladen.','p und k; Satzglieder verbinden',3,true),
('5ec73679-e979-5ef6-bbac-8d14af8d2651','A2','A2.1','Ein Rezept von meiner Mutter','Meine Mutter hat mir am Telefon ein einfaches Rezept erklärt. Ich wollte einen Apfelkuchen backen, hatte aber wenig Erfahrung. Zuerst habe ich die Zutaten aufgeschrieben und alles eingekauft. Dann habe ich den Teig vorbereitet. Während der Kuchen im Ofen war, habe ich die Küche aufgeräumt. Nach vierzig Minuten roch die ganze Wohnung nach Äpfeln. Der Kuchen war etwas dunkel, hat aber gut geschmeckt. Meiner Mutter habe ich ein Foto geschickt.','r und ch; Reihenfolge hörbar machen',4,true),
('3dfcf736-84e5-599d-a492-b780ffc491c4','A2','A2.1','Sport nach der Arbeit','Seit einem Monat besuche ich einen Sportkurs im Stadtteilzentrum. Der Kurs findet immer mittwochs nach meiner Arbeit statt. Am Anfang waren die Übungen ziemlich anstrengend. Jetzt kann ich schon länger mitmachen. Die Trainerin zeigt jede Bewegung langsam und erklärt sie noch einmal. In der Gruppe sind Menschen aus verschiedenen Ländern. Nach dem Training trinken wir manchmal zusammen Wasser und unterhalten uns. Ich bewege mich mehr und lerne dabei neue Leute kennen.','sp und st; längere Wortgruppen',5,true),
('dbe98ecb-4d32-5767-be6c-f54728c93f7d','A2','A2.1','Ein Besuch auf dem Land','Letztes Wochenende haben wir Freunde auf dem Land besucht. Sie wohnen in einem alten Haus mit einem großen Garten. Wir sind morgens mit dem Zug gefahren. Am Bahnhof haben sie uns abgeholt. Nach dem Mittagessen haben wir einen langen Spaziergang gemacht. Die Kinder haben Pferde gesehen und viele Fragen gestellt. Abends haben wir draußen gesessen, bis es kühl wurde. Am Sonntag wollten die Kinder gar nicht wieder nach Hause fahren.','l und au; weiche Übergänge',6,true),
('2f3b292b-8bdb-5007-90cb-278f9c00fc02','A2','A2.1','Die Anmeldung im Verein','Ich möchte in einem Verein Fußball spielen und habe mich im Internet informiert. Ein Verein in meiner Nähe bietet ein kostenloses Probetraining an. Ich habe eine E-Mail geschrieben und nach der Uhrzeit gefragt. Der Trainer hat schnell geantwortet. Ich soll Sportschuhe und etwas zu trinken mitbringen. Am Donnerstag gehe ich zum ersten Mal hin. Ein Freund begleitet mich, weil er auch gern Fußball spielt. Wir freuen uns auf das Training.','ng und ei; höfliche Bitten',7,true),
('ad61d4d1-2223-533e-974e-51a2d97806b0','A2','A2.1','Ein Ausfall der Heizung','Heute Morgen war es in unserer Wohnung sehr kalt. Obwohl ich die Heizung aufgedreht habe, blieb sie kalt. Ich habe den Vermieter angerufen und das Problem beschrieben. Er hat sofort einen Handwerker bestellt. Bis der Handwerker kam, haben wir warme Pullover angezogen und Tee getrunken. Zum Glück war nur ein kleines Teil kaputt. Am Nachmittag wurde die Wohnung wieder warm. Ich war froh, dass der Vermieter so schnell reagiert hat.','h und z; Problem erklären',8,true),
('c5d7b014-5b84-57f5-bfb0-67e3bcb65066','A2','A2.1','Lernen in der Gruppe','Vor der letzten Prüfung haben wir uns zu dritt in der Bibliothek getroffen. Jeder hat eine kleine Aufgabe vorbereitet. Zuerst haben wir neue Wörter wiederholt. Danach haben wir kurze Gespräche geübt. Wenn jemand einen Fehler gemacht hat, haben die anderen geholfen. Niemand musste sich schämen. Nach einer Stunde haben wir eine Pause gemacht. Das gemeinsame Lernen war angenehm, und wir möchten uns jetzt jede Woche treffen.','ü und gr; Betonung wichtiger Wörter',9,true),
('99feaf25-8ae7-58f7-a492-e2aa4a501707','A2','A2.1','Ein Tag ohne Handy','Am Sonntag habe ich mein Handy zu Hause vergessen. Zuerst war ich unruhig, weil ich meine Nachrichten nicht lesen konnte. Im Park habe ich mich dann auf eine Bank gesetzt und die Menschen beobachtet. Später habe ich in einem Café eine Zeitung gelesen. Ohne Handy hatte ich viel mehr Zeit. Am Abend habe ich meine Nachrichten beantwortet. Es war nichts Dringendes dabei. Vielleicht lasse ich mein Handy am nächsten Sonntag wieder zu Hause.','a und ei; deutliche Satzenden',10,true),
('bea3e65f-1668-5539-a4c3-ce044fe067e1','A2','A2.2','Eine Reise mit Hindernissen','Wir wollten am Samstag früh zu meinen Eltern fahren, doch unser Zug hatte Verspätung. Auf dem Bahnsteig war es voll, und die Durchsage war schwer zu verstehen. Eine Mitarbeiterin erklärte uns, dass wir einen anderen Zug nehmen konnten. Weil wir in einer fremden Stadt umsteigen mussten, war ich zunächst unsicher. Zum Glück zeigte uns ein Mitreisender das richtige Gleis. Wir kamen zwei Stunden später an als geplant. Meine Eltern hatten das Essen warm gehalten. Trotz der langen Fahrt wurde es noch ein schöner Abend.','r und ch; Nebensatzpausen',1,true),
('3243b764-4bfc-5fc6-8c24-1a49962988ff','A2','A2.2','Ein Gespräch über Arbeitszeiten','Seit meine Tochter in die Schule geht, passen meine Arbeitszeiten nicht mehr gut zu unserem Alltag. Deshalb habe ich meine Chefin um ein Gespräch gebeten. Ich habe erklärt, dass ich am Nachmittag früher zu Hause sein muss. Dafür könnte ich morgens eine Stunde früher anfangen. Meine Chefin wollte zuerst mit dem Team sprechen. Einige Tage später hat sie meinem Vorschlag zugestimmt. Wir probieren die neue Regelung zunächst für einen Monat aus. Ich bin froh, dass ich offen über mein Problem gesprochen habe.','ts und ei; Wünsche betonen',2,true),
('51347d93-a3a8-50aa-811e-4ea2816386f9','A2','A2.2','Unser gemeinsamer Innenhof','Der Innenhof unseres Hauses war lange leer und ungemütlich. Bei einem Treffen haben wir Nachbarn überlegt, wie wir ihn verändern könnten. Einige wollten Blumen pflanzen, andere wünschten sich eine Bank. Gemeinsam haben wir einen Plan gemacht und beim Vermieter nachgefragt. Nachdem er zugestimmt hatte, haben wir an einem Samstag alles vorbereitet. Jeder hat eine kleine Aufgabe übernommen. Jetzt sitzen wir abends oft draußen. Der Hof ist schöner geworden, und wir kennen uns im Haus viel besser.','h und ö; Gegensätze hörbar machen',3,true),
('194df28b-7175-5ffa-9813-2c5967cc2cb9','A2','A2.2','Eine Reklamation im Geschäft','Vor zwei Wochen habe ich neue Schuhe gekauft. Schon nach wenigen Tagen hat sich an einem Schuh die Sohle gelöst. Deshalb bin ich mit den Schuhen und dem Kassenbon ins Geschäft gegangen. Ich habe der Verkäuferin ruhig erklärt, was passiert ist. Sie hat die Schuhe geprüft und eine Kollegin dazugeholt. Leider war meine Größe nicht mehr da. Wir haben vereinbart, dass das Geschäft mich anruft, sobald ein neues Paar ankommt. Die freundliche Lösung hat mich erleichtert.','k und r; sachlicher Ton',4,true),
('cdc98a2c-2e24-505e-bcc8-a1e68bfe2553','A2','A2.2','Hilfe beim Deutschlernen','Mein Nachbar lernt seit Kurzem Deutsch und hat mich gefragt, wie ich zu Hause übe. Ich habe ihm gezeigt, dass ich jeden Tag nur wenige neue Wörter lerne und ältere Wörter regelmäßig wiederhole. Außerdem höre ich kurze Texte mehrmals an. Zuerst achte ich auf den Inhalt, später auf die Aussprache. Wir haben beschlossen, uns zweimal in der Woche für zwanzig Minuten zu treffen. Dabei wollen wir über Alltagsthemen sprechen. Ich kann selbst noch nicht alles richtig sagen, aber wir helfen uns gegenseitig.','ch und l; indirekte Fragen',5,true),
('1c914afb-1958-5045-bda2-d609de2bd365','A2','A2.2','Ein freiwilliger Einsatz','In unserem Stadtteil wurde am Samstag Müll gesammelt. Ich habe durch einen Aushang davon erfahren und mich angemeldet. Am Treffpunkt bekamen wir Handschuhe und große Säcke. Eine Organisatorin erklärte, welche Wege wir sauber machen sollten. Ich war mit einer älteren Frau in einer Gruppe. Während wir arbeiteten, erzählte sie mir viel über den Stadtteil. Nach zwei Stunden waren die Wege deutlich sauberer. Zum Schluss gab es Suppe für alle. Beim nächsten Mal möchte ich wieder mithelfen.','f und ei; flüssige Aufzählungen',6,true),
('cff8a034-8b6e-5258-affc-6958091ef60b','A2','A2.2','Ein Missverständnis am Telefon','Ich hatte telefonisch einen Termin beim Friseur vereinbart. Als ich am Dienstag im Salon ankam, war mein Name nicht im Kalender. Die Mitarbeiterin fragte noch einmal nach meiner Telefonnummer. Dann stellte sich heraus, dass sie Donnerstag statt Dienstag verstanden hatte. Früher hätte ich mich in so einer Situation sehr geärgert. Diesmal blieben wir beide ruhig und suchten eine Lösung. Nach einer kurzen Wartezeit konnte ich doch noch bleiben. In Zukunft wiederhole ich Datum und Uhrzeit am Ende des Gesprächs.','st und ä; nachfragen und korrigieren',7,true),
('4533b44b-4ec1-5147-8a69-3345d5df7933','A2','A2.2','Ein Haustier auf Zeit','Unsere Freunde sind für eine Woche verreist und haben uns gebeten, auf ihre Katze aufzupassen. Jeden Morgen bin ich in ihre Wohnung gegangen. Ich habe frisches Wasser hingestellt, Futter gegeben und das Katzenklo sauber gemacht. Am ersten Tag hat sich die Katze unter dem Sofa versteckt. Nach einigen Tagen kam sie schon zur Tür, wenn sie mich hörte. Ich habe unseren Freunden ein Foto geschickt, damit sie sich keine Sorgen machen. Als sie zurückkamen, war die Katze trotzdem am glücklichsten.','au und sch; Erzählrhythmus',8,true),
('4c550a8b-95b1-5a53-ac3c-b2ad48ea592d','A2','A2.2','Die Entscheidung für einen Kurs','Ich möchte mich beruflich weiterentwickeln und suche einen Computerkurs. Im Internet habe ich zwei passende Angebote gefunden. Ein Kurs findet am Wochenende statt, der andere an zwei Abenden in der Woche. Obwohl der Abendkurs günstiger ist, habe ich mich für den Wochenendkurs entschieden. Nach der Arbeit bin ich oft zu müde, um konzentriert zu lernen. Vor der Anmeldung habe ich gefragt, ob man einen eigenen Laptop braucht. Das ist zum Glück nicht nötig. Die Schule stellt Geräte zur Verfügung.','ü und ei; Gründe klar gliedern',9,true),
('f6fed4f3-e48e-5cc0-91e6-270734c1e369','A2','A2.2','Ein Gespräch mit der Lehrerin','Die Lehrerin meines Sohnes hat mich zu einem Gespräch eingeladen. Zuerst war ich besorgt, weil ich nicht wusste, worum es ging. Im Gespräch erklärte sie, dass mein Sohn im Unterricht gut mitarbeitet, aber seine Hausaufgaben oft vergisst. Gemeinsam haben wir überlegt, wie wir ihm helfen können. Er bekommt jetzt ein kleines Heft, in das er seine Aufgaben schreibt. Zu Hause schauen wir jeden Nachmittag kurz hinein. Nach zwei Wochen klappt es schon besser. Die gemeinsame Lösung war hilfreicher als Schimpfen.','l und r; ruhige Fragemelodie',10,true),
('19846618-a6c3-5001-84d5-06b21b99dff5','B1','B1.1','Ein neuer Beruf als Chance','Nachdem ich viele Jahre im Verkauf gearbeitet hatte, wollte ich beruflich etwas Neues ausprobieren. Besonders die Arbeit mit älteren Menschen interessierte mich. Deshalb habe ich mich über eine Ausbildung im Pflegebereich informiert. Die Beratung war hilfreich, trotzdem hatte ich Zweifel: Würde mein Deutsch für den Unterricht ausreichen? Eine Beraterin empfahl mir ein Praktikum. Dort merkte ich, dass ich vieles verstehen konnte und bei Unklarheiten nachfragen durfte. Jetzt bereite ich meine Bewerbung vor. Der Wechsel wird bestimmt anstrengend, aber ich möchte es versuchen. Für mich bedeutet Lernen auch, neue Möglichkeiten zu entdecken.','b und ch; längere Satzbögen',1,true),
('b5bd057d-17ae-5fac-824a-a8a75fe827ed','B1','B1.1','Nachhaltiger einkaufen','Früher habe ich im Supermarkt häufig mehr gekauft, als ich brauchte. Am Ende der Woche musste ich manchmal Lebensmittel wegwerfen. Das hat mich gestört, deshalb plane ich meine Einkäufe inzwischen genauer. Bevor ich losgehe, schaue ich in den Kühlschrank und schreibe eine Liste. Außerdem kaufe ich kleinere Mengen, auch wenn große Packungen manchmal günstiger erscheinen. Ganz ohne spontane Einkäufe klappt es noch nicht. Trotzdem landet deutlich weniger im Müll. Für mich ist diese Veränderung gut machbar, weil sie kein besonderes Wissen verlangt. Sie kostet nur ein wenig Zeit und Aufmerksamkeit.','ch und au; Argumente betonen',2,true),
('f0c48467-2e7b-53ef-acde-b08564514ba9','B1','B1.1','Freundschaften in einer neuen Stadt','Als ich nach Hannover gezogen bin, kannte ich außer meiner Schwester niemanden. Nach der Arbeit blieb ich meistens zu Hause und fühlte mich oft allein. Meine Schwester schlug vor, einen Kurs zu besuchen, der nichts mit meinem Beruf zu tun hatte. Ich entschied mich für einen Fotokurs. Anfangs fiel es mir schwer, die anderen anzusprechen. Doch bei den gemeinsamen Spaziergängen kamen Gespräche fast von selbst zustande. Aus zwei Bekanntschaften sind inzwischen Freundschaften geworden. Ich habe gelernt, dass Kontakte Zeit brauchen. Manchmal reicht ein gemeinsames Interesse, damit aus einem ersten Gespräch mehr entsteht.','fr und sch; Gefühle im Ton',3,true),
('a32ba623-4578-55b4-9b44-b717c857a46c','B1','B1.1','Eine faire Aufgabenverteilung','In unserer Wohngemeinschaft gab es immer wieder Streit über die Hausarbeit. Einige putzten häufig, andere bemerkten den Schmutz angeblich gar nicht. Irgendwann setzten wir uns zusammen, statt nur kurze Nachrichten in die Gruppe zu schreiben. Jeder erklärte, welche Aufgaben er übernehmen konnte und was ihn störte. Wir erstellten einen einfachen Plan, der jede Woche wechselt. Außerdem vereinbarten wir, rechtzeitig Bescheid zu geben, wenn jemand keine Zeit hat. Seitdem ist nicht alles perfekt, aber die Stimmung ist besser. Besonders geholfen hat uns, einander zuzuhören und konkrete Absprachen zu treffen.','f und t; Gegensätze und Lösungen',4,true),
('525d59e3-5cad-543c-820a-b9316809645f','B1','B1.1','Ein sicherer Umgang mit Nachrichten','In einer Chatgruppe bekam ich eine Nachricht über eine angebliche Änderung bei unseren Kurszeiten. Viele Teilnehmende waren sofort beunruhigt. Bevor ich die Nachricht weiterleitete, schaute ich auf der Webseite der Schule nach. Dort stand nichts dazu. Ich rief im Büro an und erfuhr, dass es sich um eine alte Information handelte. Anschließend schrieb ich eine kurze Erklärung in die Gruppe. Die Situation hat mir gezeigt, wie schnell Missverständnisse entstehen können. Heute prüfe ich wichtige Nachrichten lieber einmal mehr. Dabei helfen mir das Datum, die Quelle und eine direkte Nachfrage bei der zuständigen Stelle.','ng und ch; sachlich erklären',5,true),
('2824e504-aef5-5a89-9290-aa72f1d42342','B1','B1.1','Eine kleine Reise allein','Zum ersten Mal seit vielen Jahren bin ich allein für ein Wochenende verreist. Ich hatte mir eine kleine Stadt ausgesucht, die gut mit dem Zug erreichbar war. Zuerst fand ich es ungewohnt, alle Entscheidungen selbst zu treffen. Niemand fragte, wann wir essen oder welches Museum wir besuchen wollten. Nach einigen Stunden begann ich, diese Freiheit zu genießen. In einem Café kam ich mit einer anderen Reisenden ins Gespräch. Wir tauschten Tipps aus und gingen dann wieder eigene Wege. Zu Hause freute ich mich auf meine Familie. Trotzdem möchte ich eine solche Reise gern wiederholen.','ei und r; Erzähltempo variieren',6,true),
('92818a0b-1e3d-5f69-b023-f61637d49279','B1','B1.1','Homeoffice im Alltag','An zwei Tagen in der Woche arbeite ich von zu Hause aus. Dadurch spare ich den Arbeitsweg und kann morgens ruhiger beginnen. Allerdings war es anfangs schwierig, nach Feierabend wirklich aufzuhören. Mein Laptop stand auf dem Küchentisch, und ich beantwortete noch spät Nachrichten. Inzwischen habe ich einen festen Arbeitsplatz und klare Arbeitszeiten. Nach der letzten Aufgabe schalte ich den Computer aus und gehe kurz spazieren. Diese kleine Gewohnheit hilft mir, Arbeit und Freizeit zu trennen. Den Kontakt zu meinen Kolleginnen und Kollegen möchte ich trotzdem nicht verlieren. Deshalb bin ich auch gern regelmäßig im Büro.','h und o; Vor- und Nachteile',7,true),
('d0e1136a-e6ee-5b28-b3b8-37c744be5528','B1','B1.1','Gemeinsam eine Veranstaltung planen','Unser Deutschkurs organisiert einen kleinen Nachmittag für Familien und Freunde. Wir möchten zeigen, was wir in den letzten Monaten gelernt haben. Eine Gruppe bereitet kurze Geschichten vor, eine andere kümmert sich um Spiele für die Kinder. Ich bin für die Einladung zuständig. Zuerst hatte ich Angst, dabei Fehler zu machen. Die Lehrerin erklärte jedoch, dass wir uns gegenseitig helfen sollen. Gemeinsam haben wir den Text gelesen und verbessert. Bei der Planung merken wir, wie viel man mit Deutsch schon erreichen kann. Entscheidend ist, dass wir miteinander sprechen und nicht auf den perfekten Satz warten.','v und st; Informationen ordnen',8,true),
('8c963a66-e60b-5f88-bee3-73aa3f3e3df7','B1','B1.1','Mit Fehlern umgehen','In meinem ersten Jahr in Deutschland wollte ich möglichst keine Fehler machen. Deshalb habe ich oft geschwiegen, obwohl ich etwas sagen konnte. Das änderte sich bei einem Gespräch mit einer Kollegin. Sie erzählte mir, wie unsicher sie selbst beim Lernen einer anderen Sprache war. Seitdem versuche ich, Fehler als Teil des Lernens zu betrachten. Wenn ich ein Wort falsch benutze, schreibe ich mir später ein Beispiel auf. Natürlich gibt es Situationen, in denen Genauigkeit wichtig ist. Im Alltag hilft es mir aber mehr, freundlich nachzufragen und weiterzusprechen. So werde ich langsam sicherer.','f und ä; Betonung von Schlüsselsätzen',9,true),
('c5dc1e9e-43fb-5505-ae4a-82cdc74fac41','B1','B1.1','Ein Ort für alle Generationen','In unserem Stadtteil wurde ein leer stehender Laden in einen offenen Treffpunkt umgebaut. Dort kann man lesen, Kaffee trinken oder an kleinen Veranstaltungen teilnehmen. Besonders schön finde ich, dass Menschen verschiedener Generationen zusammenkommen. Eine Rentnerin bietet Hilfe beim Nähen an, während Jugendliche Fragen zum Smartphone beantworten. Niemand muss etwas kaufen, um bleiben zu dürfen. Ich besuche dort einmal im Monat ein Sprachcafé. Dabei üben wir Deutsch und sprechen über unseren Alltag. Der Treffpunkt zeigt, dass gute Begegnungen nicht viel kosten müssen. Wichtig sind ein offener Raum und Menschen, die ihre Zeit miteinander teilen.','ö und g; ruhige Satzmelodie',10,true),
('cacb3a6d-e789-5abc-9e94-f6eecfb36bdb','B1','B1.2','Ein Vorschlag im Betrieb','In unserem Betrieb werden Besprechungen häufig kurzfristig angesetzt. Dadurch können Mitarbeitende mit Teilzeitverträgen nicht immer teilnehmen. Bei der letzten Teamsitzung habe ich vorgeschlagen, einen festen Termin einzuführen und die wichtigsten Ergebnisse schriftlich festzuhalten. Zunächst befürchteten einige, dass dadurch zusätzliche Arbeit entstehen würde. Ich erklärte, dass kurze Notizen auch Rückfragen vermeiden könnten. Schließlich beschlossen wir, die Idee sechs Wochen lang auszuprobieren. Nach dieser Zeit wollen wir gemeinsam prüfen, ob sich die Zusammenarbeit verbessert hat. Ich finde es wichtig, Veränderungen nicht nur zu kritisieren oder zu fordern. Ein konkreter Vorschlag mit einer überschaubaren Testphase macht es leichter, gemeinsam eine Lösung zu finden.','sch und tr; überzeugend sprechen',1,true),
('6b4676fc-7a16-51d6-8c1c-4b5da00ffaf2','B1','B1.2','Wem gehört der öffentliche Raum?','Auf dem Platz vor unserer Bibliothek treffen sich abends häufig Jugendliche. Einige Anwohner fühlen sich durch die Gespräche und die Musik gestört. Andere finden, dass junge Menschen einen Ort brauchen, an dem sie kostenlos zusammenkommen können. Bei einem Treffen im Stadtteilzentrum wurden beide Seiten angehört. Die Jugendlichen erklärten, dass es in der Nähe kaum Angebote für sie gibt. Gemeinsam wurden feste Ruhezeiten und ein zusätzlicher Treffpunkt vorgeschlagen. Noch sind nicht alle zufrieden, aber das Gespräch war ein Anfang. Für mich zeigt die Situation, dass öffentlicher Raum unterschiedliche Bedürfnisse erfüllen muss. Dauerhafte Lösungen entstehen eher durch klare Regeln und Beteiligung als durch gegenseitige Vorwürfe.','r und ö; verschiedene Sichtweisen',2,true),
('876f98ba-930f-59f0-8b53-e7e09e235b6e','B1','B1.2','Lernen neben Beruf und Familie','Seit drei Monaten besuche ich einen Abendkurs, obwohl mein Alltag mit Beruf und Familie bereits gut gefüllt ist. In den ersten Wochen wollte ich jeden freien Moment zum Lernen nutzen. Bald merkte ich jedoch, dass ich ständig müde war und mir wenig merken konnte. Gemeinsam mit meiner Familie habe ich deshalb feste Lernzeiten vereinbart. An zwei Abenden kümmert sich mein Partner um das Essen, damit ich konzentriert arbeiten kann. Dafür bleibt der Sonntag weitgehend frei. Mein Fortschritt ist vielleicht langsamer als geplant, aber die neue Routine lässt sich durchhalten. Ich habe verstanden, dass ein realistischer Plan langfristig hilfreicher ist als ein besonders ehrgeiziger Anfang.','l und er; Pausen bei Nebensätzen',3,true),
('fd156fa0-66df-5eeb-8558-f3d99b3b7119','B1','B1.2','Eine Entscheidung im Verein','Unser Sportverein möchte seine Mitgliedsbeiträge erhöhen, weil die Kosten für die Halle gestiegen sind. Bei der Versammlung gab es dazu unterschiedliche Meinungen. Einige Mitglieder hielten die Erhöhung für notwendig, andere sorgten sich um Familien mit wenig Geld. Der Vorstand stellte die wichtigsten Ausgaben vor und beantwortete Fragen. Anschließend wurde vorgeschlagen, einen Sozialbeitrag und eine freiwillige Unterstützung einzuführen. Dieser Vorschlag fand breite Zustimmung. Mir hat gefallen, dass Zahlen erklärt wurden, bevor die Abstimmung begann. So konnten alle besser einschätzen, warum eine Veränderung nötig war. Eine faire Entscheidung bedeutet für mich nicht, dass jeder dasselbe zahlt, sondern dass möglichst viele weiter teilnehmen können.','ei und ng; Argumente gewichten',4,true),
('b080a8ae-7be6-5225-af48-1d7aae6f1f6c','B1','B1.2','Künstliche Intelligenz beim Lernen','Digitale Programme können beim Sprachenlernen nützlich sein. Sie erklären Wörter, lesen Texte vor und bieten Übungen zu verschiedenen Themen an. Ich nutze solche Hilfen gern, besonders wenn ich zu Hause eine kurze Frage habe. Trotzdem prüfe ich Antworten, die mir ungewöhnlich vorkommen. Ein Programm kennt meine persönliche Situation nicht immer und kann auch Fehler machen. Das Gespräch mit einer Lehrkraft bleibt deshalb wichtig. Sie hört, was ich eigentlich ausdrücken möchte, und kann gezielt nachfragen. Für mich ergänzen sich digitale Übungen und persönlicher Unterricht. Entscheidend ist, dass ich selbst aktiv bleibe, statt jede Aufgabe sofort von einem Programm lösen zu lassen.','k und ts; Fachwörter verständlich sprechen',5,true),
('2fa06ffd-6b82-5386-9c84-a4320c87bbc7','B1','B1.2','Ein Konflikt mit einem Nachbarn','Über mehrere Wochen hörte ich spät am Abend laute Musik aus der Nachbarwohnung. Zunächst ärgerte ich mich nur und erzählte anderen davon. Als ich schließlich an der Tür klingelte, versuchte ich bewusst, ruhig zu bleiben. Ich erklärte, wann ich schlafen muss und wie die Musik mich dabei stört. Mein Nachbar war überrascht, weil er nicht wusste, wie deutlich man die Bässe durch die Wand hört. Wir vereinbarten, dass er ab einer bestimmten Uhrzeit Kopfhörer benutzt. Seitdem hat sich die Situation verbessert. Das Gespräch war mir vorher unangenehm, doch es hat mehr bewirkt als meine stillen Vorwürfe. Manchmal fehlt der anderen Person einfach eine wichtige Information.','ch und kn; respektvoller Ton',6,true),
('13264420-65a8-54f1-984e-b001a5244341','B1','B1.2','Warum ich mich ehrenamtlich engagiere','Einmal pro Woche helfe ich in einer kleinen Fahrradwerkstatt, die von Freiwilligen organisiert wird. Dort unterstützen wir Menschen dabei, ihre Räder selbst zu reparieren. Als ich damit angefangen habe, wollte ich vor allem meine handwerklichen Kenntnisse nutzen. Inzwischen schätze ich besonders die Gespräche mit Menschen, denen ich sonst kaum begegnen würde. Nicht jeder Termin verläuft einfach: Manchmal fehlen Teile, manchmal braucht eine Erklärung viel Geduld. Trotzdem gehe ich meistens zufrieden nach Hause. Ich sehe unmittelbar, dass meine Zeit jemandem geholfen hat. Gleichzeitig lerne ich selbst weiter. Ehrenamt bedeutet für mich deshalb nicht nur, etwas zu geben, sondern auch Erfahrungen und neue Perspektiven zu gewinnen.','eh und ge; persönliche Haltung',7,true),
('5dc0cf34-6f7c-5e67-9728-22bbe90c5dc7','B1','B1.2','Ein bewusster Umgang mit Bewertungen','Bevor ich einen Kurs buche oder ein Gerät kaufe, lese ich häufig Bewertungen im Internet. Früher habe ich mich vor allem an der Zahl der Sterne orientiert. Heute schaue ich genauer hin. Mich interessiert, ob jemand konkrete Erfahrungen beschreibt und ob die Bewertung zu meinen eigenen Erwartungen passt. Ein Kurs kann für Anfänger hilfreich und für Fortgeschrittene zu langsam sein. Auch das Datum spielt eine Rolle, denn Angebote können sich verändern. Einzelne sehr positive oder negative Kommentare entscheiden deshalb nicht allein über meine Wahl. Bewertungen sind für mich eine erste Orientierung. Wenn eine Entscheidung wichtig ist, suche ich zusätzliche Informationen oder frage direkt beim Anbieter nach.','b und w; Einschränkungen betonen',8,true),
('8cf76d58-8428-59ef-b449-4301051413ba','B1','B1.2','Die Stadt aus einer anderen Perspektive','Vor Kurzem habe ich einen Spaziergang mit einer Bekannten gemacht, die einen Rollstuhl benutzt. Wir wollten gemeinsam ein Café besuchen und danach in die Bibliothek gehen. Schon auf dem Weg fiel mir auf, wie viele kleine Hindernisse ich sonst übersehe: eine hohe Bordsteinkante, Fahrräder auf dem Gehweg und eine schwere Eingangstür. Meine Bekannte erklärte, welche Wege gut funktionieren und wo sie Hilfe braucht. Gleichzeitig wollte sie nicht, dass ich alles ungefragt für sie übernehme. Der Nachmittag hat meinen Blick auf die Stadt verändert. Seitdem achte ich stärker darauf, ob Orte wirklich für alle zugänglich sind. Gute Absichten helfen, aber Zuhören und konkrete Verbesserungen sind ebenso wichtig.','st und sp; flüssig erzählen',9,true),
('6e667abd-3011-597c-9cf9-0c20c2c30e2d','B1','B1.2','Was Erfolg beim Sprachenlernen bedeutet','Vor einem Jahr hätte ich Erfolg beim Deutschlernen vor allem an einer guten Prüfungsnote gemessen. Heute denke ich auch an viele kleine Situationen: ein verständliches Telefonat, ein Gespräch mit der Lehrerin meines Kindes oder eine Frage bei der Arbeit. Solche Erlebnisse zeigen mir, dass ich die Sprache tatsächlich nutzen kann. Natürlich möchte ich meine Grammatik und Aussprache weiter verbessern. Trotzdem versuche ich, meinen Fortschritt nicht ständig mit dem anderer Menschen zu vergleichen. Jeder bringt andere Erfahrungen mit und hat unterschiedlich viel Zeit. Mein nächstes Ziel ist, in einer Besprechung meine Meinung klar zu erklären. Es ist ein kleines Ziel, aber für meinen Alltag ein bedeutender Schritt.','ch und spr; abschließende Gedanken',10,true)
ON CONFLICT(id) DO NOTHING;
-- Snapshot the reading text server-side, never trust a caller's text or level.
CREATE OR REPLACE FUNCTION pronunciation_private.create_submission(p_prompt_id uuid, p_audio_path text)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE actor uuid := (SELECT auth.uid()); prompt public.pronunciation_prompts%ROWTYPE; result uuid;
BEGIN
 IF actor IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
 SELECT * INTO prompt FROM public.pronunciation_prompts WHERE id = p_prompt_id AND is_active;
 IF NOT FOUND OR prompt.level IS NULL OR NOT EXISTS(SELECT 1 FROM public.profiles p WHERE p.id = actor AND
   (p.role IN ('teacher','admin') OR prompt.level = ANY(COALESCE(p.allowed_levels,ARRAY[]::text[])))) THEN RAISE EXCEPTION 'Level not allowed'; END IF;
 IF p_audio_path NOT LIKE 'storage://pronunciation_audio/' || actor::text || '/%' OR NOT EXISTS(
 SELECT 1 FROM storage.objects o WHERE o.bucket_id = 'pronunciation_audio' AND 'storage://pronunciation_audio/' || o.name = p_audio_path)
 THEN RAISE EXCEPTION 'Invalid recording'; END IF;
 INSERT INTO public.submissions(user_id,type,content_url,text_content,status,level,prompt_id,prompt_title)
 VALUES(actor,'audio',p_audio_path,prompt.sentence_de,'pending',prompt.level,prompt.id,prompt.title) RETURNING id INTO result;
 RETURN result;
END;
$$;
REVOKE ALL ON FUNCTION pronunciation_private.create_submission(uuid,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION pronunciation_private.create_submission(uuid,text) TO authenticated;
CREATE OR REPLACE FUNCTION public.create_pronunciation_submission(p_prompt_id uuid,p_audio_path text)
RETURNS uuid LANGUAGE sql SECURITY INVOKER SET search_path = '' AS $$ SELECT pronunciation_private.create_submission(p_prompt_id,p_audio_path); $$;
REVOKE ALL ON FUNCTION public.create_pronunciation_submission(uuid,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_pronunciation_submission(uuid,text) TO authenticated;
