import {randomUUID} from 'node:crypto'
import {act,fireEvent,render,screen,waitFor} from '@testing-library/react'
import SitovLearningSpecialStaff from '@/components/admin/SitovLearningSpecialStaff'
import {getSitovLearningSpecialStaff,getSitovLearningSpecialPublication,publishSitovLearningSpecial} from '@/app/actions/sitov-learning-specials'
import {sitovSpecialStaffCopy} from '@/lib/learning/sitov-learning-specials-staff-i18n'
jest.unmock('lucide-react')
beforeAll(()=>{Object.defineProperty(global.crypto,'randomUUID',{value:randomUUID,configurable:true})})
const refresh=jest.fn()
jest.mock('next/navigation',()=>({useRouter:()=>({refresh})}))
jest.mock('@/app/actions/sitov-learning-specials',()=>({getSitovLearningSpecialStaff:jest.fn(),getSitovLearningSpecialPublication:jest.fn(),publishSitovLearningSpecial:jest.fn()}))
const node='00000000-0000-4000-8000-000000000001',def='00000000-0000-4000-8000-000000000002',task='00000000-0000-4000-8000-000000000003',run='00000000-0000-4000-8000-000000000004',hash='a'.repeat(64),source='b'.repeat(64)
const definition={id:def,node_id:node,version:hash,source_ref:'sitov.source.test',blueprint:{masculine:10},pool:[{id:task,stratum:'masculine',snapshot:{id:task,type:'multiple_choice' as const,goal_id:'P4-G1',content:{question:'Welcher Artikel gehört zu Flur?',instruction:'Wählen Sie.',target_form:['Artikel'],options:['der','die','das'],correct_answer:'der',accepted_answers:['der']},translations:{de:{explanation:'Der Flur ist hier.'}}}}],published:false,editorial_proof:null,audio_import_proof:null,created_by:null,created_at:'2026-10-09T00:00:00Z'}
const catalog={definitions:[definition],runs:[{id:run,studentId:task,mode:'learning' as const,status:'completed' as const,revision:4,result:null}]}
const props={accountKey:'a',nodeId:node,title:'Artikel im Nominativ',sourceSha256:source,baseActiveDefinitionId:null,lang:'en'}
beforeEach(()=>{jest.clearAllMocks();jest.mocked(getSitovLearningSpecialStaff).mockResolvedValue({ok:true,data:JSON.parse(JSON.stringify(catalog))});jest.mocked(getSitovLearningSpecialPublication).mockResolvedValue({ok:true,data:{nodeId:node,definitionId:def,definitionVersion:hash,sourceSha256:source,activeDefinitionId:null,ready:false}})})
it.each(['de','en','ru','uk','tr'])('loads onlyselectedprivatecatalog and Germancontent stays German with %s UI',async lang=>{const {container}=render(<SitovLearningSpecialStaff {...props} lang={lang}/>);const copy=sitovSpecialStaffCopy(lang);expect(await screen.findByText(copy.preview)).toBeInTheDocument();expect(getSitovLearningSpecialStaff).toHaveBeenCalledWith({nodeId:node});expect(screen.getByText('Artikel im Nominativ')).toHaveAttribute('lang','de');const text=screen.getByText('Welcher Artikel gehört zu Flur?');expect(text.closest('[lang=de]')).toHaveAttribute('translate','no');expect(container).not.toHaveTextContent(hash);expect(container).not.toHaveTextContent(node);expect(publishSitovLearningSpecial).not.toHaveBeenCalled();expect(screen.getByText(`${copy.learning} · ${copy.completed}`)).toBeInTheDocument()})
it('rejects foreigncatalog before showing private tasks',async()=>{jest.mocked(getSitovLearningSpecialStaff).mockResolvedValue({ok:true,data:{...catalog,definitions:[{...definition,node_id:task}]}});render(<SitovLearningSpecialStaff {...props}/>);expect(await screen.findByRole('alert')).toHaveTextContent(sitovSpecialStaffCopy('en').error);expect(screen.queryByText('Welcher Artikel gehört zu Flur?')).not.toBeInTheDocument();expect(getSitovLearningSpecialPublication).not.toHaveBeenCalled()})
it('retiredaccount ignores latecatalog reply',async()=>{let finish!:(r:Awaited<ReturnType<typeof getSitovLearningSpecialStaff>>)=>void;jest.mocked(getSitovLearningSpecialStaff).mockReturnValueOnce(new Promise(resolve=>{finish=resolve})).mockResolvedValueOnce({ok:true,data:{definitions:[],runs:[]}});const view=render(<SitovLearningSpecialStaff {...props}/>);view.rerender(<SitovLearningSpecialStaff {...props} accountKey="b"/>);await screen.findByText('No version yet.');await act(async()=>finish({ok:true,data:catalog}));expect(screen.queryByText('Welcher Artikel gehört zu Flur?')).not.toBeInTheDocument()})
it('publicationack waitsforactualcatalogreread before success and refresh whilehistory is preserved',async()=>{
 jest.mocked(getSitovLearningSpecialPublication).mockResolvedValue({ok:true,data:{nodeId:node,definitionId:def,definitionVersion:hash,sourceSha256:source,activeDefinitionId:null,ready:true}})
 const ack={nodeId:node,definitionId:def,definitionVersion:hash,sourceSha256:source,activeDefinitionId:def,active:true as const,published:true as const};jest.mocked(publishSitovLearningSpecial).mockResolvedValue({ok:true,data:ack})
 let finish!:(r:Awaited<ReturnType<typeof getSitovLearningSpecialStaff>>)=>void;jest.mocked(getSitovLearningSpecialStaff).mockResolvedValueOnce({ok:true,data:catalog}).mockReturnValueOnce(new Promise(resolve=>{finish=resolve}))
 render(<SitovLearningSpecialStaff {...props}/>);const button=await screen.findByRole('button',{name:'Publish this version'});await waitFor(()=>expect(button).toBeEnabled());fireEvent.click(button);await waitFor(()=>expect(getSitovLearningSpecialStaff).toHaveBeenCalledTimes(2));expect(screen.queryByText(sitovSpecialStaffCopy('en').saved)).not.toBeInTheDocument();expect(refresh).not.toHaveBeenCalled()
 const confirmed={...definition,published:true,editorial_proof:{reviewId:task,definitionVersion:hash,sourceSha256:source}};await act(async()=>finish({ok:true,data:{definitions:[confirmed],runs:catalog.runs}}));expect(screen.getByText(sitovSpecialStaffCopy('en').saved)).toHaveFocus();expect(refresh).toHaveBeenCalledTimes(1);expect(screen.getByText('Learning · Completed')).toBeInTheDocument()
})
