/** @jest-environment node */
jest.mock('server-only',()=>({}),{virtual:true})
jest.mock('@/utils/supabase/server',()=>({createClient:jest.fn()}))
import {createClient} from '@/utils/supabase/server'
import {publishSitovSpecial,loadSitovSpecialPublicationState} from '@/lib/learning/sitov-learning-specials-staff-server'
const uid='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002',hash='e'.repeat(64)
const stateInput={nodeId:uid,definitionId:other,definitionVersion:hash,sourceSha256:hash,baseActiveDefinitionId:null}
const input={...stateInput,requestId:uid},data={nodeId:uid,definitionId:other,definitionVersion:hash,sourceSha256:hash,activeDefinitionId:other,active:true,published:true}
const client={auth:{getUser:jest.fn()},rpc:jest.fn()}
beforeEach(()=>{jest.clearAllMocks();(createClient as jest.Mock).mockResolvedValue(client);client.auth.getUser.mockResolvedValue({data:{user:{id:uid}},error:null})})
it('rejects proof/approval/actor injection before RPC',async()=>{for(const extra of [{editorialProof:true},{audioImportProof:{assets:[]}},{reviewId:uid},{actorId:uid},{approved:true}])expect(await publishSitovSpecial({...input,...extra})).toEqual({ok:false,error:'invalid_input',retryable:false});expect(client.rpc).not.toHaveBeenCalled()})
it('requires current cookie user',async()=>{client.auth.getUser.mockResolvedValue({data:{user:null},error:null});expect(await publishSitovSpecial(input)).toEqual({ok:false,error:'authentication_required',retryable:false});expect(client.rpc).not.toHaveBeenCalled()})
it('sends only exact CAS/version/source/request identifiers and accepts bound publication',async()=>{client.rpc.mockResolvedValue({data:{ok:true,data},error:null});expect(await publishSitovSpecial(input)).toEqual({ok:true,data});expect(client.rpc).toHaveBeenCalledWith('sitov_publish_special',{p_node_id:uid,p_definition_id:other,p_definition_version:hash,p_source_sha256:hash,p_base_active_definition_id:null,p_request_id:uid})})
it('preserves current SQL denial/CAS/readiness and retry flags',async()=>{for(const error of ['not_found','version_conflict','request_conflict','authoring_not_ready']){client.rpc.mockResolvedValue({data:{ok:false,error,retryable:false},error:null});expect(await publishSitovSpecial(input)).toEqual({ok:false,error,retryable:false})}})
it('rejects stale/foreign/inactive/surplus acknowledgement',async()=>{for(const changed of [{...data,nodeId:other},{...data,definitionVersion:'f'.repeat(64)},{...data,activeDefinitionId:uid},{...data,active:false},{...data,published:false},{...data,proof:'fake'}]){client.rpc.mockResolvedValue({data:{ok:true,data:changed},error:null});expect(await publishSitovSpecial(input)).toEqual({ok:false,error:'retryable_failure',retryable:true})}})
it('readonly state remains honest and has no request/proof payload',async()=>{const state={nodeId:uid,definitionId:other,definitionVersion:hash,sourceSha256:hash,activeDefinitionId:null,ready:false};client.rpc.mockResolvedValue({data:{ok:true,data:state},error:null});expect(await loadSitovSpecialPublicationState(stateInput)).toEqual({ok:true,data:state});expect(client.rpc).toHaveBeenCalledWith('sitov_get_special_publication',{p_node_id:uid,p_definition_id:other,p_definition_version:hash,p_source_sha256:hash,p_base_active_definition_id:null})})
it('transport/invalid SQL retry truth remain retryable',async()=>{client.rpc.mockResolvedValue({data:null,error:{code:'timeout'}});expect(await publishSitovSpecial(input)).toEqual({ok:false,error:'retryable_failure',retryable:true});client.rpc.mockResolvedValue({data:{ok:false,error:'not_found',retryable:true},error:null});expect(await publishSitovSpecial(input)).toEqual({ok:false,error:'retryable_failure',retryable:true})})
