import {act,fireEvent,render,screen,waitFor} from '@testing-library/react'
import SitovLearningSpecialStaffTargets from '@/components/admin/SitovLearningSpecialStaffTargets'
import {getSitovLearningSpecialStaffTargets} from '@/app/actions/sitov-learning-specials'
import {sitovSpecialStaffTargetsCopy} from '@/lib/learning/sitov-learning-specials-staff-i18n'
jest.unmock('lucide-react')
jest.mock('@/app/actions/sitov-learning-specials',()=>({getSitovLearningSpecialStaffTargets:jest.fn()}))
const mounted=jest.fn()
jest.mock('@/components/admin/SitovLearningSpecialStaff',()=>({__esModule:true,default:(props:unknown)=>{mounted(props);return <div data-testid="sitov-staff-window"/>}}))
const node='00000000-0000-4000-8000-000000000001',unit='00000000-0000-4000-8000-000000000002',other='00000000-0000-4000-8000-000000000003',active='00000000-0000-4000-8000-000000000004',source='e'.repeat(64)
const target={nodeId:node,unitId:unit,title:'Artikel im Nominativ',level:'A1.1',sourceSha256:source,activeDefinitionId:null},second={...target,nodeId:other,title:'Ein zweites Extra',level:'A1.2'}
const initial={ok:true as const,data:[target,second]},props={accountKey:unit,lang:'en',initial}
beforeEach(()=>{jest.clearAllMocks();jest.mocked(getSitovLearningSpecialStaffTargets).mockResolvedValue(initial)})
it.each(['de','en','ru','uk','tr'])('renders %s UI with German target boundary and explicit authorized selection',lang=>{const {container}=render(<SitovLearningSpecialStaffTargets {...props} lang={lang}/>);const copy=sitovSpecialStaffTargetsCopy(lang);expect(screen.getByRole('heading',{name:copy.title})).toBeInTheDocument();expect(screen.getByText(target.title)).toHaveAttribute('lang','de');expect(screen.getByText(target.title)).toHaveAttribute('translate','no');expect(screen.queryByTestId('sitov-staff-window')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:target.title+' '+target.level}));expect(mounted).toHaveBeenLastCalledWith({accountKey:unit,nodeId:node,title:target.title,sourceSha256:source,baseActiveDefinitionId:null,lang});expect(container).not.toHaveTextContent(node);expect(screen.queryByRole('textbox')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:target.title+' '+target.level})).toHaveAttribute('aria-pressed','true')})
it('authorized empty and current denial states expose no private window and allow reload',async()=>{const view=render(<SitovLearningSpecialStaffTargets {...props} initial={{ok:true,data:[]}}/>);expect(screen.getByRole('status')).toHaveTextContent(sitovSpecialStaffTargetsCopy('en').targetsEmpty);view.rerender(<SitovLearningSpecialStaffTargets {...props} initial={{ok:false,error:'not_found',retryable:false}}/>);expect(screen.getByRole('alert')).toHaveTextContent(sitovSpecialStaffTargetsCopy('en').targetsDenied);expect(screen.queryByTestId('sitov-staff-window')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Load current data'}));expect(await screen.findByText(target.title)).toBeInTheDocument();expect(getSitovLearningSpecialStaffTargets).toHaveBeenCalledWith({level:null})})
it('uses actual level reload, hides old private window while pending and prevents duplicate calls',async()=>{let finish!:(value:typeof initial)=>void;jest.mocked(getSitovLearningSpecialStaffTargets).mockReturnValueOnce(new Promise(resolve=>{finish=resolve}));render(<SitovLearningSpecialStaffTargets {...props}/>);fireEvent.click(screen.getByRole('button',{name:target.title+' '+target.level}));fireEvent.change(screen.getByRole('combobox'),{target:{value:'A1.2'}});expect(screen.getByRole('status')).toHaveTextContent('Loading the current list');expect(screen.queryByTestId('sitov-staff-window')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Load current data'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Load current data'}));expect(getSitovLearningSpecialStaffTargets).toHaveBeenCalledTimes(1);expect(getSitovLearningSpecialStaffTargets).toHaveBeenCalledWith({level:'A1.2'});await act(async()=>finish({ok:true,data:[second]}));expect(screen.queryByText(target.title)).not.toBeInTheDocument();expect(screen.getByText(second.title)).toBeInTheDocument();expect(screen.queryByTestId('sitov-staff-window')).not.toBeInTheDocument()})
it('rejects foreign-level or surplus response without rendering targets',async()=>{render(<SitovLearningSpecialStaffTargets {...props}/>);fireEvent.change(screen.getByRole('combobox'),{target:{value:'A1.2'}});expect(await screen.findByRole('alert')).toBeInTheDocument();expect(screen.queryByText(target.title)).not.toBeInTheDocument();expect(mounted).not.toHaveBeenCalled()})
it('retires late replies after actor/locale switch',async()=>{let finish!:(value:typeof initial)=>void;jest.mocked(getSitovLearningSpecialStaffTargets).mockReturnValueOnce(new Promise(resolve=>{finish=resolve}));const view=render(<SitovLearningSpecialStaffTargets {...props}/>);fireEvent.click(screen.getByRole('button',{name:'Load current data'}));view.rerender(<SitovLearningSpecialStaffTargets {...props} accountKey="other-account" lang="ru" initial={{ok:true,data:[]}}/>);await act(async()=>finish(initial));expect(screen.queryByText(target.title)).not.toBeInTheDocument();expect(screen.getByRole('status')).toHaveTextContent(sitovSpecialStaffTargetsCopy('ru').targetsEmpty);expect(mounted).not.toHaveBeenCalled()})
it('server refresh preserves chosen actual node and supplies updated activation/source base',()=>{const view=render(<SitovLearningSpecialStaffTargets {...props}/>);fireEvent.click(screen.getByRole('button',{name:second.title+' '+second.level}));const updated={...second,sourceSha256:'a'.repeat(64),activeDefinitionId:active};view.rerender(<SitovLearningSpecialStaffTargets {...props} initial={{ok:true,data:[target,updated]}}/>);expect(mounted).toHaveBeenLastCalledWith({accountKey:unit,nodeId:other,title:second.title,sourceSha256:'a'.repeat(64),baseActiveDefinitionId:active,lang:'en'})})
it('transport rejection is localized and clears previous private selection',async()=>{jest.mocked(getSitovLearningSpecialStaffTargets).mockRejectedValueOnce(new Error('transport'));render(<SitovLearningSpecialStaffTargets {...props}/>);fireEvent.click(screen.getByRole('button',{name:target.title+' '+target.level}));fireEvent.click(screen.getByRole('button',{name:'Load current data'}));await waitFor(()=>expect(screen.getByRole('alert')).toHaveFocus());expect(screen.queryByTestId('sitov-staff-window')).not.toBeInTheDocument()})
