/** @jest-environment node */
jest.mock('server-only',()=>({}),{virtual:true})
jest.mock('@/utils/supabase/server',()=>({createClient:jest.fn()}))
import {createClient} from '@/utils/supabase/server'
import {loadSitovSpecialStaffTargets} from '@/lib/learning/sitov-learning-specials-staff-server'
import {getSitovLearningSpecialStaffTargets} from '@/app/actions/sitov-learning-specials'
const uid='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002'
const target={nodeId:uid,unitId:other,title:'Artikel im Nominativ',level:'A1.1',sourceSha256:'e'.repeat(64),activeDefinitionId:null}
const client={auth:{getUser:jest.fn()},rpc:jest.fn()},denied={ok:false,error:'not_found',retryable:false}
beforeEach(()=>{jest.clearAllMocks();(createClient as jest.Mock).mockResolvedValue(client);client.auth.getUser.mockResolvedValue({data:{user:{id:uid}},error:null});client.rpc.mockResolvedValue({data:{ok:true,data:[target]},error:null})})
it('uses exact typed cookie RPC and action for null and selected level',async()=>{expect(await getSitovLearningSpecialStaffTargets({})).toEqual({ok:true,data:[target]});expect(client.rpc).toHaveBeenLastCalledWith('sitov_get_special_staff_targets',{p_level:null});expect(await loadSitovSpecialStaffTargets({level:'A1.1'})).toEqual({ok:true,data:[target]});expect(client.rpc).toHaveBeenLastCalledWith('sitov_get_special_staff_targets',{p_level:'A1.1'})})
it('rejects actor/proof/unknown properties and malformed levels before auth',async()=>{for(const input of [{actorId:uid},{level:' A1.1'},{level:'D1'},{level:3},null,{level:'A1.1',published:true}])expect(await loadSitovSpecialStaffTargets(input)).toEqual({ok:false,error:'invalid_input',retryable:false});expect(createClient).not.toHaveBeenCalled()})
it('requires verified cookie user',async()=>{client.auth.getUser.mockResolvedValue({data:{user:null},error:null});expect(await loadSitovSpecialStaffTargets({})).toEqual({ok:false,error:'authentication_required',retryable:false});expect(client.rpc).not.toHaveBeenCalled()})
it('preserves exact SQL errors and accepts empty authorized index',async()=>{for(const error of ['authentication_required','invalid_input','not_found']){client.rpc.mockResolvedValue({data:{ok:false,error,retryable:false},error:null});expect(await loadSitovSpecialStaffTargets({})).toEqual({ok:false,error,retryable:false})}client.rpc.mockResolvedValue({data:{ok:true,data:[]},error:null});expect(await loadSitovSpecialStaffTargets({})).toEqual({ok:true,data:[]})})
it('rejects PII/pool/key/proof or unknown result fields',async()=>{for(const extra of [{pool:[]},{studentId:uid},{answers:{}},{published:true},{sourceRef:'private'}]){client.rpc.mockResolvedValue({data:{ok:true,data:[{...target,...extra}]},error:null});expect(await loadSitovSpecialStaffTargets({})).toEqual(denied)}client.rpc.mockResolvedValue({data:{ok:true,data:[target],extra:true},error:null});expect(await loadSitovSpecialStaffTargets({})).toEqual(denied)})
it('rejects foreign level, duplicate identities, malformed hashes and excessive lists',async()=>{for(const data of [[{...target,level:'A1.2'}],[target,target],[{...target,sourceSha256:'fake'}],[{...target,activeDefinitionId:'fake'}],Array(1001).fill(target)]){client.rpc.mockResolvedValue({data:{ok:true,data},error:null});expect(await loadSitovSpecialStaffTargets({level:'A1.1'})).toEqual(denied)}})
it('reads actual pointer without inferring readiness and fails closed on transport/schema errors',async()=>{client.rpc.mockResolvedValue({data:{ok:true,data:[{...target,activeDefinitionId:other}]},error:null});expect(await loadSitovSpecialStaffTargets({level:null})).toEqual({ok:true,data:[{...target,activeDefinitionId:other}]});for(const data of [null,{ok:false,error:'retryable_failure',retryable:true},{ok:false,error:'not_found',retryable:true}]){client.rpc.mockResolvedValue({data,error:null});expect(await loadSitovSpecialStaffTargets({})).toEqual(denied)}client.rpc.mockRejectedValue(new Error('transport'));expect(await loadSitovSpecialStaffTargets({})).toEqual(denied)})
