jest.mock('server-only',()=>({}),{virtual:true})
jest.mock('@/utils/supabase/server',()=>({createClient:jest.fn()}))
import {createClient} from '@/utils/supabase/server'
import {readSitovBillingSettings,writeSitovBillingPrice,disableSitovBilling,sitovBillingSettingsSchema} from '@/lib/access/sitov-billing-staff'
import {ACCESS_LEVELS} from '@/lib/access/levels'
const settings={enabled:false,provider:'none',revision:0,configuration_ready:false,missing:['provider_adapter'],products:ACCESS_LEVELS.map(level=>({level,amount_minor:null,currency:null,revision:0}))}
function setup({role='teacher',signedIn=true,mfa=true,response=settings as unknown}:{role?:string;signedIn?:boolean;mfa?:boolean;response?:unknown}={}) {
 const profile={select:jest.fn().mockReturnThis(),eq:jest.fn().mockReturnThis(),single:jest.fn().mockResolvedValue({data:{role,sitov_mfa_required:role==='admin'},error:null})}
 const client={from:jest.fn().mockReturnValue(profile),rpc:jest.fn(async(name:string)=>({data:name==='sitov_staff_mfa_status'?{satisfied:mfa}:response,error:null})),auth:{getUser:jest.fn().mockResolvedValue({data:{user:signedIn?{id:'staff'}:null},error:null})}}
 jest.mocked(createClient).mockResolvedValue(client as unknown as Awaited<ReturnType<typeof createClient>>);return client
}
beforeEach(()=>jest.clearAllMocks())
it.each([{signedIn:false},{role:'student'},{role:'admin',mfa:false}])('rejects unauthorized billing access %p',async options=>{const client=setup(options);expect(await readSitovBillingSettings()).toEqual({ok:false,error:'forbidden'});expect(client.rpc.mock.calls.some(([name])=>name==='get_sitov_billing_settings')).toBe(false)})
it('reads actual complete null price rows without inventing a tariff',async()=>{setup();expect(await readSitovBillingSettings()).toEqual({ok:true,data:settings});expect(settings.products.every(p=>p.amount_minor===null&&p.currency===null)).toBe(true)})
it('sends exact product CAS args and accepts the actual acknowledgement',async()=>{const client=setup({response:{success:true,revision:5}});expect(await writeSitovBillingPrice({level:'A1.1',amountMinor:250,currency:'EUR',revision:4})).toEqual({ok:true,data:{revision:5}});expect(client.rpc).toHaveBeenCalledWith('set_sitov_product_price',{p_level:'A1.1',p_amount_minor:250,p_currency:'EUR',p_expected_revision:4})})
it.each([0,-1,1.2,Number.MAX_SAFE_INTEGER+1])('rejects invalid minor amount %s before RPC',async amountMinor=>{const client=setup();expect((await writeSitovBillingPrice({level:'A1.1',amountMinor,currency:'EUR',revision:0})).ok).toBe(false);expect(client.rpc).not.toHaveBeenCalled()})
it('rejects unknown currency/extra fields and keeps revision conflict explicit',async()=>{const client=setup({response:{error:'revision_conflict'}});expect((await writeSitovBillingPrice({level:'A1.1',amountMinor:10,currency:'ZZZ',revision:0})).ok).toBe(false);expect((await writeSitovBillingPrice({level:'A1.1',amountMinor:10,currency:'EUR',revision:0,enabled:true})).ok).toBe(false);expect(client.rpc).not.toHaveBeenCalled();expect(await writeSitovBillingPrice({level:'A1.1',amountMinor:10,currency:'EUR',revision:0})).toEqual({ok:false,error:'revision_conflict'})})
it('has only an off action and accepts enabled:false acknowledgement',async()=>{const client=setup({response:{success:true,revision:1,enabled:false}});expect(await disableSitovBilling({revision:0})).toEqual({ok:true,data:{revision:1,enabled:false}});expect(client.rpc).toHaveBeenCalledWith('set_sitov_billing_enabled',{p_enabled:false,p_expected_revision:0});expect((await disableSitovBilling({revision:0,enabled:true})).ok).toBe(false)})
it('rejects wrong acknowledgements and leaked or inconsistent DTOs',async()=>{setup({response:{success:true,revision:1,enabled:true}});expect((await disableSitovBilling({revision:0})).ok).toBe(false);expect(sitovBillingSettingsSchema.safeParse({...settings,orders:['private']}).success).toBe(false);expect(sitovBillingSettingsSchema.safeParse({...settings,products:[...settings.products.slice(1),settings.products[1]]}).success).toBe(false);expect(sitovBillingSettingsSchema.safeParse({...settings,products:settings.products.map((p,i)=>i? p:{...p,amount_minor:100})}).success).toBe(false)})
