import { sitovTrainerHelpCopy } from '@/lib/sitov-trainer-help-copy'
import {randomUUID} from 'node:crypto'
import {act,fireEvent,render,screen,waitFor} from '@testing-library/react'
import SitovSpecialPublication from '@/components/admin/SitovSpecialPublication'
import {getSitovLearningSpecialPublication,publishSitovLearningSpecial} from '@/app/actions/sitov-learning-specials'
import {sitovSpecialStaffCopy} from '@/lib/learning/sitov-learning-specials-staff-i18n'
jest.unmock('lucide-react')
jest.mock('@/app/actions/sitov-learning-specials',()=>({getSitovLearningSpecialPublication:jest.fn(),publishSitovLearningSpecial:jest.fn(),getSitovLearningSpecialStaff:jest.fn()}))
beforeAll(()=>{Object.defineProperty(global.crypto,'randomUUID',{value:randomUUID,configurable:true})})
const nodeId='00000000-0000-4000-8000-000000000001',definitionId='00000000-0000-4000-8000-000000000002',other='00000000-0000-4000-8000-000000000003',version='a'.repeat(64),sourceSha256='b'.repeat(64)
const input={nodeId,definitionId,definitionVersion:version,sourceSha256,baseActiveDefinitionId:null},ack={nodeId,definitionId,definitionVersion:version,sourceSha256,activeDefinitionId:definitionId,active:true as const,published:true as const}
const state=()=>({ok:true as const,data:{nodeId,definitionId,definitionVersion:version,sourceSha256,activeDefinitionId:null,ready:true}})
const props={accountKey:'account-a',nodeId,definition:{id:definitionId,version,published:false},sourceSha256,latestDefinitionId:definitionId,baseActiveDefinitionId:null,lang:'en',onPublished:jest.fn(),onReload:jest.fn()}
beforeEach(()=>{jest.clearAllMocks();jest.mocked(getSitovLearningSpecialPublication).mockResolvedValue(state());jest.mocked(publishSitovLearningSpecial).mockResolvedValue({ok:true,data:ack})})
async function button(){const b=screen.getByRole('button',{name:'Publish this version'});await waitFor(()=>expect(b).toBeEnabled());return b}
it.each(['de','en','ru','uk','tr'])('readyfalse blocks writes with %s UI and closed shared help',async lang=>{jest.mocked(getSitovLearningSpecialPublication).mockResolvedValue({ok:true,data:{...state().data,ready:false}});render(<SitovSpecialPublication {...props} lang={lang}/>);const c=sitovSpecialStaffCopy(lang);expect(await screen.findByText(c.missing)).toBeInTheDocument();expect(screen.getByRole('button',{name:c.publish})).toBeDisabled();expect(publishSitovLearningSpecial).not.toHaveBeenCalled();expect(getSitovLearningSpecialPublication).toHaveBeenCalledWith(input);expect(screen.getByRole('button',{name:sitovTrainerHelpCopy(lang).label})).toHaveAttribute('aria-expanded','false')})
it('explicit publication sends exactCAS, validatesack and requests fresh confirmation',async()=>{render(<SitovSpecialPublication {...props}/>);fireEvent.click(await button());await waitFor(()=>expect(props.onPublished).toHaveBeenCalledWith(ack));expect(publishSitovLearningSpecial).toHaveBeenCalledWith({...input,requestId:expect.any(String)});expect(screen.getByText(sitovSpecialStaffCopy('en').confirming)).toHaveFocus()})
it('doublepress cannot duplicate mutation and uncertainretry keeps identicalrequest without oldbasepreflight',async()=>{let finish!:(r:Awaited<ReturnType<typeof publishSitovLearningSpecial>>)=>void;jest.mocked(publishSitovLearningSpecial).mockReturnValueOnce(new Promise(resolve=>{finish=resolve}));render(<SitovSpecialPublication {...props}/>);const b=await button();fireEvent.click(b);fireEvent.click(b);expect(publishSitovLearningSpecial).toHaveBeenCalledTimes(1);await act(async()=>finish({ok:false,error:'retryable_failure',retryable:true}));jest.mocked(getSitovLearningSpecialPublication).mockResolvedValue({ok:false,error:'version_conflict',retryable:false});fireEvent.click(screen.getByRole('button',{name:'Check publication again'}));await waitFor(()=>expect(props.onPublished).toHaveBeenCalledWith(ack));expect(jest.mocked(publishSitovLearningSpecial).mock.calls[1][0]).toBe(jest.mocked(publishSitovLearningSpecial).mock.calls[0][0]);expect(getSitovLearningSpecialPublication).toHaveBeenCalledTimes(1)})
it('foreignack/transport preserves uncertainty and never exposes private error text',async()=>{jest.mocked(publishSitovLearningSpecial).mockResolvedValueOnce({ok:true,data:{...ack,nodeId:other}}).mockRejectedValueOnce(new Error('PRIVATE_STACK'));render(<SitovSpecialPublication {...props}/>);fireEvent.click(await button());fireEvent.click(await screen.findByRole('button',{name:'Check publication again'}));await screen.findByText(sitovSpecialStaffCopy('en').uncertain);expect(props.onPublished).not.toHaveBeenCalled();expect(screen.queryByText('PRIVATE_STACK')).not.toBeInTheDocument()})
it.each(['accountKey','lang','nodeId'] as const)('retiring %s ignores delayedpublishack',async key=>{let finish!:(r:Awaited<ReturnType<typeof publishSitovLearningSpecial>>)=>void;jest.mocked(publishSitovLearningSpecial).mockReturnValueOnce(new Promise(resolve=>{finish=resolve}));const view=render(<SitovSpecialPublication {...props}/>);fireEvent.click(await button());view.rerender(<SitovSpecialPublication {...props} {...{[key]:key==='nodeId'?other:key==='lang'?'de':'account-b'}}/>);await act(async()=>finish({ok:true,data:ack}));expect(props.onPublished).not.toHaveBeenCalled()})
it('CASfailure is honest and requests current data instead of rewriting proof',async()=>{jest.mocked(publishSitovLearningSpecial).mockResolvedValue({ok:false,error:'version_conflict',retryable:false});render(<SitovSpecialPublication {...props}/>);fireEvent.click(await button());fireEvent.click(await screen.findByRole('button',{name:'Load current data'}));expect(props.onReload).toHaveBeenCalledTimes(1);expect(props.onPublished).not.toHaveBeenCalled()})
it('published/olddefinition never startsreadiness orpublication',()=>{render(<SitovSpecialPublication {...props} definition={{...props.definition,published:true}}/>);expect(screen.getByRole('button',{name:'Publish this version'})).toBeDisabled();expect(getSitovLearningSpecialPublication).not.toHaveBeenCalled();expect(publishSitovLearningSpecial).not.toHaveBeenCalled()})
