/** @jest-environment node */
jest.mock('server-only',()=>({}),{virtual:true})
jest.mock('@/utils/supabase/server',()=>({createClient:jest.fn()}))
import {createClient} from '@/utils/supabase/server'
import {createSitovSpecialAuthorDraft,loadSitovSpecialAuthorContext} from '@/lib/learning/sitov-learning-specials-staff-server'
import {sitovSpecialAuthorInputSchema} from '@/lib/learning/sitov-learning-specials-staff-contract'
import draft from '@/supabase/seeds/sitov-learning-special-pools-2026-10-08.json'
const uid='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002',hash='e'.repeat(64),sourceRef='sitov.source.a11.wohnung.artikel.pdf.v1' as const
const client={auth:{getUser:jest.fn()},rpc:jest.fn()}
const input=()=>structuredClone({requestId:uid,unitId:uid,anchorNodeId:other,sourceRef,sourceSha256:draft.sources[0].sha256,expectedAnchorVersion:hash,specialSourceId:draft.pools[0].specialId,title:draft.pools[0].title,topic:'Artikel im Nominativ',goalId:'P4-G1',blueprint:draft.pools[0].blueprint,items:draft.pools[0].items.map(item=>({id:item.id,stableId:item.stableId,stratum:item.stratum,snapshot:item.snapshot,sourceEvidence:item.sourceEvidence}))})
const response=()=>({ok:true,data:{nodeId:uid,unitId:uid,anchorNodeId:other,definitionId:other,definitionVersion:hash,sourceRef,sourceSha256:draft.sources[0].sha256,itemIds:input().items.map(i=>i.id),active:false,published:false}})
beforeEach(()=>{jest.clearAllMocks();(createClient as jest.Mock).mockResolvedValue(client);client.auth.getUser.mockResolvedValue({data:{user:{id:uid}},error:null})})
it('accepts source-evidenced actual draft shape and rejects publication/identity injection',()=>{expect(sitovSpecialAuthorInputSchema.safeParse(input()).success).toBe(true);for(const extra of [{published:true},{actorId:uid},{editorialProof:true},{audioImportProof:true}])expect(sitovSpecialAuthorInputSchema.safeParse({...input(),...extra}).success).toBe(false)})
it('rejects unsupported content, duplicates, wrong source and unbalanced pool before any RPC',async()=>{const duplicates=input();duplicates.items[1]=duplicates.items[0];const malformed=input();malformed.items[0].snapshot.content={...malformed.items[0].snapshot.content,correct_answer:'unknown'};for(const value of [duplicates,malformed,{...input(),sourceSha256:hash},{...input(),blueprint:{masculine:5,feminine:4,neuter:1}}])expect(await createSitovSpecialAuthorDraft(value)).toEqual({ok:false,error:'invalid_input',retryable:false});expect(client.rpc).not.toHaveBeenCalled()})
it('requires cookie session before creation',async()=>{client.auth.getUser.mockResolvedValue({data:{user:null},error:null});expect(await createSitovSpecialAuthorDraft(input())).toEqual({ok:false,error:'authentication_required',retryable:false});expect(client.rpc).not.toHaveBeenCalled()})
it('uses only exact101 RPC payload and accepts immutable inactive acknowledgement',async()=>{client.rpc.mockResolvedValue({data:response(),error:null});expect(await createSitovSpecialAuthorDraft(input())).toEqual(response());expect(client.rpc).toHaveBeenCalledWith('sitov_special_author_create',{p_input:input()})})
it('preserves SQL CAS/source/currentrole failures',async()=>{for(const error of ['not_found','stale_revision','source_conflict','request_conflict','already_exists','item_conflict']){client.rpc.mockResolvedValue({data:{ok:false,error,retryable:false},error:null});expect(await createSitovSpecialAuthorDraft(input())).toEqual({ok:false,error,retryable:false})}})
it('rejects foreign/active/extra/missing/reordered acknowledgements',async()=>{for(const data of [{...response().data,unitId:other},{...response().data,active:true},{...response().data,published:true},{...response().data,itemIds:response().data.itemIds.slice().reverse()},{...response().data,secret:'bad'}]){client.rpc.mockResolvedValue({data:{ok:true,data},error:null});expect(await createSitovSpecialAuthorDraft(input())).toEqual({ok:false,error:'retryable_failure',retryable:true})}})
it('context response must match exact source/parent and strict shape',async()=>{const context={unitId:uid,anchorNodeId:other,sourceRef};const data={...context,sourceSha256:draft.sources[0].sha256,anchorVersion:hash,specialExists:false};client.rpc.mockResolvedValue({data:{ok:true,data},error:null});expect((await loadSitovSpecialAuthorContext(context)).ok).toBe(true);expect(client.rpc).toHaveBeenCalledWith('sitov_special_author_context',{p_unit_id:uid,p_anchor_id:other,p_source_ref:sourceRef});client.rpc.mockResolvedValue({data:{ok:true,data:{...data,anchorNodeId:uid}},error:null});expect((await loadSitovSpecialAuthorContext(context)).ok).toBe(false)})
it('transport/malformed response remain retryable',async()=>{client.rpc.mockResolvedValue({data:null,error:{code:'timeout'}});expect(await createSitovSpecialAuthorDraft(input())).toEqual({ok:false,error:'retryable_failure',retryable:true});client.rpc.mockResolvedValue({data:{ok:false,error:'not_found',retryable:true},error:null});expect(await createSitovSpecialAuthorDraft(input())).toEqual({ok:false,error:'retryable_failure',retryable:true})})
